### ISSUE TITLE
Visual artifacts on non-retina external display

### ISSUE THREAD

**Issue by kesne** [warpdotdev/warp#10]
**Describe the bug**
There appear to be visual artifacts in a handful of places when moving the terminal from the build-in retina display to an external non-retina display. This was 

**To Reproduce**
Open warp on a non-retina display, inspect edges closely.

**Expected behavior**
Crispness.

**Screenshots**
On the Retina display, things look _generally_ fine:
<img width="72" alt="Screen Shot 2021-07-16 at 1 23 58 PM" src="https://user-images.githubusercontent.com/498479/126004698-ef5d1ea6-bb2e-42ec-94ae-a96460369a69.png">
<img width="64" alt="Screen Shot 2021-07-16 at 1 27 15 PM" src="https://user-images.githubusercontent.com/498479/126004927-98abff83-1da5-4bf7-99cf-26d555c5555b.png">

On the external display, the edges look crunchy. 
![Screen Shot 2021-07-16 at 10 47 43 AM](https://user-images.githubusercontent.com/498479/126004841-8e75b541-27ed-4334-98f1-728f41307d85.png)
![Screen Shot 2021-07-16 at 1 27 10 PM](https://user-images.githubusercontent.com/498479/126004941-4bef9662-7aba-49aa-9e1b-a5ddc22019a5.png)

**Desktop (please complete the following information):**
MacOS 11.2
External display: 3440 x 1440 display

**Comment by alokedesai** [comment]
Thanks for filling! This is a known issue the team is looking into

**Comment by michlimlim** [comment]
We just released the fix for this today in `v0.2021.08.11.15.36.stable_00`
