### ISSUE TITLE
Mac M1: Cannot jump to warp application normally after github authorization

### ISSUE THREAD

**Issue by Linyuqiz** [warpdotdev/Warp#1001]
### Describe the bug

```text
The warp terminal installed on mac intel works normally, but after installation on mac m1, github is also authorized normally, and there is no response when clicking to jump to the warp application
```

### Operating System

MacOS

### OS Version

12.x.x

**Comment by cleanwk** [comment]
same problem 

> ### Describe the bug
> ```
> The warp terminal installed on mac intel works normally, but after installation on mac m1, github is also authorized normally, and there is no response when clicking to jump to the warp application
> ```
> 
> ### Operating System
> MacOS
> 
> ### OS Version
> 12.x.x

same ,is there any solution ?

**Comment by HappyFerry** [comment]
and i encountered the same

**Comment by yu-tou** [comment]
me too

**Comment by siriusctrl** [comment]
same here

**Comment by dev4joel** [comment]
The login issue is here:
👉 https://github.com/warpdotdev/Warp/milestone/5

How to fix the confusing login flow issue is here:
👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)

How to fix the proxy issue is here:
👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by yu-tou** [comment]
add https_proxy and boot from teminal solve my issues

**Comment by lxf-lxf** [comment]
> 添加https_proxy并从teminal启动解决我的问题

is nothing to me

**Comment by lxf-lxf** [comment]
> 添加https_proxy并从teminal启动解决我的问题

<img width="841" alt="image" src="https://user-images.githubusercontent.com/61101384/162962287-dc1de3e0-d75a-4db9-87e9-56aa0583eb1c.png">

try it ,i can run

**Comment by elviskahoro** [comment]
@yu-tou @HappyFerry @siriusctrl @Linyuqiz @cleanwk 
Recently had an update and made a guide in our documentation, please check out:
https://docs.warp.dev/help/troubleshooting-login-issues

Please comment if this hasn't fixed the issue!
