### ISSUE TITLE
Mac: Non-standard use of macOS menu system

### ISSUE THREAD

**Issue by chriskrycho** [warpdotdev/Warp#101]
**Describe the bug**
The Warp "File" menu currently contains a mix of actions ("New Window") and settings ("Left Option Key is Meta"); the actions do not all belong in that menu; and it is probably misnamed. 

**To Reproduce**
Open the app and observe the "File" menu and its contents.

**Expected behavior**
Per Apple's (decades-long) guidance in its [Human Interface Guidelines][hig], the [File menu][file-menu] should *only* have actions for creating/working with the current "document". Further, it's conventional *not* to have a "File" menu on terminal apps on macOS, but instead to have a menu named "Shell" (cf. Terminal.app, iTerm 2.app, etc.). Navigation through the window should normally happen via the "Window" menu, and preferences should live at the app level.

Accordingly:

- The configuration settings like those for Option Key should either go under the "Warp" top-level menu or, better, a preferences submenu (or window!)
- The "File" menu item should probably be renamed to "Shell"
- The navigation items within "File" should be moved to the standard "Window" menu

Additionally, menu bar items should generally use verbs, so for example "Use Left Option Key as Meta" rather than "Left Option Key is Meta".

[hig]: https://developer.apple.com/design/human-interface-guidelines/macos/
[file-menu]: https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/#file-menu

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS Version: macOS Version 11.5.1
- iMac (Retina 5K, 27-inch, 2019)

**Additional context**
N/A

**Comment by elviskahoro** [comment]
From: @hillegass
In #358
Every standard Mac app has the `Preferences...` menu item in the App menu (the menu with the Application's name as its label).  Attaching it to the window menu is non-standard and weird.

**Comment by elviskahoro** [comment]
From @fbartho via #692

### Describe the solution you'd like?

**Short Description:** Check-for-updates/Install-updates should appear in the System Menu bar for an application, and should be searchable from the Help menu.

On macOS, it's weird to have an action or operation that isn't available in the standard System Menu bar. Commands in the System Menu can be highlighted if users type fuzzy-match letters to find commands in any of the menus, so this makes the functionality more accessible.

`Update Available` seems to only appear embedded in the Terminal Window Chrome around the 3-dots menu in the top right.

Moving everything in the 3-dots menu under the `Help` menu (except for settings to the `Warp` menu #358 #101) would better match the platform conventions.

### Is your feature request related to a problem? Please describe.

I struggled to find where to check if my app was up-to-date. I checked all the menus in the App's System Menu, and I checked the App's Settings page. Before finally finding the non-standard 3-dots menu.

### Additional context

![Screenshot of the 3-dots menu, open, with no-pending updates](https://user-images.githubusercontent.com/209712/151425552-6575230f-0e29-4920-a33c-72b7f774ec00.png)

**Comment by panckreous** [comment]
Similarly, I wasnt able to find a quick way back to this repo via the application. What do you think about adding a plain ol direct "github" link to the discord/docs/changelog menu? 

I think it'd also be great to make those links available via the command palette, as well as any other actions available in the menus or elsewhere. 

I did a quick check to confirm: Raycast and Alfred both function like this, as well as VS Code, the Jetbrains IDEs + Linear and Height. 


<img width="797" alt="Screen Shot 2022-01-28 at 10 59 11 PM" src="https://user-images.githubusercontent.com/208280/151651457-d6eac3d5-8c5c-4510-acf6-2c4127a5ac5c.png">

<img width="593" alt="Screen Shot 2022-01-28 at 10 59 18 PM" src="https://user-images.githubusercontent.com/208280/151651456-5f219ac1-e12b-45a7-8abc-b5cd72fadae0.png">

**Comment by elviskahoro** [comment]
### Describe the solution you'd like?

I would like it if under the "Warp" heading in the macOS menu bar (next to the apple symbol), there was a "Settings..." or "Preferences..." option that opened the settings window just like the "Cmd+," shortcut.

### Is your feature request related to a problem? Please describe.

This is a pretty standard design, so I didn't even think there was a settings window for a while. I found it on accident. (The option in the top-right drop-down menu seems obvious in retrospect, but I'm a religious mac user and I always expect the settings option to be somewhere in the menu bar.)

**Comment by dannyneira** [comment]
Hi @chriskrycho, We've made some recent improvements to our mac menu items, please update to the latest build of Warp and let us know if the issue persists.

**Comment by alokedesai** [comment]
Closing this out. Please reopen if you're still experiencing issues here. Thanks!

**Comment by chriskrycho** [comment]
Hey folks, I do see some incremental progress here, but you've definitely still got some Mac-native gaps in the menu system—not least in that (as I noted in my original writeup) you shouldn't have a **File** menu at all! It should, following all the other terminals on macOS, be named **Shell** instead. (You’re not dealing with *files* there, after all!)

A couple other notes:

- Having **Settings** nested under **Preferences** as a sub-menu item is pretty weird.
- So is having two other menu items there which also just go to views in the same settings panel!

(The fact that said Settings panel is *also* super non-Mac-like is a different issue entirely.)

I do appreciate the improvements you made, but it’s *really* obvious that Warp is not going to provide a particularly Mac-like UI/UX. While, unfortunately, that means it's never going to be for me, that's a totally reasonable trade-off for you all to make. Good luck!
