### ISSUE TITLE
jumpserver not support

### ISSUE THREAD

**Issue by lone1y-51** [warpdotdev/Warp#1011]
### Describe the bug

```text
i want to connection company's jumpserver, but show me this
`Request type `session:exec` not support nowConnection to xxxxxx closed.`
```

### To Reproduce

Steps to reproduce:
1. input `ssh user@domain -p port`
2. See error 'Request type `session:exec` not support nowConnection to domain closed.'

### Expected behaviour

```text
can connection to jumpserver
```

### Operating System

MacOS

### OS Version

12.0.1

**Comment by johndb2016** [comment]
i came to the same problem, however other terminals works just fine, maybe there is something wrong with the socket options?

**Comment by messense** [comment]
Same kind of issue:

```
Received disconnect from x.y.z.a port 22:11: [USM] token GATE 'exec' not supported
```

**Comment by LeeMo2K10** [comment]
i came to the same problem(equest type `session:exec` not support nowConnection to xxxx closed)

**Comment by a252937166** [comment]
`debug1: Sending command:
                         hook=$(printf "{\\"hook\\": \\"SSH\\", \\"value\\": {\\"socket_path\\": \\"~/.ssh/165301488017893\\", \\"user\\": \\"%s\\", \\"machine\\": \\"%s\\", \\"remote_shell\\": \\"%s\\"}}" $(whoami) $(hostname) ${SHELL##*/} | command od -An -v -tx1 | command tr -d " \\n")
                                               printf '\033P$d%s\234' $hook
                                                                           if test "${SHELL##*/}" != "bash" -a "${SHELL##*/}" != "zsh"; then
                     exec $SHELL
                                fi

                                  case ${SHELL##*/} in
                                                        bash) exec -a bash bash --rcfile <(echo 'set -o vi; set +o vi; HISTCONTROL=ignorespace; printf '\\''\033P$d7b22686f6f6b223a2022496e69745368656c6c222c202276616c7565223a207b227368656c6c223a202262617368227d7d\234'\\''')
                                     ;;
                                         zsh) WARP_TMP_DIR=$(mktemp -d warptmp.XXXXXX)
                                                                                      if [[ $? == 0 ]]; then
                                                                                                            echo '756e7365746f7074205a4c453b20756e736574205243533b20756e73657420474c4f42414c5f5243533b207072696e746620275c7831625c7835305c7832345c7836343762323236383666366636623232336132303232343936653639373435333638363536633663323232633230323237363
debug2: channel 1: request exec confirm 1`

**Comment by uptutu** [comment]
i came to the same problem.

**Comment by elviskahoro** [comment]
Sorry about this. Will circle back when it's fixed!

**Comment by lone1y-51** [comment]
> Sorry about this. Will circle back when it's fixed!

this bug  like  #2077 ?

**Comment by lone1y-51** [comment]
turn off Warp's SSH wrapper (in Settings > Features) resolve this issues
