### ISSUE TITLE
Warp being marked as a security threat

### ISSUE THREAD

**Issue by JurjenBraam** [warpdotdev/Warp#1018]
### Describe the bug

```text
Warp is being specified as a threat by the security software that governs the vm's we use at our company with the following alert: A history file has been cleared.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Operating System

MacOS

**Comment by vorporeal** [comment]
Thanks for the report!  Our SSH wrapper removes a line from history (a line that we create, to be clear) as part of setting up a remote shell - we don't want to pollute your shell history with our initialization script.

We'll find an alternative that won't be regarded as suspicious.

**Comment by JurjenBraam** [comment]
Thanks for your reply! Sorry that I couldn't provide you with any further information but I just wanted to inform you that the currently implementation might give some issues with strict government policies. 

Hope that you manage to find an alternative because I think the app is great!

**Comment by sonuame** [comment]
It has impact me now. 
Created [2387](https://github.com/warpdotdev/Warp/issues/2387) with more details.

I love SSHing from this app and I don't want to get rid of this so early. Please get a fix for this
Thanks

**Comment by siw36** [comment]
I'm getting the same error when connecting to Azure VMs with enabled Azure Defender.

Alert description in Azure Defender (this is a default alert):
Analysis of host data indicates that the command history log file has been cleared. Attackers may do this to cover their traces. The operation was performed by the specified user account.

Suspicious Command Line:
This is the init script. I shortened it.
`bash -c $'\nexport TERM_PROGRAM=\'WarpTerminal\'\n\n_user="$(whoami 2>/dev/null || echo $USER)"[...]`

**Comment by vorporeal** [comment]
Hey all, I submitted a change that should fix this; it'll go live in next week's Warp release.  I'll follow up here when the fix is live so y'all can confirm the issue has been resolved. :)

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!

**Comment by sonuame** [comment]
So this is fixed ?
There is no way to know from our side, unless a security incident is triggered by infrastructure scanners

**Comment by vorporeal** [comment]
Yes, sorry for failing to follow up - this should be fixed in the latest versions of Warp.
