### ISSUE TITLE
Add Pure like prompt for Git

### ISSUE THREAD

**Issue by lzm0** [warpdotdev/Warp#1019]
### Describe the solution you'd like?

```text
Showing a `*` for dirty Git repos and `⇣⇡` arrows that indicates sync status.
```

### Additional context

I like the Git prompt of https://github.com/sindresorhus/pure and hope Warp can achieve similar functionality.
![image](https://user-images.githubusercontent.com/7163127/162808228-52be7bad-f8c1-4dae-93be-b4c288282197.png)

**Comment by mantou132** [comment]
need git prompt for me.

i use [zsh-git-prompt](https://github.com/olivierverdier/zsh-git-prompt)

**Comment by lzm0** [comment]
> 



> need git prompt for me.
> 
> i use [zsh-git-prompt](https://github.com/olivierverdier/zsh-git-prompt)

Sounds like what we really need is a plugin interface for different preferences.

**Comment by wesleylether** [comment]
👍🏽
