### ISSUE TITLE
Enable opening from Finder

### ISSUE THREAD

**Issue by ishaangandhi** [warpdotdev/Warp#102]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when you have to navigate to a working directory.

**Describe the solution you'd like**
In iTerm2 or with the built in Terminal, an option shows up in system preferences to open a terminal tab at a specific folder from within Finder. It would be nice if Warp would support that.

![image](https://user-images.githubusercontent.com/761037/128577836-6c39b4c1-296b-4676-bddc-cb818267b2c6.png)

**Comment by elviskahoro** [comment]
TermHere

From @alon357 via #347

### Describe the solution you'd like?

```shell
I'm a Mac user and I'm using TermHere a basic extension to the finder that opens a terminal in a specific location.
https://hashbang.productions/apps/termhere/
Do you Support this tool I was not able to open wrap with it?
Do you have something similar to it?
Thanks
```


### Is your feature request related to a problem? Please describe.

_No response_

### Additional context

_No response_

**Comment by jjmerri** [comment]
Is there a workaround for this? Pretty key feature.

**Comment by justinhporter** [comment]
Having a command-line argument to specify a directory would make this easy to script.

**Comment by warpdotdev-dx** [comment]
We're keeping track of controlling Warp via CLI here:
https://github.com/warpdotdev/Warp/discussions/612

--- original message ---
On April 22, 2022, 4:16 PM EDT ***@***.*** wrote:



Having a command-line argument to specify a directory would make this easy to script.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by its-all-waves** [comment]
Darn... The lack of this feature is an immediate deterrent for me, despite all the rest. Kinda discouraging as this has been an issue for over a year. I guess there are only 20 users who want this? 

I have a key shortcut rigged to the "Open folder in iTerm" option. I find the folder, hit the keys, iTerm launches with the path of the selected folder. This is how I launch my console every time. I have quite deep folder structures, so cd-ing my way there sucks.

**Comment by dannyneira** [comment]
Hi @its-all-waves , Sorry about this blocking you. Please +1 this request as it helps us gauge interest.  We will post updates on this thread if this is being worked on.

**Comment by dannyneira** [comment]
Comment from @Aivean on #2206
> Ability to open the file using a specific app, selected from the Finder-like "Open with" menu.

**Comment by redouredou** [comment]
Hello guys ! 

If I understand the issue, you want to open Warp terminal at specific folder.

I found an article that explain how to do this with Vscode: 
https://thehotcode.com/macos-open-with-vscode-finder/

You can use the same process for Warp, I did it and it works.

**Comment by Aivean** [comment]
> Is there a workaround for this? Pretty key feature.

There is. You can open a new tab in the terminal (or reuse an existing tab), type `cd` and drag the directory you want to open from the Finder into the terminal:

![warp-dir-cd](https://user-images.githubusercontent.com/2865203/203656324-84ea95e1-599a-4f28-a567-bbaa25bed678.gif)

Alternatively you can play with Automator to create `Services` or `Quick Actions` menu entry that does what you want (it can receive the selected files as an argument).

Here is how a similar action "Copy path to clipboard" looks like:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/2865203/203656570-4f852d47-a094-4cb4-b080-797112635066.png">

**Comment by dalhaan** [comment]
I was able to do it with Automator.

1. Open Automator
2. When prompted with "Choose a type for your document:", select "Quick Action"
3. Set "Workflow receives current" to "folders" and "in" to "Finder"
4. In the "Actions" sidebar, select "Utilities" then "Run Shell Script" and drag it into the "Drag actions or files here to build your workflow" space
5. In "Run Shell Script", set "Pass input:" to "as arguments"
6. Copy and paste `open -a Warp.app $1` into the text box
7. Save the Quick Action (File > Save) and give it a name like "Open folder with Warp"
8. Now right click any folder in Finder then select your new Quick Action from the "Quick Actions" context submenu
9. Profit

![Open folder in Warp DEMO](https://user-images.githubusercontent.com/21114237/203695316-97bd5ceb-1839-4205-9651-52353c31e4f3.gif)

**Comment by dannyneira** [comment]
Hey Folks! With the latest release of Warp, we've enabled opening a new tab or window from Finder. You can also drag a folder into the Warp input editor and quickly enter the path. See below:

![CleanShot 2023-02-17 at 10 02 04](https://user-images.githubusercontent.com/16809145/219717440-621590af-fd63-4258-8f69-668d2d133a36.gif)

**Comment by vorporeal** [comment]
Going to close this out, now that it's launched, but please don't hesitate to leave a comment here if you encounter any issues!

**Comment by ramirezlab** [comment]
Hello,

I followed @redouredou recommendations by using this post -> https://thehotcode.com/macos-open-with-vscode-finder/ 
1. With the Automator app I created a quick action (as the example for VSCode
2. In Preferences, go to keyboard shortcuts and select "Services" on the left menu
3. Activate the "New warp Window Here" and add your shortcut.
4. Test It in Finder. Just use the shortcut and voalá!!!

Let me know if works

Best,

**Comment by zhalice2011** [comment]
The above methods are all too complicated. Is there a way like Go2shell(https://zipzapmac.com/Go2Shell), where I only need one operation to open the terminal from a folder?

<img width="525" alt="image" src="https://user-images.githubusercontent.com/24289349/226100927-de73b676-062e-4719-a557-02b3267d5e68.png">

**Comment by zhalice2011** [comment]
> 

I used this open source program to solve my problem. [ https://github.com/Ji4n1ng/OpenInTerminal
](url)

<img width="828" alt="image" src="https://user-images.githubusercontent.com/24289349/226155473-dc4f91de-e69a-4299-805a-8e42fda58b22.png">

**Comment by vorporeal** [comment]
@zhalice2011 If your goal is to open a new tab/window in Warp with a specific folder as the initial working directory, this is now supported without any additional tools - make sure you're running an up-to-date version of Warp, then right-click on a folder in Finder and select "New Warp Tab here" or "New Warp Window here"!  (They might be under the "Services" submenu.)

**Comment by zhalice2011** [comment]
> 

Yes, This is a natively supported method, it's just not as convenient. I just want to click the button once, forgive me, LoL

**Comment by Bryant-Yang** [comment]
> > 
> 
> I used this open source program to solve my problem. [ https://github.com/Ji4n1ng/OpenInTerminal ](url)
> 
> <img alt="image" width="828" src="https://user-images.githubusercontent.com/24289349/226155473-dc4f91de-e69a-4299-805a-8e42fda58b22.png">

Do you have a fork version? The original source doesn‘t seem to support warp.

**Comment by Bryant-Yang** [comment]
> > > 
> > 
> > 
> > I used this open source program to solve my problem. [ https://github.com/Ji4n1ng/OpenInTerminal ](url)
> > <img alt="image" width="828" src="https://user-images.githubusercontent.com/24289349/226155473-dc4f91de-e69a-4299-805a-8e42fda58b22.png">
> 
> Do you have a forked version? The original source doesn‘t seem to support warp.

ok, found the custom option to easily support warp: 
<img width="461" alt="image" src="https://github.com/warpdotdev/Warp/assets/1195951/c1f92e84-d54a-4f21-81dc-c47001b660a7">

**Comment by jeannen** [comment]
Started using the app not long ago, but not being able to open a folder in terminal from a keyboard shortcut (like with mac terminal) is a no-go :/

Any plan to add it?

**Comment by Krishpkreame** [comment]
###New Automator app

![Screenshot 2024-02-20 at 2 02 05 AM](https://github.com/warpdotdev/Warp/assets/79666419/69db956a-5b63-4ba7-ade3-b3d3d745240c)

Export the app and while holding CMD drag it into your finder toolbar

**Comment by johan456789** [comment]
> ### New Automator app
> ![Screenshot 2024-02-20 at 2 02 05 AM]
> 
> Export the app and while holding CMD drag it into your finder toolbar

Here's the code you can copy directly:

```applescript
on run {input, parameters}
    tell application "Finder"
        set f to (get target of front window)
        return f as alias
    end tell
end run
```

```sh
open -a Warp.app "$1"
```

**Comment by budgetdevv** [comment]
I kinda found a way to do it, but thanks! I think it will be helpful for others. I feel that they should make this configurable in Warp
