### ISSUE TITLE
Hotkey Wrap terminal

### ISSUE THREAD

**Issue by abfshaal** [warpdotdev/Warp#1023]
### Describe the solution you'd like?

```text
Hello!

Right now when brining Wrap up with global hotkey window, it is getting hidden when switching to any other application, it would be great for it to persist through that.

I do not know whether this is a bug or it is intended by the developers.
This is an awesome terminal, many thanks for your work on it! 

Many thanks!
```

**Comment by kevinyang372** [comment]
Do you mind clarifying the bug a little bit? Is it hidden behind any application window or just fullscreen app windows?

**Comment by abfshaal** [comment]
Apologies I realize I had some typos in the first comment of the issue 
I am not sure whether it is a bug or this is how Warp was intended to be used. 
So, there is the option to bring up warp to the front with a hotkey. However what this is doing right now is opening a new warp instance, not really bringing up what is currently there. 
When using this Hotkey to bring warp (instance) to the front of the screen, clicking on any other window will bring it to the back, even when not in full screen mode. I can create a video recording if needed and post it to further describe this

**Comment by kevinyang372** [comment]
That's the intended behavior -- we consider hotkey window to be a new type of window with different layout behaviors and it will be confusing to users if we replace their existing window with the new behavior.

For the second issue -- you could untick the option in settings `Autohides on loss of keyboard focus` to disable that behavior.

Let me know if this helps!
