### ISSUE TITLE
Tab completion truncates long file paths 

### ISSUE THREAD

**Issue by zachlloyd** [warpdotdev/Warp#103]
<img width="702" alt="Image 2021-08-06 at 6 21 23 PM" src="https://user-images.githubusercontent.com/8727141/128583565-ffa5df19-e3a1-4db0-9a97-172f81d3c540.png">

Makes it unusable in this case

**Comment by mittalyashu** [comment]
Doesn't it have option to scroll horizontally?

**Comment by elviskahoro** [comment]
Added a description for file path next to the completion menu so you can see the full path.
