### ISSUE TITLE
Support for changing cursor type (blinking/non-blinking, solid or bar)

### ISSUE THREAD

**Issue by EmmEff** [warpdotdev/Warp#1031]
### Describe the solution you'd like?

```text
I simply cannot see the blinking bar cursor as well as a non-blinking block.
```

**Comment by jpbowen** [comment]
+1. Am missing a block cursor option and sometimes lose the current thin blinking bar.

**Comment by elviskahoro** [comment]
Good call out! Thanks for opening!

**Comment by socketbox** [comment]
@EmmEff I too struggled to see the blinking line in my chosen theme, but then discovered by chance that in Gruvbox (and perhaps others) the cursor is a block. 

@dannyneira It would also be nice to allow for changing the cursor shape to reflect vim mode. For example, it would be nice to be able to configure the shell such that the cursor changes to an insertion line in Input mode and back to a block in command and visual mode.

**Comment by heysweet** [comment]
I just wanted to let you know we've also [shipped Block and Underline cursor variants](https://github.com/warpdotdev/Warp/issues/3787), which should close this issue out!
