### ISSUE TITLE
SSH integration: wrong shell / fully broken

### ISSUE THREAD

**Issue by andig** [warpdotdev/Warp#1036]
### Describe the bug

```text
With ssh integration enabled I see the following prompt on the remote machine:

    sh-4.4$ 

There is no coloring. With my old terminal I get full coloring and a decent prompt:

    admin@NAS:~$

Seems the ssh integration is not working here?
```

### To Reproduce

SSH into Synology NAS

### Expected behaviour

```text
Fancy prompt similar to local.
```

### Screenshots

<img width="901" alt="Screenshot 2022-04-13 at 17 40 11" src="https://user-images.githubusercontent.com/184815/163218095-7842c0f6-010e-4c33-aa3f-19d8d9f5cd19.png">

vs

<img width="1053" alt="Screenshot 2022-04-13 at 17 40 31" src="https://user-images.githubusercontent.com/184815/163218153-b059d2c6-22e4-4d94-8eea-9b6617076eb5.png">

### Operating System

MacOS

**Comment by andig** [comment]
The impact is actually worse than I thought:

```
sh-4.4$ sudo docker logs evcc
Password:
sudo: docker: command not found
```

This happens with and without the warp ssh shell. At this time, ssh in warp is unusable for me.

**Comment by andig** [comment]
As of 2022.04.18 it is *only* broken when "warp ssh shell" is enabled. When disabled it's working now.

**Comment by sentience** [comment]
The typical way to set up Zsh on Synology is to use this `.profile` file:

```
if [[ -x /usr/local/bin/zsh ]]; then
  export SHELL=/usr/local/bin/zsh
  exec /usr/local/bin/zsh
fi
```

It appears Warp's SSH shell support doesn't execute this.

**Comment by elviskahoro** [comment]
Thanks for all the details will circle back when this is fixed!
