### ISSUE TITLE
clipboard copy doesn't work properly when find is open

### ISSUE THREAD

**Issue by garythung** [warpdotdev/Warp#1042]
### Discord username (optional)

chunk#9916

### Describe the bug

```text
Having find open causes clipboard (CMD+C) to not work properly. Copying text doesn't get saved to clipboard.
```

### To Reproduce

1. Open find with CMD+F
2. Try to copy CMD+C some text in the terminal
3. Paste it
4. It's not the text you CMD+C'd

### Expected behaviour

```text
Expect to be able to copy paste terminal text
```

### Screenshots

https://user-images.githubusercontent.com/7055455/163299818-ec2092b3-17a4-41a9-b9be-05eec190568c.mov

### Operating System

MacOS

### OS Version

Monterey 12.3

### Additional context

<img width="328" alt="image" src="https://user-images.githubusercontent.com/7055455/163300060-4e266e78-0cb5-4aec-a0ae-457e6af45227.png">

**Comment by dev4joel** [comment]
Did it fix this in the new release?

**Comment by dmilith** [comment]
I can confirm it's not yet fixed in the current release (2022-05-13)

**Comment by elviskahoro** [comment]
Should be fixed!
