### ISSUE TITLE
Trial without Sign In

### ISSUE THREAD

**Issue by burkee75** [warpdotdev/Warp#1045]
### Describe the solution you'd like?

```text
The product seems very interesting but requiring a sign-in for a terminal is just a no go for me. I understand its needed for the cloud based features but you should have an offline only mode that doesn't require creating an account.
```

**Comment by elviskahoro** [comment]
Gonna close this in favor of #900, so it's all in one place

Updated the docs with the how the team is currently thinking about all this!
Please check it out!
https://docs.warp.dev/getting-started/privacy

Will share any changes to login and telemetry here.
