### ISSUE TITLE
Can't use byobu in Warp

### ISSUE THREAD

**Issue by 4AKker** [warpdotdev/Warp#1046]
### Describe the solution you'd like?

```text
can't use f2-f4 in warp which is very important in byobu
```

### Is your feature request related to a problem? Please describe.

```text
when press f2-f4, there is a empty character in warp but no function in byobu
```

**Comment by elviskahoro** [comment]
Thanks for opening. I'll circle back after looking more into this!

**Comment by toneplex** [comment]
I'm also experiencing the same issue.

* Function keys aren't working
* after exiting byobu, the enter key doesn't work either, so you have to close the tab and open a new one

**Comment by orphetov** [comment]
I am having the same issue. Cannot use Warp with Byobu enabled on remote host.

**Comment by obelixA** [comment]
+1
byobu running on remote host leads in warp seeing the whole session as one block.

**Comment by alexzinnde** [comment]
+1 
unable to switch terminals using FN keys
