### ISSUE TITLE
Starship prompt not displayed at all

### ISSUE THREAD

**Issue by steveocr** [warpdotdev/Warp#1047]
### Describe the bug

```text
I've tried enabling the custom PS1 setting but when I do, I end up with no prompt.
There are two issues here:
1. Obviously if PS1 isn't set correctly, displaying no prompt at all is a poor user experience
2. Starship isn't working in Warp even though it works fine in ZSH/iterm2

I have `eval "$(starship init zsh)"` in my .zshrc. Warp seems to pick up other things from there but doesn't seem to execute that line or something.

If I run `eval "$(starship init zsh)"` manually in Warp, the prompt shows up as expected. But if I close and reopen or open a new tab, it's gone again.

I installed starship via `brew install starship`.
```

### To Reproduce

Steps to reproduce:
1. Install starship `brew install starship`
2. Enable starship in ZSH by adding `eval "$(starship init zsh)"` to ~/.zshrc
3. Open Warp and enable the custom prompt feature

### Expected behaviour

```text
I'm expecting to see the starship prompt, just like in ZSH/iterm2
```

### Operating System

MacOS

### OS Version

12.3.1

**Comment by steveocr** [comment]
I figured out what was wrong.

I had this line in my ~/.zshrc just before the starship line:
```zsh
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
```

Commenting this line allows starship to work in Warp.

However, I'm leaving this ticket open because I believe Warp should be fixed to handle this kind of thing.

**Comment by gagata** [comment]
hey! yes - the `iterm2_shell_integration.zsh` script in your rc files is a known issue. if you wish to keep it for your other terminals you can just wrap it in an `if`:
```if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi```
