### ISSUE TITLE
Configure default directory for new tab, new windows, new session, new pane

### ISSUE THREAD

**Issue by mittalyashu** [warpdotdev/Warp#105]
**Is your feature request related to a problem? Please describe.**

When opening a new tab using `command + T` it opens the terminal in same as previous tab directory path.

Instead it should open in the default directory, defined by user in preferences, same goes when opening a new Warp window.

**Comment by zachlloyd** [comment]
Good call.  We are planning on implementing this behind a user setting.

**Comment by elviskahoro** [comment]
Linking
- #322

**Comment by nipunn1313** [comment]
My preferred/expected behavior is different from the above posters
(new window -> current dir) and (new tab -> current dir).

Configurable sounds great as it sounds like different folks have different expectations / preferences for this.

If you want to consolidate - you probably merge #322 into this and rename this to handle both tabs and new windows

**Comment by elviskahoro** [comment]
From @nipunn1313 via #322

### Describe the solution you'd like?

```shell
When opening a new window or tab while focus is on an existing window, I would love for the default current working directory (cwd) to match the one on the preexisting window.

Alacritty has this behavior and I find it useful
Terminal/ITerm appear to have it in settings, but it's not default
```


### Is your feature request related to a problem? Please describe.

```shell
When I'm working on a project in a particular directory, 80% of the time when I open a new tab, I want to be in the same directory (eg open a build in another window).

The other 20% of the time, I'm happy to do a `cd` at the beginning (probably was planning to anyway).
```


### Additional context

_No response_

**Comment by elviskahoro** [comment]
From @DreierF via #656 

### Describe the solution you'd like?

```shell
I'd like to have a setting to override the default working dir, which is ~ ATM.
```


### Is your feature request related to a problem? Please describe.

```shell
I mainly work on one project and it is annoying to have to cd into this directory at the start of every session. I don't want to add this to `.zshrc` as I also use the finder integration of `iTerm` for example to open the terminal in the current folder, which does no longer work when adding `cd project` in `.zshrc`
```


### Additional context

iTerm settings:
![image](https://user-images.githubusercontent.com/5631865/150633978-34d23d07-e8a5-45e0-be5f-228fbcdb6736.png)

**Comment by syabro** [comment]
I've added `cd ~` to the end of my `.zsrhc` as a temporary solution.

**Comment by davidlukerice** [comment]
This is something I'm needing as well. Currently, I use ITerm2 and it has the ability to save different layouts (ie. tabs and splits and what directories each are on). And then you can save which layout will be used by default when opening a new window.

**Comment by elviskahoro** [comment]
From alejoar via Discord
Being able to configure the path opened by new split panes

**Comment by elviskahoro** [comment]
@alejoar I'm not sure. Going to bring it back up to the team though.

**Comment by jacobgraf** [comment]
Just showing my support here. It's really one of the main things I am missing from iTerm 2. I want a new session to start in ~/Sites but when I open a new tab, I want it to start in whatever PWD I am in. In the meantime, I've added this to my .zshrc...

```
# Starting Directory
cd $HOME/Sites/
```

But then when I open new tabs, they all start in ~/Sites.

If I remove this line from .zshrc, new windows start in ~, but new tabs open in PWD. I want my cake and eat it too! 😁

**Comment by elviskahoro** [comment]
It's still not possible to to configure what the default directory is via the settings. But it is possible to save an arrangement via Launch Configurations `CTRL-CMD-L`.

See docs: https://docs.warp.dev/features/session-management/launch-configurations

**Comment by jacobgraf** [comment]
> It's still not possible to to configure what the default directory is via the settings. But it is possible to save an arrangement via Launch Configurations `CTRL-CMD-L`.
> 
> See docs: https://docs.warp.dev/features/session-management/launch-configurations

Hmm.

Seems to be inconsistencies between the docs and the app itself. In the docs, the launch configs are at ~/.warp/launch_configurations/ but when you do the CMD-CTRL-L shortcut, it says they are at ~/.warp/session_templates/.

**Screenshot:** https://cln.sh/OwFLLdCt9aPbjxTQFwgn

Also, how do you set the default launch config??

**Comment by warpdotdev-dx** [comment]
It isn't possible to set a default launch configuration. Maybe we can add that to this feature request.

--- original message ---
On August 22, 2022, 10:36 AM EDT ***@***.*** wrote:



> It's still not possible to to configure what the default directory is via the settings. But it is possible to save an arrangement via Launch Configurations CTRL-CMD-L.

> See docs: https://docs.warp.dev/features/session-management/launch-configurations


Hmm.

Seems to be inconsistencies between the docs and the app itself. In the docs, the launch configs are at ~/.warp/launch_configurations/ but when you do the CMD-CTRL-L shortcut, it says they are at ~/.warp/session_templates/.

Screenshot: https://cln.sh/OwFLLdCt9aPbjxTQFwgn

Also, how do you set the default launch config??

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by jacobgraf** [comment]
> It isn't possible to set a default launch configuration. Maybe we can add that to this feature request.
> --- original message ---
> On August 22, 2022, 10:36 AM EDT ***@***.*** wrote: It's still not possible to to configure what the default directory is via the settings. But it is possible to save an arrangement via Launch Configurations CTRL-CMD-L. See docs: https://docs.warp.dev/features/session-management/launch-configurations
> Hmm. Seems to be inconsistencies between the docs and the app itself. In the docs, the launch configs are at ~/.warp/launch_configurations/ but when you do the CMD-CTRL-L shortcut, it says they are at ~/.warp/session_templates/. Screenshot: https://cln.sh/OwFLLdCt9aPbjxTQFwgn Also, how do you set the default launch config?? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
> […](#)
> -- You received this message because you are subscribed to the Google Groups "github" group. To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.*** --- end of original message ---

Ergh. Being able to have Warp start in a specific directory is literally the one thing I've been missing since I switched from iTerm 2. I've been patiently waiting for this since I chatted with your team back last November.

We're so close! I'll keep an eye on future updates and hopefully there is a solution!

Thanks!

**Comment by dannyneira** [comment]
@jacobgraf 

We've recently released [Launch Configurations](https://docs.warp.dev/features/session-management/launch-configurations) and that may help with the initial launch of the terminal to specific directories. Will post any more updates on user defined default directories here.

**Comment by jacobgraf** [comment]
> @jacobgraf
> 
> We've recently released [Launch Configurations](https://docs.warp.dev/features/session-management/launch-configurations) and that may help with the initial launch of the terminal to specific directories. Will post any more updates on user defined default directories here.

Yeah, but like I said, there still isn't a way to specify a default launch configuration, correct? That's the issue here. I can create a config, but if I have to manually open a specific config every time I launch, I might as well manually change directories too. Hoping I'm missing something?

**Comment by dqhieu** [comment]
I have read the [Launch Configurations](https://docs.warp.dev/features/session-management/launch-configurations) and still have no idea how to config this behavior: open default directory for new tab. Can someone help with the config?

**Comment by dqhieu** [comment]
> I've added `cd ~` to the end of my `.zsrhc` as a temporary solution.

Thanks. I'm doing this too

**Comment by mhsemcheski** [comment]
When I open a new tab or a new window, I expect a new terminal.  I do not want my first command on opening a new tab to be `cd`.  Just put me in my home directory when I open a new tab.  

This is a breaking change from every other terminal emulator I've ever used.  New tabs should be new, they shouldn't carry context (ie working directory) from another tab.

This is the number one annoyance I have with Warp.

**Comment by dannyneira** [comment]
@mhsemcheski 

There is a workaround to use `cd ~` in your .bashrc or .zshrc file to set the default directory on each new Window/Tab/Pane, but yes, potentially this could be a setting as well in the future.

**Comment by vorporeal** [comment]
Hey all!  I've sent out a PR internally to add this functionality; it probably won't make next week's release but I'm optimistic that'll it'll go live in the 2/16 release. :)
