### ISSUE TITLE
opening ssh displays "sed and tr not found" + SSH Wrapper not working on hosts that are missing tr and sed

### ISSUE THREAD

**Issue by t3az0r** [warpdotdev/Warp#1050]
### Shell and Version

5.0.2

### Operating System and Version

CentOS Linux release 7.9.2009 (Core)

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

```shell
warp_escape_json:17: command not found: sed
warp_escape_json:17: command not found: tr
warp_escape_json:17: command not found: sed
warp_escape_json:17: command not found: tr
warp_escape_json:17: command not found: sed
warp_escape_json:17: command not found: tr
```

**Comment by sdzywei** [comment]
设置把里的Warp SSH Wrapper选项关掉，效果不错

**Comment by elviskahoro** [comment]
Thanks for opening. Will get back to you after changes to fix this are made. Someone has been looking into it

**Comment by elviskahoro** [comment]
This is fixed now!
