### ISSUE TITLE
Support fish for SSH - Warp raised an error when using SSH under fish shell

### ISSUE THREAD

**Issue by Toma62299781** [warpdotdev/Warp#1054]
### Shell and Version

fish shell 3.3.1

### Operating System and Version

macOS Monterey 12.3.1

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [x] Yes

### Screenshots

Warp raised an error when I tried to use SSH, the screenshot is shown below. Thanks for your great software.

<img width="506" alt="image" src="https://user-images.githubusercontent.com/6964699/163429600-5e64d62b-d3ae-4b03-a0bc-ed0f3049d8d7.png">
The command I used in the screenshot is like `ssh username@ip -oPort=xxxx`. By the way, the same command works fine under zsh.

**Comment by victortrac** [comment]
Man.. I spent hours trying to figure out WTF was wrong with my fish.config on my SSH host.  I couldn't find any trace of this code in any of my functions, plugins, etc.  Turns out it's an issue with warp. 🤦

**Comment by SichangHe** [comment]
Same problem
```shell
ssh username@ip
username@ip's password:
fish: Unsupported use of '='. In fish, please use 'set hook $(printf "{\"hook\": \"SSH\", \"value\": {\"socket_path\": \"~/.ssh/15932\", \"user\": \"%s\", \"machine\": \"%s\", \"remote_shell\": \"%s\"}}" $(whoami) $(hostname) ${SHELL##*/} | command xxd -p | command tr -d "\n")'.
Connection to ip closed.
```

**Comment by elviskahoro** [comment]
Gonna merge this into #871

**Comment by michaelaye** [comment]
this is still an issue today:

```
ssh **remote_machine**
fish: Unsupported use of '='. In fish, please use 'set hook $(printf "{\"hook\": \"SSH\", \"value\": {\"socket_path\": \"~/.ssh/18090\", \"remote_shell\": \"%s\"}}" "${SHELL##*/}" | command od -An -v -tx1 | command tr -d " \n")'.
hook=$(printf "{\"hook\": \"SSH\", \"value\": {\"socket_path\": \"~/.ssh/18090\", \"remote_shell\": \"%s\"}}" "${SHELL##*/}" | command od -An -v -tx1 | command tr -d " \n")
```
