### ISSUE TITLE
UIUX: Copy app version

### ISSUE THREAD

**Issue by mittalyashu** [warpdotdev/warp#106]
**Is your feature request related to a problem? Please describe.**

I was trying to copy the app version to create a bug report and I was too lazy to type that long version.

Or there can be something like "About Warp" from where we can easily get Warp info.

<img width="280" alt="CleanShot 2021-08-07 at 15 11 29@2x" src="https://user-images.githubusercontent.com/29014463/128596030-bb20878a-62d1-407b-820f-c9bbe58f2c66.png">

**Additional context**

![CleanShot 2021-08-07 at 15 09 23](https://user-images.githubusercontent.com/29014463/128596001-1947d1f2-693c-40f6-a369-dc48d472f34a.gif)

**Comment by zachlloyd** [comment]
Good call.  The UI in this menu isn't great.  I like the idea of copying the version if you select the item!

**Comment by elviskahoro** [comment]
This should be coming out in the next update.

**Comment by elviskahoro** [comment]
Closed: v0.2021.11.09.19.46.stable_00
