### ISSUE TITLE
Code Snippets

### ISSUE THREAD

**Issue by jvanderen1** [warpdotdev/Warp#1062]
### Describe the solution you'd like?

```text
I would like there to be a feature to save code snippets by at least name.
```

### Is your feature request related to a problem? Please describe.

```text
I have a lot of scripts I need to run at work to accomplish my workflow, so saving these snippets would be helpful.
```

### Additional context

This feature would be similar to one offered by iTerm2: https://iterm2.com/documentation-preferences-shortcuts.html

**Comment by joeyparis** [comment]
Could you accomplish this with [workflows](https://docs.warp.dev/features/workflows)? Either way though I do like the idea of also having snippets similar to iTerm2

**Comment by jvanderen1** [comment]
I'll give it a try! Looks pretty useful :)
