### ISSUE TITLE
Chinese directory error.

### ISSUE THREAD

**Issue by Mjhuu** [warpdotdev/Warp#1067]
### Describe the bug

```text
Chinese directory error.

cd 中文目录报错
```

### Screenshots

<img width="989" alt="截屏2022-04-15 14 41 02" src="https://user-images.githubusercontent.com/45823607/163532100-0d70c816-af8d-4bdf-85e6-4dbdc07b8ef7.png">

### OS Version
macos 12
_No response_

**Comment by ooopscc** [comment]
same here

**Comment by elviskahoro** [comment]
Can you comment here instead:
https://github.com/warpdotdev/Warp/issues/648
