### ISSUE TITLE
Unable to minimise using CMD-M

### ISSUE THREAD

**Issue by mittalyashu** [warpdotdev/warp#107]
**Describe the bug**

I am not able to minimise the warp using `command + M` shortcut key.

**Desktop (please complete the following information):**
 - OS Version: MacOS v11.5
 - Warp version: v0.2021.07.27.17.17

**Comment by zachlloyd** [comment]
Thanks for the report.  Should be a simple fix - we will prioritize in the next few weeks.

**Comment by elviskahoro** [comment]
Closed with v0.2022.01.03.09.07.stable_01
