### ISSUE TITLE
Stuck when login the Warp

### ISSUE THREAD

**Issue by flyflypeng** [warpdotdev/Warp#1070]
### Describe the bug

```text
Warp cannot log in after authentication by github.
```

### To Reproduce

1. I download the newest version of Warp from the https://www.warp.dev/ 

2. After installation， I click the `login` button, and jump to do auth by Github in the Chrome Browser.

3.  Authentication  is passed

![image](https://user-images.githubusercontent.com/8475378/163548931-a7977596-fce6-4e5a-84af-5be031555e84.png)

5. Jump back to the Warp GUI, however, Warp is not responsible
![image](https://user-images.githubusercontent.com/8475378/163548999-7dccad64-01c1-46d2-9838-73109d4d9a66.png)

### Expected behaviour

```text
Login successfully!
```

### Operating System

MacOS

### OS Version

12.3

**Comment by Bigshowzyb** [comment]
me too

**Comment by LIYANG-UST** [comment]
same problem

**Comment by kbfx1234** [comment]
same problem

**Comment by dev4joel** [comment]
How to Troubleshooting Login Issues is here :
- 👉 [Troubleshooting Login Issues](https://docs.warp.dev/help/troubleshooting-login-issues)

How to fix the confusing login flow issue is here:
- 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)

How to fix the proxy issue is here:
- 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by hhstore** [comment]
> How to Troubleshooting Login Issues is here :
> 
> * 👉 [Troubleshooting Login Issues](https://docs.warp.dev/help/troubleshooting-login-issues)
> 
> How to fix the confusing login flow issue is here:
> 
> * 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)
> 
> How to fix the proxy issue is here:
> 
> * 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

not works!

**Comment by flyflypeng** [comment]
> > How to Troubleshooting Login Issues is here :
> > 
> > * 👉 [Troubleshooting Login Issues](https://docs.warp.dev/help/troubleshooting-login-issues)
> > 
> > How to fix the confusing login flow issue is here:
> > 
> > * 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)
> > 
> > How to fix the proxy issue is here:
> > 
> > * 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)
> 
> * I use `ClashX Pro` as a Proxy, so.
> * Open this app by setting up a proxy, fix this problem.
> 
> > fix:
> 
> ```ruby
> cd /Applications/Warp.app/Contents/MacOS
> 
> # open with local proxy:
> export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890; ./stable
> ```

Cool! Your solution fixed my problem, so it is a network problem for logging in to the warp.
