### ISSUE TITLE
Supports setting the max number of scrollback rows

### ISSUE THREAD

**Issue by patrick-fu** [warpdotdev/Warp#1071]
### Describe the solution you'd like?

```text
Supports setting the max number of scrollback rows,

just like the macOS default Terminal

(Preferences -> Profiles -> Window -> Scrollback)
```

**Comment by sanggonlee** [comment]
This is pretty crucial to me, would love this as well.

**Comment by PanMartinez** [comment]
Are there any news in this topic? I love this terminal, but without infinite scrollback on blocks I have to stick to default one :(

**Comment by elviskahoro** [comment]
Thanks for reporting gonna close in favor of #610
