### ISSUE TITLE
Automatic SSH reconnect

### ISSUE THREAD

**Issue by neongreen** [warpdotdev/Warp#1078]
### Describe the solution you'd like?

Currently if I'm in an SSH session and I close my laptop, after re-opening it I might get "broken pipe" or just a stuck session.

I'd love if Warp's custom SSH support had auto-reconnect. I know that Mosh exists, but having this built-in without having to install Mosh on the server would be much nicer.

**Comment by micahjon** [comment]
Reconnecting automatically aside, does anybody know how to keep using a Warp tab (to manually reconnect) after an SSH session disconnects and the `client_loop: send disconnect: Broken pipe` error occurs? I've tried pressing `ctrl c` on my Mac to no avail and have to create a new tab to keep working. 

Not a dealbreaker, but definitely an ergonomic issue for those of us coming from iTerm. Thanks!

**Comment by elviskahoro** [comment]
Thanks for the idea.
We're tracking stuff like this here, gonna migrate what you have over:
https://github.com/warpdotdev/Warp/discussions/442
