### ISSUE TITLE
Warp terminal is hanging

### ISSUE THREAD

**Issue by brandontan** [warpdotdev/Warp#1086]
### Describe the bug

```text
Please see screenshot
```

### To Reproduce

Steps to reproduce:
1. Open Terminal
2. You will see "start zsh" - the default terminal does not have this 
3. You will see "Seems like your shell is taking a while to start"

### Expected behaviour

```text
The shell should just go straight to prompt
```

### Screenshots

<img width="336" alt="CleanShot 2022-04-17 at 10 37 41@2x" src="https://user-images.githubusercontent.com/1005474/163697939-13c799db-9b1e-4890-a3ab-14b5892e1926.png">

### Operating System

MacOS

### OS Version

12.3.1

**Comment by brandontan** [comment]
<img width="566" alt="CleanShot 2022-04-17 at 10 39 04@2x" src="https://user-images.githubusercontent.com/1005474/163698200-9c3bfc2c-0d02-44f8-b723-8efa52777949.png">

**Comment by jvrdom** [comment]
Having the same issue 😞

**Comment by eshinkawa** [comment]
Are you using M1's? I just disabled the `Opening using Rosetta` option and it's started working again

**Comment by jvrdom** [comment]
In my case I'm not using M1. OS Version 11.5

**Comment by elviskahoro** [comment]
Sorry for the delay!
It's likely that there are things in your dotfiles that we're not compatible with, probably prompt and maybe some other stuff, checkout these docs:
https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files
