### ISSUE TITLE
Font rendering artifacts

### ISSUE THREAD

**Issue by zachlloyd** [warpdotdev/warp#11]
There are various font rendering artifacts that make the text look suboptimal.

E.g. the tops of letters are sometimes cropped:

![image](https://user-images.githubusercontent.com/8727141/126004718-1046230c-945f-4b69-ae90-33e9adabeebd.png)

Sometimes characters are misaligned from the baseline at different zoom levels.

![New Issue · warpdotdevwarp 2021-07-16 at 4 27 56 PM](https://user-images.githubusercontent.com/8727141/126004983-c34c1913-4f9b-4a2e-a96b-51d6abb50334.jpg)

**Comment by michlimlim** [comment]
We just released the fix for this today in `v0.2021.08.11.15.36.stable_00`
