### ISSUE TITLE
If Chinese appears in the path,cannot use tab to complete it

### ISSUE THREAD

**Issue by bkingalex** [warpdotdev/Warp#1104]
### Describe the bug

```text
I created a folder named "测试123" in Chinese, then input "cd 测", and then press tab to complete, but the completion is invalid. English folder or file name. Enter a part of the name and press tab to complete the name
```

### To Reproduce

Steps to reproduce:
1.Run “mkdir  测试123”
2.input "cd 测"
3.Press tab

Cannot complete a folder with Chinese by using tab

### Expected behaviour

```text
Enter a part of the Chinese folder or file name, and press tab to complete the whole folder or file name
```

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
Can you comment here instead:
https://github.com/warpdotdev/Warp/issues/648
