### ISSUE TITLE
SSH Wrapper not working on hosts that are missing tr and sed

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#1107]
### Describe the bug

```text
warp_escape_json:17: command not found: tr
warp_escape_json:17: command not found: sed
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

**Comment by ahoiroman** [comment]
Possible duplicate of https://github.com/warpdotdev/Warp/issues/1050

**Comment by sdzywei** [comment]
把设置里的Warp SSH Wrapper选项关掉，好多功能不在生效

**Comment by elviskahoro** [comment]
Thanks @ahoiroman gonna close this in favor of that.
