### ISSUE TITLE
Previous command not working

### ISSUE THREAD

**Issue by remykarem** [warpdotdev/Warp#1108]
### Describe the bug

```text
When I click the up arrow button, I don't see the previous command.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```text
I should be able to see the previous command that I typed.
```

### Operating System

MacOS

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
Should be fixed!
