### ISSUE TITLE
Multiple Window Support

### ISSUE THREAD

**Issue by tyun08** [warpdotdev/Warp#1113]
### Describe the solution you'd like?

```text
In MacOS, it only allows open one Wrap at all windows. So in case we have multiple windows open we can't easily move the app around. It's better to be able to create multiple Wrap app, just like VScode.
```

**Comment by henrik2706** [comment]
I have this problem as well, and I urge the devs to fix it.

This problem leads to me having to force Warp to one screen, which in turn makes it impossible to open the hotkey window from any other screen.

**Comment by elviskahoro** [comment]
Sorry for the delay here. But having trouble understanding the issue. It might have been fixed honestly between now and April. Can you let me know if this is still happening?

I can get warp to display on multiple, so gonna close for now
