### ISSUE TITLE
control over mouse reporting

### ISSUE THREAD

**Issue by jcourteau** [warpdotdev/Warp#1114]
### Describe the solution you'd like?

```text
The equivalent of the iterm "mouse reporting" options; controlling whether the mouse clicks and scroll wheel events are passed through to terminal apps, or ignored. This would be a toggle-able option, ideally with 2 separate options for clicks vs mouse wheel events, just like iterm.

This would allow people to ignore mouse clicks, and use the OS-level drag-to-select / right click menu / etc; which I find a heck of a lot more useful for cross-application interaction (highlight a thing in an SSH session, CMD-C, over to IDE, CMD-V, etc)
```

### Is your feature request related to a problem? Please describe.

```text
With the current setup, mouse clicks are passed through to things like vim, so when you try to highlight / copy / paste text with the mouse, instead you get vim's visual mode / select / etc.

This is useful to a lot of folks! But I (and probably a few others) prefer it the other way.
```

**Comment by gagata** [comment]
hey! I think you can disable it in vim specifically by running `set mouse-=a`

mind pointing where this config option is in iterm?

**Comment by jcourteau** [comment]
🤦 I didn't even think to check vim-specific settings; I'm not surprised they have this specific combo featured. It works exactly how I'm used to, too.

In iterm2, the settings I mentioned are at:

1. `session` menu ->
2. `edit session ...` menu item ->
3. `terminal` tab ->
4. `terminal emulation` section ->
5. `enable mouse reporting` and its 2 sub-options

It can also be accessed via the `iterm2` menu, `preferences`, `profiles`, <select a profile>, and then from 3. above.

**Comment by tarwich** [comment]
I was looking at opening an issue, but this one seems to describe what I'm after.

When using TMUX, I use `:set mouse` which allows me to click tabs, drag split panes around, etc. When I need to select text to copy it, it activates TMUX's selection, which I don't want. In the macOS Terminal app, I can hold **option** to disable mouse reporting while I select text locally. 

- I'm using TMUX in SSH, so the TMUX + macOS clipboard integration doesn't solve my problem
- I'm using TMUX to maintain terminal persistence over SSH, so the Warp split-pane doesn't solve my problem (still need TMUX)

**Comment by elviskahoro** [comment]
@tarwich we added some toggles to the Settings dialog: Settings > Feature
Can you check it out and let us know your feedback?

**Comment by warpdotdev-dx** [comment]
Yeah no problem!

**Comment by elviskahoro** [comment]
S/O to @MaggieShan
