### ISSUE TITLE
Support offline mode, without login

### ISSUE THREAD

**Issue by indooorsman** [warpdotdev/Warp#1119]
### Describe the solution you'd like?

```text
as a terminal app I think offline mode is a baisc feature, 
and you know in some country network connection with github may be not so stable. 
I'm stuck by login when I try Warp first time.
```

**Comment by dev4joel** [comment]
How to Troubleshooting Login Issues is here :
- 👉 [Troubleshooting Login Issues](https://docs.warp.dev/help/troubleshooting-login-issues)

How to fix the confusing login flow issue is here:
- 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)

How to fix the proxy issue is here:
- 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by indooorsman** [comment]
> How to Troubleshooting Login Issues is here :
> 
> * 👉 [Troubleshooting Login Issues](https://docs.warp.dev/help/troubleshooting-login-issues)
> 
> How to fix the confusing login flow issue is here:
> 
> * 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)
> 
> How to fix the proxy issue is here:
> 
> * 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

@dev4joel I know how to deal with network issue, however, I still strongly want to use Warp in offline mode

**Comment by Fanduzi** [comment]
I agree with @indooorsman . Why does a terminal have to be logged in for the user to use it?

**Comment by dev4joel** [comment]
I agree with you too. 

Meanwhile, the official explanation is here:
Login serves two functions now. 
One is that we think there are features that require login in order to create a better user experience (ie our OpenAI feature). The other is to improve our product during beta. But we only track metadata, never console input or output.

For an exhaustive list of events that we track, see here:
https://docs.warp.dev/getting-started/privacy#exhaustive-telemetry-table

**Comment by harrisjnu** [comment]
There is an absence of account logout/remapping option as well under settings. The mapped gitHub account remains hardcoded even after a complete reinstallation, making it difficult to try out Warp if it gets mapped to your company/employers account (which in my case was silently open in ones of the browser tabs and got mapped to Warp).
Can a fix/feature be added to allow logout/remapping of another GitHub account? Or how can the hardcoded account info be deleted to allow clean reinstallation of Warp.

**Comment by Kaol-Fu** [comment]
Agree with @indooorsman. I'm the one of users who was stuck in the sign in screen. :-(

**Comment by jcarlos** [comment]
Yeah, i've installed to have a look but uninstalled as soon as I saw that login screen. If some features require login then only ask for login when I want to use those features. Feels silly, do I really need to login just to execute an `ls` on my home directory?

**Comment by kevinvangelder** [comment]
This trend of requiring a login to use a terminal or terminal plugin is absurd. You can collect usage information without an account, it's a clear ploy at getting the user's email address. Anyone who does this should be ashamed of themselves.

**Comment by agigao** [comment]
> I agree with you too.
> 
> Meanwhile, the official explanation is here:
> 
> ```
> Login serves two functions now. 
> One is that we think there are features that require login in order to create a better user experience (ie our OpenAI feature). 
> The other is to improve our product during beta. But we only track metadata, never console input or output.
> 
> For an exhaustive list of events that we track, see here:
> https://docs.warp.dev/getting-started/privacy#exhaustive-telemetry-table
> ```

This, is not in any way, explains or justifies requirements to log-in. My colleague shared your blog-post, I got interested, downloaded the app and saw a log-in screen.

Well, short a sweet experience - good bye.

**Comment by Bobronium** [comment]
"opt-in" you say? 🤡 
<img width="358" alt="image" src="https://user-images.githubusercontent.com/36469655/166634039-bddc56d7-242b-4f82-b0de-fc6c154cdb1d.png">

**Comment by silent-tan** [comment]
but how to logout?

**Comment by elviskahoro** [comment]
You can log out by removing Warp from your mac keychain.

Gonna close this in favor of #900 so discussion is in one place.

Updated the docs with the how the team is currently thinking about all this!
Please check it out!
https://docs.warp.dev/getting-started/privacy

Will share any changes to login and telemetry there.

**Comment by hackingguy** [comment]
what is the logic if making it open source if you are enforcing to share data!

**Comment by SHND** [comment]
The features of this terminal app are amazing, but I find the fact that terminal app forces you to login pretty suspicious. As much as I like to try this, I'll never use this app even if the creators provide an offline version. Even if they have a good Privacy notes today (which I'm not gonna bother going through), who knows if they change it and sometime in future show a modal with "I AGREE" button to relinquish all your rights over your information. I simply refuse to risk.

**Comment by vugarli** [comment]
Could have popped up login whenever needed. Probably not developers' choice, rather something to do with management. Uninstalled anyways.
