### ISSUE TITLE
In vim the character '{' cannot be typed

### ISSUE THREAD

**Issue by stianrincon** [warpdotdev/warp#112]
I cannot type the character '{'

**Comment by zheng** [comment]
We're having trouble reproducing this. Is it possible there's something special about your vim or keyboard configuration? Does this reproduce only in certain circumstances?

**Comment by stianrincon** [comment]
Hi, sorry for the late response, my keyboard is a Spanish keyboard specifically this one: https://www.apple.com/es/shop/product/MQ052Y/A/magic-keyboard-con-teclado-numérico-español

**Comment by kevinyang372** [comment]
I think this should be fixed by the latest update. Please re-open this issue if it is not the case!
