### ISSUE TITLE
Zsh: Autocomplete broken

### ISSUE THREAD

**Issue by andig** [warpdotdev/Warp#1121]
### Describe the bug

On `iTerm` I can do this:

    gb -D fix/amtron fix/cfos fix/docs fix/docs-3 fix/go-118-certs fix/hybrid

by typing `fix` and the tabbing through the branch names.

On Warp there is no autocomplete after the first branch.

### To Reproduce

See above.

### Expected behaviour

```text
Autocomplete for >1 parameter
```

### Operating System

MacOS

**Comment by TehShrike** [comment]
File and git autocomplete have stopped working for me as well.

**Comment by elviskahoro** [comment]
Thanks for opening gonna close this in favor of:
#562
