### ISSUE TITLE
Copy on select failed on auto-completed commands

### ISSUE THREAD

**Issue by zzxwill** [warpdotdev/Warp#1122]
### Discord username (optional)

zzxwill#6122

### Describe the bug

```text
`go test pkg/apiserver/rest/usecase/config_test.go` is auto-completed command which hasn't executed. It could be copied when selected.
```

### To Reproduce

Steps to reproduce:
1. Auto-complete a command
2. Select it
3. Try to paste in the terminal or to somewhere else.

### Expected behaviour

```text
Copy on paste.
```

### Screenshots

![image](https://user-images.githubusercontent.com/2805315/164001783-0d192d5e-6191-4399-a6c9-1fcce487baf9.png)

### Operating System

MacOS

### OS Version

11.4

**Comment by elviskahoro** [comment]
@zzxwill sorry but i still don't understand the issue here. Can you share a video of what it's doing? and explain a bit more as to what you expect it to do?

**Comment by elviskahoro** [comment]
As an fyi we chose to disable copy on select for the input editor because often times when you're pasting something into the input editor you'll highlight an area of text to replace. The highlighting process would then override your current clipboard (what you want to paste).
