### ISSUE TITLE
clear feature not working

### ISSUE THREAD

**Issue by nicole-meng** [warpdotdev/Warp#1124]
### Describe the bug

```text
you know how you can clear the whole terminal window by typing clear? Warp is not doing that i dont think
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

**Comment by zheng** [comment]
Does Ctrl + L give you your desired behavior? Agreed we should definitely make clear also do that though

**Comment by nicolem321** [comment]
Yes, Ctrl+L do the trick! Thank you

**Comment by elviskahoro** [comment]
Thanks for reporting gonna track this here instead:
#1163
