### ISSUE TITLE
Warp should request Automation privileges the first time it is run

### ISSUE THREAD

**Issue by HotFusionMan** [warpdotdev/Warp#1127]
### Describe the solution you'd like?

```text
Warp should request Automation privileges in System Settings > Security & Privacy > Privacy > Automation the first time it is run, so that the user can grant permission.
```

### Is your feature request related to a problem? Please describe.

```text
I cannot launch BBEdit from the command line to open a document:
>bbedit some_script
>You must allow the application which is running `bbedit` to send events to the BBEdit application.
>Please make appropriate changes in your Security & Privacy system preferences,
or contact your terminal/IDE application's developer for assistance.
bbedit: error: -1743
```

**Comment by shrugalic** [comment]
👍 Same issue here.

`bbedit` works fine in Terminal.app, and that does have this privileges:
<img width="780" alt="Screen Shot 2022-04-21 at 09 09 32" src="https://user-images.githubusercontent.com/41343671/164395224-b3bf2ec9-2a12-49d0-b4af-50db5fef483e.png">

**Comment by meyerweb** [comment]
I came here to make the same request, for the same reasons.  According to Rich Seigel, Warp “is missing an "NSAppleEventsUsageDescription" in the Info.plist.”  I thought about adding one myself, but decided potentially warping Warp was not on my list of things to do today.

**Comment by siegel** [comment]
> I thought about adding one myself, but decided potentially warping Warp was not on my list of things to do today.

That would have invalidated the application's code signature, resulting in a warp core breach. Not a good thing.

Devs: you can learn more about `NSAppleEventsUsageDescription` [here](https://developer.apple.com/documentation/bundleresources/information_property_list/nsappleeventsusagedescription?language=objc).

**Comment by leehinde** [comment]
I posted a note on this on the Discord server and it scrolled off without a response. Commenting on that here only in case you're tracking interest in the feature.

**Comment by gagata** [comment]
thanks for the feedback folks!
@leehinde sorry your message got lost on discord and thanks for jumping in here - we do use gh comments / reactions to track interest and prioritize better.

**Comment by roballie** [comment]
Same issue here.  I want to use the bbedit command line tools but cannot.

**Comment by berkus** [comment]
Same here, cannot launch Hopper via its cmdline tool.
