### ISSUE TITLE
Undo with CTRL-Z

### ISSUE THREAD

**Issue by ShukantPal** [warpdotdev/warp#113]
Sometimes I use "tab" to autocomplete a path but select the wrong subfolder. Right now, I have to do lots of backspace or select with mouse and backspace to fix that. A undo with ctrl + z would make this suuuper fast :)

**Comment by alokedesai** [comment]
We definitely agree! We're working on this now :) It should be out to users in the next week or two

**Comment by elviskahoro** [comment]
Feature Request for undo functionality concerning the input editor actions.
undo a clear line for example, undo for any of the input editor shortcuts mentioned in the docs here: https://docs.warp.dev/features/keyboard-shortcuts

**Comment by elviskahoro** [comment]
Not sure what the best way to track this would be (not sure what implementation details are), maybe a list of current keyboard shortcuts for the input editor to keep track of what to support undo for? Copying and pasting the input editor keyboard shortcuts from the doc isn't keeping the formatting correct, it'd be easier to copy and paste from the gitbook md source directly

**Comment by elviskahoro** [comment]
Coming out this wednesday! @ShukantPal
