### ISSUE TITLE
Dropdown capability

### ISSUE THREAD

**Issue by aspatari** [warpdotdev/Warp#1133]
### Describe the solution you'd like?

```text
It will be very useful to have dropdown capability like in guake or iterm 
For example: https://www.youtube.com/watch?v=TK3PUH30F5Q
```

**Comment by gagata** [comment]
hey! we already have this feature - checkout settings -> features -> hotkey window to set this up!

**Comment by aspatari** [comment]
@gagata i'm blind, sorry 
thanks for answering 
Also leave here link docs: https://docs.warp.dev/features/hotkey-window
