### ISSUE TITLE
Command pallette keybind does not update on cleared screen

### ISSUE THREAD

**Issue by egriff38** [warpdotdev/Warp#1137]
### Describe the bug

```text
Minor issue, but the updated keybind for command pallette (maybe for Search Commands too, haven't tested) does not appear correctly on the cleared terminal screen

I've set my keybind to `cmd+shift+p` but it still renders as `cmd+p`
```

### To Reproduce

Steps to reproduce:
1. Go to settings/keyboard shortcuts
2. Modify keybind for command palette to `⌘⇧p`
3. Exit and clear screen (⌘K)
4. See page still says "Command Palette ⌘P"

### Screenshots

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/6627718/164297358-03a09ecc-c91f-4f26-92ed-a87eda579a65.png">
Should show "Command Palette   ⌘⇧P"

### Operating System

MacOS

### OS Version

12.2.1

**Comment by elviskahoro** [comment]
This was fixed! Sorry for the delay
