### ISSUE TITLE
Chinese display problem after ssh connection to the server

### ISSUE THREAD

**Issue by sdd540578217** [warpdotdev/Warp#1139]
### Describe the bug

```text
The local Chinese display is normal, but after ssh to the server, the Chinese is displayed with "?"
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```text
Chinese display normally
```

### Screenshots

<img width="687" alt="k" src="https://user-images.githubusercontent.com/66023365/164367710-277a9aba-55f2-4d25-a072-622ebb0acc8b.png">

### Operating System

MacOS

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
This should be fixed now!
