### ISSUE TITLE
zsh right side custom prompt ($RPS1) causes extra space at start of prompt

### ISSUE THREAD

**Issue by humblehacker** [warpdotdev/Warp#1140]
### Discord username (optional)

humblehacker

### Describe the bug

```text
I have a custom right-side prompt in zsh defined:


RPS1="%{%}%n@%m%{%}  "


In Warp with the honor PS1 setting disabled, I get an extra space in my prompt. With this extra space, every command I type isn't saved in my history unless I remember to delete the extra space.

I can unset this variable myself, but it looks like Warp is already unsetting my PS1 variable, so it would make sense to auto-unset RPS1 as well until it's able to render them both successfully.
```

**UPDATE** I managed to reproduce this issue with only this:

```sh
RPS1="@"
```

So I'm simplifying the reproduction steps.

### To Reproduce

Steps to reproduce:
1. Set
    ```sh
    RPS1="@"
    ```
2. Note the extra space at the start of the prompt

### Expected behaviour

```text
RPS1 should be unset or otherwise ignored until fully supported
```

### Operating System

MacOS

### OS Version

12.3.1

**Comment by bygui86** [comment]
Setting RPS1="%{%}%n@%m%{%}  " I see it only in the result of a command...

**Comment by humblehacker** [comment]
@bygui86 I just tried it again, and pared it down to the simplest reproducible case. 
```sh
RPS1="@"
```
This seems to be enough to cause the problem. I'll update the problem report.

**Comment by wellcaffeinated** [comment]
I'm also having this issue which is the main reason I don't use warp at the moment. Confirmed that i can reproduce it as described above

**Comment by elviskahoro** [comment]
Thanks for opening
Gonna close this in favor of #936
