### ISSUE TITLE
Support direnv - stdout & stderr are pre-filled as input text

### ISSUE THREAD

**Issue by ptim** [warpdotdev/Warp#1142]
### Discord username (optional)

ptim#7095

### Describe the bug

```text
stdout & stderr are pre-filled as a command
```

### To Reproduce

Steps to reproduce:

Eg, with [direnv](https://github.com/direnv/direnv/), given .envrc has changed:

```bash
# <blank line; hit enter>
---
# the following stderr is filled, with the cursor at the end of the line (hitting enter submits it as a command)
direnv: error .envrc is blocked. Run `direnv allow` to approve its content
---
# clear input, then type:
direnv allow .
---
# the following stdout is printed as input, cursor at the end of the line:
direnv: loading .envrc
```

### Expected behaviour

```text
stdout & stderr should be printed above a blank line, not as a pre-filled command
```

### Screenshots

![screenshot -  - 2022-04-21 at 15 57](https://user-images.githubusercontent.com/218044/164385058-3ba5f9c0-de50-4a60-8f38-cdb010137f77.png)

### Operating System

MacOS

### OS Version

11.6.4

### Additional context

```sh
bash --version
GNU bash, version 5.0.17(1)-release (x86_64-apple-darwin19.4.0)

# .bash_profile
eval "$(direnv hook bash)"
```

**Comment by elviskahoro** [comment]
Thanks for opening will circle back when there's progress

**Comment by wzzrd** [comment]
Any progress on this? It doesn't do well as UX :(

**Comment by warpdotdev-dx** [comment]
I don't anticipate any progress until we start working on the prompt more formally.

**Comment by hovsater** [comment]
@warpdotdev-dx just ran into this myself. @warpdotdev-dx I think this should be prioritised as it messes up the prompt completely and it's not just related to [direnv](https://direnv.net) specifically but any tool that hook into `PROMPT_COMMAND`.

```console
$ __break_warp() { echo "This breaks Warp prompt!"; }
$ export PROMPT_COMMAND="$PROMPT_COMMAND; __break_warp"
```

**Comment by ericsampson** [comment]
@warpdotdev-dx it would be great to get this prioritized, it is the one single thing that is constantly wrecking my otherwise lovely experience using Warp <3

**Comment by ericsampson** [comment]
@elviskahoro it would be great to get this prioritized, it is the one single thing that is constantly wrecking my otherwise lovely experience using Warp <3

**Comment by beamery-tomht** [comment]
Having the same issue, also similar to the custom prompt problem here https://github.com/warpdotdev/Warp/issues/2516#issuecomment-1432857757

**Comment by dannyneira** [comment]
@beamery-tomht Sorry to hear about this, please take a look at our prompt and troubleshooting docs for more info on possible solutions. TLDR, you may have to encase some of your rcfile lines in a conditional so Warp ignores it, in particular I've noticed issues with multi-line or right-side prompts but this direnv seems to be another one. 

https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table
https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files

**Comment by beamery-tomht** [comment]
Hi @dannyneira - I'm 99% sure my issues are related to @hovsater 's comment that any tool that hooks into `PROMPT_COMMAND`

**Comment by dannyneira** [comment]
hey @ptim This has been resolved in the latest version of Warp. Please update and let us know of any issues. Closing as completed.
