### ISSUE TITLE
I can't get to home page after github authorization and always stay in sign in page

### ISSUE THREAD

**Issue by 511098425** [warpdotdev/Warp#1149]
### Describe the bug

```text
I can't get to home page after github authorization and always stay in sign in page
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Screenshots

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/3291861/164431424-f91b893e-28b8-430e-966f-537bba5bd7e9.png">

### OS Version

macos monterey

**Comment by dev4joel** [comment]
How to Troubleshooting Login Issues is here :
- 👉 [Troubleshooting Login Issues](https://docs.warp.dev/help/troubleshooting-login-issues)

How to fix the confusing login flow issue is here:
- 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)

How to fix the proxy issue is here:
- 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by rrtt2323** [comment]
me too

**Comment by elviskahoro** [comment]
Gonna close since we've improved login. Please comment or reopen if you still cannot.

**Comment by rrtt2323** [comment]
You are really great



At 2022-06-21 23:39:46, "elvis kahoro" ***@***.***> wrote:

Gonna close since we've improved login. Please comment or reopen if you still cannot.
