### ISSUE TITLE
Hotkey Window: Some combinations don't work on international keyboards

### ISSUE THREAD

**Issue by pyronaur** [warpdotdev/Warp#1156]
### Discord username (optional)

pyronaur

### Describe the bug

On Macbooks with "International layout" keyboards, the following shortcuts don't work:

```
cmd + `
cmd + §
```

I've attached a screenshot and a picture of the keyboard.

### To Reproduce

Steps to reproduce:
1. Set global window hotkey to be `cmd + §`
2. Press `cmd + §`
3. Warp doesn't toggle

### Expected behavior

Warp does allow setting `cmd + §` as the window hotkey, it should also be able to toggle the window 🙂

### Screenshots

![IMG_1048](https://user-images.githubusercontent.com/988095/164613555-607cbef9-9c73-4892-becf-e63c91bc6723.jpg)

![Screenshot 2022-04-22 at 08 56 57](https://user-images.githubusercontent.com/988095/164613561-527e0db1-cf55-48e0-8c43-630b028a4c59.png)

![Screenshot 2022-04-22 at 09 09 20](https://user-images.githubusercontent.com/988095/164613925-2aa6b59b-b18e-4db8-afde-56fd14c17813.png)

![Screenshot 2022-04-22 at 09 09 32](https://user-images.githubusercontent.com/988095/164613951-03abbb05-beae-4cb4-8128-4d6d6de980a7.png)

### Operating System

MacOS

### OS Version

12.3

### Additional context

This is a relatively common issue that I've seen other terminals have with binding keys. For example, it's also present on Tabby.

My current workaround is to use Raycast to bind the shortcut. Raycast and Alfred are both able to recognize the shortcut and toggle Warp for me.

![Screenshot 2022-04-22 at 09 11 26](https://user-images.githubusercontent.com/988095/164614195-64529a61-73a3-4251-9197-6b930d48d06b.png)

**Comment by juliusmarminge** [comment]
Also experiencing this. I had that keybinding on iTerm and now that I want to test Warp I need that keybinding to work...

**Comment by wutzi15** [comment]
I can confirm the bug. I'm trying to bind to "^ + <" (control & less than). It is not working on the german keyboard layout.

**Comment by alexejk** [comment]
Same thing, trying to bind Ctrl+§ on Swedish keyboard. Works with iTerm 2.

**Comment by pyronaur** [comment]
Looks like this is a duplicate of #856 


Self-closing
