### ISSUE TITLE
Quickly open a directory or file

### ISSUE THREAD

**Issue by sbfkcel** [warpdotdev/Warp#1158]
### Describe the solution you'd like?

```text
Increase the ability to press and hold cmmand + click on the name (directory/file) to open the path or directory through Finder or the corresponding program
```

**Comment by rodelta** [comment]
Essential to navigate those error logs

**Comment by zhaopan-pan** [comment]
It is very important for quickly locating problems during development and debugging

**Comment by warpdotdev-dx** [comment]
I think is a duplicate:
GitHub issue for opening file (by clicking) in finder or default app: https://github.com/warpdotdev/Warp/issues/177
