### ISSUE TITLE
Have to login on restart

### ISSUE THREAD

**Issue by ShukantPal** [warpdotdev/warp#116]
I shut down my computer everyday, and Warp asks me to "Sign in" each time I start it. Would prefer not to :)

**Comment by mittalyashu** [comment]
That's definitely seems like a bug, it's not happening for me.

@ShukantPal Can you share more information, like OS and build version for the dev's?

**Comment by ShukantPal** [comment]
An iMac on macOS 11.4, v.0.2021.07.27.17.17 build of Warp

**Comment by ShukantPal** [comment]
BTW, it happened once / twice but it doesn't seem to happen more now
