### ISSUE TITLE
Clear does not clear the screen

### ISSUE THREAD

**Issue by kianjavaheri** [warpdotdev/Warp#1163]
### Describe the bug

```text
When I type clear into warp, it does not clear the screen. It just indicates that the command was valid but doesn't actually do anything.
```

**Comment by elviskahoro** [comment]
What happens when you press CTRL-L?
There might be something that Warp is incompatible with in your dotfiles? Could you share them with me over email? elvis at warp dot dev

**Comment by santaji1986** [comment]
Hi @elviskahoro 
`CTRL + L` doesn't perform any action in warp terminal

**Comment by cesarvarela** [comment]
Same problem here, `CTRL+L` does work.

I'm using ohmyzsh with no customizations 🤷

**Comment by dannyneira** [comment]
Hi @kianjavaheri @cesarvarela Are you still seeing the clear issue on the latest Warp build?

**Comment by cesarvarela** [comment]
Seems to be fixed!

**Comment by dannyneira** [comment]
Closing as resolved, but please do let us know if the issue persists.
