### ISSUE TITLE
Allow being able to change the path in here

### ISSUE THREAD

**Issue by nikivdev** [warpdotdev/Warp#1166]
### Describe the solution you'd like?

iTerm allows making the tab names be path where the tab is currently in. It's very useful and something I miss from iTerm but can't seem to do in Warp.

So this in Warp:

<img width="921" alt="image" src="https://user-images.githubusercontent.com/6391776/164814869-4ec07c3d-832e-44e3-b2d9-9781319301d2.png">

Would be this: 

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/6391776/164814918-f9fbcd44-3fc7-4b93-8474-a7e9c9f45d6e.png">

Note the path names. (~zsh) is not useful to me but iTerm adds.

Thank you.

**Comment by nikitavoloboev** [comment]
Okay apparently it does show but I don't get when it shows and when it doesn't.

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/6391776/164861773-39a28e41-88a9-4a65-b4e8-46188bfba8d7.png">

Is it possible to force it to always show the path no matter what. I would really love this.
