### ISSUE TITLE
Split Panes introduce unwanted UI movement

### ISSUE THREAD

**Issue by tals** [warpdotdev/Warp#1168]
### Describe the bug

When using the [built-in split panes feature](https://docs.warp.dev/features/split-panes), the focused pane shifts up and down to make room for the input prompt, causing the whole UI to shift.
it's pretty disorienting when working with a few panes.

It happens in fish and other shells.
As soon as you enter a sub-shell, the shifting goes away

### To Reproduce

This worked for me with the default shell config (`rm -fr ~/.config/fish`)
fish: 3.4.1

1. Split terminal with cmd+d
2. with shell on both panes, jump back and forth
3. Observe UI shifting

### Expected behaviour

```text
UI doesn't shift, which is the case with bash and iterm
```

### Screenshots

https://user-images.githubusercontent.com/761863/164845709-50970986-9e57-4235-92d2-4851f232970d.mp4

https://user-images.githubusercontent.com/761863/164845718-fef9109d-6467-40e1-b22e-931d7e8eea8e.mp4

### Operating System

MacOS

### OS Version

12.3 (21E230)

**Comment by dev4joel** [comment]
Thanks for the feedback!


Duplicate: GitHub issue for consistently sized input editor when using split panes: #303


Will close this in favor of that one.

**Comment by elviskahoro** [comment]
Closing in favor of #303

**Comment by dannyneira** [comment]
Thanks for your patience folks! As requested, in Warp version `v0.2023.09.19.08.04.stable_00` and above, the input editor remains visible in inactive panes when using split panes. 

![CleanShot 2023-09-21 at 13 34 04](https://github.com/warpdotdev/Warp/assets/16809145/5b27a944-5add-4296-9166-1e502f70fab7)

Closing as completed, but please let us know if any issues.
