### ISSUE TITLE
Svg on download page broken

### ISSUE THREAD

**Issue by mjlyons** [warpdotdev/warp#117]
**Describe the bug**
One of the images on your download page is broken

**To Reproduce**
1. Go to https://app.warp.dev/download/r/XXXXXXX

**Expected behavior**
You should see an image on the left

**Screenshots**
<img width="1644" alt="Screen Shot 2021-08-10 at 10 42 15 AM" src="https://user-images.githubusercontent.com/636631/128887755-651af620-2315-48b2-8774-738af1bac46e.png">

**Desktop (please complete the following information):**
- Safari 14.1.1 on MacOS 11.4

**Comment by zachlloyd** [comment]
Thanks for the report - we will fix this week!
