### ISSUE TITLE
I can't successfully landed by github account

### ISSUE THREAD

**Issue by rrtt2323** [warpdotdev/Warp#1174]
### Describe the bug

```text
Sign in.
The process is not responding for some time.
Back to the Start menu.
There's nothing wrong.
```

### To Reproduce

Steps to reproduce:
...

### Expected behaviour

```text
Let me use.
```

### Operating System

MacOS

### OS Version

12.3.1

**Comment by JohnMicl** [comment]
me too.
MacOS Version: 12.1

**Comment by liziqiang** [comment]
me too.
macOS Monterey 12.3.1

**Comment by dev4joel** [comment]
How to Troubleshooting Login Issues is here :

👉 Troubleshooting Login Issues
How to fix the confusing login flow issue is here:

👉 Can Not Sign Up Or Sign In Warp With Github(Public Beta)
How to fix the proxy issue is here:

👉 WARP-does-not-work-after-submitting-an-invite-code

**Comment by dev4joel** [comment]
How to Troubleshooting Login Issues is here :

👉 [Troubleshooting Login Issues](https://docs.warp.dev/help/troubleshooting-login-issues)
How to fix the confusing login flow issue is here:

👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)

How to fix the proxy issue is here:

👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by JohnMicl** [comment]
> me too. MacOS Version: 12.1

Feeling depressed still not working after trying, kind of want to give up.
👉 [Troubleshooting Login Issues](https://docs.warp.dev/help/troubleshooting-login-issues)

**Comment by sjn4048** [comment]
me too.
macOS Monterey 12.3.1

**Comment by houseme** [comment]
me too.
macOS Monterey 12.3.1

**Comment by nzh10** [comment]
Encountered this problem in a restricted network as well, solved by the second article: simply execute warp with PROXY environment variable in the terminal.

**Comment by Y80** [comment]
ClashX 用户试试我的解决方案。

Steps:
1. 复制 proxy 命令行，并执行
![image](https://user-images.githubusercontent.com/40132433/164953697-8449cda3-ff7f-43ac-8b4f-7e4aba6ddc89.png)
2. terminal 中：
![image](https://user-images.githubusercontent.com/40132433/164953767-a003982a-dddb-40dd-8631-788ccb96d401.png)
3. 然后 sign in/up

**Comment by houseme** [comment]
> ClashX 用户试试我的解决方案。
> 
> Steps:
> 
> 1. 复制 proxy 命令行，并执行
>    ![image](https://user-images.githubusercontent.com/40132433/164953697-8449cda3-ff7f-43ac-8b4f-7e4aba6ddc89.png)
> 2. terminal 中：
>    ![image](https://user-images.githubusercontent.com/40132433/164953767-a003982a-dddb-40dd-8631-788ccb96d401.png)
> 3. 然后 sign in/up

按照这个步骤是可以成功的

**Comment by rrtt2323** [comment]
I landed by replacing the network, no pop-up login window again.
By the time it popup, I try clashx.

**Comment by Three-fire** [comment]
Why not open  other online registration methods？Not Only Github

**Comment by elviskahoro** [comment]
We've since added the ability to login via Google or email

**Comment by rrtt2323** [comment]
You are the best team



At 2022-06-22 00:08:00, "elvis kahoro" ***@***.***> wrote:

We've since added the ability to login via Google or email
