### ISSUE TITLE
Pointless issue

### ISSUE THREAD

**Issue by Inffinite** [warpdotdev/Warp#1175]
### Discord username (optional)

white#9035

### Describe the solution you'd like?

```text
My day was going great until i saw such a great terminal available only on mac and not on linux.
```

### Is your feature request related to a problem? Please describe.

More or less

### Additional context

Sigh

**Comment by eordano** [comment]
FWIW I am experiencing the same :(
Much love and respect for what you're doing! <3

**Comment by elviskahoro** [comment]
Tracking this in #120
