### ISSUE TITLE
Fish Starship prompt newline not supported

### ISSUE THREAD

**Issue by nanthony007** [warpdotdev/Warp#1176]
### Discord username (optional)

TimeWellWasted#3327

### Describe the bug

```text
My fish shell Starship prompt does not respect the newline in the default prompt.
```

### To Reproduce

1. Enable fish shell as default shell
2. Enable starship prompt

### Expected behaviour

```text
I expected to see a 2-line prompt.
```

### Screenshots

<img width="80" alt="Screen Shot 2022-04-23 at 4 56 43 PM" src="https://user-images.githubusercontent.com/45318637/164945732-dd86c2f3-707e-4ed8-a4d5-465f9a812fde.png">
<img width="80" alt="Screen Shot 2022-04-23 at 4 56 59 PM" src="https://user-images.githubusercontent.com/45318637/164945739-0f32a489-ebbb-4e58-a546-e146b831e08a.png">

### Operating System

MacOS

### OS Version

12.3.1

### Additional context

Interestingly this DOES work when I enter the fish prompt inside Warp, but then the entire fish session is treated as one cell.

**Comment by PeterCardenas** [comment]
I ended up disabling the character module when the terminal is warp. You can do this by checking the TERM_PROGRAM env variable in fish config to select the correct config for the terminal.

**Comment by nanthony007** [comment]
This doesn't seem like a solution but a workaround... If you are going to support custom prompts they should be supported fully and "work" out of the box IMO.

**Comment by warpdotdev-dx** [comment]
We don't have support for multi-line prompts because our Input Editor is a separate UI element from our Prompt. This is what enables the modern text editor experience.


The goal is to improve our built in prompt so people can use that in lieu of custom prompt.

**Comment by elviskahoro** [comment]
Gonna close this in favor of:
#1015
