### ISSUE TITLE
Save connection information for SSH

### ISSUE THREAD

**Issue by Artanis-c** [warpdotdev/Warp#1178]
### Describe the solution you'd like?

```text
Is it possible to save a list of SSH connection information like Tabby or XSHell, to avoid needing to enter the account and password every time, it is really troublesome to remember the IP address and account password
```

**Comment by mortalBibo** [comment]
+1

**Comment by mrudrara** [comment]
+1

**Comment by mrudrara** [comment]
Iterm password manger can be used with any command-line tool needing password interactively
like `sudo su -` `psql `

**Comment by RobsOnWaves** [comment]
+1

**Comment by elviskahoro** [comment]
It's possible but we're tracking this here:
GitHub discussion on [Remote connection management for SSH:](https://github.com/warpdotdev/Warp/discussions/442) <https://github.com/warpdotdev/Warp/discussions/442>
