### ISSUE TITLE
I want to be able to customize the size of the open window

### ISSUE THREAD

**Issue by wChenonly** [warpdotdev/Warp#1181]
### Describe the solution you'd like?

```text
I want to be able to customize the size of the open window，
```

**Comment by wChenone** [comment]
<img width="645" alt="image" src="https://user-images.githubusercontent.com/37658262/164966198-25d745f9-1b88-448b-a1b4-864398a6a6b8.png">
iterm2 can

**Comment by wChenone** [comment]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/37658262/164966232-82a15228-2dc7-40a1-a3e1-ee2fca3c1166.png">

Iterm2 can. After setting it, every startup will be so small. I like small windows.

**Comment by pizsd** [comment]
@wChenonly 　这个默认窗口大小已经有了吗，我没找到设置，你是怎么处理的

**Comment by warpdotdev-dx** [comment]
It doesn't exist yet!
GitHub issue for configuring Warp's default size: https://github.com/warpdotdev/Warp/issues/19
