### ISSUE TITLE
hello~warp can not login

### ISSUE THREAD

**Issue by leozz705** [warpdotdev/Warp#1182]
### Describe the bug

```text
Click "Login Up Via Githup" to pop up a blank page window!
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

**Comment by dev4joel** [comment]
How to Troubleshooting Login Issues is here :
- 👉 [Troubleshooting Login Issues](https://docs.warp.dev/help/troubleshooting-login-issues)

How to fix the confusing login flow issue is here:
- 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)

How to fix the proxy issue is here:
- 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by shuifa** [comment]
> How to Troubleshooting Login Issues is here :
> 
> * 👉 [Troubleshooting Login Issues](https://docs.warp.dev/help/troubleshooting-login-issues)
> 
> How to fix the confusing login flow issue is here:
> 
> * 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)
> 
> How to fix the proxy issue is here:
> 
> * 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

Click "Login Up Via Githup" to pop up a blank page window! I have this problem, I confirm that my safari browser does not have an ad blocker and I removed the dev.warp.Warp-Stable folders in the Library/ Application Support. The same problem remains after the restart warp. Please help see if there are other ways to fix it

**Comment by dev4joel** [comment]
Could you try it:
- Go to Safari Preferences > Privacy
- Uncheck the "Block all cookies" checkbox

**Comment by shuifa** [comment]
> Could you try it:
> 
> * Go to Safari Preferences > Privacy
> * Uncheck the "Block all cookies" checkbox

Thank you for your reply. I checked Safari Preferences > Privacy, the "Block all cookies" checkbox, originally, it was unchecked

**Comment by dev4joel** [comment]
Try this link: https://app.warp.dev/login/remote?scheme=warp&nolocalhost=true, to see what error you get.

**Comment by shuifa** [comment]
> Try this link: https://app.warp.dev/login/remote?scheme=warp&nolocalhost=true, to see what error you get.
<img width="1324" alt="截屏2022-04-30 12 16 13" src="https://user-images.githubusercontent.com/53784478/166090178-16774130-eb8b-450c-bc8e-4eba57900e0a.png">

Wait a few seconds to see this error

**Comment by dev4joel** [comment]
Probably, are you on a proxy? If not, try using a proxy.

**Comment by elviskahoro** [comment]
Gonna close since there have been lots of improvements to login. Please reopen if you're still having trouble!
