### ISSUE TITLE
Implement fullscreen keybinding

### ISSUE THREAD

**Issue by sycured** [warpdotdev/Warp#1187]
### Describe the solution you'd like?

```text
Like iTerm when doing Command+Enter (Return), we switch between windowed <-> fullscreen
```

**Comment by leecade** [comment]
Also hope to have a transparent background.

**Comment by elviskahoro** [comment]
We support doing this with CTRL-CMD-F!
If you're looking for a window that is set to take the whole screen but isn't technically a Full screen app then look follow here #710
