### ISSUE TITLE
DUP: Duplicate of #058 - Support drag-and-drop to rearrange tabs

### ISSUE THREAD

**Issue by rvlasveld** [warpdotdev/warp#119]
**Is your feature request related to a problem? Please describe.**

When opening multiple tabs, it becomes hard to know which tab refers to what exactly. When opening multiple tabs from different locations, they become unorganised. 

**Describe the solution you'd like**
Support drag-and-drop behaviour on the tabs, similar to how other apps (e.g. Mac Terminal, Chrome) allow this.

Bonus point: dragging a tab _out_ of the window to create a new window for that tab, and dragging a tab/window _in_ one to embed it.

**Comment by zachlloyd** [comment]
Agreed on this being desirable.  Duplicate of #58
