### ISSUE TITLE
Auto Complete Issue

### ISSUE THREAD

**Issue by RamziJabali** [warpdotdev/Warp#1196]
### Describe the bug

```text
Auto Complete completes entire line including date and time, which isn't supposed to be the case.
```

### To Reproduce

Steps to reproduce:
1. Go to warp
2. Autocompleting sometimes when using suggestion(hitting right key) takes user to end of line where the date is.
3. It seems to better work when autocompleting from start of line, not a space in as default added by warp

### Screenshots

https://user-images.githubusercontent.com/18749441/165234162-9ce82627-293d-4490-9eab-b3e182e64d77.mov

### Operating System

MacOS

### OS Version

11.6.2

**Comment by elviskahoro** [comment]
Thanks for reporting. Check out these docs:
https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files

Gonna close in favor of:
#936
