### ISSUE TITLE
Cannot complete Chinese directory name

### ISSUE THREAD

**Issue by shidephen** [warpdotdev/Warp#1197]
### Discord username (optional)

BluRadius#9136

### Describe the bug

```text
Directory complete does not support Chinese charactors(maybe Unicode)
```

### To Reproduce

Steps to reproduce:
1. Go to a directory contains Chinese charactors.
2. Type cd[space].
3. Press tab to complete directory name.

### Expected behaviour

```text
Display all directories in the prompt panel. And I can choose the one with Chinese charactors.
```

### Screenshots

![image](https://user-images.githubusercontent.com/10269623/165244581-a8f7439d-652f-4321-bb61-627ad9862a2a.png)

### Operating System

MacOS

### OS Version

11.5.2 (20G95)

**Comment by elviskahoro** [comment]
This should be fixed! Apologies for the delay.

**Comment by shidephen** [comment]
> This should be fixed! Apologies for the delay.

Awesome it works!
