### ISSUE TITLE
Zoom split window

### ISSUE THREAD

**Issue by wesleylether** [warpdotdev/Warp#1198]
### Discord username (optional)

wesleylether#3749

### Describe the solution you'd like?

When you split a window with `CMD + D` or `CMD + SHIFT + D` it would be nice if you can zoom / full screen the active window. (With a keyboard shortcut would be great).

### Additional context

It's a feature like tmux zoom. With CMD + B followed by Z it will zoom / full screen the active pane. When run the same command it will zoom out.

**Comment by luizsignorelli** [comment]
I came here to ask for this feature. I use it on iTerm all the time with `CMD + SHIFT + Enter`

**Comment by wesleylether** [comment]
@luizsignorelli it has just implemented and works now with `CMD + SHIFT + Enter`
