### ISSUE TITLE
Full P3 color on mac

### ISSUE THREAD

**Issue by kynrai** [warpdotdev/Warp#1201]
### Describe the solution you'd like?

```text
Alacritty terminal supports full P3 color on mac screens which means the colors sort of "pop" more and are generally more vibrant, matching the colour of most other apps.

Im unsure if warp supports this but from comparrision with matching color themes, it feels like warp does not support this and instead has a more muted color range like terminal and iterm2.

I have no idea how hard this is to implement considering iterm2 has had this as an open issue for 4 years but seeing as alacritty has done it also in rust i thought it might be worth a feature request.
```

**Comment by kynrai** [comment]
Same ticket open on iterm2

https://gitlab.com/gnachman/iterm2/-/issues/6436

**Comment by elviskahoro** [comment]
Thanks for the FR. Will update when this is a WIP

**Comment by jordanbrauer** [comment]
Going to reference #1110 since it seems to be related. 😁

**Comment by dannyneira** [comment]
Hi folks @kynrai @jordanbrauer, we recently released an [update](https://github.com/warpdotdev/Warp/issues/362#issuecomment-2140826971) to the way Warp renders ANSI colors, removing the previous dimming and respecting the way colors should be rendered based on the user's theme. Please update Warp and let us know if the issue with the lack of color in Warp persists.
