### ISSUE TITLE
(git-info) Output from zsh/Prezto breaks input line

### ISSUE THREAD

**Issue by rvlasveld** [warpdotdev/warp#121]
**Describe the bug**
I'm using zsh/Prezto with the `git-info on` mode, which renders branch name and other info at the end of my terminal input. Previously this didn't give any issues, but since the update yesterday (now on version v0.2021.08.11.15.36.stable) the cursor is put after the git-info and it becomes part of the input. 

This means that I have to manually clear the current input each time - making Warp broken / useless :(

**Comment by alokedesai** [comment]
Hey there! Thanks for filing, this is fixed at head and we should be pushing a new release with the fix to all users shortly.

**Comment by alokedesai** [comment]
This should be fixed with the current release--would you mind autoupdating and confirming it's fixed for you?

**Comment by rvlasveld** [comment]
Seems like it's working again indeed, thanks for the quick fix! Keep it up!

**Comment by alokedesai** [comment]
Thank you for filling and using Warp! Keep the issues and feedback coming ❤️
