### ISSUE TITLE
Path suggestion is hidden under text of a split pane

### ISSUE THREAD

**Issue by Gray-Wind** [warpdotdev/Warp#1210]
### Discord username (optional)

Gray_Wind#9277

### Describe the bug

```text
The suggestion popover is behind text of a split pane.
```

### To Reproduce

Steps to reproduce:
1. open a split pane
2. in the first one call autocompletion for path

### Expected behaviour

```text
right half of a popover would be on top of text
```

### Screenshots

<img width="651" alt="image" src="https://user-images.githubusercontent.com/4902794/165483055-0b14b0a8-05dd-4311-af69-69f2fc6269bd.png">

### Operating System

MacOS

### OS Version

12.3.1

### Additional context

```text
v0.2022.04.18.09.08.stable_04
```

**Comment by elviskahoro** [comment]
Hey @Gray-Wind I think this was fixed. Can you comment if it's still happening for you? Will close meanwhile
