### ISSUE TITLE
Replace xxd with od

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#1218]
### Describe the solution you'd like?

```text
Replace the xxd dependency with od since it's supported by more devices.
```

**Comment by guyeu** [comment]
Is there a workaround to fix this issue as soon as possible?

**Comment by elviskahoro** [comment]
@guyeu 
Still no workaround but it's being worked on

**Comment by elviskahoro** [comment]
From @lululombard via #1422
### Discord username (optional)

lululombard#1337

### Local Shell and Version

5.8.1

### Remote Shell and Version

5.9

### Operating System and Version

Asahi Linux (Arch Linux)

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

When connecting to a server that doesn't have `hostname` and `xdd`, you'll get:
```
zsh:2: command not found: hostname
zsh:13: command not found: xxd
```

<img width="1092" alt="Broken" src="https://user-images.githubusercontent.com/2182934/171315043-973ac9c0-6cd0-4a33-b9a5-cbf8852f8822.png">

The AI auto completion will also not work.

These are not from the .zshrc file, it's just that is a bare install of Arch Linux. Running `sudo pacman -S inetutils vim` fixes the issue:

<img width="1092" alt="Fixed" src="https://user-images.githubusercontent.com/2182934/171315656-0a87e9bf-6268-4686-999f-0fb6d6108abb.png">

As I often use my terminal to connect to very minimalistic Linux installs, I'd like if there's a fallback that would let me use Warp instead of iTerm that does not require `hostname`:
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/2182934/171315887-0169bb1a-5aa4-4105-ab3c-99f1db9ec0fa.png">

### Include shell xtrace output

It will not output anything. 

<img width="300" alt="image" src="https://user-images.githubusercontent.com/2182934/171315306-e83d7524-02c6-4040-a7bb-bfa1de1f00c3.png">


### Warp Internal (ignore) - linear-label:018de222-5d69-45e6-ba7c-c94b9ae09495

_No response_

**Comment by vorporeal** [comment]
This should be fixed now; please re-open if you're experiencing issues with ssh due to the remote machine missing commands (e.g.: `od`).
