### ISSUE TITLE
Support double tap keybinding

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#1221]
### Describe the solution you'd like?

```text
One thing that keeps me from using it for work is the hotkey window. I need the shortcut to be able to be something like "ctrl+ctrl".
```

**Comment by BossElijah** [comment]
Yup, this is my feature request. I'd be very glad if that could be added since, that's what I'm used to with iTerm.

**Comment by chrishiste** [comment]
Adding some context:

<img width="1011" alt="166066618-21339fea-bb3f-47eb-a53a-d4ff99a96f43" src="https://user-images.githubusercontent.com/24848602/166067016-5f562fe2-eab0-4332-87c5-624d16f13902.png">

iTerm has an option to double-tap Control, Option, Shift or Command to trigger the hotkey window.

This is so ingrained in my workflow that I can't consider switching to Warp without it.

**Comment by dannyneira** [comment]
Hi Folks, we have an existing request tracking this over at https://github.com/warpdotdev/Warp/issues/2809

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/2809
