### ISSUE TITLE
keyboard shortcuts for Find Next/Previous Occurrence

### ISSUE THREAD

**Issue by HotFusionMan** [warpdotdev/Warp#1227]
### Describe the solution you'd like?

```text
I was surprised that the Find feature doesn't respond to the typical Command-G to go to the next occurrence of the search string. While we're at it, being able to "find next occurrence" in the opposite direction ("find previous occurrence") would be nice, too. Allowing these keybindings to be edited in the Settings would also be great.
```

**Comment by gagata** [comment]
hey! thanks for the feedback! while you can't adjust those shortcuts, we do support `enter` to go to next occurence and `shift-enter` to go to the previous one.

**Comment by vjindal0112** [comment]
Support for `cmd-g` and cmd-shift-G` was just added in the most recent release! Please let us know if you have any feedback.
