### ISSUE TITLE
Can warp support AppleScript

### ISSUE THREAD

**Issue by wathenjiang** [warpdotdev/Warp#1228]
### Discord username (optional)

spongecaptain#1876

### Describe the solution you'd like?

```text
Can warp support AppleScript?
```

### Is your feature request related to a problem? Please describe.

```text
I want to write some scripts on Mac to easy using of Warp.

But I found Warp might not support AppleScript.
```

### Additional context

When I use Iterm2, It works well, for example:

```
set command to "clear; cd ~/Desktop"

tell application "iTerm"
	select first window
	tell the first window
		tell current session to write text command
	end tell
end tell
```
The abovbe scripts can make the session on Iterm2 cd the target directory, which means `~/Desktop`.

But when I use "Warp" instead of Iterm, it occurs problems:

```
set command to "clear; cd ~/Desktop"

tell application "Warp"
	select first window
	tell the first window
		tell current session to write text command
	end tell
end tell
```

![image](https://user-images.githubusercontent.com/48505670/165790587-461f2150-76b9-4e4e-ac9c-769ef5bd53e3.png)

**Comment by dev4joel** [comment]
Thanks for the feedback!


Duplicate: GitHub issue for General Scriptability : https://github.com/warpdotdev/Warp/discussions/612


Will close this in favor of that one.

**Comment by wisinfun** [comment]
I also need this request very much
