### ISSUE TITLE
Rename Tabs in Warp

### ISSUE THREAD

**Issue by lizziekoshelev** [warpdotdev/Warp#1229]
### Describe the solution you'd like?

```text
Similar to mac terminal, I'd like to be able to name my tabs for better workflow. Command shift I is the usual command on a mac to do this
```

**Comment by fsferrara** [comment]
Could we also reorganize the tabs order without closing them?

**Comment by gagata** [comment]
Hey! Thanks for the feedback!

We have yet to publish a more detailed doc on the current state of tab titles, but the recent release has some changes that may help you out here:

we adjusted the default tab titles (so you'll see the current directory vs seeing the user@hostname)
for now, you can set the custom content using your rc files, for zsh it'll be something like that:
  window_title="\033]0;<HERE GOES YOUR DESIRED TITLE>\007"
  echo -ne "$window_title"
}

precmd_functions+=(set_title)```

let us know what you think!

@fsferrara tab reordering is currently being worked on!
