### ISSUE TITLE
Tab completion on `curl -I` results in another I being added (repeatedly)

### ISSUE THREAD

**Issue by RSO** [warpdotdev/warp#123]
**Describe the bug**
When I put `curl -I` in the terminal and press tab to autocomplete another `I` is added to the command, if I press tab again it repeats

**To Reproduce**
1. In any folder
2. Type `curl -I`
3. Press tab

**Expected behavior**
I expect either to see a list of different options I can add to the command, or nothing to happen (if there's no suggestions).

**Screenshots**
<img width="227" alt="CleanShot 2021-08-14 at 11 03 50@2x" src="https://user-images.githubusercontent.com/139663/129440998-d80aceea-1a67-4f73-8c2c-79998d9ddd3b.png">

**Desktop (please complete the following information):**
 - OS Version: MacOS 11.5

**Comment by zachlloyd** [comment]
Thanks for the report - still working through a number of completion issues.

@charlespierce something to check with your parser change.

**Comment by gagata** [comment]
Looks like it's been fixed, so closing this one!
