### ISSUE TITLE
Add a Show/Hide option to the Hotkey Window positioning options

### ISSUE THREAD

**Issue by zpthree** [warpdotdev/Warp#1230]
### Discord username (optional)

zpthree#4668

### Describe the solution you'd like?

```text
Currently there are only options to pin a separate window to one side of the window. It would be cool to have an option of Show/Hide that simple toggles the warp app between shown and hidden and not have to pin a new window. This is how I used Hyper. I would toggle the app between shown and hidden with a global hotkey.
```

### Is your feature request related to a problem? Please describe.

```text
Nothing is broken, it's just the one thing I miss from Hyper.
```

**Comment by elviskahoro** [comment]
@zpthree 
So the request is the Global Hotkey Window keybinding should focus Warp on whatever window / screen is in focus?

**Comment by zpthree** [comment]
@elviskahoro Not necessarily whatever screen is in focus. It would just show/hide the warp window wherever it is. So like if I have the warp app open a certain monitor (not in quake mode), I could use the global hotkey to show/hide it with no repositioning. An example of an apps that have this functionality are Todoist, Numi, and Hyper terminal.

**Comment by BlakeTheAwesome** [comment]
I'd also like this feature.
If I have VS Code focused for example, it'd be nice to just hit my shortcut keys (I used to use Option+Space with iTerm) and be able to start writing into my existing Warp window on whichever monitor it currently resides, then hit my shortcuts again when I want the focus to swap back.
The current quake thing feels like it's just a temporary window in its own context, when I want to switch to/from my persistent terminal window with all its long-running apps.

**Comment by natebrunette** [comment]
I also used this with iterm2. I would configure my hotkey window to float on the desktop (not pinned) and the hotkey would bring it to the front when pressed.

**Comment by acarl005** [comment]
Closing this issue since the feature was shipped. See #2585 for how to enable.
