### ISSUE TITLE
Text Spacing changed

### ISSUE THREAD

**Issue by fbsh** [warpdotdev/Warp#1231]
### Describe the bug

```text
I just updated the Warp and noticed the text spacing is way larger than the previous path. Is it any bug?

Device: MacBook Air M1
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Screenshots

[](url
<img width="1018" alt="Screen Shot 2022-04-28 at 11 08 37 PM" src="https://user-images.githubusercontent.com/13392191/165884086-d9f7a1a9-f1b0-4a7c-9fb0-3f087af9eaad.png">
)

### Operating System

MacOS

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
This should be fixed. I think we reverted that commit.
