### ISSUE TITLE
"Toggle Fullscreen" keybinding

### ISSUE THREAD

**Issue by brunobelotti** [warpdotdev/Warp#1238]
### Discord username (optional)

Bruno#2712

### Describe the solution you'd like?

```text
Add a keyboard shortcut (and the possibility to customize it in the preferences) for the "Window -> Zoom" menu command (Fullscreen toggle).
```

### Is your feature request related to a problem? Please describe.

```text
I commonly toggle my terminal between a window and fullscreen (as in "cover the screen fully", not in "MacOS horribly invasive animated fullscreen mode").
Warp already have a "Windows -> Zoom" option for that, which works great, but there is no keyboard shortcut, nor it's possible to set one (for example my choosen one "CMD + Enter" in Alacritty).
```

**Comment by hrbrmstr** [comment]
On macOS, a common idiom is to have a "View" menu with an "Enter Full Screen" menu item, which has a common shortcut of `^⌘F`.  Maintaining that idiom for toggling full screen mode would also be great.

**Comment by elviskahoro** [comment]
We support this now!
Using CTRL-CMD-F to go full screen and also using Zoom to expand the app to the full-screen
