### ISSUE TITLE
Completions: Add zsh-autosuggestions/fish-like suggestions

### ISSUE THREAD

**Issue by RSO** [warpdotdev/warp#124]
**Is your feature request related to a problem? Please describe.**
I'm loving the autocomplete list in Warp, and would love it if Warp can already suggest one command in the same way that zsh-autosuggestions does. I have zsh-autosuggestions installed but the suggestion is not showing up in Warp so I think that some work is needed to support this?

**Describe the solution you'd like**
Screenshot from iTerm:
<img width="227" alt="CleanShot 2021-08-14 at 11 07 22@2x" src="https://user-images.githubusercontent.com/139663/129441042-08a39da6-94ff-4447-8d55-6893cf7c6b5d.png">

**Additional context**
https://github.com/zsh-users/zsh-autosuggestions

**Comment by zachlloyd** [comment]
This is on our roadmap - I expect we will launch it within the next month.

Thanks for suggesting

**Comment by elviskahoro** [comment]
Closed: v0.2021.11.09.19.46.stable_00
