### ISSUE TITLE
Support for sequence / chords as a keybinding

### ISSUE THREAD

**Issue by kuklyy** [warpdotdev/Warp#1240]
### Discord username (optional)

kuklyy#5245

### Describe the solution you'd like?

```text
When I double press ctrl (or any other key) the terminal window should appear on the screen.
```

### Is your feature request related to a problem? Please describe.

```text
I'm trying to use your software instead of iTerm, but there is one key feature that is missing. I really want to use a sequence of e.g. ctrl + ctrl to summon the terminal window.
```

**Comment by elviskahoro** [comment]
Thanks for opening! will circle back when there are updates!

**Comment by dannyneira** [comment]
Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Hi Folks, we have an existing request tracking this over at #2809

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

**Comment by dannyneira** [comment]
Duplicate of #2809

**Comment by seangaffney** [comment]
The description of this issue is correctly a duplicate of #2809, however the title functionality is actually a duplicate of the newer, more descriptive issue #5890. Please cast your vote there for keyboard shortcut chords.
