### ISSUE TITLE
Can't show permission dialog when record audio

### ISSUE THREAD

**Issue by tp7309** [warpdotdev/Warp#1242]
### Describe the bug

```text
With ffmpeg I tried to record audio on MacOS.

ffmpeg -f avfoundation i :0 out.wav
```
It can not run normally, show **19108 abort**, and no audio permission dialog shown,
but `Terminal` or `iTerm2` is work fine.

Warp version: v0.2022.04.25.09.59.stable_03
```


### To Reproduce

Steps to reproduce:
1. Go to 'warp'
2. run `ffmpeg -f avfoundation i :0 out.wav`
3. See error '19108 abort'


### Expected behaviour

```text
command run normally, and can trigger show audio permission dialog.
```

### Screenshots

<img width="805" alt="9478567381252ce2add8604af193188" src="https://user-images.githubusercontent.com/5046191/166140279-eddde3c7-7238-449e-8e4b-477a82c29975.png">

### Operating System

MacOS

### OS Version

10.15.7

**Comment by geohuz** [comment]
I'm having similiar issue with running ffmpeg in warp but succesful in mac's terminal. 
I got error:
```
zsh: abort      ffmpeg -f avfoundation -pix_fmt yuyv422 -video_size 640x480 -framerate 30 -i
```

**Comment by kevinyang372** [comment]
Closing this as this should be fixed in the latest version of Warp
