### ISSUE TITLE
When using honor PS1 settings, unable to copy the current prompt

### ISSUE THREAD

**Issue by robinmonjo** [warpdotdev/Warp#1249]
### Describe the bug

```text
Current prompt is not selectable (and hence can't be copied/pasted).
```

### To Reproduce

Steps to reproduce:
1. start a shell with "Honor user's custom prompt (PS1) setting" feature enabled
2. try to select the active prompt 
3. you can't 😥

### Expected behaviour

```text
The current prompt should be selectable
```

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment]
DUP: https://github.com/warpdotdev/Warp/issues/36
