### ISSUE TITLE
Can't output Arabic letters

### ISSUE THREAD

**Issue by mtbaqer** [warpdotdev/Warp#125]
**Describe the bug**
The console does not output Arabic letters. I can type them in, but any output even showing the inputted command does not show them. 

**To Reproduce**
1. use `echo سلام`
2. see how first line is only `echo` with nothing next to it and second line is empty space

**Expected behavior**
All Arabic letters should be shown correctly. Please note that this is a thing that many console apps get wrong, they either don't show it like Warm right now or show the letter in reverse like iTerm.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: MacOS 11.4

**Additional context**
I was using an app that was outputting Arabic letters and they weren't showing up.

**Comment by zachlloyd** [comment]
Thanks for the report. We haven't yet tested with RTL scripts so I'm not surprised we are doing this wrong.  Not sure on an ETA for a fix.

**Comment by elviskahoro** [comment]
We have support for this now. But not sure when it was added exactly. Sorry for following up so late @mtbaqer

**Comment by elmobark** [comment]
<img width="1680" alt="‏لقطة الشاشة ٢٠٢٣-٠٩-١٤ في ١ ٤٧ ٣٩ م" src="https://github.com/warpdotdev/Warp/assets/15808644/8c57ee54-d9c0-43ec-8cf7-525dc5dd297b">
maximize and minimize buttons not working right in RTL mode macOS too

**Comment by BSN4** [comment]
this is being fixed in PR #10809, before and after screenshots on the PR, tracking issue is #10355
