### ISSUE TITLE
Custom the AI suggestions input command keyboard shortcut

### ISSUE THREAD

**Issue by justchokingaround** [warpdotdev/Warp#1252]
### Discord username (optional)

chokerman#4418

### Describe the solution you'd like?

```text
I would like to have a setting where I can change the default AI suggestions input command keyboard shortcut, which is by default set to cmd + enter (this conflicts with skhd shortcut for opening a warp window)
```

**Comment by elviskahoro** [comment]
@justchokingaround Thanks for opening. We support changing the keybinding now. Check out keyboard shortcuts in the settings dialog.
<img width="846" alt="Screen Shot 2022-07-09 at 00 47 19" src="https://user-images.githubusercontent.com/29553206/178091999-c113f5e1-b0b9-4f59-8660-35bf265d1ac1.png">

**Comment by justchokingaround** [comment]
> @justchokingaround Thanks for opening. We support changing the keybinding now. Check out keyboard shortcuts in the settings dialog.
> <img width="846" alt="Screen Shot 2022-07-09 at 00 47 19" src="https://user-images.githubusercontent.com/29553206/178091999-c113f5e1-b0b9-4f59-8660-35bf265d1ac1.png">
> 

ty very mich :) 🙏
