### ISSUE TITLE
Terminal not updating directly when cmd-tabbing into Warp

### ISSUE THREAD

**Issue by juliusmarminge** [warpdotdev/Warp#1253]
### Describe the bug

```text
When having a background job (in my case a dev server and some tests running in watch mode), and cmd-tabbing from my editor into Warp, the terminal output does not update straight away. I have to click in the window to have the output outputted.

When I'm developing, I want to quickly tab Warp into view, check the tests, then tab my editor back in. Currently, I have to also click the Warp window before the test-results show up.
```

### To Reproduce

Steps to reproduce:
1. Open Warp
2. Start a job that you know will update the terminal output when you are not using Warp in the foreground, I use `npx jest --watch`. But the bug is reproducible with any command that should update when not using Warp.
3. Trigger the update, in my case this is done by saving the file I'm working in. The test runner will then restart the tests and the output is shown in the terminal window.
4. Wait a second or two, then CMD+TAB Warp into view. You will see that the terminal is frozen until you click in it.

### Expected behaviour

```text
I expect the output to be updated directly after tabbing the window into view.
```

### Screenshots

After tabbing Warp into view:
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/51714798/166290884-5c140574-9688-4668-9821-f7ac52930543.png">

After clicking:
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/51714798/166290835-12c894d8-840b-4e03-b351-70574a7c0164.png">

### Operating System

MacOS

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
Thanks for reporting! Will circle back once there are updates

**Comment by dannyneira** [comment]
@juliusmarminge We've made attempt to reproduce but have been unable to at this time. Are you still experiencing this issues in more recent versions of Warp?

**Comment by juliusmarminge** [comment]
> @juliusmarminge We've made attempt to reproduce but have been unable to at this time. Are you still experiencing this issues in more recent versions of Warp? 
> 
> 
> 
> 

Seems to be fine now 👍
