### ISSUE TITLE
Bring to front shortcut (Maybe an option on quake mode to use existing window)

### ISSUE THREAD

**Issue by dbpolito** [warpdotdev/Warp#1254]
### Describe the solution you'd like?

```text
Quake mode is great, but it creates a separate terminal.

I would love a similar feeling of Quake Mode but using the existing session, instead of using a separate one, so i could still cmd tab to that terminal, and not only be available on quake mode...
```

**Comment by henrykuzmick** [comment]
Same here.
Migrating from iTerm is annoying because of this. Would be great to be able to simply focus the existing window OR have quake mode like it is now, but be able to hide the other Warp window entirely. 

Otherwise there are always two terminals

**Comment by elviskahoro** [comment]
Thanks for reporting! Will update you when there's progress on this!

**Comment by acarl005** [comment]
Closing this issue since the feature was shipped. See #2585 for how to enable.
