### ISSUE TITLE
Can Tab Titles show repo instead of name handle

### ISSUE THREAD

**Issue by iKK001** [warpdotdev/Warp#1255]
### Describe the solution you'd like?

```text
Warp is great ! thank you very much.

I often use several Tabs open in Warp. Eeach Tab leading to a different git repository clone.

The idea:
Wouldn't it be great if each Tab title shows the name of the repo (or eventually the name of the branch) instead of the handle-name ?
```
![Screenshot 2022-05-02 at 19 36 43](https://user-images.githubusercontent.com/8404556/166297598-6ed1ce53-3c22-4371-9b35-e373bfd9b4b7.png)

**Comment by gagata** [comment]
Hey! Thanks for the feedback!

We have yet to publish a more detailed doc on the current state of tab titles, but the recent release has some changes that may help you out here:
- we adjusted the default tab titles (so you'll see the current directory vs seeing the user@hostname)
- for now, you can set the custom content using your rc files, for zsh it'll be something like that:
```function set_title () {
  window_title="\033]0;<HERE GOES YOUR DESIRED TITLE>\007"
  echo -ne "$window_title"
}

precmd_functions+=(set_title)```

**Comment by iKK001** [comment]
Thank you - unfortunately the function placement inside zshrc did not lead to the desired title change.

**Comment by gagata** [comment]
@iKK001 i tested your code and it doesn't work if you keep `window_title` and `echo` in the same line (it's not really a correct syntax)
try the below:
```
function set_title () {
  window_title="\033]0;MyTitle\007" 
  echo -ne "$window_title"
}
precmd_functions+=(set_title)
```

**Comment by iKK001** [comment]
Ah now it works, thank you very much - however now all the Tabs do have the same title all at once. Is there a way to give each Tab another title ?

**Comment by twyatt** [comment]
> Hey! Thanks for the feedback!
> 
> We have yet to publish a more detailed doc on the current state of tab titles, but the recent release has some changes that may help you out here:
> 
> * we adjusted the default tab titles (so you'll see the current directory vs seeing the user@hostname)
> * for now, you can set the custom content using your rc files, for zsh it'll be something like that:
> 
> ```
> function set_title () {
>   window_title="\033]0;<HERE GOES YOUR DESIRED TITLE>\007"
>   echo -ne "$window_title"
> }
> 
> precmd_functions+=(set_title)
> ```
> 
> let us know what you think!

@gagata this was working for me, but stopped working when I upgraded to Warp v0.2022.05.16.09.01.stable_01.

**Comment by gagata** [comment]
> 

hey, thanks for reporting. is there anything specific about your setup? i'm trying to repro on the same stable version, but for me it just works (here's my minimal `.zshrc` that i got for comparison: https://app.warp.dev/block/AxxFsqLwAv27psgwwcvkAn ). it consistently shows `MyTitle` in the tab.

**Comment by twyatt** [comment]
I tried using your example block in `.zshrc` and it worked, but does not work setting title from the prompt. Is that expected behavior?

In other words, I can set title via `.zshrc` but from the prompt, executing (for example) `DISABLE_AUTO_TITLE="true" echo -ne "\033]0;Test\007"` has no effect.

**Comment by gagata** [comment]
> I tried using your example block in `.zshrc` and it worked, but does not work setting title from the prompt. Is that expected behavior?
> 
> In other words: I can set title via `.zshrc`, but from the prompt, executing (for example) [the following](https://app.warp.dev/block/5V2viK0Vu8AqPVs6CXHsMR) as no effect:
> 
> ```shell
> DISABLE_AUTO_TITLE="true" echo -ne "\033]0;Test\007"
> ```

ah, got it - just to confirm, is your use case to set the specific title per tab (and not just once and for all tabs)? if so - the good news is that i'm working on adding a UI support for that (with keyboard shortcuts too), we should be able to release soon, after some ui polishing (so bear with us :) )

~anyways, without going into much detail here (i guess we just need to finally write tab renaming user doc...) it'll work per specific tab if you use... `WARP_DISABLE_AUTO_TITLE="true"` (instead of `DISABLE_AUTO_TITLE`).~
~overall, the `WARP_...` one disables our auto title, while the `DISABLE_AUTO_TITLE` is specific to ohmyzsh (which sets its own title, and we wanted to honor that too, with the options for users to opt-out of one and not the other, hence not reusing the env variable).~

I prepared the entire response, and realized that it works as described in bash but not in zsh, so investigating...

**Comment by twyatt** [comment]
> use... `WARP_DISABLE_AUTO_TITLE="true"` (instead of `DISABLE_AUTO_TITLE`).

@gagata thanks for the hint.

Changed my previous zsh function as follows, and everything works as expected for me now! 💯 

```diff
set_warp_title () {
- 	DISABLE_AUTO_TITLE="true"
+ 	export WARP_DISABLE_AUTO_TITLE="true"
	echo -ne "\033]0;$@\007"
}
