### ISSUE TITLE
2020-04-27升级后，远程连接异常

### ISSUE THREAD

**Issue by sdzywei** [warpdotdev/Warp#1256]
### Describe the bug

```text
warp_escape_json:19: command not found: sed
warp_escape_json:19: command not found: tr
warp_escape_json:19: command not found: sed
warp_escape_json:19: command not found: tr
warp_escape_json:19: command not found: sed
warp_escape_json:19: command not found: tr
warp_escape_dcs_json:1: command not found: xxd
warp_escape_dcs_json:1: command not found: tr
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Screenshots

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/17894131/166403456-555cffa4-bf13-4ac3-a543-3c845375551a.png">

### Operating System

MacOS

**Comment by kunish** [comment]
把设置里的Warp SSH Wrapper选项关掉再试试
Try again with Warp SSH Wrapper option turned off in settings

**Comment by sdzywei** [comment]
谢谢，可以了

**Comment by sdzywei** [comment]
把设置里的Warp SSH Wrapper关闭，历史提示就不能用了

**Comment by elviskahoro** [comment]
Gonna close this in favor of #1050
