### ISSUE TITLE
Keybinding "option+`" stop works after update to latest (v0.2022.04.25.09.59.stable_05) release

### ISSUE THREAD

**Issue by ramzzzay** [warpdotdev/Warp#1258]
### Discord username (optional)

RAMZAY (Антон)#3383

### Describe the bug

```text
I'm hitting the "option+`" and Warp quake mode not appears. On old version all works as expected.
```

### To Reproduce

Steps to reproduce:
1. Go to 'Settings'
2. Click on 'Feature'
3. Toggle 'Hotkey Window'
4. Set 'Keybinding' to option+`

### Expected behaviour

```text
After option+` Warp window should appears at screen
```

### Screenshots

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/5748239/166431642-5e17a217-509c-4cd7-8367-2b6ee234c409.png">

### Operating System

MacOS

### OS Version

12.3.1

**Comment by kevinyang372** [comment]
This should be fixed in the latest release!

**Comment by warpdotdev-dx** [comment]
v0.2022.05.02.09.00.stable_01
