### ISSUE TITLE
Remove misleading/false claim from warp.dev or make it real.

### ISSUE THREAD

**Issue by Bobronium** [warpdotdev/Warp#1263]
### Describe the bug

warp.dev contains misleading/false claim "All cloud features are opt-in.".

In fact, warp requires you to log in before you can use any features at all. 

I believe this contradicts the claim since having an account is a cloud feature in itself. And the explanation on why you require login contradicts with the claim even more:

>  Login serves two functions now. One is that we think there are features that require login in order to create a better user experience. We believe that the terminal is more powerful when you can share commands with teammates, generate commands using Open AI Codex, or run shared wikis directly in the terminal.
The other is to improve our product during beta because it makes it much easier to reach out and get feedback when something goes wrong.

You are basically forcing the user to use cloud features, yet claim otherwise.

### To Reproduce
1. Go to warp.dev
2. Scroll down a bit
3. See claim "All cloud features are opt-in."
4. Install warp
5. Launch to see a log-in wall

### Expected behaviour
warp.dev doesn't have false claims — either log-in should not be required to use non-cloud features or "All cloud features are opt-in." should be removed/rephrased.

Can't be both.

### Screenshots

<img width="574" alt="image" src="https://user-images.githubusercontent.com/36469655/166635476-af375998-2c77-4076-bae7-868c3c335d63.png">

**Comment by hanej** [comment]
This is insane.  Just found out about the telemetry data that is also being sent that cannot be disabled.  I'll stick with an honest developer/company for my terminal needs.  This has no place on my laptop.

**Comment by Bobronium** [comment]
@hanej, mind sharing your findings?

**Comment by hanej** [comment]
Besides the login wall reported here #900 and #1119, this issue is about the telemetry data #1131.

**Comment by tbennett6421** [comment]
I agree wholeheartedly. I as a user/dev was mislead by the home page not mentioning anything about requiring login. After installing and not being able to use to do forced login/telemetry, it was only then that I dug through the website and found this information not on the home page, but buried in the docs under the FAQs.

This feels morally wrong to mislead users by promoting on the front page opt-in, and have no mention whatsoever that there is a forced login to even use the application.

Therefore, even as interested as I am, I uninstalled and will not support this until changes have been made.

**Comment by kuthair** [comment]
Yep.. this is a non-starter for me.

Warp looks cool! Too bad -- I'll never know.

I don't need or want, yet, another login. What for?

**Comment by elviskahoro** [comment]
Thanks for the feedback.

Will work on making it more clear on the website.


Also, we updated the docs with the how the team is currently thinking about all this!
Please check it out!
https://docs.warp.dev/getting-started/privacy


I'm gonna close this in favor of #900, so that the conversation is all in one thread.

Will share any changes to login and telemetry there.
