### ISSUE TITLE
Hotkey does not work with `⌘+esc`

### ISSUE THREAD

**Issue by ivanbanov** [warpdotdev/Warp#1265]
### Discord username (optional)

ivanbanov#1069

### Describe the bug

The hotkey feature is not working anymore, not sure when it stopped working, my current version is `v0.2022.04.25.09.59.stable_05`

Another issue that Im facing is the shortcut configuration, on iTerm I used to have the following `⌘+esc`, but it seems like Warp does not allow to this combination

### Operating System

MacOS 11.6

**Comment by kevinyang372** [comment]
`CMD-ESC` is a system keybinding and unfortunately warp does not support overriding system keybinding yet.

For the regression on old keybindings, this should be fixed in the latest release. Is the error still occurring to you after updating?
