### ISSUE TITLE
Support for theming

### ISSUE THREAD

**Issue by neeravp** [warpdotdev/warp#127]
**Is your feature request related to a problem? Please describe.**
Blocks is a super nice pattern to have in terminal.

The output and background colours make the appearance unpleasant, especially when being used to some themes of oh-my-zsh with custom background colour & theme on iTerm2

**Describe the solution you'd like**
Would love to have support for themes like oh-my-zsh and background colour and transparency customisation like iTerm2.

**Additional context**
Terminal is a very important and large part of a devs life so having a pleasant looking terminal with customisation ability to suit personal preferences would be a great addition.

**Comment by zachlloyd** [comment]
This is in the works!  If you check out the feature-requests channel in our discord you can see some previews:

https://drive.google.com/file/d/1DlYIeuUR71QG7I9mhmUBbHWNF1ERmJcB/view?usp=sharing

**Comment by neeravp** [comment]
That's great. Thank you for reminding about the discord channel. Am excited and look forward for it to be integrated & available. 

Appreciate the thoughtfulness behind the design, especially blocks - it's a game changer for me. Thank the entire team.

**Comment by richardbagshaw** [comment]
this looks great, can't wait to be able to change some small things like fonts and line heights etc

**Comment by zachlloyd** [comment]
Font support coming next week I think #9 

Also, you can change line heights now in a rudimentary way using File > Compact Mode if that helps at all!

**Comment by gagata** [comment]
Closing, as this has been implemented already!
