### ISSUE TITLE
Multiline Support

### ISSUE THREAD

**Issue by AdiAyyakad** [warpdotdev/Warp#1270]
### Describe the bug

```text
When trying to create a multiline string, Warp doesn't scroll to show all content so I have to type blind.
```

### To Reproduce

Steps to reproduce:
1. Go to the prompt
2. Type echo 'Hello
4. Click enter three times

### Screenshots

![Screen Recording 2022-05-04 at 4 19 01 PM](https://user-images.githubusercontent.com/901668/166819260-ee59a049-2bdb-4a3d-b9a3-3ce60c8de72e.gif)

### Operating System

MacOS

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
@AdiAyyakad thanks for originally reporting. Is this still happenign to you? I can't repro this

**Comment by AdiAyyakad** [comment]
Nope looks fixed on my latest! Closing thanks!
