### ISSUE TITLE
Enabling icons for exa in warp

### ISSUE THREAD

**Issue by pulanski** [warpdotdev/Warp#1272]
### Discord username (optional)

Josh#6406

### Describe the solution you'd like?

```text
One tool that I discovered in the last year or so has been exa (modern replacement for ls), and ever since landing upon it I've been in love. One of the primary features of exa that I appreciate is its ability to provide icons on display. As of writing this, I have tested warp's interoperability with exa on two machines and both weren't able to have icons displaying. I was wondering if this functionality could be added to the terminal.
```

### Is your feature request related to a problem? Please describe.

```text
Unable to display icons in exa.
```

**Comment by twyatt** [comment]
@pulanski you should be able to get icons to work w/ `exa` if you [change to a font that contains the needed glyphs](https://the.exa.website/features/icons).

For example, I am using **Hack Nerd Font** (as found [here](https://www.nerdfonts.com/font-downloads)) and icons are showing up for me:

```
brew tap homebrew/cask-fonts && brew install --cask font-hack-nerd-font
```

**Comment by pulanski** [comment]
I do have the fonts installed. They work fine in other terminals (i.e. alacritty, iTerm2, VSCode's integrated terminal). My issue however is that I can't even get the general icons to display in warp as seen in the picture below.


<img width="855" alt="Screen Shot 2022-05-24 at 4 22 30 PM" src="https://user-images.githubusercontent.com/63331369/170125384-0fb5150e-08b9-4f63-917b-e5eb5fb7e62f.png">


 I was wondering if anyone else is having a similar issue. Here's an image showing the desired functionality working in VSCode's integrated terminal.


<img width="707" alt="Screen Shot 2022-05-24 at 4 25 16 PM" src="https://user-images.githubusercontent.com/63331369/170125695-ea7913c7-9f61-4180-8a1d-73dbf9b107dd.png">

**Comment by twyatt** [comment]
My Warp (v0.2022.05.16.09.01.stable_01):

![Screen Shot 2022-05-24 at 1 29 14 PM](https://user-images.githubusercontent.com/98017/170126371-866d57cc-1fc0-4dd8-a344-b4f81ea9ffff.png)

Configured with the following font settings:

![Screen Shot 2022-05-24 at 1 29 57 PM](https://user-images.githubusercontent.com/98017/170126934-a39bfe85-a083-4026-adc2-c9f299604857.png)

```zsh
exa --version

exa - list files on the command-line
v0.10.1 [+git]
https://the.exa.website/
```

**Comment by elviskahoro** [comment]
Thanks for opening. Gonna close this in favor of #789 as a fallback font that does support the glyphs should fix it

**Comment by Vatsalvinit-17** [comment]
How to import Hack nerd Font in warp, there is no options there
