### ISSUE TITLE
htop, window shake and unknown characters

### ISSUE THREAD

**Issue by doroved** [warpdotdev/Warp#1273]
### Describe the bug

```text
After connecting to the server via ssh, opening htop and abruptly moving the application window, htop crashes and unknown characters are inserted in the input field.
```

### To Reproduce

Please see my screen recording...

### Expected behaviour

```text
I expect that htop will not crash and unknown characters will not appear )
```

### Screenshots

I recorded a video screenshot of the problem, you can watch it on YouTube, because it exceeds the size of the githab

https://youtu.be/-0H6Zrdjhyo

### Operating System

MacOS

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
@doroved Thanks for opening this gonna close in favor of:
#607 

The htop bug is wicked, it happens even when you're not in SSH
