### ISSUE TITLE
Chinese input method keyboard can not follow up

### ISSUE THREAD

**Issue by laipaang** [warpdotdev/Warp#1275]
### Describe the bug

```text
Chinese input method keyboard can not follow up
```

### To Reproduce

Steps to reproduce:
1. Open Warp
2. Switch input method to Chinese
3. Enter Chinese characters
4. Chinese characters are not displayed properly

### Expected behaviour

```text
Chinese characters are displayed properly
```

### Operating System

MacOS

### OS Version

11.4

**Comment by nfwyst** [comment]
plus one, thats not a good user experience

**Comment by dev4joel** [comment]
Can you please comment here instead:
GitHub issue for expanding support for international input sources: [#783](https://github.com/warpdotdev/Warp/issues/783)

**Comment by elviskahoro** [comment]
These should be fixed. If not can you share a video, I might be misunderstanding the request.
