### ISSUE TITLE
Options / Setting window cut of in Hotkey (quake) mode

### ISSUE THREAD

**Issue by wutzi15** [warpdotdev/Warp#1277]
### Discord username (optional)

wutzi#1545

### Describe the bug

```text
When opening the options `cmd+ ,` in the the hotkey (quake) mode, the options window is cut of.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```text
The options window should be its own window and not appear in the termial which has only 30% screen height by default
```

### Screenshots

<img width="1668" alt="Bildschirmfoto 2022-05-05 um 08 56 22" src="https://user-images.githubusercontent.com/674868/166875812-bba06956-0ca1-46de-abfc-f2228c75a2b3.png">

### Operating System

MacOS

### OS Version

12.3.1

### Additional context

```text
Warp v.2022.05.02.09.00.stable_01
```

**Comment by elviskahoro** [comment]
Thanks for opening! Gonna close this in favor of #366
