### ISSUE TITLE
Warp is on top of spotlight

### ISSUE THREAD

**Issue by wutzi15** [warpdotdev/Warp#1278]
### Discord username (optional)

wutzi#1545

### Describe the bug

```text
When running in hotkey (quake) mode and opening spotligt `cmd + space` the warp window is on top of the spotlight search.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```text
The spotlight search window should have precedence and always appear on top.
```

### Operating System

MacOS

### OS Version

12.3.1

### Additional context

```text
Warp v.0.2022.05.02.09.00.stable_1
```

**Comment by kayleg** [comment]
It's not just Spotlight but really any window that also draws with `always on top`.

Which makes accessing something like Dash for documentation reference unusable.
