### ISSUE TITLE
Make the version string in warps setting copyable

### ISSUE THREAD

**Issue by wutzi15** [warpdotdev/Warp#1279]
### Discord username (optional)

wutzi#1545

### Describe the solution you'd like?

```text
When filing bug reports and feature requests it helps to add the precise version string of warp. Currently one has to type it by hand and it is rather long so prone to errors. This could be avoided by making it selectable and copyable or adding a "copy to clipboard" button.
```

**Comment by kevinyang372** [comment]
@wutzi15 You could copy the version from the dropdown menu on top right corner of the app!
<img width="339" alt="image" src="https://user-images.githubusercontent.com/30107576/167653486-fc102370-e1c0-4c52-b921-f7e6809d0d1c.png">
