### ISSUE TITLE
DUP: Duplicate of #069 - Drag files and folders into terminal to get the path

### ISSUE THREAD

**Issue by Smith-Chris1** [warpdotdev/warp#128]
**Is your feature request related to a problem? Please describe.**
I can't drag a file/folder into the terminal window.

**Describe the solution you'd like**
I must have this functionality: Grab a folder or file in an open Finder window, and drag it to the terminal to get a direct path to the file/folder

**Additional context**

**Comment by zheng** [comment]
Hello! Thanks for reporting - we agree this functionality should be available in Warp. Closing since it is a dup of #69.

**Comment by elviskahoro** [comment]
Linking:
- #069

**Comment by elviskahoro** [comment]
v0.2021.11.16.20.05.stable_01
