### ISSUE TITLE
terminal Unable to display last line

### ISSUE THREAD

**Issue by zhangyiming748** [warpdotdev/Warp#1280]
### Discord username (optional)

zen

### Describe the bug

```text
When I execute the command, no matter how I scroll down, the last line of the command cannot be displayed. Only after the latest line appears, can I fully see the output information of the previous line
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Screenshots

[![Oed1jx.png](https://s1.ax1x.com/2022/05/05/Oed1jx.png)](https://imgtu.com/i/Oed1jx)

### Operating System

MacOS

### OS Version

12.3.1

**Comment by zheng** [comment]
Sorry for the issue. There's a fix in the release coming out today!
