### ISSUE TITLE
Tab switching hotkey does not work

### ISSUE THREAD

**Issue by wutzi15** [warpdotdev/Warp#1282]
### Discord username (optional)

wutzi#1545

### Describe the bug

```text
I've bound the active next/previous tab to `cmd + left/right arrow` on the german keyboard, but it does not work.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Operating System

MacOS

### OS Version

12.3.1

### Additional context

```text
Warp v2022.05.02.09.00.stable_1
```

**Comment by jmnavarro** [comment]
Same for Spanish keyboard, really annoying bug

**Comment by elviskahoro** [comment]
Thanks for opening! Gonna close this in favor of #341
