### ISSUE TITLE
Re-focusing Warp app doesn't select clicked pane

### ISSUE THREAD

**Issue by martynchamberlin** [warpdotdev/Warp#1286]
### Describe the bug

```text
Loving warp so far! Just one thing I'm really noticing, coming from iTerm2. If you have multiple (split) panes and you blur the Warp app, when you refocus the app by clicking on a pane, that pane doesn't become selected; the previously selected pane is retained. It would be nice if the focus click selects the clicked pane.
```

### To Reproduce

Steps to reproduce:
- Have a split screen (i.e. 2 panes) on a Warp window. Select the first pane. 
- Blur Warp app
- Refocus Warp by clicking on the second pane. 
- **Bug**: The first pane is still the selected one

### Expected behaviour

```text
- Expected: The second pane is the one selected
```

### Operating System

MacOS

### OS Version

12.3.1

**Comment by kaplanoah** [comment]
I just came here to post this. Warp not focusing on the pane I click on causes me tons of extra clicks and unexpected behavior throughout the day.

**Comment by elviskahoro** [comment]
DUP: https://github.com/warpdotdev/Warp/issues/739
