### ISSUE TITLE
Ability to customize the WARP prompt

### ISSUE THREAD

**Issue by ctwise** [warpdotdev/Warp#1287]
### Describe the solution you'd like?

```text
Instead of switching to a custom prompt, I would like to be able to customize the WARP prompt instead. That custom Warp prompt should be consistent regardless if I'm in a Bash, ZSH or Fish shell. Things I might put in there: python environment, kubernetes context, aws profile, etc. This Warp-prompt customization should include the ability to customize the existing prompt.
```

**Comment by gagata** [comment]
Hey! Thanks for the feedback!

We've thought of that a bit already - you can find some of our mocks and more info about what we called "Context Chips" in this twitter thread: https://twitter.com/warpdotdev/status/1496263490491023362

There's no official ETA on us implementing it just yet, we'll update once we have a more concrete estimates on that. Feel free to let us know what you think about the context chips designs though :)

**Comment by ctwise** [comment]
Looks great! Especially if the plugin stuff is there at the same time. Please make it trivial to create a _simple_ "context chip" so anyone can toss one off.

**Comment by elviskahoro** [comment]
We should make a github discussion for context chips. Gonna close this. Will update this thread though when it comes out
