### ISSUE TITLE
Snackbar remains visible for TUI programs over SSH in Bash

### ISSUE THREAD

**Issue by nelson137** [warpdotdev/Warp#1288]
### Describe the bug

```text
For TUI programs that take over the full terminal screen (ncurses-like) on my local machine the snackbar that jumps to the top of the command block is not visible. However, when the same command is run remotely over SSH in a bash shell, the snackbar is visible and does not go away.
```

### To Reproduce

Steps to reproduce:
1. ssh into a machine where the login shell is bash
2. Run vim, htop, tmux, or any other TUI program
3. See the snackbar at the top center of the screen

### Expected behaviour

```text
The snackbar should not be visible in TUI applications because it may cover content.
```

### Screenshots

<details><summary>Images</summary>

<br />

**Vim on my local machine (no snackbar):**
<img width="600" alt="Screen Shot 2022-05-05 at 11 36 03 AM" src="https://user-images.githubusercontent.com/25290530/166970829-44b0841b-c9b9-40ee-9dda-a2f16c002057.png">

**Vim on remote machine (with snackbar):**
<img width="600" alt="Screen Shot 2022-05-05 at 11 36 40 AM" src="https://user-images.githubusercontent.com/25290530/166970923-952600e5-059a-47f1-95fe-102b0322df0c.png">

</details>

### Operating System

MacOS

### OS Version

12.3.1

### Additional context

```text
A workaround for this problem is to start a zsh shell on the remote machine. The snackbar behavior is correct when the shell is zsh.

I have no control over the login shell for my user on the remote machine so I tried adding some logic to my bashrc to `exec zsh` but this just completely breaks Warp. The "Starting shell..." message at the bottom of the screen doesn't go away and any new command output only appears within the bottom-most code block. Even exiting from the ssh session doesn't seem to fix it, the tab must be closed.
```

**Comment by elviskahoro** [comment]
Thanks for opening
Gonna close this in favor: #8
