### ISSUE TITLE
Tab name disappears when SSH-ing into server

### ISSUE THREAD

**Issue by JosephTLyons** [warpdotdev/Warp#1289]
### Describe the bug

```text
I added a tab and ssh'ed into a server at work.  The tab name disappeared as soon as the password went through:
```

### Screenshots

![SCR-20220505-l8m](https://user-images.githubusercontent.com/19867440/167009742-c853f489-ef3c-481d-a647-90eaf580c963.jpeg)

### Operating System

MacOS

### OS Version

12.3.1

**Comment by gagata** [comment]
thanks for the report! taking a look...

**Comment by elviskahoro** [comment]
This has been fixed! Sorry for the delay!
