### ISSUE TITLE
Moving to #434 - Kubernetes - `kubectl`

### ISSUE THREAD

**Issue by zheng** [warpdotdev/Warp#129]
Requested by harshthakur in Discord.

**Comment by joscdk** [comment]
Would like to add to this, for example by adding something like kube-ps1, so being able to show current K8s context and namespace just like git info.

Kube-ps1: https://github.com/jonmosco/kube-ps1

**Comment by elviskahoro** [comment]
Moving this into #434

**Comment by elviskahoro** [comment]
@joscdk @uhinze 

Gonna move this into #434

**Comment by elviskahoro** [comment]
@joscdk @uhinze 
Actually #652 instead!
