### ISSUE TITLE
Arrow Up doesn't show the last command

### ISSUE THREAD

**Issue by emadb** [warpdotdev/Warp#1293]
### Discord username (optional)

emadb

### Describe the bug

```text
When arrow-up is pressed the last command should appear first in the popup so that users can easily repeat the last issued command.
Now the pop up shows a list of the last N-1 command (non the the last one).
```

### To Reproduce

Steps to reproduce:
1. Go to a folder
2. Type `ls`
3. Press arrow-up
4. The popup does not present the `ls` command

### Expected behaviour

```text
The popup should present the last command (`ls` in the example above)
```

### Screenshots

First command:
<img width="378" alt="Screenshot 2022-05-06 at 07 38 17" src="https://user-images.githubusercontent.com/276876/167073478-f50daf21-bd77-43fe-b7c9-0cf98314d48e.png">
Arrow up
<img width="378" alt="Screenshot 2022-05-06 at 07 38 33" src="https://user-images.githubusercontent.com/276876/167073490-21ee088f-0ded-4a8c-8cce-f43af9982131.png">

### Operating System

MacOS

### OS Version

12.3.1

### Additional context

I'm using the fish shell.

**Comment by emadb** [comment]
Update on this.
Seems that the problem is in the custom prompt configuration. I'm using starship and the `right_prompt` is causing this glitch.
This is my starship configuration:
```
format = "$directory$git_branch$git_state$git_status$cmd_duration$character"

right_format = """$time"""

add_newline = true

[time]
disabled = false
format = "[$time](bright-black)"
time_format = "%T"
utc_time_offset = "+2"

[directory]
style = "blue"
truncation_length = 1000
truncation_symbol = "…/"
truncate_to_repo = false

[line_break]
disabled = true

[character]
format = "$symbol "
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[( *$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
```

**Comment by marhaupe** [comment]
I'm actually having the same problem on a fresh install of Warp. How has this issue been resolved? Is this worth reopening or is there a fix on user side?

**Comment by fekete965** [comment]
I think this issue should be re-opened. I am having this issue as well and it is very annoying and slows my work down since I have to manually type in long commands because warp doesn't remember the last command constantly...
I don't want 3-4 more keystrokes, type my long command again or use my touchpad/mouse to copy the my long command just because I made a typo etc... 😭 

I am very much at a phase to switch back to the primary terminal on mac just because of this.
I love the whole style and tools that warp provides, but this feature really slows down productivity.

If anybody has a solution for this please let us know, I couldn't find anything regarding this functionality in the terminal's config.

**Comment by aidan-melen** [comment]
I toggled off and on the `Toggle Autosuggestions` and the `UP` arrow is now giving me the last terminal command instead of some seemingly arbitrary command from history.

**Comment by aidan-melen** [comment]
It looks like the up arrow maps to `history` by default and not last command. pretty annoying.

**Comment by korczas** [comment]
I am using zsh with some plugins. Turning off them in .zshrc file fixed the issue
```
  # plugins=(git tmux common-aliases z zsh-autosuggestions zsh-syntax-highlighting alias-tips brew asdf)
  plugins=(git brew asdf)
```
