### ISSUE TITLE
Fish abbreviations (abbr) do not expand

### ISSUE THREAD

**Issue by omninonsense** [warpdotdev/Warp#1295]
### Discord username (optional)

nino#9000

### Describe the bug

Fish abbreviations ([`abbr`](https://fishshell.com/docs/current/cmds/abbr.html)) do not expand when part of a multi-word call

### To Reproduce

Steps to reproduce:
1. Create abbreviation: `abbr -a k kubectl`
2. Try to use `k get pods` as a command/alias
3. See error `fish: Unknown command: k`

Interestingly, it works with just `k` (the abbreviation on its own).

I speculate it might be a weird interaction with how fish "edits" the buffer as the user types, which it no longer has access to now that there's an editor in front of that.

### Expected behaviour

Abbreviations continue to work as before:

- `k` would expand to `kubectl`
- `k get pods` would expand to `kubectl get pods`

### Operating System

MacOS

### OS Version

12.3.1

### Warp Internal (ignore): linear-label:24888f54-df93-45d5-9bdd-e38f740cac19

Ignore

**Comment by sophiabrandt** [comment]
I think this is the same as https://github.com/warpdotdev/Warp/issues/852

**Comment by omninonsense** [comment]
Thanks noticing, @sophiabrandt! I'll close this issue in favour of the more active one.
