### ISSUE TITLE
Global hotkey stop working

### ISSUE THREAD

**Issue by zxch3n** [warpdotdev/Warp#1302]
### Describe the bug

- version: 2022.05.02.90.00.stable_01
- OS: macOS Monterey 12.3.1

The keybinding setting in `Hotkey Window` is not working.

**Comment by Gavinchen92** [comment]
+ 1

**Comment by iyu98** [comment]
I have the same problem.

### Operating System
macOS Monterey 12.3.1
Inter Core i5
