### ISSUE TITLE
Will Windows and Linux be supported in the future?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [warpdotdev/Warp#1303]
### Describe the solution you'd like?

```text
Will Windows and Linux be supported in the future?
```

**Comment by dev4joel** [comment]
Please upvote / follow those issues!
https://github.com/warpdotdev/Warp/issues/204
https://github.com/warpdotdev/Warp/issues/120

**Comment by adamdicarlo** [comment]
Can't upvote on locked issues. See https://github.com/warpdotdev/Warp/issues/1389
