### ISSUE TITLE
Why i cant sign up,Through i try it too many times!!!!!!!

### ISSUE THREAD

**Issue by Three-fire** [warpdotdev/Warp#1304]
### Describe the bug

```text
When i click it, it pop up this
```

### Screenshots

<img width="815" alt="截屏2022-05-07 下午10 27 07" src="https://user-images.githubusercontent.com/56632599/167258642-5906a722-bc30-4791-b2a6-1c98541ecb73.png">

### Operating System

MacOS

**Comment by dev4joel** [comment]
How to Troubleshooting Login Issues is here :
- 👉 [Troubleshooting Login Issues](https://docs.warp.dev/help/troubleshooting-login-issues)

How to fix the confusing login flow issue is here:
- 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)

How to fix the proxy issue is here:
- 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by alokedesai** [comment]
@Three-fire sorry for the issues! Do you see anything printed in the console when you see this error message?

**Comment by alokedesai** [comment]
@Three-fire friendly ping on this! Would love to make sure your login issues get resolved if you are still experiencing it

**Comment by Three-fire** [comment]
> @alokedesai  sorry for not a getting back to u in time,i have solved this problem and used this product! That Warp is a good product, thank for ur asking

**Comment by alokedesai** [comment]
@Three-fire Glad to hear! what was the issue out of curiosity?

**Comment by Three-fire** [comment]
@alokedesai I forgot to turn off the network agent,it was my fault = =
