### ISSUE TITLE
Warp loses parts of text written while executing previous command

### ISSUE THREAD

**Issue by vasimi** [warpdotdev/Warp#1312]
### Describe the bug

```text
Hi,
I've encountered a very annoying issue. When I execute a command (like `git pull`) and start writing the next command (like `git checkout -b awesome_branch`) while the previous one is being executed, some parts of the text I already wrote (especially spaces) simply dissapears.
```

### To Reproduce

Steps to reproduce:
1. Execute a command
2. Start writing the next one while the previous runs
3. Be upset because a space disappeared

### Expected behaviour

```text
Keep all the text that's written while executing the previous command.
```

### Screenshots

<img width="416" alt="Snímek obrazovky 2022-05-08 v 15 52 43" src="https://user-images.githubusercontent.com/9162439/167299536-d8ee5d54-2315-45c7-8b51-fc8bb72b10a7.png">
(I wrote `git pull origin`, however, only `git pullorigin` is present in the input)

### Operating System

MacOS

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
Team shipped a fix for this. So this should be working now. @vasimi can you let me know if this still happens and I'll reopen.

**Comment by vasimi** [comment]
Seems fixed, thanks!
