### ISSUE TITLE
Black frozen window using k9s

### ISSUE THREAD

**Issue by azamora-zsc** [warpdotdev/Warp#1315]
### Describe the bug

```text
I'm using warp version v0.2022.05.02.09.00.stable_01 and k9s version v0.25.12. The issue is pretty annoying as it makes me waste a lot of time. 
The matter is that when I go into a pod and start a shell session in a container (pressing s) everything works just well until I execute exit to get out of the container. At this moment, the window gets unresponsive, without showing the k9s interface again, only a black empty space. To continue working, this window has to be closed and start a new one, executing k9s and the same process again.
```

### To Reproduce

Steps to reproduce:
1- Execute k9s
2- To inside any pod.
3- Select one container and press "s".
4- Execute "exit" command
5- The window will become unresponsive.

### Expected behaviour

```text
After exiting from inside a container, the window should show the containers in the current pod again.
```

### Operating System

MacOS

**Comment by azamora-zsc** [comment]
I forgot to mention that the same happens when I edit a resource (deployment, ConfigMap, etc) and exit the editor (vim)

**Comment by vlameiras** [comment]
I have the exact same issue

**Comment by derlin** [comment]
I see the exact same behaviour. This is a real blocker for me !

**Comment by elviskahoro** [comment]
Will circle back when there are updates!

**Comment by AndrzejOlender** [comment]
I have the same problem, only because of this Bug I don't have Warp as default terminal

**Comment by igoooor** [comment]
> I have the same problem, only because of this Bug I don't have Warp as default terminal

yep same reason

**Comment by dannyneira** [comment]
Hi all, sorry about this issue, we know this is a huge blocker for many so we appreciate your patience.

Closing as duplicate, please +1 and track this issue there > https://github.com/warpdotdev/Warp/issues/833

**Comment by dannyneira** [comment]
Hi all, sorry about this issue, we know this is a huge blocker for many so we appreciate your patience.

Closing as duplicate, please +1 and track this issue there > https://github.com/warpdotdev/Warp/issues/833

**Comment by szgupta** [comment]
Hey folks, sorry for resurrecting such an old issue but I've been investigating [removing the padding from the alt-screen](https://github.com/warpdotdev/Warp/issues/2373) and I want to make sure I am not regressing how Warp works with k9s. Would any of you be willing to test out k9s on a build that doesn't have alt-screen padding? If so, please email me at suraj@warp.dev. Much appreciated!
