### ISSUE TITLE
Warp light

### ISSUE THREAD

**Issue by constantskeptic** [warpdotdev/Warp#1318]
### Describe the solution you'd like?

```text
I just want an iTerm replacement that is super fast, configurable, and with a portable config I can import on different machines. All of the extra crap provided by these features are not helpful, add to cognitive load in the form of yet-another-wrapper-command I need to learn that pulls away further from core unix values. Just give me a warp lite.
```

**Comment by elviskahoro** [comment]
@constantskeptic You should try Alacritty I think it's what you're looking for.

**Comment by elviskahoro** [comment]
Can you elaborate on this a bit more:
"add to cognitive load in the form of yet-another-wrapper-command I need to learn that pulls away further from core unix values."

It will help me figure out what's creating friction.
