### ISSUE TITLE
My ZSH theme (managed by oh-my-zsh) ignored

### ISSUE THREAD

**Issue by acarl005** [warpdotdev/Warp#1319]
### Describe the bug

I'm using ZSH as my default shell. I also have [oh-my-zsh](https://ohmyz.sh/) installed, which allows my to pick some themes for my prompt by configuring an env variable, e.g. `ZSH_THEME="powerlevel10k/powerlevel10k"`.

I am using the romkatv/powerlevel10k theme. However, it seems that this config is getting ignored. I'm ending up with a default ZSH prompt. See screenshot for comparison with my other terminal emulators.

### To Reproduce

1. Use ZSH
2. [Install oh-my-zsh](https://ohmyz.sh/#install)
3. [Install powerlevel10k](https://github.com/romkatv/powerlevel10k#oh-my-zsh)
4. Set `ZSH_THEME="powerlevel10k/powerlevel10k"` in `~/.zshrc`
5. open new terminal session

### Expected behaviour

The powerlevel10k theme should be respected

### Screenshots

![Screen Shot 2022-05-09 at 3 45 09 PM](https://user-images.githubusercontent.com/8334252/167487412-10675b91-2643-40fd-ae35-f8869d642baf.png)

Warp vs iTerm2 vs included MacOS Terminal.app

### Operating System

MacOS

### OS Version

Monterey 12.3.1 (21E258)

### Aside

BTW, this app is **freaking awesome** and I'm using it as my main terminal app. Well done! Truly a 21st-century experience. Also very glad it isn't another Electron app. Hats off to you sir(s)/ma'am(s).

**Comment by imjoaq** [comment]
I Have the same issue, using ZSH and Oh my Zsh! but still getting the default Zsh Theme. 

MacOS default terminal and iterm2 change every time I switch themes

![Screen Shot 2022-05-12 at 1 10 16 AM](https://user-images.githubusercontent.com/44004184/167996672-aee7d899-2e7a-45b0-abf9-52ee746dafc2.png)

**Comment by sirmong** [comment]
@imjoaq many thanks!

**Comment by acarl005** [comment]
This didn't work for me. I enabled "honor user's custom prompt (PS1) setting" and it goes back to the Zsh default prompt, and for some reason my `PS1` is empty....

<img width="551" alt="Screen Shot 2022-05-13 at 12 21 36 PM" src="https://user-images.githubusercontent.com/8334252/168326125-3c868b77-8b1f-4e74-9d07-21a1368b2f36.png">

In other terminals my `PS1` is properly set.

<img width="1753" alt="Screen Shot 2022-05-13 at 12 21 58 PM" src="https://user-images.githubusercontent.com/8334252/168326230-63aea5ee-a47c-4ac2-8d34-53f59ed6ab69.png">

**Comment by elviskahoro** [comment]
@acarl005 Check out the prompt section of our documentation. We don't support P10K and likely won't. We explain more here: https://docs.warp.dev/features/prompt#powerlevel10k-p10k

**Comment by acarl005** [comment]
@elviskahoro Thanks for answering. I'll choose another theme for now. I'm curious.. if one felt motivated to update p10k to more easily work with Warp, how would they do that?

**Comment by elviskahoro** [comment]
@acarl005 Sorry for the delay. I'm not sure tbh I usually just recommend starship. We try to parse the Prompt variable. I think it would be hard unless we open source since the parser could change without you knowing.
