### ISSUE TITLE
Ability to specify / change / configure warp to use different shell from system default.

### ISSUE THREAD

**Issue by imumesh18** [warpdotdev/Warp#132]
**Is your feature request related to a problem? Please describe.**
warp currently picks up default shell set on the system. It should have an option to specify non default shell in settings so that without changing the system shell I can continue to use a different shell(bash).

**Describe the solution you'd like**
Give a setting similar to iterm2 where I can specify which shell should it pickup.
![image](https://user-images.githubusercontent.com/23421535/130120023-0f5eaa47-6b45-4e67-95bb-7cfd0a9bc441.png)

**Additional context**
NA

**Comment by federico-pi** [comment]
I'm waiting for this issue to be solved before transitioning from iTerm, is this being worked on?

**Comment by jorpilo** [comment]
Any update on this? Please, this is a deal breaker as I do not want to change my default shell from POSIX-compatible due to compatibility issues but I mostly run fish or nushell in my terminal

**Comment by onehundredfeet** [comment]
Running on a Mac M1, I would really appreciate this feature.  I want to be able to specify one shell for arm and one for intel.

**Comment by dannyneira** [comment]
Hey Folks, @imumesh18 Warp now allows you to specify the shell to use in `Settings > Features > Session`

You can choose between default, zsh, bash, or custom in the ["Startup shell for new sessions" dropdown](https://docs.warp.dev/getting-started/using-warp-with-shells#changing-default-shell).

![CleanShot 2023-03-22 at 16 16 00](https://user-images.githubusercontent.com/16809145/227051006-7b69953e-8a85-4896-adb0-e63626321ab4.png)

I hope this fulfills your request and use case! Closing as completed but please let us know if any issues.
