### ISSUE TITLE
Need to mouse click to refocus after quitting program.

### ISSUE THREAD

**Issue by adambeck7** [warpdotdev/Warp#1320]
### Describe the bug

```text
When I quit a program with `control + c` it doesn't refocus on the command line like every other terminal does. I have to mouse click to set the focus. I frequently quit, then up arrow, then enter to kill and restart a local server easily.
```

### To Reproduce

Steps to reproduce:
1. Go to the command line and run a local web server. 
2. Use `control + c` to quit. 
3. Try to type or use up arrows without using the mouse. 

### Expected behaviour

```text
Once a program is quit, refocus on the command line, not the text box above it.
```

### Screenshots

![warpIssue](https://user-images.githubusercontent.com/18033909/167494275-d7279286-2a5d-4a3d-bf3d-1eb21f1b7fcf.gif)

### Operating System

MacOS

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
@adambeck7 is this still happening to you? I think it was fixed but want to confirm

**Comment by adambeck7** [comment]
@elviskahoro can confim. Thank you!
