### ISSUE TITLE
issue with scroll

### ISSUE THREAD

**Issue by igorkasyanchuk** [warpdotdev/Warp#1326]
### Describe the bug

```text
When executing some commands like `rails s` (starting ruby on rails app) I can't see output from it.

It makes the terminal completely unusable.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Screenshots

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/11101/167695673-f09997cb-0a68-4a05-be5a-7280cd53f30f.png">

**Comment by elviskahoro** [comment]
This should be fixed now! Apologies for the delay!
