### ISSUE TITLE
When I use Django's interpreter, I can't use option+LEFT to move the cursor

### ISSUE THREAD

**Issue by owenbrownzc** [warpdotdev/Warp#1327]
### Discord username (optional)

Dis who?

### Local Shell and Version

zsh 5.8

### Remote Shell and Version

4.4.20(1)-release

### Operating System and Version

Mac 0S 12.3.1

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

When I use Django's interpreter, I can't use option+LEFT to move the cursor
Note that I'm shelled into a Docker image, which isn't maybe the exact same thing as SSH.

### Include shell xtrace output

I'm not using SSH exactly.
I use 
docker exec -it  CONTAINER_NAME_HERE  /bin/bash

**Comment by elviskahoro** [comment]
Thanks for reporting! I think this is related to #259
