### ISSUE TITLE
Escape not working in keyboard shortcuts settings tab

### ISSUE THREAD

**Issue by ericvrp** [warpdotdev/Warp#1330]
### Describe the bug

```text
Escape key is working in all tabs of the settings dialog except for in the keyboard shortcuts tab.
```

### To Reproduce

Steps to reproduce:
1. Go to 'settings'
2. Click on 'Keyboard shortcuts'
3. Hit escape key
4. See error 'not closing dialog'

### Expected behaviour

```text
All tabs should behave identical
```

### Operating System

MacOS

**Comment by elviskahoro** [comment]
Thanks for reporting. Some related issues: #223, #503

**Comment by dannyneira** [comment]
AFAIk, you need to press ESC twice on the keyboard shortcuts tab to exit, once to exit the search on the right, and a second time to exit the menu. closing this as resolved since the ESC is now working to close the tab/settings.
