### ISSUE TITLE
cannot completion of paths after tar with args

### ISSUE THREAD

**Issue by neil-acc** [warpdotdev/Warp#1335]
### Describe the bug

```text
When i wanna to uncompress a file using `tar zxvf somefile.tar.gz`, path complete not work.
But using `tar -zxvf` will work, i think it is a bug 🤣🤣
```

### Screenshots

![image](https://user-images.githubusercontent.com/75743591/167985814-8e413c4d-563f-4c27-94ce-7f0c8bee57ec.png)

### Operating System

MacOS

### OS Version

Version 15.4 (17613.1.17.1.13)

**Comment by elviskahoro** [comment]
I think this was fixed!
