### ISSUE TITLE
Warp does not support Starhip multi-line prompts

### ISSUE THREAD

**Issue by KieranP** [warpdotdev/Warp#1338]
### Describe the bug

I am using Starship, which works well with Warp as long as I keep it to one line.

However, if I want a multiline prompt, Warp is compacting it to one line, breaking the formatting.

### To Reproduce

Starship config:

```
format = "$directory\n\\$"
```

### Expected behaviour

Expected:

```
~/app
$ |
```

(where | is warps blinking cursor)

Instead, the result is:

```
~/app   $
|
```

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
Thanks for opening. Gonna close this in favor of #1015
