### ISSUE TITLE
Warp does not stay open

### ISSUE THREAD

**Issue by taylorjdawson** [warpdotdev/Warp#1348]
### Discord username (optional)

foba#7587

### Describe the bug

```text
When clicking the Warp icon in the launcher, Warp opens very briefly before closing.
```

### To Reproduce

Steps to reproduce:
1. Click on Warp icon
2. See it not open

https://user-images.githubusercontent.com/29665732/168145603-c97ec4e3-fbaa-453d-81b2-cef6dcce2aac.mp4

### Operating System

MacOS

### OS Version

<img width="202" alt="image" src="https://user-images.githubusercontent.com/29665732/168343096-6297f433-9f98-4a54-bdb7-cb493c9b10b7.png">

### Additional context

From `warp.log`
00:50:54 [ERROR] Failed to write User to secure storage: invalid Info.plist (plist or signature have been modified)

**Comment by dev4joel** [comment]
Interesting. Sorry to hear about the troubles you've been experiencing!

Do you mind sharing what is your OS version and the Warp version using?

**Comment by taylorjdawson** [comment]
@dev4joel Updated the issue with more info!

**Comment by dev4joel** [comment]
From foba via Discord
https://discord.com/channels/851854972600451112/852249738002956311/974380638050332813

**Comment by elviskahoro** [comment]
This was fixed in the recent update!
