### ISSUE TITLE
Integration: Use JSC for better fig specs

### ISSUE THREAD

**Issue by Milo123459** [warpdotdev/warp#135]
**Is your feature request related to a problem? Please describe.**
N/A
**Describe the solution you'd like**
Fig specs have a way allowing for JavaScript to be run to help generate better options, warp currently isn't hopping on this and is only getting half of the Fig experience. If something like JSC was used (JavaScriptCore) it'd mean you could get the full Fig experience. Fig has a [Discord](https://discord.com/invite/cg4UjshF2M) which I'm sure any Warp staff could ask in for help.
**Additional context**
N/A

Thanks! 👋

**Comment by elviskahoro** [comment]
@Milo123459 started a github discussion for this check it out here:
https://github.com/warpdotdev/warp/discussions/433#discussioncomment-1667680
