### ISSUE TITLE
Block Pattern Breaking

### ISSUE THREAD

**Issue by bwedl** [warpdotdev/Warp#1354]
### Describe the bug

```text
Running `omz reload` breaks Warp's block pattern.
```

### To Reproduce

Steps to reproduce:
1. Run `omz reload`

Upon completion of `omz reload` the input focus is "stuck" in the current block.

### Expected behaviour

```text
`omz reload` results in a new block (like echo in the screenshot) and editor is in default state.
```

### Screenshots

<img width="234" alt="Screenshot 2022-05-12 at 15 31 08" src="https://user-images.githubusercontent.com/88787929/168415006-05a4bb8c-4388-47e4-b746-449f5e822de0.png">

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

**Comment by elviskahoro** [comment]
Thanks for opening! Gonna close this in favor of #672
