### ISSUE TITLE
Odd issues with CLIs that accept input

### ISSUE THREAD

**Issue by KieranP** [warpdotdev/Warp#1364]
### Describe the bug

```text
I use Terraform for AWS provisioning. I ran "terraform apply" today, and it got through the planning phase, then halted at the part where it asks whether to proceed, y or n. This never showed up on my screen. I switched back to iTerm2 and it worked fine. So Warp appears to have issues with long running scripts that need user input.
```

### To Reproduce

Run "terraform apply" on an terraform codebase

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

5.8.1

**Comment by elviskahoro** [comment]
Thanks for opening. Warp doesn't work the best with terraform right now.

**Comment by sfroment** [comment]
That's still the case with v0.2022.10.11.08.13.stable_01.
I was so happy to finally passing to warp as we now have the fish syntax like highlighting but if you are using Terraform in your day to day work routine this issue make warp not really usable sadly.
