### ISSUE TITLE
The title shows nothing

### ISSUE THREAD

**Issue by Jeffrey28** [warpdotdev/Warp#1366]
### Describe the bug

```text
ssh link to the remote service. The title shows nothing.
```

### To Reproduce

ssh the remote service
![image](https://user-images.githubusercontent.com/26816785/168762934-9b29d1fb-9d0a-4d2b-be7b-82dfcb0af791.png)

### OS Version

12.3.1 monterery

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

**Comment by dev4joel** [comment]
This should be fixed in the next release!

**Comment by gagata** [comment]
Hey @Jeffrey28 mind confirming that the newest release fixed it for you?

**Comment by Jeffrey28** [comment]
Yes, it works well now.
