### ISSUE TITLE
Mac Os 11.3.1 M1 chip each opt cost long time to response

### ISSUE THREAD

**Issue by westlakestudent** [warpdotdev/Warp#1369]
### Describe the bug

```text
open Wrap cost long time，click one option cost event more time，it can't use normally
```

### To Reproduce

Steps to reproduce:
1. Go to 'open Wrap'
2. Click on 'right top option'

### Screenshots

![image](https://user-images.githubusercontent.com/6357368/168953534-4aeba8d0-30e3-445b-b5b3-ce8f9db7479e.png)

### OS Version

11.3.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin20.0)

**Comment by westlakestudent** [comment]
![image](https://user-images.githubusercontent.com/6357368/168954097-692e5325-3939-4bdb-977f-05c8500885be.png)

**Comment by westlakestudent** [comment]
open too slow

**Comment by chenkaiC4** [comment]
yes, catch same issue, why? the first expirece is not good. Mac M1 air book

**Comment by Goobercute** [comment]
terrible experience on m1 mac

**Comment by HonLuk** [comment]
same issue on intel mac

**Comment by fangyuandoit** [comment]
starting  zsh...        very slowly

**Comment by elviskahoro** [comment]
Sorry for the slowness. Can yall share your dotfiles here or email them to me: feedback@warp.dev

**Comment by westlakestudent** [comment]
it‘s better now

**Comment by elviskahoro** [comment]
@fangyuandoit @HonLuk @Goobercute @chenkaiC4 What about yall? What's it like on your end?
Will close this. if you're still experiencing slowness please open a new issue so we can get up to date details + details for your machine instead of westlake's
