### ISSUE TITLE
The keymappings and the block broke when ssh twice or type the `sudo su -` command.

### ISSUE THREAD

**Issue by dev4joel** [warpdotdev/Warp#1372]
### Discord username (optional)

MattyP#0231

### Describe the bug

```text
If I open Warp on my localmachine, and ssh to a remote box - all of the features stay intact - keymappings, the "blocks" etc. But, if I ssh to another box from that one, or "sudo su -" to the root user, the keymappings no longer work as well as the blocks.
```

### To Reproduce

1. ssh to host
2. ssh to host

or 

1. ssh to host
2. sudo su -

### OS Version

no

### Shell Version

no

**Comment by elviskahoro** [comment]
Ah yes! I think the underlying issue is #64

Thanks for reporting!

**Comment by PedroM0lina** [comment]
Hello , I think this never was fixed, it is happening to me :( 
if I do a ssh to a server and from there I change the user, the keymappings and the block behaviour stops working
