### ISSUE TITLE
Zsh defined functions (i.e. function () { ... }) should autocomplete by name

### ISSUE THREAD

**Issue by robmoore-i** [warpdotdev/Warp#1373]
### Describe the bug

In my `~/.profile`, I have this:

```text
function removeStalePostmasterPid() {
  rm /Users/robmoore/Library/Application\ Support/Postgres/var-12/postmaster.pid
}
```

And many more functions like it.

In the native Mac Terminal, these functions autocomplete, which enables discoverability of these functions which I use infrequently, but which save me time in Googling. I generally can just about remember how the function name starts based on the problem, and then pressing tab tells me what I need to run.

In the Warp Terminal, these functions do not autocomplete. In order to discover this function today, just now, I ran `tail -n 100 ~/.profile`, which works just fine, but is not ideal.

When indexing commands for autocomplete (however you do it - I don't know how to make terminals), Warp should include user-defined functions, like this one.

### To Reproduce

Steps to reproduce:

1. `echo "function myReproducerFunction () { echo 'reproduced' }" >> ~/.profile`2. 

2. `source ~/.profile`

3. Try to get 'myReproducerFunction' to autocomplete at the terminal, for example, type 'myRepr' and press tab.4. 

4. Observe that 'myReproducerFunction' is not autocompleted.

### Expected behaviour

In the reproducer example above, 'myReproducerFunction' should be autocompleted if I type 'myRepr' and press tab.

### Operating System

MacOS

### OS Version

11.6

### Shell Version

zsh 5.8 (x86_64-apple-darwin20.0)

### Warp Internal (ignore): linear-label:24888f54-df93-45d5-9bdd-e38f740cac19

**Comment by alokedesai** [comment]
Thanks for flagging--closing as this should be fixed as of this week's release. Please reopen if you are not seeing this work correctly!
