### ISSUE TITLE
Ability to copy/select/scroll When the suggested command is too long

### ISSUE THREAD

**Issue by dev4joel** [warpdotdev/Warp#1375]
### Discord username (optional)

Something Else#8449

### Describe the bug

```text
Hey guys! I've been playing around with the A.I. Command Search, and it's truly awesome! One thing I've noticed, however, is that it cuts off the command if it's too long, including copying it to the terminal itself... Is this a known issue?
```

### To Reproduce

1. Press ^ + `
2. Type display a mac notification saying that the aves beat the blues last night
3. Input command (via button or CMD + Enter)
4. Command is partial (and missing)
osascript -e 'display notification "The Aves beat the Blues last night" with title "

### Screenshots

![image](https://user-images.githubusercontent.com/58339060/169329385-c459512d-02cf-40eb-b5ac-45e1e4ee1907.png)

### OS Version

11.6.2

### Shell Version

5.8

### Additional context

```text
Version: v0.2022.05.09.09.06.stable_01
```

**Comment by elviskahoro** [comment]
Thanks for opening @dev4joel
