### ISSUE TITLE
Release Notes After Upgrade Aren't Scrollable When the Terminal is Too Small to Fit Them

### ISSUE THREAD

**Issue by zoominGiladSher** [warpdotdev/Warp#1376]
### Discord username (optional)

ThEldeRS#7593

### Describe the bug

```text
After upgrading Warp, it shows the release notes which is great, but when the terminal is too small to show the entire modal/dialog of the release notes you can't scroll down to continue reading, you have to enlarge the entire terminal.
```

### To Reproduce

Steps to reproduce:
1. Display the release notes modal/dialog with a lot of text in it
2. Reduce the height of the terminal so that the entire modal/dialog doesn't fit in it
3. See that you can't scroll down to continue reading and have to enlarge the entire app to read the release notes properly

### Expected behaviour

```text
Release notes modal/dialog should be scrollable if it doesn't fit within the app's height/width
```

### Screenshots

https://user-images.githubusercontent.com/56221821/169334261-a697d104-4f43-4f60-a2e0-da696c59f356.mov

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

**Comment by elviskahoro** [comment]
Great call out! Thanks for opening!
