### ISSUE TITLE
The input method status bar is always positioned in the bottom left corner of the desktop

### ISSUE THREAD

**Issue by dotnot2014** [warpdotdev/Warp#1379]
### Describe the bug

```text
The input method status bar is always positioned in the bottom left corner of the desktop
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```text
I need it following the terminal window
```

### Screenshots

![image](https://user-images.githubusercontent.com/9623347/169441514-879cfccb-45eb-4a91-aa04-624c800503c5.png)

### OS Version

macOS Monterey 12.4

### Shell Version

bash 3.2.57

**Comment by elviskahoro** [comment]
Thanks for opening! Apologies for this!

**Comment by ArkUmbra** [comment]
Just want to add that I am also observing this issue. 

Additionally, when I am full screen then I don't even see the hotkey window at all. This means I can't see the entered text at all until I press enter, which unfortunately makes it quite difficult to use Warp with these other input methods.
