### ISSUE TITLE
UIUX: Only open URL when user clicks, allow selections on URL objects

### ISSUE THREAD

**Issue by waldekmastykarz** [warpdotdev/warp#138]
**Is your feature request related to a problem? Please describe.**
Right now, by clicking on an URL it automatically opens in the browser. This makes it impossible to select a portion of the URL in the terminal like its hostname or path.

**Describe the solution you'd like**
Rather than opening URLs with a click automatically, consider requiring a modifier key like option to open the URL. A regular click would allow users to select a fragment URL like they would with regular text.

**Additional context**
n/a

**Comment by elviskahoro** [comment]
Changed back to your old name cause we have a different internal ticket for a modifier button.

**Comment by elviskahoro** [comment]
please reopen or comment if it still persists v0.2021.11.29.18.59.stable_01
