### ISSUE TITLE
zsh startup is occasionally very slow

### ISSUE THREAD

**Issue by neongreen** [warpdotdev/Warp#1380]
### Describe the bug

```text
zsh is almost instant to start in Terminal.app, but takes maybe 5–10s in Warp.
```

### To Reproduce

Open Warp

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

zsh 5.8

**Comment by neongreen** [comment]
It's not always slow, though. Sometimes I open Warp and it's fast. Huh.

**Comment by aggKartik** [comment]
It's occasionally quite slow for me as well.

**Comment by neongreen** [comment]
Still happens on v0.2022.05.16.09.01.stable_01.

**Comment by alokedesai** [comment]
Hey @neongreen sorry for the issues! Would you mind sharing a redacted version of your zshrc so that we can debug further? It's likely there's something in your zshrc that is affecting our bootstrap start times

**Comment by neongreen** [comment]
@alokedesai This is the complete file, without the comments:

```sh
DISABLE_AUTO_UPDATE="true"
export ZSH="/Users/artyom/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
```

**Comment by neongreen** [comment]
I'm happy to try to debug the issue if you tell me how. (Enable debug logs, etc..?)

**Comment by alokedesai** [comment]
Apologies for the delay here, I misinterpreted that this occasionally happens--which makes it seem like it may not be an issue with your RC file. Can you elaborate when it's slow or is it just completely random?

**Comment by neongreen** [comment]
One thing I've noticed is that if I close Warp and open it again, the second (and third, etc) time it seems to be fine.

Otherwise seems to be random.

**Comment by neongreen** [comment]
Yeah, I restarted my laptop again and the first startup was slow again. In fact, it took about a minute (usually it's only 10s or so, when the slowness hits). Doesn't happen with Terminal.app.

**Comment by neongreen** [comment]
I can also provide remote access via Zoom if this would help troubleshooting the issue. (Contact me at artyom@artyom.me then.)

**Comment by neongreen** [comment]
Still happening on v0.2022.07.11.09.11.stable_01.

**Comment by elviskahoro** [comment]
Does this happen with blank RC files?
Try this from the docs:
https://docs.warp.dev/help/known-issues#debugging
You can quickly set up clean configs by putting ZDOTDIR=/ in a ~/.zshenv file. This forces zsh to run with zero configs.


Also you can disable stuff just for Warp:
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

    # POWERLEVEL10K

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

**Comment by neongreen** [comment]
I have bought a new computer and Warp hasn't been hanging here (so far). I'll close this issue for now.

**Comment by elviskahoro** [comment]
That's one way to solve it.
