### ISSUE TITLE
The triangle is always at the top left corner when in VIM mode.

### ISSUE THREAD

**Issue by dev4joel** [warpdotdev/Warp#1381]
### Discord username (optional)

lironb#7068

### Describe the bug

```text
Hello, Is there a way to remove the blue thing at the top left corner? it is hiding my text 🙂 In this screen I am in VIM mode.
```

### To Reproduce

Steps to reproduce:
1. Type the command `CMD + D` to split pane.
2. Type the command `vim foo.txt`.
3. See the blue thing at the top left corner.

### Screenshots

![image](https://user-images.githubusercontent.com/58339060/169538645-65213727-398b-4db7-8c0f-b1794ce3f7ba.png)

### OS Version

any

### Shell Version

any

**Comment by elviskahoro** [comment]
Great call out. Thanks @dev4joel

**Comment by dansku** [comment]
Second ;)

![image](https://user-images.githubusercontent.com/590207/189630921-24b0d582-e961-4f65-ba94-dd0c023f7df6.png)

**Comment by Tolluset** [comment]
Is there any workaround?

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
