### ISSUE TITLE
shift + tab not work in vim

### ISSUE THREAD

**Issue by mycf** [warpdotdev/Warp#1382]
### Describe the bug

```text
in vim, I keymap <S-Tab> is not work
and I see <S-Tab> duplicate prev lines words
```

### To Reproduce

Steps to reproduce:
1. open file 'vim a'
2. random input "sasdfasfas" 
3. enter to next line 
4. one click <S-Tab> will input "s"
5. one more click    <S-Tab> will input "a"
6. one more click    <S-Tab> will input "s"
7. ....
8. finally input  "sasdfasfas" 

### Expected behaviour

```text
can keymap <S-Tab> to other like 
keymap("n", "<S-Tab>", "<C-w>h", opts)   is useful
```

### OS Version

10.15.7 

### Shell Version

zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by cfurrow** [comment]
I've had a similar experience with neovim, where I use `<S-Tab>` to move to the previous buffer, and `<Tab>` to go to the next buffer. `<Tab>` works fine, but `<S-Tab>` seems to scroll the current buffer up a line or to until it reaches the top of the buffer. 

In other terminals this same mapping is working with the same neovim config.

I wondered if it was possibly a Warp keymap, but there were none for "shift + tab". 

Outside of neovim, "shift+tab" does not seem to behave the same way as it does within neovim. Doesn't seem to do anything at all, which is expected.

**Comment by cfurrow** [comment]
Looks like Neovim + `<S-Tab>` was reported in https://github.com/warpdotdev/Warp/issues/903

**Comment by elviskahoro** [comment]
Thanks for opening. Gonna close this in favor of that one: #903  Will move your comment to there as well.
