### ISSUE TITLE
How to set warp as default terminal?

### ISSUE THREAD

**Issue by AvailableForTheWorld** [warpdotdev/Warp#1384]
### Describe the solution you'd like?

```text
I debugged the vscode cpp in while the origin default terminal was showing. How to set warp as default? I could not find the setting and searched in the doc but noting on.
```

### Is your feature request related to a problem? Please describe.

```text
Maybe a default button in the mac tabs or settings?
```

**Comment by alokedesai** [comment]
Hi @AvailableForTheWorld, thanks for the report! Would you mind clarifying what you mean here? Is this setting the default terminal within Vscode or generally within Macos?

**Comment by baruchiro** [comment]
Maybe duplicate of https://github.com/warpdotdev/Warp/issues/257?
