### ISSUE TITLE
Running a terraform command gets stuck forever; exits properly in MacOS Terminal

### ISSUE THREAD

**Issue by victortrac** [warpdotdev/Warp#1388]
### Describe the bug

I'm sure this isn't terraform specific, but I've only noticed it with the terraform binary.  The terraform process returns an error (which is expected and works fine on MacOS Terminal), but running the same command in Warp gets the process stuck. I have to `kill -9` the command in another terminal to exit.

### To Reproduce

```
/opt/homebrew/bin/terraform init -reconfigure -backend-config=prefix=terraform/state/processing
Initializing modules...


^C^C^C^C^C^C^C^C^C^C^C^Czsh: killed     /opt/homebrew/bin/terraform init -reconfigure
```

### Expected behaviour

```text
When using Terminal, it does this (which is expcted):

% /opt/homebrew/bin/terraform init -reconfigure                                                  
Initializing modules...

Initializing the backend...
╷
│ Error: Failed to get existing workspaces: querying Cloud Storage failed: Get "https://storage.googleapis.com/storage/v1/b/xxx/o?alt=json&delimiter=%2F&pageToken=&prefix=&prettyPrint=false&projection=full&versions=false": oauth2: cannot fetch token: 400 Bad Request
│ Response: {
│   "error": "invalid_grant",
│   "error_description": "reauth related error (invalid_rapt)",
│   "error_uri": "https://support.google.com/a/answer/9368756",
│   "error_subtype": "invalid_rapt"
│ }
│ 
│ 
╵
```
```


### Screenshots

_No response_

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

### Additional context

_No response_

### Warp Internal (ignore): linear-label:24888f54-df93-45d5-9bdd-e38f740cac19

_No response_

**Comment by elviskahoro** [comment]
Sorry about this! Our support for terraform is pretty bad!

**Comment by elviskahoro** [comment]
Will report back when there are updates

**Comment by PlugaruT** [comment]
Adding here just to raise awareness. I'd like to switch to warp full time, but since I run terraform at least once a day, this is a big issue for me. Running terraform in warp is a hit or miss, haven't found a pattern of when it works and when it's not.

**Comment by alokedesai** [comment]
Closing this out as we believe this has been fixed. Please reopen if you are still experiencing issues!

**Comment by nguyenvanduocit** [comment]
I get this issue, not just terraform, but any long run process.

**Comment by alokedesai** [comment]
@nguyenvanduocit Mind opening a new issue for this with more details? The underlying bug for this issue has been fixed, but we'd love to understand more about the issue you're experiencing. Thanks!
