### ISSUE TITLE
Can't add reaction to "Build Warp for Linux" issue because it's locked

### ISSUE THREAD

**Issue by adamdicarlo** [warpdotdev/Warp#1389]
Hi, I wanted to add my support for Linux... er, support. But I'm unable to leave a reaction because the thread is locked.

So I'd suggest putting a really big "Go here if you want Linux support" message at the top of the initial message here with the https://zachlloyd.typeform.com/to/lWeDTQnr link!

> @khionu I'll just lock the issue. This should help with notifications.

_Originally posted by @elviskahoro in https://github.com/warpdotdev/Warp/issues/120#issuecomment-1017793149_

**Comment by adamdicarlo** [comment]
After some digging I found https://github.com/warpdotdev/Warp/issues/204#issuecomment-1017793730 saying to subscribe to the "Build Warp for Windows" issue, and acknowledging that reactions aren't possible. I didn't see a message about that on #120 ("Build Warp for Linux") though, so could you clarify this in that issue for newcomers? Thanks!

**Comment by elviskahoro** [comment]
@adamdicarlo just updated the original comment in the linux issue thanks for flagging @adamdicarlo
