### ISSUE TITLE
Dialog close button is on the wrong side on macOS

### ISSUE THREAD

**Issue by tanuva** [warpdotdev/Warp#1392]
### Describe the bug

Dialogs in Warp have their close buttons on the wrong side on macOS. The "What's new" or Preferences dialogs have it on the right whereas the system window controls on the main window are on the left as expected.

(This is one of two reasons why Warp doesn't feel native at all to me. The other one is that dialogs are locked inside the main window. Not movable, no native window frame. Just like any other Chromium app.)

### To Reproduce

Steps to reproduce:
1. Start Warp on macOS
2. Open Preferences

### Expected behaviour

The close button should be on the left and (ideally) look like a native macOS close button.
### Operating System

MacOS

### OS Version

12.3

**Comment by elviskahoro** [comment]
Thanks! will report back when there are updates
