### ISSUE TITLE
Mac: Windows list in the Window menu

### ISSUE THREAD

**Issue by petergerard** [warpdotdev/Warp#1397]
### Describe the solution you'd like?

```text
Normally the Window menu in a Mac app has a list of windows after the Bring All To Front option, so you can switch between open windows and see which ones are minimized, etc.

I would like to see that standard list of windows in the Window menu so I can more easily toggle between the various Warp windows I have open.
```

### Is your feature request related to a problem? Please describe.

```text
It's hard for me to find other open Warp windows when I am multi-tasking.
```

### Additional context

Here's a screenshot of the Window menu from Apple's Terminal which lists the 2 windows I have open at the bottom of the menu
<img width="298" alt="Screen Shot 2022-05-24 at 2 01 59 PM" src="https://user-images.githubusercontent.com/17451/170102323-6530ec60-15f2-438b-8a07-c10f91570084.png">
.

**Comment by fuzzygroup** [comment]
This is absolutely standard behavior in a Mac app.  Additionally I have had the issue of Warp losing an entire terminal window -- I don't know where it went and I minimized every single window on my system trying to find it.  It only came back when I clicked update.

**Comment by elviskahoro** [comment]
Sorry about this yall! There are updates to the mac menu soon!

**Comment by elviskahoro** [comment]
### Discord username (optional)

_No response_

### Describe the solution you'd like?

```text
When you right click the default Mac terminal's dock icon, a context menu opens that shows a list of each window open with titles. Warp does not support this which makes it tedious to find a specific window when many windows are open.
```


### Is your feature request related to a problem? Please describe.

_No response_

### Additional context

Mac terminal
<img width="353" alt="Screenshot 2022-04-27 at 12 42 18 AM" src="https://user-images.githubusercontent.com/29553206/170551595-3453646d-3bf8-4aa2-8b7a-701df67f3d62.png">

Warp:
<img width="201" alt="Screenshot 2022-04-27 at 12 42 33 AM" src="https://user-images.githubusercontent.com/29553206/170551625-5a3aa84d-f7f9-43aa-adbd-871b06719de7.png">



### Warp Internal (ignore) - linear-label:efcea52d-0ab4-4a92-a41b-93c3e244f0a0

_No response_

**Comment by dannyneira** [comment]
Hey Folks, Warp's latest release now sets the title in the Window menu as well as right-clicks on the dock icon!

![CleanShot 2023-02-10 at 11 34 10](https://user-images.githubusercontent.com/16809145/218170590-a22e198f-3b96-4c06-bc34-c2edd68e7669.png)

![CleanShot 2023-02-10 at 11 31 01](https://user-images.githubusercontent.com/16809145/218170151-aac11525-0137-4060-95c2-5f111dd295cd.png)
