### ISSUE TITLE
Canceled: Newline command doesn't work when in git repository.

### ISSUE THREAD

**Issue by ob1dev** [warpdotdev/warp#140]
**Describe the bug**
Newline command `Option` + `Return` doesn't work when I'm in a git repo. But works fine when I'm not in a git repo.

**To Reproduce**
1. Go to a git repo. 
2. Type `foo` on the first line, then hit `Option` + `Return` to go to a new line
3. `foo` disappears

**Expected behavior**
Go to a new line where I can type `bar`:

```
foo
bar
```

**Screenshots**

https://user-images.githubusercontent.com/2487951/130336696-5ec478dd-b5e1-4360-b6c4-8b486ff853b7.mov

**Desktop (please complete the following information):**
 - OS Version: macOS 11.5.2, Git 2.33.0, Warp v0.2021.08.16.23.50.stable_02

**Comment by olegburov** [comment]
Okay, looks like it's related to [Spaceship](https://github.com/spaceship-prompt/spaceship-prompt) prompt I'm using.

In my `~/.zshrc`, if I disable the git status that it shows (see the next tab in the above video), then Warp works as expected

```
SPACESHIP_RPROMPT_ORDER=(
  # git           # Git section (git_branch + git_status)
)
```

Is it something you can do about it?

**Comment by zheng** [comment]
Is there any chance you had one of the "Option Key is Meta" settings on?

**Comment by olegburov** [comment]
No, it's not Meta. 

To me, it seems like it conflicts with Spaceship prompt's [git](https://github.com/spaceship-prompt/spaceship-prompt/blob/master/sections/git.zsh) section.
