### ISSUE TITLE
duoble click will mark entire row and not stop on hypthens

### ISSUE THREAD

**Issue by Oterem** [warpdotdev/Warp#1400]
### Describe the solution you'd like?

```text
when double clicking a row in warp after performing a k8s command, double click on a row will mark it entirely for easier copy
```

### Additional context

double click on the pod name marks only partial text instead of all line (the expected behavior is supported in iterm2)

<img width="1271" alt="Screen Shot 2022-05-25 at 10 46 59" src="https://user-images.githubusercontent.com/26056415/170210030-be9f9400-8993-45ca-bcb9-6948000bc8b4.png">

**Comment by elviskahoro** [comment]
Thanks for reporting. Gonna close in favor of #659
