### ISSUE TITLE
can warp support add args behind？

### ISSUE THREAD

**Issue by fireinrain** [warpdotdev/Warp#1401]
### Describe the bug

```text
Hello dude. I am use warp for daily work. and I want to make warp work with Alfred. I find warp does not support pass some args behind it. or you cant use such command like that 

open -a 'Warp' ./

but you can do this in iTerm2. so can warp support this feature?
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Screenshots

<img width="539" alt="image" src="https://user-images.githubusercontent.com/14249262/170300223-fa3bc73b-031d-4eeb-83c4-ad762d44aaa8.png">
You can see that I use Iterm2, it can work ok, but with warp, it does not work.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/14249262/170300976-872f3120-5fae-4bfc-8843-97fe28c538b4.png">

### Operating System

MacOS

### OS Version

10.15.7 

### Shell Version

zsh 5.8

### Additional context

```text
warp v0.2022.05.16.09.01.stable_01
```

**Comment by elviskahoro** [comment]
Thanks for reporting. We're tracking this here:
#612
