### ISSUE TITLE
History is not updated

### ISSUE THREAD

**Issue by razbakov** [warpdotdev/Warp#1402]
### Describe the bug

```text
When I execute commands, they don't appear in history
```

### To Reproduce

Steps to reproduce:
1. Go to Warp
2. Run `pwd`
3. Run `ls`
4. Press key up

### Expected behaviour

```text
Command `ls` is displayed
```

### Screenshots

<img width="793" alt="Screen Shot 2022-05-26 at 11 52 15 AM" src="https://user-images.githubusercontent.com/298778/170464423-f22b3c25-34e0-48e9-8ed1-45785b228918.png">

### Operating System

MacOS

### OS Version

12.2.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

**Comment by veged** [comment]
same for me

**Comment by elviskahoro** [comment]
The initial space is a bug, see here:
https://github.com/warpdotdev/Warp/issues/893

Gonna close this out since 893 is the underlying issue.
