### ISSUE TITLE
A.I. Command Search hotkey overrides potential global hotkey window keybinding

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#1406]
### Describe the bug

```text
Cannot map quake to ctrl-` because ai command search takes precedence
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### OS Version

n/a

### Shell Version

n/a

**Comment by ephemer** [comment]
Thanks for opening this. In general it'd be great to not have hotkeys competing with one another. Was there any progress here?

**Comment by ShaneK** [comment]
FWIW this issue doesn't seem to exist anymore. The global hotkey takes precedence over the AI command suggestion one. Also, you can edit the hotkey binding for the AI command suggestion or clear it out if you don't use it now (not sure if you could before or not).

**Comment by dannyneira** [comment]
Thanks for letting us know @ShaneK. Closing as resolved but please feel free to comment if you see the issue persists.
