### ISSUE TITLE
Cannot clear history

### ISSUE THREAD

**Issue by owenbrownzc** [warpdotdev/Warp#1409]
### Describe the solution you'd like?

```text
It's not possible to clear command history. 

This is deal breaker for me.
```

**Comment by warpdotdev-dx** [comment]
Can you try pressing CTR-L? This should clear the history.

**Comment by elviskahoro** [comment]
Thanks for reporting. Gonna close in favor of #516

**Comment by skogsmaskin** [comment]
`CTRL-Shift+K` does it for me (Linux/Gnome).
