### ISSUE TITLE
Support double tapping (consecutive clicks) within the keybinding schema

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#1410]
### Describe the solution you'd like?

```text
Ability to double press a key and register it as a keybinding.
```

**Comment by dannyneira** [comment]
We have a request tracking this over at #1240 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Duplicate of #2809
