### ISSUE TITLE
Add setting to require cmd+click to open a link

### ISSUE THREAD

**Issue by kayleg** [warpdotdev/Warp#1414]
### Describe the solution you'd like?

```text
Add setting to require holding `command` (or some other key) while clicking a link in order for it to open.
```

### Is your feature request related to a problem? Please describe.

```text
While the auto link detection is great, it's a nightmare when editing a web page in terminal. When I just want to click on a NeoVim split to regain focus sometimes I hit a link and find myself thrown into browser.
```

### Additional context

iTerm2 does the `cmd+click` option which is really nice.

**Comment by huxiang** [comment]
Not only link, but also local paths in command output, like:

    Please check detailed logs at:
    /Users/tony/PycharmProjects/my-project/workspace

In iTerm2 + zsh, the local path can be opened by cmd+click

**Comment by elviskahoro** [comment]
Thanks for opening. Gonna clsoe this in favor of #177
