### ISSUE TITLE
Windows platform support

### ISSUE THREAD

**Issue by SuperCuteXiaoSi** [warpdotdev/Warp#1417]
### Describe the solution you'd like?

```text
Windows platform support
```

### Is your feature request related to a problem? Please describe.

```text
Hello, warp developers!

I think I am a dual platform user of windows and MAC. When my colleagues saw me using the Warp tool, they were deeply shocked by the function of this tool. They were all asking me whether this tool has a Windows platform. I am also looking forward to the support of the windows platform. So do you have any plans to support the windows platform? When do you expect to experience it on the windows platform?
```

**Comment by cherryleafroad** [comment]
If Windows support was added, this would take off even more than it is already. It'd be an instant hit. I'd say Windows support would be good not only for users, but for the life of the project (not to mention, you could license it to companies and such to get paid even more; many companies also use Windows)

**Comment by elviskahoro** [comment]
Clsong in favor #204
