### ISSUE TITLE
Configure padding for Alt-screens (vim, less, nano, top, etc)

### ISSUE THREAD

**Issue by lreto** [warpdotdev/Warp#1418]
### Describe the bug

```text
When using vim, nano, less or similar editors or file viewers there is no padding at all on the left side of the terminal. The first row seems to be cut off, making the first character of each line difficult to read and moreover, just does not look very good.

In iTerm or Tabby everything looks fine. Is there maybe a setting that I did not yet find to modify this display behavior?
```

### To Reproduce

1.) Open a file in vim, less, nano or any terminal-based file editor or viewer in Warp

### Expected behaviour

```text
I would like to have some padding between the edge of the terminal window and the first characters of the editor, possibly the same padding that is right now between the window edge and the command output/prompt.
```

### Screenshots

![less-no-padding](https://user-images.githubusercontent.com/97523160/170966433-5e0f130a-e9b9-4984-b47f-8e6ba8641fff.png)
![nano-no-padding](https://user-images.githubusercontent.com/97523160/170966446-820b0002-9fe4-4c8c-82d7-c72e679d3085.png)
![vim-no-padding](https://user-images.githubusercontent.com/97523160/170966449-a5241b9c-220d-4a4c-acd6-59c8b575c3b2.png)

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1

**Comment by trun222** [comment]
I second this. It's weird how basic text/styling settings aren't available. The only place I've seen where you can customize text-related options is within a theme.

**Comment by elviskahoro** [comment]
Thanks for opening! will report back when there are updates!

**Comment by marcusthelin** [comment]
Any updates on this?

**Comment by elMestre** [comment]
just a +1 here.
It's also weird for me having the characters so close to the edge

**Comment by elMestre** [comment]
Ups... don't known if it was the last update, or VScode warp-companion. 

But this is fixed for me


![Captura de Pantalla 2023-03-11 a las 22 46 55](https://user-images.githubusercontent.com/1005595/224512847-97fa7aa4-27d5-4a02-b59d-f3d381438112.png)

**Comment by kamalkech** [comment]
ok for me i need to remove this padding, because i need to use full space, but cannot found this option in the settings!! any one here can help and thank u

**Comment by kamalkech** [comment]
any answer ??

**Comment by dannyneira** [comment]
hey @kamalkech Sorry about this blocker, but you can't remove the padding at this time. It was added a while back to improve compatibility with alt-screens like [k9s](https://github.com/warpdotdev/Warp/issues/833)

**Comment by jeffschwartz** [comment]
I prefer iTerm2's handling of margins. It allows you to set both top and bottom margins per profile. Having a fixed static margin doesn't make sense to me.

**Comment by dannyneira** [comment]
@lreto Thanks for submitting, this has been resolved in recent versions of Warp padding has been added.

For anyone else interested in removing padding, please track. https://github.com/warpdotdev/Warp/issues/2373

**Comment by kamalkech** [comment]
@dannyneira cannot understand ur last comment, i have the last version but cannot found this option of padding !!

**Comment by dannyneira** [comment]
My mistake, I misunderstood the request, its not for added padding, but for the ability to configure the amount of padding. Reopening and changing the title to match. 

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dexwert85** [comment]
+1

**Comment by danyalutsevich** [comment]
please +1 🙏

**Comment by szgupta** [comment]
Hey y'all, sorry for the silence on this feature request. We'll be launching this soon. Checkout this thread if you want to try it out before release: https://github.com/warpdotdev/Warp/issues/2373#issuecomment-2492581897!

**Comment by szgupta** [comment]
Hey folks, there is a new setting for this on the latest version of Warp (v0.2024.12.03.08.02.stable_04 and beyond). Please see the steps here to configure the padding: https://docs.warp.dev/features/full-screen-apps#padding

I'll leave this ticket open for a couple of days in case folks have any further feedback.

**Comment by szgupta** [comment]
Going to close out this issue. Please feel free to open up a new issue if you're running into any problems / have more feedback about the change!
