### ISSUE TITLE
SSH broken for remote machines that lack git and use PackageKit-command-not-found

### ISSUE THREAD

**Issue by harrisjnu** [warpdotdev/Warp#1424]
### Local Shell and Version

echo $ZSH_VERSION 5.8.1

### Remote Shell and Version

echo $BASH_VERSION 4.4.19(1)-release

### Operating System and Version

RHEL 8.3

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Include shell xtrace output

SSH login into any VM lands up in 
bash-4.4#
Install package 'git-core' to provide command 'git'? [N/y] 

Tried, disabling SSH Wrapper as well.

**Comment by elviskahoro** [comment]
Thanks for opening. Will circle back once it's fixed!

**Comment by absktoday** [comment]
I am getting the same issue trying to SSH to Rocky Linux 8.6. It does work fine when SSH to CentOS 7.9.2009. So the issue seems related to RHEL 8 or above.

**Comment by vorporeal** [comment]
Hey all, is this still an issue for you?

**Comment by DTclo** [comment]
Hello,

This is still an issue on RHEL and ALMA.
Operating System: Red Hat Enterprise Linux 9.1 (Plow)     
CPE OS Name: cpe:/o:redhat:enterprise_linux:9::baseos
Kernel: Linux 5.14.0-162.6.1.el9_1.x86_64

After successful ssh login:
Install package 'git-core' to provide command 'git'? [N/y]
Then the prompt gets stuck on "Loading prompt..."

<img width="534" alt="Screen Shot 2022-12-20 at 12 29 03 PM" src="https://user-images.githubusercontent.com/121122357/208729154-2b4e9ca8-527a-4782-849d-281910432925.png">

<img width="540" alt="Screen Shot 2022-12-20 at 12 29 38 PM" src="https://user-images.githubusercontent.com/121122357/208729236-42402bea-2183-47eb-bace-37cceb420048.png">

**Comment by vorporeal** [comment]
Hey @DTclo, thanks for letting me know.  I think I have a fix; aim is to get it out in either this week's release or next week's release.  I'll post an update here when it's live. :)

**Comment by DTclo** [comment]
Hi @vorporeal , I can confirm that installing git on the remote server fixes the issue. Thank you!

**Comment by vorporeal** [comment]
Good to know!  This Thursday's release will also fix this issue in general (i.e.: SSH into that server will work even if you uninstall git). :)

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
