### ISSUE TITLE
Search box keeps focus

### ISSUE THREAD

**Issue by cnuss** [warpdotdev/Warp#1427]
### Describe the bug

```text
Greetings!

Love the terminal.

I think this is a bug? I've attached a screen recording.

When the search box is up, and then I click away from the window, then click back in the window, the text cursor defaults to the search box and not where I clicked.
```

### To Reproduce

See screen recording

https://user-images.githubusercontent.com/819991/171431876-951abf98-7a37-47d3-9c12-6580ff42b2ba.mov

.

### Expected behaviour

```text
Personally I think upon re-clicking the window, the active focus should be the terminal input at the bottom.
```

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

**Comment by elviskahoro** [comment]
Ah yes. Thanks for flagging. Gonna close in favor:
#739
