### ISSUE TITLE
Pasting in nano misses line breaks

### ISSUE THREAD

**Issue by AustinSmart** [warpdotdev/Warp#1429]
### Describe the bug

```text
Copying a yaml document outside of Warp and pasting via Nano misses many (but not all) line breaks. Other terminal apps (iterm, terminal) paste without issue.
```

### To Reproduce

Steps to reproduce:
1. Copy this document https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure.md#manifest-for-clusters-with-rbac-enabled-namespace-access
2. Open a file via nano in Warp
3. Ctrl + V
4. Observe (seemingly random) missing line breaks

### Expected behaviour

```text
Document pastes with line breaks preserved.
```

### Operating System

MacOS

### OS Version

12.2.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

**Comment by elviskahoro** [comment]
Thanks for reporting. Gonna close in favor of #465

**Comment by truongvietttruong** [comment]
Just install nano with brew and use this from /usr/local/bin/nano.
Its will copy and paste without problems.
