### ISSUE TITLE
Opening nano nuked the Warp application

### ISSUE THREAD

**Issue by robmoore-i** [warpdotdev/Warp#1433]
### Describe the bug

```text
I opened nano, and I got the Mac beach ball. I pressed Cmd-Q and it didn't die immediately. The beach ball also took over my cursor so I could click the Force Quit menu in the Mac (although the keyboard shortcut may have worked if I could remember it). It died after only about 20 seconds, which is still long enough to be annoying. Not a terrible bug, but just wanted to let you know I encountered this today.

Thanks,
Rob
```

### To Reproduce

Steps to reproduce:
1. Open a file in nano.

I have updated to the latest version of Warp today, just now. How do I copy my current Warp version from the app? I expect to be able to go to the top left of my Mac, and under "Warp" in the top bar I should see "About Warp", which should open a little window which prominently displays the exact version of the application that is running.

### Expected behaviour

```text
Opening nano should not cause an interminable beach ball cursor.
```

### Operating System

MacOS

### OS Version

11.6

### Shell Version

zsh 5.8 (x86_64-apple-darwin20.0)

### Additional context

```text
- I have this nano version:

robmoore@Robs-MacBook-Pro ~ % nano --version
 GNU nano version 2.0.6 (compiled 03:16:25, Aug 30 2021)
 Email: nano@nano-editor.org	Web: http://www.nano-editor.org/
 Compiled options: --disable-nls --enable-color --enable-extra --enable-multibuffer --enable-nanorc --enable-utf8
```
```

### Warp Internal (ignore): linear-label:24888f54-df93-45d5-9bdd-e38f740cac19

**Comment by vorporeal** [comment]
Thanks for the report!  We've figured out the bad commit and are working to get a patched release out today.
