### ISSUE TITLE
Error when launching new window

### ISSUE THREAD

**Issue by mkapra** [warpdotdev/Warp#1434]
### Discord username (optional)

mkapra#9235

### Describe the bug

When starting warp or creating a new tab the following error occurs:

```
warp_bootstrapped:print:10: bad option: -t
```

### To Reproduce

Just start a new window. Either by `Cmd+N` or `Cmd+T`

### Expected behaviour

```text
Just the prompt without any errors
```

### Screenshots

<img width="460" alt="Bildschirmfoto 2022-06-02 um 11 13 42" src="https://user-images.githubusercontent.com/34742358/171597418-d359dbfa-71fa-4e03-8a5e-71c5b418ebc9.png">

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

**Comment by mkapra** [comment]
I have to add that this worked the version before. This only occurs in the current version of warp.

**Comment by sfroment** [comment]
I have the exact same issue, @mkapra are you also using starship ?

**Comment by mkapra** [comment]
> I have the exact same issue, @mkapra are you also using starship ? 

No I use plain zsh with antigen Plugin Manager

**Comment by chrisfromredfin** [comment]
I have this same issue, but I _am_ using Starship with zsh. I also am using Antigen.

**Comment by vorporeal** [comment]
We run the command `print -l ${(ok)functions}` as part of shell initialization in order to get the list of user-defined functions (for auto-completion purposes).

Seems like something is adding a `-t` there; perhaps there's some zsh plugin which sets an alias for `print`?

Mind running `whence -v print` and posting the result here?

**Comment by mkapra** [comment]
> We run the command `print -l ${(ok)functions}` as part of shell initialization in order to get the list of user-defined functions (for auto-completion purposes).
> 
> Seems like something is adding a `-t` there; perhaps there's some zsh plugin which sets an alias for `print`?
> 
> Mind running `whence -v print` and posting the result here?

whence -v print
print is a shell builtin

Seems to not be the case.

**Comment by mkapra** [comment]
I do not know what changed. I only use a plain zsh version with antigen. Antigen only provides one plugin for me: 
[https://github.com/lukechilds/zsh-nvm](https://github.com/lukechilds/zsh-nvm)

I don't have something else.

**Comment by vorporeal** [comment]
Sorry, didn't mean to imply anything changed on your end - we introduced a call to `print -l ${(ok)functions}` in the build where things started going wrong for you, and that's almost certainly where the error is coming from.  I'm just trying to understand what about your configuration might be causing that line to fail.

If you run `print -l ${(ok)functions}` in your shell, do you get the same error message?

**Comment by vorporeal** [comment]
Ok, cool.  Last question for now: does `print -l -- ${(ok)functions}` work correctly?

**Comment by mkapra** [comment]
yep that works 👍🏼

**Comment by vorporeal** [comment]
Awesome!  I'll have a fix out in this week's release.

**Comment by mkapra** [comment]
Seems to be fixed for me. Thanks!
