### ISSUE TITLE
Terminal hangs forever when using commitzen, commitlint with husky

### ISSUE THREAD

**Issue by 0xckylee** [warpdotdev/Warp#1435]
### Discord username (optional)

stine#1892

### Describe the bug

```text
The spinning wheel of death appears for Warp application when I complete the commitzen process.
```

### To Reproduce

Steps to reproduce:
1. install [husky](https://www.npmjs.com/package/husky) 
2. install [commitlint](https://github.com/conventional-changelog/commitlint)
3. install [commitzen](https://github.com/commitizen/cz-cli)
4. `git commit`

### Expected behaviour

```text
git commit completes successfully, ready to be pushed remotely.
```

### Screenshots

<img width="1189" alt="스크린샷 2022-06-02 오후 6 40 26" src="https://user-images.githubusercontent.com/8842929/171602647-6ddb7c3a-2aa6-4c3a-b042-4246e39896fa.png">

### Operating System

MacOS

### OS Version

11.6.5

### Shell Version

GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

```text
My development environment is setup in a way that I am running a Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-110-generic x86_64) virtual machine on Virtualbox, and using Vagrant `vagrant ssh` to access the box. RAM usage is limited to 2GB.
```

**Comment by elviskahoro** [comment]
Thanks for reporting. Will circle back when there are updates!

**Comment by elviskahoro** [comment]
Should be fixed now!
