### ISSUE TITLE
Cancelled: Long input lines make next command entry have large indent.

### ISSUE THREAD

**Issue by JimmyDeemo** [warpdotdev/warp#144]
### Describe the bug

When I execute a long line in the terminal the next entry appears to be filled with tabs or spaces such that the cursor is on the right side of the entry window.

### To Reproduce

Steps to reproduce:
1. Open a new Warp window.
2. Run the following command; `java -jar '/Users/username/Dev/P4/project/BuildScriptsP4/bundletool-all-0.8.0.jar' build-apks --bundle '/Users/username/Dev/P4/project/Build/Android/Live/myproject.aab' --output '/Users/username/Dev/P4/project/Build/Android/Live/myproject.apks' --ks=/Users/username/Dev/P4/project/BuildScriptsP4/some_name.keystore --ks-pass=pass:**** --ks-key-alias=myproject`
3. It will fail, but observe the next entry box.
4. Cursor is on the far right of the window and has a `⍉` character.

### Expected behaviour

```shell
New entry box should always start with empty command a cursor on the far left.
```

### Screenshots

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/4234718/130747820-b2f3e815-2ba1-47ad-8663-69dea18a66e2.png">

### Operating System

MacOS

### OS Version

11.4

**Comment by zheng** [comment]
Hello @JimmyDeemo, thanks for the report!

Does this happen for every long command for you, or only this command? Is there anything in your ~/.zshrc or ~/.zprofile that may be responsible for this?

**Comment by JimmyDeemo** [comment]
Hello.

Not that I can tell. The command listed in the OP was just one that would do it every time. I have also had it happen with shorter commands since the post, but i've yet to find a pattern.

I can certainly check my ~/.zshrc or ~/.zprofile but what sort of things would should I be looking for? In the standard teminal I have used https://ohmyz.sh/ if that might cause conflicts.

**Comment by JimmyDeemo** [comment]
Ah I think I have found what the cause is. For some reason my setup mean that a red '⍉' character is added whenever a command errors;

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/4234718/131495587-f8268821-7924-47e6-91d2-4299b4b87fb1.png">

Looks like this is spilling over in Warp.

**Comment by elviskahoro** [comment]
Cancelled.

**Comment by JimmyDeemo** [comment]
Does ‘cancelled’ effectively mean ‘won’t fix’?

**Comment by elviskahoro** [comment]
Sorry for the confusion. Cancelled != won't fix. I've been reserving cancelled for issues that the original issue author cancels themselves because they opened in error, etc.

This case is special however. I'm in the process of moving your request to this GitHub issue, which we recently turned into a GitHub discussion. GitHub discussions allow people to reply to each individual comment and branch out vs sequential replies. Since you're request is related to custom prompts.
- https://github.com/warpdotdev/warp/issues/64

Normally, I'll change the title to DUP: Duplicate of #XXX
- so that we can easily consolidate related issues, but that doesn't work for this particular case since we converted the prompts to a github discussion.

I thought I'd be done by the time you were online, but you beat me to it.

**Comment by elviskahoro** [comment]
Thanks for the feedback on cancelled not being intuitive, just changed the title to:
Moved to discussions - 422

**Comment by elviskahoro** [comment]
One thing I find a bit annoying is that I can't @someone in an issue that they haven't interacted with even if it's in the same repo.

**Comment by JimmyDeemo** [comment]
@elviskahoro Thanks for moving this to a relevant discussion, but I am still left with the problem.

Any advice on how I can work around this in Warp or find which of my terminal 'plugins' is causing the issue such that I can turn it off?

**Comment by elviskahoro** [comment]
I emailed you!

**Comment by elviskahoro** [comment]
> @elviskahoro Thanks for moving this to a relevant discussion, but I am still left with the problem.
> 
> Any advice on how I can work around this in Warp or find which of my terminal 'plugins' is causing the issue such that I can turn it off?

I emailed you!
