### ISSUE TITLE
Warp hangs when running nano over ssh

### ISSUE THREAD

**Issue by jaredmoody** [warpdotdev/Warp#1445]
### Describe the bug

```text
Warp consistently hangs with the following steps:
```

### To Reproduce

Steps to reproduce:
1. ssh into a server
2. edit a file with nano
3. There is no step 3

### Expected behaviour

```text
I'd like to not have to force quit warp.
```

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

zsh 5.8

### Warp Version

0.2022.05.30.09

**Comment by pionoor** [comment]
Specifically when i run this command `sudo nano /etc/sysctl.conf`
