### ISSUE TITLE
Support horizontally expanding the  AI / Workflows / Command History GUI

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#1447]
### Describe the solution you'd like?

```text
In some cases, the text length is cut off because it exceeds the width of the UI element.
```

**Comment by champo** [comment]
A related point would be to support line breaking. I have several long commands that would benefit from both. Maybe should be workflows, but I found the setup process wasn't just a dialog and churned 🙈.

**Comment by rsjatl** [comment]
Adding a note of support here to this issue. This essentially makes the history search GUI unusable (multiple commands with multiple parameters/flags).

**Comment by d0b1010r** [comment]
Yes! I can fully support @rsjatl comment! For long commands the history search is completely broken. There is no visible difference between all these commands (but they are different). Finding the correct one is completely guess work.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/1316750/220553615-89d48260-1ffc-4e2d-826f-bb2f6b0ebe4f.png">

**Comment by ghouston** [comment]
currently I can use the mouse to drag the pop-up wider.  however every time warp restarts it goes back to a narrow search pop-up.  this is a quality of life, accessibility issue (yes there are people like me who need to avoid the mouse as much as possible) and a daily annoyance with warp.  please either a) remember the width of the search popup between restarts b) default the width of the popup to the width of the warp window c) have wrapping of lines in the popup.

**Comment by nichoj10** [comment]
Hi @ghouston! Warp should persist the horizontal widths of common panels like universal search, workflows browser, Warp AI, etc. This should work across sessions as long as you have config restoration enabled - this is bundled under "Restore Windows, Tabs, and Panes on Startup" which you can find with the command palette (`CMD-P`). Please let us know if you're still encountering issues!

**Comment by dannyneira** [comment]
Closing as resolved since the horizontal width of the Workflow/WarpAI/Command Search panels now persists, but please feel free to let us know of any issues.
