### ISSUE TITLE
ksh: syntax error: `(' unexpected

### ISSUE THREAD

**Issue by e-minguez** [warpdotdev/Warp#1448]
### Discord username (optional)

N/A

### Local Shell and Version

zsh 5.8.1

### Remote Shell and Version

@(#)PD KSH v5.2.14 99/07/13.2

### Operating System and Version

OpenBSD 7.1 GENERIC#0 amd64

### Warp Version

v0.2022.05.30.09.10.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

Trying to access an OpenBSD machine it fails as $TITLE

### Include shell xtrace output

WARP_DEBUG_MODE=1 ssh edu@xxx
ksh: syntax error: `(' unexpected
Shared connection to xxx closed.

**Comment by elviskahoro** [comment]
Thanks for opening. Will circle back when there are updates

**Comment by vorporeal** [comment]
Hey @e-minguez, I believe this is fixed now. :)  We have limited support for ksh as a remote shell (no Warp features like blocks), but there shouldn't be any syntax error when you attempt to ssh into a machine with ksh as the remote shell.

Please don't hesitate to re-open this issue if you're still experiencing problems!
