### ISSUE TITLE
Custom triggers

### ISSUE THREAD

**Issue by gagata** [warpdotdev/Warp#145]
### Is your feature request related to a problem? Please describe.

```shell
Requested on Discord by zouhir
```

### Describe the solution you'd like?

```shell
what are custom triggers?
allow users to define some regular expression and when matched in a command output, trigger an action. Example:
- if matched '^ERROR.*' -> highlight red.
- if matched ^https?:// -> make clickable link
```

### Additional context

iTerm2 triggers & supported actions
- https://iterm2.com/documentation-triggers.html

**Comment by mds1** [comment]
+1 on this. The one big thing I miss from iTerm2 is their trigger support, namely:
- Highlighting text various colors when it matches some regex
- Having text link to a URL if it matches some regex, where the URL includes the matched string

**Comment by elviskahoro** [comment]
Combining triggers with collapsable blocks +/ compact mode

only show one line of output, for instance when running yarn add react, for example it would be useful when upgrading from yarn outdated output

would be great if the output is smart ;) and you can activate it with something like shift+enter

The way I imagine it is that all output is squashed into one line with an ability to expand (or scroll).
It really depends on your current workflow in the terminal. Some commands, like code generation or package installation give a whole bunch of lines of output while the only thing I need to know is "success" or "failure". It's nice to have the blocks as a history without having to scroll a whole bunch.

**Comment by elviskahoro** [comment]
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/29553206/148191305-c3e0559e-063d-450e-a990-c28620e9e18d.png">
