### ISSUE TITLE
Warp is unusable after installing latest update

### ISSUE THREAD

**Issue by bradenpowers** [warpdotdev/Warp#1450]
### Describe the bug

```text
I went to install the latest update. After I installed the update, I am stuck on a pink screen, unable to use the application.
```

### To Reproduce

click on install update
![Screen Shot 2022-06-03 at 4 15 44 PM](https://user-images.githubusercontent.com/376102/171945592-4249bb85-bf12-409d-bf4f-f8a49e5a455e.png)

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

5.8

### Warp Version

unsure

**Comment by elviskahoro** [comment]
@bradenpowers we have a fix incoming! Just waiting on the builds to finish running.

**Comment by bradenpowers** [comment]
Cool. Thanks!

**Comment by szgupta** [comment]
Hey @bradenpowers, are you still seeing this bug?

**Comment by szgupta** [comment]
Hey @veypi, do you remember what sequence of events caused this? Or was this the state when you opened the app after downloading?

**Comment by veypi** [comment]
luckily, it worked after reboot and I don't know why.

> Hey @veypi, do you remember what sequence of events caused this? Or was this the state when you opened the app after downloading?

**Comment by szgupta** [comment]
Got it. Did you see this issue after an update? We'd love to figure out how this happened to prevent it in the future!

> luckily, it worked after reboot and I don't know why.
> 
> > Hey @veypi, do you remember what sequence of events caused this? Or was this the state when you opened the app after downloading?

**Comment by veypi** [comment]
No.I run the warp in a terminal, and there is no error info. Just only I did is to kill all apps and reboot my Mac

> Got it. Did you see this issue after an update? We'd love to figure out how this happened to prevent it in the future!
> 
> > luckily, it worked after reboot and I don't know why.
> > > Hey @veypi, do you remember what sequence of events caused this? Or was this the state when you opened the app after downloading?

**Comment by bradenpowers** [comment]
> Hey @bradenpowers, are you still seeing this bug?

I am not. I got rid of it by uninstalling the app. I then rebooted and reinstalled.

**Comment by vorporeal** [comment]
@bradenpowers Just to clarify, an uninstall and reinstall of the app fixed the issue?

**Comment by bradenpowers** [comment]
Yes. It fixed the issue
