### ISSUE TITLE
<alt-`> <alt-u> <alt-U> not working in editor

### ISSUE THREAD

**Issue by xcpky** [warpdotdev/Warp#1454]
### Describe the bug

```text
I'm using helix-editor (inspired by kakoune). There are key commands combined with alt key. Most of them work after I set my option key as meta. However some of them, such as <alt-`> <alt-u> <alt-U>, still don't work.
```

### To Reproduce

1. install helix
2. try the key command <alt-u> <alt-U> <alt-`>

### Expected behaviour

```text
the key commands work
```

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.05.30.09.10.stable_02

### Additional context

```text
I tried showkey -a. When I enter those 3 key combination, nothing echos before I enter another key.
```

**Comment by elviskahoro** [comment]
THanks! Will circle back when there are updates

**Comment by dannyneira** [comment]
Hi Folks, This issue has been resolved in the latest version of Warp. Closing as resolved, but please update Warp and let us know if the issue persists.
