### ISSUE TITLE
Selecting multi blocks

### ISSUE THREAD

**Issue by JuHyung-Son** [warpdotdev/Warp#146]
### Is your feature request related to a problem? Please describe.

```shell
I hope i can choose, copy, share multiple blocks.
```

### Describe the solution you'd like?

```shell
shift + cmd + up choose multi blocks.
```

### Additional context

I hope multiple blocks have to be able to share.

**Comment by willosbourne** [comment]
I'd also love this. It was one of the first things I tried to do in Warp, I think it would be really helpful for quickly sharing multiple steps for things like git practices or project setup!

**Comment by elviskahoro** [comment]
The 'Share' function would definitely become a lot more useful if it's possible to share multiple Warp blocks at the same time. I can envision that people would even put these kinds of screenshots in blog posts, tutorials, and other articles, just like they'd do with regular code blocks/embeds.

So naturally, if you're able to implement a multi-select and a range-select (holding down Cmd for the multi-select, Shift for the range-select), using both the arrow keys and the mouse, that would be the cherry on top ✌
Alternatively, transitioning Warp into a multi-select mode where you could just move between all blocks and select them to mark them as „please do add this block to the share as well”, just like when you start sharing a photo on your iPhone from within the Photos app where you can slide through all your photos and simply select them as well — or even closer to what I'm proposing would be clicking „Select” in the top right corner of your iPhone Photos app.

**Comment by tyliec** [comment]
👍 I would also like this functionality

**Comment by elviskahoro** [comment]
@tyliec & people following this issue. We have support for multi-Block selection. So I'm gonna close this actually! See #873 for sharing multiple Blocks.
