### ISSUE TITLE
Clear blocks cause input box to stop working

### ISSUE THREAD

**Issue by jonbuffington** [warpdotdev/Warp#1462]
### Describe the bug

```text
After starting a long-running process, e.g. vim, and executing Warp's Clear Blocks command, the input for the long-running process becomes unusable.
```

### To Reproduce

Steps to reproduce:
1. Start with a new session
2. Execute `vim .zsh_history`
3. Execute the Clear Blocks command.
4. Only CRTL-D will cause Warp to render something but the result is not predicable. In the case of vim, the vim process needs to be killed before the Warp prompt returns.

### Expected behaviour

```text
If I Clear Blocks, lines that are offscreen are truncated and the process still accepts input. This is the behavior in Apple's Terminal.app for example.
```

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.05.30.09.10.stable_02

**Comment by michlimlim** [comment]
Thank you for the report! By 'Clear Blocks command', you mean Cmd-K right?.

**Comment by dannyneira** [comment]
Thanks for your feedback, we've been able to repro this one and will post any updates here.

**Comment by jonbuffington** [comment]
@dannyneira The undesired behavior I was referring to, the Text Editor Input became unavailable/unstable, was repaired in later builds. You are correct that the output visual matches Apple's Terminal. I did not mean to imply the output needed to change; I just wanted to continue to use the Text Editor Input after using CMD-K.

**Comment by dannyneira** [comment]
I appreciate you clearing this up @jonbuffington! Please reopen this issue if you find the problem has come back. Thanks for your patience and response!
