### ISSUE TITLE
Settings window cannot be dismissed with the escape key under certain conditions

### ISSUE THREAD

**Issue by JasonDiBabbo** [warpdotdev/Warp#1466]
### Discord username (optional)

Monster Abe#1001

### Describe the bug

```text
There are certain conditions that when triggered prevent the settings window from being dismissed using the escape key.
```

### To Reproduce

Steps to reproduce:
1. Go to a warp console window
2. Open the settings modal (⌘ + ,)
3. Click on the "Keyboard shortcuts" tab
4. Click on any other tab
5. Press escape

### Expected behaviour

```text
When pressing the escape key in scenarios where input is not being otherwise captured, the escape key should dismiss the settings window.
```

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.05.30.09.10.stable_02

**Comment by elviskahoro** [comment]
Thanks for reporting.
Gonna close this since we have:
#503 #223 #1330
