### ISSUE TITLE
Enable Terminal Graphics Protocol

### ISSUE THREAD

**Issue by oaklandgit** [warpdotdev/Warp#1467]
### Describe the solution you'd like?

```text
The ability to view graphics in the terminal. Some use cases:
* list thumbnail images in a directory
* process images in the terminal (e.g. using ImageMagick) and then seeing the output without needing to switch to the OS GUI
```

### Is your feature request related to a problem? Please describe.

```text
I'm always frustrated when I need to leave the terminal in order to view an image.
```

### Additional context

Recommended protocol:
https://sw.kovidgoyal.net/kitty/graphics-protocol/

Example projects that use it:
https://github.com/atanunq/viu
https://github.com/mirukana/pixcat

**Comment by elviskahoro** [comment]
Thanks for reporting. Gonna close this in favor of #26

**Comment by oaklandgit** [comment]
Thank you
