### ISSUE TITLE
Add setting to disable the blinking cursor

### ISSUE THREAD

**Issue by diocletiann** [warpdotdev/Warp#1468]
### Describe the solution you'd like?

```text
There is no way to disable the blinking cursor in the app and I'm not aware of an OS-level setting in MacOS.

I would like a toggle for a solid cursor.
```

**Comment by elviskahoro** [comment]
THanks! Will circle back when there are updates

**Comment by dpolivaev** [comment]
Hey, are there any updates? This issue is very important for people with some brain disabilities who can not easily ignore the blinking cursor. Improvement here is a great deal of inclusion.

**Comment by dannyneira** [comment]
Hi @dpolivaev Thanks for letting us know! We're sorry about this, this is not an ideal experience. There are no plans for this on the roadmap, but I can see how it's a major issue, I will bring it up with the team and circle back with any updates.

**Comment by restfuladi** [comment]
I for one find it very hard to read while something is blinking. And I'd say 95% of my terminal time is spent reading.

**Comment by zhanghaotongxue** [comment]
The blinking cursor impacts me, I always focus on it, I hope add the disable blinking cursor settings.

**Comment by arcadefx** [comment]
+1 on the blinking cursor. I like the App, but I had to go back to iTerm2 due to the blinking.

**Comment by RykZee** [comment]
+1 on the blinking cursor, was the first thing I tried to disable.

**Comment by elviskahoro** [comment]
This came out today!
![CleanShot 2023-01-13 at 01 23 30@2x](https://user-images.githubusercontent.com/29553206/212284719-7452348b-0392-4222-8041-704cc37b34c7.png)
