### ISSUE TITLE
Can’t open Warp.

### ISSUE THREAD

**Issue by Jonathan0827** [warpdotdev/Warp#1474]
### Describe the bug

```text
I can’t open warp on macOS Ventura beta
```

### To Reproduce

Steps to reproduce:
1. Install macOS Ventura
2. Open Warp

### Expected behaviour

```text
Fix the bug
```

### OS Version

13.0

### Shell Version

Latest version if zsh

### Warp Version

Latest version

**Comment by ayush5harma** [comment]
same issue here on macos ventura

**Comment by hrbrmstr** [comment]
Dup of #1463
