### ISSUE TITLE
Bot Workflow to Update Homebrew Creating Conflicts

### ISSUE THREAD

**Issue by bevanjkay** [warpdotdev/Warp#1476]
### Describe the bug

```text
I am a maintainer for Homebrew-Cask and the @warpdotdev-dx workflow that bumps the `warp` cask in https://github.com/homebrew/homebrew-cask is creating a conflict every time a PR is opened.
I would suggest it is likely because the homebrew tap is not being updated before running the `brew bump-cask-pr` command - meaning the commit head is behind.
```

### To Reproduce

https://github.com/Homebrew/homebrew-cask/pull/125049

### OS Version

N/A

### Shell Version

N/A

### Warp Version

N/A

**Comment by alokedesai** [comment]
Thank you for flagging! Will make sure to get this fixed asap

**Comment by bevanjkay** [comment]
@alokedesai This issue still seems to be occurring - https://github.com/Homebrew/homebrew-cask/pull/125953#pullrequestreview-1011235181
