### ISSUE TITLE
When alias `ll` ,`tab-key` can't call autocomplete 

### ISSUE THREAD

**Issue by h4rk8s** [warpdotdev/Warp#1477]
### Describe the bug

```text
When alias `ll` ,`tab-key` can't call autocomplete
```

### To Reproduce

Steps to reproduce:
1. set alias
2. any folder in warp terminal
3. input: `ll $target_dir`
4. enter `tab` key, can't call autocomplete 

### Screenshots

![case](https://user-images.githubusercontent.com/63350517/172757088-1b8f8e8a-a0b8-40eb-b91b-c85bcb3ed8a9.png)

### OS Version

12.4

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Warp Version

v0.2022.06.06.09.05.stable_01

**Comment by randy** [comment]
Happens for any alias. This is basically a block and I won't be using Warp until it's fixed. I'm an older OS, but I believe that's moot. The feature just isn't there.

**Comment by h4rk8s** [comment]
> 

yep. Not to mention that warp does not support certain settings of fzf, but if I set up a list of directories that are not ls, even ll ~/Downl-o-a-d-s is not supported, it is a bit funny, so I can only be "forced" to use such advanced cd as enhancd. hey ~ questions also I'll have to fix it myself sometime. Thank you for your reply!

**Comment by h4rk8s** [comment]
yep. Not to mention that warp does not support certain settings of fzf, but if I set up a list of directories that are not ls, even ll ~/Downl-o-a-d-s is not supported, it is a bit funny, so I can only be "forced" to use such advanced cd as enhancd. hey ~ questions also I'll have to fix it myself sometime. Thank you for your reply!

**Comment by elviskahoro** [comment]
Thanks for reporting. There should be significant enhancements regarding command entry over the next 2 quarters!

**Comment by elviskahoro** [comment]
@h4rk8s @randy do you use any zsh plugins or omz? It also looks like you're using syntax highlighting?

**Comment by h4rk8s** [comment]
@elviskahoro yes 👇 is my plugin.
Plugin loading times:
   17 ms - zsh-users/zsh-syntax-highlighting
    1 ms - OMZ::lib/grep.zsh
    2 ms - djui/alias-tips
    2 ms - romkatv/gitstatus
    4 ms - mafredri/zsh-async
   22 ms - skywind3000/z.lua
    5 ms - b4b4r07/enhancd
    4 ms - seletskiy/zsh-fuzzy-search-and-edit
    4 ms - b4b4r07/zsh-history
    1 ms - mattmc3/zsh-safe-rm

**Comment by alokedesai** [comment]
Elvis is correct if this only happens for the `exa` command. @h4rk8s are you experiencing this for _all_ aliases or only specific ones?

**Comment by h4rk8s** [comment]
> Elvis is correct if this only happens for the `exa` command. @h4rk8s are you experiencing this for _all_ aliases or only specific ones?

only `exa` alias `ll` and native `exa` both support DIR auto complete

**Comment by alokedesai** [comment]
@h4rk8s Just to confirm, you're saying `exa` never completes directories? If I'm in a directory that has 3 subdirectories, I see all of them when I type `exa <tab>`. 

Are you not seeing that?

**Comment by h4rk8s** [comment]
> @h4rk8s Just to confirm, you're saying `exa` never completes directories? If I'm in a directory that has 3 subdirectories, I see all of them when I type `exa <tab>`.
> 
> Are you not seeing that?

yes , when typeing `exa` , if empty args , can complete , it's OK. if typeing `exa --long --header`, it's OK. if typeing `exa --long --header --time-style long-iso --sort time --reverse --all --git` , it's NOT OK. clearly saying：

1. `exa` OK
2. `exa --long --header` OK
3. `exa --long --header --time-style long-iso --sort time NOT OK

I think if command `exa`after with key=value argments , it's NOT OK . 

@alokedesai

**Comment by h4rk8s** [comment]
@alokedesai 

I had a temp solution
```
export TIME_STYLE='long-iso'
alias ll="exa --long --header --reverse --all --git"
```

And build exa from git settings (exa/src/options/filter.rs):
```
/ You can get the old behaviour back by sorting with `--sort=Name`.
impl Default for SortField {
    fn default() -> Self {
        Self::Name(SortCase::AaBbCc)
        //Self::Name(SortCase::AaBbCc)
        Self::ModifiedDate
    }
}

```

it's works for me ~

**Comment by alokedesai** [comment]
Hey @h4rk8s@ Thanks for your patience, we have a fix for that just went in today. We expect it to be in next week's release (going out next Thursday). Will follow up next once it's been released

**Comment by alokedesai** [comment]
@randy A release should be coming out today that has a fix for this. Would you mind verifying once it's released? Thanks!

**Comment by randy** [comment]
@alokedesai, sorry for the late reply, but unfortunately, no, it didn't fix it. 

Steps:

1. Open Warp.
2. Type "ex"
3. Notice the pre-filled auto-complete(?) of "exit"
4. Hit Tab

Expected: "exit" is auto-completed
Actual: a popup comes up and "exit" isn't the first or last or "auto-selected" option (i.e., nothing easy to use).
![image](https://user-images.githubusercontent.com/22246488/196419960-bbbc910a-a3dd-4297-9030-85adeb01ee7a.png)


If this is unrelated to the issue, that's fine. Even if this is expected, that's fine, too. I've already stated why I probably won't adopt Warp... It's like switching IDEs.

**Comment by alokedesai** [comment]
@randy Thanks for this feedback! Unfortunately, only right arrow autocompletes the ghosted text right now. 

We're actively working on improving this UX and hope to have a fix for this in the coming weeks.
