### ISSUE TITLE
Cannot acknowledge split pane welcome tip, shortcut missing

### ISSUE THREAD

**Issue by miles-cloudlead** [warpdotdev/Warp#1478]
### Describe the bug

```text
I cannot complete the split pane welcome tip in the same way as the other tips and the shortcut is missing. I discovered the split pane shortcut in the command palette and after using it the split pane welcome tip completed.
```

### To Reproduce

Steps to reproduce:
1. Log into warp having not completed welcome tips.
2. Open welcome tips.
3. Observe split pane tip has no shortcut.
4. Attempt to complete the split pane tip by clicking on it.
5. Observe nothing happens.

### Expected behaviour

```text
The shortcut is visible and upon clicking the tip, the functionality is demonstrated.
```

### Screenshots

https://user-images.githubusercontent.com/92437649/172795860-becf78f1-846d-4473-9640-c862718ee910.mov

### Operating System

MacOS

### OS Version

11.6

### Shell Version

zsh 5.8 (x86_64-apple-darwin20.0)

### Warp Version

v0.2022.06.06.09.05.stable_01

**Comment by kevinyang372** [comment]
Should be fixed now!
