### ISSUE TITLE
Get rid of scroll bar and support hiding tab bar at the top, please!  Also adding transparency support would be perfect.

### ISSUE THREAD

**Issue by mhwgoo** [warpdotdev/Warp#1479]
### Describe the solution you'd like?

```text
For people not using a mouse, those elements are redundant.
```

**Comment by elviskahoro** [comment]
Thanks for reporting. These have all been reported before so I'm gonna close.
Off head checkout:
#017

**Comment by arglin** [comment]
https://github.com/warpdotdev/Warp/issues/17 is about transparency, but this ticket also mentioned **Get rid of scroll bar and support hiding tab bar at the top**. Please reopen this ticket.

**Comment by aarnnavds** [comment]
Yeah the scrollbar and ugly tab bar are the only things stopping me form using warp over iterm2
