### ISSUE TITLE
CB: Missing Characters under Tmux/zsh-prezto theme

### ISSUE THREAD

**Issue by Blitz2145** [warpdotdev/warp#148]
### Describe the bug

```shell
When I switch from Hack default font over to Monaco font through settings, my prompt prefix characters disappears.
```

### To Reproduce

Steps to reproduce:
1. Install prezto (with default sorin theme) and tmux for zsh.
2. Run `tmux` to open new session
3. Switch from Hack to Monaco font in Settings.
4. Prompt prefix characters are missing.

### Expected behaviour

```shell
Characters should be displayed.
```

### Screenshots

![image](https://user-images.githubusercontent.com/1255031/131003522-2113fdf1-96c8-41f4-8ede-69df2cf463ce.png)
![image](https://user-images.githubusercontent.com/1255031/131003565-51581319-570a-4e64-b442-a547d4c29076.png)

### Operating System

MacOS

### OS Version

11.5.2

**Comment by zheng** [comment]
Excellent report, thank you! we will investigate why the chevron doesn't show for this font

**Comment by elviskahoro** [comment]
@Blitz2145 is this still happening/

**Comment by elviskahoro** [comment]
@zheng just following up!

**Comment by Blitz2145** [comment]
@elviskahoro Yup, still happening, actually now even with Hack font, my prompt does not show. On latest stable warp:
![image](https://user-images.githubusercontent.com/1255031/142516733-945f8b58-5b46-4528-808d-6ee885d42a9f.png)

**Comment by elviskahoro** [comment]
@zheng !

**Comment by zheng** [comment]
Hi @Blitz2145 it’s not supposed to show in Warp (outside of tmux). Warp doesn’t yet have support for custom prompts. Customizing the prompt is a top request and it’s on our roadmap for next quarter.

Does this happen in tmux for you?

**Comment by Blitz2145** [comment]
@zheng Cool, this issue is fixed now, I can see the prompt characters now.

**Comment by zheng** [comment]
Awesome! 😄
