### ISSUE TITLE
WARNING: Log in  warp signs you up to spam lists

### ISSUE THREAD

**Issue by badders** [warpdotdev/Warp#1484]
### Describe the bug

```text
Signed in to warp with my github account to try it out, started getting spam emails from warp, unsubscribed - then continued to get spam emails from DevNetwork (never heard of or signed up for)
```

### To Reproduce

Steps to reproduce:
1. Sign in with github
2. receive spam

### Expected behaviour

```text
Sign up not required
Sign up doesnt add you to spam lists
```

### Operating System

MacOS

### OS Version

11.4

### Shell Version

zsh

### Warp Version

recent

**Comment by elviskahoro** [comment]
Hey @badders,

Thanks for the feedback.

Wanted to write and let you know that we do not sell or exchange any data. TBH I’m not even sure who DevNetwork is. 

Our business model is that we are free for everyone for now and will eventually experiment with different premium features for enterprise. The general philosophy is that we would never charge for anything a terminal currently does. So no paywalls around ssh or anything like that.The types of features we could eventually charge for are things that have a cost to us, like for example keeping an infinite searchable command history, or enabling real-time terminal collaboration. Even those though would probably be free to some level of usage and only charged in a company context.
We’ve written in more detail here <https://docs.warp.dev/getting-started/privacy> and also here: <https://www.warp.dev/privacy>

The first link also articulates how we’re thinking about login and also has an exhaustive list of the telemetry that we collect (only metadata never console input or output).
