### ISSUE TITLE
Allow disabling of auto brace/quote/etc matching

### ISSUE THREAD

**Issue by pzoomin** [warpdotdev/Warp#1485]
### Describe the solution you'd like?

If I enter an opening `(`, `"`, or perhaps other opening brace (don't know the exhaustive list), warp automatically adds the closing/matching `)`, `"`. 

While I understand some people find it helpful, for me it just causes a lot of invalid commands -- eg I'll type `rg -foo` looking to match the literal `-foo`, then realize I need to wrap that in quotes. Since I'm at the end of the line, I start with adding a quote there, but I don't notice it adds two quotes instead of one, so I end up with `rg "-foo""`, which is invalid.

I'd like at least one of several options:
- the ability to turn this off, since I don't find it particularly useful
- a better explanation of how this is supposed to work -- maybe there's some shortcut key to wrap with quotes after I've already typed some text? There might be, but I have no idea how to discover that -- AI command search doesn't help, cmd-P doesn't seem to have anything relevant, and docs.warp.dev doesn't seem to have anything on this.
- maybe some other customization? For instance, maybe it turns out this feature is useful for parenthesis, but not quotes -- would be nice to selectively enable/disable.

**Comment by pzoomin** [comment]
Ah, thank you!

**Comment by lucifiel1618** [comment]
disabling the feature does nothing for me.

**Comment by sfanous** [comment]
Using v0.2022.11.14.14.55.stable_01

Disabling the feature does not stop warp from autocompleting quotes/parantheses/bracket.
