### ISSUE TITLE
Fish autosuggestions don't work

### ISSUE THREAD

**Issue by PeterCardenas** [warpdotdev/Warp#1488]
### Discord username (optional)

pizzapete#9178

### Describe the bug

Fish provides autosuggestions that you can select with right arrow when at the end of the input and are shown in lower opacity. Warp seems to have the fish shell running, but does not support this feature. I have wrapped every file in .config/fish with if test $TERM_PROGRAM != WarpTerminal, but the issue persists.

### To Reproduce

Steps to reproduce:
1. Type 'ls'
2. Check whether autocomplete shows up

### Expected behaviour

```text
It should show the last ls command I put.
```

### Screenshots

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/16930781/173185360-2cd27d1a-a00b-473e-ac56-e6e460b3645c.png">

### Operating System

MacOS

### OS Version

12.4

### Shell Version

fish 3.4.1

### Warp Version

v0.2022.06.06.09.05.stable_01

### Additional context

```text
I have recently switched to fish from zsh and installed Starship with fnm. I also have Fig installed.
```

**Comment by nanthony007** [comment]
I think this is a duplicate of #1177

**Comment by PeterCardenas** [comment]
Oh I don't see any autosuggestions for fish. Are fish autosuggestions turned off by Warp? I was under the impression that fish support entailed that.

**Comment by alokedesai** [comment]
Is it possible you have autosuggestions turned off? Mind running the "toggle autosuggestions" command in the command palette to see if that changes anything?

**Comment by PeterCardenas** [comment]
Ah I thought by autosuggestions you meant the autocomplete window, my mistake. That seemed to work! Thanks a bunch

**Comment by alokedesai** [comment]
Glad to hear! Thanks for following up!
