### ISSUE TITLE
Support macOS High Sierra

### ISSUE THREAD

**Issue by hronro** [warpdotdev/Warp#1490]
### Describe the solution you'd like?

```text
It would be very nice if Warp supported macOS High Sierra (macOS 10.13).
```

**Comment by alokedesai** [comment]
Hey @hronro, thank you for flagging. Could you elaborate on what the issues you are seeing with Warp on High Sierra? Thanks!

**Comment by hronro** [comment]
@alokedesai 

It simply can't run on High Sierra.

![CleanShot 2022-06-15 at 14 19 11](https://user-images.githubusercontent.com/15059605/173756380-a6c15fda-9c9d-4c6e-bb3d-a29c45c00e66.png)

**Comment by warpdotdev-dx** [comment]
Pretty sure it requires mojave because of the notifications API.

**Comment by elviskahoro** [comment]
It does require some mac APIs that were launched in 14.0
