### ISSUE TITLE
Render and Layout issue with ZSH git plugin

### ISSUE THREAD

**Issue by nodexchange** [warpdotdev/Warp#1491]
### Discord username (optional)

mars

### Describe the bug

```text
With ZSH and Git plugin enabled, any folder shifts the layout and automatically adds the time stamp to the command-line.

The cursor focus lands after the git date.

Full .zshrc:
`
# export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="/Users/marcin.wotjala/.oh-my-zsh"

ZSH_THEME="avit"

plugins=(git git-flow-completion)

source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
alias vscode="/Applications/Visual\ Studio\ Code.app/contents/Resources/app/bin/code"

export PNPM_HOME="/Users/marcin.wotjala/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
`
```

### To Reproduce

Steps to reproduce:
1. Install latest version of the terminal
2. Run it via ZSH
3. Ensure git theme ZSH_THEME="avit" is installed
4. .zshrc to also have plugins=(git git-flow-completion)

### Expected behaviour

```text
The Git timestamp should not be prefilled to the terminal's command line
```

### Screenshots

<img width="1024" alt="Screenshot 2022-06-13 at 09 28 19" src="https://user-images.githubusercontent.com/16758689/173313004-964967a7-311b-47e2-a33e-6e5b0800afab.png">
<img width="998" alt="Screenshot 2022-06-13 at 09 28 09" src="https://user-images.githubusercontent.com/16758689/173313029-1dc91c2a-c766-4c14-920a-700426b087eb.png">

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.06.06

**Comment by rlataguerra** [comment]
Can confirm, same configuration and same behavior here

**Comment by elviskahoro** [comment]
Gonna close in favor of #936
