### ISSUE TITLE
Hotkey window does not honor active screen

### ISSUE THREAD

**Issue by simerlec** [warpdotdev/Warp#1495]
### Describe the bug

As per request from https://github.com/warpdotdev/Warp/issues/862#issuecomment-1154086582 I opened up a new bug report. 

The hotkey window does not honor the currently active screen for me. It always opens up on the screen that warp was started on.

As a matter of fact the dropdown setting for the active screen does nothing at all. The dropdown shows me 2 options to select from but it always opens on the internal screen not the external one, even if set.

### To Reproduce

Steps to reproduce:
1. Enable hotkey window
2. (optional) Set custom hotkey
3. Focus Desktop 1
4. Press hokey shows hotkey window
5. Focus Desktop 2 (on external monitor)
6. Press hotkey shows hotkey window on Desktop 1

### Expected behaviour

```text
Press hotkey after the active screen changed should show the hotkey window on the currently active screen.
```

### Screenshots

Setting in Warp
![image](https://user-images.githubusercontent.com/5793380/173395200-5db0fc30-8d53-4cbd-89ce-05c46428e3dd.png)

### Operating System

macOS

### OS Version

12.3.1 (21E258)

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.06.06.09.05.stable_01

### Additional context

I also enabled/disabled the feature - to see if a reset helps, but to no avail.

**Comment by wesleylether** [comment]
Exact same as @simerlec describes. I have the same versions above!

**Comment by simerlec** [comment]
seems to be working with the latest version `v0.2022.06.27.09.14.stable_01`

**Comment by wesleylether** [comment]
Just tested on version `v0.2022.06.27.09.14.stable_01` does not work like expected.

Like iTerm it looks on with screen the mouse is en there it will pop open. This is not the case even with this version.

**Comment by wesleylether** [comment]
I finally fixed it! @warpdotdev-dx  Handy to know:
When I enabled the "Displays have separate Spaces" in Max OS. The active screen is working!

But it would still be better if warp will look at the mouse position on witch screen it is. :)
