### ISSUE TITLE
Remove the shortcut suggestion from background and make it clear.

### ISSUE THREAD

**Issue by M0hammad-Kashif** [warpdotdev/Warp#1497]
### Discord username (optional)

kashif#7541

### Describe the solution you'd like?

```text
Give us an option to hide or unhide the shortcuts displayed in background.
```

### Is your feature request related to a problem? Please describe.

```text
Its a feature that will improve the aesthetics of the terminal(warp).
```

**Comment by alokedesai** [comment]
Hi there! Thanks for the feedback. We actually already support this within the settings. The name of the feature is "Shortcut screen on new tab"

I'm going to go ahead and close this out, but feel free to reopen if you're still seeing issues with this!
