### ISSUE TITLE
Command History doesn't show latest command

### ISSUE THREAD

**Issue by luisAzcuaga** [warpdotdev/Warp#1499]
### Describe the bug

```text
As the title suggest opening **Command history** doesn't always show the latest command.
```

### To Reproduce

1. I write a command on a single tab window.
2. I hit `UP arrow`.
3. Warp opens command history but most of the time shows the command I've been using recently but no the last.

### Expected behaviour

```text
Hit UP arrow and get the latest commands.
```

### Screenshots

Last command was: `rspec spec/models/absence_notification_spec.rb`
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/37643667/173672377-db6580fe-91bd-46d8-9843-9e0713c770d0.png">

I hit arrow up and:
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/37643667/173672484-ddef6cac-5a13-45c0-970f-b300b3b2e12c.png">

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.06.06.09.05.stable_01

**Comment by elviskahoro** [comment]
Hey!

The underlying issue is that we don't support right sided prompts and so they're leaking into the input editor.
Check out our docs!
https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files

Gonna close in favor of #936
