### ISSUE TITLE
Support functions

### ISSUE THREAD

**Issue by zheng** [warpdotdev/Warp#150]
### Is your feature request related to a problem? Please describe.

```shell
Add completions for shell functions
```

### Describe the solution you'd like?

```shell
^
```

### Additional context

^

**Comment by neeravp** [comment]
@zheng Just want to check if autocompletion for shell functions is in-progress or planned for near future? Can you please provide any update on the current status with regards to the priority?

Thanks

**Comment by zheng** [comment]
Hi @neeravp, we haven't heard a ton of reports for this so it hasn't been prioritized. Is this a blocker for you?

**Comment by zheng** [comment]
Thanks for the detailed feedback!

We recently have made progress on an issue where defining a lot of aliases caused issues for bootstrapping being slow, so I think we're a bit closer to being able to resolve this.

cc @alokedesai and @charlespierce who have been working on completions

**Comment by ubamrein** [comment]
We also use plenty of custom functions and auto completion for it in `zsh`. I use them on a daily basis and them not working means I cannot use warp right now. Since I love all the other features around warp, I am also eagerly awaiting support for "custom" auto completion :)

**Comment by tokestermw** [comment]
Agree with above. This is a blocker for using Warp currently. 🙂

**Comment by dmorda** [comment]
I also use functions quite extensively, but without auto-completion I can't remember most of the names. I'm able to get by for now, but this would be a big win for me adopting Warp.

**Comment by alokedesai** [comment]
Hey all, thank you for your patience here. Marking this closed as we should support completions for functions in the latest release (support for shell builtins coming soon). Please let us know if this is not working correctly for you on the latest version of Warp!
