### ISSUE TITLE
Input Editor: Prompt overlapping output when running multiple pasted commands

### ISSUE THREAD

**Issue by itsmingjie** [warpdotdev/warp#151]
### Describe the bug

See screenshot -- after pasting multiple commands in bash, the outputs of all these commands have prompts slightly overlapping the output content.

### To Reproduce

Steps to reproduce:
1. bash
2. paste in multiple lines of command in one go, and execute them all

### Expected behaviour

```shell
The prompt line should have the correct line height/offset from the output.
```

### Screenshots

![image](https://user-images.githubusercontent.com/13333578/131463769-4ee1a42f-a32e-45b7-b546-4eca9b42c7d9.png)

### Operating System

MacOS

### OS Version

12.0b6

**Comment by zheng** [comment]
Thanks for filing! We've noticed this regress recently & are solving related issues on terminal sizes. I think this one will also get prioritized soon

**Comment by elviskahoro** [comment]
@itsmingjie I think this is fixed. Can you reopen + comment if not?
