### ISSUE TITLE
Prompt focus after rename

### ISSUE THREAD

**Issue by schophil** [warpdotdev/Warp#1510]
### Describe the solution you'd like?

```text
After renaming a tab, the prompt of that tab should receive focus.
```

### Is your feature request related to a problem? Please describe.

```text
I use cmd-p to execute "rename tab". 
Focus is transferred to tab.
After renaming the tab and pressing enter, the focus is lost. 

I would expect the focus to switch to the prompt again. This avoid using the mouse.
```

**Comment by elviskahoro** [comment]
Thanks for reporting.
I can't seem to repro this. Can you share a video?
When i try this the focus does go back to the input

**Comment by schophil** [comment]
It seems to work in the latest version. Guess this was already a todo :-)
