### ISSUE TITLE
Lazygit sometimes does not come back after external commit command

### ISSUE THREAD

**Issue by Bringoff** [warpdotdev/Warp#1511]
### Describe the bug

```text
In my git flow I use https://github.com/jesseduffield/lazygit, https://github.com/zyedidia/micro and some hooks.
I always use lazygit command "commit changes with external git editor" because lazygit itself does not honor commit message hooks. 
And when after a successful commit I try to return to lazygit, I often get just a blank screen. 
Didn't happen a single time with Iterm, so I suppose it has something to do with Warp's terminal UI support.
```

### To Reproduce

Steps to reproduce:
1. From opened lazygit, perform "commit changes with external git editor"
2. Wait for pre-commit hook to finish (gradle task in my case)
3. Write commit message in micro, that pops up after hook finishes successfully
4. Press "Enter" when "Press Enter to return to lazygit" prompt appears

### Expected behaviour

```text
Lazygit should open, but sometimes I just get blank Warp tab instead
```

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.06.13.09.15.stable_00

**Comment by elviskahoro** [comment]
Thanks for reporting. will circle back when there are updates!

**Comment by hungtranphan** [comment]
I have the same problem. Steps to reproduce: From opened lazygit, I commit some files -> husky automatic run -> some files fail lint -> I press "Enter" when "Press Enter to return to lazygit" prompt appears -> I always get blank Warp tab, cannot type anything.


Operating System
MacOS

OS Version
11.7

Shell Version
zsh 5.8 (x86_64-apple-darwin20.0)

Warp Version
v0.2022.09.27.08.11.stable_00

**Comment by mintyPT** [comment]
I think we can all agree this is an issue with warp, at least it seems like it. When I replicate the behavior both in iTerm and warp, only warp freezes.

**Comment by cfurrow** [comment]
A current "workaround" is to use a terminal multiplexer, like [zellij](https://zellij.dev/) (or possibly [tmux](https://github.com/tmux/tmux/wiki)). Running lazygit from inside of zellij does not seem to have the same issues as running lazygit directly in warp.

**Comment by cfurrow** [comment]
It may be the case that https://github.com/warpdotdev/Warp/issues/833 has fixed this current issue as well! In my own testing, I could use lazygit within warp (not in a sub shell, or multiplexer), and I was able to commit changes and not have lazygit return a blank screen back.

Would be curious if other people have the same experience as me!

**Comment by dannyneira** [comment]
Thanks for letting us know @cfurrow 
@Bringoff are you seeing the same fix in lazygit after the most recent update to Warp?

**Comment by Bringoff** [comment]
I've been trying the latest update with lazygit today, no black screen so far.

**Comment by vorporeal** [comment]
Glad to hear it's working as expected now!  Going to close out this issue, but don't hesitate to re-open it if things aren't working for you on the latest version!

**Comment by alfonsocj** [comment]
👋 I'm getting exactly this issue now on Warp `v0.2024.12.03.08.02.stable_04` and lazygit `0.44.1`.

**Comment by ManeFunction** [comment]
Can confirm this back on Warp `v0.2024.12.10.15.55.stable_04` and lazygit `0.44.1` :(

**Comment by szgupta** [comment]
Hey folks, sorry for the issues here. It looks like lazygit is not responding well to resize and so the change in padding between the blocklist and alt-screen is causing rendering problems.

I'll send a patch to ensure that lazygit doesn't use custom padding and that should solve the issue -- that should be released tmrw. For anyone blocked in the meantime, you can follow the instructions here to disable custom padding in the alt-screen: https://docs.warp.dev/features/full-screen-apps#how-to-access-it-1
