### ISSUE TITLE
Warp not shown in an App with fullscreen when pressed on the global hot keys

### ISSUE THREAD

**Issue by putchi** [warpdotdev/Warp#1512]
### Describe the bug

```text
When you wish to open Warp (using the global hotkey feature) while you are working in an app that is in full screen mode and on your main display, Warp will not be opened or focused!.
```

### To Reproduce

Steps to reproduce:
1. On your main display monitor (if you use more than 1 monitor)
1. Go to any app and toggle 'Full screen'
2. Click on 'Your hot keys combination'
3. Error: Warp will not show.

### Expected behaviour

```text
When working in a Full screen app and you click on the hot key combo Warp has to be opened on your main focused monitor and main desktop.
```

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2022.06.13.09.15.stable_00

### Additional context

```text
This bug is acting the same on previous OS Versions as well.
```

**Comment by elviskahoro** [comment]
Thanks for reporting. Gonna close in favor of #975
