### ISSUE TITLE
Support for IBM Plex Mono font

### ISSUE THREAD

**Issue by arlo-j** [warpdotdev/Warp#1515]
### Describe the solution you'd like?

```text
I have IBM's open source Plex mono font installed, yet it doesn't show up in your supported fonts list.  I would like to use it in Warp.  Thanks!
```

### Is your feature request related to a problem? Please describe.

```text
I am unable to see IBM's open source Plex mono font in your supported fonts list, yet it is installed on my machine.
```

### Additional context

[https://github.com/IBM/plex/releases](https://github.com/IBM/plex/releases)

**Comment by elviskahoro** [comment]
Make sure to enable the checkbox: View all available system fonts
<img width="334" alt="Screen Shot 2022-06-28 at 13 50 04" src="https://user-images.githubusercontent.com/29553206/176249439-b1b34a7b-08a1-4045-a85e-60db98739fc0.png">
