### ISSUE TITLE
Ability to search tabs/sessions 

### ISSUE THREAD

**Issue by halhenke** [warpdotdev/Warp#1517]
### Describe the solution you'd like?

```text
A Command that will search existing Tabs/Sessions by directory/tab name - same as the feature in iTerm
```

### Is your feature request related to a problem? Please describe.

```text
Related to the problem of navigating large numbers of open Terminals
```

**Comment by elviskahoro** [comment]
This is a great feature idea! Something is in the works!

**Comment by vorporeal** [comment]
We now support this via the Navigation Palette!  Press Cmd+Shift+P to open the Navigation Palette, which displays all of your sessions and allows you to filter by path, running command name, git branch, and more!
