### ISSUE TITLE
cannot see command history when connecting remote host via ssh

### ISSUE THREAD

**Issue by P-CAmilE** [warpdotdev/Warp#1520]
### Describe the bug

```text
If I press ↑ on keyboard when connecting remote host via ssh, the command history does not show as expected.
```

### To Reproduce

Steps to reproduce:
1. use ssh command to connect remote host
2. press ↑ on keyboard to get command history in remote host

### Screenshots

<img width="1136" alt="screenshot of bug" src="https://user-images.githubusercontent.com/43110057/174432164-3b5f77ce-98eb-405a-9b15-923acf4d3807.png">

### OS Version

local: macOS 12.4      remote: CentOS 7.5

### Shell Version

local: zsh 5.8.1      remote: bash 4.2.46(2)-release 

### Warp Version

v0.2022.06.13.09.15.stable_01

**Comment by elviskahoro** [comment]
Thanks for reporting. Will cirlce back as we have updates!

**Comment by vorporeal** [comment]
Hey @P-CAmilE, is this still an issue for you?  If so, mind sharing the last few commands in your history?  (I'm curious whether the problem is with our rendering of the history items, as opposed to an issue retrieving history from your remote machine.)

**Comment by P-CAmilE** [comment]
> Hey @P-CAmilE, is this still an issue for you? If so, mind sharing the last few commands in your history? (I'm curious whether the problem is with our rendering of the history items, as opposed to an issue retrieving history from your remote machine.)

it is not a problem in the last version, thanks for reply :)
