### ISSUE TITLE
Copy any text inside the terminal

### ISSUE THREAD

**Issue by miguelperez** [warpdotdev/Warp#1522]
### Describe the bug

```text
It is not possible to copy the text that indicates where are you in the path. Or the text that appears as title to a command result.
```

### To Reproduce

Steps to reproduce:
1. Open a shell
I am in `~/Downloads`. In the following image the `~/Downloads` text is not copyable.
![image](https://user-images.githubusercontent.com/141042/174434540-c0d0b5d9-36a6-47ef-a028-39b20f8d29a6.png)
2. Also, when looking at the results of a command execution the first part of the block is not copyable either:
![image](https://user-images.githubusercontent.com/141042/174434614-61a7aed5-0237-454c-9857-3b745135e837.png)

It is annoying because sometimes it is faster to copy a path from the previous command this way than using the autocomplete.

### Expected behaviour

```text
Be able to copy/paste any text that appears in the terminal.
```

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.06.13.09.15.stable_01

**Comment by warpdotdev-dx** [comment]
GitHub issue for copyable prompt: https://github.com/warpdotdev/Warp/issues/36

**Comment by elviskahoro** [comment]
Thanks for reporting. Gonna close in favor of #036
