### ISSUE TITLE
Better support for custom prompts

### ISSUE THREAD

**Issue by japanese-goblinn** [warpdotdev/Warp#1523]
### Discord username (optional)

japanese_goblinn#2202

### Describe the solution you'd like?

```text
I'd like to have better support for custom prompts
```

### Is your feature request related to a problem? Please describe.

It'll be nice to have support of multi line prompts. I use [pure](https://github.com/sindresorhus/pure) prompt because it has some nice features like showing is there anything in stash or do i have something to push to remote etc. For now, none of this features exist in Warp and respecting of `PS1` also do not work.

### Additional context

This how this prompt looks in iTerm 
<img width="180" alt="image" src="https://user-images.githubusercontent.com/33631005/174448908-ed13f1bd-b0d8-44c4-844a-436952ecc7eb.png">

This is how it looks in Warp
<img width="378" alt="image" src="https://user-images.githubusercontent.com/33631005/174448792-ea510f8b-7b17-4512-8a2d-86cca4437fe4.png">

**Comment by sgiddings-kunzleigh** [comment]
I agree. Neither my `oh-my-posh` prompt or my `Starship` prompt render correctly in Warp. It is easily my biggest complaint. Starship renders well, except for the second line of the prompt is forced on to the single line. And with the nerdfont elements on my oh my posh prompt, the endings are all discolored.

**Comment by jlucktay** [comment]
Warp has trouble with my custom prompt as well.

I'm using Bash (`$BASH_VERSION` is `5.1.16(1)-release`) and I have `$PROMPT_COMMAND` pointing to a small function that sets `$PS1` with some basic logic to show git info and last exit status.

![image](https://user-images.githubusercontent.com/460028/176894259-931769cd-2e2e-4365-b911-f53118093cf1.png)

In `Settings > Features` I have `Honor user's custom prompt (PS1) setting` toggled on, and it does show my custom prompt, but every time I press the Return key it types the contents of the prompt itself into the terminal as well, so I need to Cmd+Backspace to delete the extra input and then type my next command.

![image](https://user-images.githubusercontent.com/460028/176893958-8224d4c0-21fe-440a-bc2e-38bebea01bd7.png)

If I turn off `Honor user's custom prompt (PS1) setting` then it still inputs the contents of the prompt but doesn't show anything custom any more, it just shows the current working directory by itself as the prompt.

This is how my prompt looks normally in Alacritty, VSCode, etc:

![image](https://user-images.githubusercontent.com/460028/176894760-1c5712c3-b135-44ff-974b-11be673d9c73.png)

**Comment by elviskahoro** [comment]
Thanks for reporting. We're tracking these in #1015 

Here's the context as to why: https://github.com/warpdotdev/Warp/issues/1015#issuecomment-1141464869

**Comment by elviskahoro** [comment]
Moved the discussions over. Gonna close in favor of #1015

**Comment by warpdotdev-dx** [comment]
We don't have support for multi-line prompts because our Input Editor is a separate UI element from our Prompt. This is what enables the modern text editor experience.


The goal is to improve our built in prompt so people can use that in lieu of custom prompt.
