### ISSUE TITLE
Minimized window title

### ISSUE THREAD

**Issue by japanese-goblinn** [warpdotdev/Warp#1524]
### Discord username (optional)

japanese_goblinn#2202

### Describe the solution you'd like?

```text
I'd like so that minimized in dock window of Warp will show name of selected tab in that window (like in iTerm)
```

### Additional context

This how windows with same directories opened looks like 

in iTerm
<img width="148" alt="image" src="https://user-images.githubusercontent.com/33631005/174449535-22040a97-add3-4745-aded-d626b7b376e7.png">

in Warp
<img width="221" alt="image" src="https://user-images.githubusercontent.com/33631005/174449540-b6bde358-c686-4fba-a90d-2b6c669d0bc0.png">

**Comment by elviskahoro** [comment]
Ah nice! Great callout. Thanks for reporitng!

**Comment by simschla** [comment]
It would be great to see the following as window titles (in this priority):

1. launch_configuration name (if any)
2. working directory (if any)
3. app name (Warp, fallback)

Currently, having multiple warp windows open leaves you guessing what is where, which is not a great user experience.

**Comment by simschla** [comment]
Seems to be related to #2054

**Comment by dannyneira** [comment]
@japanese-goblinn @simschla The latest update to Warp now sets the title for windows, based on the active tab/pane. Please try update then right-click on the Warp icon to see the window titles and let us know if this meets your use case/requirements.

**Comment by simschla** [comment]
@dannyneira Thank you, that is a great improvement step! 🥇 
Now, if the window is created from a launch_configuration, prefixing that launch-configuration-name to the reported window title would make me thrilled 😉

**Comment by dannyneira** [comment]
@simschla I think that's a great idea, warrants a separate FR. Please submit one here: https://github.com/warpdotdev/Warp/issues/new?assignees=&labels=Feature&template=02_feature_request.yml

@japanese-goblinn Awesome! Are we okay to close this as resolved since the titles are showing properly now?

**Comment by simschla** [comment]
@dannyneira Thanks, opened #2645

**Comment by dannyneira** [comment]
@japanese-goblinn closing as resolved, but please do reopen if the issue returns.

**Comment by japanese-goblinn** [comment]
@dannyneira yep, everything works fine
