### ISSUE TITLE
Warp often breaks when opening an SSH tunnel

### ISSUE THREAD

**Issue by DaniruKun** [warpdotdev/Warp#1526]
### Describe the bug

```text
When I open an SSH tunnel, very often Warp will simply stop responding and will need to be force quit.
```

### To Reproduce

Steps to reproduce:
1. Open a `zsh` shell in Warp
2. Open an SSH tunnel somewhere with `ssh -L ...`
3. Do this a couple times
4. Observe Warp stopping to respond

### Expected behaviour

```text
Warp does not freeze.
```

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.06.13.09.15.stable_01

**Comment by elviskahoro** [comment]
Thanks for reporting!

**Comment by chhuang789** [comment]
It's not working when I ssh to Windows OpenSSH via tunnel. I don't have the problem when using iterm2. The version of Warp is v0.2022.11.14.14.55.stable_01

ssh administrator@localhost -p 10022

At line:5 char:3
+ if test ${SHELL##*/} != bash -a ${SHELL##*/} != zsh; then
+   ~
Missing '(' after 'if' in if statement.
At line:10 char:7
+   bash) exec -a bash bash --rcfile <(echo 'set -o vi; set +o vi; HIST ...
+       ~
Unexpected token ')' in expression or statement.
At line:10 char:36
+   bash) exec -a bash bash --rcfile <(echo 'set -o vi; set +o vi; HIST ...
+                                    ~
The '<' operator is reserved for future use.
At line:12 char:6
+   zsh) WARP_TMP_DIR=$(mktemp -d warptmp.XXXXXX)
+      ~
Unexpected token ')' in expression or statement.
At line:13 char:3
+ if [[ $? == 0 ]]; then
+   ~
Missing '(' after 'if' in if statement.
At line:13 char:5
+ if [[ $? == 0 ]]; then
+     ~
Missing type name after '['.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement

Connection to localhost closed.
