### ISSUE TITLE
Command (mvn) hangs

### ISSUE THREAD

**Issue by liufuyang** [warpdotdev/Warp#1529]
### Describe the bug

Running command `mvn compile` hangs with version `v0.2022.06.13.09.15.stable_01`

### To Reproduce

Just run command `mvn compile` in a Java project folder.

### Expected behaviour

`mvn compile` finishes build or gives an error.

### Screenshots

<img width="934" alt="image" src="https://user-images.githubusercontent.com/161689/174772622-9e279827-7358-49bf-bf0f-6a0e275cdcfe.png">

<img width="631" alt="image" src="https://user-images.githubusercontent.com/161689/174772559-4caa01a3-a6de-476b-882e-38b83fa36f31.png">

### Operating System

MacOS

### OS Version

12.4

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)

### Warp Version

v0.2022.06.13.09.15.stable_01

**Comment by elviskahoro** [comment]
Ah yes! Thanks for reporting. Gonna mov ethis to #414
