### ISSUE TITLE
Warp creates a new icon in macOS Dock on Update.

### ISSUE THREAD

**Issue by AxonDragonScale** [warpdotdev/Warp#1535]
### Describe the bug

```text
In update version v0.2022.06.20.09.15.stable_02 and the one before, if warp has been added to Dock, updating creates a new icon and the old one stops working.
```

### To Reproduce

1. Add Warp to Dock.
2. Update by clicking the Update button on top right.
3.  This will create extra Warp icon and old one will stop working.

### Expected behaviour

```text
New icon should not be created, existing Dock icon should continue working.
```

### Screenshots

<img width="235" alt="Screenshot 2022-06-23 at 12 31 47 PM" src="https://user-images.githubusercontent.com/22011353/175237910-fc1d5108-0e79-4432-bbba-46ab2596784a.png">

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.06.20.09.15.stable_02

**Comment by elviskahoro** [comment]
Thanks for reporting!

**Comment by iMacTia** [comment]
Noticed the same over the past 3-4 updates and it keeps happening on each update. It's not the end of the world but it's quite annoying as you have to re-pin it and delete the old one every time

**Comment by MaHeinze** [comment]
This behavior still exists. It's a pity it is not fixed yet.

**Comment by nfiacco** [comment]
Same issue here

**Comment by HafizAhmedMoon** [comment]
Facing same issue 👀

**Comment by danulqua** [comment]
Same issue here, wanted to create an issue for it, but seems like it exists since 2022 😱

**Comment by danulqua** [comment]
Seems like it's finally fixed?
`v0.2023.10.10.08.06.stable_02` - updated and there isn't new Warp icon.

**Comment by kg-currenxie** [comment]
I just got it today, updating to `v0.2023.10.31.08.03.stable_02`

**Comment by muendelezaji** [comment]
Any updates on this issue? Just updated to `v0.2024.02.06.08.02.stable_01` and still seeing it

**Comment by mr-chetan** [comment]
Same issue every time i face
![image](https://github.com/warpdotdev/Warp/assets/56998650/145dec91-2f34-45e0-a3fb-cd85449cf0bb)

**Comment by sphvn** [comment]
Just updated to `v0.2024.05.21.16.09.stable_02` and got this exact issue.

**Comment by kg-currenxie** [comment]
lol why did the bot suddenly close this?

**Comment by alokedesai** [comment]
Hi all, thanks for flagging. This was inadvertently closed--I'll flag this to our developer support team so it doesn't happen again.

As for the underlying bug: we are actively looking into this and we believe we have a fix for this. We should have a more concrete update in the coming days.

**Comment by elviskahoro** [comment]
@kg-currenxie should be fixed now! Thanks for your patience!

**Comment by kg-currenxie** [comment]
:tada:

**Comment by alokedesai** [comment]
To be clear: @elviskahoro is referring to the issue with bot being fixed. 

We believe we have a fix for the underlying autoupdate issue, assuming no hiccups it should be fixed in next week's release.

**Comment by alokedesai** [comment]
Hi all, this should now be fixed with the latest version of Warp that was released today. Please reopen if you're still experiencing issues!

**Comment by kg-currenxie** [comment]
Updated to `v0.2024.06.04.08.02.stable_02`. No new icon! 🎉
