### ISSUE TITLE
CMD+K Shortcut in a REPL Environment Makes The Pane Completely Unusable

### ISSUE THREAD

**Issue by eldenjohn** [warpdotdev/Warp#1538]
### Describe the bug

```text
When using the cmd+k shortcut to "clear" the terminal and scrollback in a REPL environment such as python or ruby, the REPL seems to go into some kind of unusable state.  I suspect this has something to do with the way Warp tries to clear "blocks" when using cmd+k in a regular shell but because you are in a REPL that doesn't really adhere to the block paradigm, it gets confused.  

Unfortunately I use a REPL for a good portion of my workday and this is a frustrating bug that is kind a showstopper for me switching to Warp full-time.
```

### To Reproduce

Steps to reproduce:
1. Open the `python` interactive REPL
2. input some commands as a test, such as `1+3`
3. press the CMD+K keyboard shortcut to clear the terminal
4. the terminal clears, try typing any new commands

### Expected behaviour

```text
I expect the terminal to clear but then I should be able to continue using the REPL as normal.
```

### Screenshots

open the REPL, with test command:

![image](https://user-images.githubusercontent.com/25520297/175312762-2586b167-4f62-4abf-9490-2b1939910b4a.png)

after pressing cmd+k - at this point if I type anything, nothing happens:

![image](https://user-images.githubusercontent.com/25520297/175312878-e8177733-99df-4f6d-8856-00fdd8a1d877.png)

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Warp Version

v0.2022.06.20.09.15.stable_02

**Comment by beet** [comment]
Came here to report the same issue and found this existing card.

Experiencing the same thing when running a Ruby IRB _(Rails)_ console remotely on an AWS ECS environment. Hitting CMD+K clears the screen, but then causes the session to become completely unresponsive.

Have to close the Warp tab and open a new session.

Is there another way to clear the screen that doesn't cause it to freeze?

**Comment by warpdotdev-dx** [comment]
Does CTRL-L work for you?

**Comment by beet** [comment]
> Does CTRL-L work for you?

Thanks, not really, it kinda pushes the line with the prompt in it all the way to the top of the window, but if you scroll up the previous output is still there.

My use-case:

* dive into a production console to debug an issue
* poke things with sticks until I've found the likely culprit
* clear the screen
* print out a data snippet that I need to record
* use "copy output" to copy to the clipboard

When I only need to copy a small snippet, I can just drag a selection over it with the mouse which is fine, but if it's a few hundred lines for example dragging a selection that extends over the boundaries of the viewport is slow and arduous.

**Comment by eldenjohn** [comment]
yup, @beet 's workflow/use-case is pretty much exactly the same as mine

**Comment by HotFusionMan** [comment]
I have the same problem. It's with bash rather than zsh both locally and on our Linux servers, and I notice it when I'm in a `rails console` session. I mostly don't use a REPL aside from that use case.

**Comment by beet** [comment]
Just confirming that as of v0.2022.07.18.09.06.stable_01 July 20, 2022, this issue seems to be resolved for me.

Thanks!

**Comment by elviskahoro** [comment]
Thanks @beet!

**Comment by eldenjohn** [comment]
Just got the update, thank you so much!
