### ISSUE TITLE
Warp becomes unresponsive when trying to bootstrap the shell when using tailscale ssh

### ISSUE THREAD

**Issue by jazzdan** [warpdotdev/Warp#1541]
### Discord username (optional)

null#0252

### Local Shell and Version

5.8.1

### Remote Shell and Version

4.4.20(1)-release

### Operating System and Version

centos 8

### Warp Version

v0.2022.06.20.09.15.stable_02

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

Repro steps

1. Create a tailscale account
2. Install tailscale on your laptop
3. Install tailscale on a server
4. Start tailscale on that server with ssh enabled (`sudo tailscale up --ssh`)
5. `ssh` in to that server via the tailscale IP address (`ssh centos@100.89.249.32`)

What should happen:
You should be able to ssh in like normal

What actually happens:
Warp becomes unresponsive and needs to be force quite.

### Include shell xtrace output

Unfortunately I can't catch the full output because the app hangs and becomes unresponsive, but here's a screenshot of what it looks like right after the hang:
<img width="1414" alt="Screen Shot 2022-06-23 at 11 16 29 AM" src="https://user-images.githubusercontent.com/452453/175367225-e9ca6264-d622-4c94-bcf1-1dbabab56cef.png">

**Comment by jazzdan** [comment]
Here's a stacktrace from the macOS crash reporter https://gist.github.com/jazzdan/e4d580bc3a3da4958c9bb1ae3f58932b

**Comment by jazzdan** [comment]
Interestingly when I try to `ssh` in from a different terminal I get a different error:

```
dan@Dans-MacBook-Pro ~ % ssh centos@centos-test
Last login: Thu Jun 23 18:19:04 from 100.119.21.89
centos: no shell: Permission denied
Connection to centos-test closed.
```

Maybe that is what's causing the issue?

**Comment by jazzdan** [comment]
Ah, apparently tailscale ssh doesn't work on hosts with selinux. I was able to use tailscale ssh on an ubuntu host, but warp still hangs in exactly the same way when connecting to it even though the ssh session works from iterm.

**Comment by SebDanielsson** [comment]
Having the same problem here. Warp hangs when trying to SSH into my Fedora Server 36 with SELinux in permissive mode. The hang only occurs with Warps SSH wrapper enabled and Tailscale SSH combined. Not if you disable either of them.

**Comment by elviskahoro** [comment]
Tailscale's twitter mentioned that they don't have support for multiplexing. We rely on it for our wrapper. Thanks for reporting!

**Comment by SebDanielsson** [comment]
Did they tell if they plan to address this?

**Comment by jazzdan** [comment]
Hey @elviskahoro thanks for the update. Do you have a link to their tweet? I wasn't able to find it on GitHub or in their issue tracker.

**Comment by warpdotdev-dx** [comment]
Just found it!
https://twitter.com/maisem_ali/status/1541213021309001728

**Comment by dannyneira** [comment]
@jazzdan Tailscale version 1.28.0 ssh appears to be working properly in latest version of Warp.

Can you please try again and confirm if you still seeing the issue?

**Comment by jazzdan** [comment]
@dannyneira yes it appears to work, thanks!

**Comment by dannyneira** [comment]
Great! I'll close this issue out, thanks for confirming!
