### ISSUE TITLE
I can't use control + left to move the cursor of a word to the left

### ISSUE THREAD

**Issue by laotoutou** [warpdotdev/Warp#1549]
### Describe the solution you'd like?

```text
I can't use control + left to move the cursor of a word to the left, but't iterm2 and other terminal software can do it, it's a good feature.
```

**Comment by yasuf** [comment]
I'm pretty sure you can, you just have to open a new tab for the settings to be updated

**Comment by warpdotdev-dx** [comment]
I can't get CTRL-LEFT to work in iterm. Is there a specific setting that needs to be enabled for it to work?

**Comment by yasuf** [comment]
@warpdotdev-dx you have to configure it in the shortcuts tab in settings, after you configure it and open a new tab it should just work

**Comment by laotoutou** [comment]
> @warpdotdev-dx you have to configure it in the shortcuts tab in settings, after you configure it and open a new tab it should just work

how do it

**Comment by laotoutou** [comment]
https://docs.warp.dev/features/keyboard-shortcuts

This doc helped me.

Write the following configuration in `~/.warp/keybindings.yaml`
```
"editor_view:move_backward_one_word": ctrl-left
"editor_view:move_forward_one_word": ctrl-right
```

and restart warp.
