### ISSUE TITLE
Input Editor: Prompt becomes the input

### ISSUE THREAD

**Issue by 0x01BF52** [warpdotdev/warp#155]
### Describe the bug

```shell
When using zsh and powerline10k, Prompt becomes the input, which it shouldn't.
```

### To Reproduce

Steps to reproduce:
Use powerline10k with zsh

### Expected behaviour

```shell
Should be displayed in the Prompt part.
```

### Screenshots

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/25280745/131697610-620c34ac-62ac-4d3b-b9a8-05a8bc52fdf4.png">

### Operating System

MacOS

### OS Version

11.5.2

### Additional context

```shell
zsh 5.8 (x86_64-apple-darwin20.1.0)
Powerline10k
```

**Comment by zheng** [comment]
This is a known issue and top-priority for us! The prompts are currently getting interpreted as the typeahead, and we will be able to prevent this from happening

**Comment by joeshaw** [comment]
I am seeing this as well with bash, on Mac OS.  My `PROMPT_COMMAND` calls a bash function that sets the prompt, emits escape codes for the window title, and a couple other things:

```bash
function __prompt_command() {
    local exit="$?"
    if [ $exit -eq 0 ]; then
        prompt_color=${AMPLE_FG}
    else
        prompt_color=${AMPLE_RED}
    fi

    PS1="${AMPLE_FG}\\h ${AMPLE_TAN}\\w\$(__git_ps1 \" ${AMPLE_BLUE}(%s)${RESET}\")${prompt_color}\\$ ${RESET}"
    PS2="${AMPLE_FG}→ ${RESET}"

    local tilde='~'
    if [ -z "$SSH_CLIENT" ]; then
        echo -ne "\033]0;${PWD/#$HOME/$tilde}\007"
    else
        echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/#$HOME/$tilde}\007"
    fi

    history -a
}

PROMPT_COMMAND="__prompt_command"
```

**Comment by elviskahoro** [comment]
We do not support custom prompts yet. We have prompt customization in this quarter's roadmap. The core issue is that to provide the modern input editor experience we have to take over the prompt and currently unset PS1. I'm really looking forward to the custom prompt feature myself.

**Comment by joeshaw** [comment]
I'm happy to disable my custom prompt, the one that Warp uses looks great for my usage.   What's the best way to detect if I'm running under Warp?

**Comment by elviskahoro** [comment]
You can use this, in this example powerlevel is what you want to ignore.
`if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
    source ~/.config/powerlevel10k/powerlevel10k.zsh-theme
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
    (( ! ${+functions[p10k]} )) || p10k finalize
fi
`
`

**Comment by joeshaw** [comment]
Thanks for that.  Once I conditionalize away the `PS1` and `PS2` assignments, I stop getting the prompt as typeahead.
