### ISSUE TITLE
'Update Permissions' bar hides important content

### ISSUE THREAD

**Issue by ViktorJT** [warpdotdev/Warp#1551]
### Describe the solution you'd like?

```text
Make the red bar: 

- Dismissible
- Push content down instead of laying on top of it
```

### Is your feature request related to a problem? Please describe.

```text
I regularly get the "A new version of Warp is available, but Warp doesn't have permissions to update" due to my company's security protocols, and it's super frustrating that it obscures important content.
```

### Additional context

Here's an example of me trying to amend a commit message, and since I can't ever see the first line I have no clue what I'm writing:

![Image 2022-06-25 at 10 11 43 AM](https://user-images.githubusercontent.com/15237362/175765503-ea67d542-0084-49e8-adae-8eda3b316d4a.jpg)

**Comment by elviskahoro** [comment]
Thanks for reporting!

**Comment by lreto** [comment]
Agreed! See also my comment here: https://github.com/warpdotdev/Warp/issues/1631#issuecomment-1196463517
Shouldn't it be possible to just open a dialog where one can enter the username and password of an administrator user (as other applications do, i believe), instead of having to download and manually install a dmg file?

**Comment by elviskahoro** [comment]
From @ireto via #1631

> I second this. As much as I linke getting updates with new features and bugfixes, this banner is quite annoying. It should at least be possible to dismiss the banner. Also, I don't think it is necessary to update Warp manually with a dmg. Maybe I'm wrong, but can't other applications also update themselves even if the logged in user is not an administrator? These applications simply open a dialog where one can enter the username and password of an administrator user.

**Comment by marcosvm** [comment]
+1 on this issue. On my corporate laptop I can only upgrade via Homebrew because of lack of admin permissions, to during the time in between a new release is available and it shows up in Homebrew Warp becomes unusable.

**Comment by gayuna** [comment]
+1 on this issue. I reported #1537 for this too.

**Comment by elviskahoro** [comment]
Should be coming out next week!

**Comment by elviskahoro** [comment]
The fix came out today!

**Comment by marcosvm** [comment]
I just used this feature today. Thank you for putting it out.
