### ISSUE TITLE
Stuck at "Starting shell" when ssh to remote machine

### ISSUE THREAD

**Issue by Arthur-Null** [warpdotdev/Warp#1553]
### Local Shell and Version

5.8.1

### Remote Shell and Version

5.1.1

### Operating System and Version

Ubuntu 16.04

### Warp Version

v0.2022.06.20.09.15.stable_02

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

<img width="305" alt="CleanShot 2022-06-27 at 14 18 45@2x" src="https://user-images.githubusercontent.com/24970454/175872283-53d9a1e2-cee8-418c-9a77-38a35af36f40.png">
Stuck at starting shell

### Include shell xtrace output

[ssh.log](https://github.com/warpdotdev/Warp/files/8989186/ssh.log)

**Comment by mauricioklein** [comment]
Same problem here

Running Warp version: v0.2022.06.27.09.14.stable_01

**Comment by Arthur-Null** [comment]
This problem only seems to occur when I use Proxyjump configuration.

**Comment by MicePilot** [comment]
Same problem here
Warp v0.2022.07.04.09.08.stable_01 
Disabling the Warp SSH Wrapper in settings allows me to SSH.

**Comment by elviskahoro** [comment]
Thanks for all the feedback will circle back when we have updates!

**Comment by gmjuhasz** [comment]
Same issue here, do we have a solution yet?

**Comment by fedefabre** [comment]
I started with this issue today after two months of using the same ssh. I can't connect now

**Comment by gmjuhasz** [comment]
Hi @elviskahoro, thanks for jumping in!

Unfortunately the issue is still there, The input block stucks at `Starting shell...` and I can issue commands in the output block, and it works as a default shell with SSH connection. Also if I exit from remote the panel is dead, and I have to create a new one.

What is interesting, that for me it works fine with some hosts and have issues with others. What is also interesting that the host that I have trouble with is working fine for one of my colleagues. Same Warp version.

For now I just disabled the SSH wrapping option, it works like that, but obviously I lose all the awesome features of Warp like that. 😞

**Comment by elviskahoro** [comment]
Can you open a new issue using the SSH template so we can get info on remote box?
Also I'm guessing there's a difference between the config files **you** have on that machine vs your **teammates**?

**Comment by noit-arthur** [comment]
I am using the current version (v0.2023.02.14.08.05.stable_01) and have the same problem.
SSH access works only if I turn off the Warp SSH Wrapper. 
This seems to be a returning bug. Can anyone of the developers give a hint how to avoid this by different usage?

**Comment by marcin-piechaczek** [comment]
The problem started with the last update, disabling Warp SSH Wrapper fixes this problem. Proxy SSH connection.

**Comment by dmitrylala** [comment]
Same problem, version v0.2023.02.14.08.05.stable_01

**Comment by doccodyblue** [comment]
Same for me on v0.2023.02.14.08.05.stable_01 MacOS, direct SSH Connection.

**Comment by a73x3434** [comment]
> 

same here

**Comment by LiljaAdam** [comment]
Same for me v0.2023.02.21.08.03.stable_01 MacOS

**Comment by vorporeal** [comment]
Hey folks, if you're still encountering this, can you try downloading and installing this hotfix release (not on autoupdate yet) and let me know if it fixes your SSH issues? https://storage.googleapis.com/warp-releases/stable/v0.2023.02.21.08.03.stable_02/Warp.dmg

**Comment by skobow** [comment]
Same for me

**Comment by pascalpas** [comment]
> Hey folks, if you're still encountering this, can you try downloading and installing this hotfix release (not on autoupdate yet) and let me know if it fixes your SSH issues? https://storage.googleapis.com/warp-releases/stable/v0.2023.02.21.08.03.stable_02/Warp.dmg

This hotfix works for me

**Comment by 6ylqq** [comment]
> > Hey folks, if you're still encountering this, can you try downloading and installing this hotfix release (not on autoupdate yet) and let me know if it fixes your SSH issues? https://storage.googleapis.com/warp-releases/stable/v0.2023.02.21.08.03.stable_02/Warp.dmg
> 
> This hotfix works for me

but the latest version installed by Brew seems doesn't fix yet

**Comment by fesnault** [comment]
Hi there,
I'm facing this issue, I can ssh on a remote vm, but at the bottom I see "Starting shell". When I exit the remote VM, I'm still stuck with Starting shell, forced to close terminal.

Is there a fix on the way ?

I'm on MacOS Ventura, Warp v0.2023.06.27.19.34.stable_01 installed with brew.

Regards

**Comment by kanra824** [comment]
I faced the same issue.
I'm using Warp v0.2023.07.11.08.03.stable_00, and MacOS Ventura.

**Comment by VincentPerspectivs** [comment]
Hi there,
Configuration also posted [here](https://github.com/warpdotdev/Warp/issues/2682#issuecomment-1827468782).
It was working fine then suddenly stopped. Despite no configuration change/update on neither local or remote machine.
It also works when I deactivate the ssh wraper.
Thanks!
Vincent

**Comment by PengFoo** [comment]
Same for me.

**Comment by vmn171** [comment]
Same for me. It seems that when the remote is zsh, it will get stuck in the Starting shell

**Comment by mokhosh** [comment]
Same problem.

v0.2024.03.05.08.02.stable_01

**Comment by prd-tai-le** [comment]
Same problem in my local Ubuntu machine: **warp-terminal_0.2024.04.02.08.02.stable.01_amd64**

**Comment by fsklenar** [comment]
Same problem
v0.2024.04.16.08.02.stable_00

**Comment by zhanglistar** [comment]
Same problem.
v0.2024.05.21.16.09.stable_02

**Comment by zhanglistar** [comment]
v0.2024.08.20.08.02.stable_00  the same problem.

**Comment by alexanderswerdlow** [comment]
Same problem: v0.2024.08.27.08.02.stable_02

**Comment by freQuensy23-coder** [comment]
same problem

**Comment by AuroraDysis** [comment]
Same problem on macOS `v0.2024.11.19.08.02.stable_03`

**Comment by vsourirajan** [comment]
Same problem on macOS v0.2024.12.03.08.02.stable_04

**Comment by jakelauer** [comment]
Same here, v0.2025.01.29.08.02.stable_03

**Comment by carapai** [comment]
Same problem

**Comment by xoscar** [comment]
Same problem!

**Comment by rehoehle** [comment]
I have now on Mittwald a problem and can't connect. He tries so start a shell and then i get an error that a sed parameter is wrong. So i can't use it.

**Comment by d53dave** [comment]
Just hit the same problem. SSH-ing into a machine on my local network, usually very fast in other terminals (iTerm, Ghossty, Kitty), Warp gets stuck in "Starting shel..."

**Comment by ooxx5626** [comment]
the same problem...
