### ISSUE TITLE
Integration: New tmux session from zshrc crashes Warp

### ISSUE THREAD

**Issue by thomasmarcel** [warpdotdev/warp#156]
### Describe the bug

```shell
I have some functions to open a new tmux session or reattach it when a new terminal session is opened, but it keeps crashing Warp on zsh startup.

I tried with no `.tmux.conf` file, with less logic, only opening a new session, same error.

Opening a tmux session after Warp finishes loading works fine.
```

### To Reproduce

Steps to reproduce:
1. Add the line below to your `.zshrc`
```
tmux new-session -As "test"
```
2. Launch Warp

### Expected behaviour

```shell
The terminal starts as expected and opens a tmux session.
```

### Screenshots

<img width="1021" alt="Screenshot 2021-09-01 at 19 25 16" src="https://user-images.githubusercontent.com/1779231/131716464-4f62ee16-991c-4670-8407-2495c76a5a5c.png">

### Operating System

MacOS

### OS Version

11.5.2

**Comment by zheng** [comment]
To clarify, does it crash - or does it show this modal?

We've been meaning to make this modal less intrusive (show a toast instead). I also think it may make sense for us to avoid showing it if the user's in a full screen program

**Comment by thomasmarcel** [comment]
It freezes and shows the modal, precisely!

**Comment by elviskahoro** [comment]
This should be fixed. @thomasmarcel reopen or comment if not!

**Comment by elviskahoro** [comment]
Moving into our Tmux github discussion so all of tmux is in one place.
