### ISSUE TITLE
Hotkeys in shortcut screen are not updated according to their actual values

### ISSUE THREAD

**Issue by hpl002** [warpdotdev/Warp#1562]
### Describe the solution you'd like?

```text
E.g.,
A.I search defaults to opt+`
Changed the binding to opt+r
Expected the displayed shortcuts to reflect this change
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:efcea52d-0ab4-4a92-a41b-93c3e244f0a0

Ignore

**Comment by elviskahoro** [comment]
Thanks for reporting!
