### ISSUE TITLE
Show terminal over full screen app/spaces

### ISSUE THREAD

**Issue by gijsroge** [warpdotdev/Warp#1565]
### Describe the solution you'd like?

Currently if you toggle the global shortcut to open Warp while you are in a full screen app/space it doesn't show the terminal, you have to move to the desktop to see it.

I know terminals like [Iterm2 support specifically this feature](https://iterm2.com/documentation-hotkey.html#:~:text=Floating%20window%3A%20When%20selected%2C%20the%20dedicated%20hotkey%20window%20can%20appear%20over%20other%20apps%27%20full%20screen%20windows%20(provided%20the%20profile%27s%20Window%20%3E%20Space%20setting%20is%20All%20Spaces).%20Floating%20windows%20overlap%20the%20dock.)

### How important is this feature to you?

4

**Comment by gijsroge** [comment]
duplicate of https://github.com/warpdotdev/Warp/issues/975

**Comment by elviskahoro** [comment]
Thanks for closing.
