### ISSUE TITLE
DUP: Duplicate of #150 - Autocompletions with zsh custom functions as aliases in .zshrc not working

### ISSUE THREAD

**Issue by neeravp** [warpdotdev/warp#157]
### Describe the bug

Autocompletions for custom function used as aliases are not working
I think this happened after today's update - can't say for sure though

### To Reproduce

Say I have following defined in `.zshrc`

```bash
lpac() { cd ~/Packages/laravel/$1; }
compctl -W ~/Packages/laravel/ -/ lpac
```

When I use the alias `lpac <initial letters of directory name>` and hit `tab` I should get autocompletion, but it doesn't work. Autocompletions for git and other commands work though

### Expected behaviour

Autocompletions with custom function defined in `.zshrc` should work

Eg:
``` shell

lpac <initial letters of dir name>   //hit tab
```

Should provide autocompletion

### Operating System

MacOS

### OS Version

11.5.2

### Additional context

```shell
warp v0.2021.08.30.16.44.stable
```

**Comment by zheng** [comment]
We have completions for aliases, and don't have completions for functions yet. I'm closing this issue because it's a dup of #150. In general, getting completions to work properly for people is top priority for us, but I'd love to see more people mention functions if it's important for them!

**Comment by elviskahoro** [comment]
Linking: #150
