### ISSUE TITLE
Auto fill directory names (pressing tab) does not work when directory name contains space

### ISSUE THREAD

**Issue by JosueMolinaMorales** [warpdotdev/Warp#1571]
### Discord username (optional)

Faults#1644

### Describe the bug

When attempting to go into my "School Work" directory from home, i am not given the list of directories if start typing like i would if were to changing into a directory with no space.

This only occurs during an absolute path. `$ ~ cd Onedrive/School\ Work/` but works fine when i am in the directory. 

### To Reproduce

Steps to reproduce:
1. Start in a directory
2. Try to change into a directory inside another directory whose name contains a space

### Expected behaviour

The mac terminal still gives you an option when you press tab
<img width="486" alt="Screen Shot 2022-06-30 at 8 35 51 PM" src="https://user-images.githubusercontent.com/72173743/176800134-53b2899e-120e-4e53-91c7-71575962eac1.png">

Warp does not

### Screenshots

<img width="229" alt="Screen Shot 2022-06-30 at 8 36 55 PM" src="https://user-images.githubusercontent.com/72173743/176800239-ede00aae-fa90-4eaf-be7d-b394cc43e437.png">
<img width="214" alt="Screen Shot 2022-06-30 at 8 37 25 PM" src="https://user-images.githubusercontent.com/72173743/176800242-3fe3ba0b-6d43-4834-b3cf-2f3e83bc9de4.png">

### Operating System

MacOS

### OS Version

12.1

### Shell Version

zsh 5.8

### Warp Version

v0.2022.06.27.09.14.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for this! Will circle back when there are updates!

**Comment by elviskahoro** [comment]
@JosueMolinaMorales gonna close this in favor of: #669
