### ISSUE TITLE
Popups (settings and update one) are not responsive

### ISSUE THREAD

**Issue by alex-rantos** [warpdotdev/Warp#1573]
### Describe the bug

Settings popup:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/22919198/176878474-67dbeee4-59ed-4020-8aeb-8f44fa294f2a.png">

What's new in Warp popup:
![image](https://user-images.githubusercontent.com/22919198/176877666-d34d70fa-aaa4-4522-ae67-2c016656982e.png)

### To Reproduce

Steps to reproduce:
1. Open either settings or `What's new in Warp` popup (via updating client)
2. Shrink the window
3. Popup on 1. has fixed position

### Expected behaviour

`What's new in Warp` popup should be responsive.

### OS Version

12.4

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Warp Version

v0.2022.06.27.09.14.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks! Gonna close this in favor of #366
