### ISSUE TITLE
Splitting pane change name tab

### ISSUE THREAD

**Issue by luispied** [warpdotdev/Warp#1575]
### Describe the bug

Scenario: 
I have a lot of tabs with his respective names.

Bug:
When splitting panes the name of the tab changes and I have to rewrite it again for the one that I had

### To Reproduce

Steps to reproduce:
1. Create a new tab
2. Rename the tab
3. Split the pane
4. The renamed tab will change

### Expected behaviour

When splitting the tab I think that it should keep the name that I wrote.

### Operating System

MacOS

### OS Version

11.6.6

### Shell Version

zsh 5.8, bash 3.2.57(1)-release

### Warp Version

v.0.2022.06.27.09.14.stable_01

### Does this block you from using Warp daily?

No

**Comment by kojuka** [comment]
Not sure if this is the exact same, but this is what im running into.  Here is a gif.  

Ideally when you split a pane, the new and old pane would maintain the same (renamed) tab name
![2022-07-05 10 13 14](https://user-images.githubusercontent.com/154551/177372072-c0360305-d6d4-4b5f-a2e2-9d74c0eac97a.gif)

**Comment by luispied** [comment]
Hi! Yes that is the issue that I was going into, now with this demo gif I can see that it's fixed, thanks Ken!

**Comment by kojuka** [comment]
@luispied its actually not fixed.  Thats what I was trying to demonstrate with the gif.  Sorry if it was unclear.  When I create the new pane, it defaults the tab.  The problem I run into is that I always have 3/4 panes per tab.  If I don't remember to rename all the panes, the tab will say the name of the last active pane.  If its a pane I've already renamed, it will be correct.  If I'd forgotten to rename the tab, it will be the default value given to all new tabs(which isn't all that helpful in my case).

**Comment by luispied** [comment]
Sorry for the delay in the response Ken, now is clear, I didn't pay attention at detail that the last splitting changes the name to the console default I think. But yes I want all the panes with the same name as the tab idk how difficult is to accomplish this, but if you are able to do it will be a must. thanks by the way for taking this bug into account.

**Comment by elviskahoro** [comment]
Thanks for reporting. I had opened up #1501 but I'm gonna close that in favor of this since you have more details!

**Comment by elviskahoro** [comment]
This was fixed!

**Comment by kojuka** [comment]
Yes fixed!  thank you.  Loving warp guys.  Keep up the good work!
