### ISSUE TITLE
Cannot run sudo commands

### ISSUE THREAD

**Issue by yasuf** [warpdotdev/Warp#1576]
### Discord username (optional)

yasu#9289

### Describe the bug

When I type in a sudo command and try to type in my password and press "Enter" nothing happens

### To Reproduce

Steps to reproduce:
1. Go to any folder
2. Run a `sudo mv [fileB] [fileB]`
3. Type in your password
4. Press enter and see that nothing happens

### Expected behaviour

I expect to be able to run the `mv` command with a sudo

### Screenshots

![Screen Shot 2022-07-01 at 11 49 08 AM](https://user-images.githubusercontent.com/7065942/176936984-ab9bcea8-4da0-4289-8af5-bc470b4563c5.png)

### Operating System

MacOS

### OS Version

11.5.2

### Shell Version

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

### Warp Version

2022.06.27.09

### Additional context

NA

### Does this block you from using Warp daily?

Yes

**Comment by kevinyang372** [comment]
Hi! Apologies for the experience. I couldn't repro from my end but I have seen some similar reports on command hanging. Could you provide some more context for this issue? More specifically:
1. Does only `sudo mv` hang for you? Or any sudo command will hang?
2. Does long running commands like `ping` or `sleep` hang for you?
3. Could you ctrl-c to terminate the process?

**Comment by yasuf** [comment]
@kevinyang372  it's working for me now, I don't know what it was then but I couldn't ctrl-c to terminate, it was the password prompt that was causing it, if it happens again I'll let you know

**Comment by yasuf** [comment]
Feel free to close it, I can reopen again and comment if I see it and notice how it happens

**Comment by kevinyang372** [comment]
Awesome! Thanks for reporting!
