### ISSUE TITLE
Right click dock icon should show New Window

### ISSUE THREAD

**Issue by lzm0** [warpdotdev/Warp#1577]
### Describe the solution you'd like?

```text
I can hardly say that I will continue to use Warp if this is not at least in the backlog.
Most macOS applications allow creating new windows by right-clicking the dock icon.
e.g. Chrome, VS Code
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by ivenhov** [comment]
I also would like to have this added.
It especially annoying with multiple desktops. To create new window you have to left-click on Warp in dock which moves you to another desktop with existing Warp window.
Then you need to create new Warp window and drag it over somehow to a desktop where you want it in the first place.
Finally you need to switch back to that desktop.
Way to many steps.

**Comment by lzm0** [comment]
> I also would like to have this added.
> It especially annoying with multiple desktops. To create new window you have to left-click on Warp in dock which moves you to another desktop with existing Warp window.
> Then you need to create new Warp window and drag it over somehow to a desktop where you want it in the first place.
> Finally you need to switch back to that desktop.
> Way to many steps.

A global hot key to create new windows would be even nicer.

**Comment by karol-kucharski** [comment]
Indeed it's really annoying and one of the most annoying things I discovered so far in this app.

**Comment by TheNoim** [comment]
> Indeed it's really annoying and one of the most annoying things I discovered so far in this app.

Yes, every time I am on another space and want to open a new warp window, I get really angry. Warp still doesn't feel like a real native macos app.

**Comment by elviskahoro** [comment]
Thanks for reporting. Gonna close this in favor of #420
