### ISSUE TITLE
Only show possible options for cd (change directory) command?

### ISSUE THREAD

**Issue by psquizzle** [warpdotdev/Warp#1579]
### Describe the solution you'd like?

```text
It seems like it could be very simple to achieve and I am not sure whether it is already in Warp. When I type for example cd code (enter), my next suggestion when I type cd is 'cd code', browsing directories would be a whole lot easier if I could type cd (press the up key) and only see realistic options e.g. the folders within the current directory.
```

### Is your feature request related to a problem? Please describe.

```text
I am always frustrated with typing long directory names in terminal.
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by elviskahoro** [comment]
Thanks for opening this! Great feature request. It might be reported already, I checked but couldn't find it. Will share updates when we have them

**Comment by elviskahoro** [comment]
@psquizzle Have you tried pressing tab to open up the completions menu? e.g. try typing git and then pressing tab!
