### ISSUE TITLE
When using REPL applications inside warp, command+arrow keys do not jump to the next whitespace 

### ISSUE THREAD

**Issue by Baccata** [warpdotdev/Warp#1584]
### Discord username (optional)

Baccata#0257

### Describe the bug

When using a REPL application inside warp (such as the python REPL), command+arrow keys do not allow to jump to the next whitespace 

I do not know the exact name of the feature, but when in a terminal, using command+left/right arrow keys usually let me jump the cursor to the next whitespace. This feature usually works in REPL applications loaded inside the terminal. 

### To Reproduce

1. Inside warp, open a REPL application (python, for instance)
2. write a few words separated by spaces (doesn't have to be valid syntax) 
3. attempt to use command+left-arrow 
4. nothing happens

### Expected behaviour

My expectation is that the cursor should jump to the previous whitespace 

### Screenshots

Using the integrated vscode terminal (correct behaviour): 
https://user-images.githubusercontent.com/4439335/177481151-a2ecc289-92ec-4963-a602-7300183d8601.mov

Using warp (incorrect behaviour): 
https://user-images.githubusercontent.com/4439335/177481257-7bc6a1a6-ed96-43a6-b106-2eaca9e64417.mov

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

zsh 5.8 

### Warp Version

v0.2022.06.27.09.14.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for reporting gonna merge this into #259
