### ISSUE TITLE
Completions for alias

### ISSUE THREAD

**Issue by ThanksSirAlex** [warpdotdev/Warp#1586]
### Discord username (optional)

ThanksSirAlex#6764

### Describe the solution you'd like?

```text
Many develop use alias to code faster. So I want completions can be available for alias.
for example:
When using git with Wrap I type `git checkout` and then press `tab` it will show all available branches for me. 
It's a brilliant feature. But I use `ch` as a shortcut for `checkout`. 
Then, when I press `tab` after `ch` this feature is not available any more.
 It's my custom for many year and other developers must have their own.
 I really want this completions can be available for alias.
BTW, this feature worked when I use oh my zsh. Though it's not friendly enough.
```

### Additional context

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/22314407/177702371-822afdd3-af1a-4a4f-bcfb-73d1cd0e92ea.png">
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/22314407/177702415-57675972-0d90-4437-a4c3-2ffc33827490.png">

![image](https://user-images.githubusercontent.com/22314407/178639598-1794368f-0bb9-4de3-9e5a-accd94eea99e.png)
![image](https://user-images.githubusercontent.com/22314407/178639623-e1294264-a8a5-4fb0-9a74-b9ed27795972.png)

### How important is this feature to you?

3

**Comment by willlma** [comment]
I'm trying to transition to Warp and this is very important for me as well. My old `git-completion.bash` was able to complete with my git aliases.

**Comment by yunfan777** [comment]
this is very important for me too

**Comment by elviskahoro** [comment]
Thanks for opening. We're tracking this here:
#562
