### ISSUE TITLE
Allow tabs to be moved

### ISSUE THREAD

**Issue by LeoMartinDev** [warpdotdev/Warp#1587]
### Describe the solution you'd like?

```text
I would be nice to be able to move a tab using drag and drop like in Chrome or Firefox.
```

### Is your feature request related to a problem? Please describe.

```text
It's a bit annoying that I cannot order my tabs as I wish.
```

### How important is this feature to you?

4

**Comment by acarl005** [comment]
Re-ordering tabs with a hotkey is also nice, and may be easier to implement than drag-and-drop style re-ordering. iTerm2, for example, allows you to re-order tabs using `cmd+shift+⬅️` and `cmd+shift+➡️`

**Comment by yasskate** [comment]
I think this issue/requirement is duplicated

Someone already created an issue proposing this functionality 👇🏽 
https://github.com/warpdotdev/Warp/issues/1585

**Comment by elviskahoro** [comment]
Thanks for opening. We're tracking this here:
#58

**Comment by elviskahoro** [comment]
You can also right click the tab to move it right or left. We just don't support drag to move yet

**Comment by acarl005** [comment]
@elviskahoro Right-click isn't showing up for me. When I right-click the tab I only get the option to rename the tab.
<img width="755" alt="Screen Shot 2022-07-20 at 13 07 02" src="https://user-images.githubusercontent.com/8334252/180041706-3b9f3ca9-9946-45e0-88b2-f9b9084e2d95.png">

**Comment by elviskahoro** [comment]
Can you try these keybindings
<img width="519" alt="Screen Shot 2022-07-20 at 14 05 51" src="https://user-images.githubusercontent.com/29553206/180051902-1abcaf79-f7a3-4d42-848b-3e755efd2659.png">
