### ISSUE TITLE
Cannot select prompt line, I want to select the git branch name to copy it easily

### ISSUE THREAD

**Issue by yasuf** [warpdotdev/Warp#1588]
### Describe the solution you'd like?

```text
I just want to be able to select the branch name like in iTerm or other terminals
```

### Is your feature request related to a problem? Please describe.

```text
Yes, I want to quickly copy the branch name when I want to push to Github, which is something I do every day
```

### Additional context

NA

### How important is this feature to you?

3

**Comment by Raulif** [comment]
Hey @yasuf . At least on my Mac, if you do right-click on top of the prompt (or anywhere on the terminal input area) you get the option "_Copy Git Branch_", which copies the name of your current branch to the clipboard. Don't you have that option?

**Comment by elviskahoro** [comment]
You can right click the prompt to copy the git branch like Raulif was saying!
