### ISSUE TITLE
Custom keyboard shortcut not reflected when opening new tab

### ISSUE THREAD

**Issue by arguiot** [warpdotdev/Warp#1590]
### Describe the bug

When opening a new tab, Warp shows some keyboard shortcuts you can use. But if one of them, let's say AI suggestion was modified, it still shows the default one.

### Operating System

MacOS

### OS Version

13

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.07.04.09.08.stable_02

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:24888f54-df93-45d5-9bdd-e38f740cac19

Ignore

**Comment by elviskahoro** [comment]
Thanks! Tracking here: #1190
