### ISSUE TITLE
Warp freeze every time using the "Welcome Tips" keyboard shortcut

### ISSUE THREAD

**Issue by tobatha** [warpdotdev/Warp#1592]
### Describe the bug

I'm running Ventura beta 3 on M1 Max laptop, Warp's performance on that hardware architecture is terrible every time I was using major features provided by default like cmd history, AI command, switching between themes, once the shortcut sommoned, Warp starts loading somehow and irresponsive for quite a long time before being interactive again

### To Reproduce

Steps to reproduce:
1. Launch Warp
2. Using keyboard shortcut like command + P
3. App starts loading and freeze
4. After a min or two, it came back to life, and every time using keyboard shortcut, step 2 ~ step 4 repeats

### Expected behaviour

App should not freeze, and user interaction should not be blocked

### OS Version

Ventura 13.0 beta 3

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)

### Warp Version

v0.2022.07.04.09.08.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by elviskahoro** [comment]
Thanks for reporting. Can u share a video!

**Comment by tobatha** [comment]
hi, sorry for the delay, attached the video, you can see that I only intend to access Theming & AI command search tips, it kept loading for quite a loong time before being responsive

https://user-images.githubusercontent.com/2382153/179341837-2d7f7037-94a4-499d-a507-762b791cd337.mp4
https://user-images.githubusercontent.com/2382153/179341838-7cd25055-1dda-4e13-a796-b076e8471d28.mp4

**Comment by elviskahoro** [comment]
Are you in SSH?
Can you try this from the docs?
You can quickly set up clean configs by putting ZDOTDIR=/ in a ~/.zshenv file. This forces zsh to run with zero configs.

https://docs.warp.dev/help/known-issues#debugging

**Comment by tobatha** [comment]
oh, I cas see the doc list incompatible tools that i all installed under zsh, this's gonna be a problem, I kinda need these tools to work with in terminal, thanks for the support anyway @elviskahoro , let's see if Warp could be more compatible in the future with all existing tools out there.

**Comment by tobatha** [comment]
I figured that on my work MacBook Pro with pretty much the same zsh config equipped with Intel chip, Warp works normally with very good quick response/interaction, maybe this is kinda hardware architectural issue rather than the zsh config related incompatibility. @elviskahoro

**Comment by elviskahoro** [comment]
Thanks @tobatha
