### ISSUE TITLE
Key Repeat Doesn't Work

### ISSUE THREAD

**Issue by endoze** [warpdotdev/Warp#1594]
### Describe the bug

When holding down a key like j for example (in neovim), it won't repeat like other terminal emulators I'm used to. In iTerm2, if I hold a key it will continually repeat said key until I let go.

This leads to awkward buffer navigation in neovim as I have to release all keys before it actually navigates between buffers (ctrl+h or ctrl+l). In other terminals, I don't have to let go of the control key as it continually repeats input while I'm holding said key.

### To Reproduce

Steps to reproduce:
1. Launch warp
2. Hold any letter key at the prompt

### Expected behaviour

I'd expect the key to continually repeat until I release the key.

### Screenshots

![warp-key-repeat](https://user-images.githubusercontent.com/997161/178127037-dee59cf1-f464-48e4-bfa1-33a5fee92e34.gif)
![iterm2-key-repeat](https://user-images.githubusercontent.com/997161/178127038-bb6cc090-a180-4c89-ad08-2db86a690128.gif)

### Operating System

MacOS

### OS Version

11.6.2

### Shell Version

zsh 5.5.1 (x86_64-apple-darwin18.0.0)

### Warp Version

v0.2022.07.04.09.08.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by endoze** [comment]
I modified the defaults setting and it didn't resolve the issue. If it was a MacOSX setting that was causing the issue, I don't think key repeat would work in any terminal emulator (like Alacritty and iTerm2) or any app for that matter. 

I've verified in the default Terminal.app, Alacritty, and iTerm2 that key repeat works as is. It's just Warp that seems to not want to repeat a key while I'm holding it down.

**Comment by weallwegot** [comment]
same issue for me, unable to hold down a key to have it repeat.

I tried the command from the article:
`defaults write -g ApplePressAndHoldEnabled -bool false`
but no luck

**Comment by Bigsby** [comment]
Same here.

macOS: Version 12.6
Warp: v0.2022.09.20.08.08.stable_01

**Comment by hazzlim** [comment]
Ping!!!! Same issue here, would be great to fix this as I really like Warp - but this is a complete deal breaker.

**Comment by erquhart** [comment]
Same here:

Mac OS Ventura 13.1
Occurs on all keyboards, macbook built in and external. Standard US keyboard layout.
Seems to only occur within Warp.

Note: when using vim inside of Warp, repeats work. But not on the command line itself, or for instance when holding <kbd>j</kbd> to scroll with `less`.

**Comment by betta-cyber** [comment]
macOS: 12.2.1
Warp: v0.2023.02.14.08.05.stable_01

solved by set `defaults write -g ApplePressAndHoldEnabled -bool false`

But it's a little strange that to set `ApplePressAndHoldEnabled false`, when i set it to true. I still can input repeat character using iTerm2

**Comment by zachlloyd** [comment]
The fix is ```defaults write -g ApplePressAndHoldEnabled -bool false``` followed by restarting Warp.  Warp honors the system ApplePressAndHoldEnabled setting, so I think we are working as intended in this case.  In the future we could introduce a better UX around how to turn this off though if it continues to confuse users.

Here's a video showing Warp's and iterm's behavior.  Note that iterm (in my opinion) is not correctly honoring this setting and has somewhat buggy behavior with it by doing both a key repeat and showing the character palette.

https://user-images.githubusercontent.com/8727141/232628500-63201777-47a0-4f4f-bb42-76c024b5b401.mov

**Comment by rmfuhrer** [comment]
Late to the party, but I've had the same issue with Warp on my MacBook Pro, US keyboard, for several major OS versions now, up through Sequoia 15.5. Key auto-repeat works properly in all other apps that I've tried: Terminal, Xcode, etc..

So how is writing a global setting considered a fix for the problem, when only Warp manifests the problem to begin with?

I've never had to manipulate this setting on behalf of any other app.

This sounds much more like a workaround, with possibly unintended consequences, than a fix.

**Comment by lemraus** [comment]
> This sounds much more like a workaround, with possibly unintended consequences, than a fix.

I disagree with this statement. The other terminal apps seem to ignore the system wide setting for the "press and hold" feature, whereas Warp inherits this setting. And IMO it makes sense: if press and hold is disabled globally, you should not be able to use it in apps.
