### ISSUE TITLE
Make accounts/login optional

### ISSUE THREAD

**Issue by benwaffle** [warpdotdev/warp#160]
### Describe the solution you'd like?

```shell
I had to log in via github to start using Warp. I hope that's just for the beta, but if not, I would like to recommend that online accounts be optional for Warp.
```

### Is your feature request related to a problem? Please describe.

```shell
I want my tools to respect my privacy and collect the least amount of data as possible, especially a tool as central as my terminal.
```

**Comment by zheng** [comment]
Yes, this is for the closed-beta only and warp will not require any login. Also still figuring out how it will work exactly but the terminal itself will also be free, but cloud-backed features will be optional + require payment at some time.

**Comment by benwaffle** [comment]
sgtm

**Comment by bfad** [comment]
So, the website doesn't say anything about a private beta, but the app is still requiring logging in via GitHub. When will this be fixed?

**Comment by robertlong** [comment]
Yeah, I'd also like to opt-in to GitHub login not have to authenticate the first time I'm installing a new terminal. It's great so far though!

**Comment by smereczynski** [comment]
How to opt-out? I don't see the information about opt-out on privacy page. I feel like it is GDPR non-compliant.
