### ISSUE TITLE
Tab completion doesn't work after path name with spaces(MacOS m1pro)

### ISSUE THREAD

**Issue by 826541814** [warpdotdev/Warp#1600]
### Discord username (optional)

kerck

### Describe the bug

Tab completion doesn't work after path name with spaces

For example：
 if i want go to path "/Users/xxx/Library/Application Support"
<img width="974" alt="image" src="https://user-images.githubusercontent.com/37057859/178444968-fc74624e-0461-43e3-bc29-8858a85417f5.png">

When I first entered "Application", I can use Tab completion "Application\ Support", Then if i click "Enter" to confirm path,  and delete last letter "t\", try to use Tab completion,  it's didn't work.

If I want to use Tab to show all the files in "/Users/kerck/Library/Application\ Support\", it doesn't work either.

I find same issue in https://github.com/warpdotdev/Warp/issues/60 , but the problem still appeared in my case

### To Reproduce

try Tab completion in "vim /Users/xxx/Library/Application Support/"

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

can't find it, i download at 2022-07-12 from https://app.warp.dev/get_warp

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for opening!

**Comment by elviskahoro** [comment]
Gonna close this in favor of #669
