### ISSUE TITLE
Can't sign in on Mac osx 12.4 , no token is provided

### ISSUE THREAD

**Issue by rickyking** [warpdotdev/Warp#1602]
### Describe the bug

Tried to sign in use both github/gmail/email... nothing works.

When I click on copy the code, I got this: warp://auth/desktop_redirect?refresh_token=&is_user_new=false

it appears to be I can't get token.

I have disabled the ads blocker.

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

sign in correctly

### Operating System

MacOS

### OS Version

12.4

### Shell Version

5.8.1 zsh

### Warp Version

v0.2022.07.04.09.08.s

### Does this block you from using Warp daily?

Yes

**Comment by brymon68** [comment]
+1 - Having same issue

**Comment by juliendsv** [comment]
+1 - Having same issue

**Comment by michlimlim** [comment]
Looking and fixing now. Thank you for reporting!

**Comment by michlimlim** [comment]
Fix should be deployed in around 15min. Thank you!

**Comment by gatsbysghost** [comment]
+1, I would also note that the web sign-in has this text:

> Button not working? Click here to copy your auth token, then open Warp and paste the token directly into the app.

...but in the pre-sign-in stage of the flow, there's nowhere in the Warp app to paste that token and pasting does nothing; just FYI, the UX on that is confusing, at a minimum.

Thanks @michlimlim for investigating and shipping a fix so quickly!

**Comment by michlimlim** [comment]
The fix is deployed and I verified that it worked.

**Comment by michlimlim** [comment]
> ...but in the pre-sign-in stage of the flow, there's nowhere in the Warp app to paste that token and pasting does nothing; just FYI, the UX on that is confusing, at a minimum.

Thank you for the feedback on this! Agreed this is confusing and worth fixing.

**Comment by caesar** [comment]
I'm having the same issue so it doesn't seem fixed. I finally decided I'd tolerate the forced login just to see what Warp is all about – and it doesn't work.
Honestly it's really off-putting that you require online sign-in to use the app, but you can't even get the sign-in to work properly. Absolutely does not give me confidence.

**Comment by michlimlim** [comment]
Hi @caesar thank you for reporting this. Can I confirm that when you click copy code, the result is `warp://auth/desktop_redirect?refresh_token=&is_user_new=false`? I wasn't able to reproduce this.
