### ISSUE TITLE
Link recognition includes last quote

### ISSUE THREAD

**Issue by westernwontons** [warpdotdev/Warp#1603]
### Describe the bug

Hovering over a link in Warp underlines it and on click it navigates to it. If the link is wrapped in single quotes, the last quote is included in the match.

### To Reproduce

Steps to reproduce:
1. Type `echo "'https://example.com'"` into Warp
2. Click on the highlighted link
3. The browser will navigate to `https://example.com'`

### Expected behaviour

Navigate to `https://example.com`

### Screenshots

<img width="836" alt="Screenshot 2022-07-13 at 11 52 11" src="https://user-images.githubusercontent.com/75550932/178694642-7e080213-322c-4339-bc07-77bdc6752a72.png">
<img width="1624" alt="Screenshot 2022-07-13 at 12 01 23" src="https://user-images.githubusercontent.com/75550932/178694802-79a7286f-9097-4087-b16e-42d7699e30e2.png">

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.07.04.09.08.stable_02

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for opening!

**Comment by elviskahoro** [comment]
This should have been fixed with the latest release!
