### ISSUE TITLE
Alias expansion

### ISSUE THREAD

**Issue by that70schris** [warpdotdev/Warp#1605]
### Describe the solution you'd like?

```text
I really like the `abbr` feature of fish expanding when hitting the space bar.  Would be really cool if Warp auto expanded aliases like this. 
```

### How important is this feature to you?

4

**Comment by that70schris** [comment]
i've recently installed `zsh-abbr` which is working in iTerm, but not Warp

**Comment by elviskahoro** [comment]
Thanks for reporting. We're tracking this in #537
