### ISSUE TITLE
Scroll doesn't work while using tmux

### ISSUE THREAD

**Issue by ofarukcaki** [warpdotdev/Warp#1606]
### Describe the bug

I'm connecting to my linux instance over ssh from my mac. Tmux is installed on the remote machine and while I'm in the tmux window and run `geth --help`, I can't scroll to top to see output generated by the [geth](https://github.com/ethereum/go-ethereum) but just the bottom part.

Scrolling seems to iterate through history it seems, instead of the output. It is not related with the [geth](https://github.com/ethereum/go-ethereum) itself, as the same problem also applies with `go help`

### To Reproduce

Steps to reproduce:
1. Open a tmux window with `tmux new -s test`
2. Download the geth binary https://github.com/ethereum/go-ethereum (available in releases)
3. Run `geth --help`
4. Try to scroll to see the beginning of the output

### Expected behaviour

The beginning portion of the output should be accessible

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.07.11.09.11.stable_00

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for reporting this! Can you move this into #501
