### ISSUE TITLE
Tab names don't update when pane focus changes

### ISSUE THREAD

**Issue by mystaticself** [warpdotdev/Warp#1609]
### Discord username (optional)

mystaticself#8244

### Describe the bug

If you have a tab containing split panes and you rename each pane the tab title doesn't update when the pane focus changes, only after mousing over the tab name will it update.

### To Reproduce

Steps to reproduce:
1. Split a tab into multiple panes
2. Click on each pane and give it a unique tab name
3. Change pane focus and notice the tab name doesn't update
4. Mouse over the tab name to make it update

### Expected behaviour

Tab name would update when pane focus changes.

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.7.1 (x86_64-apple-darwin18.2.0)

### Warp Version

v0.2022.07.11.09.11.stable_00

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for opening. Tracking in #1566
