### ISSUE TITLE
Show kubernetes context in prompt

### ISSUE THREAD

**Issue by benwaffle** [warpdotdev/Warp#161]
### Describe the solution you'd like?

```shell
I work with multiple kubernetes clusters, so it's important that I always know which one I'm applying things to.
```

### Additional context

You can see the context name here in blue, coming from my https://starship.rs/ prompt

<img width="327" alt="image" src="https://user-images.githubusercontent.com/1713819/131910249-e5a6f375-5def-4257-a7e5-2f04a6fdef9c.png">

**Comment by zheng** [comment]
Thanks for filing! K8 is very popular, would love to see how many of our users also want this!

**Comment by syepes** [comment]
+1

**Comment by elviskahoro** [comment]
Moving into our custom prompts discussion:
- https://github.com/warpdotdev/Warp/discussions/422
