### ISSUE TITLE
Warp hard crashes after running terraform plan (complex plan)

### ISSUE THREAD

**Issue by kevinvalk** [warpdotdev/Warp#1619]
### Describe the bug

See [crash-report.txt](https://github.com/warpdotdev/Warp/files/9123779/crash-report.txt)

### To Reproduce

Sadly I cannot isolate what exactly from terraform is crashing Warp

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.07.11.09.11.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by kevinvalk** [comment]
Not at all, please go ahead.

**Comment by alokedesai** [comment]
@kevinvalk going to close this out as we believe we have fixed this. Please reopen if you are still experiencing this!
