### ISSUE TITLE
⌘+⬅️ and ⌘+➡️ to switch terminal tabs

### ISSUE THREAD

**Issue by benwaffle** [warpdotdev/Warp#162]
### Describe the solution you'd like?

```shell
Pressing ⌘+⬅️ should go to the previous tab, and ⌘+➡️ should go to the next tab. iTerm 2 has this.
```

**Comment by benwaffle** [comment]
^+➡️ and ^+⬆+➡️ doesn't seem to be working for me

**Comment by zheng** [comment]
For this, we have:
* ^ + tab and ^ + shift + tab (native mac shortcut)
* cmd + # like in chrome tabs

Are these all iTerm2 specific shortcuts?

**Comment by benwaffle** [comment]
Looks like iTerm 2 supports all 3 ways

**Comment by JanJakes** [comment]
> cmd + # like in chrome tabs

@zheng This doesn't seem to work for keyboards that use numeric keys for special symbols and numbers themselves are done using `Shift + #` (like the Czech keyboard). In iTerm, Chrome, and other apps `CMD + #` works for me even on the Czech keyboard. Should I create a new issue for that?

**Comment by ephemer** [comment]
Please leave `Cmd + Left` / `Cmd + Right` as they are :( In a text editor (which a terminal largely is, IMHO) these shortcuts move to the start / end of a line. I would really like it to stay that way.

`Ctrl (+ Shift) + Tab` is the standard for switching tabs and I also think it should stay that way 👍🏼

**Comment by elviskahoro** [comment]
Moving to #579 so all keybinding related issues are in one place:
- #579

**Comment by csaid** [comment]
Is it possible to for this action to be made remappable in the Settings page?

**Comment by cristiangrojas** [comment]
+1 

I'm coming from iTerm and this is really useful!

Specially if you consider the following scenarios:

1. Searching for a tab (you don't know the number) is hard with the default OSX command because pressing the Shift key to go back doesn't feel that natural
2. When you've more than 9 tabs

Would be awesome to have this
