### ISSUE TITLE
word-wrap support

### ISSUE THREAD

**Issue by ivribalko** [warpdotdev/Warp#1620]
### Discord username (optional)

ivribalko#6485

### Describe the solution you'd like?

```text
hello!

huge commands shown in multiple lines automatically (i.e. word-wrapping them) would be :rocket:

effectively that means any time i end up filling the input line completely with a long command i'd like warp to continue on a new line, not on the same line using horizontal scrolling like it does now

optimally it would move a whole word onto the new line but even proceeding on a new line by breaking the word at any word's character would be nice!

this will allow to see all the command at once


love warp! <3
```

### Is your feature request related to a problem? Please describe.

```text
i'm debugging a huge command and i have to use IDE with word wrapping to effectively iterate on it and i don't really want to rewrite it using "\" new line escape character because i simply won't need it and searching through this long command with ALT+arrow is not very robust
```

### Additional context

warp's window bottom with the input line:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/20713003/179302963-fac88a48-3eb8-40f1-b17d-152acc96f225.png">

### How important is this feature to you?

2

**Comment by ivribalko** [comment]
this would also enhance command preview support because currently is shows only starting (first line) characters too so i can't see all the changes i made across multiple attempts at this long command easily

**Comment by elviskahoro** [comment]
Thanks for opening. We're trackign this here: #520

**Comment by elviskahoro** [comment]
This launched today!
