### ISSUE TITLE
Can Warp be launched without creating a new tab?

### ISSUE THREAD

**Issue by gaggle** [warpdotdev/Warp#1622]
### Describe the solution you'd like?

I'd like to open Warp from IntelliJ by pressing a shortcut, but not have Warp create a new tab. [Following your documentation](https://docs.warp.dev/features/integrations-and-plugins) results in a new tab opening up every time I click the shortcut key in IntelliJ.

I'm hoping I can pass an argument ala `--skip-new-tab` or something to that effect so Warp merely opens on the tab I left it at. That would more closely behave like IntelliJ's built-in terminal where I can press the shortcut key every time I want to switch to it.

I hope this is a minor feature-request :) And thanks for making this terminal available!

### How important is this feature to you?

2

**Comment by elviskahoro** [comment]
@gaggle Thanks for opening. I think this is planned as a follow up V2. @vjindal0112
