### ISSUE TITLE
启动卡顿、不稳定

### ISSUE THREAD

**Issue by jiyaoxiong** [warpdotdev/Warp#1624]
### Describe the bug

刚打开warp较慢，容易出现没有响应的情况，且在使用途中，经常卡顿没有响应

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.07.11.09.11.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by elviskahoro** [comment]
can you send us crash reports?

**Comment by jiyaoxiong** [comment]
I hava to submit a new issue , please

**Comment by elviskahoro** [comment]
Can you send us a video? + some log reports?
