### ISSUE TITLE
启动卡顿、使用途中延迟厉害

### ISSUE THREAD

**Issue by jiyaoxiong** [warpdotdev/Warp#1625]
### Describe the bug

我在打开Warp途中，大约用了30s才能启动；进入Warp后，强制退出应用中显示Warp未响应，我将它强制退出后，重新启动打开，仍然启动较慢，进入Warp加载很久，随后在Warp的设置中任何一步操作都会出现Warp未响应的情况

### To Reproduce

1、启动Warp，用时30s及以上；
2、进入Warp，Warp未响应；
3、强制退出Warp后重新打开，上述情况依然存在；
4、进入Warp加载成功以后，进入设置中进行自定义修改，每一个步骤都会使得Warp未响应。

### Expected behaviour

能够便捷、快速进入Warp，且在使用途中能够顺利丝滑。

### Screenshots

![IMG_0393](https://user-images.githubusercontent.com/88077941/179654430-9123691b-e1e8-4fbc-bad1-2db13324f7df.JPEG)
![IMG_0394](https://user-images.githubusercontent.com/88077941/179654605-ec6171e0-56a8-4dfd-b794-cc7f155efb38.JPEG)

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.07.11.09.11.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by elviskahoro** [comment]
Thanks for opening. Will get back to you on this!

**Comment by jiyaoxiong** [comment]
请问什么时候能够发行正式版本
