### ISSUE TITLE
it takes  long time to open a panel.  heavily block daily use

### ISSUE THREAD

**Issue by NickHu150** [warpdotdev/Warp#1626]
### Describe the bug

it often takes about 20s to launch warp. and it always no responding when i try to open theme setting or create a new panel. it blocks daily operation seriously, please fix it

### To Reproduce

Steps to reproduce:
1. Go to 'Warp'
2.and it blocked

### Operating System

MacOS

### OS Version

12.4

### Shell Version

5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.07.11.09.11

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment]
Hey @NickHu150, thanks for filing. Could you post a video of the behavior you're experiencing on app startup? Is the delay in  the first window opening or in Warp starting a new session?

**Comment by NickHu150** [comment]
video is coming~ 

https://user-images.githubusercontent.com/9206069/180700556-bcc6d7e4-3e53-4368-ad47-e70ac10b2064.mp4

**Comment by alokedesai** [comment]
Thank you for flagging! Does this repro if you turn off "Restore windows, tabs, and panes on startup" in the settings? 

Also what type of Mac are you using?

**Comment by NickHu150** [comment]
> 

i tried it. but it does't work, here are messages of my mac
![image](https://user-images.githubusercontent.com/9206069/180951912-450da110-f293-4809-8c64-d519f3cc9eeb.png)

**Comment by dannyneira** [comment]
Hi @NickHu150 We've made some recent improvements to performance, are you still seeing the slow startup times in Warp's latest build? v0.2022.10.11.08.13.stable_01

**Comment by dannyneira** [comment]
Hi @NickHu150, Any luck with updating Warp to the latest version and your macOS to 12.6.1 or above?

**Comment by NickHu150** [comment]
> Hi @NickHu150, Any luck with updating Warp to the latest version and your macOS to 12.6.1 or above?

Thanks! all of the bugs were fixed.
