### ISSUE TITLE
Clicking on inactive tab causes unexpected window resizing

### ISSUE THREAD

**Issue by eagr** [warpdotdev/Warp#1627]
### Describe the bug

When having multiple tabs open, clicking on an inactive tab sometimes resizes the Warp window. Sometimes it becomes "shorter" (in height), sometimes it becomes narrower.

There may not be helpful, but
* I use [Rectangle](https://rectangleapp.com/) to tile my windows.
* I'm using font size 10.
* I'm using the compact mode.

Tbs, Warp's looking great. Kudos to you guys.

### To Reproduce

Steps to reproduce:
1. Open multiple tabs in Warp.
2. Resize Warp window to fill the left 1/3, or the right 2/3 of the viewport whatever (as long as it is as tall as the viewport).
3. Click on an inactive tab to switch to it.
4. See the window resizes.

It doesn't always happen, and the way how the window resizes is a bit random, either shorter or narrower.

### Expected behaviour

Keep the window as is, don't resize it.

### Operating System

MacOS

### OS Version

12.3

### Shell Version

zsh 5.8

### Warp Version

v0.2022.07.11.09.11.stable_01

### Does this block you from using Warp daily?

No

**Comment by eagr** [comment]
sure
[Screen Recording 2022-07-20 at 08.58.07.webm](https://user-images.githubusercontent.com/64203473/179873499-c7074021-01f9-4f81-a80e-60c585de1355.webm)

**Comment by eagr** [comment]
https://user-images.githubusercontent.com/64203473/179875157-4ab2df38-fa11-4d4e-81bb-16753eab0b39.mp4

**Comment by elviskahoro** [comment]
Wow. That's really bizarre!

**Comment by johnurbanik** [comment]
This is happening for me as well. I'm also a rectangle user.

**Comment by flaxton** [comment]
Also happening to me. Also using Rectangle.

After I open Warp, I use my rectangle keyboard shortcut to make it fill the screen.

Then I run a script that uses Applescript to open 3 more tabs and runs a command in them, to connect via mosh > ssh > tmux to my servers.

Then when I click on one of the new tabs, it often will resize the window to what it was before. I hit the keyboard short cut to fill then screen again. Then click another tab, and often/sometimes it will resize it *again*. Sometimes I have to do this two or three times.

Sometimes it does it, sometimes it doesn't.

After using it for a bit it stops doing this.

[Warp resizing screen in error.mp4](https://www.dropbox.com/s/jiiinmlmdh0kkci/Warp%20resizing%20screen%20in%20error.mp4?dl=0)

Thanks!

Fred

**Comment by dannyneira** [comment]
Hi @eagr, I've been able to repro this with Warp also using Rectangle, since the Warp window is snapped from its current window size to whatever you have set for Rectangle. If you `CLICK+ever so slightly drag in any direction` when selecting another Tab, the Window will snap back to its original size.

This is due to Warp Tabs not being click-to-dragable, but we have an feature request for that here if you care to. +1 and get updates. https://github.com/warpdotdev/Warp/issues/58
