### ISSUE TITLE
After double clicking in the Input Editor to highlight a word unable to drag to extend the selection

### ISSUE THREAD

**Issue by warpdotdev-dx** [warpdotdev/Warp#1630]
### Describe the bug

After double clicking in the Input Editor to highlight a word unable to drag to extend the selection

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### OS Version

47

### Shell Version

47

### Warp Version

47

### Does this block you from using Warp daily?

No

**Comment by warpdotdev-dx** [comment]
https://user-images.githubusercontent.com/87875561/179786822-0a17e56e-dc97-46f3-a4b3-44303e1d71bd.mov

**Comment by elviskahoro** [comment]
Closing for #766
