### ISSUE TITLE
Update banner cannot be dismissed

### ISSUE THREAD

**Issue by warpdotdev-dx** [warpdotdev/Warp#1631]
### Describe the bug

On work and enterprise clients in particular where devs might not have the permission to update, the banner cannot be dismissed.

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### OS Version

NA

### Shell Version

NA

### Warp Version

NA

### Does this block you from using Warp daily?

No

**Comment by lreto** [comment]
I second this. As much as I linke getting updates with new features and bugfixes, this banner is quite annoying. It should at least be possible to dismiss the banner. Also, I don't think it is necessary to update Warp manually with a dmg. Maybe I'm wrong, but can't other applications also update themselves even if the logged in user is not an administrator? These applications simply open a dialog where one can enter the username and password of an administrator user.

**Comment by elviskahoro** [comment]
I'll circle back with yall when this is fixed. Will try to get the priority bumped up.

**Comment by elviskahoro** [comment]
Actually will close this for #1551
