### ISSUE TITLE
Hotkey Window does not (at least) Chinese input source <option> key

### ISSUE THREAD

**Issue by ZaynJarvis** [warpdotdev/Warp#1632]
### Describe the bug

Under Chinese input source, <option> key does not work with Warp. (But it works with iTerm2)

### To Reproduce

Steps to reproduce:
1. Go to Hotkey Window, Set Keybinding to <option> + <space> 
2. change input source to Chinese (not sure if other source will have the same issue)
3. <option> + <space> does not have respond

### Expected behaviour

<option> key should apply to any input source, not just English input source

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8

### Warp Version

(in settings, no long in 3-dots menu) v0.2022.07.11.09.11.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by elviskahoro** [comment]
Thanks for opening. We're tracking this here:
#783
