### ISSUE TITLE
Screen -r autocompletion

### ISSUE THREAD

**Issue by guillaumefrd** [warpdotdev/Warp#1635]
### Describe the solution you'd like?

```text
Autocompletion when typing `screen -r ...` showing the existing screens inside the session.
```

### Is your feature request related to a problem? Please describe.

```text
Without warp the autocompletion (pressing tab) works fine to complete `screen -r`. 
With warp I need to do `screen -ls` then copy-paste my screen name after `screen -r`. 
I am constantly switching between screens so it is a pain.
```

### How important is this feature to you?

5

**Comment by Anloubie42** [comment]
I am having this issue as well. It would be really nice to have this !

**Comment by elviskahoro** [comment]
Thanks for flagging this. Will reach back out when there are updates.

**Comment by guillaumefrd** [comment]
Any update on this?

**Comment by alokedesai** [comment]
@guillaumefrd Thanks for following up here! We should have a fix for this coming out this week's release (this Thursday). I'll close this issue out once it is fixed

**Comment by guillaumefrd** [comment]
Seems that the feature was pushed in prod! Thanks a lot, much appreciated 🙏 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/14927435/203093436-d825e967-98f4-4c59-8baa-4406d42e6260.png">

**Comment by alokedesai** [comment]
Great to hear this is working for you! Closing this as fixed.
