### ISSUE TITLE
Hotkey Window should appear on any active screen above other things

### ISSUE THREAD

**Issue by IlyaCherkasov** [warpdotdev/Warp#1637]
### Discord username (optional)

Cherkasik#1767

### Describe the solution you'd like?

```text
I want hotkey window to display above other windows when I use fullscreen mode for application (like iTerm2 hotkey window). So it should appear on any active screen above other windows.
This kind of behaviour is critical for me to choose between terminals. I love terminal to be like built-in the system and having it opened above everything on any screen by hotkey.
```

### Is your feature request related to a problem? Please describe.

```text
It's not a problem, just something I'd love to have
```

### How important is this feature to you?

4

**Comment by ozsay** [comment]
this is already being discussed https://github.com/warpdotdev/Warp/issues/975

**Comment by IlyaCherkasov** [comment]
sorry, tried to find, but coudn't, closed as duplicate

**Comment by elviskahoro** [comment]
Thanks @ozsay 
@IlyaCherkasov Kevin has been looking at it.
