### ISSUE TITLE
Enter key not working

### ISSUE THREAD

**Issue by wpbeckwith** [warpdotdev/warp#164]
### Describe the bug

```shell
I have installed Warp on 16" MBP and on my desktop.  Warp on the MBP is working but on the desktop it starts and gives me a prompt.  However after that I can type in the input editor but the enter key does nothing.  I'm pretty sure it worked the absolute 1st time I logged in on the desktop.  Since then the enter key does nothing.  Is there a way to completely remove warp from the system and reinstalling?  Deleting the app and reinstalling did not solve the situation.
```

### To Reproduce

Steps to reproduce:
1. Start warp
2. Ge the home prompt
3. Try and enter any command like 'pwd'.  Hitting the enter key will do nothing

### Expected behaviour

```shell
Command would be executed.
```

### Operating System

MacOS

### OS Version

11.4

### Additional context

```shell
Using zsh on both desktop and MBP.
```

**Comment by zheng** [comment]
We've fixed some issues related to international keyboards. Does this issue still reproduce? @wpbeckwith

**Comment by wpbeckwith** [comment]
Nope, this issue has been fixed. Thanks.
