### ISSUE TITLE
Mac OS Terminal app ssh server success connection，but warp ssh server fail

### ISSUE THREAD

**Issue by lvgang296** [warpdotdev/Warp#1640]
### Describe the bug

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/31500689/180351841-ba37d15f-bc37-4c0d-af57-4abd6ea6dafb.png">

### To Reproduce

ssh user@server
input password
wait a minute........
connection to server closed.

mac os terminal connection is success

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.07.11.09.11.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@lvgang296 Can you reopen an issue but using our SSH t4emplate?
https://github.com/warpdotdev/Warp/issues/new?assignees=&labels=&template=03_ssh.yml
