### ISSUE TITLE
It seems History Search has low performance

### ISSUE THREAD

**Issue by cvincent00** [warpdotdev/Warp#1643]
### Describe the bug

When I use History Search feature by pressing Ctrl+R, I get big lag when navigating the options.

### To Reproduce

Steps to reproduce:
1. press Ctrl+R
2. type command
3. navigate between options or continue typing

### Expected behaviour

smoothly navigation and command recommendation

### OS Version

macOS Monterey 12.3.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.07.18.09.06.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by cvincent00** [comment]
FYI, I am using oh-my-shell, and  over 10k commands in history file (.zsh_history), is it the root cause of this problem?

**Comment by elviskahoro** [comment]
@cvincent00 can you disable oh-my-shell just for Warp?
Look at the configuring and debugging section of our docs:
https://docs.warp.dev/help/known-issues

Gonna CC @zheng as she's been improving Warp performance

**Comment by zheng** [comment]
I am able to repro this & I will look at making a fix. oh-my-shell shouldn't be related

**Comment by alokedesai** [comment]
Hey @cvincent00, @zheng recently made some changes here that should have fixed this issue. Could you confirm you are no longer seeing this?

**Comment by cvincent00** [comment]
Hi @alokedesai @zheng , I got latest version of warp (v0.2022.08.23.08.06.stable_01). But it seems no improvement.

**Comment by CfirTsabari** [comment]
@cvincent00 
I had the same issue - the problem was that some of the items in my history file were very large, I solved it by removing the large item and restarting Wrap.
I have opened a feature request to exclude large items from the commands search : https://github.com/warpdotdev/Warp/issues/1892

**Comment by warpdotdev-dx** [comment]
Thanks Zheng.

**Comment by dannyneira** [comment]
@cvincent00 Are you still seeing the same issue in latest version of Warp?

**Comment by cvincent00** [comment]
@dannyneira I followed @CfirTsabari instruction, removed large items in history file, and updated to latest version. It became more smoothly. Thanks @CfirTsabari 🙏
