### ISSUE TITLE
Reopen closed tab

### ISSUE THREAD

**Issue by morsdyce** [warpdotdev/Warp#1649]
### Describe the solution you'd like?

```text
Similar to Chrome and other systems, I'd like a "Reopen last closed tab" as I'm clumsy and click on the close button (X) on the tab sometimes and close an entire session.
```

### How important is this feature to you?

2

**Comment by elviskahoro** [comment]
Dup: #088

**Comment by elviskahoro** [comment]
We're keeping a list of keybindings as well in #579 so it's easier for people to see everything that Warp supports.
