### ISSUE TITLE
Minor Annoyance (Copy output directory)

### ISSUE THREAD

**Issue by davidrenne** [warpdotdev/Warp#1654]
### Describe the solution you'd like?

```text
After I run a command, you output the directory I was in and the number of seconds the command took, but that cannot be copied.  It looks like part of the stdout, but it isnt.  This should be copyable if I want to copy that directory to do something with
```

### How important is this feature to you?

1 (Not too important)

**Comment by davidrenne** [comment]
This also goes for the current area where its ready to send a command, the directory is not copyable, I have to send it a pwd which is annoying.

**Comment by elviskahoro** [comment]
Gonna close this in favor #036.
You can also right click @davidrenne there should also be some keybindings that you can use once the Block is selected.
