### ISSUE TITLE
Repo is Marked as a Template

### ISSUE THREAD

**Issue by hughesjs** [warpdotdev/Warp#1656]
### Describe the bug

The repo seems to be marked as a template

It doesn't look like a template repo to me...

### To Reproduce

Open the github page

### Expected behaviour

Should be public, but not a template

### Screenshots

<img width="331" alt="image" src="https://user-images.githubusercontent.com/4203766/180995781-2e9bb2eb-9403-47ba-839e-9d256badb604.png">

### Operating System

MacOS

### OS Version

N/A

### Shell Version

N/A

### Warp Version

N/A

### Additional context

N/A

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
It is a template repository. This makes it easier for people to fork it, pull the submodules, and then make their own customizations. As you can just rename the repo from warp to .warp which is what we index for keysets, themes, etc.
