### ISSUE TITLE
Evans gRPC calls hangs up forever

### ISSUE THREAD

**Issue by mispon** [warpdotdev/Warp#1658]
### Describe the bug

Terminal hangs up forever on gRPC call in [evans](https://github.com/ktr0731/evans)

### To Reproduce

Just do any of unary or stream call with [evans](https://github.com/ktr0731/evans)

### Screenshots

![image](https://user-images.githubusercontent.com/19244573/181056766-1fe16777-fb84-402d-af5d-76d9083eb297.png)

### Operating System

MacOS

### OS Version

BigSur v11.6.3

### Shell Version

zsh 5.8 (x86_64-apple-darwin20.0)

### Warp Version

v0.2022.07.18.09.06.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Sorry about this! Will circle back here once there are updates!

**Comment by alokedesai** [comment]
@mispon We believe this should be fixed, so going to mark this as closed. Please feel free to reopen if you're still seeing issues!

**Comment by mispon** [comment]
Fixed in latest update, thanks!
