### ISSUE TITLE
Git diff autocomplete - branch not rendering text for list of options

### ISSUE THREAD

**Issue by koalazub** [warpdotdev/warp#166]
### Describe the bug

```shell
When comparing the `diff` of a git project - it seems like it’s able to fetch all of the branches related to that project. But it seems like it’s not able to render the text related to these branches.

There were a large number of branches listed in this tab complete - so I wonder if maybe there's a buffer issue. But that's just speculation. Attached below is a video of what I mean
```

### To Reproduce

Steps to reproduce:
1. Go to a project with a git that's init and has a significant number of branches(production grade eg.)
2. tab on `git diff` followed by a space
3. watch the beach ball spin
4. Then wait for the tooltip with the list of branches to (not) render.

### Expected behaviour

```shell
Supposed to render the text of all the branches related in the `git diff`
```

### Screenshots

https://user-images.githubusercontent.com/7111524/132012765-db251b12-96bc-4d86-90ce-04ecb6d5a84c.mov

### Operating System

MacOS

### OS Version

11.5.2

### Additional context

```shell
Although just a hunch - it might not be viewable if there aren't enough branches to explain what's going on. 

Some guesses I could make is that the text only renders once the fetch is complete, while the UI populates the list completely along with the description of each branch?

So 

Branch Name
 -> Commit
 -> Commit number
 -> commit description

Except Commit shows up blank
```

**Comment by elviskahoro** [comment]
Should be fixed. Please reopen if still broken.
