### ISSUE TITLE
Missing lsd from completion spec

### ISSUE THREAD

**Issue by guytavor** [warpdotdev/Warp#1662]
### Discord username (optional)

gtx#4760

### Describe the bug

Auto-complete does not list files for some commands.

`cat x/<tab>` brings a list of all files to choose from, BUT
`ls x/<tab>` does not.

### To Reproduce

$ mkdir -p /tmp/x
$ echo "hello, world!" >> /tmp/x/myfile
$ echo "hello, world!" >> /tmp/x/myfile22
$ cd /tmp
now type
ls x/<tab>
A list of files under X does not appear.

### Expected behaviour

ls x/<tab>
should display a list of files to choose from, or autocomplete to the single file that exists there

### Operating System

MacOS

### OS Version

12.5

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Warp Version

0.2022.07.18.09

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for opening can you send a video?

**Comment by guytavor** [comment]
A video will just show me doing `ls x/` and nothing happens.
I figured out why this happens.
On my machine I have the following alias:
`ls=lsd`
this prevents warp from activating the completions.
if I override the alias by using `\ls x/` and click <tab> the completion *does* come up.

**Comment by elviskahoro** [comment]
The team is currently in the process of updating the completion specs. Next week let's cirlce back and see whether LSD was added.

**Comment by guytavor** [comment]
Thanks

**Comment by guytavor** [comment]
Thanks!

**Comment by alokedesai** [comment]
Hey @guytavor we sent a fix for this recently. We expect this to be available to all users on our stable build next thursday. Thanks for your patience here!

**Comment by elviskahoro** [comment]
This should be out now!
