### ISSUE TITLE
Crashed after running diff

### ISSUE THREAD

**Issue by sfragis** [warpdotdev/Warp#1670]
### Describe the bug

Just installed the fresh version `v0.2022.07.25.09.05.stable_01`.
I start a new session and run `diff -r path1 path2` without skipping binary files (mostly zip files): Warp crashes as soon as some non printable bytes are output.
Attached is the crash report.

### To Reproduce

Just diff some binary files to standard output. Piping the output to less cause no harm instead.

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.07.25.09.05.stable_01

### Additional context

[warp crash report.txt](https://github.com/warpdotdev/Warp/files/9217068/warp.crash.report.txt)

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for opening and also including the logs.

**Comment by alokedesai** [comment]
@sfragis We believe this is fixed so going to close out. Please reopen if you're still experiencing this issue!
