### ISSUE TITLE
mitmproxy doesn't work as expected

### ISSUE THREAD

**Issue by sfragis** [warpdotdev/Warp#1671]
### Describe the bug

I use [mitmproxy](https://mitmproxy.org/) as a reverse proxy for rapid development of APIs and web apps. If I run it in Warp it appears incomplete, the bars are in the wrong place and it's actually unusable (screenshot 1). Compare it to how it works in Terminal (screenshot 2).
Resizing Warp's window helps a bit but I have to find the right size to have everything in place (and still there're some issues as you can see in the screenshot 3). 

### To Reproduce

Just open `mitmproxy` in Warp with a command like this one:

```
mitmproxy -p 7001 --mode reverse:https://ipinfo.io
```

### Expected behaviour

See screenshot 2: this is how mitmproxy works in Terminal.

### Screenshots

Screenshot nr 1:

<img width="1136" alt="#1 - mitmproxy in warp" src="https://user-images.githubusercontent.com/337381/181707805-b140f950-fb37-48c6-811b-722f11b3bdbe.png">

Screenshot nr 2:

<img width="1060" alt="#2 - mitmproxy in terminal" src="https://user-images.githubusercontent.com/337381/181707814-6b89f873-c255-4833-b932-d8a33a346ddd.png">

Screenshot nr 3:

<img width="1157" alt="#3 - mitmproxy in warp after resizing" src="https://user-images.githubusercontent.com/337381/181707822-f052ff06-da47-4a00-b297-93855761ad34.png">

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.07.25.09.05.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by elviskahoro** [comment]
Thanks for opening. Will let you know when there are updates!

**Comment by wmorgue** [comment]
Same here 🥲

**Comment by nichoj10** [comment]
Hi all, this should be fixed as of v0.2022.12.06.08.03.stable_01 (release from ~2 weeks ago). Let us know if you have any problems!

**Comment by wmorgue** [comment]
It works in my case, I confirm 🎉

**Comment by matthewmturner** [comment]
Works for me as well. Thanks!

**Comment by sfragis** [comment]
It works for me as well, thank you! 🥳

**Comment by LicketySpliket** [comment]
Are you able to scroll/click inside MITMProxy in Warp? Not working for me on latest MacOS/Warp v0.2024.01.16.16.31.stable_01.
