### ISSUE TITLE
Support setting Warp to open Fish shell by default with full support of Fish

### ISSUE THREAD

**Issue by nikitavoloboev** [warpdotdev/Warp#1674]
### Discord username (optional)

nikivi#5640

### Describe the solution you'd like?

I [asked this question on Discord](https://discord.com/channels/851854972600451112/852249738002956311/1002589849720721518) but got no reply, after a while I noticed that neither of these work in Warp from my testing:

1. setting default shell to Fish
2. have history search work in Fish
3. have blocks work in Fish

This a huge blocker for me as I'd love to migrate to [Fish shell](https://fishshell.com) but still use Warp.

**Comment by elviskahoro** [comment]
I answered in Discord.
