### ISSUE TITLE
Missing nvim-tree icon when using warp

### ISSUE THREAD

**Issue by kayac-chang** [warpdotdev/Warp#1675]
### Describe the bug

Icon disappear when using nvim-tree.
Only happened on warp, iTerm2 still work fine.

### To Reproduce

```
git clone https://github.com/brainfucksec/neovim-lua
ln -s neo-vim-lua/nvim ~/.config/nvim
```

### Screenshots

1. Test on Iterm2
<img width="1440" alt="Screen Shot 2022-07-30 at 8 50 48 PM" src="https://user-images.githubusercontent.com/32451546/181915292-8c6e206e-13c0-4b10-afc5-27353b956574.png">

2. Test on Warp
![Screen Shot 2022-07-30 at 8 50 57 PM](https://user-images.githubusercontent.com/32451546/181915321-819a099a-31a0-43b1-9d41-9680c83af73a.png)

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.07.25.09.05.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for flagging! There's a number of vim stuff that needs fixing

**Comment by zheng** [comment]
Hi @kayac-chang, I've installed the plugin and it seems to be working just fine for me in Warp. Do you have the same font in Warp that you have set in iTerm2?

To troubleshoot, in nvim, you can type `:help nvim-tree-commands` and then go to line 36. It has a line that says `  should look like an open folder`. And it should show the open folder icon in Warp if you have the right font set.

<img width="484" alt="Screen Shot 2022-08-08 at 2 03 30 PM" src="https://user-images.githubusercontent.com/29991019/183514246-5ea9e81a-b17a-4c5b-907e-5c3df5708620.png">

**Comment by kayac-chang** [comment]
Hello @zheng, thank you for your help!!!
After set up same font in iTerm2, it's work fine now.
Close this issue here.
