### ISSUE TITLE
Opening Find popup should auto-select existing search text

### ISSUE THREAD

**Issue by salamagd** [warpdotdev/Warp#1680]
### Describe the bug

When opening the Find popup, the existing search text should be auto-selected, so that typing or pasting any new text will overwrite the existing value.

### To Reproduce

1. Press ⌘F and then ⌘V to paste text to search
2. Search text should be updated with the text from the clipboard
3. If you had previously made a search, the new search text will be appended onto the existing text

### Expected behaviour

Search text should be replaced with the new entry. It is extremely unlikely that a user actually wants to append to their existing search text after pressing ⌘F.

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.07.25.09.05.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
This came out today actually.

**Comment by salamagd** [comment]
Thanks a lot @elviskahoro 🙇‍♂️
