### ISSUE TITLE
How do I change Warp from zsh to bash?

### ISSUE THREAD

**Issue by sagnik** [warpdotdev/Warp#1681]
### Describe the solution you'd like?

```text
This might be a stupid question, but I can not find how to change the default shell to bash. On The mac-OS terminal, I can do this (In preferences->general):

Shells open with:
  - [ ] default login shell
  - [ ] Command (complete path): /bin/bash

How to do this in Warp?
```

### Additional context

<img width="582" alt="image" src="https://user-images.githubusercontent.com/4563472/182683062-18b63937-7909-4c0f-8218-f9463f6ddb10.png">

### How important is this feature to you?

5 (Can't work without it!)

**Comment by warpdotdev-dx** [comment]
Warp uses your login shell by default. There's another issue for specifying which shell to load:
GitHub issue for specifying which shell to use: https://github.com/warpdotdev/Warp/issues/132
