### ISSUE TITLE
Active pane marker obscures top left character

### ISSUE THREAD

**Issue by markshep** [warpdotdev/Warp#1682]
### Describe the bug

When using a full-screen interactive command (e.g. emacs) the triangular active pane marker mostly obscures the character in the top left position.  Please can you change the active pane marker to something which doesn't obscure the terminal contents, such as making the pane's border a different colour?

### To Reproduce

Run a full-screen interactive command that has content in the top left character cell.

### Expected behaviour

I can see all the content in the current pane.

### Screenshots

![Screenshot 2022-08-03 at 23 07 25](https://user-images.githubusercontent.com/490067/182721049-deb3983f-ddf7-474f-870e-40326fda657a.png)

### Operating System

MacOS

### OS Version

12.5

### Shell Version

GNU bash, version 5.1.16(1)-release (x86_64-apple-darwin21.1.0)

### Warp Version

v0.2022.08.01.09.12.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for opening this. Will circle back once there are updates.

**Comment by dannyneira** [comment]
Hi @markshep We've made some improvements to the padding in panes to reduce the change of blocking text. Please update to the latest version and let us know if this helped with your pain point.

**Comment by dannyneira** [comment]
We are working on adding some padding to address this pain point.
Tracking  general improvements to the active pane indicator here: https://github.com/warpdotdev/Warp/issues/304

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
