### ISSUE TITLE
Switch tabs with cmd + option (left arrow, right arrow) in addition to cmd + numbers (1-9)

### ISSUE THREAD

**Issue by sidv-z** [warpdotdev/Warp#1684]
### Describe the solution you'd like?

```text
Like in browsers, there should be an option switch tabs with option + cmd + left or right arrow to move between adjacent tabs.
```

### Is your feature request related to a problem? Please describe.

```text
Yes, I want to move between adjacent terminal tabs quickly, thinking about tab number slows me down
```

### How important is this feature to you?

4

**Comment by elviskahoro** [comment]
Hey!

Just made a loom for you. Those keybindings are currently mapped to switch panes, but you can remap them so that they switch tabs left and right.

https://www.loom.com/share/3f6857f3201e4817bba705b179c71e92
