### ISSUE TITLE
Integrate with Intellij terminal

### ISSUE THREAD

**Issue by vlio20** [warpdotdev/Warp#1686]
### Describe the solution you'd like?

```text
Many engineers are using the built in terminal in their preferred editor - I am using Intellij.
It would be great to have Warp available there.
```

### How important is this feature to you?

4

**Comment by elviskahoro** [comment]
Thanks for opening. Gonna close in favor of #472

**Comment by mpiniarski** [comment]
As the https://github.com/warpdotdev/Warp/issues/472 does not allow to add comments, I'll share it here:

There is a NewTerminal (currently in beta) in IntelliJ that has some of features Warp has and might be an alternative: https://www.jetbrains.com/help/idea/terminal-emulator.html#new-terminal

**Comment by Jitsusama** [comment]
> As the #472 does not allow to add comments, I'll share it here:
> 
> There is a NewTerminal (currently in beta) in IntelliJ that has some of features Warp has and might be an alternative: https://www.jetbrains.com/help/idea/terminal-emulator.html#new-terminal

It's insane how much of a blatant rip-off of Warp this is.
