### ISSUE TITLE
Shortcuts for changing pane now working when maximized

### ISSUE THREAD

**Issue by ialiendeg** [warpdotdev/Warp#1687]
### Describe the bug

When a shortcut for changing pane is used in a maximized pane, a character is returned instead of changing the pane.

### To Reproduce

Create a right split pane with <cmd-d>, then press the shortcut for changing to the left pane (<meta-j> for me) and the focus is now in the first one.

Now maximize the pane with <shift-cmd-enter> and try to change to the next pane again with the shortcut (<meta-k> for me), a `§` character appears and nothing happens. The same happens when changing to previous pane or using a different shortcut, a character is written but the change does not happen.

### Expected behaviour

The changing of pane should happen regardless of the maximize state of the panes.

### Operating System

MacOS

### OS Version

11.6.8

### Shell Version

zsh 5.8 (x86_64-apple-darwin20.0)

### Warp Version

v0.2022.08.01.09.12.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by elviskahoro** [comment]
Thanks for reporting. 
@ialiendeg i think this was fixed. Please comment if it hasn't been.

**Comment by ialiendeg** [comment]
@elviskahoro , now it changes pane correctly, but then it returns to unmaximized state.

**Comment by zachlloyd** [comment]
For now that's the intended behavior - OOC what were you expecting to
happen?  change panes while staying maximized?  We could potentially do that

**Comment by ialiendeg** [comment]
Yes, I'd expect the maximized status to remain the same because I only want to change pane, with the current behaviour it's not usable for me.

**Comment by elviskahoro** [comment]
@ialiendeg @zachlloyd I've made a new github issue for this specific feature request. Please subscribe to it @ialiendeg so you're notified when it launches!

https://github.com/warpdotdev/Warp/issues/1718#issue-1339158245

**Comment by ialiendeg** [comment]
Subscribed. Thx!
