### ISSUE TITLE
Featur Request: set Warp as default Terminal App in options

### ISSUE THREAD

**Issue by muescha** [warpdotdev/Warp#1690]
### Discord username (optional)

Muescha#3499

### Describe the solution you'd like?

```text
i like to have an option to set Warp as the default Terminal app
```

### Is your feature request related to a problem? Please describe.

```text
when i click in Docker Desktop to open the Terminal 
other apps are opened but not Warp
```

### Additional context

Similar option in other apps: https://superuser.com/questions/379342/setting-iterm2-as-the-default-terminal-osx-lion

### How important is this feature to you?

1 (Not too important)

**Comment by elviskahoro** [comment]
Thanks for opening. Closing in favor of #753
