### ISSUE TITLE
Wrong shortcut displayed for Rename the Current Tab in the menu

### ISSUE THREAD

**Issue by assayire** [warpdotdev/Warp#1691]
### Discord username (optional)

higherkindedtype#4936

### Describe the bug

Bug: The shortcut displayed besides _Rename the Current Tab_ menu item is not right. Either it is cut off or not showing the right shortcut (Alt-F2). See screenshot below.

### To Reproduce

See description

### Expected behaviour

Shortcut should be Alt=F2 (or whatever the user has (re)configured)

### Screenshots

![unknown](https://user-images.githubusercontent.com/66568479/183268898-31913f35-ddcf-47cd-9acf-409dcf66aa7e.png)

Tagging @zachlloyd as [**requested**](https://discord.com/channels/851854972600451112/1005148965030866944/1005220509912404070).

### OS Version

macOS 11.6.7

### Shell Version

NA

### Warp Version

v0.2022.08.01.12.49.beta_02

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for opening. Will update you when there some.
