### ISSUE TITLE
Error retrieving current directory when I try to open a split terminal

### ISSUE THREAD

**Issue by neo-franklin-tina** [warpdotdev/Warp#1698]
### Describe the bug

When a I try to open a split terminal `Shift+Command+D`, I get the following error:
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
```
<img width="644" alt="Screen Shot 2022-08-08 at 12 33 46" src="https://user-images.githubusercontent.com/76698025/183478679-f7d44acf-5797-424a-a051-9818b50d13db.png">

### To Reproduce

1. Open the Warp terminal
2. Navigate to a project's directory
3. Press `Shift+Command+D`

### Expected behaviour

Before the error started occurring (today), it will create a new split terminal in the current directory as the one above

### Screenshots

<img width="644" alt="Screen Shot 2022-08-08 at 12 33 46" src="https://user-images.githubusercontent.com/76698025/183478679-f7d44acf-5797-424a-a051-9818b50d13db.png">

### Operating System

MacOS

### OS Version

12.5

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)

### Warp Version

Current version is v0.2022.08.01.09.12.stable_02

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for opening. Will update you when we have some. Might reach out for help reproducing.

**Comment by neo-franklin-tina** [comment]
Hi @elviskahoro, just an update on this.
I re-installed Warp after this, and the problem went away.
I don't know if I should close this now or leave it open for further investigation. 
Thanks for reaching out, 
Thanks for making Warp!

**Comment by elviskahoro** [comment]
Thanks for following up!
