### ISSUE TITLE
Warp should auto append a whitespace after the command auto-complete

### ISSUE THREAD

**Issue by azone** [warpdotdev/Warp#1699]
### Describe the bug

When I input the command and press the `<tab>` key to auto-complete, the auto-complete function was doing well, but no whitespace after the command. We usually need to add some parameters after the command, so this makes me feel very inconvenient.

### To Reproduce

1. Open Warp
2. Input a command like `git com`
3. press `<tab>` key

### Screenshots

https://user-images.githubusercontent.com/164407/183612400-bab7d49a-52d8-4793-81b2-62527248c164.mp4

### Operating System

MacOS

### OS Version

12.4

### Shell Version

fish, version 3.5.1

### Warp Version

v0.2022.08.01.09.12.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by elviskahoro** [comment]
Hey!

Thanks for opening. We're actually tracking this issue here:
https://github.com/warpdotdev/warp/issues/290
