### ISSUE TITLE
Theming: Ability to set background transparency / transparent / opacity

### ISSUE THREAD

**Issue by domderen** [warpdotdev/Warp#17]
**Is your feature request related to a problem? Please describe.**
I normally set my terminal to have a semi-transparent background, to be able to see windows beneath it. This allows me to see a website with an article or a tutorial in the background while still being able to work in a terminal. It's much easier than switching between windows.

**Describe the solution you'd like**
Add the ability to set background transparency.

**Additional context**
I usually work just on my laptop, no external monitors.

**Comment by elviskahoro** [comment]
https://github.com/warpdotdev/warp/issues/32
https://github.com/warpdotdev/warp/issues/45
https://github.com/warpdotdev/warp/issues/127

**Comment by gagata** [comment]
Hey! This one is in the works - as we continue iterating on themes and other related features.

**Comment by nicoeg** [comment]
Blur would be a very nice addition as well.

**Comment by shmidt** [comment]
Would be great too add theming support. I personally big fan of Solarize theme

**Comment by elviskahoro** [comment]
@shmidt checkout this guide on themes we have plenty you can download and use!
https://github.com/warpdotdev/themes

**Comment by elviskahoro** [comment]
From @zdzielinski via themes repo

This would be a great feature to have. Generally, I prefer to have a transparent terminal in order to see content in other windows during use. It would be nice to have the ability to specify opacity at a global level, both via yaml customization; and potentially as a "slider" for default themes.

**Comment by madisonhope** [comment]
I just wanted to chime in here to say this and tab names are what's keeping me from switching over full-time.  And I've used iTerm since my first dev job with a Mac, so kudos for giving a terminal the UX refresh it deserves!

**Comment by ramzzzay** [comment]
I'm here to say -- this is must have feature.  :)
I'm using it every day in Iterm.

**Comment by kuldeeprishi** [comment]
+1 for this feature

**Comment by raaspazasu** [comment]
Can I add on adding a blur option as well?

**Comment by ramzzzay** [comment]
> Can I add on adding a blur option as well?

Yep, I've used iTerm transparent with blur.

**Comment by tuortheblessed** [comment]
Transparency, would Love this instead of a solid block of color or static image.

**Comment by Delorfindel** [comment]
+1 would be a game changer

**Comment by yoannsark-decath** [comment]
+1 the only feature that Warp needs...

**Comment by dim-vin** [comment]
+1 transparency would force me off iterm2!

**Comment by elviskahoro** [comment]
We still don't have an ETA on this apologies folks.

**Comment by denodaeus** [comment]
Why is it that every time someone rolls a new terminal (Microsoft, Warp), I fall in love with it and it's literally missing one of the most important productivity features for users on laptops  without an external monitor who travel a lot?

I really love Warp after trying it, but the transparency thing makes me keep going back to Hyper until it's available.

**Comment by jonesaustindev** [comment]
i would leave iTerm2 completely for warp if transparency is added. hope that could be soon.

**Comment by warpdotdev-dx** [comment]
Still no ETA.

--- original message ---
On August 19, 2022, 5:21 PM EDT ***@***.*** wrote:



i would leave iTerm2 completely for warp if transparency is added. hope that could be soon.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by codeyash** [comment]
+1

**Comment by menyinch** [comment]
Any news?

**Comment by Bobeta** [comment]
+1

**Comment by GiancarloGomez** [comment]
+1

**Comment by menyinch** [comment]
+1

**Comment by shooooori0128** [comment]
+1

**Comment by sohaha** [comment]
Any update on the progress of Is there any latest progress?

**Comment by zdzielinski** [comment]
@gagata Any updates? It's been a year or so at this point - Figure I'd try and @ someone directly.

**Comment by gnomeria** [comment]
Definitely a must have feature for many folks to try this terminal.

**Comment by goens** [comment]
+1

**Comment by bilal-kilic** [comment]
+1

**Comment by pkoczan-plaid** [comment]
massive +1

**Comment by pmontp19** [comment]
Maybe to avoid notifying everyone in this thread with +1 spam, we can show support for this feature with emojis 👍 on OP post. Also, if you intend to be updated, you can subscribe to this thread on the right side pane.

**Comment by somoza** [comment]
I do need opacity + blur, is not a wish Is a necessity. +1

**Comment by kvrvgixzis** [comment]
for top hotkey terminal opacity is required

**Comment by stephan-v** [comment]
+1 This would make me switch over.

**Comment by ilja275** [comment]
+1 for opacity

**Comment by MartinBischofNNA** [comment]
+1 for opacity

**Comment by altitudedashboard** [comment]
+1

**Comment by dannyneira** [comment]
Hi Folks, this is on the roadmap and being worked on. We'll update here once it's live!

**Comment by ascendedco** [comment]
@dannyneira Thanks so much! Excited to finally use Warp as a main terminal

**Comment by rog** [comment]
+1

**Comment by aneeley05** [comment]
Very excited to be able to use this terminal full time!

**Comment by nfwyst** [comment]
no any update?

**Comment by dannyneira** [comment]
@nfwyst Yup it's launching on Warp Stable this week! Already on [Warp Preview](https://warpdev.notion.site/Warp-Ambassadors-7aeacbc565694985a64710871470af67)

Sneak Peek:
https://user-images.githubusercontent.com/16809145/211429505-2e1b46ed-2e5f-4f7c-b200-6b3142e85f1c.mp4

**Comment by nickroberts** [comment]
I'm on version `v0.2023.01.10.08.02.stable_01`, and it looks great! Nice work!

**Comment by ascendedco** [comment]
Thanks a ton @dannyneira !

**Comment by ramzzzay** [comment]
Best ever update. Thanks!

**Comment by maksimr** [comment]
Nice update, but it would be great to have a keyboard shortcut to enable/disable opacity (like in iTerm)

Thx 🙏

**Comment by NAKKA-K** [comment]
> Nice update, but it would be great to have a keyboard shortcut to enable/disable opacity (like in iTerm)

I agree with you, too.
It is especially used for screen sharing.

**Comment by elviskahoro** [comment]
@NAKKA-K @maksimr Just opened a new issue:
https://github.com/warpdotdev/Warp/issues/3327
