### ISSUE TITLE
Warp crashing many times

### ISSUE THREAD

**Issue by jeremybarbet** [warpdotdev/Warp#1703]
### Describe the bug

Warp crashes unexpectedly. It happened already 3 times in ~6 hours of usage. Here are the crash logs:

[Report 1](https://pastebin.com/qL8NKxBw)
[Report 2](https://pastebin.com/Pbr12rbG)
[Report 3](https://pastebin.com/gZxpRxSm)

### To Reproduce

I don't have a good way to reproduce that sorry. It just happened randomly while doing some "basics" commands, e.g. `yarn start`, `yarn add`, and/or moving between tabs.

### Operating System

MacOS

### OS Version

12.4

### Shell Version

fish, version 3.3.1

### Warp Version

v0.2022.08.01.09.12.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by elviskahoro** [comment]
Thanks for including the crash reports. Will follow up with updates when we have them.
