### ISSUE TITLE
Show history doesn't show the last command

### ISSUE THREAD

**Issue by eidan66** [warpdotdev/Warp#1706]
### Discord username (optional)

idan#7367

### Describe the bug

Hey! I write some commands (for example - `yarn`), and when i click the upper arrow, to see the commands history (to re-command the last command), it doesn't appears there 😢 

### To Reproduce

1. Run some commands (ex: `yarn` | `git commit -am "Hello world"` | more random commands).
2. Open the History command popup.
3. look for the last command.

### Expected behaviour

See the last command i wrote

### Screenshots

![image](https://user-images.githubusercontent.com/41434778/184075143-91e8ab3f-c125-4462-b7b9-b15993c558af.png)

### Operating System

MacOS

### OS Version

12.5

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.08.08.09.21.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by szgupta** [comment]
Hey @eidan66, from the screenshot you posted, it seems that you might have a space character (` `) before the command (in the example, `yarn`). In this case, what's likely happening is that you have your [`HISTCONTROL`](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#:~:text=is%20subsequently%20reset.-,HISTCONTROL,-A%20colon%2Dseparated) var set to `ignorespace` (or `ignoreboth`) which essentially means that commands prefixed with a space will not show up in your history
> If the list of values includes ‘ignorespace’, lines which begin with a space character are not saved in the history list.

But that's not uncommon -- I'm a little more confused why there's a space before the command in the first place. Are you manually adding a space before the command, or is it automatically getting inserted there?

**Comment by eidan66** [comment]
> Hey @eidan66, from the screenshot you posted, it seems that you might have a space character (` `) before the command (in the example, `yarn`). In this case, what's likely happening is that you have your [`HISTCONTROL`](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#:~:text=is%20subsequently%20reset.-,HISTCONTROL,-A%20colon%2Dseparated) var set to `ignorespace` (or `ignoreboth`) which essentially means that commands prefixed with a space will not show up in your history
> 
> > If the list of values includes ‘ignorespace’, lines which begin with a space character are not saved in the history list.
> 
> 
> 
> But that's not uncommon -- I'm a little more confused why there's a space before the command in the first place. Are you manually adding a space before the command, or is it automatically getting inserted there?

Hmm, Didn't know about this space before. Is adding it automatically to there 🫣

**Comment by szgupta** [comment]
Would you be comfortable sharing your `.zshrc` file (with any PII redacted) with us so that we can try to reproduce the issue on our end?

**Comment by szgupta** [comment]
If so, feel free to email the dotfile to `suraj@warp.dev` :)

**Comment by elviskahoro** [comment]
@eidan66 do you normally have OMZ btw?

**Comment by eidan66** [comment]
Sorry, waiting for my boss to approve sending all the information there in this file :)

**Comment by elviskahoro** [comment]
You don't need to send everything actually. @eidan66 

The best way to debug what's causing this--it's likely something in your config if blank ones worked--is to disable everything (just for Warp) by placing it behind this flag:

```sh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

    # POWERLEVEL10K

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi
```

Then repeatedly / iteratively re-enable things by moving them out of the conditional until you drill down on the culprit.

**Comment by eidan66** [comment]
Ok, i will try.
We want to check what cause us the spaces?

**Comment by eidan66** [comment]
> You don't need to send everything actually. @eidan66
> 
> The best way to debug what's causing this--it's likely something in your config if blank ones worked--is to disable everything (just for Warp) by placing it behind this flag:
> 
> ```shell
> if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
> ##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW
> 
>     # POWERLEVEL10K
> 
> ##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
> fi
> ```
> 
> Then repeatedly / iteratively re-enable things by moving them out of the conditional until you drill down on the culprit.

I tried this in this way:
```shell
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
ZSH_THEME="powerlevel9k/powerlevel9k"
fi
```

And now, the spaces are gone when i start write commands in the terminal

**Comment by warpdotdev-dx** [comment]
Ah I see! That makes sense. We actually don't support powerlevel10k or powerlevel9k, check out these docs:
<https://docs.warp.dev/features/prompt#powerlevel10k-p10k>

**Comment by eidan66** [comment]
Oki, after few days of work with this change, i able to see the history correct!
Thanks for the help!

**Comment by warpdotdev-dx** [comment]
Also check out this link:
https://github.com/warpdotdev/Warp/issues/734#issuecomment-1042656530
