### ISSUE TITLE
Commands history get the command with unnecessary detailes

### ISSUE THREAD

**Issue by eidan66** [warpdotdev/Warp#1707]
### Discord username (optional)

idan#7367

### Describe the bug

When we use the last commit feature, we can see extra details that are added to the last commit (from the theme: `powerlevel9k`).

### To Reproduce

1. Install the theme: `powerlevel9k`.
2. Use some commands.
3. Try to use the last command and you will see in the history the commands with the extra non-relevant details.

### Expected behaviour

To see only the command without `powerlevel9k` theme details.

### The terminal block
![image](https://user-images.githubusercontent.com/41434778/184087542-2689ee1e-7ddf-485a-a2d0-05f44b909a60.png)

### The problem in the lasts commands
![Screen Shot 2022-08-11 at 10 49 03](https://user-images.githubusercontent.com/41434778/184088850-062f4206-94b1-4435-b84d-75c5cd910e9a.png)

### Operating System

MacOS

### OS Version

12.5

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.08.08.09.21.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by gagata** [comment]
Hey! This is a known issue. As of now, powerlevel is not compatible with Warp. 

You can conditionally turn it off for Warp by following the steps from the doc https://docs.warp.dev/help/known-issues#debugging

Sorry for the inconvenience!

**Comment by elviskahoro** [comment]
Specifically this section. You want to move P10K and P9K to behind the conditional so it's disabled just for Warp.
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

    # POWERLEVEL10K

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi
