### ISSUE TITLE
Zsh completions that work in iTerm do not work in Warp

### ISSUE THREAD

**Issue by petrbouchal** [warpdotdev/Warp#1708]
### Describe the bug

For `m-cli`, zsh autocompletions do not appear in Warp but they do in iTerm.

### To Reproduce

1. `brew install m-cli`
2. type `m` and `Tab`

Completions appear in iTerm, not in Warp.
Other completions 

### Expected behaviour

Completions should appear in tab-able menu as they do for many other commands.

### Operating System

MacOS

### OS Version

12.5

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.08.08.09.21.stable_00

### Additional context

Filing mostly to see if it can be reproduced or if there is a clear cause.

The autocompletions are defined in https://raw.githubusercontent.com/rgcr/m-cli/master/completion/zsh/_m

Additionally, `which _m` returns this in iTerm

```
_m () {
	local -a opts
	local commands
	commands=(help "--update:update m-cli to the latest version" "--uninstall:uninstall m-cli" "airdrop:manage airdrop status" "battery:get the battery status" "bluetooth:manage bluetooth status" "dir:show and delete dir trees" "disk:manage disks and volumes" "display:display settings" "dns:manage dns" "dock:manage dock" "finder:manage finder properties" "firewall:manage firewall" "flightmode:manage flightmode" "gatekeeper:manage gatekeeper (security for apps)" "group:manage groups" "hostname:displays or set the computer's hostname" "info:print macOS operating system version information" "itunes:itunes command line control" "localhost:manage localhost file" "lock:lock session" "network:manage interfaces and locations" "nosleep:prevent sleeping" "notification:manage the notification settings" "ntp:manage the network time service" "printer:display information about the printers" "restart:restart computer" "safeboot:manage safeboot" "screensaver:launch and manage the screensaver" "service:manage services" "shutdown:shutdown computer" "sleep:put the computer to sleep" "timezone:manage timezone" "touchbar:manage touchbar" "trash:manage the trash" "user:manage users" "update:manage macOS updates" "volume:manage the sound's volume" "vpn:basic vpn operations, start, stop, status, list" "wallpaper:set the wallpaper" "wifi:manage the wifi")
	case $CURRENT in
		(2) _describe 'm commands' opts -- commands ;;
		(*) local sub=${words[2]}
			_m_cmd $sub ;;
	esac
}
```
but this in Warp:

```
_m () {
	# undefined
	builtin autoload -XUz
}
```

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Our completions are not sourced from the shell but a completion spec that we ship with Warp. The spec will eventually be open sourced so people can contribute their own completions. See #434
