### ISSUE TITLE
Emacs doesn't render properly- right side blank - stty size, tput cols, $COLUMNS return incorrect column width

### ISSUE THREAD

**Issue by eddof13** [warpdotdev/Warp#1710]
### Describe the bug

In Emacs 28.1 it isn't rendering the entire screen- this displays fine in iTerm2 and Terminal
stty size, tput cols, $COLUMNS return incorrect column width

### To Reproduce

My emacs config https://github.com/eddof13/config/blob/master/.emacs

### Screenshots

<img width="1440" alt="Screen Shot 2022-08-11 at 16 14 52" src="https://user-images.githubusercontent.com/1346/184243904-4b2bd516-9ad6-4060-bf1a-0aa52e4fe3d2.png">

### Operating System

MacOS

### OS Version

12.5

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.08.08.09.21.stable_00

### Additional context

➜  ~ omz version
omz version
master (835a0a5)

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for reporting. Will update you when we have some.

**Comment by alokedesai** [comment]
@eddof13 Does this repro consistently for you? Does it repro without the config?

**Comment by eddof13** [comment]
@alokedesai I did some debugging on the config- and the error seems to appear specifically with the menu bar disabled: commenting out `(menu-bar-mode -1)` appears to fix the display for the most part (except a tiny square on the bottom right)

Note: I do suspect this is still some issue between Warp and emacs, given this displays correctly in iterm2 and Terminal (and I doubt it's an emacs specific bug)

**Comment by eddof13** [comment]
<img width="1728" alt="Screen Shot 2022-08-21 at 12 55 14 PM" src="https://user-images.githubusercontent.com/1346/185804447-d9a32211-c6ad-4784-9754-1f2500498491.png">

**Comment by eddof13** [comment]
@alokedesai some more details:

The following is the output from the warp terminal:
tput cols
209
tput lines
65

when menu-bar-mode is disable it is reading those values 'correctly' and emacs is showing 209 columns, which is not the actual column width of the terminal

when menu-bar-mode is enabled it is not reading those values apparently, because emacs is more like 216 columns, which is the actual column width of the terminal

I think tput cols should be returning 216 or thereabouts but it is not

**Comment by alokedesai** [comment]
Does this only repro with certain files? I can't repro with that config you linked, which is somewhat odd

**Comment by eddof13** [comment]
No, it can be done without any file at all. If you run 'tput cols' on your machine are you getting the correct value for your terminal width? That could be part of it

**Comment by eddof13** [comment]
@alokedesai I just came up with a workaround:

warp outputs:
stty size
65 209

I added to .zshrc:
stty cols 216

and now it works correctly. for whatever reason the column sizing in $COLUMNS (based on that font I guess?) is not correct

**Comment by alokedesai** [comment]
@eddof13 thanks for all your detailed instructions here, @dannyneira was able to get a repro. We'll investigate what's causing this and get back to you shortly

**Comment by alokedesai** [comment]
Does this repro in other terminals for you? This is what I'm seeing in iterm, for example:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/4110292/186675384-f511931b-6c30-4205-930b-18b82d413788.png">

**Comment by eddof13** [comment]
@alokedesai I tested it again in Terminal and iTerm and it appears to work correctly there, so for me it's just in Warp

in Terminal with it full screen and font set to Hack size 13 I get:
stty size
61 214

in iTerm2 with it full screen and font set to Hack size 13 I get:
stty size
65 214

and as mentioned Warp at full screen and font set to Hack size 13 I get:
stty size
65 209
and it looks good with 216 rather than the 214 the others are showing

**Comment by dannyneira** [comment]
@eddof13 We recently made performance/compatibility updates to alt-screen apps like emacs, please let us know if you're still seeing the issues with the latest version of Warp.

**Comment by eddof13** [comment]
Looks good to me- I think you can mark this one as resolved: 
<img width="1725" alt="Screen Shot 2022-12-27 at 12 05 34 PM" src="https://user-images.githubusercontent.com/1346/209698703-ad0d852a-2b59-41bf-9e2f-5012a9595ef0.png">

**Comment by dannyneira** [comment]
Cool thanks for the update! Feel free to let us know if the issue comes back.

**Comment by szgupta** [comment]
Hey @eddof13, I'm making a change to our alt-screen padding and want to make sure I'm not regressing your emacs experience. Would you be down to test these changes in a custom build?

**Comment by szgupta** [comment]
Hey @eddof13, sorry for the extra nag, but we're close to launching some changes to our alt-screen padding defaults and want to make sure we're not regressing Warp's compatibility with `emacs`. To release these changes safely, we're introducing an explicit opt-in before a full rollout. I would greatly appreciate if you can try out the change here and let me know if it causes problems with your `emacs` setup: https://github.com/warpdotdev/Warp/issues/2373#issuecomment-2492581897!
