### ISSUE TITLE
Settings menu non-responsive when in window is smaller than menu

### ISSUE THREAD

**Issue by dannyneira** [warpdotdev/Warp#1712]
### Describe the bug

The settings menu isn't responsive. When the terminal is not as wide as the settings menu it doesn't adjust to the size of the window.

### To Reproduce

1. Open warp settings menu
2.1 make the terminal window smaller than the settings menu ( vertically and/or horizontally )
2.2 OR, tile the terminal window on the left/right side and adjust the width to be smaller than the settings menu.

### Expected behaviour

Responsiveness on the settings menu, similar to settings menu in slack app for example ( possibly with a minimum size like in slack app).

### Screenshots

Recording: https://www.loom.com/share/2df034d8194a42a493c605f697bd749e
Issue ( Warp Settings Non-responsive ): https://www.loom.com/i/dc2402c3917a463ab03057e73f9cd18b
Expected ( Slack example ): https://www.loom.com/i/a1fe26cfadfc49c0be9a61845fe1a222

### Operating System

MacOS

### OS Version

12.5

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.08.08.09.21.stable_00

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Gonna close in favor of #366
