### ISSUE TITLE
Option to disable bouncing of the dock icon on bell events 

### ISSUE THREAD

**Issue by destroycomputers** [warpdotdev/Warp#1713]
### Describe the solution you'd like?

```text
Are there any plans to be able to disable the dock icon's bouncing on bell? iTerm doesn't ever bounce it simply shows an indicator with the count of events happened. I have a bell being generated on mentions in weechat and Warp bouncing endlessly until I put it in focus is irritating, I'd much prefer the iTerm behaviour here
```

### How important is this feature to you?

3

**Comment by elviskahoro** [comment]
This is a new request! Thanks for opening.

**Comment by gabrielittner** [comment]
This is really needed for the hotkey window. When the warp icon is bouncing the only way to stop it is clicking on it which opens a new regular warp window when you are using the hotkey one.

**Comment by janosmiko** [comment]
+1, it's kinda annoying :(

**Comment by benje** [comment]
+1 I get this too and it's really annoying. Same issue as @gabrielittner

**Comment by mmackowiak** [comment]
+1, indeed, very annoying.

**Comment by elviskahoro** [comment]
gonna merge this into #1932
