### ISSUE TITLE
find highlighting breaks on line wrap

### ISSUE THREAD

**Issue by mvanh** [warpdotdev/Warp#1715]
### Describe the bug

"find" highlighting doesn't work if the text is line wrapped at the first character

### To Reproduce

1. enter a 'find' string to highlight
2. modify window size to force line wrapping
3. shorten/widen the window and highlighting will disappear when the line wrap splits after the first character of the find string

### Expected behaviour

would expect find highlighting to work regardless of line wrap

### Operating System

MacOS

### OS Version

12.5

### Shell Version

5.8.1

### Warp Version

v0.2022.08.08.09.21.stable_00

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for reporting. Will update you when we have some
