### ISSUE TITLE
Double / Triple Click to expand selection to the next text bounds

### ISSUE THREAD

**Issue by muescha** [warpdotdev/Warp#1717]
### Discord username (optional)

Muescha#3499

### Describe the solution you'd like?

```text
i like to have a double or triple click to expand the selection 
to more than one word.


current behaviour:

select word -> select line
```

### Is your feature request related to a problem? Please describe.

```text
Example:

- i search for a brew formula `brew search karabiner`
- i see a result: `karabiner-elements`
- i like to select this result
- i double click on it only one word is selected 
- i triple click the line is selected
- but i like to have some click (with or without modifiers) that i have
  selected the `karabiner-elements` as a result

Same with `ls` when i like to select a directory/file name. 
a double click only select a word but not the full name
```

### Tried this

```text
i tried this - to check if this behaviour already included:

shift + double click -> no luck
  alt + double click -> no luck 
 ctrl + double click -> no luck
  cmd + double click -> no luck

```

### Additional context

Example: `brew` double click

![Bildschirmfoto 2022-08-15 um 16 02 19](https://user-images.githubusercontent.com/184316/184650103-6676ee65-a259-4522-95c3-c6b8b3d7acd5.png)

Example: `brew` triple click

![Bildschirmfoto 2022-08-15 um 16 07 08](https://user-images.githubusercontent.com/184316/184650906-9e8d93dd-f259-427b-84c9-487289baee09.png)

Example: `brew` expected new behaviour result

![Bildschirmfoto 2022-08-15 um 16 09 03](https://user-images.githubusercontent.com/184316/184651258-b9692c41-cc94-43cd-90fc-cea7d843ec11.png)

Example: `ls` double click

![Bildschirmfoto 2022-08-15 um 16 03 39](https://user-images.githubusercontent.com/184316/184650259-83b4ba9d-9e9b-4eb9-882b-80e2897411c2.png)

Example: `ls` triple click

![Bildschirmfoto 2022-08-15 um 16 08 04](https://user-images.githubusercontent.com/184316/184651033-4f8ea569-e475-4adb-8e2f-4722499abbc1.png)

Example: `brew` expected new behaviour result

![Bildschirmfoto 2022-08-15 um 16 09 20](https://user-images.githubusercontent.com/184316/184651286-fa155741-f850-4a8f-8136-8e7e57940b67.png)

### How important is this feature to you?

4

**Comment by warpdotdev-dx** [comment]
Thanks for reporting, we're tracking this here:
GitHub issue for Warp supporting an easy way to copy text patterns and paths: https://github.com/warpdotdev/Warp/issues/659

**Comment by muescha** [comment]
i close this issue in favour of:
#659

**Comment by warpdotdev-dx** [comment]
Thanks for closing!
