### ISSUE TITLE
Double click drag text selection not working in editor block

### ISSUE THREAD

**Issue by warrenbhw** [warpdotdev/Warp#1719]
### Describe the bug

In the text editor (the area where you type out a command), double click+drag text highlighting doesn't work. This is a common gesture that lets you select text by word (single click drag highlights text by character, double click drag highlights text by word). This gesture works in most text editors, and it works on the text output of previously executed blocks in Warp. However, it doesn't work in the editor block.

I use this feature heavily in most text editors, and it would be very helpful to have it in Warp.

### To Reproduce

First, to see how double click + drag text selection is supposed to work, find some text in your browser or in the output of a previously executed block in warp. Double click on a word and, without releasing the left mouse button, continue to drag your mouse to select additional words. You will notice that the text gets highlighted by word (selecting text through to the end of the hovered word, rather than only selecting text through to the hovered character).

Now, to see the issue, type a few words into the editor block in Warp. Double click the first word and, without releasing the left mouse button, drag your cursor to the right, attempting to select additional words. You will notice that the additional words are not selected as you drag your cursor.

### Expected behaviour

First, to see how double click + drag text selection is supposed to work, find some text in your browser or in the output of a previously executed block in warp. Double click on a word and, without releasing the left mouse button, continue to drag your mouse to select additional words. You will notice that the text gets highlighted by word (selecting text through to the end of the hovered word, rather than only selecting text through to the hovered character).
I expect this same behavior when selecting text in the editor block.

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.08.08.09.21.stable_00

### Does this block you from using Warp daily?

No

**Comment by warpdotdev-dx** [comment]
Thanks for opening. Tracking this here:
#1630 can you add your analysis as a comment there.
