### ISSUE TITLE
failed to load referral code

### ISSUE THREAD

**Issue by cutety** [warpdotdev/Warp#1722]
### Describe the bug

warp can not load referral code

### To Reproduce

click `Send a invite` button  on setting menu for Account, referral code won't be loaded.

### Screenshots

![image](https://user-images.githubusercontent.com/38933640/185089859-991b9acf-0909-49e5-814d-4b5853a8dce9.png)
![image](https://user-images.githubusercontent.com/38933640/185090064-26aa8d82-a108-426c-8158-dc4eb07d77fd.png)

### Operating System

MacOS

### OS Version

MacOS 12.5

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.08.08.09.21.stable_00

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Interesting! Thanks for reporting.

**Comment by cutety** [comment]
It works well now, I think it could be my bad internet connection.

**Comment by warpdotdev-dx** [comment]
Thanks for reporting. I'll close it.
