### ISSUE TITLE
I can not open `the Launch Configuration Palette` by using `CTRL`-`CMD`-`L` 

### ISSUE THREAD

**Issue by cutety** [warpdotdev/Warp#1728]
### Describe the bug

I want to save my configuration of windows and tabs so I followed the [document](https://docs.warp.dev/features/session-management/launch-configurations#windows), but it doesn't work for me.
I can not open `the Launch Configuration Palette` by using `CTRL`-`CMD`-`L`. Nothing pops up when I press `CTRL`-`CMD`-`L`

### To Reproduce

 Nothing pops up when I press `CTRL`-`CMD`-`L`

### Expected behaviour

Is there any other entrance for this feature? I really love warp as my terminal tool.If this feature works for me, I will abandon iTerm2:>

### Operating System

MacOS

### OS Version

MacOS 12.5

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.08.08.09.21.stable_00

### Does this block you from using Warp daily?

No

**Comment by cutety** [comment]
I just updated the latest version, this feature works now.

**Comment by warpdotdev-dx** [comment]
Sorry for the confusion. This hasn't come out yet! It comes out today.

**Comment by cutety** [comment]
> Sorry for the confusion. This hasn't come out yet! It comes out today.

This feature helps me a lot in my daily work. Thanks you.
