### ISSUE TITLE
cant ssh a windows10 desktop which installed openssh server

### ISSUE THREAD

**Issue by fireinrain** [warpdotdev/Warp#1729]
### Describe the bug

use ssh login in a remote windows 10 desktop which installed openssh server. but when i use iterm2, it can login success

this is warp:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/14249262/185497939-f1ab2eca-6b2e-4d22-b26a-0e30a78af481.png">

this is iterm2
<img width="378" alt="image" src="https://user-images.githubusercontent.com/14249262/185498046-f5332907-fb90-4aa9-8e3b-7c321fafae8e.png">

### To Reproduce

install warp and use ssh to login in a remote windows10 which installed openssh server

### Operating System

MacOS

### OS Version

10.15.7 

### Shell Version

zsh 5.8

### Warp Version

v0.2022.08.08.09.21.stable_00

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for opening. Will let you know when there are updates on our end.

**Comment by basictheprogram** [comment]
Maybe something wrong on the macOS side? macOS bash problem?
```
sw_vers
ProductName:	macOS
ProductVersion:	12.6.1
BuildVersion:	21G217
```
```
bash --version
GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin21.6.0)
```
```
warp 
v0.2022.12.06.08.03.stable_02
```
The below command works as expected in iTerm.
```
ssh windows10.local

At line:9 char:3
+ if test ${SHELL##*/} != bash -a ${SHELL##*/} != zsh; then
+   ~
Missing '(' after 'if' in if statement.
At line:14 char:6
+  bash) exec -a bash bash --rcfile <(echo 'set -o vi; set +o vi; HISTC ...
+      ~
Unexpected token ')' in expression or statement.
At line:14 char:35
+  bash) exec -a bash bash --rcfile <(echo 'set -o vi; set +o vi; HISTC ...
+                                   ~
The '<' operator is reserved for future use.
At line:16 char:5
+  zsh) WARP_TMP_DIR=$(mktemp -d warptmp.XXXXXX)
+     ~
Unexpected token ')' in expression or statement.
At line:18 char:3
+ if [[ $? == 0 ]]; then
+   ~
Missing '(' after 'if' in if statement.
At line:18 char:5
+ if [[ $? == 0 ]]; then
+     ~
Missing type name after '['.
At line:19 char:27
+  if (( ${+commands[xxd]} )); then
+                           ~
Missing statement block after if ( condition ).
At line:22 char:5
+  for i in {0..$((${#ZSH_ENV_SCRIPT} - 1))..2}; do
+     ~
Missing opening '(' after keyword 'for'.
At line:22 char:50
+  for i in {0..$((${#ZSH_ENV_SCRIPT} - 1))..2}; do
+                                                  ~
Missing statement body in do loop.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
```

**Comment by tetsuyasu** [comment]
> Maybe something wrong on the macOS side? macOS bash problem?
> 
> ```
> sw_vers
> ProductName:	macOS
> ProductVersion:	12.6.1
> BuildVersion:	21G217
> ```
> 
> ```
> bash --version
> GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin21.6.0)
> ```
> 
> ```
> warp 
> v0.2022.12.06.08.03.stable_02
> ```
> 
> The below command works as expected in iTerm.
> 
> ```
> ssh windows10.local
> 
> At line:9 char:3
> + if test ${SHELL##*/} != bash -a ${SHELL##*/} != zsh; then
> +   ~
> Missing '(' after 'if' in if statement.
> At line:14 char:6
> +  bash) exec -a bash bash --rcfile <(echo 'set -o vi; set +o vi; HISTC ...
> +      ~
> Unexpected token ')' in expression or statement.
> At line:14 char:35
> +  bash) exec -a bash bash --rcfile <(echo 'set -o vi; set +o vi; HISTC ...
> +                                   ~
> The '<' operator is reserved for future use.
> At line:16 char:5
> +  zsh) WARP_TMP_DIR=$(mktemp -d warptmp.XXXXXX)
> +     ~
> Unexpected token ')' in expression or statement.
> At line:18 char:3
> + if [[ $? == 0 ]]; then
> +   ~
> Missing '(' after 'if' in if statement.
> At line:18 char:5
> + if [[ $? == 0 ]]; then
> +     ~
> Missing type name after '['.
> At line:19 char:27
> +  if (( ${+commands[xxd]} )); then
> +                           ~
> Missing statement block after if ( condition ).
> At line:22 char:5
> +  for i in {0..$((${#ZSH_ENV_SCRIPT} - 1))..2}; do
> +     ~
> Missing opening '(' after keyword 'for'.
> At line:22 char:50
> +  for i in {0..$((${#ZSH_ENV_SCRIPT} - 1))..2}; do
> +                                                  ~
> Missing statement body in do loop.
>     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
> ```

**Comment by tetsuyasu** [comment]
No, please see the issue #2027.

> > Maybe something wrong on the macOS side? macOS bash problem?
> > ```
> > sw_vers
> > ProductName:	macOS
> > ProductVersion:	12.6.1
> > BuildVersion:	21G217
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > bash --version
> > GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin21.6.0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > warp 
> > v0.2022.12.06.08.03.stable_02
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The below command works as expected in iTerm.
> > ```
> > ssh windows10.local
> > 
> > At line:9 char:3
> > + if test ${SHELL##*/} != bash -a ${SHELL##*/} != zsh; then
> > +   ~
> > Missing '(' after 'if' in if statement.
> > At line:14 char:6
> > +  bash) exec -a bash bash --rcfile <(echo 'set -o vi; set +o vi; HISTC ...
> > +      ~
> > Unexpected token ')' in expression or statement.
> > At line:14 char:35
> > +  bash) exec -a bash bash --rcfile <(echo 'set -o vi; set +o vi; HISTC ...
> > +                                   ~
> > The '<' operator is reserved for future use.
> > At line:16 char:5
> > +  zsh) WARP_TMP_DIR=$(mktemp -d warptmp.XXXXXX)
> > +     ~
> > Unexpected token ')' in expression or statement.
> > At line:18 char:3
> > + if [[ $? == 0 ]]; then
> > +   ~
> > Missing '(' after 'if' in if statement.
> > At line:18 char:5
> > + if [[ $? == 0 ]]; then
> > +     ~
> > Missing type name after '['.
> > At line:19 char:27
> > +  if (( ${+commands[xxd]} )); then
> > +                           ~
> > Missing statement block after if ( condition ).
> > At line:22 char:5
> > +  for i in {0..$((${#ZSH_ENV_SCRIPT} - 1))..2}; do
> > +     ~
> > Missing opening '(' after keyword 'for'.
> > At line:22 char:50
> > +  for i in {0..$((${#ZSH_ENV_SCRIPT} - 1))..2}; do
> > +                                                  ~
> > Missing statement body in do loop.
> >     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
> >     + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
> > ```

No, please see the issue #2027.

**Comment by basictheprogram** [comment]
> No, please see the issue #2027.

Says it's a dup of this issue?

![Cannot_log_in_to_Windows_system_via_ssh__·_Issue__2027_·_warpdotdev_Warp](https://user-images.githubusercontent.com/6723257/208000896-87270192-2c53-4dba-bb3e-5ddcff1a7fec.png)

**Comment by dannyneira** [comment]
Hello everyone, We would like to inform you that we will be closing this feature request and tracking it in the following issue: #2413 

By consolidating the discussions in one place, we can better focus our efforts and provide you with updates on the progress of the issue.

Thank you for your understanding and continued support.
