### ISSUE TITLE
Support tab names in launch configuration

### ISSUE THREAD

**Issue by adamsuskin** [warpdotdev/Warp#1733]
### Describe the solution you'd like?

```text
It would be really nice to be able to set the names of the tabs in launch configuration definitions!
```

### How important is this feature to you?

2

**Comment by elviskahoro** [comment]
Great idea! Will circle back when there are updates

**Comment by gagata** [comment]
hey @adamsuskin this has actually been implemented, i think it was just missing from the docs - I updated the documentation (https://docs.warp.dev/features/session-management/launch-configurations) you can specify the title, and also as of this - a tab color for your configs :)

**Comment by adamsuskin** [comment]
Thanks @gagata!
