### ISSUE TITLE
Triple clicking does not work

### ISSUE THREAD

**Issue by yang** [warpdotdev/Warp#1742]
### Discord username (optional)

yaaang

### Describe the bug

Great app!

If you cat a file with a line that exceeds terminal width, then try double or triple clicking on it to select the whole line, strange things start happening, esp. once you try copy/pasting what you see:

### To Reproduce

generate random long one-line string into a file

cat it

double or triple click to select entire line (notice the selection)

hit cmd+c then cmd+v (notice the paste)

### Expected behaviour

1. Should select the entire line

2. (More importantly) The clipboard content should match the selection (even if the selection is off)

### Screenshots

https://user-images.githubusercontent.com/7129/185759861-9b1bf3fe-b49d-4769-a738-3e9f228791ce.mp4

(I initially thought this was perhaps related to ssh-ing, but it's not - also repro'd with a local file.)

### Operating System

MacOS

### OS Version

12.5

### Shell Version

bash 5.1

### Warp Version

v0.2022.08.16.10.16.stable_02

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for opening. We're tracking this here:
#659 
Will close this in favor of that.
