### ISSUE TITLE
cannot see the command line clearly after using 'clear' command

### ISSUE THREAD

**Issue by guaguastandup** [warpdotdev/Warp#1743]
### Describe the bug

![image](https://user-images.githubusercontent.com/45114416/185888274-0dc61970-b553-4447-8124-b785535e7081.png)

I have to click several space to see the current command line

![image](https://user-images.githubusercontent.com/45114416/185888782-a4bf0dbf-b72e-40b5-829d-b7519976fef6.png)

### To Reproduce

no

### Operating System

MacOS

### OS Version

mac OS Monterey

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.08.16.10.16.stable_02

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Closing in favor of #8
