### ISSUE TITLE
Using Sequential npm Commands Appears to Have a Memory Leak

### ISSUE THREAD

**Issue by zoominGiladSher** [warpdotdev/Warp#1747]
### Discord username (optional)

ThEldeRS#7593

### Describe the bug

While using warp, I tried to run a sequential set of npm commands: `npm start & npm run e2e` to run my application and do e2e tests on it. This is required for the local development of such tests.
When doing so the app (using webpack-dev-server) is running, the tests are passing, and then the command appears to stop but the server is still running.
Trying to run `npm start` now shows that the port is already used by that application, and even hard quitting Warp does not stop the server from running. The only way to shut down the webpack server is to force shut it with the Activity Monitor.
This reproduces with any set of commands that include running sequential commands.

### To Reproduce

Simple case since I can't share the repo this is happening.
1. `npx create-next-app test`
2. `cd test`
3. Add a test command to `package.json`: "test": "echo 'no tests yet'"
4. Run `npm run dev & npm run test`
5. You'll see that the app runs correctly, the test script runs correctly, you can access the app in localhost:3000 even though the commands (appear) to have stopped running and pressing `ctrl+c` doesn't terminate the app at all.
To close the app go to Activity Monitor and shut down the node process

### Expected behaviour

Running sequential npm commands should close all processes that were initiated by the sequential commands once they are all done.

### Operating System

MacOS

### OS Version

12.5

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.08.16.10.16.stable_02

### Does this block you from using Warp daily?

No

**Comment by vorporeal** [comment]
Hey @zoominGiladSher, I think this is due to your use of `&` vs `&&` when chaining commands.  `&` puts the executed command into the background, whereas `&&` waits for the first command to complete, then runs the second if the first returned a exit code of 0.

Do things work as expected if you run `npm run dev && npm run test` instead of `npm run dev & npm run test`?

**Comment by vorporeal** [comment]
@zoominGiladSher Yep, if you want to run the tests without waiting for the server to quit, `&&` won't work.

I tested your command on iTerm, and it produces the same result - the `npm run dev` command gets executed in the background, `npm run test` runs and prints output, and the server continues running in the background, where ctrl+c can't reach it.

Can you run your example command in iTerm and let me know how it behaves differently?

**Comment by zoominGiladSher** [comment]
Oh that's interesting! I only know what used to be from when I used iTerm last time, haven't used it since I got access to Warp :) Maybe it's not a bug then!

**Comment by elviskahoro** [comment]
Gonna close meanwhile please open if it turns out to be a bug.
