### ISSUE TITLE
File paths with escaped spaces are not completed

### ISSUE THREAD

**Issue by ark-1** [warpdotdev/Warp#1748]
### Discord username (optional)

ark1#9569

### Describe the bug

Completions for file paths with escaped spaces are not working

### To Reproduce

1. Enter `ls /Library/Application\ Support/` into prompt.
2. Press Tab.
3. Observe the lack of completion options.

### Expected behaviour

Completion options are offered.

### Operating System

MacOS

### OS Version

12.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.08.16.10.16.stable_02

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Will ping team about this and circle back when there are updates.

**Comment by elviskahoro** [comment]
Turn outs we're tracking this here:
#669

Closing this in favor of that one.
