### ISSUE TITLE
Discussion: Config / Configuration spec

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/warp#175]
### Describe the solution you'd like?
```
The Warp team is likely already thinking about this, but the two approaches I'm familiar with are Iterm's GUI with nested hierarchies and alacritty's config file. My intuition is that a config file will be easier to port across devices but may not be as accessible to new terminal users.

Options:
A: GUI (similar to Iterm)
B: Config File
C: Maybe a GUI that syncs directly to a config file. Any updates made directly to the config file will be updated in the GUI Preferences Pane.

Some ideas for each
A1. Syncing can likely be handled with our warp credentials, particularly for the enterprise version.
B1. The config file is lightweight, and you'd likely be serializing point A1 into some json or config file for syncing anyway. An explicit config file would help for offline interoperability. 

Would love some comments and suggestions on how the team and current beta users are thinking about this. Especially the arrangement of all the configurable settings in the case of a config file.
```

### Is your feature request related to a problem? Please describe.

```
More so a design / product architecture question.
Relates to these issues
```
Tab Completion Settings: https://github.com/warpdotdev/warp/issues/39
Custom Completion Spec: https://github.com/warpdotdev/warp/issues/131
Keybinding Settings: https://github.com/warpdotdev/warp/issues/30
Prompt Settings: https://github.com/warpdotdev/warp/issues/96

### Additional context
```
Github Features and Issues that imply having an accompanying configurable setting. Checked up to issue #174
```

#### Custom Triggers:

- [ ]     https://github.com/warpdotdev/warp/issues/145

#### Mac Native + UI + Appearance:

- [ ]         https://github.com/warpdotdev/warp/issues/92
- [ ]         https://github.com/warpdotdev/warp/issues/19
- [ ]         https://github.com/warpdotdev/warp/issues/22
- [ ] https://github.com/warpdotdev/warp/issues/286
- [ ] https://github.com/warpdotdev/warp/issues/250
- [ ] #288
- [ ] https://github.com/warpdotdev/warp/issues/287
- [ ] https://github.com/warpdotdev/warp/issues/304
- [ ] #313 

#### Visual Indicator upon some action:
- [ ]         https://github.com/warpdotdev/warp/issues/66
- [ ]         https://github.com/warpdotdev/warp/issues/71

#### Copy:

- [ ]             https://github.com/warpdotdev/warp/issues/77
- [ ]             https://github.com/warpdotdev/warp/issues/138

#### Shell
- [ ]         https://github.com/warpdotdev/warp/issues/132
- [ ]         https://github.com/warpdotdev/warp/issues/105
- [ ]         https://github.com/warpdotdev/warp/issues/52

#### Both: Config and Key Bindings

- [ ]     https://github.com/warpdotdev/warp/issues/167
- [ ]     Via VIM-Mode: https://github.com/warpdotdev/warp/issues/89
- [ ]     https://github.com/warpdotdev/warp/issues/35
- [ ] https://github.com/warpdotdev/warp/issues/73
- [ ] #314 

#### Running List (no associated issue)

- [ ]  autoclosing quotes/parenthesis in the command editor

**Comment by elviskahoro** [comment]
Iterm GUI
<img width="794" alt="Screen Shot 2021-09-08 at 7 09 20 PM" src="https://user-images.githubusercontent.com/29553206/132599438-7aedf43d-ec58-4cca-9550-db22e628c319.png">

[Alacritty Config](https://github.com/alacritty/alacritty/releases/download/v0.9.0/alacritty.yml)

**Comment by Advait-M** [comment]
Hey folks 👋 ! For anyone tracking this discussion - with respect to the point around syntax highlighting (`Visual Indicator upon some action`): 

Super excited to let everyone know that we just launched **Syntax Highlighting and Error Underlining on Warp yesterday** 🎉 ! By default, Warp will highlight each part of a command in a different color denoting arguments, options/flags, variables, etc. and underline invalid commands with a dashed red line. You can toggle these features on/off via the Command Palette or Settings > Features.

Please download the latest release (`v0.2022.10.11.08.13.stable_01`) to get access to these features! The screenshot below shows the features in action:

![Syntax Highlighting and Error Underlining Demo](https://user-images.githubusercontent.com/12927474/195830313-e3eab7b1-84c7-4118-896d-443215c1e3b5.png)

Check out our [user documentation](https://docs.warp.dev/features/editor/error-syntax-highlighting) for more details!

Let us know if you have any comments/feedback on these features!
