### ISSUE TITLE
Support image view  in terminal

### ISSUE THREAD

**Issue by wellcomez** [warpdotdev/Warp#1754]
### Discord username (optional)

#6801

### Describe the solution you'd like?

```text
Currently iterm2 or kitty has a public interface for  image display.

Warp can implement same protocol.

About iterm2, https://iterm2.com/documentation-images.html
```

### Is your feature request related to a problem? Please describe.

```text
view image in terminal
```

### How important is this feature to you?

3

**Comment by wellcomez** [comment]
Protocol
iTerm2 extends the xterm protocol with a set of proprietary escape sequences. In general, the pattern is:

ESC ] 1337 ; key = value ^G
Whitespace is shown here for ease of reading: in practice, no spaces should be used.

For file transfer and inline images, the code is:

ESC ] 1337 ; File = [arguments] : base-64 encoded file contents ^G
The arguments are formatted as key=value with a semicolon between each key-value pair. They are described below:

**Comment by elviskahoro** [comment]
We're tracking this in #026
Moved your comment over so the context is still there.

**Comment by dannyneira** [comment]
Duplicate of #26
