### ISSUE TITLE
Restart required for new launch configurations to be detected

### ISSUE THREAD

**Issue by Blitz2145** [warpdotdev/Warp#1759]
### Discord username (optional)

blitz2145#0529

### Describe the bug

I saved 2 new launch configurations, and they did not show up for me to be able to use them, until I restarted warp.

### To Reproduce

1. Save new launch_configuration_1.yaml
2. Press cmd-shift-P
3. Launch config does not show up in list

### Expected behaviour

Launch configs appear in selection list as soon as they are saved to a file. Might be a good to scan that dir in the background when opening up the launch session chooser.

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.08.16.10.16.stable_02

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
@Blitz2145 Sorry for the late response, the default Launch Configuration shortcut is CTRL-SHIFT-L. 

You can use CMD-P for the Command Palette and search for relevant features/shortcuts.
