### ISSUE TITLE
Option to open new tabs in the home directory

### ISSUE THREAD

**Issue by artran** [warpdotdev/Warp#1762]
### Describe the solution you'd like?

```text
When I need a new window or tab I would like it to open in my home directory.

I understand that some people prefer to open in the current directory so having it as a preference would be great.

Alternatively a keyboard shortcut (e.g. Cmd-Shift-T) would also be good.
```

### Is your feature request related to a problem? Please describe.

```text
It's frustrating when working on several different issues to have to always start a session with `cd` to reset my session to the home directory.
```

### How important is this feature to you?

4

**Comment by dannyneira** [comment]
Thanks for this feature request, please +1 his request as it helps us gauge interest. We will post any updates here.

Create New Tab shortcut is default CMD-T, but can be changed in the Settings > Keyboard Shortcuts to your preference.

**Comment by warpdotdev-dx** [comment]
Gonna close this in favor of:
GitHub issue for configuring the default directories for new sessions, windows, and tabs: <https://github.com/warpdotdev/Warp/issues/105>
