### ISSUE TITLE
ssh: Warp gets stuck logging on to RHEL 7 machine

### ISSUE THREAD

**Issue by clelange** [warpdotdev/Warp#1763]
### Local Shell and Version

zsh 5.8.1

### Remote Shell and Version

zsh 5.0.2

### Operating System and Version

Red Hat Enterprise Linux Server release 7.9 (Maipo)

### Warp Version

v0.2022.08.23.08.06.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Include shell xtrace output

Sent by email.

**Comment by dannyneira** [comment]
Hi @clelange thanks for the info you send via email. 
Is it possible to attach a video/screenshots reproducing the issue?

Also please see more info on SSH support here: https://docs.warp.dev/features/ssh

**Comment by clelange** [comment]
Seems resolved, thanks! Closing
