### ISSUE TITLE
Startup lag delay

### ISSUE THREAD

**Issue by javasopp** [warpdotdev/Warp#1768]
### Describe the bug

In the process of using warp recently, there is an obvious situation that the startup is stuck. After clicking Start, it will take about 1 minute to officially start. The page starts to spin wildly, and then it cannot be operated. I don’t know what happened. I hope you can help me solve this problem , I can help you record the screen to check the problem. thanks

### To Reproduce

It appears every time I open it

### Expected behaviour

Open normally, no lag or delay

### Operating System

MacOS

### OS Version

13.0 Beta版(22A5321d)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.08.23.08.06.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by javasopp** [comment]
This happens to my macbook using my m1 chip, and it also happens to my macbook using intel chips, whether it's macos 13 or macos 12.

**Comment by kevinyang372** [comment]
Hey! Sorry for the experience here. Does this only start happening recently? Do you mind sharing your rc file and screen recording?

**Comment by javasopp** [comment]
This is the address of my screen recording file: [Problem Description](https://www.aliyundrive.com/s/GAwSu39wqYM) ，but I don't know what the rc file you are talking about is, you can describe it clearly, I can provide. thanks

**Comment by javasopp** [comment]
> Hey! Sorry for the experience here. Does this only start happening recently? Do you mind sharing your rc file and screen recording?

This is the address of my screen recording file: [Problem Description](https://www.aliyundrive.com/s/GAwSu39wqYM) ，but I don't know what the rc file you are talking about is, you can describe it clearly, I can provide. thanks

**Comment by dannyneira** [comment]
I'm Danny, a support engineer at Warp. You can sent rc file to feedback@warp.dev add the # to the subject line. Thanks!

Common config file locations by shell are:

Bash = `~/.bashrc` and `~/.bash_profile`
Zsh = `~/.zshrc` and `~/.zprofile`

**Comment by javasopp** [comment]
I have sent a feedback email to the corresponding email, I hope to reply as soon as possible, thank you

**Comment by javasopp** [comment]
> I'm Danny, a support engineer at Warp. You can sent rc/profiles to [feedback@warp.dev](mailto:feedback@warp.dev) add the #1768 to the subject line. Thanks!
> 
> Common config file locations by shell are:
> 
> Bash = `~/.bashrc` and `~/.bash_profile` Zsh = `~/.zshrc` and `~/.zprofile`

I have sent a feedback email to the corresponding email, I hope to reply as soon as possible, thank you

**Comment by javasopp** [comment]
I would like to ask about this startup delay problem, how have you solved it? Have you found the corresponding problem, and do I need to provide other documents? thanks

**Comment by seventeenman** [comment]
I also met that, guess it may be caused by ohmyzsh.

**Comment by javasopp** [comment]
> I also met that, guess it may be caused by ohmyzsh.

But I still have the same situation after uninstalling oh my zsh, it doesn't work~ So I don't think this is the problem, there should be something else.

**Comment by seventeenman** [comment]
> > I also met that, guess it may be caused by ohmyzsh.
> 
> But I still have the same situation after uninstalling oh my zsh, it doesn't work~ So I don't think this is the problem, there should be something else.

ok, r u sure that the legacy configuration files are not loaded in zshrc and bash_profile? I uninstalled ohmyzsh but its config file still worked. I don't have any advice, just give the author some possibilities as much as possible.

**Comment by javasopp** [comment]
> ok, r u sure that the legacy configuration files are not loaded in zshrc and bash_profile? I uninstalled ohmyzsh but its config file still worked. I don't have any advice, just give the author some possibilities as much as possible.

Thank you for your suggestion, but I have tried all the possible situations that I can think of so far. My intel computer cannot hard-decode HEVC. I see many descriptions on the Internet that warp is to call gpu. I wonder if it may be related to this? But this also happens with the m1 chip, so I don't know the specific reason.

**Comment by dannyneira** [comment]
My guess is that you normally have a [custom prompt and that Warp is unable to parse it. ](https://docs.warp.dev/features/prompt#ps1-compatibility-table)

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Set
`ZDOTDIR=/`
in your
`~/.zshenv`
file. This forces Zsh to run with zero configs.

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# Whatever you want to disable

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by javasopp** [comment]
> 我的猜测是您通常有一个[自定义提示，而 Warp 无法解析它。 ](https://docs.warp.dev/features/prompt#ps1-compatibility-table)
> 
> 您可以通过[设置干净的配置来检查它是否在您的点文件中：](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files) 在您的 文件中 设置。这会强制 Zsh 以零配置运行。 `ZDOTDIR=/` `~/.zshenv`
> 
> 您可以使用以下条件语句仅针对 Warp 禁用部分点文件：
> 
> ```shell
> if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
> ##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW
> 
> # Whatever you want to disable
> 
> ##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
> fi
> ```
> 
> 我们在此处列出了不兼容的工具：[https](https://docs.warp.dev/help/known-issues#list-of-incompatible-tools) ://docs.warp.dev/help/known-issues#list-of-incompatible-tools 此处有关自定义提示的更多信息：[https ://docs.warp.dev/功能/提示](https://docs.warp.dev/features/prompt)

Thank you for your reply. I have tried the possible solutions you provided above, but they are of no use. I don't know whether there are logs in the warp and other related possibilities to view the runtime problems. If so, I can provide them to You look at and analyze why

**Comment by elviskahoro** [comment]
You can access log reports via the console app:

<img width="1007" alt="CleanShot 2022-09-21 at 12 45 52@2x" src="https://user-images.githubusercontent.com/29553206/191563698-cac19670-7935-43e8-859d-8b8c29bd1a1b.png">

**Comment by javasopp** [comment]
> 
This is the warp log I checked, you can analyze it and see what's going on~ If there is anything else that needs my help in the future, you can let me know, thank  @elviskahoro 。
[warp.log](https://github.com/javasopp/picture/blob/338c68e9f2b4060182689c7814e15368188d9564/warp.log)

**Comment by javasopp** [comment]
Hello, I think I have found the problem from this error message. My warp is logged in with a google account. The warp will automatically load the authorization authentication information when logging in, and then it will load the avatar of my google account. , but I see that the path has been spliced out, and the spliced path can also access the avatar of my google account, but it cannot be loaded, so an error is reported, and there is a lag and startup delay. After I re-registered with my email address, there is no problem. It is estimated that this is also a problem. I hope it can be fixed. Thank you for your support during this time. I also hope that warp will get better and better.
@elviskahoro @dannyneira @seventeenman
