### ISSUE TITLE
Preferences view clipped when using Hotkey Window

### ISSUE THREAD

**Issue by mskri** [warpdotdev/Warp#1769]
### Describe the bug

When using Hotkey Window opening preferences does not allow you to see the preferences window completely. Close button is not accessible unless you drag the height of hotkey window to be taller and preferences windows is clipped.

### To Reproduce

Using 1440p monitor, hotkey window height set to 30%.

1. Show hotkey window
2. Open preferences

### Expected behaviour

Preferences view is shown completely and not clipped. Close button is accessible without having to change height of hotkey window.

Preferably the preferences windows would be floating over the terminal.

### Screenshots

![Screenshot 2022-08-27 at 9 35 20](https://user-images.githubusercontent.com/2499987/187018263-93667baf-1c7a-49d1-a371-aa1d95d3ddcc.png)

### OS Version

12.5

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.08.16.10.16.stable_02

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

**Comment by dannyneira** [comment]
@mskri your hotkey binding conflicts with default the A.I. Command Search key bind, CTRL-`. Try changing one or the other and let us know if the issue persist.

**Comment by mskri** [comment]
Changing the hotkey window to something else did not change the outcome. Issue is when hotkey windows is shown and you open preferences e.g. with `cmd,`. Preferences UI gets clipped and only way to use it properly is to drag the hotkey window height to be bigger.

Steps

1. Show terminal with hotkey window 
2. Open preferences with `cmd,`

**Comment by szgupta** [comment]
I believe @vorporeal recently fixed this! Should be in the next release (09/01/22) 🙂

**Comment by szgupta** [comment]
> I believe @vorporeal recently fixed this! Should be in the next release (09/01/22) 🙂

Scratch that -- this _won't_ actually be coming out this week. Will update this thread once we have a better idea of when this will be fixed

**Comment by elviskahoro** [comment]
We're also gonna close this cause we're tracking it in #366
