### ISSUE TITLE
Open relative paths / files with modifier or CMD-click (mouse press) with finder or default app

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#177]
### Describe the solution you'd like?

```
launch an external application based on a file hyperlink and extension
maybe warp for mac could just piggy back off of the open command like so:
```

```sh
open filename.txt
```

### Is your feature request related to a problem? Please describe.

```
UX
```

### Additional context

```
Sourced from Discord (feature requests - 08/31/2021)

"Not sure if this has been discussed but it'd be really cool if there was a way to configure warp such that file system paths output to the terminal could have a click action (similar to links) where it could open another program. Eg a path to a file in a stack trace where you could click on the file path and it open your editor."
```

**Comment by elviskahoro** [comment]
From @zachlloyd via
- #253 

### Describe the solution you'd like?

```shell
iTerm supports a cool features where if you press cmd and click on a directory like /Users/zach it will open a finder window in that directory.  We should implement this in Warp.
```


### Is your feature request related to a problem? Please describe.

_No response_

### Additional context

_No response_

**Comment by elviskahoro** [comment]
Of these scenarios, which one are you looking for?

1. CMD-Click, (acts as a right click), opening a menu that has an option called "Open in default program" (which is your system set handler for that file type.
2. CMD-Click automatically

**Comment by elviskahoro** [comment]
From @kylehqcom via #665

### Describe the solution you'd like?

```shell
Currently a long iTerm2 user and I use this feature all the time.

When viewing a full filepath/filename and your mouse pointer is hovering over the filepath/filename, you can hold Command key to make the filepath/filename clickable to open into your default editor.

This makes it really easy to open/edit files with errors/issues at the line in question.
```


### Is your feature request related to a problem? Please describe.

_No response_

### Additional context

Notice the link creation on each time I hold the Cmd key and hover.

https://user-images.githubusercontent.com/424321/150853152-c3b4a7cb-5f48-4ea4-beef-e8f422ff8c70.mp4

**Comment by Nitive** [comment]
There is a few corner cases with file names

1. There is also often line number and character position alongside with file name. For example, `path/to/file.rs:10:5`. It would be also nice to jump to exact line and character when you click on such path, but I'm not sure if it can be done generally for all editors. I know I can use `subl path/to/file.rs:10:5` for Sublime Text and `code --goto path/to/file.rs:10:5` for VSCode to do this. At least we shouldn't try to `open path/to/file.rs:10:5` in such cases, we need to strip character position info

2. By default git prepend file names with `a/` and `b/` prefixes if `git diff` output. It would be nice to support opening such files as `path/to/file.rs` and not `a/path/to/file.rs`

**Comment by elviskahoro** [comment]
This is in the works! Should be launching soon! Will close this when it does.

**Comment by essenciary** [comment]
This is literally the first reason why I go back to iTerm, 2 minutes into the session every time I want to give Warp another chance.

**Comment by zachlloyd** [comment]
Makes sense - we are pretty close on the implementation (just trying to get
the experience to be right).

**Comment by mnapoli** [comment]
You guys rock, this product rocks. I was a hardcore iTerm fan, these are the last bits I'm missing.

(sorry for the noise 🙏 )

**Comment by brandonkboswell** [comment]
I would also like to be able to do this. I often tunnel into our db and it has a postgresql:// url. In iTerm2 I used to able to command click it, but can't in Warp. Thank you, warp is awesome.

**Comment by elviskahoro** [comment]
@brandonkboswell what version of Warp are you on?

**Comment by brandonkboswell** [comment]
v0.2022.08.08.09.21.stable_00

**Comment by elviskahoro** [comment]
This launched! We have some documentation here:
https://docs.warp.dev/features/files-and-links

We're working on a video as well to walkthrough the feature!

**Comment by elviskahoro** [comment]
Yeah let's make a separate issue as follow up:
https://github.com/warpdotdev/Warp/issues/1755

**Comment by rienstra** [comment]
Would love for http links to work as well.

**Comment by mnapoli** [comment]
This stopped working completely (cannot click links at all anymore), not sure what happened here.

**Comment by warpdotdev-dx** [comment]
We have a bug. Have someone who is investigating this week!

**Comment by lewisl9029** [comment]
@warpdotdev-dx @elviskahoro It's been 3 months since you had someone investigate the issue and this is still not working on my side. Maybe re-open the issue to track its status properly?

Not being able to jump to a line in a stack trace in my editor is a huge problem for day to day dev experience. I've actually just reverted to the built-in VSCode terminal because of this.

**Comment by elviskahoro** [comment]
Will try to circle back with you this week @lewisl9029

**Comment by aviflombaum** [comment]
Has this been implemented? Don't mean to pile-on, just curious. Love warp. :-)

**Comment by kg-currenxie** [comment]
Still broken in `v0.2023.04.04.08.03.stable_01`

**Comment by kevinyang372** [comment]
Hey engineer at Warp here. I am very sorry about your experience.

We have tried but couldn't repro this issue. If you have encountered this bug, do you mind:
1. Start a new session and check if link highlighting is working there
2. If step 1 does not resolve the issue, paste the full line that contains the file link into a comment below so we could try to repro it

Thank you very much!

**Comment by patik** [comment]
It's not working for relative paths for me. Both of the examples shown here are clickable in VS Code's built-in terminal.

https://github.com/warpdotdev/Warp/assets/262137/153bbe24-e0d8-4995-a010-d9ae39200a43

> We have tried but couldn't repro this issue. If you have encountered this bug, do you mind:

Some example patterns:

```
at Object.getItem (foo/bar.test.tsx:82:12)

 PASS  foo/bar.test.tsx (24.042 s)

foo/bar.ts:39:5 - error TS2322: Type blah blah blah
```
