### ISSUE TITLE
cannot use ssh to connect to a server using fish.

### ISSUE THREAD

**Issue by Cat7373** [warpdotdev/Warp#1771]
### Describe the bug

cannot use ssh to connect to a server using fish.

### To Reproduce

1. Set the user's default shell to fish on any server
2. Use ssh to connect to it
3. The following error is prompted:

```sh
ssh root@******
fish: Unsupported use of '='. In fish, please use 'set hook $(printf "{\"hook\": \"SSH\", \"value\": {\"socket_path\": \"~/.ssh/2593\", \"user\": \"%s\", \"machine\": \"%s\", \"remote_shell\": \"%s\"}}" $(whoami) $(hostname) ${SHELL##*/} | command od -An -v -tx1 | command tr -d " \n")'.

Connection to ****** closed.
```

4. Server Environment:
   * Ubuntu Server 22.04.1 LTS
   * Kernel: 5.15.0-46-generic
   * fish: 3.3.1

### Operating System

MacOS

### OS Version

MacOS 12.5.1

### Shell Version

fish, version 3.5.1

### Warp Version

v0.2022.08.23.08.06.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Please try and disabling the shell wrapper in the Settings > Features to enable customizations within ssh sessions.

See more about the SSH wrapper here: https://docs.warp.dev/features/ssh#implementation

**Comment by Cat7373** [comment]
the fixed.

**Comment by elviskahoro** [comment]
The issue to follow is #871. @Cat7373
