### ISSUE TITLE
Cmd/Opt+left/right not working in python and ruby shells

### ISSUE THREAD

**Issue by rkwap** [warpdotdev/Warp#1772]
### Discord username (optional)

rkwap

### Describe the solution you'd like?

```text
If this works in the terminal as general, it should work with these shells also like iterm2 and Terminal.app
```

### Is your feature request related to a problem? Please describe.

```text
These shortcuts to move across text don't work in shells like python or irb.

1. cmd + left/right
2. opt + left/right

They work fine in the terminal but not in these shells.
```

### How important is this feature to you?

4

**Comment by dannyneira** [comment]
Please submit a bug report here: <https://github.com/warpdotdev/Warp/issues/new?assignees=&labels=&template=01_bug_report.yml>

**Comment by dannyneira** [comment]
We don't currently support our keyboard shortcuts within subshells like python/irb.

I recommend you use these shortcuts
Ctrl+a / Ctrl+e
or
Home / End
to jump to the top left/right side of the commands in subshells.

There is currently an issue for more subshell support, be sure to +1 that and track any updates there <https://github.com/warpdotdev/Warp/issues/64>

**Comment by acarl005** [comment]
This should be working now. Please re-open if we've missed something.
