### ISSUE TITLE
crash with "cat /dev/random"

### ISSUE THREAD

**Issue by superwindstorm** [warpdotdev/Warp#1774]
### Describe the bug

Just exec `cat /dev/random` then crash.

### To Reproduce

1. Run `cat /dev/random`.
2. Wait.
3. Crash.

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2022.08.23.08.06.stable_01

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
@superwindstorm thanks for bringing this up, I was able to repro and confirm this issue.

Please specify your use case so we can document that.

**Comment by vorporeal** [comment]
I just let `cat /dev/random` run for a while on my machine and Warp didn't crash.  My best guess as to the original cause is that `cat /dev/random` occasionally happens to produce a series of bytes which we interpret as one of our own custom control sequences.

Given that I couldn't reproduce it myself, I'm going to hope that current builds of Warp are more robust to unexpected/malformed control sequences, and no longer crash.

If this does still reproduce for you, feel free to re-open the issue!
