### ISSUE TITLE
Quake style window should support not always being on top

### ISSUE THREAD

**Issue by bduff9** [warpdotdev/Warp#1782]
### Discord username (optional)

Duffmaster#9200

### Describe the solution you'd like?

```text
The Quake style window is great and I use it all the time in iTerm.  One thing that I like about the iTerm style is I can open and focus the Quake style window with my hotkey, but then I can click to another window to send it to the background.  I would like Warp to offer the same functionality.
```

### Is your feature request related to a problem? Please describe.

```text
Currently, the Quake-style window stays on top of all other windows.  This makes it difficult to switch between different tasks (i.e. run a long-running command and move on to reading some documentation in the browser while it runs).  Additionally, since the Quake-style window is 100% of the width, I can still see its progress in the background.  Currently, I can only hide/show the entire window which is not ideal for my usual workflow.
```

### How important is this feature to you?

4

**Comment by dannyneira** [comment]
Thanks for this feature request, please +1 his request as it helps us gauge interest. You can also select "Autohides on loss of keyboard focus" and the window will hide automatically, if you have any long running commands you're waiting to finish, we also have Notifications feature to help notify you when the long running command is finished.

Also see more info/updates about our Quake mode/Notification features here. Let me know if that helps. <https://docs.warp.dev/features/hotkey-window>
<https://docs.warp.dev/features/notifications>

**Comment by dannyneira** [comment]
closing as resolved, the autohide function covers this use case.

**Comment by bduff9** [comment]
@dannyneira If you want to close as won't do, I understand I don't agree with closing as completed as I mentioned autohide does not solve this issue for me as I like the current iTerm behavior of keeping it open in the background so I can still see and be reminded of it.

**Comment by dannyneira** [comment]
Got it, what you're describing is a window that you can hotkey but will stay in the background like a normal window not autohide or stay on top like Warps.

**Comment by bduff9** [comment]
👍  Yes please

**Comment by bduff9** [comment]
Is this available now?  I don't see it in the latest preview but this was marked as completed 🤔
