### ISSUE TITLE
Programmatic/Configurable Tab Names

### ISSUE THREAD

**Issue by gwayne9955** [warpdotdev/Warp#1784]
### Describe the solution you'd like?

```text
It would be really nice to have programmatic or configurable control over what each tab name is. 

For example, I'd like to name the tab after the folder of the current working directory. 
I can programmatically do this by running 
echo -ne "\033]0;${PWD##*/}\007"
in most terminals, and I have my .zshrc setup to run this each time I change directories/open a new tab.

Running this command in warp does not let me change the tab name.
```

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
@gwayne9955 We've added more info on the process for programmatically naming tabs below:

> You can change the Tab names (either rename the tab with something constant, by right clicking the tab; or changing the whole "template" using your zshrc by adding something like:
```sh
function set_title () {​echo -ne "\033]0;MyTitle\007" }
precmd_functions += (set_title) 
```
where MyTitle would be whatever you want to see in the tab (either a fixed string, or $PWD or something else)

**Comment by dannyneira** [comment]
This tip will also be reflected in our up coming Tabs doc, should be found here by next week > https://docs.warp.dev/features/tabs

**Comment by elviskahoro** [comment]
The documentation was launched!
