### ISSUE TITLE
Disable copying to clipboard when deleting words

### ISSUE THREAD

**Issue by yang** [warpdotdev/Warp#1786]
### Discord username (optional)

yaaang

### Describe the solution you'd like?

```text
I think overwriting your clipboard when deleting a word is the safer default and the far more modern UX, and that it can be left as a pref.
```

### Is your feature request related to a problem? Please describe.

```text
Very frustrating to have your clipboard contents wiped out inadvertently whenever you delete a word.
```

### How important is this feature to you?

4

**Comment by elviskahoro** [comment]
Can you send a video of this happening? I think this is a bug. I don't remember Warp ever doing this.

**Comment by szgupta** [comment]
I'm guessing the copy is not happening on when the text is _deleted_, but rather when the text is _selected_. We have a setting for this (`Settings -> Features -> Copy on select`) which I believe is defaulted to ON. @yang, does disabling this setting fix the problem you're seeing?

**Comment by yang** [comment]
No, it's when I press alt-backspace or ctrl-w. Will try to share a video at
some point.

**Comment by yang** [comment]
I see now there are also multiple other issues reporting this on the repo.

**Comment by rushi** [comment]
I think this is related to https://github.com/warpdotdev/Warp/issues/1785 where `option` + `delete` does the same thing

**Comment by dannyneira** [comment]
Closing this request in favor of #1785 since it's related to a bug. We'll post updates on that thread.
