### ISSUE TITLE
Shortcuts displayed on startup suggests defaults after remapping

### ISSUE THREAD

**Issue by reillymarkowitz** [warpdotdev/Warp#1789]
### Discord username (optional)

Reilly#3277

### Describe the bug

In keyboard shortcuts settings, I changed the keybinding for History Search from the default Control-R to Command-R:

<img width="674" alt="Screen Shot 2022-08-31 at 9 42 01 PM" src="https://user-images.githubusercontent.com/13988685/187832893-60f2c5d1-11b3-4a7c-99af-97e6e28a3450.png">

However, when I restart Warp, it still shows the default Control-R mapping for History Search.

<img width="792" alt="Screen Shot 2022-08-31 at 9 47 00 PM" src="https://user-images.githubusercontent.com/13988685/187833396-db0472bb-29c6-4c8c-9761-31a01d8b4074.png">

### To Reproduce

1. Open settings
2. Select "Keyboard shortcuts"
3. Change the shortcut for History Search
4. Restart Warp

### Expected behaviour

I would expect to see the new keybinding instead of the default here.

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

zsh 5.8

### Warp Version

v0.2022.08.23.08.06.stable_01

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
@reillymarkowitz Thanks for bringing this up, we are aware of the issue and will post updates here with any changes.

**Comment by alokedesai** [comment]
This should now be fixed. Thanks for flagging!
