### ISSUE TITLE
Tab rearrangement ability

### ISSUE THREAD

**Issue by touhidurabir** [warpdotdev/warp#179]
### Describe the solution you'd like?

```shell
Tab rearrangement ability, like move a tab left or right by dragging it when multiples tabs are open .
```

**Comment by elviskahoro** [comment]
i think there's an issue already open for this: https://github.com/warpdotdev/warp/issues/58

**Comment by touhidurabir** [comment]
> i think there's an issue already open for this: #58

Ah, sorry. Did not noticed that one . I am closing this one as it has already been mentioned in the issue tracker .
