### ISSUE TITLE
ssh: CentOS 7 VM fails

### ISSUE THREAD

**Issue by philjones88** [warpdotdev/Warp#1790]
### Local Shell and Version

5.8.1

### Remote Shell and Version

5.0.2

### Operating System and Version

MacOS 12.5 + CentOS 7

### Warp Version

v0.2022.08.23.08.06.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

Asks for password then shows:

```
warp_escape_json:19: command not found: tr
warp_escape_json:19: command not found: sed
warp_escape_json:19: command not found: tr
warp_escape_json:19: command not found: sed
warp_escape_json:19: command not found: sed
warp_escape_json:19: command not found: tr
warp_escape_json:19: command not found: sed
warp_escape_json:19: command not found: tr
warp_escape_dcs_json:1: command not found: od
warp_escape_dcs_json:1: command not found: tr
```

Then just says `Starting shell...`

### Include shell xtrace output

Sent in email as too long

**Comment by elviskahoro** [comment]
Thanks Phil! Also for sending the log

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
