### ISSUE TITLE
allow saving of text

### ISSUE THREAD

**Issue by HotFusionMan** [warpdotdev/Warp#1797]
### Describe the solution you'd like?

```text
The functionality of Terminal.app's `Export Selected Text` or iTerm's `Save Selected Text` Shell menu items.

EDIT: https://github.com/warpdotdev/Warp/issues/385 is essentially the same as this request.
```

### Is your feature request related to a problem? Please describe.

```text
While the same functionality can be achieved via copy and paste, a direct-to-disk feature might be worthwhile for the case of very large amounts of text that a user wants to save.
```

### How important is this feature to you?

2

**Comment by warpdotdev-dx** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.


You may have two stopgap options that can help here. You can right-click on a block you want to save then "Copy Output"/"Copy Command"/"Copy Both" or you can select desired text, even across multiple blocks, and right-click "Copy", then save to your txt file. 

__
Danny Neira (he/him/his)
Support Engineer
www.warp.dev

**Comment by elviskahoro** [comment]
I found an issue that tracks the same feature request.
Will close this in favor of: https://github.com/warpdotdev/warp/issues/385
