### ISSUE TITLE
Warp crashes on `exit` with multiple tabs open

### ISSUE THREAD

**Issue by lucieleblanc** [warpdotdev/warp#18]
**Describe the bug**
When I open multiple tabs, typing `exit` on the terminal prompt crashes Warp.

**To Reproduce**
1. Open Warp.
2. Open a new tab.
3. In either tab, type `exit` at the prompt.

**Expected behavior**
When I type `exit`, I expect only the current tab to close.

**System info:**
 - OS: `MacOS 11.4`
 - Shell: `zsh`
 - Warp version: `0.1.0`

**Additional information**
I'm happy to send over the full stack trace if needed.

**Comment by alokedesai** [comment]
Thanks for reporting! We already have a fix for this in, it will be in the next release that will go live next week

**Comment by lucieleblanc** [comment]
Got it, thanks for the super fast reply!

**Comment by zheng** [comment]
The fix was in our last release! :)
