### ISSUE TITLE
Auto-completion for "exit" suggests "exrmultipart"

### ISSUE THREAD

**Issue by KieranP** [warpdotdev/Warp#1801]
### Describe the bug

Autocompletion on for each keystroke, typing "exit" suggests "exrmultipart"

So "exit"[enter] does the wrong thing.

### To Reproduce

Type "exit"

### Expected behaviour

"exit" is top result

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

zsh 5.9

### Warp Version

v0.2022.08.31.18.11.stable_00

### Does this block you from using Warp daily?

No

**Comment by KieranP** [comment]
@warpdotdev-dx @dannyneira That is correct, I am using the experimental feature "Open completions menu as you type". Disabling it does indeed allow me to type "exit" and hit enter properly. But it would be nice if the autocomplete was aware of shell commands like "exit".

**Comment by szgupta** [comment]
Support for builtins (including `exit`) should be coming out today (yesterday's release was rolled back)!

**Comment by szgupta** [comment]
Sorry I misspoke. This will be coming out in this week's release!

**Comment by elviskahoro** [comment]
This should be out now! Please comment if it isn't working as expected.

**Comment by warpdotdev-dx** [comment]
Hi @KieranP, I'm Danny, Support Engineer at Warp.


So sorry to hear you're having this issue. By any chance have you enabled the experimental feature "Open completions menu as you type"? If so, as a possible workaround, try disabling that for now and see if the "exit" issue persist.


I will bring this up with the team and post any updates here.
__
Danny Neira (he/him/his)
Support Engineer
www.warp.dev
