### ISSUE TITLE
Hotkey Window like Iterm

### ISSUE THREAD

**Issue by namkam5** [warpdotdev/Warp#1802]
### Describe the solution you'd like?

```text
Iterm has a hotkey window that always floats on top, would be nice to have it in Warp as well.
```

### How important is this feature to you?

4

**Comment by warpdotdev-dx** [comment]
Hello @namkam5, I'm Danny, Support Engineer at Warp. 


We actually do have a Hotkey Window feature, please see more about here. https://docs.warp.dev/features/hotkey-window


You can enabled and configure it in the `Settings > Features > Hotkey Window`


I hope this helps, I will close this feature request, but if you have any other questions or issues let us know.

__
Danny Neira (he/him/his)
Support Engineer
www.warp.dev

**Comment by dannyneira** [comment]
Hotkey Window feature already implemented. **https://docs.warp.dev/features/hotkey-window**
