### ISSUE TITLE
Please support double-tap of a modifier  like iTerm and Alfred did to trigger the hot window quickly.

### ISSUE THREAD

**Issue by graycreate** [warpdotdev/Warp#1803]
### Describe the solution you'd like?

```text
Like Alfred and iTerm did:
![](https://picx.zhimg.com/80/v2-e5849440860fcf39d8f59844308dcf22_1440w.jpg?source=1940ef5c)

https://iterm2.com/documentation-hotkey.html
```

### How important is this feature to you?

4

**Comment by warpdotdev-dx** [comment]
Hello @sethcreate, I'm Danny, Support Engineer at Warp.


Please +1 this request as it helps us gauge interest.

__
Danny Neira (he/him/his)
Support Engineer
www.warp.dev

**Comment by mwasilewski** [comment]
yup, I would love that, I'm used to open iTerm hotkey window with double control key

**Comment by dannyneira** [comment]
Duplicate of #2809
