### ISSUE TITLE
Drop SSH connection

### ISSUE THREAD

**Issue by pavel-hushcha** [warpdotdev/Warp#1804]
### Describe the bug

When I try to connect to my router I get an error and the connection drops.

### To Reproduce

1. ssh admin@192.168.1.1 -p 22

### Expected behaviour

I expect to see no errors.

### Screenshots

![image](https://user-images.githubusercontent.com/73911482/188413443-5118eaa3-6a56-4560-8c63-ff29d6fe166b.png)

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.08.31.18.11.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by warpdotdev-dx** [comment]
Hello @pavel-hushca, I'm Danny, Support Engineer at Warp. 


So sorry to hear you're having this issue with SSH. 

To enable Blocks over SSH, Warp uses an SSH Wrapper function; navigate to `Settings > Features` if you need to disable it.

Note: You'll need to start a new session before a change is reflected) or try invoking the SSH binary directly: /usr/bin/ssh

__
Danny Neira (he/him/his)
Support Engineer
www.warp.dev

**Comment by dannyneira** [comment]
@pavel-hushcha, Hi I'm Danny, Support Engineer with Warp. Have you had any luck with the above troubleshooting steps?

**Comment by dannyneira** [comment]
I'm unable to repro this issue on my end, Any updates on the above steps.

> Hello @pavel-hushca, I'm Danny, Support Engineer at Warp. So sorry to hear you're having this issue with SSH. To enable Blocks over SSH, Warp uses an SSH Wrapper function; navigate to `Settings > Features` if you need to disable it. Note: You'll need to start a new session before a change is reflected) or try invoking the SSH binary directly: /usr/bin/ssh
> […](#)
> __ Danny Neira (he/him/his) Support Engineer [www.warp.dev](http://www.warp.dev)

**Comment by dannyneira** [comment]
Since we cant reproduce this issue i'll close out this one, but feel free to reopen if you can confirm this is happening with the latest version of Warp.

**Comment by pavel-hushcha** [comment]
> Hello @pavel-hushca, I'm Danny, Support Engineer at Warp. So sorry to hear you're having this issue with SSH. To enable Blocks over SSH, Warp uses an SSH Wrapper function; navigate to `Settings > Features` if you need to disable it. Note: You'll need to start a new session before a change is reflected) or try invoking the SSH binary directly: /usr/bin/ssh
> […](#)

Disabling SSH wrapper helps.
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/73911482/190561741-e3bdb3d2-1e3d-4b1f-948e-3f0af3224a51.png">
But with enabled SSH wrapper have the same issue:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/73911482/190561878-98826d06-b019-49c2-bd80-15f4bc32a54e.png">

**Comment by pavel-hushcha** [comment]
@dannyneira, could you please reopen it?

**Comment by dannyneira** [comment]
@pavel-hushcha No problem, we can open but will need abit of help with the repro as i'm unable to repro on my end. Are you using bash or zsh on the remote machine? are you using any custom prompt or rc files on the remote machine? 

My guess is that you normally have a [custom prompt or rc file and that Warp is unable to parse it. ](https://docs.warp.dev/features/prompt#ps1-compatibility-table)

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Set
`ZDOTDIR=/`
in your
`~/.zshenv`
file. This forces Zsh to run with zero configs.

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# Whatever you want to disable

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by pavel-hushcha** [comment]
> @pavel-hushcha No problem, we can open but will need abit of help with the repro as i'm unable to repro on my end. Are you using bash or zsh on the remote machine? are you using any custom prompt or rc files on the remote machine?
> 
> My guess is that you normally have a [custom prompt or rc file and that Warp is unable to parse it. ](https://docs.warp.dev/features/prompt#ps1-compatibility-table)
> 
> You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files) Set `ZDOTDIR=/` in your `~/.zshenv` file. This forces Zsh to run with zero configs.
> 
> You can disable parts of your dotfiles just for Warp by using this conditional statement:
> 
> ```shell
> if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
> ##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW
> 
> # Whatever you want to disable
> 
> ##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
> fi
> ```
> 
> We have a list of incompatible tools here: https://docs.warp.dev/help/known-issues#list-of-incompatible-tools And more info on custom prompts here: https://docs.warp.dev/features/prompt

I have that issue trying connect to router's CLI.
http://docs.help.keenetic.com/cli/3.1/en/cli_manual_kn-1011.pdf

**Comment by archer-github** [comment]
Hey there,
Is it possible to not use the "SSH Wrapper feature" for some connections, make a list of exclusions, etc.? In this case, it will solve such a problem with connecting to the Keenetic, which Pavel also has.
