### ISSUE TITLE
ssh the remote linux server chinese display abnormal when vi、vim or less the log file

### ISSUE THREAD

**Issue by xiaovjianai** [warpdotdev/Warp#1807]
### Local Shell and Version

$ZSH_VERSION=5.8.1

### Remote Shell and Version

$BASH_VERSION=4.2.46(2)-release

### Operating System and Version

macos13.0

### Warp Version

v0.2022.08.31.18.11.stable_00

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots
use vi or vim comand
<img width="661" alt="image" src="https://user-images.githubusercontent.com/19337296/188527844-ac646d28-35ca-4919-808d-ca324cf7a21d.png">

use less comand
<img width="660" alt="image" src="https://user-images.githubusercontent.com/19337296/188530407-774661a7-6eec-4e87-95a2-384d520e86de.png">

### Include shell xtrace output

when vi、vim or less the log file, chinese display abnormal, but grep、tail or more log file the chinese display normal

**Comment by dannyneira** [comment]
@xiaovjianai Hi i'm Danny, Support Engineer with Warp. So sorry to hear you're having issues with vi and less. I'm unable to reproduce this error with chinese text on my machine. would it be possible to post a sample file of what you're trying to less/vi so that we can investigate further?

**Comment by xiaovjianai** [comment]
> @xiaovjianai Hi i'm Danny, Support Engineer with Warp. So sorry to hear you're having issues with vi and less. I'm unable to reproduce this error with chinese text on my remote machine via ssh. would it be possible to post a sample file of what you're trying to less/vi so that we can investigate further?
> 
> I tried with following characters:
> 
> ```
> 天地玄黄 宇宙洪荒 日月盈昃 辰宿列张 寒来暑往 秋收冬藏
> 
> 闰馀成岁 律吕调阳 云腾致雨 露结为霜 金生丽水 玉出昆冈
> 
> 剑号巨阙 珠称夜光 果珍李柰 菜重芥姜 海咸河淡 鳞潜羽翔
> 
> 龙师火帝 鸟官人皇 始制文字 乃服衣裳 推位让国 有虞陶唐
> ```



> 

I download the log file from the server to local,then use warp software to vi/less the log file,the Chinese in the file is displayed normally,So I think it's a problem with the ssh remote server

**Comment by xiaovjianai** [comment]
> Hi i'm Danny, Support Engineer with Warp. So sorry to hear you're having issues with vi and less. I'm unable to reproduce this error with chinese text on my remote machine via ssh. would it be possible to post a sample file of what you're trying to less/vi so that we can investigate further?

I use iterm2 software to ssh the remote server, and then vi/less the log file, the Chinese in the file is displayed normally.

**Comment by dannyneira** [comment]
Thanks for clearing that up, if you can please provide a copy of the log file to feedback@warp.dev and include Github Issue #1807 in the subject. This will help us to reproduce the issue on our end.

Also, if you can please try vi/less the file with SSH wrapper disabled in the `Settings > Features` menu. This will also help us narrow down the issue further.

**Comment by xiaovjianai** [comment]
> Thanks for clearing that up, if you can please provide a copy of the log file to [feedback@warp.dev](mailto:feedback@warp.dev) and include Github Issue #1807 in the subject. This will help us to reproduce the issue on our end.
> 
> Also, if you can please try vi/less the file with SSH wrapper disabled in the `Settings > Features` menu. This will also help us narrow down the issue further.



> Thanks for clearing that up, if you can please provide a copy of the log file to [feedback@warp.dev](mailto:feedback@warp.dev) and include Github Issue #1807 in the subject. This will help us to reproduce the issue on our end.
> 
> Also, if you can please try vi/less the file with SSH wrapper disabled in the `Settings > Features` menu. This will also help us narrow down the issue further.

I tried,the problem still exists.And I've emailed you the log file, please check it out.

**Comment by xiaovjianai** [comment]
vim ~/.zshrc 
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

**Comment by dannyneira** [comment]
Thanks for clearing this up @xiaovjianai , just to confirm, did you add those values  `export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8` to your `~/.zshrc` file and it corrected the issue?

**Comment by xiaovjianai** [comment]
> Thanks for clearing this up @xiaovjianai , just to confirm, did you add those values
> 
> ```
> export LC_ALL=en_US.UTF-8
> export LANG=en_US.UTF-8
> ```
> 
> to your `~/.zshrc` file and it corrected the issue?

Yes, it works.
