### ISSUE TITLE
command `aafire` aborted very fast abnormally, which should be cancelled until you press any key

### ISSUE THREAD

**Issue by sfwn** [warpdotdev/Warp#1813]
### Discord username (optional)

sfwn

### Describe the bug

`aafire` is a ascii fire display command. It works on iTerm2, but aborted very fast abnormally.
This command should be cancelled until you press any key.
So I guess Warp maybe send some keys, but I captured nothing using `Karabiner-EventViwer`.

### To Reproduce

1. use `nix-env -iA nixpkgs.aalib` to install `aafire`.
2. just run `aafire` command.

### Expected behaviour

`aafire` quit until you press a key, such as `q` or `ctrl-c`. Works as `iTerm2`.

### Screenshots

warp:
<img width="211" alt="image" src="https://user-images.githubusercontent.com/13919034/189024040-9c70aadf-b2fc-402f-8076-09aa49117ec6.png">

iTerm2:
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/13919034/189024082-92ee2763-01b0-46d6-ae57-b220843642d0.png">

### Operating System

MacOS

### OS Version

OS: macOS Monterey 12.5.1 21G83 arm64

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21) | zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.08.31.18.11.stable_00

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
@sfwn Hi, I'm Danny, Support Engineer at Warp. Thanks for bringing this to our attention. I'm not seeing aafire close abruptly on the latest build of Warp, are you seeing the same now after updating?

Also, as a possible workaround for closing aafire, I found you can quit with `CTRL-C` but not `Q`, or suspend it with `CTRL-Z`.

**Comment by dannyneira** [comment]
Since I'm unable to repro this issues on latest version of Warp I'm closing this issues, but feel free to reopen if you find the issue still happening on your end.
