### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by StarNumber12046** [warpdotdev/Warp#1814]
### Describe the solution you'd like?

```text
Opening to track windows support and to let community help (?) like with the fig support
```

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
@StarNumber12046 I'm Danny Support Engineer at Warp, Thanks for this request. We currently have [#204](https://github.com/warpdotdev/Warp/issues/204) out for this request. Please +1 that request as it helps us gauge interest.
