### ISSUE TITLE
Ability to move tabs around

### ISSUE THREAD

**Issue by davidrenne** [warpdotdev/Warp#1822]
### Describe the solution you'd like?

```text
Like chrome and most tabbed UI's I want the ability to move things around logically according to how I am using my shells in groups instead of having multiple terminals with MAC+N, i'd rather have one application window and group my terminal shells how I want.
```

### How important is this feature to you?

2

**Comment by dannyneira** [comment]
Hi @davidrenne, I'm Danny, Support Engineer at Warp. I like the idea of grouped tabs as well so thanks for this feature request. Please +1 as it helps us gauge interest.

**Comment by elviskahoro** [comment]
Quick clarification, you want to be able to move a tab from one window to another Warp window?

Or the order in the current Warp widnow.

**Comment by davidrenne** [comment]
@elviskahoro just move within same window.  Moving between new windows seems a bit too much work I would think.  Just simple move like chrome does.

**Comment by elviskahoro** [comment]
We support doing this with the context menu. Gonna close this in favor of #058 since that's where it was originally posted.

<img width="208" alt="CleanShot 2022-09-20 at 14 42 17@2x" src="https://user-images.githubusercontent.com/29553206/191338709-005764ac-57c7-45a2-b35d-42fba6b044a9.png">
