### ISSUE TITLE
Tab autocomplete for path not working with vim -p

### ISSUE THREAD

**Issue by pzoomin** [warpdotdev/Warp#1824]
## Expected:

`vim -p pathbeginning... <tab>` should present autocomplete suggestions

## Actual

`vim -p pathbeginning... ` shows some possibilities greyed out, but on hitting `<tab>` suggests cli flags rather than paths.

 
 

### To Reproduce

Assuming vim is installed on system,

`vim beginningofpath... <tab>` and you will see it work correctly

`vim -p beginningofpath... <tab>` and you will see not work as expected.

### Expected behaviour

Using the `-p` flag for the `vim` command should allow path completion just as omitting the `-p flag does. Eg `vim pathstart <tab>` and `vim -p pathstart <tab>` should behave the same.

### Screenshots

*Correct:*

![Screen Shot 2022-09-09 at 4 28 00 PM](https://user-images.githubusercontent.com/104377446/189437614-e38a7a68-0955-45d1-b6df-1be0deeea509.png)

*Incorrect:*
(note that I typed `sr` then <tab>, but Warp changed it to `sr-` on hitting `<tab>`

![Screen Shot 2022-09-09 at 4 28 14 PM](https://user-images.githubusercontent.com/104377446/189437640-8e3c4ec2-c767-4b2d-82ec-16a3704e7fc4.png)

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.07.14.56.stable_00

### Additional context

Noticed possible similar issues already filed:

- https://github.com/warpdotdev/Warp/issues/1022
- https://github.com/warpdotdev/Warp/issues/1403

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Hi @pzoomin , I'm Danny, Support Engineer at Warp. Thanks for bringing this to our attention. I was able to repro this bug. We will post any updates here.

**Comment by szgupta** [comment]
Hey @pzoomin, quick question, are you using the experimental "Completions as you type" feature when seeing this bug?

**Comment by pzoomin** [comment]
No, I don't believe so, but attaching a screenshot of my settings:

<img width="686" alt="Screen Shot 2022-09-26 at 10 03 19 AM" src="https://user-images.githubusercontent.com/104377446/192297386-99989a9b-d5ec-4311-92a4-1c764ee49d4e.png">

**Comment by szgupta** [comment]
Thanks, that's helpful! And just to confirm, can you repro this problem on the latest version of Warp (`v0.2022.09.20.08.08.stable_01`)? We had some command entry bug fixes go in recently and I can't repro this on the latest version, so I'm curious if we might have fixed this in the process 🤔

**Comment by pzoomin** [comment]
Just tried, looks like it is indeed working correctly now!

version: `v0.2022.09.20.08.08.stable_01`

**Comment by szgupta** [comment]
Awesome! Thanks for confirming and for your patience with this issue! :)
I'll close this out for now, but feel free to re-open if you find it still doesn't work as expected

**Comment by xandervr** [comment]
Does not work for scp either in the current version

**Comment by juanlopez4691** [comment]
Path autocompletion works for me with `vim`, `vim -p` but fails with [LunarVim](https://www.lunarvim.org/) (a neovim IDE layer).
