### ISSUE TITLE
prevent accidently closing tab

### ISSUE THREAD

**Issue by oshanz** [warpdotdev/Warp#1828]
### Describe the solution you'd like?

```text
sometimes I accidentally enter the close hotkey in the wrong window(wanted to close a browser tab) and warp just closes the working tab. I wish there were a way to "lock" important tabs. so then it would ask for a confirmation before closing the tab.
```

### How important is this feature to you?

4

**Comment by plaukiu** [comment]
+1

Especially when a process is running. Lost a few unsaved vim sessions this way.

**Comment by dannyneira** [comment]
Hi @oshanz, Thanks again for your request, as this is a very similar/duplicate request so I'm closing in favor of https://github.com/warpdotdev/Warp/issues/197

Please +1 that request as it helps us gauge interest. We will post any updates there.
