### ISSUE TITLE
[Bug] Warp doesn't get the last command from terminal

### ISSUE THREAD

**Issue by Soromeister** [warpdotdev/Warp#1830]
### Discord username (optional)

Soromeister#1365

### Describe the bug

When pressing UP arrow to repeat the previous command, Warp inserts a totally different command, it's as if it doesn't read or write the commands properly to/from the history. This wasn't the case in previous Warp versions.
Another thing I've noticed is that my input has an extra space at the beginning of the line, so any command I input is prefixed by an empty space. Not sure how it goes through but it's just a cosmetic issue for now.

### To Reproduce

1. Make sure you have your bash/zsh history populated
2. Open up warp
3. Execute a command you haven't executed before
4. Press UP arrow to populate input with previous command
5. You will notice that the previous command doesn't fill the input.

### Expected behaviour

When pressing UP arrow, Warp should populate prompt with the previous command.

### Screenshots

Warp Settings:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/45243695/189636819-3e03bea2-7a1a-474e-a17c-149f77d4bb8b.png">

<img width="674" alt="image" src="https://user-images.githubusercontent.com/45243695/189636894-b086cb1d-a7ce-4fb0-b0a5-1700c8ce8af7.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/45243695/189636997-e40ffe38-a111-4446-ba05-6e1c41e4fbfa.png">

### Operating System

MacOS

### OS Version

12.5.1 (21G83)

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2022.09.07.14.56.stable_00

### Additional context

Here is [my .zshrc file](https://github.com/warpdotdev/Warp/files/9547902/my-zshrc.txt) and the accompanying [starship.toml](https://github.com/warpdotdev/Warp/files/9547267/starship.txt)

Also, these are [my custom plugins](https://github.com/warpdotdev/Warp/files/9547906/plugins.zip) for oh-my-zsh. They need to go to `~/.oh-my-zsh/custom/plugins`

Everything works properly in iTerm2, so I don't think the issue is related to my RC files.

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @Soromeister, I'm Danny, Support Engineer with Warp. Sorry to hear you're having this issues with history and input. I suspect the two issues you're having may be related to your custom prompt ( PS1 ) setting.

My guess is that you normally have a custom prompt and that Warp is unable to parse it. Currently [multi-line or right sided prompts aren't supported](https://docs.warp.dev/features/prompt#why-some-custom-prompts-are-not-supported). 

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Set
ZDOTDIR=/
in your
~/.zshenv
file. This forces Zsh to run with zero configs.

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# Whatever you want to disable

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```

**Comment by Soromeister** [comment]
Hi @dannyneira,

Thanks for your response. Apparently, the issue is caused by the extra line prefixing the prompt input. There is no workaround to it at the moment, except disabling the Starship prompt entirely and running with the vanilla ZSH prompt.

Do you plan on adding support for these custom prompts, like Powerlevel10k or Starship?

Related to the right side sided prompt, It would be nice to include a setting within Warp to show the executed time of each block, with options to configure the format for it. This is the only reason I'm using the right side prompt for the time being.

**Comment by Soromeister** [comment]
Hi @dannyneira,

I'm closing this as I managed to fix it so far. I have disabled the right side prompt, which, in turn, eliminated the extra space at the beginning of the prompt.

One question remains: Will Warp support Powerlevel10k with right side prompt and when do you thing it would happen?
