### ISSUE TITLE
Warp not respecting default shell

### ISSUE THREAD

**Issue by paymog** [warpdotdev/Warp#1833]
### Describe the bug

When I open a new tab in Warp I see `starting zsh` but then it seems that zsh doesn't start.

<img width="990" alt="image" src="https://user-images.githubusercontent.com/1986950/190194219-51f232f0-6813-4850-9fc3-5a2122df4e19.png">

However, if I then manually start zsh, I see what I expect

<img width="990" alt="image" src="https://user-images.githubusercontent.com/1986950/190194300-be75e77f-6dfd-4fdf-8a94-8e955d8d36cd.png">

### To Reproduce

Don't know how to reproduce unfortunately

### Expected behaviour

I expect zsh to start when I open a new warp tab

### Screenshots

I've attached screenshots above

### Operating System

MacOS

### OS Version

12.5

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2022.09.07.14.56.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by paymog** [comment]
oh wait, it seems warp does load my shell because my aliases are there, but it seems that vim mode and other such aspects of my customized shell aren't loaded by default.

**Comment by dannyneira** [comment]
Hi @paymog, I'm Danny, Support Engineer with Warp. Sorry youre having these issues with the app. You're correct in that vim mode isn't currently supported but we do have a feature request out for support, #159, so please 👍 that one as it helps us gauge interest.

Now for your other issues, my guess is that you normally have a custom prompt and that Warp is unable to parse it. 

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Set
ZDOTDIR=/
in your
~/.zshenv
file. This forces Zsh to run with zero configs.

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# Whatever you want to disable

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```

We have a list of incompatible tools in our documentation: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>

**Comment by Soromeister** [comment]
Hey @paymog, you need to enable `Honor user's custom prompt (PS1)` in the Preferences > Features page. Make sure your prompt doesn't have a right side to it and it should work.

**Comment by dannyneira** [comment]
@paymog any luck with zsh startup by running clean configs?

**Comment by paymog** [comment]
I think it was my custom prompt which has stuff on the right hand side. I use vim mode with zsh - if I fix up my prompt to remove stuff on the RHS, would we expect warp to work with the zsh vim mode?

**Comment by Soromeister** [comment]
@paymog , I use [Starship Prompt](https://starship.rs/) and I recommend it. It's pretty easy to setup and to make it work in Warp you need to make sure the below:
- No right side stuff. It's not supported
- No multiline terminal. It will get crunched to one line anyway, so make sure input is on the same line as the prompt.

**Comment by paymog** [comment]
Awesome thanks for the tip @Soromeister! I'll give it a shot. Hoping there are good guides for getting to work with zprezto without adding extra bloat 🤞

**Comment by dannyneira** [comment]
@paymog no vim-mode at this moment, but we do have an FR #159 out for that support. Please +1 that one as it helps us gauge interest.

Please let us know if you're still having issues with shell after trying the recommendations above.

**Comment by dannyneira** [comment]
Any updates on this @paymog ?

**Comment by paymog** [comment]
I think we can close this out, I'll wait for vim mode to be natively supported.
