### ISSUE TITLE
Solarized Dark Theme is not using the right colors

### ISSUE THREAD

**Issue by buesing** [warpdotdev/Warp#1835]
### Describe the bug

Compare this (warp):
<img width="988" alt="image" src="https://user-images.githubusercontent.com/1181371/190447698-67131c52-9e4a-401a-bbf5-7a37ef4981e9.png">

To this (iTerm2):
<img width="880" alt="image" src="https://user-images.githubusercontent.com/1181371/190447752-a57dced2-d572-4ac9-a51b-155fdb960be4.png">

Some colors seem to be switched around in the solarized color scheme. What's normally grey is white in warp, and vice versa, other colors are changed too. I don't mind putting a spin on color schemes but solarized specifically has been popular due to it's precision, so I think it should be used as-is.
In my example what is specifically questionable is that the comments are a lighter shade than the actual code, which is confusing in terms of visual hierarchy.

Another example from within zsh:
warp:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/1181371/190451414-41a0936c-04dd-4112-840c-005d6cc78d42.png">

iterm2:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/1181371/190451477-14a48383-c97f-4a4e-9aeb-60d6a3e80093.png">

Terminal.app
<img width="670" alt="image" src="https://user-images.githubusercontent.com/1181371/190451535-af392545-2b16-4ff7-b25f-0503ade8b48e.png">

### To Reproduce

Open warp with solarized dark, observe a different color scheme than in other terminal emulators.

### Operating System

MacOS

### OS Version

12.0

### Shell Version

zsh 5.8

### Warp Version

v0.2022.09.07.14.56.stable_00

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Hi @buesing Thanks for bringing this to our attention. We'll see about getting those colors changed and post an updates here.

You can also modify the default themes to you liking, see more here: 
https://docs.warp.dev/features/themes/custom-themes

Or make you own custom themes with this tool: https://warp-themes.com/

**Comment by elviskahoro** [comment]
Gonna merge this into #362

**Comment by elviskahoro** [comment]
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">
