### ISSUE TITLE
[Feature] Hide tab bar when only one tab is open

### ISSUE THREAD

**Issue by Soromeister** [warpdotdev/Warp#1836]
### Discord username (optional)

Soromeister#1365

### Describe the solution you'd like?

```text
Have an option in Warp that when having just one tab open, the tab bar should be hidden, kind of how iTerm2 has it.
```

### How important is this feature to you?

1 (Not too important)

**Comment by dannyneira** [comment]
Thanks for this feature request @Soromeister. Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by Zabriskije** [comment]
+1
Would also be nice to have the window controls and warp AI/Settings buttons hidden until mouse hover, since when using terminals in quarter-screen sizes (or smaller), any pixel counts.
