### ISSUE TITLE
Support switching to previously used tab

### ISSUE THREAD

**Issue by BugWriter2** [warpdotdev/Warp#1839]
### Describe the solution you'd like?

```text
It would be great if there is a shortcut for switching to previously used tab.
```

### Is your feature request related to a problem? Please describe.

```text
I do not want to count the order of tabs before switching
```

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by simPod** [comment]
From my Iterm I'm used to switch between tabs in the order they were used with `ctrl+tab`. 

Warp is great but if you have like 20 tabs open, the previously used tab is 19x `ctrl+tab` far away which is not friendly at all 😄

**Comment by dannyneira** [comment]
Currently, Warp does not have a built-in feature to quickly switch between the two most recently used tabs. The existing tab navigation options include:
- Using Cmd + number (1-8) to switch to specific tabs or using keyboard shortcuts to navigate to the previous or next tab sequentially, [as documented here](https://docs.warp.dev/features/windows/tabs#how-to-use-it).

That being said, we're tracking an existing feature request to keyboard shortcut cycle thru the last used tabs over at https://github.com/warpdotdev/Warp/issues/2136

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
