### ISSUE TITLE
Blocks history too short

### ISSUE THREAD

**Issue by berkus** [warpdotdev/Warp#1843]
### Describe the solution you'd like?

```text
I would like a much larger default of stored blocks in the session history or perhaps configurable "blocks scrollback" size.

Also a configurable scrollback buffer size for each block (and perhaps make it loadable or otherwise expandable - a way to keep it from having huge unwieldy buffer with tiny scrollbar while still being able to see the entire session output).
```

### Is your feature request related to a problem? Please describe.

```text
For some reason the number of remembered blocks in the session is too short - I cannot scroll back past perhaps last 20 or so.

Each block also has very limited number of last lines available - as an example, I have a program that causes endless loop of exceptions in QEMU and by the time I manage to press Ctrl+C the whole startup scrollbar just breezes past the history limit and I don't see anything that lead to the exception (so even if I'm fast, in half a second it manages to scroll through about 300,000 lines of text, of which I can see about 2000 last).
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by Michael-Choi** [comment]
not being able to increase the scrollback buffer is the only feature holding our team back from switching over from iterm2

**Comment by dannyneira** [comment]
Closing in favor of https://github.com/warpdotdev/Warp/issues/610

**Comment by Alex-EEE** [comment]
When I see the other issue, it looks very different. 

This one refers to restoring a session.  This other issue refers to not having enough lines for long output from a command no?????
