### ISSUE TITLE
Copy folder location automatically to write a line

### ISSUE THREAD

**Issue by yanirmanor** [warpdotdev/Warp#1844]
### Describe the bug

Copy folder location automatically to write a line

### To Reproduce

open

### Screenshots

<img width="418" alt="image" src="https://user-images.githubusercontent.com/16289435/190894481-a101c208-251d-454c-b8ff-85ea612116a6.png">

### Operating System

MacOS

### OS Version

12.5

### Shell Version

5.8.1

### Warp Version

v0.2022.09.13.08.15.stable_03

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @yanirmanor, I noticed you closed this issue, just curious if it was a custom prompt issue and how did you find a resolution?

**Comment by yanir-armis** [comment]
I think after I edit the starship configuration it is fixed.
Thanks
