### ISSUE TITLE
Path completion broken on paths with whitespaces

### ISSUE THREAD

**Issue by chrmoritz** [warpdotdev/Warp#1845]
### Describe the bug

Path completion stops showing any suggestions once you hit a path containing an (escaped) whitespace.

### To Reproduce

type `ls ~/Library/Application\ Support/` and press `tab` and you won't see any folder suggestions

### Expected behaviour

to see a list of folders for the completions

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Warp Version

v0.2022.09.13.08.15.stable_03

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Thanks for bringing this to our attention @chrmoritz. I was able to reproduce this issue. We will post any updated to this here.

**Comment by kLy** [comment]
Yes this is very broken and makes Warp very unusable for me. Happening for me on fish.

**Comment by chrmoritz** [comment]
Looks like this bug was fixed with the latest release: `v0.2023.01.10.08.02.stable_01`. Thank you!
