### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by javasopp** [warpdotdev/Warp#1846]
### Describe the bug

I want to know how to completely uninstall the warp and delete all the configurations. After I installed it once with brew, it started to freeze. After reinstalling, I still use my account information. I think it should be re-login, so I want to test if the problem is caused by not completely uninstalling.

### To Reproduce

just uninstall

### OS Version

13.0 beta 7

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.09.13.08.15.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by javasopp** [comment]
association #1768

**Comment by dannyneira** [comment]
Hi @javasopp You can remove the user login by deleting the Keychain Access entry for `warp-stable`. Also for the brew install, try running a `brew uninstall warp ; brew cleanup warp` to see if that helps cleanup the older installation

**Comment by dannyneira** [comment]
@javasopp We added uninstalling Warp docs page with a bit more details on removing Warp. 

https://docs.warp.dev/help/uninstalling-warp

**Comment by ravshan2rtikov** [comment]
how to uninstall warp from ubuntu, the app just stopped responding, not launching nothing
