### ISSUE TITLE
Support Hyperlinks based on escape sequences

### ISSUE THREAD

**Issue by rushi** [warpdotdev/Warp#1854]
### Describe the solution you'd like?

Support hyperlinks in the terminal https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

Example try the following in Iterm2 vs Warp

```shell
printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'
```

### Is your feature request related to a problem? Please describe.

Reading logs and other output becomes harder. If you use an npm module like [terminal-link](https://www.npmjs.com/package/terminal-link) 

It's much easier to develop rich TUIs with hyperlinks in the terminal

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Hi @rushi Thanks for submitting this FR, we currently support hyperlinks for http(s), ftp, etc. out of the box in Warp, but not in this exact way, see more [here](https://docs.warp.dev/features/files-and-links) Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by elviskahoro** [comment]
Gonna close this actually in favor of #176
