### ISSUE TITLE
Warp was unable to start

### ISSUE THREAD

**Issue by radoshi** [warpdotdev/warp#186]
### Describe the bug

```shell
v0.2021.09.08.20.40.stable
```

### To Reproduce

Steps to reproduce:
1. Start Warp.
2. Wait. See starting zsh stall for a while ~10 seconds)
![image](https://user-images.githubusercontent.com/329812/132749143-dea5c281-b665-487c-8221-e0abab00565b.png)
3. Get a Warp was unable to start.
![image](https://user-images.githubusercontent.com/329812/132749273-cc1618c7-7378-4c74-9f40-54164cd8a11e.png)
4. Check for .fig. Nope.
```➜  ~ grep 'fig' .zshrc .zshrc.pre-oh-my-zsh .profile .bash_profile
.zshrc:# User configuration
.zshrc:# alias zshconfig="mate ~/.zshrc"
```

### Expected behaviour

```shell
Warp to start.
```

### Operating System

MacOS

### OS Version

11.5.2

**Comment by zheng** [comment]
Does it work with clean configs? e.g. if you prepend a line to `~/.zshenv` to set `ZDOTDIR=/` or another directory that doesn't have any config files what happens?

**Comment by radoshi** [comment]
Yep that gets it to work. So there is something in my zsh that warp does
not like.

**Comment by Yonben** [comment]
Same issue here. If a dev wants some of my zsh config files, feel free to ping.

**Comment by zheng** [comment]
@radoshi @Yonben could you send those to me at zheng@warp.dev?

Appreciate it!

**Comment by TreTuna** [comment]
Yeah, I have this same issue even though I've commented out all Fig configuration in all of my files. It only happens about once a day and then any additional tabs/windows open just fine.

**Comment by dbowling** [comment]
I've had the same experience... no Fig currently in my configuration, and only some sessions fail to start.

**Comment by zheng** [comment]
Hey everyone! One factor that slowed down bootstrapping was having a lot of
aliases. Oh my zsh git and kubectl plug-ins are one source of this.

We have a fix for this that should be going out this week. You can also
check out whether commenting those plugins out fixes it.
