### ISSUE TITLE
Unable to open terminal after sleep mode on MacOS

### ISSUE THREAD

**Issue by ihor-chepurnyi** [warpdotdev/Warp#1864]
### Describe the bug

Unable to open terminal after sleep mode on MacOS Monterey 12.06. Warp terminal opens with black screen and doesn't allow to enter commands. Only restarting computer helps

### To Reproduce

It reproduces always for me after Mac wake up from sleep mode. Also, tried to kill the process, but it didn't help

### Expected behaviour

Warp terminal should work without any problems after sleep mode

### Screenshots

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/54581474/191743316-6b98719f-5157-473e-a8ce-ac59c30a4f6a.png">

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.07.14.56

### Does this block you from using Warp daily?

Yes

**Comment by ihor-chepurnyi** [comment]
Last 4 days haven't seen this issue. Closing the issue.

**Comment by dannyneira** [comment]
Thanks for the update @ihor-chepurnyi, feel free to reopen if you see the issue return.
