### ISSUE TITLE
can't close update changes when terminal height < dialogue height

### ISSUE THREAD

**Issue by daweth** [warpdotdev/Warp#1868]
### Describe the bug

After a new update you can't close the update message without resizing the terminal

### To Reproduce

1. Update terminal that is kind of short
2. observe terminal changes

### Operating System

MacOS

### OS Version

latest

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.09.20.08.08.stable_01

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Hi @daweth, We are working on this and will post any updates here.
