### ISSUE TITLE
DUP: Duplicate of #8 - "clear"  in the snackbar doesn't make sense

### ISSUE THREAD

**Issue by zachlloyd** [warpdotdev/warp#187]
### Describe the bug

```shell
After you type the "clear" command, you see clear in the snackbar, which is kind of useless and defeats the purpose of clearing the screen.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Screenshots

![New Issue · warpdotdevwarp 2021-09-09 at 3 29 56 PM](https://user-images.githubusercontent.com/8727141/132750630-9f64b6e0-6c13-47fd-855d-17b3ab51eac9.jpg)

**Comment by elviskahoro** [comment]
What if the config file had a section with a list of arguments for the UI snackbar to ignore? The clear command could be included by default. It's not clear to me yet whether there are other commands the developers would want ignored, but I think an approach like this would be enable some extensibility.

**Comment by elviskahoro** [comment]
Linking:
- #8

**Comment by lonnylundsten** [comment]
How about an option to turn off the snackbar. Some people won't want it at all, for any commands.
