### ISSUE TITLE
Use Thin Strokes Settings Field Issue when Changing Theme

### ISSUE THREAD

**Issue by RDStewart** [warpdotdev/Warp#1872]
### Describe the bug

In Settings > Appearance > Text, the picker for "Use thin strokes" uses a text color which contrasts with the current theme. When you change themes, the text color doesn't update until you mouse over the field. If you switch from a light theme to a dark theme, it becomes hard to read.

Additionally, the theme of the menu itself does not update after changing themes. It does update once you mouse over the menu.

### To Reproduce

1. Go to Settings > Appearance.
2. Set the Dark theme.
3. Restart the application.
4. Go to Settings > Appearance.
5. Note the color of the text in the "Use thin strokes" picker.
6. Open the picker and note the colors of the menu.
7. Change the theme to Light.
8. Note the color of the text in the "Use thin strokes" picker.
9. Note that when mousing over the picker to open the menu, the text color changes.
10. Open the picker and note the colors of the menu are from the Dark theme, not the currently selected theme.
11. Note that when mousing over the menu, its theme updates.

### Expected behaviour

The text stroke color and the menu theme should update when the the theme is changed rather than waiting for mouseover events.

### Operating System

MacOS

### OS Version

12.6 (21G115)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.20.08.08.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@RDStewart I think this was fixed. I'm not able to repro. Please comment if there are still issues.

**Comment by elviskahoro** [comment]
Thanks for the detailed repro btw
