### ISSUE TITLE
White Text in Settings Fields

### ISSUE THREAD

**Issue by RDStewart** [warpdotdev/Warp#1873]
### Describe the bug

In Settings > Appearance > Text, the picker and fields (Terminal font, Font size, Line height) use white text. Same for Settings > Features > Choose an editor to open file links. With a light theme (especially Solarized Light), these fields all become extremely hard to read.

### To Reproduce

1. Go to Settings > Appearance.
2. Set the Solarized Light theme.
3. Restart the application.
4. Go to Settings > Appearance.
5. Note the color of the text in the "Terminal font" picker and the "Font size" and "Line height" fields.

### Expected behaviour

The text in these pickers and fields should be a contrasting color, like the text in the Settings > Appearance > Text > "Use thin strokes" picker (though that picker also has issues, as described in #1872).

### Operating System

MacOS

### OS Version

12.6 (21G115)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.20.08.08.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
This should be out now!

**Comment by RDStewart** [comment]
I'm on v0.2022.11.14.14.55.stable_01, and the issue still seems present for me. These three controls all have white text on whatever background the theme has. Very difficult to read on Solarized Light.

Incidentally, the text in my terminals is also always white, regardless of theme: ![image](https://user-images.githubusercontent.com/14946241/202804630-5f9db97a-cca6-4f72-9c3d-9fb9a315567c.jpeg)

#1872 definitely seems to be fixed, though. Thanks!
