### ISSUE TITLE
Warp editor not opening by default

### ISSUE THREAD

**Issue by chewels** [warpdotdev/Warp#1878]
### Describe the bug

Tried to install Warp twice. Both time Warp opened without the editor. Just a flashing cursor. I expected as shown in the introduction video to see the editor.

### To Reproduce

Tried installation twice

### Expected behaviour

Expected to see the editor open as shown in the introduction video

### Screenshots

![warp-error](https://user-images.githubusercontent.com/100007146/192155786-e479ad1c-5c07-4820-8a92-767f90ea2308.png)

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 

### Warp Version

v0.2022.09.20.08.08.stable_01

### Additional context

moved back to my old faithful MAC terminal. 

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment]
Hey @chewels! Thanks for filing. Could you clarify what you mean by "editor open" in the video? The screenshot you linked with the cursor seems correct at first glance, so trying to better understand what's wrong here!

**Comment by dannyneira** [comment]
Closing as Stale since I can't reproduce this issue. @chewels Please reopen if you're still seeing the editor issue in Warp's latest version.
