### ISSUE TITLE
Core: Resizing Window crashes warp

### ISSUE THREAD

**Issue by raguay** [warpdotdev/warp#188]
### Describe the bug

```shell
I keep a small terminal window (usually iterm2) to my left while working in my editor to my right. I was trying to shrink the window to the size I wanted when it just crashed.
```

### To Reproduce

Steps to reproduce:
1. Open Warp on a M1 chipset computer
2. Resize the window to smaller size
3. It will disappear and give the crash dialog

### Expected behaviour

```shell
I expect the window to resize without any issues.
```

### Operating System

MacOS

### OS Version

11.5.2 (20G95)

### Additional context

```shell
System:  MacBook Pro (13-inch, M1, 2020)
```

**Comment by elviskahoro** [comment]
@raguay is this still happening?

**Comment by raguay** [comment]
> @raguay is this still happening?

The latest version isn't showing this problem so far. Thanks.
