### ISSUE TITLE
Holding cmd while hovering a link should show a pointer cursor

### ISSUE THREAD

**Issue by gregoirenovel** [warpdotdev/Warp#1881]
### Describe the bug

When hovering a link with the mouse, the cursor should turn into a pointer to indicate that it can be clicked.

### To Reproduce

1. Type and submit `echo "http://google.com"`
2. Hold <kbd>cmd</kbd>
3. Hover the output's link
4. Your cursor stays an arrow

### Expected behaviour

Cursor should become a pointer.

### OS Version

11.6.8

### Shell Version

zsh 5.8 (x86_64-apple-darwin20.0)

### Warp Version

v0.2022.09.20.08.08.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for the patience! This was fixed!
