### ISSUE TITLE
Can't log out / Allow for users to logout of Warp account in the UI

### ISSUE THREAD

**Issue by zhu-yifang** [warpdotdev/Warp#1883]
### Describe the solution you'd like?

```text
I can't find the place to log out the current user
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment]
Remove Warp user login with `sudo security delete-generic-password -l "dev.warp.Warp-Stable" $HOME/Library/Keychains/login.keychain`

**Comment by dannyneira** [comment]
Remove Warp user login with `sudo security delete-generic-password -l "dev.warp.Warp-Stable" $HOME/Library/Keychains/login.keychain`

**Comment by bericp1** [comment]
FWIW / for future readers: I ran the following commands to fully reset warp after running into issues where all my requests failed to view or upload shared blocks:

```
rm -rf ~/Library/Application\ Support/dev.warp.Warp-Stable
sudo security delete-generic-password -l "dev.warp.Warp-Stable" $HOME/Library/Keychains/login.keychain
```

After running those I had to open Warp, it was still logged in, then I had to quite and re-open warp again for it to finally be logged out.

**Comment by angusjknowby** [comment]
cool product, kinda crazy that we cant logout via the UI ! example: i installed and tested it using a personal login. then our company decided to use it across the dev team. so i go back to logout, to create a new account as part of our company - and......erm.....

**Comment by EvannG1** [comment]
Same problem here, I'd like to use Warp within my company and therefore create a new account with my work email, but for the moment it's impossible to log out / switch account easily.
I think this is an important feature to add since the addition of Warp Drive.

**Comment by Dillonsmart** [comment]
I think this should be prioritised.

**Comment by jaroslavmerta** [comment]
reason to uninstall

**Comment by michlimlim** [comment]
Hey all, Michelle from Warp here. I built Log Out, and as of the latest release you can log out of Warp via the UI. You can log out through the settings menu, command palette, as well as the menu item. 

![image](https://github.com/warpdotdev/Warp/assets/24448704/7bc8d10d-edf2-4d56-b708-90801c32b7be)
![image](https://github.com/warpdotdev/Warp/assets/24448704/e7932bb5-7b8b-485a-b33b-a93bc6ead0d4)
![image](https://github.com/warpdotdev/Warp/assets/24448704/f84a32fa-4fd2-4a6e-8023-482a0a125d85)

There are some known issues I've listed [here](https://docs.warp.dev/help/uninstalling-warp#known-issues). Although this main issue thread will be closed, please open new issues in this repo and upvote (:thumbsup:) more logout issues to help us prioritize them. Thank you for your patience!

**Comment by zhu-yifang** [comment]
Thank you!
