### ISSUE TITLE
Cutting long output

### ISSUE THREAD

**Issue by yaroslavyaroslav** [warpdotdev/Warp#1884]
### Describe the bug

When it going to provide some real long output, like building some software within verbose mode term cutting initial output at some point with no way to restore it.

### To Reproduce

1. `git clone https://github.com/skywinder/web3swift.git`
2. `pod spec lint Web3Core.podspec --allow-warnings --verbose`

### Expected behaviour

All building output should not be cutted

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.20.08.08.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by icecrystal23** [comment]
I'm seeing the same. It seems like the top of the block output gets cut at some point. Is there a setting for this? Or perhaps some way to see the full block output?

**Comment by icecrystal23** [comment]
Seems to be the same as #134

**Comment by elviskahoro** [comment]
We do have a maximum line limit of 10000. This is likely the root issue.

**Comment by dannyneira** [comment]
Closing in favor of https://github.com/warpdotdev/Warp/issues/610
