### ISSUE TITLE
multiple panes

### ISSUE THREAD

**Issue by alenberg6** [warpdotdev/Warp#1885]
### Describe the bug

The blue triangle in the up left corner of the right pane hides the first char typed on the line in Vim.

### To Reproduce

1. Open a new pane on the right
2. open Vim
3. typing : the blue triangle hides the characters.

### Expected behaviour

no hiding behind this blue triangle. Finding another way to signal the current pane.

### Operating System

MacOS

### OS Version

Ventura

### Shell Version

bash 5.1

### Warp Version

v0.2022.09.20.08.08.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@alenberg6 I'm seeing this too. I've enabled line numbers as a workaround so that there's left padding.
