### ISSUE TITLE
Input syntax highlighting

### ISSUE THREAD

**Issue by snasirca** [warpdotdev/Warp#1886]
### Describe the solution you'd like?

```text
Since the command input is an editor, it'd be great if we could get shell syntax highlighting.
This would help with readability of longer commands as we write them out.
```

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by Strandbummler** [comment]
+1

**Comment by snasirca** [comment]
+1

**Comment by Advait-M** [comment]
Hey folks 👋 ! @snasirca @dylandifilippo @nikolamus @Strandbummler 

Super excited to let everyone know that we just launched **Syntax Highlighting and Error Underlining on Warp yesterday** 🎉 ! By default, Warp will highlight each part of a command in a different color denoting arguments, options/flags, variables, etc. and underline invalid commands with a dashed red line. You can toggle these features on/off via the Command Palette or Settings > Features.

Please download the latest release (`v0.2022.10.11.08.13.stable_01`) to get access to these features! The screenshot below shows the features in action:

![Syntax Highlighting and Error Underlining Demo](https://user-images.githubusercontent.com/12927474/195830313-e3eab7b1-84c7-4118-896d-443215c1e3b5.png)

Check out our [user documentation](https://docs.warp.dev/features/editor/error-syntax-highlighting) for more details!

Let us know if you have any comments/feedback on these features!

**Comment by snasirca** [comment]
@Advait-M you folks are awesome! I can't believe how quickly you shipped this and my experience of using Warp terminal has just improved even more 😄

**Comment by Advait-M** [comment]
> @Advait-M you folks are awesome! I can't believe how quickly you shipped this and my experience of using Warp terminal has just improved even more 😄

Awesome to hear @snasirca - thank you for the kind words ❤️ !

**Comment by dylandifilippo** [comment]
@Advait-M Thanks for the quick update! ☺️

**Comment by Advait-M** [comment]
Going to close this issue - feel free to open a new one if anything comes up!
