### ISSUE TITLE
Move the default cursor position instead of using a single space

### ISSUE THREAD

**Issue by lambda-makes-things** [warpdotdev/Warp#1890]
### Discord username (optional)

possum 🐾#6310

### Describe the solution you'd like?

```text
instead of every block automatically starting with a single space move the default cursor instead.
```

### Is your feature request related to a problem? Please describe.

```text
Basically what happens when you make a new line is something like this (see attached video) 

because the single space is not put in to that new line, so either just put in a single space every new line or just change the default cursor position
```

### Additional context

https://user-images.githubusercontent.com/96893300/192625784-5bf57f07-875d-4fb8-88d8-94d8a0eb2751.mp4

### How important is this feature to you?

2

**Comment by dannyneira** [comment]
Hi @lambda-makes-things, It's most likely going on because you have a custom prompt or unsupported plugins in your RC files, please see this doc on troubleshooting. https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files

**Comment by lambda-makes-things** [comment]
yeah that helped, thanks!

**Comment by dannyneira** [comment]
Thanks for the update, happy to help!
