### ISSUE TITLE
Certain regexs cause minutes-long beachball

### ISSUE THREAD

**Issue by SimonBohnenQC** [warpdotdev/Warp#1893]
### Discord username (optional)

Simon Bohnen#2532

### Describe the bug

When searching for regexes like `.*` in the terminal output, the app just hangs. It does come back after a couple minutes.

### To Reproduce

1. Create some longer output
2. Cmd+F and enter `.*`

### Expected behaviour

A warning that this regex generated a lot of matches? I'm not sure what the typical approach is here. E.g. PyCharm seems to be able to handle `.*` and just highlights the whole file.

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.09.20.08.08.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks for finding this edge case!

**Comment by dannyneira** [comment]
hey folks, this issue has been fixed in the latest version of Warp.
Closing as completed, but please update and let us know if the issue persists.
