### ISSUE TITLE
Add "kick another logged-in user from macOS" to workflows/ai search

### ISSUE THREAD

**Issue by guytavor** [warpdotdev/Warp#1894]
### Discord username (optional)

gtx#4760

### Describe the solution you'd like?

```text
Kick another logged-in user from macOS
`sudo launchctl bootout user/$(id -u <username>)`
```

### How important is this feature to you?

1 (Not too important)

**Comment by dannyneira** [comment]
Hi @guytavor 

You can add workflows that all Warp users can use by contributing directly to the [Workflows repo](https://github.com/warpdotdev/workflows/tree/main/specs). See the [Contributing](https://github.com/warpdotdev/workflows#contributing) section for more details.
