### ISSUE TITLE
Broken pipe is ungraceful

### ISSUE THREAD

**Issue by yagmot** [warpdotdev/Warp#1896]
### Describe the bug

When an SSH connection dies (broken pipe), one is not returned to the local terminal session as expected. The prompt and blocks are just gone, though the terminal session appears to remain functional.

### To Reproduce

Wait for an SSH connection to die.

### Expected behaviour

Return to the regular prompt.

### Screenshots

<img width="1504" alt="Screen Shot 2022-09-29 at 12 02 36" src="https://user-images.githubusercontent.com/2442238/192930339-f0006f93-f2e0-402c-bd14-4f9c03ddd716.png">

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.20.08.08.stable_01

### Does this block you from using Warp daily?

No

**Comment by ryanbreen** [comment]
I would say this is closer to a blocker.  I need to hard kill every tab that was sshed if I switch networks, so it's a common painpoint in my usage.

**Comment by mohammedabbas27** [comment]
Any update on this? Seems to be a very common issue.

**Comment by michaelgruner** [comment]
Bumping this issue

**Comment by NikolayBorisov** [comment]
Interesting behavior. If you log in via ssh with the wrapper enabled, then disable SSH Wrapper in the settings, then open a second tab and log in via ssh again, then when Wi-Fi is disconnected/switched, the session in both tabs (with wrapper and without) is preserved and works correctly.

**Comment by zachbai** [comment]
Hey all, I'm looking into this issue. Is this still easily reproducible? I'm trying to simulate the issue by setting a super low `ClientAliveInterval` on my remote machine and after getting the broken pipe error message on the client, properly being returned back to the local shell session.

A couple follow up questions:
* Which shell are you using locally and remotely?
* Is local session still responsive (as is in @yagmot's case demonstrated by the "hello?" input)?
* Does this reproduce for all remote hosts you connect to?

**Comment by CaptainVincent** [comment]
I think this issue is very easy to reproduce, and it still happens every day in the current version. First, you SSH into a remote server, and then any network interruption can break this session.
1. zsh
2. can't go back to local session
3. yes. all remote hosts

**Comment by michaelgruner** [comment]
I'll keep an eye to answer the last two questions, but in my case:
* Which shell are you using locally and remotely?
```bash
# Locally
$SHELL --version
zsh 5.9 (x86_64-apple-darwin22.0)

# Remote
$SHELL --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
```

Interestingly, today I made a test where I'm connected to my remote server through a VPN. While logged in, I disconnected the VPN and the terminal froze for a moment. However, eventually, the local session regained life with the usual `Broken pipe`. My current warp version is `v0.2023.06.06.08.02.stable_00`. I'm not saying its fixed, just adding some evidence to the issue investigation.

**Comment by CaptainVincent** [comment]
Sorry, you are right. I missed out on something very important. My testing process actually involves attaching a tmux session on a remote server.

```
# Local
zsh 5.9 (x86_64-apple-darwin22.0)
# Remote
zsh 5.8 (x86_64-ubuntu-linux-gnu)
```

My test procedure
1. ssh server
2. tmux
3. disconnect wifi
4. wait and you're right. Eventually, the local session regained life. 
> Part of the reason for my previous misunderstanding was that I was too impatient. But...
6. reconnect wifi
7. ssh server again
8. terminal not normal anymore. (Unable to type and displaying gibberish)

**Comment by iheffner-gt** [comment]
I experienced similar behavior SSHing into an EC2 instance with a warpified remote shell. Similarly, I'm using a multiplexor on the remote (GNU/screen). I stumbled onto a workaround that restored proper Warp functionality to the broken terminal: open and close vim. My guess would be that something in this forces the terminal through a state transition that is missed on the broken pipe.

**Comment by devdoshi** [comment]
I get this when my ssh connection to an EC2 instance times out. I'm using bash

```bash
# debug output from ssh
client_loop: send disconnect: Broken pipe
# I type ssh xyz
00~ssh xyz01~
bash: 00~ssh: command not found
# any subsequent command is prefixed by 00~
```
locally (`warp v0.2023.07.11.08.03.stable_00`)
```bash
$SHELL --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
```
remotely:
```bash
$SHELL --version
GNU bash, version 5.2.15(1)-release (x86_64-amazon-linux-gnu)
```

**Comment by C00010FF** [comment]
This is an extremely frustrating issue and the main reason why I'm not pushing Warp to my team and going all in on Warp Drive.

This mainly happens to me when I move around and naturally disconnect from SSH. The frustrating part is that instead of having a quick and easy way to reconnect (e.g. pressing r), the terminal window is left in a broken state (with a red warning sign in the tab) where no commands are accepted as they get pre- and postpended some special characters.

```
00~exit01~
bash: 00~exit01~: command not found
```

**Comment by dhruvik7** [comment]
i love warp but this happens multiple times a day and has been happening for months, any chance we can get it addressed soon?

**Comment by alokedesai** [comment]
Hi all, this should now be fixed. Could you check on the latest version of Warp and confirm it no longer repros? Thank you!
