### ISSUE TITLE
Window moves during tab switching

### ISSUE THREAD

**Issue by toby-brilliant** [warpdotdev/Warp#1897]
### Describe the bug

When moving between tabs in warp with the mouse the Warp window will "walk" about. It can sometimes walk to the point where characters aren't visible off one side of the screen

### To Reproduce

Open a bunch of tabs with different programs, e.g. vim seems to shift things left (sometimes?) and click between them

### Expected behaviour

Changing tabs should never impact where the window is on my desktop

### Screenshots

Focus on one of the borders (e.g. the top right) while the video plays

https://user-images.githubusercontent.com/99420996/193131865-b97527cd-7637-4647-bc39-0162f757ccf4.mov

### Operating System

MacOS

### OS Version

macOS 12.6 (21G115)

### Shell Version

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21), zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.07.14.56.stable_00

### Does this block you from using Warp daily?

No

**Comment by PhilipDukhov** [comment]
I've run into this too, it seems to happen when I move the cursor during a click - and on the touchpad, moving a couple of pixels is a common thing

Position changes should be ignored when a click is detected
