### ISSUE TITLE
CTRL+W does not yield expected clipboard result

### ISSUE THREAD

**Issue by TomK** [warpdotdev/Warp#1902]
### Describe the bug

Possibly related to #61

In both macOS Terminal and iTerm I can use my system clipboard independently from the terminal clipboard.
CTRL+W seems to interfere with this.  In Warp, CTRL+W also copies the cut text into my system clipboard.  In addition, it does not seem to update the terminal clipboard.

### To Reproduce

1. Write `testing1 testing2 testing3`
2. CTRL+U - cuts the line
3. CTRL+Y - pastes `testing1 testing2 testing3`
4. CTRL+W - cuts `testing3`
5. CTRL+Y - pastes `testing1 testing2 testing3` - WRONG

final result is
`testing1 testing2 testing1 testing2 testing3`

### Expected behaviour

I expected the final output to be `testing1 testing2 testing3`, as the final word cut and pasted was `testing3`

Additional:
As a side effect, the system clipboard is now also `testing1 testing2 testing1 testing2 testing3`. IMO none of these commands should interfere with system clipboard, unless you deem it a "feature" of Warp (TIHI)

### Operating System

MacOS

### OS Version

2.6

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.09.27.08.11.stable_00

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Thanks for bringing this to our attention, We are able to repro this issue and will post any changes here.

**Comment by arxpoetica** [comment]
Can confirm this is happening.

**Comment by dannyneira** [comment]
Hey Folks! Just wanted to give you a quick update - as @akwodkiewicz mentioned, we've fixed the issue with the latest version of Warp `v0.2023.04.25.08.05.stable_00`.

I'll go ahead and mark this task as complete, but if you notice anything else, feel free to give us a heads-up. Thanks!
