### ISSUE TITLE
Hover state for right click menu disappeared

### ISSUE THREAD

**Issue by tkafka** [warpdotdev/Warp#1903]
### Describe the bug

When right-clicking the Warp terminal, the items had hover states, so I could see which item will be invoked when I click the mouse. Now the hover states have disappeared and the menu feels broken.

### To Reproduce

1. Right click the terminal
2. Move the mouse over the menu

### Expected behaviour

Items have hover state

### Screenshots

![SCR-20220930-fxa-2](https://user-images.githubusercontent.com/876717/193240082-2cd0a054-baf2-4cd2-b180-842cd23a02c4.png)

### Operating System

MacOS

### OS Version

12.6 (21G115)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.27.08.11.stable_00

### Additional context

n/a

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Hi @tkafka , I'm not seeing this on the latest build, can you please share a video/gif of the issue and some details of your logs? in the console.app > log reports > warp.log

**Comment by tkafka** [comment]
@dannyneira Hello Danny, I have now tried it, and the repro steps seem a bit more convoluted:

1. Set up a hotkey window
2. Start Warp
3. Open hotkey window, try right clicking - hover state works
4. Close the hotkey window with the hotkey or by clicking outside
5. (important step) Click into another app's window - in my case Arc browser (Chromium-based browser)
6. Open the hotkey window again
7. Right click there - the hover state has disappeared and won't appear again until Warp restart.

**Comment by dannyneira** [comment]
Thanks for the precise steps and video! I will bring this up with the team, only seems to be affecting the hotkey windows and not normal Warp windows.

**Comment by tkafka** [comment]
@dannyneira Thank you!

**Comment by dannyneira** [comment]
Hi @tkafka This one is apparently a feature/behavior in Mac — an app can only be focused via left clicking and only a focused app can receive mouse move events. So what happens is the right click actually does not focus the app and thus no mouse events. Closing this issue as it's not related to the app but the MacOS. Please do let us know if you have any other issues we can help with.

A similar thing happens in Slack:
https://www.loom.com/share/16c58172c1e449e48b979ebb8c408863

**Comment by tkafka** [comment]
@dannyneira Thank you for the investigation! I wondered why the hover state isn't reacting even after I left-click into the hotkey window, but apparently the hotkey window seems to be some weird state, where the app that was active before is still considered the 'active app' (and so the hotkey window is technically inactive)?
