### ISSUE TITLE
Solve for machines that are unable to resolve "warp.dev"

### ISSUE THREAD

**Issue by nfohs** [warpdotdev/Warp#1907]
### Discord username (optional)

deltaon#5148

### Describe the bug

This is more of an FYI than anything after I was banging my head against the wall forever, unable to get warp.dev to resolve at all on only one of my machines. It seems that some very old Ruby or development envs would make liberal use of /etc/resolver/dev which caused issues post TLD creation of .DEV. 

[This Stackoverflow post](https://superuser.com/questions/1374892/dev-domains-dont-resolve) was the source of my fixing it, but deleting /etc/resolver/dev allowed me to finally hit your domain. Suggest that you add this to your connection FAQs / support docs (the ones that exist outside of *.warp.dev naturally :) )

### To Reproduce

Any scenario where warp.dev will not resolve over http, https, icmp, but will via nslookup or host.

### OS Version

13.0

### Shell Version

zsh 5.8.1

### Warp Version

n/a

### Additional context

FYI submission - it does block installation and login, but it's not *your* bug to solve, mostly a troubleshooting step

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @nfohs, Thanks for bringing this to our attention, I'll be sure to add this to our https://docs.warp.dev/help/troubleshooting-login-issues docs for the future.
