### ISSUE TITLE
Theming: select one for dark mode and one for light mode

### ISSUE THREAD

**Issue by cabello** [warpdotdev/Warp#1912]
### Describe the solution you'd like?

```text
Be able to select two themes, one for light operational system theme and one for dark operational system theme.
```

### Additional context

My Mac changes light/dark based on Sunrise/Sunset.

On iTerm I have Solarized Light set to Light theme and Solarized Dark set to Dark Theme.
Same behaviour for VSCode.

Would be lovely to be able to pick two preferred themes and they auto-transition as needed.

### How important is this feature to you?

2

**Comment by dannyneira** [comment]
Hi @cabello, Fortunately, this feature already exists in Warp. Simply go to `Settings > Appearance` and enable "Sync with OS". Then choose your desired themes for light/dark modes and it should sync with the OS when you've set to change it.
Please see this loom with an example of this feature. I will close this issue in kind as the feature already exists.
https://www.loom.com/share/0b98b655d2c742c0a2139bbf7f6595c0
