### ISSUE TITLE
Ability to set tab color

### ISSUE THREAD

**Issue by randallhammond-whs** [warpdotdev/Warp#1914]
### Discord username (optional)

belamber#2626

### Describe the solution you'd like?

```text
1. Have the ability to set the tab color via cmdline.
   Something like:
   echo -n -e "\033]6;1;bg;red;brightness;255\a"
   or something similar

2. Have an option to set a random tab color when a new tab is open.
```

### Additional context

I had this for iTerm2 and it was a nice color separation between tabs instead of just words on a bar one of which has an underline.  Iterm2 would brighten the selected tab and dim the others.

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

Also as an aside, please see our Tabs docs for more info on setting tabs titles programmatically. https://docs.warp.dev/features/tabs

**Comment by randallhammond-whs** [comment]
Yes, I already use precmd_functions to set my title.

**Comment by elviskahoro** [comment]
Gonna close this out since it was launched!

**Comment by randallhammond-whs** [comment]
It was?  When was it launched?

**Comment by randallhammond-whs** [comment]
I don't see how to programmatically set the tab color to anything in the 255,255,255 space.  Just manually select 1 of 6 color balls.

**Comment by aodhagan-cf** [comment]
I also agree here with @randallhammond-whs here. I'd love a way to programatically set these, I find myself regularly having more than 6 tabs and also would love to mess around with different palettes

**Comment by jakeonrails** [comment]
Just wanna add my vote to support _programmatically changing tab colors_, so that i can quickly identify tabs by the `pwd` or the app that is running.

**Comment by maxfahl** [comment]
I really want this as well :)

**Comment by rljacob** [comment]
Probably need to open a new issue?
