### ISSUE TITLE
Feature Request: Support double tap hotkeys (eg press CTRL twice) for Hotkey Window

### ISSUE THREAD

**Issue by janosmiko** [warpdotdev/Warp#1915]
### Describe the solution you'd like?

```text
Could you add support for double-tap hotkeys for Hotkey Windows? Eg: press CTRL twice to open it? This is a feature in iTerm2 that seems to be a small but easy-to-fall-in-love-with feature.
```

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

Also as an aside, please see more on our hotkey window here: https://docs.warp.dev/features/hotkey-window

**Comment by dannyneira** [comment]
Hey folks, we will be tracking this over at #2809

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
