### ISSUE TITLE
.command file is not run when warp is set as default app for the extension

### ISSUE THREAD

**Issue by dannyneira** [warpdotdev/Warp#1917]
### Describe the bug

.command file is not run when warp is set as default app for the extension

### To Reproduce

1. Set Warp as a default app for .command extension
2. Double-click any script with .command extension. A new tab will be opened but no script is run

### Expected behaviour

.command file should execute as with other terminals

### Operating System

MacOS

### OS Version

MacOS 12.6 (21G115) Apple M1 Pro

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.27.08.11.stable_00

### Does this block you from using Warp daily?

No

**Comment by LampPrinter** [comment]
Same. Nothing happens when opening .sh files in warp either.
In iTerm I could directly open from finder.

**Comment by aceslick911** [comment]
+1 I can't get this to actually run the file in macos when a .command file or other file exitension is opened through file association

**Comment by git-commit** [comment]
This is especially critical as OSX ventura seems to prevent launching "Terminal.app" from Warp, making `open some.comman` not a viable workaround

**Comment by patrikniebur** [comment]
This would be very useful for react-native development. The default RN startup script is starting the script with `.command` extension which warp cannot run so it needs to start another terminal.

**Comment by aceslick911** [comment]
Been having this issue for over a month now - put up with it for a bit but this is seriously a pain..

**Comment by vhuerta** [comment]
just downloaded this and I'm switching back to iterm this is a deal breaker

**Comment by asdolo** [comment]
Same. I can't use Warp for React Native development. Switching back to iTerm!

**Comment by yoea13** [comment]
same problem here

**Comment by Mcrich23** [comment]
@warpdotdev-dx Ideas?

**Comment by LampPrinter** [comment]
There are so many topics about this issue. It is a basic functionality I believe they should add.
Can not open any script files directly in Warp.

**Comment by abbasahmad** [comment]
This behavior is back. the .command files are opened as files for editing and not executed;
