### ISSUE TITLE
Delay with prompt recovery

### ISSUE THREAD

**Issue by International** [warpdotdev/Warp#1919]
### Describe the bug

Command prompt does not recover soon enough, and if you start typing before it recovers, usually the first letter of the next command will be missing.

### To Reproduce

For example I do a `git add`, press enter,  followed by `git commit -m "whatever"`, or any other command while the initial one is still executing. Very often, the second command becomes `it commit -m "whatever"`. In the attached screenshots, `git co` is an alias for `git checkout`, and `git st` is an alias for `git status`.

### Expected behaviour

Second command should contain all the letters.

### Screenshots

<img width="977" alt="image" src="https://user-images.githubusercontent.com/1022918/193983534-b1ee1048-d866-4de6-9386-80c6ba366231.png">
<img width="326" alt="image" src="https://user-images.githubusercontent.com/1022918/193983554-4148bc54-4a16-4ccf-b6f6-ec970b55efd7.png">

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.27.08.11.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by zheng** [comment]
We have a fix for this issue which should be going out on Thursday's release

**Comment by dannyneira** [comment]
Hi @International, I'm Danny, Support Engineer at Warp.
Pardon the delay in response, can you please let us know if you're still seeing the issues in the latest version of Warp?

**Comment by International** [comment]
Hi @dannyneira it is much better now. I don't know if there's a bug open for it or not, but sometimes the prompt appears on the right side of zsh prompt. Know anything about it?

**Comment by dannyneira** [comment]
My guess is that you normally have a [custom prompt, theme, or plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table)

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs.

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# Whatever you want to disable

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by dannyneira** [comment]
@International Closing this issue as resolved. please see my above comments on the right side prompt issue.
