### ISSUE TITLE
Warp bot creates unmergable Homebrew PRs

### ISSUE THREAD

**Issue by SMillerDev** [warpdotdev/Warp#1920]
### Describe the bug

https://github.com/Homebrew/homebrew-cask/pull/132828 has a list of all the reviews that could not be merged because the bot does PRs wrong.

### To Reproduce

Open link above

### Expected behaviour

Bot makes PRs that are useful

### OS Version

12.6

### Shell Version

none

### Warp Version

none

### Additional context

The bot will be permanently banned from Homebrew if this is not resolved.

### Does this block you from using Warp daily?

Yes

**Comment by vorporeal** [comment]
Hey @SMillerDev, can you give a brief explanation of what it is doing wrong?  The engineer who set this up originally is OOO at the moment and a bit of assistance would help me get out a fix quickly.

**Comment by SMillerDev** [comment]
The best fix for now would be turning the bot off. The pull requests in the linked issue are duplicates or aren't based on the latest upstream branch so it seems something is going wrong with the start state of the integration.

**Comment by SMillerDev** [comment]
https://github.com/warpdotdev/Warp/issues/1476 was an earlier issue for this

**Comment by vorporeal** [comment]
Ok, the automated PRs have been disabled.  Sorry for all the spam!
