### ISSUE TITLE
Custom keyboard shortcuts are not passed to new instance of shell

### ISSUE THREAD

**Issue by jakubzeman-acc** [warpdotdev/Warp#1921]
### Describe the bug

My use case looks like this:
- I'm on Mac, and I remapped Ctrl R to Cmd R
- Works well on Warp terminal
- If I run bash (or in my case, mostly pipenv shell which executes behind the scenes new shell), the Cmd R stops working, and I have to use Ctrl R

### To Reproduce

- Remap the keyboard shortcut from Ctrl R to Cmd R
- execute bash
- press Cmd+r - nothing happens

### Expected behaviour

- Remap the keyboard shortcut from Ctrl R to Cmd R
- execute bash
- press Cmd+r - the command history search is executed

### OS Version

macOS 12.5.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.27.08.11.stable_00

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Hi @jakubzeman-acc, Sorry about this issue, thanks for bringing it to our attention. You should be able to remap your keyboard shortcuts for Command Palette ( or many other commands ) in Warps `Settings > Keyboard Shortcuts` Menu.

![CleanShot 2022-10-24 at 15 51 21](https://user-images.githubusercontent.com/16809145/197636720-b81dffd0-659b-4853-994c-4bbc9038a554.png)

Please let me know if this helps with your issue.

**Comment by dannyneira** [comment]
Hi, just checking in, was the above helpful for your issue?

**Comment by dannyneira** [comment]
@jakubzeman-acc Any luck with the above?

**Comment by dannyneira** [comment]
Closing as Stale. Please feel free to reopen if the issue persists.

**Comment by dannyneira** [comment]
Closing as stale, please reopen if the issue persists.
