### ISSUE TITLE
Horizontal layout shift

### ISSUE THREAD

**Issue by titungdup** [warpdotdev/Warp#1925]
### Describe the bug

When I switch from command mode to editor mode, there is a slight shift in horizontal spacing which causes non-essential motion that can trigger discomfort for some users.

### To Reproduce

1. Switch to editor mode. eg: vi
2. Switch back to command mode

### Expected behaviour

The UI, horizontal spacing, should be consistent across all screens.

### Screenshots

https://user-images.githubusercontent.com/7068899/194235558-20bfe1bd-74f1-48ce-a060-4260ec32d92d.mov

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.09.27.08.11.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @titungdup We have a feature request here for VI / VIM / NeoVIM support, 
https://github.com/warpdotdev/warp/discussions/451
Please +1 that request as it helps us gauge interest. We will post any updates there.
Closing this request.
