### ISSUE TITLE
History only works with current session commands if the session is terminated.

### ISSUE THREAD

**Issue by fabiocmazzo** [warpdotdev/Warp#1931]
### Describe the bug

History only works with current session commands if the session is terminated in Mac Pro M1. Pressing up arrow or using the control + R only displays the history of previous sessions

### To Reproduce

1. Open Warp and digit ls, clear, or another command.
2. Press Arrow up or Control + R, the commands don't appear.
3. Close session and reopen
4. Press Arrow up or Control + R, commands of previous session appear.

### Expected behaviour

Commands of current session appear in history

### Screenshots

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/3148792/194578174-c35dce14-91fb-493e-838b-4e181309832f.png">
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/3148792/194578270-bf8066b2-3192-4507-b716-e4d17572e4aa.png">

### Operating System

MacOS

### OS Version

MonteRey 12.5.1 (21G83)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.04.08.05.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by elviskahoro** [comment]
@fabiocmazzo I think what's happening here is that Warp is unable to properly parse your prompt and a leading space ends up in the Input Editor, which tells the shell to ignore history.

Disabling your custom prompt just for warp should fix it:
https://docs.warp.dev/features/prompt#powerlevel10k-p10k
