### ISSUE TITLE
Beachballs when hovering with the mouse over a specific URL

### ISSUE THREAD

**Issue by tancred** [warpdotdev/Warp#1933]
### Discord username (optional)

mlt#0781

### Describe the bug

Warp hangs when hovering with the mouse pointer over a specific URL in a block output.

### To Reproduce

1. Open a new shell.
2. type `brew info graphicsmagick`.
3. In the output of that command, move the mouse pointer over the URL `http://www.graphicsmagick.org/`
4. Warp beachballs. 😢

### Expected behaviour

No beachballin'! 🏖🥎🚫

### Screenshots

https://user-images.githubusercontent.com/1009061/194672376-5c26fcc4-233c-4516-a314-a75159e188f1.mp4

### Operating System

MacOS

### OS Version

12.6

### Shell Version

3.2.57(1)-release (arm64-apple-darwin21)

### Warp Version

v0.2022.10.04.08.05.stable_00

### Does this block you from using Warp daily?

No

**Comment by tancred** [comment]
I must unfortunately amend my answer to the question "Does this block you from using Warp daily?" to a yes.

Beachballing happens on many more URLs which makes the bug a lot more likely to trigger. I noticed that at least one other person ran into this issue (see #1936).

**Comment by h4rk8s** [comment]
@alokedesai Metoo.... hover URL link hans whole Warp Terminal

**Comment by szgupta** [comment]
Sorry for the issue folks! we have a fix for this in tomorrow's release
