### ISSUE TITLE
Blank lines displayed in history window

### ISSUE THREAD

**Issue by marc-l-gitHub** [warpdotdev/Warp#1934]
### Describe the bug

When pressing Up Arrow Key, the History Window opens but displays blank lines (no text).

However, the correct text is displayed on the command line. Moving up or down doesn't correct the problem in the History Window. The behaviour is the same.

My current Warp Version: v0.2022.10.04.08.05.stable_00. This problem started with the previous update and is not corrected with this one.

Restarting Warp didn't correct the problem.

### To Reproduce

At the prompt, press Up Arrow to open the command history.

### Screenshots

![Capture d’écran, le 2022-10-07 à 22 14 41](https://user-images.githubusercontent.com/53619544/194683324-32dcdd87-1812-4d6d-9cef-aee419fa4c67.png)

### Operating System

MacOS

### OS Version

12.6 (21G115)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.04.08.05.stable_00

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@marc-l-gitHub Is this still happening to you? I think this was fixed so gonna close. But comment if not.
