### ISSUE TITLE
Got `sed: RE error: illegal byte sequence` Error After Upgrading to v0.2022.10.04.08.05.stable_00 on macOS 12.6 (M1 Max)

### ISSUE THREAD

**Issue by Przeblysk** [warpdotdev/Warp#1935]
### Describe the bug

Got `sed: RE error: illegal byte sequence` Error After Upgrading to v0.2022.10.04.08.05.stable_00 on macOS 12.6 (M1 Max)

### To Reproduce

1. Open/Reopen the Warp
2. It shows the error info

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.04.08.05.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by Przeblysk** [comment]
I used the dmg installation package from the official website to overwrite the installation and the problem was solved

**Comment by elviskahoro** [comment]
@Przeblysk Apologies for the delay. Is this still happening to you?

**Comment by Przeblysk** [comment]
@elviskahoro  Yes, I found this problem when using Chinese naming for git branches. Hope to get your help

**Comment by edm00se** [comment]
I suspect this is closely related to #1431

**Comment by MonkeyInWind** [comment]
+1

**Comment by hychen** [comment]
+1

**Comment by nexcube** [comment]
+1

**Comment by conorzhong** [comment]
> @elviskahoro Yes, I found this problem when using Chinese naming for git branches. Hope to get your help

+1
