### ISSUE TITLE
Queue a command to run when the currently running command exits successfully

### ISSUE THREAD

**Issue by chuckdries** [warpdotdev/Warp#1939]
### Describe the solution you'd like?

```text
I've entered a command, and it's taking a while. I want to be able to pull up a command input, type a command, and have that command run immediately when the currently-running command exits
```

### Is your feature request related to a problem? Please describe.

```text
I started a command that I wasn't sure how long it would take, but it turns out it takes a while. I want to get up and get a coffee, but I have another command (this one I know will take a while) that I want to kickoff asap as soon as the current command finishes.
```

### How important is this feature to you?

2

**Comment by dannyneira** [comment]
This has been implemented in the latest version, please update Warp and confirm if you're seeing this feature.

For example, try `sleep 10` and then enter another command while it's running like `echo 'it works!'`

**Comment by chuckdries** [comment]
oh sick, I didn't even realize. Awesome work!
