### ISSUE TITLE
Auto completions as you type not providing path suggestions with `ls --color=auto`

### ISSUE THREAD

**Issue by dannyneira** [warpdotdev/Warp#1945]
### Discord username (optional)

can_I_crypto#0925

### Describe the bug

Autocompletion as you type feature not working with `ls` commands. I've noticed that the `--color=auto` flag appears to be breaking the directory completion. Others could be doing the same.

### To Reproduce

* Enable Autocompletions as you type feature in Warps `Settings > Features`
* Type `ls`, then space to enable auto-completion, then notice how it doesn't provide directory suggestions.

### Expected behavior

I expect to see the auto-completion menu showing directories.

### Screenshots

https://user-images.githubusercontent.com/16809145/195134340-72e1b372-e844-4fea-bccd-99ff1e026288.mp4

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.04.08.05.stable_00

### Additional context

Note: options ( flags ) suggestions for `ls` appear to be working fine

As a workaround, you can use `-G` flag instead of `--color=auto` or disable the experimental feature and continue to use TAB to engage patch/directory autocompletion.

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
