### ISSUE TITLE
Switch tabs with track pad gesture

### ISSUE THREAD

**Issue by dannyneira** [warpdotdev/Warp#1946]
### Describe the solution you'd like?

```text
switch tabs with the trackpad.
```

### Additional context

Workaround: use one of the keyboard shortcuts for navigating Tabs listed [here](https://docs.warp.dev/features/tabs).

### How important is this feature to you?

1 (Not too important)

**Comment by igoooor** [comment]
yes please, this is a default feature of mac terminal, I can switch tabs with three fingers swipe to the left or right, I am missing this with warp too

**Comment by wisarmy** [comment]
+1 I think it affects the experience for me

**Comment by dannyneira** [comment]
Hey folks! We will be tracking this request over at #582 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
