### ISSUE TITLE
Autosuggestions includes invalid completions for cd

### ISSUE THREAD

**Issue by DavidSouther** [warpdotdev/Warp#1954]
### Describe the bug

Autosuggestions uses historical cd commands. Generally, a cd command from my history isn't going to be useful.  This is so distracting, I just autosuggestions off. If you really want to suggest this, run it through a filter first to validate that the suggestion is valid from the current directory. If it did that, I'd go from frustrated to delighted!

### To Reproduce

cd between a bunch of directories to get cd into teh history. Start a new shell. Notice cd completions for unrelated directories.

### Expected behaviour

cd should only show valid autosuggestions

### Screenshots

<img width="688" alt="image" src="https://user-images.githubusercontent.com/498712/195675625-bc0576fc-3241-4240-8b38-d2a28f303ba7.png">

### OS Version

12.5

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.04.08.05.stable_00

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks david. We should have another open issue for this. Will try to merge this into the primary one soon.

**Comment by dannyneira** [comment]
Thanks for letting us know @DavidSouther 
We're tracking this in this here [#24](https://github.com/warpdotdev/warp/issues/24)
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge impact of the bug.

Closing as duplicate.

**Comment by DavidSouther** [comment]
I don't think these are the same thing? #24 is tracking tab completion. This bug happens without hitting tab, and is part of the ML autosuggestions. The bug is that the autosuggested path (the greyed out part in the command) is not a valid path for the directory that I'm currently in. (The pop up is a third place this shows up in, and is also not discussed in #24).
