### ISSUE TITLE
Gray border on window

### ISSUE THREAD

**Issue by muuvmuuv** [warpdotdev/Warp#1956]
### Discord username (optional)

muuvmuuv#1717

### Describe the bug

The window has some gray/white border on macOS.

<img width="220" alt="Bildschirmfoto 2022-10-14 um 09 52 52" src="https://user-images.githubusercontent.com/11534760/195792918-3d836ccc-810c-49a2-ad3f-36a749e967a7.png">

### To Reproduce

Open a window

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2022.10.11.08.13.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@muuvmuuv I don't think this is Warp specific. All of my mac windows have this same border. Do you have any screenshots of other apps that have what you expect?

**Comment by muuvmuuv** [comment]
Hm I only see this that strong in Warp. VS Code has a border but it matches the theme/window.

**Comment by dannyneira** [comment]
I'm seeing the same across Chrome, Docker Desktop, and Warp.

![CleanShot 2022-12-19 at 14 04 28](https://user-images.githubusercontent.com/16809145/208523760-659245ee-5ad2-406d-9117-794aa201d4d3.png)

Closing as not planned.
