### ISSUE TITLE
global hotkey activate window (restore position and size)

### ISSUE THREAD

**Issue by zhaohuanyuu** [warpdotdev/Warp#1961]
### Describe the solution you'd like?

```text
I hope hotkey acticate window should be restore the postiion and window size and it can be draged
```

### Is your feature request related to a problem? Please describe.

```text
the hotkey evoking should operate on only one window, but now if there is one window it will open another
```

### How important is this feature to you?

4

**Comment by zhaohuanyuu** [comment]
[Untitled.webm](https://user-images.githubusercontent.com/25791574/196020816-c22f28ad-18fd-415e-8522-4712294f2bdf.webm)

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.
