### ISSUE TITLE
Click on links feature stop working in Global Hotkey Window mode

### ISSUE THREAD

**Issue by joaorr3** [warpdotdev/Warp#1962]
### Discord username (optional)

joaoribeiro#7373

### Describe the bug

Click on links feature stop working when in Global Hotkey Window mode after clicking on a link with success the first time.

The screenshot shows the hover effect after clicking the link and reveal Warp with keybinding.

### To Reproduce

1. Open Warp or restart it
2. Enable `Hotkey Window` and define a keybinding
3. Check: `Autohides on loss of keyboard focus`
4. Hover + Click on a link (Should work the first time Warp is launched)
5. Press the keybinding you've define earlier
6. Hover + Click again (stops working)

### Expected behaviour

1. When keybinding is pressed to reveal Warp again the link i click earlier should not have the hover effect.
2. When i click the same or any other link i expect to see the actual opening of the link i'm hovering.

### Screenshots

<img width="378" alt="image" src="https://user-images.githubusercontent.com/38807975/196032317-6ce2e5f6-cdf2-43e3-bbbe-8c6c0898e516.png">

### Operating System

MacOS

### OS Version

12.5

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.3.0)

### Warp Version

v0.2022.10.11.08.13.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @joaorr3, Thanks for letting us know! We're sorry about this, this is not an ideal experience. Closing in favor of #2012 as there is more discussion on that thread.
