### ISSUE TITLE
Go to previous block is on top of the contents

### ISSUE THREAD

**Issue by osuuster** [warpdotdev/Warp#1964]
### Describe the bug

<img width="430" alt="image" src="https://user-images.githubusercontent.com/16510636/196124485-466c7481-a33a-4ae8-b72c-5370b077deeb.png">
As seen on the screenshot, when using SQL the `go to the previous block` is on top of the contents of the terminal, making it hard to work with, as continuous up and down scrolling is needed.

### To Reproduce

Open up any SQL and try to query a table that has a lot of entries to fill out the whole page.

### Expected behaviour

The button should either be above the contents or there should be an option to remove that button altogether.

### Screenshots

<img width="430" alt="image" src="https://user-images.githubusercontent.com/16510636/196125099-bed5f7ce-f08b-4b2a-9e1d-b6f8caf75078.png">

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.08.13.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment]
Thanks @osuuster, we're actively working on making changes to the UX of the snackbar so that this doesn't occur anymore. Will ping back once we've launched that

**Comment by paulmiddelkoop** [comment]
Same problem here. I hope we can disable the previous item since in most cases it's not important at all.

**Comment by alokedesai** [comment]
@paulmiddelkoop As part of a revamp of the snackbar UX, we plan to support disabling it entirely. We hope to launch this within the coming weeks.

**Comment by dannyneira** [comment]
We've launched a sticky command header to replace the snack bar over the blocks which can be disabled altogether. See more info on this here. https://docs.warp.dev/features/blocks/sticky-command-header

Closing as completed 🚀
