### ISSUE TITLE
Problem with LC_CTYPE

### ISSUE THREAD

**Issue by AlexeySHU** [warpdotdev/Warp#1968]
### Describe the bug

Hello! When i connect to CentOS, in console message: /etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Problem in ssh_config (/etc/ssh/ssh_config on MacOS) in lines:
Host *
    SendEnv LANG LC_*

For resolve problem (before update MacOS):
Comments or delete this lines

On iTerm2 and Console (embedded in MasOS) problem is absent 

### To Reproduce

1. Run Warp on MacOS with setting in /etc/ssh/ssh_config:
Host *
    SendEnv LANG LC_*
2. Connect to CentOS 7.x version for example

### Screenshots

![warp_problem](https://user-images.githubusercontent.com/30590420/196254043-204bdc0b-255c-47e4-966e-a62e53cd221e.png)

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.11.08.13.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@AlexeySHU Thanks for reporting. Warp still has some weirdness around locales. I think we are tracking this in another issue, will try to merge this into that if so.

**Comment by WizoneDE** [comment]
same here with different systems via ssh:


connected on an Debian system running updates:
```
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
```


directly when connecting to a redhat system via ssh:
`bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory`

**Comment by dannyneira** [comment]
We're tracking this in this here #1271 
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.

Closing as duplicate.
