### ISSUE TITLE
Warning / Prompt / Confirm before quitting + after installation

### ISSUE THREAD

**Issue by MathieuDoyon** [warpdotdev/Warp#197]
### Describe the solution you'd like?

```shell
When I did the update Warp restart by itself without asking before closing.
All running session shutdown. Could be a good idea to prompt before quit so the user can decide when he's ready to shutdown is running command.
```

**Comment by elviskahoro** [comment]
Linking:
- #324

**Comment by raulfdm** [comment]
That would be awesome indeed. Because I do this mistake often I'm training myself to be careful with hotkeys while using warp :/

**Comment by renchap** [comment]
Since starting to use Warp, I very often hit command-w while warp is in focus instead of my editor, closing the active Warp tab.
I would like to be able to have a confirmation before closing a tab (even if there is no process running in it, I want to keep the previous's commands output visible).

**Comment by himanshub16** [comment]
+1. Pressing cmd+q instead of cmd+w by mistake quits the app. A warning would have prevented such cases.

**Comment by dev4joel** [comment]
From lukecdev via Discord

There's this thing where I'll open up 3 or 4 tabs quickly to check sys and log stuff in vertical/horizontal screens and then press CMD+W to shut them down. Sometimes I press 1 too far and it closes Warp and whatever I was doing (nvim stuff is painful). An optional alert/notification like "Are you sure?" would really help. Or just having to exit the last tab twice with CMD+W*2

**Comment by mardoqueo** [comment]
+1
just updated Warp and it quit faster than a blink of an eye.

**Comment by dannyneira** [comment]
Hey Folks, this is on the roadmap and being worked on.

**Comment by elviskahoro** [comment]
This has been launched!

**Comment by mhz5** [comment]
Thank you Warp team for launching the warn before quit feature!

Can we please add a feature to warn before closing **_any_** tab (whether there is a running process or not)?
This would prevent plenty of accidental "Close Tab" keypresses, and seems like many folks on this thread have echoed this requirement.

**Comment by mhz5** [comment]
Thank you Warp team for launching the warn before quit feature!

Can we please add a feature to warn before closing any tab (whether there is a running process or not)?
This would prevent plenty of accidental "Close Tab" keypresses, and seems like many folks on this thread have echoed this requirement.

**Comment by vasilev-alex** [comment]
@dannyneira, this only works when you have running processes. But it still quits without a warning even though you have multiple tabs open.

It would make sense to always ask before quitting. In my case, I have lots of tabs arranged in a specific order for different projects. Losing them all after an accidental quit button click is really unpleasant experience.

**Comment by mhz5** [comment]
More specifically, warning before **tab close** would be helpful.
