### ISSUE TITLE
SSH:// url links

### ISSUE THREAD

**Issue by cdsgroupinc** [warpdotdev/Warp#1970]
### Discord username (optional)

Anthonyverga#5269

### Describe the solution you'd like?

```text
Using Jamf Self Service app, I’d like to have a bookmark that references to ssh://user@example.com. Currently from Jamf self service app with standard macOS terminal as default it will automatically connect to ssh and prompt for end user password. With warp it just launches warp and doesn’t respond to the url command.
```

### Is your feature request related to a problem? Please describe.

```text
Just looking to give my clients the ability to have ssh server shortcuts accessible via self service app that open in warp.
```

### How important is this feature to you?

3

**Comment by jgriem** [comment]
+1

**Comment by westerlind** [comment]
+1

**Comment by mazedlx** [comment]
+1

**Comment by ahoiroman** [comment]
+1

**Comment by dannyneira** [comment]
Hey folks, since we already have a request tracking this over at  https://github.com/warpdotdev/Warp/issues/1741

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/1741

**Comment by nico81** [comment]
+1
