### ISSUE TITLE
Bug with spaceship prompt theme.

### ISSUE THREAD

**Issue by namirinz** [warpdotdev/Warp#1973]
### Describe the bug

It produce the prefix text from default spaceship-prompt theme

~
->

https://user-images.githubusercontent.com/35620424/196377319-57fa7f6b-cd28-4515-b502-ef1bb1707393.mov

### To Reproduce

1. Start the warp terminal
2. Bug appear

### Expected behaviour

Test on default terminal app for Mac
<img width="358" alt="image" src="https://user-images.githubusercontent.com/35620424/196376710-4cb58eca-b8ed-44c7-bf27-98b4b8d5be20.png">

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.11.08.13.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by danilopolani** [comment]
Same issue here. There's nothing special needed to reproduce it: just install Warp and the Spaceship theme for Oh My Zsh.
The only thing I can do right now is to disable Spaceship for Warp and use it in VSCode and somewhere else when needed:

```bash
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
    ZSH_THEME="spaceship"
fi
```

**Comment by dannyneira** [comment]
Thanks for letting us know. We will post updates here if/when multi-line prompts are supported in Warp.

**Comment by enavarrocu** [comment]
This was working in a previous version of `spaceship` I upgraded  today to the version 4 and start failing in `warp`.

**Comment by danilopolani** [comment]
> This was working in a previous version of `spaceship` I upgraded today to the version 4 of `spaceship` and started failing in `warp`.
> 
> Update: Looks like is a combination between `spaceship` and `warp`. If you set `SPACESHIP_PROMPT_ASYNC=false` it works fine.

Can confirm that `SPACESHIP_PROMPT_ASYNC=false` works. Or, at least, it does not create a wrong output in the shell.
It still does not show the Spaceship data (e.g. current k8s environment), but that's okay I guess.

Standard terminal:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/6277291/198027825-011d801f-3c89-47bd-9cf6-268f8c22e815.png">

Warp:

<img width="140" alt="image" src="https://user-images.githubusercontent.com/6277291/198027867-0ba19bd4-d9c3-4a5e-bd83-ef22f4d6c46a.png">

**Comment by danilopolani** [comment]
> For me, it shows correctly. I'm not using `k8s`.
> 
> <img alt="image" width="608" src="https://user-images.githubusercontent.com/318491/198028295-28435e2d-72f0-4d96-98ac-1fa1a0389422.png">

Oh right, I had to enable the `Honor user's custom prompt (PS1)` Feature flag, now it works perfectly, thank you!

**Comment by dannyneira** [comment]
@namirinz are you still seeing this issue after recent updates?

**Comment by dannyneira** [comment]
> @dannyneira I am seeing it with the most updated version

Thanks for the updates, try adding `SPACESHIP_PROMPT_ASYNC=FALSE` into your `~/.zshrc` file then open a new Tab and let us know if the issue persist.

**Comment by dannyneira** [comment]
Opened a bug report with the Spaceship team here to track updates on the ASYNC issue:

**Comment by bfaulk96** [comment]
@dannyneira that did indeed work, sorry for not reading the thread more completely before commenting!

**Comment by AlmogBaku** [comment]
I noticed Wrap is very slow with Spaceship

**Comment by maurelian** [comment]
Same issue, but the suggested fix does not work. 
i.e. After adding `SPACESHIP_PROMPT_ASYNC=FALSE` to my `.zshrc` file and opening a new tab (with "honor custom prompt" enabled), I have a blank prompt. 

Manually running `source .zshrc` again properly activates my prompt, but I'd rather not have to do this everytime I open a new tabl.

**Comment by dannyneira** [comment]
I wonder if there is anything else in your prompt causing this. Opening new tabs/windows/panes should automatically "source" the .zshrc file.

**Comment by mrwolny** [comment]
Hey @maurelian, try following [this instructions](https://spaceship-prompt.sh/config/intro/#create-a-config-file) to create spaceship config. 

Adding `SPACESHIP_PROMPT_ASYNC=FALSE` in `~/.spaceshiprc.zsh` fixed the issue for me.

**Comment by maurelian** [comment]
@mrwolny ty, I gave it a shot but no luck. 

@dannyneira Thank you. I have definitely verified that: 
1. `.zshrc` is run on startup
2. `SPACESHIP_PROMPT_ASYNC=FALSE` is set.
3. manually running `source ~/.zshrc` fixes the prompt

![image](https://user-images.githubusercontent.com/23033765/218075747-3a182a05-a44c-4928-94bc-e5627b7d9513.png)

So, it's really quite confusing to me. I'll try working through your debug instructions when I get a chance.

**Comment by dannyneira** [comment]
@maurelian Also make note of the following: 
To activate Spaceship, add the following line to `~/.zshrc`:
```
source "/opt/homebrew/opt/spaceship/spaceship.zsh"
SPACESHIP_PROMPT_ASYNC=FALSE  
```
If your `.zshrc` sets `ZSH_THEME`, remove that line and also make sure that that your `echo $SHELL` reads `/bin/zsh`

Here is my example below, installed with `brew install spaceship`, and set the following in my .zshrc file.

![CleanShot 2023-02-10 at 09 48 05](https://user-images.githubusercontent.com/16809145/218148580-be99fe36-de0c-4dba-a630-07ee1e0aa42a.png)

**Comment by viandwi24** [comment]
> > For me, it shows correctly. I'm not using `k8s`.
> > <img alt="image" width="608" src="https://user-images.githubusercontent.com/318491/198028295-28435e2d-72f0-4d96-98ac-1fa1a0389422.png">
> 
> Oh right, I had to enable the `Honor user's custom prompt (PS1)` Feature flag, now it works perfectly, thank you!

i follow your step and now is work, but look in yours why "arrow" in one line with spachips data. in me this right arrow keep in new line.

![Screenshot 2023-07-02 at 04 31 59](https://github.com/warpdotdev/Warp/assets/41994283/10e6000d-c405-405d-a76e-29e8eaddec3f)

**Comment by gitgabe2000** [comment]
whtsup Guys??...
