### ISSUE TITLE
Option-Left, Option-Right to move cursor between words

### ISSUE THREAD

**Issue by andylima** [warpdotdev/Warp#1976]
### Describe the solution you'd like?

```text
Support Option-Left, Option-Right to move cursor between words.

This is very basic functionality for editing text, supported by all Mac apps (including Apple ones, like Terminal) — Warp is the first one I use without support.

It's incredible that Option-Left Option-Right is not supported yet. Please add this.
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment]
Hi @andylima, As far as I'm aware, this is supported, unless I'm misinterpreting your request or you're experiencing a bug. `OPTION+LEFT/RIGHT` is working as in my video below. If you're not seeing the same, it may be some issues with RC files. 

[Please see our docs for more help with troubleshooting RC file issues.](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
