### ISSUE TITLE
Add support for zsh/bash/fsh completions

### ISSUE THREAD

**Issue by ConorNevin** [warpdotdev/Warp#1979]
### Discord username (optional)

Naruda#0587

### Describe the solution you'd like?

```text
Warp should be able to make use of custom completion scripts generated by a CLI, such as kubectl completion zsh, etc.
```

### Is your feature request related to a problem? Please describe.

```text
Many CLIs have a command that generates a completion script for a given shell environment. While the in-built support for many CLIs is excellent, it means that many CLIs which have this ability lack support, such as an internal cli. It's also hard to know if Warp supports the current version of the CLI you are using, so individuals forced onto an older (or newer) version may run into issues where command completion doesn't work or generates incorrect arguments.
```

### Additional context

As an example of the completion command, this library is used by many Golang-built CLIs, https://github.com/spf13/cobra, (including kubectl) adds this command by default. Explicitly, https://github.com/spf13/cobra/blob/main/shell_completions.md, covers it which might be helpful for context on how its used

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

we may be opening up our completion spec for open-source contribution at some point, and have our completion support listed [here](https://docs.warp.dev/features/completions#supported-completion-specs).

**Comment by marcusthelin** [comment]
This is a must feature 🙏

**Comment by kLy** [comment]
+1

**Comment by marcusthelin** [comment]
+1

**Comment by pantoninho** [comment]
+1

**Comment by nesl247** [comment]
Without this Warp is not usable.

**Comment by dannyneira** [comment]
More user feedback on support for this: 
> The whole completion thing is what makes me go back to native terminal emulators where i can control completions myself. I really hope Warp is, at some point in time, going to add external completions to be honored as well.

> I really hope warp supports an option to disable their own autocompletion feature. I think their goal is infeasible. as Toontje said, there are so many tools..!!

>Yeah, I might switch back and wait for some more support on this

**Comment by dannyneira** [comment]
Hi All! Closing this one in favor of #652 As that encompasses all the features requested here as well as custom completions specs.

Please +1 and sub that discussion as it helps us gauge interest in this support.

**Comment by JoshanFan** [comment]
+1
