### ISSUE TITLE
Ohmyzsh fails to start up

### ISSUE THREAD

**Issue by abhishekp106** [warpdotdev/warp#198]
### Describe the bug

```shell
My default shell is Oh My Zsh (https://ohmyz.sh), and before it usually starts it prompts me:

"zsh compinit: insecure directories, run compaudit for list"
"Ignore insecure directories and continue [y] or abort compinit [n]"

Warp fails to start and the terminal stops at "Starting zsh..."
```

### To Reproduce

Steps to reproduce:
1. Download Oh My Zsh
2. Introduce an insecure directory to get zsh compinit error
3. Start up Warp

### Expected behaviour

```shell
I thought I would be able to interact with the prompts and hit y for zsh to start up.
```

### Screenshots

![Screen Shot 2021-09-12 at 10 43 28 PM](https://user-images.githubusercontent.com/40919306/133164628-5204e849-06a2-4de3-a909-02138fe5f229.png)

### Operating System

MacOS

### OS Version

11.3.1

**Comment by zheng** [comment]
If you close the dialog, are you able to continue and hit y?

We're working on making the dialog less intrusive, and in the meantime, I think this workaround will work. Understand it's pretty annoying.

**Comment by abhishekp106** [comment]
Yes I am able to continue! For a second I thought the dialog was not closeable. The workaround fixes it, and Warp works as normal.
