### ISSUE TITLE
Blank terminal after editing specs in k9s

### ISSUE THREAD

**Issue by jamiecuthill** [warpdotdev/Warp#1982]
### Describe the bug

I am using k9s to manage a kubernetes cluster, when the tool breaks out into vim to edit a spec and you save/exit instead of returning to k9s the terminal goes blank.

This doesn't happen every time, reproducing this is random.

### To Reproduce

1. Launch `k9s`
2. Browse to a resource, eg. Deployment
3. Press `e` to edit
4. Save and exit with `:wq`
5. See that the terminal does not return to k9s

### Expected behaviour

In step 5 above you should see k9s

### Screenshots

![out](https://user-images.githubusercontent.com/779188/196672426-c7fe8d5e-b5df-489a-ac52-348b51bd8ed1.gif)

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.11.08.13.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment]
Hey folks, thanks for filing this! Going to close this out in favor of https://github.com/warpdotdev/Warp/issues/1315. 

We are actively working on fixing this, but unfortunately I don't have a concrete timeline for when we think we'll be able to launch this to our stable build. We will follow up shortly

**Comment by dannyneira** [comment]
original k9s issue is #833, please track if there.

**Comment by dannyneira** [comment]
We recently made performance/compatibility updates to alt-screen apps like emacs, please let us know if you're still seeing the issues with the latest version of Warp.
