### ISSUE TITLE
Meta key does not seem to work

### ISSUE THREAD

**Issue by brandon-fryslie** [warpdotdev/Warp#1989]
### Describe the bug

With "Left Option key is Meta" enabled in preferences, pressing `opt+<key>` sends special characters rather than `meta+<key>` to terminal as expected

I use `meta+shift+<key>` for custom keybindings in ZSH.  I have "Left Option key is Meta" enabled in preferences.  However even with this enabled, the option key does not send `meta` to the terminal.

### To Reproduce

Setup:
- Fresh install of `warp` (version: `v0.2022.10.11.08.13.stable_01`)
- MacOS Monterey `12.6 (21G115)`
- Using `zsh` with custom keybindings
  - I'm using `rad-shell` (https://github.com/brandon-fryslie/rad-shell) where opt+cmd+p brings up a filterable list of my project directories
  - Keybinding is defined here: https://github.com/brandon-fryslie/rad-plugins/blob/master/zaw/proj-zaw.zsh#L1
  - This works in `Terminal` and `iTerm2` and is the standard way of binding keys in zsh
- Enable "Left Option key is Meta" in Warp preferences

To Reproduce:
- Press `opt+<key>` which should send `meta+<key>` to ZSH
- Non-ascii characters are displayed in the terminal input which is the same behavior as when "Left Option key is Meta" is not enabled

### Expected behaviour

I expect `meta+<key>` to be sent to zsh which will activate the keybinding.

### Screenshots

Result of `meta+shift+p` in Warp terminal:

![Screen Shot 2022-10-20 at 10 49 52 AM](https://user-images.githubusercontent.com/530235/197010119-bedeca82-2a4e-4367-a7ab-96c3175b0b20.png)

Result of `meta+shift+p` in iTerm2 terminal:

![Screen Shot 2022-10-20 at 10 51 11 AM](https://user-images.githubusercontent.com/530235/197010369-15392816-67d6-4738-98fb-aac55a98b24d.png)

### Operating System

MacOS

### OS Version

12.6 (21G115)

### Shell Version

zsh 5.9 (x86_64-apple-darwin20.6.0)

### Warp Version

v0.2022.10.11.08.13.stable_01

### Additional context

This is pretty much a non-starter for using Warp for anything at all since I rely heavily on the meta key for custom keybindings.  Otherwise it looks pretty cool

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment]
@brandon-fryslie Thanks for the report! Just to confirm, the bindings you have set up are bindkeys for use when in the ZSH line editor? If so, unfortunately Warp does not support these just yet because we have our line editor instead of using the shells. 

This means we only send characters to ZSH once you're pressed enter instead of on every keystroke while typing within the editor.

**Comment by micgeronimo** [comment]
@alokedesai  can we have support of regular linux command line shortcuts please?
Setting "Use Option as Meta key"  allows to move cursor in the command line with Option+F, Option+B etc.

Steps to reproduce:
Open default macos Terminal -> Preferences -> Keyboard -> Check "Use Option as Meta key"
Open warp
Type "hello world"
Press Option + B
Expected: cursor goes back one word
Actual: weird character appears on a screen

**Comment by alokedesai** [comment]
Seeing the cursor go back by one word is what I'm seeing in Warp once "Option as Meta" is enabled. Are you using an international (non-US) keyboard by any chance?

**Comment by micgeronimo** [comment]
@alokedesai I'm using `ABC - extended`, tried with `U.S.` layout but got same result. Could you please tell me the name of your input source?

**Comment by dannyneira** [comment]
@micgeronimo @brandon-fryslie 
I'm just following up on Aloke's comment, the meta key is in Warp's Settings > Features.
![CleanShot 2022-12-08 at 17 07 50](https://user-images.githubusercontent.com/16809145/206592615-dd5acde2-53e1-4c11-b4b5-0c0afad74dfe.png)
Any luck with that setting enabled?

**Comment by voodoojunk** [comment]
I have a similar problem. I have a nvim mapping <A-i> which does not seem to work.
I have "Left Option key is Meta" enabled.
It **does** work as expected on iterm2
