### ISSUE TITLE
We need infinite output

### ISSUE THREAD

**Issue by szhou42** [warpdotdev/Warp#1990]
### Describe the solution you'd like?

```text
when running long running test that outputs a ton of debug info to console, they get truncated by Warp. Please provide the option to allow configurable, larger output size.
It's needed for ppl who work on non-trivial project that outputs a lot of info.
```

### Is your feature request related to a problem? Please describe.

```text
xxx
```

### Additional context

xxx

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

Ignore

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by dannyneira** [comment]
We do have a maximum line limit of 10000. This is likely the root issue.

**Comment by dannyneira** [comment]
Closing in favor of #1884 & #1843
