### ISSUE TITLE
Application hangs indefinitely on startup

### ISSUE THREAD

**Issue by oliver-leung** [warpdotdev/Warp#1996]
### Describe the bug

Not sure when exactly this started or if I caused it, but whenever I try to start up Warp, the window hangs indefinitely until I force quit the application. I have my `.zshrc` configured to run a script on terminal startup, which prompts me to log in with my work credentials, but in the past that hasn't affected Warp at all. No idea how to move any further on this, so I call upon your help, Warp wizards! 🧙‍♀️

### To Reproduce

Open the Warp application

### Expected behaviour

Warp should complete startup and allow me to enter commands

### Screenshots

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/13292691/197229216-65aeae02-4cc4-4af2-90fc-1a6d3606ad76.png">

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

zsh 5.8.1

### Warp Version

Can't check since it won't load. Reinstalled latest as of 21 Oct 2022 via homebrew

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment]
Hey @oliver-leung, sorry for the issues you are experiencing! OOC, If you comment out the script in your `zshrc` does Warp startup successfully?

**Comment by oliver-leung** [comment]
@alokedesai Unfortunately no, it still fails to start up. I commented out just the script, then my entire `.zshrc`, and both times failed to load.

**Comment by alokedesai** [comment]
@oliver-leung When you say "hanging", is the app beachballing or the session just never starts successfully?

**Comment by oliver-leung** [comment]
@alokedesai It's beachballing (TIL that term!) and it's stuck looking like the attached screenshot above

**Comment by oliver-leung** [comment]
@alokedesai Sure, here it is: [Sample of Warp.txt](https://github.com/warpdotdev/Warp/files/9840644/Sample.of.Warp.txt)

**Comment by alokedesai** [comment]
@oliver-leung Thanks! That's very information to help us debug what's going on. OOC, do you see any sort of dialog asking you to enter your password (it could even be on another monitor) when you open Warp?

**Comment by alokedesai** [comment]
@oliver-leung Did this start happening randomly or was it after an update? If you uninstall Warp and reinstall does it keep happening?  Is Warp in your `Applications` directory?

**Comment by oliver-leung** [comment]
@alokedesai I really can't remember if this started after an update, but it's continued to happen after reinstalling twice. And yes, Warp is in my Applications directory

**Comment by alokedesai** [comment]
@oliver-leung, got it, thanks for the update! As one more thing to test, could you go to the `Keychain Access` app, search for "dev.warp.Warp-Stable", and try deleting the keychain entry and see if that fixes it (note you'll have to restart warp afterwards)?

**Comment by alokedesai** [comment]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/4110292/197276917-a860500e-688a-4372-aa5a-b4f41a76d099.png">

**Comment by oliver-leung** [comment]
@alokedesai Uh oh... Keychain Access is also beachballing when I try to delete the Warp entry. Keychain Access also seems to freeze up whenever I do any sort of write operations (e.g. creating new entries, deleting other entries). I think it could be a permissions issue due to it being a work laptop, but I don't have a personal laptop that I can test on.

Also, I've been reinstalling Warp using `brew` and still having the same issue, but installing from the DMG on your website also has the same issue.

**Comment by alokedesai** [comment]
@oliver-leung, it seems likely that this is an OS issue (instead of a Warp issue) if Keychain Access is also beachballing :(

**Comment by oliver-leung** [comment]
@alokedesai Got it, I'll spend some time troubleshooting on my own. Is it all right to keep this issue open in the meantime?

**Comment by alokedesai** [comment]
Sure thing!

**Comment by dannyneira** [comment]
@oliver-leung Keychain Access can sometimes bug out deleting, use this command instead and let us know if that helps. `sudo security delete-generic-password -l "dev.warp.Warp-Stable" $HOME/Library/Keychains/login.keychain`

**Comment by oliver-leung** [comment]
@dannyneira That command prints the following and then hangs for a long time:
```
keychain: "/Users/olileung/Library/Keychains/login.keychain-db"
version: 512
class: "genp"
attributes:
    0x00000007 <blob>="dev.warp.Warp-Stable"
    0x00000008 <blob>=<NULL>
    "acct"<blob>="User"
    "cdat"<timedate>=0x32303232303532353030333835315A00  "20220525003851Z\000"
    "crtr"<uint32>="aapl"
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "gena"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303232313031343138333332305A00  "20221014183320Z\000"
    "nega"<sint32>=<NULL>
    "prot"<blob>=<NULL>
    "scrp"<sint32>=<NULL>
    "svce"<blob>="dev.warp.Warp-Stable"
    "type"<uint32>=<NULL>
```

**Comment by dannyneira** [comment]
Wow sorry to hear about this, try it with the Mac Terminal app and if it still hangs you maybe having a macOS issue as mentioned above.

**Comment by dannyneira** [comment]
Great! thanks for letting us know if was a macOS issue, feel free to reopen it if the issue persists.

**Comment by oliver-leung** [comment]
Unfortunately, the issue is happening again after I updated Warp this week. I'm also still unable to delete the keychain entry using either iTerm2 or the default Terminal

**Comment by dannyneira** [comment]
I've noticed other users resolve a variety of issues, not just Warp, by upgrading to macOS 12.6 at least, or macOS 13 (Ventura) is optional, but should still. Please upgrade macOS and let us know if that helps.

**Comment by oliver-leung** [comment]
Got it - my work MBP isn't authorized to upgrade to Ventura yet, but I'll try Warp out again once I'm able to.
