### ISSUE TITLE
Interactive console menus using simple-term-menu (Python) doesn't work as expected

### ISSUE THREAD

**Issue by peterschmidt85** [warpdotdev/Warp#1998]
### Describe the bug

If my CLI uses interactive console menus via https://pypi.org/project/simple-term-menu/, the menus do not disappear after selection.

In all other Terminals that I checked incl. iTerm, it works perfectly well.

### To Reproduce

1. `pip install dstack`
2. Run `dstack config`
3. Select a region

### Expected behaviour

After selecting the region, the menu with regions must disappear (as in other Terminals).

### Screenshots

iTerm:
<img width="810" alt="Screenshot 2022-10-24 at 10 15 56" src="https://user-images.githubusercontent.com/54148038/197479852-962f9823-998e-44f3-88b7-70163eae57a1.png">

Warp:
<img width="1728" alt="Screenshot 2022-10-24 at 10 16 02" src="https://user-images.githubusercontent.com/54148038/197479920-d7939b66-021b-4ac8-bf34-a23f8b45d4c2.png">

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2022.10.18.08.10.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi. @peterschmidt85, Sorry about this issue, it's not an ideal experience. I've been able to reproduce this issue. We will post updates here on the status of the compatibility of this tool.

**Comment by dannyneira** [comment]
@peterschmidt85 Thanks for featuring Warp on your [front page](https://dstack.ai/)! I noticed on your docs that `dstack config` now works with a config file and may no longer use the python interactive console menus, does this issue still reproduce on your end?

**Comment by dannyneira** [comment]
Thanks so much for letting us know.
