### ISSUE TITLE
Moved to #579L Command Palette Key Binding -> CMD+K

### ISSUE THREAD

**Issue by lostdesign** [warpdotdev/Warp#200]
### Describe the solution you'd like?

```shell
So currently the shortcut is CMD+P on macOS, while commonly a command palette is found on CMD+K. Is there a way to change that behaviour?
```

**Comment by lostdesign** [comment]
Edit: While writing this issue, I noticed that CMD+K is the default for clearing the command line, so it's kinda conflicting anyways.. Guess can be closed

**Comment by elviskahoro** [comment]
Consider following this issue @lostdesign https://github.com/warpdotdev/warp/issues/30

**Comment by elviskahoro** [comment]
This should be an option + reinvestigated.

**Comment by elviskahoro** [comment]
Moving to #579 so all keybinding related issues are in one place:
- #579
