### ISSUE TITLE
NeoVim init logs does not show 

### ISSUE THREAD

**Issue by EtshD1** [warpdotdev/Warp#2000]
### Discord username (optional)

Etsh#0756

### Describe the bug

I created an `init.lua` file for NeoVim that I installed using homebrew on a Macbook Air M1. When I ran NeoNim the logs did not show up. I think the script runs because, if do run nvim with an invalid lua code, an error is prompted at startup.

I also noticed the nvim intro page never shows.

Here is a comparison of the behavior using Warp (left) and MacOS terminal (right):

https://user-images.githubusercontent.com/33322463/197520958-01dd293a-dedc-4faf-9c0b-124f0de1eecd.mp4

### To Reproduce

1) Clean install NeoVim (0.8.0)
2) Clean install Warp
3) Run nvim in Warp

### Expected behaviour

A log at the bottom and intro page if no args are supplied.

<img width="725" alt="Screen Shot 2022-10-24 at 14 57 29" src="https://user-images.githubusercontent.com/33322463/197531240-8867c2ee-8b64-42a0-9bd1-37eb97bfbf1a.png">

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.18.08.10.stable_01

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Hi @EtshD1, We don't currently support all neovim features ootb, but have an open Feature request here for this support. 
#451 Please +1 that request as it helps us gauge interest. We will post any updates there.
