### ISSUE TITLE
"Warp is damaged and cannot be opened"

### ISSUE THREAD

**Issue by sergiocasero** [warpdotdev/Warp#2002]
### Describe the bug

Just after update to macOS Ventura stable release, I get this message from the system. Early adopter user haha

### To Reproduce

Update to macOS ventura (or not, I can test something if you prefer haha)

### Expected behaviour

Warp should works

### Screenshots

<img width="318" alt="imagen" src="https://user-images.githubusercontent.com/10833202/197619990-84efc38a-b79f-481b-9e76-bf06dda5730c.png">

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

latest

### Does this block you from using Warp daily?

Yes

**Comment by TheSpyder** [comment]
I saw this too. Right before installing the new OS I noticed warp had an update available bubble in the top right, not sure if that's related.

Downloading a new build from warp.dev fixed it with settings intact (it even popped up a "what's new" box when it loaded, as if it had just upgraded itself).

**Comment by dyriavin** [comment]
Installing the most recent version fixes this problem. 

Probably it was wise to update all of the apps before installing OS update.

**Comment by sergiocasero** [comment]
My mistake! Let me close the issue

**Comment by TheSpyder** [comment]
Installing the website release fixed the problem, but I think it might've been an older release. Warp just offered an update using the 'update available' button in the top right and now it's damaged again.

**Comment by sergiocasero** [comment]
> Installing the website release fixed the problem, but I think it might've been an older release. Warp just offered an update using the 'update available' button in the top right and now it's damaged again.
> 
> 
> 
> I confirmed this by extracting a new copy from the DMG and opening the preference window to force an update check.

Yep, I've faced same issue, after updating from the app, I get the message again...

**Comment by dyriavin** [comment]
@TheSpyder @sergiocasero  

This is work-around for this issue: 
Right-click on the Warp.app icon, select Open and Warp will work with the update applied.
In my case it works fine, and the error is gone. 

Not sure if there will be dedicated patch for this, but there is an open issue  - https://github.com/warpdotdev/Warp/issues/2003 

In any case, try to use this work arround

**Comment by TheSpyder** [comment]
Yes that workaround fixed it for me, thank you
