### ISSUE TITLE
After upgrading to ventura, launching warp displayed "Warp is damaged and should be put in trash". Reinstall fixed.

### ISSUE THREAD

**Issue by guytavor** [warpdotdev/Warp#2003]
### Discord username (optional)

gtx#4760

### Describe the bug

After upgrading to ventura, launching warp displayed "Warp is damaged and should be put in trash". Reinstall fixed.

### To Reproduce

upgrade to ventura

### Operating System

MacOS

### OS Version

13

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Warp Version

don't know reinstalled it with new

### Does this block you from using Warp daily?

Yes

**Comment by ahoiroman** [comment]
Reinstall fixes it only until you update warp again using the built-in updater.

**Comment by x4fingers** [comment]
This problem needs to be fixed urgently.

**Comment by westernwontons** [comment]
@x4fingers It is fixed, have a look at this:
https://docs.warp.dev/help/known-issues#auto-update-on-macos-ventura

**Comment by joshwcorbett** [comment]
if it's fixed we should close this thread

**Comment by dannyneira** [comment]
Hey folks, we are aware of an issue with Warp's auto-update on MacOS Ventura and already released a fix!
Please see our docs for troubleshooting steps.
https://docs.warp.dev/help/known-issues#auto-update-on-macos-ventura

**Comment by H4kt** [comment]
I've got yet another Warp update that caused the same thing.
The right-click workaround fixed that again.

Warp v0.2022.10.25.08.06.stable_02
MacOS Ventura 3.0 (22A380)

**Comment by DriesMeerman** [comment]
I've encountered this issue twice after updating warp on Sonoma (14.2.1 (23C71))
