### ISSUE TITLE
Mouse showing hover states on links under Settings pane

### ISSUE THREAD

**Issue by dombarnes** [warpdotdev/Warp#2006]
### Discord username (optional)

dombarnes#5378

### Describe the bug

When you have the Settings pane open, if the mouse's current hover location is over an item that can respond to a hover state (i.e hyperlink, file/folder link) that link reacts as if its being hovered over.

### To Reproduce

1. Ensure the window has some list of files or URLs behind it
2. Open the Settings pane
3. Move mouse over url thats under the Settings window

### Expected behaviour

Links would not be responsive

### Screenshots

![Screenshot 2022-10-26 at 00 39 18](https://user-images.githubusercontent.com/511773/197902192-d0ee8626-16ba-436c-acba-6fd732414a32.png)
Note the blue text under the Settings pane, next to the Check for update button. 

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.3.0)

### Warp Version

v0.2022.10.18.10.stable_03

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@dombarnes I think this was fixed. Gonna close for now. Please comment if it's still happening to you!
