### ISSUE TITLE
Support the use of function + aliases

### ISSUE THREAD

**Issue by isanmu** [warpdotdev/Warp#2010]
### Describe the bug

1. First, Warp support  automatic completion/selection for command `cd`;

2. Second, I alias `cd` to function:
```
function cdd(){
    cd $1;ls
}
alias cd='cdd'
```
But automatic completion/selection cannot work in Warp, that confused me. 

3. Third, While i test it in iTerm, Tabby or just local terminal, they all support automatic completion/selection.

e.g.
In Warp, no hints for `cd`
<img width="227" alt="image" src="https://user-images.githubusercontent.com/39163110/197954246-e1845c21-742c-4520-a597-9fe50c93c667.png">

In other terminals, exist hints for `cd`(with same alias)
<img width="478" alt="image" src="https://user-images.githubusercontent.com/39163110/197954331-8f942274-7f5c-442a-9635-e9d576658ff3.png">

### To Reproduce

1. go to `~/.zshrc`
2. add 
```
function cdd(){
    cd $1;ls
}
alias cd='cdd'
```
3. save and `source ~/.zshrc` or open new tab
4. text `cd` with `Tab` key

### Expected behaviour

expect automatic completion and selection

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.18.08.10.stable_03

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @isanmu, I'm Danny, a Support Engineer at Warp. 

Thanks for letting us know! We're sorry about this, this is not an ideal experience. 
For cd completion/suggestions, you can toggle "Open Completions as you type" in Warps`Settings > Features`

Then disable your alias/function just for Warp by putting it in this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

function cdd(){
    cd $1;ls
}
alias cd='cdd'

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```
We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

Please let me know if this helps with your issue.

**Comment by isanmu** [comment]
> https://docs.warp.dev/features/prompt

@dannyneira Thanks for your reply and suggestions. 
1. I already toggle "Open Completions as you type". And it work fine in Warp
2. I could get completions/suggestions if type `cd` in Warp before alias.
<img width="542" alt="image" src="https://user-images.githubusercontent.com/39163110/198780068-d7124fcb-49fd-414b-b609-53c93fd69436.png">

3.  _**After add function and alias, I lost the completions in Warp, but normal in other Terminals**_

4.  I actually expect alias(plus functions) work well in Warp, not disable it in Warp.
5.  I have tried `alias cd="cd $1 ; ls"` before, but it seems only `ls` worked, while `cd` not(like picture bellow, i `cd` to folder `Applications`, but it work as command `ls ./Applications`, and still keep in `~` folder. ). That's why i turn to use function instead.
<img width="334" alt="image" src="https://user-images.githubusercontent.com/39163110/198779403-532d75b2-d653-4776-bac6-115295bd5894.png">

6.  Anyway, It would be great to support auto completions/suggestions for alias(plus with functions) in Warp in the future.

**Comment by dannyneira** [comment]
Thanks for your feedback, i'll change this one to a Feature Request to support alias functions in Warp.

**Comment by isanmu** [comment]
After update, wrap support `alias cd="cd $1 ; ls" ` now, and work fine!

**Comment by dannyneira** [comment]
@isanmu Nice! what about the other functions you mentioned above like?
```function cdd(){
    cd $1;ls
}
alias cd='cdd'```

**Comment by isanmu** [comment]
> @isanmu Nice! what about the other functions you mentioned above? Are we Okay to close this request?
> 
> ```
> function cdd(){
>     cd $1;ls
> }
> alias cd='cdd'
> ```

Sorry, it's my mistake. 😵‍💫   `alias cd="cd $1 ; ls" ` still worked as `ls` and lost function of`cd`... 
And for function way, warp still lost auto completions.
Sorry for mistakenly thinking it worked after update.

**Comment by isanmu** [comment]
> @isanmu Nice! what about the other functions you mentioned above? Are we Okay to close this request?
> 
> ```
> function cdd(){
>     cd $1;ls
> }
> alias cd='cdd'
> ```

This feature is supported now(test in latest version) and this request could be closed. Thanks for support of this feature! 😄 @dannyneira
