### ISSUE TITLE
cmd + click, Link recognition not working on hotkey window

### ISSUE THREAD

**Issue by iyu98** [warpdotdev/Warp#2012]
### Describe the bug

If you only use the ’hotkey window‘ function, the link will not be recognized. You need to open the original window again before you can use it.
like this:
https://user-images.githubusercontent.com/52142803/198219047-8c36f1e6-c18f-4f82-8f2b-05674004322e.mp4

### To Reproduce

The link is not recognized by opening the window using the 'hotkey window' function

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.10.18.08.10.stable_03

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Thanks for letting us know! I was able to reproduce this issue as well. We're sorry about this, this is not an ideal experience. We will post any updates here.

**Comment by joaorr3** [comment]
Hi @dannyneira, i've opened #1962 a few weeks ago about the same issue, but no answer. Anyway
I'm not 100% sure, but i think #1911 is causing #2012, #1962 and #1863. Meaning that it's still possible to click on links with Global Hotkey but **only** if Warp gains focus again.

**Comment by iyu98** [comment]
> Hi @dannyneira, i've opened #1962 a few weeks ago about the same issue, but no answer. Anyway I'm not 100% sure, but i think #1911 is causing #2012, #1962 and #1863. Meaning that it's still possible to click on links with Global Hotkey but **only** if Warp gains focus again.

Think you, I saw the problem in [#1911 ](https://github.com/warpdotdev/Warp/issues/1911) and knew what caused it.

**Comment by iyu98** [comment]
> Hi @dannyneira, i've opened #1962 a few weeks ago about the same issue, but no answer. Anyway I'm not 100% sure, but i think #1911 is causing #2012, #1962 and #1863. Meaning that it's still possible to click on links with Global Hotkey but **only** if Warp gains focus again.

As you said, the reason why it does not take effect is that the warp does not get the focus

**Comment by dannyneira** [comment]
Thanks for this extra info, We are aware of this issue and it does appear to be related to the focus of normal Warp windows. Will post updates on this thread when the issues are resolved. Thanks for your patience all!

**Comment by joaorr3** [comment]
Hey, i've found a workaround using **[apptivateapp](http://www.apptivateapp.com/)**. It works great btw.
Just make sure Hotkey Window is turned off in warp.

![image](https://user-images.githubusercontent.com/38807975/202256150-9b044fb3-e838-4e32-8052-3284519a1e9f.png)

**Comment by vorporeal** [comment]
Hey all, is this still an issue?  I'm having trouble reproducing it on the latest release (v0.2023.02.14.08.05.stable_01).

**Comment by dannyneira** [comment]
I can't reproduce this either with the latest Warp release, I think we'll close as resolved.

@iyu98 @joaorr3 please reopen if you see this issue again.
