### ISSUE TITLE
Increase font size of window elements (tabs, settings, command palette, resource center, etc.)

### ISSUE THREAD

**Issue by enisdenjo** [warpdotdev/Warp#2015]
### Discord username (optional)

enisdenjo#0419

### Describe the solution you'd like?

I'd like to increase the font size of **everything**, not just the terminal.

### Is your feature request related to a problem? Please describe.

On retina displays, the tab title can get quite small. I like my fonts big...

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by dannyneira** [comment]
We have an issue tracking this here #1443 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
