### ISSUE TITLE
Crashing on MacOS Ventura

### ISSUE THREAD

**Issue by Zoomelectrico** [warpdotdev/Warp#2018]
### Describe the bug

Hi there! First let me thank you for the awesome product that you're building!

Now the bug, I just updated to MacOS Ventura (13.0) when I tried to open Warp I got a crash error then I just uninstall the app and install it again everything was working fine! And update pops up I click on the update button and the app crashes again I just uninstalled and installed again and accidently press cmd + q, and quit the app again it crashes the message from the OS is this.

![image](https://user-images.githubusercontent.com/12375252/198427014-695276d1-c251-4b3c-b055-346b0720c5c4.png)

This translate from spanish to `"Warp.app" is damage and could not be open. You should moved to the trash.`

### To Reproduce

Open warp and quit the app for any reason

### Screenshots

![image](https://user-images.githubusercontent.com/12375252/198427867-79df0a19-4132-4d60-be63-24a7912c55a8.png)

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.10.18.08.10.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by envomer** [comment]
I have experienced the same thing. Is there a way to view the logs?

**Comment by ndanny** [comment]
Same here.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/18640311/198483641-082f5980-c22c-4ccb-9c8b-98e37a896d50.png">

**Comment by khrisnagunanasurya** [comment]
This problem can be fixed by reinstall the warp. #2003

**Comment by brandonkboswell** [comment]
@khrisnagunanasurya that's true, but I run into it after the new auto-update.

**Comment by dannyneira** [comment]
Hey folks, we are aware of an issue with Warp's auto-update on MacOS Ventura and already released a fix!

If you experience an error opening Warp, please try the following:

* Go to the macOS Applications folder, right-click on Warp, choose Open, then the '"Warp" is damaged' dialog will have the option to click the Open button.
![ezgif-3-7ebccee3a3](https://user-images.githubusercontent.com/16809145/198677273-48f2e942-5940-4868-8a6d-270be698295f.gif)
* If the above doesn't work, [uninstall Warp](https://github.com/help/uninstalling-warp), then [re-install Warp](https://github.com/getting-started/getting-started-with-warp).

Please see our docs for troubleshooting steps.
https://docs.warp.dev/help/known-issues#auto-update-on-macos-ventura

**Comment by dannyneira** [comment]
closing as this issue is resolved
