### ISSUE TITLE
DUP: Duplicate of #133 - Add support for path completion without `./`

### ISSUE THREAD

**Issue by waldekmastykarz** [warpdotdev/warp#202]
### Describe the solution you'd like?

When using iTerm2 with zsh, you get path completion for files and folders in the current path without having to begin with `./`. This is very convenient and would be a great addition to Warp.

**Comment by zheng** [comment]
Just so I understand, is this for when the input box is empty? Currently, it inserts four spaces, but it should bring up local path completions instead.

As of the last release, you should be getting completions for local filepaths when there's a command in the input box!

**Comment by waldekmastykarz** [comment]
Correct, the idea is that I can cd to a folder by just typing its name, without having to prepend it with `./`

**Comment by elviskahoro** [comment]
Moved to #133
