### ISSUE TITLE
Commands does not always go to history

### ISSUE THREAD

**Issue by brian316** [warpdotdev/Warp#2022]
### Describe the bug

if you type a command that fails it does not add it to history so I press the up arrow to amend the command it doesnt show up. kills basic user workflow.

### To Reproduce

i see that it happens with failed commands but it also happens when I use cat command. feels very buggy

### Expected behaviour

up arrow should always show previous typed command

### Screenshots

Press up arrow after command entered
<img width="224" alt="image" src="https://user-images.githubusercontent.com/3878246/198697284-2209339d-e9d6-401b-818f-417e2c7d3713.png">

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.25.08.06.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @brian316, unfortunately, I'm unable to repro this on my end.

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Running `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs.

Also, you can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# Whatever you want to disable

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```
We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by brian316** [comment]
wrapping that around my zsh plugins and theme fixed it. thank you.
extra question. will zsh plugins be supported in the future as that does make me lose certain functionality

**Comment by dannyneira** [comment]
It's hard to say, as there are many possible plugins to support. 
We primarily support zsh/bash/fish shells ootb along with some custom prompts https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table. 
Would love to get some great dev productivity first-party integrations in the future!

Closing this as you've we've resolved the issue with the unsupported plugin.
