### ISSUE TITLE
Getting a "Library not loaded" error when running `npm run` or any node related command. Problem only happens in Warp.

### ISSUE THREAD

**Issue by whoisjuan** [warpdotdev/Warp#2024]
### Describe the bug

I'm trying to run a very simple Next.js project from Warp, and I get the error below:

```[21890]: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.67.dylib
  Referenced from: /usr/local/Cellar/node/15.5.0/bin/node
  Reason: tried: '/usr/local/opt/icu4c/lib/libicui18n.67.dylib' (no such file), '/usr/local/lib/libicui18n.67.dylib' (no such file), '/usr/lib/libicui18n.67.dylib' (no such file), '/usr/local/Cellar/icu4c/70.1/lib/libicui18n.67.dylib' (no such file), '/usr/local/lib/libicui18n.67.dylib' (no such file), '/usr/lib/libicui18n.67.dylib' (no such file)
zsh: abort      npm run dev
```

This doesn't happen in any other terminal software in my Mac. Only in Warp.

### To Reproduce

I don't know if there's an reproduceable scenario since this might be exclusive to my machine. But I'm running a Next.js project when this error occurs.

### Expected behaviour

Run the command without errors like it effectively does when I do it outside of warp.

### Operating System

MacOS

### OS Version

12.2

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.10.25.08.06.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by whoisjuan** [comment]
Ok. I was able to fix it  by doing `brew upgrade icu4c` but I still consider this a bug since it was only reproducible in Warp. The other shells outside of Warp were not running into this problem.

**Comment by dannyneira** [comment]
Hi @whoisjuan, I'm Danny, a Support Engineer at Warp. Thanks for letting us know! We're sorry about this, this is not an ideal experience. 

I'll work on reproducing this issue and post any updates on this thread. Could you please provide a sample next.js file so we can test it on our end?

**Comment by dannyneira** [comment]
@whoisjuan Any progress on the above request?

**Comment by whoisjuan** [comment]
@dannyneira, I'm gonna close this since I solved it by upgrading a library to homebrew. I don't have any particular input that would allow you to reproduce this besides the above information. Thanks.
