### ISSUE TITLE
Input area does not respond to input if Up-arrow is pressed too quickly after the prompt is printed.

### ISSUE THREAD

**Issue by HotFusionMan** [warpdotdev/Warp#2028]
### Describe the bug

Input area does not respond to input if Up-arrow is pressed too quickly after the prompt is printed.

### To Reproduce

1. Run any command.
2. Quickly after that command has completed running, press the up-arrow key.
3. Notice that the up-arrow key has not resulted in the command history being brought up. This effect can also be observed by Cmd-Tab'ing to another application quickly after invoking a command.
4. Notice that none of the arrow keys have any effect on the input area unless a printable character is typed (I usually press the spacebar and then delete the space character that I have thereby typed).

### Expected behaviour

Input area should respond to the Up-arrow invocation of command history regardless of how quickly it is pressed after the last command has finished running.

### Operating System

MacOS

### OS Version

12.6

### Shell Version

GNU bash, version 5.1.16(1)-release (x86_64-apple-darwin21.1.0)

### Warp Version

v0.2022.10.25.08.06.stable_02

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Hi @HotFusionMan, Sorry about this issue. I'm unable to repro this on my end.

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)

move your ~/.bashrc file to another location temporarily, then open new warp window to apply changes. `mv ~/.bashrc /tmp/.bashrc`
Move the file back with `mv /tmp/.bzshrc ~/.bashrc`
If the issues persist please record the problem and let us know.

**Comment by HotFusionMan** [comment]
It seems likely this problem was related to some general slowness and weirdness on my machine. After upgrading to macOS 12.6.1, which required a reboot, I think this problem has gone away.

**Comment by dannyneira** [comment]
Thanks for letting us know! @HotFusionMan

**Comment by HotFusionMan** [comment]
I'm not sure I want to reopen this issue, given that it was hard for you to reproduce, but now I think I better understand what's happening, so in case it inspires any thoughts about what is happening in the code, here it is: what I think happens is that after pressing Command-K to clear the screen, very often the terminal pane seems to be in the block navigation mode, interpreting up-arrow as moving up one block. However, because the screen was just cleared, the block navigation cannot really do anything, especially not display anything different from what is currently on the screen. Pressing the Return key or another printing character (though the only other one I've really tried is the space bar) puts Warp back into input mode in the latest block and prompt. From that point, up-arrow now starts navigating the command history as I wished in the first place.
