### ISSUE TITLE
Discussion: SSH + Remote connection management

### ISSUE THREAD

**Issue by mittalyashu** [warpdotdev/warp#203]
Option to manage remote connections.

**Comment by elviskahoro** [comment]
Just interested in general, but what do you mean by this?

**Comment by mittalyashu** [comment]
* https://termius.com
* https://coreshell.app

**Comment by djsipe** [comment]
For my part, it would be nice if there was a way to configure connections to remote servers that you frequently access.  Some means of prefilling the hostname and other connection details that would be part of the `ssh` command.  Then a simple way to be able to pick one of those (maybe from the command pallet?).
