### ISSUE TITLE
Launch update as same app/MacOS dock item

### ISSUE THREAD

**Issue by evangrim** [warpdotdev/Warp#2030]
### Describe the solution you'd like?

```text
When using in-app update button, relaunch windows in same MacOS Dock item.
```

### Is your feature request related to a problem? Please describe.

```text
Presently, a second Warp dock item appears. This is briefly confusing, and it's a minor nuisance because I then need to take some manual steps:
- move new dock item to preferred location
- remove old Warp from dock
```

### Additional context

I'm on BigSur 11.6.8 and just updated to 0.2022.10.25.08.06.stable_02

### How important is this feature to you?

1 (Not too important)

**Comment by dannyneira** [comment]
Hi @evangrim, Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

I'm not seeing the same issue on macOS 12.6, so as a workaround I recommend you try to update to that version ( if possible )

**Comment by evangrim** [comment]
Not possible for me to update because I'm supporting legacy code, but I do appreciate you offering the workaround. It's a minor issue I'm personally willing to live with.

I'll make an effort to pay attention next time I update and record anything I notice. Thanks for your work on this cool project :)

**Comment by dannyneira** [comment]
Got it thanks for the update! I will keep this open as an FR, but I do not promise if/when this will be addressed. 🙏

**Comment by zandoh** [comment]
I experience this issue on macOS Monterey Version 12.6

**Comment by zandoh** [comment]
Video showcasing the issue https://streamable.com/xf230h
