### ISSUE TITLE
Navigate between arguments in workflows

### ISSUE THREAD

**Issue by chaitanya-cloudknox** [warpdotdev/Warp#2033]
### Describe the solution you'd like?

```text
When defining a workflow with arguments its hard to navigate between arguments at least for a long command without mouse. If there is a simple keyboard shortcut to navigate between the arguments its really helpful

If I have a command like `echo "hi {{arg1}}, welcome to {{arg2}}".` after entering arg1 if I can switch to arg2 with a shortcut it would save a lot of time.
```

### Is your feature request related to a problem? Please describe.

```text
I have to use mouse every time I need to go to next argument.
```

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Hi @chaitanya-cloudknox, Sorry if this wasn't clear or intuitive, but we already support `SHIFT-TAB` as a shortcut to cycle thru the workflow parameters. See my example below and our docs on workflows. I'm closing this one, but please let me know if you have issues with this shortcut ( it can't be rebounded now).

https://docs.warp.dev/features/workflows
https://user-images.githubusercontent.com/16809145/199316958-147a0ea4-2580-420f-8c80-24031d3f7b08.mp4

**Comment by chaitanya-cloudknox** [comment]
Thank you, shift tab works. I was trying tab and other commands none works and couldn't find anything in keyboard shortcuts
