### ISSUE TITLE
Open file links in Jet Brains Fleet (PhpStorm, WebStorm, etc.)

### ISSUE THREAD

**Issue by f1rstC0de** [warpdotdev/Warp#2035]
### Describe the solution you'd like?

```text
Open file links in Jet Brains Fleet
```

### How important is this feature to you?

1 (Not too important)

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by glade-at-gigwell** [comment]
Really, opening the links in any other editor.  Add Webstorm to that list, currently it only seems to have IJ and Pycharm.

**Comment by KevinRousseau** [comment]
Gonna leave a comment here since I opened a separate issue. It was kind of the same as this one. 

Would love love love to have this feature and go full circle with Warp and PhpStorm 👍

**Comment by dannyneira** [comment]
hey Folks, closing as resolved. In the most recent version of Warp you can now configure other Jetbrains IDEs like phpstorm, webstorm, goland, etc. as default! https://docs.warp.dev/getting-started/changelog#2023.08.10-v0.2023.08.08.08.04
