### ISSUE TITLE
Not sufficient space on second line of text

### ISSUE THREAD

**Issue by bushmr** [warpdotdev/Warp#2043]
### Describe the bug

When running long running apps that have text output on the next line, the window isn't large enough to properly display status.  

### To Reproduce

Mostly seen running Azure cli commands

### Screenshots

![Screen Shot 2022-11-03 at 10 08 06 AM](https://user-images.githubusercontent.com/17806414/199759845-d259f469-b01c-47e6-b849-404f3adbff37.png)

### Operating System

MacOS

### OS Version

Monterey (12.6)

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.10.25.08.06.stable_03

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@bushmr Gonna close this out cause the team launched support for soft-wraping!
