### ISSUE TITLE
Add a confirmation window when closing a tab

### ISSUE THREAD

**Issue by ZPVIP** [warpdotdev/Warp#2044]
### Describe the solution you'd like?

```text
I always close the tab with CMD + w, sometimes I have both chrome and Warp open and just want to close a Chrome tab with CMD + w, but not noticed that Warp is the currently active window, the warp tab will be closed. This causes me to lose my work environment.

pls just add a confirmation window, it can be an option in settings. thanks!
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment]
Hi @ZPVIP, Thanks for this feature request! It's a duplicate request so I'm closing in favor of #197

Please +1 that request as it helps us gauge interest. We will post any updates there.
