### ISSUE TITLE
Having trouble to list the options per block in compact mode.

### ISSUE THREAD

**Issue by shankarshastri** [warpdotdev/warp#205]
### Describe the bug

```shell
Having trouble selecting the list of options per block in compact mode.
```

### To Reproduce

Steps to reproduce:

1. Run some commands and have at least a couple of blocks on the terminal, Go to 'Warp' and select compact mode.
2. Try to Click on the list of options icon on each block in compact mode, it doesn't allow you to click or select the option.

Adding screen recording for behavior.

https://user-images.githubusercontent.com/10391044/134186175-9e006f9b-a5bf-4230-8b1a-a073ab2d465d.mov

### Expected behaviour

```shell
In Compact mode as well, users should be able to choose the options on each of the blocks, though options are still available using a two-finger tap on Mac.
```

### Operating System

MacOS

### OS Version

11.5.2

**Comment by zheng** [comment]
Thanks for filing! It looks like this has regressed, and we will prioritize it.

**Comment by zheng** [comment]
This issue has been patched in our repo, we should be able to release it soon!

**Comment by shankarshastri** [comment]
Hope to receive an update on the app soon !!
Thanks !!

**Comment by charlespierce** [comment]
It likely won't be in this week's release, but should be in next week's.

In the mean time: The issue itself is related to toggling Compact Mode on or off. So if you have one that you prefer over the other, you can switch to that mode, then close and re-open Warp (or even just open a new tab and close the old one) and it should work going forward. It should only be when switching modes that things can get misaligned like that.

**Comment by charlespierce** [comment]
Looks like we were able to fit it in actually! Today's release should fix this even when switching modes :+1:
