### ISSUE TITLE
Commands that start with a blank don't show up in history

### ISSUE THREAD

**Issue by jvermeir** [warpdotdev/Warp#2050]
### Discord username (optional)

JanVermeir#2435

### Describe the bug

When scrolling through history with the up arrow key, a command that starts with a space is skipped. 
So 
"ls" 
shows in the history list, but 
" ls"
 doesn't

### To Reproduce

enter this command sequence in a new folder:

touch x.txt
 ls

Note that the line with 'ls' starts with a space character.

the output of ' ls' is shown in the terminal window, as expected
Now move to the previous command in history using the up arrow key. Then ' ls' should be shown but in stead 'touch x.txt' is shown

### Expected behaviour

command lines starting with a space character should show up when scrolling through history.

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.11.01.08.03.stable_00

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@jvermeir This is controlled by the shell and not the terminal actually! Starting with a space is what's typically used to communicate to the shell to ignore the command within history. This can be configured however:
https://unix.stackexchange.com/questions/115917/why-is-bash-not-storing-commands-that-start-with-spaces

**Comment by jvermeir** [comment]
Hi Elvis, thanks for the link, but I'm using zsh and not bash on OSX. 
If I start bash from a warp terminal window and run the test I've described in my question, lines starting with a space are shown. Bash responds to the HISTCONTROL setting, but it seems to be bash specific and not available in zsh. 
The stackexchange question you've mentioned works as advertised in bash.

I've tested using iTerm and osx's default term. Both show lines starting with a space. I'm also using zsh from these terminals (ps shows a bunch of zsh processes like this:
  PID TTY           TIME CMD
 4853 ttys000    0:01.12 -zsh -g --no_rcs
 5256 ttys001    0:00.97 -zsh -g --no_rcs
 9135 ttys002    0:08.07 -zsh -g --no_rcs
). 

So there must be something in the combination of warp an zsh that causes this behavior. What could that be?

regards, Jan

**Comment by ishridharhegde** [comment]
Also, every new block has a default space at the starting. 
Is there a way to disable that?

**Comment by dannyneira** [comment]
@ishridharhegde My guess is that you may have a multi-line prompt.

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here <
end
```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>
