### ISSUE TITLE
Can not ls on ~/Downloads after update

### ISSUE THREAD

**Issue by thearyanahmed** [warpdotdev/Warp#2051]
### Describe the bug

After updating to the latest (as of today : v0.2022.11.01.08.03.stable_00) I can't use `ls` on `~/Downloads` directory. Though I can use ls on other directories. 

Did a restart but it is still there. I can do the same operation with other terminals. 

### To Reproduce

- `cd ~/Downloads`
- `ls` 

### Expected behaviour

List files in the directory

### Screenshots

<img width="680" alt="image" src="https://user-images.githubusercontent.com/20617352/199998687-3f3d6f07-ef62-4377-b523-e521f73a8cac.png">

### Operating System

MacOS

### OS Version

12.6 (21G115) (apple m1)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.11.01.08.03.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @thearyanahmed Sorry to hear about this. I can't quite reproduce this, but I just want to make sure. Run `which ls` just to confirm you're not using some alias for that command.

**Comment by thearyanahmed** [comment]
Right now, `which ls` returns `/bin/ls`. After creating this issue, I had to reboot my mac for some other reason. And it was fixed. I had to change nothing. But, right now, I just did an update (current version: `v0.2022.11.08.08.07.stable_02`) and here I am with the same issue again. 

<img width="719" alt="image" src="https://user-images.githubusercontent.com/20617352/201298590-3542ae56-4f40-4af3-babe-5c1a5bf7e35b.png">

But before this update, operation was permitted.

**Comment by dannyneira** [comment]
wow so sorry about this, we have another version released, are you still seeing the same issue with ls?

**Comment by thearyanahmed** [comment]
The problem is persistent. Last checked on version `v0.2022.11.29.08.03.stable_06`

**Comment by fc7** [comment]
I am also having this issue with v0.2022.12.06.08.03.stable_02

**Comment by fc7** [comment]
This is easy to fix manually however: under macOS Preferences -> Security & Privacy -> Files and Folders,
for the application Warp, simply tick the checkboxes for Downloads and Desktop, as they are unchecked by default. After reloading Warp, you'll be able to access them. But I agree that this should be set during installation, as is the case e.g. with iTerm2.

**Comment by juli4nb4dillo** [comment]
@fc7 Solution worked for me, somehow if you miss the permissions prompt you'll have errors every time you `ls` a new folder.
![image](https://user-images.githubusercontent.com/100711062/222458394-899a6e1e-52e0-484f-ba4a-fe45ba3b1772.png)

**Comment by Christophe1997** [comment]
After upgrade My macOS version to 14.4 (23E214), the issue occurs with v0.2024.04.09.08.01.stable_01. BUT it's ok with my iterm2

**Comment by senkhxsi** [comment]
I just upgraded to MacOS 14.5 and I'm encountering this issue when using v0.2024.05.21.16.09.stable_02 but not Terminal.

**Comment by jcrapet** [comment]
You probably should add _Warp_ on System Settings > Privacy & Security > Full Disk access

<img width="827" alt="Screenshot 2024-06-05 at 14 11 42" src="https://github.com/warpdotdev/Warp/assets/107399141/86588abf-1998-4476-ba9e-d3edd6ede913">

**Comment by thearyanahmed** [comment]
Seems like there is a way around now. Not using it anymore myself. For others who are, see the comments above
