### ISSUE TITLE
Takes too much startup time when using fish

### ISSUE THREAD

**Issue by tyrone98** [warpdotdev/Warp#2053]
### Describe the bug

Take over 2 seconds to "starting fish ..."  when I start a new pane.

If I switch to zsh or bash, The warp terminal works well.  This problem only occurs with fish.

but Terminal, iterm2 does not have the same problem.

### To Reproduce

1. Remove fish personal config ( rm -rf ~/.config/fish)
2. Open the warp
3. Press CMD+D to open the new pane

Take over 2 seconds to "starting fish ..." 

### Expected behaviour

I accept that the boot time does not exceed 500 ms

### Operating System

MacOS

### OS Version

13.1 beta

### Shell Version

fish 3.5.1

### Warp Version

v0.2022.11.01.08.03.stable_00

### Additional context

Here is the log:

22:39:50 [INFO] application did become active
22:39:50 [INFO] active window changed
22:39:50 [INFO] dispatching global action for root_view:update_quake_mode_state
22:39:50 [INFO] dispatching global action for workspace:save_app
22:39:51 [INFO] Dispatching custom action SplitPaneRight
22:39:51 [INFO] dispatching typed action: Add(Right)
22:39:51 [INFO] Starting shell /opt/homebrew/bin/fish
22:39:51 [INFO] Initializing Sentry for cocoa app with endpoint https://0195a81da0714f55a93ee4624825f9ec@o540343.ingest.sentry.io/5658526
22:39:51 [INFO] Successfully spawned child fish process with pid 51331
22:39:51 [INFO] dispatching global action for workspace:save_app
22:39:51 [WARN] Expected to have session for session ID None, but doesn't exist
22:39:51 [INFO] dispatching global action for workspace:save_app
22:39:51 [WARN] Expected to have session for session ID None, but doesn't exist
22:39:51 [WARN] redraw_frame was called 2 times before the frame was drawn
22:39:51 [WARN] redraw_frame was called 5 times before the frame was drawn
22:39:51 [WARN] redraw_frame was called 6 times before the frame was drawn
22:39:52 [INFO] Received DCS string
22:39:52 [INFO] Decoded DCS
22:39:52 [WARN] redraw_frame was called 2 times before the frame was drawn
22:39:52 [WARN] redraw_frame was called 2 times before the frame was drawn
22:39:52 [INFO] Received DCS string
22:39:52 [INFO] Decoded DCS
22:39:52 [INFO] Block finished with new state DoneWithNoExecution
22:39:52 [INFO] Incrementing stage from WarpInput to ScriptExecution
22:39:52 [INFO] dispatching global action for workspace:save_app
22:39:52 [WARN] Expected to have session for session ID None, but doesn't exist
22:39:52 [INFO] Received DCS string
22:39:52 [INFO] Decoded DCS
22:39:52 [WARN] redraw_frame was called 2 times before the frame was drawn
22:39:52 [INFO] Received DCS string
22:39:52 [INFO] Decoded DCS
22:39:52 [INFO] Bootstrapping shell
22:39:52 [INFO] Parsed shell version string: Some([Number(3), Number(5), Number(1)])
22:39:52 [INFO] executing local command
22:39:52 [INFO] Shell is bootstrapped with session_id SessionId(18641)
22:39:52 [INFO] Received DCS string
22:39:52 [INFO] Setting shell history for shell "fish" and session id SessionId(18641)
22:39:52 [INFO] History file already read for (fish), not re-loading
22:39:52 [INFO] Decoded DCS
22:39:52 [INFO] Block finished with new state DoneWithNoExecution
22:39:52 [INFO] Incrementing stage from Bootstrapped to PostBootstrapPrecmd
22:39:52 [INFO] dispatching global action for workspace:save_app
22:39:52 [INFO] Received DCS string
22:39:52 [INFO] Decoded DCS
22:39:52 [WARN] redraw_frame was called 2 times before the frame was drawn
22:39:52 [WARN] redraw_frame was called 2 times before the frame was drawn
22:39:53 [INFO] application did resign active
22:39:53 [INFO] dispatching global action for root_view:update_quake_mode_state
22:39:53 [INFO] active window changed
22:39:53 [INFO] dispatching global action for root_view:update_quake_mode_state
22:39:53 [INFO] dispatching global action for workspace:save_app

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@tyrone98 gonna close this in favor of #1298. 

The root issue is here:
https://github.com/fish-shell/fish-shell/issues/7296

Please +1 the issue on fish's repo, as it's a blocker!
