### ISSUE TITLE
Warp doesn't set window titles

### ISSUE THREAD

**Issue by westernwontons** [warpdotdev/Warp#2054]
### Describe the bug

Warp doesn't set the window title, which causes an application such as [rcmd](https://lowtechguys.com/rcmd/) to now work with Warp.

### To Reproduce

1. Have rcmd installed on you system and enable experimental window switching
2. Open multiple Warp windows
3. Hold down right command

### Expected behaviour

Window titles are set by warp

### Screenshots

![rcmd](https://user-images.githubusercontent.com/75550932/200127258-b4627fee-96c5-4ff1-9525-664d8b6e299a.jpeg)
![warp](https://user-images.githubusercontent.com/75550932/200127260-f3885a9e-4312-4c1f-ac4b-32720b2317e2.jpeg)

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.01.08.03.stable_00

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

**Comment by dannyneira** [comment]
Hi @westernwontons, Thanks for letting us know! We're sorry about this, this is not an ideal experience. We will post updates here on this thread.

**Comment by dannyneira** [comment]
In the latest version of Warp, it now sets the title for the window based on the active tab/pane. Please try this rcmd switcher again and let us know if the missing title issue persists.

**Comment by westernwontons** [comment]
@dannyneira it's working great now, thank you!
