### ISSUE TITLE
bigger buffer size

### ISSUE THREAD

**Issue by geekerzhou** [warpdotdev/Warp#2056]
### Describe the solution you'd like?

```text
make buffer size settable, big log is not complete
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment]
Hi @geekerzhou, Thanks for this feature request! Closing this in favor of #610, as they are similar requests. Please +1 that request as it helps us gauge interest. We will post any updates there.

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/610
