### ISSUE TITLE
open warp in any folder

### ISSUE THREAD

**Issue by javasopp** [warpdotdev/Warp#2057]
### Describe the solution you'd like?

```text
It is recommended that warp add a function that can open warp in any folder according to the current path.thanks
```

### Is your feature request related to a problem? Please describe.

```text
It is recommended that warp add a function that can open warp in any folder according to the current path.thanks
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment]
hi @javasopp, Thanks for this feature request! Closing this in favor of [#102](https://github.com/warpdotdev/Warp/issues/102), as its a very similar request. Please +1 that request as it helps us gauge interest. We will post any updates there.
