### ISSUE TITLE
Incorrect render on Powerlevel10K theme

### ISSUE THREAD

**Issue by Simohara** [warpdotdev/Warp#2058]
### Describe the bug

It seems unable to display the work directory when using Powerlevel10K theme.

### To Reproduce

Install the theme.

### Screenshots

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/15936122/200324175-c05eb5f4-468f-415e-9dda-668d9cdc5a33.png">

### OS Version

Mac OS 12.6

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.11.01.08.03.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by Simohara** [comment]
1. yes, it works normally on iTerm and Terminal
2.  [p10k.zsh.zip](https://github.com/warpdotdev/Warp/files/9953485/p10k.zsh.zip)

**Comment by dannyneira** [comment]
Closing as duplicate #422
