### ISSUE TITLE
Regarding positioning for current block

### ISSUE THREAD

**Issue by shankarshastri** [warpdotdev/warp#206]
### Describe the solution you'd like?

```shell
Would love to have the positioning for the current block as an option, so that either the user can choose it to be top or bottom.
```

### Is your feature request related to a problem? Please describe.

```shell
I usually use a terminal with positioning mostly in the top and have a practice of keep using the `clear` command very often, so that the screen is clear and clean
```

### Additional context

<img width="1792" alt="Screenshot 2021-09-22 at 9 29 48 AM" src="https://user-images.githubusercontent.com/10391044/134281410-70045f6d-dfc9-42ab-8247-58c7408682dd.png">

**Versus** 

<img width="1792" alt="Screenshot 2021-09-22 at 9 30 13 AM" src="https://user-images.githubusercontent.com/10391044/134281440-b20d88cb-606d-4260-adf8-c2725498fe46.png">

**Comment by elviskahoro** [comment]
@shankarshastri 
There's an issue open that mostly if not completely covers this here: https://github.com/warpdotdev/warp/issues/22
It was posted kinda early 22nd so it's hard to find. But I would consider following and also elaborating on other related ideas you have concerning this on that thread instead. Consider closing this? -- to minimize duplicates

**Comment by shankarshastri** [comment]
Yes, please close it as duplicate for the same !!

**Comment by elviskahoro** [comment]
I can't close it, I'm not Warp staff or a maintainer haha. I was proposing you close it lol
