### ISSUE TITLE
Blank space on emacs theme

### ISSUE THREAD

**Issue by nemixe** [warpdotdev/Warp#2062]
### Discord username (optional)

nemixe#2822

### Describe the bug

Hi, i'm currently learning emacs on warp, it feels good but i notice there is an interface bug when i open emacs on it, there is a blank space on the right side.

### To Reproduce

- install emacs
- open emacs on warp
- apply any theme

### Expected behaviour

there is not blank space on the right terminal and theme applied to whole window successfully.

### Screenshots

<img width="1275" alt="Screenshot 2022-11-08 at 00 46 37" src="https://user-images.githubusercontent.com/33045816/200379162-2bd5ac04-eadd-4b88-b4e7-baf68f13d96f.png">

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.01.08.03.stable_00

### Additional context

the issue is gone when i resize the warp window application, but still there is weird little blank space on the right bottom corner. 
<img width="641" alt="Screenshot 2022-11-08 at 00 41 22" src="https://user-images.githubusercontent.com/33045816/200378291-d874a937-c78a-4f46-9f86-4d6f1632726e.png">

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Hi @nemixe, I'm Danny, a Support Engineer at Warp. Thanks for letting us know! We're sorry about this, this is not an ideal experience. We will post updates on this here if/when this is being worked on of it we need more information.

**Comment by dannyneira** [comment]
Closing this one in favor of
