### ISSUE TITLE
TERM_PROGRAM env not set when using ssh in WARP

### ISSUE THREAD

**Issue by brian316** [warpdotdev/Warp#2068]
### Describe the bug

I use zsh as my default shell on my machines.
I was told to disable certain features of zsh like plugins if I use warp by wrapping configs with
```
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
  ....
fi # end if [[ $TERM_PROGRAM != "WarpTerminal" ]]
```
but when I ssh into other machines with the zsh shell i have to wrap all those machines with the same code (which is unfortunate because if i enter a machine that is not mine i cant change it and it breaks warp functionality).
Even after setting that on remote machines the `$TERM_PROGRAM` env does not get set when ssh-ing into those machines! 

I feel like forcing users to do things your way vs the standard way will turn off so many people. any way to keep our configs and turn off warps features to make it work?

### To Reproduce

ssh into a machine with zsh plugins etc.

### Expected behaviour

should not give false autosuggestions and history should work

### OS Version

macos 12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.11.01.08.03.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by vorporeal** [comment]
Hey @brian316, sorry things aren't working well for you!  For the time being, you can disable Warp's SSH wrapper in Settings -> Features, which should turn off the functionality that is causing problems.

Thanks for pointing out the lack of `$TERM_PROGRAM` via SSH; we can certainly fix that.

**Comment by dannyneira** [comment]
Hi @brian316, We've fixed this issue in the most recent build. Please update Warp and confirm it's resolved/closed when you get a chance.
