### ISSUE TITLE
Input Editor: Hitting escape to focus the input box does not show the cursor bar

### ISSUE THREAD

**Issue by mskelton** [warpdotdev/warp#207]
### Describe the bug

```shell
When hitting escape to re-focus the input box after focusing a block, the flashing cursor bar does not appear.
```

### To Reproduce

Steps to reproduce:
1. Click cmd+up arrow to focus the last block
2. Click escape to focus the input box
3. Notice that the flashing cursor does not appear

### Expected behaviour

```shell
I would expect the flashing cursor to appear which would make it visually clear that I am focused in the input box.
```

### Screenshots

https://user-images.githubusercontent.com/25914066/134348091-155948ff-4ad4-4a9a-a51d-339bcb369429.mov

### Operating System

MacOS

### OS Version

11.6

**Comment by zheng** [comment]
I think that's the right behavior! We will fix this!

**Comment by elviskahoro** [comment]
This should be fixed! @mskelton reopen or comment if not!
