### ISSUE TITLE
TERM_PROGRAM is not set on the remote host

### ISSUE THREAD

**Issue by joggienl** [warpdotdev/Warp#2070]
### Discord username (optional)

jogchum#6123

### Local Shell and Version

zsh 5.8.1

### Remote Shell and Version

zsh 5.8.1

### Operating System and Version

macOS Ventura 13.0

### Warp Version

v0.2022.11.01.08.03.stable_00

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

Trying to prevent loading of non working zsh settings for warp on a remote host does not work. There is a common way to do it:

```zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# Whatever you want to disable

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi
```

But what I noticed is that when connecting to a machine with a code block like above, it does not work. The `TERM_PROGRAM` variable is not set on the remote host (probably while connecting). I tried this code snippet on the remote host, on top of my .zshrc file:

```zsh
if [[ -v TERM_PROGRAM ]]; then
  echo "TERM_PROGRAM variable exists and is set to ${TERM_PROGRAM}!"
else
  echo "TERM_PROGRAM variable does not exist"
fi
```

On connecting it prints out "TERM_PROGRAM variable does not exist".

![image](https://user-images.githubusercontent.com/1089150/200778062-121a8099-f36f-4bcb-bb95-8d29f7130198.png)

### Include shell xtrace output

If needed I would like to provide these logging through e-mail, thanks.

**Comment by joggienl** [comment]
Hey @dannyneira thanks for you kind reply, as well as on Discord!

**Comment by joggienl** [comment]
Hey @dannyneira, I just tested it on the new release and it seems to work!

I currently do not have actual config that should not work, but I tested with the snippet I shared here.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/1089150/202296403-945ae833-8820-466a-bbc1-62559c0e489b.png">

🚀

**Comment by dannyneira** [comment]
Awesome, thanks for letting us know! Closing this issue, but if any other problems with TERM_PROGRAM please reopen and let us know.
