### ISSUE TITLE
Restore previous session

### ISSUE THREAD

**Issue by endymion1818** [warpdotdev/Warp#2080]
### Describe the solution you'd like?

```text
I just accidentally closed my tab, and found I couldn't get back the previous contents of the terminal or the pane layout I'd crafted for the task I was working on.

It would be great if you had the option similar to some browsers of "restoring previous session" which could contain not only the pane layout but also the contents of each pane.
```

### Is your feature request related to a problem? Please describe.

```text
As described above, session restore would save me having to re-run my 15min+ test to get back the information I lost.
```

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Hi @endymion1818 We have a feature called Session Restoration which may help for this use case. Please take a look at our docs on it and let us know if that helps. https://docs.warp.dev/features/session-management/session-restoration

**Comment by endymion1818** [comment]
That's just the ticket, thanks! Unless you think it could be a menu item as well in case of accidental closures like mine was?
