### ISSUE TITLE
rapidly hitting alt-d crashes the terminal

### ISSUE THREAD

**Issue by ryjm** [warpdotdev/Warp#2081]
### Describe the bug

Hitting alt-d repeatedly will crash warp. This is delete forward word and is built into my muscle memory (and probably most emacsers'). 

### To Reproduce

Spam alt-d

### Expected behaviour

Doesn't crash.

### Operating System

MacOS

### OS Version

Ventura

### Shell Version

zsh 5.9 (aarch64-apple-darwin21.6.0)

### Warp Version

v0.2022.11.01.08.03.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by ryjm** [comment]
`alias testurbit="urbit -L"`                                                                                                                
highly recommend defining this so you don't boot live on accident

**Comment by dannyneira** [comment]
Hi @ryjm, I'm Danny, a Support Engineer at Warp. Thanks for letting us know! We're sorry about this, this is not an ideal experience. 
I'm working to actively reproduce this issue. Could you please help us with a video of the problem? 
Are you using any custom prompts or plugins, or just default .zshrc files?

**Comment by ryjm** [comment]
oh man yeah my zsh is so customized i'm afraid to touch it. would be nice to figure out which plugin is breaking it though. i'll try disabling one by one, might take me a bit though.

**Comment by dannyneira** [comment]
Got it, you can quickly check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv` this forces Zsh to run with zero configs.
Then open a new Tab/Window and try to reproduce the issue.

Essentially, You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# Whatever you want to disable

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```
We have more on debugging your rcfiles here: https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files

**Comment by ryjm** [comment]
perfect, thank you! i'll give it a shot and report back

**Comment by ryjm** [comment]
okay i disabled everything and it still crashes (weirdly it's when i press alt-d exactly 4 times in a row): 

https://user-images.githubusercontent.com/2065299/201182187-99ba8b4c-f582-444f-b9a5-818f9eadc145.mov

**Comment by ryjm** [comment]
seems like it's a segfault

<img width="713" alt="image" src="https://user-images.githubusercontent.com/2065299/201182652-890e7e49-4c7f-4549-b286-edcd5e3a28d2.png">

**Comment by ryjm** [comment]
just tried rebinding cut word right to another key and it doesn't crash when i use that key, but still crashes after 4 alt-d's.

**Comment by ryjm** [comment]
okay this is weird - it's a problem with using the Unicode Hex Input source (I use it so my option key doesn't input unicode characters, since i use it as alt). if i switch to the US input source it no longer crashes.


https://user-images.githubusercontent.com/2065299/201189220-e745f21d-3a6c-4342-ba7b-7b22a905ec63.mov

**Comment by ryjm** [comment]
works now! i have a knack for finding the weird stuff. thanks for the quick turnaround.

**Comment by alokedesai** [comment]
Great, thanks for confirming! I'll go ahead and close this out 🚀
