### ISSUE TITLE
IP address recognition for text-selection (double-click)

### ISSUE THREAD

**Issue by xyzzy314** [warpdotdev/Warp#2084]
### Describe the solution you'd like?

```text
Double-clicking an IPv4 address should select (such as for copying) the entire IPv4 address, not just the octet clicked.

Bonus points for getting this to work for IPv6 too.
```

### Is your feature request related to a problem? Please describe.

```text
In Terminal, if I double click an IP address, the full IP address is automatically selected.  In Warp, if I double click an IP address, only the octet I've clicked upon is selected.
```

### Additional context

I work with a lot of IP addresses, and being able to swiftly double-click, copy, paste, etc, is (unfortunately) a high-frequency task.

### How important is this feature to you?

5 (Can't work without it!)

**Comment by elviskahoro** [comment]
imo (personal opinion) the text selection behavior should be configurable. Gonna close this in favor of #659
