### ISSUE TITLE
Mouse reporting doesn't properly report right (secondary) clicks

### ISSUE THREAD

**Issue by AngerM** [warpdotdev/Warp#2085]
### Describe the bug

Mouse reporting isn't properly sending right-clicks

### To Reproduce

open neovim. Right click, or select some text and right click.

neovim config has
```
set mouse=a
if has("mouse_sgr")
  set ttymouse=sgr
else
  if !has('nvim')
    set ttymouse=xterm2
  end
end
```

### Expected behaviour

the neovim right-click menu. Example from Alacritty:
<img width="247" alt="image" src="https://user-images.githubusercontent.com/1715525/201237880-f7333c60-0b49-49ae-9da9-4d3a1c5dcb64.png">

### Operating System

MacOS

### OS Version

12.6.1

### Shell Version

fish

### Warp Version

v0.2022.11.08.08.07.stable_02

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@AngerM thanks for reporting. Will see if someone can look into this

**Comment by dannyneira** [comment]
A fix is being worked on for this. Thanks for your patience, we will post update here when complete.

**Comment by dannyneira** [comment]
hey folks, a fix has been released for this, Warp mouse reporting should now show the nvim menu on right-click.

Closing as resolved, but please let us know if any issues persist.
