### ISSUE TITLE
Support optional argument values in workflow

### ISSUE THREAD

**Issue by caipengbo** [warpdotdev/Warp#2086]
### Describe the solution you'd like?

```text
There are several configured alternative values for workflow parameters, which can be selected through the UI
```

### Is your feature request related to a problem? Please describe.

```text
There may be multiple alternative values for arguments in workflow, and it would be nice if warp could support argument value selection in workflow.
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by elviskahoro** [comment]
We should have another open issue for this. Will try to merge this with the other one if so

**Comment by dannyneira** [comment]
Closing in favor of https://github.com/warpdotdev/Warp/issues/997
