### ISSUE TITLE
Tab to accept auto complete suggestion

### ISSUE THREAD

**Issue by TylerGriffin99** [warpdotdev/Warp#2088]
### Describe the solution you'd like?

```text
Pressing TAB when in a folder should accept the current present suggestion 
Also when typing a folder name to go into I should be able to begin typing the folder name then use TAB to auto complete the folders name, then ENTER to enter into it

Currently you have the CMD + right arrow for this but is a pain when quickly navigating through folders.

The other folder suggestions that TAB currently presents should be moved to a less prime button other than TAB
```

### Additional context

Easy folder navigation is very important when selecting a terminal product. ITerm currently handles this very well but I want to move to Warp for the other features. Although core feature for me is folder name and fast command completion

### How important is this feature to you?

5 (Can't work without it!)

**Comment by IlyaCherkasov** [comment]
In my latest Warp terminal it's going through folders on tab press. There is some UI for this, so enter to select or just arrow right to apply suggestion that is transparent a bit.

**Comment by mingzaily** [comment]
I think tab completion is more consistent with using traditional tools.

**Comment by eric-mitchell** [comment]
Would also love to be able to configure this behavior. Command-right is quite awkward for me, and tab to accept autocomplete suggestion is very standard IMO.

**Comment by michaelrhanson** [comment]
Agree, I cannot learn a new gesture for autocomplete.  Tab is deeply, deeply ingrained in my muscle memory, and always, always means autocomplete in a terminal or a readline-based app.

Command-left/right arrow is more variable and has poor repeatability, but on the Mac at least it has meant "whole line cursor move" and should be aliased to the same command as Ctrl-A.  But other terminals mess with it; iTerm uses it for "change tabs" in the default configuration.

See also #2129 for additional tab complete weirdness.

**Comment by dannyneira** [comment]
Thanks for the feedback and suggestions, we are tracking this issue here: https://github.com/warpdotdev/Warp/issues/1909
Merging the comments into that issues. Please +1 that request as it helps us gauge interest. We will post any updates there.
