### ISSUE TITLE
Proxy func.

### ISSUE THREAD

**Issue by mingzaily** [warpdotdev/Warp#2089]
### Describe the solution you'd like?

```text
1. Would like a feature to support configuring a command-line proxy? Similar to the iterm2 configuration on the 'login shell', for example 'export https_proxy=http://127.0.0.1:.XXXX'
2. Can command line input be entered from the top instead of the current bottom?
```

### Is your feature request related to a problem? Please describe.

```text
No
```

### How important is this feature to you?

3

**Comment by elviskahoro** [comment]
We're tracking having input entered from the top in this issue:
#22 

Adding your feedback regarding proxies to #705
