### ISSUE TITLE
Make the text caret more visible when at the edge of the usable window area

### ISSUE THREAD

**Issue by igilham** [warpdotdev/Warp#2090]
### Describe the solution you'd like?

```text
A little padding in the main view may be sufficient to make a vertical bar caret easier to see,
but it may also work to switch up the font or rendering a bit.
```

### Is your feature request related to a problem? Please describe.

```text
When the text caret is a vertical bar and in the first column, it can be very hard to see. This is
problematic when navigating a document in vim-like editors.

Example:

- Open vim. The default caret is a block and can be seen just fine.
- Enter insert mode. The caret changes to a thin bar and is difficult to spot quickly.
```

### Additional context

Block

![Screenshot 2022-11-11 at 10 46 00](https://user-images.githubusercontent.com/541775/201324632-612b33ba-2d02-47f1-865d-600e613722ba.png)

Bar

![Screenshot 2022-11-11 at 10 46 09](https://user-images.githubusercontent.com/541775/201324658-3dac2467-7d4d-471e-859d-46f4b7bd2a29.png)

### How important is this feature to you?

4

**Comment by elviskahoro** [comment]
@igilham makes sense! thanks for opening!

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by igilham** [comment]
Looks like this has been fixed now

![Screenshot 2022-12-16 at 09 39 03](https://user-images.githubusercontent.com/541775/208069438-98bf0c9a-f9e5-4ea9-958d-dd97752c7435.png)

![Screenshot 2022-12-16 at 09 39 11](https://user-images.githubusercontent.com/541775/208069451-12d3b140-e733-4faf-acfe-0f09a382bd21.png)

**Comment by kamalkech** [comment]
how can i set this padding size ???
