### ISSUE TITLE
Freeze when use telescope/fzf search for a file with NeoVim

### ISSUE THREAD

**Issue by ligan** [warpdotdev/Warp#2091]
### Describe the bug

When I open neovim on warp and trying to do a fzf search for a file with telescope. Neovim was frozen after I type the second letter. The first letter do bring up search result though. 

### To Reproduce

install neovim
Install plugins: fzf, telescope. 
run nvim and bring up telescope for a fzf search for a file. 

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh

### Warp Version

v0.2022.11.08.08.07.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by ligan** [comment]
I think this may be because the search is too expensive and may not be a bug. However, the same search is relatively faster on iTerm2.

**Comment by dannyneira** [comment]
thanks for letting us know. FZF is on the list of incompatible tools https://docs.warp.dev/help/known-issues#list-of-incompatible-tools
