### ISSUE TITLE
How to accept only part of a completion?

### ISSUE THREAD

**Issue by AndreaPi** [warpdotdev/Warp#2092]
### Describe the bug

Sorry if this is not really a bug, but as you're not allowing to open blank issues and this is neither a feature request or an SSH issue, there wasn't really a right choice. Let me know if there are better channels for this kind of request (preferably, channels where it's easy to share pics and you can write a lot of text).

I often try to do the following:
![image](https://user-images.githubusercontent.com/8233615/201348267-94034e02-155c-46ab-80fb-d76fe797308a.png)

I start typing a command, and Warp correctly infers that I want to use `git switch`. However, I **don't** want to switch to master (that was the last switch command I used). I want to switch to another branch. Right now, if I click the right arrow, Warp will immediately complete the full command:

![image](https://user-images.githubusercontent.com/8233615/201348718-01a8bb5f-e851-4c0b-a513-963fdd6e4db3.png)

Then I have to go back one word (⌥+ ←), select `master`, delete it, and finally write `tutorial`. 

![image](https://user-images.githubusercontent.com/8233615/201351038-b351e956-bf62-42be-a4f0-8fa8f681dd3f.png)

This gets old pretty quickly. Isn't there a simpler way to achieve what I want? Would it be possible to accept only the first part of the suggestion (`git switch`) but not all of it (`git switch master`)?

### To Reproduce

1. in a git repository, start writing `git sw`
2. `git switch master` is suggested. Accept suggestion with ←
3. Go back one word (⌥+ ←)
4. Delete `master`, write the name of the branch you actually want to switch to

### OS Version

12.6

### Shell Version

bash 3.2.57

### Warp Version

v0.2022.11.08.08.07.stable_02

### Does this block you from using Warp daily?

No

**Comment by kLy** [comment]
+1 here.

It's much worse when the third part is a very long path or URL. Then there's a hug amount of selecting and deleting.

**Comment by obelixA** [comment]
+1

**Comment by 0x90pkt** [comment]
+1

**Comment by nystrom** [comment]
⌥+ → rather than → will accept one word at a time of the suggestion.
