### ISSUE TITLE
Text on auto-suggestion box being converted to icons when using NerdFonts

### ISSUE THREAD

**Issue by OneComputerGuy** [warpdotdev/Warp#2093]
### Discord username (optional)

OneComputerGuy#5692

### Describe the bug

Not sure if the issue is when the font itself or Warp but when changing the font to SpaceMono from NerdFonts some text within the auto-complete box and command entry box is changed to icons.

So far I've seen that for any word that has `fi` in it, the terminal (or font directly) changes it to a phone icon:

### To Reproduce

1. Download the SpaceMono font from nerdfonts.com
2. Open warp and change the font to SpaceMono
3. Within the terminal open the auto-complete and search for any file/folder that has fi in the name or type fi on the terminal 

### Expected behaviour

Terminal should show the word as it is instead of the icon

### Screenshots

<img width="346" alt="image" src="https://user-images.githubusercontent.com/44152511/201368092-8972a3f6-7f8d-44ae-85e9-e6f076ab7f69.png">

<img width="555" alt="image" src="https://user-images.githubusercontent.com/44152511/201370355-17c00928-7ac5-4357-86f0-cfd9806e7666.png">

### OS Version

MacOS Ventura 13.0.1 (22A400)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.08.08.07.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by OneComputerGuy** [comment]
Additional testing shows issues with Inconsolata NerdFont

Fonts that work without issue:

- Anonymice NF
- FantasqueSansMono
- Hurmit (Hermit)
- Lekton
- Monofur NF
- Terminess NF

**Comment by OneComputerGuy** [comment]
After additional testing, the issue seems to be scoped to the font itself and not Warp. Closing this since it has to be addressed by NerdFonts.

**Comment by dannyneira** [comment]
Thanks for letting us know, We're sorry this issue happend but good to know it was a problem with the font.
