### ISSUE TITLE
Not possible to sign-in forst time user

### ISSUE THREAD

**Issue by johan162** [warpdotdev/Warp#2094]
### Describe the bug

Downloaded and installed Warp but can not signup nor sign-in. Is caught in an infinite loop behind signup-provider (GitHub or Google) and trying to open the app.

### To Reproduce

Downloaded and installed Warp. 

1. Open the app and was asked to sign-up. 
2. Proceed to GitHub sign-up and authentication. 
3. When finished signing up. Clicked "Take me to Warp" in the browser 
4. The App is opened but the same "Sign up" window is displayed as in step 1 above. 
5. Repeat.

I can never break out of this. Have tried both GitHub and Google account. 

### Expected behaviour

The application is signed in and open

### Operating System

MacOS

### OS Version

12.6.1

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.11.01.08.03.stable_00

### Additional context

- Behind company proxy
- Having ZScaler as internet security application installed
- When signing in on my private laptop everything works as expected
- Does not seem possible to access any settings in the terminal before logging in (can't even check the version number)
- Have tried quitting both browser (and clearing cache) still impossible to start the terminal on my work laptop due to the loop in trying to sign in

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment]
Hey @johan162, sorry for the issues you're seeing here! OOC does manually pasting the token work for you? More instructions here: https://docs.warp.dev/help/troubleshooting-login-issues#nothing-happens-when-i-click-take-me-to-warp

**Comment by OneComputerGuy** [comment]
Try what alokedesai said first and see if you can login with the code.

If not, most of the time (speaking from experience with similar issues) the error is related to the cookies on the browser being blocked. Check if you have any adblock/cookie blocker like uBlock Origin or Privacy Badger, if so, disable them while you log in.

If you're using safari, there's an option under Settings > Privacy that disables cross-site tracking, which sometimes also blocks oAuth requests.

**Comment by johan162** [comment]
Thanks for the reply. When I took my work-laptop home and connected outside the company proxy/firewall it all worked. So, it seems to a firewall/proxy issues. Unfortunately I cannot give more details since I since I didn't have Wireshark or similar enabled. So I suggest close this as "Not Planned/Cannot reproduce".

**Comment by dannyneira** [comment]
closing as the user was able to connect outside of company firewall.
