### ISSUE TITLE
Very first start is broken when using fish

### ISSUE THREAD

**Issue by mfeif** [warpdotdev/Warp#2096]
### Describe the bug

I just installed Warp and ran it for the first time. Here is what I saw:

```
echo -e "$(cat "/Applications/Warp.app/Contents/Resources/assets/onboarding/welcome_to_warp.txt")"
fish: $(...) is not supported. In fish, please use '(cat)'.
echo -e "$(cat "/Applications/Warp.app/Contents/Resources/assets/onboarding/welcome_to_warp.txt")"
```

The script isn't compatible with fish.

So then I ran the command that it was trying to run, and get this:
```
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⡄⠀
⠀⢀⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀
⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠀
⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠋⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠁⠀⠀
⠈⠛⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀


Welcome to \033[1;34mWarp\033[00m—a blazingly fast, Rust-based terminal reimagined from the ground up to work like a modern app.

\033[1;32mBlocks\033[00m
In Warp, command input and output are grouped together into atomic units called "Blocks." The text you are reading now is part of a Block. Easily perform actions, like copy and share, via its context menu.

\033[1;32mInput Editor\033[00m
The Input Editor is a full-fledged code editor. Complete commands with <tab> completion menus. Select text and move the cursor with IDE keyboard shortcuts.
```

Clearly the escape sequences aren't working.

I know that fish support isn't 100%, though the marketing says that fish is supported. This isn't a big deal, but I don't see it in the bug reports here. It's not a strong showing for a new user when the first two things don't work ;-)

### To Reproduce

Install Warp when your login shell is fish.

### Expected behaviour

Not sure; this is my only experience with Warp.

### Operating System

MacOS

### OS Version

12.4

### Shell Version

fish, version 3.3.1

### Warp Version

v0.2022.11.01.08.03.stable_00

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Just notified the DRI for this. Thanks for reporting

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
