### ISSUE TITLE
Homebrew install on Linux

### ISSUE THREAD

**Issue by BarbzYHOOL** [warpdotdev/Warp#2097]
### Describe the solution you'd like?

```text
Is it possible to install Warp with Brew on linux? Homebrew is apparently working on linux but i haven't tried it yet
```

### How important is this feature to you?

2

**Comment by GnuoyedC** [comment]
Warp currently does not support Linux.

**Comment by dannyneira** [comment]
@BarbzYHOOL We are tracking the Linux support in this issue here: https://github.com/warpdotdev/Warp/issues/120
Please +1 that request as it helps us gauge interest. We will post any updates there.

Thanks for the assist @GnuoyedC!

**Comment by dannyneira** [comment]
closing as duplicate request for linux support

**Comment by BarbzYHOOL** [comment]
> @BarbzYHOOL We are tracking the Linux support in this issue here: #120 Please +1 that request as it helps us gauge interest. We will post any updates there.
> 
> Thanks for the assist @GnuoyedC!

can't reply to the issue but anyway it got 367 upvotes lol


i wish someone told me exactly "the homebrew installation won't work on linux" because I have tested homebrew on a test machine and it worked fine on linux, so i'm a bit confused as to why it wouldn't work
