### ISSUE TITLE
Synchronized Panes

### ISSUE THREAD

**Issue by outlawpractice** [warpdotdev/Warp#2098]
### Describe the solution you'd like?

```text
Just like tmux synchronized panes (input goes to all synced panes), but with block support, autocomplete, etc.
```

### Is your feature request related to a problem? Please describe.

```text
I use tmux on remote servers to deploy/manage multiple cloned instances on DigitalOcean.  It works normally, but I lose all the improved functionality of Warp!
```

### How important is this feature to you?

4

**Comment by elviskahoro** [comment]
Thanks for opening. We have an open issue for this, will try to get back to you soon with the issue number. It should be something along the lines of: "Broadcasting to panes"

**Comment by dannyneira** [comment]
Closing in favor of #409. Please +1 that request as it helps us gauge interest. We will post any updates there.
