### ISSUE TITLE
Limited block output size

### ISSUE THREAD

**Issue by nystrom** [warpdotdev/Warp#2099]
### Describe the solution you'd like?

```text
Blocks should display as much output as there is. Or, at least the limit should be configurable.
```

### Is your feature request related to a problem? Please describe.

```text
Blocks only display the last 10062 lines of the output. If I copy the output, only 10062 lines are copied. This is insufficient for some commands I use regularly, where I get a lot of output, then search through results. The workaround of redirecting to a file won't work easily for me either, since the command is interactive.
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by elviskahoro** [comment]
Thanks for opening. We have an open issue for this i'll try to get back to you with the issue number soon!

**Comment by dannyneira** [comment]
Closing in favor of #610 please sub to that issue to track progress
