### ISSUE TITLE
Closing tab with active process quits Warp entirely

### ISSUE THREAD

**Issue by ccpost** [warpdotdev/warp#21]
**Describe the bug**
Closing any tab with a process that's still controlling the terminal causes the entire Warp app to quit.

**To Reproduce**
1. Open a new tab
2. Run a program that keeps control of the terminal (ex: `man ls` / `vi` / etc)
3. Close the tab through either the X button or Cmd+W
4. The entire Warp app quits

**Expected behavior**
Expect all the tab's children to be terminated, but Warp to stay running.

Bonus: might be worth considering an "undo close" grace period like iTerm (https://gitlab.com/gnachman/iterm2/-/issues/2877#note_335567160), though that'd be a separate FR.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS Version: macOS 10.15.7

**Additional context**
N/A

**Comment by donaldguy** [comment]
Duplicate of #18 

Hi, Chris 👋

**Comment by ccpost** [comment]
LGTM on the 2021.07.21 release; thanks team!

(Hi Donald! 👋 )
