### ISSUE TITLE
Merge duplicate blocks

### ISSUE THREAD

**Issue by push-22** [warpdotdev/Warp#2101]
### Describe the solution you'd like?

```text
Quite often I find myself typing the same command in, say when I'm checking disk space/pinging a machine/compiling source etc, and getting the same results back

If the result is the same I can't delete the duplicate block (I would like to!), it would be nice if the command and results just merged into the previous one and that block moved down.

Thanks.
```

### How important is this feature to you?

4

**Comment by elviskahoro** [comment]
Interesting feature request. We do need to add a way to manage Block history. There's an open issue for clearing the last Block. I'll try to get back to you with the issue number of that one.

**Comment by dannyneira** [comment]
Closing this in favor of #516 Please :+1:  and subscribe to that request as it helps us gauge interest. We will post any updates there.

**Comment by dannyneira** [comment]
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.
