### ISSUE TITLE
Docker exec not autocompleting container names

### ISSUE THREAD

**Issue by ylinik-dn** [warpdotdev/Warp#2102]
### Describe the bug

I connected to a linux VM from my macbook.
Tried getting auto completion for `docker exec -it bash <start of container name><tab>`.
This didn't work.

### To Reproduce

1. Connect to a linux VM using ssh
2. Try get autocompletion for `docker exec` (container names)

### Expected behaviour

The autocompletion should show the container names

### Operating System

MacOS

### OS Version

13.0

### Shell Version

bash 5.0.17 on VM and zsh 5.8.1 on MAC

### Warp Version

v0.2022.11.08.08.07.stable_02

### Does this block you from using Warp daily?

No

**Comment by crushingCodes** [comment]
+1

I am going to wait for this feature before using warp, i get better completion with the bash autocomplete, and i lose that by using warp. I wonder if there was a workaround?

**Comment by dannyneira** [comment]
We dont fully support Warp feature, including our autocomplete, inside subshells Please sub to this issue to track and updates on this feature.#64

**Comment by dannyneira** [comment]
Sorry all but we dont fully support all Warp feature inside of subshells like docker exec ( python, and others ). Please sub to this issue here to track any updates #64

**Comment by dannyneira** [comment]
closing as duplicate.
