### ISSUE TITLE
Detach sessions (processes)

### ISSUE THREAD

**Issue by AndreaPi** [warpdotdev/Warp#2106]
### Describe the solution you'd like?

```text
I want to be able to:
1. connect to a remote server
2. detach a session (like in tmux)
3. close the Warp terminal
4. reattach the same session in another Warp terminal (window).
```

### Is your feature request related to a problem? Please describe.

```text
I'm always frustrated when my connection to the remote server goes down (this happens often for various reasons) and I have to SSh-connect to it again, losing any ongoing process in the meantime. I can fix this by launching tmux when I connect to the remote terminal with Warp, but since I like Warp's multiplexing more than tmux's, I'd rather just use Warp.
```

### How important is this feature to you?

4

**Comment by elviskahoro** [comment]
Thanks for opening. We have a GitHub discussion for remote connection management. Please check it out. Will probably merge this issue into that discussion later

**Comment by AndreaPi** [comment]
You're welcome, thanks for your reply! This is the discussion, right?

https://github.com/warpdotdev/Warp/discussions/442

**Comment by dannyneira** [comment]
Yes that's the one, please Sub and 👍 that discussion to receive updates, closing this one as duplicate.
