### ISSUE TITLE
Display Kube context in the prompt 

### ISSUE THREAD

**Issue by schabrolles** [warpdotdev/Warp#2108]
### Describe the solution you'd like?

```text
Give the user the possibility to activate the current kube_context in the prompt. (like git)
It will allow to know exactly on which Kubernetes cluster we are connected before sending a command.
```

### How important is this feature to you?

4

**Comment by tdgeery** [comment]
You can try using https://github.com/justjanne/powerline-go and the `kube` module

**Comment by tdgeery** [comment]
And setting "Honor user's custom prompt" enabled

**Comment by schabrolles** [comment]
Ok but it won't work when I conne t to a remote host with ssh (bastion node)

**Comment by dannyneira** [comment]
I recommend you try the https://www.starship.rs prompt as it supports showing the context in the prompt as well and is supported in Warp.
https://docs.warp.dev/features/prompt
https://starship.rs/config/#kubernetes

please let us know if this helps with your use case.

**Comment by schabrolles** [comment]
Well this is what I setup, it works for me when I stay on my local laptop.

One feature I like with warp is the ssh wrapper ... the original prompt is replicated directly on the target ssh server with for the moment only "directories" and git status ... 

For my daily activity I need to connect to some of my cluster from a "ssh bastion" node. I can't really setup my PROMPT PS1 as I want from this remote system or setup starship. That's why I as to have the possibility to get kubecontext from native warp prompt.

Another annoying thing is the limited current kubectl completion and the lack of "oc" (Openshift client) completion...
having a way to force completion from the OS (shift-TAB for example) could be good

**Comment by chrispoupart** [comment]
While I can leverage starship to display kubernetes details, I have to agree that the lack of "oc" auto-completion (even when it's part of my default shell) has made it nearly impossible to use Warp as my daily console. Even if it was just aliased to what is currently supported for "kubectl", it would make a world of difference in usability.

**Comment by dannyneira** [comment]
A user has mentioned that the kube-ps1 plugin for oh-my-zsh which would normally show `kubectl ` context isn't working as a Warp custom prompt.

**Comment by skeenan947** [comment]
actually, that user was me, and it was simply because I didn't have the honor the user's custom prompt setting enabled.  so, kube-ps1 works.  I'm using it with bullettrain in zsh

**Comment by locustbaby** [comment]
I also think it would be great for WARP to be supported so that I don't have to configure so many shells

**Comment by dannyneira** [comment]
Thanks for submitting this @schabrolles 

We'll be closing this issue in favor of #2055 which is also asking for kube context/completions. It's something we're aware of and will be prioritizing in upcoming release ( no eta ).

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Hi Folks, We've added the [Kube context chip to Warps prompt](https://docs.warp.dev/appearance/prompt#kubernetes) to the latest version of Warp!
 
![CleanShot 2023-12-01 at 08 57 25](https://github.com/warpdotdev/Warp/assets/16809145/c45f4573-abc0-4579-a33c-0f9f70b18a26)

Closing as completed, but please let us know of any issues.

**Comment by dannyneira** [comment]
Reopening to address feedback regarding the support for `KUBECONFIG` env variable as well as aliases for kube context commands (`kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubent|kubecolor|cmctl|sparkctl|etcd|fubectl`)

**Comment by dannyneira** [comment]
Closing as resolved as `KUBECONFIG` is now referenced by Warps Kubernetes prompt chip. https://docs.warp.dev/appearance/prompt#kubernetes

**Comment by gr00by** [comment]
Hi @dannyneira, is there a way to extend the default list of commands that trigger the kube context chip in Warp? I use aliases for some of these commands, but the chip doesn’t appear when using them. I couldn’t find a way to make it work while using Warp’s default prompt.

Is there a workaround for this, or any plans to support aliases in the future?

Thanks!
