### ISSUE TITLE
Support opening new tabs from the command line

### ISSUE THREAD

**Issue by frankie-swrve** [warpdotdev/Warp#2110]
### Describe the solution you'd like?

```text
Currently I have an allias that will run several commands each in a new tab in iTerm for easier management

e.g.: `alias runall="ttab -G runac && ttab -G runamp && ttab -G runch && ttab -G rundb && ttab -G rundc && ttab -G runui && cdui"`

Running this command opens the MacOS terminal, and opens new tabs in that instead of warp
```

### Additional context

ttab is an external library, but it would be great if this was something native in warp when just running some command will open a new tab and stay going

### How important is this feature to you?

4

**Comment by elviskahoro** [comment]
Thanks for opening. We have a GitHub discussion on this, should be be something like: General Scriptability.

I'll probably merge this into that later, as this functionality would likely be in the MVP of that project.

The closest thing we have now is launch configurations:
https://docs.warp.dev/features/sessions/launch-configurations

**Comment by dannyneira** [comment]
Closing as duplicate #612
