### ISSUE TITLE
 Pre-configured layouts of windows and panes

### ISSUE THREAD

**Issue by yerrysherry** [warpdotdev/Warp#2112]
### Describe the solution you'd like?

```text
In Iterm2, I use itermocil (https://github.com/TomAnthony/itermocil). With this command, I split my terminal in multiple windows and execute commands in it. Very easy to start a project. Is this also possible with wrap?
```

### How important is this feature to you?

2

**Comment by dannyneira** [comment]
Hi @yerrysherry, I'm Danny, a Support Engineer at Warp. Thanks for this feature request!

We have a feature called Launch Configurations that can help with this use case ( if so, please close this request ). See more on this feature here: https://docs.warp.dev/features/session-management/launch-configurations

If this doesn't meet your use case. Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by yerrysherry** [comment]
Perfect
