### ISSUE TITLE
Directory suggestions not working when there's a variable in the path.

### ISSUE THREAD

**Issue by bencolder** [warpdotdev/Warp#2123]
### Describe the bug

If you go to a path with a variable, for example, $d/mee... where $d is a variable. There would be no suggestions for available directories even if there's a directory name matching mee 

### To Reproduce

See above

### OS Version

11.4

### Shell Version

zsh

### Warp Version

55_stable_01

### Does this block you from using Warp daily?

Yes

**Comment by nichoj10** [comment]
Thanks for filing this! As of now, we don't support environment variables in completions. We'll post here with any updates on this work.

Here's the full documentation on completions: https://docs.warp.dev/features/completions

**Comment by dannyneira** [comment]
Hi @bencolder We are tracking this in the greater discussion here: #652
