### ISSUE TITLE
disabling autocomplete for quotes and parentheses does not disable the feature

### ISSUE THREAD

**Issue by skateordev** [warpdotdev/Warp#2124]
### Discord username (optional)

spicyfknrob#9252

### Describe the bug

The setting under Features to enable "Autocomplete quotes, parentheses and brackets" does not turn off. This feature was working (could be disabled) up until a few builds ago (though I failed to note the working version)

### To Reproduce

1. Go to Settings > Features
2. Disable the setting "Autocomplete quotes, parentheses and brackets"
3. Close settings
4. Type `"` in the prompt
5. Observe that 2 `"` characters are inserted with the cursor in-between

### Expected behaviour

With the setting disabled, typing `"` only inserts a single `"`. Same for `(` and `[`, etc.

### Screenshots

![Screenshot 2022-11-15 at 3 04 17 PM](https://user-images.githubusercontent.com/16905960/202043626-0dbdd0e8-bd02-41be-a3f6-c3dd0dbd4005.png)

### Operating System

MacOS

### OS Version

12.6.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@skateordev thanks for opening. I was able to repro!

**Comment by vorporeal** [comment]
Hey, sorry about the regression here!  I've identified the issue on our end and have a fix out for review; should go live in the first release of the new year. :)

**Comment by skateordev** [comment]
@vorporeal great news! thanks for the update
