### ISSUE TITLE
Arrow up doesn't show command which was halted with CTRL+C

### ISSUE THREAD

**Issue by stavell** [warpdotdev/Warp#2125]
### Describe the bug

Arrow up doesn't show command which was halted with CTRL+C

### To Reproduce

ping 1.1.1.1
hit CTRL+C
hit ARROW_UP 

### Expected behaviour

Arrow up should show the previously executed command no matter it was terminated with CTRL+C

### Screenshots

https://youtu.be/dEsEXKfLRq0

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment]
Hey @stavell, thanks for filing! Do you have the `histignorespace` setting in ZSH enabled by chance? To check, you can run `setopt` and check the output.

Additionally, it seems like there's an extra space in the buffer after the command executes. If you remove that space before executing the command, does this still repro?

**Comment by elviskahoro** [comment]
@stavell we don't have proper support for your custom prompt. this results in a space being prefixed in your input editor, which triggers histignorespace.

Check out this section of the docs, it explains how you can disable your prompt and sections of your RC files just for Warp:
https://docs.warp.dev/features/prompt#powerlevel10k-p10k
