### ISSUE TITLE
Honor user's custom prompt (PS1) stopped working after switching from bigsur to monterey (bash custom prompt)

### ISSUE THREAD

**Issue by shoguevara** [warpdotdev/Warp#2128]
### Discord username (optional)

shoguevara#7078

### Describe the bug

Using some color customization in .bash_profile
`export PS1="\[\e[01;33m\]\u\[\e[0m\]\[\e[00;37m\]@\[\e[0m\]\[\e[01;36m\]\h\[\e[0m\]\[\e[00;37m\] \t \[\e[0m\]\[\e[01;35m\]\w\[\e[0m\]\[\e[01;37m\] > \[\e[0m\]"`

While using the same customization while my mac was on BigSur and switching "Honor user's custom prompt (PS1)" radio on had achieved what I needed, but lately I had the OS reinstalled with Monterey, and when I'm switching the same button, I'm getting an empty prompt. 

Don't really know what diagnostic data to attach here to help with troubleshooting. Any suggestions?

### To Reproduce

Monterey clean install, install homebrew, install warp with homebrew. 
Update Warp with biult in updater.
Switch to bash chsh -s /bin/bash 

### Expected behaviour

Warp would show colored bash command prompt

### Screenshots

<img width="513" alt="Screen Shot 2022-11-16 at 13 35 55" src="https://user-images.githubusercontent.com/7438784/202157948-0ecc7699-c311-4765-9d9f-ad91d5915fcf.png">
<img width="510" alt="Screen Shot 2022-11-16 at 13 35 05" src="https://user-images.githubusercontent.com/7438784/202157958-8c46e9c7-a019-4353-97a3-86b9bfc273f5.png">
<img width="572" alt="Screen Shot 2022-11-16 at 13 35 25" src="https://user-images.githubusercontent.com/7438784/202157967-19490e04-f3a0-4c62-9a98-246dcb111910.png">

### Operating System

MacOS

### OS Version

12.6.1

### Shell Version

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Will try to repro this and get back to you!

**Comment by devilgate** [comment]
I have the same problem. No matter how simple I make PS1, if I set "Honor user's custom prompt" on, it shows nothing.

I'm on Ventura, 13.0.1. with Warp v0.2002.11.14.14.55.stable_01 (and I can't copy from your About screen, unlike _every other Mac app_!)

**Comment by vorporeal** [comment]
Hey all, this seems to be due to the fact that the bash functionality we're using to evaluate the prompt configuration (`${PS1@P}`) isn't supported before bash 4.4.  I've raised this internally and we'll see about fixing things for older bash versions.

In the meantime, one option would be installing a newer version of bash via homebrew (`brew install bash`; current version there is 5.2.9) and using that as your shell.

Sorry about this!

**Comment by shoguevara** [comment]
Upgrading bash doesn't seem to be such a bad thing to do. Thanks!

**Comment by grabus** [comment]
@vorporeal thanks! update bash helped.
would be nice to see it in "known issues".

**Comment by ajacocks** [comment]
I'm having issues with $PS1 being included in the text that warp things the user has typed. This happens with Mac OS' built-in bash and with homebrew bash, and I have "honor custom prompts" turned on.

![247F165E-D794-407C-8EE7-476CEBE7966E](https://user-images.githubusercontent.com/22501234/207687972-c732cfc0-4935-4cdf-9726-ecfd9673b529.jpeg)

**Comment by vorporeal** [comment]
@ajacocks What are you using for your prompt?

**Comment by dannyneira** [comment]
Hey Folks, this fix is out on today's release v0.2023.02.28.08.03.stable_01.

Closing as completed but please let us know if the issue persists.
