### ISSUE TITLE
`clear` in a chain of shell commands renders output offscreen to the top

### ISSUE THREAD

**Issue by cruisen** [warpdotdev/Warp#2130]
### `clear` in a chain of shell commands 

- example ```clear ; date ```
- renders output offscreen to the top
- is reproducible in all windows sizes
- is reproducible with different font sizes

### To Reproduce

1. open warp
2. send ```clear ; date ```

### Expected behaviour

Rendering, if 
```clear```
and
``` date```
were executed one after each other, but in one warp **block**
However as the topmost, but VISIBLE block.

### Screenshots

<img width="516" alt="Screenshot 2022-11-16 at 13 06 19" src="https://user-images.githubusercontent.com/12435251/202176677-2e2c1259-e0cc-408b-8b05-ea3d86ba6d5e.png">
<img width="670" alt="Screenshot 2022-11-16 at 13 06 10" src="https://user-images.githubusercontent.com/12435251/202176681-b2b76a8a-6143-42f7-9a62-2496bd2d54d0.png">

### Operating System

MacOS

### OS Version

10.14.5

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin18.6.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Additional context

Thank you for WARP, 

I will continue to try it out, plan to exchange it for iTerm.

Nikolai

### Does this block you from using Warp daily?

Yes

**Comment by elviskahoro** [comment]
Thanks for opening. Will let you know once we're able to look into this.

**Comment by dannyneira** [comment]
As a workaround please just try using clear, then run your desired command, So sorry about this issue.

**Comment by dannyneira** [comment]
So this is a known issue, we have a feature request to decouple clear from other run commands, as with other terminals. You can track that request here: https://github.com/warpdotdev/Warp/issues/2382

We'll post updates on that thread.

Closing as duplicate request/issue.
