### ISSUE TITLE
Paste with mouse middle button

### ISSUE THREAD

**Issue by garbigaus** [warpdotdev/Warp#2132]
### Describe the solution you'd like?

```text
I'd like to use the mouse middle button to paste texts in the terminal.
```

### Is your feature request related to a problem? Please describe.

```text
I'm used to select some text in the terminal and paste using the mouse middle button without using the keyboard.
Paste any text that already in the clipboard from another location it is a possibility too.
```

### How important is this feature to you?

3

**Comment by elviskahoro** [comment]
I think we're tracking this in another issue. Will try to follow up with the issue number soon.

**Comment by joey-squid** [comment]
#416

**Comment by garbigaus** [comment]
Thanks guys, I'll close the issue.
