### ISSUE TITLE
Issue with returning to k9s after k9s opens vim

### ISSUE THREAD

**Issue by tommysolsen** [warpdotdev/Warp#2133]
### Describe the bug

k9s is a terminal application for managing Kubernetes. One of the features of it is to press e to edit a resource in your cluster. This opens Vim, where you can edit the file, save and close vim to apply changes.

Returning to k9s after editing a resource with vim returns you to a blank screen. It is not possible to interact with the app.
It is not possible to interact with the app such as performing a quit command in order to quit the application, so there is something more than just a rendering issue here.

### To Reproduce

1. Open `k9s`
2. Navigate to an editable resource and press `e`
3. Exit out of vim using `:q!`
4. You should now have a broken view.

### Expected behaviour

The k9s terminal ui.

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.11.14.14.55.stable_01

### Additional context

Opening vim to edit resources is a `kubectl` functionality. Im not sure if k9s uses kubectl to do this or not. But it might be related

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
Thanks tommy. Will circle back here once we have updates on progress.

**Comment by lprouza** [comment]
I also have this problem.

**Comment by AndrzejOlender** [comment]
Me too

**Comment by dannyneira** [comment]
Closing as duplicate, please check this issue for updates > #833

**Comment by dannyneira** [comment]
We recently made performance/compatibility updates to alt-screen apps like emacs, please let us know if you're still seeing the issues with the latest version of Warp.

**Comment by tommysolsen** [comment]
Hey Danny.

Yea, this issue seems to be resolved now. I've gotten intermittent session halts when using vim/k9s, but I can't replicate it. Since I updated to version `2022-12-13.08.04.stable_1` I haven't encountered this issue at all.

Thanks!
