### ISSUE TITLE
No title bar option (frameless) like iTerm2

### ISSUE THREAD

**Issue by albert-ying** [warpdotdev/Warp#2139]
### Describe the solution you'd like?

```text
The iTerm2 allows the option with the title bar removed. Is it possible for Warp?
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment]
Thanks for this feature request! We are tracking one for "Zen mode or No tab bar" here: #1009
Please +1 that request as it helps us gauge interest. We will post any updates there. Closing this one as a duplicate.

**Comment by adoolaard** [comment]
Weird that no-one has upvoted this. Definitely a +1 here.
