### ISSUE TITLE
DUP: Duplicate of #031 - Table display / tabulated output

### ISSUE THREAD

**Issue by japsu** [warpdotdev/warp#214]
### Describe the solution you'd like?

Please add support for co-operating command line programs to show output as a two-way scrollable table.

Use cases that come to mind that would benefit from this:

1. Relational database clients such as `psql` (able to configure output separators in `.psqlrc`)
2. `numpy`, `pandas` and other Python libraries working with 2D arrays when used with the REPL (conforming output could probably be implemented via a Python module, need not be in numpy/pandas core; or leverage existing support designed for Jupyter Notebook etc. GUI tools)

**Comment by zheng** [comment]
Nice! We actually have some mocks for this, please follow #31!

**Comment by elviskahoro** [comment]
Linking:
- #31

**Comment by elviskahoro** [comment]
Moved to github discussion at @japsu

**Comment by elviskahoro** [comment]
https://github.com/warpdotdev/warp/discussions/500
