### ISSUE TITLE
full width history search window

### ISSUE THREAD

**Issue by jkhales** [warpdotdev/Warp#2140]
### Describe the solution you'd like?

```text
When searching command history, I would like it to be screen width so I can see the whole command.
```

### How important is this feature to you?

3

**Comment by elviskahoro** [comment]
Thanks @jkhales I think we have an open issue for this. will try to merge it with the primary one

**Comment by dannyneira** [comment]
Thanks for this feature request! We have an issue for the same here: #1405
Please +1 that request as it helps us gauge interest. We will post any updates there. Closing this one as a duplicate.
