### ISSUE TITLE
when there is only one tab, hide it

### ISSUE THREAD

**Issue by rickmarry** [warpdotdev/Warp#2141]
### Describe the solution you'd like?

As a tmux user, I very rarely have a need for tabs in a terminal window.  It would be great if we could hide the tab bar completely when there is only one of them.  For some reason it bothers me most when warp is in full screen mode.  Once we have more than one tab, it makes sense to show it

### How important is this feature to you?

4

**Comment by dannyneira** [comment]
Thanks for this feature request! We are actually tracking a similar one here: #2178

I'll merge this request into that one, but please +1 that request as it helps us gauge interest. We will post any updates there.

**Comment by dannyneira** [comment]
Thanks for this feature request! We have a duplicate one here: #1009
Please +1 that request as it helps us gauge interest. We will post any updates there.
