### ISSUE TITLE
Kbrd Shortcuts Activate Next/Previous Tab not working as expected when reassigned

### ISSUE THREAD

**Issue by ghstridr** [warpdotdev/Warp#2143]
### Describe the bug

When reassigning the Activate Next/Previous Tab shortcuts, they do not operate as expected.
When setting cmd- --> to Activate Next Tab or cmd- <-- to Activate Previous Tab, they are not recognized unless I click on one of the previous outputs above the current prompt. Then I can use one of the shortcuts, but on the tab that is switched to you are stuck back into the prompt there and have to click on previous output there to activate the shortcuts again.

### To Reproduce

1. Open Preferences
2. Select Keyboard shortcuts
3. Type 'tab' in search
4. Reassign Activate Next Tab to cmd- --> and save
5. Reassign Activate Previous Tab to cmd- <-- and save
6. Close preferences.
7. Click near prompt (usually are there by default when leaving preferences)
8. Attempt to switch tabs with new shortcuts and fail
9. Click in prior output above current prompt
10. Attempt to switch tabs and success
11. Notice that you are in next tab and that prompt line is selected or active (this is probably default and I would think expected).
12. Try switching tab again and fail
13. Click in prior output of current tab
14. Try switching tab again and success

### Expected behaviour

After reassigning shortcuts, they should work no matter what part of a tab is currently active. You should be able to switch tabs with those shortcuts at any time that contextually makes sense to apply to.

### Operating System

MacOS

### OS Version

12.6.1 Intel

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Warp Version

v0.2022.11.14.15.stable_01

### Additional context

BTW, the default shortcuts for this do stay active instead of being directly over-ridden. Most other software, when a shortcut/key-combo is changed, it overrides the default completely. The default shouldn't be active any longer, though there may be some argument for keeping this behavior. I feel that if you reassign a shortcut, you are doing so for a reason and the defaults should be unassigned as you might like to use them for something else.

### Does this block you from using Warp daily?

Yes

**Comment by szgupta** [comment]
Hey @ghstridr, for `Activate Next Tab`, can you ensure that there aren't any conflicting keybindings with `cmd - ->`? The default keybinding that will conflict with this is `End` which moves your cursor to the end of the buffer in the input editor. This might be why you're noticing that the new keybinding doesn't work when the input editor is focused. Similarly, can you ensure that there aren't any conflicting keybindings with `Activate Previous Tab`?

**Comment by ghstridr** [comment]
Yes, there were conflicting shortcuts. I will look to find something
comfortable for me to use that doesn't conflict with something else.
I noticed that there is no option to clear a binding so you can use that
binding somewhere else.
<https://about.me/michael.gracy?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>
Michael Gracy
about.me/michael.gracy
<https://about.me/michael.gracy?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>

**Comment by ffactory-ofcl** [comment]
I don't have this issue. I have set prev. tab to `Cmd`+`Opt`+`←` and it works fine wherever my cursor / focus is.

**Comment by szgupta** [comment]
@ffactory-ofcl that makes sense! That keybinding likely doesn't conflict with others!

**Comment by szgupta** [comment]
I'll close this out for now -- please re-open if you have any more questions/concerns

**Comment by jkoopmann** [comment]
Please repopen. I have a very similar problem.

In my case: Sometimes it shows me a keybinding conflict but I was unable to ever find the conflicting one. If I rebind it to something different (non conflicting) it still only works sometimes and most of the times only one tab (I hit the combo three times and expect to go three tabs to the right but only go one right).
