### ISSUE TITLE
Networking Features

### ISSUE THREAD

**Issue by brian316** [warpdotdev/Warp#2144]
### Describe the solution you'd like?

```text
would be nice to have something like https://www.termius.com/ where you can more easily manage connections and sessions.
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by elviskahoro** [comment]
Thanks for submitting. We're tracking this in a GitHub discussion called Remote Connection Management. Will try to merge this into that discussion at some point in the future

**Comment by dannyneira** [comment]
Thanks for this feature request! 
We are merging this into #442 
Please +1 that request as it helps us gauge interest. We will post any updates there.
