### ISSUE TITLE
search the local Github repository with fuzzy find and cd

### ISSUE THREAD

**Issue by ya2s** [warpdotdev/Warp#2147]
### Describe the solution you'd like?

Now I'm using [ghq](https://github.com/x-motemen/ghq) in another terminal to download the github repository.
Search and cd the downloaded repository using fzf and tmux

<img width="1232" alt="CleanShot 2022-11-17 at 10 52 20@2x" src="https://user-images.githubusercontent.com/42740055/202334558-559ae39e-4147-4c7d-8f21-2174ec0c39e5.png">

Since fzf seems to be incompatible, is it possible to achieve these behaviors now with a different approach?

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment]
Thanks for this feature request!  Consolidating into #1647. 
Please +1 that request as it helps us gauge interest. We will post any updates there on fuzzy find compatibility.

**Comment by yamatsum** [comment]
@elviskahoro @dannyneira 
I'm looking forward to the follow -up report.
Many people will change the terminal by introducing this function
