### ISSUE TITLE
google gcp centos7 ssh connection error

### ISSUE THREAD

**Issue by hwanghyeonjun98** [warpdotdev/Warp#2149]
### Local Shell and Version

zsh 5.8.1

### Remote Shell and Version

zsh 5.8.1

### Operating System and Version

13.0.1(22A400)

### Warp Version

v0.2022.11.14.14.55.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [ ] Yes

### Screenshots

<img width="398" alt="image" src="https://user-images.githubusercontent.com/66707120/202338306-acfc5f51-2402-4cef-8be3-03e89860ba01.png">

### Include shell xtrace output

-

**Comment by elviskahoro** [comment]
@hwanghyeonjun98 thanks for opening. We have an engineer investigating how we can replace with sed, tr, and od with some other tools that are more widely available across linux distributions

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
