### ISSUE TITLE
SSH: Unable to clear terminal on Debian 10

### ISSUE THREAD

**Issue by joeydotdev** [warpdotdev/Warp#215]
### Describe the bug

```shell
`clear` does clear the terminal on Debian 10 boxes
```

### To Reproduce

Steps to reproduce:
1. ssh into debian box
2. run `clear`

### Expected behaviour

```shell
Expected to have terminal cleared
```

### Screenshots

![image](https://user-images.githubusercontent.com/9088799/134546130-3b76d3f0-f9d3-4966-b44e-1947d3b49115.png)

**Comment by zheng** [comment]
Thanks for the report! Agree it should work.

**Comment by elviskahoro** [comment]
@joeydotdev 
Subscribe to (this is where we'll share updates):
- #578

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and provides an easy way for people to get progress updates. As they'll only need to subscribe (GitHub watch) a single issue versus.
