### ISSUE TITLE
Background process outputs

### ISSUE THREAD

**Issue by daiyoba** [warpdotdev/Warp#2150]
### Describe the bug

The process running in background (in my case, by ending with & when exe or CTRL-Z then bg to background in a ZSH), the output of it when still running, will be inserted in the beginning of my current "editing line". This makes future shell commands not feasible.

### To Reproduce

run anything in background with a lot of outputs and spawn a long time (e.g. "du / &"), then continue doing something else.

### OS Version

13.0

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment]
@daiyoba Thanks for filling! This is a KI with how our "blocks" feature works--closing this out in favor or https://github.com/warpdotdev/Warp/issues/1387.

We do plan on fixing this, but unfortunately I can't give a concrete timeline given the eng lift to fix this is very high
