### ISSUE TITLE
zsh:14: command not found: xxd

### ISSUE THREAD

**Issue by krolingo** [warpdotdev/Warp#2152]
### Describe the bug

login into a Manila FreeBSD install yield error: zsh:14: command not found: xxd

### To Reproduce

ssh to a fresh install of freebsd 13.1

### Expected behaviour

to work normal

### Operating System

MacOS

### OS Version

12.6.1

### Shell Version

zsh 5.9 (amd64-portbld-freebsd13.1)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment]
@krolingo Thanks for filing! We are actively prioritizing fixing this. In the meantime, you can disable the SSH wrapper in settings or start `ssh` via `command ssh` instead to still access the box in Warp.

See  https://github.com/warpdotdev/Warp/issues/1218 where we are tracking this more closely
