### ISSUE TITLE
UIUX: When resizing the app in empty state, three dots menu for hiding shortcut screen goes off screen

### ISSUE THREAD

**Issue by shankarshastri** [warpdotdev/warp#216]
### Describe the bug

```shell
On minimize, Hide shortcuts are not visible
```

### To Reproduce

Steps to reproduce:
1. Open warp, and change the size of the application.

### Screenshots

<img width="1792" alt="Screenshot 2021-09-23 at 9 59 34 PM" src="https://user-images.githubusercontent.com/10391044/134547450-d837abc2-1ed0-42f9-83e3-f91e30427646.png">
<img width="1792" alt="Screenshot 2021-09-23 at 10 01 59 PM" src="https://user-images.githubusercontent.com/10391044/134547546-e47e52a2-a6d3-4bf3-ab0b-57bb7db39f2d.png">

### Operating System

MacOS

### OS Version

11.5.2

**Comment by elviskahoro** [comment]
I think this has been fixed. @shankarshastri can you reopen or comment if not
