### ISSUE TITLE
Default working directory

### ISSUE THREAD

**Issue by bertheyman** [warpdotdev/Warp#2161]
### Describe the solution you'd like?

```text
Coming from iTerm2, I'm used to setting a default working directory.
Is this currently possible in Warp? If not, I'd be a great fan of such a feature.
In the meanwhile, what would be the best way to go about it?
```

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

The closest feature we have for this is [Launch Configurations](https://docs.warp.dev/features/sessions/launch-configurations), You can set up a variety of configurations of Windows/Tabs/Panes set to specific CWDs and even run commands on startup of the configs.

**Comment by bertheyman** [comment]
Thank you! I'll keep this open for now, and keep track of updates.

**Comment by esycat** [comment]
Launch Configurations + #2166 and/or #2490 would provide the desired functionality, I believe.

**Comment by dannyneira** [comment]
Closing this one in favor of the duplicate issue https://github.com/warpdotdev/Warp/issues/105

Please sub and follow the progress on that issue and 👍 to help us gauge interest in that feature.

**Comment by philfreshman** [comment]
Issue closed, but I can't see an option set up a possible solution for this with the https://github.com/warpdotdev/Warp/issues/105 feature...

I am really interrested in opening a launch config right in the current window!
