### ISSUE TITLE
Zoom in further

### ISSUE THREAD

**Issue by shankarshastri** [warpdotdev/Warp#217]
### Describe the bug

```shell
Currently, I can't zoom beyond a certain limit.
```

### To Reproduce

Steps to reproduce:
1. Open Warp, and press `Cmd + plus` for zooming in.

### Expected behaviour

```shell
Zooming more would really be good.
```

### Operating System

MacOS

### OS Version

11.5.2

**Comment by zheng** [comment]
Hmm i think we intentionally capped this at some point. Could you elaborate on your use case?

**Comment by shankarshastri** [comment]
In general felt, that Warp could have supported zoom functionality very similar to how terminal supports.

**Comment by dannyneira** [comment]
Warp now supports increase and decrease of the font size with `CMD-=` and `CMD--`, and reset the font with `CMD-0`.

See more on info here: https://docs.warp.dev/appearance/text-fonts
Closing as complete.
