### ISSUE TITLE
Zoom triggers N+1 times sometimes

### ISSUE THREAD

**Issue by xorik** [warpdotdev/Warp#2174]
### Describe the bug

In some cases, zoom hotkeys is triggered one more time. It happened for some commands e.g. any of those:
```
sleep 100500
read test
php -a
tail -f /some/file
```

### To Reproduce

- Run any of those commands:
```
sleep 100500
read test
php -a
tail -f /some/file
```

- Press cmd+shift+"+" or cmd+shift+"-" one or more times
- Press any key e.g. spacebar
- Zoom in/out triggered N+1 times

### Expected behaviour

Zoom in/out triggered N times

### Screenshots

When I press space, it zooms one more time:
https://user-images.githubusercontent.com/347044/202675678-213bb235-0034-43a7-9e29-59c8d7926a9b.mov

### OS Version

13.0

### Shell Version

3.2.57

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
I was able to repro this thanks for opening! @xorik

**Comment by dannyneira** [comment]
We will post updates here. Thanks for your patience!

**Comment by elviskahoro** [comment]
This should be fixed, if not it'll be out next week.
