### ISSUE TITLE
ptPython functional keys not working

### ISSUE THREAD

**Issue by PushUpek** [warpdotdev/Warp#2175]
### Describe the bug

In ptPython (https://github.com/prompt-toolkit/ptpython) functional keys not working.

### To Reproduce

run ptPython and push F3

### Expected behaviour

Functional keys working. 

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

fish, version 3.5.1

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
@PushUpek We might be tracking this in another issue, if so I'll try to merge them. We have gotten reports of key sequences not being passed e.g. with the ruby repl, etc. Will update u when there's more info.

**Comment by dannyneira** [comment]
Hi @PushUpek sorry about this issue.
Closing in favor of #64 
Please sub to that issue for tracking on subshell support.
