### ISSUE TITLE
Simplified appearance with a single tab

### ISSUE THREAD

**Issue by pavelmacek** [warpdotdev/Warp#2178]
### Describe the solution you'd like?

Warp window can be simpler without a visible tab bar when only one tab is open. Fewer distractions and visual noise when not necessary. (see attached screenshot)

### Is your feature request related to a problem? Please describe.

I personally use Warp often with just a single tab, and the visible tab bar at the top is distracting and isn't needed in that case. The tab bar is great for affordability, and it's clear I can have more tabs, but that isn't so useful once I know about it.

### Additional context

<img width="706" alt="image" src="https://user-images.githubusercontent.com/61699/202717405-32cb86f1-0a48-4e94-b2b4-003118a81604.png">

### How important is this feature to you?

1 (Not too important)

**Comment by dannyneira** [comment]
Thanks for this feature request! We already have existing feature request to track this "Zen mode" here: #1984 

Please +1 that request as it helps us gauge interest. We will post any updates there. Closing this one as a duplicate.
