### ISSUE TITLE
Tab completions do not work after escaped spaces or with quotes

### ISSUE THREAD

**Issue by 0x90pkt** [warpdotdev/Warp#2183]
### Describe the bug

When specifying a path that contains spaces, tab completion will not work after escaping the spaces in path. This is not avoidable by using quotes as tab completion does not work inside single or double quotes.

### To Reproduce

When attempting to tab complete a path such as while changing directories `cd /foo/example\ directory/bar` the completions will stop at `cd /foo/example\ directory/` and will not allow further recursion with completions.

Trying to work around this utilizing quotes, tab completion does not work at all inside the quotations (both single and double).

### Expected behaviour

Tab completion through multiple layers of recursion regardless of escaped spaces in path or quoted path.

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
I think someone on the team was investigating this. will try to get back to you with more info around the status

**Comment by dannyneira** [comment]
The duplicate issue is here: https://github.com/warpdotdev/Warp/issues/669
please sub to the other issue to track the status of this fix

**Comment by vysecurity** [comment]
I also have this issue.
