### ISSUE TITLE
Customize color of directory links

### ISSUE THREAD

**Issue by maxpetretta** [warpdotdev/Warp#2186]
### Describe the solution you'd like?

```text
Custom controls over directory link and prompt command colors
```

### Additional context

Hello!  Tried out Warp recently, and I could not figure out a way to customize the color of directory links shown in the terminal.  I would expect that something seen so often would use a chosen theme color (see below example vs iTerm), but that doesn't appear to be the case.

![warp_comparison](https://user-images.githubusercontent.com/19291506/202832811-3f860e35-a0ee-45d4-98d4-57f32fac1ab6.png)

### How important is this feature to you?

3

**Comment by maxpetretta** [comment]
I got it, my bad 😅

**Comment by dannyneira** [comment]
Cool thanks for letting us know!

**Comment by rive-n** [comment]
Is there any way to configure that? Dirs/files are just grey..
