### ISSUE TITLE
Drag the tabs to change order

### ISSUE THREAD

**Issue by r1p71d3** [warpdotdev/Warp#2188]
### Describe the solution you'd like?

```text
The ability to drag the tabs (like in Chrome) to change their order in the tab bar (currently have to right-click on each tab and choose "move left/right"). Can also add a little margin at the top of the window so that the whole window can be dragged around the screen (again, see how it's implemented in Chrome).
```

### How important is this feature to you?

3

**Comment by elviskahoro** [comment]
@r1p71d3 there should be an already open issue for this. will try to merge this into the other one if so. thanks for requesting. we have a prototype of this internally but it's still far from polished.

the GUI framework was built in house and so this kind of functionality had to be built from scratch, hence the delay!

**Comment by dannyneira** [comment]
Merging into #58.
Please +1 that request as it helps us gauge interest. We will post any updates there.
