### ISSUE TITLE
Application is running, but no window or tab will open

### ISSUE THREAD

**Issue by pvegh** [warpdotdev/Warp#2189]
### Describe the bug

After clean install I can't use Warp. Application is running, but no window or tab will open.

### To Reproduce

Open Warp

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Additional context

I'm suspecting some old shell config from the Intel Mac which sometimes shows up in IDEs, but now everywhere. It might be the old homebrew location for zsh, not really sure.
I'd be happy for any suggestions I could try to find a potential bad config.

### Does this block you from using Warp daily?

Yes

**Comment by pvegh** [comment]
Digging more I found the problem, it has nothing to do with Warp.
I just had to chsh -s /bin/zsh for the system use an existing path for new shells.

**Comment by dannyneira** [comment]
Sorry about this thanks for opening the issues and closing/letting us know.
