### ISSUE TITLE
[Feature Request] "Search this error on Google" link that appear next to errors

### ISSUE THREAD

**Issue by TowhidKashem** [warpdotdev/Warp#2190]
### Describe the solution you'd like?

```text
It would be great if a "Search this error on Google" link appeared next to errors whenever they occurred. Clicking this would open google with the search term being the error message.

Bonus points if AI could be used to strip the project specific things like naming/part of the path for privacy reasons and also to get better search matches.
```

### Is your feature request related to a problem? Please describe.

```text
I always find myself copy pasting the error message from the terminal into google, this would reduce that extra step.
```

### Additional context

Artist's rendition:

<img width="1357" alt="Screen Shot 2022-11-19 at 1 45 49 PM" src="https://user-images.githubusercontent.com/1139927/202868791-6170de8e-29d3-4e4a-ae42-36536ba455c9.png">

### How important is this feature to you?

4

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.
