### ISSUE TITLE
Opening an existing Warp terminal instead of a new one on 'Hotkey Window' feature

### ISSUE THREAD

**Issue by Anivone** [warpdotdev/Warp#2194]
### Describe the solution you'd like?

```text
It would be great if the 'Hotkey Window' feature opens an existing terminal window instead of creating a new one as it clears the current working directory as well as blocks. For example, I would like to open Warp if I have to run and test a script, but I am obliged to go to current working directory each time I use the hotkey.
```

### How important is this feature to you?

4

**Comment by elviskahoro** [comment]
I'm not sure how feasible this is, will check and get back to you.

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by AaronRoethe** [comment]
This is my favorite feature about iterm, I use an ultra wide monitor with my setup so the window sizing options are hard to use. Setting my original terminal window exactly where I'd like it and then having a hotkey to pull it into view would be a great feature. Users that have nonstandard monitor sizes would greatly benefit from this.

**Comment by Tprezioso** [comment]
+1! Like said above, being able to use the hotkey shortcut to pull up a window with my current terminal session tabs instead of getting a new terminal would be super useful.

**Comment by dannyneira** [comment]
Hey Folks, the update released today `v0.2023.03.07.08.02.stable_01` adds this feature to Warp. 
You can set the hotkey via the `Settings > Features > Keys`, select 'Show/hide all windows' in the Global hotkey dropdown, then set your preferred keybinding.

![CleanShot 2023-03-09 at 16 10 18](https://user-images.githubusercontent.com/16809145/224181687-0104f727-89ab-44ad-8be8-4e6c6696b1ab.png)

Closing as resolved. 🚀

**Comment by AaronRoethe** [comment]
Thank you! This feature is amazing, I just tested it out.

**Comment by Tprezioso** [comment]
Thank you and the warp team so much! I just turned it on and couldn’t be happier! 🤘🏻

**Comment by maadilrehman** [comment]
Not Supported on wayland.
