### ISSUE TITLE
hotkey for history search not working

### ISSUE THREAD

**Issue by dmb23** [warpdotdev/Warp#2198]
### Discord username (optional)

dmb23#8709

### Describe the bug

The switch to "Command Search" breaks my workflows in a Terminal when pressing CTRL-R does not reliably produce most recent results (see also the thread in Discord). I tried to change the new keybindings to use "History Search" instead. Unfortunately the keyboard shortcut for "History Search" does nothing at the moment.

### To Reproduce

1. Go to Settings -> Keyboard shortcuts
2. change the settings of "History search" or of "Command Search" to something else than `CTRL-R` (so they don't overlap anymore)
3. press the keyboard shortcut for "History search"
4. Nothing happens

### Expected behaviour

The keyboard shortcut for "History search" should activate a history search

### OS Version

12.6

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by szgupta** [comment]
Hey @dmb23, thanks for reporting! We'll work on making the keybinding configurable. Though the keybinding would still open up the new `Command Search` modal -- would it help if we introduced a new keybinding to open the `Command Search` modal with the `history` filter applied?
<img width="1136" alt="Screen Shot 2022-11-22 at 10 58 58 AM" src="https://user-images.githubusercontent.com/39461854/203361484-492bf872-2ab1-4b91-aa35-8de7bd4a3012.png">

**Comment by dmb23** [comment]
You are welcome, thanks for the quick reply (and great piece of software!) To your question:

- It would be a big step forward in the issue as stated above for the keybind
- But I don't know if it would allow me to comfortably use Warp: after testing a bit I found you have some added intelligence in your search: When I search e.g. `tnyl` in the history, I get a few results of `git tnylog ...` but then all of a sudden "pylint --rcfile=.../py**t**ho**n**/.p**yl**intrc", so not at all what I would expect from my experience with other shells. And I started noticing all this, because the first result from your search was not always the last command I entered that matched the search term - and this is how I use CTRL-R normally (probably many others also?)

**Comment by vorporeal** [comment]
Hey @dmb23, thanks for giving your feedback on this!

Definitely agree about making it possible to set a keybinding to jump directly to history-only search; I've already started working on fixing that. :)

In terms of the "ranking" of results - this actually hasn't changed between the previous "History Search" and the new "Command Search".  :)  (We've been ordering based on "fuzzy match score" for some time now.)  It's certainly a different experience from the chronologically-ordered results that shells typically provide, but there are some pros and cons to the change.

**Comment by dmb23** [comment]
Interesting, then it might have been coincidence that last week I stumbled upon this behaviour a few times. Thanks for the quick reaction!

**Comment by vorporeal** [comment]
Hey @dmb23 - you should be able to set up a keybinding for History Search now; please re-open this issue and let me know if it's not working for any reason!
