### ISSUE TITLE
I would love to have cursor: pointer on buttons/etc.

### ISSUE THREAD

**Issue by stefanmatar** [warpdotdev/Warp#2199]
### Describe the solution you'd like?

```text
When I hover over elements that are clickable, my cursor should become a pointer
```

### How important is this feature to you?

2

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by dannyneira** [comment]
Hey @stefanmatar This feature is launched and appears to be in the latest version of Warp. When you hover over a clickable item, the cursor becomes a pointer appropriately. 

https://user-images.githubusercontent.com/16809145/225421773-39d89534-9576-4b8a-9dcb-a75a273ee8a2.mp4

Closing as completed.
