### ISSUE TITLE
Differentiating User Shells And Subshells

### ISSUE THREAD

**Issue by shankarshastri** [warpdotdev/Warp#220]
### Describe the solution you'd like?

```shell
It would be great based on the context, to show to users that currently in shell or subshell mode (For example docker shell container id for docker exec, and in case of ssh to ssh and hostname)
```

### Is your feature request related to a problem? Please describe.

```shell
It's always a challenge to know whether we are in actual shell or any subshells.
```

**Comment by zheng** [comment]
Thanks for the idea! We certainly want to improve the product behavior when in subshells. Agree it would be nice to show full info about the shell environment.

**Comment by elviskahoro** [comment]
Moving to:
- #64
