### ISSUE TITLE
When using TABS you can't select the first character on the screen.

### ISSUE THREAD

**Issue by oceans1908** [warpdotdev/Warp#2200]
### Describe the solution you'd like?

```text
When using TABS you can't select the first character on the screen, as it is covered by the TAB Active sign. It would be nice if the tab active sign can be replaced to the TAB it self.
```

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Hi! thanks for this request! 
I'm not seeing the same on my end. May you please provide an example of this issue with the text being blocked by a Tab or Pane indicator? This would help us get a better idea of what your feature request is.

![CleanShot 2022-11-23 at 16 14 48](https://user-images.githubusercontent.com/16809145/203661965-5acff1ec-9ac3-4478-9ae7-ca7a18f2b85d.png)

**Comment by dannyneira** [comment]
Got it thanks! will post updates here on this, its being worked on, but not ready quite yet.

**Comment by dannyneira** [comment]
Hi @oceans1908 Closing this one as completed since there is not padding on the edges of the text that allows for the active pane triangle not to block the text ( same padding applies in compact mode and in the alt screen ).
