### ISSUE TITLE
Suggestion can be disabled

### ISSUE THREAD

**Issue by pchalamet** [warpdotdev/Warp#2202]
### Describe the solution you'd like?

```text
Suggestion can be disabled if user do not like it. Add a toggle button in Settings/Features.
```

### Is your feature request related to a problem? Please describe.

```text
Suggestion is always getting in the way. I do not always type the same commands and this get in the way and is misleading (for eg for `cd` where I'm not in the correct folder).
```

### Additional context

Here suggestion display `telemedicine` but it's not true as `telemedicine` is not in this folder:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/1562400/203314432-1367a45e-554e-4763-93f5-dafae0ff6f44.png">

### How important is this feature to you?

5 (Can't work without it!)

**Comment by elviskahoro** [comment]
You can disable it from the Command Palette!
<img width="692" alt="CleanShot 2022-11-22 at 11 12 36@2x" src="https://user-images.githubusercontent.com/29553206/203364830-682f6497-7cbd-42d4-ad81-ec096937c44f.png">

Press CMD-P and search autosuggestion.

**Comment by pchalamet** [comment]
Ha 😅 ! Thanks !

**Comment by dannyneira** [comment]
NP, hope this helps! 
https://docs.warp.dev/features/editor/autosuggestions
