### ISSUE TITLE
Tabs > "Rename Tab" Feature Does Not Work Consistently

### ISSUE THREAD

**Issue by dotSomething** [warpdotdev/Warp#2203]
### Describe the bug

One tab of many does not retain its custom name. 

## Steps
1. Open 3 Warp windows
2. Configure each window: 
   * Window 1: 4 tabs
   * Window 2: 1 tab
   * Window 3: 2 tabs
3. Rename all tabs in window 1
4. Rename the tab in window 2
5. Rename both tabs in window 3
6. Restart Warp

## Actual Behavior
1. All tabs in windows 1 and 2 retain their custom names.
2. Window 3, tab 2 retains its custom name.
3. Window 3, tab 1 does NOT retain its custom name.

### Expected behaviour

All tabs across all windows retain their custom names.

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

bash 3.2.57(1)-release (arm64-apple-darwin21); zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Hi @dotSomething, Thanks for letting us know! We're sorry about this, this is not an ideal experience.

I can't repro this currently, so may you please try to make sure you have Session Restoration enabled? it should be by default, but this may be part of the reason the tabs names aren't restoring.

https://docs.warp.dev/features/sessions/session-restoration

**Comment by dannyneira** [comment]
Hi @dotSomething I'm not noticing the same issue in the latest version of Warp, `v0.2023.05.09.08.03.stable_01`, closing as completed, but please feel free to reopen with a video/screenshots of the issue if the bug persists.
