### ISSUE TITLE
Mouse selection for commands

### ISSUE THREAD

**Issue by pchalamet** [warpdotdev/Warp#2204]
### Describe the solution you'd like?

```text
Ability to mouse select text for command in history and current command.
```

### Is your feature request related to a problem? Please describe.

```text
I can't select text using mouse on commands. Otherwise I have to use "Copy Command" and remove unnecessary text :-(
```

### Additional context

![image](https://user-images.githubusercontent.com/1562400/203346682-eb95bcfb-bba0-4635-ad64-9a574bab2258.png)

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment]
Hi @pchalamet We actually have this functionality in Warp, you can select the text for a command with a mouse, or if the block is selected use `CMD-SHIFT-C` to copy only the command, then `CMD-L` to jump to the input editor, and to `CMD-V` to paste. Please see my example below, and more in block actions [here ](https://docs.warp.dev/features/blocks/block-actions). Hope this helps. 

https://user-images.githubusercontent.com/16809145/203640759-7fc5683e-6d2c-46d5-bbc7-05972acb9069.mp4

Please close this issue if the above helped. If not please provide a more detailed explanation of your request, with better visual examples of the use case, as it's not clear what feature/functionality you're asking for.

**Comment by pchalamet** [comment]
Yes sorry you are right. That was not the command but the path (see screenshot in inssue). Sorry for confusion.
Anyway, would be good to copy/paste path as well.
