### ISSUE TITLE
Inactive pane dimming

### ISSUE THREAD

**Issue by zenria** [warpdotdev/Warp#2205]
### Describe the solution you'd like?

```text
Dim the content of the entire pane when it's inactive to give an immediate visual feedback on where the active cursor is.
```

### Is your feature request related to a problem? Please describe.

```text
This feature is what I miss the most from iTerm2. In warp it is very difficult to see which is the active pane. You have to search for the active text input. It is even worse if the terminal is running an application, only the little top left mark
```

### Additional context

Here are a sample of how iterm2 does this...
<img width="1088" alt="Capture d’écran 2022-11-22 à 20 08 21" src="https://user-images.githubusercontent.com/1299045/203401830-6c4e69b6-9bd2-459a-ade9-9e6a078d543c.png">

<img width="1088" alt="Capture d’écran 2022-11-22 à 20 08 46" src="https://user-images.githubusercontent.com/1299045/203401850-84d8d4bf-8690-4acd-97cf-f5c12eb6f10c.png">

and it is fully configurable

<img width="897" alt="Capture d’écran 2022-11-22 à 20 08 50" src="https://user-images.githubusercontent.com/1299045/203401869-d07b8616-d21c-45e8-b7df-941be980f1ff.png">

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

Currently, in Warp the active pane is denoted by a triangle in the corner, in addition, the active pane has the text input editor, while the inactive pane(s) will only show the prompt, no input. See more on the panes here: https://docs.warp.dev/features/windows/split-panes

![CleanShot 2022-11-23 at 11 02 47](https://user-images.githubusercontent.com/16809145/203617517-48f6f155-6ffa-4292-b6e6-162b7fb359b5.png)

**Comment by elviskahoro** [comment]
This was launched today!
