### ISSUE TITLE
Cannot detect custom themes.

### ISSUE THREAD

**Issue by RoyRao2333** [warpdotdev/Warp#2211]
### Describe the bug

I followed [instructions 1](https://docs.warp.dev/features/appearance/custom-themes) and [instructions 2](https://github.com/warpdotdev/themes/) to add my custom themes, but no matter how long I wait or simply restart Warp, my themes just don't show up in themes panel.

### To Reproduce

In ~/.warp/themes:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/31413093/203462999-a940573b-f458-453d-8d44-8358a2fba342.png">

In theme file:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/31413093/203463047-e485e736-4c0a-4236-90fb-0f1902d7e03d.png">

I originally downloaded this theme from [catppuccin](https://github.com/catppuccin/warp) and added my custom background image.

In images folder:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/31413093/203463194-5a1a3a91-0759-4a4f-9fa2-e91fe992a3be.png">

### Expected behaviour

I should find my new theme according to the instructions:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/31413093/203463546-3e353c7d-9b3e-43d2-99c7-730b5b717aa9.png">

However, it didn't...

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Hey! sorry about this!
Warp currently only supports images with the .jpg file format:
.jpeg
.jpg
.JPEG

the image path is relative to `~/.warp/themes` so make sure the `/Images/bg_image.jpg` is inside that folder.

**Comment by RoyRao2333** [comment]
> Hey! sorry about this! Warp currently only supports images with the .jpg file format: .jpeg .jpg .JPEG
> 
> the image path is relative to `~/.warp/themes` so make sure the `/Images/bg_image.jpg` is inside that folder.

Thanks for the reply!

Yes, the images folder is in ```~/.warp/themes``` and now I've converted my image to ```.jpg```:

> ~/.warp/themes/images/bg_image.jpg

Now the theme file looks like this:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/31413093/203466424-29421dda-68e1-468a-92ce-83bb36a174b0.png">

However, after I restarted Warp, I'm still not seeing my new theme...

**Comment by RoyRao2333** [comment]
> Hey! sorry about this! Warp currently only supports images with the .jpg file format: .jpeg .jpg .JPEG
> 
> the image path is relative to `~/.warp/themes` so make sure the `/Images/bg_image.jpg` is inside that folder.

Further information: 

If I remove the ```background_image``` attribute, my theme will immediately show up.

What did I do wrong on background image? 😨

**Comment by dannyneira** [comment]
So I did some testing and the opacity value is required for the themes to show up properly. It can range from 0-100, but must be there under the path. I've updated the docs to reflect this requirement. 

![CleanShot 2022-11-23 at 09 11 44](https://user-images.githubusercontent.com/16809145/203595561-51d8e8b3-7837-4f72-bef1-f264ceb7ca6d.png)

Closing this case as resolved, thanks for your patience.

**Comment by RoyRao2333** [comment]
> So I did some testing and the opacity value is required for the themes to show up properly. It can range from 0-100, but must be there under the path. I've updated the docs to reflect this requirement.
> 
> ![CleanShot 2022-11-23 at 09 11 44](https://user-images.githubusercontent.com/16809145/203595561-51d8e8b3-7837-4f72-bef1-f264ceb7ca6d.png)
> 
> Closing this case as resolved, thanks for your patience.

Yes, it's working like a charm now! 🎉 Thanks for your help!
