### ISSUE TITLE
Provide a way to hide selected block border?

### ISSUE THREAD

**Issue by RoyRao2333** [warpdotdev/Warp#2212]
### Describe the solution you'd like?

```text
I really like the idea of block-like terminal, which is really a boost for my development.

But can I hide the border on a selected block?

Maybe after we clicked on a block, we can click it again to unselected it?
```

### Additional context

Preview as below:

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/31413093/203482176-7ac3ea32-c89c-42d2-b138-9f9500c23895.png">

Small blocks with border can be a pretty view. But as a block growing big and the border fills the whole window, it'll become a disaster for my lovely custom themes and I feel like it's a mask over texts...  😂 That's not looking good.

Also, the bottom-left && bottom-right corner-radius are not so smooth...

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Hi! Thanks for this feature request! There is a duplicate here: #2177 
Please +1 that request as it helps us gauge interest. We will post any updates there.

There is currently no way to do this, but I recommend you try 'Compact Mode', search for it in `settings > appearance` or in the command palette `cmd-p`.

Closing as duplicate.
