### ISSUE TITLE
SSH Wrapper using remote zsh shell is unable to parse correctly

### ISSUE THREAD

**Issue by adradr** [warpdotdev/Warp#2214]
### Describe the bug

When logging in a remote ssh machine and it already uses `zsh` then the local Warp SSH wrapper feature automaticall inputs the zsh added characters into the input field.

<img width="915" alt="Screenshot 2022-11-23 at 12 36 51" src="https://user-images.githubusercontent.com/9167422/203537665-d20c8a0a-2c3c-41c5-ac4e-850a839c0b8d.png">

### To Reproduce

1. ssh into machine
2. type any command
3. the styling characters are inputted into the input field, instead of visualizing it or completely hiding

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by vorporeal** [comment]
Hey @adradr, this is an issue with our handling of right-side prompts; I submitted a fix yesterday and it should go live in next week's release. Sorry about the bug!

**Comment by adradr** [comment]
No problem, otherwise I love it! Thanks for the quick response!On 2022. Nov 23., at 17:08, David Stern ***@***.***> wrote:﻿
Hey @adradr, this is an issue with our handling of right-side prompts; I submitted a fix yesterday and it should go live in next week's release. Sorry about the bug!

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
