### ISSUE TITLE
Launch Warp from terminal in particular directory

### ISSUE THREAD

**Issue by sd-godaddy** [warpdotdev/Warp#2215]
### Describe the solution you'd like?

```text
launch Warp from any other terminal:

    open /Applications/Warp.app --args /Users/mysusername/Workspace/PEX_dev/myprojectname

It opens warp but clearly passing arg /Users/mysusername/Workspace/PEX_dev/myprojectname 
is not making Warp to open in this location.
Probably Warp is not accepting arguments at all.
```

### Is your feature request related to a problem? Please describe.

```text
Usually I'm using terminal from IDE but very often I'm opening iTerm from IDE's builtin terminal.
The thing is I can launch it in the same directory as Ide terminal is opened in, so I can 
carry on with my work there in richer terminal.

I can launch Warp from IDE's terminal too, but it will start not in the location I desire, 
so I have to navigate in Warp do proper directory and only then continue my job in the project.

Making above command (from "Describe the solution you'd like?" section ) would help.

NOTICE: It would be nice probably to cover the case when Warp app 
is already launched to open new tab in that locations.
This case is not covered in iTerm either

```

### How important is this feature to you?

3

**Comment by vicenciomf2** [comment]
This bash function worked for me:
```
openwarp(){
   nohup warp-terminal warp://action/new_tab?path=$(pwd) &
}
```
Hope it helps:)

**Comment by dddrop** [comment]
for mac user

```shell
openwarp(){
    open "warp://action/new_tab?path=$(pwd)" &
}
```

for supported uri schemes, see: https://docs.warp.dev/features/uri-scheme

**Comment by its-tim-lee** [comment]
> for mac user
> 
> ```shell
> openwarp(){
>     open "warp://action/new_tab?path=$(pwd)" &
> }
> ```
> 
> for supported uri schemes, see: https://docs.warp.dev/features/uri-scheme

is it possible to integrate this in VSC?

**Comment by jakubsuchybio** [comment]
I use a shortcut in total commander on windows to start a WT at current dir.
I tried to replicate with warp via 
```
warp://action/new_tab?path=.
```
but it doesn't capture the current dir :/
any ideas?

**Comment by jakubsuchybio** [comment]
Hmmm, I hate starting it via cmd /c, as it opens a console first, then closes, then opens warp. could there be a way to open warp directly at some folder via just
```
warp .
```
??? Please
