### ISSUE TITLE
always-on-top

### ISSUE THREAD

**Issue by bogdanrn** [warpdotdev/Warp#2216]
### Describe the solution you'd like?

```text
I would like an option to activate "always on top" mode, having the terminal window to be always on top of any other window. Especially nice when you use it combined with the quake style hot key.
```

### Is your feature request related to a problem? Please describe.

```text
When i work from a small screen it's very frustrating to find the terminal when i have 30 windows open. I use the quake style hotkey to bring it up, but when i want to copy/paste stuff or keep an eye on the terminal while i can answer a message on slack i have to akwardly try to resize my windows or hit the hotkey multiple times. 

When using the quake style hot-key in my opionion the terminal should always be on top unless you dismiss it. But i would be glad to just have a setting that works globally, i do not use it any other way.

Thanks!
```

### How important is this feature to you?

4

**Comment by dannyneira** [comment]
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here

**Comment by dannyneira** [comment]
Thanks for this feature request! Closing as duplicate. #1782
Please +1 that request as it helps us gauge interest. We will post any updates there.

**Comment by dannyneira** [comment]
Checking to see if we can update the wording on this to make it more clear what the toggle is doing and update our docs accordingly.

**Comment by dannyneira** [comment]
Checking to see if we can update the wording on this to make it clearer what the toggle is doing and update our docs accordingly.

Closing as this feature already exists.

**Comment by bogdanrn** [comment]
Uh, you're right. This is exactly what the feature does. Sorry i missed it. I think my brain was looking for toggles since most of the settings are like that, except this one and something related to fonts. 

<img width="557" alt="Screenshot 2022-11-24 at 13 27 23" src="https://user-images.githubusercontent.com/5882067/203773264-8a7a7dca-72d6-4e70-a94b-b650ad7b22f3.png">

Looking at the setting screen it makes me believe that this is related only to the quake style setting, if that's the case, a new dropdown instead of checkbox would make it a lot clearer, the dropdown could have two values: 

  - Always keep window on top of others
  - Hide window on loss of focus
  
<img width="668" alt="Screenshot 2022-11-24 at 13 44 40" src="https://user-images.githubusercontent.com/5882067/203776718-f8fc1b77-4f8c-4198-b33b-1e9ba89fcbfd.png">

**Comment by dannyneira** [comment]
Thanks for your feedback! I've updated the wording on the checkbox to help with this but agree it can be presented better.
