### ISSUE TITLE
Support IDE-style editor for REPLs

### ISSUE THREAD

**Issue by xxchan** [warpdotdev/Warp#2217]
### Describe the solution you'd like?

```text
Pretty enjoy the IDE-style editor, especially the ability of selecting the text to delete it. 

So I'm wondering is it possible to support this feature in REPLs, e.g., python, psql, ... 🤔
```

### How important is this feature to you?

4

**Comment by dannyneira** [comment]
Thanks for this feature request! We have a duplicate here: #64 
Please +1 that request as it helps us gauge interest. We will post any updates there.
