### ISSUE TITLE
Latest update on Warp for Ubuntu 22.10?

### ISSUE THREAD

**Issue by slickmode** [warpdotdev/Warp#2218]
### Describe the solution you'd like?

```text
Really would like to install Warp terminal on Ubuntu machines.  Any timeline on when this will be available? Even for beta testing?
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment]
Thanks for this feature request! 
Closing as duplicate https://github.com/warpdotdev/Warp/issues/120
Please +1 that request as it helps us gauge interest. We will post any updates there.
