### ISSUE TITLE
Split pane right/left doesn't work as intented

### ISSUE THREAD

**Issue by bit1creative** [warpdotdev/Warp#2221]
### Discord username (optional)

bit1creative

### Describe the bug

When having more than two panes opened in one tab clicking `Split pane left/right` doesn't creates a new pane next to the one I've been on.

### To Reproduce

When clicking `Split pane left/right` the new pane is created next to the one I've been on.

### Expected behaviour

When clicking `Split pane left/right` the new pane's index is shifted.

### Screenshots

https://user-images.githubusercontent.com/48476397/203762049-0e55758b-9b04-4273-8690-a93f4e1cd306.mp4

### Operating System

MacOS

### OS Version

13.0.1 (22A400)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Thanks for bringing this up, Sorry about the issue. Will post updates here when this is resolved.

**Comment by elviskahoro** [comment]
This should be fixed, if not it'll be out next week.
