### ISSUE TITLE
Add support for nushell 

### ISSUE THREAD

**Issue by mmerdes** [warpdotdev/Warp#2222]
### Describe the solution you'd like?

```text
If I understand warp's architecture correctly, the terminal application is internally separated from the shell it uses, thus enabling the choice between several shells.

Nushell is a modern shell based on pipelines over _structured_ data (as opposed to text-based piping of traditional shell).
https://www.nushell.sh

The combination of warp's powerful terminal with nushell's expressiveness would deliver great productivity gains.
```

### Additional context

A simple example of the powerful pipelines possible with nushell:

![image](https://user-images.githubusercontent.com/9845887/203763004-23b2bc18-9b34-4be4-9e9f-a93c7ef7a64a.png)

### How important is this feature to you?

4

**Comment by dannyneira** [comment]
Thanks for this request, closing in favor of duplicate #880 Please subscribe there for updates.
