### ISSUE TITLE
Seriously annoying autosuggestion / autocomplete bug, issues, and suggestions

### ISSUE THREAD

**Issue by SynaptSea** [warpdotdev/Warp#2225]
### Discord username (optional)

Mysterysib#4099

### Describe the bug

When I use the suggestions box for autocomplete on *keypress:* *ENTER* , the completion / auto-enter functionality does not replace the existing string with the suggestion, but adds it onto it as shown below in my screenshot.

This is annoying and should at least be an option, but given how annoying it is I'd presume it's an unintended bug.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/36235551/203864944-283cab5a-7161-4c21-8517-27800243dc98.png">

**Further Suggestion:** 
**A.** An option to keep the suggestion box but to disable autocomplete / autoenter on *keypress:* *ENTER*, or change the autoenter hotkey.

*This is implemented in the terminal tool Fig (https://github.com/withfig), for reference.*

**B.** Autosuggestion box auto-completion / autoenter into the shell upon the hotkey keypress without needing to press *ENTER* again should at least be an option. This is important for **BOTH security and convenience of use**.

*This is also implemented in Fig*

### To Reproduce

1. Type in a command with the last string in the input line being something the autosuggestion suggests...
	**Ex** *.* Like, `gcc -fcommo`
3. Press enter.
4. See the invalid command being input into the shell
 	**Ex** *(continued) .* for the aformentioned gcc example: `gcc -fcommo-fcommon`

### Expected behaviour

I expect the input being transformed before even being input into the shell to validate the command (and avoid accidentally inputting something wrong, **Which can even be dangerous!!**) like so (for the example in the **To Reproduce** section of my report):
`gcc -fcommo` turns to `gcc -fcommon` *(from the suggestion box)*, **BUT** remains in the input line for the user to check over it *keypress:* *ENTER* before pressing *ENTER* again to input it to the shell for eval.

Autosuggestion box auto-completion / autoenter into the shell upon the hotkey keypress without needing to press *ENTER* again should at least be an option. This is important for **BOTH security and convenience of use**.

### Screenshots
*(additional screenshot):* ![image](https://user-images.githubusercontent.com/36235551/203866539-b6e54336-b0a9-4666-8fba-ffb3ce3e2b19.png)

### Operating System

MacOS

### OS Version

Ventura 13.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0) *//default shell that comes with Mac OSX*

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

No, but it seriously impedes my personal workflow and makes me opt for other tools at the moment like Fig.

However, I love Warp and believe it has great potential, so I hopes bugs like these are addressed so I may switch back!

<details>
<summary>Details</summary>

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

</details>

**Comment by dannyneira** [comment]
Closing as a duplicate feature request in favor of https://github.com/warpdotdev/Warp/issues/1909 
We will post updates on this in the above issue.

There is currently no way to change `ENTER `for completion. As a workaround I suggest you try and disable 'Completions as you type' in the `Settings > Features`, you will need to press `TAB` to open the completion menu and press `ENTER` to accept still, but may reduce the friction with usability some. Hope this helps!
