### ISSUE TITLE
`git diff` not working

### ISSUE THREAD

**Issue by noobmldude** [warpdotdev/Warp#2230]
### Discord username (optional)

NoobMLDude#3834

### Describe the bug

`git diff` command seems to open an empty file, but doesnt show the diff of the git repository.

### To Reproduce

1. Navigate to a git repository
2. Run `git diff <filename>`

### Expected behaviour

Show the diff of the files in the git repo

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.8 (x86_64-apple-darwin19.6.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi! Sorry about this, I'm not seeing the same on my end and can't repro this, are you using any custom completion plugin? or can you please try in another repro or provide more details?

![CleanShot 2022-11-28 at 14 06 15](https://user-images.githubusercontent.com/16809145/204380984-d19fbd33-3500-400b-a57c-f0600dd8e971.png)

**Comment by noobmldude** [comment]
I'm facing this issue when running `git diff`. 
```
git-nbdiffdriver diff: git-nbdiffdriver: command not found
fatal: external diff died, stopping at 0-course-logistics.ipynb
```
Any clue what I could be missing?

**Comment by noobmldude** [comment]
Here's a screencast of what I'm seeing.
https://user-images.githubusercontent.com/98090437/205492970-5b4a8d8e-a1d2-43aa-a960-d496c7f58a3e.mov

Any clue what I could be missing?

**Comment by vorporeal** [comment]
What appears when you do the same in iTerm or Terminal.app?  I can't think of anything we'd be doing that would affect the results of `git diff`... 🤔

**Comment by FreddieOnly** [comment]
Hello Warp-Support Team,

I encounter the same error in Warp as well in the terminal from Mac Os 11.72
![git diff Screen Warp](https://user-images.githubusercontent.com/102794884/214853736-dd0eab2a-4ced-42b1-a231-1ef77dfd69f9.png)
![git diff Screen Terminal Mac OS 11 72](https://user-images.githubusercontent.com/102794884/214853744-5678e28d-7e77-4a6b-87ef-358b5095af16.png)

How can i continue to get back to the ‘normal‘ window?
I am looking forward hearing from you

**Comment by vorporeal** [comment]
If you're "stuck" with the diff visible, try pressing "q" to quit the pager.

**Comment by FreddieOnly** [comment]
Thank you very much!

During the day i got to this solution
Kind regards Freddie

David Stern ***@***.***> schrieb am Do. 26. Jan. 2023 um
21:30:
