### ISSUE TITLE
AI Command: checkout remote branch

### ISSUE THREAD

**Issue by itsjoshpark** [warpdotdev/Warp#2234]
### Describe the solution you'd like?

I was trying to fetch and checkout a remote branch but couldn't remember the git command for it. I tried asking AI Command `git checkout remote branch` but it suggested `git checkout -b branch_name origin/branch_name` instead of `git checkout -t origin/branch_name` which was what I was looking for. Suggesting the `-t` option rather than `-b` (create new branch) would've been more helpful.

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Hi, unfortunately, the ai isn't perfect, got you like 80%+ of the way at least, but it's always improving due to the API it's powered by. https://www.warp.dev/blog/story-behind-ai-command-search

Good thing we still have our brains to correct any mistakes.
