### ISSUE TITLE
Window menu should display open windows

### ISSUE THREAD

**Issue by hsheresd** [warpdotdev/Warp#2235]
### Discord username (optional)

sirgreendragon#4325

### Describe the solution you'd like?

```text
When multiple windows are open, display them at the bottom of the windows menu so i can quickly navigate to the one I want. I never use multiple tabs in one window, it is too limiting.
```

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Hi Thanks for this request, as a stop-gap, we have a feature that may help with your use case. https://docs.warp.dev/features/sessions/session-navigation

**Comment by hsheresd** [comment]
> Hi Thanks for this request, as a stop-gap, we have a feature that may help with your use case. https://docs.warp.dev/features/sessions/session-navigation

This is a nice feature for navigating open windows/tabs, but I usually close windows and tabs for projects I am not currently working on so I don't accidentally type into the wrong place. I use the sets feature in the terminal app to re-open a set of windows.

**Comment by dannyneira** [comment]
I understand, in that case, I recommend Launch Configurations, you can save a set of windows/tabs and panes to work on different tasks. https://docs.warp.dev/features/sessions/launch-configurations

I'll bring this up with the team as a useful feature for sure.

**Comment by dannyneira** [comment]
As per the latest release, Warp will now show the active windows on right-click of the dock icon!

![CleanShot 2023-02-10 at 10 45 51](https://user-images.githubusercontent.com/16809145/218160728-0153882f-ba72-48ca-aaae-81423ca41124.png)

![CleanShot 2023-02-10 at 10 48 18](https://user-images.githubusercontent.com/16809145/218160793-011d2a4f-9743-4688-92c6-502c2ac01e8b.png)
