### ISSUE TITLE
Support Window Sets

### ISSUE THREAD

**Issue by hsheresd** [warpdotdev/Warp#2236]
### Discord username (optional)

sirgreendragon#4325

### Describe the solution you'd like?

```text
I would like to be able to save groups of windows as a set so i can open them all again later.
```

### Additional context

I have several windows for each project I work on, when I switch to a project, i close all the windows for the previous project and open the windows for the new project. The windows remember my current working directory so this helps a lot.

### How important is this feature to you?

4

**Comment by dannyneira** [comment]
There is a feature for that! https://docs.warp.dev/features/session-management/launch-configurations
