### ISSUE TITLE
Cannot use CMD key shortcut for Hotkey Window

### ISSUE THREAD

**Issue by victorkirov** [warpdotdev/Warp#2237]
### Describe the bug

I'm trying to set the Hotkey Window keyboard shortcut to CMD + ` but any shortcut with just CMD and another key doesn't get registered. It works on iTerm and I need it to switch to Warp as it's built into my muscle memory.

Option + another key or Ctrl with another key work fine though, and so does CMD + Option/Ctrl + another key.

### To Reproduce

> Go to settings
> Go to Features
> Hot Key Window
> Keybinding

Then try set the shortcut to CMD + `

### Expected behaviour

The keybinding accepts CMD + <other key> as a shortcut

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.9

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi! thanks we are tracking this feature request here: #1851
