### ISSUE TITLE
open failed: administratively prohibited:

### ISSUE THREAD

**Issue by ricky-charlet** [warpdotdev/Warp#2244]
### Describe the bug

when 
1. ssh logged into a linux server...
2. cd into an environment where I am in a local git repo
3. I am making use of [git_promt.sh](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh)

Then, 
 I see this type of output on almost any command attempt
 (here I tried to cd into a sub dir)
--- copy ---
✔ /ws/charletr/halon [brackets_poc ↓·1|✚ 2…1⚑ 1]
09:30 $ channel 19: open failed: administratively prohibited: open failed
channel 21: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 25: open failed: administratively prohibited: open failed
channel 21: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 25: open failed: administratively prohibited: open failed
channel 21: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 25: open failed: administratively prohibited: open failed
channel 3: open failed: administratively prohibited: open failed
channel 21: open failed: administratively prohibited: open failed
channel 25: open failed: administratively prohibited: open failed
channel 19: open failed: administratively prohibited: open failed
channel 21: open failed: administratively prohibited: open failed
channel 11: open failed: administratively prohibited: open failed
channel 11: open failed: administratively prohibited: open failed
channel 21: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 17: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 25: open failed: administratively prohibited: open failed
channel 13: open failed: administratively prohibited: open failed
channel 17: open failed: administratively prohibited: open failed
channel 25: open failed: administratively prohibited: open failed
channel 17: open failed: administratively prohibited: open failed
channel 21: open failed: administratively prohibited: open failed
channel 25: open failed: administratively prohibited: open failed
channel 5: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 15: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 19: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 19: open failed: administratively prohibited: open failed
channel 25: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 19: open failed: administratively prohibited: open failed
channel 25: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 15: open failed: administratively prohibited: open failed
channel 25: open failed: administratively prohibited: open failed
channel 15: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 25: open failed: administratively prohibited: open failed
channel 15: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 19: open failed: administratively prohibited: open failed
channel 17: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 19: open failed: administratively prohibited: open failed
channel 17: open failed: administratively prohibited: open failed
channel 19: open failed: administratively prohibited: open failed
channel 23: open failed: administratively prohibited: open failed
channel 17: open failed: administratively prohibited: open failed
channel 21: open failed: administratively prohibited: open failed
✔ /ws/charletr/halon [brackets_poc ↓·1|✚ 2…1⚑ 1]
bash: ✔: command not found
bash: ✚: command not found
channel 23: open failed: administratively prohibited: open failed

---- paste ---

Wild guess: 
 the git_promt.sh is attempting to run (git) commands to collect the info it wants to form it's complex promt. Those are the commands which warp is worried about "admin prohibited" things.

### To Reproduce

ssh to a linux host
install git_prompt.sh
create or clone a git repo (from anywhere...I reproduce my issue from a company private repo I will not share)
cd into the git repo
run any trivial command from there such as `cd` or `ls`

### Expected behaviour

a well formed git_prompt as formed by git_prompt.sh script
the output of my trivial command (`cd` or `ls`)
no error messages

### Operating System

MacOS

### OS Version

12.6

### Shell Version

bash --version GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21) Copyright (C) 2007 Free Software Foundation, Inc.

### Warp Version

v0.2022.11.14.14.55.stable_01

### Additional context

from my linux server:

charletr@hpnsw4371:~$ cat /etc/issue
Ubuntu 16.04.7 LTS \n \l

charletr@hpnsw4371:~$ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
charletr@hpnsw4371:~$ uname -a
Linux hpnsw4371.rose.rdlabs.hpecorp.net 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
charletr@hpnsw4371:~$ 

and...I have a version of git-promt.sh from about 4 years ago. Not much versioning info on the script. Sorry.

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

**Comment by ricky-charlet** [comment]
Thanks warpdotdev,

Yes, if I disable my git-promt.sh, then warp shell is happy to ssh into my linux vm, enter my git repo, and do stuff. 
Like you said, warp terminal even has clever prompting of it’s own inside of a git repo. This is entirely fine with me and I am happy to make use of warp git promting rather than a bash shell script extension for git repo prompting.

So I’m very pleased. This is closable.

----
Ricky Charlet
***@***.***
C 510.579.1470

**Comment by dannyneira** [comment]
Thanks for your feedback and follow-up @ricky-charlet!
