### ISSUE TITLE
Real time output not displayed until the command has finished executing

### ISSUE THREAD

**Issue by Vishu26** [warpdotdev/Warp#2245]
### Describe the bug

Whenever I run a long running command, for example `git clone` or `conda list`, it does not show any output until the command has finished executing. As a result of this behavior, I am not able to input anything if the command asks for any inputs.

### To Reproduce

Run a long running command that involves user inputs.

### Operating System

MacOS

### OS Version

13.1

### Shell Version

bash 4.4.20

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @Vishu26 Sorry about this, 13.1 macos is the beta version, please upgrade to 13.0.1 GA and let us know if the issues persist.

**Comment by alanzeino** [comment]
How does one 'upgrade' from 13.1.0 to 13.0.1?

Isn't still an issue if it's on 13.1.0?

**Comment by alokedesai** [comment]
@Vishu26 @alanzeino Do you have the "completions as you type" setting enabled? Does this still repro if you turn that setting off?

**Comment by alokedesai** [comment]
Hey folks--just an update here. We are actively working on a fix for this--we're hoping to have it in this week's release (going out Thursday)

**Comment by Vishu26** [comment]
@dannyneira @alokedesai Thank you for the comments and suggestions. Mac does not show any updates currently. Maybe its just a small glitch with displaying the outputs in the blocks. Waiting for the next update.

**Comment by dannyneira** [comment]
> How does one 'upgrade' from 13.1.0 to 13.0.1?
Upgrade macos from beta to GA with this process: https://support.apple.com/en-us/HT213265
macOS 13.1 is a BETA release, GA only goes up to 13.0.1 for now. https://en.wikipedia.org/wiki/MacOS_Ventura

**Comment by alokedesai** [comment]
@Vishu26 Given we know what the underlying issue is, no need to upgrade to GA. We'll have this fix out shortly. Thanks!

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
