### ISSUE TITLE
Session hangs with 100% CPU after editing kubernetes resources using k9s

### ISSUE THREAD

**Issue by jkdv** [warpdotdev/Warp#2248]
### Discord username (optional)

primitiveman

### Describe the bug

I use [k9s](https://k9scli.io/) to manage kubernetes a lot. I found that every time I enter an edit mode and exit using k9s, e.g. editing statefulsets, the warp session becomes black and consumes 100% CPU. I assume this might be because a VI session inside k9s is causing this issue.

### To Reproduce

Reproducing the issue may be hard as we need some kubernetes clusters and resources. Docker Kubernetes extension or minikube might help.

- Install k9s [k9s](https://k9scli.io/) and execute.
- Browse any resources and press `e` to edit. This opens a VI session.
- You can not exit from the session. No need to save.

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @jkdv sorry about this issue, we know this is a huge blocker for many so we appreciate your patience while we work thru it.

Closing as duplicate, please +1 and track this issue there > https://github.com/warpdotdev/Warp/issues/833

**Comment by dannyneira** [comment]
We recently made performance/compatibility updates to alt-screen apps like emacs, please let us know if you're still seeing the issues with the latest version of Warp.
