### ISSUE TITLE
powerlevel10k installation in warp disfunction block understanding

### ISSUE THREAD

**Issue by Dennisovan92** [warpdotdev/Warp#2250]
### Describe the bug

Once I install and configure p10k in the macOS WARP terminal. Blocks are not splitting by command execution. only when I exit zsh

### To Reproduce

Install warp, install p10k and execute it ,switch to zsh shell

### Screenshots

https://app.warp.dev/block/J8FIWczMO5MiksyAhhkAoz

### Operating System

MacOS

### OS Version

13.0.1 (22A400)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @Dennisovan92 So sorry about this but we dont support p10k currently. If you want a powerful custom prompt i recommend starship.rs

https://docs.warp.dev/features/appearance/prompt#powerlevel10k-p10k

**Comment by dannyneira** [comment]
Please track the progress of other prompt support in this thread > # 422
