### ISSUE TITLE
Theme: Remove opacity requirement for background images

### ISSUE THREAD

**Issue by dannyneira** [warpdotdev/Warp#2253]
### Describe the bug

When you create or modify a theme to include a background image, if the opacity parameter is missing or empty, the Theme will not show up in Warps Theme picker.

See https://docs.warp.dev/features/appearance/custom-themes#background-images-and-gradients

### To Reproduce

1. Create a new theme, easy with https://warp-themes.com/
2. Add theme background image to theme folder ( e.g warp.jpg )
3. Modify the theme to include a background image, but comment out opacity, including:
```sh
background_image:
  # the path is relative to ~/.warp/themes/
  # the full path to the picture is: ~/.warp/themes/warp.jpg
  path: warp.jpg
  #opacity: 100
```
4. Go to Warp theme picker , and notice the theme is missing.
5. uncomment the opacity line, go back to the Warp theme picker `CTRL-CMD-T` and the theme should be there.

### Expected behaviour

Expect to see a background image default to opacity 100 if missing from the yaml file.

### Screenshots

https://user-images.githubusercontent.com/16809145/204618386-391fe88d-9f00-4d04-8d28-6273589d360f.mp4

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Additional context

Updated docs to reflect this requirement as a stop gap.

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
