### ISSUE TITLE
bash: parameter null or not set

### ISSUE THREAD

**Issue by ak--47** [warpdotdev/Warp#2255]
### Describe the bug

when running scripts with `node` i see this response every time:

`bash: __bp_last_argument_prev_command: parameter null or not set`

e.x.

```
$ node myscript.js  | tee log.txt
> bash: __bp_last_argument_prev_command: parameter null or not set
```

some infos:
```
$ which node
> /Users/ak/.volta/bin/node

$ node --version
> v16.17.1
```

might be user error here... i haven't seen this before...

### To Reproduce

```
touch foo.js
node foo.js
```

### Screenshots

![param not set?](https://user-images.githubusercontent.com/3978760/204711963-0abea37e-ad42-4bcd-9a61-ff51cd4f522c.png)

### Operating System

MacOS

### OS Version

10.14.6

### Shell Version

3.2.57(1)-release (x86_64-apple-darwin18)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @ak--47, My guess is that you normally have a [custom prompt, theme, or plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table)

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs.

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# Whatever you want to disable

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by ak--47** [comment]
@dannyneira that was exactly it! 

toggling around in there made it go away... i didn't know the prompt was interactable... that's a nice feature!

here was my `PS1` for my custom prompt from `~/.bash_profile` for reference:
```
export PS1="\n$C_LIGHTGREEN\u$C_RED@$C_LIGHTBLUE\h$C_DARKGRAY:  $C_LIGHTYELLOW\w\n$C_LIGHTPURPLE\$ 
```

nothing to fancy, but then i'm a minimalist.

closing for now. appreciate the solve! warp is fabulous!
