### ISSUE TITLE
bash: command not found

### ISSUE THREAD

**Issue by thetonywu** [warpdotdev/Warp#2256]
### Describe the bug

Totally new to Warp. Install it and open the terminal (bash). The very first command works, every subsequent command ends up with the same type of error, eg

```
bash: 09:21:37: command not found
```

### To Reproduce

1. open terminal
2. type any command
3. type another command
4. error

### Screenshots

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/4994276/204714770-8b0ddad4-6431-4866-aca0-62f5c3432a61.png">

### OS Version

11.4

### Shell Version

bash

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @thetonywu , My guess is that you normally have a [custom prompt, theme, or plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table) This may be causing the errors in your input editor

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs.

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# Whatever you want to disable

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

Please let me know if this helps with your issue.

**Comment by thetonywu** [comment]
@dannyneira that makes sense. It's just a timestamp. Seems like it should be supported? I can use this workaround for now but it seems like a basic use case that should be supported?

**Comment by dannyneira** [comment]
> @dannyneira that makes sense. It's just a timestamp. Seems like it should be supported? I can use this workaround for now but it seems like a basic use case that should be supported?

I understand the use case, I suggest your try the starship.rs prompt as it's supported in Warp and let's you setup all kind of information in the prompt.

See more in our docs
https://docs.warp.dev/features/prompt

**Comment by elviskahoro** [comment]
@thetonywu does this still happen to you david added some fixes for right sided prompts
