### ISSUE TITLE
Low performance executing basic commands

### ISSUE THREAD

**Issue by akaspi** [warpdotdev/Warp#2258]
### Describe the bug

running simple commands, like "echo", takes more than a second to execute.

### To Reproduce

1. open warp
2. type `echo "abc"`

### Expected behaviour

Should run immediately.

### Screenshots

<img width="268" alt="image" src="https://user-images.githubusercontent.com/6525513/204799100-c25fa172-df06-4c6c-a5b4-4f7fbca92791.png">

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by arckid** [comment]
I am having same Issue with almost similar platform. Mac M1 Pro, OS 13.0.1. Its running too slow. If I open "htop" fps is too slow.

**Comment by dannyneira** [comment]
Hi all, thanks for letting us know. You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs and if it improves performance than there may be something in your dotfiles you need to disable for Warp.

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# Whatever you want to disable

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by akaspi** [comment]
Thanks for the quick reply!
I've uninstalled Zsh and it seems to solve the issue.
Don't know yet which plugin caused this issue, (might be one of the defaults) but I'll check, and if I'll find something I'll post it here.

Closing the ticket. Thanks!

![image](https://user-images.githubusercontent.com/6525513/204984206-b3bd127a-9b22-4b61-8e8d-954a1b0dd7a7.png)
