### ISSUE TITLE
First time user onboarding

### ISSUE THREAD

**Issue by shankarshastri** [warpdotdev/Warp#226]
### Describe the solution you'd like?

```shell
It's a very good feature to have first-time user onboarding to applications, which clearly explains how to use WARP effectively and where to find things on the WARP app.
```

### Is your feature request related to a problem? Please describe.

```shell
Feature enhancement to make users comfortable with the application in real time. I understand that there will video recordings which will help in onboarding. But getting a user do things within the App, will let the user use and learn the app within the app itself.
```

**Comment by elviskahoro** [comment]
I had an idea that relates too this too. Having profiles / personas that are associated with keybindings, specific config settings (changing defaults) that would help users coming in from certain IDEs, shells, etc. (fish, emacs for example). I talked a little bit about it here so I'm just gonna reference.
https://github.com/warpdotdev/warp/issues/30#issuecomment-917173997

> Idea - Default Keybinding Profiles.
Situation: I use tmux primarily for session management and would not mind using native session management as an alternative, if I'm able to keep the tmux bindings I'm used to. However, some bindings may clash with Warp's default keybindings, maybe in the config file there could be default keybinding profiles to help people ramp up and make a switch from their various and different tools.
Tmux is the first one that comes to mind for me, looking forward to ppl's feedback on this.

**Comment by elviskahoro** [comment]
Linking:
- #254

**Comment by elviskahoro** [comment]
Gonna close this as it's an internal project that the team is working on.
