### ISSUE TITLE
Keyboard input lag inside Kubernetes container

### ISSUE THREAD

**Issue by jkdv** [warpdotdev/Warp#2261]
### Discord username (optional)

primitiveman

### Describe the bug

I can feel there's a noticeable keyboard input lag when I type in a bash shell inside a kubernetes container. It can become worse when I open another interactive application in the bash, e.g. psql--PostgresSQL client.

### To Reproduce

kubectl exec -it <kubernetes pod name> -c <container name> -- bash -c 'psql -h <hostname> -U <username> -W <password>'

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @jkdv, we are tracking this issue here > #64 
Unfortunately, we don't have full subshell support for Blocks/Autocomplete/etc and this may be what's affecting your performance.

Closing as duplicate, but please sub to the issue above for more updates.

**Comment by jkdv** [comment]
> Unfortunately, we don't have full subshell support for Blocks/Autocomplete/etc and this may be what's affecting your performance.

Looking at the issue in #64, I can't quite figure out if they are related to keyboard input lag. While might be because I didn't look into Warp implementation, could you briefly describe how the lack of subshell support could contribute to a noticeable keyboard input lag?
