### ISSUE TITLE
Exit code bug on custom prompt

### ISSUE THREAD

**Issue by jagill** [warpdotdev/Warp#2266]
### Describe the bug

In my normal terminal, I display the exit code of the last command.  This is a key tool in my workflow.  In Warp, it does not populate.

If I use starship, it populates _one command late_, which is quite misleading.

I use zsh, and my (somewhat extensive) promptfile can be found at https://github.com/jagill/dotfiles/blob/master/zsh_prompt

### To Reproduce

1. Use https://github.com/jagill/dotfiles/blob/master/zsh_prompt as a prompt file, or one significantly reduced.
2. Issue a command with a non-0 return code.  Note that the prompt has a green "0" instead of a red number reflecting the return code.

### Expected behaviour

I expect to see a red number reflecting the return code.

### Screenshots

iterm2:
<img width="311" alt="Screen Shot 2022-12-01 at 8 24 15 AM" src="https://user-images.githubusercontent.com/495664/205065683-e3617534-b74a-499e-bae7-745a0b6fcfd3.png">

warp:
<img width="700" alt="Screen Shot 2022-12-01 at 8 24 06 AM" src="https://user-images.githubusercontent.com/495664/205065771-f8c5f548-a20d-4c7c-b2a4-f10b67cfa1b4.png">

iterm2 w/ starship:
<img width="312" alt="Screen Shot 2022-12-01 at 8 26 22 AM" src="https://user-images.githubusercontent.com/495664/205065791-601bda03-721b-439b-90b0-d81f77cd7232.png">

warp w/ starship:
<img width="361" alt="Screen Shot 2022-12-01 at 8 26 50 AM" src="https://user-images.githubusercontent.com/495664/205065800-52524098-a17c-4062-a2af-51ee6438588e.png">

### Operating System

MacOS

### OS Version

MacOS Monterey 12.6.1 (21G217)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi! Thanks for submitting. although we do support Starship prompt, we currently don't support multi-line prompts in Warp. Please see more below on that and how to troubleshoot.

https://docs.warp.dev/features/prompt#multi-line-and-right-sided-prompts
https://youtu.be/NfggT5enF4o?t=576

Closing as duplicate #1015

**Comment by jagill** [comment]
@dannyneira Apologies if my report was misleading, but I was specifically _not_ talking about multiline.  I was talking about the exit code.  It also happens that the prompt was multiline, but I don't believe any part of the bug report mentioned that?  If I did, I apologies and please point it out so that I can correct it.

**Comment by dannyneira** [comment]
Yeah sorry about the misunderstanding, i noticed the multiline prompt on the screenshots, but that is ultimately why youre not seeing the right exit code imo. Once you address that it should be good, please feel free to reopen and let us know if thats not the case. We will need more details to reproduce the error.
