### ISSUE TITLE
Keyboard shortcuts in settings are wrong

### ISSUE THREAD

**Issue by tricki** [warpdotdev/Warp#2267]
### Describe the bug

The keyboard shortcuts for changing font size (and some others) shown in settings don't respond to the ones shown in the menu bar. The ones in the menu correspond with the actual keys on my keyboard (German layout), the ones in Warp seem to be the same key but on US keyboards.

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/523154/205037334-6047f7a6-7b58-4382-aa96-c619c1965a06.png">

### To Reproduce

1. Change the keyboard layout to something other than US (e.g. German)
2. Open Warp and go to Settings -> Keyboard shortcuts
3. Compare the shortcuts in the menu with the ones in Warp

A good one to check is the A.I. Command Search which by default uses the bottom left key.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/523154/205051006-e02bb5ac-be7f-4641-b12e-2a1ffeb38f2e.png">

### Expected behaviour

The keyboard shortcuts displayed in Warp should correspond to the current keyboard format.

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment]
Hi! this is a known issue, please sub and 👍 to track the issue > #341

We don't yet have full support for international keyboards. closing as duplicate.
