### ISSUE TITLE
history autocomplete have small rows and it doesn't show the whole command

### ISSUE THREAD

**Issue by Hamzablm** [warpdotdev/Warp#2269]
### Describe the solution you'd like?

```text
Most of the commands I type are long, and I want to see the whole command in the history, not just a portion of it.

Allow is to make the autocomplete bigger.
```

### Additional context

Example of long commands that I would like to see in the history autocomplete:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/32052228/205153470-7aee98bb-6ab2-41b4-a2ca-40170de1e20e.png">

Right now, the autocomplete history shows them cropped, which is annoying, and I don't know which command is the right one. 

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

Ignore

**Comment by dannyneira** [comment]
Hi @Hamzablm Thanks for this request, closing in favor of duplicate #1405

Please :+1:  that request as it helps us gauge interest. We will post any updates there.
