### ISSUE TITLE
Warp quits after pressing Cmd + Q without any warning

### ISSUE THREAD

**Issue by srini-leanfolks** [warpdotdev/Warp#2273]
### Discord username (optional)

msv96#6715

### Describe the bug

Warp quits after pressing Cmd + Q without any warning like those in iTerm2 or Mac terminal.

This option is necessary and also another option in settings to warn multiple tabs or windows before quit.

### To Reproduce

Run an app in warp and use press Cmd + W or Cmd + Q

### Expected behaviour

It should warn us before closing the window or tab about the running process

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.29.08.03.stable_01

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi thanks for this request, we will track this duplicate issue here: #197 
Please :+1:  that request as it helps us gauge interest. We will post any updates there.

**Comment by dannyneira** [comment]
Hi thanks for this request, we will track this duplicate issue here: #197 
Please :+1:  that request as it helps us gauge interest. We will post any updates there.
closing as duplicate.

**Comment by elviskahoro** [comment]
This was launched! Please give it a try. You'll primarily see it when you have a process that is already running and you accidentally close Warp
