### ISSUE TITLE
Terragrunt commands because of user interaction?

### ISSUE THREAD

**Issue by seagullmouse** [warpdotdev/Warp#2277]
### Describe the bug

Running terragrunt across a bunch of modules just hangs after user input
```
terragrunt run-all apply --terragrunt-working-dir ../infra
... 
Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n) y
... 
Hangs, nothing happens
```

Works fine in iTerm2.

### To Reproduce

See above

### Operating System

MacOS

### OS Version

12.6.1

### Shell Version

zsh 5.9

### Warp Version

v0.2022.11.29.08.03.stable_01

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi! thanks for letting us know! we may need more detailed repro steps as most of us don't have this kind of environment setup. We will post any further updates on this thread.

**Comment by seagullmouse** [comment]
I updated to the latest version of Warp this morning and this bug has gone away.

v0.2022.11.29.08.03.stable_03

Thanks
