### ISSUE TITLE
Should remember last opened monitor on multi-display setup

### ISSUE THREAD

**Issue by naytun** [warpdotdev/Warp#2284]
### Describe the solution you'd like?

```text
It would be nice if Wrap can remember which monitor it was last opened on, in multi-monitor setup. Thanks!
```

### Is your feature request related to a problem? Please describe.

```text
It's a bit annoying to move the windows to different monitor everytime I open Warp.
```

### Additional context

Only in Multi-display setup

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi thanks for this, We have a duplicate request here: https://github.com/warpdotdev/Warp/issues/2042

Please :+1:  and subscribe to that request as it helps us gauge interest. We will post any updates there.

If I can recommend a workaround, something like [Rectangle](https://rectangleapp.com/) can be used to quickly snap windows to a certain position. We also have a [Global Hotkey Window](https://docs.warp.dev/features/windows/hotkey-window) feature that can set a window to show up in a certain monitor/position with a keyboard shortcut.

**Comment by naytun** [comment]
Thanks for the reply. I'll do that.
