### ISSUE TITLE
brew completions does not work

### ISSUE THREAD

**Issue by Reoooh** [warpdotdev/Warp#2287]
### Describe the bug

When I use the warp completions function, there is a brew completions phenomenon that I can't succeed. But I find brew commands is full of support form https://docs.warp.dev/features/completions. So I think this might be a bug.

### To Reproduce

input brew and then use TAB.
There should output some brew command completions but only my File Directory.

### Expected behaviour

brew command completions

### Screenshots

<img width="956" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/44220955/205421994-d31349e3-594c-41ee-a34e-9c5e601fb738.png">

### Operating System

MacOS

### OS Version

11.7.1

### Shell Version

zsh 5.9

### Warp Version

v0.2022.11.29.08.03.stable_03

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

**Comment by dannyneira** [comment]
Hi @Reoooh Thanks for letting us know. I will bring this up with the team.
May you please run `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs, then try completions again and let us know if the issue persists.

**Comment by Reoooh** [comment]
> 

Thanks for your reply! This does solve the problem to a certain extent. But I won't be able to use another terminal because of this, and I'm looking forward to a more elegant solution.
All in all, thanks again😃
