### ISSUE TITLE
MacOS 'scp' path autocomplete is not working

### ISSUE THREAD

**Issue by unbreakabl3** [warpdotdev/Warp#2288]
### Describe the bug

When trying to provide a local path to copy files from, the autocomplete is not working. 

### To Reproduce

Start to type any path (for example /Users) after a forward slash `scp /`

### Expected behaviour

Terminal should complete the path, like its doing it with `cd /Users`

### Operating System

MacOS

### OS Version

13.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Warp Version

v0.2022.11.29.08.03.stable_03

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi! Sorry about this but I'm not seeing the same on my end. Can you please run `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs. Then provide a video screengrab of the issue.

**Comment by unbreakabl3** [comment]
Hi, @dannyneira .
Thanks a lot for the quick response. Please see the attached video.

https://user-images.githubusercontent.com/13556249/205875257-611fef6c-75e8-4593-be32-f40ba636b18a.mov

**Comment by unbreakabl3** [comment]
That’s correct

**Comment by bybunni** [comment]
I have this same issue on MacOS 13.1 for lots of applications, bibtex, gcc, make, while things like mv, cp, nvim work fine. Disabling `Open completions menu as you type` allows me to Tab complete again.

**Comment by henryxrl** [comment]
Same here. It seems file path autocompletion doesn't work for any commands other than the basic ones such as ```ls```, ```cp```, ```mv``` etc. For example, no completion for commands like ```rsync``` or ```dkpg```. 

As of now, it seems disabling the ```Open completions menu as you type``` is the solution. Please look into this.

**Comment by dannyneira** [comment]
Hey folks, Sorry about the missing completions, please see a list of our supported completions here: https://docs.warp.dev/features/completions#supported-completion-specs

Also, we'll be tracking the missing completions in the following discussion thread #https://github.com/warpdotdev/Warp/discussions/652

Please ⬆️ and comment there if you're also seeing something missing, as it helps us gauge the impact and gather a list of what's missing.

Closing as duplicate.
