### ISSUE TITLE
No completion on Google Drive volume

### ISSUE THREAD

**Issue by lnocera** [warpdotdev/Warp#2289]
### Describe the bug

Completion on `~/Google\ Drive/` using TAB does not show choices. It is working as expected on Terminal.

### To Reproduce

1. type `ls ~/Google`
2. TAB to complete will give `ls ~/Google\ Drive/` as expected
3. TAB again does nothing

### Expected behaviour

TAB in step 3 should work similar to Terminal:

```sh
~ ls ~/Google\ Drive/
My\ Drive/       Shared\ drives/
```

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.29.08.03.stable_03

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi Sorry about this, it's a known issue https://github.com/warpdotdev/Warp/issues/669 not with Google Drive but with spaces in the folder/file name in general. We are working on it and will provide updates on the GH issue above.

Closing as Duplicate.
