### ISSUE TITLE
SSH: Tab completion on SSH makes Warp unresponsive for a few seoncds

### ISSUE THREAD

**Issue by activatedgeek** [warpdotdev/Warp#229]
### Describe the bug

```shell
Tab completion in an SSH terminal appears to visibly make Warp unresponsive for more than a few seconds. Switching to the default terminal does not appear to have this issue, and is able to normally execute tab completion on the same machine.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```shell
1. `ssh` into a machine of your choice.
2. Type `cd ~/<TAB>`
3. Warp becomes unresponsive for a few seconds, but then behaves as it should with completion recommendations.
```

### Operating System

MacOS

### OS Version

11.5

**Comment by elviskahoro** [comment]
Subscribe to (this is where we'll share updates):
- #578

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and provides an easy way for people to get progress updates. As they'll only need to subscribe (GitHub watch) a single issue versus.
