### ISSUE TITLE
Suggest opening the URL to create a pull request upon `git push --set-upstream origin my-branch-name`

### ISSUE THREAD

**Issue by ben-nathanson** [warpdotdev/Warp#2293]
### Describe the solution you'd like?

Warp has a very handy set of `Insert suggested command` rules, particularly around git commands. For example, if I push a branch that doesn't exist yet, Warp will offer `Insert suggested command: git push --set-upstream origin my-branch-name`. But once we `git push --set-upstream origin my-branch-name`, I have to manually copy and paste the link to create a pull request for that branch. We could use automation to make this smoother.

When I do `git push --set-upstream origin my-branch-name`, and there is a response along the lines of `Create a pull request for 'my-branch-name' on GitHub by visiting...`, then Warp offers `Insert suggested command: open https://github.com/my-username/my-repo/pull/new/my-branch-name`.

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

If I may recommend a workaround, I use the GH CLI often to open PRs from the terminal, and I don't need to remember any URLs. https://cli.github.com/ I like to use `gh pr create --web` after pushing the changed to the remote branch. Hope this helps!

**Comment by szgupta** [comment]
Hey @ben-nathanson, that's a very cool idea and definitely do-able! (we're also in the process of open-sourcing our corrections API so that our users can also contribute to this sort of automation!)

**Comment by ben-nathanson** [comment]
@dannyneira thanks for the suggestion! I wasn't aware of the GitHub CLI. I might adopt that in my workflow.

@szgupta that would be fantastic. I'll keep my eyes peeled for that.

**Comment by dannyneira** [comment]
Hey Folks, this feature is out on today's release v0.2023.02.28.08.03.stable_01.

Closing as completed but please let us know if the issue persists.

**Comment by ben-nathanson** [comment]
Thanks @dannyneira and the whole Warp team! I'm using this in my workflow every day now.
