### ISSUE TITLE
Use with Python Textual UI

### ISSUE THREAD

**Issue by jzrake** [warpdotdev/Warp#2297]
### Describe the solution you'd like?

```text
It would be great if Warp were working fully with terminal apps built with Python's textual module. Textual is a sister project to rich. Rich renders perfectly (and fast) in a warp terminal. Textual apps render fast and with correct output, but mouse events are not captured, so most widgets (buttons, scroll views, etc) don't work.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

Also as a possible workaround, make sure you have Mouse and Scroll Reporting enabled as this may help with your use case. https://docs.warp.dev/features/full-screen-apps#mouse-and-scroll-reporting

**Comment by jzrake** [comment]
@dannyneira thanks for the reply. Enabling mouse and scroll reporting totally fixes the issue, it works great.
