### ISSUE TITLE
reprint the directory after execute the command 

### ISSUE THREAD

**Issue by xiegudong45** [warpdotdev/Warp#2298]
### Describe the bug

After I execute source ~/.zshrc, I found that the command line will auto print the directory after I execute the previous command.

![20221205-224513](https://user-images.githubusercontent.com/30063330/205665649-afe0c51f-342a-4306-966f-d70674b64582.gif)

### To Reproduce

1. Open Warp
2. execute `source ~/.zshrc`
3. cd /random/directory

### Operating System

None

### OS Version

osx 13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.29.08.03.stable_03

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @xiegudong45 Thanks for bring to our attention. By any chance are you using any ZSH plugins/custom prompt?

My guess is that you normally have a [custom prompt, theme, or plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table)

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs.

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here <
end
```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by xiegudong45** [comment]
> Hi @xiegudong45 Thanks for bring to our attention. By any chance are you using any ZSH plugins/custom prompt?
> 
> My guess is that you normally have a [custom prompt, theme, or plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table)
> 
> You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files) Run `echo 'ZDOTDIR=/' > ~/.zshenv` This forces Zsh to run with zero configs.
> 
> You can disable parts of your dotfiles just for Warp by using this conditional statement:
> 
> ```shell
> # Bash and Zsh
> if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
> # > What you want to disable here <
> fi
> ```
> 
> ```shell
> # Fish
> if test "$TERM_PROGRAM" != "WarpTerminal"
> # > What you want to disable here <
> end
> ```
> 
> We have a list of incompatible tools here: https://docs.warp.dev/help/known-issues#list-of-incompatible-tools And more info on custom prompts here: https://docs.warp.dev/features/prompt

Thanks, the instructions are really helpful.
