### ISSUE TITLE
Discussion: Full support of Vi / Vim / Neovim Performance

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/warp#230]
### Describe the solution you'd like?

```shell
Vim Speed + Performance similar to alacritty.
```

### Is your feature request related to a problem? Please describe.

```shell
My full Vimrc with various plugins installed, performs noticeably slower in Warp compared to Alacritty. I removed the plugins but kept sensible vim settings from the vimrc to test scrolling time with a base vimrc. Without plugins the difference is not as pronounced and not to the detriment of usability, but with plugins it was very noticeable and led to me using alacritty for text editing related tasks.
```

### Additional context

Results

Alacritty - 59 seconds
08:05:20
08:06:19

Warp - 77 seconds total
08:06:23
08:07:40

~1.3 X - length

**Comment by elviskahoro** [comment]
Video Here: https://elvis.ai/assets/warp_test_01.m4v
Warp - Test
09/23/2021

Vim's Scrolling Speed via Shift + ]
	is considerably slower in warp compared to alacritty.
	Scroll through a large file (pandas-core/generic.py)

Note: Tried to get the display to be as similar as possible (via alacritty.yml) but the warp window displays 49 vim lines and alacritty displays 48 vim lines.
Have a window running TOP under alacritty and warp for the clock.

Alacritty Settings:
	window
		padding: x = 8
		padding: y = 0

	font:
		size: 14.0
		offset: y = 2

Warp Settings:
	font size: 14

-----------------------------------------------------------
" ---------------------- section --------------------------------------- 1
colorscheme monokai

set autochdir
set autoindent
set autoread
set backspace=indent,eol,start
set clipboard^=unnamed,unnamedplus
set cmdheight=2
set colorcolumn=80
set complete-=i
set cursorline
set display+=lastline
set encoding=utf-8
set expandtab
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent
set hidden
set history=1000
set ignorecase
set lazyredraw
set nobackup
set nowritebackup
set nocompatible
set nowrap
set nrformats-=octal
set number
set ruler
set scrolloff=3
set shiftwidth=4
set sessionoptions-=options
set shortmess+=c
set showcmd
set showmatch
set smartindent
set smarttab
set softtabstop=4
set splitright
set splitbelow
set tabstop=4
set viewoptions-=options
set wildmenu
set wrapscan
set viewoptions-=options

" ---------------------- section --------------------------------------- 2
let mapleader = ";"

nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprev<CR>

"remap world
nnoremap j gj
nnoremap k gk
nnoremap gV `[v`]
nnoremap dil ^d$

" File Explorer usage
let g:netrw_banner = 0
let g:netrw_liststyle = 4
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 80

" ---------------------- section --------------------------------------- 3
set incsearch
if maparg('<C-L>', 'n') ==# '' " incsearch  Use <C-L> to clear the highlighting of :set hlsearch.
  nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
endif

" ---------------------- section --------------------------------------- 4
" has
if has('autocmd')
  filetype plugin indent on
endif
if has('path_extra')
  setglobal tags-=./tags tags-=./tags; tags^=./tags;
endif
if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

" ---------------------- section --------------------------------------- 5
" if
if &encoding ==# 'latin1' && has('gui_running')
  set encoding=utf-8
endif
if &listchars ==# 'eol:$'
  set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
endif
if !&scrolloff
  set scrolloff=1
endif
if !&sidescrolloff
  set sidescrolloff=5
endif
if &t_Co == 8 && $TERM !~# '^Eterm' " Allow color schemes to do bright colors without forcing bold.
  set t_Co=16
endif
if v:version > 703 || v:version == 703 && has("patch541")
  set formatoptions+=j " Delete comment character when joining commented lines
endif
if empty(mapcheck('<C-U>', 'i'))
  inoremap <C-U> <C-G>u<C-U>
endif
if empty(mapcheck('<C-W>', 'i'))
  inoremap <C-W> <C-G>u<C-W>
endif
if !empty(&viminfo)
  set viminfo^=!
endif

" ---------------------- section --------------------------------------- 6
let python_highlight_all=1
au BufNewFile,BufRead *.py;
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |
    \ set list listchars=tab:▷⋅,trail:⋅,nbsp:⋅ |

au BufNewFile,BufRead *.js,*.html,*.css
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \

**Comment by CalgaryMichael** [comment]
x-post from [Discord message](https://discord.com/channels/851854972600451112/852251449068486773/895014131239886929):

Small visual bug that I had noticed when using vim (v 8.2) on Warp. You can see the cursor is bouncing around at random when scrolling on a file. Does not seem to have any affect besides visual -- when you stop scrolling, the cursor is in the correct location.

https://user-images.githubusercontent.com/8285462/136083815-77e90a1a-0818-427c-9630-a593c89706b5.mov

Let me know if you need another further information (vim plugins, etc.)

**Comment by S15** [comment]
Ran into similar performance issues using with vim + warp. I see slow scrolling, slow cursor movement, and slow input. I was directed to this ticket to add information. What I am seeing _appears_ to be related to having a (drawing a?) background color.

I `set termguicolors`, and use a custom color scheme. I link (most of) the rest of the highlight groups against the Normal group, and I set the Normal highlight group to:

```viml
hi Normal guifg=#bbbbbb guibg=#333333 gui=NONE
```
Changing Normal to: 
```viml
hi Normal guifg=#bbbbbb guibg=NONE gui=NONE
```

seems to resolve the performance problems.

**Comment by Caprowni** [comment]
Just wanted to chime in on this after experiencing the same issues with lag using Vim, using the fix @S15 mentioned above worked for me also, speed increased to what I would expect!

**Comment by gagata** [comment]
oddly enough i most often hit the issues (gettiing a rainbow circle and all) when pressing `backspace` or switching between modes.

**Comment by elviskahoro** [comment]
From discord #vim-users 11.13.2021
> I can't use ctrl-6 to go back to my latest buffer in nvim. This works in all other terminals I've used so far. 
>  map <C-6> <C-^> even adding this to my init.vim doesn't change anything...
>  <C-^> works but <C-6> doesn't
