### ISSUE TITLE
Move panes using mouse 

### ISSUE THREAD

**Issue by EmmaPuls** [warpdotdev/Warp#2303]
### Describe the solution you'd like?

```text
I would like to be able to arrange the panes in my Warp window using my mouse.
```

### Is your feature request related to a problem? Please describe.

```text
It's annoying that I have to close my windows and reopen them to reshape or re-order my panes.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Also, if you find yourself having the same panes set up all the time, look into the [Launch Configuration](https://docs.warp.dev/features/sessions/launch-configurations) feature. may help with saving/restoring different windows/tabs/panes.

**Comment by Koziar** [comment]
+1

Would be nice to be able to organize the split panes by dragging them with a cursor (or keybindings), similar to how it works in iTerm2

**Comment by dannyneira** [comment]
We have a issue tracking this here: #623 

Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
