### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by OmerFlame** [warpdotdev/warp#231]
Apart from custom themes (which I am aware are coming soon and it's awesome), could you add custom font support down the line?

Thank you for everything!

**Comment by alokedesai** [comment]
Hey @OmerFlame, thanks for filing! What specifically are you looking for in custom fonts? 

We already support using any monospace system font within the settings menu

**Comment by OmerFlame** [comment]
I literally just got help from Kevin in the public Discord, all is resolved now!

Though, I would suggest that you clarify this, as it's not obvious from first glance.

I will mark this issue as closed now. Thank you again!
