### ISSUE TITLE
ZSH custom shell doesn't respect LF

### ISSUE THREAD

**Issue by Dynom** [warpdotdev/Warp#2312]
### Discord username (optional)

Dynom#1627

### Describe the bug

Neither:
```zsh
PS1="$FG[032][%~] \n$FG[237]%n@%m $FG[105]$%{$reset_color%} "
```
which results in:
```warp
WARP_PS1=$'%{\C-[[38;5;032m%}[%~] \\n%{\C-[[38;5;237m%}%n@%m %{\C-[[38;5;105m%}$%{\C-[[00m%} '
```

nor:
```zsh
PS1='$FG[032][%~] 
$FG[237]%n@%m $FG[105]$%{$reset_color%} '
```
Which results in
```warp
WARP_PS1=$'$FG[032][%~] \n$FG[237]%n@%m $FG[105]$%{$reset_color%} '
```

Result in the same behaviour that I've come to expect:
![Screenshot 2022-12-07 at 13 21 40](https://user-images.githubusercontent.com/39014/206181044-25fc5a8e-1aa5-4502-ad92-bfd8e155e8a4.png)

### To Reproduce

^

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.9

### Warp Version

v0.2022.11.29.08.03.stable_03

### Does this block you from using Warp daily?

No

### Known issue?
I suppose this falls under the [Known Issues](https://docs.warp.dev/features/prompt#multi-line-and-right-sided-prompts). However I consider the items listed much more advanced than multiline. Perhaps supporting two prompt lines is achievable before a fully interactive prompt (-:

**Comment by dannyneira** [comment]
This is a known issue with multi-line prompt #1015. I tried your PS1 setting and wasn't able to reproduce it, are you using any ohmyzsh themes or plugins by any chance? 

My guess is that you normally have a [custom prompt, theme, or plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table)

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs.

Closing as duplicate, please track this status on the issue above.
