### ISSUE TITLE
the hotkey window binding feature does not work in multi-language layouts

### ISSUE THREAD

**Issue by beshkenadze** [warpdotdev/Warp#2313]
### Describe the bug

The hotkey binding only works on the en keyboard layout.

### To Reproduce

1. Open Settings
2. Go to Features
3. Switch the keyboard layout to non-english layout (ex. cyrillic)
4. Try to bind the key
5. Nothing happens/you can't bind the key

### Expected behaviour

The hotkey window works on any active keyboard layout (like iTerm2).

### Operating System

MacOS

### OS Version

13.0.1 (22A400)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.29.08.03.stable_03

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @beshkenadze Thanks for submitting, this is a known issue with keybinds on international kb layouts in general #341

Unfortunately not supported at this time, but you can track this in the issue above. Closing as duplicate.
