### ISSUE TITLE
poetry shell starts powerlevel10k 

### ISSUE THREAD

**Issue by Podidiving** [warpdotdev/Warp#2315]
### Describe the bug

Hi everyone!

I was playing around with poetry and faced the next issue: when I start `poetry shell` it invokes powerlevel10k theme and it sort of breaks my terminal style:

I have [powerlevel10k](https://github.com/romkatv/powerlevel10k) installed on my Mac for my iterm.

This is how my warp looks like before:
<img width="988" alt="image" src="https://user-images.githubusercontent.com/26285240/206291778-0dc3b9cb-1ffd-4a5c-b24e-dc137138d2e2.png">

This is how my warp looks like right after I run `poetry shell`:
<img width="1166" alt="Screenshot 2022-12-08 at 00 45 56" src="https://user-images.githubusercontent.com/26285240/206292404-2c383a9e-deeb-4b90-9b25-292951663acc.png">

So, it looks like, when creating a new virtual environment `poetry` invokes `powerlevel10k` and it overwrites my terminal settings.
Additional headache is that with powerlevel theme my terminal fails to render some characters properly.
I am not sure, though, if it is a really bug, but it looks like one to me.

Thanks in advance for response!

### To Reproduce

1. install powerlevel10k - https://github.com/romkatv/powerlevel10k
2. install poetry: `curl -sSL https://install.python-poetry.org | python3 -`
3. run `poetry shell`

### Expected behaviour

Terminal settings doesn't change

### Operating System

MacOS

### OS Version

13.0

### Shell Version

5.8.1

### Warp Version

v0.2022.11.29.08.03.stable_04

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @Podidiving Thanks for letting us know, We have an issue with subshell support ( which includes poetry ), and you can track it here: #64 

For the plvl10k issue, it's not currently supported so you'll have to disable that part of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# >> plvl10k code here <<
fi
```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts we support here: <https://docs.warp.dev/features/prompt>

Closing as duplicate https://github.com/warpdotdev/Warp/discussions/422
