### ISSUE TITLE
Core: Memory Leak

### ISSUE THREAD

**Issue by AFutureD** [warpdotdev/warp#232]
### Describe the bug

```shell
When I open the Wrap, the memory usage start growing and up to 24GB.
```

### To Reproduce

Steps to reproduce:
1. Open Warp
2. Wait

### Expected behaviour

stable memory usage

### Screenshots

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/17228538/135209574-8542bf63-c762-4114-9ca5-bd6ff36f7663.png">

### Operating System

macOS 11.4 

### OS Version

macOS 11.4

**Comment by zheng** [comment]
Hey @AFutureD, in general runaway memory usage is a known issue - that we're going to prioritize in the future. When did this happen to you?

I think a lot of users get by restarting the app periodically.

**Comment by joshchngs** [comment]
I opened Warp for the first time, did nothing in the first tab (separate issue), opened a second tab.
Commands issued were just basic ls, cd, git log. Tried some commands not in PATH (tig, brew, htop).

<img width="452" alt="~55GB memory usage" src="https://user-images.githubusercontent.com/16120047/136070461-2bbbdb69-a2a3-43c3-b101-87c68717635a.png">

Reopened Warp to find the feedback link. Issued no commands. Typed the above (2 mins ish).

<img width="475" alt="~18GB memory usage" src="https://user-images.githubusercontent.com/16120047/136070635-8c3a713e-05d1-4d71-ac77-6e605daaa898.png">

**Comment by zheng** [comment]
Hey @joshchngs, if you're not issuing any commands, I'd guess your shell is doing a bunch of work. What happens if you force it to do nothing (i.e. put this in the first line of `~/.zshenv`)?

`ZDOTDIR=/`

We've gotten a few reports about memory usage blowing up without doing anything. So I'd love to narrow it down a bit.

**Comment by joshchngs** [comment]
No difference. I normally use fish shell, so the only thing in `~/.zshenv` was the Cargo env call inserted by rustup.

I'm on arm64. If you send me a binary signed with the right entitlements, I can run Instruments on it.

**Comment by elviskahoro** [comment]
@AFutureD this fix will be coming out this wednesday. let us know if you're still having trouble after you update.

**Comment by kevinyang372** [comment]
@joshchngs @AFutureD Checking in since we just released an update that should fix this issue. Are you guys still experiencing memory leak after updating Warp?

**Comment by AFutureD** [comment]
@kevinyang372 

During the 24-hour experience, this issue was never happened.
