### ISSUE TITLE
File completion for directory names with spaces

### ISSUE THREAD

**Issue by mstankus** [warpdotdev/Warp#2321]
### Describe the bug

File completion does not work when a directory in the relative path has a space.

### To Reproduce

1. mkdir -p Try\ Me/Hi
2. cd Try\ Me/H AND then type tab key.

### Expected behaviour

Perform file completion.

### Operating System

MacOS

### OS Version

12.6.1

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2022.11.29.08.03.stable_07

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @mstankus, Thanks for submitting this. This is a known issue that can be tracked here: #669 

Please sub to that issue for updates. Closing as duplicate.
