### ISSUE TITLE
Ability to dismiss the Update notification

### ISSUE THREAD

**Issue by jessecoddington** [warpdotdev/Warp#2324]
### Describe the solution you'd like?

```text
Would like an option to dismiss the update notification and/or have an option to not show the update banner.
```

### Is your feature request related to a problem? Please describe.

```text
It blocks the top text of the terminal
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @jessecoddington Thanks for this request, you can track the progress of this option in the following issue. #1991
