### ISSUE TITLE
ssh remote encoding bug

### ISSUE THREAD

**Issue by snowair** [warpdotdev/Warp#2326]
### Describe the bug

![企业微信截图_c5995ffe-b9f3-4ab5-980b-7f73eaa2c934](https://user-images.githubusercontent.com/1695133/206829457-1ffbd902-a9c5-4d6c-b129-8928b1971956.png)
Run `ls` in a ssh remote server.
The left is Warp terminal,  right is other terminal.

### To Reproduce

1.  ssh to a linux remote server. 
2. run `ls`  to show the chinese filename/dirs.

Note: you can create a test file by this:

```
touch 中文文件名测试.txt
```

### Operating System

None

### OS Version

Centos 8.2

### Shell Version

GNU bash, version 4.4.19

### Warp Version

v0.2022 12 06

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by snowair** [comment]
export LC_CTYPE=en_US.UTF-8

**Comment by dannyneira** [comment]
Thanks for letting us know, Feel free to reopen if the issue persists.
