### ISSUE TITLE
Symlink/aliases open in terminal app instead of link target

### ISSUE THREAD

**Issue by KerryXEX** [warpdotdev/Warp#2327]
### Describe the bug

Since installation of Warp, all symlinks (aliases) on my desktop open the respective folder in terminal app (not warp) instead of opening the link target (application).
Links to folders still open correctly in finder.
I tried to recreate / add new links either with drag&drop or with ln -s but have the same result.

Is there any way to fix this behaviour?

Thanks
Kerry.

### To Reproduce

- Double click on application alias on desktop
-> Terminal.app will open in the target app folder

### Expected behaviour

- Alias traget (Application) will open

### Operating System

MacOS

### OS Version

Ventura

### Shell Version

zsh

### Warp Version

latest

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @KerryXEX 
We're tracking this in this here #102 
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge impact of the bug.

Closing as duplicate.

**Comment by KerryXEX** [comment]
Hi Danny,

I don't think this is a duplicate to the feature request regarding "open here..." from finder.
My issue is an issue that existing App aliases on desktop don't work anymore and instead open the terminal (not 'Warp).

**Comment by dannyneira** [comment]
Sorry about that, let me see if I can repro this and find some workaround. In the meantime, please comment with a video of the issue so we can have a better idea of the problem.

**Comment by KerryXEX** [comment]
Danny,

The issue got resolved now, presumably by the latest macOS Preview update. So it seems it was a macOS issue not related to Warp.

Sorry for the consfusion.

Thanks
Kerry.
