### ISSUE TITLE
View Kubernetes context

### ISSUE THREAD

**Issue by samuelbailey123** [warpdotdev/Warp#2333]
### Describe the solution you'd like?

```text
Powerlevel10k theme allows us to view our kubernetes context when I type a kubectl or helm command. That seems to be missing here... Would be a huge feature win. I believe it's the last thing I would need to switch over from iTerm2.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by samuelbailey123** [comment]
I understand that I can use something like starship or oh my zsh. But I'd prefer it to be native.

**Comment by dannyneira** [comment]
Thanks for this feature request and for clarifying you'd prefer it to be native. Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by samuelbailey123** [comment]
To add to this, it seems that using kubernetes in any capacity with warp just feels like a bad experience. I know K9S specific is already made another issue but even return anything from the control plane feels.... slow. 

And yes it's specific to warp. It works great in iTerm2 or even just terminal.

I really want to use warp but this one is a big show stopper for me.

**Comment by Saeger** [comment]
@samuelbailey123 I know it's not ideal but I have been using aliases bounded to context like:
```
k-dev get po ....
k-prod-eu get po ... 
```
etc

Just an idea to force ourselves to contextualize properly since we don't have the visual feedback from warp.

**Comment by samuelbailey123** [comment]
Interesting idea @Saeger, but I think I'll just wait until it's more along in development

**Comment by dannyneira** [comment]
Thanks for submitting this @samuelbailey123 

We'll be closing this issue in favor of #2055 which is also asking for kube context/completions.

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by samuelbailey123** [comment]
Thanks @dannyneira I will thumbs up
