### ISSUE TITLE
ssh connection to server : bash: line 6: od: command not found

### ISSUE THREAD

**Issue by vdvcoder** [warpdotdev/Warp#2334]
### Describe the bug

When i want to ssh into a server i always get this error: bash: line 6: od: command not found
Then i need to switch to ITerm2 to connect to the ssh server.

Error:

```
ssh redacted@redacted.redacted
**************************************************************
*                                                            *
*                                                            *
*               Unauthorized access to this                  *
*               system/network is prohibited.                *
*                                                            *
*                                                            *
**************************************************************
bash: line 6: od: command not found
```

Any help?

### To Reproduce

```
Step 1: ssh redacted@redacted.be

Step 2: Error:
**************************************************************
*                                                            *
*                                                            *
*               Unauthorized access to this                  *
*               system/network is prohibited.                *
*                                                            *
*                                                            *
**************************************************************
bash: line 6: od: command not found
```

### Operating System

MacOS

### OS Version

latest

### Shell Version

zsh --version:  zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v.0.2022.12.06.08.03.stable_01

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
THanks for letting us know @vdvcoder. As a workaround you can disable the SSH Wrapper in Warps `Settings > Features`

**Comment by vdvcoder** [comment]
Thank you @dannyneira , this solved my issue.

**Comment by dannyneira** [comment]
Thanks for letting us know!

**Comment by kdorff** [comment]
I needed to disable this to be able to ssh into my Qnap NAS. I was sort of going in circles trying to fix a non-problem until I tried using iterm2, I thought something had broken on my NAS... Doh.

**Comment by travislee89** [comment]
You need to install `coreutils`.
Warp needs `stty`, `od`, `sort`(full function, the busybox built-in doesn't satisfy), `comm`.
In OpenWrt, the package name is `coreutils-stty` `coreutils-od` `coreutils-sort` `coreutils-comm`.
