### ISSUE TITLE
Mouse Middle Click(scroll) Paste

### ISSUE THREAD

**Issue by oriolcmp** [warpdotdev/Warp#2336]
### Describe the solution you'd like?

```text
It would be nice if it was possible to paste by using mouse middle click(scroll). This option is available in other tools and I'm missing it in Warp.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by trandaison** [comment]
This feature is helpful for me. I would love it to be included in WARP to ❤️
