### ISSUE TITLE
Fish shell takes a long time to respond when switching to Warp

### ISSUE THREAD

**Issue by tylerstillwater** [warpdotdev/Warp#2338]
### Discord username (optional)

TylerS#1178

### Describe the bug

Warp is unresponsive for a seemingly random amount of time when switching back to Warp after a long-running command has completed. Warp also appears not to recognize that a command finished when the window does not have focus.

### To Reproduce

Using the fish shell:

1. Run `sleep 5`
2. Switch to another application
3. Watch `sleep 5` not complete in the background
4. Switch back to Warp
5. Terminal is unresponsive.
6. Hit a bunch of keys and combos and eventually it comes back.

### Expected behaviour

Warp should recognize background commands finished. Warp should also be responsive when I switch back to it from another application.

### Screenshots

https://cln.sh/JZdcDH3BjGpI2orTy8hR

### Operating System

MacOS

### OS Version

12.6.1

### Shell Version

fish 3.5.1

### Warp Version

v0.2022.12.06.08.03.stable_01

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @tylerstillwater I'm unable to reproduce this. 

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs. let me know if that helps resolve the issue.

**Comment by tylerstillwater** [comment]
Hey Danny,

This issue does not occur with zsh. It only occurs with Fish. I can attempt clean configs with Fish as well and see if that addresses the issue.

**Comment by tylerstillwater** [comment]
I've tracked it down to https://github.com/franciscolourenco/done - when this is installed and running, the behavior I recorded goes away.
