### ISSUE TITLE
MOTD is not displayed at all or at least not properly

### ISSUE THREAD

**Issue by JustChris** [warpdotdev/Warp#2346]
### Local Shell and Version

ZSH 5.8.1

### Remote Shell and Version

BASH 4.2.46(2)-release

### Operating System and Version

Local: macOS 13.0.1; Remote: CentOS Linux 7.9

### Warp Version

v0.2022.12.06.08.03.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Include shell xtrace output

[warp-debug.txt](https://github.com/warpdotdev/Warp/files/10215695/warp-debug.txt)

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

**Comment by JustChris** [comment]
That's the MOTD:
```
  _______        _
 |__   __|      | |
    | | ___  ___| |_
    | |/ _ \/ __| __|
    | |  __/\__ \ |_
    |_|\___||___/\__|


WARNING: Unauthorized access to this system is forbidden and will be prosecuted
by law. By accessing this system, you agree that your actions are monitored.

Admin:   root@test.com
Host:    host01.test.com
IPAddr:  10.168.30.1
```

**Comment by dannyneira** [comment]
Thanks for letting us know @JustChris We'll post any updates on this thread.
Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by bartagergely** [comment]
👍

**Comment by artis3n** [comment]
Looks like https://github.com/warpdotdev/Warp/issues/1160 has some additional 👍 , but commenting as requested, I'd like this fixed

**Comment by donCarlosOne** [comment]
This is also something that I'm missing - and need.  A simple fix would be to issue 'cat /run/motd.dynamic' (for Ubuntu) when first logging in.  Being able to specify an initial command to execute (which can be done with iTerm2) would also be useful.

**Comment by Rugbyte** [comment]
So our company uses the MOTD to provide some additional information on the system and the last time ansible was run against it. Seeing the MOTD would be very helpful for us.

**Comment by bdacus01** [comment]
Yep no MOTD...

**Comment by janscarton** [comment]
We also relay on MOTD for important server status messages.

**Comment by MattTheEmp** [comment]
👍

**Comment by Milofax** [comment]
me, too!

**Comment by dannyneira** [comment]
Hey Folks! As of Warp version `v0.2023.05.09.08.03.stable_01' this issue has been resolved. 

Closing but please let us know if there are any further issues.

**Comment by Munchotaur** [comment]
I'd like very much for MOTD *not* to show with every new shell! But the environment variable fix doesn't seem to do the trick :(
