### ISSUE TITLE
Support Hyperlinks (a.k.a. HTML-like anchors) in Warp

### ISSUE THREAD

**Issue by dzmitry-kankalovich** [warpdotdev/Warp#2348]
### Describe the solution you'd like?

```text
Basically, implement this specification https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

iTerm2 supports this as well as [Xterm](https://github.com/xtermjs/xterm.js/pull/4005)

The benefit is that you can leverage such functionality to display otherwise long URLs in a shorter and more concise way. Python's [Rich](https://github.com/Textualize/rich/issues/51) supports such links OOTB, but without terminal support, they're rendered just as normal text.

The idea came from using [starcli](https://github.com/hedyhli/starcli) which renders GitHub links as repo titles, allowing for more effective use of available screen space. Example with **iTerm2**: ![Screenshot 2022-12-13 at 13 17 01](https://user-images.githubusercontent.com/6346981/207315916-87487b87-f561-4cde-8d63-b89478a0426e.png)
```

### Is your feature request related to a problem? Please describe.

```text
Some terminal utilities use HTML anchor-like rendering of links which is not working properly in Warp
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by dandavison** [comment]
I agree @dzmitry-kankalovich, hyperlinks are really useful in the terminal emulators which support them. This issue is actually a duplicate of https://github.com/warpdotdev/warp/issues/176 -- I think it would help to close this one to keep discussion together.

**Comment by kirkbushell** [comment]
Subscribed. There's so many integrations of mine that don't work while working in Warp, making it considerably more difficult to do some common tasks.

**Comment by dzmitry-kankalovich** [comment]
I've closed it so discussion moves to a single issue here https://github.com/warpdotdev/Warp/issues/176
