### ISSUE TITLE
Shell not working when disk is full

### ISSUE THREAD

**Issue by SirTificate** [warpdotdev/Warp#2351]
### Describe the bug

When you log into a server which hardisk is full, the terminal is stuck in "loading prompt" and won't recover.

### To Reproduce

create a VM (ubuntu 20.x in my case)
open the terminal
ssh root@full-server
start typing any command

### Expected behaviour

I expect a terminal to work under any circumstances to be able to fix server related like this one issues as quickly as possible.

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.12.06.08.03.stable_01

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

**Comment by dannyneira** [comment]
Thanks for letting us know @SirTificate 
We're tracking this in this here #1032
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge impact of the bug.

Closing as duplicate.
