### ISSUE TITLE
Default pager does not scroll

### ISSUE THREAD

**Issue by Peechiz** [warpdotdev/Warp#2352]
### Describe the bug

When scrolling `git diff` with my mouse, the screen does not scroll for longer diffs.

### To Reproduce

Context:

I'm using [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) as my pager, so my git config for pager is:
`core.pager=diff-so-fancy | less --tabs=4 -RFX --mouse`

To Repro:

- Install diff-so-fancy with Brew (or similar)
- Set as pager `git config --global --replace-all core.pager 'diff-so-fancy | less --tabs=4 -RFX --mouse'`
- view a long diff
- attempt to scroll with mouse wheel / trackpad

### Expected behaviour

Trackpad / mousewheel able to scroll output.  This works in OSX Terminal.

### Screenshots

While not directly relevant, iTerm has settings that apparently allow this behavior by sending arrow inputs on scroll:
![image](https://user-images.githubusercontent.com/6421349/207401225-6cda2392-49dc-4c29-bf4d-4132ac1c1f59.png)

### Operating System

MacOS

### OS Version

12.6

### Shell Version

5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.12.06.08.03.stable_01

### Additional context

Having to press arrow keys to see my whole diff is killing me

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @Peechiz 

May you please try enabling Mouse and Scroll Reporting and see if that helps with the issue? https://docs.warp.dev/features/full-screen-apps#mouse-and-scroll-reporting

**Comment by Peechiz** [comment]
Oh, my bad.  Everything I've mentioned above is in the context of those two things toggled on.
<img width="494" alt="image" src="https://user-images.githubusercontent.com/6421349/207628573-6be36158-4a6d-4d23-841d-03b971751a46.png">

**Comment by Peechiz** [comment]
Actually, it turns out this was my fault for passing the -X flag to less.  Scrolling works now, closing this issue.
