### ISSUE TITLE
Window background opacity (window transparency)

### ISSUE THREAD

**Issue by mitris** [warpdotdev/Warp#2356]
### Describe the solution you'd like?

```text
I want to be able to change the transparency of a window without a background image.
This feature exists in most popular terminals by default as a basic feature. This is one of the things that keeps me from completely switching to using Warp as my main terminal application.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @mitris We are actually working on this and it should be released in the near future! 
We have an issue tracking this here #17  We'll post any updates there.

Closing as duplicate.
