### ISSUE TITLE
Shift-tab is not interpreted correctly in terminal apps

### ISSUE THREAD

**Issue by jfdoming** [warpdotdev/Warp#2357]
### Describe the bug

When working in an editor such as `vim` or `ed`, pressing shift-tab appears to send the character 0x19 rather than being interpreted as the appropriate control character.

### To Reproduce

1. Open vim: `vim -u NONE`.
2. Type `:vs `, then hold SHIFT and press TAB.
3. Observe that the files in the current directory are not reverse-cycled in Warp.

OR

1. Run `ed`.
2. Hold SHIFT and press TAB.
3. Observe that the resulting character differs between the default terminal app (`^[[Z`) and Warp (`^Y`).

### Expected behaviour

In step 3 above (for `vim`), pressing SHIFT-TAB should reverse-cycle the files in the directory. In step 3 above (for `ed`), I would expect the same character sequence (`^[[Z`) to be sent in both cases.

### Screenshots

Expected:
![terminal](https://user-images.githubusercontent.com/9922514/207526848-a41fb0ad-3a2c-4309-839b-a6e6772161bb.gif)

Actual:
![warp](https://user-images.githubusercontent.com/9922514/207526851-62beb26e-5494-4d58-9d6f-a955b1190e6d.gif)

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)

### Warp Version

v0.2022.12.06.08.03.stable_02

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @jfdoming I was able to reproduce this bug. I'll bring this up with the team and post any updates on this thread.

Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by Omnikar** [comment]
I just found out about Warp and I'll say that, at least for me, this bug is a deal-breaker and I definitely won't be switching to Warp until it's fixed.

**Comment by cgxxv** [comment]
I have tried other terminals on my mac, seems only warp take `shift+tab` for `^Y`, and others are `^[[Z`.

**Comment by princhcanal** [comment]
just downloaded Warp and had the same problem. i use Shift-tab a lot for vim remaps so it's a bit annoying that it doesn't work 😕

**Comment by superspike7** [comment]
Same issue for me, I thought there was something wrong with my nvim config.

**Comment by ParisTheProgrammer** [comment]
Same issue here. @cgxxv I'm not familiar with ^Y and ^[[Z, how would I tell nvim to use ^Y as shift-tab instead until Warp decides to fix this issue?

**Comment by superspike7** [comment]
@ParisTheProgrammer can you share how you do it?

**Comment by ParisTheProgrammer** [comment]
@superspike7 I have this bit of code in a maps.lua file that gets included in my init.lua
The <c-Y> is the one that fixed it for me. Shoutout to @cgxxv for commenting that it was doing control+Y
**Note**: I use 'akinsho/bufferline.nvim' to handle my tabs so it was recommended to me that i use BufferlineCycleNext.


`
function map(mode, shortcut, command)
	vim.api.nvim_set_keymap(mode, shortcut, command, { noremap = true, silent = true })
end

function nmap(shortcut, command)
	map('n', shortcut, command)
end

nmap("<tab>", '<Cmd>BufferLineCycleNext<CR>')
nmap("<s-tab>", '<Cmd>BufferLineCyclePrev<CR>')
nmap("<c-Y>", '<Cmd>BufferLineCyclePrev<CR>')
`

**Comment by denolehov** [comment]
Same issue here.

**Comment by rkshthrmsh** [comment]
Experiencing the same issue.

**Comment by dannyneira** [comment]
Hey Folks! We're tracking this issue here #903 

Please 👍  and comment on that issue going forward to help us track this issue, All updates we have will be posted there.

Closing as duplicate.
