### ISSUE TITLE
When there is no window opened, `new tab` should open a new window

### ISSUE THREAD

**Issue by czj** [warpdotdev/Warp#2358]
### Describe the solution you'd like?

```text
iTerm2 and macOS Terminal apps behave this way :

- you have no Warp opened window at all
- you press the keyboard shortcut for "new tab" (likely CMD + T)
- a new window opens

On Warp, nothing happens. You have to use the "new window" shortcut.

I have 15 years of muscle memory for this behavior / command, and I think many people moving from Terminal / iTerm2 to Warp have it also.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

Also, we do have a [Hotkey Window](https://docs.warp.dev/features/windows/hotkey-window) Feature that may help with your use case in the meantime.

**Comment by elviskahoro** [comment]
This should be fixed, if not it'll be out next week.
