### ISSUE TITLE
SSH: Warp adds --rcfile and other args to ssh commands

### ISSUE THREAD

**Issue by aimichal** [warpdotdev/Warp#236]
### Describe the bug

```shell
Warp seems to add `--rcfile` and other args to my ssh commands, which doesn't work when I run a program remotely via ssh.

For example, `ssh host1 df` fails with `df: unrecognized option '--rcfile'`.
```

### To Reproduce

I ran this:

```
ssh host1 echo
```

and I saw this:

```
exec -a bash bash --rcfile /dev/fd/63
```

### Expected behaviour

```shell
I expected to see nothing:



```
```


### Screenshots

_No response_

### Operating System

_No response_

### OS Version

_No response_

### Additional context

_No response_

**Comment by zheng** [comment]
Hey @aimichal, what's happening here is that Warp uses an ssh wrapper to make blocks work in ssh. You can run `/usr/bin/ssh host1 df` to circumvent this for now.

We definitely need to make this more transparent in the app + explain what's going on, though.

**Comment by elviskahoro** [comment]
@aimichal 
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
