### ISSUE TITLE
CTRL+R window is too narrow

### ISSUE THREAD

**Issue by ostrolucky** [warpdotdev/Warp#2363]
### Describe the solution you'd like?

```text
Make CTRL+C popover use 100% width.
```

### Is your feature request related to a problem? Please describe.

Window for CTRL+C results in view using ~ 30% of available warp window width.

![image](https://user-images.githubusercontent.com/496233/207665283-389e10cc-b8e4-40a7-909d-46f87acfc73f.png)

This issue is not present for history that pops up when pressing up arrow. That one uses 100% - I would expect same from ctrl+r

![image](https://user-images.githubusercontent.com/496233/207665339-8218ec19-7e97-4dd3-8b1b-7772a586e9a0.png)

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for letting us know @ostrolucky 
We're tracking this in this here #1405
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge impact of the bug.

Closing as duplicate.
