### ISSUE TITLE
“Left Option key is meta” breaks Option + ←/→ to navigate terminal command by word

### ISSUE THREAD

**Issue by rlanday** [warpdotdev/Warp#2364]
### Discord username (optional)

rlanday

### Describe the bug

In both macOS Terminal, and in Warp with Preferences → Settings → Features → “Left Option key is meta” disabled, I can hold option and use the left and right arrow keys to navigate a terminal command I’m typing word-by-word. In Warp, “Left Option key is meta” breaks this. macOS Terminal has a similar option in Terminal → Settings → (pick a shell in the list) → Keyboard → “Use Option as Meta key” that does _not_ break this functionality.

### To Reproduce

1. Open Warp
2. Go in Preferences → Settings → Features and enable “Left Option key is meta”
3. Type some words with spaces between them, e.g. “dfs adsf dafs”
4. Try holding the left Option key and pressing the left and right arrow keys. Nothing happens.

### Expected behaviour

Pressing Option + ←/→ should move the cursor to the beginning of the previous or next word, respectively.

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.12.06.08.03.stable_02

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @rlanday We are able to reproduce this bug. Someone from the team and post any updates here.

**Comment by johnib** [comment]
Same here, if there's an ETA please share, thank you!

**Comment by dhairav** [comment]
+1 for this, facing the same. Very used to navigating commands with Option + Left/Right, holding till a release can fix this.
Love how the product is shaping up till then.

**Comment by johnib** [comment]
Can the repo owners update on this priorities of this bug? Maybe an ETA for a fix?

I'm really loving this terminal, but I'm currently compromising on my convenience and productivity in order to use Warp.

**Comment by madhavajay** [comment]
Yeah so far its nice but this and a few other small niggles are almost forcing me back to `iterm2`.

**Comment by tfcace** [comment]
same here

**Comment by dannyneira** [comment]
@adhdalien @madhavajay @tfcace @johnib @dhairav I'll bring this up with the team this week as an issue affecting a lot of users. We'll try and get some engineering eyes on this.

**Comment by johnib** [comment]
Is there an update in this regard? @dhairav

**Comment by dannyneira** [comment]
None yet @johnib , but we will post updates on this thread once this is being worked on. No ETA at this time.

**Comment by johnib** [comment]
> None yet @johnib , but we will post updates on this thread once this is being worked on. No ETA at this time.

I'm willing to contribute here if this may help. You have no idea how this issue ruins my day..

All I need is just a 5m guidance on where this should be fixed.

**Comment by elviskahoro** [comment]
This was launched! Please follow up if Warp is still folks trouble.
