### ISSUE TITLE
Copy git branch from via the Command Palette

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#2371]
### Describe the solution you'd like?

```text
Copy git branch from via the Command Palette
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by elviskahoro** [comment]
This was added today!
