### ISSUE TITLE
The background process output filled as command line input

### ISSUE THREAD

**Issue by shpasser** [warpdotdev/Warp#2375]
### Describe the bug

When I run the following command its output filled as an input in the command line:
```
sleep 1 &
```

### To Reproduce

Run the following command
```
sleep 1 &
```

### Expected behaviour

A background process output should appear in the output window and it should not be filled as an input input in the command line. 

### Operating System

MacOS

### OS Version

12.6.2

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for filling! This is a KI with how our "blocks" feature works--closing this out in favor of https://github.com/warpdotdev/Warp/issues/1387.

We do plan on fixing this, but unfortunately, I can't give a concrete timeline given the eng lift to fix this is very high
