### ISSUE TITLE
add preference to specify color of block border/separator lines

### ISSUE THREAD

**Issue by HotFusionMan** [warpdotdev/Warp#2377]
### Describe the solution you'd like?

```text
I would like to be able to choose my own color for the lines that separate/delimit blocks.
```

### Is your feature request related to a problem? Please describe.

```text
I get a lot of red "error" blocks, and the color of the line (grey) that separates two error blocks does not have enough visibility.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by dannyneira** [comment]
We have an issue tracking this here #617 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
