### ISSUE TITLE
Will you please add quack :duck: mode?

### ISSUE THREAD

**Issue by Austin-SALVATORE** [warpdotdev/Warp#2383]
### Describe the solution you'd like?

```text
I feel like it will be very helpful and nice to have the quack mode, a.k.a to just click a shortcut in order to invoke the terminal overlay or hover on the current desk or workspace
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @Austin-SALVATORE We already have a feature likes Quake mode, its called hotkey window and it can be activated in Warps `Settings > Features` https://docs.warp.dev/features/windows/hotkey-window
