### ISSUE TITLE
Limit the time period for app bar bouncing

### ISSUE THREAD

**Issue by worldwidejamie** [warpdotdev/Warp#2384]
### Describe the solution you'd like?

```text
When developing with a long-running process (Gulp in my case), when an operation finishes, the icon continually bounces, letting me know the operation has been completed. I know the operation has been completed, but the icon continues to bounce until I focus on Warp again.
It would be great if the icon stopped bouncing after 3 or 4 notices.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by vorporeal** [comment]
Yesterday's Warp release includes a change to make the dock icon only bounce once, instead of bouncing until Warp is brought back into focus. :)
