### ISSUE TITLE
Text highlight even when another window is in front

### ISSUE THREAD

**Issue by AlexJWayne** [warpdotdev/Warp#2386]
### Describe the bug

When a clickable file path is present in the terminal, it will highlight based on the mouse position _through_ another applications window.

### To Reproduce

1. Get some terminal output that look like a project file
2. Position a window form another application so that it partially obscures the terminal
3. Move your move in the window of that other application
4. Notice that the file paths are highlighting

### Expected behaviour

Links should highlight only if there is not another window between the link and the mouse cursor.

### Screenshots

https://user-images.githubusercontent.com/482/208793192-47719edb-f8ee-4974-b00c-1c0095a325c7.mov

### Operating System

MacOS

### OS Version

13.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @AlexJWayne I was able to reproduce this issue. 
We'll post any updates on this thread.
Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by elviskahoro** [comment]
This should be fixed, if not it'll be out next week.
