### ISSUE TITLE
Security Vulnerability Detected - Clear History Activity

### ISSUE THREAD

**Issue by sonuame** [warpdotdev/Warp#2387]
### Describe the bug

My security firewalls has detected a suspicious activity and found the below code to be executed on warp connect
ALERT - VM_HistoryFileCleared

`
export TERM_PROGRAM='WarpTerminal'

_user="$(whoami 2>/dev/null || echo $USER)"
_hostname="$(hostname 2>/dev/null || uname -n)"
hook=$(printf "{
"hook": "SSH", "value": {
"socket_path": "~/.ssh/16714319117984", "user": "%s", "machine": "%s", "remote_shell": "%s"}}" "$_user" "$_hostname" "${
SHELL##*/}" | command od -An -v -tx1 | command tr -d " 
")
printf 'eP$d%sx9C' $hook

if test "${
SHELL##*/}" != "bash" -a "${
SHELL##*/}" != "zsh" then
 exec $SHELL
fi

case ${
SHELL##*/} in
 bash) exec -a bash bash --rcfile <(echo 'set -o vi set +o vi HISTCONTROL=ignorespace printf '''eP$d7b22686f6f6b223a2022496e69745368656c6c222c202276616c7565223a207b227368656c6c223a202262617368227d7dx9C'''') 
 
 zsh) WARP_TMP_DIR=$(mktemp -d warptmp.XXXXXX)
local ZSH_ENV_SCRIPT='756e7365746f7074205a4c453b20756e736574205243533b20756e73657420474c4f42414c5f5243533b207072696e746620275c7831625c7835305c7832345c7836343762323236383666366636623232336132303232343936653639373435333638363536633663323232633230323237363631366337353635323233613230376232323733363836353663366332323361323032323761373336383232376437645c78396327'
if [[ $? == 0 ]] then
 if (( ${
+commands[xxd]} )) then
 echo $ZSH_ENV_SCRIPT | command xxd -p -r > $WARP_TMP_DIR/.zshenv
 else
 for i in {
0..$((${
#ZSH_ENV_SCRIPT} - 1))..2} do
 builtin printf "x${
ZSH_ENV_SCRIPT:$i:2}"
 done > $WARP_TMP_DIR/.zshenv
 fi
else
 echo "Failed to bootstrap warp. Continuing with a non-bootstrapped shell."
fi
TMPPREFIX=$HOME/.zshtmp- WARP_SSH_RCFILES=${
ZDOTDIR:-$HOME} ZDOTDIR=$WARP_TMP_DIR exec -a zsh zsh -g 
 
esac
`

I have been asked to stop using the wrap or get a way to not execute this in behind 

### To Reproduce

connect SSH to any box

### Expected behaviour

It shouldn't execute any history clear activity on ssh connect

### Operating System

None

### OS Version

13.1

### Shell Version

5.8.1

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by MaikSoriano** [comment]
Same here. 2 hours ago

**Comment by dannyneira** [comment]
Thanks for the additional details! 

I'll bring this up with the team and discuss if we can prioritize this. AFAIK, 
> Our SSH wrapper removes a line from history (a line that we create, to be clear) as part of setting up a remote shell - we don't want to pollute your shell history with our initialization script.

Closing this in favor of duplicate #1018
