### ISSUE TITLE
Strange border around Neovim

### ISSUE THREAD

**Issue by Brendonovich** [warpdotdev/Warp#2390]
### Describe the bug

After updating to v0.2022.12.13.08.04.stable_01 an empty border has begun appearing when I open neovim. There was previously a border but it was much thinner, it's as if Warp is inserting an extra character of padding horizontally.

### To Reproduce

1. Use neovim with the Warp version about a week prior to v0.2022.12.13.08.04.stable_01.
2. Use neovim with Warp version v0.2022.12.13.08.04.stable_01
3. Hopefully notice the extra padding

### Expected behaviour

A much thinner border that only fills the space that characters cannot.

### Screenshots

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/14191578/208919018-a1fdbec6-e13b-4db9-9461-ae8989f526b7.png">

### Operating System

MacOS

### OS Version

12.5

### Shell Version

5.8.1

### Warp Version

v0.2022.12.13.08.04.stable_01

### Additional context

Would be great if I could downgrade to a version where this doesn't work, it's not a blocker but it's pretty annoying.

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know! We're actually tracking this here: https://github.com/warpdotdev/Warp/issues/2373. TLDR is that it's a tradeoff we decided to make for compatibility and reliability reasons with Alt Screens like `neovim`, `k9s`, etc.

As a workaround, this [thread](https://www.reddit.com/r/neovim/comments/gjuvys/comment/fqov3rt/) has some info on settings you can try to set `neovim` background to match the terminal. ( just like `vim` does ) 

Closing as duplicate.

**Comment by Brendonovich** [comment]
Ah whoops, I looked at previous issues but didn't find that one.

I appreciate the suggestion to adjust my neovim theme, but the colour isn't the problem - the space is. I'd really appreciate if I could just downgrade until the problem is fixed.
