### ISSUE TITLE
Add possibility to remove or reduce bezels

### ISSUE THREAD

**Issue by maksimr** [warpdotdev/Warp#2392]
### Describe the solution you'd like?

```text
Ideally I would like to remove bezels it all to increase working space (like it works in iTerm)
```

## Warp
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/616193/208924969-76456961-b42c-4f2e-bc06-f39cd3ce265c.png">

## iTerm
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/616193/208925424-cbbfa80f-96f4-474c-82a3-0f9cfc2df4cd.png">

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for letting us know! We're actually tracking this here: https://github.com/warpdotdev/Warp/issues/2373. TLDR is that it's a tradeoff we made for compatibility and reliability reasons with Alt Screens like neovim, k9s, etc.

As a workaround, many alt-screen apps allow you to set a background to `None` or `Transparent`, and that should help with the background/border color difference.

Closing as duplicate.
