### ISSUE TITLE
Allow user to log out off or swap accounts ( personal / work )

### ISSUE THREAD

**Issue by czj** [warpdotdev/Warp#2393]
### Describe the bug

There seems to be no way to logout (even by deleting Warp config files) in order to login with a different account.

### To Reproduce

1. You install warp on a new computer
2. You click "login with Google" by mistake
3. You get logged in with a Warp account for something@work-domain.com
4. You realize you where logged in using your Github account (or email login) before
5. You cannot logout of Warp and re-authenticated (tried, it keeps the same account)

### Operating System

None

### OS Version

13.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey, Thanks for letting us know! 
Just run `sudo security delete-generic-password -l "dev.warp.Warp-Stable" $HOME/Library/Keychains/login.keychain`
Sorry, but it's tucked away in our [Uninstall Warp](https://docs.warp.dev/help/uninstalling-warp#removing-warp-login-settings-files-log-and-database) page. We'll look into ways of making an easier solution in the app.

Changing to a Feature Request. Please 👍 +1:  and subscribe to this request as it helps us gauge interest.

**Comment by czj** [comment]
Thanks a lot. That worked well :-)

**Comment by dannyneira** [comment]
Thanks for submitting this @czj 

We already have a request tracking this over at #1883 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
