### ISSUE TITLE
Window size/position not saved when closing/opening the app

### ISSUE THREAD

**Issue by mattbanks** [warpdotdev/Warp#2395]
### Describe the bug

When closing the app or a window and re-opening it, the size and position of the window is not retained. Every launch or new window is a square shape, centered on the screen. I did a fresh install of the app today and have observed this behavior since installing.

### To Reproduce

1. Open the app
2. Resize and reposition the window
3. Close the window
4. Open a new window
5. Observe the new window is in the default square shape in the center of the screen

### Expected behaviour

Window size and position is retained between launches

### Screenshots

![warp](https://user-images.githubusercontent.com/302970/209254121-89deb182-07e4-4cea-9733-996ef195711b.jpg)

### Operating System

MacOS

### OS Version

macOS Ventura 13.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know we have a couple of related issues here: https://github.com/warpdotdev/Warp/issues/2042 & https://github.com/warpdotdev/Warp/issues/1961

Changing to a Feature request, please 👍  if you're interested in this support. As a workaround I recommend you try the [Global Hotkey Window](https://docs.warp.dev/features/windows/hotkey-window)

**Comment by elviskahoro** [comment]
Gonna close this in favor of #2512
