### ISSUE TITLE
non-Latin-based input method will display abnormally

### ISSUE THREAD

**Issue by f820602h** [warpdotdev/Warp#2396]
### Describe the bug

When using a non-Latin-based input method(ex: Chinese Zhuyin input method), the pinyin symbol and word selection list of the input method will display abnormally

### To Reproduce

1. focus on warp's input area
2. just input with a non-Latin-based input method. ex: Chinese Zhuyin input method

### Expected behaviour

show the Zhuyin which is user typing

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.9

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @f820602h  We're tracking this in this here #341 
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge impact of the bug.

Closing as duplicate.
