### ISSUE TITLE
Warn before closing a tab that is running a task.

### ISSUE THREAD

**Issue by RoyRao2333** [warpdotdev/Warp#2397]
### Describe the solution you'd like?

```text
I think it'll be better to warn users before closing a tab that is running a task. Just like Terminal.app does. 😊
```

### Additional context

<img width="739" alt="image" src="https://user-images.githubusercontent.com/31413093/209299626-481e6a60-49fe-449b-a0a0-b4dbc38eb6ba.png">

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for letting us know @RoyRao2333 We're tracking this in this here #197 
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge impact of the bug.

Closing as duplicate.
