### ISSUE TITLE
Warp doesn't resize on resolution changes when used in full-screen mode

### ISSUE THREAD

**Issue by macbem** [warpdotdev/Warp#2399]
### Describe the bug

Warp doesn't handle it well when it's maximized and the resolution changes. I assume that switching the resolution via settings manually is a rare case, but unplugging an external display is quite common, especially in offices etc.

### To Reproduce

1. Open Warp using the macOS green title bar button (maximize or something) on an external display.
2. Unplug the external display
3. Warp is now sized improperly (larger than laptop screen res) and in a weird position. Hovering your cursor on top of the screen should show the title bar so that I can resize the window, but it doesn't show.

OR

1. Open Warp in full-screen mode on any display. Change the resolution in `System Preferences -> Desktop`.
2. If the new res is smaller, Warp doesn't fit on the screen and title bar is not accessible. If the new res is bigger, Warp is now smaller than full-screen, but title bar is accessible.

### Expected behaviour

Warp should handle resolution / display changes when in full-screen mode and resize to fit the screen.

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for this, we have similar issue here: #2381
