### ISSUE TITLE
Support different session encoding

### ISSUE THREAD

**Issue by Ret2rO** [warpdotdev/Warp#2402]
### Describe the solution you'd like?

```text
I used to use iterm2 in the past, but today I find that the warp is great. However, I found that this tool does not support the setting of character encoding. I think this feature is necessary. I hope it can be supported as soon as possible. Thank you
```

### Additional context

![image](https://user-images.githubusercontent.com/59255790/209456353-53d9e136-2284-4048-8442-cf42e9caef05.png)

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi thanks for the heads up, i think may be related to #320

**Comment by Ret2rO** [comment]
> Hi thanks for the heads up, i think may be related to #320

Thank you for your reply. I will close this issue. I will pay attention to the issue you mentioned. Thank you
