### ISSUE TITLE
Improve performance on m1 with stage manager

### ISSUE THREAD

**Issue by taugsbourger** [warpdotdev/Warp#2403]
### Describe the solution you'd like?

```text
It would be nice to optimise the application to be smoothly integrated with the stage manager.
```

### Is your feature request related to a problem? Please describe.

```text
When using Warp and stage manager, the animations are very slow with Warp (Cyber wave theme with a single tab and empty prompt).
I run it on a MacBook Air M1 with 8 GO RAM.

My free memory is 4 GO and CPU Usage less than 10%, so clearly my machine is not suffering while I'm using Warp.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! 
Please :+1:  and subscribe to this request as it helps us gauge interest. 
We will post any updates here.

**Comment by NickantX** [comment]
This seems to be fixed in the latest Warp release

**Comment by vorporeal** [comment]
Glad to hear it!  Please re-open this issue if the problems come back. :)
