### ISSUE TITLE
Warp windows are misplaced when going from one multi-monitor setup to another

### ISSUE THREAD

**Issue by johnib** [warpdotdev/Warp#2409]
### Describe the bug

I have 2 different multi-monitor setup (office and home), with different layouts.

When I open my macbook at home, after I used Warp at office, the Warp windows are misplaced (see example):
This happens only with Warp, the rest of my apps are placed somewhere on my monitors, but in **whole**.

![image](https://user-images.githubusercontent.com/5327862/209622183-54189199-4680-4e60-adf4-4bac6c2184b4.png)

### To Reproduce

1. Have 2 different layouts of monitors
2. Locate Warp somewhere on the monitors
3. Disconnect from the first layout
4. Connect your macbook to the second layout

### Expected behaviour

The Warp windows should appear somewhere on the screens, but in whole.

### Screenshots

![image](https://user-images.githubusercontent.com/5327862/209622376-b0d7c32d-c541-469e-b2d7-730c12999c8e.png)

### Operating System

MacOS

### OS Version

13.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
This appears to be related to #https://github.com/warpdotdev/Warp/issues/2381

Thanks for opening this! closing as duplicate
