### ISSUE TITLE
Full width prompt causes unwanted newline

### ISSUE THREAD

**Issue by Moarram** [warpdotdev/Warp#2410]
### Describe the bug

When the prompt has the same number of characters as `$COLUMNS`, an extra newline is added between the prompt text and the input text
```
prompt
    <-- (unwanted newline)
> input
```

### To Reproduce

1. Use Zsh
2. In the settings, enable "Honor user's custom prompt (PS1)"
3. Set prompt to the same number of characters as the terminal width with `PROMPT="${(pl:$COLUMNS::x:)}"`
4. Observe the bug: unwanted newline between prompt and input

### Expected behaviour

Full width prompt should have the same newline placement as a shorter prompt.
```
prompt
> input
```

### Screenshots

<img width="523" alt="warp-full-prompt-newline" src="https://user-images.githubusercontent.com/24483562/209700004-e31be04e-a38b-4ba9-b0cd-b3659c8f8cdd.png">

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for the heads up, afaik there are some issues with multiline and rprompts. So this may be related. #1015
