### ISSUE TITLE
Background tasks write into the input editor.

### ISSUE THREAD

**Issue by dannyneira** [warpdotdev/Warp#2411]
### Describe the bug

`bg` will write the output of the suspended background tasks into the input editor. 

### To Reproduce

Setup: 
- `cd ~ ; echo '#!/usr/bin/env bash' > test.sh ; echo 'for i in {1..100}; do echo $i; sleep 3; done' >> test.sh ; chmod +x ./test.sh`

Repro:
-`./test.sh`
- Press `CTRL-Z` to suspend
- enter `bg` to run in the background, and notice how the output from the script is written into the input editor.

Teardown:
-`rm ~/test.sh

### Expected behaviour

the output doesn't mix into the input editor.

### Screenshots

https://user-images.githubusercontent.com/16809145/209725784-e74b45ac-4093-45c7-98d2-e1654162bcc0.mp4

### Operating System

None

### OS Version

13.1

### Shell Version

zsh 5.9 (arm-apple-darwin22.1.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Additional context

Based on this thread by @wesbos: https://twitter.com/wesbos/status/1606366308349640707

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by wesbos** [comment]
Thanks a ton @dannyneira  - I think this is a duplicate of this: https://github.com/warpdotdev/Warp/issues/1387

**Comment by dannyneira** [comment]
Missed that one, thanks for mentioning it. closing as dup.
