### ISSUE TITLE
Allow developers/ users to add Completions

### ISSUE THREAD

**Issue by EmmaPuls** [warpdotdev/Warp#2412]
### Describe the solution you'd like?

```text
As a developer that creates their own command line tools,
I would like to be able to add Completions for my own or public CLI tools,
So that I can work faster and improve Warp Completions for all
```

### Is your feature request related to a problem? Please describe.

```text
My coworkers have CLI tools with plugins for other terminal applications for tab-completion. 
We would like to be able to do the same using Warp's interface.

I would personally like to contribute to the list of Completions that you have for public tools.
Much like contributing Workflows.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @EmmaPuls 
We're tracking this in this request here #652  and ultimately the goal is to implement a completion spec that users can contribute to.
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.
Closing as duplicate.
