### ISSUE TITLE
Display the datetime of the command execution

### ISSUE THREAD

**Issue by JesusTheHun** [warpdotdev/Warp#2415]
### Describe the solution you'd like?

```text
When I hover a block, I would like to have the datetime at which this command was executed.
```

### Is your feature request related to a problem? Please describe.

```text
I connect to many servers, I don't want to setup a custom shell prompt.
Even if I did, the prompt will show the time at which it first appeared, not the time at which the command was run.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @JesusTheHun Thanks for the request, we currently show the date/time of the execution by hovering over the prompt. If you'd like for this to show up in the prompt I recommend you try a [supported custom prompt](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table).

**Comment by dannyneira** [comment]
Closing as duplicate #1862

**Comment by UmungoBungo** [comment]
For anyone else that is struggling to get the date/time to show on hover, you need to hover the run-time in particular. It took me awhile to work it out 😅

<img width="582" alt="image" src="https://github.com/warpdotdev/Warp/assets/22192773/62908cc6-8208-420a-bceb-d07acdd23227">

**Comment by john-kurkowski** [comment]
> For anyone else that is struggling to get the date/time to show on hover, you need to hover the run-time in particular.

Note unfortunately the timestamp does not appear on hover with a non-Warp prompt, like Starship.

**Comment by ParkerRex** [comment]
> Note unfortunately the timestamp does not appear on hover with a non-Warp prompt, like Stars

NOOOOOooOoOOOOOOOOOOOOOOOOOo

**Comment by obsidian33** [comment]
> > For anyone else that is struggling to get the date/time to show on hover, you need to hover the run-time in particular.
> 
> Note unfortunately the timestamp does not appear on hover with a non-Warp prompt, like Starship.

Have you found a way to get it to show up with non-Warp prompt, specifically Starship?

**Comment by john-kurkowski** [comment]
No. I switched to Starship printing the datetime aligned right on every prompt. [Example config](https://github.com/john-kurkowski/dotfiles/commit/e3f23f548b9ff69fff6ce239e8e3d42ba98a82f4)
