### ISSUE TITLE
SSH fails with 'Error: exec: "export": executable file not found in $PATH'

### ISSUE THREAD

**Issue by eclecticjohny** [warpdotdev/Warp#2416]
### Describe the bug

```
ssh -p 64535 54.210.9.249
Error: exec: "export": executable file not found in $PATH
Connection to 54.210.9.249 closed.
```

The above is what I receive any time that I try to use SSH from within warp. SSH works as expected in MacOS terminal and in iTerm2.

### To Reproduce

1. Enter ssh command
2. Press enter to run command
3. Receive error output

### Expected behaviour

1. Run ssh command
2. ssh command connects to remote server successfully

### Operating System

MacOS

### OS Version

12.5.1

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by vorporeal** [comment]
@eclecticjohny Hey Johny, what shell is being used on the remote machine?

Warp sets up an alias for `ssh` in your local shell so we can do some magic to upgrade remote sessions with the full set of Warp functionality, but it doesn't always play nicely with certain remote shells/configurations (we're working to improve this).  As a workaround, you could try either explicitly using `/usr/bin/ssh` instead of `ssh` (to bypass the alias), or you can totally disable the SSH wrapper in Settings > Features.

**Comment by eclecticjohny** [comment]
hey @vorporeal thanks for the quick reply. to answer your question here is some outputs from the remote server:

```
ps -p $$
PID TTY          TIME CMD
10604 pts/2    00:00:00 bash
```

```
bash --version
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

i'll probably just bypass the ssh feature or turn off as you suggested for now.

**Comment by eclecticjohny** [comment]
looks like my issues are a result of the known issues around ssh so i'll close this.

**Comment by Greyvend** [comment]
I face the same issue. The remote host is CircleCI Linux with bash.

**Comment by vorporeal** [comment]
Hey @Greyvend, can you share the output you get when you try to SSH?  What shell is being used on the remote machine?

**Comment by danyf90** [comment]
Same error here 🙏

**Comment by awhiteside1** [comment]
Here's the debug output when I try to connect to Circle. Works fine in normal terminal. 

```bash
ssh -p 547XX 44.211.76.XXX -v

.....token exchange.....


Authenticated to 44.211.76.127 ([44.211.76.127]:54782) using "publickey".
debug1: setting up multiplex master socket
debug1: channel 0: new [/Users/alexwhiteside/.ssh/16815058158013]
debug1: channel 1: new [client-session]
debug1: Entering interactive session.
debug1: pledge: id
debug1: Sending environment.
debug1: channel 1: setting env LANG = "en_US.UTF-8"
debug1: Sending command:
                         export TERM_PROGRAM='WarpTerminal'

                                                           _user="$(command -v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER)"
                                                           _hostname="$(command -v hostname >/dev/null 2>&1 && command hostname 2>/dev/null || uname -n)"
                                                                 hook=$(printf "{\\"hook\\": \\"SSH\\", \\"value\\": {\\"socket_path\\": \\"~/.ssh/16815058158013\\", \\"user\\": \\"%s\\", \\"host\\": \\"%s\\", \\"remote_shell\\": \\"%s\\"}}" "$_user" "$_hostname" "${SHELL##*/}" | command od -An -v -tx1 | command tr -d " \\n")
                                                               printf '\033P$d%s\234' $hook

   if test "${SHELL##*/}" != "bash" -a "${SHELL##*/}" != "zsh"; then
                                                                      exec $SHELL
                                                                                 fi

                                                                                   case ${SHELL##*/} in
                 bash) exec -a bash bash --rcfile <(echo 'set -o vi; set +o vi; HISTCONTROL=ignorespace; HISTIGNORE=" *"; printf '\\''\033P$d7b22686f6f6b223a202249[about-40-chars-but-this-looked-scary-to-not-mask-]7b227368656c6c223a202262617368227d7d\234'\\''')
                                                                                 ;;
                                                                                     zsh) WARP_TMP_DIR=$(mktemp -d warptmp.XXXXXX)
                                          local ZSH_ENV_SCRIPT='75
debug1: client_input_channel_req: channel 1 rtype exit-status reply 0
Error: exec: "export": executable file not found in $PATH
debug1: channel 1: free: client-session, nchannels 2
debug1: channel 0: free: /Users/alexwhiteside/.ssh/16815058158013, nchannels 1
Connection to 44.211.76.127 closed.
Transferred: sent 4588, received 1480 bytes, in 0.0 seconds
Bytes per second: sent 97648.2, received 31499.4
debug1: Exit status 1
```

**Comment by danyf90** [comment]
I can confirm it works fine when disabling `Warp SSH Wrapper`

**Comment by kg-currenxie** [comment]
@danyf90 thanks!

**Comment by DecathectZero** [comment]
This is still occuring. Is it possible to reopen?

**Comment by mbrowne** [comment]
This just happened to me as well, trying to connect to a machine running in CircleCI

**Comment by fgmarand** [comment]
Same issue with CircleICI. (`export TERM_PROGRAM='WarpTerminal'` causes: `Error: exec: "export": executable file not found in $PATH`.

When checking that shell

- `echo $SHELL` returns `/bin/sh` 
- `ls -l /bin/sh` returns `lrwxrwxrwx 1 root root 4 Mar 23  2022 /bin/sh -> dash`. Probably https://wiki.archlinux.org/title/Dash

Using `/usr/bin/ssh` works around the problem.

**Comment by lou-daiglecostello** [comment]
Same issue in 2025. Had to disable "Warpify SSH sessions" for SSH to CircleCI docker container to work, otherwise get `Error: exec: "export": executable file not found in $PATH`.
