### ISSUE TITLE
Links sometimes incorrectly detected

### ISSUE THREAD

**Issue by soof-golan** [warpdotdev/Warp#2418]
### Discord username (optional)

soofgolan#4728

### Describe the bug

Hey, in some cases (when there is some non whitspace text after quotes), links are highlighted including the trailing `'` (tick), this makes them not usable with CMD+Click.

This is a very small inconveniece but, you'd still probably want to know :)

<img width="367" alt="image" src="https://user-images.githubusercontent.com/83900570/209950497-b649fa19-f26e-4610-968a-b6db39b6c7a8.png">

### To Reproduce

```shell
echo "'https://example.com',"
```

### Expected behaviour

Link should not include trailing tick `'`
<img width="249" alt="image" src="https://user-images.githubusercontent.com/83900570/209950852-2e07d700-162a-4a38-b173-70b180cda038.png">

### Screenshots

Actual:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/83900570/209950497-b649fa19-f26e-4610-968a-b6db39b6c7a8.png">
Expecetd:
<img width="249" alt="image" src="https://user-images.githubusercontent.com/83900570/209950852-2e07d700-162a-4a38-b173-70b180cda038.png">

### Operating System

MacOS

### OS Version

13.0.1 

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @soof-golan We're tracking this in this here #2331
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge impact of the bug.

Closing as duplicate.
