### ISSUE TITLE
Support for Nu shell

### ISSUE THREAD

**Issue by ghalibansari** [warpdotdev/Warp#2419]
### Describe the solution you'd like?

```text
warp terminal block not working with nu shell
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @ghalibansari Thanks for submitting, this is related to our lack of Subshell support, please track the progress of this here: #64 

:+1: that issue if you're interested in this. It's on the roadmap and being investigated.

Closing as duplicate.
