### ISSUE TITLE
Pure Prompt gets inserted as typeahead

### ISSUE THREAD

**Issue by jpwain** [warpdotdev/warp#242]
### Describe the bug

```shell
When I resize my Warp window, the current directory is inserted into my command edit space. 

One guess is that it's caused by something in my .zshrc -- I'll email this to Aloke to help reproduce.

Video attached.
```

### To Reproduce

Steps to reproduce:
1. Open Warp
2. Clear the text out of the command edit space
3. Resize the window

### Expected behaviour

```shell
Command edit space doesn't get repopulated on window resize.
```

### Screenshots

Video attached.

https://user-images.githubusercontent.com/1234304/135732737-175c6498-7592-4e0a-a544-01ee5a5228e9.mov

### Operating System

MacOS

### OS Version

11.6

**Comment by alokedesai** [comment]
Hi all, closing this since a fix for this just went out today in our most recent release!

**Comment by hpohlmeyer** [comment]
The fix worked, thank you!
