### ISSUE TITLE
channel ##: open failed: administratively prohibited: open failed issue with warp

### ISSUE THREAD

**Issue by Samiran4448** [warpdotdev/Warp#2422]
### Describe the bug

I frequently get these warning messages while using warp over an ssh target.
```
channel 13: open failed: administratively prohibited: open failed
channel 13: open failed: administratively prohibited: open failed
channel 15: open failed: administratively prohibited: open failed
channel 13: open failed: administratively prohibited: open failed
channel 15: open failed: administratively prohibited: open failed
channel 14: open failed: administratively prohibited: open failed 
```

The channel number and number of warnings vary each time.

I never get this message with other terminal applications (I have tried Terminator and the (default) terminal).
What is this message, and how to fix it? I have tried all changes in the sshd_config file, but nothing has helped. I have attached my sshd_config file here.

### To Reproduce

Platform dependent.
ssh platform is on centOS 7

### Expected behaviour

No warnings

### Screenshots

![image](https://user-images.githubusercontent.com/39446317/209992665-46e7be8b-3f48-4591-bcba-e2d2e2251412.png)

### Operating System

MacOS

### OS Version

13.1

### Shell Version

bash 4.2.46(2)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Additional context

[sshd_config.txt](https://github.com/warpdotdev/Warp/files/10320935/sshd_config.txt)

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @Samiran4448 This is a known issue and can be tracked here: https://github.com/warpdotdev/Warp/issues/1957

**Comment by sur-sakthy** [comment]
I am facing the same issue.
