### ISSUE TITLE
SSH login into any RHEL based OS locks up prompt(RHEL/ALMA/Rocky)

### ISSUE THREAD

**Issue by DTcloudOps** [warpdotdev/Warp#2423]
### Discord username (optional)

DTclo

### Local Shell and Version

3.2.57(1)-release

### Remote Shell and Version

5.1.8(1)-release

### Operating System and Version

RHEL 9.1 - ALMA 9.1 - Rocky 9.1

### Warp Version

v0.2022.12.13.08.04.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

After successful ssh login:
Install package 'git-core' to provide command 'git'? [N/y]
Then the prompt gets stuck on "Loading prompt..."

Disabling Warp SSh Wrapper fixes the issue but defeats the point of using Warp.

<img width="534" alt="Screen Shot 2022-12-20 at 12 29 03 PM" src="https://user-images.githubusercontent.com/121122357/210017797-65c8274e-a130-4845-b19f-bcfdd0328747.png">

<img width="540" alt="Screen Shot 2022-12-20 at 12 29 38 PM" src="https://user-images.githubusercontent.com/121122357/210017809-0f36f7e8-d541-47d3-90fb-a72766c23c6e.png">

### Include shell xtrace output

dt@192.168.210.142's password:
+ set -o vi
+ set +o vi
+ HISTCONTROL=ignorespace
+ printf '

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @DTclo Sorry to hear about this, but yeah the workaround is to disable the ssh wrapper. We're working on some ssh improvements and we'll post any updates on this thread. 

Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by DTclo** [comment]
Thanks!, @dannyneira, looks like installing git on the server fixes the issue with the shh wrapper.

**Comment by vorporeal** [comment]
This should also be fixed (without the "install git" workaround) in this week's release. :)

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
