### ISSUE TITLE
Warp shell prompt give 'warp_precmd:print:28: bad option:'

### ISSUE THREAD

**Issue by PatrickForget** [warpdotdev/Warp#2429]
### Describe the bug

On startup, the terminal indicate the following text (v 0.2022.12.13.08.04.stable_01):

```
warp_precmd:print:28: bad option: ->
```

Entering a command will not work (for example, calling *pwd*):
```
warp_precmd:print:28: bad option: ->
warp_precmd:print:28: bad option: ->pwd
zsh: command not found: warp_precmd:print:28:
```

Getting a command to execute require deleting all the error message (since the error get pre-pended to the command).

### To Reproduce

Managed to track down the issue from the prompt in my .zshrc file

1) edit .zshrc

2) at the end of the .zshrc, set a custom prompt

PROMPT='->  '

3) save the file

4) create a new tab in the terminal (will force executing .zshrc)

The problem should occurs from that point

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know, it looks like the combination of `-` and `>` is what's not working in Warp. 
As a workaround try using only `PROMPT=">"` without the dash. And if you prefer a more robust custom prompt solution look into one of our [supported prompts](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table) or use a [bash prompt generator](https://bashrcgenerator.com/) to create your own PS1 prompt.

**Comment by vorporeal** [comment]
I think I see what's wrong here - `print -P` is interpreting the "->" text as another argument, not the string that should be printed.  Fix is easy; should be able to get it into this week's release. :)

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
