### ISSUE TITLE
Warp moves after waking up from sleep

### ISSUE THREAD

**Issue by nickcheek** [warpdotdev/Warp#2431]
### Describe the bug

After mac goes to sleep and wakes up, warp moves from the lower right hand portion of my screen to the center.  I have to move the terminal back each time after waking.

I'm using on a widescreen monitor (49")

### To Reproduce

Move terminal to the lower right hand section of the screen.  Sleep your mac and then wake it up, warp will now be offset to the centered.

### Expected behaviour

Terminal should stay where it's at when mac sleeps.

### Operating System

None

### OS Version

Ventura 13.2 (a)

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know, we're investigating issues with window placement and will post updates here.

**Comment by jorgerodrigues** [comment]
Also having this issue with the newest builds. In my case it seems to be a persistent issue specially when using external screens. It also happens without being connected, but not as often. 

When using warp in full screen mode on the mac, it does not resize per se, it blacks out half of the upper screen part. I will update this comment with screen dumps later when recreating the issue

**Comment by javimbk** [comment]
Having this issue on my side but it also happens randomly when alt-tabbing between different windows when having an external monitor connected, I have not been able to replicate consistently following a series of steps, but it has been happening for a while now.

Some details on my side in case it is helpful:

```
macOS Ventura 13.1 (22C65)
zsh 5.8.1 (x86_64-apple-darwin22.0)
warp_version=v0.2022.12.13.08.04.stable_01
```

It is a bit annoying, doesn't block me but definitely is going against the main reason why I'm using it, which is great UX!

Thank you guys!

**Comment by hcancelik** [comment]
I'm also having a similar issue where the window is resized and moved to a different position after wakeup. Please let me know if I should provide any technical details.

```
macOS Ventura Version 13.1 (22C65)
warp_version=v0.2023.01.03.08.03.stable_01
```

**Comment by jorgerodrigues** [comment]
This seems to have been fixed in the latest release. I suggest to close the issue.
