### ISSUE TITLE
Distinguish between shell and Warp autocompletions

### ISSUE THREAD

**Issue by EricPetersonIBKR** [warpdotdev/Warp#2433]
### Describe the solution you'd like?

```text
Please distinguish visually between the two kinds of autocompletions, shell or Warp, or perhaps just show which key (Tab or Ctrl+F/Right Arrow) should be used to accept the suggestion. This would reduce user confusion.
```

### Is your feature request related to a problem? Please describe.

```text
While typing in a command, Warp will often show a suggested autocompletion in light gray. These autocompletions can be based on the shell, which can be accepted by pressing Tab, or they can be from Warp, in which case the user needs to use Ctrl+F or Right Arrow to get the completion.

The issue is that sometimes when suggesting a directory autocompletion it can be difficult to tell whether the suggestion is coming from Warp or the shell. Many times I have found myself pressing Tab because it looked like a shell autocompletion but it was actually coming from Warp so I had to change to Ctrl+F.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by thepatchworkapp** [comment]
From the perspective of a person who does a lot of server Ops by running scripts, I often get Warp auto-completions suggestions that are not applicable to the current directory. 

In addition to the proposed solution above, could there be some smart ordering of the suggestions, or could there be an indicator for suggestions that won't work in the current path?

![image](https://user-images.githubusercontent.com/73358033/210378265-0fedaff3-52c7-4c1f-9379-a80bae4d36b8.png)

`bash: ./update_graph.sh: No such file or directory`

**Comment by dannyneira** [comment]
Thanks for submitting! By chance are you using another autocompletion tool/plugin in your dotfiles? If so, could you please post a quick video of this behavior with some examples of shell vs Warp commands? This will help us determine the use case and any issues you're trying to solve.

**Comment by peterdragon** [comment]
An example I have hit is where I am trying to autocomplete a second directory for grep. 
bash would normally show possible matches when I press TAB. 
In warp nothing happens.

![Screenshot 2023-01-04 at 16 47 28](https://user-images.githubusercontent.com/166183/210606529-4b9c06af-eb49-481c-893b-6938f2a9d005.png)
press TAB after 'fi' nothing happens.
expected popup directory choosing so I can pick 'files.old'.

And then the output after typing manually 
![Screenshot 2023-01-04 at 16 47 43](https://user-images.githubusercontent.com/166183/210606673-027dba0e-eba8-4878-9c75-142163d7e159.png)

**Comment by EricPetersonIBKR** [comment]
> Thanks for submitting! By chance are you using another autocompletion tool/plugin in your dotfiles? If so, could you please post a quick video of this behavior with some examples of shell vs Warp commands? This will help us determine the use case and any issues you're trying to solve.

@dannyneira let me first ask a question to see if I have correctly understood how Warp behaves.

When Warp shows a light gray autocompletion, do those ever come from the shell itself? Or, are they always suggestions from Warp?

**Comment by dannyneira** [comment]
Yes those are Warp's completion suggestions based on history. Can be accepted with a right arrow or disabled in the settings features

**Comment by EricPetersonIBKR** [comment]
Ok then I believe I opened this issue in error. I was assuming, incorrectly, that the light gray autocompletion suggestions came from Warp's AI based on history AND autocompletions available in the shell.

Since that isn't true, then what I have noticed is simply that some of Warps autocompletions happen to be things that the shell will do for you also if you hit <Tab>. But the point is that you can always get the light gray suggestion by using Right Arrow or Ctrl+F.

Thanks  @dannyneira for the clarification!

Others who commented here: you may want to open a new issue to address the separate items pointed out.
