### ISSUE TITLE
Adding Custom Autocompletions

### ISSUE THREAD

**Issue by JackHumphries9** [warpdotdev/Warp#2435]
### Describe the solution you'd like?

```text
Hi,
I've written some command line tools and I would love the ability to add the custom autocompletions to Warp so that it will suggest arguments when you type the command.

Is there any support for this kind of API in the works or would it be a future feature later down the line.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @JackHumphries9 
We have an issue tracking this here: #652 TLDR is we're looking to add the ability for custom completion spec for our users to add onto Warp's existing completions. In the meantime here's the full list of [completions we support](https://docs.warp.dev/features/completions).

Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
