### ISSUE TITLE
Don't Collapse the Input Block for Unfocused Panes

### ISSUE THREAD

**Issue by cnw004** [warpdotdev/Warp#2436]
### Describe the solution you'd like?

```text
When I have a tab of Warp running with two windows (one created from either Ctrl-d or Ctrl-Shift-d) the text in the current input block is only visible for the window that has focus.

I do not want the input block on the unfocused window to collapse and hide the command that I was writing. I want to be able to switch between these windows while being able to see the command that I had "primed for execution" in the unfocused window.
```

### Is your feature request related to a problem? Please describe.

```text
Often, I want to have one window that I search history on and then prime the command (e.g., accept it so it fills the block, but don't hit enter again to execute). I then jump to the other window to write a command and use the primed command in the unfocused window as reference.

Today, I cannot do this in Warp because as soon as I switch focus between windows the unfocused window collapses and hides all of the text that is primed for execution.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this. Afaik the input is hidden when there are panes out of focus, not seeing this in Windows out of focus, but I'm sure having the input preview is best across all windows/tabs/panes, at least as an option.
Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by dannyneira** [comment]
Here is an example of the unfocused window still showing the input, let me know if you're seeing it differently.

https://user-images.githubusercontent.com/16809145/210612260-bc7a55d9-8807-46f0-a336-480dc026a353.mp4

**Comment by cnw004** [comment]
Apologies, I believe my terminology was incorrect.

>Afaik the input is hidden when there are panes out of focus

This is what I don't want. If I split a window into 2 panes I don't want the input on pane 1 to be hidden when I shift focus to pane 2. I often have workflows where I need to refer to the input I have primed in pane 1 as reference for the input I am writing in the now focused pane 2.

**Comment by cnw004** [comment]
@dannyneira @elviskahoro I see this was closed with #1220 linked. Has this problem been fixed? If so, can you describe the new user experience or how I can configure what I am looking for? There is very little detail in #1220.

**Comment by elviskahoro** [comment]
@cnw004 it hasn't been launched. didn't mean to close this thanks for commenting!

**Comment by purepear** [comment]
I believe this is related to https://github.com/warpdotdev/Warp/issues/510
I'm looking through the github issues every once and then, hoping that this gets fixed but apparently it's still considered design decision?
I agree with the comments saying that layout shifting is anti-pattern especially in the context of 2 terminals opened side by side.

**Comment by cnw004** [comment]
Reading that issue, they definitely look related -- thank you for sharing! If it is considered a design decision, I hope it can be re-evaluated. It is impactful enough that I have switched back to iTerm2 until it is fixed.

**Comment by dannyneira** [comment]
Thanks for your patience folks! As requested, in Warp version `v0.2023.09.19.08.04.stable_00` and above, the input editor remains visible in inactive panes when using split panes. 

![CleanShot 2023-09-21 at 13 34 04](https://github.com/warpdotdev/Warp/assets/16809145/5b27a944-5add-4296-9166-1e502f70fab7)

Closing as completed, but please let us know if any issues.
