### ISSUE TITLE
Moved to #434: Tab completion for Azure CLI

### ISSUE THREAD

**Issue by robinhultman** [warpdotdev/Warp#244]
### Describe the solution you'd like?

```shell
I would love to have tab completion for the Azure CLI
```

**Comment by elviskahoro** [comment]
@robinhultman moving this to:
- #434
Since that's where we're gonna be keeping completions related discussion

**Comment by elviskahoro** [comment]
Actually #654 instead!

**Comment by lucieleblanc** [comment]
FYI we have Azure CLI completions as of last week's release, `v0.2026.04.08.08.36`!
