### ISSUE TITLE
Send command to all open panes (sync all panes)

### ISSUE THREAD

**Issue by booua** [warpdotdev/Warp#2443]
### Describe the solution you'd like?

```text
Hi,
I'm a new Warp user, trying to switch from iTerm2, which was my daily driver for past several years. Warp is a veery strong contender, but I feel like it's missing my favourite feature from iTerm2 - sending command to all open panes. I use it daily - from working on 2 ssh sessions at the time or trying to access the same folder of my project in 2 or 3 panes simultaneusly.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this! So we have a duplicate request for Broadcast feature similar to iterm #409 

Closing this one as duplicate, but please sub and 👍  to that issue for updates.
