### ISSUE TITLE
Refresh window switch screen

### ISSUE THREAD

**Issue by xpt300** [warpdotdev/Warp#2444]
### Describe the bug

Hello, I found a visual bug while going to eat.

I'm on a mac and I use a second screen, I closed my mac and it automatically displayed on my second screen, except that when I reopened my mac the warp window didn't readjust to my mac window.

(thank you for this beautiful terminal)

### To Reproduce

On a mac, with a second screen connected.

step 1 : close the laptop, with WRAP in full screen (normally the screen is displayed on the second screen)

step 2 : open it again and see the bug

### Screenshots

<img width="1440" alt="Capture d’écran 2023-01-05 à 14 45 46" src="https://user-images.githubusercontent.com/26505541/210795574-5527375c-f027-4a09-a28f-27def644edcf.png">

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this! It less than ideal, but a known issue and can best be tracked here: #2381 

Closing this one as a duplicate.
