### ISSUE TITLE
Autocomplete Bug: `yarn` -> `_dynamic_directory_name`

### ISSUE THREAD

**Issue by lacymorrow** [warpdotdev/Warp#2458]
### Describe the bug

<img width="385" alt="image" src="https://user-images.githubusercontent.com/1311301/211185772-68f75507-daa6-4f3c-976e-d5f775e922c3.png">

Warp is autocompleting commands which are already completely typed-out, replacing them with entirely unused commands.

### To Reproduce

<img width="385" alt="image" src="https://user-images.githubusercontent.com/1311301/211185811-727d2536-2551-4772-bb2a-9a73bed430a8.png">

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

5.8.1

### Warp Version

v0.2023.01.03.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting, I've been able to repro this before. We'll post any updates on this thread. Please 👍 this issue as it helps us gauge impact.

**Comment by alokedesai** [comment]
@lacymorrow Does this only occur when you are SSH'd into a remote box or also on your local machine? Do you have `yarn` installed?

**Comment by lacymorrow** [comment]
I haven’t tried while ssh’d  into a box, only tested locally. In this test I had yarn installed.

**Comment by alokedesai** [comment]
@lacymorrow, do completions for any top level commands work for you?

**Comment by lacymorrow** [comment]
I have updated warp and it _seems_ like this may be fixed? but I was going through setup of a fresh MacOS install so I may have "paved over" the problems.

**Comment by alokedesai** [comment]
Awesome! I'm going to close this out, the other theory is that there could be something in your RC files that was causing this. Please reopen if you see this issue again
