### ISSUE TITLE
Ability to increase scroll limit to unlimited

### ISSUE THREAD

**Issue by eturino** [warpdotdev/Warp#2463]
### Describe the solution you'd like?

```text
I'd like to be able to increase the limit of a block's scroll history (block's scrollback or block's output), ideally to be able to set it to unlimited.
```

### Is your feature request related to a problem? Please describe.

```text
I have to switch to another terminal (in my case iTerm2) where I can set unlimited scroll history when I am running a local server on the app I am developing, since sometimes I need to look at very long console logs and I hit the limit of the block's scroll history.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by eturino** [comment]
![Screenshot 2023-01-09 at 10 14 57](https://user-images.githubusercontent.com/1095800/211275071-f9779cf7-7097-4c44-a742-8c35df8b95a6.png)

**Comment by dannyneira** [comment]
Thanks for submitting @eturino! This is being worked on and can be tracked here #610
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.
Closing as duplicate.

**Comment by eturino** [comment]
ah, I missed that issue. Terribly sorry for it.
Thanks a lot!
