### ISSUE TITLE
Preview windows from dock on right click

### ISSUE THREAD

**Issue by evangrim** [warpdotdev/Warp#2468]
### Describe the solution you'd like?

```text
I have several warp windows, each with multiple tabs, which I typically group by work context. One for this environment/environment, one for that.

I'd like another way to switch to the window I want, by right clicking the Warp item in MacOS Dock and clicking a description of the window (VSCode and Chrome are two apps with multiple windows, each with multiple tabs, that demonstrate this behavior).
```

### Is your feature request related to a problem? Please describe.

```text
It's a little jarring when an app doesn't behave like other apps I frequently use.

Sometimes I'd prefer to use the mouse instead of CMD + Tab, especially when some of my windows are minimized (in which case I might to look all over multiple screens to see every window). easier then to look in one place and read through window names.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by elviskahoro** [comment]
@evangrim We might already have an open issue for this. I'll check and see at some point. Meanwhile here are screenshots of the feature:



![CleanShot 2023-01-11 at 12 13 40@2x](https://user-images.githubusercontent.com/29553206/211908480-340cc5e1-7dfc-436d-937a-c732e28f732c.png)

**Comment by evangrim** [comment]
Yes, that screenshot of Chrome's behavior is exactly what I'm hoping for, @elviskahoro! Sorry I couldn't find that existing issue when I looked.

**Comment by dannyneira** [comment]
As per the latest release, Warp will now show the active windows on right-click of the dock icon!

![CleanShot 2023-02-10 at 10 45 51](https://user-images.githubusercontent.com/16809145/218160728-0153882f-ba72-48ca-aaae-81423ca41124.png)

![CleanShot 2023-02-10 at 10 48 18](https://user-images.githubusercontent.com/16809145/218160793-011d2a4f-9743-4688-92c6-502c2ac01e8b.png)
