### ISSUE TITLE
cat x.log | grep someword on server (ssh) does not output

### ISSUE THREAD

**Issue by mackermedia** [warpdotdev/Warp#2469]
### Describe the bug

When I'm ssh'd into my server and try to `cat production.log | grep word`, the output is not displayed.

### To Reproduce

Not sure how to reproduce, as this may be Warp environment + ssh environment specific? 

`cat production.log` works fine, so it may be related to the pipe to `grep`?

Could possibly b/c I installed the Warp helper up on that server?

I am sending app crash reports / telemetry data if that helps debug.

### Expected behaviour

The output of my log + grep functionality.

### Screenshots

![](https://s3.amazonaws.com/mackerman/Monosnap_2023-01-10_19-04-59.png)

### Operating System

MacOS

### OS Version

12.3

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

### Warp Version

v0.2023.01.03.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by mackermedia** [comment]
Sorry I was mistaken. I thought it was a "warp helper", but instead was [Fig.io](https://fig.io/) tool that I was referring to. I've since uninstalled that tool and see that the problem still exists.

**Comment by elviskahoro** [comment]
@mackermedia can you send us a video of what happens when you do the same thing with mac terminal? this would help since bugs over SSH are pretty hard to debug on our end.

**Comment by mackermedia** [comment]
@elviskahoro 
🤦 My mistake! Thanks for pointing out the obvious to try it on Mac OS terminal. 
The Mac OS terminal showed empty output as well. 
I was incorrectly thinking my logs contained a string that was case insensitive!
