### ISSUE TITLE
Input Editor: Prompt: Support or supplant Starship modules

### ISSUE THREAD

**Issue by adamshaylor** [warpdotdev/warp#247]
### Describe the solution you'd like?

This is a great app. I like the concepts behind it. In order to make it my daily driver, though, I’d need one of the following:

1. Support for [Starship](https://starship.rs).
2. Additional prompt info comparable to Starship’s [modules](https://starship.rs/config/#terminology).

### Is your feature request related to a problem? Please describe.

I currently have Starship set up in my `.zshrc`. Warp fails to launch unless I disable it.
The one thing that makes me reluctant to give Starship up is its _modules_ functionality. It tells me:

* If the current working directory is the root of some project that expects some language or framework to be installed.
* Whether that language/framework is in my `$PATH` and resolves to a compatible version.

I don’t use or care for its custom icon font, which makes it impossible to copy the prompt outside the terminal. I have it configured to use plain text.

### Additional context

<img width="666" alt="Screen Shot 2021-10-05 at 12 58 54" src="https://user-images.githubusercontent.com/673870/136094418-02e97c63-a0ca-401b-a2ad-7ad775af0770.png">

**Comment by elviskahoro** [comment]
The current discussion on this is here: https://github.com/warpdotdev/warp/issues/96
