### ISSUE TITLE
Shell is taking to long to start and blocks 

### ISSUE THREAD

**Issue by JulianoRodrigues** [warpdotdev/Warp#2472]
### Describe the bug

When I open a new terminal window the Warp terminal runs my configuration and prints it on the terminal. With this I'm not able to run a single command in the terminal. 

![Screenshot 2023-01-11 at 10 13 27](https://user-images.githubusercontent.com/8126428/211778942-85d55a4f-72a0-4831-9be0-28f7ef8f52d5.png)

### To Reproduce

Open the warp app.

### Operating System

MacOS

### OS Version

12.5

### Shell Version

none

### Warp Version

v0.2023.01.03.08.03

### Additional context

I can't see the shell version because I can't run any command.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
Are you SSH'd into a machine or is this on your local laptop?

**Comment by JulianoRodrigues** [comment]
Local laptop, I'll close this issue because I found the root cause for this. 

It was `rover` path that I've added to my `zshrc` file that was causing this issue.
