### ISSUE TITLE
Layout is broken when macos comes back from slepping/lock screen

### ISSUE THREAD

**Issue by franklinjavier** [warpdotdev/Warp#2475]
### Describe the bug

Layout is broken when macos comes back from slepping/lock screen

### To Reproduce

1. Click in the fullscreen button
2. Let mac sleep
3. When you gets the mac from sleeping, you will see the broken layout as in the screenshot below

### Screenshots

![image](https://user-images.githubusercontent.com/440220/211852277-680a40d8-a98f-46b0-bd6f-abcb19969a86.png)

### Operating System

MacOS

### OS Version

13.1 (22C65)

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22) / zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.01.03.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by adimyth** [comment]
I think I am also facing the same issue here.  The top part of the terminal turns black when coming back from sleep mode

![Screenshot 2023-01-12 at 12 03 25 AM](https://user-images.githubusercontent.com/26377913/211889922-41be6a04-837f-48cd-91eb-406bae47bf64.png)


PS - Ignore the yellow highlight

**Comment by elviskahoro** [comment]
Does resizing the window fix the layout?

**Comment by adimyth** [comment]
Minimizing the window & maximising it again, fixes it

**Comment by franklinjavier** [comment]
> Does resizing the window fix the layout?

Yes, but everytime my mac goes to sleep, it does that.
