### ISSUE TITLE
Fullscreen on MacOS freaks out

### ISSUE THREAD

**Issue by Roxxas96** [warpdotdev/Warp#2488]
### Describe the bug

I've been using Warp for 2 month now and I recently (in the 2 las weeks) seen some bug when I left Warp in full screen for a long time. Sometime Warp translate a bit to the top or the bottom of the screen, causing the app to be completely shifted from the limit it is supposed to be, this can hide the "window" bar for example (the bar where you close the app or disable fullscreen), when disabling and reanabling fulscreen the bug disapear and Warp works properly. My friend had the same issue some days ago.

### To Reproduce

1. Open Warp and put it in full screen mode
2. Navigate through your desktops and wait (some time it only takes 20 min to Warp to be shifted)
3. Come back to Warp

### Expected behaviour

The application should not be shifted like this when using fullscreen.

### Screenshots

<img width="1728" alt="Screenshot 2023-01-12 at 08 04 13" src="https://user-images.githubusercontent.com/23388848/211999896-993d1540-fdc0-4d15-99d6-1d924c2d7dfb.png">

### Operating System

None

### OS Version

13.1 (22C65)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.01.03.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by franklinjavier** [comment]
Related #2475
