### ISSUE TITLE
Keyboard shortcuts affect multiple panes

### ISSUE THREAD

**Issue by wiccy46** [warpdotdev/Warp#2494]
### Describe the bug

When there are multiple panes opened, pressing one shortcut combo affect all. This is problematic for example when you have two Vim opened on each. 

If you pressed ctrl + 6 on one to switch to the previous buffer. The other pane will also do that. 

### To Reproduce

1. cmd + d to split pane
2. Each open vim or nvim. 
3. Type a line of words on both. Move both cursor to the beginning of the line
4. Focus on one pane, type ctrl + w to move the cursor
5. Observe both vim instances moved

### Expected behaviour

Keyboard shortcut in one pane should not affect this other.

### Operating System

None

### OS Version

OSX, 12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2023.01.10.08.02.stable.01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
The fix came out today!
