### ISSUE TITLE
Remapping Command Palette keyboard shortcut doesn't persist through restart

### ISSUE THREAD

**Issue by mchristiansen** [warpdotdev/Warp#2496]
### Discord username (optional)

marticus#6903

### Describe the bug

I'm trying to remap Toggle Command Palette under keyboard shortcuts to `^⌘Space`. It works initially, but after quitting and restarting Warp the shortcut reverts back to the default `⌘P`.

### To Reproduce

1. Settings -> Keyboard shortcuts -> Toggle Command Palette
2. Change shortcut to `^⌘Space` and Save and close Settings
3. Press `^⌘Space`, Command Palette pops up correctly
4. Quit Warp
5. Launch Warp
6. Press `^⌘Space`, Command Palette no longer pops up 

### Operating System

MacOS

### OS Version

12.6.2

### Shell Version

zsh 5.8.1

### Warp Version

v0.2023.01.10.08.02.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
Thanks for filing, will try to repro and then update you!

**Comment by elviskahoro** [comment]
Was able to repro this!

**Comment by elviskahoro** [comment]
This has been fixed!
