### ISSUE TITLE
A.i has no network connection

### ISSUE THREAD

**Issue by goldjunge91** [warpdotdev/Warp#2506]
### Describe the bug

when I try to get any help from A.i command menu I get an error.

### To Reproduce

start a terminal window

### Screenshots

![Bildschirm­foto 2023-01-15 um 12 05 44](https://user-images.githubusercontent.com/30201929/212537182-94c07896-f6e0-41d3-a545-9f1d819078b9.png)

### Operating System

MacOS

### OS Version

13.1

### Shell Version

zsh 5.8.1

### Warp Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
@goldjunge91 Someone is investigating this but no ETA on a fix!

**Comment by dannyneira** [comment]
Hey @goldjunge91 Please try the workaround for this known issue listed here:

https://docs.warp.dev/help/known-issues#online-features-ai-command-block-sharing-referrals-etc.

Let us know if the problem persists after the workaround or please close this issue if the steps fix it.

**Comment by goldjunge91** [comment]
> Hey @goldjunge91 Please try the workaround for this known issue listed here:
> 
> https://docs.warp.dev/help/known-issues#online-features-ai-command-block-sharing-referrals-etc.
> 
> Let us know if the problem persists after the workaround or please close this issue if the steps fix it.

sorry i allready removed
