### ISSUE TITLE
Clicking the Warp icon consecutively on top right triggers window control settings

### ISSUE THREAD

**Issue by nemoitis** [warpdotdev/Warp#2508]
### Describe the bug

If I click the Warp icon to open the sidebar, I have to wait at least 2 seconds to click it again to close the sidebar. Otherwise it triggers the window control settings (in my case, maximizes/restores the window as per my MacOS settings). The button's area should be an exception from this behavior as followed by other applications, e. g. Jetbrains IDEs, TablePlus etc. 

### To Reproduce

1. Click on the Warp icon on top right to open sidebar.
2. Try to click the button immediately (or a second later) to close the sidebar. 

### Expected behaviour

Clicking the button consecutively should toggle the sidebar instead of triggering window control settings.

### Screenshots

https://user-images.githubusercontent.com/80112748/212613083-020ca64b-6fef-4898-ba76-121106037929.mov

### Operating System

MacOS

### OS Version

Ventura 13.1

### Shell Version

zsh 5.8.1

### Warp Version

v0.2023.01.10.08.02.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
Thanks for opening! I ran into this myself actually (today).

**Comment by dannyneira** [comment]
Thanks for submitting @nemoitis , So from what I'm seeing it doesn't always trigger, if you click it repeatedly and fast it doesn't trigger, but if you delay about a second it'll min/max the window.

**Comment by nemoitis** [comment]
Thanks @dannyneira. I couldn't regenerated what you showed. In my case double clicking also triggers this issue. I can't click any faster lol. 😁

**Comment by nemoitis** [comment]
Thanks @dannyneira. I couldn't regenerated what you showed. In my case double clicking also triggers this issue. I can't click any faster lol. 😁

**Comment by dannyneira** [comment]
Hey Folks, the update released today `v0.2023.03.07.08.02.stable_01` fixes this issue in Warp. Closing as resolved. 🚀

**Comment by dannyneira** [comment]
Hi All! Looks like the fix didn't make the cut for this week's release. It'll go live next week!
