### ISSUE TITLE
CB: Phantom command on init

### ISSUE THREAD

**Issue by agonzalezro** [warpdotdev/warp#251]
### Describe the bug

```shell
Every time I open Wrap I see a previous executed empty command and I don't see where it's coming from, maybe it's some of the steps from oh-my-zsh or anything I have in my zshrc but it doesn't seem to happen in other terminals (please take a look to the screenshots).

My .zshrc can be found here: https://github.com/agonzalezro/dotfiles/blob/master/dot_zshrc.tmpl

Thanks!
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```shell
1. Open Wrap
2. You will already see the phantom command
```

### Screenshots

What I see when starting Wrap:

<img width="1103" alt="Screenshot 2021-10-06 at 08 24 40" src="https://user-images.githubusercontent.com/205176/136151170-d30c1fcd-4fb4-4768-a99e-06675dd477cc.png">

What I see when starting Mac's terminal:
<img width="375" alt="Screenshot 2021-10-06 at 08 25 19" src="https://user-images.githubusercontent.com/205176/136151237-a1407264-8105-4444-981d-d8558a42375d.png">

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
Play around with your ZSHRC. This should help:
```sh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
    source ~/.config/powerlevel10k/powerlevel10k.zsh-theme
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
    (( ! ${+functions[p10k]} )) || p10k finalize
fi

```

**Comment by agonzalezro** [comment]
Thanks @elviskahoro!

I don't use/have installed that ZSH theme (`powerlevel10k`) unless it's being used somehow behind the scenes. However, you gave me the clue that it could be related to a theme so I just changed mine and the "phantom command" has disappeared :)

**Comment by mkrajinovic** [comment]
> Thanks @elviskahoro!
> 
> I don't use/have installed that ZSH theme (`powerlevel10k`) unless it's being used somehow behind the scenes. However, you gave me the clue that it could be related to a theme so I just changed mine and the "phantom command" has disappeared :)

I also didn't have p10k installed. Tried installing it and adding what @elviskahoro suggested to my .zshrc.
For me powerlevel10k.zsh-theme wasn't in ~/.config/powerlevel10k/ as suggested but in /user/local/opt/powerlevel10k/. 
Tried both but phantom command still appears only in Warp.

**Comment by elviskahoro** [comment]
The things I usually see:
powerlevel10k
a ZSH theme
a random ZSH Plugin
some kind of binding / keybinding

I'm trying to make a running list / guide based on feedback we collected. But unfortunately, sometimes, we end up just having to start with blank rc files and then incrementally add things until it breaks.

**Comment by mkrajinovic** [comment]
Hi @elviskahoro 
Sorry for the late response. I didn't have time to respond earlier. I've tested with the most basic .zshrc, and I still get the same phantom command. Here is the .zshrc I've tested with:
```
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt extendedglob
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/mkrajinovic/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
```

**Comment by elviskahoro** [comment]
@mkrajinovic Are you using antigen? + What ZSH plugins do you currently have installed?

**Comment by mkrajinovic** [comment]
@elviskahoro no antigen installed, no oh-my-zsh, no plugins. This is a clean install on latest macOS.

**Comment by elviskahoro** [comment]
Can you try this:
Put `ZDOTDIR=/` in a ~/.zshenv file. This forces zsh to run with zero configs.

**Comment by elviskahoro** [comment]
@mkrajinovic 
Can you try this:
Put `ZDOTDIR=/` in a ~/.zshenv file. This forces zsh to run with zero configs.

**Comment by mkrajinovic** [comment]
Hi @elviskahoro
I tried this but it doesn't change anything. ZSH still works perfecetly fine in macOS terminal and in iTerm2 (and it was working as expected with my .zshrc).

**Comment by alokedesai** [comment]
I can definitely repro with the `refined` ohmyzsh theme--to some extent at least with that theme it looks like it's working as intended because one of the features it supports is printing the prompt at the end of the command (see iterm on the left and warp on the right). @mkrajinovic are you using this theme by chance?

![image](https://user-images.githubusercontent.com/4110292/142909747-0974f6f0-6cd7-40eb-9070-6017651414be.png)

**Comment by mkrajinovic** [comment]
@alokedesai currently no oh-my-zsh, no themes, no plugins. I've put ZDOTDIR=/ in a ~/.zshenv file. This forces zsh to run with zero configs. as @elviskahoro said and I still experience this behaviour.

**Comment by alokedesai** [comment]
@mkrajinovic would you be open to a quick (~20 minute) call to help debug further? I'd love to help debug this but unfortunately can't repro myself. Can send you a link to schedule if so!

**Comment by mkrajinovic** [comment]
Sure, send me a schedule at mkrajinovic8@gmail.com.

**Comment by mkrajinovic** [comment]
@alokedesai I've also just tried creating a new user on my macbook, installing Warp and got the same behaviour.
