### ISSUE TITLE
Restore window size and location after closing a window with the X button

### ISSUE THREAD

**Issue by joshknowles** [warpdotdev/Warp#2512]
### Discord username (optional)

joshknowles#1862

### Describe the bug

I have the "Restore windows, tabs, and panes on startup" feature enabled, but when I open Warp nothing is restored.

Also unsure if it's related, but I've also tried using the "Save New Launch Configuration" feature, and it returns an error of "an issue was encountered while saving" when trying to save the config.

### To Reproduce

1. Enable "Restore windows, tabs, and panes on startup"
2. Open new tabs or move window location
3. Close & Reopen Warp

### Expected behaviour

I would expect that the window is restored to it's previous configuration upon restarting.

### Operating System

MacOS

### OS Version

13.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.01.10.08.02.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by joshknowles** [comment]
Ok, thanks. I clearly don't agree, but it's your product! At a minimum, perhaps this could be made more explicit in the docs and UI?

**Comment by joshknowles** [comment]
Thought about this one a bit more. I understand not wanting to do a full restore when re-opening after a cmd-W or clicking "X", but would you be open to at least re-opening the window back at the same size & location?

**Comment by elviskahoro** [comment]
@joshknowles We'll change this issue to be for restoring window size and location!

**Comment by elviskahoro** [comment]
No problem!

**Comment by dannyneira** [comment]
Closing this as a duplicate in favor of #1399 

Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.
