### ISSUE TITLE
Unable to type '~'

### ISSUE THREAD

**Issue by robinhultman** [warpdotdev/warp#252]
### Describe the bug

```shell
I don't know if I am doing something really stupid here but I am unable to type tilde ('~') in Warp on a keyboard with Swedish layout. Nothing happens as far as I can tell.
It works in any other program.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Operating System

MacOS

### OS Version

11.6

**Comment by kevinyang372** [comment]
Sorry for this experience! This is caused by the same issue as #174. We are going to release a fix for the text input bug soon!
