### ISSUE TITLE
Completions description get's chopped / bleeds off screen after filtering to one entry

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#2520]
### Describe the bug

Type git rebase start adding a flag: `git rebase --` press tab and then filter to one entry: `onto`. Notice that it comes off screen.

### To Reproduce

https://www.loom.com/share/20d535ce806f45a6baac3bf58090bfa4

### Operating System

None

### OS Version

NA

### Shell Version

NA

### Warp Version

NA

### Additional context

https://www.loom.com/share/20d535ce806f45a6baac3bf58090bfa4

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Fixed as of Warp version `v0.2023.03.28.08.03.stable_01`! 🚀 

Closing as completed
