### ISSUE TITLE
Enable Notebook style editing and markup

### ISSUE THREAD

**Issue by raghuvv** [warpdotdev/Warp#2523]
### Describe the solution you'd like?

```text
I like how Jupyter Notebooks enabke incremental learning and annotation for later reference.

This can be a powerful feature if implemented for terminal. I want to save all commands I execute along with their output and optional markdown notes.

Can we add this to roadmap?

Save as Warp Notebooks? Edit each cell / command block and execute in any order. Add markdown cells, hyperlinks, cross-notebook references and imports, extensible through plugins.
```

### Is your feature request related to a problem? Please describe.

```text
I want to be able to save what I learn when I adopt new command line tools like Docker, AWS CLI etc and share my work with the world
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Something like this is already on our Roadmap! See https://www.warp.dev/

![CleanShot 2023-02-08 at 15 01 41](https://user-images.githubusercontent.com/16809145/217661163-314e1dfd-06cc-43cc-8c0a-208866be10f2.png)

**Comment by rgbkrk** [comment]
👋  Hi, Jupyter dev here.

For the time being, I'm using the markdown viewer and clicking to run shell scripts from each block. It's a really nice workflow.

**Comment by dannyneira** [comment]
Hey Folks, Warp Notebooks are in tomorrow's release officially! https://www.warp.dev/blog/notebooks-in-warp-drive

**Comment by dannyneira** [comment]
@raghuvv Closing this as resolved since we've launched Notebooks, but opening a new issue to track the request to save commands AND output Blocks in a Notebook here https://github.com/warpdotdev/Warp/issues/4704
