### ISSUE TITLE
ssh commands with wrapper enabled crash with exit code 137

### ISSUE THREAD

**Issue by mchristiansen** [warpdotdev/Warp#2527]
### Discord username (optional)

marticus#6903

### Local Shell and Version

zsh 5.8.1

### Remote Shell and Version

bash 5.1.4(1)-release

### Operating System and Version

Debian GNU/Linux 11 (bullseye)

### Warp Version

v0.2023.01.10.08.02.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

![Screen Shot 2023-01-19 at 2 32 02 PM](https://user-images.githubusercontent.com/989644/213567170-818e1efa-c222-4e49-a7ca-5daa172219a4.png)

### Include shell xtrace output

As seen in the screenshot, there is no output, it just returns immediately. It is the same with any host I try.

### Does this block you from using Warp daily?

No

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by vorporeal** [comment]
Hey @mchristiansen, thanks for reporting this!  As far as I can tell from searching the web, exit code 137 signifies that the process was terminated via `SIGKILL`, often due to running out of memory.  I'm guessing that's not the case here?

**Comment by mchristiansen** [comment]
It's very consistent behavior even if nothing else is running (doesn't seem to be an oom issue). It fails immediately with pretty much no delay. I tried your suggestion and reinstalled Warp, but that didn't help.

Honestly I was hesitant to even open an issue because I figured it would be hard to reproduce, but it has been this way for quite a while. It's happening on one of my macs, but not the other one. I _think_ it used to happen on both, but I recently tried turning the wrapper back on to see if the issue went away and it seems to be gone for one and not the other. They're both M1 macs, one is running Monterey 12.6.2 (problem), the other is Ventura 13.1 (not a problem).

Happy to try any other suggestions you have.

**Comment by mchristiansen** [comment]
I'm now running warp version v0.2023.01.31.08.08.stable_02 and the ssh wrapper seems to work now. Not sure if there was a fix implemented or if it was something else that changed with my environment, but going to close this out. Thanks!

**Comment by vorporeal** [comment]
Glad to hear it!  I will admit I was at a bit of a loss and wasn't sure how to debug further, so "it's fixed now" is music to my ears 😅
