### ISSUE TITLE
Background process output for commands started with & becomes added to the command history

### ISSUE THREAD

**Issue by dpolivaev** [warpdotdev/Warp#2531]
### Describe the bug

`[1]  + 51280 done       gitk` and output from background processes are interpreted  as commands and added to the command history

### To Reproduce

run command `gitk&`using warp command prompt
Close the gitk window
Read line `[1]  + 80462 done       gitk`
Press enter
Press arrow up key
See that this line becomes a part of the command history

### Expected behaviour

Background process related output should not be interpreted as possible commands

### Screenshots

<img width="508" alt="gitk" src="https://user-images.githubusercontent.com/1558052/213731813-f6295458-b6ad-40a4-af4b-9edc239e2d50.png">

### Operating System

MacOS

### OS Version

11.3.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.01.17.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting @dpolivaev  i'm noticing the same issue with even `sleep 10 &` command. 

We're tracking this in this here https://github.com/warpdotdev/Warp/issues/1796
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge impact of the bug.

Closing as duplicate.
