### ISSUE TITLE
Top-to-Bottom

### ISSUE THREAD

**Issue by jasonosgood** [warpdotdev/Warp#2533]
### Discord username (optional)

zappini

### Describe the solution you'd like?

```text
Two part feature request:

Can I place the command entry at the top of the window (tab)?

And if so, it could be fun to then order the blocks with most recent on top.

Bridge too far: Our terminals took after teletype machines, right? Scroll bottom-up. What if terminals scrolled top-down? Would that be so weird?
```

### Is your feature request related to a problem? Please describe.

```text
My eye gaze is not drawn to the bottom of the window. Using Terminal.app, I'm always hitting Meta-K (clear screen) to move the command line prompt to the top of the window.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by ulken** [comment]
Duplicate: https://github.com/warpdotdev/Warp/issues/22

**Comment by dannyneira** [comment]
Thanks for submitting @jasonosgood 
We have a issue tracking this here #22 TLDR, we're working on this feature and will post updates on that thread.

Please :+1: and subscribe to that request as it helps us gauge interest.
Closing as duplicate.
