### ISSUE TITLE
Feature Request: Option to disable enter for selecting command completions

### ISSUE THREAD

**Issue by muescha** [warpdotdev/Warp#2535]
### Discord username (optional)

Muescha#3499

### Describe the solution you'd like?

```text
i would like to see an option to disable the enter key to select the autocompletion selection.

i still can use the tab key to select the autocompletion suggestions.
```

### Is your feature request related to a problem? Please describe.

```text
autocomplete not always selecting the needed option. muscle memory give me that i just hit enter also when the autocomplete is not matching. instead of using my written command it selects the autocompletion and execute this command.
```

### Additional context

see similar problems can be solved with disabling the enter key:

- #2497 Autocompletion should learn common commands 
- #2509 When typing '..' the suggestion menu chooses the '...' alias. Instead of leaving it '..' 

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @muescha 
We have a issue tracking this here: https://github.com/warpdotdev/Warp/issues/1806
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.
Closing as duplicate.
