### ISSUE TITLE
Fish takes forever to start 

### ISSUE THREAD

**Issue by NikosEfthias** [warpdotdev/Warp#2536]
### Describe the bug

I have fish as default shell  which starts instantaneously on any other terminal emulator however on warp it takes like a minute to start

### To Reproduce

open warp as fish default shell

### Expected behaviour

open at once 

### Screenshots

<img width="553" alt="image" src="https://user-images.githubusercontent.com/9097437/213906179-c14906a6-554e-48b1-ad90-79748ea39e6c.png">

### Operating System

MacOS

### OS Version

13.1 

### Shell Version

fish 3.6.0

### Warp Version

v0.2023.01.17.08.03.stable_01

### Additional context

i just moved `fish` folder even then it takes a solid 5 seconds to start not as bad as a minute but still on the annoyingly slow end 

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by illuminos** [comment]
+1 Same problem here and the only reason for me to not use warp as of now.

**Comment by NikosEfthias** [comment]
@illuminos at the moment i just keep a warp running on background always however this is not a permanent solution i cant use splits or anything

**Comment by illuminos** [comment]
I actually reverted to iTerm because of this issue. I check Warp weekly to see if this is fixed.

**Comment by dimeloper** [comment]
+1 same problem here and I also reverted to iTerm because of this issue. Please let us know if this will be fixed.

**Comment by dannyneira** [comment]
Sorry about this all, thanks for letting us know of the issues with fish. We'll look into this but in the meantime, please see our troubleshooting docs for possible solutions.

https://docs.warp.dev/help/known-issues#debugging / https://docs.warp.dev/help/known-issues#fish-and-fig
https://docs.warp.dev/getting-started/using-warp-with-shells#using-fish-shell-with-warp

**Comment by illuminos** [comment]
After today's update, fish startup time went down to 3 seconds. While better than the previous 5+ seconds of boot time, it is nowhere compared to iTerms <1s time. Hopefully future updates make it better

**Comment by NikosEfthias** [comment]
@illuminos when are we getting that update ? on warp itself no new updates are available as far as i can see

**Comment by illuminos** [comment]
@NikosEfthias Maybe its a staggered rollout. Hopefully you'll see it soon.

**Comment by NikosEfthias** [comment]
well definitely looking forward to it while its not optimal 3 seconds are workable

**Comment by dannyneira** [comment]
Hey Folks,
Thanks for letting us know @
We're tracking this issue here https://github.com/warpdotdev/Warp/issues/1298
Please :+1: and comment there if you also see the issue, as it helps us gauge the bug's impact.

Closing as duplicate.
