### ISSUE TITLE
Tools to learn commands + Onboarding

### ISSUE THREAD

**Issue by adithyabsk** [warpdotdev/Warp#254]
### Describe the solution you'd like?

```shell
One thing I'm trying to do right now is learn the advanced command line args of different tools I use (git, gcc, etc...) and tools I don't use as much so I can make more use of them (curl, sed, awk) -- I could see huge value in warp building tools around this space (i.e. in user generated courses similar to https://www.vim.so/)

Other Keywords: Spaced Repetition, SRS
```

**Comment by elviskahoro** [comment]
Linking:
- #266

**Comment by elviskahoro** [comment]
Linking:
- #226

**Comment by elviskahoro** [comment]
Linking
- #344

**Comment by elviskahoro** [comment]
Support for Import from --help Options

From @Gregory-Gelfond via: #344

### Describe the solution you'd like?

```shell
A lot of unix utilities have a `--help` or `-h` option for printing out their arguments. It'd be nice if some way of "learning" new completions for frequently used commands from their help text could be implemented.
```


### Is your feature request related to a problem? Please describe.

_No response_

### Additional context

_No response_

**Comment by elviskahoro** [comment]
@adithyabsk Gonna close this out as we have a feature being built that will help considerably with this! The internal tame is Command X-Ray but not sure if that will be the public one when it launches.
