### ISSUE TITLE
AI commands when ssh'ed into a remote compute server with screen

### ISSUE THREAD

**Issue by jamespblloyd-uwa** [warpdotdev/Warp#2540]
### Describe the solution you'd like?

```text
When I used Warp on my MacOS laptop to ssh into a Linux (Ubuntu) server for work, the format changes and I can no longer get AI commands suggested using the # or work in blocks of code. I do use screen, which seems to be the problem.
```

### Is your feature request related to a problem? Please describe.

```text
I cannot get AI commands on my server when I use screen
```

### Additional context

<img width="1507" alt="Screenshot 2023-01-23 at 10 44 56 am" src="https://user-images.githubusercontent.com/54612219/213958047-29867fcf-b43b-4c9c-94e1-5bd4a27e0898.png">

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
I believe this may have to do with the lack of subshell support. Please follow this issue to get updates on this. https://github.com/warpdotdev/Warp/issues/64

**Comment by dannyneira** [comment]
closing as duplicate since `screen` support is included under subshells.
