### ISSUE TITLE
starship prompt is broken even when it's not multilined

### ISSUE THREAD

**Issue by Gorthog** [warpdotdev/Warp#2544]
### Describe the bug

when i choose "use my custom prompt" i see starship prompt for just a second and then it disappears. and no prompt appears at all.

i used a very minimal starship configuration. even when i only enable directory and nothing else, the problem persists.

```
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
"""

[line_break]
disabled = true
```

### To Reproduce

install warp, fish and starship
change warp to use custom prompt

### Expected behaviour

starship prompt shows up

### Screenshots

![image](https://user-images.githubusercontent.com/15230040/214297723-5a963467-2a67-47d1-a082-7921a8c6ee20.png)

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

fish 3.5.0

### Warp Version

v0.2023.01.17.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @Gorthog In your config it looks like there may be a second line for the directory:

````format = """
$directory\
"""```

I'm thinking if you make this one like it may work, like:

```
format = """$directory"""
```

Give it a try and let us know if resolved the issue.

**Comment by Gorthog** [comment]
@dannyneira thanks for the reply, unfortunately, I get the same results
![image](https://user-images.githubusercontent.com/15230040/217888103-bc9f8067-c401-4710-8c9b-c1d799bed525.png)

**Comment by dannyneira** [comment]
Oh, i noticed you using fish, make sure the source line is in your [fish config](https://starship.rs/guide/#%F0%9F%9A%80-installation) and for troubleshooting try the most basic format in your starship.toml `format = '$all'`



![CleanShot 2023-02-09 at 10 22 38](https://user-images.githubusercontent.com/16809145/217890442-520bd4a8-5384-4cbe-8739-cd90abd9f13b.png)

**Comment by Gorthog** [comment]
`starship init fish | source` worked!

but i'm baffled. I have the same line in my fish config, why do I need it to run it again whenever I start warp? Is there a way to automate it so i won't have to do it manually every time?

**Comment by dannyneira** [comment]
I just tested this and it looks like the fish config should look like this for it to load automatically.
```
if status is-interactive
    # Commands to run in interactive sessions can go here
    starship init fish | source
end
```

![CleanShot 2023-02-09 at 11 21 00](https://user-images.githubusercontent.com/16809145/217903237-2f671db5-358a-4478-b48d-c53971796e3f.png)


Hopefully, the above works for you as well, please let us know by closing this issue.

**Comment by Gorthog** [comment]
my fish config looks like that, and still the issue persists. any ideas?

**Comment by dannyneira** [comment]
Hm, you can refer to the fish docs for more info on setting up fish as the default shell in Warp. 
https://docs.warp.dev/getting-started/using-warp-with-shells#using-fish-shell-with-warp

I've setup fish as per the docs and installed starship along with the config.fish above and can't repro the issue. It could be that you have some other unsupported fish plugin or known issue preventing it from loading automatically. See: https://docs.warp.dev/help/known-issues#fish-shell-read-command
https://docs.warp.dev/help/known-issues#debugging

**Comment by Gorthog** [comment]
In one of your links I've found the issue. It was indeed an incompatiblity, with fig.
Once I deleted both mentioned files, the problem went away
https://docs.warp.dev/help/known-issues#fish-and-fig

Thanks!!!!!
