### ISSUE TITLE
Passwords are visible in history

### ISSUE THREAD

**Issue by Akshaya-Dhelaria-au7** [warpdotdev/Warp#2548]
### Describe the bug

When terminal asks for permission and we add the password, those passwords are visible in history.

### To Reproduce

1. Add any package with sudo command.
2. Enter the password.
3. Check history by clicking on `cmd` + `r`

### Operating System

None

### OS Version

macos 13.0

### Shell Version

zsh 5.8.1

### Warp Version

v0.2023.01.17.08.03

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting, this is something we're working on improving blocks in general which includes history deletion management. https://github.com/warpdotdev/Warp/issues/516

Closing in favor of that request so we can track it there. Please 👍  on it and subscribe for updates.
