### ISSUE TITLE
gsutil auto completion

### ISSUE THREAD

**Issue by lappazos** [warpdotdev/Warp#2549]
### Describe the solution you'd like?

```text
in "normal" terminal, when you perform gsutil cp or cat operations, you can press tab and it will offer 
you list of options (it queries the api behind the scenes) just like local dir completions. 
In wrap, this option doesn't work with tab.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @lappazos I'm closing this as part of the greater discussion on missing completion specs.

Please subscribe to receive updates on this issue. https://github.com/warpdotdev/Warp/discussions/652
