### ISSUE TITLE
Delete or blur a block

### ISSUE THREAD

**Issue by ajunior** [warpdotdev/Warp#2550]
### Discord username (optional)

Jr#8752

### Describe the solution you'd like?

```text
I would like to have some way to exclude or blur a specific block.
```

### Additional context

Sometimes we need to share our screen, so it would be good to be able to blur or exclude (or both) a specific block.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @ajunior Sorry for the delayed response but we have an issue tracking this here  
https://github.com/warpdotdev/Warp/issues/23

Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
