### ISSUE TITLE
A.I. Command Search server seems currently broken

### ISSUE THREAD

**Issue by varenc** [warpdotdev/Warp#2555]
### Describe the bug

AI Command search isn't working. The request to the server hangs and then returns an error. Inspecting the traffic I can see that the request to app.warp.dev stalls and then eventually returns `{"error":"open ai returned empty choices: \u003cnil\u003e"}`

### To Reproduce

I would guess AI Command Search is broken for everyone right now, but possibly it's just me? I've tried updating the Warp app and it had no effect. Seems a server side issue.

### Expected behaviour

Warp's awesome AI Command Search would keep working.

### Screenshots

<img width="464" alt="image" src="https://user-images.githubusercontent.com/167585/214734758-2aaae344-4f1c-4e57-a0cc-f5c4f53179b8.png">

### Operating System

MacOS

### OS Version

12.6.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2023.01.17.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by varenc** [comment]
it now seems to be back up! Cheers.

**Comment by salv0** [comment]
I am still having the same issue on build 0.2023.01.31.08.08.stable_02 
any other idea?

**Comment by XiaofengXie16** [comment]
Same.  i am still seeing issue with v0.2023.02.14.08.05.stable_01.
