### ISSUE TITLE
Support executing history entries directly

### ISSUE THREAD

**Issue by uhinze** [warpdotdev/Warp#256]
### Describe the solution you'd like?

Ability to execute commands from history with a single keyboard stroke.

### Is your feature request related to a problem? Please describe.

To execute a command from history, one can either use the up arrow or reverse search. After finding the right one, one has to hit Enter to paste the command to the current command line and then hit Enter again to execute. This becomes annoying when having to execute a single command lots of times. 
Behavior in most other terminals is so that hitting Enter directly executes a command. I find this more sensible as a default for everyday usage.

**Comment by elviskahoro** [comment]
Still no ETA on this! Will reach back out when there's progress!

**Comment by elviskahoro** [comment]
This was launched today!
