### ISSUE TITLE
How to disable clicking anywhere on the terminal pane focuses on the window

### ISSUE THREAD

**Issue by letiesperon** [warpdotdev/Warp#2560]
### Is your feature request related to a problem? Please describe.

It's frustrating that clicking on any place in the terminal selects the whole window (adds a blue border and background to the terminal) and typing is disabled until you double-click somewhere.

### Additional context

<img width="1086" alt="Screen Shot 2023-01-26 at 08 57 18" src="https://user-images.githubusercontent.com/17788257/214830340-7accae56-5087-4c46-abd2-0e76f9dc4d96.png">

### Describe the solution you'd like?

I think I saw this being a configuration option but now I can't seem to find it

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @letiesperon! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by jeffcstock** [comment]
I completely agree - this is extremely frustrating to work with when you're not used to selectable "blocks". Making a way for that "click to select block" functionality to be turned off, so that clicking into Warp _always_ focuses the text input would be fantastic. Possibly going to have to switch back to iTerm temporarily until this is fixed. 😞

**Comment by elviskahoro** [comment]
Can you share a video of what's happening?

**Comment by dannyneira** [comment]
Thanks for submitting this @letiesperon 

We already have a request tracking this over at #739, there is a partial fix noted in the comments there. https://github.com/warpdotdev/Warp/issues/739#issuecomment-1585235653

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
