### ISSUE TITLE
In a window with two panes, clicking the scroll in the top pane scrolls the bottom pane to the top

### ISSUE THREAD

**Issue by iteratemanually** [warpdotdev/Warp#2564]
### Describe the bug

When trying to use the scroll bar, if it's on a window with split panes, clicking on the top scroll bar will scroll the bottom pane all the way to the top

### To Reproduce

1. Create a new window
2. Split the into two vertical panes
3. Create enough content in both to scroll
4. Click on the scroll bar for the top pane
5. Bottom pane will scroll to top

### Expected behaviour

1. Create a new window
2. Split the into two vertical panes
3. Create enough content in both to scroll
4. Click on the scroll bar for the top pane
5. Bottom pane should not scroll

### Operating System

MacOS

### OS Version

13.1

### Shell Version

zsh 5.9

### Warp Version

v0.2023.01.24.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know about this bug. I was able to reproduce this and will bring it up with the team. Posting any updates here.

**Comment by vorporeal** [comment]
Figured out what's going wrong and sent out some code for review; should be fixed in next week's release!

**Comment by iteratemanually** [comment]
Quick turn around. This is great! Thanks!

**Comment by elviskahoro** [comment]
This should be out now!
