### ISSUE TITLE
Warp doesn't "auto-raise" when using AutoRaise

### ISSUE THREAD

**Issue by samholmes** [warpdotdev/Warp#2565]
### Describe the bug

- Warp's window is somehow unique to other windows on macOS such that it is broken when using the [AutoRaise](https://github.com/sbmpost/AutoRaise) app. Perhaps it doesn't report cursor enter/leave events?

### To Reproduce

1. Open Warp
2. Install AutoRaise (https://github.com/sbmpost/AutoRaise)
3. Open AutoRaise
4. Hover mouse over Warp app

Result: Warp doesn't auto-raise

### Expected behaviour

Warp auto-raises like every other window

### Operating System

MacOS

### OS Version

12.5.1

### Warp Version

v0.2023.01.24.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Sorry about this issue, but thanks for letting us know. I'll have to try and repro this, will let you know if we need more info and post any updates on this thread.

**Comment by vorporeal** [comment]
Hey @samholmes, I tried to repro this but Warp windows seem to auto-raise correctly for me.  Could you attach a screenshot of your AutoRaise configuration? (in case there's a particular setting that's causing problems)

**Comment by samholmes** [comment]
```
delay=0
focusDelay=2
mouseStop=true
warpX=0.5
warpY=0.5
```

This is my AutoRaise configuration.

**Comment by vorporeal** [comment]
Ah, the issue is with auto-focus vs. auto-raise.  I think I have a fix; if all goes well it'll be in next week's release.

**Comment by sbmpost** [comment]
@vorporeal @dannyneira 
Is this solved now? AutoRaise uses a very obscure and undocumented private Apple API to make focus only work. So I can imagine not all apps being compatible with that.

**Comment by vorporeal** [comment]
@sbmpost Just tested it out with the latest release (v0.2023.02.14.08.05.stable_01) and it seems to be working correctly now. :) Please re-open if I'm wrong!
