### ISSUE TITLE
How to quit

### ISSUE THREAD

**Issue by phpmac** [warpdotdev/Warp#2566]
### Describe the bug

How do I log out of github?

### To Reproduce

How do I log out of github?

### Operating System

None

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by McGeerDev** [comment]
Heyy @phpmac. Could you please provide more details to the issue you are having.
It doesn't seem to be an issue with the warp terminal.
If you are having issues signing out of the github browser app:
1. Go to the top right of the github page and click on the dropdown next to your profile icon
2. Click on "Sign out" (At the bottom of the dropdown.
If you are having issues signing out of your account on your local system follow this guide:
1. You need to remove your github credentials from the system
2. Seeing as warp is a mac only product (At the moment) follow the link below to know how to update your github credentials on your mac.
https://docs.github.com/en/get-started/getting-started-with-git/updating-credentials-from-the-macos-keychain

**Comment by dannyneira** [comment]
In the case you want to log out of Warp, please remove Warp user login with `sudo security delete-generic-password -l "dev.warp.Warp-Stable" $HOME/Library/Keychains/login.keychain`

**Comment by dannyneira** [comment]
Closing as resolved as this appears to be a GH issue, not Warp.
