### ISSUE TITLE
Mouse focus stopped working in the latest version

### ISSUE THREAD

**Issue by boris-aws** [warpdotdev/Warp#2568]
### Describe the bug

I started using Warp for a while now. I usually connect to my Ansible server and then run tmux sessions. I was able to make new windows and panes and use my mouse pointer to choose which window or pane I want to focus on and run commands. This has stopped working in the latest version for some reason. 

### To Reproduce

1. start tmux session
2. create new window or split the current one you are typing in 
3. try to use mouse to click to a window name or window screen to focus your typing on that particular one
4. not working, cursor stays at the same original screen/window/pane

### Expected behaviour

1. start tmux session
2. create new window or split the current one you are typing in 
3. try to use mouse to click to a window name or window screen to focus your typing on that particular one
4. you are now on that window and can run commands
5. you should be able to go back and forth between the split panes and choose where you want to run commands. This was working before.

### Operating System

MacOS

### OS Version

Ventura 13.1

### Shell Version

zsh 5.9

### Warp Version

v0.2023.01.24.08.03.stable_01

### Additional context

I have to use iTerm again because Warp makes tmux unusable! 

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by hundehausen** [comment]
I have the same issue
