### ISSUE TITLE
The ability to change font weight

### ISSUE THREAD

**Issue by spaceexperiment** [warpdotdev/Warp#2569]
### Describe the solution you'd like?

```text
Is it possible to add the option to modify the font weight? I always prefer bold font as it makes reading easier for me.
```

### Is your feature request related to a problem? Please describe.

```text
increase readability
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by hundehausen** [comment]
You can change it in the settings under appearance

**Comment by spaceexperiment** [comment]
> You can change it in the settings under appearance
@hundehausen 
I only see the option to change the font family and font size, but not font weight. Am I missing something?

**Comment by hundehausen** [comment]
you're right

**Comment by dannyneira** [comment]
Thanks for submitting this @spaceexperiment, you're correct we dont have weight options, as a workaround i recommend installing the "Bold" version of your preferred font which should bold it by default.

Also, please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by mikka2061** [comment]
Installing a bold version is not feasible in cases of variable size font packs like Iosevka or Hack. This is, right now, the breaker for me.

**Comment by heybigneel** [comment]
Not a deal breaker but would definitely appreciate having an option to configure font weight.

**Comment by Toxicom** [comment]
Shook that this isn't a feature yet

**Comment by 917huB** [comment]
+1

**Comment by iamvoidcoder** [comment]
+1. Can't use Warp w/o font weight control.

**Comment by moeamaya** [comment]
Not a deal breaker, but definitely high up on my list

**Comment by sgmonda** [comment]
+1, I need this feature

**Comment by pibo** [comment]
+1

**Comment by yuritoledo** [comment]
+1

**Comment by cubatic45** [comment]
+1, I'll change my default terminal from iterm2 to warp if warp add text weight

**Comment by nfwyst** [comment]
font is tooooo thin....

**Comment by jzuijlek** [comment]
+1

**Comment by NXTaar** [comment]
+1 also need a font weight control

**Comment by HakonHarnes** [comment]
+1

**Comment by PaulWeinsberg** [comment]
+1

**Comment by PaulWeinsberg** [comment]
I've just disabled thin stroke (Never) and it's much better on my MacBook

**Comment by dannyneira** [comment]
Hi Folks, Sorry about this but i'm be closing this request in favor of #280 which is an older request. We'll be tracking interest in font weight settings there, please continue to 👍 the topline issue and avoid spam comments like "+1".

Closing as duplicate.

**Comment by dannyneira** [comment]
Duplicate of #280

**Comment by okharedia** [comment]
+1
