### ISSUE TITLE
Warp launch time is 1-2 slower than MacOS Terminal

### ISSUE THREAD

**Issue by soleares** [warpdotdev/Warp#2572]
### Describe the bug

"WARP IS A BLAZINGLY FAST, RUST-BASED TERMINAL..." but it launches 1-2 seconds slower than MacOS Terminal. 

Warp launch time to a usable terminal is about 4 seconds on my machine. MacOS Terminal takes about 2 seconds. This is significant when you use it all day.

 

### To Reproduce

1. Open MacOS Terminal
2. Open Warp Terminal
3. Warp takes longer

### Expected behaviour

1. Open MacOS Terminal
2. Open Warp Terminal
3. Warp takes the same or less time to open as MacOS terminal

### Operating System

MacOS

### OS Version

13.2

### Shell Version

zsh 5.8.1

### Warp Version

v0.2023.01.24.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
Are you using fish shell?

**Comment by soleares** [comment]
zsh and ohmyzsh in particular. 

To be honest this isn't really a bug, and more of a feature request. But it was the first thing I noticed when I used the tool and likely the reason I won't use it so I thought it was worth mentioning.

I think it's just related to app launch time since opening tabs in Warp and MacOS Terminal seems to take the same amount of time.

**Comment by elviskahoro** [comment]
The initial load time is longer because Warp needs to set up a wrapper that enables Blocks. Disabling OMZ should help speed up boot time, you can disable it just for Warp:
https://docs.warp.dev/help/known-issues#debugging

Ideally Warp will make a number of plugins and tools like OMZ obsolete by building fixing pain points with native solutions.

**Comment by elviskahoro** [comment]
Gonna close this cause there isn't much that can be done here.

**Comment by soleares** [comment]
> The initial load time is longer because Warp needs to set up a wrapper that enables Blocks. Disabling OMZ should help speed up boot time, you can disable it just for Warp: https://docs.warp.dev/help/known-issues#debugging

Thanks, I will try that since based on the docs it looks like OMZ themes and plugins are incompatible with Warp anyways.

**Comment by ekwoka** [comment]
I'm just curious. If you use it all day, why do you close it?
