### ISSUE TITLE
Block filtering - real-time grep without data loss

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#2574]
### Describe the solution you'd like?

```text
Would be really nice if we could filter out a Block's contents at the terminal level (without data loss).
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by danielpeng2** [comment]
We released the [block filtering](https://docs.warp.dev/features/blocks/block-filtering) feature that supports this!
