### ISSUE TITLE
Scrolling in linux screen

### ISSUE THREAD

**Issue by NickDemidov** [warpdotdev/Warp#2578]
### Describe the bug

Hi! I found a problem with scrolling in screen mode
When I'm trying to scroll content in screen mode - all the content stays in freeze and instead of content scrolling works only for list of last used commands from history

### To Reproduce

1) screen -S some_session
2) cat some_long_file.txt
3) try to scroll  in screen some_session

### Expected behaviour

Scroll should work the same way, like window without screen mode

### Screenshots

Screen recording is here: https://youtu.be/UzOcP0SSAtw

### Operating System

MacOS

### OS Version

13.1

### Shell Version

zsh 5.8.1

### Warp Version

v0.2023.01.24.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by dannyneira** [comment]
So the screen along with other subshells isn't fully supporting all the Warp features. I'll bring this up with the team and you can track this here: #64 

Closing as duplicate for subshell support.
