### ISSUE TITLE
Global hotkey shows existing Warp window(s) instead of a dedicated "hotkey window".

### ISSUE THREAD

**Issue by acarl005** [warpdotdev/Warp#2585]
### Discord username (optional)

acarl005#8446

### Describe the solution you'd like?

This is a new issue derived from the feedback in the thread in #91.

It would be nice if Warp could have a global hotkey which activates Warp's _normal window(s)_ instead of showing a special, dedicated window, a.k.a. the "hotkey window" or "Quake mode". This new implementation would be analogous to iTerm's "show/hide all windows with a system-wide hotkey" option, while the current implementation would be like iTerm's "create a dedicated hotkey window" option.

![Screenshot 2023-01-30 at 4 55 55 PM](https://user-images.githubusercontent.com/8334252/215607534-df25f35d-62b5-41ef-bed2-c75afbaa5cfa.png)

The hotkey window is ideal for use cases where you want to guarantee a Warp window can be shown above anything else, including fullscreen apps. However, there are some usage patterns in which a normal window is a better fit.
I will henceforth refer to this as the "activation hotkey".

### Is your feature request related to a problem? Please describe.

This implementation would directly close the following issues: #1188, #1230, #1254.

Furthermore, assuming these users don't have some other reason to prefer a hotkey window, these issues can be solved by using the activation hotkey instead: #1536, #1911, #2328, #2521, #2604, #2606, #2473.
These issues can be summarized as follows:

1. The hotkey window cannot be moved/resized on the fly. The size and position are fixed in settings and will return to that size/position next time it is shown. Normal windows **will** obey this behavior.
1. The hotkey window can only be one window, and it doesn't support **multiple windows**.
1. The hotkey window doesn't "activate" the application, e.g. does not show "Warp" as the active app in the menu bar. This is an issue if the user wants to interact with the menu, or if they expect another app to trigger something on loss of focus, e.g. an editor autosaving some work.
1. The hotkey window doesn't respond to cmd+tab, clicking the dock, or app launchers/switchers like Raycast or Alfred.
1. Opening Warp from VSCode can't be opened into the hotkey window, only into a normal window.
1. Launch configurations don't respect the hotkey window.

### Additional context

Currently, configuring a separate app to activate Warp is required to achieve the described behavior, e.g. [Hotkey App](https://apps.apple.com/de/app/hotkey-app/id975890633) or [Raycast](https://www.raycast.com/).

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by enyuhsu** [comment]
This is one of the iTerm features I miss most after switching to Warp!

**Comment by dannyneira** [comment]
I'm all for this! Anyone else interested, please :+1:  and subscribe to this request as it helps us gauge interest.

**Comment by FlashThePlayer** [comment]
this, only thing from keeping me to switch permanently to warp is this missing feature!

**Comment by Arkhas** [comment]
Can't wait to have it, I have to use raycast hotkey to do this

**Comment by dannyneira** [comment]
Hey Folks, the update released today `v0.2023.03.07.08.02.stable_01` adds this feature to Warp. 
You can set the hotkey via the `Settings > Features > Keys`, select 'Show/hide all windows' in the Global hotkey dropdown, then set your preferred keybinding.

![CleanShot 2023-03-09 at 16 10 18](https://user-images.githubusercontent.com/16809145/224181687-0104f727-89ab-44ad-8be8-4e6c6696b1ab.png)

Closing as resolved. 🚀

**Comment by dannyneira** [comment]
Added this to our docs here: https://docs.warp.dev/features/windows/hotkey-window#show-hide-all-windows

**Comment by GrayedFox** [comment]
This might not be the place for it but - I'd like to be able to show and hide the warp terminal no matter what virtual desktop (space) I'm in/on, even if I have a full screen application on that desktop.

Is that currently possible? Or would this be a separate feature request to bring it more in line with how iTerm (and Guake) behave?

**Comment by elviskahoro** [comment]
We support this! On quake mode make sure that you're using the "Dedicated hotkey window setting"
![CleanShot 2024-02-01 at 23 59 09@2x](https://github.com/warpdotdev/Warp/assets/29553206/39d78acd-743d-4d44-aeb8-9ec769d83513)

**Comment by GrayedFox** [comment]
Ah! That has indeed solved the first part of the issue, thanks 🙇🏽 

I have a saved launch configuration that I would like to be used whenever I use the hotkey - right now I just get a single tab instead of my 5 named tabs.

Is there a way to connect that hotkey to a specific launch configuration?

**Comment by SanchezSobrino** [comment]
^ Interested in the above suggestion too. I could do that in iTerm.

**Comment by jbaccarelli-equinix** [comment]
i wish also the window would keep the dimensions manually set between invocations, and that we could add a slide down animation to it

**Comment by colorglut** [comment]
I wish I could make the default window just the Visor, so that I was only ever using that and could bring that up with the Dock icon too!

**Comment by n-WN** [comment]
> Hey Folks, the update released today `v0.2023.03.07.08.02.stable_01` adds this feature to Warp.大家好，今天发布的更新 `v0.2023.03.07.08.02.stable_01` 在 Warp 中添加了此功能。 You can set the hotkey via the `Settings > Features > Keys`, select 'Show/hide all windows' in the Global hotkey dropdown, then set your preferred keybinding. 您可以通过 `Settings > Features > Keys` 设置热键，在全局热键下拉列表中选择“显示/隐藏所有窗口”，然后设置您的首选键绑定。
> 
> Also added this to our docs here: https://docs.warp.dev/features/windows/hotkey-window#show-hide-all-windows还将其添加到我们的文档中：https://docs.warp.dev/features/windows/hotkey-window#show-hide-all-windows
> 
> ![CleanShot 2023-03-09 at 16 10 18](https://user-images.githubusercontent.com/16809145/224181687-0104f727-89ab-44ad-8be8-4e6c6696b1ab.png)
> 
> Closing as resolved. 🚀关闭已解决。 🚀

我启动了

> Hey Folks, the update released today `v0.2023.03.07.08.02.stable_01` adds this feature to Warp. You can set the hotkey via the `Settings > Features > Keys`, select 'Show/hide all windows' in the Global hotkey dropdown, then set your preferred keybinding.
> 
> Also added this to our docs here: https://docs.warp.dev/features/windows/hotkey-window#show-hide-all-windows
> 
> ![CleanShot 2023-03-09 at 16 10 18](https://user-images.githubusercontent.com/16809145/224181687-0104f727-89ab-44ad-8be8-4e6c6696b1ab.png)
> 
> Closing as resolved. 🚀

I made sure that the warp monitoring input option in the accessibility function was turned on, and the global shortcut key in the warp option was turned on, but I still can't open the warp after pressing the hotkey as expected.
