### ISSUE TITLE
Addition of a feature to make Warp the default terminal for macOS as it is currently lacking.

### ISSUE THREAD

**Issue by s-Bzz** [warpdotdev/Warp#2590]
### Describe the solution you'd like?

```text
This feature would allow users to set Warp as the default terminal app on their Mac, so that when they open a terminal window or run a command that requires a terminal, Warp would be used by default instead of the default terminal app provided by the operating system. Having this feature would provide a better user experience and make it easier for users to use Warp as their primary terminal app.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @s-Bzz 
We have a issue tracking this here: #753
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.
Closing as duplicate.
