### ISSUE TITLE
DUP: Duplicate of #239 - Support font ligatures

### ISSUE THREAD

**Issue by rossvz** [warpdotdev/warp#260]
Would be awesome to support ligatures via a configurable Preferences setting. I find the |> operator ligature much nicer when writing a lot of Elixir code!

**Comment by elviskahoro** [comment]
Linking:
- #239

**Comment by elviskahoro** [comment]
@harrisj
From #239

> Describe the solution you'd like?
> This is obviously not urgent, but would it be possible to add a toggle to enable something like Emacs prettify-symbols mode for the terminal. This is a display mode that translates things like -> or != into Unicode characters for things like right arrow or the not-equals sign. Obviously, people might want to tweak this in different ways and it's a complicated feature, but it is pretty too!
> 
> Is your feature request related to a problem? Please describe.
> No
> 
> Additional context
> A peek at prettify-mode
> Doom Emacs ligature mode
