### ISSUE TITLE
Open new tabs in home directory

### ISSUE THREAD

**Issue by tomeresk** [warpdotdev/Warp#2600]
### Describe the solution you'd like?

```text
Currently, opening a new tab opens it in the same directory as the current tab.
I would like an option to always open the new tab at the home directory.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this! Closing this one in favor of the duplicate issue https://github.com/warpdotdev/Warp/issues/105

Please sub and follow the progress on that issue and 👍 to help us gauge interest in that feature.
