### ISSUE TITLE
Python virtualenv with conda / mamba links Python properly but not pip

### ISSUE THREAD

**Issue by gerardsimons** [warpdotdev/Warp#2601]
### Discord username (optional)

gsimons

### Describe the bug

When I activate an environment with conda or mamba, the python seems properly linked but the pip is not. Not sure if this is some very strange misconfiguration of my terminal or not, but I cannot find anything related to it. I tried different shells and removing the bash_profile / zshrc / fishconfig. Nothing seems to work.

### To Reproduce

Install conda, miniconda or mamba.

Create new environment : 

conda create -n abcdef python=3.8  
conda activate abcdef
which python; which pip

### Expected behaviour

I was expecting pip to be like : /Users/gerard/.mambaforge/envs/abcdef/bin/pip but it was still using the base pip from homebrew.

Please advise

### Screenshots

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/4247845/216587207-52a53f92-ee60-4afc-9048-d8eb2050a856.png">

### Operating System

MacOS

### OS Version

13.2

### Shell Version

bash 3.2.57(1)-release (arm64-apple-darwin22) zsh 5.8.1 (x86_64-apple-darwin22.0) fish, version 3.6.0

### Warp Version

v0.2023.01.31.08.08.stable_02

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by gerardsimons** [comment]
I fixed it by reinstalling brew ... still strange that somehow Warp preferred the homebrew pip and the other terminals did not. In any case, it seems to have been more of a misconfiguration than a real bug!

**Comment by dannyneira** [comment]
Thanks for the update! feel free to reopen if you notice it happen again after the brew update.

**Comment by zhylmzr** [comment]
I have the same problem too, and I found that it seems that warp will repeatedly add PATH, The duplicated PATH won't appear in other terminals.

```
echo $PATH
... /opt/homebrew/bin /opt/homebrew/sbin ... /Users/zhylmzr/miniconda3/bin /Users/zhylmzr/miniconda3/condabin 
## It's starting to repeat here, note that it didn't add miniconda3 again.
/opt/homebrew/bin /opt/homebrew/sbin ...
```

```
conda activate d2l
which -a pip
/opt/homebrew/bin/pip
/Users/zhylmzr/miniconda3/envs/d2l/bin/pip
/opt/homebrew/bin/pip
```

<details >
<summary>This is the comparison screenshot.</summary>
<img width="839" alt="SCR-20230309-nnwt" src="https://user-images.githubusercontent.com/15730824/223948728-6489fc00-0508-4cc4-a72d-243bab2ec897.png">

</details >

**Comment by elviskahoro** [comment]
@zhylmzr can you disable your custom prompt and let us know what happens. Try this:
https://docs.warp.dev/features/prompt#disabling-unsupported-prompts-for-warp-e.g.-powerlevel10k-p10k

**Comment by zhylmzr** [comment]
@elviskahoro I only use [fish](https://github.com/fish-shell/fish-shell) and [oh-my-fish](https://github.com/oh-my-fish/oh-my-fish). I tried to uninstall oh-my-fish but it didn't work. Below is my configuration:

```fish
# for display language
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# homebrew
eval (/opt/homebrew/bin/brew shellenv)

# rust yarn
set -g PATH $PATH ~/.cargo/bin /Users/zhylmzr/.yarn/bin

# node version manager
fnm env --use-on-cd | source
# quick jump to directory
zoxide init fish | source

export GPG_TTY=(tty)

# deno
export DENO_INSTALL="/Users/zhylmzr/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

# pnpm
set -gx PNPM_HOME "/Users/zhylmzr/Library/pnpm"
set -gx PATH "$PNPM_HOME" $PATH
# pnpm end

# Bun
set -Ux BUN_INSTALL "/Users/zhylmzr/.bun"
set -px --path PATH "/Users/zhylmzr/.bun/bin"

# dprint
set DPRINT_INSTALL "/Users/zhylmzr/.dprint"
set PATH "$DPRINT_INSTALL/bin" $PATH

# go bin
set -g PATH $PATH /Users/zhylmzr/go/bin

export VCPKG_ROOT=$HOME/vcpkg

# zig
set -g PATH $PATH /Users/zhylmzr/Person/Tool/zig

# dotnet tool
set -g PATH $PATH /Users/zhylmzr/.dotnet/tools

set CONDA_LEFT_PROMPT 1


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
if test -f /Users/zhylmzr/miniconda3/bin/conda
    eval /Users/zhylmzr/miniconda3/bin/conda "shell.fish" "hook" $argv | source
end
# <<< conda initialize <<<

```
