### ISSUE TITLE
Can't SSH: `Error: exec: "export": executable file not found in $PATH`

### ISSUE THREAD

**Issue by GuilhermeFreire** [warpdotdev/Warp#2602]
### Local Shell and Version

bash 3.2.57(1)-release

### Remote Shell and Version

bash 5.0.17(1)-release

### Operating System and Version

Local: macos Ventura 13.1; Remote: Ubuntu 20.04.4 LTS

### Warp Version

v0.2023.01.31.08.08.stable_02

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

Warp fails:
<img width="764" alt="Screenshot 2023-02-03 at 14 18 17" src="https://user-images.githubusercontent.com/9718154/216626939-dc3814ba-82d3-468c-a608-a09c493fd798.png">

Default mac terminal works:
<img width="471" alt="Screenshot 2023-02-03 at 14 18 35" src="https://user-images.githubusercontent.com/9718154/216626942-4f4d9e75-ef03-4d82-90e3-87518342e7ed.png">

### Include shell xtrace output

```
Error: exec: "export": executable file not found in $PATH
Connection to 34.XXX.XXX.XXX closed.
```

### Does this block you from using Warp daily?

No

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @GuilhermeFreire, as a workaround you can try disabling the SSH Wrapper in Warp's `Settings > Features`

**Comment by GuilhermeFreire** [comment]
Hey @dannyneira , thanks for the reply. This was not a blocker to me at all, as I simply used the default terminal that comes with macos. I created the issue so we can diagnose warp, and hopefully warp becomes better :)

So yeah, I SSHed into the server and can confirm `export` works (the shell is `bash 5.0.17(1)-release`). I think there is something weird with how warp SSHes. It's as if it's trying to find an executable called `export`, whereas in reality, it's just a bash command. If I disable the SSH Wrapper, it works fine.

I have also tried to SSH with the Wrapper into a different machine running Ubuntu 22.04.1 LTS (different cloud provider), and warp is able to SSH just fine. Not sure what the differences are.

**Comment by GuilhermeFreire** [comment]
So apparently there's something weird with the remote server. It tries to interpret the first word of the command as an executable for whatever reason.
I got it to fail on the normal macos terminal by running `ssh -i ~/.ssh/github_rsa -p 54782  34.XXX.XXX.XXX -t 'export A=/usr'` (exact same error).

Since Warp's SSH wrapper uses `export TERM_PROGRAM='WarpTerminal'`, it'll fail for the same reason.

Since this is not something related to Warp directly, I'll close the issue. Thanks for your time anyway :)

BTW, the server I was trying to SSH into is a CircleCI one running unit tests, so it's possible you might receive more issues like this in the future if this is something CircleCI is doing to their SSH configs or whatnot. Not sure if it's worth to investigate further 🤷‍♂️

**Comment by neobats** [comment]
Hey, I'm chiming in to say I encountered the same issue with a Circle CI build I was trying to connect to. I disabled the Wrapper Warp provides, opened a new tab and successfully connected to the remote.

Thanks for the workaround! Would be interesting to see what's up in Circle CI that makes this fail 🤔
