### ISSUE TITLE
Slightly blurry fonts

### ISSUE THREAD

**Issue by slifty** [warpdotdev/Warp#261]
### Describe the bug

```shell
I find the bold fonts in the tabs to be a bit difficult to read.  I don't know if it's an anti-aliasing issue or something else but wanted to raise the issue in case there is a way to make the font rendering in Warp crisper overall!
```

### To Reproduce

Just opening the application.

### Expected behaviour

```shell
I would love the fonts in Warp to be more legible by default.
```

### Screenshots

<img width="298" alt="image" src="https://user-images.githubusercontent.com/208884/136835507-bcb10e04-8382-4e02-917b-e667adb672d9.png">

### Operating System

MacOS

### OS Version

10.5.7

**Comment by elviskahoro** [comment]
Related: 
- #317

**Comment by kyle-mccarthy** [comment]
I am having the same issue. I think that it is most noticeable when the font is bold. The font kerning also seems to be a little off. For comparison, my screenshot shows warp compared to alacritty. 

warp version: v0.2021.11.29.18.59.stable_01
font: VictorMono

![image](https://user-images.githubusercontent.com/7758522/144762503-b9054297-fe6f-4c02-bfaa-ebaf92485f17.png)

**Comment by aparajita** [comment]
> The font kerning also seems to be a little off.

That's actually letter spacing, which I agree is way too small. Kerning refers to the spacing between individual, specific pairs of letters.

**Comment by daniloc** [comment]
+1, the type rendering is really bad, and as typography is the principal interface element of a terminal, it's hard to get excited to try using it, when my perfectly rendered Terminal.app is sitting right there.

**Comment by fbartho** [comment]
I too have noticed this issue -- it's notable because I think it's only appearing when the Warp window is on an external Monitor, the fonts don't look blurry on the main laptop display, so I'm wondering if a Screen-flag isn't being updated properly per display.

**Comment by allyouaskfor** [comment]
Also having this issue running Warp on a 2015 Macbook Air with Big Sur.

**Comment by hugows** [comment]
Also happening to me - this gives a feeling of old Java interfaces that would do their own custom anti-aliasing or something. 
Great product btw, congrats. Regular terminal feels very dated in comparison.

**Comment by zayenz** [comment]
Tried Warp now, and the font rendering in the application parts (that is, not the actual terminal but for example in the settings and similar) is very bad. I initially thought something must be wrong with the installation. Here is a screenshot of the sidebar menu in settings as an example.
![Screenshot 2022-04-07 at 13 32 47](https://user-images.githubusercontent.com/245350/162190910-a1d78bc3-fcbf-4c93-a8fd-1190379b2c51.png)

**Comment by igorgoroun** [comment]
The same on MacOS Monterey:
<img width="294" alt="Screenshot 2022-04-19 at 21 23 12" src="https://user-images.githubusercontent.com/608121/164070437-a0dbb7d6-ab7d-4457-847a-fef89e4f7945.png">
Common terminal on left, Warp on right.

**Comment by stooboo** [comment]
Glad it's not just me ;-) - the blurry fonts make it unusable for my eyes

**Comment by grzegorzkycsw** [comment]
For me the font rendering is perfect on MacBook Pro built-in retina display, but the fonts become blurry when I close the laptop and use 2x full hd monitor via DisplayLink

**Comment by jonohill** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4335965/168026655-6e1c413f-145f-459a-a4c0-02680bb4da07.png">
I've also noticed blurry fonts and bad kerning. For example here, the spacing between `p y` in Copy, `l e` in select, `u s` in user's. For some people I've shown this to they can't even see it and for others a deal breaker, including me unfortunately.

**Comment by vorporeal** [comment]
General note - we're delegating to CoreText for glyph rasterization, so rendering in the terminal grid should be largely the same as other Mac apps.  Rendering of proportional fonts is definitely off, as we're not currently respecting fractional pixel advances between glyphs (things get forced to pixel boundaries).  This may also be what's leading to low-quality font rendering on non-retina displays, as that forcing would be moving glyphs further from the desired location (in mm/inches).

I'm working on improving kerning this week. :)  (FYI @jonohill)

The comments about glyphs appearing bolder is due to iTerm (and, presumably, Terminal.app) using a private API to render glyphs with thinner outlines on retina displays.  When you disable that functionality, glyphs for Warp should be pixel-identical to iTerm (as of today's release).

Similarly to kerning, I'm working on addressing the too-bold issue this week. :)

If you want some more details about known issues with our font rendering, or a visual comparison with iTerm, see my comment here: https://github.com/warpdotdev/Warp/issues/317#issuecomment-1119075732.

**Comment by alokedesai** [comment]
Closing this out as @vorporeal made a bunch of improvements to our text rendering. Please reopen if you are still seeing blurry fonts!

**Comment by zmb3** [comment]
Thank you, Warp team. Things look much better now!

**Comment by elviskahoro** [comment]
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">
