### ISSUE TITLE
Docker stopping interpreted as a new command

### ISSUE THREAD

**Issue by mattcorner** [warpdotdev/Warp#2617]
### Describe the bug

I often run docker containers from warp. These containers run until I `Cmd + C` to stop the container. The container does not stop straight away, instead showing something like:

```
[+] Running 0/1
 ⠋ Container container_name  Stopping                                                                                  6.1s
[+] Running 0/1
```

However, warp interprets the Ctrl + C as entering a new block, and includes the docker stopping response as a new command. 

### To Reproduce

Assuming you have a docker compose file:

```
docker-compose up
```
Once container is running, Cmd + c to stop, waiting for it to stop gracefully.

### Expected behaviour

Command terminates within the correct block even when it takes some time to complete. Command history is not littered with lingering command termination responses.

### Operating System

MacOS

### OS Version

13.1 (22C65)

### Shell Version

3.2.57

### Warp Version

v0.2023.01.31.08.08.stable_02

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting @mattcorner , do you mind providing some screenshots of the video of the issue? maybe provide a sample compose file for us to be able to reproduce the issue.

Also, you can try running in detached mode with `-d` and it will not take up the terminal input, but afaik CTRL-C is the default way to stop docker containers.
