### ISSUE TITLE
Keyboard shortcut support for sql

### ISSUE THREAD

**Issue by djgundrum** [warpdotdev/Warp#2621]
### Describe the solution you'd like?

```text
I would like to be able to use the keyboard shortcuts that exist everywhere else in warp when writing sql queries (mysql specifically in my case). 

examples: 
option+right_arrow => right one word
option+left_arrow => left one word

command+right_arrow => end of statement
command+left_arrow => beginning of statement
```

### Is your feature request related to a problem? Please describe.

```text
I'm always frustrated when I have to press and hold the arrow keys to move back and forth in the sql wrapper. If I make a mistake in my select, I have to move all the way back in order to change it, then all the forwards again to keep writing.
```

### Additional context

It seems in general if you are in the sql format, warp doesn't recognize each run of a query as a block and doesn't partition it off like it does with the rest of the commands that you can run. This seems like a fix that could probably be pretty quick and would drastically change my entire experience with warp. The tool is amazing and with this feature it would be perfect.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates on this thread.

**Comment by djgundrum** [comment]
Hey @dannyneira I saw that you implemented this and I can't thank you enough. This makes Warp perfect <3

**Comment by dannyneira** [comment]
Closing as this main issue is resolved, please feel free to open a new bug report for other requests.
