### ISSUE TITLE
it suggests folders/files which are not there

### ISSUE THREAD

**Issue by RalphBergmannKMB** [warpdotdev/Warp#2624]
### Describe the bug

I am in the folder `~/Downloads/mock` and want to go one level up.
When I start typing `cd ../` it suggests me `uses_cases`.

This folder exists but in a completely different location. But it remembers that I was there and suggests it now.

Is it possible that it only suggests folders/files which are there? And not also the ones it remembers?

![SCR-20230209-p7c](https://user-images.githubusercontent.com/47594120/217887875-7b7db8b9-99d9-4824-a13a-0e28d4e9e9b9.png)

### To Reproduce

I have no idea how to reproduce it :( 

Go throuth your file system for a while that it remmbers all folders and then do `cd ../` in a different folder.

### Expected behaviour

I only suggests folders/files which are there.

### Operating System

MacOS

### Shell Version

zsh 5.8 (x86_64-apple-darwin20.0)

### Warp Version

v0.2023.01.31.08.08 stable 02

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
So what you're seeing is the Autosuggestions, which are based on the history of commands run in the past or AI based suggestions, it can either be accepted with `RIGHT-ARROW` or just ignore it by pressing `ENTER` or typing what you want instead. You can also disable the auto-suggestion altogether with the Command Palette `CMD-P` by toggling the "Autosuggestion"

![CleanShot 2023-02-09 at 14 38 54](https://user-images.githubusercontent.com/16809145/217945809-8bdb8840-7172-4da5-a970-44832e438df9.gif)

**Comment by RalphBergmannKMB** [comment]
Hi @dannyneira is it not possible to have this auto-suggestion based on the context? Because most of the time I like it and do not want to disable it. But on the other hand, when it always suggests wrong things it gets useless.

So why not have a function which filters all auto-suggestions if they are valid or not?

**Comment by dannyneira** [comment]
Thanks! It's certainly a great idea for an enhancement, I'll bring this up with the team as there is general push for improving completions and suggestions.
