### ISSUE TITLE
Regression: channel 3: bad ext data

### ISSUE THREAD

**Issue by mhz5** [warpdotdev/Warp#2626]
Regression of #2325

This issue is back again. Warp version `v0.2023.01.03.08.03.stable_01`. macOS Monterey Version `12.6.1`. I can't capture my screen on my work machine but perhaps I can recreate it on my personal laptop later. But also perhaps not, different macOS.

_Originally posted by @noahprime in https://github.com/warpdotdev/Warp/issues/2325#issuecomment-1376124468_
            
____
I also have this issue.

# OS Version
macOS 12.6.1

# Shell Version
zsh 5.8 (x86_64-ubuntu-linux-gnu)

# Warp Version
v0.2023.01.31.08.08.stable_02

# Does this block you from using Warp daily?
Yes

**Comment by dannyneira** [comment]
Thanks for letting us know, I'll bring this up with the team and we'll post any updates on here.

**Comment by sjpocnionetihmz** [comment]
Thanks! In the meantime, I believe[ this temporary](https://github.com/warpdotdev/Warp/issues/2325#issuecomment-1347321607) workaround still works.

**Comment by mhz5** [comment]
Thanks! In the meantime, I believe[ this temporary](https://github.com/warpdotdev/Warp/issues/2325#issuecomment-1347321607) workaround still works.

**Comment by dannyneira** [comment]
We had engineers looking into this. Not a regression but related to #https://github.com/warpdotdev/Warp/issues/1957
Please subscribe to that issue for more updates on a fix.
Closing this issue as duplicate.
