### ISSUE TITLE
Any way to remove/hide the top tab completely?

### ISSUE THREAD

**Issue by muscaiu** [warpdotdev/Warp#2629]
### Discord username (optional)

TyLeR#2307

### Describe the solution you'd like?

```text
Looking for a way to completely remove the top bar and tabs.
```

### Additional context

<img width="700" alt="Screenshot 2023-02-10 at 09 25 54" src="https://user-images.githubusercontent.com/11426309/218030282-5efc0daa-fccc-4b8d-9fae-5416dcb080bb.png">

Any way to remove/hide this?

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @muscaiu, I like your screenshot
We have an issue tracking this here: https://github.com/warpdotdev/Warp/issues/1009
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.
Closing as duplicate.
