### ISSUE TITLE
Config path of default starting directory

### ISSUE THREAD

**Issue by XinwenCheng** [warpdotdev/Warp#2635]
### Describe the solution you'd like?

```text
Please provide an option to set the path of default starting directory in the future version, thanks in advance!
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @
We have an issue tracking this here #105

This is actively being worked on, and soon to be released. We'll post any updates there ⬆️ 
Closing as duplicate.
