### ISSUE TITLE
Certain PROMPT_COMMAND in bashrc breaks ssh wrapper

### ISSUE THREAD

**Issue by gnattu** [warpdotdev/Warp#2636]
### Describe the bug

When the bashrc includes the syntax `+=`, the ssh wrapper will never finish initializing and resulted in a not completed prompt.

I noticed this because the recent update to `bash` package on Arch Linux changed the default system-wide bashrc which breaks warp's ssh wrapper. After I modified the bashrc I can use the ssh wrapper once again, but this is not ideal as I have a bunch of systems running on Arch Linux and I have to do this manually for all of them.

### To Reproduce

- Edit the bashrc, in my case, the `/etc/bash.bashrc` on Arch Linux

- Set `PROMPT_COMMAND` with `+=` syntax, for example:  `PROMPT_COMMAND+=('printf "\033_%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"')`

- Then you will see this:
<img width="198" alt="Screenshot 2023-02-13 at 11 36 58" src="https://user-images.githubusercontent.com/12995396/218364876-f355b35e-bc43-492d-b8a5-b751b1075cd5.png">

- Same prompt, but this time with `=` : `PROMPT_COMMAND=('printf "\033_%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"')`

- Warp bootstraps normally: 
<img width="283" alt="Screenshot 2023-02-13 at 11 38 24" src="https://user-images.githubusercontent.com/12995396/218365042-a54a18ce-24fa-4d74-b332-a8e5bedde35d.png">

### Expected behaviour

The SSH wrapper should bootstrap.

### Operating System

None

### OS Version

macOS 13.2 local, Arch Linux (rolling latest on 20220212) remote

### Shell Version

zsh 5.8.1 local, bash 5.1.016-3 remote

### Warp Version

v0.2023.01.31.08.08.stable_02

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @gnattu  looks like using the += operator to append may be breaking the bootstrap process. I'll let the team know and post any updates on this thread.

**Comment by dannyneira** [comment]
Reopening for now, but this should be fixed in an upcoming release.

**Comment by dannyneira** [comment]
Hey Folks, the update released today `v0.2023.03.07.08.02.stable_01` fixes this issue in Warp. Closing as resolved. 🚀
