### ISSUE TITLE
Warp doesn't open ".command" file type on Mac

### ISSUE THREAD

**Issue by Wolfenberg** [warpdotdev/Warp#2640]
### Describe the bug

What is a COMMAND file? Script file created for Terminal, the command line utility included with Mac OS X; contains plain text shell commands; used for executing commands automatically as if they were typed successively at the command line. You can double-click a COMMAND file to run it.

iTerm for example opens it and runs it, but Warp open it, but doesn't run it. 

### To Reproduce

Create test.command file with contents:
`#!/bin/bash
echo "Hello world"`

Right click, select Get Info and choose Open with Warp.

Double click test.command.

Observe that Warp opens a new tab with a folder where test.command file is, but it doesn't try to run it.

### Operating System

MacOS

### OS Version

13.2 (22D49)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.01.31.08.08.stable_02

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know, closing in favor of duplicate #1917

**Comment by abbasahmad** [comment]
This behavior is back. the .command files are opened as files for editing and not executed;
