### ISSUE TITLE
Output from detached process goes to input line

### ISSUE THREAD

**Issue by absorbb** [warpdotdev/Warp#2642]
### Describe the bug

If you run some detached process that prints something to stdout 
or kill a process that prints something as part of shutdown routine after releasing tty – that text goes to input line.

That may mess your input command badly and it is annoys a lot cleaning some line unexpectedly appeared in terminal input.
I think under no circumstance text should appear in input line without actions from user. 

### To Reproduce

1. run  `ping example.com &`

### Expected behaviour

Detached process output may be added to the block of process where it comes from or to the new "detached process"  block. Probably that block must be moved to the bottom every time new lines added.

### Screenshots

<img width="550" alt="image" src="https://user-images.githubusercontent.com/741268/218683642-24d9e50b-abca-4073-a72e-7cc122e479f2.png">

### Operating System

MacOS

### OS Version

13.2

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.02.07.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @
We're actively working on this known issue, and tracking it here #1387 
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.

Closing as duplicate.
