### ISSUE TITLE
Make the prompt start on top

### ISSUE THREAD

**Issue by nitzcard** [warpdotdev/Warp#2643]
### Describe the solution you'd like?

```text
The prompt start at the bottom of the screen, is it possible to make it start at the top and be more dynamic in position like in other terminals? 

Thanks.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @nitzcard ( appreciate the help @ulken )

This is being worked on and we have an issue tracking this here #22

Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.
Closing as duplicate.
