### ISSUE TITLE
Shift+up/down arrows not working correctly

### ISSUE THREAD

**Issue by tomkludy** [warpdotdev/Warp#2646]
### Describe the bug

When I open an editor in the terminal, Shift+Up or Shift+Down do not work - the cursor does not move.  In emacs and micro editors this prevents doing multi-line selection.  Additionally, if pressing Shift+Up/Down many times in rapid succession, then regular Up/Down (without Shift) also stops working, until I press some other key.

### To Reproduce

1. Open micro (https://micro-editor.github.io) in a warp terminal, on a multi-line text file.
2. Press Up/Down arrows to verify they are working.
3. Press Shift+Down arrow.  Cursor does not move, and no text is selected.
4. Press Shift+Down arrow many times rapidly.  (5 quick taps in a row always reproduces the problem for me)
5. Press Up/Down arrows (without Shift), now they don't work.
6. Press Left or Right arrows, or type any text
7. Press Up/Down arrows (without Shift), now they are working again.

### Expected behaviour

Shift+Up and Shift+Down should move the cursor up or down while selecting the line.  Up/Down should move the cursor up and down without selecting, even after many presses of Shift+Up/Down.

### Operating System

MacOS

### OS Version

13.2

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.02.07.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Sorry to hear about this @tomkludy , I was able to repro this. will bring up with the team and post any updates on this thread.

**Comment by elviskahoro** [comment]
This should be fixed and already out! Please comment if you're still experiencing any trouble!
