### ISSUE TITLE
perl warning: Setting locale failed.

### ISSUE THREAD

**Issue by bunam** [warpdotdev/Warp#265]
### Describe the bug

```shell
pveupgrade
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
```

### To Reproduce

Steps to reproduce:
1. Go to 'launch pveupgrade command on proxmox server'

2. See error 

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"

### Expected behaviour

```shell
no perl warning
```

### Operating System

MacOS

### OS Version

11.6 (20G165)

### Additional context

```shell
iterm2/Terminal on the same server is OK
```

**Comment by prikkprikkprikk** [comment]
I'm seeing this also, exactly as @bunam describes.

On a server from another provider I get:

```
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory`
```

**Comment by elviskahoro** [comment]
@bunam is this still happening to you? please comment if so gonna close for now thoughu
