### ISSUE TITLE
Command 'clear' is executed after its order

### ISSUE THREAD

**Issue by XinwenCheng** [warpdotdev/Warp#2651]
### Describe the bug

When I input commands like `clear;ll`, it should execute `ll` after `clear` is done, but the current situation is more like `ll;clear`.

Please check my screenshot, and I have to say, iTerm2 is right in this scenario.

Hope you will consider fixing it. Thanks in advance!

### To Reproduce

You can just simply input `clear;ll` and check the result.

### Expected behaviour

Command(s) after `clear` executes after `clear` is done.

### Screenshots

https://user-images.githubusercontent.com/795334/219003062-28f0bc1c-d505-48f9-9929-f4ea1ed099d4.mov

### Operating System

None

### OS Version

Ventura 13.2

### Warp Version

v0.2023.02.07.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
So this is a known issue, we have a feature request to decouple clear from other run commands, as with other terminals. You can track that request here: #2382

We'll post updates on that thread.

Closing as duplicate request/issue.
