### ISSUE TITLE
How do you logout?

### ISSUE THREAD

**Issue by petty** [warpdotdev/Warp#2655]
### Describe the bug

I signed up & logged in ... just curious how do I log out? how do I delete my account?

### To Reproduce

Log in then try logging out ...

### Operating System

None

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @petty You can remove Warp user login with `sudo security delete-generic-password -l "dev.warp.Warp-Stable" $HOME/Library/Keychains/login.keychain`

Please see more here: https://docs.warp.dev/help/uninstalling-warp
