### ISSUE TITLE
Inaccurate text selection

### ISSUE THREAD

**Issue by probablykasper** [warpdotdev/Warp#2657]
### Describe the bug

Text selection does not behave like native

### To Reproduce

Select text

### Expected behaviour

The middle of a character should be used to determine whether it's selected

### Screenshots

https://user-images.githubusercontent.com/11315492/219204440-b6cc6d13-116b-4fca-93b7-effba87e1c0e.mp4

### Operating System

None

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this! We're tracking this issue here #1871

Closing this one as duplicate, but please do 👍 that issue to help us gauge the impact.

**Comment by probablykasper** [comment]
I did see that issue, but I think that's about determining which words to select when double-clicking, not about accurately selecting individual characters
