### ISSUE TITLE
DUP: Duplicate of #056 - Feature Request: Live Blocks

### ISSUE THREAD

**Issue by DavidMChan** [warpdotdev/warp#266]
### Describe the solution you'd like?

When using warp, it would be super awesome if I could run blocks in the background of the current session - for example, if I ran top, the command would continue running in the block, while presenting a new prompt so I could continue working in the same session. While I could use something like tmux to do this, it would be super cool to have this working natively in the shell.

(Yes, I know this is a crazy amount of work, but man would it be cool.)

**Comment by elviskahoro** [comment]
Linking:
- #56
