### ISSUE TITLE
Warp (Application not Responding)

### ISSUE THREAD

**Issue by aPinix** [warpdotdev/Warp#2660]
### Describe the bug

The app doesn't run (Application not Responding)

I've been trying to run the app for a long time.
I am constantly downloading the latest versions to see if I can get them to work.

### To Reproduce

1. Click to launch the Warp.app
2. Appears on the Dock and hangs (Application not responding)

### Expected behaviour

I would expect it to run

### Screenshots

<img width="329" alt="CleanShot 2023-02-16 at 17 47 32@2x" src="https://user-images.githubusercontent.com/698523/219446634-6e99cd94-2248-4d72-8048-d106e3d8d369.png">

### Operating System

None

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

downloaded latest on 16th Feb 2023

### Additional context

It used to run and shut down, and for a split second, I would see a black window and disappear immediately, but now it just hangs.

LOG:
default22:22:36.715883+0000runningboarddCalculated state for app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>: running-active (role: UserInteractiveFocal)
default22:22:36.715882+0000runningboardd[app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>:88260] Ignoring jetsam update because this process is not memory-managed
default22:22:36.715898+0000runningboardd[app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>:88260] Ignoring suspend because this process is not lifecycle managed
default22:22:36.715924+0000runningboardd[app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>:88260] Ignoring GPU update because this process is not GPU managed
default22:22:36.716083+0000runningboardd[app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>:88260] Ignoring memory limit update because this process is not memory-managed
default22:22:36.724286+0000stableorder window: 233f3 op: 0 relative: 0 related: 0
default22:22:36.749794+0000runningboarddInvalidating assertion 184-174-5531800 (target:[app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>:88260]) from originator [osservice<http://com.apple.WindowServer(88)>:174]
default22:22:36.752753+0000runningboarddInvalidating assertion 184-174-5531801 (target:[app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>:88260]) from originator [osservice<http://com.apple.WindowServer(88)>:174]
default22:22:36.867865+0000runningboardd[app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>:88260] Ignoring jetsam update because this process is not memory-managed
default22:22:36.867902+0000runningboarddCalculated state for app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>: running-active (role: UserInteractiveFocal)
default22:22:36.867904+0000runningboardd[app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>:88260] Ignoring suspend because this process is not lifecycle managed
default22:22:36.867939+0000runningboardd[app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>:88260] Ignoring GPU update because this process is not GPU managed
default22:22:36.868005+0000runningboardd[app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>:88260] Ignoring memory limit update because this process is not memory-managed
default22:22:37.114614+0000ReportCrashloadStoreInfo [platform 1] dev.warp.Warp-Stable from file:///Applications/Warp.app/
default22:22:37.136267+0000ReportCrashdev.warp.Warp-Stable is not a MetricKit client
default22:22:37.136367+0000ReportCrashSending event: http://com.apple.stability.crash {"appVersion":"0.1.0","bundleID":"dev.warp.Warp-Stable","bundleVersion":"20230112.015956","coalitionName":"dev.warp.Warp-Stable","exceptionCodes":"0x0000000000000000, 0x0000000000000000(\n    0,\n    0\n)EXC_CRASHSIGABRT","incidentID":"E8B728C6-F959-49B4-BD9C-EA19BBE8057E","logwritten":1,"process":"stable","responsibleApp":"stable","terminationReasonNamespace":"<none>"}
default22:22:37.136468+0000analyticsdReceived event: http://com.apple.stability.crash {"appVersion":"0.1.0","bundleID":"dev.warp.Warp-Stable","bundleVersion":"20230112.015956","coalitionName":"dev.warp.Warp-Stable","exceptionCodes":"0x0000000000000000, 0x0000000000000000(\n    0,\n    0\n)EXC_CRASHSIGABRT","incidentID":"E8B728C6-F959-49B4-BD9C-EA19BBE8057E","logwritten":1,"process":"stable","responsibleApp":"stable","terminationReasonNamespace":"<none>"}
default22:22:37.136724+0000analyticsdAggregated. Transform: StabilityCrashNumerator3WithBundleVersion Dirty: 1 Event: http://com.apple.stability.crash {"appVersion":"0.1.0","bundleID":"dev.warp.Warp-Stable","bundleVersion":"20230112.015956","coalitionName":"dev.warp.Warp-Stable","exceptionCodes":"0x0000000000000000, 0x0000000000000000(\n    0,\n    0\n)EXC_CRASHSIGABRT","incidentID":"E8B728C6-F959-49B4-BD9C-EA19BBE8057E","logwritten":1,"process":"stable","responsibleApp":"stable","terminationReasonNamespace":"<none>","timestamp":1673821357136323}
default22:22:37.136802+0000analyticsdAggregated. Transform: StabilityCrashNumerator3WithIncidentID Dirty: 1 Event: http://com.apple.stability.crash {"appVersion":"0.1.0","bundleID":"dev.warp.Warp-Stable","bundleVersion":"20230112.015956","coalitionName":"dev.warp.Warp-Stable","exceptionCodes":"0x0000000000000000, 0x0000000000000000(\n    0,\n    0\n)EXC_CRASHSIGABRT","incidentID":"E8B728C6-F959-49B4-BD9C-EA19BBE8057E","logwritten":1,"process":"stable","responsibleApp":"stable","terminationReasonNamespace":"<none>","timestamp":1673821357136323}
default22:22:37.136862+0000analyticsdAggregated. Transform: StabilityCrashNumerator3 Dirty: 1 Event: http://com.apple.stability.crash {"appVersion":"0.1.0","bundleID":"dev.warp.Warp-Stable","bundleVersion":"20230112.015956","coalitionName":"dev.warp.Warp-Stable","exceptionCodes":"0x0000000000000000, 0x0000000000000000(\n    0,\n    0\n)EXC_CRASHSIGABRT","incidentID":"E8B728C6-F959-49B4-BD9C-EA19BBE8057E","logwritten":1,"process":"stable","responsibleApp":"stable","terminationReasonNamespace":"<none>","timestamp":1673821357136323}
error22:22:37.140178+0000kernel1 duplicate report for Sandbox: locationd(152) deny(1) file-read-data /Applications/Warp.app
default22:22:37.649764+0000runningboarddInvalidating assertion 184-174-5531796 (target:[app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>:88260]) from originator [osservice<http://com.apple.WindowServer(88)>:174]
default22:22:37.650528+0000runningboarddInvalidating assertion 184-146-5531797 (target:[app<http://application.dev.warp.Warp-Stable.167715373.167715470(501)>:88260]) from originator [osservice<http://com.apple.coreservices.launchservicesd>:146]

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @aPinix Sorry to hear about this issue, I'll bring this up with the team but in the meantime can you please try a full [uninstall](https://docs.warp.dev/help/uninstalling-warp) (remove all the database/settings/etc.), then [reinstall](https://docs.warp.dev/getting-started/getting-started-with-warp#installing-warp).

**Comment by tsarbo** [comment]
@vorporeal I had the same issue when I updated Mac OS to 13.2.1 and running the command you provided solved it.
Thank you!

**Comment by vorporeal** [comment]
We'll be more broadly rolling out this fix soon.  If you encounter this issue and the command above doesn't fix things for you, please open a new issue!
