### ISSUE TITLE
Partial lines at top of 'less' window don't scroll

### ISSUE THREAD

**Issue by rogerl50** [warpdotdev/Warp#2661]
### Describe the bug

If my window height accommodates a fractional number of lines, the line at the top is cut off. That makes sense. But when I hit up arrow to scroll up one line in `less`, that line does not scroll - it remains at the top and is duplicated below. The first screenshot in the screenshots section is a view of the window initially, and the second is a view after an up-arrow.

### To Reproduce

See above description.

### Expected behaviour

I would expect the fractional line to scroll along with everything else.

### Screenshots

<img width="443" alt="Screen Shot 2023-02-16 at 1 46 44 PM" src="https://user-images.githubusercontent.com/63379656/219459419-fb9a0c4f-0bb8-428e-a4be-94848d93f316.png">

<img width="410" alt="Screen Shot 2023-02-16 at 1 47 15 PM" src="https://user-images.githubusercontent.com/63379656/219459514-1320ce4e-ac8e-4fcf-a88d-3dfcc3c452dc.png">

### Operating System

MacOS

### OS Version

11.7.1

### Shell Version

zsh 5.8

### Warp Version

v0.2023.02.07.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @rogerl50 Thanks for submitting, do you mind providing a recording of the issue, I think it may help to provide the better context of the issue for us to reproduce on our end vs screenshots. We'll follow up with any updates/questions on this thread.

**Comment by rogerl50** [comment]
As requested, here is a movie of the interaction. Twice during the movie I hit 'k', which moves the window one line backwards toward the start of the file.

https://user-images.githubusercontent.com/63379656/219503233-7a541970-3dd6-4190-997f-bba80f112cbd.mov

**Comment by dannyneira** [comment]
Thanks for the extra context @rogerl50 , I wasn't able to reproduce this issue on my end. Just curious if you may have some flags on your less alias `l`, can you try with just normal `less` and see if the issue persists?

I'm running `alias less='less -R'` and have no issues with the rendering. If the issue persists with normal less or less -R, then I recommend you try [disabling the sticky command header](https://docs.warp.dev/features/blocks/sticky-command-header), as it appears to still be visible during a `less` which isn't normal.

**Comment by rogerl50** [comment]
This was caused by a `-X` in my `less` defaults. I have no idea why that was there, probably been there for ten years. I've removed it and things are fine. I have no idea if this is something you want to address anyway. Thanks.

**Comment by rogerl50** [comment]
I just noticed that removing `-X` makes the `-F` switch (which is also in my defaults) fail, and fail by not showing the file at all. That is, `less -F <small file>` prints nothing, while `less -FX <small file>` shows the file and exits `less`, as it is supposed to. That is not the way things work on, for example, `iterm2`,

**Comment by dannyneira** [comment]
We'll be tracking this issue over at #3214  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
