### ISSUE TITLE
Ctrl-Enter to prevent line breaks.

### ISSUE THREAD

**Issue by ChiakiUehira** [warpdotdev/Warp#2663]
### Discord username (optional)

Chiaki Uehira#9754

### Describe the solution you'd like?

```text
Can set Ctrl-Enter to not break lines.
Can set keyboard shortcuts other than line breaks for Ctrl-Enter (I assign Enter).
```

### Is your feature request related to a problem? Please describe.

```text
Sometimes the timing of keyboard input overlaps, causing a line break when I want to execute a command.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @ChiakiUehira We will post updates here on this thread, but in general we have a couple of related requests here:

https://github.com/warpdotdev/Warp/issues/1909
https://github.com/warpdotdev/Warp/issues/537
