### ISSUE TITLE
Transparency and Blurring documentation link is broken

### ISSUE THREAD

**Issue by prabhathkotha** [warpdotdev/Warp#2667]
### Describe the bug

This link is broken: https://docs.warp.dev/appearance/transparency-and-blurring.
This url is accessible by going to: Settings > Appearance > Window Blur Radius > _tooltip_.

### To Reproduce

1. Open settings (`⌘` + `,`)
2. Navigate to `Appearance`
3. Click on the tooltip next to `Window Blur Radius`

### Expected behaviour

I expected to be taken to documentation about what "Window blur radius" is.

### Screenshots

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/35498076/219770862-5372fe17-7aca-4305-a0b6-a836ee350d68.png">
<img width="265" alt="image" src="https://user-images.githubusercontent.com/35498076/219770957-e18b91c3-9326-459f-bd56-ce71e72bfa13.png">

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.02.14.08.05.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
@prabhathkotha Thanks for letting us know, I've added redirects for this page to the new one. https://docs.warp.dev/appearance/opacity-blurring-dimming
