### ISSUE TITLE
SSH wrapper and fish shell

### ISSUE THREAD

**Issue by bmorris591** [warpdotdev/Warp#2670]
### Local Shell and Version

bash 3.2.57(1)-release. fish 3.6.0. No ZSH

### Remote Shell and Version

5.1.16(1)-release. fish 3.3.1. No ZSH

### Operating System and Version

Local Ventura 12.2.1 Remote Ubuntu Server 22.04.2

### Warp Version

v0.2023.02.14.08.05.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

Error shown on SSH and the session is terminated.

```
fish: Unsupported use of '='. In fish, please use 'set _user "$(command -v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER)"'.
```

![Screenshot 2023-02-18 at 08 37 52](https://user-images.githubusercontent.com/3940884/219850734-6b2390f7-0543-4fa7-ba57-2b65d84de9d9.png)

SSH works fine when the remote user doesn't have fish as its login shell.

### Include shell xtrace output

Tried `set -x WARP_DEBUG_MODE 1` before running the ssh, didn't produce any extra output.

### Does this block you from using Warp daily?

No

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @bmorris591 Sorry to hear about this, as far as I'm aware improvements for fish shell in SSH session support are being worked on and can be tracked here https://github.com/warpdotdev/Warp/issues/871

Closing as duplicate, but please feel free to :+1: to the request above as it helps us gauge the interest/impact.

**Comment by idolize** [comment]
@dannyneira Any update on those improvements that are being worked on? Because the linked issue has 61 thumbs up and has been open for over 3.5 years...
