### ISSUE TITLE
Allow option to copy Version number from About page in settings

### ISSUE THREAD

**Issue by onecrayon** [warpdotdev/Warp#2672]
### Discord username (optional)

Skaak#0007

### Describe the bug

It is not possible to either select the version number (in order to copy it) or click to copy the version number in the Warp settings. This adds an additional, unnecessary layer of annoyance to posting accurate bugs to this issue tracker.

### To Reproduce

1. Open the Warp settings (`command-,`)
2. Click the About sidebar option
3. Attempt to select or copy the version number

### Expected behaviour

It should be possible to easily copy the version number from within Warp's settings (or via some sort of specialized commandline option).

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin22.1.0)

### Warp Version

v0.2023.02.14.08.05.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by onecrayon** [comment]
**Update:** Immediately after posting this, I discovered that the version number *is* copyable from the Account portion of settings. 🤦 

So this is pretty low-priority, but still a nice-to-have if there are other folks like myself who just don't look at that page in settings.

**Comment by dannyneira** [comment]
Hey @onecrayon Thanks for letting us know, Keeping this open as a feature request to put the version/copy option in the typical "About" Page. In general, we are looking to make improvements to the settings modal.

Also here's a demo of a couple of places to copy the version in Warp:

https://user-images.githubusercontent.com/16809145/220478205-2faa607b-57c6-4008-a11e-399e3ffe312c.mp4

**Comment by dannyneira** [comment]
Hey Folk, this is being worked on and should be released soon! 🚀

**Comment by dannyneira** [comment]
Hey Folks, This option was released in Warp version `v0.2023.03.21.08.02.stable_01`

You can now copy the Warp version from the about page. 🚀 

![CleanShot 2023-03-24 at 14 04 07](https://user-images.githubusercontent.com/16809145/227628131-3f68d6bb-86af-4a20-9709-881155ea3a41.png)
