### ISSUE TITLE
Improve mouse scroll speed for sidebar "Warp Essentials" and "Keyboard Shortcuts"

### ISSUE THREAD

**Issue by dawdmaow** [warpdotdev/Warp#2673]
### Describe the bug

The relevant sidebar is slow to a degree that is obviously not correct.

### To Reproduce

1. Open he "Keyboard Shortcuts" sidebar
2. Notice if it moves slower than expected when using the mouse wheel on it

### Expected behaviour

Speed closer to one I see in other apps.

### Operating System

None

### OS Version

February 16, 2023

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @dawdmaow I'll mark this one as a feature request to improve the scroll speed for the sidebar in general ( not just keyboard shortcuts that seem slow ). AFAIK it was designed to scroll a bit slower currently, but this can be improved.

**Comment by SampsonCrowley** [comment]
@dannyneira it's ungodly slow. it should be labeled a bug it's that bad in my opinion. I have to go through a full revolution to get through a pixel. there should at least be at minimum a setting to set your desired speed. it's not usable
