### ISSUE TITLE
Disconnect from remote shell crash the terminal

### ISSUE THREAD

**Issue by chungquantin** [warpdotdev/Warp#2674]
### Discord username (optional)

chasechung#4533

### Describe the bug

When I try to connect to any remote shell and if my shell disconnect because timeout, the terminal will be dead too. 

### To Reproduce

1. Connect to a remote shell on any virtual machine
2. Wait for it to reach the timeout
3. Auto disconnect and log you out of the shell back to the main terminal
4. Bug appear when trying to run any command on the main terminal

### Expected behaviour

After disconnecting, the main terminal should work normally instead of throwing a bug.

### Operating System

MacOS

### OS Version

macOS Big Sur v11.5.2

### Shell Version

GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Warp Version

v0.2023.02.14.08.05.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @chungquantin 
We're tracking this in this here #2476 
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.

Closing as duplicate.
