### ISSUE TITLE
Blur effect not applied when launched by folder drag-drop

### ISSUE THREAD

**Issue by susemi99** [warpdotdev/Warp#2676]
### Describe the bug

Blur not applied when launched by folder drag-drop

### To Reproduce

1. Window opacity: 70, Blur radius: 18
2. quit Wrap
3. folder drag-drop to Warp app
4. blur not applied

### Screenshots

https://user-images.githubusercontent.com/1233318/220053353-040f04d2-a9fd-4dd4-934d-18c6acd3fdcd.mov

### Operating System

MacOS

### OS Version

13.2.1

### Warp Version

v0.2023.02.14.08.05.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @susemi99 
We'll post any updates on this thread.
Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by vorporeal** [comment]
Hey @susemi99 - what tool are you using that adds the Warp icon to the Finder toolbar?

**Comment by susemi99** [comment]
> Hey @susemi99 - what tool are you using that adds the Warp icon to the Finder toolbar?

Go to `/System/Applications` then press `Command` and  `Drag Warp app`  to toolbar

**Comment by susemi99** [comment]
fixed in `v0.2023.04.11.08.03.stable_00`
