### ISSUE TITLE
Tab auto completion not working anymore with cd command

### ISSUE THREAD

**Issue by guillaumebesse** [warpdotdev/Warp#2677]
### Describe the bug

No more TAB auto completion proposed with cd command

### To Reproduce

1 Go your home directory (/Users/username)
2  type "cd D"
3 nothing proposed 

### Screenshots

Everything is working as expected with ls command
<img width="746" alt="Screenshot 2023-02-20 at 09 55 58" src="https://user-images.githubusercontent.com/197707/220058767-3a75ae27-1249-4104-b07b-3d9d50c06d2f.png">

But not working with cd command 
<img width="760" alt="Screenshot 2023-02-20 at 09 55 35" src="https://user-images.githubusercontent.com/197707/220059169-5381946d-4bb2-4bff-96f9-1165976a9f44.png">

### Operating System

MacOS

### OS Version

12.6.3

### Shell Version

zsh 5.8.1 

### Warp Version

v0.2023.02.14.08.05.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by el-zoltan** [comment]
Something similar has kept me from transitioning to fully using Warp. As far as I can tell, normal Mac/VS Code/etc terminal behavior will default to auto completing paths if it doesn't know any better. So, when I want to do something like:

`aws s3 cp <some local path> ...` Warp will require that I type out or copy-pasta the local path, but in any other terminal I use they will auto complete the path--I assume for my mental well-being.

I'd like to use Warp if this gets addressed.

**Comment by endafarrell** [comment]
In "something that feels similar to this", I would like `python <first-part-of-path>+TAB` to allow me to use tab completion to find and execute my python modules.

**Comment by guillaumebesse** [comment]
@el-zoltan FYI I have already fully move from Iterm to Warp and I am really happy with it.

**Comment by szgupta** [comment]
Hey @guillaumebesse, are you using the `Open completions menu as you type` feature? If so, in the `cd` screenshot you shared, it seems there isn't a space after `cd`. If you do `cd `, you should be able to see the directory completions. If you still don't, would you mind sharing a video of what happens as you type out `cd `?

Similarly, if you aren't using `Open completions menu as you type`, you should be able to see the completions after `cd <tab>` (note the space after `cd`)

**Comment by szgupta** [comment]
@el-zoltan do you have `Open completions menu as you type` turned on? We intentionally disabled the fallback of file path completion for this case, but this could be something we re-consider. In your `aws` example, does it work as expected if that feature is turned on and you hit `<TAB>` after `... cp `?

**Comment by szgupta** [comment]
@endafarrell mind filing this as a separate feature request?

**Comment by dannyneira** [comment]
Thanks for submitting @guillaumebesse.

As Suraj mentioned try `cd `, once you put the space after cd the completion should default to showing directories to cd into.

**Comment by guillaumebesse** [comment]
@dannyneira Thank you for your response. 
I tried to put a space like for ls command without success. This functionality stopped working I don't know when.

@szgupta Yes I have the open "Open completion as you type"

**Comment by endafarrell** [comment]
> @endafarrell mind filing this as a separate feature request?

Done: https://github.com/warpdotdev/Warp/issues/2694

**Comment by guillaumebesse** [comment]
This is a serious problem for me. Any help or ideas welcomed.

**Comment by el-zoltan** [comment]
> @el-zoltan do you have `Open completions menu as you type` turned on? We intentionally disabled the fallback of file path completion for this case, but this could be something we re-consider. In your `aws` example, does it work as expected if that feature is turned on and you hit `<TAB>` after `... cp `?

Hey, @szgupta, sorry I missed your reply, but I do have that turned on, yes. If I hit tab at that point I get nothing, and even if I start populating the path... nothing. HOWEVER, if I turn that off path completion starts working with hitting tab.

**Comment by mparramont** [comment]
I was having the same issue on a new install of Warp (I installed Warp many months ago before and it kept my settings from then).

I turned "Open completions menu as you type" on and off and it fixed the problem for me.

**Comment by dannyneira** [comment]
@guillaumebesse Any luck with turning the "Open completions menu as you type" feature off/on to fix the issue?

**Comment by guillaumebesse** [comment]
@dannyneira I tried but unfortunately it did not work for me.

**Comment by dannyneira** [comment]
@guillaumebesse Got it, try to remove Warp settings with `defaults delete dev.warp.Warp-Stable` it's possible there is a keyboard shortcut set overriding the normal completion `TAB` key. beyond that I'm not 100% sure what may be causing this issue and we'll need to setup some kind of live troubleshooting session on Zoom.

**Comment by guillaumebesse** [comment]
@dannyneira I executed your command without success. Thank you for your help.

**Comment by guillaumebesse** [comment]
Good news... Its looks like the last update v0.2023.03.07.08.02.stable_01 fixes the problem.
