### ISSUE TITLE
Please provide an option to confirm tab closing

### ISSUE THREAD

**Issue by hclihn** [warpdotdev/Warp#2679]
### Describe the solution you'd like?

```text
I would like to have a setting which allows the user to set "Confirm on tab/window closing". 

I have accidentally closed important tabs many times due to the crowded tabs in the window. Unfortunately, there is no unding the tab closing action and the information in the tab is lost.

If Warp has a setting which allows the user to set "Confirm on tab/window closing", then every time, when the user accidentally close the tab/window, Warp would show a confirmation dialog box to confirm the user's intent. This feature would say my a lot of "Oops, *&%$#...".
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @hclihn!

This could totally be an enhancement to the quit modal feature. https://docs.warp.dev/features/sessions/quit-warning-modal. Currently, it only warns on Windows/Tabs/Panes running an active command but may be adapted to show on any window/tab/pane.

Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by muescha** [comment]
I believe your muscle memory would automatically click on the confirm button every time.

It would be preferable to have an "undo" command that remains available for a specified number of minutes (which can be adjusted in the settings).

**Comment by CRoulandSpiral** [comment]
@dannyneira more broadly a prompt before quitting would also be great. When cleaning up tabs, I often accidentally hit Ctrl + Q instead of Ctrl + W, and then all tabs go away (unless I'm fortunate to have one running an active command and am saved by your warning). I'm nearly at the point of having one tab always running something so this stops happening.

**Comment by dannyneira** [comment]
We may be working on something to address this issue in the near future, possibly the option to restore closed tabs or something long those lines, no promises or ETA 🤞

**Comment by dannyneira** [comment]
Thanks for submitting this Folks. We will now be tracking this over at #2717

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Hi folks, we added window/tab/pane restoration. You can use a shortcut to reopen a recently closed window/tab/pane, and configure the grace period (default: 60 seconds) in Settings > Features > Session > Enable reopening of closed sessions.

<img width="853" height="126" alt="Image" src="https://github.com/user-attachments/assets/d6a42c7b-d4b4-4821-b005-9bc215b5f887" />
