### ISSUE TITLE
Referral feature not working after 10 referrals

### ISSUE THREAD

**Issue by Teleri** [warpdotdev/Warp#2680]
### Discord username (optional)

Teleri#1814

### Describe the bug

I've recently managed to refer 10 people to warp using the email or link options in the settings. However since then I am not able to continue using it and have the error message in screenshot attached.

### To Reproduce

Get 10 referrals, then try to view referral setting again

### Expected behaviour

Still be able to send emails or copy the link and see how many I have.

### Screenshots

<img width="506" alt="Screenshot 2023-02-21 at 09 11 27" src="https://user-images.githubusercontent.com/26676054/220300252-59f7bdad-5d13-4bc8-bc44-2814f72e92c0.png">

### Operating System

MacOS

### OS Version

Venture 13.2.1

### Shell Version

zsh 5.9

### Warp Version

v0.2023.02.14.08.05.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @Teleri sorry to hear about this. Not sure of a way to get that link back, but I'll bring it up with the team and we'll post updates here.

**Comment by Teleri** [comment]
> Hi @Teleri sorry to hear about this. Not sure of a way to get that link back, but I'll bring it up with the team and we'll post updates here.

@dannyneira reading the other issue #2723, I tried removing the keychain (to logout) as mentioned, and logged back in - now referral code is back.

**Comment by dannyneira** [comment]
Great that worked for you thanks for letting us know. I'll post some info in the docs around this issue and the workaround/resolution.

**Comment by AnurupMondal** [comment]
this referral feature still does not work as intended 
Even on the version for windows which has just been released

Operating System
Windows 11

OS Version
24H2

Warp Version
v0.2025.02.24.20.50.stable_04

Does this block you from using Warp daily?
No
