### ISSUE TITLE
SSH-Shell is stuck at "Starting shell..."

### ISSUE THREAD

**Issue by Finn-Ev** [warpdotdev/Warp#2682]
### Local Shell and Version

ZSH 5.8.1

### Remote Shell and Version

BASH 5.0.3(1)-release

### Operating System and Version

Debian 4.19.269-1

### Warp Version

v0.2023.02.14.08.05.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

![SCR-20230221-f1u](https://user-images.githubusercontent.com/52169228/220310257-5e9bfc2f-d627-4a09-afb9-822736898f1a.jpeg)

Before the latest update, the "Starting shell..." text disappeared after a few seconds. After the update it just stays there and I am not able to use the terminal at all. (The manpath hint has always been there and has never caused any problems)

### Include shell xtrace output

I've sent the output via email.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Sorry to hear about this known issue @Finn-Ev , Appreciate you taking the time to submit this issue.

We're tracking the issue here: https://github.com/warpdotdev/Warp/issues/1271 There is a possible workaround on that thread. Please :+1: as it helps us gauge the impact of the bug.

Closing as duplicate.

**Comment by ArthurEichmann** [comment]
same problem here. since last update ssh connection stuck in "starting shell...". with deactivated warp ssh wrapper its working again, but this cant be the solution since im working 90% in terminal with ssh.

**Comment by dannyneira** [comment]
Hey Folks, we're reopening this issue to track a few new SSH issues after recent updates.

**Comment by vorporeal** [comment]
Hey all - looking into this.  After successfully SSHing into these affected remote machines (with the SSH wrapper disabled or via a different terminal), can you tell me what shell you're using on the remote machine, and the output of running `echo $EPOCHREALTIME`?

**Comment by DEV-JWebers** [comment]
Same problem here, unable to start an SSH connection, local seems to work normally.
I think it happens to me since the update 1 week ago

**Comment by dan-jc-h** [comment]
Hi Thanks for looking at this.

> After successfully SSHing into these affected remote machines ... can you tell me what shell you're using on the remote machine, and the output of running `echo $EPOCHREALTIME`?

Here you go...

````bash
pi@raspberrypi:~ $ bash --version
bash --version
GNU bash, version 5.0.3(1)-release (arm-unknown-linux-gnueabihf)
````

````bash
pi@raspberrypi:~ $ echo $EPOCHREALTIME
echo $EPOCHREALTIME
1677279138.949908
pi@raspberrypi:~ $ date
date
Fri Feb 24 17:52:27 EST 2023
pi@raspberrypi:~ $ 
````

Let me know if you need anything else...

**Comment by vorporeal** [comment]
@dan-jc-h Is this using SSH via Warp with the wrapper disabled?  What's the output of running `locale` within Warp on your local machine (without SSH)?

I have an understanding of one possible cause, and am working on a fix.

**Comment by dan-jc-h** [comment]
That was actually with mac os Terminal as it's what I had open, so i went to just verify it in Warp... and I was able to connect with the SSH Wrapper enabled!

Output is the same as before (EPOCHREALTIME has obviously advanced).  

Here's my local `locale`... (in Warp)

````bash
locale
LANG=""
LC_COLLATE="en_CA.UTF-8"
LC_CTYPE="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_ALL="en_CA.UTF-8"
````

However - given that it's working now (for me) I'm not sure if you want to pursue this.  I did reboot the pi today.

I'll keep an eye on it an let you know if the wrapper stops working for me again, in the meantime, I will understand if you park this.

**Comment by domideimel** [comment]
Hey Folks here is my Output:

Bash on the Remote Machine:
`
$ bash --version
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
`

`
$ echo $EPOCHREALTIME
1677320086,077811
`

On my local Machine:
`
$ locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
`

@vorporeal If theres any more info I can provide, please let me know!

**Comment by domideimel** [comment]
>  However - given that it's working now (for me) I'm not sure if you want to pursue this. I did reboot the pi today.

I rebooted the remote machine as well, but with no difference in behaviour to the above mentioned Issue. My machine is a 1:1 Copy of @Finn-Ev.

**Comment by vorporeal** [comment]
Hey folks, can you try downloading and installing this hotfix release (not on autoupdate yet) and let me know if it fixes your SSH issues? https://storage.googleapis.com/warp-releases/stable/v0.2023.02.21.08.03.stable_02/Warp.dmg

**Comment by domideimel** [comment]
> Hey folks, can you try downloading and installing this hotfix release (not on autoupdate yet) and let me know if it fixes your SSH issues? https://storage.googleapis.com/warp-releases/stable/v0.2023.02.21.08.03.stable_02/Warp.dmg

Will try this first thing tomorrow! 👍

**Comment by dan-jc-h** [comment]
I tried to replicate my previous failure by restarting my session on my mac - and trying to connect to my pi from warp (v0.2023.02.21.08.03.stable_01)... and it works... I'm still able to ssh to my pi OK, with the SSH wrapper feature active.

So I won't be able to tell you of the hotfix fixes this issue, hopefully @domideimel will be able to verify if it fixes things or not.

But I can see if it obviously breaks anything...

Using the fix (...stable_02) everything continues to work OK (I didn't test a lot, couple of SSH sessions, with and without the wrapper... all works).

So I can't say if it has fixed anything, but I can say that it doesn't appear to have broken anything (and in the software world, that's not a bad day!)

Also - fired up an EC2 server on Amazon AWS, and was able to connect to it fine with the wrapper on and wrapper functions seemed to work.

**Comment by domideimel** [comment]
> Hey folks, can you try downloading and installing this hotfix release (not on autoupdate yet) and let me know if it fixes your SSH issues? https://storage.googleapis.com/warp-releases/stable/v0.2023.02.21.08.03.stable_02/Warp.dmg

@vorporeal I can connect no problem with this hotfixed version! Everything works as expected!

**Comment by Lumberjackz94** [comment]
this hotfix also works for me, thanks!

**Comment by vorporeal** [comment]
Wonderful; glad to hear it!  The fix will also be part of this week's standard release (on Thursday), so you can update without fear. :)
