### ISSUE TITLE
Fish-like abbreviations.

### ISSUE THREAD

**Issue by dawdmaow** [warpdotdev/Warp#2683]
### Describe the solution you'd like?

```text
One reason making them built-in is that even fish abbreviations currently don't work correctly, another is that other shells should probably have access to this feature too, and it makes sense to have access to same abbreviations across shells.
Yet another reason - aliases are more error-prone, when working with sudo for example.

Information about how fish shell abbreviations work is easy to find, I think I don't need to provide links here.
```

### Is your feature request related to a problem? Please describe.

```text
Lack of abbreviations.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @dawdmaow 
We have an issue tracking this here: https://github.com/warpdotdev/Warp/issues/1895

Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.
Closing as duplicate.

**Comment by dawdmaow** [comment]
I was hoping that it could be implemented in a way that Fish itself would not be necessary - whenever Nushell gets support in Warp I will probably switch to that shell.

**Comment by dannyneira** [comment]
We'll most likely support fish abbr first before trying to implement Warp abbr, but we'll reopen if this gets put on the roadmap, can't promise it will thou, but thanks for submitting!
