### ISSUE TITLE
Cannot search Emoji

### ISSUE THREAD

**Issue by Saafo** [warpdotdev/Warp#2685]
### Discord username (optional)

Saafo#9108

### Describe the bug

Cannot search Emoji(❌ ) in search bar

### To Reproduce

1. run command `echo "❌"`
2. search ❌

### Expected behaviour

found 1/1

### Screenshots

<img width="250" alt="image" src="https://user-images.githubusercontent.com/46736350/220553952-9e9cfdc5-5092-40cb-9ba2-c06df20654bf.png">

### Operating System

None

### Additional context

I know this may be related to the lack of IME ( international keyboard/character ) support which is actually being worked on and can be tracked here: https://github.com/warpdotdev/Warp/issues/320, but I'm using xcpretty and searching ❌  is the only way for me to find all building errors.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this, I was able to reproduce the issue. We'll post any updates/questions on this thread.

**Comment by ekkkkki** [comment]
same

**Comment by Saafo** [comment]
Seem resolved by the release of this week.
