### ISSUE TITLE
Warp keybinding for clear Blocks should be re-mappable (CMD-K)

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#2690]
### Describe the bug

From @HenryC-3

Hi.  Warp assigns `cmd+k` to `clear blocks` by default, which is not available in `keybindings.yaml`.

Is `cmd+k` overwriteable?

<img width="996" alt="image" src="https://user-images.githubusercontent.com/41246463/203536620-f32861d7-8765-44c4-a0f7-7f8e3c91c74e.png">

### To Reproduce

N/A

### Operating System

None

### Additional context

Hi.  Warp assigns `cmd+k` to `clear blocks` by default, which is not available in `keybindings.yaml`.

Is `cmd+k` overwriteable?

<img width="996" alt="image" src="https://user-images.githubusercontent.com/41246463/203536620-f32861d7-8765-44c4-a0f7-7f8e3c91c74e.png">

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.
