### ISSUE TITLE
Always show command input for inactive panes

### ISSUE THREAD

**Issue by gudmundurh** [warpdotdev/Warp#2696]
### Describe the solution you'd like?

First of all, thanks for building this awesome terminal. I was a skeptic at first – old habits die hard – but use it all the time today.

I always use multiple panes, jumping frequently between them. What annoys me is that whenever a pane becomes inactive, the command I am editing disappears. For a starter, this causes a visually disturbing jump in the UI. What is though more important is that I can not see my work-in-progress. I often compose a complex command in one pane, using a second pane while doing so to execute smaller commands to be able to complete the complex one. This is quite hard when commands are hidden in the inactive panes.

I love your approach to make the terminal resemble an IDE. Showing the active command would be in line with the incremental coding one typically does – while making the UI calmer.

Keep up the good work!

### Is your feature request related to a problem? Please describe.

No

### Additional context

![Warp_input_jumping](https://user-images.githubusercontent.com/46501/220992576-0232400e-5f3c-408f-8388-29192cf3572e.gif)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting, I see how seeing/comparing all commands in panes before could be useful. 

Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by simonst** [comment]
+1 for this, it would really calm and improve the user experience. Right now the Layout Shift is distracting.

**Comment by jolbax** [comment]
+1

**Comment by dannyneira** [comment]
hey Folks! We'll be tracking this request over on #303 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Thanks for your patience folks! As requested, in Warp version `v0.2023.09.19.08.04.stable_00` and above, the input editor remains visible in inactive panes when using split panes. 

![CleanShot 2023-09-21 at 13 34 04](https://github.com/warpdotdev/Warp/assets/16809145/5b27a944-5add-4296-9166-1e502f70fab7)

Closing as completed, but please let us know if any issues.
