### ISSUE TITLE
Auto-focus input to search on Keyboard Shortcuts modal `CMD+/`

### ISSUE THREAD

**Issue by dannyneira** [warpdotdev/Warp#2698]
### Describe the solution you'd like?

```text
When you open this list of keyboard shortcuts with cmd+/, it should focus on the search input for the keyboard shortcuts
```

### Is your feature request related to a problem? Please describe.

```text
The search input behavior is inconsistent when Keyboard Shortcuts in Settings or with the shortcut `CMD+/`
```

### Additional context

https://user-images.githubusercontent.com/16809145/221037070-67a6152a-67a0-4d80-9757-bf1960d9be2f.mp4

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
If anyone is interested in this feature, please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by elviskahoro** [comment]
This launched today! S/O to @MaanavKhaitan for fixing this!
