### ISSUE TITLE
Right-click in blocks (ctrl key)

### ISSUE THREAD

**Issue by lemarier** [warpdotdev/Warp#27]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The `Control` + `click` should trigger a right-click, especially in a block based on macOS standards.

**Additional context**
https://support.apple.com/en-ca/guide/mac-help/mh35853/mac

**Comment by zvory** [comment]
please!

**Comment by elviskahoro** [comment]
Sorry no ETA on this one! Will update you when there is!
