### ISSUE TITLE
SSH wrapper broken after update to v0.2023.02.21.08.03.stable_01

### ISSUE THREAD

**Issue by dan-jc-h** [warpdotdev/Warp#2701]
### Local Shell and Version

5.8.1

### Remote Shell and Version

5.0.3(1)-release

### Operating System and Version

mac os 13.2.1

### Warp Version

v0.2023.02.21.08.03.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

````
ssh pi@192.168.2.100

Starting shell...
````

...and the session never starts.

This worked (multiple times a day for the last couple of weeks) until I updated to v0.2023.02.21.08.03.stable_01 earlier today.  No other software updates to anything else today.

If I disable the ssh wrapper I can connect.

The remote host is a raspberry pi... output from `uname -a`:

`Linux raspberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l`

I can still use Warp (without the ssh wrapper) but many nice features are not available.

(I did not mess with my system and user rc files as indicated above, but it was a required item to submit this form.)

### Include shell xtrace output

+ '[' -z '\s-\v\$ ' ']'
+ shopt -s checkwinsize
+ '[' -z '' ']'
+ '[' -r /etc/debian_chroot ']'
+ '[' -n '' -a -n '' ']'
+ PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
+ '[' -x /usr/lib/command-not-found -o -x /usr/share/command-not-found/command-not-found ']'
+ set -o vi
+ set +o vi
+ HISTCONTROL=ignorespace
+ HISTIGNORE=' *'
+ printf '

### Does this block you from using Warp daily?

No

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by domideimel** [comment]
Same Issue here, Even after the latest update! 
This Issue was already reported but closed due to a misunderstanding...
https://github.com/warpdotdev/Warp/issues/2682

**Comment by dan-jc-h** [comment]
Thank you @domideimel, #2682 describes my situation as well, but I think you are correct, it got sidetracked.
