### ISSUE TITLE
Change warp icon

### ISSUE THREAD

**Issue by allmightychaos** [warpdotdev/Warp#2703]
### Discord username (optional)

Chaos#3003

### Describe the solution you'd like?

```text
Another solution I came up with, is an option to change the Warp Icon. 
For example instead of the standard, it has a white background - and I even designed one for it.

I have added either a png or the zip file with the .icns file in it down below. 
Would be a nice feature to add! :)
```

### Is your feature request related to a problem? Please describe.

```text
And yes, I do know it's possible to change it on MacOS, but the problem is after each update, it resets to the one with a black background, and I don't like that.
```

### Additional context

![Warp](https://user-images.githubusercontent.com/85056161/221151383-dee5374b-03d9-4548-a0fd-35dfc7ea0f5b.png)
[Warp.icns.zip](https://github.com/warpdotdev/Warp/files/10822991/Warp.icns.zip)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @allmightychaos! We're actually working on some improvements to the icon that will help it look good with any theme/background you set up on your Mac.

**Comment by djkgamc** [comment]
I'd like the Warp icon to look more a Terminal-y icon! I confuse it for too many other tools and it legitimately slows me down as a result.

**Comment by luizgabriel** [comment]
Hi, any update on that?

**Comment by dannyneira** [comment]
@luizgabriel no nothing yet. The icon may be updated, but not to look more like traditional terminal apps icons. You may be able to workaround this by manually changing the icon for Warp, but please note the icon will be replaced with the normal one on update.

**Comment by Ameer-Jamal** [comment]
Id love an update on this, VS CODE , Microsoft Outlook, Android Studio Edge Finder..etc ALL ARE BLUE and look so simmilar this would make an awesome feature 
I self implemented an icon as such on mac with these steps, 
1.Open applications folder 
2.find warp
3. press on warp then press cmd+i  to open "Get Info"
4.Drag and drop a png into the Get Info pane to the top left orginal icon here : 
![image](https://github.com/user-attachments/assets/5dcdcbc7-0386-4d83-b6d7-bfae6e57422d)
5. Remove from dock and put back or just logout login should show you the new icon.

-----
this is the icon for whoever wants it:
![Warp_Icon-custom](https://github.com/user-attachments/assets/a2a774ed-3fb8-4588-bced-ddc0d60b8409)

**Comment by agrohs** [comment]
Looking forward to a new longer tem icon...in the interim, here's a temporary cut that I created for myself in case any one needs another option to hold you over!

![WarpIcon](https://github.com/user-attachments/assets/a888cdae-9b5d-4c6d-862e-b21bc5f19b97)

**Comment by dannyneira** [comment]
Warp has a new logo and site today! https://www.warp.dev

![image](https://github.com/user-attachments/assets/36789e30-0e8a-4578-9b03-f5ae78a40a4a)

**Comment by dannyneira** [comment]
Closing as resolved, but please feel free to let us know if any issues with updating Warp.

**Comment by sebj54** [comment]
@dannyneira Can you share the previous icon file so we can replace the new one? 🙏 

I appreciate the new website and understand the change from a globl redesign perspective but the new icon is not enough colorful for my dock 😅

**Comment by zhangmxxx** [comment]
It seems like a dark-theme icon, which does not fit well into MacOS default icons.

**Comment by dannyneira** [comment]
Classic Warp icon, please note this will change on Warp updates. 

[Warp.icns.zip](https://github.com/user-attachments/files/17437915/Warp.icns.zip)

**Comment by rogerho1224** [comment]
@dannyneira Thank you so much for sharing the old icons. Funny how much hate the new icon is getting. Personally I found the left and right edges jarring enough to go down the rabbit hole of figuring out how to change it. It clashed too much with the rest of my app icons, which are much more flat visually.

**Comment by dannyneira** [comment]
Yeah, I get that. It's a very subjective thing, design. Some love it, and some hate the new logo/website/icon. 

Either way, it was a labor of love from many folks in our team so I can't discount that ❤️

**Comment by pquerner** [comment]
To change the icon via script:

1. Download the incs files and put them in a directory. Mine is at `~/.customicons`.

2. Add a script to your shell. For me `.zshrc`.

```
function fix_warp_icon() {
  cp ~/.customicons/Warp.icns /Applications/Warp.app/Contents/Resources/Warp.icns
  touch /Applications/Warp.app
  pkill -f "Warp.app"
}
```

3. Now, if an update of Warp changes the icon, go to another terminal application (the default `Terminal` App will do) and type in `fix_warp_icon`.

Warp should be killed (if open) and its icons should be replaced for the next time you start the app.
You'd have to do this on every Warp update.

**Comment by kevinjohncutler** [comment]
I am glad I am not the only one who just went into the rabbit hole of changing macOS app icons over this change...

@dannyneira I do appreciate the work that goes into designing a new icon, so no hate on a totally subjective thing like this. In fact, it would be great if users had the choice of choosing more icons from the Warp team or elsewhere. Do you think it is feasible to do build icons into appearance/theme settings? Arc browser has a good example of this.

**Comment by dhanushkac** [comment]
> Warp has a new logo and site today! https://www.warp.dev
> 
> ![image](https://private-user-images.githubusercontent.com/16809145/377627670-36789e30-0e8a-4578-9b03-f5ae78a40a4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjM3MTQsIm5iZiI6MTcyOTU2MzQxNCwicGF0aCI6Ii8xNjgwOTE0NS8zNzc2Mjc2NzAtMzY3ODllMzAtMGU4YS00NTc4LTliMDMtZjVhZTc4YTQwYTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAyMTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZTdhZTk1MTM5NDhjYTBmNjVmZGFhZjMzM2I2NThjMTI5ODQ4YmRiMjQxOWE2NzM3NWVlMmMyNWMxNmI4ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cFh8WTPQu-d15x5wD-GCHEP_mmn0JrP4DuIQ-SsjtpA)

This logo is hard to see and identify when it is in the dock. At least there should be an option to change the icon.

**Comment by TheFern2** [comment]
Jeez new icon is awful, just why, I loved the old one, and now I have to look at this ugly one every day. I also found this thread trying to figure out how to change it. I get used to seeing my icons on the dock, these type of changes should always have an option to keep old icons imo.

**Comment by TheFern2** [comment]
> @dannyneira Thank you so much for sharing the old icons. Funny how much hate the new icon is getting. Personally I found the left and right edges jarring enough to go down the rabbit hole of figuring out how to change it. It clashed too much with the rest of my app icons, which are much more flat visually.

People including me don't like ui changes out of the blue, we get used to seeing it how it was.

**Comment by neongrau** [comment]
The problem is you can't even get used to this new icon. It's completely off and doesn't fit into either a light or a dark theme on macOS. Was it designed to fit into some Linux Desktop?

**Comment by TheFern2** [comment]
> The problem is you can't even get used to this new icon. It's completely off and doesn't fit into either a light or a dark theme on macOS. Was it designed to fit into some Linux Desktop?

It sure does stick out like a sore thumb, compare to the rest of the icons, that's one of the reasons I wanted the old one but then again, I don't switch I stay in dark theme. For some odd reason I keep losing time with this tool that's supposed to make me productive. Every update I have to figure out how to revert it if possible in the settings. or some hacky way. Every update is pushing me more and more to go back to iTerm2. This company doesn't realize some of us spend 90% of our day in the terminal the last thing we want is daily changes to our every day tool, is highly counter productive.

**Comment by edencakir** [comment]
I agree that having an option to change the icon would be useful. The current one is sleek, but I have trouble distinguishing it from the Cursor editor. I'll also open an issue on their repo, so that hopefully both tools will eventually offer a customization option similar to the Arc browser as others have mentioned.

**Comment by 0nn0** [comment]
The new icon is harder to quickly distinguish from the apps I commonly use, particularly Linear and Cursor. 

![CleanShot 2024-11-16 at 13 50 44@2x](https://github.com/user-attachments/assets/37230209-7ffd-4ba8-aafa-07a3468dfb49)

**Comment by yigitkonur** [comment]
Could not agree more, WARP vs Cursor vs Linear is real nightmare on CMD + TAB.

**Comment by dhanushkac** [comment]
@neongrau No it updates for me. The only thing is new icon replaces the manually added icon.

**Comment by cookie-drummer** [comment]
New, blue-accented icon looks so ugly. :(

**Comment by edencakir** [comment]
Personally, I think the new blue icon works well when distinguishing Warp from Cursor and Linear. Thanks for the update!

**Comment by cedvdb** [comment]
> very subjective thing, design

Seems pretty unanimous to me :P

**Comment by TheFern2** [comment]
>  > very subjective thing, design
> 
> 
> 
> Seems pretty unanimous to me :P 

Very subjective == we don't care || want to agree we made the wrong decision

**Comment by ianterrell** [comment]
Thanks @Ameer-Jamal for the workaround here: https://github.com/warpdotdev/Warp/issues/2703#issuecomment-2257265523

I don't know why a terminal app doesn't have an icon that looks like a terminal! Cmd-Tab was so confusing. I just took iTerm's.

**Comment by gcjbr** [comment]
Woah, I thought it was just me, but it seems like the new icon confusion IS a thing!

I also mix it up with Steam a lot

**Comment by TheFern2** [comment]
> Woah, I thought it was just me, but it seems like the new icon confusion IS a thing!
> 
> I also mix it up with Steam a lot

Is like all designers lost all creativity. Icons should be unique.

**Comment by dannyneira** [comment]
Hey folks, were tracking this request here https://github.com/warpdotdev/Warp/issues/5408

**Comment by gavan1** [comment]
@dannyneira thank you and your team for one of the best pieces of software in the past decade. 
Adding features that allow this level of customization will retain a whole lot of users.

I am on MacOS I did notice that when dragging an icon In the "getinfo" pane Warp reverts back to it' s own icon. 
Are there any ways to use our own icons? (png, icons)?

**Comment by felipetesc** [comment]
Any chance to post an svg icon ?

**Comment by felipetesc** [comment]
> ### Discord username (optional)
> 
> Chaos#3003
> ### Describe the solution you'd like?
> 
> ```
> Another solution I came up with, is an option to change the Warp Icon. 
> For example instead of the standard, it has a white background - and I even designed one for it.
> 
> I have added either a png or the zip file with the .icns file in it down below. 
> Would be a nice feature to add! :)
> ```
> 
> ### Is your feature request related to a problem? Please describe.
> 
> ```
> And yes, I do know it's possible to change it on MacOS, but the problem is after each update, it resets to the one with a black background, and I don't like that.
> ```
> 
> ### Additional context
> 
> ![Warp](https://user-images.githubusercontent.com/85056161/221151383-dee5374b-03d9-4548-a0fd-35dfc7ea0f5b.png) [Warp.icns.zip](https://github.com/warpdotdev/Warp/files/10822991/Warp.icns.zip)
> ### How important is this feature to you?
> 
> 3
> ### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087
> 
> None

Any chance to post an svg icon ?

**Comment by likegravity** [comment]
https://www.figma.com/community/file/1528900179382651330

use&config it as you want

**Comment by wwwonka** [comment]
Thank y'all for finding a way to customize the icon.
Though it's annoying to have to replace the icon every time Warp gets 
updated... 

is there a way to make the custom icon persist?

**Comment by owencmcgrath** [comment]
@wwwonka 

you might want to check out something like https://pictogramapp.com

**Comment by wwwonka** [comment]
> you might want to check out something like [pictogramapp.com](https://pictogramapp.com)

Unless I'm mistaken, Pictogram only works when Warp is not running. Warp uses its own internal "customizable" icon (set via its settings), separate from the one Finder/Pictogram would modify.

I currently have a script that automates patching `aurora.png` each time Warp updates, but updates are frequent and it gets old fast.

Is there a way to persist a custom icon across Warp updates without manual intervention? A hidden setting, a hook, or another approach?

(See image below for context on the file being patched.)

<img width="2972" height="1922" alt="Image" src="https://github.com/user-attachments/assets/b9a04490-f783-4450-a43c-73594099d800" />
