### ISSUE TITLE
ZSH prompt is not the same as it is in iTerm with no changes to .zshrc

### ISSUE THREAD

**Issue by WTPascoe** [warpdotdev/Warp#2706]
### Describe the bug

The zsh prompt does not appear to be set the same in in Warp as in iTerm with the same .zshrc. Specifically, kubernetes context is not shown.

In iTerm, I see the following prompt
`(☸|kubecontextname) ~/do/mydev/dir   main ±`

In warp, my prompt is 
`~/do/mydev/dir git:(main)±1`

### To Reproduce

Launch iTerm, see first prompt.

Launch Warp, see second prompt.

### Expected behaviour

I expect to see the current Kubernetes context in my prompt as well as the other context displayed.

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.02.21.08.03.stable_01

### Additional context

My .zshrc is 
```
export PATH=/opt/homebrew/bin:${PATH}
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"
pluxins=(
    git
    kube-ps1
)

source $ZSH/oh-my-zsh.sh
source "/opt/homebrew/opt/kube-ps1/share/kube-ps1.sh"

export EDITOR=vim
source <(kubectl completion zsh)
alias k=kubectl
compdef __start_kubectl k
alias ktx="kubectx"
alias kns="kubens"

alias scp='noglob scp'
setopt no_auto_remove_slash

PS1='$(kube_ps1)'$PS1
KUBE_PS1_NS_ENABLE=false
KUBE_PS1_SYMBOL_USE_IMG=true
USE_GKE_GCLOUD_AUTH_PLUGIN=True
autoload -U compinit; compinit

export CLOUDSDK_PYTHON_SITEPACKAGES=1
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

source /Users/me/.docker/init-zsh.sh || true # Added by Docker Desktop
USE_GKE_GCLOUD_AUTH_PLUGIN=True
export DEFAULT_USER=$USER

source ~/.aliases

if [ -f '/Users/testzsh/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/testzsh/google-cloud-sdk/path.zsh.inc'; fi
if [ -f '/Users/testzsh/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/testzsh/google-cloud-sdk/completion.zsh.inc'; fi
```

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by WTPascoe** [comment]
Ah - found it - need to enable 'Honor user's custom prompt (PS1)' in settings.

**Comment by taichi221228** [comment]
I am facing a similar problem.

A complement created using `compdef` does not work only with Warp.
Only in Warp, pressing Tab displays a list of files under a directory.

> 'Honor user's custom prompt (PS1)'

I don't see this setting in the current Warp, how can this be resolved?

**Comment by taichi221228** [comment]
Thank you, @dannyneira.
I was able to find the settings successfully!

But the problem was not solved... I am not very familiar with shells, so maybe the PS1 Prompt settings had nothing to do with the problem I wanted to solve in the first place and the question itself was wrong.

**Comment by dannyneira** [comment]
@taichi221228 this is an issue for the prompt, your `compdef` issue may be related to zsh completions not being supported in Warp as this time, which we are tracking here #434
