### ISSUE TITLE
Doesn't connect via SSH (Starting shell...)

### ISSUE THREAD

**Issue by DEV-JWebers** [warpdotdev/Warp#2710]
### Describe the bug

When I try to SSH to any server it stays in starting shell and never connects.

Tests Carried Out:
1.The Mac terminal connects in less than 1sec to any of the servers via ssh
2. Reinstall Wrap with the latest version, previously uninstalling the one you had installed.

This has been happening to me for about 1 week, I think I remember after an update. I always keep the program updated.

### To Reproduce

ssh name host

### Expected behaviour

Connect to SSH terminal

### Screenshots

<img width="360" alt="CleanShot 2023-02-24 at 23 30 25@2x" src="https://user-images.githubusercontent.com/74836878/221306512-ce28071b-d6a9-48e7-95af-5125696c15e5.png">

### Operating System

MacOS

### OS Version

macOS Monterey 12.6.2

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Warp Version

v0.2023.02.21.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @
We're tracking this in this here #2682

Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.

Closing as duplicate.
