### ISSUE TITLE
Hot key shortcut is only availale for English language.

### ISSUE THREAD

**Issue by wangmir** [warpdotdev/Warp#2712]
### Describe the bug

When I trying to launch shell with hot key, it is only available when I'm in the English mode. When I change the language format, hot key is not available.

Becuase, in case of the shortcut, it should be work for both Korean and English, so I think it seems bug.

### To Reproduce

1. English mode
2. Launch warp 
3. Go to vscode
4. click hot key (in my case, cmd + shift + t)
5. will show hotkey window
6. Change language into Korean (maybe other language too)
7. When I hit the hotkey shortcut, it is not showing.

### Operating System

None

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @wangmir I think this may be related to the lack of #341 IME ( international keyboard ) support. It's something we're working on and can be tracked in that issue.

We'll close this one as a duplicate.
