### ISSUE TITLE
Resizing window displays PS1

### ISSUE THREAD

**Issue by nachocab** [warpdotdev/Warp#2713]
### Describe the bug

I just installed Warp and noticed that when I resize the warp screen, my PS1 gets inserted in the input area:

![CleanShot 2023-02-25 at 11 01 18](https://user-images.githubusercontent.com/27538/221351101-2bd5a9a8-dd54-461c-bff9-3aa6d1aa4775.gif)

### To Reproduce

It happened out of the box. I'm using zsh 

### Expected behaviour

Nothing appearing in the input box until I type something

### Screenshots

![CleanShot 2023-02-25 at 11 01 18](https://user-images.githubusercontent.com/27538/221351126-feffec8c-48df-484f-a6a2-6f4e8985d9f7.gif)

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.9

### Warp Version

v0.2023.02.21.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @nachocab Thanks for submitting, May you please provide a sample of your PS1 in the rc file?

We'd like to be able to reproduce this issue. In the meantime I recommend, you try one of our supported [Prompts](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table).

**Comment by nachocab** [comment]
I set my PS1 via a function in a zprezto module:

```
prompt_my_ps1 () {
    setopt localoptions noxtrace noksharrays

    local -ah ps1
    local -h host hist1 hist2 dir space date time rs="%b%f%k"
    local -h eon="%(?.[.%20(?.[%U.%S[))" eoff="%(?.].%20(?.%u].]%s))"

    # Set up the components of the upper line
    host="%{$fg[%m]%}%m$rs"
    hist1="%9(v. . %{$fg[%h]%}$eon%7v$eoff$rs )"
    hist2=$'%9(v.\n'"%{$fg[%h]%}$eon%7v$eoff$rs.)"
    dir="%{$fg[%~]%}%8~$rs"
    space=%8v
    date="%{$fg[date]%}%D$rs"	# Prefer "%{$fg[%D]%}%W$rs" in the USA?
    time="%{$fg[time]%}%*$rs" #  see http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html for format

    # Assemble the new prompt
    ps1=( ${(f)PS1} )		    # Split the existing prompt at newlines
    ps1=(
        "%$[COLUMNS-PSCOL]>..>"	# Begin truncation (upper left prompt)
    	"$host"
        " "                     # space
        "$dir"                  # current dir
        '${vcs_info_msg_0_}'    # git info
    	"%<<"			        # End truncation (end upper left prompt)
    	"$space"		        # Pad line to upper right position
    	"%$[COLUMNS-PSCOL-15](l. . $date)"
    	"%$[COLUMNS-PSCOL-7](l.. $time)"
    	$'\n'                   # end in newline
	)
    PS1="${(j::)ps1}"
}
```

**Comment by dannyneira** [comment]
Hi Folks! We've fixed this issue in a recent release. Please update Warp and try it out!

https://github.com/warpdotdev/Warp/assets/16809145/66796b54-39c1-42bf-aa1e-7344fd5ae49f

Closing as resolved, but please feel free to let us know and reopen if the issue persists.
