### ISSUE TITLE
filename does not update when changes made using finder

### ISSUE THREAD

**Issue by saujanya01** [warpdotdev/Warp#2714]
### Describe the bug

Folder path does not update correctly when changes made using GUI(finder)

### Steps to reproduce the bug
1. go inside any folder using warp - let's take `~/warp/error` for example
2. now open this same location in finder
3. create a new folder inside `~/warp`, lets say that is `~/warp/problems`
4. move the `~/warp/error` inside `~/warp/problems~` using the finder
5. now open warp and do `cd ..`
6. the path shown in warp will be `~/warp` instead of `~/warp/problems`.
7. and that's the bug

### Expected behaviour

Point 6 of `To Reproduce`

### Operating System

MacOS

### OS Version

13.2.1 (22D68)

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting @saujanya01 I think we had a similar issue open for something like this, but I'm noticing the behavior is the same for other terminals ( iTerm, Terminal.app, see demo ). 

https://user-images.githubusercontent.com/16809145/221673093-4c7ef8b6-892f-46dc-bd69-31dee5f527b7.mp4

That being said, it's certainly an opportunity to improve and add more intelligence to Warp! As a workaround, you can open a new Warp tab/pane/window and it should update the correct/current folder structure.

**Comment by saujanya01** [comment]
@dannyneira Thanks, should i close this issue?

**Comment by dannyneira** [comment]
Thanks, yes we'll close this one but certainly looking to make improvements in this in the future with more intelligent completion suggestions ( within the limits of the OS )
