### ISSUE TITLE
Warn before closing a tab that is running a task.

### ISSUE THREAD

**Issue by RoyRao2333** [warpdotdev/Warp#2717]
### Describe the solution you'd like?

```text
If I'm running a task and I'm quitting Wrap, it'll give you a warning, which is great. 

But if I have several tabs that running tasks, and I'm closing one of them, nothing happens and that tab is simply closed.

Can this be improved? Much thanks!
```

### Additional context

See [@mhz5's comment](https://github.com/warpdotdev/Warp/issues/197#issuecomment-1412620802)

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @RoyRao2333 , Good to see you're still enjoying Warp!

**Comment by JamieMcMillan** [comment]
Having the same warning as the quit process when running something would be very helpful!

**Comment by patrykk21** [comment]
I'm switching to vim and the amount of times I press "cmd+w" to close an open file because I'm used to vs code is too damn high... Would be helpful to have a warning box appearing

**Comment by 7k50** [comment]
Any updates on this? Frustrating to accidentally close processes that have been running a long time, just because I wanted to view another tab…

**Comment by EvHaus** [comment]
I accidentally close a tab at least once a week. Reopening a closed tab seems useless right now because it won't let me interact with that tab.

Can you please consider re-opening this ticket?

**Comment by mmulvahill** [comment]
Adding a comment that could just be a +1 because I've now accidentally closed open work in Neovim several times since starting w/ Warp last week. My previous teminal emulators asked for confirmation before closing -- might need to switch back to prevent lost work, but am really liking warp otherwise.  (ligatures too, but that's a different issue)

**Comment by dannyneira** [comment]
hey folks, for tabs that have a running process (like alt-screen or servers, etc), we have the Quit Warning feature here. 

For tabs with no running process, we have Tab Restoration. https://docs.warp.dev/features/windows/tabs#tab-restoration

Hope this helps!

**Comment by 7k50** [comment]
> For tabs that have a running process (like alt-screen or servers, etc), we have the Quit Warning feature here.
> 
> For tabs with no running process, we have Tab Restoration. https://docs.warp.dev/features/windows/tabs#tab-restoration
> 
> Hope this helps!

Correct me if I'm wrong, but doesn't the Quit Warning feature only warn when attempting to quit the app itself – not when closing a tab running a process?

I ask, because I believe had the Quit Warning feature enabled the whole time, while still accidentally closing tabs running processes with CMD + W on MacOS, with no warning.

**Comment by EvHaus** [comment]
> For tabs that have a running process (like alt-screen or servers, etc), we have the Quit Warning feature here.

This doesn't work for me. Here's the problem:

https://github.com/warpdotdev/Warp/assets/226640/f5f4f46b-3c73-4e12-bdef-052c8f9f0356

**Comment by patrykk21** [comment]
Well this feature doesn't work for me either. True I can do `cmd-shift-t` but what then? 
I don't get all my windows and buffers I opened in nvim back and I don't want to use a different multiplexer like tmux in combination of warp.

This is the single feature reason that just made me quit Warp.
I'm switching to a simpler terminal emulator which has implemented the very simple yet effective dialogue box for confirmation.

**Comment by bnavetta** [comment]
Reopening this - we're tracking it as a separate issue from tab restoration and the quit warning

**Comment by bnavetta** [comment]
Hey! As of the `v0.2024.10.08.08.02.stable_01` release, Warp will show a warning before closing a tab if the [Quit Warning](https://docs.warp.dev/features/quit-warning) setting is enabled:

https://github.com/user-attachments/assets/6f93b02b-92dc-4ab3-836a-7deafcf631ef

This also works when closing a tab from the [Command Palette](https://docs.warp.dev/features/command-palette) (`Close the Current Tab`, `Close Other Tabs`, etc.), or a custom keybinding.

Warp doesn't yet show a quit warning when closing a single pane (e.g. with `cmd-w`) - we're tracking that in #1887. Please upvote there if you'd like to see the quit warning supported for panes.

**Comment by EvHaus** [comment]
Confirmed. Thank you! This helps a lot.

**Comment by usmanajmal** [comment]
My version is v0.2024.10.15.08.02.stable_03 but I don't see the warning, even though the setting toggle: "Show warning before quitting" is ON.

**Comment by dannyneira** [comment]
@usmanajmal this Warning will only trigger if there is running process in the Tab, can you please run `sleep 100` and try closing that TAB which it's running on to see if the Warning works?

If not, please let us know and provide your logs. https://docs.warp.dev/help/sending-us-feedback#gathering-warp-logs

**Comment by usmanajmal** [comment]
You are right. That works. Perhaps we need to make the 'Show warning before quitting' setting more descriptive, to show that it will work only where there is a running process. Moreover, there should be a similar setting for allowing user to have that warning even for tabs, which have no process running. Too often do we (or at least I) mistakenly click the x button while clicking a tab or resizing a window or repositioning the tabs.

**Comment by ADTC** [comment]
Interesting observations:

* Pressing Shift-Cmd-T to restore a closed tab (with no running process) restores the history of the tab, and it looks like it was never closed in the first place.
  * This is good. ✅
* If I have only one pane and I close tab (confirming the warning) with a running process, pressing Shift-Cmd-T to restore it, it's a dead tab, with the message "Shell Process Exited".
  * This seems bad. ❌
  * Perhaps the existing content of the tab can be pushed to "tab history" and a new session started below the "Shell Process Exited" message.
* If I have two or more panes, and I close tab (confirming the warning) with a running process, pressing Shift-Cmd-T to restore it, the pane that had the running process is removed, and only the other panes are kept.
  * This seems bad. ❌
  * I think all panes should be kept, and the one with "Shell Process Exited" should have a new session launched.
  * BUG 🪲: If I split a restored pane, it opens four new panes instead of just one.

**Comment by destroy314** [comment]
Hi, I've noticed that the tab restore feature causes closed tabs to leave file descriptors open for a period of time, which prevents the file system from being unmounted. Is there any way to resolve this?

**Comment by dannyneira** [comment]
@destroy314 Go to `Settings > Features > Session > Enable reopening of closed sessions' and either disable it or lower the time it's allowed to keep sessions open in the background.

**Comment by contributor** [comment]
> For tabs that have a running process (like alt-screen or servers, etc), we have the Quit Warning feature here.
> 
> For tabs with no running process, we have Tab Restoration. https://docs.warp.dev/features/windows/tabs#tab-restoration

But this is useless if you run claude/gemini/qwen cli. If you accidentally click x on a tab title, you won't get any warnings and will lose context/work. 

Please reopen the issue. The simple option to confirm tab closing is a MUST

**Comment by contributor** [comment]
@dannyneira the video for all three:

https://github.com/user-attachments/assets/bfc7cd8e-a645-44e9-b76b-16ba1c2f98d4

Version: v0.2025.08.20.08.11.stable_03
Windows 11

**Comment by dannyneira** [comment]
oh i see, looks like youre using gitback or wsl in Windows, please confirm which one and run `echo $shell`

**Comment by contributor** [comment]
@dannyneira thanks for the suggestion, CTRL-SHIFT-W does show the warning. Now I only need a way to remove X from tabs :)

The problem with X is that is very likely to click on it when switching to a tab when there are lots of them and they got very narrow. So hiding X would help with that. Other solution is could be vertical tabs - they would have the same width independently of how many are there, and they would not occupy scarce screen height.

**Comment by dannyneira** [comment]
No problem, track the issue and subscribe to be notified of a fix. I have already submitted the reproduction and details to the team.

**Comment by kennyeliason** [comment]
Using `Command + #` to switch between tabs, super convenient... Not convenient is how close `Q` and `W` are to the 1 and 2 buttons which causes an occasional accidental Quit or Close... "Show warning" feature is turned on and it never confirms. 

<img width="1020" height="470" alt="Image" src="https://github.com/user-attachments/assets/87c55cfa-eb23-451c-9db7-48f9abaa855f" />

Anywho. My .02.

**Comment by zachlloyd** [comment]
@kennyeliason you're saying there's a bug where it's not actually showing the warning even when the setting is enabled? do you have a screencast by chance? Also, if there's a bug here, let's open as a new issue

**Comment by kennyeliason** [comment]
@zachlloyd whelp... I had to google it but this is a classic Vorführeffekt, or Demonstration Effect. Of course working perfectly now that I finally reached out about it. 

<img width="329" height="371" alt="Image" src="https://github.com/user-attachments/assets/24edde72-2acf-4f3d-a2c5-226b6ed5f3b5" />

Nevermind my previous comment...
