### ISSUE TITLE
show time to run on each block

### ISSUE THREAD

**Issue by mvolkmann** [warpdotdev/Warp#2720]
### Discord username (optional)

mvolkmann#6822

### Describe the solution you'd like?

```text
I saw a YouTube video about Warp where each block displayed how long it took for its command to run. But I don't see that in my blocks. Is there an option to turn that on? Perhaps that was a feature that was removed.
```

### Is your feature request related to a problem? Please describe.

```text
I'd like to have an option to see the time required to execute the command in each block.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @mvolkmann It's part of the default Prompt, just Disable the custom prompt in the `Settings > Features`

![CleanShot 2023-02-28 at 10 19 36](https://user-images.githubusercontent.com/16809145/221929548-e6b0677b-5fc9-4b55-bbbb-20414c388575.png)

Please see more on this here: https://docs.warp.dev/features/prompt

Closing as resolved but please let us know if you need any additional assistance.

**Comment by mvolkmann** [comment]
@dannyneira Thanks so much for explaining that!
