### ISSUE TITLE
Referral code failed to load.

### ISSUE THREAD

**Issue by iankhou** [warpdotdev/Warp#2723]
### Discord username (optional)

ikh#0105

### Describe the bug

After clicking on "Invite a Friend to Warp," I see "Failed to load referral code." where the referral code should be. I've updated Warp several times since first having the issue and it persists. I have tried closing and reopening, including for e resets and complete restarts.

### To Reproduce

After clicking on the dropdown from the top right, click on "Invite a Friend to Warp"

### Expected behaviour

There should be a referral code displayed.

### Screenshots

<img width="454" alt="Screenshot 2023-02-27 at 11 38 47 PM" src="https://user-images.githubusercontent.com/45278651/221755320-49dc7386-db2d-4bd2-adb2-c21c358eb879.png">

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.02.21.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by Ecleptor** [comment]
> Hi @iankhou Sorry to hear about this issue, are you on any proxy or VPN by any chance? Did the referral link ever work for you?
> Can you try the following and let us know the result?
> `ping www.googleapis.com`
> 

This could be related to #2690

**Comment by Ecleptor** [comment]
This could be the same problem as #2680

**Comment by iankhou** [comment]
> This could be the same problem as #2680

The conditions are slightly different, that issue is for 10+ referrals. I have not had any referrals.

**Comment by iankhou** [comment]
@dannyneira pinging that server gives expected behavior. I'm not on VPN or proxy. The referral link never worked for me.

**Comment by dannyneira** [comment]
@iankhou Thanks for confirming, just curious if you can also [Share a block](https://docs.warp.dev/features/blocks/block-sharing) or if are you getting an error there as well?

![CleanShot 2023-03-03 at 13 30 42](https://user-images.githubusercontent.com/16809145/222823014-d1ea3e96-0361-4021-bae7-487c1a81eb30.png)

If the sharing also fails then please try logging out of the user/profile with `sudo security delete-generic-password -l "dev.warp.Warp-Stable" $HOME/Library/Keychains/login.keychain` then login to see if that fixes the issue.

**Comment by iankhou** [comment]
I couldn't share a block. Logging out and back in worked though, now the referral link shows as expected. Thanks!

**Comment by dannyneira** [comment]
Great that worked for you thanks for letting us know. I'll post some info in the docs around this issue and the workaround/resolution.
