### ISSUE TITLE
Scroll alternate screen

### ISSUE THREAD

**Issue by jonyen** [warpdotdev/Warp#2725]
### Describe the solution you'd like?

```text
In the default Mac OS terminal, you can scroll the alternate screen by holding down Fn or Shift, which makes it easy to scroll out of Vim and into the terminal output. It would be nice to implement this in Warp as well.
```

### Additional context

![Screenshot 2023-02-28 at 10 27 41 AM](https://user-images.githubusercontent.com/674440/221899884-3b57ec64-f347-49fd-9fa8-7c90652f5090.png)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @jonyen, I think the Mouse and Scroll Reporting feature in Warp should help with this use case. Enable mouse and scroll reporting in the `Settings > Features`

https://docs.warp.dev/features/full-screen-apps#mouse-and-scroll-reporting

![CleanShot 2023-02-28 at 11 15 15](https://user-images.githubusercontent.com/16809145/221943528-310a9247-8409-4256-beb4-71fe5eefd3af.png)

**Comment by jonyen** [comment]
Hi @dannyneira , thank you for the quick response. I have tried this, but that does not seem to work. Please see the attached screen recording (sorry the quality is low b/c the max file size is 10MB). 

https://user-images.githubusercontent.com/674440/221960232-9a9dfc5f-ad41-4594-b557-931896023df6.mov
