### ISSUE TITLE
chinese word break

### ISSUE THREAD

**Issue by geekerzhou** [warpdotdev/Warp#2726]
### Describe the bug

see screenshots . "productName"  chinese word break

### To Reproduce

log break on chinese word

### Screenshots

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/5682822/222049209-a2ac1c07-8df0-4684-a8a5-d66df78b46d3.png">

### Operating System

None

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by geekerzhou** [comment]
it's on line but warp treat is as two line

**Comment by dannyneira** [comment]
Hi @geekerzhou Thanks for letting us know. 

Just curious about this, is the line wrapping or actually split into two lines?
May you please provide an example of the text so we can test on our end and reproduce the issue?

**Comment by geekerzhou** [comment]
> Hi @geekerzhou Thanks for letting us know.
> 
> Just curious about this, is the line wrapping or actually split into two lines? May you please provide an example of the text so we can test on our end and reproduce the issue?

It's weird, same log cann't reproduce this issue today.
