### ISSUE TITLE
Allow mouse clicks to select tabs when window is not active

### ISSUE THREAD

**Issue by lordpengwin** [warpdotdev/Warp#2729]
### Describe the solution you'd like?

```text
Please support something like iTerm's "Always accept first mouse event on terminal windows". I've noticed that if Warp does not have focus, clicking on a tab gives the focus to Warp but does not (usually) activate the tab. This can lead to the confusion where you end up typing into the wrong tab. In iTerm, when the window is not active and you click on a tab, that tab is automatically selected.
```

### Is your feature request related to a problem? Please describe.

```text
It is frustrating when you think you have switched tabs and have not.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @lordpengwin. This behavior can be a bit annoying, so thanks for submitting. 

Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.
