### ISSUE TITLE
Allow the partial selecting of autosuggestions

### ISSUE THREAD

**Issue by jjw00d** [warpdotdev/Warp#2732]
### Describe the solution you'd like?

```text
The Auto suggestion feature based on previous commands is excellent. Instead of having to fully accept a suggestion it would be good if I could partially accept
```

### Is your feature request related to a problem? Please describe.

I'm frustrated when I have to go back and edit the autosuggestion because it is almost but not -quite right

e.g.
I start typing

```
git c
```

The auto-suggestion gives me
```
git checkout -b branch-name-of-something-I-did-yesterday
```

I can either ignore it, and type out the full command, or I can accept it and edit the suggestion after accepting it

I would rather be able to accept each part of a command in turn (using space as the separator?), e.g. using a shortcut - maybe shift + right arrow.

Then I could press the shortcut twice to get

```
git checkout -b
```

and then start typing the branch name etc - and the autosuggestion would kick in again?

This is especially useful for longer commands, I feel like this would be a really good accelerator
```


### Additional context

_No response_

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! 

Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by alokedesai** [comment]
Hey @jjw00d thanks for the feedback! You can use `option + ->` to select the next word in an autosuggestion. Does that fix the issue you are seeing?

**Comment by jjw00d** [comment]
it does! 😍 thank you - I clearly need to read the docs properly
