### ISSUE TITLE
AI Command Search is not working

### ISSUE THREAD

**Issue by alexk1919** [warpdotdev/Warp#2740]
### Describe the bug

With this release and 1 back, the AI command search has not been working. I am on a Mac M1 Mini.

### To Reproduce

# command query

### Screenshots

![Screenshot 2023-03-03 at 10 34 02 AM](https://user-images.githubusercontent.com/54913409/222800132-34a0ec01-d620-48dd-a264-332618627f41.png)

### Operating System

MacOS

### OS Version

Ventura 13.2.1

### Warp Version

v0.2023.02.28.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @alexk1919 Sorry to hear about this, can you try `ping www.googleapis.com`? Are you using any proxy or VPN that may be blocking the domain?

**Comment by alexk1919** [comment]
Hi, I can ping. No proxies or vpn enabled.

**Comment by bishshoy** [comment]
I've got the same problem here. Same OS, same Warp version.
No proxies, or VPNs. Can ping google.com successfully.

**Comment by Nusnus** [comment]
Same here..

M1 Max: `Monterey Version 12.6.3`
Warp: `v0.2023.02.28.08.03.stable_01`
No VPN, no proxies.

![CleanShot 2023-03-08 at 14 44 58@2x](https://user-images.githubusercontent.com/4662342/223716891-26ccac92-e826-4712-b162-2cf99bc79b57.png)

**Comment by dannyneira** [comment]
Hey Folks, there is a known issue where the auth token is invalidated after making changes to the the account you've logged into Warp with ( change password on your gmail/github account ). 

Please remove Warp user login with `sudo security delete-generic-password -l "dev.warp.Warp-Stable" $HOME/Library/Keychains/login.keychain` then login back into Warp with your usual account and let us know if the issue persists.

**Comment by Nusnus** [comment]
> Hey Folks, there is a known issue where the auth token is invalidated after making changes to the the account you've logged into Warp with ( i.e. change the password on your gmail/github account ).
> 
> Please remove Warp user login with `sudo security delete-generic-password -l "dev.warp.Warp-Stable" $HOME/Library/Keychains/login.keychain` then login back into Warp with your usual account and let us know if the issue persists.

Works!
Thanks!! @dannyneira
I've been without it for some time, using chatgpt instead, now can use Warp AI.
Awesome 🚀 

**Before Fix:**
> Same here..
> 
> M1 Max: `Monterey Version 12.6.3` Warp: `v0.2023.02.28.08.03.stable_01` No VPN, no proxies.
> 
> ![CleanShot 2023-03-08 at 14 44 58@2x](https://user-images.githubusercontent.com/4662342/223716891-26ccac92-e826-4712-b162-2cf99bc79b57.png)

**After Fix:**
<img width="736" alt="CleanShot 2023-03-10 at 22 36 34@2x" src="https://user-images.githubusercontent.com/4662342/224423469-b2135c22-099b-40f0-a73a-7f44e416a4f5.png">

**Comment by dannyneira** [comment]
Thanks for confirming @Nusnus. I'm glad you're back up and running with Warp! I've noted this in our known issue section of the docs. https://docs.warp.dev/help/known-issues#online-features-ai-command-block-sharing-referrals-etc.

Also, we're looking into adding a better experience around this or a notification to let users know the token has gone stale and how to fix it.

@alexk1919 Please try the above steps to resolve this and let us know if it is fixed for you by closing this GitHub bug report.

**Comment by alexk1919** [comment]
This has fixed the problem... thanks!
