### ISSUE TITLE
Brightness issues on low DPI monitor

### ISSUE THREAD

**Issue by velocibear** [warpdotdev/Warp#2741]
### Describe the bug

Hi there, this is a weird one. I have a widescreen 1440p monitor and no mater what theme I select the colors for the text look really washed out and hard to read. I don't have this issue with iterm2. Is there anyway to increase the brightness or contrast of the colors maybe?

### To Reproduce

Not really a bug.

### Operating System

None

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @velocibear, appreciate you submitting. we have an [Enforce minimum contrast](https://docs.warp.dev/appearance/text-fonts-cursor#text-and-fonts) in the `Settings > Appearance` which may help with the issue. 

![CleanShot 2023-03-03 at 13 43 59](https://user-images.githubusercontent.com/16809145/222825654-1974d2eb-c977-484f-a17d-0670eb56c99d.png)

Also, if you could, please provide a screenshot of an example it would be very helpful to us in troubleshooting the issue.
