### ISSUE TITLE
Arrow at front of my commands (from zsh spaceship) causes errors

### ISSUE THREAD

**Issue by adityachoudhari26** [warpdotdev/Warp#2746]
### Describe the bug

```
core/services/gorilla on  achoudhari/automatic-upgrades-banners [⇡$] via ⬢ v16.19.0 via 🐹 v1.20.1 on 🐳 v20.10.23 runs 🐙 GGGGG using ☁️  default/wandb-qa took 5.8s
➜
```

This is what my terminal prompt looks like in ITerm2. This is because I have a zsh spaceship config. However, this causes errors in warp: 

```
➜ source ~/.zshrc
zsh: permission denied: /Users/adityachoudhari
zsh: command not found: ➜
```

### To Reproduce

i'm not going to write out the full steps, just get spaceship and configure it to have the arrow/prompt show up on your terminal, and then itll start saying that it doesn't recognize the command.

### Expected behaviour

it recognizes that its just a terminal prompt and that its not actually part of the command

### Operating System

MacOS

### OS Version

12.2.1 

### Shell Version

zsh 5.8 (x86_64-apple-darwin21.0)

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
thanks for letting us know @adityachoudhari26 , There is a known issue with spaceship prompt causing type ahead into the input editor, try the following workaround and let us know if that helps. https://docs.warp.dev/features/prompt#spaceship

`echo "SPACESHIP_PROMPT_ASYNC=FALSE" >>! ~/.zshrc`
