### ISSUE TITLE
Right-sided prompt - ZSH - Not respecting RPROMPT in .zshrc

### ISSUE THREAD

**Issue by reimund** [warpdotdev/Warp#2751]
### Describe the bug

Right prompt is not shown. I was expected to see the current working directory.

This is how it looks like in iTerm2:
<img width="910" alt="Screenshot 2023-03-09 at 09 57 02" src="https://user-images.githubusercontent.com/83687/223971467-d2079495-1b23-485d-922c-1e01a84ff134.png">

Instead I get this:
<img width="315" alt="Screenshot 2023-03-09 at 10 02 12" src="https://user-images.githubusercontent.com/83687/223972866-33bafad3-e705-45de-af70-f4074d417df4.png">

This is the part of my .zshrc that touches RPROMPT:
```zsh
set -A prompt_array \
       "%(1j.[%j] .)" \
       "%B%m%b" \
       "%(1v.%1v%f.)" \
       "%(!@.%{$fg[red]%}%n%{$reset_color%}@)" \
       "%(?.%{$fg[green]%}%#.%{$fg[red]%}%#)%{$reset_color%} "

set -A rprompt_array \
       "%U%$MAXWIDTH<...<%~%u" \
       " %{$fg_bold[black]%}%T%{$fg[black]%}%{$reset_color%}"

PROMPT=""
for i in $prompt_array
do
       PROMPT=${PROMPT}${i}
done

RPROMPT=""
for i in $rprompt_array
do
       RPROMPT=${RPROMPT}${i}
done
```

### To Reproduce

Use this zsh config

```zsh
((MAXWIDTH=$COLUMNS/3))

# Do stuff for git stuff.
autoload -Uz vcs_info

# set formats
# %b - branchname
# %u - unstagedstr (see below)
# %c - stangedstr (see below)
# %a - action (e.g. rebase-i)
# %R - repository path
# %S - path in the repository
FMT_BRANCH="${PR_GREEN}%b%u%c${PR_RESET}" # e.g. master¹²
FMT_ACTION="(${PR_CYAN}%a${PR_RESET}%)"   # e.g. (rebase-i)
FMT_PATH="%R${PR_YELLOW}/%S"              # e.g. ~/repo/subdir

# Check-for-changes can be really slow.
# You should disable it, if you work with large repositories
zstyle ':vcs_info:*:prompt:*' enable git
zstyle ':vcs_info:*:prompt:*' check-for-changes true
zstyle ':vcs_info:*:prompt:*' unstagedstr '¹'  # Display ¹ if there are unstaged changes
zstyle ':vcs_info:*:prompt:*' stagedstr '²'    # Display ² if there are staged changes
zstyle ':vcs_info:*:prompt:*' actionformats " ${FMT_BRANCH}${FMT_ACTION}" " ~${FMT_PATH}"
zstyle ':vcs_info:*:prompt:*' formats       " ${FMT_BRANCH}"              " ~${FMT_PATH}"
zstyle ':vcs_info:*:prompt:*' nvcsformats   ""                             "%~"

precmd()
{
	psvar=()
	vcs_info 'prompt'

	[[ -n $vcs_info_msg_0_ ]] && psvar[1]="$vcs_info_msg_0_"

	# Remove leading whitespace.
	trimmed_branch="${vcs_info_msg_0_## }"

	if [ -z "$trimmed_branch" ]; then
		branch=''
	else
		branch="(${trimmed_branch})"
	fi

	# Set the iTerm tab title to current directory.
	echo -ne "\e]1;${PWD##*/} ${branch}\a" 2> /dev/null;
}

set -A prompt_array \
       "%(1j.[%j] .)" \
       "%B%m%b" \
       "%(1v.%1v%f.)" \
       "%(!@.%{$fg[red]%}%n%{$reset_color%}@)" \
       "%(?.%{$fg[green]%}%#.%{$fg[red]%}%#)%{$reset_color%} "

set -A rprompt_array \
       "%U%$MAXWIDTH<...<%~%u" \
       " %{$fg_bold[black]%}%T%{$fg[black]%}%{$reset_color%}"

PROMPT=""
for i in $prompt_array
do
       PROMPT=${PROMPT}${i}
done

RPROMPT=""
for i in $rprompt_array
do
       RPROMPT=${RPROMPT}${i}
done

#-/ Nice titles /----------
case $TERM in ((x|a|E)term|*rxvt*)
   # Show path in titlebar
   #precmd () { print -Pn "\e]0;%n@%m: %~\a" }
   # Show command in titlebar
   #preexec () { print -Pn "\e]0;%n@%m: $1\a" }
   ;;
esac
```

### Expected behaviour

<img width="910" alt="Screenshot 2023-03-09 at 09 57 02" src="https://user-images.githubusercontent.com/83687/223974084-14dd83af-e1cd-492a-a94f-ca303feab3b6.png">

### Screenshots

<img width="315" alt="Screenshot 2023-03-09 at 10 02 12" src="https://user-images.githubusercontent.com/83687/223974316-7d5d8325-ed9c-4ef6-af87-138a23ba5692.png">

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.02.28.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @reimund Sorry about this but RPROMPT isn't currently supported in zsh PS1 prompt. afaik the only prompt that Warp supports and has a working Right-sided prompt is oh-my-posh. 

Please see more on this here: https://docs.warp.dev/features/prompt

Closing as this is a known incompatible prompt.

**Comment by elviskahoro** [comment]
@reimund there are improvements to right prompt support coming out soon hopefully over this month!
