### ISSUE TITLE
No editors available under "Choose an editor to open file links"

### ISSUE THREAD

**Issue by renbou** [warpdotdev/Warp#2752]
### Describe the bug

I have Visual Studio Code Insiders Edition installed using brew (https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/visual-studio-code-insiders.rb). The app iteself is located under "/Applications/Visual Studio Code - Insiders.app/", so nothing unusual. Warp, however, is unable to detect it, which is why I'm not able to select it as the editor to use.

### To Reproduce

1. Install Visual Studio Code Insiders Edition (maybe the bug manifests itself only with the brew version?)
2. Warp -> Settings -> Features -> General -> Choose an editor to open file links. It will not contain "VSCode Insiders" or something similar.

### Expected behaviour

Have VScode Insiders listed as a possible choice. Since there doesn't seem to be any documentation as to what editors are shown there, it's impossible to debug the issue.

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2023.02.28.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @renbou Thanks for letting us know!

A fix is being worked on and should be out in an up-and-coming release. We appreciate your patience and will post any updates on this thread.

**Comment by dannyneira** [comment]
This is launched as of Warp version `v0.2023.03.21.08.02.stable_01`

**Comment by dannyneira** [comment]
Hey Folks! This fix was released in Warp version: `v0.2023.03.21.08.02.stable_01`

Preview of the option:

![CleanShot 2023-03-22 at 08 45 46](https://user-images.githubusercontent.com/16809145/226941489-a9ce4a39-8738-4508-b4ae-d1ee1324029d.png)
