### ISSUE TITLE
Scroll too fast in vim

### ISSUE THREAD

**Issue by Saafo** [warpdotdev/Warp#2754]
### Discord username (optional)

Saafo#9108

### Describe the bug

I use mouse to scroll in vim using `set mouse=a` in .vimrc file, however when I scroll using my trackpad, it's too fast comparing with iTerm2 or Terminal. Neovim has the same problem

### To Reproduce

1.  `set mouse=a` in .vimrc file
2. open a file using vim
3. compare with iTerm or Terminal with the same scroll speed

### Expected behaviour

scroll the same as iTerm or Terminal

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.03.07.08.02.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @Saafo Are you also seeing the same when scrolling with a mouse? Can you try adjusting the tracking speed in the Mac settings to see if that helps as well? 

![CleanShot 2023-03-10 at 14 43 58](https://user-images.githubusercontent.com/16809145/224434263-87de8b87-5bd1-4f0e-8416-b06930ffea1c.png)

We'll post any updates on this thread.
Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by Saafo** [comment]
@dannyneira sorry I don't have a mouse. I tried the trackpad setting, but even I adjust the tracking speed to the slowest gear, It doesn't make **any** help to the issue(same fast as before).
I put the screen recording of Warp, iTerm and Terminal, with the same scroll speed(Warp maybe with a little slower trackpad scroll speed, but it has the fastest scroll speed among three.)
![Warp](https://user-images.githubusercontent.com/46736350/224493784-30091eac-e80f-4765-93fb-c2f2993f2136.gif)
![iTerm2](https://user-images.githubusercontent.com/46736350/224493773-5db07d82-8376-4344-8196-cc5cbf69c6bb.gif)
![Terminal](https://user-images.githubusercontent.com/46736350/224493788-ea8647ae-1d16-4270-a116-c239ec8e927c.gif)

Another scrolling bug you might notice in the screen recording is that when I scroll to top of the file in Warp, it will automatically scrolling back to line 4 from line 1.

**Comment by dannyneira** [comment]
Thanks for the details, I'll bring it up with the team and we'll follow up with more updates when we have them.

**Comment by Saafo** [comment]
> For me, it helped disabling scroll reporting in the Warp settings (but keeping mouse reporting enabled).
Not sure whether this is a sustainable fix though.

It's a better solution in most cases, however, there's a bad case in `lazygit`:

1. Make many changes in one file
2. open `lazygit`, focus on `Files` tab, and scroll in `(Un)staged Changes` area

* If we turn `toggle scroll reporting` on, the `(Un)staged Changes` area will scroll very very fast.
* If we turn off, the `(Un)staged Changes` cannot scroll at all! Instead, it scrolls in the `Files` tab.

Found the issue from https://github.com/jesseduffield/lazygit/issues/2117#issuecomment-1538073993.

**Comment by vorporeal** [comment]
This should be fixed in this week's release (on Thursday)!

**Comment by Saafo** [comment]
> This should be fixed in this week's release (on Thursday)!

Can confirm fixed in `v0.2023.05.09.08.03.stable_01`! Now I can use Warp smoothly with `Toggle Scroll Reporting` open!
