### ISSUE TITLE
Copy On Select doesn't work while running any program that runs in a TUI (vim, less, git log, screen)

### ISSUE THREAD

**Issue by scooberu** [warpdotdev/Warp#2758]
### Describe the bug

Generally speaking, the Copy On Select feature works fine for me in most areas of Warp. However, when I use vim (`VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 16 2022 23:27:53)`) or any other program that runs a whole TUI (`less`, `screen`, `gdb`'s tui, the default terminal paging for `git log`), I find that Copy On Select doesn't work at all on my local machine (selecting works fine, but whatever I select is not added to the paste buffer; it is only possible to copy with Cmd+C).

### To Reproduce

1. Open a program that runs in a TUI
2. Highlight a line of text
3. Use cmd+v to paste; it will not paste the highlighted text.

### Expected behaviour

I expect that when Copy On Select is enabled, selecting text in Warp will result in that text being added to the paste buffer, even in vim (and other applications with paging).

### Screenshots

https://github.com/warpdotdev/Warp/assets/4369667/8dc2fb5e-4020-4a9c-b39f-07df0dffcc2e

### Operating System

MacOS

### OS Version

13.2.1 (and all other current macOS versions through 14.4)

### Shell Version

zsh 5.8.1 (via oh-my-zsh) (also seen in zsh 5.9)

### Warp Version

v0.2023.03.07.08.02.stable_01 (still seen in every version up to and including v0.2024.02.20.08.01.stable_02)

### Additional context

I'm not blocked from using Warp daily because of this, but it's pretty annoying unexpected behavior (not least because generally one doesn't want text from the paste buffer to end up getting pasted in an unintended context! consequences could range from innocuous to embarrassing all the way to full-blown incorrect input / security issue).

### Does this block you from using Warp daily?

No, but I'm getting pretty tired of it.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
@gatsbysghost We appreciate you letting us know about this issue with vim. I was able to reproduce the issue, will bring it up with the team and we'll post any updates on this thread.

Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by mkrisher** [comment]
Thanks @dannyneira and @gatsbysghost, I posted the same issue in the Discord channel, using NVIM (inside tmux) over here

**Comment by mf-lit** [comment]
I'm finding this is in `vim` too but also in other applications that take over the terminal. `less` and `k9s` being other examples.

Is this ncurses related maybe?

**Comment by mattiaspantzare** [comment]
I can't paste att all from vi when I ssh to a linux computer. Not even when I use the menu.
It works if I use vi on the local mac.

**Comment by mylabzhen** [comment]
I have the same problem with vim8.2.
When I ssh a linux computer with the warp command, open one file with vim, select some code with the mouse.
Can't paste it anywhere else.
iterm2 does not have this problem

**Comment by djmango** [comment]
Same problem with NeoVim, MacOS Sonata. Confirmed no problem on iTerm2

**Comment by cathykc** [comment]
Are there any plans to fix? Pretty inconvenient for my workflow and considering switching off Warp.

**Comment by mkrisher** [comment]
thanks for the update @dannyneira, simple example, open a tmux session, run `ls`, try to copy the one of the lines. I haven't figured out a work around, other than no tmux session. I've experimented with vim binding and copy on select to no avail.

**Comment by rrojas-prmnt** [comment]
This issue is also affecting commands that use `less` screens. ([less](https://en.wikipedia.org/wiki/Less_(Unix)#:~:text=less%20is%20a%20terminal%20pager,backward%20navigation%20through%20the%20file.))

git branch
git log
etc...

Any text that is displayed in `less` screen, is not getting copied with "copy on select" feature.

**Comment by mikelange-revium** [comment]
I dont know if this is really VIM related, I found copying text to be an issue with zoom-out. Selecting text for copy, whilst it looks "correct" doesn't actually select the text you're seeing highlighted - it selects a different line of text due to the zoom, very odd behaviour.

The only workaround for this is using the terminal at 1:1 zoom (dont zoom out/in).

**Comment by terris-peer** [comment]
To make Vim copy text to the system clipboard when pressing `Ctrl` + `C`, you can add the following lines to your `~/.vimrc` file:

```bash
" Enable copying to system clipboard with Ctrl + C
vnoremap <C-c> "+y
```

This mapping will allow you to copy text in visual mode to the system clipboard by pressing `Ctrl` + `C`.

**Comment by scooberu** [comment]
> To make Vim copy text to the system clipboard when pressing `Ctrl` + `C`, you can add the following lines to your `~/.vimrc` file:
> 
> 
> 
> ```bash
> 
> " Enable copying to system clipboard with Ctrl + C
> 
> vnoremap <C-c> "+y
> 
> ```
> 
> 
> 
> This mapping will allow you to copy text in visual mode to the system clipboard by pressing `Ctrl` + `C`.

This issue specifically concerns copy-on-select (automatic copying when text is highlighted), not copying with Ctrl-C.

**Comment by mylabzhen** [comment]
Hi all, any update about this issue? I encountered the same problem.

**Comment by terris-peer** [comment]
> This issue specifically concerns copy-on-select (automatic copying when text is highlighted), not copying with Ctrl-C.

Thanks for the clarification. Copying text out of vim when using warp used to work fine but it broke recently. I keep Warp up to date; vim not so much. However, it's difficult to tell what broke it.

**Comment by ZsBT** [comment]
I can't reproduce this. Vim itself captures mouse events by default. You might want to try
`set mouse=`
in vim, to release mouse and allow selecting text.
I guess it is not a Warp bug.

**Comment by jmoseley** [comment]
I don't use vi*, but this affects me using other commands that use `less` (git log, git diff, etc)

**Comment by scooberu** [comment]
> I can't reproduce this. Vim itself captures mouse events by default. You might want to try `set mouse=` in vim, to release mouse and allow selecting text. I guess it is not a Warp bug.

Here's a repro. (You can see me highlight-selecting text in Warp and then hitting Cmd+V into an empty text editor on the left, only for nothing to be pasted there). You'll notice that when I `set mouse=r`, that still does not fix the issue for me. My vimrc does not have any settings for `mouse`, either, so that's certainly not it, and it works fine in iTerm2 on the same machine, so it's not a vi* problem. Definitely a Warp problem.

https://github.com/warpdotdev/Warp/assets/4369667/759a3a86-dff5-4451-ad48-9a8132f28057

**Comment by scooberu** [comment]
> I don't use vi*, but this affects me using other commands that use `less` (git log, git diff, etc)

Yeah, it's a problem with anything that runs a TUI I think. That discrepancy has been bugging me for a while (since [it was initially noticed](https://github.com/warpdotdev/Warp/issues/2758#issuecomment-1491557978)); I have renamed the issue accordingly.

**Comment by Saafo** [comment]
Seems fixed in v0.2024.03.12.08.02

**Comment by dannyneira** [comment]
Hey folks, this issue has been fixed in the latest version of Warp! [v0.2024.03.12.08.02](https://docs.warp.dev/getting-started/changelog#id-2024.03.14-v0.2024.03.12.08.02), along with a list of improvements. 

Closing as resolved, but please let us know if anything persists.

**Comment by obsidian33** [comment]
This issue seems to have resurfaced with the latest version v0.2024.07.09.08.01.stable_00

**Comment by augustin4s** [comment]
Yeah, seems copy on select does not work anymore after update

**Comment by dannyneira** [comment]
Thanks for letting us know folks, I was able to reproduce this issue again. I'll bring this up with the team and we'll post further updates on this thread.

**Comment by dannyneira** [comment]
Hi Folks, you should be able to `SHIFT-CLICK-SELECT` test to copy while in alt-screens. This was as part of a change to shift-click alt-screen functionality, we'll post any updates on this thread if we make changes to this in the future.

**Comment by scooberu** [comment]
_Huh?_

If I understand the new alt-screen behavior correctly, my options are:

1. Turn mouse and scroll reporting off (meaning I can't scroll in vim)
2. Turn mouse and scroll reporting on (meaning I need to intentionally disable this functionality any time I want to copy-on-select)

If I've got that wrong, then disregard the following.

Sorry to be a malcontent, but @dannyneira -- could you help me understand the design considerations that led to this functionality being broken out into a knob, and then allowing for that knob to be temporarily defeated with the shift key, such that part of vim is always behaving unexpectedly no matter what I do? Does this help to resolve some other issue somewhere?

From the perspective of a vim user with copy-on-select muscle memory who doesn't bother with much of the AI stuff, it feels very much like a regression of this issue has been introduced on purpose (though, in this case, I guess it's at least good to know that it was intentional--and to have a workaround :) ). Again, sorry to be a cranky ingrate user and put you on the spot, but I would really appreciate it if you could help me understand the reasoning here.

**Comment by acarl005** [comment]
Hi @scooberu thanks for the detailed explanation. Sorry for the frustration. I'm the one who implemented the change (as well as a Neovim user myself) and I want to make sure I've understood these details correctly. There are several pieces here, so forgive me if I'm a little pedantic or overly verbose here, as this comment is intended for a wide audience of Warp users.

In order for the copy-on-select feature to trigger in an _alt-screen program_ which _utilizes mouse reporting (SGR mouse)_, you must do either of the following:

1. Disable mouse reporting in Warp (and therefore scroll reporting), or...
2. When mouse reporting is _enabled_, hold shift and perform the selection.

What does this mean for some of the programs you might use?

1. `less` does not use SGR mouse. Copy-on-select happens regardless of whether mouse reporting in Warp is enabled. Shift+click is not necessary.
2. `vim` and `neovim` may operate with or without SGR mouse. Vim has it off by default while neovim has it on by default.
    a. If SGR mouse in (neo)vim is disabled, e.g. `:set mouse=`, copy-on-select happens just as it does in `less`.
    b. If SGR mouse in (neo)vim is enabled, e.g. `:set mouse=a`, selection is not handled in Warp, and so copy-on-select does not trigger. Use shift+click to escape-hatch this.

If any of the behaviors are not working as I've described above, there may actually be a bug.

What exactly do I mean by "selection is not handled in Warp"? Mouse reporting means that mouse events are reported to the hosted program, e.g. vim, and that program decides what those mouse events mean. In (neo)vim, mouse events may perform an equivalent of "selection", i.e. visual mode. It certainly looks similar to a Warp-handled text selection, but it's not. Importantly, there exist programs that _do_ use SGR mouse such that mouse events do _not_ do any form of text selection, e.g. [fx](https://github.com/antonmedv/fx) and [midnight commander](https://midnight-commander.org/). This means that when Warp is doing mouse reporting, it can't know how the hosted program will handle those mouse events, it may not be doing any kind of "selection". Therefore, pressing shift+click is a temporary escape hatch from mouse reporting. It just makes Warp handle the mouse events, does a selection and triggers copy-on-select.

This behavior with shift+click is quite common among many terminals, e.g. Alacritty, GNOME terminal, and Konsole. That's not to say it's how Warp _must_ do it, but that's the reasoning behind the current design.

***However,***

Obviously, there are many users here who are surprised by the current functionality. If you believe there's a bug (Warp isn't behaving as I've specified), please do say so. But, I'll need to know about the SGR mouse settings of the hosted program. (Neo)Vim is tricky b/c it's so highly configurable. You can read the current setting with `:set mouse` and it should print the value of the setting in the bottom, e.g. `mouse=` means disabled. Please specify Vim or NeoVim. Finally, if it's practical to do so, provide the vim RC.

**Comment by scooberu** [comment]
Hi @acarl005 -- thanks so much for explaining; that actually makes perfect sense to me and I really appreciate that you took the time to explain the reasoning. I had a little fun messing with my vimrc just now and everything works as expected for me.

Sorry for making a ruckus, and thanks again :)

**Comment by acarl005** [comment]
No need to be sorry! You've been nothing but helpful! Thanks again for engaging.
