### ISSUE TITLE
The color of the command output result is obviously dull

### ISSUE THREAD

**Issue by xzbdmw** [warpdotdev/Warp#2759]
### Describe the bug

The color of the command output result is obviously dull

### To Reproduce

It is default

### Screenshots

<img width="583" alt="image" src="https://user-images.githubusercontent.com/97848247/224463492-5e136afd-fffb-4dc0-b992-2bc926caa326.png">
see the cargo'green is much lighter than the output ,so as the white color

### Operating System

MacOS

### OS Version

13.2

### Shell Version

zsh 5.8.1

### Warp Version

v0.2023.03.07.08.02.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for bringing this up @xzbdmw 
We'll post any updates on this thread.

Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.
