### ISSUE TITLE
DUP: Duplicate of #026 - Support ITerm2 Style Images Protocol/Tools

### ISSUE THREAD

**Issue by DavidMChan** [warpdotdev/warp#276]
### Describe the solution you'd like?

iTerm2 is able to display images (and animated gifs) within the terminal, see: https://iterm2.com/documentation-images.html.

It would be cool if this was supported within warp as well.

**Comment by elviskahoro** [comment]
Linking this https://github.com/warpdotdev/warp/issues/180
MIME Types Rendering #180

**Comment by elviskahoro** [comment]
Linking:
- #26
