### ISSUE TITLE
Option-delete deletes the full suggestion, not just word-by-word

### ISSUE THREAD

**Issue by arvid220u** [warpdotdev/Warp#2765]
### Describe the bug

When I accept a suggestion with tab, I often want to change just the last few words. Normally, in iTerm for example, I'd just use option-delete, which deletes word-by-word. In Warp, option-delete deletes the entire suggestion, which is unexpected.

### To Reproduce

1. Write something.
2. Accept the multi-word suggestion with ctrl-F.
3. Press option+backspace.
4. Watch how the entire suggestion, not just the last word, gets deleted

### Expected behaviour

Only the last word gets deleted.

### Operating System

MacOS

### OS Version

?

### Shell Version

fish, version 3.5.0

### Warp Version

?

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @arvid220u, I appreciate you submitting this, but I can't see to reproduce the issue, is there any autocompletion you have enabled in FISH by any chance? Can you also check your keyboard shortcuts and make sure OPT-DEL isn't bound to any other shortcuts? https://docs.warp.dev/features/keyboard-shortcuts

This is what I see when I do the steps, using FISH.

https://user-images.githubusercontent.com/16809145/224748740-07e84b0f-a6d3-4279-bf4e-0a5b3a72c5ed.mp4

**Comment by elviskahoro** [comment]
I can't repro this either!

**Comment by arvid220u** [comment]
yeah it doesn't seem to happen to me anymore either! not sure what it was (maybe some weird thing on my end) but i'm glad it's fixed :) thanks!

**Comment by PelagicDev** [comment]
This happens to me as well, but only when in the `irb` or `rails` console. I'm also using Fish shell, but it doesn't do this in iTerm. See video below...

https://github.com/warpdotdev/Warp/assets/2034140/0919774f-d68f-4679-bcdd-c7dc298b0109

**Comment by bellef** [comment]
Same here, only in rails console or IRB, must be a really specific issue...

**Comment by domelqq** [comment]
Have the same issue with aider.chat application now
