### ISSUE TITLE
stronger workflow

### ISSUE THREAD

**Issue by Saafo** [warpdotdev/Warp#2767]
### Discord username (optional)

Saafo#9108

### Describe the solution you'd like?

```text
1. make warp workflow stronger like [fig scripts](https://fig.io/scripts), making params support not only text, but also switcher, file picker, selector and so on just like fig scripts.
2. run workflow directly from command line, like add command alias so we don't need to invoke workflow panel.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by Dmitrijs-Doit** [comment]
Looking for a way to execute warp workflows via CLI commands, i think it's an excellent feature.

**Comment by dannyneira** [comment]
Hey Folks and @Saafo , we recently launched [Enums in Warp Drive Workflows](https://docs.warp.dev/features/warp-drive/workflows#enum-type-arguments) which allows for a list of default options. Please let us know if this partially helps with your use case.

**Comment by Saafo** [comment]
Hi @dannyneira it helps (as switcher and selector)! And expecting more types, like file picker and so on.
