### ISSUE TITLE
Let users enable/disable completion

### ISSUE THREAD

**Issue by jonatan-ivanov** [warpdotdev/Warp#2768]
### Describe the solution you'd like?

```text
Create a similar switch to `Open completions menu as you type` but for enabling/disabling built-in completions/suggestions.

There are users would like to use the built-in suggestions of their shell, or things like `zsh-autosuggestions`, fig etc.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @
We have a issue tracking this here: https://github.com/warpdotdev/Warp/issues/1811

Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.
Closing as duplicate.
