### ISSUE TITLE
Syntax error when connecting to a WPEngine.com server

### ISSUE THREAD

**Issue by paulgibbs** [warpdotdev/Warp#2769]
### Describe the bug

Trying to connect to a web server from WPEngine.com is failing in Warp. In other terminal software, the connection works fine, using the same SSH config etc.

### To Reproduce

Sign up for a server at wpengine.com, and connect to the server via SSH.

Connection fails immediately with output:

```
Warning: Permanently added 'mywpengineserver.ssh.wpengine.net' (RSA) to the list of known hosts.
bash: -c: line 0: syntax error near unexpected token `then'
bash: -c: line 0: `export TERM_PROGRAM=WarpTerminal _user=$(command -v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER) _hostname=$(command -v hostname >/dev/null 2>&1 && command hostname 2>/dev/null || uname -n) hook=$(printf {"hook": "SSH", "value": {"socket_path": "~/.ssh/167872186624052", "user": "%s", "host": "%s", "remote_shell": "%s"}} $_user $_hostname ${SHELL##*/} | command od -An -v -tx1 | command tr -d  \n) printf %
```

### Expected behaviour

Succesful connection

### Operating System

MacOS

### OS Version

13.2

### Shell Version

zsh 5.8.1

### Warp Version

v0.2023.03.07.08.02.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @wuhhh Sorry to hear about this issue.
We're tracking this issue here #2764

Please :+1: and comment there if you also see the issue, as it helps us gauge impact of the bug.

Closing as duplicate.

**Comment by mblais** [comment]
I just encountered this problem when using ssh to remotely execute a bash script on a wpengine site.

From testing the issue, it appears that wpengine is changing _all whitespace characters_ in the ssh command string into **spaces**.

**As a result wpengine bash is interpreting multi-line bash scripts as a single line**, resulting in bash syntax errors.
