### ISSUE TITLE
Autocomplete stops working after typing diacritics

### ISSUE THREAD

**Issue by ruza-net** [warpdotdev/Warp#277]
### Describe the bug

```shell
I can use tab for path autocomplete.

However, when the inserted path contains a (letter with) diacritical mark (eg. ˇ or š), or I type it myself, path autocomplete stops working for the whole session.

Autocomplete still works for commands.
```

### To Reproduce

Steps to reproduce:
1. `cd path` where `path` contains a diacritical mark
2. use tab for path autocomplete
3. it does nothing

### Expected behaviour

```shell
Tab still invokes autocomplete.
```

### Operating System

MacOS

### OS Version

11.3.1

**Comment by elviskahoro** [comment]
This should be fixed already! Please comment if not. Apologies for the delay
