### ISSUE TITLE
Try to run `brew upgrade colima`: it fails

### ISSUE THREAD

**Issue by jeiksegovia** [warpdotdev/Warp#2773]
### Describe the bug

Run `brew upgrade colima`
It tries to download the formula.json, but it's corrupted always.
In the default terminal, it works.

This is the terminal output https://app.warp.dev/block/exSBzhCzExHTF270xmzUUS

### To Reproduce

Mac Ventura 13.2.1 
homebrew 4.0.4 
Run `brew upgrade colima`

### Expected behaviour

It should execute the brew command and run the upgrade as usual. 

### Screenshots

https://app.warp.dev/block/exSBzhCzExHTF270xmzUUS

### Operating System

MacOS

### OS Version

13.2.1 

### Warp Version

v0.2023.03.07.08.02.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by vorporeal** [comment]
Hey @jeiksegovia, can you follow some of the steps in this `brew` GitHub issue and see if they fix your problem?  https://github.com/Homebrew/brew/issues/14516

**Comment by jeiksegovia** [comment]
Yup, it looks like the cache was the issue. But, not sure why using the default terminal there were no issues.
I ran: 
```shell
rm -r "$(brew --cache)/api"
brew upgrade
```

Thanks @vorporeal

**Comment by vorporeal** [comment]
Hm, I also wonder...

@jeiksegovia Any chance `which brew` returns different values in Warp and Terminal.app?
