### ISSUE TITLE
No block level intelligence when logged in to a remote docker container.

### ISSUE THREAD

**Issue by bishshoy** [warpdotdev/Warp#2776]
### Describe the bug

When developing inside of a docker container hosted at a remote server, Warp loses all its functionality as it treats the docker container attach process as a single block. Any workarounds?

### To Reproduce

1. SSH into a remote machine
2. Start a docker container and attach your current terminal session to it.
3. Even if the docker container has zsh installed as the default shell, Warp does not provide any block level intelligence while you are in it.

### Operating System

MacOS

### OS Version

13.1

### Shell Version

5.8

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting, closing as a duplicate since this is due to the lack of subshells support which we're working on. 

Please track the progress on this github issue #64.
