### ISSUE TITLE
Autocomplete separates diacritical marks from their letters

### ISSUE THREAD

**Issue by ruza-net** [warpdotdev/Warp#278]
### Describe the bug

```shell
Suppose I have a folder named "škola".

When I use autocomplete in its parent folder, it inserts "s\̌kola".
```

### To Reproduce

Steps to reproduce:
1. have a folder with a name containing a diacritical mark
2. go to its parent folder
3. `cd` with autocomplete
4. see the folder's name inserted with the diacritical mark on a backslash instead of the original letter

### Expected behaviour

```shell
The combining diacritical marks sits on the original letter, instead of a backslash.
```

### Operating System

MacOS

### OS Version

11.3.1

**Comment by lexpierce** [comment]
I am not sure whether for file a new bug or not as I bet these are related, but let's say you are copying a file to a directory, and that file contains a diacritical mark, the autocomplete of the file name adds the backslash, and then the second element (the directory) duplicates the 1st letter -- even if part way into the autocompete, thus breaking auto-complete, and requiring the user to go back and edit the directory name.
