### ISSUE TITLE
Out of date Changelog in your documentation

### ISSUE THREAD

**Issue by lucianthorr** [warpdotdev/Warp#2782]
### Describe the bug

Not really a bug but just a note, when updating Warp, there's a popup to read documentation about new features but the actual changelog hasn't been updated
https://docs.warp.dev/getting-started/changelog

### To Reproduce

update Warp

### Operating System

MacOS

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for the heads-up @lucianthorr! We'll look into updating it for the latest releases.

**Comment by elviskahoro** [comment]
Updated!
