### ISSUE TITLE
windows 

### ISSUE THREAD

**Issue by kalu5** [warpdotdev/Warp#2784]
### Describe the solution you'd like?

```text
I want to use it on windows .
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @kalu5 Thanks for your interest in a Window version of Warp! There is a request tracking it here: https://github.com/warpdotdev/Warp/issues/204 

Please +1 that request as it helps us gauge interest.

Closing as duplicate
