### ISSUE TITLE
when view search result, new log will scroll the screen, scroll out the search result, item2 will fix position when search

### ISSUE THREAD

**Issue by bilosikia** [warpdotdev/Warp#2786]
### Describe the solution you'd like?

```text
when searching, not scroll the search result
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @bilosikia Thanks for submitting this. We have a duplicate tracking this here: https://github.com/warpdotdev/Warp/issues/1355

Please 👍 and subscribe to that issue for updates on progress.

Closing as duplicate.
