### ISSUE TITLE
Warp for Mac: Updater should handle installation from non-admin account.

### ISSUE THREAD

**Issue by BryanAtVimcal** [warpdotdev/Warp#2787]
### Describe the bug

The updater will not automatically handle updating from a non-admin account. As a safety precaution, I do not work from an admin account. And, with Warp incredible update schedule, I end up with the red update banner every other day. In order to update, I need to stop, click download, close Warp, open the disk image, drag warp, answer the question regarding the drag from the OS, then input my credentials. After, when opening, I need to answer the OS question about apps downloaded from the Internet. Could you improve the updater. This is becoming a bit of a PITA. Thanks.

### To Reproduce

Use Warp in a non-admin account on MacOS and go through an update.

### Expected behaviour

Click update and enter my credentials.

### Operating System

MacOS

### OS Version

13.2.1

### Warp Version

All

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @BryanAtVimcal Please see our docs on how to handle updating as a non-admin user. https://docs.warp.dev/help/updating-warp

There isn't much we can do about this given the permissions of non-admins but there is a flow that attempts to update the app manually. I hope this helps!

Closing as not planned.

**Comment by BryanAtVimcal** [comment]
I have been through the flow. You guys are the ONLY app I use regularly that doesn’t auto update for non-admin users. I am not sure why you are the outlier.

Bryan
