### ISSUE TITLE
什么时候可以出ui的中文版本 / Release Chinese version of Warp UI

### ISSUE THREAD

**Issue by lengwangye** [warpdotdev/Warp#2789]
### Discord username (optional)

lengwangye

### Describe the solution you'd like?

```text
什么时候可以出ui的中文版本

When will the Chinese version of UI be released?
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
感谢您提出此功能请求！ Warp中文UI版时间暂无预估。
请 :+1: 并订阅此请求，因为它有助于我们衡量兴趣。 我们将在此处发布任何更新。

Thanks for this feature request! There is no estimate for the time on the Chinese UI version of Warp.
Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by dannyneira** [comment]
We have an issue tracking this here: #1194

Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.

**Comment by ChannD** [comment]
I need Chinese。

**Comment by who10086** [comment]
> We have an issue tracking this here: [#1194](https://github.com/warpdotdev/Warp/issues/1194)
> 
> Please 👍 and subscribe to that request as it helps us gauge interest. We'll post any updates there.
> 
> Closing as duplicate.

3 years ago

**Comment by kaka77** [comment]
I need Chinese。

**Comment by zpj80231** [comment]
I need Chinese。

**Comment by balnkmint** [comment]
I need Chinese。

**Comment by dannyneira** [comment]
Hi folks, we are tracking support for chinese Warp here. https://github.com/warpdotdev/Warp/issues/1823

**Comment by Spenlu** [comment]
i need Chinese

**Comment by StoryNight** [comment]
i need Chinese
