### ISSUE TITLE
A.I. Command Search / Workflows / Completions / History pop ups stay over / overlaps the Settings view

### ISSUE THREAD

**Issue by renrique92** [warpdotdev/Warp#2792]
### Describe the bug

When you type # to bring up the command search, if you open the settings, the pop up stays on top.

### To Reproduce

- Type # and wait for the pop up prompt
- Open settings

### Expected behaviour

I think the settings should gray out all the screen and stays on top, leaving the rest behind

### Screenshots

<img width="1362" alt="Captura de pantalla 2023-03-19 a las 1 52 34" src="https://user-images.githubusercontent.com/12242257/226147885-1ffefa29-5566-4431-ace1-99e4335209c2.png">

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.03.07.08.02.stable_03

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Changed the description on this issue to match all the affected views/modals.

**Comment by dannyneira** [comment]
Hey Folks, this issue has been resolved and other modals/ popups no longer overlap the settings page.

Closing as resolved, but please feel free to let us know if the issue persists.
