### ISSUE TITLE
Live load theme changes

### ISSUE THREAD

**Issue by assayire** [warpdotdev/Warp#2794]
### Describe the solution you'd like?

```text
Currently theme development is painful 😫. For every change to the theme file, one has to quit and re-open Warp to see the theme changes. It would be helpful if theme file changes are auto-loaded / refreshed without having restart Warp.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request @assayire!
There are certainly some improvements we can make around realtime theme development so we appreciate your input.

Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by assayire** [comment]
Now that warp-themes is gone, can you consider implementing this feature request?
