### ISSUE TITLE
Integration: Neovim - status bar appears higher than expected

### ISSUE THREAD

**Issue by dylanwishner** [warpdotdev/warp#28]
**Describe the bug**
In neovim, the status bar at the bottom (as seen in the screenshot) is not at the bottom of the terminal window.

**To Reproduce**
1. So far, simply running Neovim seems to trigger it nearly every time.

**Expected behavior**
The status bar should be at the very bottom of the window, as seen in the second screenshot (how it looks in kitty).

**Screenshots**
The first screenshot is warp, the second is what is expected.
![warp](https://user-images.githubusercontent.com/36526431/126239098-bfea07bd-b0df-4324-b6d3-1dc4b9762f14.png)
![kitty](https://user-images.githubusercontent.com/36526431/126239114-4854a268-7e84-4615-9d77-07ccc5b9ee16.png)

**Desktop (please complete the following information):**
 - OS Version: MacOS 12.0 Beta 2

**Comment by gagata** [comment]
Hey! Thanks for the report! I've taken a look and can repro on the vanilla `nvim` installation. We'll keep you posted once it's fixed :)

**Comment by manuraj17** [comment]
@gagata Was a fix released? I pulled a recent update and seems like it's fixed.

**Comment by elviskahoro** [comment]
@manuraj17 is this still happening to you?

**Comment by dylanwishner** [comment]
Not sure when it happened, but this appears to be fixed for me. @elviskahoro

**Comment by elviskahoro** [comment]
awesome!
