### ISSUE TITLE
Copying terminal prompt

### ISSUE THREAD

**Issue by B4Dmonkey** [warpdotdev/Warp#2802]
### Describe the solution you'd like?

```text
I would like the ability to highlight my current prompt so that I can copy my current git branch and paste it somehwere else (specifically messages but maybe I want to search github sometimes)
```

### Is your feature request related to a problem? Please describe.

```text
Currently I can't copy my current prompt when trying to select it with a mouse. When I issue a command and create a new block I can copy my old prompt.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @B4Dmonkey , Thanks for submitting, so we don't have the option to copy the prompt via selection, but given how we've implemented the prompt/input editor, you can right-click on the default prompt and copy the entire thing, or just certain parts. Please see more on this here in our [Prompt Docs](https://docs.warp.dev/features/prompt)

![CleanShot 2023-03-21 at 13 04 03](https://user-images.githubusercontent.com/16809145/226714589-d40a80fd-3000-49c6-b926-2407baa0d550.png)

Closing as a feature for this use case already exists.

**Comment by Integralist** [comment]
@dannyneira ah! I didn't actually notice that before! That's good enough for me 🙂 

In fact I can just hit <Enter> and it achieves the same effect 👍🏻
