### ISSUE TITLE
Add visual indicator that panes are hidden after maximizing dimmed pane

### ISSUE THREAD

**Issue by remziz4** [warpdotdev/Warp#2804]
### Describe the bug

When you have multiple panes in a tab open, and use `CMD + Shift + Enter` to have your active pane take up the entire tab, there is no visual indicator which informs you of your current state.

If you came back to that screen later, you would simply think that the pane showing was the only pane.

iTerm2 for example will show an indicator in the corner of the screen indicating you are in this "full pane" mode. This tells the user that if they exit this mode by hitting `CMD + Shift + Enter`, they'll see all of the hidden panes.

### To Reproduce

1. Open one or more additional panes on a tab by hitting `CMD + D`.
2. Allow one of those panes to take up the entire screen-space by hitting `CMD + Shift + ENTER`.

### Operating System

MacOS

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @remziz4, once the pane is maximized you should be able to see this with the triangle indicator on the top left corner. Please see my demo:

https://user-images.githubusercontent.com/16809145/226971328-17102163-25cc-4599-82dc-6e04d5e7e53a.mp4

That being said, this isn't the case with pane dimming enabled thou so we can certainly improve in that scenario. I'll change this to a feature request to add an indicator of a max pane when dimming is enabled and will post updates here if/when we have them.

**Comment by remziz4** [comment]
Thanks Danny! My mistake, I thought that triangle indicator was always present even in a single pane layout, didn't realize it only showed in a multi-pane tab. That indicator can definitely be used to infer the information I was looking for.

Appreciate the quick response

**Comment by dannyneira** [comment]
No problem @remziz4  Will close this as the feature exists, but let me know if any issues with the feature.
