### ISSUE TITLE
Program output not shown after clear screen message was sent to the console

### ISSUE THREAD

**Issue by ageron** [warpdotdev/Warp#2805]
### Describe the bug

Try running:

```bash
python -c 'print("\033[2J"); bomb'
```

In iTerm2 or Terminal, this code clears the screen and displays an exception.

However, in Warp the output is not shown.

### To Reproduce

Just make sure `python` is on your `PATH` and run the command above.

### Expected behaviour

The screen should be cleared and the command output should be:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'bomb' is not defined
```

### Screenshots

<img width="463" alt="image" src="https://user-images.githubusercontent.com/76661/226798082-c8015d3a-58f3-4f7f-9664-714b37989456.png">

### Operating System

MacOS

### OS Version

12.6.3

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2023.03.14.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @ageron we're closing this issue as resolved, but please let us know if you're still having the issue.
