### ISSUE TITLE
Add option to disable AI

### ISSUE THREAD

**Issue by dviske** [warpdotdev/Warp#2808]
### Describe the solution you'd like?

```text
Out of an abundance of caution, I'd like to have the ability to disable the AI options altogether in the settings menu, if possible. :)
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @dviske Thanks for submitting this request. 

We're considering options around this, please note more details on what is sent in our [privacy docs](https://docs.warp.dev/getting-started/privacy). Just to be clear, nothing is sent to an API unless you specifically send it ( hitting Enter on an AI Command Search or Warp AI for example ).

Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by LampPrinter** [comment]
Yeah this is needed. I am trying to run a script and the AI command pops up. I have to press ESC and then ENTER to execute the script.
This would not be an issue if we could directly run .sh or .command files in warp from file explorer.

**Comment by rshkv** [comment]
Compare with iTerm's handling of AI features [(changelog)](https://iterm2.com/downloads/stable/iTerm2-3_5_1.changelog):

> 3.5.1
> 
> This release adds some safety valves to eliminate
> the risk of private information leaving the
> terminal via the AI endpoints. While an API key
> and explicit user action were always needed to use
> AI features, some users asked for an impenetrable
> firewall for safety and regulatory purposes.
> 
> To that end, there are three relevant changes:
> 
> 1. Code that communicates with AI providers such
> as OpenAI has been moved into a plugin that you
> must install separately. Enterprise system admins
> can block bundle id com.googlecode.iterm2.iTermAI
> to prevent it from being installed in the first
> place.
> 
> See here for details:
> https://iterm2.com/ai-plugin.html
> 
> 2. In addition, you must manually enable AI
> features in Settings. Doing so requires admin
> access.
> 
> 3. Enterprise administrators who wish to disable
> iTerm2's AI access may set the user default
> GenerativeAIAllowed to False in their MDM systems.
>

**Comment by danielgary** [comment]
Agreed, a global disable AI feature would be wonderful.

**Comment by danielgary** [comment]
> And legal issues aside, "AI In Everything" is wearing a lot of people out real fast. The release notes seem like nothing but AI hype now. And even my command prompt has become a call to use AI. Seeing "Try typing natural language instead of a command" as a placeholder at my command prompt... it really makes me want to change terminals.

I found this issue by searching for how to disable that prompt...

**Comment by jacob-alford** [comment]
💯 I don't want AI in my terminal

**Comment by msmiel** [comment]
I would like to try Warp, but until that feature can be turned off or there is a version where it is excluded entirely, Warp isn't an option.

**Comment by NadineKhis** [comment]
YES!! WHEN?

**Comment by MilanNXT** [comment]
I am uninstaling Warp this AI is so annoying

**Comment by gamory** [comment]
I was about to install and did a quick search to see if it could be disabled.  It's unfortunate that this option isn't implemented. I don't install AI tools, but I'll check back later and see if that's fixed.

**Comment by bocciab** [comment]
I'm not allowed to use this app. I loved it while I could, before the policy was put in place. I would personally pay for an AI free version to have it back.

**Comment by kevindashton** [comment]
There are so many great potential features in Warp... why kill it by forcing us to also interface with an AI?  If warp had no AI (or at least had AI off by default) it would be my new favorite terminal and I'd be recommending it everywhere.  As is, there's no way I can use this in any professional setting, and I also won't even use it personally until there's at least an option to fully disable all AI features.  Optimally, the AI features should be _OFF by default_, with a setting to _enable_ them.

**Comment by juandiago** [comment]
Glad to see I'm not the only one suffering from AI in everything. I do not want it on my terminal, it's really getting on my nerve when I try to execute a command and instead get a GPT response of what that command does. Maybe the prev impl was fine, keep the AI in it's own independent panel, leave the terminal be a terminal.

**Comment by gamory** [comment]
Seems this has been open for a bit with plenty of support. Can someone at Warp comment if this is something that will be done or if we should look elsewhere?

**Comment by simonkeng** [comment]
Warp looks like a beautiful terminal with a lot of potential. I'd love to see this addressed because I can't use AI terminals (nor do I want to). I had to abandon iTerm2 after so many years of loving it. Now I use Kitty, and its fine, but I'm still shopping around.. 

I also love the comments here and couldn't agree more.. @juandiago _"Glad to see I'm not the only one suffering from AI in everything"_ - yes! 🙌

**Comment by vrutberg** [comment]
I used Warp well before the introduction of AI features, and I think it's a great terminal app. Personally I never use the AI features, so to me they're mostly distracting (and sometimes they get in the way: #2227). I would love to keep using Warp, and I can understand that some people do use the AI features, but to me it would be a great addition to be able to disable the AI features completely. Otherwise I feel like I may have to look for alternatives (i.e. go back to iTerm2).

**Comment by zachbai** [comment]
Hey folks, appreciate all the feedback. We are in fact shipping a global AI opt-out setting that will disable all AI features (and remove all AI-related entrypoints from UI). Keep an eye on this thread for updates -- this will be shipping soon.

**Comment by zachbai** [comment]
Following up, this was released today:

<img width="1136" alt="Screenshot 2024-12-13 at 4 33 50 PM" src="https://github.com/user-attachments/assets/676579b3-d1c5-40a3-be73-b143e5d53574" />

If you notice any issues with the setting, don't hesitate to reach out.
