### ISSUE TITLE
Lag on large screens

### ISSUE THREAD

**Issue by gagata** [warpdotdev/warp#281]
### Describe the bug

```shell
When Warp runs on the large screen (more than 350 cols), there's a consistent lag (unrelated to how long the app's been in use) on keypresses etc.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

**Comment by beet** [comment]
+1

I'm running it maximised on a 4K 27" display with the resolution scaled to look like 2560 x 1440, which correlates to about 358 columns and 84 rows of text, and while most short commands are fast enough, "full screen" apps like VIM experience significant lag in insert mode.

**Comment by elviskahoro** [comment]
Just a clarification, but does Vim lag even when using: `vim -u NONE` ?

**Comment by beet** [comment]
> Just a clarification, but does Vim lag even when using: `vim -u NONE` ?

No, it doesn't lag actually, but in insert mode the arrow keys output uppercase characters instead of moving the cursor. I suppose it's a usable workaround, kinda.

**Comment by elviskahoro** [comment]
We started looking into this. Hopefully we'll be able to share updates sometime this month!

**Comment by elviskahoro** [comment]
@beet this should be fixed! can you reopen and comment if not!

**Comment by beet** [comment]
> @beet this should be fixed! can you reopen and comment if not!

It is, thank you! Much faster now.

With vi, the background goes light grey, is that tweak-able somewhere? I'm using a dark theme with the leafy background.

**Comment by gagata** [comment]
@beet do you have a screenshot, just to confirm i understand what's going on? what's in your config? just the `colorscheme` or do you have stuff like `set termguicolors` etc?

**Comment by beet** [comment]
Regular appearance:

<img width="1392" alt="Screen Shot 2021-12-20 at 12 06 51 pm" src="https://user-images.githubusercontent.com/4745/146698216-aa23a6ac-b70f-443a-bf3b-0b78cc055c5b.png">

With Vim:

<img width="1392" alt="Screen Shot 2021-12-20 at 12 06 58 pm" src="https://user-images.githubusercontent.com/4745/146698235-7378fd1d-051c-42e3-b108-9b801bc302ab.png">

Vim in Terminal for reference:

<img width="1390" alt="Screen Shot 2021-12-20 at 12 09 25 pm" src="https://user-images.githubusercontent.com/4745/146698270-6696c82d-3cb6-4d0a-abe2-ad2043605e4d.png">

Warp settings:

<img width="693" alt="Screen Shot 2021-12-20 at 12 08 11 pm" src="https://user-images.githubusercontent.com/4745/146698292-c1abced6-373a-4a15-b970-2460b9fe06d1.png">

**Comment by elviskahoro** [comment]
@beet 
Set this in your vimrc:
`hi Normal guifg=#bbbbbb guibg=#333333 gui=NONE`

We've been talking about Vi / Vim / NeoVim in this GitHub Discussion:
https://github.com/warpdotdev/warp/discussions/451

An example of Vim with Warp's custom background image.
<img width="1092" alt="Screen Shot 2021-12-19 at 20 13 39" src="https://user-images.githubusercontent.com/29553206/146698491-f839e438-1c74-4e60-ba20-cdf84766eab5.png">

**Comment by beet** [comment]
Ah, I went in to edit `~/.vimrc`, and found that commenting out this line did the trick:

```
colorscheme industry
```

Didn't have to add `hi Normal guifg=#bbbbbb guibg=#333333 gui=NONE`, and it's still nice and fast on a 4K display!

Cheers
