### ISSUE TITLE
Pre-configured layouts

### ISSUE THREAD

**Issue by Greyvend** [warpdotdev/Warp#2815]
### Describe the solution you'd like?

```text
Add pre-configured layouts similar to itermocil: https://github.com/TomAnthony/itermocil.
```

### Is your feature request related to a problem? Please describe.

I need to run multiple services (FE, BE, job queue) locally. Having them run in a single window helps to see their output at a glance.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @Greyvend We have an existing feature called Launch Configuration that should handle this use case. Please see more on this feature and how to use it in our Docs: https://docs.warp.dev/features/sessions/launch-configurations

Closing as there is a feature that exists for this use case.
