### ISSUE TITLE
No response when ssh to a windows 11 pc

### ISSUE THREAD

**Issue by jessie1129** [warpdotdev/Warp#2819]
### Describe the bug

When ssh to windows 11 pc, after input username and password, nothing output.

### To Reproduce

nothing

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1

### Warp Version

v0.2023.03.14.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by osmboy** [comment]
workaround： you can install cygwin on windows then ssh
