### ISSUE TITLE
SSH: Disconnecting from VPN while ssh'd locks up tab

### ISSUE THREAD

**Issue by wrhall** [warpdotdev/Warp#282]
### Describe the bug

```shell
Initial conditions: When I am on VPN & ssh onto a host I can only access through VPN
Trigger: I disconnect from VPN
Result: The terminal tab completely locks up (ideally, it would let me ctrl+c or something, although iterm is similar. iterm does unlock faster, though)
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```shell
Eventual result: https://app.warp.dev/block/flNRXVAPVBczQsOFEuqKIL
Expect it much faster :)
```

### Screenshots

https://capture.dropbox.com/cf11hrIqzaKQV4qj

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
@wrhall 

Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
