### ISSUE TITLE
Show hint for behind and above number commits from remote branch

### ISSUE THREAD

**Issue by MartinSandeCosta** [warpdotdev/Warp#2822]
### Describe the solution you'd like?

```text
I would like to request a feature for Warp that shows the number of commits ahead or behind the remote branch. This feature would be similar to the functionality provided by the "git status" command like: "have diverged, and have X and Y different commits each, respectively". This could be shown in the prompt with two arrows, one indicating the number of commits ahead and another indicating the number of commits behind the remote branch.
```

### Is your feature request related to a problem? Please describe.

```text
Currently, Warp does not provide a way to see how many commits a local branch is ahead or behind its remote counterpart. This makes it difficult for users to keep track of changes and ensure they are up to date with the remote branch. This is an important feature for developers who work on collaborative projects and need to stay synchronized with their team members. Having this feature would greatly improve the user experience and productivity for those using Warp as their primary terminal.
```

### Additional context

![image](https://user-images.githubusercontent.com/32274019/227233963-3df58ad9-2abb-4e36-83ce-21460fd11c20.png)

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @MartinSandeCosta, The git status indicator exists in Warps default prompt. https://docs.warp.dev/features/prompt#git-status-indicator

As an alternative, you can use one of the supported custom prompts to show a similar number. https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table

I hope this helps! Closing as this feature already exists in Warps default prompt.

**Comment by MartinSandeCosta** [comment]
The status indicator I was mentioning (highlighted in red in the image provided above in the issue's body) shows to the number of commits ahead or behind the remote branch. The default prompt shows "changed file count on branch" as per doc https://docs.warp.dev/features/prompt#git-status-indicator.

**Comment by danieladams456** [comment]
Same, in Mac terminal I use git-prompt that is bundled with git and `GIT_PS1_SHOWUPSTREAM=auto` set.  Very basic, but gives me an idea if someone else has pushed on a branch.
