### ISSUE TITLE
Current git branch in terminal should automatically update on change

### ISSUE THREAD

**Issue by ggaabe** [warpdotdev/Warp#2823]
### Describe the solution you'd like?

```text
Sometimes the current git branch is changed from another terminal or code editor. The current branch in warp should update to reflect that.

ie :

`~/ git:(previous-branch-name)`

should update automatically to 

`~/ git:(current-branch-name)`

if the branch change doesn't occur from that warp / the current session.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by ggaabe** [comment]
Thanks @dannyneira ! I know this is a common behavior. I just think it'd be awesome if Warp had this feature.

**Comment by armandsalle** [comment]
It would be nice if the `cmd+k` shortcut does this too

**Comment by dannyneira** [comment]
Thanks for letting us know folks! We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/1657

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/1657
