### ISSUE TITLE
Autocompletion for yarn workspace/package package.json scripts

### ISSUE THREAD

**Issue by jbaccarelli-equinix** [warpdotdev/Warp#2828]
### Describe the solution you'd like?

```text
when working on a yarn project with workspaces, it would be nice to have autocompletion for the corresponding scripts.

So, for example if i have the structure


project-root/
 package.json // commands for start,build,test,etc
 packages/
  ui/
    package.json // commands for star,build,etc with particularities
  server/
    package.json // commands for star,build,etc with particularities

```

I can start typing `yarn` and press tab to see suggestions for the root package.json scripts, but if i type `yarn ui` and press tab, other tools like Fig are able to load the corresponding nested scripts, but Warp is only wrongly suggesting files and folders. 

I would expect the autocomplete menu to show me the nested package.json scripts
```

**Comment by dannyneira** [comment]
Hey @jbaccarelli-equinix, Sorry about the missing completions, please see a list of our supported completions here: https://docs.warp.dev/features/completions#supported-completion-specs

Also, we'll be tracking the missing completions in the following discussion thread https://github.com/warpdotdev/Warp/discussions/652

Please ⬆️ and comment there if you're also seeing something missing, as it helps us gauge the impact and gather a list of what's missing.

Closing as duplicate.
