### ISSUE TITLE
When will warp support Chinese?

### ISSUE THREAD

**Issue by loks666** [warpdotdev/Warp#2829]
### Describe the solution you'd like?

```text
I'm a chinese developer,Chinese is more familiar to me, but I did not find the relevant language Settings on the page. When will warp support the installation of multiple languages or language packs，And when I use AI to ask warp questions, he always understands that Cloudflare Warp VPN, warp and Cloudflare Warp VPN are two things, right? Is there no strong relationship between AI and warp?
```

### Additional context

<img width="402" alt="image" src="https://user-images.githubusercontent.com/33214035/227530526-6f995373-ac4e-4b62-98d7-d537cedbfe3e.png">

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thank you for submitting this @loks666. We have an issue tracking this here: #1194

Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
