### ISSUE TITLE
SSH: Support SSH fallback to bash if default shell is something different

### ISSUE THREAD

**Issue by SyntaxColoring** [warpdotdev/Warp#283]
### Describe the bug

When I try SSHing into a Dropbear-based server, I get an error message and the SSH connection fails.

### To Reproduce

Steps to reproduce:
1. Run a Dropbear server. If it matters, my remote system's Dropbear is v2018.76, and its `/bin/sh` is from BusyBox v1.29.3.
2. Try to SSH in via `ssh user@hostname -i ~/path/to/key`. My `$SHELL` is `/bin/zsh`, if it matters.
3. See the error:
    ```
    sh: syntax error: unexpected "("
    Connection to red-dust.local closed.
    ```

### Expected behaviour

```shell
A successful SSH connection.
```

### Operating System

MacOS

### OS Version

11.5.2

### Additional context

I can successfully SSH into this system if I use the default macOS terminal instead of Warp.

**Comment by elviskahoro** [comment]
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
