### ISSUE TITLE
Full-screen Apps Text Selection Doesn't Track

### ISSUE THREAD

**Issue by praxder** [warpdotdev/Warp#2830]
### Describe the bug

Visually selected text doesn't track when scrolling

### To Reproduce

1. Visually highlight text in a full screen app (ex: `man brew`)
2. Scroll the page
3. Notice the highlighted text selection didn't track with the scroll

### Expected behaviour

The selected text does track when scrolling

### Screenshots

![CleanShot 2023-03-24 at 08 37 57](https://user-images.githubusercontent.com/6300971/227537286-d4c6c3f3-6fed-4cfe-a3a4-4efd48d4ec16.gif)

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.03.21.08.02.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @praxder this has been resolved in Warp, please update and let us know if any issues with scrolling selected text in alt screen.

![CleanShot 2024-07-31 at 13 13 06](https://github.com/user-attachments/assets/cce5ca73-9c4a-4c76-86f7-2a9795b62565)
