### ISSUE TITLE
FreeBSD export: Command not found.

### ISSUE THREAD

**Issue by oceans1908** [warpdotdev/Warp#2831]
### Describe the bug

When I wanna log into a FreeBSD server with the latest version of WARP v0.2023.03.21.08.02.stable_01 I get the following error:

(xxxxx@xxxxxx) Password:
export: Command not found.
printf "\\33[u\\33[0J"; exec "/bin/tcsh"
cmd: Undefined variable.
Connection to xxxxxx closed.

I worked with the previous version.

### To Reproduce

ssh to freebsd machine

### Expected behaviour

a promo after login

### Operating System

None

### OS Version

13.2.1 (22D68)

### Shell Version

GNU bash, version 5.2.15(0)-release (amd64-portbld-freebsd12.3) Copyright (C) 2022 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

### Warp Version

v0.2023.03.21.08.02.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @oceans1908 Sorry about this issue, We're looking into this and will post any updates on this thread.

**Comment by vorporeal** [comment]
Hey @oceans1908, this should be fixed in the latest release.  Please let us know if you're still experiencing issues after updating!
