### ISSUE TITLE
Error highlighting in emacs not working

### ISSUE THREAD

**Issue by tapegram** [warpdotdev/Warp#2832]
### Describe the bug

I'm trying to use emacs (spacemacs, more specifically) in warp. The biggest issue I have is that lsp/flycheck syntax highlighting appears not to render.

In Warp
<img width="850" alt="Screenshot 2023-03-24 at 9 47 34 AM" src="https://user-images.githubusercontent.com/1281274/227558129-69dfec3f-1c7d-443b-8b1f-8c10c6aed61b.png">

iTerm2
<img width="872" alt="Screenshot 2023-03-24 at 9 49 08 AM" src="https://user-images.githubusercontent.com/1281274/227558582-8ae915b8-86d4-458d-90a9-016d4aab2c2f.png">

I know it's a pretty minor difference, but that tiny underscore being rendered is pretty critical to me.

A more obivous example with a big typo

Warp:
<img width="851" alt="Screenshot 2023-03-24 at 9 57 39 AM" src="https://user-images.githubusercontent.com/1281274/227561278-c12ca987-0001-4aab-b4fc-52ca64543a1d.png">

iterm2
<img width="855" alt="Screenshot 2023-03-24 at 9 58 09 AM" src="https://user-images.githubusercontent.com/1281274/227561410-fde1f7f8-d31c-475d-bb28-4f7962abc8de.png">

Also if this is just a configuration issue on my end in warp that would be great!

### To Reproduce

1) Install spacemacs https://www.spacemacs.org/
2) Add some language layer (I'm using kotlin with lsp, but I would assume this applies to any syntax checking)
3) Introduce a syntax error and see that the underlining/error highlighting isn't appearing

Note that some themes appear to change the color of the bad syntax, which is good, but it seems like its the minority of themes -- and they still don't underline which is the main indication I am looking for :(

### Operating System

None

### OS Version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.03.21.08.02.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @tapegram, We appreciate you letting us know, I'll bring this up with the team and if/when we have any updates, we'll post them on this thread.

If anyone else is seeing the same on emacs, please let us know in the comments or with a 👍

**Comment by acarl005** [comment]
Hi @tapegram thank you for reporting. This is also affecting my editor. I'm working on a fix for it. Should be fixed soon.

**Comment by dannyneira** [comment]
Hi all! this has been resolved in the most recent version of Warp. Please update and let us know.

**Comment by dannyneira** [comment]
Closing as resolved!
