### ISSUE TITLE
Setting to Configure Window Size on Open/in Launch Configurations

### ISSUE THREAD

**Issue by kevinmburk** [warpdotdev/Warp#2835]
### Describe the solution you'd like?

```text
A setting to set the initial size of the Warp terminal window when opening a new terminal session.

Additionally, an option in the launch configuration YAML files to set the initial window size.

This could be implemented with either of the following:
- width in pixels X height in pixels
- width by character count X height by number of lines
```

### Is your feature request related to a problem? Please describe.

```text
- I find the default window size of Warp to be too large and have to resize it
  every time I start a new terminal session.

- I find the default window size of my launch configurations (often with three terminal 
  panes stacked vertically) to be too wide and have to resize it every time I open 
  a launch configuration.

- iTerm2 has a default window size setting and it's the only feature I miss 
  having when using Warp.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! 

Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

We have a related issue tracking this here #1399 that would have to get resolved before it can be implemented in launch configs.

**Comment by dannyneira** [comment]
Thanks for submitting @kevinmburk 
We have an issue tracking this here: #1399 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.
Closing as duplicate.
