### ISSUE TITLE
Pane rotation

### ISSUE THREAD

**Issue by bishshoy** [warpdotdev/Warp#2837]
### Describe the solution you'd like?

```text
Let's say I have two vertically split panes. The pane of the right is split horizontally into right upper and right lower pane. I want the ability to rotate the panes, i.e. have the right lower pane goes to the left and occupies the same spot as the left pane did with the dimensions of the left pane, the left pane goes to right upper and the right upper moves down to right lower.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @bishshoy 
We have an issue tracking this here #623 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.
Closing as duplicate.
