### ISSUE TITLE
Changing opacity on window stuck, restart of app fixed it.

### ISSUE THREAD

**Issue by wilshipley** [warpdotdev/Warp#2838]
### Discord username (optional)

Wil Shipley

### Describe the bug

I was playing with the appearance and the opacity slider seemed to stop working. A restart fixed it.

### To Reproduce

I played with the opacity slider and at some point it stopped applying the changes.

### Expected behaviour

Should apply the changes.

### Operating System

MacOS

### OS Version

13

### Shell Version

zsh 5.9 (arm-apple-darwin)

### Warp Version

v0.2023.03.21.08.02.stable_02

### Additional context

None

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @wilshipley I'll bring this up with the team and we'll post updates on this thread.

**Comment by dannyneira** [comment]
Good news! The newest version of Warp, `v0.2023.04.25.08.05.stable_00`, has resolved this issue.

Closing as completed, but if you come across any further problems, please don't hesitate to reach out. Thank you!
