### ISSUE TITLE
Integration with 1password SSH Agent

### ISSUE THREAD

**Issue by djvickery** [warpdotdev/Warp#2840]
### Describe the solution you'd like?

```text
When using an SSH private key to SSH into hosts, use either IdentityAgent or SSH_AUTH_SOCK to find the appropriate SSH key. 

To my (limited) knowledge this will allow Warp to securely access the SSH key from 1password as per:https://developer.1password.com/docs/ssh/agent/compatibility
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @djvickery 
We have an issue tracking this here #1087 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.
Closing as duplicate.
