### ISSUE TITLE
Warp editor in tmux

### ISSUE THREAD

**Issue by wbrijesh** [warpdotdev/Warp#2842]
### Describe the solution you'd like?

```text
I liked the warp editor, but it doesn't work with tmux.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @wbrijesh 
We have a discussion tracking this here https://github.com/warpdotdev/Warp/discussions/501

Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

As a possible stopgap, I suggest you try the Split Panes https://docs.warp.dev/features/windows/split-panes, they fully support Warp features and hopefully help with your use case. 

Closing as duplicate.
