### ISSUE TITLE
Respect Bash EMACS key bindings on command line

### ISSUE THREAD

**Issue by HotFusionMan** [warpdotdev/Warp#2844]
### Describe the solution you'd like?

```text
I would like Ctrl-t on a Bash command line to transpose the two adjacent characters, as happens in Bash under other terminal emulators when Bash is using its EMACS key bindings.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @HotFusionMan this is a known issue and we're tracking it here #2064 
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the issue.

Closing as duplicate.
