### ISSUE TITLE
x86_64 environment on M1/M2 ARM? 

### ISSUE THREAD

**Issue by horsto** [warpdotdev/Warp#2846]
### Describe the solution you'd like?

```text
Is it possible to enable a x86_64 environment ("rosetta2 enabled terminal") in warp on a ARM Mac?
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Not sure if this is possible, we'd have to test it, but Warp does run on Intel Macs so there is a strong chance it may be possible. [Link for context](https://apple.stackexchange.com/questions/428768/on-apple-m1-with-rosetta-how-to-open-entire-terminal-iterm-in-x86-64-architec)

Thanks for submitting this request, we'll post any updates on this thread.

**Comment by cgatesman** [comment]
Create a copy of your Warp application and change the "Open using Rosetta" option on it:

![image](https://user-images.githubusercontent.com/6276072/229209995-8fed7daa-e362-481e-98cb-a6edb59a3ecb.png)
