### ISSUE TITLE
Button to Disable "insert suggested command"

### ISSUE THREAD

**Issue by curtischong** [warpdotdev/Warp#2847]
### Describe the solution you'd like?
```text
Most of the time, the suggestions aren't useful. 

For example, if I `cd assignments` but it doesn't exist, it tells me to insert `mkdir -p assignments && cd assignments`.

But I was just in the wrong directory.

I don't like this feature because you have to mouse over it to click it AND it takes up valuable vertical space on my screen. That's why I'd like a button to disable this. I think if you can make a keyboard shortcut to quickly insert the suggestion (without a mouse) that'd be better.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @curtischong you can disable command corrections from `Settings > Features > Editor` and Disable Suggest Command Corrections

![CleanShot 2023-03-28 at 15 45 38@2x](https://user-images.githubusercontent.com/16809145/228374457-c09d11bd-330a-4eed-a6d6-3aa0fa4a8580.png)

Or with the Command Palette `CMD-P` by searching for "Correction"

![CleanShot 2023-03-28 at 15 48 16@2x](https://user-images.githubusercontent.com/16809145/228374491-d5a4d7a7-0b9b-4004-ac8d-90aec6f19d13.png)

See more on this feature here: https://docs.warp.dev/features/editor/command-corrections

Closing as a way to disable this feature already exists.
