### ISSUE TITLE
Press Tab to insert suggested command

### ISSUE THREAD

**Issue by curtischong** [warpdotdev/Warp#2848]
### Describe the solution you'd like?

```text
In the image I presented, I wrote a zsh alias called `gotoschool`. Warp correctly predicts my indented command. However, I have to press the right arrow key to insert the predicted command into my terminal.

This is counterintuitive because users normally press "tab" to autocomplete a filename. Therefore, I would like the option to also press tab to insert this suggestion much like most other tab completion tools.
```

### Additional context

<img width="389" alt="image" src="https://user-images.githubusercontent.com/10677873/228285058-d50f0214-9b81-47c6-85b9-c42d7b6e059d.png">

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @curtischong appreciate you submitting this. We have an request tracking this here: https://github.com/warpdotdev/Warp/issues/1909

Please 👍  that request as it helps us gauge interest in the enhancement/feature.
