### ISSUE TITLE
DUP: Duplicate of 174 - Can't type accents, umlauts or open brackets in spanish keyboard

### ISSUE THREAD

**Issue by kusor** [warpdotdev/Warp#285]
### Describe the bug

```shell
When I try to type any of the following symbols on a Spanish keyboard, nothing is printed to the screen:

Group One (Same key):
- ^
- `
- [
Group Two (Same key):
- ¨
- ´
- {
```

### To Reproduce

Steps to reproduce:
1. Try to type any of the aforementioned symbols in warp using a spanish keyboard layout
2. See that nothing happens

### Expected behaviour

```shell
Obviously, I'd expect any character I type to "appear" on the screen
```

### Operating System

MacOS

### OS Version

11.6

### Additional context

```shell
Other keys on the spanish keyboard, like "ñ" or "ç" work w/o issues. I think the issue is exactly with these two keys.
```

**Comment by zheng** [comment]
Hi @kusor we have a fix for this that should be out in the release today!

**Comment by gagata** [comment]
This should be fixed in the recent stable release. Closing, but feel free to reopen if that's not the case for you
