### ISSUE TITLE
Vim mode is broken with fish

### ISSUE THREAD

**Issue by fwrs** [warpdotdev/Warp#2850]
### Describe the bug

If fish vim mode is on, warp becomes completely unusable. Every time a prompt is displayed, the line below PS1 is prefixed with the current vim mode and it's treated as a part of the inputted command, so it has to be manually erased. Furthermore none of the vim functionality actually works. Pressing `esc` does not switch the shell to normal mode.

### To Reproduce

preconditions:
1. config.fish has the following line: `fish_vi_key_bindings`
2. warp has its startup shell set to fish, e.g. `/opt/homebrew/bin/fish`
3. the "honor user's custom prompt (PS1)" setting can be on or off, it doesn't affect this

steps:
1. open a new warp instance
2. observe that the text indicating current vim mode `[I]` is on the incorrect line
3. try to enter a command, observe that this text is included as a part of the command, e.g. if you try to execute a command `test_command`, warp actually runs `[I]test_command`
6. press esc, observe that `[I]` doesn't change to `[N]`

### Expected behaviour

`[I]` is displayed before the ps1 prompt, vim mode works correctly, pressing escape changes the prompt to `[N]`, you don't have to erase unnecessary text each time you want to run a command

### Screenshots

<img width="1243" alt="Screenshot 2023-03-29 at 4 35 36 AM" src="https://user-images.githubusercontent.com/44343874/228405083-b7d70814-fd62-4de2-b69c-e8230f9097cd.png">

### Operating System

MacOS

### OS Version

13.3

### Shell Version

fish, version 3.6.0

### Warp Version

v0.2023.03.21.08.02.stable_03

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

**Comment by dannyneira** [comment]
Thanks for letting us know @
We're tracking this issue here #159 
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge interest in that feature.

Closing as duplicate.

**Comment by dannyneira** [comment]
Thanks for letting us know @GhIlyusha 

We're tracking this issue here https://github.com/warpdotdev/Warp/issues/159
Please 👍 and comment there if you're also seeing the issue, as it helps us gauge interest in that feature.

Closing as duplicate.

**Comment by GhIlyusha** [comment]
> Thanks for letting us know @GhIlyusha
> 
> We're tracking this issue here #159 Please 👍 and comment there if you're also seeing the issue, as it helps us gauge interest in that feature.
> 
> Closing as duplicate.

#159 is about bringing native vim editing to warp. But I'm using non-native vim keybindings provided by my shell and they don't work properly. I believe this is a defect, whereas #159 is an unrelated enhacement.

**Comment by dannyneira** [comment]
Got it, thanks for clearing this up @GhIlyusha I'll reopen it, but please note that progress on this most likely can't be made until native vim integration is working.

**Comment by Advait-M** [comment]
@fwrs - note that due to Warp's custom input editor (https://docs.warp.dev/features/editor), non-native vim mode _isn't_ expected to work directly i.e. fish shell's vim mode won't work in Warp. 

However, **we recently launched Warp-native vim mode, which should also work in fish** (see https://github.com/warpdotdev/Warp/issues/159#issuecomment-1749591863). See https://docs.warp.dev/features/editor/vim for the docs.

Could you please confirm this works for you and this issue is resolved? Closing this issue for now, but feel free to re-open as needed!

cc @esphen @KritPaoIn
