### ISSUE TITLE
It appears We are experiencing technical difficulties right now. Please try again later when using Warp AI

### ISSUE THREAD

**Issue by Oliverwqcwrw** [warpdotdev/Warp#2860]
### Describe the bug

<img width="423" alt="image" src="https://user-images.githubusercontent.com/31796988/229046273-d34e6ac3-4b57-4e71-bd12-ec1b0b172f51.png">

### To Reproduce

1 click Warp AI
2 send message to AI

### Expected behaviour

It can receive response normally

### Operating System

MacOS

### OS Version

12.6

### Shell Version

bash 3.2.57

### Warp Version

v0.2023.03.28.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
This is due to Open AI's servers being overloaded, which unfortunately, there isn't much we can do about. We're looking into ways to improve the messaging around this.

Closing as there is no solution to Open AI's servers.

**Comment by jovobe** [comment]
@dannyneira Warp is the only tool I use where I'm confronted with this issue. Are you certain that you cannot do anything about that? Other tools I use don't have this problem, even if they are using Open AI's servers. Perhaps you're using [old Codex models which are deprecated](https://platform.openai.com/docs/guides/code)?

**Comment by nicksp** [comment]
The issue still persists with no extra context around the issue 😞

**Comment by dannyneira** [comment]
@kevinyang372 @szgupta any insights to how users can prevent this?

**Comment by szgupta** [comment]
For those experiencing this issue, are you able to use Warp's other cloud-based features successfully, like creating a permalink or using AI Command Search?

**Comment by jovobe** [comment]
@szgupta Nope, that doesn't work:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/1265894/236024150-d343207c-d692-4b3a-8881-4d2fb8dbd712.png">

**Comment by jovobe** [comment]
@szgupta I tailed `~/Library/Application Support/dev.warp.Warp-Stable/warp_network.log` and got the following output while trying to create a permalink. Hopefully, that helps you.

> [2023-05-03 21:29:05,068]: Request { method: POST, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("securetoken.googleapis.com")), port: None, path: "/v1/token", query: Some("key=**REMOVED_KEY**"), fragment: None }, headers: {"content-type": "application/x-www-form-urlencoded"} }
> Body grant_type=refresh_token&refresh_token=**REMOVED_TOKEN**
> [2023-05-03 21:29:05,281]: Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("securetoken.googleapis.com")), port: None, path: "/v1/token", query: Some("key=*REMOVED_KEY**"), fragment: None }, status: 400, headers: {"pragma": "no-cache", "cache-control": "no-cache, no-store, max-age=0, must-revalidate", "expires": "Mon, 01 Jan 1990 00:00:00 GMT", "date": "Wed, 03 May 2023 19:29:05 GMT", "vary": "Origin", "vary": "X-Origin", "vary": "Referer", "content-type": "application/json; charset=UTF-8", "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000", "server": "ESF", "x-content-type-options": "nosniff", "x-xss-protection": "0", "x-frame-options": "SAMEORIGIN"} }
> [2023-05-03 21:29:05,281]: Request { method: POST, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("app.warp.dev")), port: None, path: "/proxy/token", query: Some("key=*REMOVED_KEY**"), fragment: None }, headers: {"content-type": "application/x-www-form-urlencoded"} }
> Body grant_type=refresh_token&refresh_token=**REMOVED_TOKEN**
> [2023-05-03 21:29:05,497]: Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("app.warp.dev")), port: None, path: "/proxy/token", query: Some("key=*REMOVED_KEY**"), fragment: None }, status: 400, headers: {"alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000", "cache-control": "no-cache, no-store, max-age=0, must-revalidate", "content-type": "application/json; charset=UTF-8", "expires": "Mon, 01 Jan 1990 00:00:00 GMT", "pragma": "no-cache", "set-cookie": "ajs_anonymous_id=**REMOVED_ID**; Path=/; Max-Age=31536000", "vary": "Origin,X-Origin,Referer", "vary": "Accept-Encoding", "x-content-type-options": "nosniff", "x-frame-options": "SAMEORIGIN", "x-xss-protection": "0", "server": "Google Frontend", "x-cloud-trace-context": "**REMOVED_CONTEXT**", "date": "Wed, 03 May 2023 19:29:05 GMT"} }

The strange thing about these requests is that the `username` is always a blank string. My account page in Warp settings says I'm logged in.

**Comment by dannyneira** [comment]
@jovobe there is a known issue causing online features not to work when the user token expires ( typically after you change your password ) Please see our docs for the workaround and let us know if that helps: https://docs.warp.dev/help/known-issues#online-features-dont-work

**Comment by jovobe** [comment]
@dannyneira that worked! Thank you so much!

**Comment by jserradellgaddexapp** [comment]
@dannyneira That works!!!! Thank you so much!!
