### ISSUE TITLE
Hieroglyphs will not display correctly, but as whitespace

### ISSUE THREAD

**Issue by lmllrjr** [warpdotdev/Warp#2861]
### Describe the bug

Display the [Egyptian Hieroglyphs](https://en.wikipedia.org/wiki/Egyptian_Hieroglyphs_(Unicode_block)) in the warp terminal does not work properly.

In our database we have alot of multibyte characters that just vanish inside the warp terminal.

### To Reproduce

1. copy `echo '𓅠 𓅡 𓅢 𓅣 𓅤 𓅥 𓅦'`
2. paste it in warp terminal + press enter

### Expected behaviour

When running the `echo '𓅠 𓅡 𓅢 𓅣 𓅤 𓅥 𓅦'` command in warp terminal it will print invisible hieroglyph characters.

### Screenshots

<img width="1440" alt="Screenshot 2023-03-31 at 1 42 16 PM" src="https://user-images.githubusercontent.com/93522910/229111149-5a8ce301-0026-4cbc-8f3e-20dd27a3fc1a.png">

left iTerm2, right warp

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.03.28.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting @lmllrjr 

We have an issue tracking this here #1832 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
