### ISSUE TITLE
SSH wrapper not working with cluster that prints custom prompt

### ISSUE THREAD

**Issue by Aariq** [warpdotdev/Warp#2863]
### Local Shell and Version

5.8.1

### Remote Shell and Version

4.2.46(2)-release

### Operating System and Version

macOS 13.2.1

### Warp Version

v0.2023.03.28.08.03.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

My University compute cluster prints the name of the cluster before the command prompt.  This becomes editible text, interpreted as a command if I turn on the SSH wrapper.

Without SSH wrapper:
<img width="1009" alt="Screenshot 2023-03-31 at 9 56 48 AM" src="https://user-images.githubusercontent.com/25404783/229140228-ffb43c67-88b1-44ad-9715-0b02bfd566d5.png">

With SSH wrapper:
<img width="1009" alt="Screenshot 2023-03-31 at 9 58 22 AM" src="https://user-images.githubusercontent.com/25404783/229140654-d354dfdc-6af6-4d85-95e7-62b6c69cdbed.png">

With SSH wrapper and "honor user's cusom prompt":
<img width="1025" alt="Screenshot 2023-03-31 at 11 18 21 AM" src="https://user-images.githubusercontent.com/25404783/229161463-8ded4523-157f-4276-9da9-2062669f462e.png">

### Include shell xtrace output

[xtrace.txt](https://github.com/warpdotdev/Warp/files/11123375/xtrace.txt)

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by Aariq** [comment]
Possibly duplicate of #2858??

**Comment by dannyneira** [comment]
Hi @Aariq Sorry to hear about this issue. As a workaround, I recommend you disable the SSH Wrapper, you'll lose Warp features in ssh sessions, but it should work and render as normal.

I'll surface this with the team, and we'll follow up here with any updates.

**Comment by Aariq** [comment]
Seems like this is maybe working now with the latest update

**Comment by Aariq** [comment]
Updated issue in #5428
