### ISSUE TITLE
Warp doesn't show the /etc/motd (message of the day)

### ISSUE THREAD

**Issue by rocoll** [warpdotdev/Warp#2864]
### Describe the bug

When ssh'ing into a Linux (CentOS) host using the MacOS Terminal (or most any other ssh client), the contents of the /etc/motd file are automatically shown prior to the first prompt. When using Warp, this doesn't happen - the motd is suppressed?

[https://man7.org/linux/man-pages/man5/motd.5.html](https://man7.org/linux/man-pages/man5/motd.5.html)

### To Reproduce

1. On a remote Linux host, put some testing text in /etc/motd
2. Use Warp to ssh to the remote host - the motd does not appear using Warp's command-line terminal
3. Stay in Warp, but ssh to `localhost` on the remote host - the motd should appear in the sub-shell's command-line terminal

### Expected behaviour

The motd should appear, if present, at initial logon when SSH'ing to a remote host using the Warp command-line terminal. 

### Operating System

None

### Warp Version

v0.2023.03.28.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @rocoll 
We're tracking this issue here https://github.com/warpdotdev/Warp/issues/1160
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.

Closing as duplicate.
