### ISSUE TITLE
Keybindings for cursor navigation in REPLs and subshells breaks shortcuts with conflicting combinations

### ISSUE THREAD

**Issue by mvlabat** [warpdotdev/Warp#2866]
### Describe the bug

Keybindings for cursor navigation in REPLs and subshell break shortcuts assigned to the following combinations: ⌥←, ⌥→, ⌥⌫, ⌘←, ⌘→, ⌘⌫, ⌘fn⌫

### To Reproduce

1. Apply the following hotkey settings:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/2943388/229274750-df408c20-2044-4c37-983e-4559f5bfd7d6.png">

2. Create a new tab
3. Try switching tabs by using the hotkeys

### Expected behaviour

I'd expect tabs to be switched

### Operating System

MacOS

### OS Version

13.3

### Shell Version

zsh 5.9

### Warp Version

v0.2023.03.28.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by mochaslave** [comment]
This is very annoying. It was working fine before this update. I just want to use the same hotkey as iTerm.

**Comment by alokedesai** [comment]
Hey folks, thanks for calling this to our attention and very sorry for the issues you are facing. I am actively working on a fix for this so that users can customize thes cursor navigation shortcuts. I expect this to be released on Thursday.

**Comment by dannyneira** [comment]
@th3fallen We don't normally advise downgrading Warp, given there may be other bug fixes/updates in the latest version. 

We will have a fix on this week's release. Appreciate your patience!

**Comment by th3fallen** [comment]
> @th3fallen We don't normally advise downgrading Warp, given there may be other bug fixes/updates in the latest version.
> 
> We will have a fix on this week's release. Appreciate your patience!

While i normally would not, it was either downgrade it or go back to iterm until it's resovled. given the two options i opted to downgrade.

**Comment by alokedesai** [comment]
Hey everyone, we pushed a new version of Warp today that allows you to unset these new bindings:

![image](https://user-images.githubusercontent.com/4110292/229950499-8f78cc95-3b0d-49e9-98f7-135a52c9a3a8.png)

Please let me know if you have any issues with this fix!

**Comment by th3fallen** [comment]
@alokedesai  you are a saint! My keys work again!!!!

**Comment by mvlabat** [comment]
I was able to re-assign the cursor navigation keys, and switching tabs started working again, thank you!

**Comment by alokedesai** [comment]
Great to hear! Thank you for using Warp and your patience here <3
