### ISSUE TITLE
save ssh profile same as iterm2

### ISSUE THREAD

**Issue by mhprabin** [warpdotdev/Warp#2868]
### Describe the solution you'd like?

```text
if we could save config file same as iterm2, then that will be great. i'm a network engineer so i would like to save remote server/router IP address.
```

### Is your feature request related to a problem? Please describe.

```text
not a problem but i would like to have this feature.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @

We have an issue tracking this here https://github.com/warpdotdev/Warp/discussions/442
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
