### ISSUE TITLE
tab into panes

### ISSUE THREAD

**Issue by ZonzeeLi** [warpdotdev/Warp#2871]
### Describe the solution you'd like?

```text
How to move another open tab into a pane combination？
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @ZonzeeLi, appreciate you taking the time.

We have an issue tracking this here #466 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
