### ISSUE TITLE
oh-my-posh sections are truncated by 1 character

### ISSUE THREAD

**Issue by quentin-sommer** [warpdotdev/Warp#2872]
### Describe the bug

warp is missing the first character in segments like directory name or branch name

### To Reproduce

install oh-my-posh with default theme. Both terminals are using Hack nerd font

### Expected behaviour

the strings should not miss their first character

### Screenshots

warp:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/9129496/229559143-32e70a7b-dd79-4ed8-b8b8-c029a9060121.png">

iterm:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/9129496/229559350-a576b7be-4505-43bf-a3f8-cc9ef455706a.png">

<img width="391" alt="image" src="https://user-images.githubusercontent.com/9129496/229559398-e7de8882-b6c6-4bc0-9721-dd8bb51356cd.png">

<img width="391" alt="image" src="https://user-images.githubusercontent.com/9129496/229559433-90bb1514-92aa-47a9-83da-f9f7130fc384.png">

### Operating System

macos

### OS Version

13.3 (22E252)

### Shell Version

zsh 5.8.1 (arm-apple-darwin21.3.0)

### Warp Version

v0.2023.03.28.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @quentin-sommer Sorry to hear about this, just to rule out any incompatibility on the prompt end of things, please open a [bug report with oh-my-posh maintainer](https://github.com/JanDeDobbeleer/oh-my-posh/issues/new?assignees=jandedobbeleer&labels=%F0%9F%90%9B+bug&template=bug.yml) as it may help as well, and link the issue here on this thread. 

We'll post any updates on the Warp side of things on this thread.
Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by JanDeDobbeleer** [comment]
@dannyneira I can confirm this isn't a bug in oh-my-posh but rather Warp escaping the ANSI link text.

**Comment by JanDeDobbeleer** [comment]
@dannyneira confirmed that Warp doesn't handle the hyperlink correctly.

```bash
%{[38;2;243;174;53m%}%{[0m%}%{[48;2;243;174;53m%}%{[38;2;38;43;68m%} ● 11 %{[0m%}%{[38;2;243;174;53m%}%{[0m%}%{[0m[38;2;240;118;35;49m[7m%}%{[0m%}%{[48;2;240;118;35m%}%{[38;2;224;222;244m%} 󰉋 %{]8;;file:/Users/jan/code/Sapling\%}Sapling%{]8;;\%} %{[0m%}%{[38;2;240;118;35m%}%{[0m%}%{[0m[38;5;32;49m[7m%}%{[0m%}%{[48;5;32m%}%{[38;2;224;222;244m%}  %{[0m%}%{[38;5;32m%}%{[0m%}%{]0;zsh in ~/code/Sapling%} %{]7;file://Jans-Air//Users/jan/code/Sapling\%}
``` 

<img width="331" alt="image" src="https://user-images.githubusercontent.com/2492783/229598678-64b2698b-58e9-42f6-9f79-b26d36df32df.png">

This is the full prompt string in zsh and Warp swallows the S from my Sapling directory. Without the hyperlink everything works as expected.

```bash
%{[38;2;243;174;53m%}%{[0m%}%{[48;2;243;174;53m%}%{[38;2;38;43;68m%} ● 13 %{[0m%}%{[38;2;243;174;53m%}%{[0m%}%{[0m[38;2;240;118;35;49m[7m%}%{[0m%}%{[48;2;240;118;35m%}%{[38;2;224;222;244m%} 󰉋 Sapling %{[0m%}%{[38;2;240;118;35m%}%{[0m%}%{[0m[38;5;32;49m[7m%}%{[0m%}%{[48;5;32m%}%{[38;2;224;222;244m%}  %{[0m%}%{[38;5;32m%}%{[0m%}%{]0;zsh in ~/code/Sapling%} %{]7;file://Jans-Air//Users/jan/code/Sapling\%}
```

<img width="331" alt="image" src="https://user-images.githubusercontent.com/2492783/229598751-9d1fcdcd-d718-4e90-9b10-ea02135bd46d.png">

**Comment by dannyneira** [comment]
@JanDeDobbeleer Thanks for the details! I'll bring this up with the team asap as a product quality issue.

**Comment by JanDeDobbeleer** [comment]
@dannyneira I wouldn't be much of an ambassador if I didn't go the extra mile now would I 😄

**Comment by kenmorse** [comment]
Thanks for reporting this @quentin-sommer — I see the very same problem.

**Comment by dannyneira** [comment]
Hi @quentin-sommer Yes, this has been added to our product quality sprint, we should be making progress on this issue sometime this quarter. We'll post more updates on this thread. We appreciate your patience and hope this isn't a huge blocker.

**Comment by quentin-sommer** [comment]
Thanks for the update 👍

**Comment by dannyneira** [comment]
@quentin-sommer Thanks for your patience with us. We've recently made some changes to prompt rendering in Warp, and it appears the changes fixed this issue with the rendering of oh-my-posh dir and branch names. Please update Warp to the latest (v0.2023.09.19.08.04.stable_00) and let us know if you still see the issue on your end.

![CleanShot 2023-09-28 at 09 21 08](https://github.com/warpdotdev/Warp/assets/16809145/766943df-e226-4f4a-9c5e-2d75809d07e7)

**Comment by kenmorse** [comment]
@dannyneira oh-my-posh looks good in Warp now — thank you!

**Comment by dannyneira** [comment]
@quentin-sommer @kenmorse Nice! I'll close this one as resolved, but if any further issues with oh-my-posh, please let us know.
