### ISSUE TITLE
Fish abbreviation is not expanded in Warp

### ISSUE THREAD

**Issue by timnew** [warpdotdev/Warp#2875]
### Describe the bug

I have a bunch of abbreviation setup in Fish, which is expanded into full string when I typed the abbreviation followed by a space. 

e.g. 
Given abbre setup as https://github.com/timnew/git.fish/blob/master/conf.d/git.fish

```
> gp
```
would be expanded to 

```
> git push
```

But the feature is broken in Warp now: 
<img width="231" alt="CleanShot 2023-04-04 at 14 58 22@2x" src="https://user-images.githubusercontent.com/1287238/229690999-22add680-3f4c-4426-a6a7-4f33a1450bce.png">

### To Reproduce

```
Fish> abbr -a -U -- gp 'git push'
Fish> gp <space>
```

### Expected behaviour

```
Fish> git push
```

### Screenshots

<img width="269" alt="CleanShot 2023-04-04 at 15 00 01@2x" src="https://user-images.githubusercontent.com/1287238/229691214-50d6b56d-2648-42fd-a68c-7c61bbebed56.png">

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

fish, version 3.5.1

### Warp Version

v0.2023.03.28.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by timnew** [comment]
I noticed that `<enter>` would expand the abbr normally, but `<space>` doesn't.

So if I type `gp<enter>` it works, but if I type `gp --force` it doesn't work

**Comment by bmikaili** [comment]
See https://github.com/warpdotdev/Warp/issues/1895

**Comment by dannyneira** [comment]
Thanks for submitting @

We have an issue tracking this here #1895 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
