### ISSUE TITLE
Setting for hiding three dots

### ISSUE THREAD

**Issue by olivernybroe** [warpdotdev/Warp#288]
### Describe the solution you'd like?

```shell
A simple setting for not showing the three dots in the corner.
```

### Is your feature request related to a problem? Please describe.

```shell
I like to do a clean UI and the three dots for me is unnecessary as on mac we are used to always open settings via cmd+j.

So it would be nice to be able to simply just hide the three dots for cleaning up my UI even more.
```

**Comment by elviskahoro** [comment]
Linking

- [ ] https://github.com/warpdotdev/warp/issues/175

**Comment by dannyneira** [comment]
We're working on some improvements in this area and will be releasing something soon!

**Comment by dannyneira** [comment]
Closing as resolved since Warp no longer has the ... button. Regarding cleanup of the UI tab bar we are tracking that here https://github.com/warpdotdev/Warp/issues/3216
and here: https://github.com/warpdotdev/Warp/issues/1009
