### ISSUE TITLE
bash $PROMPT_COMMAND

### ISSUE THREAD

**Issue by MadBomber** [warpdotdev/Warp#2882]
### Describe the bug

Running `bash` as the default shell with lots of extensions and functions.  I use a function to generate the $PS1 value.  That functions is hookd into the system via the $PROMPT_COMMAND.  Several extension also hook into the prompt in order to keep track of which directories I commonly visit so that I can use shortcuts to get from any where to anywhere else with have to type `cd the/long/painful/path/to/where/I_want/to/go`

Taking my environment without modification and using Warp - btw great name because my extensions load a warp speed compared to iTerm2 - my prompt gets displayed exactly how I expect.  HOWEVER, Warp thinks that the prompt is really the first part of any command that I type in.  I have to backspace over the prompt to enter the command that I want executed.

I had to add this code at the bottom of my `.bashrc` file to remove my prompt extensions when in a Warp terminal session:

if [[ -n "${WARP_SESSION_ID}" ]]; then
  echo "Running in a warp terminal"
  unset PROMPT_COMMAND
else
  echo "Not running in a warp terminal"
fi

### To Reproduce

Install some extensions that hook into the $PROMPT_COMMAND.  Here is what the value of mine look like:

16:59:11 3.2.0  Earth:~ $ echo $PROMPT_COMMAND
__prompt_command;__jump_prompt_command;_direnv_hook;history -a; history -n; syncHistory _z --add "$(command pwd -P 2>/dev/null)" 2>/dev/null;

_prompt_command is my function that builds PS1 with current time, ruby version git branch database name prefix host name and pwd basename

jump and direnv are common extensions.

The history stull is mine that syncs history from each tab in the terminal into one history file.

### Expected behaviour

I expect Warp not to prepend $PS1 to the command entered.  Just display the prompt - don't try to execute it.

### Operating System

None

### OS Version

MacOS 13.2.1  M1-max

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)

### Warp Version

v0.2023.03.28.08.03.stable_02

### Additional context

I am not a daily Warp user... yet.  What I've seen so far is bery exciting.  The quickness at which it load the 68 .bashrc_* that establish my bash environment is astounding.  I'm also liking the command line suggestions / completions.

When I can see my prompt with all of its extensions hooked in and be able to automatically open the 9 common tabs that I use with each focused on a different directory and background jobs, then its going to be hard to say no to using Warp as a daily driver.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by MadBomber** [comment]
I'm closing this issue as a duplicate of one that was raised back in January.

**Comment by alokedesai** [comment]
Thanks for filing @MadBomber! We are actively working on a fix for this that will fix this issue, we expect it to launch in the next few weeks.

**Comment by dannyneira** [comment]
Duplicate of #2516
