### ISSUE TITLE
"ls -ltr" command won't display correct file info if vs code modifies those files

### ISSUE THREAD

**Issue by zxcfan** [warpdotdev/Warp#2883]
### Describe the bug

In existing tab, initially "ls -ltr" command can display correct file names under a folder. Switch to VS code, run "mvn clean install package azure-functions:run", it will first clean up all files, and run an application, which will create those files again. After the mvn process is complete, go back to existing tab, run "ls -ltr", nothing is there, but if run "cd" command to other folder, and "cd" back, then "ls -ltr" can display correct files.

### To Reproduce

1.  initially "ls -ltr" command can display correct file names under a folder.
2. Switch to VS code, run "mvn clean install package azure-functions:run", it will first clean up all files, and run an application, which will create those files again. I believe that other app out of Warp will cause the same issue.
3. go back to existing tab, run "ls -ltr", nothing is there.

### Expected behaviour

"ls -ltr" should display correct file names after other app delete files and add files.

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1

### Warp Version

v0.2023.03.28.08.03.stable_02

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @zxcfan 

Unfortunately, I can't reproduce this on my end, but I also don't have a working `pom.xml` to try it with maven, so it may only be an issue with running maven and not with just creating/deleting files within the vs code terminal(that seems to work).

Could you please provide a video /screenshots of the issue along with an example pom.xml so we can try and reproduce it on our end?

We'll post any updates on this thread.
Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by zxcfan** [comment]
I created a video, and updated [here](https://mega.nz/file/dT0UDCAa#d9_YgSsH3UFp1T9eMTvudsOFiaxYIj5fALkHiuLQ6Pc), please let me know if you can review it. This page won't let me update the video since it has 100+MB file size.

**Comment by dannyneira** [comment]
Thanks for submitting the video, we'll follow up here if there are any updates on this issue.

Just to set realistic expectations, it may be a while before a fix given the issue seems very specific to maven so I recommend you just do the `cd ../ ; cd /your_folder` as a workaround for the time being.

**Comment by vorporeal** [comment]
@zxcfan If the maven command is deleting the folder that your shell is using as its working directory and recreating it, this is how Unix behaves (and you'd be able to reproduce this with any shell and terminal).

The current directory, while represented visually to you as a file path, is actually internally represented by a unique identifier for the working directory.  When you delete and recreate the folder at a given path, the shell is still actually within the old working directory.  When you cd out of the directory and back in, while it appears that you haven't actually changed your working directory, you're leaving the directory that _used_ to exist at that path and entering the directory that _now_ exists at that path.

Can you try this out in a different terminal and let me know whether it's a Warp-specific issue?

**Comment by zxcfan** [comment]
Thanks for your information. I use Mac built-in Terminal and it shows exactly the same behavior, so it's not an issue in Warp. I will close this issue.
