### ISSUE TITLE
The keyboard shortcut for the workflow is not working, even after changing it to a different one.

### ISSUE THREAD

**Issue by JuniperPhoton** [warpdotdev/Warp#2888]
### Describe the bug

The keyboard shortcut to invoke the workflow panel is not working: when I press the key, nothing happens.

I tried setting the keyboard shortcut to another one, ensuring that it's not used by other apps, and the issue still occurred.

### To Reproduce

1. Set the keyboard shortcut for the workflow to Shift+Command+T
2. Press Shift+Command+T, nothing happened

The default one is not working either.

### Expected behaviour

The keyboard shortcut should work.

### Screenshots

<img width="897" alt="image" src="https://user-images.githubusercontent.com/7578386/230391487-090d7415-63ce-4e08-99ec-9b15e786b372.png">

### Operating System

MacOS

### OS Version

macOS 13

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.03.28.08.03.stable_02

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by alokedesai** [comment]
Hey @JuniperPhoton, sorry for the issues you are experiencing! Are you using a non-english keyboard by chance?

Also just confirming that the default shortcut `ctrl-shift-r` did not work? The reason I ask is that you mention you tried `cmd-shift-T` in the Github issue, but I want to sanity check that you weren't accidentally swapping `ctrl` and `cmd` here when you tried the original shortcut.

**Comment by JuniperPhoton** [comment]
I thing I managed to resolve this issue by setting it to `Ctrl+Cmd+R`, which does not include `Shift` key. By setting this, the default one and the new one are working. I tried reinstall Warp and it still works, great.

And by the way, `Ctrl` and `cmd` are not swapped and in that case, I was using an English keyboard.

Furthormore, after resolving the issue like I said above, I tried switch to Chinese keyboard and it still works, this is strange.

**Comment by dannyneira** [comment]
I'd also confirm if you have the Global hotkey enabled or not in `Settings > Features > Keys`, this one has a default of `SHIFT-CMD-T` so that may have been in conflict with your Workflow keybind. 

![CleanShot 2023-04-06 at 10 30 39](https://user-images.githubusercontent.com/16809145/230440551-932e6b40-9019-4a21-8785-cb9ca365c411.png)

Closing as resolved since you're figured out the workaround.
