### ISSUE TITLE
The context menu should utilize the native style of the target platform.

### ISSUE THREAD

**Issue by JuniperPhoton** [warpdotdev/Warp#2889]
### Describe the solution you'd like?

```text
I know currently the whole UI is written in Rust by yourself, which is awesome.

But sometimes it would be better to have some native experience like showing the native style context menu on right-clicking the selected texts.

Currently the context menu is not as good as the one on macOS. If Warp is targeting to Windows, then it should also use the standard context menu as well.
```

### Is your feature request related to a problem? Please describe.

```text
No.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @

We have an issue tracking this here #2648
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
