### ISSUE TITLE
Unable to use ProxyJump (-J) with SSH

### ISSUE THREAD

**Issue by Clansty** [warpdotdev/Warp#2896]
### Describe the bug

If I use ProxyJump feature of SSH, I will get 

```
banner exchange: Connection to UNKNOWN port 65535: Broken pipe
```

### To Reproduce

Use `ssh host1 -J host2` or set `ProxyJump` option of a host in `~/.ssh/config`, connect to the host with ssh in warp

### Expected behavior

Got a warp-featured ssh session to the host

### Screenshots

<img width="752" alt="image" src="https://user-images.githubusercontent.com/18461360/230554667-e632cc2d-6214-4095-89d6-2b129d6a356d.png">

### Operating System

MacOS

### OS Version

13.4

### Shell Version

zsh 5.9 (aarch64-apple-darwin22.2.0)

### Warp Version

v0.2023.04.04.08.03.stable_01

### Additional context

`Host *` part of `~/.ssh/config`:
```
Host *
  ForwardAgent yes
  Compression yes
  ServerAliveInterval 30
  ServerAliveCountMax 10
  HashKnownHosts no
  UserKnownHostsFile ~/.ssh/known_hosts
  ControlMaster auto
  ControlPath ~/.ssh/master-%r@%n:%p
  ControlPersist 4h
  TCPKeepAlive yes
  User clansty
```

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by vorporeal** [comment]
@Clansty Warp's SSH wrapper, at present (we're planning on changing this), internally uses ControlMaster to be able to generate autocompletions data for the remote shell.  If you comment out the ControlMaster and ControlPath lines in your ssh config, does that fix the issue?

**Comment by Clansty** [comment]
Still doesn't work.

config file:
```
Host *
  ForwardAgent yes
  Compression yes
  ServerAliveInterval 30
  ServerAliveCountMax 10
  HashKnownHosts no
  UserKnownHostsFile ~/.ssh/known_hosts

  TCPKeepAlive yes
  User clansty
```

**Comment by vorporeal** [comment]
@Clansty We figured out one possible source of the issue and have a fix going out in this week's release.  Did you configure the startup shell (in Settings > Features) to be "zsh"?  If so, it'll be fixed this week, and you can temporarily work around it by switching the startup shell configuration to "custom" and providing the absolute path to the `zsh` binary.

**Comment by Clansty** [comment]
> Did you configure the startup shell (in Settings > Features) to be "zsh"?

Yes, I think that is the problem. After I set to default it got work.

**Comment by dannyneira** [comment]
Hey Folks! Just wanted to give you a quick update - we've fixed the issue with the latest version of Warp `v0.2023.04.25.08.05.stable_00`. 

I'll go ahead and mark this task as complete, but if you notice anything else, feel free to give us a heads-up. Thanks!
