### ISSUE TITLE
Double click on the titlebar expands the window under the dock

### ISSUE THREAD

**Issue by manuhank** [warpdotdev/Warp#2899]
### Describe the bug

The window gets expanded above the dock space.
https://user-images.githubusercontent.com/19393548/230615386-c770d505-d3a2-4229-b6f2-fde9b9c65c18.mov

### To Reproduce

1. open wrap
2. double click the title bar (where no tabs are displayed)
The window expands to take the entire work area (display minus dock and menubar)

### Expected behavior

The window expands to the entire of the display minus the menubar.

### Screenshots

https://user-images.githubusercontent.com/19393548/230615386-c770d505-d3a2-4229-b6f2-fde9b9c65c18.mov

### Operating System

MacOS

### OS Version

13.2.1

### Warp Version

v0.2023.04.04.08.03.stable_01

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @manuhank Thanks for submitting this. Can you try and quick Warp, make sure you don't have hide enabled on your dock, and then restart Warp and see if the issue persists. If so, please run the following and let us know the result.
`defaults read dev.warp.Warp-Stable`

**Comment by manuhank** [comment]
Hi @dannyneira . I upgraded to macos 13.3.1 and the issue stopped reproducing since.

**Comment by dannyneira** [comment]
Thanks for letting us know, I'll recommend to users upgrade MacOS in the future.
