### ISSUE TITLE
Can't close command pallete with Esc after creating new tab while command pallete is open

### ISSUE THREAD

**Issue by dylanwishner** [warpdotdev/warp#29]
**Describe the bug**
You can not close the command palette with `escape` if a new tab is created while the command palette is open.

**To Reproduce**
1. Open the command palette
2. Create a new tab (cmd + t or by clicking the + button)
3. Try to close command palette with `escape` key.

**Expected behavior**
The command palette should close when the `escape` key is pressed, as it does before creating a new tab.

**Desktop (please complete the following information):**
 - OS Version: macOS 12.0 Beta 3
 
**Additional context**
The command palette can still be closed by clicking on one of the commands, just not with `escape`.

**Comment by zheng** [comment]
This is fixed & released!

**Comment by zheng** [comment]
Mistook this for another issue!

This has been root-caused & will be in soon. It should be released next week, if not this week.
