### ISSUE TITLE
Add space after completion

### ISSUE THREAD

**Issue by SBoudrias** [warpdotdev/Warp#290]
### Describe the solution you'd like?

When autocompleting a command, it's a time saver to add a space after the command so we can continue typing right away.

For example `git che<TAB>` today will enter `git checkout`, but we'd want it to complete to `git checkout ` (with the space at the end.)

### Is your feature request related to a problem? Please describe.

I think most terminal do add the space after the autocomplete; so it has indeed been a little of frustrating experience when typing and then having to inject a space.

**Comment by zheng** [comment]
Thanks for the feature request!

**Comment by lkoepsel** [comment]
Similar to the request above, I expect a space to be placed after a file/folder has been dropped on to the terminal.

For example I have a command which operates on two folders, I type the command:
```
mf.py 
```
Then drag and drop two parameters (typically folders from Finder) onto the terminal. In iTerm, there is a space automatically placed between the two parameters, in Warp it ends up looking like:
```
mf.py /Users/lkoepsel/2015_10_16/Users/lkoepsel/2015_10_16_copy
```
It does work properly if I select both files before dropping them onto Warp.

**Comment by martinbean** [comment]
This would be a _huge_ quality of life improvement.

I’m battling muscle memory every day hitting <kbd>Tab</kbd> and just typing the rest of a command, only to realise I need to go back and add a space.

**Comment by alokedesai** [comment]
Closing this out since we've since fixed this. Feel free to reopen if you are still experiencing issues here!
