### ISSUE TITLE
Possibility to disable discrete hardware acceleration

### ISSUE THREAD

**Issue by VladStepanov** [warpdotdev/Warp#2904]
### Describe the solution you'd like?

```text
As a intel-based macbook owner, i would be happy if i could tell the Warp  
to don't utilise my discrete GPU because it makes the macbook hotter
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @

We have an issue tracking this here #76 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

As a workaround, there is the possibility to disable the dGPU and Mac will fall back to using the iGPU. [See instructions on this here](https://github.com/warpdotdev/Warp/issues/76#issuecomment-1397309917).

Closing as duplicate.
