### ISSUE TITLE
Make it visible/clear that Warp won't work without login/account

### ISSUE THREAD

**Issue by ghost** [warpdotdev/Warp#2905]
### Describe the bug

Hello,

Prior to installing Warp, I did read the top pages of your website, such as [the homepage](https://www.warp.dev/) and [the download page](https://app.warp.dev/get_warp), and at no point was it mentioned to me that Warp won't work without login/account. In fact, [the homepage](https://www.warp.dev/) says:

> Private & Secure
> All cloud features are opt-in.

If "all cloud features are opt-in", as you claim, one would assume that login/account is also opt-in.

Anyway, this is _not_ a request to remove the login/account requirement, because apparently you've already rejected this request on multiple occassions:

- #900
- #160
- #1838
- #1119
- #1045

This is a request to make the requirement visible/clear on the top pages of your website.

### To Reproduce

(See above.)

### Operating System

None

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @kersti-h Thanks for calling this to our attention. We could work on making this more clear and will consider updating the website/download page. 

For now, we do have something in our Getting Started docs, that mentions the login requirement. https://docs.warp.dev/getting-started/getting-started-with-warp#logging-into-warp

**Comment by notstephen** [comment]
> For now, we do have something in our Getting Started docs, that mentions the login requirement.

So you expected users to read the documentation before downloading the package? Good luck with that!

**Comment by danymat** [comment]
From your docs, you mentioned: 

> During our closed beta, we require a login to interact with you, get your feedback, and focus on improving the app. After installing Warp for the first time, you will be prompted to log in with GitHub, Google, or via an email link.

That means login will be optional after beta ?

**Comment by epipheus** [comment]
wtf? who wants to login for a term?! please remove this!

**Comment by freitagdavid** [comment]
It really needs to be in big red letters right on the front page of your site, or even better require a log-in before you can download the app.

**Comment by wociscz** [comment]
<rant> Insta-uninstall after login prompt popped up. Like wtaf? Imagine vscodium with forced login - I'd never use it 24/7 as I do. Could be best in the world, but login? For terminal app? What sick world we are living at. </rant>

**Comment by zachlloyd** [comment]
The login requirement has now been lifted.

More info here if you're interested: https://www.warp.dev/blog/lifting-login-requirement
