### ISSUE TITLE
DUP: Duplicate of #023 - Collapsable Cells / Blocks

### ISSUE THREAD

**Issue by JosephTLyons** [warpdotdev/warp#291]
### Describe the solution you'd like?

```shell
It would be neat if you could collapse the cells, much like you would with code folding in an editor, so that it hides all of the contents, except for maybe some sort of identifying like, like that one that contains the command ran.  Being able to collapse the cells of long items would make it easier to scroll up and down between commands that were ran before and after it.
```

**Comment by JosephTLyons** [comment]
> Thanks for filing! We have mocks for how we want this to work. I'm not sure when we will prioritize it.
> 
> ![image](https://user-images.githubusercontent.com/29991019/138179092-6ec74190-0c29-46e5-8f5c-7b6198744064.png)

This workflow seems to make sense to me too

**Comment by elviskahoro** [comment]
Support (collapse all except current, specific ones, etc)

**Comment by elviskahoro** [comment]
Team has decided to merge this into:
- https://github.com/warpdotdev/warp/issues/023

Will move conversations there.
