### ISSUE TITLE
Cursor on top of the window

### ISSUE THREAD

**Issue by abhinavkshitij** [warpdotdev/Warp#2910]
### Discord username (optional)

AbhinavKshitij

### Describe the solution you'd like?

```text
Warp has been a great productivity booster in my daily workflow. Except like most of terminals, it would be great to have the cursor/prompt on top rather than at the bottom to get a clearer, more natural feel.
```

### Is your feature request related to a problem? Please describe.

```text
Having the cursor/prompt at the bottom occludes view and prevents separating sets of cmds.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by siva-kommireddy** [comment]
@abhinavkshitij -- This feature was recently rolled-out (April 6th) by Warp. If you update the warp to latest release, you will find the setting for `input position` in preferences to select various options for cursor input positions as seen in the image below.

<img width="496" alt="2023-04-10_0-54-0" src="https://user-images.githubusercontent.com/40446666/230836435-e0a7d5f7-3a7d-4fdd-9c5e-9b760e6dce20.png">
