### ISSUE TITLE
Duplicate Warp icon on Mac Dock after an upgrade

### ISSUE THREAD

**Issue by abhinavkshitij** [warpdotdev/Warp#2911]
### Discord username (optional)

AbhinavKshitij

### Describe the bug

Warp creates a new Warp icon instead of replacing the existing one in Mac’s dock. Usually if an app icon is added permanently to the Dock, the same icon is used after updating the app. 

### To Reproduce

1. Add Warp to Dock
2. Open a few windows 
3. Click on Warp’s Upgrade button 
4. Warp shuts down and launches with a new icon outside the section containing permanently added apps in the Dock
5. The old icon then needs to be removed and replaced by the new icon every time after an upgrade. 

### Expected behavior

The Warp icon should be the same after each upgrade. 

### Operating System

None

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @abhinavkshitij!

We're tracking this issue here #2824 

Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.

Closing as duplicate.

**Comment by lahirudx** [comment]
Same issue here. Duplicate Warp Icon in the recent area.
<img width="1153" alt="Screenshot 2023-09-07 at 10 52 42 PM" src="https://github.com/warpdotdev/Warp/assets/34573001/3bb2e825-ea7e-42e0-8738-209ded1e0c7c">
