### ISSUE TITLE
Ability to use `ESC` key for keybindings

### ISSUE THREAD

**Issue by pavlospt** [warpdotdev/Warp#2913]
### Describe the solution you'd like?

```text
Ability to use `ESC` key for combination of keybindings.
```

### Is your feature request related to a problem? Please describe.

```text
Hello, 

Generally on macOS you can use `ESC + Delete` in order to delete left whole words, but on Warp you cannot assign a keybinding that has a combination of `ESC` + another button. 

Is there a specific reason for that?
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @pavlospt 

We have an issue tracking this here #1563 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
