### ISSUE TITLE
Control Over Cursor Type / Consistent Cursor Type

### ISSUE THREAD

**Issue by astrobc1** [warpdotdev/Warp#2916]
### Describe the solution you'd like?

```text
It would be nice if either:

1. One can customize the type of cursor.
2. The cursor is consistent across different effective shells/repls.

For example, the default cursor is a line, whereas in Python the cursor changes to a block.

Since not everyone can agree on lines vs blocks, option #1 is preferred.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @astrobc1 

We have an issue tracking this here #1031 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
