### ISSUE TITLE
Slow Initial zsh Load Time

### ISSUE THREAD

**Issue by falchion10** [warpdotdev/Warp#2917]
### Discord username (optional)

falchion#0420

### Describe the bug

Whenever you reboot macOS and initially load zsh for the first time in Warp it takes ~4.5 seconds (It stays on "Starting zsh..." for this amount of time). This isn't an issue with the default terminal app. It's only the initial Warp zsh load that is ~4.5 seconds, every load after that takes ~0.25 seconds, which is what I'd expect. I've commented out literally everything in my .zshrc and .zprofile and it still takes the same amount of time, so my zshrc and zprofile aren't the issue here. I've also switched between the native zsh and the homebrew version and they're both the same.

I'm really confused as to what the issue is here as I've basically narrowed down my issue as much as I can and I still can't pinpoint this initial slow load time issue.

### To Reproduce

1. Reboot macOS and open the default terminal for the first time, it will load in milliseconds.
2. Open Warp for the first time and it will take ~4.5 seconds to load.
3. Quit and reopen the default terminal app, still takes milliseconds to load.
4. Open Warp and now it only takes ~0.25 seconds to load.

You don't have to open the default terminal app, just wanted to use it as an example as load times for the default terminal are the exact same, no matter if you load it after a restart or just at a random time.

### Expected behavior

I expect the load time between the initial launch and opening it later to be basically the same.

### Screenshots

None

### Operating System

MacOS

### OS Version

13.3.1

### Shell Version

zsh 5.9

### Warp Version

v0.2023.04.04.08.03.stable_01

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
Hey @falchion10 thanks for opening. Are you a new Warp user, by the way? We're actually investigating this right now!

Were you using Warp 3 or more weeks ago and this started happening recently? Or are you a new user and it's been happening since you started?

**Comment by falchion10** [comment]
Yea, I'm a pretty new user. I tried it out around 3 weeks ago actually, and this is the first time I've ever experienced this bug. Glad to know you guys seem to already be aware of it. Have other users reported on this same bug? I didn't see another Issue on Github like mine.

**Comment by elviskahoro** [comment]
the team has some ideas about what's going on

@falchion10 when you're rebooting your computer, do you keep the: "reopen windows after I log in" option enabled?

**Comment by falchion10** [comment]
No, I never use that "feature". I always restart fresh and don't want programs reopening.

**Comment by falchion10** [comment]
Just updated to the latest version of Warp just now, and it appears it's taking 10-11 seconds on the initial load now instead of the ~4.5 seconds. I'm not sure what's going on here.

**Comment by falchion10** [comment]
Any eta on when this bug will be fixed? It's been a month now with seemingly no updates on it.

**Comment by elviskahoro** [comment]
Surprised it's still happening. Can you send a video of what Warp does and what iTerm / Mac Terminal do?

Also can you quickly set up clean configs by putting ZDOTDIR=/ in a ~/.zshenv file. This forces zsh to run with zero configs.
https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files

**Comment by falchion10** [comment]
Not sure why it would be fixed, I've been looking through the changelogs for the past month and there's been seemingly no mention of this bug. Here's a recording of what happens with the default Terminal and Warp on startup. I don't use iTerm so there's no video of it here. [Warp](https://cdn.discordapp.com/attachments/1095010617989025842/1108130011476668456/Warp.mov) [Terminal](https://cdn.discordapp.com/attachments/1095010617989025842/1108130301214990366/Terminal.mov)

**Comment by elviskahoro** [comment]
@falchion10 Can you try this and let us know what happens:
> ZDOTDIR=/ in a ~/.zshenv file

**Comment by vorporeal** [comment]
Alternatively, if you wouldn't mind sharing the contents of your rcfiles (~/.zprofile and ~/.zshrc), that might help us reproduce the issue you're experiencing.  Feel free to redact any personal or sensitive information.

**Comment by falchion10** [comment]
@elviskahoro That line was added to my zshenv in the video. You can see I have the default prompt in both Terminal and Warp in both videos.

**Comment by falchion10** [comment]
@vorporeal Ive already tried completely deleting my rc files and it has no effect.

**Comment by Nurou** [comment]
New user here as well, takes me around 2s to start zsh as well. Never had this issue with iTerm or stock Terminal

**Comment by falchion10** [comment]
Couldn’t be bothered to keep trying to fix the issue so I just DFU restored. The slow load times are gone, I have no idea what it was ¯\_(ツ)_/¯

**Comment by falchion10** [comment]
I'm 99% sure this issue has something to do with installing Xcode, right after I installed it I started getting slow zsh load times again.

**Comment by falchion10** [comment]
I just found the solution! TLDR: when you install Xcode the Command Line Tools path changes from /Library/Developer/CommandLineTools to /Applications/Xcode.app/Contents/Developer. This causes slow zsh load times, I have no f**king idea why. To change the path back run "sudo xcode-select -s /Library/Developer/CommandLineTools", reboot, and BOOM slow zsh load times are gone. There's no way I'm the only one experiencing this issue, I don't know if this is only caused by the App Store version of Xcode, but that's the version I use.

**Comment by vorporeal** [comment]
Whoa, this is super helpful!  This is probably due to the fact that we check if you're in a git repository while initializing the shell, and when the Xcode-provided git binary is used (and it's the first time since a restart that anything has invoked `/usr/bin/git`), it hangs for a while while macOS does \*something*.

Looks like this is an issue many people have experienced with other terminal/shell tools on macOS, e.g.: https://github.com/ohmyzsh/ohmyzsh/issues/10693

Unfortunately, switching to the non-Xcode command-line tools won't be an option for everyone (for example, Warp won't build that way).  `brew install git` also won't immediately work because the first time we invoke `git` is before we've sourced the user's rcfiles, so `PATH` won't include any homebrew-installed binaries, though that's something we can pretty easily fix.

Thank you so much for following up with the extra details!  Hopefully we can have something rolled out to address this in next week's release. :)

**Comment by falchion10** [comment]
No problem, I'm just glad I finally found out and was able to help. This bug has been annoying me for around a month now. After you guys push an update I'm going to move back over to the Xcode included command line tools!

**Comment by falchion10** [comment]
I'm sure 99% of people would not care if you had to use the homebrew version of git, hell I even use it. The Apple versions of stuff like git and zsh aren't even updated unless you do an entire os update so the homebrew version is probably just better anyway. Thanks so much for fixing this issue, can't wait to see Thursday's release and switch back to the Xcode version of command line tools!

**Comment by vorporeal** [comment]
I agree that they probably wouldn't care, but if we can provide a better experience out-of-the-box without asking users to go install some additional tool, we should!  (In general, that's what we strive for, but there's a lot of work to do to get there across all parts of the experience. 😄 )

**Comment by falchion10** [comment]
Just saw the update get pushed, seems to be working perfectly! Should we close this issue or leave it open until a fix for the default git is introduced?

**Comment by vorporeal** [comment]
Yeah, we can close this out and we'll internally track fixing the default git issues.

Thanks again for your help tracking down the cause!

**Comment by falchion10** [comment]
No problem, good luck on fixing the default git issue!
