### ISSUE TITLE
Add terminal support for Emacs-like keymap

### ISSUE THREAD

**Issue by LitoMore** [warpdotdev/Warp#292]
### Describe the solution you'd like?

In most place of macOS, we can use Emacs-like keymaps to control our cursor. Such as moving cursor, deleting characters...

But in Warp. I cannot use <kbd>control + n</kbd> and <kbd>control + p</kbd> to replace arrow keys.

Here is some information about the macOS built-in Emacs-like keymaps: https://jblevins.org/log/kbd

Here is a simple list to let you understand the habits of Emacs users:

> _`Any textarea` means any textarea on macOS, such as the textarea in browser, Notes app..._

| Keymap | Function | Any textarea | iTerm / Terminal.app | Warp |
|:-:|:-:|:-:|:-:|:-:|
| <kbd>control + n</kbd> | Down arrow | Yes | Yes | No |
| <kbd>control + p</kbd> | Up arrow | Yes | Yes | No |
| <kbd>control + b</kbd> | Left arrow | Yes | Yes | No |
| <kbd>control + f</kbd> | Right arrow | Yes | Yes | No |
| <kbd>control + t</kbd> | Switch characters | Yes | Yes | No |
| <kbd>control + d</kbd> | Delete right side character | Yes | Yes | No |
| <kbd>control + g</kbd> | Cancel / ESC | Yes | Yes | No |
| <kbd>control + h</kbd> | Delete left side character | Yes | Yes | Yes |
| <kbd>control + a</kbd> | Move to start of line | Yes | Yes | Yes |
| <kbd>control + e</kbd> | Move to end of line | Yes | Yes | Yes |
| <kbd>control + u</kbd> | Delete line | Yes | Yes | Yes |
| <kbd>control + j</kbd> | Return | No | Yes | No |

### Is your feature request related to a problem? Please describe.

I strongly recommend finding an Emacs and Vim expert in your team to be a consultant for this feature.

If there is not. I would like to help.

**Comment by srl295** [comment]
complete blocker for me.  I had to repeat my workflow several times in slow motion to figure out what of my ingrained muscle memory was telling Warp to suddenly shut the tab.

Control-P, Control-A, Control-F, **Control-D**

I'll come back and try Warp again when this is fixed!

**Comment by elviskahoro** [comment]
Going to merge this with 
- #100

**Comment by beorn** [comment]
@elviskahoro The new custom keybindings unfortunately does not support bindings for up/down/left/right - which are the main emacs-like keybindings people were requesting.  It's not about rebinding up/down/left/right but allowing ctrl p/n/b/f as alternative keybindings for that.

**Comment by elviskahoro** [comment]
@beorn Got it! Reopenning and decoupling from #100

**Comment by elviskahoro** [comment]
@beorn @srl295 @LitoMore these were added in this week's update!

**Comment by bistack** [comment]
@elviskahoro  The fix patch was not complete.  When login another Linux server, the key bind did not work. For example, Alt + f, Alt + b on a shell command line.  Alacritty is OK in these case, with  key binding in ~/.config/alacritty/alacritty.yml
