### ISSUE TITLE
Support RPS1

### ISSUE THREAD

**Issue by spadger** [warpdotdev/Warp#2923]
### Describe the solution you'd like?

```text
Warp supports a custom PS1 which is useful, but I make use of the RPS1 as well, which is only accessible by starting a new shell.
```

### Is your feature request related to a problem? Please describe.

```text
I use multiple Kubernetes clusters, and use `kubectx` to switch between them.  I use RPS1 so I always know what context I am using
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by spadger** [comment]
Example - I am using the GEW3 cluster, and can see this when using a standard zsh session
![image](https://user-images.githubusercontent.com/216748/231184100-238e8442-2d02-476f-8ef7-75dc5f039621.png)

**Comment by dannyneira** [comment]
Thanks for this feature request! @spadger I appreciate all the details you put into this request.

Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

As a possible stopgap, I suggest you try our custom prompt Starship.rs, it's [supported in Warp](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table) and has a configuration for Kubernetes context/namespaces/etc. https://starship.rs/config/#kubernetes

We also have a related bug you should check out here [where PS2 doesn't override PS1](https://github.com/warpdotdev/Warp/issues/2671).

**Comment by dannyneira** [comment]
@spadgr Yes, I forgot to mention, [it's in the docs](https://docs.warp.dev/features/prompt#multi-line-and-right-sided-prompts), that Warp generally doesn't work with right-sided or multi-line prompts ( the only custom prompt that does have it working in Warp is [oh-my-posh](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table) ). So, unfortunately, you'd have to disable that and relocate to somewhere else on the main prompt line.

**Comment by dannyneira** [comment]
Opened an enhancement request with the starship team we can track here: https://github.com/starship/starship/issues/5100

**Comment by spadger** [comment]
![image](https://github.com/warpdotdev/Warp/assets/216748/7db8ab67-7824-41c1-b21b-eaf143290650)
🥳

**Comment by Advait-M** [comment]
@spadger wanted to circle back here - could you confirm that the rprompt works now? Warp supports right-sided prompts as of June 20, 2023! See https://docs.warp.dev/features/prompt#multi-line-and-right-sided-prompts for the docs on this.

Closing this out for now, but feel free to re-open if there's other asks/issues here!
