### ISSUE TITLE
' ~ ➜ ' is pre-filled after every command

### ISSUE THREAD

**Issue by naveen-bharathi** [warpdotdev/Warp#2926]
### Describe the bug

```zsh
~
➜
```
the above text is pre-filled in a new terminal session or after every command I run

### To Reproduce

Open a new terminal session and run any command

### Expected behavior

nothing to be pre-filled in a new terminal session or after every command run

### Screenshots

https://user-images.githubusercontent.com/32498535/231341003-63164b41-c46f-4093-9b65-299982975218.mov

### Operating System

MacOS

### OS Version

13.3 (22E252)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.04.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @naveen-bharathi ,

My guess is you may have a multi-line prompt which is not supported in Warp. https://docs.warp.dev/features/prompt#multi-line-and-right-sided-prompts

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here <
end
```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by naveen-bharathi** [comment]
I followed this solution from [https://docs.warp.dev/features/prompt#spaceship](https://docs.warp.dev/features/prompt#spaceship) and it fixed it.

**Comment by gaurangrshah** [comment]
> I followed this solution from https://docs.warp.dev/features/prompt#spaceship and it fixed it.

This is the way.
