### ISSUE TITLE
Warp > Settings... should open settings

### ISSUE THREAD

**Issue by redfood** [warpdotdev/Warp#2937]
### Describe the bug

`Warp > Settings...` has a submenu

When a user selects `Warp > Settings ...` standard Mac behavior would be to either (1) open settings, or (2) not allow the selection and have the menu remain visible.

Warp allows for the selection of `Warp > Settings...` but does nothing when the menu item is selected.

### To Reproduce

1. Open `Warp`
2. Click on the `Warp` menu
3. Click on `Settings...`

Alternatively:
1. Open `Warp`
2. Click and hold on the `Warp`
3. drag down to `Settings...`

### Expected behavior

Either  _Settings_ should open 
**Or** The menu should remain unselected and visible.

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.11.08.03.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
@redfood Thanks for letting us know.

We'll post any updates on this thread.
Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.
