### ISSUE TITLE
Window Burring documentation wording

### ISSUE THREAD

**Issue by redfood** [warpdotdev/Warp#2938]
### Describe the bug

The documentation for [window blurring](https://docs.warp.dev/appearance/opacity-blurring-dimming#window-blurring) says:
>After adding some Opacity ( moving the slider to a value less than 100)

This wording is incorrect and confusing.  Moving the slider to less than 100 is *removing* opacity and adding transparency.

### To Reproduce

N/A

### Expected behavior

N/A

### Screenshots

N/A

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.11.08.03.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @redfood  and helping to clear it up. We've changed the wording to reflect that opacity is being removed and that should be a more accurate reflection of the behavior of the slider.
