### ISSUE TITLE
Uncommitted changes are committed when running any command in warp

### ISSUE THREAD

**Issue by james2509** [warpdotdev/Warp#2940]
### Discord username (optional)

james2509

### Describe the bug

I updated to v0.2023.04.11.08.03 this morning. Whenever I run any command (ls, terraform apply, cargo build / test) then any saved change I have been committed to the repo with a weird commit message (in my case -23). It has taken me a while to track it down to warp and this behaviour does not happen in other terminals like iTerm. I done a test by uninstalling warp and installing an older version (v0.2023.01.17.08.03.stable_01) which makes the problem go away. 

### To Reproduce

1. Update to v0.2023.04.11.08.03 of Warp
2. Make a small change on your repo
3. Run a command in Warp. E.g. ls 
4. Do a git status which show changes have been committed but not pushed

### Expected behavior

Uncommitted changes should not be commited when running non-git related commands.

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2023.04.11.08.03 

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by charlespierce** [comment]
Hi @james2509, thanks for reporting this! As I'm working through debugging, is it possible you have an alias `comm` for something like `git commit -m`?

**Comment by dannyneira** [comment]
Thanks for taking the time to submit this @james2509. 

Closing as resolved since the issue was with the alias naming.

**Comment by dannyneira** [comment]
Thanks for taking the time to submit this @james2509. 

We're working on a fix for this so the `comm` alias shouldn't conflict in the future. We'll post updates on this thread.

**Comment by james2509** [comment]
Thanks @dannyneira and @charlespierce!!🙌

**Comment by dannyneira** [comment]
Hello folks! Good news, this issue has been resolved in the latest stable version of Warp `v0.2023.04.25.08.05.stable_00`. 

I will mark this as completed, but please don't hesitate to inform us if the problem persists. Thank you!
