### ISSUE TITLE
tab instead of right arrow key to select suggestions

### ISSUE THREAD

**Issue by elgs** [warpdotdev/Warp#2941]
### Describe the solution you'd like?

```text
Can you please make it so tab instead of right arrow key will select suggestions, thus I wouldn't have to move my right hand back and forth. Thank you!
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @elgs 

We have an issue tracking this here #1909 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
