### ISSUE TITLE
When I logged into the virtual machine using vagrant, I couldn't use the shortcut switch tab

### ISSUE THREAD

**Issue by GDdark** [warpdotdev/Warp#2946]
### Describe the bug

When I logged into the virtual machine using vagrant, I couldn't use the shortcut switch tab

![image](https://user-images.githubusercontent.com/15982894/232350929-d1b06151-875b-45fc-9e9b-f0e21eb992c5.png)

### To Reproduce

1. install vagrant
2. install virtual box
3. use vagrant ssh into virtual box

### Operating System

None

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @GDdark 

We'll post any updates on this thread.
Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by GDdark** [comment]
@dannyneira 
I found that I set the shortcut conflict caused, and I changed it after the normal.
