### ISSUE TITLE
keep in-active cursor

### ISSUE THREAD

**Issue by yvess** [warpdotdev/Warp#2947]
### Describe the solution you'd like?

When you move between different panes, there shouldn't be a content jump, because of the cursor. The jumping is very disruptive. 

Please and an option to keep the cursor in an inactive pane in an inactive state (grey?).
This with #699 would make an awesome experience.

I added some example videos between wrap and iTerm

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

### Wrap
https://user-images.githubusercontent.com/178436/232433068-b8514b01-d878-4a9f-8cac-ecf2bd6515a0.mov

### iTerm 
https://user-images.githubusercontent.com/178436/232433121-734746c2-4806-4ba4-a876-45de67c25709.mov

**Comment by yvess** [comment]
@dannyneira 
Thanks for the suggestion with the dimming pane, tried that but also found it takes me out of the terminal flow.
Cool to see that #409 is on the way, this could perhaps also fix it.

**Comment by suranyami** [comment]
I second this but the biggest problem for me is the text-cursor losing focus from the original pane. This seems to happen even if only one pane is open… it seems to focus on the "block" that the mouse-cursor is currently hovering over.

This is behaviour that I *never* want. An option to just keep the text-cursor focussed on the current text-entry line unless an actual mouse-click on an other pane occurs is (strangely) needed for this.

Am I missing something fundamental about the way Warp works? I honestly can't see why anyone would constantly want their text-cursor disappearing, disabling text entry. Have I somehow borked my setup and this *isn't* normal behaviour?

Can someone confirm whether this should be happening or not? It's becoming such a constant nuisance I'm tempted to revert back to iTerm.

If it's a feature, why?

**Comment by dannyneira** [comment]
Thanks for your patience folks! As requested, in Warp version `v0.2023.09.19.08.04.stable_00` and above, the input editor remains visible in inactive panes when using split panes. 

![CleanShot 2023-09-21 at 13 34 04](https://github.com/warpdotdev/Warp/assets/16809145/5b27a944-5add-4296-9166-1e502f70fab7)

Closing as completed, but please let us know if any issues.
