### ISSUE TITLE
Input Editor: Repeated first keypress when returning focus to Warp on macOS

### ISSUE THREAD

**Issue by anicholson-sq** [warpdotdev/Warp#295]
### Describe the bug

```shell
Frequently when returning to Warp from another app (say Slack or Chrome) after a period of inactivity, the first keystroke is repeated. Switching away and back quickly via Command-Tab quickly does not appear to trigger this issue for me.

Warp version: v0.2021.10.19.21.38.stable_02
```

### To Reproduce

1. Have Warp open on your machine.
2. Command-Tab away from Warp
3. After a $PERIOD of time (don't have data on this yet, sorry!), Command-Tab back to Warp.
4. Type a command (in my experiences, `cd` & `git` at the very least.
5. Notice that first character in typed command is present twice.

### Expected behaviour

```shell
I expect the command to be entered exactly as I typed it.
```

### Operating System

MacOS

### OS Version

11.6

### Additional context

```shell
Each time it's occurred, I assumed I'd merely double-pressed, so I tried holding down the key instead, and got macOS's context-menu for accents instead.

I haven't yet attempted to run the command to see if the character is *really* present in the command string, or if the glyph is a phantom. I'll see what I can figure out.
```

**Comment by zheng** [comment]
Huh, I just repro'd this. Thanks for the report. We will look into it!

**Comment by CivelXu** [comment]
<img width="585" alt="image" src="https://github.com/warpdotdev/Warp/assets/19768199/17f33370-93ed-4ac8-a165-ff13631942c6">


I faced same issue， version v0.2024.01.09.08.02.stable_02

**Comment by elviskahoro** [comment]
@CivelXu based on the coloring of the text, it's likely that there's a plugin you have installed that Warp isn't compatible with, maybe ZSH Syntax Highlighting
