### ISSUE TITLE
Should be copyable prompts entered into Warp AI

### ISSUE THREAD

**Issue by kotaesaki** [warpdotdev/Warp#2952]
### Describe the solution you'd like?

```text
Allow text selection and copying.
```

### Is your feature request related to a problem? Please describe.

```text
It is related to the following.
https://github.com/warpdotdev/Warp/issues/2553

If a prompt is sent in the middle of a prompt, it is currently retyped again.
Since I am a Japanese speaker, I often have to send the message in the middle of the keyboarding process.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by kotaesaki** [comment]
@dannyneira 
Thanks for the reply!
There are many request errors on the GPT side, etc., so it would be very helpful if you could implement this!
I would like to operate in the manner you have presented for the time being.

**Comment by dannyneira** [comment]
hey folks, since we already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2553 we'll be closing this as a duplicate.

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/2553

**Comment by dannyneira** [comment]
Hi Folks, this option is available in Warps [Agent Mode](https://docs.warp.dev/features/warp-ai/agent-mode), you can copy any prompt provided to the LLM.


https://github.com/user-attachments/assets/abd284ed-6fa4-43f8-9f86-38c7d8a50848

Closing as resolved!
