### ISSUE TITLE
Different color background per tab and pane

### ISSUE THREAD

**Issue by zethon** [warpdotdev/Warp#2955]
### Describe the solution you'd like?

```text
With iTerm I'm able to create tabs of different colors/styles in the same window. This helps when switching between tabs being able to tell what each one is. For example, I can have a local shell be a black background, but open up an ssh session in a green background. I would love to see this in Warp, in addition to being able to colorize on a per-pane level as well.
```

### Is your feature request related to a problem? Please describe.

```text
When multiple tabs/panes are open, it can sometimes be difficult to tell them apart.
```

### How important is this feature to you?

3 (Important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @zethon 

We have an issue tracking this here #478 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
