### ISSUE TITLE
lazyvim cannot recognize keyboard shortcuts like "alt+enter" & "shift+tab"

### ISSUE THREAD

**Issue by Saafo** [warpdotdev/Warp#2957]
### Discord username (optional)

Saafo#9108

### Describe the bug

* When edit commit msg in lazyvim, it's expected to use "alt+enter" to start a new line in commit message input. However, "alt+enter" cannot be recognized in Warp, while it's ok in iTerm.
* I've opened `Option key is Meta` in Warp.

### To Reproduce

1. Install [lazygit](https://github.com/jesseduffield/lazygit)
2. open lazygit in a git repo with local changes and press "c" for commit message input
3. You'll see `alt+enter: new line` in the bottom area, and you press `option+enter`, but it will input `nter` in the input.

### Expected behavior

start a new line

### Screenshots

<img width="170" alt="image" src="https://user-images.githubusercontent.com/46736350/233272390-c5f4cb26-e134-4113-a3fc-a8e13bbd8826.png">

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.11.08.03.stable_00

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by Saafo** [comment]
It's really annoying and prevent me from normally inputing commit message

**Comment by dannyneira** [comment]
Thanks for letting us know @Saafo 
I was able to reproduce this issue, sorry about the blocker. We'll post any updates on this thread.

Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

As a possible workaround, you can input the commit message with the normal method of `git commit -m "<your message>"`

**Comment by Saafo** [comment]
Another problem is that shift+tab (go to prev section) also does not work in lazygit in Warp, which works well in iTerm.

**Comment by dannyneira** [comment]
Heard, it seems like some keyboard shortcuts aren't being properly sent to `lazygit` so others may not work as intended as well.

**Comment by Saafo** [comment]
Seems already fixed in the latest version!
