### ISSUE TITLE
Add option to minimize block

### ISSUE THREAD

**Issue by lappazos** [warpdotdev/Warp#2959]
### Discord username (optional)

lappazos

### Describe the solution you'd like?

```text
Add option to minimize block
```

### Is your feature request related to a problem? Please describe.

```text
long junk runs are getting in the way to search previous runs
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @lappazos 

We have an issue tracking this here https://github.com/warpdotdev/Warp/issues/23
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Please see other related issues here:
https://github.com/warpdotdev/Warp/issues/516
https://github.com/warpdotdev/Warp/issues/194

Closing as duplicate.
