### ISSUE TITLE
New tab crashes after typing diacritics

### ISSUE THREAD

**Issue by ruza-net** [warpdotdev/warp#296]
### Describe the bug

```shell
Suppose I navigate into a path which contains diacritics.

Anytime after that command is submitted, opening a new tab (with shortcut or the button) quits Warp (without a crash report).

Note that opening a new window is possible, and opening a new tab on that window (while the 1st window is still open) is also without problem.
```

### To Reproduce

Steps to reproduce:
1. `cd path` where `path` contains diacritics
2. optionally open any number of other windows
3. open a new tab on the **original** window (with a keystroke or by pressing the "+" button)
4. Warp quits (all the windows close)

### Expected behaviour

```shell
A new tab is open and Warp remains running.
```

### Operating System

MacOS

### OS Version

11.3.1

**Comment by gagata** [comment]
hey @ruza-net we've fixed part of the issue (no more crashes!), the other part (diacritics in the prompt) is in progress :)

**Comment by ruza-net** [comment]
@gagata I can confirm, no more crashes indeed :)
