### ISSUE TITLE
High memory usage with Warp on macOS

### ISSUE THREAD

**Issue by YingkaiSun** [warpdotdev/Warp#2964]
### Describe the bug

Hello,

I am experiencing an issue with unusually high memory usage when running R scripts using Warp on my macOS system. The memory usage distribution is as follows:

Warp: 113.25 GB
R: 19.98 GB
Safari browser: 1.79 GB
WindowServer: 1.46 GB
R: 1.31 GB

<img width="269" alt="CleanShot 2023-04-21 at 12 37 22@2x" src="https://user-images.githubusercontent.com/125189174/233541825-4c5e0bdb-3e4f-435f-af08-27a148e5e96a.png">

Under normal circumstances, I would expect Warp, as a terminal emulator, to consume a relatively small amount of memory. However, in my case, Warp is using an excessive amount of memory, which seems abnormal.

I have tried closing unnecessary processes, checking my R scripts for memory leaks or unnecessary memory usage, and restarting Warp. However, the issue persists. I would appreciate any guidance or suggestions on how to resolve this problem.

My system specifications are as follows:

Device: MacBook Pro M2 Max
OS: [Ventura version 13.3.1]
Thank you for your assistance.

Best regards,
Sun Yingkai 

### To Reproduce

1

### Operating System

None

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @YingkaiSun 
We're tracking this issue here #2611 
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.

Closing as duplicate.

**Comment by YingkaiSun** [comment]
> Thanks for letting us know @YingkaiSun
> We're tracking this issue here #2611
> Please 👍 and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.
> Closing as duplicate.


I sincerely apologize for only seeing and responding to this message now. I haven't logged into GitHub recently, which caused this delayed response, and I deeply regret that.

I've been a regular user of Warp, and I'm happy to report that I haven't encountered the mentioned issue recently. It's clear that your hard work on addressing this problem under #2611 has paid off.

Moreover, I would like to extend my heartfelt gratitude for developing such an effective and user-friendly software. Your effort and dedication significantly contribute to making our tasks smoother and our experiences better.

Thank you once again for your help and my apologies for the delayed response.

Best regards,
Yingkai

**Comment by garydgregory** [comment]
When I start warp, it sucks up 833 MB GB of RAM! When I start iTerm 2 it sips 157 MB. Please fix... surely there's a better way.

<img width="991" alt="image" src="https://github.com/warpdotdev/Warp/assets/1187639/c7c19b72-3e33-4e9f-9c7e-3d941a7288d9">

**Comment by dannyneira** [comment]
Hey @garydgregory thanks for letting us know, we're tracking this issue here https://github.com/warpdotdev/Warp/issues/2611..I'll report your comment there.

**Comment by mikelgmh** [comment]
Linux user here. ExtratermQT (Electron based terminal) is using **232mb** with 5 terminals open. On the other hand, Warp is using **458mb** with 4 terminals open.

Warp is using almost the double of RAM with 1 less terminal instance!


![image](https://github.com/warpdotdev/Warp/assets/17798459/ee3d0047-4a49-493b-99ad-e5186d1681a7)
