### ISSUE TITLE
Gradle Build Scan not displayed in Warp Terminal after executing task

### ISSUE THREAD

**Issue by ch3e3rs** [warpdotdev/Warp#2966]
### Describe the bug

The Gradle task completes without any issues; however, the build scan is only briefly visible (for a few milliseconds) in the Warp Terminal and does not remain displayed.

### To Reproduce

1. Open Warp Terminal.
2. Navigate to the project directory containing the Gradle build file.
3. Execute a Gradle task using the command `./gradlew <task-name> --scan`

### Expected behavior

After executing the Gradle task with the --scan flag, a build scan should be generated and displayed in the Warp Terminal, showing the details of the executed task.

### Screenshots

Actual: Warp used
![warp-actual](https://user-images.githubusercontent.com/88769235/233640174-9c3863d4-f642-4492-be69-217095dc599d.png)

Expected: ITerm used
![expected-iterm](https://user-images.githubusercontent.com/88769235/233640306-39363707-46e7-42a1-89c5-6b4ec36286d2.png)

### Operating System

MacOS

### OS Version

Ventura 13.3

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2023.04.11.08.03.stable_00

### Additional context

I am interested in utilizing Warp for Java development, but this particular issue acts as a significant obstacle for me. As a result, I have been unable to fully transition from iTerm to Warp.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by PatriceManser** [comment]
+1

**Comment by dannyneira** [comment]
Thanks for letting us know @ch3e3rs 
Is it possible to provide a sample Gradle build file we can use to reproduce the issue? 

We'll post any updates on this thread.
Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by ch3e3rs** [comment]
Hi there, the issue should be solved now.

**Comment by dannyneira** [comment]
Hi all! this has been resolved in the most recent version of Warp. Please update and let us know.
