### ISSUE TITLE
Problem opening terminal from PhpStorm

### ISSUE THREAD

**Issue by Hernanarica** [warpdotdev/Warp#2970]
### Describe the bug

In PhpStorm I have the option to choose which terminal to open, when I choose warp terminal, although it opens, it opens a duplicate so I always have to close a window.

<img width="1352" alt="Captura de pantalla 2023-04-22 a las 11 28 55" src="https://user-images.githubusercontent.com/44417976/233790734-b7882158-0c8a-41f0-a022-85136b64b025.png">
<img width="1318" alt="Captura de pantalla 2023-04-22 a las 11 29 37" src="https://user-images.githubusercontent.com/44417976/233790756-84d79c60-eaa0-49a8-8001-fea9cca571f6.png">

### To Reproduce

Choosing as warp terminal in phpStorm

### Screenshots

<img width="1352" alt="Captura de pantalla 2023-04-22 a las 11 28 55" src="https://user-images.githubusercontent.com/44417976/233790765-61494b9f-b785-40d7-82e8-686bddba5dac.png">
<img width="1318" alt="Captura de pantalla 2023-04-22 a las 11 29 37" src="https://user-images.githubusercontent.com/44417976/233790766-bdaf6f75-5069-4e04-8c40-79a1d3490425.png">

### Operating System

MacOS

### OS Version

ventura 13.3.1

### Warp Version

v0.2023.04.11.08.03.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @Hernanarica We do have some light integrations with Jetbrains IDE's https://docs.warp.dev/features/integrations-and-plugins#jetbrains-ides

In general, it's a known issue that when Warp is opened from scratch, via any means, it typically opens 1 window for its initial launch and others along with it depending on how you opened it ( via script, launch configuration in Raycast, etc. )

**Comment by Hernanarica** [comment]
Unfortunately I still have the same problem... I attach video

**Comment by dannyneira** [comment]
hey Folks, closing as resolved. In the most recent version of Warp you can now configure other Jetbrains IDEs like phpstorm, webstorm, goland, etc. as default! https://docs.warp.dev/getting-started/changelog#2023.08.10-v0.2023.08.08.08.04
