### ISSUE TITLE
Warp crash every time i try to using `ssh -vvv hostxx`

### ISSUE THREAD

**Issue by benny1213** [warpdotdev/Warp#2972]
### Discord username (optional)
antilochus

### Describe the bug

ssh to hostxxx using `ssh -vvv hostxxx` and wrap stop responding.

### To Reproduce

ssh to hostxxx using `ssh -vvv hostxxx`

### Expected behavior

no crash

### Screenshots

<img width="1636" alt="image" src="https://user-images.githubusercontent.com/31154512/233823599-eef76176-b36c-4ec2-b02b-9a078ec483d3.png">

### Operating System

mac OS

### OS Version

mac OS Ventura 13.1(22c65)

### Shell Version

zsh 5.8 (x86_64-apple-darwin20.1.0)

### Warp Version

v0.2023.04.11.08.03.stable_00

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this only happen in Warp

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for opening @benny1213 

There is a known issue we're tracking here #2598 

In general, we're working to improve ssh connections in the near future. and we'll post updates on the issue above.

Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.

Closing as duplicate.
