### ISSUE TITLE
Ligatures not in output

### ISSUE THREAD

**Issue by xip-niekneuij** [warpdotdev/Warp#2977]
### Describe the solution you'd like?

```text
I would like ligatures to be present in the output, not just in the input.

Ligatures working in input:
https://files.catbox.moe/o44i92.png

Not displaying in output:
https://files.catbox.moe/hkt4jn.png
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for letting us know @xip-niekneuij ! 

We're tracking this issue here #239 
Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
