### ISSUE TITLE
Activate Next/Previous Tab does't work with long running command like `tail -f file.txt` or subshell

### ISSUE THREAD

**Issue by svsool** [warpdotdev/Warp#2978]
### Describe the bug

Activate Next/Previous Tab does't work with a long running command like `tail -f file.txt` or subshell.

Tried also to release focus from a tab window using escape, but doesn't seem to help.

Alt + 1/2/3 works as expected.

Arrows tabbing works in iTerm2 as expected.

### To Reproduce

Run `touch file.txt && tail -f file.txt`, and try to use `cmd + →` or `cmd + ←`, it won't switch between tabs.

### Expected behavior

Shortcuts work and tab change.

### Operating System

MacOS

### OS Version

13.3

### Shell Version

5.1.16(1)-release (aarch64-apple-darwin21.1.0)

### Warp Version

v0.2023.04.11.08.03.stable_00

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @svsool Thanks for submitting, in Warp the default key binds for activating previous/next tabs are `SHIFT-CMD-{ / SHIFT-CMD-}`. See more on this here: https://docs.warp.dev/features/windows/tabs

If you could please change those to `CMD-LEFT/RIGHT` in Settings > Keyboard Shortcuts, keep in mind those default to HOME / END for navigating the cursor in the input editor. See here: https://docs.warp.dev/features/keyboard-shortcuts

Then let us know if you're still having the same issue as described above once you get the new key binds in place while tailing or in REPLs (subshells).

**Comment by svsool** [comment]
Alright used to do it with the arrows across my setup IDEs, Terminal, Chrome and so forth, but seems like it collides with the cursor commands in Warp, in iTerm2 it's able to recognize different contexts when shortcuts are used and allows to switch across tabs and work with the text using same shortcuts.

I think I can fallback to `{` + `}` for now.

Would be good if contexts can be also considered in the future, so context would matter for shortcuts as well.

Thanks!
