### ISSUE TITLE
Moved to #500: Option-arrow keys don't work for navigating words

### ISSUE THREAD

**Issue by saket** [warpdotdev/Warp#298]
### Describe the bug

Hey folks, I'm not sure why but I'm unable to navigate between words using option-arrow keys. I checked that it's a [supported shortcut](https://docs.warp.dev/features/keyboard-shortcuts#input-editor-shortcuts) so I'm not sure why is it not working for me. How can I help you debug this?

### Operating System

MacOS

### OS Version

11.6

### Additional context

FWIW I'm running Warp on an M1 MacBook.

**Comment by saket** [comment]
Hey Alok, they're both disabled on my side.

<img width="282" alt="Screen Shot 2021-10-24 at 8 44 54 PM" src="https://user-images.githubusercontent.com/2387680/138619627-a19521ab-665b-428a-b803-881187594179.png">

**Comment by none-da** [comment]
I am on 2015 Macbook Pro, running latest warp (v0.2021.11.09.19.46.stable_01) and "Left option key is Meta" is enabled, still "option+left/right arrows" are not working as expected.

**Comment by elviskahoro** [comment]
@none-da @saket Is this still happening to the both of you?

**Comment by elviskahoro** [comment]
Moving this to our keybindings discussion:
- https://github.com/warpdotdev/Warp/discussions/500

**Comment by elviskahoro** [comment]
@none-da @saket 

Moving this to our keybindings discussion:
- https://github.com/warpdotdev/Warp/discussions/500
