### ISSUE TITLE
Multiple keyboard shortcut for a Warp command

### ISSUE THREAD

**Issue by MatteoGauthier** [warpdotdev/Warp#2982]
### Describe the solution you'd like?

```text
Like VSCODE, multiple shorcuts can be assigned to a single action.

I want to map both `control + space` and `TAB` as Open Completions Menu
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @

We have an issue tracking this here #1909, this is a popular request and you can track any updates on that thread.

Please :+1: and subscribe to that request as it helps us gauge interest.

Closing as duplicate.
