### ISSUE TITLE
Support Zed as a default code editor

### ISSUE THREAD

**Issue by dannyneira** [warpdotdev/Warp#2983]
### Discord username (optional)

Danny N#2929

### Describe the solution you'd like?

```text
Include Zed, www.zed.dev, as an option in Settings > Features > General > "Choose and editor to open file links"
```

### Is your feature request related to a problem? Please describe.

```text
This editor is growing in usage and functionality, and becoming a daily driver for many developers so it would be cool to include it on the list of options.
```

### Additional context

![CleanShot 2023-04-25 at 12 44 21](https://user-images.githubusercontent.com/16809145/234372618-b6eb9771-755b-4d79-8165-2f5b3d84ec44.png)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
If you'd like to see this feature in Warp, please :+1:  and subscribe to this request as it helps us gauge interest.

**Comment by MaanavKhaitan** [comment]
We just added support for Zed as a default code editor, it should be fixed soon.

**Comment by serco-chen** [comment]
I have installed zed cli and set Zed as the default code editor in Warp. However when I cmd+click on a certain file in warp, nothing happens. Wonder if it is a bug or any extra configuration needs to be done.

**Comment by serco-chen** [comment]
@MaanavKhaitan I can open files by cmd+click when I run `ls`. However when I run `tsc` or other commands, those file links cannot be opened with Zed, which works fine when I use Sublime Text as the default editor.

**Comment by MaanavKhaitan** [comment]
I'm sorry I'm not able to replicate the error on my machine. I'm trying to open a file in Zed after running a `tsc` command, and it works fine. Could you maybe send us the exact command you're using that doesn't work, so we can replicate the issue?

https://github.com/warpdotdev/Warp/assets/22297592/28e41ea4-2fdd-497d-80b6-0009f7abf7b9

**Comment by dannyneira** [comment]
Try reinstalling Zed to see if that helps, or make sure it's updated and you're registered in the app.

**Comment by serco-chen** [comment]
@MaanavKhaitan Run the exam command `npx tsc --listFiles --noEmit`.

I can open all the files list above with Zed. If there are some errors, the terminal gives info like:
```
Found 1 error in src/App.tsx:9
```

`src/App.tsx` this is the link that I can open with Sublime Text but not with Zed.

**Comment by serco-chen** [comment]
@MaanavKhaitan @dannyneira No luck after reinstalling Zed.

Here's a recording video of the issue. Please note that I cannot open `nuxt.config.ts` with Zed at last.

https://github.com/warpdotdev/Warp/assets/1681147/e12349ba-12aa-43e4-bd3f-f4fec72757b9

**Comment by dannyneira** [comment]
Thanks for letting us know @serco-chen It does show up as a link since my guess is it matches the "pattern" of a file, but since the path isn't complete and it includes the `:4` at the end it's the reason for the failure to open in zed.

I'll let the team know about this issue, but to set realistic expectations, I'm not sure it will get fixed in the short term, so I recommend you use a command like `zed /path/to/file.txt` to open the file instead as a stopgap.
