### ISSUE TITLE
Buffer Input Commands while connecting to remote SSH terminal

### ISSUE THREAD

**Issue by mackermedia** [warpdotdev/Warp#2987]
### Describe the solution you'd like?

```text
I'm able to type multiple commands separated by the Enter key, and they "buffer" (execute sequentially when the previous command completes/exits) when on my local terminal.

When I SSH to a remote server, there is a moderate delay while connecting. With my previous terminals (iTerm, etc.) I was able to type commands while the SSH connection was being established and use the "buffer" capability there.

However, this does not appear to work with Warp. Commands are not executed on the remote server / SSH environment and the buffer is lost.
```

### Is your feature request related to a problem? Please describe.

```text
This frustrates me as it slows me down.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by nus-rick** [comment]
Please make a buffer, please 🙏

**Comment by dthinhle** [comment]
Warp is awesome but because my workflow using ssh a lot this is a dealbreaker feature for me. Will stick to iterm until this implemented.

**Comment by dannyneira** [comment]
Hey folks, sorry about this blocker. We do have some SSH improvements on our roadmap so appreciate your patience.

As a possible workaround you can add `command ssh` to your `Settings > Subshells > Added commands` menu, then run `command ssh <user@server>` to connect to remote session, this will attempt to enable Warp features as a subshell.

You can also try disabling the SSH Wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabling, SSH should work as normal.

Related docs:
[https://docs.warp.dev/features/ssh](https://docs.warp.dev/features/ssh#ssh-wrapper-fails)
https://docs.warp.dev/features/subshells

If those don't work, please let us know.

**Comment by mackermedia** [comment]
It seems like you guys fixed this? It's been working lately. Thank you! 🙏

**Comment by mackermedia** [comment]
It seems like you guys fixed this? It's been working lately. Thank you! 🙏
