### ISSUE TITLE
ssh stuck with a lot of debug log

### ISSUE THREAD

**Issue by Pger-Y** [warpdotdev/Warp#2991]
### Operating System

MacOS

### Operating System and Version

13.1

### Local Shell Version

5.2.15(1)-release

### Remote Shell Version

5.1.16(1)-release

### Warp Version

v0.2023.04.11.08.03.stable_00

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

![image](https://user-images.githubusercontent.com/4125972/234753311-4047586e-5433-4a86-be77-40cebb7fcd2d.png)

### Include shell xtrace output

![image](https://user-images.githubusercontent.com/4125972/234753564-7d03275b-ba58-4bc9-bd4b-e0a570c1aa7f.png)

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @Pger-Y Thanks for submitting, this is a known issue with ssh log-level debug. 

Please see the following issue for more details. https://github.com/warpdotdev/Warp/issues/2793
The workaround is to disable log level debug in the ssh config and it should stop printing the text into the input.

We also have another related issue with `ssh -v` here: https://github.com/warpdotdev/Warp/issues/2598

Closing as duplicate.
