### ISSUE TITLE
Vue create CLI cut off by command bar

### ISSUE THREAD

**Issue by trylaarsdam** [warpdotdev/Warp#2996]
### Describe the bug

The bar at the top of the terminal which shows which command is currently running will overlap with the Vue CLI create menus. Scrolling up fixes the issue, but then every time you make a selection you need to scroll back up again to see all the options.

### To Reproduce

* Install the `vue` CLI through `npx`
* Run `vue create [project name]`
* The preset selection screen will appear cut off by the currently running command bar

### Expected behavior

The entire Vue create menu should appear below the command bar, not behind it.

### Screenshots

In warp:
<img width="558" alt="Screenshot 2023-04-29 at 2 21 28 PM" src="https://user-images.githubusercontent.com/50586094/235324743-7f8a662e-158e-4bb1-bad4-b35dbadf3f67.png">
In iTerm2:
<img width="491" alt="Screenshot 2023-04-29 at 2 23 02 PM" src="https://user-images.githubusercontent.com/50586094/235324802-926e2b45-5880-48c4-8f32-a5cb99986d48.png">

### Operating System

MacOS

### Operating System and Version

MacOS 13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.04.08.03.stable_01

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @trylaarsdam We're tracking this issue here #2915

You can disable the "Sticky Command Header" in the Settings > Features menu as a workaround.

Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.

Closing as duplicate.
