### ISSUE TITLE
suggestion list stays open when opening setting using cmd+comma

### ISSUE THREAD

**Issue by thoughtlessmind** [warpdotdev/Warp#2997]
### Discord username (optional)

Rajiv#0825

### Describe the bug

while entering the command, the suggestion/completion menu opens, and if the settings page is opened using `cmd + ,` then that completion menu stays open. That completion menu stays open and closes only when clicked on that list.

### To Reproduce

- open the completion suggestion menu using the up arrow key while entering a command
- Click `cmd` + `,`

### Expected behavior

the suggestion menu should have been closed when opening settings page

### Screenshots

<img width="948" alt="image" src="https://user-images.githubusercontent.com/51883613/235344522-bc2708d4-e0c1-47d3-86de-9d7740ef876d.png">

### Operating System

MacOS

### Operating System and Version

Ventura 13.3

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.25.08.05.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @thoughtlessmind 

We're tracking this issue over at #2792 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 
There is no workaround at the moment other than to close the Command Search modal before you enter the settings menu.

We'll be closing this as a duplicate.

**Comment by thoughtlessmind** [comment]
thanks @dannyneira
