### ISSUE TITLE
Application Font size a little too smol

### ISSUE THREAD

**Issue by jk779** [warpdotdev/Warp#3001]
### Describe the bug

I know that its possible to change the font size for the terminal itself, wich works (except pressing TAB to go to the next field and inserting a tab, but i digress :D)

But the UI seems font-sized to be a little bit "tiny", Please compare the screenshots. I've not modified the other programs to look "larger" or something:

![Bildschirmfoto 2023-04-30 um 21 41 53](https://user-images.githubusercontent.com/1104528/235373236-184ce34d-aecf-4753-a2d4-0bbeae82d136.png)

![Bildschirmfoto 2023-04-30 um 21 41 03](https://user-images.githubusercontent.com/1104528/235373237-3f9dc009-b0de-4507-83c7-02807aa75ef0.png)

I've glasses and notice that i have to lean towards the monitor when i want to change a setting. Look how i'd like font for to be: (in the actual terminal. vs the context menu size. Maybe I'm not the only one? If it is, i think i have to get new glasses ;)

![Bildschirmfoto 2023-04-30 um 21 49 14](https://user-images.githubusercontent.com/1104528/235373376-6e65163e-7d62-45d6-8aea-6e3a339b6050.png)

Using a 2560x1440 external screen from dell. Same on the macbook m1 pro max 14" retina display, Ventura.

I Love your product! Its looks nice and has great features! I especially love the gradient tab underlines/buttons, i'm just a such a guy 🙈 (recommending Synthwave 85!)

Best of luck,
Michael

### To Reproduce

Open warp and be a little bit blind ;)

### Expected behavior

Maybe make the Interface-Fnot the same as the system font size, if something like this exists. otherwise, maybe make it an advanced feature to change the interface size :)

### Operating System

MacOS

### Operating System and Version

MacOS 13.3.1 Ventura

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.25.08.05.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this awesome request @jk77! sorry about the smol text, hope it's not too much of a blocker 🤞 

We already have a request tracking this over at #1443
If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by jk77** [comment]
@dannyneira Thanks for your awesome reply!  However, I think you meant to send it to @jk779 instead of @jk77.  We'll be routing this reply to the circular file.
