### ISSUE TITLE
Clicking the Menu entry Warp → Settings, instead of Warp → Settings → Settings closes the menu and nothing happens

### ISSUE THREAD

**Issue by jk779** [warpdotdev/Warp#3002]
### Describe the bug

Intuitively, I've clicked now dozends of times on the settings menu "button" on the first level of the Warp → Settings menu. I think, many people will do the same. It could be wise to not close the menu on this, or go straigt to the destination on Warp → Settings → Settings to not confuse users?

Best, Michael :)

### To Reproduce

Clicl on Warp in the MacOS menu and click on Settings

### Expected behavior

Not closing the context window at least, but doing nothing.

### Screenshots

![Apr-30-2023 22-19-48](https://user-images.githubusercontent.com/1104528/235374558-6757fa11-6544-4a7e-8bea-8cbf72d9511e.gif)

### Operating System

MacOS

### Operating System and Version

13.3.1 (22E261)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.25.08.05.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @jk779 
We'll post any updates on this thread. A possible workaround is to use a keybind to open the Settings menu, the default one is `CMD-,`.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by MaanavKhaitan** [comment]
Thanks for flagging this! We've fixed this issue, it should be released soon.
