### ISSUE TITLE
Unexpected loss of permission on macOS

### ISSUE THREAD

**Issue by markmbaum** [warpdotdev/Warp#3009]
### Describe the bug

I was in the process of fairly routine git activity and the Warp shell suddenly lost permission to access files and directories. A screenshot of the error message and failure to even run `ls` is below.

<img width="662" alt="Screenshot 2023-05-02 at 4 44 22 PM" src="https://user-images.githubusercontent.com/18745581/235781647-a395ad37-5a8c-4ba8-836f-0eafdbf6ad1f.png">

If I quit and restart, it works fine. 

Sometimes sudden permission loss happens in the middle of running a program (in this case Python scripts driving an executable), which makes it crash.

### To Reproduce

The last thing I did before the screenshot above was `git push --force` but sometimes the sudden permission loss happens in the middle of runnig a Python script.

### Expected behavior

The shell should keep running with normal permissions.

### Operating System

MacOS

### Operating System and Version

macOS 13.3.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.25.08.05.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @markmbaum Please see our guides on the [permissions](https://docs.warp.dev/features/notifications#troubleshooting-warp-notifications) and [updating warp](https://docs.warp.dev/help/updating-warp#auto-update-issues) issues that could be affecting your permissions. 

Let us know if those helped, if not, we will need a bit more information from you to reproduce this issue. most likely some [Logs](https://docs.warp.dev/help/sending-us-feedback#gathering-warp-logs).

**Comment by markmbaum** [comment]
Ok thanks for the pointer. I haven't noticed any issues updating Warp, so I'll look into the other troubleshooting.

**Comment by RobSchilderr** [comment]
Same issu here. How did you solve it?

**Comment by zain-mansuri** [comment]
Found any solution? Restarting wrap is the only thing I can find.

Running using sudo also won't work
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/db30dafc-9aca-4e70-9f43-7f51714c2960">

**Comment by jonasms** [comment]
I've also been getting this behavior. Over the fast 2 - 3 weeks.

**Comment by dannyneira** [comment]
Hey Folks, We're noticing reports of this issue returning recently. We suspect it may be related to auto-updates to Warp. We're going to reopen, investigate further, and post any updates on this thread.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by jordanwegener** [comment]
> Hey Folks, We're noticing reports of this issue returning recently. We suspect it may be related to auto-updates to Warp. We're going to reopen, investigate further, and post any updates on this thread. As a possible workaround/stopgap measure, please grant "old" Warp permission in [Mac > System Settings > Privacy & Security > Full Disk Access](https://github.com/warpdotdev/Warp/issues/5415).
> 
> ![image](https://private-user-images.githubusercontent.com/16809145/382122449-d421c5c4-e293-46d1-acf4-81b40b792540.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MTM5MDYsIm5iZiI6MTczMDQxMzYwNiwicGF0aCI6Ii8xNjgwOTE0NS8zODIxMjI0NDktZDQyMWM1YzQtZTI5My00NmQxLWFjZjQtODFiNDBiNzkyNTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDIyMjY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYWZhYjQzOTAzZWM1Yzc3YmZkNmVmNDkyYTljMjJlODUxOWQ1OWFjODIwYjdjZWFhODExMjQ5OTI1MThkYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xBn_x2njuRg5mOGX_ALDie1BmYRVl6EUm6CGXU6a5Pw)
> 
> To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

Confirming I have been experiencing this and granting permissions to 'old' seems to have been the fix for me.

**Comment by razanfawwaz** [comment]
> Hey Folks, We're noticing reports of this issue returning recently. We suspect it may be related to auto-updates to Warp. We're going to reopen, investigate further, and post any updates on this thread. As a possible workaround/stopgap measure, please grant "old" Warp permission in [Mac > System Settings > Privacy & Security > Full Disk Access](https://github.com/warpdotdev/Warp/issues/5415).
> 
> ![image](https://private-user-images.githubusercontent.com/16809145/382122449-d421c5c4-e293-46d1-acf4-81b40b792540.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDY5MzcsIm5iZiI6MTczMDQ0NjYzNywicGF0aCI6Ii8xNjgwOTE0NS8zODIxMjI0NDktZDQyMWM1YzQtZTI5My00NmQxLWFjZjQtODFiNDBiNzkyNTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA3MzcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YTViN2YxMTgzYjFhYTFhOGRjZDRkMWQ0NTYzNjU1OTVhZTAyMmEyODJkNzVkZTZhY2YwYWI1Y2EwMmExNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dStdxmExtWaXL_oU3MJj411TSCsGvtgJI12lwq7WxYw)
> 
> To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

how if in my devices there's no "old"?

**Comment by mark-jordanovic-lewis** [comment]
Adding to this thread as #5417 was closed. I didn't think it was a duplicate as this issue was closed as completed in March 2023.

There is no "old" in my settings.

**Comment by dannyneira** [comment]
@mark-jordanovic-lewis when you see the issue, is there usually a pending update in Warp? We've noticed this only on MacOS and when there is a pending update, so just want to confirm.

**Comment by mark-jordanovic-lewis** [comment]
I can't really comment on that, there was an update today and it happened. I encountered it quite a few times before I posted previous issue but I'm not sure it corresponded with an update or not.

**Comment by dannyneira** [comment]
@robbiehobby Yup, this appears to happen after a pending Update in Warp and only on directories that require permissions (i.e. Documents, Downloads, Desktop, etc), even if you've granted Warp "Full Disk Access". If you manage to run commands on those directories while Warp is still Updating in the background, then the issue may not happen. We're actively working on a fix for this, which may cause the issue again for some users, but will make sure that it doesn't return in any future updates.

The best workaround for now is to apply any pending updates to Warp.

**Comment by dannyneira** [comment]
@mark-jordanovic-lewis Keep an eye out for this, We suspect it is related to updates with high certainty, but your issue may indeed be different. There will be a hotfix patch coming soon (which may cause the issue again ), but updating to the new version will hopefully ensure it doesn't return for next week's release (typically Thursdays). If that's not the case, please reopen https://github.com/warpdotdev/Warp/issues/5417 and let us know.

**Comment by VanWieren** [comment]
Same issue for me while saving local files on mac after updating to OS 15.

**Comment by jalopez** [comment]
In case it helps finding the root cause: I only started to face this issue after upgrading my MacOS version to Sequoia

**Comment by mark-jordanovic-lewis** [comment]
@dannyneira As requested (but cannot re-open issue #5434). On Thursday and Friday there was no loss of permissions in warp. Yesterday morning, Monday 11th Nov 2024, permissions to read directories in already open warp sessions have been lost. No changes in OS settings related to Full Disk access of the application.

brew upgrade did not find warp to upgrade. brew upgrade warp re-installed warp. Warp will no longer open.

brew remove warp brew install --cask warp. Warp will no longer open.

Which logs would you like me to dump to help with the investigation?

**Comment by dannyneira** [comment]
@mark-jordanovic-lewis Thanks for sharing the details. As far as I'm aware, the fix for this issue went out last weeks release. We're fairly confident it won't return in future releases, but please keep an eye out for this issue and let us know.

**Comment by mark-jordanovic-lewis** [comment]
@dannyneira good to know. I can't pin down what it was that was causing the problem, and I was annoyed at having to set up my config again - however the UI is intuitive and it was easy to get back up and running once I could sort of work out what was going on. 

Thanks for staying on this and replying. I will post if this happens again and the solution above does not fix things.

**Comment by dannyneira** [comment]
Hi Folks, this issue should be resolved in the latest release of Warp! Note that you may still see the issue if you're on an older build and updating to [v0.2024.11.12.08.02](https://docs.warp.dev/getting-started/changelog#id-2024.11.14-v0.2024.11.12.08.02) and beyond. Once you're on version [v0.2024.11.12.08.02](https://docs.warp.dev/getting-started/changelog#id-2024.11.14-v0.2024.11.12.08.02) or higher, the permission issue should not persist.

Please update and let us know if you continue seeing the issue in this week's Thursday release.

**Comment by dannyneira** [comment]
hey Folks, this fix has been out for a couple of weeks, closing as resolved, but please do ping and let us know if the issue persists.

**Comment by fletan** [comment]
Just got the issue. On latest release.

<img width="515" alt="image" src="https://github.com/user-attachments/assets/c76637b9-2151-4a22-ae00-78083446e4d5">

**Comment by steverb1** [comment]
I just installed Warp for the first time, and have this issue also.
I'm on v0.2024.12.10.15.55.stable_02
MacOS Sonoma 14.7.2

**Comment by dannyneira** [comment]
@fletan @steverb1 sorry to hear about this, what permission does Warp have in `System Settings > Privacy & Security > Files & Folders` or `Full Disk Access`?

**Comment by steverb1** [comment]
Well, it is working now.  I added Desktop Folder under Files and Folders.  Also upgraded to v0.2024.12.10.15.55.stable_04.
<img width="485" alt="warp" src="https://github.com/user-attachments/assets/2f8f6e1d-d9dc-450f-98d9-cf0729c2f0fc" />

**Comment by lstephensca** [comment]
I have also been having intermittent issues with permissions as of late that seem to result in `EINVAL` errors while running any pnpm command. I am on the latest osx version as well as the latest warp version.

**Comment by mtsprout** [comment]
This issue still persists on Tahoe 26.0.1, Warp v0.2025.09.24.08.11.stable_03. Closing and restarting Warp does not fix the issue.

**Comment by Brodan** [comment]
just started happening to me this week

**Comment by jfrogido** [comment]
I gave warp full disk access and it's still happening to me

**Comment by ifaakash** [comment]
> [@ifaakash](https://github.com/ifaakash), what permission does Warp have in Mac > System Settings > Privacy & Security > Files & Folders or Full Disk Access?

I basically had given all the permission ( full disk permission ) to Warp

**Comment by tejasavora** [comment]
I have same issue on McOS - Warp has full disk access, it is working fine and then all of a sudden it looses permissions. Latest Warp version.

**Comment by peetya** [comment]
I was able to fix it on Mac OSX by closing completely Warp, opening native Terminal and running the following command:

```
tccutil reset SystemPolicyAllFiles dev.warp.Warp-Stable
```

**Comment by bvincent** [comment]
Still present on version: v0.2026.07.22.09.01.stable_01

<img width="271" height="166" alt="Image" src="https://github.com/user-attachments/assets/7e13e07d-c7bc-46b3-82cc-aafb81286391" />

**Comment by yordis** [comment]
This is a repeated problem for me `v0.2026.07.15.08.55.stable_01` almost every time the background auto update happens or something around those lines, I lose access to the external SSD

**Comment by Komsomol** [comment]
Still happens on v0.2026.09.02.08.27.stable_01 with Full Disk Permissions.
