### ISSUE TITLE
Add time stamp for each execution block

### ISSUE THREAD

**Issue by adar-cohen-imagenai** [warpdotdev/Warp#3010]
### Describe the solution you'd like?

```text
I wish to not only see how much time each block took (in seconds), but also see the exact time I executed the command
```

### Is your feature request related to a problem? Please describe.

```text
no
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @adar-cohen-imagenai Thanks for taking the time to submit this. When you hover over the default prompt in previously run blocks, you will see a popup that shows the start and end times of the command. 

![CleanShot 2023-05-03 at 09 12 24](https://user-images.githubusercontent.com/16809145/235962555-31265369-99cc-4d21-b241-5f01781fa5e3.gif)

As a possible workaround, I recommend you try a [supported custom prompt](https://docs.warp.dev/features/prompt) like [Starship.rs](https://starship.rs/) , which has [options for showing runtime](https://starship.rs/config/#command-duration).

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by MatthiasHowellYopp** [comment]
the hover isn't working for me - hoving the when it was run would be very helpful whether in pop-up or as static info
Warp version v0.2023.07.04.08.03.stable_02
Ventura 13.4.1

**Comment by dannyneira** [comment]
Closing as completed.
