### ISSUE TITLE
Fish shell stuck at startup after updating Warp

### ISSUE THREAD

**Issue by osamaqarem** [warpdotdev/Warp#3012]
### Describe the bug

After updating from v0.2023.01.17.08.03.stable_01 to v0.2023.04.25.08.05.stable_00, my fish shell is stuck at startup. Fish shell is working fine on the native MacOS terminal. My workaround is to revert to the older version. But I can't block the update at the next warp restart.

### To Reproduce

- Use fish shell on MacOS
- Use Warp v0.2023.04.25.08.05.stable_00
- Start Warp. The fish shell is stuck at startup.

### Expected behavior

The fish shell should load as in v0.2023.01.17.08.03.stable_01

### Screenshots

<img width="500px" src="https://user-images.githubusercontent.com/24393922/235951441-83a307c8-a74e-4110-814a-a8c38796ee89.png">

### Operating System

MacOS

### Operating System and Version

MacOS 13.1

### Shell Version

fish, version 3.3.1

### Warp Version

v0.2023.04.25.08.05.stable_00

### Additional context

I saw users sharing similar screenshots of the same problem in a different issue after the same update. But it seems the main bug report is a different thing.

https://github.com/warpdotdev/Warp/issues/1869#issuecomment-1526842035

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @osamaqarem There is a known issue with fish version 3.4.0 and below that causes problems in Warp.
https://docs.warp.dev/help/known-issues#fish-shell-read-command

Please upgrade fish and let us know if the issue persists.

**Comment by osamaqarem** [comment]
hey, I upgraded to fish 3.6.1 and it no longer hangs on v0.2023.04.25.08.05.stable_00
thank you!

**Comment by albnorleku** [comment]
This is issue is still persisting for me, I have upgraded fish to 3.6.1 and warp is still stuck on "starting fish..."

**Comment by dannyneira** [comment]
Hey @albnorleku thanks for letting us know, if you can please look at our known issues, https://docs.warp.dev/help/known-issues there are some that pertain to fish, as well as tools warp, doesn't support at this time that may be causing this issue. If not, then please open a new issue and provide as many details as possible it will help us find the root cause (i.e. include your config.fish, versions, etc.).
