### ISSUE TITLE
Ability to change font size per window?

### ISSUE THREAD

**Issue by beatak** [warpdotdev/Warp#3013]
### Describe the solution you'd like?

```text
I use a terminal multiplexer, so I **usually** don't open multiple 
terminal windows. But when I do, it's when I present my terminal 
to the audience. So naturally, I increase the font size by `CMD +`. 
Then I realize my main terminal looks janky because it also 
increases the font size.
```

### Is your feature request related to a problem? Please describe.

```text
So I wish all temporary visual change is contextual, and the 
context to me is each window.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for letting us know @beatak 

We're tracking this issue over at #1394 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue.

We'll be closing this as a duplicate.
