### ISSUE TITLE
Dismiss strategy is annoying when using Alfred clipboard via shortcut.

### ISSUE THREAD

**Issue by yam-liu** [warpdotdev/Warp#3017]
### Describe the bug

The shortcut I use to open clipboard history with Alfred is Command+Option+C. 

I often use this feature to pick up something from the clip history and paste it as a command parameter in Warp. However, when I open the Alfred input text view, the Warp window disappears, making it impossible to paste anything. I’ve also tried using Raycast and Launchbar, but I think that for these apps, the Warp window should not dismiss when I open the Alfred input text view.

### To Reproduce

1. Alfred clipboard history, set a shortcut.
2. use the shortcut to open clipboard history with Warp as a front app.
3. Warp dismiss.

### Expected behavior

Warp appear

### Operating System

MacOS

### Operating System and Version

13.3.1 (a) 

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.25.08.05.stable_00

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @ooopscc I can't quite reproduce this issue, when I press CMD-OPT-C with Warp input in focus, using Raycast, I can copy items into the input.

Even using the [dedicated hotkey window](https://docs.warp.dev/features/windows/hotkey-window#hotkey-window), which defaults to hide on the loss of focus, Raycast doesn't seem to affect it and doesn't automatically hide the hotkey window. Please see my examples below:

Uploading CleanShot 2023-05-04 at 13.00.20.mp4…

Is it possible that you have some sort of window management app running in the background causing this behavior? Does the Warp window completely close or just move to the background? Could you please provide a video example of the issue?

**Comment by ooopscc** [comment]
After further investigation, I discovered that the issue may be related to having two monitors. When I open Alfred from the other monitor, the window disappears. 
Even when I switch back to the previous monitor, the window still disappears.
Iterm2 works fine.

I forgot to mention that I’m using a dedicated hotkey window that autohides when I lose keyboard focus, and I have two monitors with the lid closed.

**Comment by ooopscc** [comment]
https://user-images.githubusercontent.com/1056803/236392288-37d9a17a-8359-4852-bf76-4b639c419622.mp4

**Comment by dannyneira** [comment]
Oh I see @ooopscc , thanks for the extra context. It appears that "with the lid closed" is what triggers the issue along with setting the dedicated window to "Active". As a workaround, I recommend either the lid open with it set to "Active screen" or the lid closed with it set to "Main screen".

![CleanShot 2023-05-05 at 09 30 55](https://user-images.githubusercontent.com/16809145/236502593-5027904d-3042-44fc-aa88-b2caf47c5420.png)

**Comment by dannyneira** [comment]
Right, "Active Screen" is the one with the issues we've noticed, what is your dedicated hotkey window settings, "Main Screen"?

**Comment by dannyneira** [comment]
@ooopscc Any success with the instructions above? If not, i suspect it may have to do with the international keyboard shortcuts not being supported at this time #341.

**Comment by ooopscc** [comment]
Still not working. what is international keyboard shortcuts?

Danny Neira ***@***.***>于2023年5月27日 周六01:06写道：

**Comment by dannyneira** [comment]
Keyboard shortcuts used on international keyboards don't trigger properly, as per #341, so if you're using an international keyboard, this could be why the Global hotkey window isn't working as intended.

**Comment by dannyneira** [comment]
Closing as this appears to be part of #341, please follow that issue to receive updates on the keyboard issue.

**Comment by youtextme** [comment]
If clipboard history + light sync is the job: free Raycast’s clipboard history covers a lot of what people buy Paste/Clipy+/Maccy Pro for. Worth a dual-hotkey week before paying another clipboard sub.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
