### ISSUE TITLE
[macOS] option-i not working even with Left/Right Option key is Meta enabled

### ISSUE THREAD

**Issue by ddbrierton** [warpdotdev/Warp#3018]
### Describe the bug

On macOS 13.3.1 (a) after upgrading to v0.2023.05.02.08.03.stable_00 today option-i stopped working in NeoVim, even though it was working correctly immediately before.

In Settings > Features > Keys, Left and Right Option Key is Meta are both enabled.

In NeoVim + NvChad option-h toggles a horizontal terminal and option-v toggles a vertical menu. Both key combinations continue to work. However, option-i which toggles a floating terminal no longer works.

I _think_ that option-i is functioning as a dead key (the system default) for adding a circumflex accent, i.e. option-i, i enters î. Whatever it is doing seems to have an unfortunate effect on NeoVim as I shortly see an error message that Lua is out of memory.

To reiterate, this was working immediately before this release.

### To Reproduce

Run nvim (with NvChad config)

Type option-i

No floating terminal appears. Shortly thereafter nvim appears to start behaving strangely, with out of memory errors.

### Expected behavior

Floating nvterm appears

### Operating System

MacOS

### Operating System and Version

13.3.1 (a)

### Shell Version

zsh 5.9

### Warp Version

v0.2023.05.02.08.03.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
@ddbrierton Thanks for opening this. Gonna flag this intenrally as it smells like a possible regression!

**Comment by ddbrierton** [comment]
This appears to be resolved as of v0.2023.05.30.08.03.stable_02.

**Comment by ivanlee1999** [comment]
this bug still exist v0.2023.08.22.08.03.stable_00
option+h and option+v works fine
but not for option+i

**Comment by jakubdonovan** [comment]
I can confirm that meta i still doesn't work.
