### ISSUE TITLE
Alias expansion on Enter

### ISSUE THREAD

**Issue by that70schris** [warpdotdev/Warp#3024]
### Describe the solution you'd like?

```Text
currently the "Expand aliases as you type" feature works nicely with the spacebar, but does not work if you just press Enter.  Would be awesome if aliases could expand in both cases.
```

### Additional context

If this feature were implemented it would bring aliases into better parity with fish abbreviations and would take away one major reason for me to need to use fish

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! 

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by danielpeng2** [comment]
Expanding on enter is supported as of our latest release (v0.2023.05.18.01.08.stable_04)! Going to close this out, but feel free to comment if you have any issues related to this feature.

**Comment by that70schris** [comment]
brilliant!
