### ISSUE TITLE
consistently sized input editor when using split panes

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#303]
### Describe the solution you'd like?

```shell
Small pet peeve: when you have two split panes (split vertically), and you switch between panes, things start to move up/down because the text input appears/disappears in each pane. Personally would prefer if things would stay the same size.
```

### Is your feature request related to a problem? Please describe.

```shell
UIUX
Consistent Style
```

### Additional context

Discord - feature requests - 10/15/2021
https://discord.com/channels/851854972600451112/852249738002956311/898726062119321611

**Comment by dev4joel** [comment]
From Leech via Discord
https://discord.com/channels/851854972600451112/852249738002956311/974032702166671430
hi, is there a way to avoid the prompt height change?

**Comment by conradwt** [comment]
@warpdotdev-dx This issue is over 2+ years old.  Thus, demos are great but it would be even better if the code was actually pushed to a production version of the application.  In short, just get it into the hands of the end users.

**Comment by dannyneira** [comment]
Thanks for your patience folks! As requested, in Warp version `v0.2023.09.19.08.04.stable_00` and above, the input editor remains visible in inactive panes when using split panes. 

![CleanShot 2023-09-21 at 13 34 04](https://github.com/warpdotdev/Warp/assets/16809145/5b27a944-5add-4296-9166-1e502f70fab7)

Closing as completed, but please let us know if any issues.
