### ISSUE TITLE
mac m1 global hotkey not work

### ISSUE THREAD

**Issue by UvDream** [warpdotdev/Warp#3032]
### Discord username (optional)

THE ONE

### Describe the bug

mac m1 global hotkey not work
<img width="518" alt="image" src="https://user-images.githubusercontent.com/33121872/236610107-77fed58b-d9af-4740-b23f-3ac9be4e8fea.png">
No matter how you set it, you can't wake up the warp

### To Reproduce

Hope the hotkey works

### Operating System

MacOS

### Operating System and Version

13.3.1 (22E261)

### Shell Version

v0.2023.05.02.08.03.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @UvDream Thanks for submitting this, currently, `ESC, BACKTICK, TAB, SHIFT, and CAPS` are not supported keyboard shortcuts for the Hotkey window in Warp. 

Please learn more about this feature in our docs. https://docs.warp.dev/features/windows/hotkey-window

**Comment by UvDream** [comment]
> 
I didn't use the keys ESC, BACKTICK, TAB, SHIFT, and CAPS in here，I tried a lot of things, but they didn’t work. Is there a lack of permissions for various button combinations?

**Comment by ZhangShangyu** [comment]
+1

**Comment by dannyneira** [comment]
`BACKTICK = ``
