### ISSUE TITLE
ability to hide tabs to be able to use full screen estate

### ISSUE THREAD

**Issue by NikosEfthias** [warpdotdev/Warp#3038]
### Describe the solution you'd like?

```Text
ability to hide tabs area to be able to use full screen estate
One way to achieve this might be that when one maximises the pane it also cover the tabs area
```

### Is your feature request related to a problem? Please describe.

```Text
Using vim it gets annoying real fast that a considerable amount of screen is used by tab bar
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @

We already have a request tracking this over at #1009 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
