### ISSUE TITLE
dim inactive split pane + focused / active pane should have a more prominent color scheme or indicator

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#304]
### Describe the solution you'd like?

```shell
ability to dim inactive split pane
+ add other passive visual indicator of which pane is in focus
```

### Is your feature request related to a problem? Please describe.

```shell
UIUX
```

### Additional context

Discord 10/18/2021 - feature requests
https://discord.com/channels/851854972600451112/852249738002956311/899669075268079616

**Comment by elviskahoro** [comment]
from @ianterrell via #700

### Describe the solution you'd like?

I use a multi-pane workflow daily, usually 3-5 or so panes. When I navigate into or out of my terminal application I want to quickly identify which pane has focus. Warp's primary indicator of pane focus is a small triangle in the upper left corner, which is entirely too subtle. The command input area being expanded is also not quickly visually discernible in several panes.

Contrast with iTerm, which uses colors to distinguish the focus.

https://user-images.githubusercontent.com/54963/151597252-8c56034a-bbcc-40e5-8f11-e9519721be1d.mov

**Comment by elviskahoro** [comment]
From @[Integralist](https://github.com/Integralist) via #911
### Discord username (optional)

integralist

### Describe the solution you'd like?

Instead of the small arrow in the top-left corner of the currently active pane I would prefer for the pane's complete border (e.g. left/top/right/bottom) to be highlighted.

Refer to the attached image for a rough illustration of the solution.

### Is your feature request related to a problem? Please describe.

I often have multiple split tmux panes open and currently it's very difficult to remember which pane I'm in. 

I don't find the arrow design (currently used) to be a good indicator of that (it's too subtle, and this can be made worse by the user's chosen theme) and so I have to look extra hard, rather than being able to know quickly 'at a glance' where I am. 

In tmux I don't have this problem because tmux highlights the border.

### Additional context

<img width="2032" alt="Monosnap 2022-04-06 13-19-48" src="https://user-images.githubusercontent.com/180050/161973387-7b011ba3-4a09-4520-9810-475dee2ce58e.png">

Because this isn't going to be to everyone's preference, maybe allow this to be configured on/off and if it's turned off the user gets the current behaviour, which is a small triangle in the top-left corner of the active pane.

**Comment by elviskahoro** [comment]
From @yacobyonas via #911
I came to report the same issue but just have one other idea for how this could work better. in iterm, all inactive panes have a gray shadow over them (see image). that helps to make clear where i'm working and blur out the rest.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/55720492/162085027-0d95b2df-27ca-42fd-b198-dd3d0f345843.png">

**Comment by Integralist** [comment]
Dimmed panes would be cool.

**Comment by arxpoetica** [comment]
Just downloaded Warp, and WOW. Excellent work. This is the only feature I see that's really missing. (Well, maybe this and session/projects/profiles/tmux integration via https://github.com/warpdotdev/Warp/discussions/697)

**Comment by damienbry** [comment]
Same here, loved the dim feature on iTerm !

**Comment by javier-tarazaga** [comment]
Yeap same here! This is one of the most show stoppers for me when using Warp, because when you work with a few panes, right now makes it very difficult to distinguish which pane is on focus (or running something), bringing a lot of visual noise when working with the terminal (something you really want to avoid something you look at all day long). 

How iterm2 has it would just be perfect IMO.

**Comment by dannyneira** [comment]
More feedback on this from discord: https://discord.com/channels/851854972600451112/852249738002956311/1044948641464459274

**Comment by dannyneira** [comment]
![CleanShot 2022-11-23 at 16 34 32](https://user-images.githubusercontent.com/16809145/203665222-94a5ed39-7471-4447-b763-3fefc54a8ae5.png)
Similar to how we handle the Active Tab indicator, could mark the active panes with a blue line on the side of the active pane, and keep all the other lines thinner and less visible.

**Comment by zenria** [comment]
This was I miss the most from iTerm! 

I think that the little triangle (or the active prompt) is not visible enough, especially on big screens where I need to search though the entire screen surface where the triangle (or the prompt) is.

**Comment by arxpoetica** [comment]
> Similar to how we handle the Active Tab indicator, could mark the active panes with a blue line on the side of the active pane, and keep all the other lines thinner and less visible.

It's fairly common for consoles to output bars on the side of logs so a visual indicator on the side wouldn't stand out that well.

Please just highlight the actual background color with an increased semitransparent black or white or however it is that iTerm does it (which is really nice).

**Comment by tylerstillwater** [comment]
Adding my voice here. This is one of the primary reasons I continue to use iTerm over Warp. Dimming/greying the inactive panes would be a huge improvement to UX.

**Comment by dannyneira** [comment]
Thanks for the feedback folks. We're testing this internally and will post here if anything changes.

**Comment by elviskahoro** [comment]
This was launched today! You can activate it via Settings > Appearance > Panes > Dim inactive panes.

**Comment by arxpoetica** [comment]
Thank you, this is so much better!
