### ISSUE TITLE
Very, very minor: Esc key to close search dialog

### ISSUE THREAD

**Issue by asikkema** [warpdotdev/Warp#3042]
### Describe the solution you'd like?

```Text
In other terminals, I've always used CMD+F open the search dialog and ESC to close it when it's got the focus. It currently doesn't do the closing. 

Feel free to ignore :-)
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @asikkema I'm not currently seeing this behaviour you described, when i have CMF-F find in focus, i can use ESC to close the find ( similar to other popups like CTRL-R command search, and CTRL-` AI Command Search ).

Were you using an international keyboard or some other apps that modify/override keyboard shortcuts by any chance?

https://user-images.githubusercontent.com/16809145/236911529-7fba6225-3e89-4ca0-957c-a591f4075d27.mp4

**Comment by dannyneira** [comment]
Closing as resolved, `ESC` can now close the Find (`CMD-F`) popup!
