### ISSUE TITLE
can not show chinese 

### ISSUE THREAD

**Issue by q0821** [warpdotdev/Warp#3043]
### Discord username (optional)

HD#3061

### Describe the bug

I am unable to display Chinese folder or file names when using the 'll' command.
It only show ???

### To Reproduce

1. open any forlder
2. type ll and enter

### Screenshots

![CleanShot 2023-05-09 at 14 10 35](https://user-images.githubusercontent.com/3828001/237009090-4ee4266a-1838-4f65-9e3b-54f1172bf2e9.png)

### Operating System

MacOS

### Operating System and Version

13.3.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.05.02.08.03.stable_00

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @q0821 Thanks for letting us know.

We're tracking this issue over at #1823  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by WiddSun** [comment]
same issue with me, cannot display chinese file name properly
