### ISSUE TITLE
Autocomplete substituting 'ls' with 'false'. Need to allow for different autocomplete confirm key. 

### ISSUE THREAD

**Issue by scott-huson** [warpdotdev/Warp#3047]
### Discord username (optional)

scott-huson

### Describe the bug

This just started today, but whenever I write 'ls', the completions popup has started to suggest 'false', and when I hit enter to confirm the command, I don't mean to confirm the substitution. 

This should not be occurring and I would like the default behavior to not include the enter key when confirming completions. 

I guess this bug is that the completions popup is recognizing 'ls' as a valid substitution. 

### To Reproduce

I am running: v0.2023.05.02.08.03.stable_00

This happens for me on both ssh shells and the default settings. 
I am running zsh not sure if that matters. 

### Expected behavior

This shouldn't happen. There should be a list of things that are not suggested for completion. 

Secondly, I don't want the confirm completion key to also be enter. 

### Screenshots

<img width="419" alt="Screen Shot 2023-05-10 at 1 48 25 PM" src="https://github.com/warpdotdev/Warp/assets/9099103/0e28cf70-dc7b-4afe-ae8c-7a7992f22346">

### Operating System

MacOS

### Operating System and Version

12.0.1

### Shell Version

zsh 5.9 (amd64-portbld-freebsd12.4)

### Warp Version

v0.2023.05.02.08.03.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @scott-huson 
AFAIK, the suggestions closest to the input editor are generally going to be the closest to what you type while suggestions further away from the input are going to be [Fuzzy](https://docs.warp.dev/getting-started/changelog#2022.09.01-v0.2022.08.31.18.11) which means they will include the letters you typed but may not start/end with the letters.

Regarding the completion confirm key bind, we already have a request tracking this over at #1909 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
