### ISSUE TITLE
Floating window and Always on Top Mode

### ISSUE THREAD

**Issue by avinayak** [warpdotdev/Warp#3048]
### Describe the solution you'd like?

```Text
It'd be cool if there is a Floating window mode. It should be possible to summon Warp using a shortcut. Window should also be always on top in the floating mode, hidden only by close button or shortcuts.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @avinayak Thanks for submitting this request. Warp has a feature called Hotkey window which allows you to configure a shortcut for a window that pops up on top of other windows and can go away automatically with loss of focus, or by pressing the same shortcut that opened it. 

https://docs.warp.dev/features/windows/hotkey-window

Please see more on this in our docs above and let us know if that works for your use case by closing this request. If not then please provide further details on what you'd like to see done differently.

**Comment by avinayak** [comment]
Wow. This is exactly what I needed. Closing this issue
