### ISSUE TITLE
SSH: ssh fails

### ISSUE THREAD

**Issue by NikosEfthias** [warpdotdev/Warp#305]
### Describe the bug

```shell
connecting to remote ssh fails with message 

<W> fish: An error occurred while redirecting file 'unset PS1; unset PS2; set -o vi; set +o vi; HISTCONTROL=ignorespace; printf '\u1b\u50\u24\u64{"hook": "InitShell", "value": {"shell": "bash"}}\u9c''
open: No such file or directory
```
```


### To Reproduce

Steps to reproduce:
1. run `ssh user@yourserver`
2. have fish as a shell on the remote (not sure if this is relevant tho)


### Expected behaviour

```shell
connect to remote with no issues
```

### Screenshots

![image](https://user-images.githubusercontent.com/9097437/138782682-d3c3dbc6-df3b-43b9-a9ad-bae0ae253b3b.png)

### Operating System

MacOS

### OS Version

11.6 big sur

**Comment by mquinnv** [comment]
so this same problem has basically made it so i can't use warp. i too had fish as my remote shell, but changing it to /bin/sh yields the same problem. changing my mac shell to /bin/zsh results in the same thing.

**Comment by mquinnv** [comment]
this is happening on Monterey as well.

**Comment by corvinux** [comment]
Same here:
<W> fish: An error occurred while redirecting file 'unset PS1; unset PS2; set -o vi; set +o vi; HISTCONTROL=ignorespace; printf '\u1b\u50\u24\u64{"hook": "InitShell", "value": {"shell": "bash"}}\u9c''
open: No such file or directory
Connection to host.domainname.net closed.

**Comment by platy** [comment]
I've also got this, in my case I'm trying to ssh to a host which only has `sh`, it looks like warp can only `ssh` to hosts with `bash`. I get:

```
ash: syntax error: unexpected "("
Connection to localhost closed.
```

From the verbose output, I think the key is:
```
﻿﻿debug1: Sending command: exec -a bash bash --rcfile <(echo 'unset PS1; unset PS2; set -o vi; set +o vi; HISTCONTROL=ignorespace; printf '\\''\\u1b\\u50\\u24\\u64{"hook": "InitShell", "value": {"shell": "bash"}}\\u9c'\\''')
```

**Comment by NikosEfthias** [comment]
For now, I found a workaround. 
If you connect to your server from tmux within warp everything works fine.

**Comment by elviskahoro** [comment]
@NikosEfthias @mquinnv @platy 

Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
