### ISSUE TITLE
Weird behavior on multiple monitors when using panes

### ISSUE THREAD

**Issue by NedimMuhamedagic** [warpdotdev/Warp#3050]
### Describe the bug

This **may** not be a bug exactly, but maybe even a feature request, and I do admit it's an **extreme** nitpick, but it's a bit annoying :)

When using multiple monitors on mac, and using multiple panes in Warp, there's a weird interaction. If I have an app (eg. Chrome) focused on one monitor, and Warp open on another monitor, if I click on a pane in warp, it's not going to focus it, but it's going to focus the warp window, so you basically have to double-click to get to the pane you need.

### To Reproduce

Preparation:
- have a multiple monitor setup on MacOS, with Warp on one monitor, and any other app on the second monitor

Steps to reproduce
- open up one tab in Warp with 2 panes (pane A to the left, and pane B to the right)
- focus the pane B by clicking on it in warp
- on the second monitor, use any app so it comes into focus (litterally just a click in chrome is enough)
- go back to the first monitor, and click on pane A in warp (remember, pane B was focused last)
- Warp will focus the pane b

### Expected behavior

When clicking on any pane in multiple monitor setup, the click should bubble and select the exact pane I clicked on instead of focusing the latest focused pane.

### Operating System

MacOS

### Operating System and Version

13.2.1

### Shell Version

zsh 5.9

### Warp Version

v0.2023.05.02.08.03.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this!

We already have a request tracking this over at #739 This is on our radar and being worked on with no official ETA.

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
