### ISSUE TITLE
Split Pane View -- Inactive Panes Shift Text Down

### ISSUE THREAD

**Issue by elliottecton** [warpdotdev/Warp#3054]
### Discord username (optional)

elliott.ecton#1676

### Describe the bug

This is a bit of a nit-pick, but figured I would submit it. If you have Warp in 'Split Pane Right' view, the inactive, dimmed pane shifts all of the text down a row. When you activate it, the text shifts back up a row to allow for the cursor at the bottom. I don't know why, but this tickles my OCD.

Maybe an easier way to describe it is the prompts aren't even across the two panes -- inactive and active.

### To Reproduce

1. Open Warp
2. 'Split Pane Right' or Command+D
3. Inactive pane's prompt is a row lower than the active pane
4. Click on the inactive pane, and now the prompts flip-flop. The now active pane is higher than the previously active pane.

### Expected behavior

Even prompts across all panes, active or inactive

### Screenshots

<img width="1197" alt="Screenshot 2023-05-11 at 7 06 19 PM" src="https://github.com/warpdotdev/Warp/assets/7132555/91c1859e-dbb2-4753-8716-3e66719de979">
Uneven prompts

### Operating System

MacOS

### Operating System and Version

Ventura 13.3.1

### Shell Version

bash --version GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22) Copyright (C) 2007 Free Software Foundation, Inc.

### Warp Version

v0.2023.05.09.08.03.stable_01

### Additional context

Sorry for nit-picking, and thanks for an awesome new terminal!!!

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @elliottecton 

We already have a request tracking this over at #303

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

Also, we just launched [Synced inputs](https://docs.warp.dev/features/entry/synchronized-inputs), which syncs/shows all the inputs across a window/tab, so this feature may not be too difficult to implement. 🤞

**Comment by dannyneira** [comment]
Thanks for your patience folks! As requested, in Warp version `v0.2023.09.19.08.04.stable_00` and above, the input editor remains visible in inactive panes when using split panes. 

![CleanShot 2023-09-21 at 13 34 04](https://github.com/warpdotdev/Warp/assets/16809145/5b27a944-5add-4296-9166-1e502f70fab7)

Closing as completed, but please let us know if any issues.
