### ISSUE TITLE
Single character alias isn't recognized

### ISSUE THREAD

**Issue by Saafo** [warpdotdev/Warp#3056]
### Discord username (optional)

Saafo#9108

### Describe the bug

The latest Warp can't recognized single character alias.

### To Reproduce

1. `alias v=nvim` in `~/.zshrc`
2. type `v` in Warp
3. the `v` has red underline

### Expected behavior

the v has no underline and is green.

### Screenshots

<img width="34" alt="image" src="https://github.com/warpdotdev/Warp/assets/46736350/ed0a37ad-1632-43d7-a872-181c8565d563">

<img width="171" alt="image" src="https://github.com/warpdotdev/Warp/assets/46736350/7b32f324-303a-4ddd-9faa-640c5b613b02">

### Operating System

MacOS

### Operating System and Version

13.2.1

### Warp Version

v0.2023.05.09.08.03.stable_01

### Additional context

The last week version is okay.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @Saafo Thanks for submitting! I noticed the same with my git alias (`alias g=git`), I'll bring this up with the team as it appears to be a regression.

In general, when an alias of command is newly added, [Error Underlining will still happen until you open a new session and the alias is bootstrapped](https://docs.warp.dev/features/editor/syntax-error-highlighting#what-is-error-underlining). This doesn't appear to be the case with this bug.

**Comment by robbienohra** [comment]
Experiencing the same thing

**Comment by Saafo** [comment]
Any update? A month passed..

**Comment by dannyneira** [comment]
Nothing yet, have you tried with alias expansion enabled? https://docs.warp.dev/features/editor/alias-expansion

**Comment by Saafo** [comment]
> Nothing yet, have you tried with alias expansion enabled?

The feature is good, but I think it's two unrelated things. Usually I alias v = nvim, and I input `v` and directly hit enter without inputing `space` to open current folder as workspace. There's no chance for me to use the alias expansion feature.

**Comment by robbienohra** [comment]
I think the point is that single-character aliases are not being properly recognized or handled:

Eg

```
alias l="exa -l --icons"
alias la="exa -la"
```

Note how `la` is highlighted correctly and `l` is not

<img width="159" alt="image" src="https://github.com/warpdotdev/Warp/assets/28514482/d333b28d-18eb-474f-bc3f-c3a8eb9b5cba">

<img width="300" alt="image" src="https://github.com/warpdotdev/Warp/assets/28514482/855fe30b-19c4-4714-a53b-2bf295163d22">

**Comment by robbienohra** [comment]
As @Saafo mentioned alias expansion, although an interesting feature, is not in itself related to this 👆 as far as we are aware.

**Comment by ajeetdsouza** [comment]
Is there an ETA on when this might be fixed? This also causes an issue with the [zoxide](https://github.com/ajeetdsouza/zoxide) plugin.

**Comment by dannyneira** [comment]
As a workaround, even if the single char alias is [Error Underlined](https://docs.warp.dev/features/editor/syntax-error-highlighting#what-is-error-underlining), it should still run like normal. In my example below: g=git and s=status.

![CleanShot 2023-06-23 at 11 41 09](https://github.com/warpdotdev/Warp/assets/16809145/7ede8d10-4db7-49ed-8fcd-5f87337209ae)

I hope this helps in the meantime until this issue gets some eng time. We appreciate your patience with us folks as we work to improve the terminal!  If there are any further updates, we'll post them on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by Saafo** [comment]
Seems resolved in the release of this week!

**Comment by 2wheeh** [comment]
@dannyneira hi, I'm using autojump and it keeps underlining on 'j'. is this related to this issue ?

**Comment by ajeetdsouza** [comment]
@2wheeh you probably need to update Warp, this is fixed.

**Comment by kvenn** [comment]
I also have an underline for `j` but `g` works. Iterm2 recognizes both.
