### ISSUE TITLE
Support custom background color and/or theme per window

### ISSUE THREAD

**Issue by jimmyaldape** [warpdotdev/Warp#3057]
### Discord username (optional)

jimmy_#2644

### Describe the solution you'd like?

```Text
When working on multiple projects for multiple clients, it would be super helpful to have a way to change the background color or theme on a specific window in order to help differentiate between projects and clients and avoid running the wrong command on the wrong window.

Having a quick visual indicator would definitely help in this situation.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @jimmyaldape 

We already have a request tracking this over at #478, as a possible workaround, you can set different [colors for the Tabs](https://docs.warp.dev/features/windows/tabs#how-to-use-it) ( as well as rename them, etc. ) which should help with identifying them. Also, the [Launch Configuration](https://docs.warp.dev/features/sessions/launch-configurations) feature may also help as you can set up different configs for each client ( with cwd, tab names/colors, commands, etc. ).

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
