### ISSUE TITLE
Add toggle to disable Warp AI feature

### ISSUE THREAD

**Issue by xiaogwu** [warpdotdev/Warp#3059]
### Describe the solution you'd like?

```Text
Can you add a toggle to disable Warp AI?
```

### Is your feature request related to a problem? Please describe.

```Text
Incase your company has policies in place to not use ChatGPT.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @xiaogwu , you may want to consider blocking OpenAI's API (`api.openai.com`) on your firewall as a workaround.

We already have a request tracking this over at #2808 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
