### ISSUE TITLE
The output of cd to a directory is one step slower

### ISSUE THREAD

**Issue by peng0119** [warpdotdev/Warp#3061]
### Describe the bug

cd to any folder and look at the next line of output,Folder names don't appear right away

### To Reproduce

1. cd to any folder
2. look at the output

### Expected behavior

The folder name immediately appears in the next line of output

### Screenshots

https://github.com/warpdotdev/Warp/assets/132866041/7370db44-9717-4a96-9f5e-c8af0aa3e8e9

### Operating System

MacOS

### Operating System and Version

macos Ventura 13.3.1

### Shell Version

fish, version 3.6.1

### Warp Version

v0.2023.05.09.08.03.stable_01

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @peng0119 Which prompt are you using? Is it on the supported list? https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table

Please note there are some known issues with prompts, there is more info and workarounds on the doc above.
