### ISSUE TITLE
title or background "tag" for the pane

### ISSUE THREAD

**Issue by AdiStrauss** [warpdotdev/Warp#3067]
### Describe the solution you'd like?

```Text
I think it would be helpful to add a title or background "tag" for the pane. For example, in Item2, you could add "badges". This would be especially useful if you have a lot of panes open at the same time. :)
I love your product, but the missing feature is a deal breaker for me. I have many panes open and I'm getting confused.
```

### Additional context

example from iterm2:
<img width="566" alt="image" src="https://github.com/warpdotdev/Warp/assets/126667384/d945591f-22fa-4899-af11-ebd9dab86795">
 

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @AdiStrauss, thanks for submitting this!

We already have a request tracking this over at #2121 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
