### ISSUE TITLE
The stupidest issue

### ISSUE THREAD

**Issue by kslstn** [warpdotdev/Warp#3068]
### label-textarea

Probably it's just me, but I thought you may want to know. Most of the time I use the VS Code terminal. I occasionally use Warp, when I need to do something that's not related to a specific project. A few times a month. And every time I want to launch it via Raycast (a Spotlight alternative), for the love of God I can't remember the name of the app. Something something terminal? Blitz? Wham? Blorp? Then I look at my dock for the icon and I can't find one that looks like a terminal. 

Probably just my memory and eyes. But I do remember I get your mails with 'Jess' as a sender. That name somehow has a stronger emotional connection in my brain.

**Comment by dannyneira** [comment]
Thanks for submitting this @kslstn We already have a request tracking this over at #1865 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
