### ISSUE TITLE
Fish Autocomplete

### ISSUE THREAD

**Issue by javadnasrolahi** [warpdotdev/Warp#3069]
### Describe the solution you'd like?

```Text
fish has a great feature that helps to speed up working with Kubectl 
for example, we have a pod named "strimzi-cluster-operator-5c7d4d846c-xdzzg" When we type `kubectl get pod strimzi-cluster-operator-` then we pressed the tab it will complete the rest of pod name, it works in mac default terminal but doesn't work in Warp.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Appreciate you taking the time to submit this request @javadnasrolahi!

This is on our radar to improve/fix and we already have a request tracking this over at #2055 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
