### ISSUE TITLE
Support a startup command argument 

### ISSUE THREAD

**Issue by kieran-osgood** [warpdotdev/Warp#307]
### Describe the solution you'd like?
Possibly related to #102 but in the default mac terminal and iTerm you can use a command like: `open -a terminal ./path/to/directory` and it will open the terminal window/tab at that directory - (which I use frequently in combination with Launchbar (https://www.obdev.at/resources/launchbar/help/index.php?chapter=OtherFeatures#:~:text=Select%20a%20folder%20in%20LaunchBar,pressing%20Tab%20and%20selecting%20Terminal.)

### Is your feature request related to a problem? Please describe.
Currently running `open -a Warp ./path/to/directory` just opens Warp at my home directory instead of the specified one

**Comment by elviskahoro** [comment]
Going to merge this into #345
