### ISSUE TITLE
Auto copy same as in Iterm2

### ISSUE THREAD

**Issue by eTaoss** [warpdotdev/Warp#3070]
### Describe the solution you'd like?

```Text
The autocopy feature saves lot of time while working with the terminal. Basically it works in Iterm2 and whenever I highlight word, or sentence with a mouse cursor, the text is automatically copied into the clipboard
```

### Is your feature request related to a problem? Please describe.

```Text
I came from Iterm2 and it's kinda frustrating on daily basis when I miss this feature...
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by szgupta** [comment]
Warp has this feature as well! If you open the command palette (`CMD-P`) and then search for "copy on select", you should be able to enable it!

**Comment by dannyneira** [comment]
Thanks @eTaoss! As @szgupta mentioned, this feature exists! and I've added a short blurb about it in our docs [here](https://docs.warp.dev/features/editor#copy-on-select). 

Let us know if this feature meets your use case by closing out this request.

Also, please note this feature has a known issue working within alt-screens like vim, less, k9s, etc. that we're tracking here: https://github.com/warpdotdev/Warp/issues/2758

**Comment by dannyneira** [comment]
Closing as this feature already exists in Warp.

**Comment by jmoseley** [comment]
I have been having trouble with this feature. As far as I can tell it is turned on in the settings, but things I select do not end up on my clipboard. Any ideas what might be going wrong?
