### ISSUE TITLE
Everytime Warp is opened shows "Powerlevel10k is not yet supported in Warp..." message, although Powerlevel10k is disabled on Warp

### ISSUE THREAD

**Issue by Chrisley304** [warpdotdev/Warp#3073]
### Describe the bug

Since some updates, every time I open a new tab or window in Warp, I see the message "Powerlevel10k is not yet supported in Warp. You might consider one of the supported prompts as an alternative." at the top. However, this is very annoying because **Powerlevel10k is already disabled for Warp** and I am using Starship instead.

I followed the instructions in the [[Warp documentation](https://docs.warp.dev/features/prompt#disabling-unsupported-prompts-for-warp-e.g.-powerlevel10k-p10k)](https://docs.warp.dev/features/prompt#disabling-unsupported-prompts-for-warp-e.g.-powerlevel10k-p10k) to disable Powerlevel10k and enable Starship. The code I used is as follows:

```shell
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
	if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
	fi
fi
```
Please fix this issue, or let the user disable this message.

### To Reproduce

Open a new tab or window on Warp.

### Expected behavior

The message "Powerlevel10k is not yet supported..." should dissapear after disabling Powerlevel10k.

### Screenshots

![SCR-20230516-av2](https://github.com/warpdotdev/Warp/assets/53919610/4a0333e6-561d-44b7-bd10-73492adda62a)

### Operating System

MacOS

### Operating System and Version

13.3.1

### Shell Version

zsh 5.9

### Warp Version

v0.2023.05.09.08.03.stable_01

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @Chrisley304 please check if you have the following snippet, or any other references to p10k, in your .zshrc and use the same conditional.
```
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```
Also, we're working to support p10k and should have some more updates you can follow here #2851

**Comment by Afrowave** [comment]
Thanks @Chrisley304 for this question. That prompt was getting to me. 

Thanks @dannyneira for the answer. I cleaned up my `.zshrc` and it works.
