### ISSUE TITLE
Support for chords in keyboard shortcuts

### ISSUE THREAD

**Issue by jogly** [warpdotdev/Warp#3076]
### Discord username (optional)

traderjoeski#3948

### Describe the solution you'd like?

I would like to use a chord, such as `ctrl+a, l`, for warp commands.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @jogly Thanks for submitting this. We already have a request tracking this over at #1240

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by seangaffney** [comment]
Despite having a similar title, this is not actually a duplicate of #1240. #1240's title does not match the intent listed in the issue. #1240 is correctly a duplicate of #2809 (as called out). This is now a duplicate of the newer, more descriptive issue #5890. If you'd like to vote in favor of this behavior, please add a 👍 there!
