### ISSUE TITLE
Add support for .command files on macOS

### ISSUE THREAD

**Issue by dkocher** [warpdotdev/Warp#3080]
### Describe the solution you'd like?

```Text
Should register to to support files with extension .command on macOS in `Info.plist` of the application bundle.
```

### Is your feature request related to a problem? Please describe.

```Text
This would allow to set Warp as the default application for `.command` files and thus allow the use as an external terminal application from [Cyberduck](https://github.com/iterate-ch/cyberduck) as documented in https://docs.cyberduck.io/protocols/sftp/#open-in-terminal.
```

### Additional context

```
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>command</string>
			</array>
			<key>CFBundleTypeName</key>
			<string>Terminal scripts</string>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
		</dict>
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Appreciate the feature request @dkocher
Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified

**Comment by LampPrinter** [comment]
When will this get added? It is a basic functionality. I can not open .sh files in Warp either. I remember people requesting it around a year ago even.

**Comment by dannyneira** [comment]
Hey Folks, Quick update, we're actively working on `.command` and `.sh` support. No official ETA, but once we have updates we'll post them on this thread. Thanks for your patience 🙏

**Comment by dannyneira** [comment]
Thanks for your patience folks! As requested, in Warp version `v0.2023.09.12.16.17.stable_00` and above, you can open `.command` and UNIX executable files with Warp.

![CleanShot 2023-09-21 at 13 46 07](https://github.com/warpdotdev/Warp/assets/16809145/49acbedc-08d0-4d78-ad28-54fbb987c3b1)

Closing as completed, but please let us know if any issues.

**Comment by LampPrinter** [comment]
@dannyneira It only works if the File Path does not contain any spaces. At least on MacOS.
If a space is there "zsh: no such file or directory:"

**Comment by dannyneira** [comment]
Cool let the Eng team know about the edge case, we'll post any updates on this thread.

**Comment by abbasahmad** [comment]
Hello, It was working for a while but i lost the ability to have .command files run directly. the .command files are opened as files for editing and not executed; am i the only one ?
