### ISSUE TITLE
How to delete my account / data?

### ISSUE THREAD

**Issue by uxduck** [warpdotdev/Warp#3084]
### Describe the solution you'd like?

```Text
I would like there to be an easy way to delete my account, either in the app or on the website. So far, I have submitted a "contact us" form.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! 

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by brunodeluk** [comment]
Wait, you're telling me the super advanced rust-based AI-driver terminal does not come with the most basic feature as delete account?

**Comment by cworld1** [comment]
half a year has passed, but they have nothing done except email my register account address regularly. Sadly.

**Comment by dannyneira** [comment]
Hi @ben-xD and Folks, We've finished implementing a data deletion process for Warp accounts.

Warp provides a convenient way for deleting your Warp account and data:
- From Warp, Go to Settings > Privacy > "Visit the data management page"
- On the [Data Management](https://app.warp.dev/data_management) page, click the Delete button and go through the data deletion flow.

Note: If you're a Warp [Team](https://docs.warp.dev/features/teams) admin, the deletion flow will require that you assign a team member as the new admin.

Closing as resolved, but please feel free to let us know if any issues.

**Comment by ben-xD** [comment]
Following the instructions Danny gave, I thought I needed to install warp again. I just needed to go to https://app.warp.dev/data_management and login.

**Comment by dexwert** [comment]
hey I deleted my warp account but when I try to make a new one with the same email I cant

**Comment by jefflloyd** [comment]
Hey @dexwert - do you mind trying again? We permanently delete user data as part of a daily job; it's possible the job hadn't run yet when you tried to sign up again. See [here](https://docs.warp.dev/getting-started/privacy#delete-your-data) for more details.

**Comment by dexwert** [comment]
I tried again and it did work I didn't notice that you need to wait a day thanks

**Comment by eudesmedeiros7** [comment]
thank you all guys. i successful asked for delete my account
