### ISSUE TITLE
Alias expansion fails in certain cases

### ISSUE THREAD

**Issue by that70schris** [warpdotdev/Warp#3089]
### Describe the bug

the new "Alias Expansion" feature is fantastic.  but it doesn't work if the alias is trying to override a standard command

### To Reproduce

1.  make sure alias expansion feature is on
2. run `alias ls='ls -a'`
3. run `ls`

### Expected behavior

In order to mimic fish abbr behavior, `ls` would expand into `ls -a`.  it does actually run `ls -a` so the alias is there

### Operating System

MacOS

### Operating System and Version

13.3.1

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2023.05.18.01.08.stable_04

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @that70schris, I was able to reproduce this. As a workaround, you can set up `alias l=ls -a` or any alias name other than `ls` and the alias should properly expand. We'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Hi @that70schris It's a known limitation of this feature, as stated in the INFO in our docs: https://docs.warp.dev/features/editor/alias-expansion

Aliases will not be expanded when the command in the expanded form is the same as the alias itself. e.g. if you have an alias `ls='ls -G'`, `ls` will not be expanded in the input editor.

**Comment by dannyneira** [comment]
Closing as this is a known limitation of the feature and there are no immediate plans to change this behavior.

**Comment by that70schris** [comment]
interesting, I'm curious where this limitation pops up as it's neither a limitation of aliases themselves, nor one for fish abbr

**Comment by dannyneira** [comment]
Hey @that70schris If we didn't limit this case, then these aliases would get expanded twice: once by Warp then once again when the shell expands it. e.g. with `alias ls="ls -a"` and alias expansion on, typing `ls + Enter` would end up executing `ls -a -a`.

**Comment by that70schris** [comment]
oh that is a problem.  i wonder how fish solves this

**Comment by dannyneira** [comment]
So fish and zsh and bash are all shells, where as warp is a terminal, and given how Warp has it's IDE-Like input editor, it doesn't work like other terminals. So we had to make the design choices when implementing the terminal feature for alias expansion. As with any of the features its a work in progress and always has room for improvement. Appreciate your input and patience with use as we push to make the terminal experience better!
