### ISSUE TITLE
Encoding for non-English file names

### ISSUE THREAD

**Issue by minsukchang** [warpdotdev/warp#309]
### Describe the bug

```shell
ls command in directories with non-English filenames results in bad behavior. The screen doesn't show such filenames.
```

### To Reproduce

ls command in directories with non-English filenames

### Expected behaviour

```shell
correct encoding for the filenames
```

### Screenshots

![image](https://user-images.githubusercontent.com/1142566/138980757-bec6e183-060c-4663-9378-6b1f11efac2b.png)

### Operating System

MacOS

### OS Version

11.6 (20G165)

**Comment by kevinyang372** [comment]
This issue should be fixed in the latest version of Warp!

**Comment by minsukchang** [comment]
works great with the latest update! Thanks!
