### ISSUE TITLE
Switching to next or previous tab

### ISSUE THREAD

**Issue by gin1314** [warpdotdev/Warp#3091]
### Describe the solution you'd like?

```Text
It would be helpful to add switching of tabs by using Cmd + ->, to go switch to the next right tab, as well as Cmd + <- switching to the left previous tab
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @gin1314 thanks for submitting, There are currently options for switching tabs which default to activate the previous or next Tab with `SHIFT-CMD-{` or `SHIFT-CMD-}`, but you can change them in the settings to whatever shortcut you want.
Please see more on this here:
https://docs.warp.dev/features/windows/tabs
https://docs.warp.dev/features/keyboard-shortcuts

Closing as the keyboard shortcuts for tab switching exist and can be changed.

**Comment by gin1314** [comment]
Hi @dannyneira , thanks for that info!
