### ISSUE TITLE
Minimize split

### ISSUE THREAD

**Issue by Lcarv20** [warpdotdev/Warp#3096]
### Discord username (optional)

Lcarv#6831

### Describe the solution you'd like?

```Text
I would love if I could minimize/hide the splits.
This is secondary but another feature I would like to see is having the possibility to choose where to open a new tab(CWD or root), but maybe this would require custom keymaps.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request for minimizing splits!

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

Regarding the other request, there is currently a way to set the [default working dir for new tabs](https://docs.warp.dev/features/working-directory), but not a way to set up new tabs to open in multiple dirs based on a keyboard shortcut so we recommend you open a new feature request for that.

**Comment by charlespierce** [comment]
Hi @Lcarv20, can you clarify what you mean by "hide the splits"? Are you referring to split panes within a single tab? The dividing line between each input/output block? Something else I'm not even thinking of?

If possible, a quick screenshot showcasing what you're referring to would be a great help to make sure we're properly understanding the request and determine the amount of work involved.

Thanks for the feedback!

**Comment by Lcarv20** [comment]
Hi there @charlespierce,

Sorry for being brief. So imagine you have 2 splits and you would like to focus only on one single split (taking the full window size), the solution that comes to my mind is to open a new tab in the CWD. However if you could toggle the current split you are focusing to take the full size of the window, and then toggle back to the layout you had before with all the splits without losing context, that would be nice.
For example, I have two splits, one with vim and another for running npm scripts, if I try to close the split that's running the npm script I lose the context and the running script stops as well.

I know you can achieve something like this using xterm, but it would be cool if the feature was native.
I hope this doesn't sound unreal.

I also would like to say thanks since this Warp is quite an exciting product.

**Comment by Lcarv20** [comment]
Ho that's great,
I feel kinda embarrassed now. I have tried to search before and couldn't find.
Thanks once again and keep the great work!
