### ISSUE TITLE
Switch to N'th tab on french keyboard doesn't work

### ISSUE THREAD

**Issue by shide1989** [warpdotdev/Warp#3098]
### Describe the bug

Switching to a different using the shortcut (for example) `CMD + 1` doesn't work on **french Magic Keyboard** on Apple M1.

### To Reproduce

- Open multiple tabs
- press `CMD + 1` or `CMD + 2` etc.. witch shouldn't work on Apple M1

### Expected behavior

It should witch tabs

### Screenshots

![Capture d’écran 2023-05-22 à 19 15 45](https://github.com/warpdotdev/Warp/assets/7138331/3f335183-ffd9-48d1-bae9-c77570eecaf2)

### Operating System

MacOS

### Operating System and Version

13.3.1

### Warp Version

v0.2023.05.18.01.08.stable_04

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Sorry to hear about this @shide1989, I suspect this issue has to do with the current lack of IME support in Warp. So keyboard shortcuts on an international keyboard don't quite work the same as in the US-based ones. As a possible workaround, you can click on the Tab you wish to activate.

We're tracking this issue over at #341 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
