### ISSUE TITLE
M1 MAC no color?

### ISSUE THREAD

**Issue by TryA9ain** [warpdotdev/Warp#3100]
### Describe the bug

M1 MAC use `ls` no color

### To Reproduce

`ls`

<img width="354" alt="image" src="https://github.com/warpdotdev/Warp/assets/51145610/88787240-4ebd-45ae-88a6-1311d150a7b0">

### Operating System

MacOS

### Operating System and Version

m1 pro

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @TryA9ain, `ls` doesn't show colors by default, you need to use `ls -G` to enable colors. You can `echo "alias ls='ls -G'" > ~/.zshrc` then open a new tab and it should load the alias and the next time you use `ls` it should be in color.

Let me know if that helped.
