### ISSUE TITLE
Opening settings does not close recent commands

### ISSUE THREAD

**Issue by tricki** [warpdotdev/Warp#3101]
### Describe the bug

When I open the recent commands list and then open the settings, the recent commands pane is still open and overlaps the settings modal.

### To Reproduce

1. Press the up arrow to show the recent commands
2. Open the settings (either through the icon at the top right or the keyboard shortcut)

### Expected behavior

Opening the settings should close open panels. Alternatively the settings dialog should be above any other panels.

### Screenshots

<img width="1082" alt="image" src="https://github.com/warpdotdev/Warp/assets/523154/fa9b03ce-5e91-437b-a418-780af1c885d3">

### Operating System

MacOS

### Operating System and Version

Ventura 13.3.1 

### Shell Version

zsh 5.9

### Warp Version

v0.2023.05.18.01.08.stable_04

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @tricki This is a known issue with other popups like AI Command Search, Workflows, and History showing up over settings. As a workaround, you can press ESC, before you open the settings modal. We'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by davidmelvin** [comment]
this should be fixed now! can you confirm it's fixed on your end in the latest version of Warp, @tricki ?

**Comment by tricki** [comment]
Can confirm it's fixed, even when opening other modals like "About Warp". Thanks for fixing this so quickly.

**Comment by davidmelvin** [comment]
Sweet!
