### ISSUE TITLE
Lost all working directory on multiple reboot

### ISSUE THREAD

**Issue by thoroc** [warpdotdev/Warp#3102]
### Describe the bug

I had to reboot a few times and I was surprised that all my sessions have been set to the home directory instead of been on the respective working directory where I have left them. I don't expect this to be the case hence the bug report.

### To Reproduce

Reboot a few times (5 times at most seems to have produced the behaviour)

### Expected behavior

All the different session should have pointed at the last directory

### Operating System

MacOS

### Operating System and Version

Ventura 13.4

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Warp Version

v0.2023.05.18.01.08.stable_04

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

**Comment by dannyneira** [comment]
any luck with the above @thoroc ?

**Comment by dannyneira** [comment]
Closing as we can't reproduce this issue and no response. Please let us know if the issue persists and provide detailed steps on reproduction.

**Comment by thoroc** [comment]
I am coming to you as I have experienced another bunch of lost sessions (2 tabs, 4 panes on one and 3 panes on the other one). It does looks like the session is being restarted twice before loosing _sight_ of the directory where it was.

I know this is extremely difficult to reproduce and might be machine/bash config specific.

Thank you for the information about the launch config, unfortunately this wouldn't work in my situation as I am not necessarily wanting to keep session open for the 100+ repos I have locally.
