### ISSUE TITLE
command completion missing for 'ls'

### ISSUE THREAD

**Issue by ethrbunny** [warpdotdev/Warp#3103]
### Describe the bug

With commands like 'pushd' I can add a space, a few characters from a folder, hit tab and the shell will try to fill the rest (or prompt if it isn't sure).

Not so for 'ls'. Type 'ls', add a space and a few folder characters, hit tab and nothing happens.

### To Reproduce

create a folder
create subfolders 'foo', 'foreign', 'fodder', and 'other'
type 'ls' then a space and hit tab
note no suggestions for subfolders

### Expected behavior

for most commands that use subfolders (or a path) I get a prompt when I tab. Nothing for 'ls'

### Operating System

MacOS

### Operating System and Version

ventura 13.3

### Warp Version

v0.2023.05.18.01.08.stable_04

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @ethrbunny 

We're tracking this issue over at #3094  Please note the [troubleshooting steps there](https://github.com/warpdotdev/Warp/issues/3094#issuecomment-1558109609). 

We would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
