### ISSUE TITLE
Will you consider supporting the Chinese visual menu?

### ISSUE THREAD

**Issue by larkzhang** [warpdotdev/Warp#3107]
### Describe the solution you'd like?

```Text
Will you consider supporting the Chinese visual menu?
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @larkzhang 

We already have a request tracking this over at #1823 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
