### ISSUE TITLE
Subwrap not working for itermocil

### ISSUE THREAD

**Issue by LiranBri** [warpdotdev/Warp#3110]
### Describe the bug

I have alias for itermocil command, but it opens it in my original terminal (Item2) instead of wrap when trying to run command on it.

tried also to add regex "itermocil" and "itermocil.*" in the preferences, but it just resulted in following error:
```bash
110:125: execution error: iTerm got an error: Can’t get current window. (-1728)
```

### To Reproduce

run itermocil

### Expected behavior

open itermocil inside Wrap

### Operating System

MacOS

### Operating System and Version

Monterey 12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2023.05.18.01.08.stable_04

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @LiranBri, thanks for submitting! Unfortunately, [`itermocil` is only designed to work with iTerm2](https://github.com/TomAnthony/itermocil#introduction). Fortunately, Warp has a very similar feature, [Launch Configurations](https://docs.warp.dev/features/sessions/launch-configurations), that should take care of the same use case. ( i.e. pre-configured layouts of windows, tabs, and panes while having each open in a specified directory and execute specified commands )

Closing as this isn't a supported cli tool and a feature already exists for the use case.

**Comment by LiranBri** [comment]
is there a migration path?
