### ISSUE TITLE
Warp is using discrete graphic card

### ISSUE THREAD

**Issue by codeshake** [warpdotdev/Warp#3112]
### Describe the bug

Hello! It's not a bug, but why does Warp use discrete graphic card?
It's not critical, but a highly reduce battery life.

MacBook Pro 16" 2019, i7, Radeon Pro 5300M, 512 SSD, 16GB RAM, macOS Catalina 10.15.7.

### To Reproduce

1) Open «About this mac» without any running apps. Make sure that discrete card isn't in a list of video adapters.
2) Open Warp and re-launch «About this mac».

### Screenshots

<img width="698" alt="Снимок экрана 2023-05-24 в 20 43 45" src="https://github.com/warpdotdev/Warp/assets/47363641/cfadc58e-87b7-4d52-8051-31ccee624cb4">

### Operating System

MacOS

### Operating System and Version

Catalina 10.15.7

### Warp Version

v0.2023.05.18.01.08.stable_04

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @codeshake

We're tracking this issue over at #76, there are a couple of comments on there that describe ways to stop Warp from using the discrete GPU as a workaround. We would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue.

We'll be closing this as a duplicate.
