### ISSUE TITLE
precmd prompt is printed in previous block

### ISSUE THREAD

**Issue by j-hui** [warpdotdev/Warp#3116]
### Describe the bug

The precmd prompt is written in the previous block, like this:

<img width="331" alt="image" src="https://github.com/warpdotdev/Warp/assets/11800204/f42845e3-4442-4555-8446-9b46942c4ea6">

### To reproduce

I extracted and reproduced this with this minimal zshrc:

```zsh
autoload -U add-zsh-hook
function prompt_precmd () { echo "((precmd prompt))" ; }
add-zsh-hook precmd prompt_precmd
PS1="the prompt > "
```

### Expected behavior

It should be printed in the same block the prompt is in

### Operating system

MacOS

### Operating system and version

13.3.1 (22E261)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.18.01.08.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @j-hui Thanks for letting us know, You can wrap the pre_cmd function and the call into a conditional so it won't be run before the prompt is rendered. 

```sh
autoload -U add-zsh-hook

# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then

function prompt_precmd () { echo "((precmd prompt))" ; }
add-zsh-hook precmd prompt_precmd

fi

PS1="the prompt > "
```

**Comment by dannyneira** [comment]
Closing as resolved, this has been fixed in recent version of Warp!
