### ISSUE TITLE
Unable to view saved bookmarked commands

### ISSUE THREAD

**Issue by santo-apollo** [warpdotdev/Warp#3119]
### Describe the solution you'd like?

```Text
Unable to view all bookmarked commands inside warp. I assume bookmarking is something like saving commands for future purposes. 

If my assumption is wrong, it would be great if we can save commands and look through it in future kind of list.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting! We already have a request tracking this over at #3120 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
