### ISSUE TITLE
"np" breaks (up and down arrows do nothing) in the tool

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#312]
### Describe the bug

```shell
I can no longer use the popular tool np (see https://github.com/sindresorhus/np), which requires me to make some selections by pressing up or down arrow.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```shell
Just works in Iterm and Hyper
```

**Comment by dannyneira** [comment]
I suspect this may have to do with a lack of subshell support. https://github.com/warpdotdev/warp/issues/64

Closing as dup.
