### ISSUE TITLE
GPT3.5/4 API Support for Warp AI

### ISSUE THREAD

**Issue by SueGK** [warpdotdev/Warp#3122]
### Describe the solution you'd like?

```Text
It would be a valuable addition to the Warp AI feature if users were given the option to select between the GPT-3.5 and GPT-4 API tokens. This would provide greater flexibility and customization
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Warp uses GPT 3.5 for Warp AI.

We have a request tracking using your own OpenAI API tokens over at #2788 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
