### ISSUE TITLE
ssh connection fails

### ISSUE THREAD

**Issue by mryzl** [warpdotdev/Warp#3124]
### Describe the bug

I can ssh to a beaglebone black running QNX using Mac terminal but not using Warp.

### To reproduce

Local host: MacOS 13.3.1 (a)
Remote host: Beaglebone Black, QNX sabre6sx-01 7.0.0 2017/06/13-10:38:51EDT AM335X_BeagleBone armle

ssh -l user IP
user@IP's password:
sh: syntax error: `(' unexpected
Connection to IP closed.

using MacOS terminal it works OK. QNX seems to use ksh:
sh -l user IP
user@IP's password: 
#

### Expected behavior

ssh should succeed

### Operating system

MacOS

### Operating system and version

13.3.1

### Current Warp version

v0.2023.05.18.01.08.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Appreciate you letting us know @mryzl We'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
You should be able to resolve this by changing the remote machines shell to a supported bash/zsh/fish with
`chsh -s $(which bash/zsh/fish)`
 Let me know if that helped resolve the issue.

**Comment by mryzl** [comment]
It would probably help but neither of the shells listed above is available on this particular builds of QNX. It is not a big issues though. Thanks

**Comment by dannyneira** [comment]
No worries, you can also disable the SSH Wrapper as a workaround, but ideally install a supported shell on the remote machine and it should work with the Wrapper. Is this issue okay to close since we know the cause of the error?

**Comment by mryzl** [comment]
Ok, to close it. Thanks for your support.
