### ISSUE TITLE
Alias Expansion not working as expected

### ISSUE THREAD

**Issue by roryfahy** [warpdotdev/Warp#3129]
### Describe the bug

An alias that works just fine when not expanded by warp does not get correctly expanded.
```bash
alias glol='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'
```
this alias should log formatted commits on one-line each however, it is expanded by warp to.
```bash
git log --graph --pretty=\%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset\
>
zsh: no matches found: -%C(auto)%d%Creset
``` 

### To reproduce

1. enable alias expansion
2. define this alias 
```
alias glol='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'\'
```
3. run it

### Operating system

MacOS

### Operating system and version

13.3.1

### Shell Version

zsh --version zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @roryfahy I'll let the engineer that worked on this feature know and we'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Hey Folks, This issue has been resolved as of the latest version of Warp.

Closing as resolved, but please let us know if the issue persists.
