### ISSUE TITLE
Implement integration with ChatGPT

### ISSUE THREAD

**Issue by Jricard0** [warpdotdev/Warp#3130]
### Describe the solution you'd like?

```Text
Implement integration with ChatGPT, to get more assertive solution for an issue. The main idea is:
- Have a button (or any stuff like this) to call the assistant 
- Assistant read all prompt content (previous stdin, stderr and stdout), then call ChatGPT API with summarized problem
- ChatGPT returns a possible solution


- extra: to force user to contribute with this feature, the user needs to provide a feedback of the returned solution to keep using warp (neither can skip or open a new tab)
```

### Is your feature request related to a problem? Please describe.

```Text
No, it's just a product improvement
```

### Additional context

If you guys want for more information, reach me on twitter: twitter.com/xJricard

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

Ignore

**Comment by dannyneira** [comment]
Thanks for submitting @Jricard0! 

Warp has a ChatGPT integration called Warp AI based on OpenAI's GPT 3.x API. Please learn more about the feature here:

https://docs.warp.dev/features/warp-ai
https://www.warp.dev/warp-ai

Closing as the ChatGPT integration already exists in Warp.
