### ISSUE TITLE
Keyboard malfunction while opening a new window

### ISSUE THREAD

**Issue by xii-kii** [warpdotdev/Warp#3132]
### Describe the bug

while i open a new window, the punctuation marks on the keyboard always(not 100% times, but always) not working, incluses `space` or `/`,which really troubling me.

### To reproduce

1.open a new window with “⌘+N” & which direct to Home dictionary.
2.type `cd+space`

space doesn't working

### Expected behavior

space working

### Operating system

MacOS

### Operating system and version

13.3.1 (a) 

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by xii-kii** [comment]
I could solve it temporarily double clicking shift

**Comment by dannyneira** [comment]
Thank you for bringing this issue to our attention, @xii-kii. We apologize for any inconvenience it may have caused.

We will provide updates on this thread as we make progress. Please note that this may be related to a lack of International keyboard shortcut support, #341.

If you are also experiencing the same issue, please consider adding a 👍 to the original post at the top or comment with your details. Your input will help us gather more information and prioritize the resolution. Furthermore, if you would like to receive notifications about any updates or developments related to this issue, please click on the subscribe button.

Once again, we apologize for the inconvenience and appreciate your understanding. Thank you for your patience as we work to resolve this.

**Comment by xii-kii** [comment]
I encountered this problem while using SougouInput in English mode, possibly due to it not adhering to the standard US-QWERTY. However, when I tried another input method, the issue did not occur.
