### ISSUE TITLE
Warp not able run .bash_profile file properly

### ISSUE THREAD

**Issue by UdayKiranPadhy** [warpdotdev/Warp#3133]
### Discord username (optional)

GoodBoy#8416

### Describe the bug

I have placed my own dotfiles which are included in .bash_profile file , my normal terminal is able to work properly but seems like Warp is unable to process that file . I have included both the screenshots how it looks like in normal terminal and how it looks in Warp .

Also including my .dot files so you can try to reproduce

```
cat .bash_profile
# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH";

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,bash_prompt,exports,aliases,functions,extra}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# Add tab completion for many Bash commands
if which brew &> /dev/null && [ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]; then
	# Ensure existing Homebrew v1 completions continue to work
	export BASH_COMPLETION_COMPAT_DIR="$(brew --prefix)/etc/bash_completion.d";
	source "$(brew --prefix)/etc/profile.d/bash_completion.sh";
elif [ -f /etc/bash_completion ]; then
	source /etc/bash_completion;
fi;

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

```

This is my .bash_prompt file 
```

cat .bash_prompt
#!/usr/bin/env bash


if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
	export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
	export TERM='xterm-256color';
fi;

prompt_git() {
	local s='';
	local branchName='';

	# Check if the current directory is in a Git repository.
	git rev-parse --is-inside-work-tree &>/dev/null || return;

	# Check for what branch we’re on.
	# Get the short symbolic ref. If HEAD isn’t a symbolic ref, get a
	# tracking remote branch or tag. Otherwise, get the
	# short SHA for the latest commit, or give up.
	branchName="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
		git describe --all --exact-match HEAD 2> /dev/null || \
		git rev-parse --short HEAD 2> /dev/null || \
		echo '(unknown)')";

	# Early exit for Chromium & Blink repo, as the dirty check takes too long.
	# Thanks, @paulirish!
	# https://github.com/paulirish/dotfiles/blob/dd33151f/.bash_prompt#L110-L123
	repoUrl="$(git config --get remote.origin.url)";
	if grep -q 'chromium/src.git' <<< "${repoUrl}"; then
		s+='*';
	else
		# Check for uncommitted changes in the index.
		if ! $(git diff --quiet --ignore-submodules --cached); then
			s+='+';
		fi;
		# Check for unstaged changes.
		if ! $(git diff-files --quiet --ignore-submodules --); then
			s+='!';
		fi;
		# Check for untracked files.
		if [ -n "$(git ls-files --others --exclude-standard)" ]; then
			s+='?';
		fi;
		# Check for stashed files.
		if $(git rev-parse --verify refs/stash &>/dev/null); then
			s+='$';
		fi;
	fi;

	[ -n "${s}" ] && s=" [${s}]";

	echo -e "${1}${branchName}${2}${s}";
}


# PS1 is the promt message in terminal eg. ukpadhy@GSHYD-C02FD2C9MD6M ~
# tput starts coloring the text in the terminal
# Check out 256 color codes charts for more colors
# tput sgr0 reset the color to default

if tput setaf 1 &> /dev/null; then
	tput sgr0; # reset colors
	bold=$(tput bold);
	reset=$(tput sgr0);
	# Solarized colors, taken from http://git.io/solarized-colors.
	black=$(tput setaf 0);
	blue=$(tput setaf 33);
	cyan=$(tput setaf 37);
	green=$(tput setaf 64);
	orange=$(tput setaf 166);
	purple=$(tput setaf 125);
	red=$(tput setaf 124);
	violet=$(tput setaf 61);
	white=$(tput setaf 15);
	yellow=$(tput setaf 136);
else
	bold='';
	reset="\e[0m";
	black="\e[1;30m";
	blue="\e[1;34m";
	cyan="\e[1;36m";
	green="\e[1;32m";
	orange="\e[1;33m";
	purple="\e[1;35m";
	red="\e[1;31m";
	violet="\e[1;35m";
	white="\e[1;37m";
	yellow="\e[1;33m";
fi;


# Highlight the hostname when connected via SSH.
if [[ "${SSH_TTY}" ]]; then
	hostStyle="${bold}${red}";
else
	hostStyle="${yellow}";
fi;

# Set the terminal title and prompt.
PS1="\[\033]0;\W\007\]"; # working directory base name
PS1+="\[${bold}\]\n"; # newline
PS1+="\[${userStyle}\]\u"; # username
PS1+="\[${white}\] at ";
PS1+="\[${hostStyle}\]\h"; # host
PS1+="\[${white}\] in ";
PS1+="\[${green}\]\w"; # working directory full path
PS1+="\$(prompt_git \"\[${white}\] on \[${violet}\]\" \"\[${blue}\]\")"; # Git repository details
PS1+="\n";
PS1+="\[${white}\]\$ \[${reset}\]"; # `$` (and reset color)
export PS1;

PS2="\[${yellow}\]→ \[${reset}\]";
export PS2;


```

Happy to cooperate with you . My personal email :- kiranu941@gmail.com

<img width="835" alt="Screenshot 2023-05-27 at 8 30 26 AM" src="https://github.com/warpdotdev/Warp/assets/58071209/fd1acdcc-0a47-48ea-8f9b-4605928dda31">
<img width="1792" alt="Screenshot 2023-05-27 at 8 30 44 AM" src="https://github.com/warpdotdev/Warp/assets/58071209/e632abbc-b75f-499b-b0a6-d87b0887f69e">

### To reproduce

Read the Description .

### Expected behavior

It should work as normal Terminal does.

### Operating system

MacOS

### Operating system and version

13.4.0

### Shell Version

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22) Copyright (C) 2007 Free Software Foundation, Inc.

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @UdayKiranPadhy Thanks for submitting a detailed bug report. Unfortunately, I wasn't able to reproduce the issue on my machine with the bash_profile you provided, I even added the code to the end of my .bashrc file with no issues. Maybe you can try the same on your end as well to see if you can run prompt_git function as I was able to.

![CleanShot 2023-05-30 at 16 23 07](https://github.com/warpdotdev/Warp/assets/16809145/90de134c-1cc6-48b2-8db2-b3567ff33cb5)

If you can't get the prompt to work, I recommend you check your bashrc and bash_profile to make sure there are no other conflicting functions/plugins/tools. You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```
We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

If the issues persist, you may want to look into a [custom prompt tool](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table) like starship.rs, as it lets you easily set up a similar prompt that just works out of the box with Warp.

**Comment by UdayKiranPadhy** [comment]
Hey @dannyneira  I am pretty sure on my side , i have rechecked it on my end . Would it be possible for you to jump on a call (zoom or gmeet) and assist me since i can share my screen ? If needed i can pay for you on hourly basis.

**Comment by dannyneira** [comment]
You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo '\nBASH_ENV=/' >> ~/.bash_profile`
This forces bash to run with zero configs.

**Comment by dannyneira** [comment]
Any luck with the above step?

**Comment by dannyneira** [comment]
Closing as no response from user, Please feel free to reopen if the issue persists with the above troubleshooting steps.
