### ISSUE TITLE
SSH to Windows 11 not working

### ISSUE THREAD

**Issue by galvesribeiro** [warpdotdev/Warp#3134]
### Describe the bug

Using the latest version of Warp SSH doesn't work.

### To reproduce

1. Get a fresh Windows 11 box
2. Enable OpenSSH server in it
3. Try to SSH from a MacOS box using Warp
4. After enter the password, it will just write empty lines on Warp terminal and return back to the prompt not connecting to the target Windows 11 machine.

### Expected behavior

It should be able to connect properly. The Terminal app connects just fine to the same box.

### Operating system

MacOS

### Operating system and version

13.3.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thank you for notifying us, @galvesribeiro.

We are actively tracking this issue at #2413. We kindly request that if you are also experiencing the same bug, please provide a 👍 and comment on that thread. Your participation will help us understand the impact of the issue and prioritize our efforts accordingly.

As this feature request duplicates the existing thread, we will be closing it. However, rest assured that we are committed to resolving the issue and appreciate your involvement in helping us improve.

Thank you for your understanding and continued support.
