### ISSUE TITLE
Global hotkeys cannot be used in chinese input methods

### ISSUE THREAD

**Issue by zhaohuanyuu** [warpdotdev/Warp#3136]
### Describe the solution you'd like?

```Text
1.Whether it can automatically switch to the English input method when the hotkey is triggered
2.The cmmand + `(BACKTICK) combination is not currently supported. Can it be supported in the future?
```

### Additional context

**To reproduce**
1. open one warp window
2. switch Chinese input method
3. display windows with custom hotkey

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @

We already have a request tracking this over at #341 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
