### ISSUE TITLE
Cursor cutoff when waiting for Node script to run

### ISSUE THREAD

**Issue by philecker** [warpdotdev/Warp#3137]
### Discord username (optional)

philecker#7769

### Describe the bug

I'm running a Node script that takes about 25 seconds to execute, when I run the command, I notice the cursor gets cutoff the bottom of the screen. I'm using JetBrains Mono font (14) with 1.3 line spacing. I'm also using the default input position. 

### To reproduce

Run a script that takes a while to complete, and cursor gets cut off while it's running.

### Expected behavior

I would expect the cursor would fully display.

### Screenshots

<img width="435" alt="Screenshot 2023-05-27 at 3 38 30 PM" src="https://github.com/warpdotdev/Warp/assets/274869/35849861-edd4-4018-95c1-02211537c822">
<img width="366" alt="Screenshot 2023-05-27 at 3 39 02 PM" src="https://github.com/warpdotdev/Warp/assets/274869/826fca2e-7998-42ca-ba49-350b87f2910b">

### Operating system

MacOS

### Operating system and version

macOS 13.3.1 (a) 

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @philecker Pardon the late reply, but can you still reproduce this in the most recent version of Warp `v0.2023.05.30.08.03.stable_03`? We suspect this may have been resolved with recent fixes so just wanted to confirm.

**Comment by philecker** [comment]
Hey @dannyneira I think I may have created the bug by creating a custom theme or it's because of the font I'm using. Not sure how to correct it, I guess I'll try a different font.

**Comment by philecker** [comment]
So it appears to be an issue with line height. I switched back to the default font and still had the same issue, I noticed though if I changed the line height from my custom "1.5" to "1", it displays as expected.

**Comment by dannyneira** [comment]
ack, thanks for letting us know, any updates on this issue will be posted on the thread.

**Comment by elviskahoro** [comment]
This should be fixed! Please comment / re-open if not!
