### ISSUE TITLE
Please update the Global Hotkey Documentation 

### ISSUE THREAD

**Issue by OldSubSailor** [warpdotdev/Warp#3139]
### Describe the solution you'd like?

```Text
https://docs.warp.dev/features/windows

This window documentation is out of date and does not match the current version of Warp and needs to be updated in order to be useful. Honestly, you need to delete this particular documentation, it is a waste of bandwidth or at least add a disclaimer stating what version that it is actually useful for.
```

### Is your feature request related to a problem? Please describe.

```Text
I can not see how to make Global Hotkeys reading the page or watching the video. Nothing matches Warp v0.2023.05.23.08.05.stable_00. And evidently this is the only way that I can resize the window and keep the resize to stay.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @OldSubSailor thanks for letting us know. We tweaked some of the docs to show that the feature has changed. Updated the demos and docs to be a bit more clear on the features.

Closing as the changes have been made to the docs.
