### ISSUE TITLE
Venv flag not appearing

### ISSUE THREAD

**Issue by divyranjan17** [warpdotdev/Warp#3141]
### Discord username (optional)

heisenberg#1060

### Describe the bug

I am not getting the virtual environment flag i.e. (venv) in front of current working directory even after turning on virtual environment. Please refer to the screenshot

### To reproduce

1. Create virutalenvironment using virtualenv venv with python installed
2. Run source/venv/bin/activate

### Expected behavior

A venv flag should appear on left side of the directory

### Screenshots

<img width="477" alt="Screenshot 2023-05-28 at 9 16 05 PM" src="https://github.com/warpdotdev/Warp/assets/28673644/ffcb783c-19d0-45ed-91b8-2166408a2eac">

### Operating system

MacOS

### Operating system and version

Ventura 13.3.1(a)

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by anloubie2** [comment]
I am having this issue as well since today, it worked perfectly before

**Comment by george-jensen** [comment]
I am also having this issue.

**Comment by dannyneira** [comment]
Thanks for letting us know @divyranjan17. 

We're tracking this issue over at #3140  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
