### ISSUE TITLE
Warp initialization command included in history

### ISSUE THREAD

**Issue by pecasdev** [warpdotdev/Warp#3147]
### Describe the bug

I see this in my shell when I hit space, I'm guessing that this is the "behind-the-scenes" code that starts up warp
<img width="933" alt="image" src="https://github.com/warpdotdev/Warp/assets/33271004/e23b5a26-9bf5-4edc-8866-390cdad453bb">

### To reproduce

1. Create a new terminal
2. Press space (note that it's possible you may have to do something else for this command to appear in the history. Something I tried recently was warpifying a shell, that could possibly have something to do with it
3. Observe that the included image appears in your shell history, despite you never having executed that command yourself

### Expected behavior

Commands not executed by the user should not appear in the shell history

### Operating system

MacOS

### Operating system and version

Monterey 12.6.3

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by zachbai** [comment]
Hey @pecasdev -- thanks for filing. I'll have a fix for this in this weeks release.

**Comment by zachbai** [comment]
This should be fixed, so marking as closed. If you do happen to reencounter the issue please feel free to re-open and tag me.
