### ISSUE TITLE
(.venv) is not displayed after activating the python virtual environment

### ISSUE THREAD

**Issue by j1philli** [warpdotdev/Warp#3148]
### Describe the bug

Before the recent update when I activated a virtual environment it would display that is was activated like this.
![CleanShot 2023-05-29 at 19 45 54](https://github.com/warpdotdev/Warp/assets/3744255/361e26ab-7f25-4dc0-9363-9fb111e8b04f)
Now it does not do that
![CleanShot 2023-05-29 at 19 47 18](https://github.com/warpdotdev/Warp/assets/3744255/535e8b89-c5e2-4bf3-8674-5239c308c04d)

### To reproduce

run 'source path/to/virtual/env/bin/activate'
There is not a visual indicator anymore for that the environment is activated

### Operating system

MacOS

### Operating system and version

13.3.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

May 28th, 2023

### Additional context

Works as expected in Terminal
![CleanShot 2023-05-29 at 19 54 09](https://github.com/warpdotdev/Warp/assets/3744255/80efba47-cf02-45e4-b32d-c7d5f8708e38)

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by george-jensen** [comment]
Also having this issue.

**Comment by divyranjan17** [comment]
Opened the same issue here - https://github.com/warpdotdev/Warp/issues/3141
