### ISSUE TITLE
Alias expansion not working with alias 'venv'

### ISSUE THREAD

**Issue by Ragura** [warpdotdev/Warp#3150]
### Describe the bug

I have an alias called `venv`, set like this:
`alias venv="source .venv/bin/activate"`

The alias doesn't expand when typing `venv` followed by a space.

There is no command called `venv` on the system, so it shouldn't trigger the exception in the docs: `Aliases will not be expanded when the command in the expanded form is the same as the alias itself. e.g. if you have an alias ls='ls -G', ls will not be expanded in the input editor.`

On thing to note is that when typing `venv`, the autocomplete menu pops up with commands related to `nvm` because of fuzzy search. Perhaps it has something to do with that?

### To reproduce

`alias venv="source .venv/bin/activate"`
Try expanding the alias afterwards.

### Expected behavior

It should expand the alias fully.

### Operating system

MacOS

### Operating system and version

Venture 13.4

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by Ragura** [comment]
It seems I must apologize. I'm not well versed in zsh workings and assumed that simply running `alias venv="source .venv/bin/activate"` in the terminal would create the alias like I was expecting, but it seems that line needed to be added to my `.zshrc` file. Now that I've done that, it works perfectly. Sorry for the confusion!

**Comment by dannyneira** [comment]
No worries @Ragura, thanks for letting us know!
