### ISSUE TITLE
Warpifying the shell will un-do virtual env set by `poetry shell`

### ISSUE THREAD

**Issue by jssln** [warpdotdev/Warp#3151]
### Describe the bug

See reproduction steps.

### To reproduce

Setup:
Created a [python Poetry](https://python-poetry.org/) project.

From a not-yet-Warpified terminal: 
1. Ran `poetry shell`
Ran diagnostic: 
    * command: `which python`
    * output: `/Users/me/Library/Caches/pypoetry/virtualenvs/learn-poetry-2up0dSRq-py3.8/bin/python`

2. Clicked "Warpify subshell" button. Saw the success message ("Success! This subshell spawned by poetry shell has been Warpified.") Saw the UI change to be Warp-ified.
Ran diagnostic:
    * command: `which python`
    * output: `/usr/local/opt/python/libexec/bin/python`

### Expected behavior

I would expect the python version in the Warpified poetry subshell to be the one in the poetry virtual env.

### Operating system

MacOS

### Operating system and version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @jssln Thanks for surfacing this issue. Is it possible that you have two different versions of python installed? I got the same result when I ran `which python` within the poetry shell, "Warpified" or not. What result do you get when you just run `which python` / `which python3` in a normal zsh shell (outside of `poetry shell` )? 

If you see two different results that may be the reason why you see two different results, but we'd have to investigate why after Warpifying one is used vs the other.

**Comment by jssln** [comment]
@dannyneira Yeah I do!

`which python`
`/usr/local/opt/python/libexec/bin/python`

`which python3`
`/usr/local/bin/python3`

**Comment by elviskahoro** [comment]
@jssln this was launched today please comment if you're having any trouble with it
