### ISSUE TITLE
Custom workflow not showing up

### ISSUE THREAD

**Issue by NamekMaster** [warpdotdev/Warp#3156]
### Describe the bug

These are my custom workflow files, for the test.yaml and my_test_cmd.yml, I just copy a file from the official repo and change the name.
<img width="744" alt="image" src="https://github.com/warpdotdev/Warp/assets/11484722/7bc920c8-b2d4-4d6d-a070-51fb48a340a6">

I can't see anything when pressed crl+shift+r and select My Workflows as shown below:
<img width="707" alt="image" src="https://github.com/warpdotdev/Warp/assets/11484722/0d214c33-250a-4a12-b37f-413ce3345c2f">

### To reproduce

These are my custom workflow files, for the test.yaml and my_test_cmd.yml, I just copy a file from the official repo and change the name.
<img width="744" alt="image" src="https://github.com/warpdotdev/Warp/assets/11484722/7bc920c8-b2d4-4d6d-a070-51fb48a340a6">

I can't see anything when pressed crl+shift+R and select My Workflows as shown below:
<img width="707" alt="image" src="https://github.com/warpdotdev/Warp/assets/11484722/0d214c33-250a-4a12-b37f-413ce3345c2f">

### Expected behavior

My custom workflows should show

### Operating system

MacOS

### Operating system and version

Mac OS 13.4 (22F66)

### Shell Version

zsh 5.9 (arm-apple-darwin22.1.0)

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @NamekMaster, Sorry to hear about this, using the same [example yaml file from our repo](https://docs.warp.dev/features/entry/workflows). I was able to get it to show up by making sure the workflow file was in my local `~/.warp/workflows` directory. Make sure your workflow files are in that directory and that they don't have any syntax errors. See more about [Workflows in our docs](https://docs.warp.dev/features/entry/workflows). 

![CleanShot 2023-05-31 at 14 24 50](https://github.com/warpdotdev/Warp/assets/16809145/f01d66d3-17b9-4518-8720-140617a9d5be)

I hope this helps! Let me know if the issue persists or if not, please close this issue.

**Comment by NamekMaster** [comment]
@dannyneira Thanks for your help, they are showed after I enable full disk access. But I can read or modify those files inside warp, why should I grant full disk access? When I access some folder, there is also a system popup asking for permission.

**Comment by dannyneira** [comment]
You may need to fully restart the app to apply for permissions, is this issue okay to close since it was a permission problem?

**Comment by dannyneira** [comment]
Closing as this appears to be a permissions issue. feel free to let me know if the issue persists.
