### ISSUE TITLE
zsh: no matches found: -%C(auto)%d%Creset

### ISSUE THREAD

**Issue by screw-hand** [warpdotdev/Warp#3158]
### Describe the bug

The `oh-my-sh` provides a `git` plugin that includes the `glols` alias command. This alias command works fine in the default terminal on macOS, but it throws an error when used in Wrap. The same error is occurring with the `glola` command.

### To reproduce

1. install the [oh-my-zsh](https://ohmyz.sh/)
2. edit `~/.zshrc` to cofing plugin: `plugins=(git node npm)`
3. open the Wrap
4. type `glols`/`glola` will get the error 

### Screenshots

<img width="1512" alt="image" src="https://github.com/warpdotdev/Warp/assets/26453811/5fb09c1f-f17c-4a70-81ec-5110903617a9">

<img width="585" alt="image" src="https://github.com/warpdotdev/Warp/assets/26453811/fba7a2c6-14a5-47c2-905c-a400a416fbad">

### Operating system

MacOS

### Operating system and version

MacOs 13.2.1 (22D68)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp-specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, only happens in Warp and not in other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @screw-hand 

We're tracking this issue over at #554 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
