### ISSUE TITLE
Unexpected prefix in Git branch completion on Fish shell

### ISSUE THREAD

**Issue by pan93412** [warpdotdev/Warp#3161]
### Discord username (optional)

pan93412#7826

### Describe the bug

Warp always adds `P$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "fish"}}*` before the completion of `main` branch.

<img width="793" alt="image" src="https://github.com/warpdotdev/Warp/assets/28441561/85017744-b9b2-445f-ae86-afaa3702e97b">

The unexpected prefix were also showed in the final result:

<img width="593" alt="image" src="https://github.com/warpdotdev/Warp/assets/28441561/7a5de33b-a27b-41af-955a-fd932bba4e0e">

Note that I have appended the hook in the `.config/fish/config.fish` according to [Subshells - Warp Documentation](https://docs.warp.dev/features/subshells):

```
67   │ printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shel
       │ l": "fish"}}\x9c'ash
```

### To reproduce

1. Start `fish` shell and switch to a Git repository
2. Type `git checkout`, then <kbd>Tab</kbd>
3. You may see the completion with a broken `main` entry.

### Expected behavior

I expected `main` shows as `main`.

### Operating system

MacOS

### Operating system and version

macOS Ventura 13.4

### Shell Version

fish, version 3.6.1

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thank you for your update, @pan93412 We will provide any updates regarding this matter through this thread.

To show your support for this issue, please add a 👍 to the original post at the top or comment with your details if you are also experiencing the same problem. Additionally, if you wish to receive notifications about any updates related to this issue, please click on the subscribe button.

Your engagement and feedback are highly appreciated as we work towards addressing and resolving this issue. If you have any further questions or need assistance, please don't hesitate to reach out.

**Comment by zachbai** [comment]
Hey @pan93412, 

Can you try updating your `config.fish` to wrap the RC file snippet in an if-condition like so:

```
if status is-interactive
  printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "fish"}}\x9c'
end
```

I think the issue here is the background `fish` process used to generate completion results is also executing the RC file snippet, which is inadvertently treated as a completion result

**Comment by pan93412** [comment]
> 

<img width="815" alt="image" src="https://github.com/warpdotdev/Warp/assets/28441561/4190c5c5-ace4-4579-b526-47ea54367dc2">

Seems work!

**Comment by zachbai** [comment]
@pan93412 Thanks for the quick feedback! We'll update our docs for the fish RC file change.

**Comment by xxnuo** [comment]
I encountered a similar issue, a new Debian system, using bash and added Warp prompt commands in .bashrc following the warp instruction
```
echo -e '\n# Auto-Warpify\nprintf '\''\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "bash", "uname": "'$(uname)'" }}\x9c'\'' ' >> ~/.bashrc
```

then set up Docker on my Mac to connect to this Debian server, but Docker reported an error.
```
Server:
ERROR: error during connect: Get "http://docker.example.com/v1.47/info": net/http: HTTP/1.x transport connection broken: malformed HTTP status code "\"SourcedRcFileForWarp\","
errors pretty printing info
```

Use
```
echo -e '\n# Auto-Warpify\nif status is-interactive\n  printf '\''\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "bash", "uname": "'$(uname)'" }}\x9c'\'' ' >> ~/.bashrc
echo -e '\nend' >> ~/.bashrc
```
Login have errors, how to fix it and make Docker remote ok?
