### ISSUE TITLE
Can't download the App

### ISSUE THREAD

**Issue by MoElnaggar14** [warpdotdev/Warp#3166]
### Describe the bug

Failed to connect to app.warp.dev port 443 after 75005 ms: Couldn't connect to server

### To reproduce

try to open the download link

### Operating system

MacOS

### Operating system and version

Version 13.4

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by charlespierce** [comment]
Hi @MoElnaggar14, thanks for reporting! I'm not able to reproduce this at the moment—Is it consistent for you? We had a server deploy earlier today, is it possible you happened to hit the button right when things were switching and you got caught in an in-between state?

**Comment by MoElnaggar14** [comment]
https://app.warp.dev/get_warp return this page

<img width="1610" alt="image" src="https://github.com/warpdotdev/Warp/assets/21294763/2ceb2c0f-1906-4fd7-a3e9-29b8dd4a44b1">

**Comment by dannyneira** [comment]
Hey @MoElnaggar14, You may have a firewall/proxy/dns blocking the download. Do the following commands complete with no errors?

```
ping app.warp.dev -p 443
traceroute app.warp.dev
```

**Comment by dannyneira** [comment]
@MoElnaggar14 any luck with the above?

**Comment by MoElnaggar14** [comment]
Hey @dannyneira sorry for the late reply, I just got the notifications. 

YES, it's banned on Google DSN so I used `1.1.1.1` and it works
