### ISSUE TITLE
swipe gesture to switch tabs

### ISSUE THREAD

**Issue by singleoo** [warpdotdev/Warp#3167]
### Describe the solution you'd like?

```Text
now just can use command + tab number to switch，Touch Pad swipe gesture to switch tabs is cool and useful，hope to support ~~~
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @singleoo 

We already have a request tracking this over at #582 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
