### ISSUE TITLE
Scrolling doesn't work in screen

### ISSUE THREAD

**Issue by egoon** [warpdotdev/Warp#3170]
### Describe the bug

When i use `screen` command to run several processes in background, scolling stops working the way I expect. Instead of 'regular' window scrolling, it starts to cycle bash history. As if I use up and down arrows.

### To reproduce

Start a new screen with `screen` command. Then use scroll wheel on mouse or scroll function on touchpad.

### Expected behavior

Window should scroll content.

### Operating system

MacOS

### Operating system and version

13.3.1

### Shell Version

GNU bash 5.2.15(1)-release (x86_64-apple-darwin22.1.0)

### Current Warp version

v0.2023.05.09.08.03.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I found the bug while using screen on a remote server via ssh, but when testing locally it is the same here.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @egoon 

We're tracking this issue over at #1629 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by chicheese** [comment]
Currently experiencing this exact bug on Ubuntu 24.04.02 LTS when ssh'd into one of my servers.
