### ISSUE TITLE
Adjustable scrollback lines w/ default value

### ISSUE THREAD

**Issue by charliegn** [warpdotdev/Warp#3173]
### Describe the solution you'd like?

>In the settings, provide a away to update the scrollback line numbers to what the user wants, while providing a default value out of the box.

### Is your feature request related to a problem? Please describe.

> I would like to increase the number of scrollback lines I can set. There are times where I have a massive amount of info getting sent to the console and currently with Warp I cannot go back to the beginning because of the unadjustable scrollback line quantity. VSCode and iTerm2 have solved this. I'm sure others are encountering this since it's a feature in other terminal apps. For myself, this is the only thing holding me back from going over to Warp full-time and never looking back!  Love what you're doing and you're SO close. Keep up the great work and looking forward to this enhancement.

### Additional context

**VSCode's Setting example**
![Screenshot 2023-06-02 at 1 47 26 PM](https://github.com/warpdotdev/Warp/assets/5805073/a1c671a5-99c9-4583-a6f6-92a7e171ad09)

**iTerm2 Scrollback example**
![Screenshot 2023-06-02 at 1 54 43 PM](https://github.com/warpdotdev/Warp/assets/5805073/025e4516-68e1-49a1-a2e7-5b3948fc0353)

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @charliegn

We already have a request tracking this over at #610. We're actively working on making it happen, no official ETA.

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
