### ISSUE TITLE
Getting "unterminated quoted string" error or ssh session closing after quoted command is executed

### ISSUE THREAD

**Issue by leoga8** [warpdotdev/Warp#3175]
### Discord username (optional)

Gaoo#0702

### Operating System

MacOS

### Operating System and Version

MacOS 13.4 (M2 Chip)

### Local Shell Version

5.9

### Remote Shell Version

Unsure due to device's nature (mobile router - could this be the issue?)

### Warp Version

v0.2023.05.30.08.03.stable_03

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/48166650/7bfbc3f7-03f7-420a-89c8-e7ec59f027e6)

### Include shell xtrace output

Don't have the device with me anymore to test this.

Same situation regarding: " I have tried commenting out my system & user rcfiles and warp still will not bootstrap" -> Can't try this right now (but the issue is not happening when ssh-ing to other devices)

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @leoga8 It's possible the remote shell isn't supported (bash/zsh/fish), you'd have to run `echo $SHELL` to confirm which one the remote machine is using. and if not supported, change it to a supported one with something like `chsh -s $(which bash/zsh/fish). 

Meanwhile, if the above workaround doesn't resolve the issue, you can disable the SSH wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabled, SSH should work as normal.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.
