### ISSUE TITLE
History polution

### ISSUE THREAD

**Issue by Micnubinub** [warpdotdev/Warp#3176]
### Describe the bug

Getting a lot of excess inputs in my history when a session ends

### To reproduce

Open a window run a command, then close it

### Screenshots

<img width="1456" alt="image" src="https://github.com/warpdotdev/Warp/assets/4921356/a6cc7753-852f-44a2-8978-476fe162b879">

### Operating system

MacOS

### Operating system and version

v0.2023.05.30.08.03.stable_03

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Current Warp version

v0.2023.05.30.08.03.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @Micnubinub Thanks for submitting. 

AFAIK, the extra items in history you see are part of the bootstrapping script that sets up features like Blocks, Autocompletion, etc. in Warp. I don't know if there is a way to stop those from showing up altogether, but as a workaround, you can clear all or delete individual items with the following commands:
`history -c`: Clears the entire history list.
`history -d {{n}}`: Deletes the command at line number `n` from the history list.

Let me know if that helps clear up why you're seeing the new lines in history.

**Comment by zachbai** [comment]
Hey @Micnubinub thanks for filing -- I should have a fix for this included in this week's release.

**Comment by dannyneira** [comment]
Hey Folks, This issue has been fixed in the latest version of Warp!

Closing as resolved, but please let us know if any further issues with bootstrap scripts in the history.
