### ISSUE TITLE
Do not autoscroll when you are scrolled up on the output but a new output is produced

### ISSUE THREAD

**Issue by jusunglee** [warpdotdev/Warp#3178]
### Describe the solution you'd like?

```Text
When I try to inspect a log line somewhere in the terminal history and a new log is produced, Warp will automatically scroll down. This makes it difficult to read the log history while the terminal is actively producing output. A good example is just running a simple server, and trying to inspect a request log, but the incoming requests force scrolls the window up so that you cannot actually read the contents.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @jusunglee There is a similar request here https://github.com/warpdotdev/Warp/issues/3160, are you able to reproduce the issue with the following? run `seq 0 10000`, then while you run `for i in {0..100}; do echo $i; sleep 1 ; done`, scroll up to one of the lines in the first `seq` block and see if the output is moved by the running `for` loop.

**Comment by dannyneira** [comment]
Any luck with the above steps @jusunglee ?

**Comment by dannyneira** [comment]
closing as no response, but please feel free to let us know if you were able to try the above steps and reliably reproduce the issue.
