### ISSUE TITLE
Tab completion for file names does not work for some commands

### ISSUE THREAD

**Issue by kieran-mace** [warpdotdev/Warp#3182]
### Describe the bug

Hitting tab does not autocomplete the file name if the terminal command is not something common. 

### To reproduce

# Setup
```
mkdir test_folder
cd test_folder
touch test.R
```

# Common command

type `cat tes` Now hit `[Tab]` → completes to `cat test.R`

# uncommon command

type `RScript test` Now hit `[Tab]` → does not complete

### Expected behavior

Tab completion should work. 

### Operating system

MacOS

### Operating system and version

Mac OS 13.4

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.30.08.03.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Appreciate you letting us know, we've been noticing reports of issues with completions and are working to prioritize a fix, so appreciate your patience. We'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by kieran-mace** [comment]
Disabling `Open completions as you type` fixed this issue for me (although I've now lost that functionality for now

Thank you!

**Comment by zachbai** [comment]
This issue should be fixed now so marking as closed. If you are still experiencing the issue, please feel free to re-open and ping.

**Comment by mspronk** [comment]
Not sure it this is a similar or related issue, but autocomplete on filenames seems to (stubbornly) prefer history over existing filenames.

Concrete example: if I have a directory with the files `foo1.bar`, `foo2.bar`, and `foo3.bar`,
and I type `rm foo`+TAB, it wil properly autocomplete, for example to `rm foo1.bar`.

However, after executing that, if I want to subsequently do an `rm` on the 2nd file, and type `rm foo`+TAB, it will autosuggest the historic `rm foo1.bar`. And I see no way to make it think otherwise.

**Comment by tomaszmi** [comment]
touch + autocomplete still does not work for me (v0.2024.11.12.08.02.stable_02)

How to reproduce:

1) prepare test data:
```
$ mkdir warp_test
$ cd warp_test
$ touch Foo.txt
$ touch Bar.txt
$ mkdir foodir
$ ls -l
total 0
-rw-r--r--  1 me  staff   0 Nov 21 10:32 Bar.txt
-rw-r--r--  1 me  staff   0 Nov 21 10:31 Foo.txt
drwxr-xr-x  2 me  staff  64 Nov 21 10:36 foodir
```
2) issue 1:
```
touch Bar<hit-the-tab>
```
nothing happens. I see a suggestion Bar.txt but I would need to press right arrow to have it completed - typing tab does not work.
3) issue 2:
```
touch Foo<hit-the-tab>
```
Hitting tab in the above example does not complete `Foo.txt`, instead it replaces `Foo` with `foodir`

**Comment by jakelauer** [comment]
> Not sure it this is a similar or related issue, but autocomplete on filenames seems to (stubbornly) prefer history over existing filenames.
> 
> Concrete example: if I have a directory with the files `foo1.bar`, `foo2.bar`, and `foo3.bar`, and I type `rm foo`+TAB, it wil properly autocomplete, for example to `rm foo1.bar`.
> 
> However, after executing that, if I want to subsequently do an `rm` on the 2nd file, and type `rm foo`+TAB, it will autosuggest the historic `rm foo1.bar`. And I see no way to make it think otherwise.

I'm seeing this as well. In a normal Terminal, I can hit tab for file suggestions that begin with what I've typed so far and it'll show me the list of matching files. Not only does Warp not do this, it only provides me the option to run the command from history if what I've typed so far matches something I've run before.

**Comment by Dazag** [comment]
To me, when I am doing SSH to another machine, if I rename a file, like a docker-compose.yml file to a compose.yml and then try to run $> git add compose.yml, if I press TAB or anything to autocomplete, it will point to compose.yml files in another directory!!
