### ISSUE TITLE
Prompt block is duplicated on every command when using a custom prompt engine

### ISSUE THREAD

**Issue by Viijay-Kr** [warpdotdev/Warp#3185]
### Discord username (optional)

ReactPoriyaalar

### Describe the bug

The prompt block is duplicated at least twice for every command when the prompt engine is set to 
ohmyposh.dev.

Not sure if this a bug in warp or bug in ohmyposh but this started happening since the latest update 

### Warp version
v0.2023.05.30.08.03.stable_03 

### Prompt engine
* [oh my posh](https://ohmyposh.dev/)
* Theme - custom theme

### Operating System
* Mac OS ventura 13.4

> NOTE: This issue does not happen with default prompt engine of warp nor does it happen in mac os terminal  

### To reproduce

1.Open warp with oh-my-posh set as prompt engine in .zshrc using 
`eval "$(oh-my-posh init zsh --config ~/.oh-my-posh.json)"`
2. Type any command 
3. Observe the output of the command has additional two or more blocks below it 

### Expected behavior

1.Open warp with oh-my-posh set as prompt engine in .zshrc using
eval "$(oh-my-posh init zsh --config ~/.oh-my-posh.json)"
2. Type any command
3. The window should not have any additional blocks after the command output

### Screenshots

https://github.com/warpdotdev/Warp/assets/8697234/a3cda668-11d1-4129-b364-9c1c98f9e848

### Operating system

MacOS

### Operating system and version

Ventura 13.4

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.30.08.03.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

6.06.2023

### Additional context

Interestingly this does not happen when I open a new tab and work on it 

https://github.com/warpdotdev/Warp/assets/8697234/ba1562de-458c-441c-a8ba-0fbfa14ed41c

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @Viijay-Kr Thanks for letting us know, Does the issue with the new blocks persist after you close/reopen Warp or in any new Tabs/Windows/Panes? If so, could you please provide a copy of your custom prompt so we can try and reproduce the issue?

**Comment by Viijay-Kr** [comment]
The issue does not occur when I am open a new tab it only happens when I open a new warp window but today , I can't reproduce the issue again.

**Comment by dannyneira** [comment]
Any luck reproducing the issue again @Viijay-Kr ?

**Comment by dannyneira** [comment]
Closing as no response from the user, but if you can provide a redacted copy of your `.zshrc` file this will help us in reproducing the issue.
