### ISSUE TITLE
`^D` shortcut for `exit` does not register inside Warpified subshells

### ISSUE THREAD

**Issue by llam15** [warpdotdev/Warp#3186]
### Describe the bug

I commented on #64 a few weeks ago: https://github.com/warpdotdev/Warp/issues/64#issuecomment-1554692003

> When I'm in a subshell of my subshell, such as running python manage.py inside of a docker exec, the ^D shortcut for exit does not seem to register. I can only exit the sub-sub-shell by typing exit() explicitly.

### To reproduce

Specifically,  the first bullet point can be replicated as follows:
1. Warpify the subshell spawned by `docker compose exec -it my-container bash`
2. Open the python REPL with `python`
3. Attempt to exit the REPL with `^D`

### Expected behavior

At step 3, I expect `^D` to close the python REPL, and return me to the Warpified `bash` session inside the Docker container. Instead it does not register and the REPL can only be exited with `exit()`.

### Operating system

MacOS

### Operating system and version

Mac OS 13.4 (22F66)

### Shell Version

5.1.4(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2023.05.30.08.03.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

Loving the Warpify capabilities, thanks again for all the hard work!

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know, I'm aware you were asked to create a [separate issue](https://github.com/warpdotdev/Warp/issues/64#issuecomment-1582597069) so appreciate it. In general, we are tracking support for non-shell-based REPLs in this thread here #64, we'll post anygeneral updates on that thread. 

Anything specific to your issue will be posted here.

**Comment by dannyneira** [comment]
Hey @llam15 We're unable to reproduce this issue, can you please try this again to see if the bug persists? If so, please provide details on the type of image you're using in docker ( OS & version ) as well as the version of python. It may only be affecting a specific combination, for example, I failed to reproduce on `Ubuntu 22.04.3 LTS` & `python 3.10.12`.

**Comment by llam15** [comment]
Hmm I am no longer able to reproduce this anymore either! (I'm on Warp version `v0.2024.01.16.16.31.stable_01` now). So I'm going to close this issue as resolved. Thanks for looking into it!
