### ISSUE TITLE
console shows undesirable suggestions

### ISSUE THREAD

**Issue by GianlucaP106** [warpdotdev/Warp#3190]
### Describe the bug

The console suggests commands that likely ran internally and not by the user (image below)

<img width="2276" alt="image" src="https://github.com/warpdotdev/Warp/assets/93693693/c9b36184-5bca-4e86-873b-060c3e4df571">

version: v0.2023.06.06.08.02.stable_00

### To reproduce

Simply start typing after shell start up

### Expected behavior

Should not see suggested commands user has not ran

### Screenshots

<img width="2276" alt="image" src="https://github.com/warpdotdev/Warp/assets/93693693/c9b36184-5bca-4e86-873b-060c3e4df571">

### Operating system

MacOS

### Operating system and version

13.4.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.06.06.08.02.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Tuesday June 6th 2023

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
hey @GianlucaP106  We're tracking this here: https://github.com/warpdotdev/Warp/issues/3176

Please give that issue a subscription to track it. We're working on a fix and will post updates there.
