### ISSUE TITLE
Software Update Always Opens A New Application

### ISSUE THREAD

**Issue by seanlynch7194** [warpdotdev/Warp#3192]
### Describe the solution you'd like?

```Text
The same app in my dock should reopen after a software update
```

### Is your feature request related to a problem? Please describe.

```Text
I'm always frustrated when Warp prompts me to update the version and when the app restarts a new app icon in my dock opens, not the one that I keep in the dock, so there are now 2 Warp icons in in the dock. I need to quit the newly opened app and click on the usual icon in my dock.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Appreciate you letting us know @seanlynch7194 

We're tracking this issue over at #2824  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
