### ISSUE TITLE
Single-click on pane to activate it when coming from another app

### ISSUE THREAD

**Issue by cdcasey** [warpdotdev/Warp#3194]
### Describe the solution you'd like?

```Text
When clicking into Warp when it has a split-pane:
* when I click on an inactive pane, I want it to become immediately active instead of having to click on it again
```

### Is your feature request related to a problem? Please describe.

```Text
I normally use a split-pane terminal. Currently, if I'm working in another window and I want to click over to Warp, when I click on an inactive pane the Warp window becomes active, but the pane does not. I have to click again in order to active the pane I want to use.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @cdcasey 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/739

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
