### ISSUE TITLE
less search matches do not highlight

### ISSUE THREAD

**Issue by sdhull** [warpdotdev/Warp#3196]
### Describe the bug

When searching for a term in `less`, matches are not highlighted.

### To reproduce

Open a large file using `less`. Type `/something` to search for "something" (but replace "something" with a word that actually appears in the file.

You'll notice that while the search works and finds matches, it does not highlight them. At first I thought I had weird default options for less, but highlights work fine in other terminals with the same options.

### Expected behavior

When searching in `less`, it should highlight matches

### Operating system

MacOS

### Operating system and version

13.4

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.06.06.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @sdhull Sorry about this blocker. I'm not seeing the same on my end `/something` highlights the results in less. It is possible you have a theme, transparency, or some other setting that could be causing this. Could you provide a video/screenshot of the issue so we can see what's happening?

Also as a workaround, you can try CMD-F to find within a less page, as you page up/down you can see the highlighted results.

https://github.com/warpdotdev/Warp/assets/16809145/32575e9d-0ef1-4d19-9b32-2cefd3f22871

**Comment by dannyneira** [comment]
@sdhull 
- Any luck reproducing the issue on a video? 
- Which Warp theme are you using ( or a custom theme)?

**Comment by dannyneira** [comment]
@sdhull Any luck with the above?

**Comment by dannyneira** [comment]
closing as no response, but please feel free to let us know if the above was helpful or if you can reliably reproduce the issue (along with video/screenshots preferably )
