### ISSUE TITLE
Two Essential Resources Remaining

### ISSUE THREAD

**Issue by ajmeireles** [warpdotdev/Warp#3197]
### Describe the solution you'd like?

```Text
The Warp terminal is an amazing thing, but I feel like it lacks too many things to make it my go-to terminal. I will list these things and I will also consider mentioning what for me would be something extremely necessary and something non-emergency, because I think that the terminal's team always seeks the users' satisfaction.

1. Tab Name *NECESSARY FOR ME!*
- Similar to iTerm2, it would be extremely helpful to be able to correct the tab names to prevent the current path/folder from being displayed as the tab name.

2. Standard terminal size *NECESSARY FOR ME!*
- Also similar to iTerm2, it would be extremely important for me to set the default initial Warp size.

3. "zsh-z" or similar integration native to Warp
- This command would be extremely necessary for me, but I could live without.

I wonder if any of these things are in the pipeline for Warp development?

Thanks for Warp!
```

### Additional context

Resources that would be helpful to me in regards to using Warp, and I'm sure others will too.

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @ajmeireles Thanks for taking the time to submit. We have a few existing feature to address some of your request.

1. You can double-click a Tab to rename it, or right-click a tab to rename it (or other options). https://docs.warp.dev/features/windows/tabs
2. [Warp now remembers and restores the previous position and size of the windows](https://github.com/warpdotdev/Warp/issues/1399#issuecomment-1545961642). We're working on a setting for opening windows at a default size that you can track here. #1399
3. Warps implemented it's own completions in the [input editor](https://docs.warp.dev/features/completions) and given how the input editor works like an IDE, it's a bit challenging to support other completion tools like Z, but you can track the progress of it here. #2026 

Please :+1: the issues above to show interest and track progress by subscribing to the requests.

Thanks again for submitting, closing this issue as one of the features already exist and the others are being tracked in the GitHub issues listed above.
