### ISSUE TITLE
Keybind options for completions menu

### ISSUE THREAD

**Issue by GNRSN** [warpdotdev/Warp#3199]
### Describe the solution you'd like?

```Text
Provide options in the keybind menu for inserting and closing the completions menu.
```

### Is your feature request related to a problem? Please describe.

```Text
I love the completions menu but not being able to rebind navigation & insertion is a daily source of frustration for me, especially since the default key is bound to insertion.

A common issue I have (especially with "enable completions while typing") is quickly writing a common command, e.g. `git push origin HEAD` and having the completions menu consume the enter click when i fire it, replacing HEAD with some suggested branch name.
```

### Additional context

In vim I have these keys mapped to `^+I` for insertions and `^+n` / `^+p` for navigation so I can enable type-ahead-suggestions without blocking these keys while typing

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @GNRSN 

We already have a request tracking this over at #1909 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
