### ISSUE TITLE
Support custom themeing

### ISSUE THREAD

**Issue by zachlloyd** [warpdotdev/warp#32]
There are several potential parts to this:

1. A richer set of built in themes (right now we just support light and dark mode).
2. A way of building and sharing custom themes.

Please upvote if this is something you're interested in!

**Comment by patspam** [comment]
Want to make sure https://github.com/chriskempson/base16 is on your radar.

I found when using iTerm that the best approach for consistently getting the colours I wanted across all my CLI programs (Vim, powerline, tmux, etc) was to use ANSI colours in iTerm, and then plugins like https://github.com/chriskempson/base16-vim.

**Comment by alokedesai** [comment]
We now support fully custom themes via a file in our newest release launched today. Please check out https://github.com/warpdotdev/themes for more information on how to define your own custom theme!

**Comment by patspam** [comment]
Love how quickly you added this!
