### ISSUE TITLE
Can we docked warp

### ISSUE THREAD

**Issue by vanquanguetk63** [warpdotdev/Warp#3200]
### Describe the solution you'd like?

```Text
Hi Warp team, i'm interested in Warp app, but i have question that did your team has ever thougt about pin it on desktop like Stay on top function of ios simulator
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @vanquanguetk63, Appreciate you submitting this request. Warp currently has a feature called Global Hotkey which you can set up to have a dedicated window that will not hide on loss of focus ( always stay on top ). Please learn more about the feature in our docs. https://docs.warp.dev/features/windows/hotkey-window#dedicated-window

If this suits your use case, let us know by closing this request. If no, please provide further details on what you'd like to see.

**Comment by vanquanguetk63** [comment]
Thanks @dannyneira  so much
