### ISSUE TITLE
Shortcut "Create personal workflow" not working

### ISSUE THREAD

**Issue by elchead** [warpdotdev/Warp#3201]
### Describe the bug

when I press the shortcut (with a block selected or not) nothing happens.
How is it supposed to work?

### To reproduce

1. Open warp
2. (select block)
3. press shortcut for "Create personal workflow"

### Expected behavior

create new workflow

### Operating system

MacOS

### Operating system and version

MacOS 13.5

### Current Warp version

v0.2023.06.06.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
hey @elchead That shortcut is for up-and-coming features that aren't in the app yet, the shortcuts are there, but they aren't bound to the features yet. You can learn more about them [here](https://docs.warp.dev/features/warp-drive).

Will close this request, but keep an eye on our [Twitter](https://twitter.com/warpdotdev) and [blog](https://www.warp.dev/blog) for more announcements on new features!

**Comment by elchead** [comment]
Ah okay, excited when it will arrive! 
Just a bit confusing to reveal shortcuts that are not yet functional :)
