### ISSUE TITLE
Refresh feature

### ISSUE THREAD

**Issue by sh-sam** [warpdotdev/Warp#3202]
### Describe the solution you'd like?

```Text
A feature I find particularly useful in iTerm2 is the ability to 'refresh' the terminal using `command+R`. In actuality it just pushes all your output up. Small thing and maybe it exists in Warp. Would be nice to have if not!
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @sh-sam Thanks for submitting this. We have a feature called clear screen which essentially is the same as refresh. The default keyboard shortcut is `CTRL-L`, but you can change it in `Settings > Keyboard Shortcuts` and learn more about this and other shortcuts here: https://docs.warp.dev/features/editor#how-to-use-it

Closing as the feature already exists and is called "Clear screen" in Warp.

**Comment by sh-sam** [comment]
Thanks a lot @dannyneira !
