### ISSUE TITLE
docker cannot running , because $WARP_PS1 have contains whitespaces

### ISSUE THREAD

**Issue by samzong** [warpdotdev/Warp#3203]
### Describe the bug

<img width="1638" alt="20230614235434" src="https://github.com/warpdotdev/Warp/assets/13782141/91d6ec24-5559-40d4-a1c9-ae8b0070f2c2">

### To reproduce

1. clone github project istio/istio.io
2. step by step make build docs site
3. can not use `make serve`

### Operating system

MacOS

### Operating system and version

MacOS 13

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.06.06.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @SAMZONG 
We'll post any updates or follow-up questions on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Hi @SAMZONG Could you please provide more detailed steps for reproduction with the commands that we should run aswell? This will help us narrow down the root of the issue.

**Comment by SAMZONG** [comment]
> Hi @SAMZONG Could you please provide more detailed steps for reproduction with the commands that we should run aswell? This will help us narrow down the root of the issue.

Hi @dannyneira, I'm working with [istio.io](https://github.com/istio/istio.io),
and follow this document https://istio.io/latest/docs/releases/contribute/build/

pls use `make serve` at your clone this repo.

**Comment by dannyneira** [comment]
@SAMZONG I was able to correctly `make serve` within the istio folder, but only after updating and running the docker engine. 

![CleanShot 2023-07-06 at 12 46 51](https://github.com/warpdotdev/Warp/assets/16809145/78711b05-209b-48a2-97b1-445907e1aed7)

It looks like there may be an issue with your docker installation, make sure it's on the latest version and the docker engine is running. I have docker desktop installed which should make updating/running easier. Please run the latest version of docker, and ensure the engine is running, then try the make serve again and let us know of any issues.

![CleanShot 2023-07-06 at 12 52 28](https://github.com/warpdotdev/Warp/assets/16809145/dc50b11c-f9b4-4ed6-a703-66a9ea6159af)

**Comment by dannyneira** [comment]
@samzong Any luck with the above suggestion to update docker engine and istio?

**Comment by dannyneira** [comment]
Closing as stale.
