### ISSUE TITLE
Block output is smashed

### ISSUE THREAD

**Issue by berkus** [warpdotdev/Warp#3207]
### Describe the bug

<img width="204" alt="image" src="https://github.com/warpdotdev/Warp/assets/80306/8a51c0b2-55f5-41ca-a202-38e5ddb30001">

There's an output from `lerna --version` somewhere in there - if you can find 6.5.1, this latest update completely broke blocks output handling and all one-line commands are simply disappearing into between the lines.

### To reproduce

Upgrade to Warp v0.2023.06.06.08.02.stable_00

### Expected behavior

Block output should be legible and not step over on itself.

### Operating system

MacOS

### Operating system and version

13.5.0

### Shell Version

fish, version 3.5.1

### Current Warp version

v0.2023.06.06.08.02.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

version prior to the current one

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @berkus Thanks for letting us know. So on my end when installed `lerna`, it returned 7.0.1 correctly with no block issues. Can you try `brew upgrade lerna` to make sure you're on the latest version and let us know if the issue persists?

![CleanShot 2023-06-15 at 11 19 50](https://github.com/warpdotdev/Warp/assets/16809145/dc854849-2dea-4b62-9668-645d4ce0a311)

**Comment by mallowigi** [comment]
I have the same problem that appeared only pretty recently, and it is a high turnoff making me consider using another terminal.

IT's not related to lerna; I'm running fish and simply inputing `ls` is enough to trigger the behavior

**Comment by mallowigi** [comment]
![CleanShot 2023-06-17 at 14 35 06@2x](https://github.com/warpdotdev/Warp/assets/5015756/a129ce52-1d4b-48ae-ba32-b99b2b448815)

**Comment by berkus** [comment]
@dannyneira this is not about lerna, any tool has first one or two lines of output printed over the block heading in warp.

**Comment by berkus** [comment]
<img width="685" alt="image" src="https://github.com/warpdotdev/Warp/assets/80306/2f9fe4da-e45a-411b-b95c-fbb69f1ea18a">

This is output of `lerna bootstrap` and `rm -rf ..` and `ls` and they all are overlapping.

**Comment by dannyneira** [comment]
Are you using Compact mode by any chance? 

If not, then my guess is that you normally have a [custom prompt, theme, or plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table)

You can check whether it’s something in your dotfiles and disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here <
end
```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by berkus** [comment]
It used to work literally two versions ago, what happened?

**Comment by dannyneira** [comment]
Not sure, but I'll flag this as a possible regression if you could please provide a redacted copy of your fish.config file, we can try and reproduce the issue.

**Comment by dannyneira** [comment]
Thanks for the update. Unfortunately, Warp doesn't support the `iterm2_shell_integrations` so disabling it for Warp with the conditional is your best bet. https://docs.warp.dev/help/known-issues#list-of-incompatible-tools

**Comment by zachbai** [comment]
Hey all, as @dannyneira mentioned above, disabling `iterm2_shell_integrations` is a short-term workaround.

The issue is due to logic we introduced to support p10k ( see #2851) in zsh, which necessitated introducing logic to the app that understands these markers (escape sequences that _also_ happen to be used by `iterm2_shell_integrations`). There should be a solution here that doesn't require you to disable `iterm2_shell_integrations` long term.

If you're experiencing this issue, would you mind sharing your `config.fish`? Any part of that file that uses the functions exposed by `iterm2_shell_integrations` (e.g. `iterm2_prompt_start`, `iterm2_prompt_end`) would be super helpful for debugging. Of course, feel free to redact any personal/sensitive info.

**Comment by dannyneira** [comment]
@berkus Just following up on this thread. If you're experiencing this issue, would you mind sharing your `config.fish`(feel free to redact any personal/sensitive info)?

**Comment by dannyneira** [comment]
Closing as stale, but please feel free to reopen with further details (i.e. redacted `config.fish`)

**Comment by berkus** [comment]
I have just disabled offending fns and all seems good so far
