### ISSUE TITLE
vim set t_ti t_te issue

### ISSUE THREAD

**Issue by zhangnew** [warpdotdev/Warp#3209]
### Describe the bug

When the following configuration is included in .vimrc, it causes display issues in the terminal, including the Warp feature obscuring the first few lines of the Vim page, and abnormal display in the terminal after exiting Vim.
```
set t_ti=
set t_te=
```

### To reproduce

see describe

### Operating system

MacOS

### Operating system and version

13.4.0

### Current Warp version

v0.2023.06.06.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Appreciate you letting us know! We'll post any updates or follow-up questions on this thread.

Please add a 👍 to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
hey @zhangnew So I did a bit of digging and I was able to apply a conditional to disable those set variables in vimrc just for warp. Add the following to your `.vimrc` instead and it should work as normal. Let me know if this helped resolve your issue.

```
if !has("gui_running") && $TERM_PROGRAM !=# "WarpTerminal"
  set t_ti=
  set t_te=
endif
```

**Comment by zhangnew** [comment]
The modification is worked, but I would like to use this feature of vim: to keep the content of vim in the terminal after exiting.

**Comment by dannyneira** [comment]
Heard, you can also disable the "Sticky Command Header" if you'd like to keep the vim settings, then there shouldn't be the override on the screen for the time being. I'll let the team know this setting is causing issues and we'll post updates on the thread.

**Comment by dannyneira** [comment]
We'll be tracking this issue over at #3214  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
