### ISSUE TITLE
Adding new personal workflows shows duplicate on warp

### ISSUE THREAD

**Issue by Hernan-V** [warpdotdev/Warp#3211]
### Describe the bug

When I add a new personal workflow on a  yaml file, i see it twice on warp

### To reproduce

Add a simple yaml file for a custom workflow.
Then open the workflow navigation on Warp.

### Screenshots

Every file on the workflow directory
<img width="1242" alt="image" src="https://github.com/warpdotdev/Warp/assets/34578114/7d377283-6be3-4795-ae32-e4c6f1ef7e38">

How is presented on Warp two times each file
<img width="704" alt="image" src="https://github.com/warpdotdev/Warp/assets/34578114/bfe565f6-ce37-4f34-8e3e-4db768b47fd7">

### Operating system

MacOS

### Operating system and version

12.6.5

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Current Warp version

v0.2023.06.06.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Appreciate you letting us know. We're working on some improvements to the workflows in the near future and this may be related to that. 

We'll post any updates or follow-up questions on this thread.

Please add a 👍 to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Hey @Hernan-V We're closing this issue out as we can no longer reproduce on recent build. If you still seeing the issue, please let us know.
