### ISSUE TITLE
Hotkey window. fzf page up/down

### ISSUE THREAD

**Issue by rhsev** [warpdotdev/Warp#3212]
### Describe the bug

I can use fzf with the hotkey window and with normal window.
In the hotkey window alt+f and alt+b does not work. In the normal window I can scroll through the list page by page with it.
I can resize the hotkey window, but that does not matter.

### To reproduce

export FZF_DEFAULT_OPTS='--bind ctrl-f:page-down,ctrl-b:page-up'
just enter fzf and use alt+f and alt+b

### Operating system

MacOS

### Operating system and version

13.4.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.06.06.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Appreciate you letting us know! We'll post any updates or follow-up questions on this thread.

Please add a 👍 to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Thanks for submitting this @rhsev 

We already have a request tracking this over at #537 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
