### ISSUE TITLE
Fish shell does not start

### ISSUE THREAD

**Issue by sajadabedi** [warpdotdev/Warp#3213]
### Describe the bug

I use Fish shell as my default shell, but when I installed Warp, it got stuck at the start and I can't figure out why it isn't working.
it's working fine with ZSH though.

### To reproduce

- installing Fish shell
- Setting the Fish as the default shell
- and open the shell

### Screenshots

<img width="400" alt="image" src="https://github.com/warpdotdev/Warp/assets/5726597/c9fdc93c-d930-43c7-ad86-5aabe9541f94">
<img width="400" alt="image" src="https://github.com/warpdotdev/Warp/assets/5726597/9bd05f39-8e79-42c5-acca-63ec42c49737">

### Operating system

MacOS

### Operating system and version

13.4.0

### Shell Version

3.6.1

### Current Warp version

v0.2023.06.13.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @sajadabedi Thanks for letting us know. Please try the following and let us know if it resolves the issue. 

1. Run `which fish` to find the location of the executable.
2. Enter that location (for example `/opt/homebrew/bin/fish`) into the Custom option in Warp > Settings > Features > Session > "Startup shell for new sessions"

![CleanShot 2023-06-20 at 10 45 10](https://github.com/warpdotdev/Warp/assets/16809145/bbab272a-e455-4f31-9aa3-edba431d7a6e)

That way Warp will explicitly use fish for sessions, whereas `chsh -s $(which fish)` may not result in the same.

**Comment by sajadabedi** [comment]
@dannyneira Thanks. this fixed the issue. 
but speed is not that great. And takes 2-3 seconds to start the fish.
We'll close this, but it would be amazing to see some improvement with Fish.

**Comment by EZVIK** [comment]
I also encountered the same problem. It was because I executed "fish /User/xx" when entering Warp. In older versions of fish, it would enter a loop and continuously print errors, causing it to wait indefinitely. If your fish version is before 3.4.0, please try upgrading to a newer version.

https://github.com/fish-shell/fish-shell/issues/8258

**Comment by henriqpohl** [comment]
@sajadabedi did you find some different way? because any of way here fixed my same problem. :(

**Comment by sajadabedi** [comment]
@henriqpohlI'm not sure if they have made any improvements, considering you're still experiencing this issue, I assume they haven't. Personally, I switched back to iTerm2. It's much more stable, and I don't have to restart my terminal every week for updates.

**Comment by henriqpohl** [comment]
@sajadabedi that's so sad, Warp has a good potential, unfortunately they don't care about this issue that for me is essential, currently I'm using Hyper Terminal and it make a good job for now.
