### ISSUE TITLE
Problem with path display after $

### ISSUE THREAD

**Issue by Nonable** [warpdotdev/Warp#3215]
### Describe the solution you'd like?

```Text
Now the full path is displayed after $, I want to modify the configuration and only output the name of the current folder as the path, but I have tried several schemes but failed to achieve it, may I ask how I can modify it to achieve my demand?
```

### Is your feature request related to a problem? Please describe.

```Text
Now the full path is displayed after $, I want to modify the configuration and only output the name of the current folder as the path, but I have tried several schemes but failed to achieve it, may I ask how I can modify it to achieve my demand?
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting @Nonable Could you please edit your request and include some screenshots? It's not clear what is entering `$` into your paths, I'm not seeing the same on my end. Are you referring to the workflows?

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by Nonable** [comment]
<img width="636" alt="Snipaste_2023-07-04_12-13-28" src="https://github.com/warpdotdev/Warp/assets/3262410/b548515f-706a-4cb1-a8e6-2ce0e545c675">
<img width="630" alt="Snipaste_2023-07-04_12-13-43" src="https://github.com/warpdotdev/Warp/assets/3262410/2f1383ff-e700-43b5-808b-2777634e3255">

Same path, display different, I want to display only the current folder, like: Fonts
