### ISSUE TITLE
View Changelog before updating 

### ISSUE THREAD

**Issue by Eazash** [warpdotdev/Warp#3217]
### Describe the solution you'd like?

```Text
I want to view the changelog for a release before it's installed (ideally next to the "Install update (<some_version>)" message). I want to be able to choose whether or not I want to install the update. I assume it'll also be very relevant when informing about any breaking changes, by allowing users to know before-hand what exactly will "break".
```

### Is your feature request related to a problem? Please describe.

```Text
Currently I can only see the version name in the update dialog. Personally, this is not useful information if I don't know what changes that version brings.
```

### Additional context

<img width="431" alt="Screenshot 2023-06-18 at 10 35 25 PM" src="https://github.com/warpdotdev/Warp/assets/56728970/28dba0e4-a0e8-4b67-b8f3-b7c0ce77fac5">

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @Eazash Thanks for submitting this request. We typically publish our changelogs on launch day in our docs which you can see here: https://docs.warp.dev/getting-started/changelog

We will be making some updates to the changelogs in the near future, but I'm not sure it will include the option to see them before the update, so looking at our docs above may be your best bet.

Closing as there are no plans to show a changelog in the app before the update.
