### ISSUE TITLE
Crash when editing a workflow in the Drive panel

### ISSUE THREAD

**Issue by Cronos87** [warpdotdev/Warp#3222]
### Describe the bug

When I want to edit an existing workflow using the new Drive panel, the app crashes when pasting a new workflow when selecting the old one, but not if the old workflow content has been deleted.

### To reproduce

1. Open the drive panel
2. Right-click on an existing workflow and select edit
3. Focus the CLI input, select all by pressing `ctrl+a`
4. Past the new command
5. The app crashes

### Expected behavior

The app won't crash and uses the new workflow.

### Operating system

MacOS

### Operating system and version

macOS 12.6.5

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @Cronos87 We're looking into the issue, trying to reproduce and we'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by Cronos87** [comment]
Hi @dannyneira! Thank you for the speedy fix! I confirm that the issue has been solved!

Many thanks to the team!

**Comment by dannyneira** [comment]
Awesome thanks for confirming! Closing as resolved.
