### ISSUE TITLE
Hide Workflows on the Left-Hand Column

### ISSUE THREAD

**Issue by wenindoubt** [warpdotdev/Warp#3223]
### Describe the solution you'd like?

```Text
Warp Version: v0.2023.06.13.08.03.stable_03
macOS Ventura: 13.4 (22F66)

I expect to have the option to hide the left-hand column that is currently showing the Workflows.
```

### Is your feature request related to a problem? Please describe.

```Text
Yes, I'd like a feature to hide the workflows.
```

### Additional context

This does not impede my workflow, but I don't like having my real estate reduced when I don't require the workflows all the time.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for letting us know your thoughts. 

At this time there isn't a way to explicitly hide workflows, but what you can do as a workaround for the time being is put them all in a folder and then collapse the folder ( see my example ). Then when collapsed you can use [Command Search](https://docs.warp.dev/features/entry/command-search) and filter for Workflows to find the ones you want with `CTRL-R`.

https://github.com/warpdotdev/Warp/assets/16809145/368d087c-7209-489e-8b83-d2c75f952072

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by wenindoubt** [comment]
> Thanks for letting us know your thoughts.
> 
> At this time there isn't a way to explicitly hide workflows, but what you can do as a workaround for the time being is put them all in a folder and then collapse the folder ( see my example ). Then when collapsed you can use [Command Search](https://docs.warp.dev/features/entry/command-search) and filter for Workflows to find the ones you want with `CTRL-R`.
> 
>  CleanShot.2023-06-20.at.14.42.12.mp4 
> Please add a 👍 to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

Thank you! I got what I needed :)
