### ISSUE TITLE
Warp drive click-to-execute for unparameterized workflows

### ISSUE THREAD

**Issue by minhth-1529** [warpdotdev/Warp#3226]
### Discord username (optional)

szgupta#1690

### Describe the solution you'd like?

```Text
Click-to-execute on Warp drive for unparameterized workflows. No need to input after that press enter.
```

### Additional context

![image_1](https://github.com/warpdotdev/Warp/assets/17897146/b7a5432d-211b-40f1-9d20-5fb5c5a9e3d0)
![image](https://github.com/warpdotdev/Warp/assets/17897146/c4d3755f-4243-4120-80cc-5210d6967702)

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by ahmedhosny** [comment]
I would say this is still very nice to have for dev velocity - the extra clicks needed make the Workflow much less attractive.
