### ISSUE TITLE
different result return in command “path_helper”

### ISSUE THREAD

**Issue by bbq191** [warpdotdev/Warp#3228]
### Describe the bug

different return in terminal.app and warp.app
 
<img width="1018" alt="image" src="https://github.com/warpdotdev/Warp/assets/377810/5961d84e-117d-45aa-8b0b-d7fedd7c721e">

### To reproduce

I using zsh in my mac
I cleanup my dotfile even /etc/zshrc, only left /etc/paths
![IMG_1034](https://github.com/warpdotdev/Warp/assets/377810/6dc5fc56-0338-4bbf-8df0-6de85291e453)

### Operating system

MacOS

### Operating system and version

14

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @bbq191 Thanks for letting us know. I wasn't able to reproduce the issue on my end.

![CleanShot 2023-06-21 at 10 01 08](https://github.com/warpdotdev/Warp/assets/16809145/09c762f6-e8a2-4efe-be7c-81f92df026ff)

Did you also clean up your `~/.zshrc`? any recent changes in that file that may be causing this?

**Comment by bbq191** [comment]
> Hey @bbq191 Thanks for letting us know. I wasn't able to reproduce the issue on my end.
> 
> 
> 
> ![CleanShot 2023-06-21 at 10 01 08](https://github.com/warpdotdev/Warp/assets/16809145/09c762f6-e8a2-4efe-be7c-81f92df026ff)
> 
> 
> 
> Did you also clean up your `~/.zshrc`? any recent changes in that file that may be causing this?

Yes, I removed it, and also removed /etc/zshrc./etc/zprofile,only left /etc/paths path.d, and emptied path.d.
Nnt only in zsh but also in bash.
So I don’t know what happened.
Btw the same in kitty except terminal

**Comment by bbq191** [comment]
Finally, i resolved through erased my all content and settings.
BTW, i don't known how and why it happend, but i can make sure it's my system env prombles.
Thx.
