### ISSUE TITLE
Command display for past commands

### ISSUE THREAD

**Issue by ravinggenius** [warpdotdev/Warp#3232]
### Describe the bug

The command text shrinks and gets crowded after entering a command, as shown in the screenshot. I discovered and started using Warp on May 25. (I put a message in my team's Slack about it.) It didn't do this at first, but it started after an update about two-three weeks ago. I've been keeping up with the updates, and this issue has been present in the last three or four.

### To reproduce

I don't really know. It just started happening after a recent update. I'm just using the terminal for regular web development (`npm` and `git` mostly). My theme is Solarized Light, but the settings are otherwise mostly defaults. (I don't recall changing anything else, except maybe the font to Fira Mono.)

### Expected behavior

The previous command's CWD and command input are clearly visible and visually distinct from the command output without crowding the output.

### Screenshots

The commands I entered are `ls -l` and `fish --version`, but they aren't shown anywhere.

<img width="426" alt="Screenshot 2023-06-21 at 12 43 41" src="https://github.com/warpdotdev/Warp/assets/21517/e25a90bd-e78f-41b3-bbf4-7c33ed9463c9">

### Operating system

MacOS

### Operating system and version

13.4.0

### Shell Version

fish, version 3.6.1

### Current Warp version

v0.2023.06.13.08.03.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

2023-05-25 and a week or two after

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @ravinggenius Sorry to hear about this blocker. I suspect you may have a [plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table)

You can check whether it’s something in your [dotfiles](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files) and then disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here <
end
```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>

**Comment by ravinggenius** [comment]
Thanks for responding. I don't have any Warp plugins installed; I didn't even know they existed!

I do have some fish customisations, so that might be it. I'll go over the resources tomorrow when I get back to work to verify I'm setting the prompt correctly.

**Comment by dannyneira** [comment]
Sorry they aren't Warp plugins, they are bash/zsh/fish plugins, like for example the iterm2_shell_integration listed here: https://github.com/warpdotdev/Warp/issues/3207#issuecomment-1602557180

Check for any of the unsupported ones in the list and put them in the conditional within your config/rcfiles in order to disable them just for Warp.

**Comment by ravinggenius** [comment]
Sorry for leaving this open for so long! I ended up starting with a fresh setup with no fish plugins. Everything worked as expected. I didn't know what specifically I had that was causing the strange rendering, but let's assume it was on my end.
