### ISSUE TITLE
Fullscreen mode isn't using the top-bar space

### ISSUE THREAD

**Issue by ricardofalasca** [warpdotdev/Warp#3234]
### Describe the bug

Fullscreen mode isn't using the whole space at the top. It's "pretending" to maximize but still with the very same window size.

### To reproduce

Use any command to enter in Full Screen mode (ie. cmd + F).

### Expected behavior

Fill the whole screen.

### Screenshots

<img width="1470" alt="Screenshot 2023-06-21 at 10 15 55 PM" src="https://github.com/warpdotdev/Warp/assets/1872547/1e0c1207-0e02-4424-935b-fc16cfd75e3c">
<img width="1470" alt="Screenshot 2023-06-21 at 10 16 01 PM" src="https://github.com/warpdotdev/Warp/assets/1872547/b8411f64-337a-435b-95fc-a781161fc154">
<img width="1470" alt="Screenshot 2023-06-21 at 10 16 06 PM" src="https://github.com/warpdotdev/Warp/assets/1872547/b0788799-448b-4cb0-b799-478897307f67">

### Operating system

MacOS

### Operating system and version

13.4.0

### Shell Version

zsh

### Current Warp version

v0.2023.06.13.08.03.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @ricardofalasca Thanks for submitting this. Could you please provide a video of the issue? based on your screenshots I can't see what the problem is,  Warp appears to be fullscreen like normal. If you happen to have the mouse hovering on the top of the screen it will show your menu bar while in fullscreen mode as with other apps.

**Comment by ricardofalasca** [comment]
Hi @dannyneira. It's my mistake, all apps are behaving exactly like that. I'm closing this issue now. Thanks for your time.

**Comment by dannyneira** [comment]
No worries, thanks for letting us know. Any issues feel free to open a new bug report.
