### ISSUE TITLE
New Tab loses focus.

### ISSUE THREAD

**Issue by sumit-shortloop** [warpdotdev/Warp#3235]
### Describe the bug

Tab loses Keyboard focus; when previous tab command gets executed .

### To reproduce

Steps to reproduce : 
- Open new tab (say Tab1) : Hit SSH command.  (Or any other command which takes some time to execute)
- Quickly move to new Tab (Say Tab2) : 
- While writing command in Tab2; if the Tab1 SSH command got successfully executed meanwhile; the Tab2 loses keayboard focus. 

(This has been a bug since a long long time.) 

### Operating system

MacOS

### Operating system and version

10.15.1

### Current Warp version

v0.2023.06.13.08.03.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Any luck with the above?

**Comment by dannyneira** [comment]
Closing for no response. please reopen if you can provide/verify the above. https://github.com/warpdotdev/Warp/issues/3235#issuecomment-1603165258
