### ISSUE TITLE
Prompt overlaps the output of the command

### ISSUE THREAD

**Issue by MaXal** [warpdotdev/Warp#3236]
### Describe the bug

Prompt overlaps the output of the command.
This happens for any command and no settings change the behavior.
The only workaround is to increase the "Line height" but the output became too large in this case.

### To reproduce

1. Open Warp
2. Execute any command that shows output like `ls`

### Expected behavior

There should be no overlap between prompt and the output.

### Screenshots

How the issue looks like:
<img width="1090" alt="image" src="https://github.com/warpdotdev/Warp/assets/266747/2394cf79-adb3-4707-9cba-2fa310801f81">

Settings:
<img width="1090" alt="image" src="https://github.com/warpdotdev/Warp/assets/266747/1dfee989-968e-44bb-9d2c-44aed1244394">

<img width="1090" alt="image" src="https://github.com/warpdotdev/Warp/assets/266747/5949fc82-4991-432e-b3c6-af79547a2e5e">

<img width="1090" alt="image" src="https://github.com/warpdotdev/Warp/assets/266747/55176fc3-1680-4c08-b507-b64ca00f324e">

### Operating system

MacOS

### Operating system and version

macOS 13.4

### Shell Version

fish, version 3.6.1

### Current Warp version

v0.2023.06.13.08.03.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @MaXal Check your config files for the unsupported plugins. We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>

There are some in particular that can affect Warp's rendering. Once found, you can disable it just for Warp in your `config.fish` file with the following conditional:

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here (i.e. `iterm2_shell_integration`) < 
end
```
Hope this helps!

**Comment by MaXal** [comment]
Thank you, it was indeed an issue with `iterm2_shell_integration`!
