### ISSUE TITLE
Warp Drive workflow does not show up in workflow search

### ISSUE THREAD

**Issue by joshdales** [warpdotdev/Warp#3238]
### Describe the bug

I've added a workflow in Warp Drive, however it is not available in the terminal input when searching for workflows.

### To reproduce

1. Add a personal workflow in Warp Drive
2. Press `ctrl` + `shift` + `R` in a terminal input
3. Search for the workflow, or select `My Workflows` in the search menu that appears

### Expected behavior

I expected the workflows that I have created here to be available so that I can find them without having to open the Drive sidebar.

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/30500472/1cc0437d-8408-4385-a871-6bdc69b56ecb)

### Operating system

MacOS

### Operating system and version

Ventura 13.4

### Current Warp version

v0.2023.06.13.08.03.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by szgupta** [comment]
Hey @joshdales. sorry for the confusion here. For now, you can find your Warp Drive workflows using `ctrl-R` (Command Search) or via `cmd-P` (Command Palette). We'll try to make this less confusing!

**Comment by joshdales** [comment]
Thanks @szgupta - TBH this is my first time really using the workflows 😅, didn't realise that they were a thing and the built in ones look very handy, but having a separation of these and the ones in Warp Drive is a bit of a curve ball.

🤔 but if I use the command pallet to try and search for workflows that still takes me to the search flow
![image](https://github.com/warpdotdev/Warp/assets/30500472/3dc7d457-76d8-490d-94eb-55652b128636)

**Comment by dannyneira** [comment]
Hey @joshdales made a quick video showing some examples of how you can quickly find the workflows you made. Essentially once you use the `workflow:` filter you can enter the name/command in the workflows to quickly find.

https://github.com/warpdotdev/Warp/assets/16809145/eb28b062-8a56-48db-a4ac-d8d5ae2a4e1a

**Comment by suchcodemuchwow** [comment]
I searched through this in issues and experiencing the same problem:

I am not sure if drive and workflows are same and keeping the same stuff which is parameterised commands simply speaking. And not sure why it's getting more complicated while we need simplicity in our lives 😅🤷🏻‍♂️

I'm sorry to say this @dannyneira but your video shows really bad experience for terminal users which needs **mouse clicks** to on command bar. Maybe I don't know the shortcut but by the intuition from other command bar experiences I tried to use tab after opening up command bar which naturally should hover over the next element but it doesn't respond.

<img width="1470" alt="Screenshot 2023-06-27 at 05 13 07" src="https://github.com/warpdotdev/Warp/assets/9674241/541d0d61-4ae2-477c-ab28-51127b3216c8">

**Comment by Scott-J-McMullan** [comment]
I just created [this issue](https://github.com/warpdotdev/Warp/issues/3304) which I think is related

**Comment by Scott-J-McMullan** [comment]
Hi @dannyneira, the [Warp documentation](https://docs.warp.dev/features/warp-drive/workflows#support-for-yaml-workflows) says 

> ...there are plans for Warp Drive workflows to be imported/exported to prevent vendor lock-in.

Does this mean that at some point, we will be able to export our existing YAML Workflows to Warp Drive?

Thanks.

**Comment by MrBanja** [comment]
The same. It would be nice to have everything in one place divided by categories.

An extended workflow block with categories looks more appealing for storing all workflows there.

For example, I want to add a new Docker command to the workflow. It would be great to keep it alongside other Docker commands in the Docker category.
<img width="1092" alt="CleanShot 2023-07-06 at 11 02 07@2x" src="https://github.com/warpdotdev/Warp/assets/18736922/4c633089-a54c-4ebe-a06a-264021f7b5a6">

**Comment by dannyneira** [comment]
testing

**Comment by ryboe** [comment]
+1 for unifying Drive workflows and whatever the other workflows are called. I was confused by this.

**Comment by dannyneira** [comment]
Hey folks, This feature has been added in a recent version of Warp. You can now see the Warp Drive workflows in the Workflows search panel (`CTRL-SHIFT-R`).

![CleanShot 2023-11-03 at 12 37 55](https://github.com/warpdotdev/Warp/assets/16809145/9b7f8bdd-7adc-4b9f-b800-e8b9d1d51fa5)

Closing as resolved, but please do let us know if any issues with the feature.
