### ISSUE TITLE
Warp inconsistent opacity when open after quit

### ISSUE THREAD

**Issue by peguimasid** [warpdotdev/Warp#3239]
### Describe the bug

Upon opening Warp for the first time after quitting the application, an issue is encountered where the opacity setting demonstrates inconsistent behavior. Initially, when launching the application, the opacity level is observed to be lower than the expected value. However, after a certain period of time, the opacity increases to a higher value.

### To reproduce

1. Quit the Warp application completely.
2. Launch Warp for the first time.
3. Note the opacity level of the interface upon startup.
4. Observe the application over time or hover over the tab bar.

### Expected behavior

The opacity of the Warp interface should remain consistent upon initial launch and during interaction with the tab bar. It should display the expected default value without any unexpected changes.

### Screenshots

https://github.com/warpdotdev/Warp/assets/54289589/2f2fdb9a-f42f-4cd1-81fc-178e03343efc

### Operating system

MacOS

### Operating system and version

MacOS Ventura Version 13.4

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Current Warp version

v0.2023.06.13.08.03.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Additional context

- This issue is not observed when relaunching Warp without quitting the application.
- The duration required for the opacity to transition from the lower value to the higher value is currently unknown.
- This behavior has been replicated consistently across two MacOS devices

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @peguimasid, I was able to reproduce this issue, and from what I can tell, the older UI loads first, then within less than a second or so, the new UI loads. This appears to be the reason for the slight jitter within the app loading that appears as an "opacity" issue. 

I'll surface this with the team and we'll post any updates on this thread.
