### ISSUE TITLE
More blur!

### ISSUE THREAD

**Issue by WoodyWoodsta** [warpdotdev/Warp#3243]
### Discord username (optional)

woodywoodsta

### Describe the solution you'd like?

```Text
Blur is great, but I think we need more of it. 18 as a blur radius means it can still be difficult to read the terminal text over the top of some applications. I would also like to replicate an Apple vibrancy effect.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Appreciate the feature request @WoodyWoodsta As a workaround, I recommend adding a bit more opacity as it improves the blur effect's reduction of background visibility.

https://github.com/warpdotdev/Warp/assets/16809145/193effb3-4e0c-4e22-a543-1dfe354def2e

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by WoodyWoodsta** [comment]
Thanks @dannyneira - have done the already.

**Comment by nickdekruijk** [comment]
More opacity works for readability but the blur slider should go to at least 30.

**Comment by WoodyWoodsta** [comment]
In iTerm, the max is 64.

**Comment by zachbai** [comment]
Hey all, thanks for the feedback. You're right it's easy to bump the max value here. I'll have a change for this in an upcoming release.

**Comment by WoodyWoodsta** [comment]
That's awesome, thank you!

**Comment by dannyneira** [comment]
Closing as resolved, you can now bump up the Blur to 64!
