### ISSUE TITLE
Automatically fill workflow parameters with the same name

### ISSUE THREAD

**Issue by norgepaul** [warpdotdev/Warp#3244]
### Describe the solution you'd like?

```Text
Take this workflow.

`echo hello, {{your_name}}, {{your_name}}`

The second occurrence of the parameter remains empty as the user fills out the first. It would be great if they were synchronized, as they should contain the same text.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! Now that Workflows are easier to create/edit/save/share, I'm sure there are some improvements that can be made. 🤞 

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by noahzweben** [comment]
Hi @norgepaul ,

Can you let me know if you are still seeing this issue/take a screenshot if possible? Currently can't recreate.

![2023-06-23 14 20 57](https://github.com/warpdotdev/Warp/assets/12701358/160ac966-d8c1-4212-8f10-edbc8baf1230)

**Comment by norgepaul** [comment]
Hi,

Thanks for the quick response, and thanks for Warp. It's fantastic!

https://github.com/warpdotdev/Warp/assets/5075985/a090a0ef-75a9-4c12-973f-53d1616493bd

**Comment by dannyneira** [comment]
Thanks for the video. When you have two or more arguments with the same name, Warp automatically selects and puts a cursor over the parameters in the input so they are synced. You can cycle thru arguments with `SHIFT-TAB`, then you can just type once you have selected the argument you want to change. If you click on the argument, you override the automatic selection and lose the sync until you press `SHIFT-TAB`.

https://github.com/warpdotdev/Warp/assets/16809145/9166d8f2-51ce-42f9-9f97-64c67fab99a9

I hope this helps, I've also added some more info about this in our docs. https://docs.warp.dev/features/warp-drive/workflows#how-to-execute-workflows

**Comment by norgepaul** [comment]
That was the issue. Thanks for the info.
