### ISSUE TITLE
DUP: Duplicate of #083 - Add ability to rename tabs

### ISSUE THREAD

**Issue by mvanschellebeeck** [warpdotdev/warp#325]
### Describe the solution you'd like?

```shell
Add the ability to rename tabs through a shortcut
```

### Additional context

The name of the tab is always the named after the process of the last focused pane in that tab. When working I like to use tabs to separate each of my workflows (with each tab consisting of multiple panes). It would be nice to be able to name these workflows. 

Functionality similar to to `tmux rename-window` would be awesome!

**Comment by Advait-M** [comment]
+1 on this feature request, would love to name tabs!

**Comment by elviskahoro** [comment]
Linking:
- #83
