### ISSUE TITLE
Open predefined launch configuration via command line

### ISSUE THREAD

**Issue by LiranBri** [warpdotdev/Warp#3252]
### Describe the solution you'd like?

```Text
Hi,

I'd like to have a way to open predefined launch configuration via command line.
something like:
warplaunch -f <path to yaml file>

thank you
```

### Is your feature request related to a problem? Please describe.

```Text
I want that so I can start launch configurations via aliases or scripts
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! As a temp workaround, you can open saved Launch Configurations via [Alfred](https://www.alfredapp.com/) Workflow or [Raycast](https://www.raycast.com/) Extension. Learn more [here](https://blog.joe.codes/open-warp-launch-configurations-from-raycast-and-alfred).

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by LiranBri** [comment]
@dannyneira in the raycast extenstion, they actually implementing that by mimicking key strokes.. i think it's pretty strange

```javascript
    se.keystroke('l', { using: ['command down', 'control down'] });
    se.keystroke(query);
    se.keyCode(36);
```

not better to just provide a command? :)

**Comment by dannyneira** [comment]
Yes, it is @LiranBri! We're working on improving this so please keep an eye on our Twitter to learn more! https://twitter.com/warpdotdev/status/1674085251495366656

**Comment by dannyneira** [comment]
Hi @LiranBri! Great news! You can now create a script to open launch configurations from the CLI using Warps URI scheme. https://docs.warp.dev/features/uri-scheme#how-to-use-it

Please see an example of this in use for the Raycast + Warp extension in our docs. https://docs.warp.dev/features/uri-scheme#how-it-works

Closing as resolved since the URI scheme covers opening Warp Launch Configurations programmatically.

**Comment by romenmedina-aircury** [comment]
I still don't understand if this can be done without an external extension, I would like it to be native

**Comment by nikos06** [comment]
> I still don't understand if this can be done without an external extension, I would like it to be native

It is native : `warp-terminal warp://launch/my-launch-config`
