### ISSUE TITLE
Warp terminal doesn't show any command results after updating to the latest version

### ISSUE THREAD

**Issue by xinthink** [warpdotdev/Warp#3254]
### Discord username (optional)

yxwthink

### Describe the bug

Wrap just doesn't show anything (blank screen), no matter what command is entered.
It used to work fine in previous versions, and it does work if I fall back to an older version.

And I also tried turning on and off some features in the settings and restarted Warp, but nothing worked.

### To reproduce

1. Open Warp
2. Enter any command

### Screenshots

https://github.com/warpdotdev/Warp/assets/390805/f5478d65-ce49-474d-9e02-eacb3526782e

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Before the latest update

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by ccraig** [comment]
I'm experiencing this too. I've deleted config files and reinstalled, but the problem remains. I'm using alacritty in the meantime.

**Comment by dannyneira** [comment]
Hey folks, sorry to hear about this issue but I can't reproduce this on my end, besides updating Warp has anything else changed?

Can you please check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs.

**Comment by ccraig** [comment]
That worked for me!

**Comment by mahtd** [comment]
For me, I found an old iTerm integration source in my fish config, and removing it seemed to fix the issue

**Comment by xinthink** [comment]
Thanks @ccraig for the tips, it does work by disabling Oh My Zsh theme.

Hi @dannyneira, for me, nothing has changed except for updating Warp.
In my case, iTerm2 works fine, and it also works by rolling back to the previous Warp version (via brew, version: 0.2023.05.30.08.03.stable_03 (118B)).

**Comment by heybigneel** [comment]
I'm facing the same issue with fish shell 🙂

**Comment by majorcode** [comment]
I use Fish and had problems with the prompt in the previous few versions of Warp. It was previously cutting off the top of the command response. I couldn't see the first few lines of the response (the elapsed time, command, etc.). However, the latest version of Warp (0.2023.06.20...) didn't display anything at all after typing any command.

I'm also a previous user if iTerm. That seems to have been important. I removed iTerm shell integrations from my fish config and the problem cleared up.

I hope this helps.

**Comment by dannyneira** [comment]
@xinthink We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>

Once you find the culprit you can disable parts of your dotfiles just for Warp by using this conditional statement, like @majorcode mentioned, which fixed the issue:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here <
end
```

**Comment by xinthink** [comment]
@dannyneira Thank you for sharing, I've solved the problem by wrapping Oh My Zsh themes in a conditional statement.
