### ISSUE TITLE
I don't like your app icon, make it look more like a terminal

### ISSUE THREAD

**Issue by alpercanberk** [warpdotdev/Warp#3256]
### Describe the solution you'd like?

```Text
Literally my only complaint about warp. All of my friends say the same thing. A terminal app needs to look like a terminal. I even designed and changed my own ap icon so that warp can look more like a terminal app.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by alpercanberk** [comment]
![warplogo (5)](https://github.com/warpdotdev/Warp/assets/9828549/1b3f1bb7-6a18-49cf-a273-284743a5b7e2)

**Comment by dannyneira** [comment]
Thanks for submitting this @alpercanberk 

We already have a request tracking this over at #1865 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
