### ISSUE TITLE
Using `less` to scroll to a regex is hidden under the prompt

### ISSUE THREAD

**Issue by colinta** [warpdotdev/Warp#3258]
### Discord username (optional)

colinta

### Describe the bug

Running `git diff` and then searching for `/someFunctionName` matched my search, but the matching result was hidden under the prompt. I tested using my own PS1 and Warp's PS1.
<img width="501" alt="image" src="https://github.com/warpdotdev/Warp/assets/27570/66e6ffd2-3631-447f-a39b-bc5a8431cfad">

### To reproduce

1. `git diff` with a long diff
   ```diff
   ~/the-code ‹ main › X
   git d
   ——————————————
   …
   -someThing
   +someThing to search for
    more line 1
    more line 2
    more line 3
   …
   ```
3. `/search` for something
5. Observed: search result is offscreen, hidden by the prompt (by ~3 lines)
   ```
   ~/the-code ‹ main › X
   git d
   ——————————————
    more line 3
   …
   ```

### Expected behavior

Expected: search result is at the top of the visible area
   ```
   ~/the-code ‹ main › X
   git d
   ——————————————
   +someThing to *search* for
   …
   ```

### Screenshots

This is an ancient bit of code, but it was open sourced long ago so it works well I guess. But don't judge me for writing coffeescript, it was 2012 and it was better than what we had! 🤣 

1. `git log -p`
<img width="714" alt="image" src="https://github.com/warpdotdev/Warp/assets/27570/6cff1aff-e16e-4204-a6c0-58406214156e">

2. `/require`
<img width="714" alt="image" src="https://github.com/warpdotdev/Warp/assets/27570/a89b75b6-b734-4d2a-9ef4-673838c523a5">

3. ↑↑↑↑
<img width="714" alt="image" src="https://github.com/warpdotdev/Warp/assets/27570/4c49d021-3322-4ccf-a5cf-87dbf5c3e745">

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

bash 5.1

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @colinta Appreciate you letting us know. We recently resolved a similar issue, but it appears to persist because different cli tools handle extra space differently. The [sticky command header](https://docs.warp.dev/features/blocks/sticky-command-header) is designed to deal with a majority of tools, but this one may have been missed. As a temporary workaround, you can disable the sticky command header.

There is no ETA on a possible fix, but please add a 👍 to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by colinta** [comment]
What is the original post- another GitHub issue?

What command did you fix it for, I could test that one out.

**Comment by esambo** [comment]
I just experienced the same issue from a `git log` output. The initial output is fine, but when I scroll down, I'm not able to scroll all the way up again, as the top few lines get hidden behind the sticky command header.

**Comment by dannyneira** [comment]
We'll be tracking this issue over at #3214  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
