### ISSUE TITLE
Tab icon to indicate hidden splits

### ISSUE THREAD

**Issue by Integralist** [warpdotdev/Warp#3261]
### Describe the solution you'd like?

```Text
An icon in each tab that indicates the tab contains hidden split panes.
```

### Is your feature request related to a problem? Please describe.

```Text
Often times I have multiple split panes inside of a tab. I'll then fullscreen a specific split and then forget that I've got other split panes currently hidden. I'll then close the tab and realise I've just closed a bunch of other splits I didn't want to close.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @Integralist Thanks for submitting. So the default behaviour of panes is that there is a blue indicator on the top left corner to show which one is active, and this indicator carries over when the pane is maximized. So there isnt currently an indicator on the tab itself, but the blue one should help in the meantime. Once the pane is maximized you should be able to see this with the triangle indicator on the top left corner. Please see my demo:

https://user-images.githubusercontent.com/16809145/226971328-17102163-25cc-4599-82dc-6e04d5e7e53a.mp4

That being said, this isn't the case with pane dimming enabled thou so we can certainly improve in that scenario.

Any others interested in this feature please 👍  the original request up top to show interest.

**Comment by Integralist** [comment]
Hi @dannyneira 

Thanks for the reply, I don't have that blue arrow indicator as I use the tinted pane feature. I'll show by way of screenshot...

<img width="2032" alt="Screenshot 2023-06-27 at 10 01 21" src="https://github.com/warpdotdev/Warp/assets/180050/ae50ddf9-1812-4173-b42b-4d6cc199c74a">

Now, if you look at the following screenshot, you'll see I have a tab with multiple splits... 

<img width="2032" alt="Screenshot 2023-06-27 at 10 02 11" src="https://github.com/warpdotdev/Warp/assets/180050/4f57bd9a-48da-4ac8-9c74-644605fe19a0">

Now, look at the following screenshot, can you tell just by looking if there are multiple splits and that currently one of them is maximised...

<img width="2032" alt="Screenshot 2023-06-27 at 10 02 50" src="https://github.com/warpdotdev/Warp/assets/180050/4b8d7707-3e67-4cc0-9eee-c2193dfc9952">

This ☝🏻 is ultimately the issue 🙂 

I'll maximise a split, work in there for a bit, maybe go away and have some lunch and then later when I come back and I'm finished with that particular split I'll just close the tab and then the other hidden splits (which I've subsequently forgotten about) will also get closed and I'll lose the work that's in them.

Now a lot of times I have multiple tabs open, and so I won't close the tab with the maximised split, I'll use `<Command>+w` to close the split and it's at that point the other two splits will become visible. But there has been more than one occasion where I've _not_ done that and I've just closed the tab directly 😬 

The other thing, which is more a mild annoyance rather than an issue 🙂 and that's when I have multiple splits in a tab and I maximise one and then I'll forget about the other splits and so I'll open a new tab and then start making similar splits for files I already have open.

So I'm thinking if there was some indicator (wherever it should go) that would indicate to me that I have hidden splits then that would help with a bunch of different workflows I go through.

Thanks!

**Comment by dannyneira** [comment]
This request is being worked on, no ETA on the release, but we'll post any updates.

**Comment by Integralist** [comment]
I cant put over strongly enough how pleased I am to hear this 🙂

**Comment by dannyneira** [comment]
Hi folks (@Integralist ), This feature has been implemented in a recent release of Warp. When you have a maximized split-pane, you should now see a "full-screen" icon on the tab which has the maxed pane.

https://docs.warp.dev/getting-started/changelog#2023.10.19-v0.2023.10.17.08.03


https://github.com/warpdotdev/Warp/assets/16809145/b088187d-62fc-4284-a672-718129f71e3d

Closing as resolved, but please feel free to let us know of any issues with the feature.
