### ISSUE TITLE
Warp swallows console output

### ISSUE THREAD

**Issue by runningcode** [warpdotdev/Warp#3267]
### Describe the bug

When executing a Gradle build, the publication of a build scan url is rapidly displayed and then sometimes disappears.

I've reproduced a video of this happening here:
https://www.loom.com/share/db4673d40e144f078905d76688969748

### To reproduce

1. Check out this repo https://github.com/runningcode/Signal-Android/tree/no/scan-swallow
2. Execute ./gradlew testDebugUnitTest
3. watch as build scan url is swallowed.

### Expected behavior

I would expect the build scan url to be displayed.

### Screenshots

https://www.loom.com/share/db4673d40e144f078905d76688969748

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @runningcode along with good details/files and a video! We also have a related issue here #2966 

I will attempt to reproduce this with the info you provided. We'll post any updates/follow-up questions on this thread.

**Comment by dannyneira** [comment]
Hi all! this has been resolved in the most recent version of Warp. Please update and let us know.

**Comment by runningcode** [comment]
Thank you so much for fixing this. I have not seen this happen anymore!
