### ISSUE TITLE
Automatically run workflow command when you click on it?

### ISSUE THREAD

**Issue by polgiron** [warpdotdev/Warp#3272]
### Describe the solution you'd like?

```Text
I didn't find an option to auto run a workflow command when you click on it, could be useful for basic "git pull", "yarn" etc
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @

We already have a request tracking this over at #3226. As a workaround, once you click the Workflow in Warp Drive or find the workflow thru the command palette CMD-P and it's in the input editor you can press Enter to run it quickly.

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
