### ISSUE TITLE
Warp Drive Workflows should not reorder when updated

### ISSUE THREAD

**Issue by CerceJo** [warpdotdev/Warp#3277]
### Discord username (optional)

CerceJo

### Describe the solution you'd like?

```Text
Every time I update a Warp Drive Workflow they all move. They should be consistently ordered, either sortable, draggable, or at least alphabetical. Thanks!
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Appreciate you submitting this request @CerceJo.

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Closing as we recently released the ability to sort Warp drive by [alphabetical and last updated.](https://docs.warp.dev/features/warp-drive#organizing-workflows-in-warp-drive-with-your-team)

![CleanShot 2023-10-03 at 14 54 50](https://github.com/warpdotdev/Warp/assets/16809145/d8731522-9a92-4aa6-9625-02d70f43b718)

For reordering by dragging, we have a request tracking this over at #3402 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this request as it's implemented.
