### ISSUE TITLE
USe warp without registration

### ISSUE THREAD

**Issue by beun1er** [warpdotdev/Warp#3283]
### Describe the solution you'd like?

```Text
Hello, Warp seem to be a good soft but i can't use it on my firm because it need to be logged to use it.
Me and the rest of my team are afraid by the leak of sensitive data on our ssh sessions.

Do you plan to devellop a kind of lite version totaly offline and working without registration in the future ?
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @beun1er 

We already have a request tracking this over at #900

At this time, Warp continues to require login.  The primary reason is that login allows us to build cloud-oriented features that make the terminal have a concept of “your stuff” and “your team’s stuff” – for example Block Sharing and Warp Drive. 

We do understand the desire to try Warp before logging in and are exploring product experiences that could allow you to use Warp before signup. You can follow the issue above and we'll post updates there when we make any product changes around log-in. 

We also have info about privacy/telemetry we collect here: https://docs.warp.dev/getting-started/privacy
As well as more info on our policy here: https://www.warp.dev/privacy/policy

Hope this helps! We'll be closing this as a duplicate.
