### ISSUE TITLE
Browsing tabs with cmd + number

### ISSUE THREAD

**Issue by jstorm31** [warpdotdev/Warp#3288]
### Describe the solution you'd like?

```Text
It'd be nice to be able to browse tabs with cmd + number like in the browser.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @jstorm31 Thanks for submitting. Warp currently defaults to the following shortcuts for activating the first thru eighth Tabs with `CMD-1` thru `CMD-8`. You can learn more about this here: https://docs.warp.dev/features/windows/tabs

And even change them in the [Keyboard Shortcut](https://docs.warp.dev/features/keyboard-shortcuts) settings to your preference.

Closing this as the feature already exists, but if any issues with the shortcuts, feel free to let me know.
