### ISSUE TITLE
Copy current path or Git branch

### ISSUE THREAD

**Issue by samiwell** [warpdotdev/Warp#3291]
### Describe the solution you'd like?

```Text
It's great that the current path and the git branch are shown by default in Warp.

It would be nice if I was able to mark them so I'll be able to copy them.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by MaanavKhaitan** [comment]
Hi! Thanks for sharing this suggestion, you can already copy the git branch and current path in Warp by right-clicking on the path/git branch in the prompt. Like this:

![image](https://github.com/warpdotdev/Warp/assets/22297592/4c40db1d-e512-4d4f-94cf-af986ab3b81d)

Hope this helps!

**Comment by dannyneira** [comment]
Thanks for submitting this @samiwell

We already have a request track being able to select/copy prompt this over at #36

But as Maanav mentioned, you can currently right-click the prompt and copy the Git Branch(or working directory, or entire prompt, etc.). Learn more about this here: https://docs.warp.dev/features/prompt

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! Closing this as a duplicate issue.

**Comment by samiwell** [comment]
> Hi! Thanks for sharing this suggestion, you can already copy the git branch and current path in Warp by right-clicking on the path/git branch in the prompt. Like this:
> 
> ![image](https://user-images.githubusercontent.com/22297592/251247910-4c40db1d-e512-4d4f-94cf-af986ab3b81d.png)
> 
> Hope this helps!

Thanks @MaanavKhaitan !
