### ISSUE TITLE
terminal loading delay = uninstall

### ISSUE THREAD

**Issue by jdion84** [warpdotdev/Warp#3295]
### Describe the bug

since about last weeks update, every time i open the terminal there is a delay while it "loads"

i never had this issue before, it used to be lightning fast in all regards

this has caused me to uninstall and just go back to ZSH

if this is resolved i may reinstall, but i can't be the only one who feels this way

### To reproduce

install warp on macos (m1 chip)

open a terminal

watch it take several seconds to load

### Expected behavior

load right away without delay like literally any other terminal

### Operating system

MacOS

### Operating system and version

ventura

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for reporting and sorry that this is disrupting you! We’re constantly iterating to make the shell experience better in Warp; however the coordination between the shell and the terminal can be complicated so occasionally when we improve one area, something else goes wrong. 

My guess is that you normally have a [custom prompt, theme, or bash/zsh/fish plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table)

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files). Run `echo 'ZDOTDIR=/' > ~/.zshenv`. This forces Zsh to run with zero configs.

Once you find the culprit, you can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by dannyneira** [comment]
@jdion84 Sorry about this blocker, Could you please provide a copy of your .zshrc file ( remove any personal/private information of course )? This would help us in trying to reproduce the slow loading issue you're having.

**Comment by dannyneira** [comment]
@jdion84 is any change we could get a copy of your rc file to try and reproduce the issue on our end?

**Comment by dannyneira** [comment]
Closing as stale, no response from the user.
