### ISSUE TITLE
Autocomplete docker containers

### ISSUE THREAD

**Issue by danulqua** [warpdotdev/Warp#3297]
### Discord username (optional)

danulqua

### Describe the solution you'd like?

```Text
Feature that I miss a lot is an autocompletion for docker containers. For example, when using `Fig`, if you write `docker container kill`, it suggests all your running containers which is super useful as you don't have to type `docker ps` first and write container ids or names by yourself.
So, it would be cool if `Warp` could autocomplete docker containers in the same way in all commands where they're have to be written.
Additionally, autocompletions for `Docker` could be improved in general and not only for containers (e.g. images).
```

### Is your feature request related to a problem? Please describe.

```Text
I'm always struggling with writing docker container ids and names by myself when I want to start or kill them. When I started using `Fig`, it started autocompleting all containers and I realised that I barely can live without this feature once I've tried it.
```

### Additional context

This is how it works in `Fig`.

https://github.com/warpdotdev/Warp/assets/38916225/2c0faa25-885d-4307-a9dd-e33805528870

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by Chadzzz1** [comment]
> _
/_

**Comment by dannyneira** [comment]
Thanks for this feature request! 

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Hi @danulqua We've added docker autocomplete to the latest [Warp version](https://docs.warp.dev/getting-started/changelog#id-2023.12.21-v0.2023.12.19.08.02). Please update and let us know of any issues with this feature. 

Closing as completed.
