### ISSUE TITLE
Integrate Password Manager

### ISSUE THREAD

**Issue by TonyTromp** [warpdotdev/Warp#3298]
### Describe the solution you'd like?

```Text
Ability to integrate with existing password managers when RegEx trigger (e.g. Password:) is found n Terminal. Or create own Password Manager inside Warp.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @TonyTromp 

We already have a request tracking this over at #1087 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
