### ISSUE TITLE
Workflows shortcut doesn't work after the last update

### ISSUE THREAD

**Issue by iacob28** [warpdotdev/Warp#3299]
### Describe the bug

After updating the warp app to the latest version, the workflows shortcut doesn't work anymore. 
Tested on two separate devices 

OS: MacOS latest version
Warp Version: v0.2023.06.27.19.34.stable_01

### To reproduce

Use the shortcut: CTRL+SHIFT+R

### Expected behavior

Open the workflows window

### Operating system

MacOS

### Operating system and version

MacOS 13.4.1 (22F82)

### Current Warp version

v0.2023.06.27.19.34.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by Scott-J-McMullan** [comment]
This is happening to me, too

OS: macOS Ventura **Version 13.4.1 (22F82)**
Warp: **v0.2023.06.27.19.34.stable_01**
Shell: **zsh**

**Comment by dannyneira** [comment]
Hey @iacob28 Sorry to hear about this, We've intentionally disabled the CTRL-SHIFT-R shortcut, but you can use the Command Search CTRL-R to look for [YAML Workflows](https://docs.warp.dev/features/entry/yaml-workflows).

**Comment by Scott-J-McMullan** [comment]
Hi @dannyneira,

Why would the Warp team intentionally disabled the CTRL-SHIFT-R shortcut but leave it documented in the application settings?

![Screenshot 2023-07-06 at 08 53 21](https://github.com/warpdotdev/Warp/assets/93307071/b0a31efd-9171-4861-a0b5-2a4cce7a993b)

**Comment by dannyneira** [comment]
That's a good catch, I'll mention it to the team. Our docs have already been updated with this change, just not the app.

**Comment by Scott-J-McMullan** [comment]
Thanks, @dannyneira

**Comment by iacob28** [comment]
Hi @dannyneira 

Thanks for the response.
