### ISSUE TITLE
Core: NumpadEnter key appending "^C" token during a CLI prompt.

### ISSUE THREAD

**Issue by rohantandon** [warpdotdev/warp#330]
### Describe the bug

This issue was observed while using the [aws-vault](https://github.com/99designs/aws-vault) command line tool. When the CLI tool prompts the user for an MFA token, entering that token using the numpad and hitting `Enter` on the numpad results in the input being appended with a `^C` token. For example, in the following scenario:

```shell
~ aws-vault login my-aws-profile
Enter token for arn:aws:iam::xxxxxxxx:mfa/my_user: 00000^C
~
```
1. The user first enters the `aws-vault command`
2. The user is then prompted to enter their MFA token in the second line.
3. The user enters their token `00000` and then presses the `Enter` key on the numpad
4. After step 3, the token `^C` is appended to the MFA token and the command is aborted as if `Ctrl C` was run instead
5. If the user repeats steps 1-2, and then after entering their MFA token hits the primary `Enter` key (not `NumpadEnter`), the command will execute correctly and not be aborted.

### To Reproduce

This issue is likely not unique to `aws-vault`, but seeing as I encountered it while using it, I'll show reproduction steps 
Steps to reproduce:

1. Download and install [aws-vault](https://github.com/99designs/aws-vault)
2. Follow the instructions to set up an AWS access profile which you can use with `aws-vault login`.
3. Ensure that your AWS account is set up to take a numeric 2FA key (such as one generated by Google Authenticator)
4. Run `aws-vault login <YOUR AWS PROFILE NAME>`
5. Enter your 2FA key on your keyboard, but do not press `Enter yet
6. Hit `Enter` **on the Numpad**
7. Verify that your 2FA code on screen gets appended by the token `^C`

### Expected behaviour

Follow steps `1` to `6` in the reproduction steps. When at step `7`, the command should execute rather than being aborted.

### Operating System

MacOS

### Additional context

Repeating these same steps using the MacOS terminal does not result in a `^C` token being appended to the MFA code.

**Comment by elviskahoro** [comment]
Closed: v0.2021.11.09.19.46.stable_00
