### ISSUE TITLE
Wrong window placement after disconnecting and connecting external monitor when using "Global dedicated hotkey window"

### ISSUE THREAD

**Issue by danulqua** [warpdotdev/Warp#3303]
### Discord username (optional)

danulqua

### Describe the bug

I've set up dedicated hotkey window to Main screen, see screenshot below:
![CleanShot 2023-07-04 at 19 53 53@2x](https://github.com/warpdotdev/Warp/assets/38916225/b0b22e88-eb58-41b6-9edc-fb26a9636b9d)

My main screen is an external display. The bug is when I send my mac to sleep and later start using it again, my dedicated window appears on my macbook's screen instead of the external monitor which isn't the way it should be (for example, dedicated window in iTerm with external monitor works fine).

By the way, if I close this window and hit hotkey again, new window appears on the main screen as it should be.

### To reproduce

1. Set up dedicated window to main screen which is your external display
2. Lock your macbook, close it
3. Later, unlock it again
4. Open window using hotkey and notice that it appears on macbook's display instead of the main screen

### Expected behavior

Even if I locked my macbook and got back to it later, Warp's dedicated window should keep appearing on the main screen which is external monitor instead of macbook's screen.

### Screenshots

![CleanShot 2023-07-04 at 19 53 53@2x](https://github.com/warpdotdev/Warp/assets/38916225/10c3d13e-d210-42f3-bdfc-b913d33da269)
/

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

fish 3.6.1, zsh 5.9

### Current Warp version

v0.2023.06.27.19.34.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I can't record a video of bug demonstration because macbook has to be asleep for while, but everything is as I actually described.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @danulqua Thanks for letting us know. Sorry to hear about this blocker. Please make sure the external monitor is set to the primary display in the mac settings. We'll try and reproduce this and post any updates/questions on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by danulqua** [comment]
@dannyneira thank you for your response! Letting you know that it's set to primary, see screenshot.

![CleanShot 2023-07-06 at 19 36 43@2x](https://github.com/warpdotdev/Warp/assets/38916225/6185f9e7-5d96-4765-a29c-06a5d1293748)

I'll try to demonstrate you the problem on video. I'll edit it so it's short but informative.

**Comment by danulqua** [comment]
Well, it's strange, but as soon as I wanted to record the bug, I didn't get it anymore, even in the morning of the next day.  
I'll be continue trying to see if it occurs again.

**Comment by mulecalle** [comment]
I also experience the same issue https://github.com/warpdotdev/Warp/issues/3275

**Comment by dannyneira** [comment]
Closing as resolved, this has been fixed in most recent version of Warp.

**Comment by dannyneira** [comment]
Hey folks, as a possible workaround to this issue, You may need to go to Mac > System Settings > Desktop & Dock , then enable "Displays have separate Spaces" and the "Active" screen hotkey settings should work after sleep. Please let us know if that helps with your issue.
