### ISSUE TITLE
Manually created workflows are not appearing in Warp Drive & vice versa

### ISSUE THREAD

**Issue by Scott-J-McMullan** [warpdotdev/Warp#3304]
### Describe the bug

Workflows which are manually created by writing a YAML file & saving it to the `~/.warp/workflows` directory do not appear in the Personal section of Warp Drive & vice versa. For example, see the images below:
![Figure 1](https://github.com/warpdotdev/Warp/assets/93307071/58a99684-5959-4dfb-bba8-61b679daa182)

In _Figure 1.1_, one can see that I created a workflow called "Edit HTTPD SSL File" using the "Create A New Personal Workflow" (⇧⌘H) dialogue & it appears under the Personal section of Warp Drive. However, if I search for this workflow in the Workflows > My Workflows dialogue (_Figure 1.2_), it doesn't appear.

The opposite is also true:
![Screenshot 2023-07-05 at 13 08 03](https://github.com/warpdotdev/Warp/assets/93307071/1b9922f0-d555-4583-a948-86b13fd9fbd4)
I manually created a workflow, "Generate Leads", by making a new `generate-leads.yaml` file & saving it to my `~/.warp/workflows` directory. This workflow does **not** show under the Personal section of Warp Drive (_Figure 2.1_), but it does show in the Workflows > My Workflows dialogue (_Figure 2.2_).

### To reproduce

Perform one or both of these steps
1. Use the "Create A New Personal Workflow" (⇧⌘H) dialogue to create a new workflow
2. Create a new workflow YAML file & save it to the `~/.warp/workflows` directory 

### Expected behavior

Workflows should appear in both the Personal section of Warp Drive & the Workflows > My Workflows dialogue, regardless of how they were created

### Operating system

MacOS

### Operating system and version

Ventura 13.4.1 (22F82)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.06.27.19.34.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @Scott-J-McMullan. You can find your Warp Drive workflows using ctrl-R (Command Search) or via cmd-P (Command Palette). Please see more about our plans for YAML workflows in our docs. https://docs.warp.dev/features/warp-drive/workflows#support-for-yaml-workflows
