### ISSUE TITLE
support istioctl auto-completion

### ISSUE THREAD

**Issue by An0nymous0** [warpdotdev/Warp#3305]
### Describe the solution you'd like?

```Text
support istioctl auto-completion

https://istio.io/latest/docs/ops/diagnostic-tools/istioctl/#istioctl-auto-completion
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @An0nymous0 

We already have a request tracking this over at #652 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
