### ISSUE TITLE
Ligature Support

### ISSUE THREAD

**Issue by 5ouma** [warpdotdev/Warp#3309]
### Describe the solution you'd like?

```Text
Please support ligature font.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @5ouma This is on our radar and we may be releasing something new on this soon? 🤞  (no official eta). That being said, we already have a request tracking this over at #239 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
