### ISSUE TITLE
Weird display with neovim and warp

### ISSUE THREAD

**Issue by martindufresne** [warpdotdev/Warp#3311]
### Discord username (optional)

madbrainmd

### Describe the bug

I use neovim as code editor. More precisely the NvChad version. For my font, I use JetBrains Nerd font. Everything works fine, except for the status bar at the bottom. Warp shows it to me in a weird way. I tested on Iterm2 and I don't have this problem. Anyone know why? And also, how to fix it :)

Thanks in advance!

### To reproduce

To reproduce it:
1- install NvChad
2- install JetBrains Nerd font
3- open NvChad. 

I have a MacBook Air M1 running macOS Ventura 13.4.1

### Screenshots

![SCR-20230706-iwfw](https://github.com/warpdotdev/Warp/assets/2438127/3915fa8a-0d36-4793-a018-16114c1dbd1c)

### Operating system

MacOS

### Operating system and version

macOS Ventura 13.4.1

### Shell Version

zsh 5.9 (arm-apple-darwin22.1.0)

### Current Warp version

v0.2023.06.27.19.34.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @martindufresne Thanks for letting us know. I'm not able to reproduce this with stock nvchad and jetbrains mono installed. 

![CleanShot 2023-07-11 at 15 39 39](https://github.com/warpdotdev/Warp/assets/16809145/da9d4eda-77ea-4efa-b64f-878c078e4992)

I suspect you may have some other settings for nvim that are causing the extra blocky space above the, I recommend you clear your nvim config file completely, then install a fresh nvchad, and start from there. slowly adding back in the other settings until you narrow down the root of the issue.

**Comment by martindufresne** [comment]
It was indeed a configuration problem. After reset, everything was fine. Thank you so much!
