### ISSUE TITLE
Subshell flooding of user@host:/path when typing instead of getting suggestions.

### ISSUE THREAD

**Issue by hareland** [warpdotdev/Warp#3313]
### Discord username (optional)

heisann#7671

### Describe the bug

After updating there is a flooding of `user@host:/path` in the box right above the input whenever i try to enter anything - it does enter my input in the terminal but it does not show suggestions and instead floods the area with the user@host..

### To reproduce

1. Open a new tab or window
2. Create a warpified subshell for a docker container (bash) e.g `docker exec -it {containerName} bash` 
3. Start typing and the "box" above the input will start flooding the input with the `user@hostname:/path`.
4. You might also notice completions from other sessions are unavailable (previous warp commands)

### Expected behavior

That it doesnt flood the screen with this stuff? this makes it really hard to use.
And i also expect to see suggestions based on my warp history - which i now only can see for the current subshell session and not across sessions.

### Screenshots

https://imgur.com/a/Imh3oiy

### Operating system

MacOS

### Operating system and version

MacOS 13.3.1 [M1 Pro]

### Shell Version

Docker: GNU bash, version 5.1.16(1)-release ///// Host: GNU bash, version 3.2.57(1)-release

### Current Warp version

v0.2023.06.27.19.34.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

The one right before the current.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by vorporeal** [comment]
Hey @hareland, mind sharing a screenshot of what you're seeing?

**Comment by hareland** [comment]
> Hey @hareland, mind sharing a screenshot of what you're seeing?

Hi @vorporeal,
Screenshots are in the report - should be this URL: https://imgur.com/a/Imh3oiy

**Comment by vorporeal** [comment]
Ah, thank you! I totally missed the link; sorry!

**Comment by hareland** [comment]
This issue was solved with release `v0.2023.07.04.08.03.stable_02`
