### ISSUE TITLE
XDG Base Directory

### ISSUE THREAD

**Issue by 5ouma** [warpdotdev/Warp#3319]
### Describe the solution you'd like?

```Text
I want to move the Warp configuration directory from `~/.warp` to `$XDG_CONFIG_HOME/warp (~/.config/warp)`.
```

### Additional context

I want to put fewer files/directories in my home directory.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by 5ouma** [comment]
https://github.com/warpdotdev/Warp/issues/814

**Comment by MurtadhaInit** [comment]
I second that! I'd love for this to be made possible and I imagine it's not too hard to implement.

**Comment by Darkstarinternet** [comment]
I would like this implemented too
