### ISSUE TITLE
Warp terminal screen is blank after computer enters sleep mode for extended periods

### ISSUE THREAD

**Issue by JOlivier92** [warpdotdev/Warp#332]
### Describe the bug

```shell
After having my laptop in sleep mode, my warp terminal screen appears blank and is not able to be used.
```

### To Reproduce

1. Open Warp and use as normal
2. Close laptop (let it go to sleep)
3. Come back after 24+ hours
4. Screen is blank

### Expected behaviour

```shell
I expect the terminal to not be blank
```

### Screenshots

<img width="984" alt="Screen Shot 2021-10-30 at 11 36 13 PM" src="https://user-images.githubusercontent.com/16915144/139571360-b2f7c4c2-19dd-415e-85bc-f492a0562d63.png">

### Operating System

MacOS

### OS Version

10.15.7

### Additional context

```shell
The terminal is still active and running as I'm able to run my local development through it, but I'm unable to do anything unless I restart the app or open a new window.

This has happened more than once after having used Warp for a little less than 1 week. Really love the experience so far, but thought I should throw this on your team's radar in case it hasn't been brought up before.
```

**Comment by shina** [comment]
A similar issue happens for me. For me it happens when I connect/disconnect my external display.

Warp version: v0.2022.03.14.08.49.stable_00
MacOS: 12.3

**Comment by elviskahoro** [comment]
@shina @JOlivier92 is this still happening to both of you?

**Comment by shina** [comment]
I never noticed this issue anymore
