### ISSUE TITLE
Warp cuts away opening bracket in git commit command

### ISSUE THREAD

**Issue by sn0wy0wly** [warpdotdev/Warp#3322]
### Describe the bug

We in our company have a convention for git commits, to make them in the following format: 

"[TICKET-NUMBER] Description of the commit"

When using Warp for committing, the opening bracket got trimmed away in the actual commit message. 
This then looks like this: 

"TICKET-NUMBER] Description of the commit"

### To reproduce

1. Navigate to a local git repository.
2. run: `git commit -m "[TICKET-NUMBER] Description of the commit"`.
3. See the actually produced commit with: `git log`.
4. See that the first bracket was removed from the message. 

This does not happen every time, but just occasionally. 

### Expected behavior

The first bracket should never be removed, just like when executing the same commands with Iterm2. 

### Operating system

MacOS

### Operating system and version

Ventura 13.4.1

### Shell Version

zsh 5.9 (arm-apple-darwin22.1.0)

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @sn0wy0wly This is certainly a tough one to reproduce and I wasn't able to get the same error.

Is it possible you may have some unsupported plugin in your rcfiles? https://docs.warp.dev/help/known-issues#list-of-incompatible-tools
Is there a specific repo where the issues happen more often?
Do you ever see the brackets correctly? if so, notice anything different in that scenario vs when you don't see the bracket?
Do you mind sharing a redacted(personal information removed) copy of your `~/.gitconfig` file and `~/.zshrc` file?

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by sn0wy0wly** [comment]
Hi @dannyneira , I had some omyzsh plugins and themes activated... Now it works perfectly. 

Thank you very much for your help.
