### ISSUE TITLE
Reopen closed tab with Control + Shift + T

### ISSUE THREAD

**Issue by spdrstar** [warpdotdev/Warp#3329]
### Describe the solution you'd like?

```Text
reopen a recently closed tab
```

### Is your feature request related to a problem? Please describe.

```Text
closed an important tab 😅
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! We may actually be launching a feature like this in the near future 🤞 (no official ETA, but it's on our radar)

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by elviskahoro** [comment]
This is launched! Note: It's CMD instead of CTRL -> SHIFT-CMD-T
