### ISSUE TITLE
Down arrow key won't work on Warp AI text field

### ISSUE THREAD

**Issue by ElBi21** [warpdotdev/Warp#3330]
### Discord username (optional)

elbi21

### Describe the bug

Pressing the down arrow key doesn't make the cursor move down in the text field of Warp AI

### To reproduce

1. Open the Warp AI panel;
2. Write any text that goes in two lines;
3. Place the cursor on the line above;
4. Press the down arrow key to go to the line below

### Expected behavior

The cursor should move to the line below

### Operating system

MacOS

### Operating system and version

macOS 12.6.7

### Shell Version

zsh 5.8.1

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

5/6 July 2023

### Additional context

I tried rebooting Warp and the OS, but nothing changed. Haven't tried uninstalling and reinstalling Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by ElBi21** [comment]
Update: I tried restarting the computer, but it still doesn't work

**Comment by dannyneira** [comment]
Thanks for letting us know @ElBi21 I was able to reproduce the issue. As a workaround, you can use the mouse to click and move the cursor to wherever you want to edit. We'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by ElBi21** [comment]
Thanks to both @dannyneira and @szgupta ! It's really a minor issue, but I'm glad that it's going to be fixed
