### ISSUE TITLE
Please support profiles

### ISSUE THREAD

**Issue by simonrouse9461** [warpdotdev/Warp#3333]
### Describe the solution you'd like?

```Text
iTerm2 supports creating profiles, which allows quick switching between different shell configurations. When launching a new tab or window, iTerm2 provides a list of profiles to choose from. This is especially useful when working with multiple shells, remote hosts, databases, and virtual machines. Please support such features in Warp.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @simonrouse9461 

We already have a request tracking this over at #3126 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
