### ISSUE TITLE
Send a command to all open windows

### ISSUE THREAD

**Issue by fukai007** [warpdotdev/Warp#3335]
### Describe the solution you'd like?

```Text
Firstly, I divided four windows and wanted to send a command to all windows in the current tab bar
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @fukai007 Thanks for submitting. Warp currently has a Synced input feature that should meet your use case. You can sync the inputs across a single tab (including the panes in the tab), or across multiple tabs in a window. https://docs.warp.dev/features/entry/synchronized-inputs

Closing this request as the feature already exists, but feel free to let us know of any issues with the feature.
