### ISSUE TITLE
Toggle Maximize Active Pane Indication

### ISSUE THREAD

**Issue by Cronos87** [warpdotdev/Warp#3336]
### Describe the solution you'd like?

```Text
When I maximize a pane, it would be lovely to display somewhere on the app that the current tab is maximized; it can confuse people that they may lose some panes.
```

### Is your feature request related to a problem? Please describe.

```Text
At the moment, when I maximize a pane, there is no indication that the current tab is maximized. As a developer, I have a lot of tabs and I may forget that a specific tab is maximized.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for letting us know @Cronos87 So the default behavior of panes is that there is a blue indicator on the top left corner to show which one is active, and this indicator carries over when the pane is maximized. So there isn't currently an indicator on the tab itself, but the blue one should help in the meantime. Once the pane is maximized you should be able to see this with the triangle indicator on the top left corner. Please see my demo:

https://user-images.githubusercontent.com/16809145/226971328-17102163-25cc-4599-82dc-6e04d5e7e53a.mp4

That being said, this isn't the case with pane dimming enabled thou so we can certainly improve in that scenario. For the case where panes are dimmed, we already have a request tracking this over at #3261 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
