### ISSUE TITLE
Warp stopped to work 

### ISSUE THREAD

**Issue by aleksander-dytko** [warpdotdev/Warp#3337]
### Describe the bug

![image](https://github.com/warpdotdev/Warp/assets/102789122/0e3d7d8b-4fc1-4c5d-a0b1-929bdf122cdc)

when I write a new command, there is just an empty line

Same as https://github.com/warpdotdev/Warp/issues/3334

### To reproduce

Open warp, write a command

### Expected behavior

Warp works

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Last week

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @aleksander-dytko Sorry to hear about this blocker. Can you please run `which zsh`, then put the result into `Settings > Features > Session > Startup shell for new sessions > Custom`. In my example, it was /opt/homebrew/bin/zsh, but yours may be different.

![CleanShot 2023-07-10 at 10 07 38](https://github.com/warpdotdev/Warp/assets/16809145/3b2a1cea-fc75-4bec-86df-040fa01c593a)

**Comment by aleksander-dytko** [comment]
@dannyneira thank for quick reaction! 

![image](https://github.com/warpdotdev/Warp/assets/102789122/0837665a-607e-4c33-bbce-ae7a4f9f663a)
Warp stared to work after I changed the startup shell - but it seems I lost my setting (fonts, namespace etc).

Could you provide me an info how to get the rc file?

**Comment by dannyneira** [comment]
could you run `which -s zsh`? I suspect you may have multiple versions of zsh installed.

Also, the `.zshrc` file is located in the user folder typically, i.e. `cat ~/.zshrc`

**Comment by aleksander-dytko** [comment]
I forgot I use [fish](https://github.com/fish-shell/fish-shell) as a default shell - it seems like zsh works fine but fish stopped to work with warp - it works fine with iTerm. 

https://github.com/warpdotdev/Warp/assets/102789122/dcf96ac6-140a-4554-9f51-f9ae7dbc7adf

Fish location is `/opt/homebrew/bin/fish` and after changing it from zsh it does not work as shown above

**Comment by dannyneira** [comment]
The first thing is to try is set `/opt/homebrew/bin/fish` in Warps `Settings > Features > Session > Startup shell for new sessions > Custom`. Then, check your config.fish file for any unsupported plugins. The most common culprit I've seen is the iterm2_shell_integration. You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here <
end
```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>

**Comment by aleksander-dytko** [comment]
@dannyneira thank you very much! 

It was the mentioned issue. The `config.fish` ended up looking like:

```shell
if status is-interactive
    # Commands to run in interactive sessions can go here
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(/opt/homebrew/bin/brew shellenv)"
end

# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
test -e {$HOME}/.iterm2_shell_integration.fish ; and source {$HOME}/.iterm2_shell_integration.fish
end
```
