### ISSUE TITLE
Global Hotkey Window Open on the Wrong Display

### ISSUE THREAD

**Issue by ClipboardJason** [warpdotdev/Warp#3339]
### Describe the bug

Dedicated hotkey window will only show up on Main Screen regardless of settings if the second screen has a fullscreen window.

### To reproduce

1. Open [Arc Browser, Webstorm] and maximize the window
2. Set the global hotkey window to open on the 'Active Window'
3. Make sure the fullscreen window is selected 
4. Open the hotkey window

### Expected behavior

The global hotkey window to open on the screen with the active window

### Operating system

MacOS

### Operating system and version

13.4.1 (22F82)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

It only appears to happen with certain fullscreen applications. I've managed to reproduce it with both Arc and Webstorm.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @ClipboardJason 

We're tracking this issue over at #3275  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
