### ISSUE TITLE
UIUX: Support for Braille fonts

### ISSUE THREAD

**Issue by alexsnaps** [warpdotdev/warp#334]
### Describe the solution you'd like?

As far as I can tell, Warp will currently not display Braille fonts. Adding support for these (e.g. `Apple Braille`) would enable nicer rendering of graphs with libraries like [tui-rs](https://github.com/fdehau/tui-rs) - at least as far I could debug this playing around with the library.

### Is your feature request related to a problem? Please describe.

I use [btm](https://github.com/ClementTsang/bottom) every now and then, which relies on [tui-rs](https://github.com/fdehau/tui-rs)'s widget set. Graphing uses braille font to display more data per cell. Currently all graphs appear empty by default. Adding the `-m` / `--dot_marker` solve the issue, but looses precision.

### Additional context

Example of graph with Braille font support from `Terminal.app`:
<img width="1004" alt="Screen Shot 2021-11-01 at 8 28 53 AM" src="https://user-images.githubusercontent.com/509058/139672346-702ac34d-229f-462b-9b96-a20f71ae01a0.png">
 

What I currently get by default using `btm` on `Warp.app`:
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/509058/139672520-fef76af7-54ce-4adc-ba33-005bc2869c09.png">

Using `-m`:
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/509058/139672718-b1978551-c582-4fc7-8f42-0069f48b5e6b.png">

**Comment by kevinyang372** [comment]
Thanks for reporting. The fix for this should come out today!

**Comment by kevinyang372** [comment]
Should be fixed in the latest release! Feel free to re-open the issue if it is not the case.
