### ISSUE TITLE
Traverse terminal blocks using VIM controls

### ISSUE THREAD

**Issue by Meronkha** [warpdotdev/Warp#3340]
Hey there!

Is it currently possible to traverse console output/blocks using VIM commands? 

A good example of this would be how TMUX allows you to enter "copy mode" in the shell

**Comment by dannyneira** [comment]
Thanks for letting us know @Meronkha 

We're tracking this issue over at #159 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
