### ISSUE TITLE
$PATH ovewritten inside a docker sub-shell

### ISSUE THREAD

**Issue by crogel23** [warpdotdev/Warp#3341]
### Discord username (optional)

crogel

### Describe the bug

Since a couple of updates, when warpifying a docker sub-shell, the $PATH is being overwritten, which leads to some programs no longer working inside that docker shell.

The path is defined in the DockerFile that builds the image.

### To reproduce

1. build a python:3.11.4-slim-bookworm docker image with a custom path defined in the dockerfile.
2. Run the image
3. Warpify the sub-shell
4. Run `echo $PATH`

### Expected behavior

Keep the $PATH as it was before warpifying the sub-shell

### Screenshots

Before
<img width="836" alt="Screenshot 2023-07-10 at 15 12 40" src="https://github.com/warpdotdev/Warp/assets/5739398/48f21416-166f-4a0c-b58b-e8a1b93bec4a">
After
<img width="472" alt="Screenshot 2023-07-10 at 15 15 53" src="https://github.com/warpdotdev/Warp/assets/5739398/f69cbda9-4cf1-41c1-a3fb-a09117a29ac6">

### Operating system

MacOS

### Operating system and version

Mac Ventura 13.4.1 (22F82)

### Shell Version

bash version 5.2.15(1)-release (aarch64-unknown-linux-gnu)

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

I'm not sure exactly, but i'm sure it worked a couple of weeks ago

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @crogel23 We'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by zachbai** [comment]
Hey @crogel23, thanks for filing. What shell is that docker image running?

**Comment by crogel23** [comment]
The outside shell is `zsh 5.9 (x86_64-apple-darwin22.0)`, and the shell inside the docker image is `bash version 5.2.15(1)-release (aarch64-unknown-linux-gnu)`

**Comment by zachbai** [comment]
@crogel23 is it possible that a `.bash_profile` or `.bashrc` is modifying the PATH set by the docker file? We don't do any manipulation of the PATH during "warpification" for bash subshells.

**Comment by crogel23** [comment]
No. The `.bashrc` doesn't have anything like that, and the path is correct after the docker image is running, but it changes after warpifying the subshell.
For some reason, the path after warpifying the subshell is the default path defined in `ENV_PATH` in `/etc/login.defs`
<img width="738" alt="image" src="https://github.com/warpdotdev/Warp/assets/5739398/abdd6a39-a387-4a57-819f-88f7331feba5">

**Comment by crogel23** [comment]
Great. Thanks for your effort.

**Comment by zachbai** [comment]
Glad to hear it, thanks!
