### ISSUE TITLE
Personal workflows not in workflow panel and vice versa

### ISSUE THREAD

**Issue by ekwoka** [warpdotdev/Warp#3343]
### Discord username (optional)

kwoka

### Describe the bug

When you use the save as workflow button it saves to `personal workflows` which as far as I can tell are only accessible by opening the command pallet typing `workflows:` and then start the name of the workflow. Not to be confused with `workflows` which opens the older panel, which is also the only one hotkey bindable.

Meanwhile the workflows panel does show or allow searching any of these.

And workflows made in the workflows panel or .warp/workflows do not appear in the personal workflows pallete.

This is either a bug in the software or a bug in the design, but it's definitely wrong.

Also doesn't seem to be a way to clean out/remove `personal workflows`?

### To reproduce

Use workflows

### Expected behavior

Custom workflows show in both the new workflows pallete and the older workflows panel, regardless of how they were made.

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

zsh

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by ekwoka** [comment]
Well, in that case, the new one is easier to create but harder to use.

There isn't a direct hotkey option to the new one to search, so the older one is easier to use.

**Comment by suparikoli** [comment]
Im not able to move my workflow files that I create on the drive
