### ISSUE TITLE
Hidden input line after nested SSH

### ISSUE THREAD

**Issue by EslamElHusseiny** [warpdotdev/Warp#3345]
### Describe the bug

The input line become hidden under the previous block after having a nested SSH sessions (i.e. ssh to bastion box and then to the target box)

### To reproduce

ssh (box 1)
ssh (box 2)

### Operating system

MacOS

### Operating system and version

13.4.1

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @EslamElHusseiny Sorry to hear about this issue, could you please provide a video of the issue or screenshots? I suspect your input may be hidden behind the [sticky command header](https://docs.warp.dev/features/blocks/sticky-command-header), but a visual would help confirm this. If so, I recommend disabling the sticky command header as a workaround. Also, you can disable the [SSH Wrapper](https://docs.warp.dev/features/ssh) by navigating to `Settings > Features`. Blocks will stop working but with it disabled, SSH should work as normal.

**Comment by dannyneira** [comment]
Any luck with the above? @EslamElHusseiny

**Comment by dannyneira** [comment]
Closing for no response as stale, feel free to reopen if you find the issue persists.
