### ISSUE TITLE
Custom hotkeys not working in active prompt

### ISSUE THREAD

**Issue by yix** [warpdotdev/Warp#3346]
### Describe the bug

If active prompt (where you can type) has focus no hotkeys are working.

### To reproduce

Assign "Command ->" hotkey to "Activate Next Tab"
Go to terminal window and click active prompt.
Try using hotkey. It will not work.

### Expected behavior

Next tab should be activated

### Operating system

MacOS

### Operating system and version

13.4.1

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @yix Sorry about this blocker. There is a known issue with International keyboard shortcuts not registering, are you using a non-US keyboard input method by any chance? If so, I recommend you switch to US(ABC) input method and try the keybinds again. If not, then please provide a video/screenshot of the issue along with a redacted (no personal information) copy of your default shell rc files (`.zshrc` / `.bashrc` /  etc.)

**Comment by dannyneira** [comment]
@yix  any luck with the above?

**Comment by yix** [comment]
@dannyneira, nope. Custom shortcuts do not work when cursor in the prompt.

**Comment by dannyneira** [comment]
Heard, make sure you don't have anything else bound to `cmd right` in the Settings > Keyboard shortcuts menu. By default, it's bound to End / Move cursor to the end so that may be the reason it's not switching tabs for you.

![CleanShot 2023-09-01 at 14 23 22](https://github.com/warpdotdev/Warp/assets/16809145/23e11eea-cb08-46de-ab10-cfd2d54faf3c)

**Comment by dannyneira** [comment]
Closing as stale.
