### ISSUE TITLE
ssh timeout unable to using terminal anymore

### ISSUE THREAD

**Issue by metalbreeze** [warpdotdev/Warp#3347]
### Describe the bug

everytime,  ssh timeout or mac close lid,
that will lead to following screen and not able to reconnect it again.(to fix the issue ,only way is close this tab) 
<img width="531" alt="image" src="https://github.com/warpdotdev/Warp/assets/12639549/fab09e6c-57eb-42b6-96ec-98170497f20a">
maybe because customize PS1?

echo $PS1
\[\e]0;\u@\h:\w\a\]\[\e[36;40m\]$?\[\e[35;40m\]$(date +%d%H%M)#\[\e[36;40m\]\W>\[\e[0m\]

### To reproduce

1.ssh some host.
2.wait be cutoff ssh connection 
3. it happens.

### Operating system

MacOS

### Operating system and version

13.4.1

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @metalbreeze

We're tracking this issue over at #2476 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue.

We'll be closing this as a duplicate.
