### ISSUE TITLE
Workflow shortcut no longer works on v0.2023.07.04.08.03.stable_02

### ISSUE THREAD

**Issue by Buzzkill-McSquare** [warpdotdev/Warp#3350]
### Describe the bug

Since updating to v0.2023.07.04.08.03.stable_02 the default shortcut for opening workflows in MacOS no longer works. Interestingly, while resetting the shortcut back to it's default won't work, if I explicitly bind it to the same key combo as the default combo it will work.

### To reproduce

Perform the default keyboard shortcut on MacOS for opening the workflow picker (Ctrl + Shift + R). Verify the picker doesn't appear. Change the shortcut to something else (including explicitly binding the default shortcut) and verify that the picker appears. Reset to the default shortcut and verify that it stops working.

### Expected behavior

The default shortcut for opening the workflow picker should work.

### Operating system

MacOS

### Operating system and version

Ventura 13.3

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @Buzzkill-McSquare Thanks for submitting. This is a known issue as the YAML workflows an Warp Drive Workflows are separate. Warp will indefinitely support the [YAML Workflows](https://github.com/features/entry/yaml-workflows), which includes personal and community workflows sourced from an open-source repository.
If needed, you can continue to access your .yaml file workflows using [Command Search](https://github.com/features/entry/command-search) CTRL-R or the [Command Palette](https://github.com/features/command-palette) CMD-P. However, these file-based workflows will not be available to access, organize, or share in Warp Drive.
Although we encourage you to create workflows with the new workflow editor in Warp Drive, we hope you’ll find it a much easier experience, there are plans for Warp Drive workflows to be imported/exported to prevent vendor lock-in.

Learn more about this here: https://docs.warp.dev/features/warp-drive/workflows#support-for-yaml-workflows
