### ISSUE TITLE
Global Hotkey Window / Floating window

### ISSUE THREAD

**Issue by luckslovez** [warpdotdev/Warp#3351]
### Discord username (optional)

luckylucks#9192

### Describe the solution you'd like?

```Text
Would it be feasible to allow the hotkey window to be a normal (floating) window? This would allow for resizing easily with tools like [rectangle](https://rectangleapp.com/).
```

### Is your feature request related to a problem? Please describe.

```Text
The global hotkey is awesome to reach out to warp quickly (as opposed to cycle through apps until getting to it), but the fixed window makes it not flexible enough to be used as a regular terminal window. Sometimes you might need it at a third of the right side of the screen, sometimes at the at a quarter of the bottom and so on.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @luckslovez thanks for submitting, afaik, when you have the hotkey window opened, you can resize it and it will remember the size/location which you set it to. The only caveat to this is with the "Active screen" option, when you open the window on a different screen it will default to the original size in your settings, but as long as it remains on a screen it will retain the size/location you changed it to. With the other screen settings (main screen, scree 2, etc.) it should remember its size/location. Here's more info on the feature. https://docs.warp.dev/features/windows/hotkey-window

https://github.com/warpdotdev/Warp/assets/16809145/88d54071-7607-41e1-965c-cdecdc522e89

I hope this helps! Closing as the ability to resize already exists for hotkey window. You can track the progress of the ability to permanently resize the active window here: https://github.com/warpdotdev/Warp/issues/1399
