### ISSUE TITLE
Ability to escape {{}} in Workflows

### ISSUE THREAD

**Issue by tomaley** [warpdotdev/Warp#3352]
### Describe the solution you'd like?

```Text
Many of the CLI tools I frequently use support GoTemplate formatting of output. While powerful and useful, these templates are a pain to craft each time they're needed so I would love to be able to save them to workflow... but the mustache syntax conflicts with the 'arguments' feature of workflow.

A command I used today:

ibmcloud cr image-list --format '{{if eq .Namespace "personal-dev"}}{{.Repository}}:{{.Tag}}{{end}}' | xargs ibmcloud cr image-rm
 
to clear out all images in my 'personal-dev' registry namespace would be a prime candidate to be saved away in workflow with the 'personal-dev' element being an argument so I can apply this to namespaces in a parameterized fashion. The issue is that the command cannot be saved because it wants to make `{{end}}` an argument.

Kubectl commands supporting `-o go-template` have the same issue and again make prime candidates for parameterized workflow entries.
```

### Is your feature request related to a problem? Please describe.

```Text
A command I used today:

ibmcloud cr image-list --format '{{if eq .Namespace "personal-dev"}}{{.Repository}}:{{.Tag}}{{end}}' | xargs ibmcloud cr image-rm
 
to clear out all images in my 'personal-dev' registry namespace would be a prime candidate to be saved away in workflow with the 'personal-dev' element being an argument so I can apply this to namespaces in a parameterized fashion. The issue is that the command cannot be saved because it wants to make `{{end}}` an argument but that is part of the GoTemplate 'if' directive.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! 

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by zheng** [comment]
Thanks for this request! I'm thinking what the product should do is allow you to escape if what you want is the explicit moustache. It looks like the standard syntax in HTML would be to do `{{{end}}}`. Does that seem like the right approach to you?

**Comment by kevin-lucas-simon** [comment]
I have this issue too with some Docker related commands. For example `docker stats --format "table {{.Name}}	{{.CPUPerc}}"` for displaying the CPU stats of my containers.

**Comment by 0Knot** [comment]
You can take a detour and enter `DOCKER_TEMPLATE=$(echo '{{ json .Mounts }}')` in the linux shell

Then use the following syntax in the workflow
```shell
docker inspect --format "$DOCKER_TEMPLATE" {{DOCKER_IMAGE}} | python3 -m json.tool
```
I hope the official can optimize this syntax

**Comment by tukusejssirs** [comment]
I am also experiencing this bug.

IMHO this is what Warp should do:

- Wrap should treat `{{anything}}` as a literal string (everything is treated literally by default, users must make a part of the code a variable _explicitly_);
- Warp should make `{{anything}}` clickable;
- _when_ a user clicks on `{{anything}}`, it would create a variable (with description and default value text boxes);
- alternatively, there should be a way to select `{{anything}}` by keyboard (without mouse/touchpad/TrackPoint; e.g. using a special keyboard shortcut like <kbd>Alt</kbd>+<kbd>1</kbd>) and then press <kbd>Enter</kbd>.

Another way to accomplish this is to select a part of the code and click a button (e.g. `Make a variable`) or press a keyboard shortcut (e.g. <kbd>Alt</kbd>+<kbd>V</kbd>).

**Comment by dannyneira** [comment]
Hi folks, we've added the ability to escape arguments in workflows by enclosing text in triple brackets in the latest version of Warp. Please update and let us know if the issue persists.

**Comment by kevin-lucas-simon** [comment]
@dannyneira I have tried it, now it works for me, thanks!
