### ISSUE TITLE
Command Search panel too high

### ISSUE THREAD

**Issue by srl295** [warpdotdev/Warp#3353]
### Describe the bug

I use the "global popup Warp shell" (not sure what it's called), Control-Shift-backquote from any app.

the "Command Search" panel is 15 items high, but if the popup window is shorter than that, the Command Search (Control-R) doesn't function properly.  I can't see my cursor, or the selected item. 

### To reproduce

1. bring up any shell window
2. Make the window shorter than 15 rows
3. hit Control-R and search for something

### Expected behavior

Command Search should resize to fit

### Screenshots

<img width="318" alt="image" src="https://github.com/warpdotdev/Warp/assets/855219/3db27a4e-fe45-4beb-a437-38fde25490db">

### Operating system

MacOS

### Operating system and version

Ventura 13.4.1 (22F82)

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

don't remember, but I use ^R every day and don't remember seeing this issue before.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know. The command search panel is a standard height, but the width can be adjusted with the mouse. AFAIK it appears to have a minimum height so there could certainly be some improvements around that. We'll post any further updates on this thread.

**Comment by srl295** [comment]
Warp windows don't seem to hav a minimum height

**Comment by dannyneira** [comment]
I agree, that's the part that could use improvement, either a minimum height on warp window, or better yet, being able to resize the command search ( or any other panels ) dynamically to whatever size Warp window is set.

**Comment by dannyneira** [comment]
Hey @srl295 Thanks for submitting, we've fixed the issue with the input being hidden for command search when the Warp window is small. Please update to the latest version of Warp and let us know if the issue persists.

**Comment by dannyneira** [comment]
Hey @srl295 Thanks for submitting, we've fixed the issue with the input being hidden for command search when the Warp window is small. Please update to the latest version of Warp.

![CleanShot 2024-01-03 at 10 27 51](https://github.com/warpdotdev/Warp/assets/16809145/2450c2a6-52bb-4258-9ea7-ff5f5713e7c8)

Closing as resolved, but please let us know if the issue persists.

**Comment by srl295** [comment]
@dannyneira looks and works great
