### ISSUE TITLE
Bad characters being inserted after an SSH session dies

### ISSUE THREAD

**Issue by elliottecton** [warpdotdev/Warp#3356]
### Discord username (optional)

elliott.ecton

### Describe the bug

When launching a new warp instance, everything is great. I can ssh into my RHEL server, and everything is still great. If I let the ssh session timeout, that is when the bug appears. The terminal window becomes unusable -- inserting characters that print as tildes (~) and 0s and 1s into each command I try to type. These obviously break the command. To fix the issue, I have to close that window or tab, and start a new one. Screenshot of the issue below:

![BB597B9A-1F5D-4DE2-A1EF-0A91EA96F7F5_1_105_c](https://github.com/warpdotdev/Warp/assets/7132555/3b2b15e2-e160-46a2-ba69-58b8f9818af4)

### To reproduce

Steps to repro:

1. Open a new warp window
2. SSH into a linux box (RHEL 9.1 in my case)
3. Let the session timeout
4. Try to run commands in the same window

### Expected behavior

When an SSH session timeout, the terminal should still be usable

### Screenshots

![Image 7-12-23 at 11 08 AM](https://github.com/warpdotdev/Warp/assets/7132555/7de183ce-7aca-4d21-92b9-629deb9e3c2e)

### Operating system

MacOS

### Operating system and version

macOS Ventura 13.3.1 (22E261)

### Shell Version

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

June 2023 (Just an estimate)

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @elliottecton, sorry about this issue. As a workaround, you can close the tab and open a new one to reconnect to the ssh session.

We're tracking this issue over at #2476  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
