### ISSUE TITLE
Tab erratic behavior when ssh'ed into a device

### ISSUE THREAD

**Issue by TheFern2** [warpdotdev/Warp#3357]
### Describe the bug

Tab only works for certain programs when ssh'ed into a device.

### To reproduce

1. Ssh into something
2. Try different programs ls, cd, vim

### Expected behavior

Expected tab to autocomplete, autocomplete works for those programs under regular terminal.

### Screenshots

I am hitting tab there, and nothing is happening. It seems to be happening with certain programs ss happens with ls, but with others like vim tab works.

![image](https://github.com/warpdotdev/Warp/assets/10265682/06b199af-8520-4e57-b2ce-8cf327612afa)

### Operating system

MacOS

### Operating system and version

Ventura 13.3.1

### Shell Version

fish 3.5.1 on mac, bash 4.4.12 on ssh'ed (Debian 9)

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I am an embedded software engineer who ssh's tons onto other devices, definitely a blocker for me in using this everyday.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @TheFern2 thanks for letting us know. What your screenshot shows appears to be the Autosuggestions, which will show a suggested command that you can complete with the right-arrow, not tab. Please learn more about the feature here and let us know if the issue persist when you disable it (cmd-p, then search for autosuggestions) https://docs.warp.dev/features/editor/autosuggestions

**Comment by dannyneira** [comment]
Hey @TheFern2 thanks for letting us know. What your screenshot shows appear to be the Autosuggestions, which will show a suggested command that you can complete with the `RIGHT-ARROW`, not `TAB`. Please learn more about the feature here and let us know if the issue persists when you disable it (cmd-p, then search for autosuggestions) https://docs.warp.dev/features/editor/autosuggestions

**Comment by TheFern2** [comment]
@dannyneira  Thanks for the tip on autocompletion I'll make sure not to confuse it in the future, however this does seem like a legit bug, I am hitting tab and nothing gets generated, it should tab to `/usr/`

![image](https://github.com/warpdotdev/Warp/assets/10265682/a0d5579d-2438-4501-bd45-05918c43eba2)

No issues tabbing in default terminal:

![image](https://github.com/warpdotdev/Warp/assets/10265682/5768a028-268f-4d85-aee0-ebace7b77db3)

**Comment by TheFern2** [comment]
Also disabling autosuggestions doesn't make a difference in results in my previous comment.

**Comment by dannyneira** [comment]
Thanks for confirming. A few suggestions, use `/usr/bin/ssh` to connect to the remote machine, or try upgrading the remote machine's bash, and/or change to zsh/fish and see if the issue persists.

**Comment by TheFern2** [comment]
Using `/usr/bin/ssh` works, I can't upgrade remote machine's bash they are production machines and really really old with debian9, I think is already running the latest from package manager. Anyways I'll use the workaround, thanks!
