### ISSUE TITLE
Text formatting issue

### ISSUE THREAD

**Issue by rombar-hijra** [warpdotdev/Warp#3359]
### Describe the bug

example usage 
`ping google.com`
output :
<img width="1266" alt="image" src="https://github.com/warpdotdev/Warp/assets/105186126/7b6f96a6-a2e3-43e5-8642-b7621f42b82b">

### To reproduce

use setup display not default one
<img width="448" alt="image" src="https://github.com/warpdotdev/Warp/assets/105186126/03e287b0-f1ff-440c-aa97-bfa3389b41cb">

and execute cmd ping on warp

### Expected behavior

text print format like terminal output
<img width="451" alt="image" src="https://github.com/warpdotdev/Warp/assets/105186126/65addaa3-469a-4b06-b5b1-e41394fa8739">

### Operating system

MacOS

### Operating system and version

Mac ventura 13.2.1

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @rombar-hijra, unfortunately, this doesn't reproduce on my end with the instructions you provided. I suspect the issue may be related to the really old version of bash you're on. Could you please update bash to the latest version (5.2.15) and/or change to zsh shell as default and see if the issue persists?

**Comment by dannyneira** [comment]
@rombar-hijra any luck with the above?

**Comment by rombar-hijra** [comment]
hi @dannyneira , after updating warp to latest version i cannot reproduce the issue again.
so for now i think it safe for now.
