### ISSUE TITLE
I Can't Starting fish shell when i start app

### ISSUE THREAD

**Issue by aizk** [warpdotdev/Warp#3360]
### Describe the bug

When I start this app, it can’t load fish shell. 

### To reproduce

1. change to bash
2. start fish will print error

<img width="1424" alt="image" src="https://github.com/warpdotdev/Warp/assets/6058767/45098007-a7d1-4d45-a3ef-66e4f4673498">

### Screenshots

<img width="1022" alt="image001" src="https://github.com/warpdotdev/Warp/assets/6058767/cbb50eb8-14e8-498e-94c3-1bf8135f19c8">

### Operating system

MacOS

### Operating system and version

Big Sur 11.5.1

### Shell Version

fish, version 3.3.1

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @aizk thanks for letting us know. This might be from the bootstrap script, but I can't seem to reproduce this on my end. 

![CleanShot 2023-07-13 at 12 11 39](https://github.com/warpdotdev/Warp/assets/16809145/bb2f3aae-5c78-49ff-bbc7-5336e01d1464)

Which is the default shell you want to use, bash or fish? (see more on this here: https://docs.warp.dev/getting-started/using-warp-with-shells)
Can you reproduce this if you set your default shell to fish? If so, Could you provide a redacted (personal info removed) copy of your config.fish?

**Comment by aizk** [comment]
@dannyneira yes, i want to set my default shell to fish.  but it can't start with warp... will bolck at Starting fish... like this screent shot https://user-images.githubusercontent.com/6058767/253147901-cbb50eb8-14e8-498e-94c3-1bf8135f19c8.png

so, i change default shell to bash and start fish with `/opt/homebrew/bin/fish`.

it will start a subshell, but i want using default shell, not sub shell

this is my config.fish:

```
if status is-interactive
    # Commands to run in interactive sessions can go here
    fish_add_path -p /opt/homebrew/bin /opt/homebrew/opt/go@1.16/bin 

    [ -f /opt/homebrew/share/autojump/autojump.fish ]; and source /opt/homebrew/share/autojump/autojump.fish

	alias sed gsed
end
fish_add_path /opt/homebrew/opt/node@16/bin

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
eval /Users/huborui/opt/anaconda3/bin/conda "shell.fish" "hook" $argv | source
# <<< conda initialize <<<
```

**Comment by dannyneira** [comment]
Sorry about this, but i still cant reproduce the issue with your config file. You can try one of the following: put the content of your config in the following conditional.
```
if test "$TERM_PROGRAM" != "WarpTerminal"
<content of your config file here>
end
```
or try using fish with an empty config file, jus trying to rule out the an issue with the config file this way. If there are still issues i recommend you try and upgrade fish to the latest version (3.6.1).

**Comment by dannyneira** [comment]
@aizk any better with the above suggestion?

**Comment by dannyneira** [comment]
@aizk bump

**Comment by dannyneira** [comment]
Closing as stale, feel free to reopen if the above suggestions didnt help.
