### ISSUE TITLE
Long git branches can overlap with the icons on the Block output (bookmark icon, etc)

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#3361]
### Describe the bug

Long git branches can overlap with the icons on the Block output (bookmark icon, etc)

### To reproduce

Create a git branch that has a long name

### Operating system

MacOS

### Operating system and version

NA

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

![CleanShot 2023-07-12 at 21 43 07](https://github.com/warpdotdev/Warp/assets/29553206/9cb758bc-27c8-4e04-bb5a-84015db36989)

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for this feature request! AFAIK we'll be working on improving this in the near future. Possibly having a background to the block buttons so they don't overlap the prompts/text.

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Closing as resolved, this has been fixed in recent version of Warp.
