### ISSUE TITLE
The Chinese characters displayed abnormally

### ISSUE THREAD

**Issue by JasonLamv-t** [warpdotdev/Warp#3366]
### Describe the bug

The Chinese characters output of git's commands display in '?', and for the `ls` command, it shows the Unicode code point.

### To reproduce

`touch` a file name with Chinese characters, such as '测试.test', then run `ls` and check the output.

### Screenshots

<img width="1196" alt="image" src="https://github.com/warpdotdev/Warp/assets/39087996/55415cb3-3bf3-4fd9-b53a-248e77d7ed2d">
<img width="1055" alt="image" src="https://github.com/warpdotdev/Warp/assets/39087996/453eef01-f58b-4f4e-bf57-3003bb7622dd">
<img width="941" alt="image" src="https://github.com/warpdotdev/Warp/assets/39087996/19667845-c20a-476d-ba7d-35a05de45a49">
<img width="781" alt="image" src="https://github.com/warpdotdev/Warp/assets/39087996/0fa9b84c-3897-443b-83c4-a72cba58da21">

### Operating system

MacOS

### Operating system and version

13.4.1

### Current Warp version

v0.2023.07.11.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by JasonLamv-t** [comment]
Supplement: the characters show normal in the command hints.
<img width="880" alt="image" src="https://github.com/warpdotdev/Warp/assets/39087996/a66b2713-9a78-433f-aa16-04506249fe40">

**Comment by JasonLamv-t** [comment]
update: it seems my system's problem, after exec this:
<img width="543" alt="image" src="https://github.com/warpdotdev/Warp/assets/39087996/f30b041f-a2b8-4e65-8fbf-3d96ac05ca9e">
then I run the `gst` again, and everything works well:
<img width="644" alt="image" src="https://github.com/warpdotdev/Warp/assets/39087996/9d08eae2-c344-4149-931e-d75a0940d303">

**Comment by JasonLamv-t** [comment]
I fix this problem via set the lang env in the zsh config.

**Comment by ZheCheng** [comment]
> 我通过在 zsh 配置中设置 lang env 来解决这个问题。

我也用你的方法解决了。在root和其他用户下显示正常，但在我的linux用户下出现问题。真奇怪。
