### ISSUE TITLE
Workflows shortcut should be able to access all worklows (work like Ctrl+R w:)

### ISSUE THREAD

**Issue by elchead** [warpdotdev/Warp#3367]
### Describe the solution you'd like?

```Text
So far, Ctrl+R w: works but I'd prefer to access them through a single shortcut
```

### Is your feature request related to a problem? Please describe.

```Text
I'd like a quick shortcut to access my workflows, especially those new and easy to create WarpDrive ones.
The existing 'Workflows' shortcut doesn't include WarpDrive and it doesn't prioritize my own workflows (over community ones).
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Appreciate you letting us know. AFAIK the workflows from Warp Drive show up closest to the input editor in the command search (CTRL-R) Panel. and there is a fuzzy search algo that lets you find what you're looking for there quickly.

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by elchead** [comment]
Thanks for the Ctrl-R tip. Indeed, it seems to match my Warp drive commands first. That's a good fix for now

**Comment by dannyneira** [comment]
Thanks for letting us know. Closing as resolved since a feature exists that suits the use case. [Command Search](https://docs.warp.dev/features/entry/command-search)
