### ISSUE TITLE
Input Editor: History cleared on restart

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/warp#337]
### Describe the bug

```shell
Whenever warp restarts the history of prior commands (both successful commands and unsucessful commands) are lost.
```

### To Reproduce

Submit commands.
Open history dropdown and navigate on historical commands.
Confirm that your commands were saved.
Restart warp.
The commands that you ran are lost.

### Expected behaviour

```shell
To keep all historical commands.
```

### Operating System

MacOS

### OS Version

11.6.1

**Comment by BearGuy** [comment]
While this gets fixed, a temporary solution is to add `setopt INC_APPEND_HISTORY` to your `zshrc`. It's what worked for me!
