### ISSUE TITLE
Can't sign up to Warp if email has a sub-domain

### ISSUE THREAD

**Issue by andrew-monroe** [warpdotdev/Warp#3370]
### Describe the bug

I'm trying to sign up to make an account with Warp, but I do not get the required verification email. It is not in my spam folder.

Email I am using is: `warp at me dot andymonroe dot dev`

Re-sending email also does not work.

### To reproduce

1. Sign up for a new account.
2. Use email for sign up.
3. Notice that email is not received.

### Operating system

MacOS

### Operating system and version

13.4 (22F66)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @andrew-monroe. Sorry to hear about this blocker with onboarding to Warp! 

I wonder if it is due to the subdomain in the email `warp@**me.**andymonroe.dev`. Is there another email with no subdomain you could try just to confirm? (i.e. `andymonroe2023@gmail.com`) This will help us out since I don't have a ready-made sub-domain email address to attempt to reproduce this on. 🙏

**Comment by dannyneira** [comment]
@andrew-monroe any luck with the above suggestions?

**Comment by dannyneira** [comment]
Or you can try with a tag like `me+warp@andymonroe.dev`, meanwhile I'll let the team know about the issue with sub-domain emails.

**Comment by timhi57** [comment]
Looks like subdomains are a problem for signup.  I'm in Australia and could not sign up with name@company.com.au or name@company.net.au email addresses.  No email was received and no error received when I submitted my email address.  I eventually signed up OK with my name@icloud.com email address.

**Comment by andrew-monroe** [comment]
I've moved on. Closing this to un-clutter my Issues tab.
