### ISSUE TITLE
Prompt no longer shown on same line as input

### ISSUE THREAD

**Issue by ashebanow** [warpdotdev/Warp#3371]
### Discord username (optional)

impasta_syndrome

### Describe the bug

I recently updated warp, and ever since my fancy starship prompt appears on a line above my input area. I checked on the same machine with Apple's Terminal and iTerm2 and they do not behave the same way. It looks like an intentional change.

FWIW, though, I am running Sonoma Beta 3, which could be a factor here.

### To reproduce

1. Setup a starship prompt
2. start warp
3. observe 

### Screenshots

  
![Screenshot 2023-07-14 at 4 44 24 PM](https://github.com/warpdotdev/Warp/assets/11263/d26a501c-2097-41b5-bc7f-911d17c6be05)

### Operating system

MacOS

### Operating system and version

Sonoma Beta 3

### Shell Version

zsh 5.9 (arm-apple-darwin22.1.0)

### Current Warp version

v0.2023.07.11.08.03.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

not sure, probably a month ago since I was out of town

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/2304

**Comment by dannyneira** [comment]
@ashebanow We're working on this now and you can track it here https://github.com/warpdotdev/Warp/issues/2304

**Comment by ashebanow** [comment]
Awesome, thanks!
