### ISSUE TITLE
Outdated document or Bug relating to opening launch configration palette

### ISSUE THREAD

**Issue by yym2** [warpdotdev/Warp#3380]
### Describe the bug

<img width="962" alt="图片" src="https://github.com/warpdotdev/Warp/assets/4157030/7eba73b8-f8ff-4e05-ac50-3421d37bcfcd">

In the https://docs.warp.dev/features/sessions/launch-configurations, you can access launch configuration palette from command palette by typing "#", or even add a new by by +, however this is not true in Warp v0.2023.07.11.08.03.stable_00 (lastest).
<img width="1060" alt="图片" src="https://github.com/warpdotdev/Warp/assets/4157030/0e62dc84-1a0c-42c8-9b2a-1b7db2855478">

I am new to Warp,  so I don't know it is because the document is outdated  and this feature is removed already or simply a bug. Obviously Ctrl + Cmd + L still works but there is no + to add new ones.
<img width="1060" alt="图片" src="https://github.com/warpdotdev/Warp/assets/4157030/87eb3254-6ad3-46e7-81ae-cfa77d7e2e6f">

### To reproduce

1. cmd + p to call up command palette
2. type # to call up launch configuration palette
3. Nothing comes up and there is no + button.
4. It would be nice to have + and - or even edit to manage launch configurations from the palette rather then dig into the folder.

### Expected behavior

configuration palette

### Operating system

MacOS

### Operating system and version

10.15

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know, access to the feature was slightly redesigned, and I've updated those docs to reflect the accurate shortcuts. https://docs.warp.dev/features/sessions/launch-configurations

Hope this helps!
