### ISSUE TITLE
Enable select while scrolling in vim

### ISSUE THREAD

**Issue by BugWriter2** [warpdotdev/Warp#3381]
### Describe the solution you'd like?

```Text
When selecting multiple lines in `vim` and reaching the bottom of the current window, scrolling is not possible.
I want the scrolling to exceed the current window's boundaries and allow access to a larger area
(so that I can copy more text with `command + c`).
```

### Additional context

![demo](https://github.com/warpdotdev/Warp/assets/26344199/f9b3e45b-7500-4490-ae02-14e11ac5993c)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! I recommend you try and enabled mouse reporting/scrolling in the settings, you may be able to mouse scroll while you select 🤞 https://docs.warp.dev/features/full-screen-apps#mouse-and-scroll-reporting

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Thanks for this feature request! I recommend you try and enabled mouse reporting/scrolling in the settings, you may be able to mouse scroll while you select 🤞 https://docs.warp.dev/features/full-screen-apps#mouse-and-scroll-reporting

Please add a 👍 to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Any luck with my recommendation? @BugWriter2

**Comment by BugWriter2** [comment]
@dannyneira Thank you for your suggestion. However, I have tried out the toggle and it appears that it does not make any difference. I am still unable to keep scrolling once I have reached the end of the current display, as shown in the gif in the description section.

<img width="508" alt="image" src="https://github.com/warpdotdev/Warp/assets/26344199/b4192eaa-d5de-4e6e-8e18-6820ea7f7711">

<img width="508" alt="image" src="https://github.com/warpdotdev/Warp/assets/26344199/4c90f801-04ab-40a3-b77e-3e982eb2ee20">

**Comment by dannyneira** [comment]
Closing this issue, unsure what the user is requesting. Please try the suggestions above to resolve the scrolling issue.
