### ISSUE TITLE
Warp AI baked in

### ISSUE THREAD

**Issue by agluck91** [warpdotdev/Warp#3382]
### Describe the solution you'd like?

```Text
I would love to see warp ai baked right into the command line, rather than it being a seperate pane.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! As a stopgap to this request, you can quickly pull up Warp [AI Command Suggestions](https://docs.warp.dev/features/warp-ai/ai-command-suggestions) in the input editor with `#` in the input. Also, you can quickly pull up [Warp AI](https://docs.warp.dev/features/warp-ai) on a selected block with `SHIFT-CTRL-SPACE`, but I agree Warp AI could be better integrated into the input as well. 

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Thanks for this feature request! As a stopgap to this request, you can quickly pull up Warp [AI Command Suggestions](https://docs.warp.dev/features/warp-ai/ai-command-suggestions) in the input editor with `#` in the input. Also, you can quickly pull up [Warp AI](https://docs.warp.dev/features/warp-ai) on a selected block with `SHIFT-CTRL-SPACE`, but I agree Warp AI could be better integrated into the input as well. 

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Hey @agluck91 We're not going to implement this now, but interesting feedback for the next set of improvements to Warp AI. We appreciate your patience and thanks for trying Warp!
