### ISSUE TITLE
fzf support

### ISSUE THREAD

**Issue by lostman** [warpdotdev/Warp#3383]
### Describe the solution you'd like?

```Text
In a standard terminal, I can type `cat /tmp/**` and select a file using `fzf`. This doesn't work in `warp`.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @lostman 

We already have a request tracking this over at #1647

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
