### ISSUE TITLE
Text contrast for confirmation dialog needs to be increased

### ISSUE THREAD

**Issue by graysoncash** [warpdotdev/Warp#3388]
### Discord username (optional)

grayson#2388

### Describe the bug

While in dark mode, the text contrast for the confirmation button in the create/delete confirmation dialog needs to be increased. It seems to be inheriting the same color from light mode, which looks to be an acceptable contrast.

Additionally, the confirmation button justification between the create and delete confirmation dialog differs. Unsure if this is intentional.

### To reproduce

1. Set macOS appearance to "Dark"
2. In Warp, open Warp Drive
3. Create or delete a new workflow folder

### Screenshots

**Dark mode**

![Screenshot 2023-07-13 at 16 36 15](https://github.com/warpdotdev/Warp/assets/3530269/468df402-dbee-44ae-9eac-10f5fa168c44)

![Screenshot 2023-07-18 at 10 45 44](https://github.com/warpdotdev/Warp/assets/3530269/45fbf705-8727-46d0-b85f-47518af28cba)

**Light mode**

![Screenshot 2023-07-13 at 16 36 07](https://github.com/warpdotdev/Warp/assets/3530269/42542eae-a19a-48a3-b2d1-9702ef58abfe)

### Operating system

MacOS

### Operating system and version

MacOS 13.4 (22F66)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @cashgl. We'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment]
Hey @cashgl Could you please provide more details on the reproduction of this issue? we're not seeing the same on our end. Which theme are you using(if custom, please share with us)? any changes in your mac settings that may affect this? Any other details/changes that may help us reproduce this?

**Comment by cashgl** [comment]
Shoot, I'm using one of the themes from warpdotcom/themes. I'll move to there
