### ISSUE TITLE
Make execution date and time more visible

### ISSUE THREAD

**Issue by cachila** [warpdotdev/Warp#3390]
### Describe the solution you'd like?

```Text
I would like to know when an execution happened without mousing over the execution duration.
```

### Additional context

Maybe this feature is already there but I couldn't find this option.

![image](https://github.com/warpdotdev/Warp/assets/5391176/01e20dc8-7657-43ed-9165-e0929183b8f2)

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! the default prompt can certainly be improved, as a possible stopgap, please look into custom prompts that can be configured to show the time. https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by cachila** [comment]
Thank you!

**Comment by ismael-xops** [comment]
Thanks!
