### ISSUE TITLE
After using screen in ssh, the latest input command cannot be seen.

### ISSUE THREAD

**Issue by Cat7373** [warpdotdev/Warp#3391]
### Describe the bug

After using screen in ssh, the latest input command cannot be seen.

### To reproduce

1. Connect to a server via ssh
2. Create a screen with screen -dmS test
3. Use screen -r test to enter the screen for operation
4. Press Ctrl + A, then D to exit screen
5. Now enter any command, it will be blocked and cannot be seen

### Expected behavior

Newly entered commands should not be blocked

### Screenshots

<img width="714" alt="iShot_2023-07-19_13 02 46" src="https://github.com/warpdotdev/Warp/assets/9296576/7f93a12f-3e0f-4875-b2eb-d4bba0246a26">

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

fish, version 3.6.1

### Current Warp version

v0.2023.07.11.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

#### Local:
1. MacOS 13.4.1
2. fish 3.6.1

#### Server:
1. Ubuntu Server 22.04
2. fish 3.3.1

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by Cat7373** [comment]
@dannyneira  reproduce video: http://172.96.194.76:81/iShot_2023-07-25_08.13.39.mp4

**Comment by Cat7373** [comment]
Seems like fish is indeed lower than 3.4.0 on the server, but this is the latest version from Ubuntu's default sources

**Comment by Cat7373** [comment]
I upgraded the server to fish 3.6.1 by adding the ppa source, and the problem can still be reproduced

**Comment by Cat7373** [comment]
@dannyneira fish 3.6.1 reproduce video:
http://172.96.194.76:81/iShot_2023-07-25_09.43.50.mp4

**Comment by dannyneira** [comment]
We'll be tracking this issue over at #3214  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
