### ISSUE TITLE
SSHing raises many "channel n: open failed: connect failed: open failed" errors

### ISSUE THREAD

**Issue by vivaansinghvi07** [warpdotdev/Warp#3398]
### Operating System

MacOS

### Operating System and Version

Ventura 13.4.1

### Local Shell Version

5.9

### Remote Shell Version

4.4.19

### Warp Version

v0.2023.07.18.08.03.stable_00

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

While I type there is a continuous stream of errors saying "channel `n`: open failed: connect failed: open failed", which `n` is some number (varying in a range of about 2-9). I can still use the remote connection though, the errors are just really constantly there.

### Include shell xtrace output

I cannot find the output.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
hey @vivaansinghvi07 Sorry to hear about this issue.

We're tracking this issue over at #1957 where we have posted a [possible workaround](https://github.com/warpdotdev/Warp/issues/1957#issuecomment-1599759475).

Would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by yassineS** [comment]
this is ongoing and very annoying

**Comment by DanyPell** [comment]
Yep very annoying

channel 17: open failed: connect failed: open failed
channel 18: open failed: connect failed: open failed
channel 17: open failed: connect failed: open failed
channel 18: open failed: connect failed: open failed
channel 17: open failed: connect failed: open failed
channel 20: open failed: connect failed: open failed
channel 14: open failed: connect failed: open failed
channel 18: open failed: connect failed: open failed

**Comment by Darragh-McCarthy** [comment]
Try adding the following to your ~/.ssh/config
  ControlMaster auto
  ControlPath ~/.ssh/control:%h:%p:%r
  ControlPersist 4h
  ServerAliveInterval 60

**Comment by ecsplendid** [comment]
please fix
<img width="569" alt="image" src="https://github.com/user-attachments/assets/ed2a7afd-f0db-4387-bc11-c158b62d02f0">

**Comment by luisdalmolin** [comment]
I have this all the time, especially inside AWS servers

**Comment by willros** [comment]
Same problem here.

**Comment by yassineS** [comment]
They don’t care about this. I went back to term and I’m very happy.

**Comment by diegobaronm** [comment]
Same here

**Comment by danvau7** [comment]
Literally just came here to check this. It is making it very difficult to screenshare when the terminal jumps 40 lines to print out these not necessary channel messages. Sad :(

Will update if I can find an answer. Really enjoy Warp all other things considered.

**Comment by wastez** [comment]
The problem appears if there are much files in a folder and i want to tap in warpify mode.

**Comment by alokedesai** [comment]
Hi all -- we've been working hard on a fix for the ssh issues and have a new approach that we'd love your feedback on.

If you're up for giving it a shot, here's how you can try it out:

**To enable the new ssh experience:**
On macOS, run `defaults write dev.warp.Warp-Stable SshTmuxWrapperOverride true`.
On Linux, add the `"SshTmuxWrapperOverride": "true"` key-value pair to `~/.config/warp-terminal/user_preferences.json`.
Quit and re-open Warp.

**Comment by zhiyanliu** [comment]
The macOS one works for me. Thanks! @alokedesai

**Comment by LordMyschkin** [comment]
did not work for me

**Comment by AxoyTO** [comment]
did not work for me on Linux

**Comment by dwidman** [comment]
did not work for me on macOS Sequoia

**Comment by enfinders** [comment]
> Hi all -- we've been working hard on a fix for the ssh issues and have a new approach that we'd love your feedback on.
> 
> If you're up for giving it a shot, here's how you can try it out:
> 
> **To enable the new ssh experience:** On macOS, run `defaults write dev.warp.Warp-Stable SshTmuxWrapperOverride true`. On Linux, add the `"SshTmuxWrapperOverride": "true"` key-value pair to `~/.config/warp-terminal/user_preferences.json`. Quit and re-open Warp.

Hi, this did not work for me.  Running version v0.2025.07.16.08.12.stable_04, macOS 26.0. 
I keep getting the very annoying channel open failed message. 

Only fix is running command + ssh etc etc

**Comment by matteohoeren** [comment]
Same issue here on macOS, the `command` fix works, however the other suggest one (`SshTmuxWrapperOverride`) does not work. Disappointing :/

**Comment by aetherwu** [comment]
> command

Interesting, it fix the error but obviously left the core Warp Agent Feature  behind.

**Comment by somethino** [comment]
The problem persists. Will there ever be a solution?

**Comment by iamwangyabin** [comment]
The problem persists.

**Comment by xis19** [comment]
I can confirm that it persists

**Comment by tylercasper** [comment]
Still an issue. Prepending `command` before the ssh command doesn't work, as it bypasses Warp's input processing (everything is simply directed to the underlying shell as a command).

In my case, the only channel I see in the error message is channel 21.

**Comment by qem19** [comment]
Any updates? Issue is still actual

**Comment by alokedesai** [comment]
Hi everyone, 
Thanks for your patience here, I recognize that SSH instability is _extremely_ frustrating. 

To keep everyone in the loop: we are actively working on a new SSH approach that should resolve the `open failed` messages. I don't have an ETA for launch yet, but I'll ping in this issue as soon as we have something folks can test.

Thanks!

**Comment by StarsTesla** [comment]
Bug Still Remains。。。。。。。。。

**Comment by farris** [comment]
Would be great if this could be fixed. Warp feels unusable on remote ssh due to all the bugs 😢

**Comment by mmendesx** [comment]
Open the hidden comments guys.

This two options worked for me.
- https://github.com/warpdotdev/Warp/issues/3398#issuecomment-2564952702
- https://github.com/warpdotdev/Warp/issues/3398#issuecomment-2501828364

Enabling TMUX on settings also is required to ensure the reliable.

**Comment by twboc** [comment]
@mmendesx It's all fun and games :D but I pay for this software to work. Not having a SSH and doing some workarounds is something I can do with other terminals that I don't pay for!

**Comment by lekhnath** [comment]
channel 21: open failed: connect failed: open failed
channel 23: open failed: connect failed: open failed
channel 25: open failed: connect failed: open failed

I dont know what these are

**Comment by vmallela0** [comment]
Longest GitHub issue in history quite possibly

**Comment by mmendesx** [comment]
> [@mmendesx](https://github.com/mmendesx) It's all fun and games :D but I pay for this software to work. Not having a SSH and doing some workarounds is something I can do with other terminals that I don't pay for!

Well, the terminal is a free feature. Only the agent mode is paid, so... I agree with u in terms. If there's a workaround people use, this must have been fixed already.

**Comment by nguyenvulong** [comment]
> > [@mmendesx](https://github.com/mmendesx) It's all fun and games :D but I pay for this software to work. Not having a SSH and doing some workarounds is something I can do with other terminals that I don't pay for!
> 
> Well, the terminal is a free feature. Only the agent mode is paid, so... I agree with u in terms. If there's a workaround people use, this must have been fixed already.

imho, he paid for a product itself, not just the agent ^_^

---
warp is opensource now https://github.com/warpdotdev/warp
not sure if the workaround can turn into a PR!

**Comment by piyush-kumar-eightfold** [comment]
I finally got a solution to work, Whatever Alias you are putting to connect to ssh or directly writing cli command to connect, append this 2> >(grep -v "channel [0-9]*: open failed" >&2) This would silent all those incoming messages and the terminal would be cleaner.

**Comment by twboc** [comment]
@piyush-kumar-eightfold dude...! I want my ssh to work not to hide it under the rug. We pay for this thing.

**Comment by piyush-kumar-eightfold** [comment]
> [@piyush-kumar-eightfold](https://github.com/piyush-kumar-eightfold) dude...! I want my ssh to work not to hide it under the rug. We pay for this thing.

I am using eternal terminal to connect to my ssh, with addition of that I was receiving those messages which was very annoying as my terminal got flooded. You can try that, my ssh connection does not drop.

**Comment by twboc** [comment]
Why would I use a different terminal if I am paying for this one?! Dude... have some self respect.

**Comment by piyush-kumar-eightfold** [comment]
> Why would I use a different terminal if I am paying for this one?! Dude... have some self respect.

That is not a different terminal, its just the name
https://eternalterminal.dev/

Eternal Terminal (ET) is a remote shell that automatically reconnects without interrupting the session. 
you can install it in your ssh machine and use warp to connect to your ssh.

**Comment by twboc** [comment]
ok. I'm done talking to you...

**Comment by kevinyang372** [comment]
Hey y'all. We just shipped a new iteration of our SSH extension that should resolve these issues + provide additional native support for a bunch of Warp's coding features like code review. Please update to the latest client version and try it out!

One thing to note is you would need to disable TMUX warpification in Settings > Warpify > SSH > Use Tmux Warpification to use this new extension

**Comment by twboc** [comment]
It seems to be working better now. Just being able to log in with ssh into a server without switching terminals is all I needed. I don't even care about the ssh extension. I haven't tried it! Thank you guys!
