### ISSUE TITLE
Executables from C++programs are bugging

### ISSUE THREAD

**Issue by Kratosix** [warpdotdev/Warp#3400]
### Discord username (optional)

biitt

### Describe the bug

I made a simple C++ project that just displays a macro and when I run my executable I get an extra percentage. I don't even know how it ended up there and my warp settings are set to default.
and my output is something like ``90%``

### To reproduce

My code
```
#include <iostream>
#define SELECT select()

int select(){
    return 90;
}
int main(){
    std::cout<<SELECT;
    return 0;
}
```

### Expected behavior

I expect it to give me an output without a ``%``

### Screenshots

![Screen Shot 2023-07-21 at 4 52 56 PM](https://github.com/warpdotdev/Warp/assets/120779609/277e1832-a804-49cf-8c1c-5582525f02dd)

### Operating system

MacOS

### Operating system and version

MacOS catalina 10.15.2

### Shell Version

zsh 5.7.1

### Current Warp version

v0.2023.07.18.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

**Comment by dannyneira** [comment]
Hi @Kratosix Thanks for letting us know. after some testing, I am seeing the same result in other terminals. My guess is that there is something in the code producing the percent sign output.

Let me know if you're seeing otherwise and provide detailed steps to reproduce the issue on Warp as well as the desired result in other terminals (without the percent sign).

![CleanShot 2023-07-24 at 16 24 55](https://github.com/warpdotdev/Warp/assets/16809145/0aa2a257-a4c0-40f8-a410-eab4c6fa7ae4)

**Comment by Kratosix** [comment]
Ok so I even tested out with a different approach by creating a simple Macro in c++ and I saved and compiled my code.
```
#include <iostream>
#define PI 3.14

int main(){
   std::cout<<PI;
   return 0;

}
```
It compiled successfully, and when ran in warp I still get the extra `%` and in mac's terminal, there's no extra `%`
![Screen Shot 2023-07-25 at 1 20 26 AM](https://github.com/warpdotdev/Warp/assets/120779609/ddde4a11-ce94-4acc-b549-7301f73fb82b)
![Screen Shot 2023-07-25 at 1 20 40 AM](https://github.com/warpdotdev/Warp/assets/120779609/923897f9-412c-4973-a619-c94d750ca7bb)
