### ISSUE TITLE
Unable to Open app

### ISSUE THREAD

**Issue by Yrahate7** [warpdotdev/Warp#3401]
### Describe the bug

Downgraded from Mac os 14 beta to 13,  Unable to open the app again.

Logs:-

2:34:04 [INFO] Spawning terminal server process...
22:34:04 [INFO] Running terminal server...
22:34:04 [INFO] application will finish launching
22:34:04 [INFO] Removing old executable dir...
22:34:04 [INFO] Removing old executable file...
22:34:04 [INFO] Failed to read User from secure storage The specified item could not be found in the keychain.
22:34:04 [INFO] Initializing crash reporting Some("stable_release") with tag "v0.2023.07.18.08.03.stable_00"...
22:34:04 [INFO] Initializing Sentry for cocoa app with endpoint https://0195a81da0714f55a93ee4624825f9ec@o540343.ingest.sentry.io/5658526

### To reproduce

Opened the app from terminal.
Also tried opening the app from launchpad.

### Expected behavior

App to launch

### Operating system

MacOS

### Operating system and version

13.4.1

### Current Warp version

0.1.0 (20230718.082512)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @Yrahate7 Sorry to hear about this blocker. Can you please try some of the following and let us know if it helps?
1. [Uninstall Warp](https://docs.warp.dev/help/uninstalling-warp), then [Reinstall Warp](https://docs.warp.dev/getting-started/getting-started-with-warp#installing-warp).
2. If the above doesn't work, then remove Warp settings with `defaults delete dev.warp.Warp-Stable` and see if that helps.

**Comment by Yrahate7** [comment]
Still same

**Comment by Yrahate7** [comment]
@dannyneira Still nothing?

**Comment by dannyneira** [comment]
Please confirm if your machine supports Metal API https://support.apple.com/en-us/HT205073

Your macOS version seems to be fine (at least 10.14). 

You can also try running Warp with an empty .zshrc file and see if that helps aswell. I'll let the team know about your issue and see if there other steps we can take to resolve.

**Comment by dannyneira** [comment]
@Yrahate7 any luck with the above?

**Comment by Yrahate7** [comment]
> 

i'll try with empty .zshrc file today, because the other steps ive performed.
Lets see how that goes

**Comment by Yrahate7** [comment]
Still the same @dannyneira

**Comment by dannyneira** [comment]
Thanks for letting us know. Sorry about the issue. And just to confirm, you also deleted all the database/settings/login/etc.? https://docs.warp.dev/help/uninstalling-warp#removing-warp-login-settings-files-log-and-database

**Comment by Yrahate7** [comment]
> Thanks for letting us know. I'll check with our team to see if there is anything else you can try to resolve. And just to confirm, you also deleted all the database/settings/login/etc.? https://docs.warp.dev/help/uninstalling-warp#removing-warp-login-settings-files-log-and-database

Yes

**Comment by geoguide** [comment]
Also unable to open app on one computer, it's fine on my other. I fully uninstalled and then reinstalled via dmg

**Comment by Yrahate7** [comment]
@dannyneira For some reason, When i reinstalled via dmg, It started opening again.

**Comment by dannyneira** [comment]
Awesome! Thanks for letting us know
