### ISSUE TITLE
After installing oh my zsh, there was an issue with the Chinese display

### ISSUE THREAD

**Issue by wisinfun** [warpdotdev/Warp#3404]
### Describe the bug

<img width="924" alt="image" src="https://github.com/warpdotdev/Warp/assets/41355260/44be5c6c-7059-443d-9913-a3cdbb7d21ec">
After installing oh-my-zsh, there was an issue with the Chinese display。(The last character in Chinese)

<img width="865" alt="image" src="https://github.com/warpdotdev/Warp/assets/41355260/5bd36546-1835-430b-864d-d3b21582c6b0">
Display normal in Terminal.app

### To reproduce

After installing oh-my-zsh

### Operating system

MacOS

### Operating system and version

13.4.1

### Current Warp version

v0.2023.07.18.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @wisinfun If you can please provide the sample characters you use it would help us with reproduction.

**Comment by wisinfun** [comment]
@dannyneira 
For example(Folder name)：测试素材
