### ISSUE TITLE
would rather not have to login. 

### ISSUE THREAD

**Issue by robinkaty** [warpdotdev/Warp#3405]
### Describe the solution you'd like?

```Text
No web login before using, I will probably eventually stop playing with warp because of this. Also, would like to be able to open it with a shortcut like with vscode = code, or sublime = subl.
```

### Is your feature request related to a problem? Please describe.

```Text
No, just function.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @robinkaty

At this time, Warp continues to require login.  The primary reason is that login allows us to build cloud-oriented features that make the terminal have a concept of “your stuff” and “your team’s stuff” – for example Block Sharing.

We do understand the desire to try Warp before logging in and are exploring product experiences that could allow you to use Warp before signup. We'll reach back out if you're interested if / when we make any product changes around log-in. You can also track this request for no login here: #900

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

We'll be closing this as a duplicate.

**Comment by robinkaty** [comment]
I am good, I don't like it but I created an account. I just don't think many of the developers that I know will do so.


---------------------
Rob Granger
***@***.***
281.507.2407
Don’t cling to a mistake just because you spent a lot of time making it.

On Jul 24, 2023, at 6:14 PM, Danny Neira ***@***.***> wrote:



Thanks for submitting this @robinkaty<https://github.com/robinkaty>

At this time, Warp continues to require login. The primary reason is that login allows us to build cloud-oriented features that make the terminal have a concept of “your stuff” and “your team’s stuff” – for example Block Sharing.

We do understand the desire to try Warp before logging in and are exploring product experiences that could allow you to use Warp before signup. We'll reach back out if you're interested if / when we make any product changes around log-in. You can also track this request for no login here: #900<https://github.com/warpdotdev/Warp/issues/900>

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

We'll be closing this as a duplicate.
