### ISSUE TITLE
how to set unlimit scrollback like iterm2

### ISSUE THREAD

**Issue by DobeReverser** [warpdotdev/Warp#3406]
### Describe the solution you'd like?

```Text
want a feture that can set unlimit scrollback like iterm2.
need to report very big output on screen.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @DobeReverser

We have a request tracking this over at #610. TL;DR there was some work being done on this feature request, but there was a performance blocker preventing the release.

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

We'll be closing this as a duplicate.
