### ISSUE TITLE
Warp AI shortcut interferes with default macOS shortcut for input language switching 

### ISSUE THREAD

**Issue by JonathanX64** [warpdotdev/Warp#3410]
### Describe the bug

So by default, Warp AI is assigned to Control + Space.

Also by default, if macOS user lives in a non-English-speaking country, they have to use Cmd+Space for Spotlight and Control+Space for input language switching. 

Nowadays, Apple tries to make us use fn key instead of Ctrl+Space, but 
1. It has much higher latency for some reason
2. It only works (by default) on M1 Macs and newer
3. Ctrl+Space is still assigned to language switching

So Control+Space is taken, and because of that, Warp does not even receive this keystroke, unless user happens to only have single language on their computer.

Please come up with a different shortcut. Thanks!

### To reproduce

Just open new window of Warp and the shortcut for Warp AI is displayed there

### Expected behavior

Maybe Option+Space? But that's frequently taken over by third-party Spotlight alternatives such as Raycast.

Maybe Cmd+I, as in Intelligence?

### Operating system

MacOS

### Operating system and version

13.4.1

### Current Warp version

v0.2023.07.18.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @JonathanX64 Thanks for letting us know. In general, Warps default shortcuts are set based on US input so this may affect other countries. As a workaround, you can go to Settings > Keyboard Shortcuts, and then look for "toggle warp ai" and clear it or set the keyboard shortcut to one that doesn't conflict with your other shortcuts. I hope this helps!

![CleanShot 2023-07-25 at 11 35 06](https://github.com/warpdotdev/Warp/assets/16809145/7618540f-fbc3-4a55-8503-599fe67ea0fc)

Closing as this isn't a bug per se, and can be solved with existing settings.

**Comment by JonathanX64** [comment]
Well, this issue is definitely not a bug, but more of a UX suggestion.

It doesn't make sense to force 90% of users to go into settings and change shortcuts when you could've simply come up with a better default option.

Please consider it. Thanks!
