### ISSUE TITLE
kubectl autocomplete

### ISSUE THREAD

**Issue by ashertz-dev** [warpdotdev/Warp#3412]
### Discord username (optional)

ashertz

### Describe the solution you'd like?

```Text
I hope that kubectl will autocomplete Pods name when I use command `kubectl logs -f --tail ` (press `Tab` now).
```

### Is your feature request related to a problem? Please describe.

```Text
After pressed `Tab`, will sent a http request to get all pod name (I guess)
```

### Additional context

<img width="742" alt="image" src="https://github.com/warpdotdev/Warp/assets/43273996/2e554faf-b401-4e3f-be5c-223ba6208ea2">
<img width="832" alt="image" src="https://github.com/warpdotdev/Warp/assets/43273996/ac8a3741-17d9-4fdc-9f7a-48dda729cc08">

* There are two pictures, and each of the above is **Warp**, and the below is **iTerm**.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @ashertz-de. We already have a request tracking this over at #2055

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
