### ISSUE TITLE
Show timestamps somewhere

### ISSUE THREAD

**Issue by nateridderman** [warpdotdev/Warp#3414]
### Describe the solution you'd like?

```Text
I would love a way to see when a command was executed. It could be in the three vertical dots menu.
```

### Is your feature request related to a problem? Please describe.

```Text
I run git from Warp and I sometimes forget when was the last time I pushed, pulled, etc.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @nateridderman Thanks for submitting this. As a possible stopgap, Warp's default prompt currently shows the run date/time on hover, or you can use a [supported custom prompt](https://docs.warp.dev/features/prompt) to render a timestamp (in my example I'm using starship.rs but many others support it).

https://github.com/warpdotdev/Warp/assets/16809145/c57269c8-c1bc-431d-89d8-efc78a7b836d

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by nateridderman** [comment]
Thank you! I had tried hovering but didn't realize you had to hover specifically over the duration text. This works for me but the discoverability of this feature is low IMHO

**Comment by dannyneira** [comment]
Appreciate the feedback @nateridderman I'll let the team know if we can make this a bit more obvious. Closing as the current feature meets your use case. Thanks again!
