### ISSUE TITLE
Unable to launch the application window, when the input method is not English

### ISSUE THREAD

**Issue by kunlongxu** [warpdotdev/Warp#3415]
### Describe the bug

The global shortcut for the indicated hotkey window is not working when the method is not English.

### To reproduce

1. Switch your input method to non-English.
2. Press the shortcut of the hotkey window.

### Expected behavior

The hotkey window can appear regardless of any input method.

### Operating system

MacOS

### Operating system and version

13.2.1

### Current Warp version

v0.2023.07.18.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @kunlongxu

As a possible workaround, try and switch the input to ABC ( US ) keyboard or rebind the keyboard shortcuts while you're input is international and try again.

Longer term we're aware of the issue and it's on the backlog of things we can improve in the future so we appreciate your patience with this issue and it's complicated to fix.

We're tracking this issue over at #341 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
