### ISSUE TITLE
Suggest a command burned through 100 request limit while just entering the prompt! No session preservation!

### ISSUE THREAD

**Issue by kolakode** [warpdotdev/Warp#3419]
### Describe the bug

Warp feature of having AI suggest a command burns through requested within a minute or two. There is also no preservation of the previous Ask Warp AI session when Warp starts.

I saw under the release notes that I had yet to try to have Warp use AI to suggest a command. So I tried entering a rather long prompt to see what it would come up with, but before I could finish it reported above the prompt "It seems you're out of requests. Please try again after". There was nothing after the word "after".

I noticed a small popup next to the command prompt with the latest suggestion as I typed. Generating and updating that is likely what caused it to burn through an entire day of requests in a minute or two. There is no way to have Warp wait until I pressed enter before making the AI request.

As soon as I got the message about being out of requests, I opened Ask Warp AI via <Ctrl-Space> and immediately saw I had used 100 of 100 requests, even though I had yet to actually submit a single request today. I also noticed my prompts and responses (my AI session) from yesterday was not preserved, which is a real bummer.

### To reproduce

1. Start Warp
2. Open the suggest a command feature (the mini Ask Warp AI) using <Ctrl-`> and start typing out the description of a compound command you want Warp to formulate. Make is complex enough that you need to periodically pause for thought or edit your description. Within a minute or two, note the text about the prompt will change indicating you are out of requests even though you have yet to press enter to make a request.
3. Confirm you have no requests left by pressing <Ctrl-Space> to open the main Ask Warp AI side panel. Notice the counter indicates 100/100 and you have no more available requests. Also note that any AI chat session you may have had the last time you used Warp is now gone.

### Expected behavior

I don't expect Warp to make AI requests automatically. There needs to be a convention for making the requests. Pressing the <tab> key to make a request would allow one to perform an edit/request/edit cycle, and pressing <enter> to accept the response could be used to indicate the current response should be copied to the command line where it could be edited further or executed by pressing <enter> again.

### Operating system

MacOS

### Operating system and version

13.4.1

### Current Warp version

v0.2023.07.18.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by szgupta** [comment]
Hi @kolakode, sorry for the inconvenience here! The new AI Command Suggestions experience is meant to streamline the steps to turn natural language into a shell command by removing the explicit action to generate the command, and instead generate commands as you type. In terms of burning through requests, we'll investigate if there are ways we can alleviate that. I'll update this issue as we make progress on this.

**Comment by dannyneira** [comment]
To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by szgupta** [comment]
@kolakode I have a fix for this that should hopefully be out by next Tuesday (08.01.23)!

**Comment by dannyneira** [comment]
Hey folks, closing as resolved since the fix has been released in recent version of Warp.
