### ISSUE TITLE
Issue with rendering Powerlevel10k prompt colors/shapes

### ISSUE THREAD

**Issue by bmongemendez** [warpdotdev/Warp#3428]
### Discord username (optional)

bmongemendez

### Describe the bug

When I try to configure Powerlevel10k on my ZSH terminal using the Rainbow Unicode style, the different shapes and colors for the prompt does not look consistent, even after trying with different themes, as you can see below in the screenshots attached.

### To reproduce

Install Powerlevel10k and configure different prompt styles, you will see issues with different prompt colors/shapes rendering on most of them.

### Expected behavior

Powerlevel10k prompt colors/shapes should look consistent, and no differences in color of the Unicode shapes should be visible in order to see the intended complete shapes.

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/70995308/67f9f41e-1169-4d3c-8778-380a051f2a91)

![image](https://github.com/warpdotdev/Warp/assets/70995308/995527ca-6af9-4d23-9466-15433e00c21f)

### Operating system

MacOS

### Operating system and version

13.5.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.07.18.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by JennieSH** [comment]
Go to `Appearance` -> `Enforce minimum contrast` and change it to `Never`. After adjusting it, the color display will become consistent.

It was mentioned in [#2851 comment](https://github.com/warpdotdev/Warp/issues/2851#issuecomment-1605005256).

<img width="658" alt="image" src="https://github.com/warpdotdev/Warp/assets/56363009/047057ba-f44e-4301-b701-dde62e5d10b7">

**Comment by bmongemendez** [comment]
Thank you so much @JennieSH, it has fixed my issue indeed!   🎉😄
