### ISSUE TITLE
Warp UnderHood

### ISSUE THREAD

**Issue by duksh** [warpdotdev/Warp#3432]
### Describe the solution you'd like?

```Text
I want to have a built-in visual block in Warp via which I can see the data that WARP is sending and receiving over the internet. I don't want to launch another terminal to snoop on WARP's background/internal connections.
```

### Is your feature request related to a problem? Please describe.

```Text
I want to be able to use Warp at the office but not considered safe as per internal security policies
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @duksh Thanks for the request. As a stopgap, Warp has a network log that you can use to see what's being sent. https://docs.warp.dev/features/network-log. Also please look at our privacy docs for more info on telemetry and options to disable it. https://docs.warp.dev/getting-started/privacy

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by TheX-fr** [comment]
In addition to the above, we need real offline version. When accepting only crash reports in privacy it still continuously send content (telemetry only?) to Google servers which is not acceptable.
We don't care about the connected drive, etc. Except AI request per user decision, and crash reports to help debugging, all other network activity/tracking is not acceptable.

**Comment by michlimlim** [comment]
Hey @duksh Michelle from Warp here. I'm working on a project to unblock Warp at work and would love to discuss how we can build Warp to comply with internal security policies. Would you be down to email feedback@warp.dev so we can discuss further? Thank you so much!

**Comment by dannyneira** [comment]
Closing as resolved since the Network log helps users see what Warp is sending "under the hood" and since the users are in communication with PM about warp at work blockers.
