### ISSUE TITLE
Custom ordering of workflows

### ISSUE THREAD

**Issue by tomaley** [warpdotdev/Warp#3433]
### Describe the solution you'd like?

```Text
I love the workflows feature but the thing that would take it to the next level for me would be the ability to order workflows within a folder and not have one move if it is updated last.

I get used to where in a list a particular workflow is and if it requires tweaking later it's annoying to have it jump to the top and not be where I expect it to live.

An aside: it may be nice to have some additional grouping mechanism to compliment the folders I.e  if a folder is API, colour coding the text of all GET requests to one colour and all POST requests to another etc. 

Again, workflows are great, this would make them awesome for me.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by uicrafts** [comment]
Came here looking for the same. I have a list of workflows that is growing, and I have established a naming convention for different workflows (names start with "Deploy", "Run", etc). I would like to drag/drop to keep all "Deploy" ones together, or right click to sort by name. Having some mechanism to keep workflows in a particular visual order would be pretty handy.
