### ISSUE TITLE
No Help on "workflow"

### ISSUE THREAD

**Issue by cfry** [warpdotdev/Warp#3440]
### Describe the solution you'd like?

```Text
On the Help menu, I type in "workflow"
and I see a menu of options, nearly all of them irrelevant,
but the top one is "workflow",
Good, so I put my mouse on the "workflow" menu item and the VIEW menu pops down with
all the items grayed out.
Useless.
I want to find out what a workflow IS. Not actually make one.
In a normal app, this is called "Help", but you redefine "Help"
for a different purpose which, um, didn't help.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by cfry** [comment]
In  https://docs.warp.dev/features/warp-drive/workflows
I quote:
"From the Command Palette, Create a New Personal Workflow"
Err, where's the "Command Palette"?
Eventually I found it, Change your doc to:
From Warp's menu bar, View menu, choose "Command Palette"
then choose: "Create a New Personal Workflow"
OK I made a new workflow, clicked save,
everything SEEMED ok but the View menu/Workflows item was still grayed out
so how do I see what workflows I've defined and invoke them?

My suggestion:
The View menu "Workflows" item is never grayed out.
Choosing it you get a dialog box who's first item is a button titled:
"New Workflow"
and below that is a list titled "Existing Workflows"
under which is the names of existing workflows
that you can click on to edit.
Also in the dialog box should be  "?" which takes you to Workflow
documentation.

I'd like to see more examples in the doc on creating workflows,
esp ones made up of multiple cmds.

I admit I don't understand workflows, but you don't understand
how to help users understand them, which I'm trying to help you with.

**Comment by dannyneira** [comment]
Thanks for the feedback, I've added a shortcut for the command palette to the workflow docs and will pass these comments along to the team. Closing as resolved.
