### ISSUE TITLE
reopen a closed tab, using cmd shift f

### ISSUE THREAD

**Issue by aghanima4** [warpdotdev/Warp#3445]
### Discord username (optional)

aghanima4

### Describe the solution you'd like?

```Text
reopen a closed tab, using cmd shift f
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
You must be a mind reader because we've been working on exactly this! No ETA on launch, but we'll be posting any updates on this thread when released.
