### ISSUE TITLE
Issues w/ SSH command printing

### ISSUE THREAD

**Issue by StupeFied** [warpdotdev/Warp#3449]
### Discord username (optional)

stupefied_

### Describe the bug

Well, I'm not really sure how to describe it. There is partial highlighted text of the command before the actual, full command. See image.
<img width="1292" alt="image" src="https://github.com/warpdotdev/Warp/assets/89881655/2bb0bb97-126c-48e6-b067-942996bf6790">

### To reproduce

Just use SSH normally. 

### Screenshots

<img width="1292" alt="image" src="https://github.com/warpdotdev/Warp/assets/89881655/2f24528a-e8e9-473d-874b-d54e22a2f046">

### Operating system

MacOS

### Operating system and version

13.4.1 (c) (22F770820d)

### Shell Version

bash version 5.2.15(1)-release

### Current Warp version

v0.2023.07.25.08.03.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Maybe 2 versions ago?

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by yumion** [comment]
same

**Comment by yumion** [comment]
It was solved at `v0.2023.08.22.08.03.stable_00` version

**Comment by dannyneira** [comment]
@StupeFied Closing as this has been resolved in recent build of Warp. Please feel free to let us know if the issue persists.
