### ISSUE TITLE
Global hotkey is not active sometimes. When I restart warp several time, it becomes active again.

### ISSUE THREAD

**Issue by wangmir** [warpdotdev/Warp#3450]
### Describe the bug

When I restart warp (mainly when I update warp), or entire mac, sometimes, the warp hotkey is not working.
My hotkey setting is `cmd` + `shift` + `t`.

When it happens, if i restart warp several times, then it becomes fine, and after that, even when I restart warp, it is fine again.

### To reproduce

Upgrade warp from previous version. Execute warp, and open hot key window.

### Operating system

MacOS

### Operating system and version

ventura 13.4.1

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by wangmir** [comment]
@warpdotdev-dx it seems current version has no problem. I updated to new version, and I couldn't see any problem on this. So, I'll close it.

**Comment by AXSJ** [comment]
happens to me constantly it's quite infuriating after my mac has been asleep open lid try the hotkey doesn't work my shortcut is option + w
