### ISSUE TITLE
Keep session on new windows

### ISSUE THREAD

**Issue by assafmanzur** [warpdotdev/Warp#3451]
### Describe the solution you'd like?

```Text
When opening a new window it will be nice to keep the session endv and other setting on the new opened tab
for example AWS_PROFILE will need to be set again on the new window.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by elviskahoro** [comment]
@assafmanzur We have a long-term solution in mind for this, but it won't be for a while. We're going to close this out
