### ISSUE TITLE
Please add support of `Unicode Normalization Form`.

### ISSUE THREAD

**Issue by Alanimdeo** [warpdotdev/Warp#3452]
### Discord username (optional)

alanimdeo

### Describe the bug

Hi there,

I hope you are doing well. I recently tried using the Warp app, and I find it quite appealing. However, I encountered a problem with Korean characters not being displayed properly due to the lack of support for Unicode normalization.

I understand that there was a related issue (#769), and I apologize that I'm creating a duplicate. I reopened it because I hadn't seen any updates on this issue.

The implementation of Unicode Normalization Form is crucial for many Korean users, myself included, to properly use this wonderful product. I'm really looking forward to a quick solution so that we can make the most out of the app.

Thank you for your attention to this matter. Your efforts in resolving this issue would be greatly appreciated.

### To reproduce

Display Hangul strings using Unicode Normalization Form D (NFD) in the terminal

### Expected behavior

Displays properly

### Screenshots

<img width="83" alt="image" src="https://github.com/warpdotdev/Warp/assets/32806763/529a2e24-34ca-4df8-bb45-0cf1431586b9">

### Operating system

MacOS

### Operating system and version

macOS 14 Sonoma Beta

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2023.07.25.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

Strings normalized with NFD are not displayed properly, so every Korean characters should be normalized with NFC.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by rakcomputing** [comment]
khmer unicode is not support it show : ?????????????

**Comment by rakcomputing** [comment]
<img width="373" alt="Image" src="https://github.com/user-attachments/assets/822a1175-3364-4b63-8b27-d31dbd791eae" />

please help to fix in warp for khmer unicode query from from mysql db

**Comment by Alanimdeo** [comment]
> khmer unicode is not support it show : ?????????????

I think this is font problem and is not related to this issue. Try changing font.
