### ISSUE TITLE
Using makefile to SSH does not ask to Warpifying subshell

### ISSUE THREAD

**Issue by hareland** [warpdotdev/Warp#3454]
### Discord username (optional)

drtydishes

### Describe the bug

When using makefile to SSH into i.e a docker container it does not give the option to "Warpify" the subshell.
Here I've used `docker exec` in the makefile.

### To reproduce

Create a makefile which has a bash or ssh command, then run it `make ssh` e.g

### Expected behavior

To ask if i want to warpify the shell.

### Operating system

MacOS

### Operating system and version

MacOS 13.5 (22G74) [M1 Pro]

### Shell Version

Docker: GNU bash, version 5.1.16(1)-release ///// Host: GNU bash, version 3.2.57(1)-release

### Current Warp version

v0.2023.07.25.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by hareland** [comment]
> Hey @hareland, adding `make ssh` (or whatever the specific command is) to your list of subshell commands per the docs [here](https://docs.warp.dev/features/subshells#adding-compatible-commands) might solve your issue

Hi @zachbai, thanks for the suggestion.

While this is true, the command that actually is called from my make file is docker exec - that's why I'm thinking it should work with make files; because it simply calls other commands.

Let me know if you think the configurable workaround for such a widely used tool should be sufficient.

IMO this should work somehow.

**Comment by zachbai** [comment]
Unfortunately the mechanism for detecting a spawned subshell isn't that sophisticated -- it's basically doing a regex match on the contents of the Warp terminal input to determine the command that's being run. Warp isn't aware which commands are being run under the hood when running `make`. (I don't think the shell itself is actually aware either, the `make` binary` is what's reading that file and exec'ing those commands).

Theoretically we could add some basic `Makefile` detection and scan its contents but I haven't thought through all the corner cases. It would basically amount to checking if an arbitrary shell script results in an interactive subshell.

For the sake of transparency, I think we're unlikely to implement this in the near term but its something we can consider for the next set of improvements to the subshell feature.
