### ISSUE TITLE
Privacy Policy page does not display any content

### ISSUE THREAD

**Issue by nickpascucci** [warpdotdev/Warp#3455]
### Describe the bug

The Warp privacy policy page at https://www.warp.dev/privacy/policy does not display any content, presenting only a blank page.

Tested in Safari and Chrome for Mac. Inspecting the page source, it appears that the page has no content to load; it successfully sources scripts for analytics but nothing else.

### To reproduce

Navigate to https://www.warp.dev/privacy/policy in a web browser. Inspect the network traffic and Javascript console using the browser developer tools, and note that there are no JS errors or failed requests.

### Expected behavior

The privacy policy should be displayed.

### Operating system

MacOS

### Operating system and version

MacOS Ventura

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by hongyi-chen** [comment]
Hey @nickpascucci, thanks for reporting this. This should be fixed now!
