### ISSUE TITLE
shell detection

### ISSUE THREAD

**Issue by x-0D** [warpdotdev/Warp#3457]
### Describe the bug

warp don't understand that's "arch -x86_64 zsh" is shell

### To reproduce

run "arch -x86_64 zsh" command in warp.

### Expected behavior

behavior like ssh session. split to blocks.

### Operating system

MacOS

### Operating system and version

Ventura 13.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0) | GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)

### Current Warp version

v0.2023.07.25.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Any luck with the above?

**Comment by x-0D** [comment]
@dannyneira yes, https://docs.warp.dev/features/subshells is helps to configure subshell properly.
