### ISSUE TITLE
multiple prompts displayed in SSH session

### ISSUE THREAD

**Issue by eventualbuddha** [warpdotdev/Warp#3460]
### Describe the bug

Previously, I'd ssh to a VM on my computer and get the standard Warp prompt. After the most recent (I think) update, I now get a double prompt.

### To reproduce

SSH somewhere? Maybe to a Debian 11 machine? Maybe to a machine with a bash starship.rs prompt?

### Expected behavior

I expect to have the standard Warp prompt when ssh'ing. Also, I do have the right settings for PS1 (disabled) and SSH wrapper (enabled), see below.

### Screenshots

https://github.com/warpdotdev/Warp/assets/1938/81c0f10c-daa4-47e7-9cc0-87014c290010

<img width="485" alt="image" src="https://github.com/warpdotdev/Warp/assets/1938/b56835ee-2ff3-4acd-88a6-9084e486aac4">

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

bash 5.1.4(1)-release

### Current Warp version

v0.2023.07.25.08.03.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Mid-to-late July?

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Any luck with the suggestions above @eventualbuddha ?

**Comment by dannyneira** [comment]
Closing as stale, but please feel free to reopen/respond if you can confirm the above.
