### ISSUE TITLE
ssh wrapper is poluting /tmp

### ISSUE THREAD

**Issue by rolandoam** [warpdotdev/Warp#3466]
### Describe the bug

Whenever I log in to my raspberrypi with Warp, the /tmp directory gets poluted with tons of temp files of size 0. I'm using zsh on my macbook and the rpi has bash (it's the octopi image) and if I stay connected for a few minutes, there are hundreds of 0 size temp files. I traced the files as being generated by mktemp and the process calling mktemp was the bash session that I was connected through warp (it was something like `bash --rcfile /dev/fd/63`, so maybe some sort of pipe passing a script to the bash?). I disabled the ssh wrapper and it stopped, so my guess is there's something wrong with the wrapper.

### To reproduce

1. enable the ssh wrapper
2. connect to a ssh host
3. check the /tmp directory

To monitor, I used `auditd` to check who was calling mktemp:

```sh
sudo auditctl -a exit,always -F path=/usr/bin/mktemp -F perm=x -k track_mktemp
sudo ausearch -k track_mktemp
```

Looking at the logs (with `ausearch`) I saw that the process executing that was the bash that was opened when connecting with Warp. Other terminals would not create this issue.

### Expected behavior

You connect to the ssh host and there are no random temp files created

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

remote: GNU bash, version 5.1.4; host: zsh 5.9

### Current Warp version

v0.2023.07.25.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by rolandoam** [comment]
> we may create a temp folder to act as the ZDOTDIR during the bootstrapping process

It's actually not a temp folder in the /tmp directory, it's a bunch of empty files.

**Comment by zachbai** [comment]
Hey @rolandoam, I was able to identify the issue here and a fix will be coming out in a release soon

**Comment by elviskahoro** [comment]
This was fixed!
