### ISSUE TITLE
Reassignable CMD + T (show Create New Tab in shortcut editor)

### ISSUE THREAD

**Issue by jdietrich-tc** [warpdotdev/Warp#3471]
### Describe the solution you'd like?

```Text
"Create New Tab" does not appear in the shortcut editor, and when I try to assign CMD + T to another shortcut, it does not register with the editor, but instead just creates a new tab. Without it in the editor, I can't reassign to CMD + T combo.
```

### Is your feature request related to a problem? Please describe.

```Text
I want to be able to use the CMD + T keybinding to open the command pallet, as that is what I am used to using for similar functionality in Arc.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @jdietrich-tc, Warp now has the ability to bind "New Tab" to another key(s). Closing as resolved, but please feel free to let us know if any related issues with the feature.

![CleanShot 2023-09-12 at 11 03 41](https://github.com/warpdotdev/Warp/assets/16809145/d4b74bf7-7201-4e0b-8309-2f8ba6260d73)
