### ISSUE TITLE
Latest update made me lose my command history

### ISSUE THREAD

**Issue by alexdauenhauer** [warpdotdev/Warp#3476]
### Describe the bug

updated Warp last night and now all my command history is gone. I use fish shell and had a ton of commands that I accessed easily in history and now they are gone

### To reproduce

update warp. try to access commands you used previously. be unsuccessful

### Expected behavior

commands would be retained after update

### Operating system

MacOS

### Operating system and version

13.5.0

### Shell Version

fish, version 3.6.1

### Current Warp version

v0.2023.08.01.08.05.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by acarl005** [comment]
Hi @alexdauenhauer. Yikes! Thanks for reporting this issue! I'm investigating it. May I ask you to look at a couple details for me?

Is your fish history file still there and does it have your history? (This is at file path `~/.local/share/fish/fish_history` by default.

Do you have and env variable `$XDG_DATA_HOME` set?

**Comment by alexdauenhauer** [comment]
ah yes you are correct, the `fish_history` file appears to be intact at that location. I do now have `$XDG_DATA_HOME` set, I had `$XDG_CONFIG_HOME` set

**Comment by acarl005** [comment]
Thanks for the update! We've identified the root cause and we'll address this ASAP!

**Comment by alexdauenhauer** [comment]
thank you! will the fix restore the use of my history since the file still exists?

**Comment by acarl005** [comment]
Yes! Your history should be accessible once again with a patched release.

**Comment by gerardsimons** [comment]
I think I am having the same issue. When I start a new fish inside of warp as a non-warped Shell, it does seem to pick up the history again (see screenshot). Can you confirm that this is the same issue @acarl005 ? Thanks! Been wrecking my head about this all day 😅

<img width="1680" alt="image" src="https://github.com/warpdotdev/Warp/assets/4247845/d8e13806-c970-4c1e-8ac0-3f5b370c33a4">

**Comment by gerardsimons** [comment]
Perfect, thanks!

**Comment by alexdauenhauer** [comment]
it is working for me now. thank you!

**Comment by srudolph-credera** [comment]
> Hey Folks, The latest update released today, `v0.2023.08.01.08.05.stable_03`, fixes the issue with fish history. Please update and confirm if this is resolved for you.

Yes, thank you, the update worked perfectly!

**Comment by gerardsimons** [comment]
The history is working for me now, but partial matching of history is still not working for me, as in type `Desktop` then press up and see `ls Desktop`. Here in the GIF I show what I mean. Note that going into non-Warp shell by typing fish, does work as it should. Maybe this is a different issue though? FYI: Haven't used Warp in a while on Mac ...

![output](https://github.com/warpdotdev/Warp/assets/4247845/2112acbc-25d2-402f-8966-8a82c67e4cd5)
