### ISSUE TITLE
Not going to sign in to use it ever

### ISSUE THREAD

**Issue by macaaw** [warpdotdev/Warp#3477]
### Describe the solution you'd like?

```Text
Please turn off the sign in requirement. What ever feature this enables I'll quite happily live with out.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
test

**Comment by zachlloyd** [comment]
This requirement has been removed.  See https://www.warp.dev/blog/lifting-login-requirement
