### ISSUE TITLE
Unknow autocompletion

### ISSUE THREAD

**Issue by Reoooh** [warpdotdev/Warp#3478]
### Describe the bug

Sorry for the newbie question. But I can't find a similar question in the known issues.

When I use the z (a plugin for omz, and its function like autojump), when I press the space bar the warp always completes automatically. And I do not know the command meaning. When I use the brew command, warp autocompletes a strange command.

How can I fix it?

### To reproduce

enter "z" or "brew" and warp autocompletes a strange command.

### Expected behavior

"zshz 2>&1" or "env PATH="${PATH//$(pyenv root)\/shims:/}" brew" command

### Screenshots

<img width="1136" alt="Screen Shot 2023-08-04 at 23 16 46" src="https://github.com/warpdotdev/Warp/assets/44220955/0de382b4-c28f-46da-a9da-136bcb79079d">
<img width="1136" alt="Screen Shot 2023-08-04 at 23 42 00" src="https://github.com/warpdotdev/Warp/assets/44220955/b1ba0580-b20c-456e-a57f-c13076823976">

### Operating system

MacOS

### Operating system and version

11.8

### Shell Version

zsh 5.9 (arm-apple-darwin20.6.0)

### Current Warp version

v0.2023.08.01.08.05.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Sorry if it wasn't clear, but the known issues docs mentioned Fig, z, and other completion plugins not being supported at this time. https://docs.warp.dev/help/known-issues#list-of-incompatible-tools

I'll bold/highlight those to help make it more visible.
