### ISSUE TITLE
DUP: Duplicate of #209 - Warp does not autocomplete and does not display the non-latin folder names in the path

### ISSUE THREAD

**Issue by VKondakoff** [warpdotdev/warp#348]
### Describe the bug

Warp does not autocomplete and does not display the non-latin folder names in the path

### To Reproduce

cd ~/Documents/Temp
mkdir Russian
mkdir Русский

1.
cd Ru(Tab) -> autocompletes to `Russian/`
cd Ру(Tab) -> does nothing
2.
cd Russian -> the path is displayed as `~/Documents/Temp/Russian`
cd Русский -> the path is displayed as `~/Documents/Temp`

### Screenshots

https://user-images.githubusercontent.com/230824/140038796-86de7cf0-2525-402a-b7d9-c66bfa1d552b.mov

### Operating System

MacOS

### OS Version

12.1

**Comment by VKondakoff** [comment]
This is reproducible in latest stable:
<img width="639" alt="Снимок экрана 2021-11-03 в 23 29 20" src="https://user-images.githubusercontent.com/230824/140188256-3ebb623e-dd04-4d87-a2ea-2f83a65fa4d9.png">

**Comment by kevinyang372** [comment]
Thanks for reporting! I think this is actually a problem in our DCS parsing logic rather than a rendering or IME issue.

**Comment by elviskahoro** [comment]
> Thanks for reporting! I think this is actually a problem in our DCS parsing logic rather than a rendering or IME issue.

@Thanks! @kevinyang372  Updating title.

**Comment by elviskahoro** [comment]
Linking:
- #209
