### ISSUE TITLE
Add ability to toggle collapsing input block on out of focus tabs

### ISSUE THREAD

**Issue by phenixblue** [warpdotdev/Warp#3481]
### Describe the solution you'd like?

```Text
I would like the option to disable the collapsing/shifting of the input block as the cursor is moved between terminals within a single window.
```

### Is your feature request related to a problem? Please describe.

```Text
Currently Warp will "collapse" the input block of an inactive/out of focus terminals within a single window. This shifts the existing blocks a bit, so if you're trying to double-click to copy from an out of focus terminal, the accuracy of the copy is off due to the shifting.
```

### Additional context

You can easily test this by having a single window with 2 terminals side by side and output blocks in each terminal.

Try to double-click to copy text from an inactive terminal within the same window.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for your patience folks! As requested, in Warp version `v0.2023.09.19.08.04.stable_00` and above, the input editor remains visible in inactive panes when using split panes. 

![CleanShot 2023-09-21 at 13 34 04](https://github.com/warpdotdev/Warp/assets/16809145/5b27a944-5add-4296-9166-1e502f70fab7)

Closing as completed, but please let us know if any issues.
