### ISSUE TITLE
sdkman doesn't work in warp

### ISSUE THREAD

**Issue by zjffdu** [warpdotdev/Warp#3486]
### Describe the bug

I'd like to use sdkman to switch different java version, but it doesn't work in warp, while it works in iTerm. 

* In Warp
![image](https://github.com/warpdotdev/Warp/assets/164491/5f1e6cdf-9a95-4f08-96e8-ba479965f72a)

* In iTerm
![image](https://github.com/warpdotdev/Warp/assets/164491/a85b6eab-1f30-4fc8-a734-9b5813115669)

### To reproduce

Step 1. Switch to different version of java
```
sdk use java 11-zulu
```

Step 2. verify java version
```
java -version
```

### Expected behavior

I expect it would switch to java 11, but actually it still use the old java version (java 8 for me)

### Operating system

MacOS

### Operating system and version

Big Sur 11.7

### Current Warp version

v0.2023.07.11.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, it works in iTerm.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @zjffdu I'm not seeing the same issue on my end. I set up SDKman and added the following line to the end of my `~/.zshrc` file `source "$HOME/.sdkman/bin/sdkman-init.sh"`

![CleanShot 2023-08-07 at 10 37 07](https://github.com/warpdotdev/Warp/assets/16809145/cb1d1dcf-47c9-46d7-8b97-97dd11cb3a50)

Can you please make sure you have the line at the end of your RC file? If it is and you're still seeing the issue, make sure you have the latest version of sdkman installed as well. Please let us know if the issue persists.

**Comment by dannyneira** [comment]
@zjffdu Any luck with the above suggestions?

**Comment by dannyneira** [comment]
Closing as stale, but please feel free to reopen if you can confirm the above.
