### ISSUE TITLE
Can't set the tab title

### ISSUE THREAD

**Issue by DenisGorbachev** [warpdotdev/Warp#3487]
### Describe the bug

I can't set the title of the currently open tab.

### To reproduce

1. Run `echo -ne "\033]0;New Title\a"`

### Expected behavior

Expected: the tab title changes to "New Title"

Actual: the tab title stays the same.

### Operating system

MacOS

### Operating system and version

MacOS 13.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.01.08.05.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

**Comment by dannyneira** [comment]
Closing as this is a working feature, but only within the rcfiles.
