### ISSUE TITLE
SSH: Lock up on network lost

### ISSUE THREAD

**Issue by tebrown** [warpdotdev/Warp#349]
### Describe the bug

```shell
I was ssh'ing into a remote machine. Just as it was 'Starting Bash...', I lost network.  All my sessions locked up, including the ones connected to the local machine. I had to force quit the app.
```

### To Reproduce

Steps to reproduce:
1. ssh to remote machine
2. Just as it is trying to start bash, disable wifi or disconnect network
3. Terminals all lock up

### Expected behaviour

```shell
If network goes away while establishing a remote connection, it should simply error out and return back to the local session
```

### Operating System

MacOS

### OS Version

12.0.1

**Comment by elviskahoro** [comment]
@tebrown 
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
