### ISSUE TITLE
changing PS1 adds the new stuff in between `%{ %}` which means nothing shows up

### ISSUE THREAD

**Issue by mxcl** [warpdotdev/Warp#3492]
In Apple Terminal:

```sh
$ echo $PS1
%F{086}%~%{%}
$ export PS1="(pkgx) $PS1
(pkgx) $ echo $PS1
(pkgx) %F{086}%~%{%}
```

In Warp with (show my custom PS1 enabled):

```sh
$ echo $PS1
%{%F{086}%~%{%} %}
$ export PS1="(pkgx) $PS1
$ echo $PS1
%{(pkgx) %{%F{086}%~%{%} %}%}
```

### Expected behavior

Warp is adding `%{` and `%}` around my prompt behind the scenes. Apparently this prevents the custom stuff I want from appearing.

### Operating system

macOS 13

### Shell Version

zsh

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Sorta.

I have evangelized Warp a lot over the last year. This behavior is concerning for me. I see the Terminal as being so low in my stack that I need it to work exactly as the standards dictate. I cannot be sitting there wondering if my terminal is being wonky. I need five nines for my expectations.

I imagine that `PS1` is a special case and maybe the only case where you do this stuff.

Still… I’m concerned about this.

Finally, maybe I'm just doing something wrong? I would like to be able to alter the user’s prompt. Is there something else I should be doing instead?

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by zachbai** [comment]
Hey @mxcl, those `%{`, `%}` sequences are added as an implementation detail to ensuring command characters echo'd by the shell are correctly positioned in the character grid -- they shouldn't affect display of the prompt (though obviously this isn't the case for you).

Would you mind sharing a screenshot of Warp with 'show custom PS1' enabled?

**Comment by dannyneira** [comment]
Closing as resolved. Feel free to let us know if the issues persist.
