### ISSUE TITLE
Warp updates clobber my custom icon - Icon hard to tell it is a terminal app

### ISSUE THREAD

**Issue by hierophantos** [warpdotdev/Warp#3499]
### Describe the solution you'd like?

```Text
I have a challenge everytime I use app switcher in finding Warp. My eyes and brain are looking for an icon that looks like a terminal. So, what I like to do is replace the warp icon found at `/Applications/Warp.app/Contents/Resouces/Warp.icns` with another terminal icon I found so that it is more recognizable.

Unfortunately, this gets overwritten with each update, which is quite frequent. (Great that you update so much and keep bringing awesome features and improvements, but maybe not clobber the *.icns??)
```

### Is your feature request related to a problem? Please describe.

```Text
I'm frustrated that I can't find my terminal app visually. I'm fatigued at having to replace the icon manually at each update. (ok, i'll make a script, but... still)
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @hierophantos 

We already have a request tracking this over at #1865 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
