### ISSUE TITLE
Allow configuring which directory new tabs open

### ISSUE THREAD

**Issue by zheng** [warpdotdev/Warp#35]
**Is your feature request related to a problem? Please describe.**
I love the idea but it was confusing to have as the default new tab behaviour, personally I'd probably want to put it behind a custom hotkey instead and keep Cmd+T as it is.

**Describe the solution you'd like**
Would be cool if this were configurable / could be disabled eventually.

**Comment by elviskahoro** [comment]
https://github.com/warpdotdev/warp/issues/105#issue-963169478

**Comment by elviskahoro** [comment]
Moving to #579 so all keybinding related issues are in one place:
- #579

**Comment by elviskahoro** [comment]
Gonna close this in favor of #105
