### ISSUE TITLE
input editor: bash - /Users/{{USERNAME}}: is a directory

### ISSUE THREAD

**Issue by ksallee** [warpdotdev/warp#350]
### Describe the bug

```shell
When I launch warp, the first command always works, but all subsequent commands fail with an error:
`bash: /Users/{{USERNAME}}: is a directory` 
with {{USERNAME}} being my username.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```shell
I expect run commands to work.
```

### Screenshots

<img width="1019" alt="Screen Shot 2021-11-03 at 12 43 41 PM" src="https://user-images.githubusercontent.com/57231302/140173006-1fc1963d-dddb-4e59-b357-a84dee7cfa8a.png">

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
Do you have any prompt plugins or change your prompt in any way?

If so can you put your prompt stuff

```sh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
   # prompt stuff here ##############################
    source ~/.config/powerlevel10k/powerlevel10k.zsh-theme
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
    (( ! ${+functions[p10k]} )) || p10k finalize
  # prompt stuf here #################################### 
fi
```

**Comment by ksallee** [comment]
that might actually be the case, I have quite a few things in my bashrc, I'll check, thanks!
