### ISSUE TITLE
Allow different themes across tabs/windows

### ISSUE THREAD

**Issue by rwinchester** [warpdotdev/Warp#3503]
### Describe the solution you'd like?

```Text
I want to be able to apply different themes to different tabs/windows so I can use them as context clues.
```

### Is your feature request related to a problem? Please describe.

In Mac Terminal, I use different colors to cue me as to what context I'm working with (different tools, etc.). I love Warp's themes, but want to be able to apply different themes to different tabs/windows so I can keep those context clues.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @rwinchester 

We already have a request tracking this over at #478 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
