### ISSUE TITLE
Update causes new dock icon on Mac

### ISSUE THREAD

**Issue by nfiacco** [warpdotdev/Warp#3504]
### Describe the bug

When Warp updates, it causes a new dock to be created on my Mac

### To reproduce

Pin Warp to the Mac dock, update Warp, then open the updated Warp.

### Expected behavior

The old dock icon is reused

### Operating system

MacOS

### Operating system and version

13.4.1

### Current Warp version

v0.2023.08.01.08.05.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @nfiacco 

We're tracking this issue over at #1535 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
