### ISSUE TITLE
WarpAI block scrolls too fast 

### ISSUE THREAD

**Issue by Liferenko** [warpdotdev/Warp#3506]
### Discord username (optional)

liferenko

### Describe the bug

Trying to scroll up a bit using the Mac's touch bar. It scrolls too far, even with a light two-finger scroll. A long bottom-up scroll causes the WarpAI conversation results to scroll all over the place. This feels strange and might negatively affect the user experience, giving minus points to those who are willing to use WarpAI.

### To reproduce

- Make kinda long conversation with WarpAI (4-5 requests with long answers)
- try to scroll a bit up to reach previous answer

Video is attached:

https://github.com/warpdotdev/Warp/assets/5435375/85b61fba-1387-4321-a778-a12e13c65ca5

### Expected behavior

light scroll up moves you a bit up, not too far. 

### Operating system

MacOS

### Operating system and version

13.3 (22E252)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.01.08.05.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by Liferenko** [comment]
feel free to assign this issue on me - I'm about to resolve it and add a PR

**Comment by moliyu** [comment]
I have the same problem with m1 mac, but it will be ok after restart warp
