### ISSUE TITLE
Enable macOS Services menu

### ISSUE THREAD

**Issue by yood** [warpdotdev/Warp#3508]
### Describe the solution you'd like?

```Text
Can you show the macOS standard Services menu in the menu bar?
```

### Is your feature request related to a problem? Please describe.

```Text
I'm frustrated when I can't run my Shortcuts actions via keyboard shortcuts when in the Warp app.

Shortcuts allows me to run my custom shortcuts when I press keyboard shortcuts via the Services menu.

Here's an example of the shortcuts that I want to access when another app is in the foreground: https://share.cleanshot.com/fZbxBvvj See the Open Xcode, Open Warp, etc items.
```

### Additional context

I'm using https://hyperkey.app to map Caps Lock to translate to all of the modifiers pressed at once.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by fior-di-latte** [comment]
I am facing the same issue over here. Other terminals usually expose the Services.
In the current state I cannot use my shortcuts.
This holds me back from using Warp as the daily driver.

**Comment by GalexyN** [comment]
@yood @fior-di-latte  i see the ticket is closed was this feature added? i cant seem to find a setting for it

**Comment by yood** [comment]
Yes it was fixed a while ago. Thank you!
