### ISSUE TITLE
auto complete directory with wrong escaping

### ISSUE THREAD

**Issue by neowu** [warpdotdev/Warp#3511]
### Describe the bug

create a folder named "~",  try to complete folder list with "cd", then it produces 
```
~/''
```
which should be '~'

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/1100909/1aefeefa-585a-4060-ae20-cbc1c493bb29)
![image](https://github.com/warpdotdev/Warp/assets/1100909/beea01ef-a878-4585-a4cb-1fcaa1398b03)

### Operating system

MacOS

### Operating system and version

MacOS 13.5

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @neowu We've fixed this issue in the latest version of Warp. Please update and let us know of any issues. Closing as completed.
