### ISSUE TITLE
Aliases can't be disabled temporarily with backslash

### ISSUE THREAD

**Issue by Bellisario** [warpdotdev/Warp#3516]
### Discord username (optional)

giorgiobellisario

### Describe the bug

Writing a backslash immediately followed with a command (ex. `\ls`) doesn't temporarily override the alias set.

### To reproduce

> The steps showed here are to configure `exa` as an alias for `ls`, but you can use the command you want.

1. edit your zsh config: (ex. `nano ~/.zshrc`)
2. add this line: `alias ls='exa'`
3. save and close the file
4. open a new terminal session
5. type `\ls` and press Enter
6. Warp replaces `\ls` with the alias `exa` (also replacing the backslash) and executes the command

### Expected behavior

Executing `\ls` on Warp I expected it to override temporarily the alias.

### Screenshots

> Commands executed in the following image:
> - `ls` (than replaced to `exa` by Warp)
> - `\ls` (also replaced to `exa`, this is the bug)
> - `"ls"` (an alternative way to override the alias, this one works as expected)

<img width="815" alt="image" src="https://github.com/warpdotdev/Warp/assets/72039923/fbdb88da-bba3-4acb-a13b-d105e3b68ded">

### Operating system

MacOS

### Operating system and version

macOS Ventura 13.5

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.01.08.05.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

None

### Additional context

If someone is encountering the same issue, you can "fix" that like so: instead of using for example `\ls -la`, try using `"ls" -la`.

---

The backslash alias override works as expected on the Terminal application and iTerm.

---

I just noticed this issue so I don't have enough context to say if this bug used to work with previous versions.

---

This bug doesn't block me from using Warp daily, but if I need to override an alias, I will probably need to write the command twice, as the first time I will use `\ls` and, remembering it doesn't work as expected, I will "fix" that using `"ls"`.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by danielpeng2** [comment]
Hey! Can you confirm that this is happening with the alias expansion featured enabled? I'm able to repro the issue with `\ls`, but I'm also noticing that `"ls"` doesn't override the alias for me -- it gets escaped as well.

**Comment by Bellisario** [comment]
Yes, I can confirm the issue is with the alias expansion enabled. Disabling it, `\ls` works as expected (overriding temporarily the alias).

`"ls"` seems to prevent the alias taking "control" and overrides temporarily the alias, but I noticed this now (`v0.2023.08.15.08.03.stable_00`) only works if you don't include arguments, for example the command `"ls" -la` gets replaced to `exa -la`, the strange thing is that this seemed to work when I originally reported the issue (`v0.2023.08.01.08.05.stable_03`).

**Comment by dannyneira** [comment]
Hey Folks, As of Warp [v0.2024.04.02.08.02](https://docs.warp.dev/getting-started/changelog#id-2024.04.04-v0.2024.04.02.08.02), Warp no longer automatically expands aliases that are escaped using a backslash.

Closing as resolved, but please let us know if any issues with the improvement.
