### ISSUE TITLE
User input doesn't get handled as expected with simple ruby script. Works in iTerm

### ISSUE THREAD

**Issue by ScotterC** [warpdotdev/Warp#3517]
### Discord username (optional)

.scotter

### Describe the bug

In Warp terminal, while running a Ruby script or rake task that prompts the user for input using the gets method, pressing the Enter key does not submit the input as expected. Instead, it prints a '^M' character. This behavior indicates a possible issue with newline handling in the terminal.

### To reproduce

chat.rb
```ruby
print "Please enter your name: "
name = gets.chomp
puts "Hello, #{name}!"
```

warp:
```bash
ruby simple.rb
Please enter your name: foo^M
```

### Expected behavior

when you hit return the input should be submitted

### Screenshots

<img width="530" alt="Screenshot 2023-08-10 at 12 53 08 PM" src="https://github.com/warpdotdev/Warp/assets/313254/586f1dcc-c2cd-44d8-b775-cab0324f0e24">

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.01.08.05.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by ScotterC** [comment]
Very weird. I'm having trouble reproducing today as well after a restart. I'm not sure what state my terminal got in yesterday. Thanks for the quick response.

**Comment by aidandonohue** [comment]
Got this error as as well using the `input()` in python. Restarted the warp terminal and the issue fixed itself. Will update with fuller context if it keeps happening.
