### ISSUE TITLE
Provide option to disable red background highlight

### ISSUE THREAD

**Issue by cricklet** [warpdotdev/Warp#3518]
### Describe the solution you'd like?

```Text
Hi! I find the red background when an error is in the output difficult to read. If there's a sea of warnings and just one error, it also makes it difficult to find that error because the red error text blends in with the red background.

Ideally, there's a way to turn off the red background or edit a theme to remove it.
```

### Additional context

<img width="749" alt="Screen Shot 2023-08-10 at 10 04 53 AM" src="https://github.com/warpdotdev/Warp/assets/659021/f028c52b-ea5b-415b-8e09-6feed8882dda">

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
test

**Comment by rsalmei** [comment]
Seems duplicated with #2385.

**Comment by dannyneira** [comment]
Thanks for letting us know @rsalmei 

We already have a request tracking this over at #2385

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by rsalmei** [comment]
You're welcome @dannyneira.
I not only subscribed there yesterday but also posted some images of my own, please take a look.
