### ISSUE TITLE
Configurable line height

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#352]
### Describe the solution you'd like?

```shell
To configure the text line height.
Discord - feature-requests - 2021.11.03:
"FR: Reduce the line-height (or add an option). I don't mind the UI taking up more space than a normal terminal, but you lose too much space to each line. I would accept whatever line-height: normal is for the current font. Based on the Fira Code repo, it's still substantially tighter than in Warp."
```

### Is your feature request related to a problem? Please describe.

```shell
N/A
```

### Additional context

https://discord.com/channels/851854972600451112/852249738002956311/905494119076474891

**Comment by pf1gura** [comment]
I like to set my line height to something bigger than the standard. I find too much text in one view to be distracting. In iTerm, my preferable value is 200. I suppose I am not alone in this and it would be nice to have that option.

![CleanShot 2021-11-05 at 21 13 52](https://user-images.githubusercontent.com/41795518/140572835-296d4e60-6d92-4056-8c86-dddf871ec0f6.png)

**Comment by argais** [comment]
I've just downloaded warp and have the same issue, line height needs to be configurable.

![image](https://user-images.githubusercontent.com/8986004/144688428-4b65c2c4-90f9-4e51-998d-4592b20ae3ec.png)
On the left there is warp, on the right iterm. While this might be ok on a desktop and big screen, on a 13" laptop its way too  much space wasted.

**Comment by lnking81** [comment]
Not only the line height but also all font rendering options: name, size, the interval between letters, ligatures, anti-aliasing, etc.

**Comment by elviskahoro** [comment]
Gonna merge this into 
- #317

**Comment by elviskahoro** [comment]
@argais @lnking81 @pf1gura just moved this to:
- #317
