### ISSUE TITLE
Make a theme using picture failed

### ISSUE THREAD

**Issue by fr0stevl** [warpdotdev/Warp#3520]
### Describe the bug

Toast "Something went wrong." after click Create theme button.

### To reproduce

1. select a picture 2. click Create theme button 3. toast wrong message

### Operating system

MacOS

### Operating system and version

13.4.1

### Current Warp version

v0.2023.08.08.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by drj613** [comment]
I'm seeing this issue as well on MacOS 13.5. Same Warp version. Happens with both `.png` and `.jpg` files regardless of dimension or file size.

**Comment by liamjones** [comment]
Same here on 13.5 too.

Something else I noticed which might be relevant? If you try and rename the theme after the error toast appears the preview background image disappears and you can see your other desktop windows behind Warp. It doesn't happen if you change the name before the error is triggered.

**Comment by drj613** [comment]
> Sorry to hear about this folks! I've not been able to reproduce this issue. If you could please provide the image you're trying to use along with the name you gave the theme and, if possible, a recording of the issue.

It seems to work just fine when making the theme, but toast error gets thrown when you try to save it.

![Kapture 2023-08-11 at 17 32 56](https://github.com/warpdotdev/Warp/assets/30848200/843fa7da-721f-413f-a544-1ca03654b97a)

**Comment by fumiama** [comment]
Same issue with me.

**Comment by liamjones** [comment]
> If you could please provide the image you're trying to use along with the name you gave the theme and, if possible, a recording of the issue.

This has happened with every single image I've tried so far. Here's one it's been happening with for me: https://imgur.com/4HPEcJ8 (download link in the ... menu to a ~900kb jpeg).

The only common thing to all the files I've tried; is they all live in the same location `/Users/liam.jones/Pictures/Wallpapers`. I've tried from 25MB PNGs with kanji in the filename/theme name down to files like that 900 KB JPEG with purely ASCII filename/theme name. Preview always generates but create fails.

**Comment by drj613** [comment]
> Hey folks, we're working on a fix. As a workaround, please manually create the `~/.warp` folder (`mkdir ~/.warp`); the theme creation should work as expected. We'll post updates when a fix is released.

Did the trick for me, thank you!! Really sweet feature 😄

**Comment by dannyneira** [comment]
Closing as resolved, please update Warp to the latest version. Feel free to let us know if the issues persist.
