### ISSUE TITLE
Top command can not show correctly

### ISSUE THREAD

**Issue by withshe** [warpdotdev/Warp#3530]
### Describe the bug

When I ssh to a server, type `top` command, the informations can not shows correctly

### To reproduce

ssh x.x.x.x
top

### Screenshots

![screenshot-20230814-141018](https://github.com/warpdotdev/Warp/assets/461748/af2222c9-18c5-41c6-a4f9-7bf51f8c23ee)

### Operating system

MacOS

### Operating system and version

14.0.0

### Current Warp version

v0.2023.08.08.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @withshe This has to do with the alt screen behavior and the [Sticky Command Header](https://docs.warp.dev/features/blocks/sticky-command-header). As a workaround, please disable the sticky command header. We'll post any further updates on this thread.

**Comment by dannyneira** [comment]
We'll be tracking this issue over at #3214  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
