### ISSUE TITLE
Disable changelog on startup

### ISSUE THREAD

**Issue by ghost** [warpdotdev/Warp#3531]
### Discord username (optional)

none

### Describe the solution you'd like?

```Text
I am not a developer — I do not care about the changelog. Every time I open Warp half my screen is covered by a changelog. Is there a way to disable the changelog/Warp Essentials window when starting Warp? Requiring the mouse to operate the CLI feels like two steps backwards.
```

### Is your feature request related to a problem? Please describe.

```Text
I'm always frustrated when I want to start working and the app is like "oh hey let me distract you with all this bullshit and clutter that some developer wants to show off"
```

### Additional context

A checkbox to "Never show the changelog" would be nice.

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
User has deleted the account and cannot respond. Closing issue as stale.
