### ISSUE TITLE
hstr closes Warp

### ISSUE THREAD

**Issue by xidiot** [warpdotdev/Warp#3537]
### Discord username (optional)

xidiot#4822

### Describe the bug

When invoking [hstr](https://github.com/dvorka/hstr) it is crashing/closing the pane in which it is executed execute it. If there's only 1 pane in the active tab it will close the pane with the tab itself without any message.

13:31:14 [INFO] dispatching typed action: Enter
13:31:14 [WARN] Received 'end_in_band_command_output' while not expecting to read in-band command output.
13:31:14 [INFO] Received Preexec hook
13:31:14 [WARN] redraw_frame was called 2 times before the frame was drawn
13:31:14 [INFO] Tried to exit the alternate screen, but it was already inactive
13:31:14 [INFO] Block finished with new state DoneWithExecution
13:31:14 [INFO] dispatching global action for workspace:save_app
13:31:14 [WARN] redraw_frame was called 4 times before the frame was drawn
13:31:14 [INFO] window will close
13:31:14 [INFO] dispatching global action for workspace:save_app
13:31:14 [INFO] dealloc native window 0x145f39c10

### To reproduce

1. Install hstr
2. Execute `hstr --` few time and at some point the pane in which `hstr` is being executed will be closed.

### Expected behavior

Execute every time  without crashing

### Operating system

MacOS

### Operating system and version

macOS Ventura Version 13.5 (22G74)

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
closing as duplicate
