### ISSUE TITLE
hstr closes Warp

### ISSUE THREAD

**Issue by xidiot** [warpdotdev/Warp#3538]
### Discord username (optional)

xidiot#4822

### Describe the bug

When invoking [hstr](https://github.com/dvorka/hstr) it is crashing/closing the pane in which it is executed execute it. If there's only 1 pane in the active tab it will close the pane with the tab itself without any message. I've tested it on quite some terminals (kitty, WezTerm, iTerm2, Terminal, Hyper) and this happens only in Warp.

Here's some of the output when starting Wrap from other terminal in order to get some logs:

```
13:31:14 [INFO] dispatching typed action: Enter
13:31:14 [WARN] Received 'end_in_band_command_output' while not expecting to read in-band command output.
13:31:14 [INFO] Received Preexec hook
13:31:14 [WARN] redraw_frame was called 2 times before the frame was drawn
13:31:14 [INFO] Tried to exit the alternate screen, but it was already inactive
13:31:14 [INFO] Block finished with new state DoneWithExecution
13:31:14 [INFO] dispatching global action for workspace:save_app
13:31:14 [WARN] redraw_frame was called 4 times before the frame was drawn
13:31:14 [INFO] window will close
13:31:14 [INFO] dispatching global action for workspace:save_app
13:31:14 [INFO] dealloc native window 0x145f39c10
```

ps: one of the reasons I would like to use hstr is because Warp search does not show full commands

### To reproduce

1. Install hstr
2. Execute `hstr --` few times and at some point the pane in which `hstr` is being executed will close.

### Expected behavior

Execute every time  without crashing

### Operating system

MacOS

### Operating system and version

macOS Ventura Version 13.5 (22G74)

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)

### Current Warp version

v0.2023.08.08.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by zachbai** [comment]
@xidiot Thanks for filing. We think we've identified the issue and are working on a fix. We'll follow up on the thread with updates.

**Comment by dannyneira** [comment]
Closing as resolved, please update Warp to the latest version. Feel free to let us know if the issues persist.
