### ISSUE TITLE
DUP: Duplicate of #292 - Meta-key not working with emacs

### ISSUE THREAD

**Issue by hillegass** [warpdotdev/warp#354]
### Describe the bug

```shell
I checked the menu items for left-Meta and right-Meta, but when i try to use it in emacs,  I get M-x \approx (the wiggly equals sign).
```

### To Reproduce

Check menu items.
Start emacs on the command line
Type Option-X.

### Expected behaviour

```shell
M-x
```

### Screenshots

<img width="393" alt="Screen Shot 2021-11-03 at 8 36 35 PM" src="https://user-images.githubusercontent.com/188895/140238251-19a0783f-cfca-4c90-a4f8-46eeae0ed182.png">

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
Linking:
- #292
