### ISSUE TITLE
MacOS 13.5 (22G74) ZSH - warp stuck trying to Warpify shell

### ISSUE THREAD

**Issue by CrazyFunker** [warpdotdev/Warp#3543]
### Discord username (optional)

crazyfunker

### Describe the bug

Warp is stuck trying to warpify the ZSH shell.
Unable to use the shell.

Warp.dev seems to be only working on the bash shell.

What approaches failed:
- Completely removing any setup from `.zshrc` and `.zprofile`.
- I've reinstalled the app and flushed data according to https://docs.warp.dev/help/uninstalling-warp 
- Inspecting warp.logs for any errors and canaries

In the end, I started inspecting and debuggin (by running each subcommand one by one) the command that kicks off the `Warpification`:
```
[ -z $WARP_BOOTSTRAPPED ] && echo $0 | command -p grep -q zsh && unsetopt ZLE && eval 'setopt hist_ignore_space; unsetopt ZLE; WARP_IS_SUBSHELL=1; WARP_SESSION_ID="$(command -p date +%s)$RANDOM"; _hostname=$(command -pv hostname >/dev/null 2>&1 && command -p hostname 2>/dev/null || command -p uname -n); _user=$(command -pv whoami >/dev/null 2>&1 && command -p whoami 2>/dev/null || echo $USER); _msg=$(printf "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"shell\": \"zsh\", \"user\": \"$_user\", \"hostname\": \"$_hostname\", \"is_subshell\": true}}" | command -p od -An -v -tx1 | command -p tr -d " \n"); printf '"'"'\x1b\x50\x24\x64%s\x9c'"'"' $_msg; unset _hostname _user _msg;' || [ -z $WARP_BOOTSTRAPPED ] && echo $0 | command -p grep -q bash && eval 'command -p stty raw;unset PROMPT_COMMAND;HISTCONTROL=ignorespace;HISTIGNORE=" *";WARP_IS_SUBSHELL=1;WARP_SESSION_ID="$(command -p date +%s)$RANDOM";_hostname=$(command -pv hostname >/dev/null 2>&1 && command -p hostname 2>/dev/null || command -p uname -n);_user=$(command -pv whoami >/dev/null 2>&1 && command -p whoami 2>/dev/null || echo $USER);_msg=$(printf "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"shell\": \"bash\", \"user\": \"$_user\", \"hostname\": \"$_hostname\", \"is_subshell\": true}}" | command -p od -An -v -tx1 | command -p tr -d " \n");printf '"'"'\x1b\x50\x24\x64%s\x9c'"'"' $_msg;unset _hostname _user _msg;' || [ -z $WARP_BOOTSTRAPPED ] && [ $FISH_VERSION ] && eval 'set -g WARP_SESSION_ID (random);set _hostname $(command -v hostname >/dev/null 2>&1 && command hostname 2>/dev/null || uname -n);set _user $(command -v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER);set _msg $(echo -n "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"user\": \"$_user\", \"hostname\": \"$_hostname\", \"shell\": \"fish\", \"is_subshell\": true}}" | od -An -v -tx1 | command tr -d " \n");echo -n \u1b\u50\u24"d$_msg"\u9c;set -e _hostname _user _msg;'
```
I arrived at the conclusion that it gets stuck when it hits the `printf '"'"'\x1b\x50\x24\x64%s\x9c'"'"' $_msg;` command.

### To reproduce

MacOS 13.5 (22G74)
ZSH

Make sure zsh is selected as default shell in Warp.dev.

After reboot it works for a brief while.
Continue work/sleep the MAC.
Come back, open new tab.

### Expected behavior

Warp is not stuck indefinitely trying to warpify the shell.

### Screenshots

<img width="229" alt="image" src="https://github.com/warpdotdev/Warp/assets/3400344/ec557549-0ea5-491b-8dba-3966ef244754">

### Operating system

MacOS

### Operating system and version

Ventura 13.5 (22G74)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.08.08.04.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

01/07/2023

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by philstevenson** [comment]
@warpdotdev-dx That didn't seem to make a difference for me. Still hangs on `Starting zsh...`
default set to `/bin/zsh`

**Comment by CrazyFunker** [comment]
Unfortunately, just like @philstevenson is reporting, it's still hanging on the same `Starting zsh...`. Default set to `/bin/zsh`

**Comment by philstevenson** [comment]
Looks like the issue could possibly have been our work setup, our `/tmp` directory wasn't writeable. 
So a quick chown fixed the issue `sudo chown $(whoami):staff /tmp`

**Comment by CrazyFunker** [comment]
As @philstevenson I confirm this worked. Closing this ticket.
