### ISSUE TITLE
Add option to save Split View

### ISSUE THREAD

**Issue by deepyes02** [warpdotdev/Warp#3553]
### Discord username (optional)

@deepyes02

### Describe the solution you'd like?

```Text
Hello there, 

I am in love with this terminal. 

I would like to have the application remember by split terminal view state, so that I don't need to split it into 4 quarters every time I restart the app.
```

### Is your feature request related to a problem? Please describe.

```Text
I'm frustrated by not being able to organize multi panels and having to do that every time I restart the app. The tabs are there but split view is a really better way to multitask. I love it. 

As you can see in the attachment below, I would like the application to remember that layout state. Maybe probably an additional menu from where I can load this state. Maybe it can save a few states like this, so that I can quickly load my layout as per my work. 

I know it's quick to simply split the panels, but as a dev I'd like the app to present me with a customized view when I load it first.
```

### Additional context

![Screenshot 2023-08-18 at 9 48 41](https://github.com/warpdotdev/Warp/assets/44121607/16fb1e71-beb7-43df-a8c3-145401154e39)

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by toddbutters-tf** [comment]
Try [launch configurations](https://docs.warp.dev/features/sessions/launch-configurations#what-is-it). You can even set up commands to run automatically at launch like launch your web server and local database.

1. Manually configure your window(s) and panes as you like them.
2. Open the command palette `Command + p`
3. Search "save new launch configuration"
4. Enter a name and save
6. Launch next time via shortcut `Ctrl + Shift + L` or just search the launch configuraiton name in the command palette.

**Comment by deepyes02** [comment]
Thank you,

I see it can help me load my panel, but still, I am not happy as it opens my configuration in a new window, which is not what my original issue was.
Instead, it is faster to just Command + D, Command + Shift + D, since it won't open up a new window.
I hope you can see what I mean, but I understand this might be complicated to implement.
Thank you for your help.
________________________________

**Comment by toddbutters-tf** [comment]
I see what you mean now. I don't believe there is a way to replace an existing window with a launch configuration. I tried the Raycast extension and even with that I end up with two windows, one with my configured layout, and one window with a single tab.

@deepyes02 , I would go vote/thumbs up [this issue](https://github.com/warpdotdev/Warp/issues/3097) which sounds like it could accomplish what you're hoping for, if added.

In the mean time, maybe you could get by with the [session restoration](https://docs.warp.dev/features/sessions/session-restoration).
