### ISSUE TITLE
Warp does not re-open in full screen after being closed

### ISSUE THREAD

**Issue by liam-reilly** [warpdotdev/Warp#3555]
### Discord username (optional)

www.liam-reilly.info

### Describe the bug

I always used Warp in full screen mode. When I open Warp each day it opens maximised but not full screen. I have to manually click the full screen button each day. None of my other apps have this issue.

I know it doesn't seem like a big deal but I've held off a long time asking for this thinking it would have been addressed by now but it hasn't. 

Can you please make Warp remember it was full screen and re-open full screen if was full screen when closed?

Many thanks. 

BTW I loved Warp from day one and it's just getting better and better all the time and I'm bringing new people to Warp any chance I get! 

### To reproduce

Click the green full screen button to put Warp into full screen mode.  Close Warp with CMD+Q.  Re-open Warp. 

Warp does not re-open in full screen mode but instead is maximised.

### Expected behavior

I'd expect Warp to open back up in full screen mode as per the previous session.

### Operating system

MacOS

### Operating system and version

13.4.1 (c) (all versions so far)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.08.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by nichoj10** [comment]
A fix for this was included in the latest release (v0.2024.08.20.08.02.stable_00). Let us know if you see any issues!

**Comment by dannyneira** [comment]
Closing as resolved, but please do let us know if the issue persists.
