### ISSUE TITLE
Display gets messed up while using nnn

### ISSUE THREAD

**Issue by revadir** [warpdotdev/Warp#3556]
### Describe the bug

Never saw this before. With the latest update (or previous), started seeing display glitches where you will see multiple highlights than the cursor and when I move into a directory that's longer than the previous or do a search, everything is messed up real bad (see search bug files. one of them shows a glitch where file names appear at the bottom of the screen when there are only 4 files at the top and the cursor stops at ontology file. Loving warp and hope you fix this asap.

### To reproduce

1. install nnn
2. set font to "ComicCodeLigatures Nerd Font"
3. start nnn and navigate and play
4. search for files.

### Screenshots

![search_bug2](https://github.com/warpdotdev/Warp/assets/11507365/a2ee8fe1-a1ad-4d3e-aaee-cff779dbb924)
![search_bug](https://github.com/warpdotdev/Warp/assets/11507365/8bc6cad6-b806-4845-b1a3-fb8cc8a616c6)
![bug1](https://github.com/warpdotdev/Warp/assets/11507365/2e97b171-870d-4b78-9a9a-2245cd4be5e6)

### Operating system

MacOS

### Operating system and version

13.5.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.08.08.04.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
@revadir Any luck with finding the installation link for the Comic Code Ligatures font?

**Comment by dannyneira** [comment]
Closing as stale, but please feel free to let us know the link for the Comic Code Ligatures font. As a workaround, We recommend you try one of the following nerd fonts which should be supported: https://www.nerdfonts.com/
