### ISSUE TITLE
vscode integrated terminal?

### ISSUE THREAD

**Issue by jdion84** [warpdotdev/Warp#3560]
### Describe the solution you'd like?

```Text
i'm just wondering if it's possible to use warp as the integrated terminal in vscode somehow

i know i can launch warp through vscode, but what would be way better is to actually just use warp inside vscode itself

is the possible in any way?
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by Sten435** [comment]
Would be nice

**Comment by BitCalSaul** [comment]
that would be great if the warp could be used as a insider terminal in the vscode.

**Comment by devwal** [comment]
Please do!

**Comment by vodila-privet** [comment]
Please do :-)

**Comment by Sten435** [comment]
Is this done?

**Comment by mrkeshav-05** [comment]
Yeah it would great to see warp in the vscode terminal

**Comment by dfsilva** [comment]
it would be wonderfull!!

**Comment by niemal** [comment]
This would be really amazing, although it has been 3 years since the original request of this feature.
