### ISSUE TITLE
workflow autofill truncates input

### ISSUE THREAD

**Issue by roryfahy** [warpdotdev/Warp#3561]
### Describe the bug

when pressing autofill button to try to save workflow, its cut off and modified.
![image](https://github.com/warpdotdev/Warp/assets/42627486/57dcc154-11bd-4fe1-b487-b85eb7143d10)
![image](https://github.com/warpdotdev/Warp/assets/42627486/63b9225f-1c64-4472-9cde-18ee260ea7ff)

### To reproduce

input 
`NO_MAPS=1 NO_EXTERNAL_API=1 NO_JOBS_RUNNER=1 \
  DEV_DB_HOST="op://Engineering/AWS Dev Postgres/server" \
  DEV_DB_USER="op://Engineering/AWS Dev Postgres/username" \
  DEV_DB_PASSWORD="op://Engineering/AWS Dev Postgres/password" \
  op run --no-masking -- iex -S mix phx.server` 
into terminal.  right click -> save as workflow -> autofill

### Expected behavior

not to truncate command

### Screenshots

attached above

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.15.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by roryfahy** [comment]
ps abosolutely LOVE warp.  its unreal

**Comment by dannyneira** [comment]
Hey @roryfahy this issue has been resolved in the latest version of Warp! closing as resolved, but please let us know if the issue persists.
