### ISSUE TITLE
The git cpu usage is especially high when I open a large project directory

### ISSUE THREAD

**Issue by LitterSun** [warpdotdev/Warp#3563]
### Describe the bug

Automatically upgrade to the latest version v0.2023.08.15.08.03.stable_00, the git cpu usage is especially high when I open a large project directory. And it doesn't return to normal after a long time. But v0.2023.08.08.08.04 is normal.

### To reproduce

1. Update v0.2023.08.15.08.03.stable_00
2. cd a git directory

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/15814506/9ac82c57-f861-48f7-8803-33c07a6fc88c)

### Operating system

MacOS

### Operating system and version

Ventura 13.2.1

### Current Warp version

v0.2023.08.15.08.03.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by szgupta** [comment]
Hi @LitterSun, sorry about the poor performance here. A couple of questions:
1. Are you using Warp's default prompt, or are you using your own custom PS1?
2. How large is this git repo? 

We recently made a change to make our prompt more dynamic and we rely on running git commands to update the status of the prompt. To speed up git commands in general, could you try enabling git's `FSMonitor` by running 
```
git config core.fsmonitor true
```
in the repo? You'll need to be running git 2.37.0 or greater. Here's some more info on `FSMonitor`: https://github.blog/2022-06-29-improve-git-monorepo-performance-with-a-file-system-monitor/

**Comment by LitterSun** [comment]
> Hi @LitterSun, sorry about the poor performance here. A couple of questions:
> 
> 1. Are you using Warp's default prompt, or are you using your own custom PS1?
> 2. How large is this git repo?
> 
> We recently made a change to make our prompt more dynamic and we rely on running git commands to update the status of the prompt. To speed up git commands in general, could you try enabling git's `FSMonitor` by running
> 
> ```
> git config core.fsmonitor true
> ```
> 
> in the repo? You'll need to be running git 2.37.0 or greater. Here's some more info on `FSMonitor`: https://github.blog/2022-06-29-improve-git-monorepo-performance-with-a-file-system-monitor/

1. I use Warp's default prompt
2. The repo is monorepo,  like chromium

FSMonitor is work for me, thanks @szgupta

**Comment by Livven** [comment]
On a large monorepo, I had like 20+ orphaned Git processes causing 100% CPU usage and making the whole system unresponsive even after exiting Warp. Enabling `core.fsmonitor` fixed things for me (and is a great improvement in general) but there should probably be some sort of circuit breaker, or at least kill the Git processes when exiting Warp.

**Comment by szgupta** [comment]
Hi @Livven, thanks for following up. Did you have multiple sessions opened in that particular monorepo when you saw the 20+ `git` processes?

Also, I wasn't able to repro orphaned `git` processes after quitting the app. Do you mind attaching a repro (in the form of a screen recording)?

**Comment by g0621** [comment]
For me it's creating around 100+  git processes, the  monorepo I am working on is really huge. I had to turn off warp prompt and kill all git processes, switching back to other terminal util next release with this bug fixed.

NOTE: git config core.fsmonitor true was already enabled with other git optimisations

**Comment by szgupta** [comment]
Hi @g0621, sorry to hear that. I'm working on a fix for this and this should hopefully be improved in the next update. Out of curiosity, does this still happen if you use your shell prompt (PS1) and restart Warp?

**Comment by pujiaxun** [comment]
For me the config `core.fsmonitor` seems not useful. I tried to set git config and restart warp, it didn't work. I have to replace it by the built-in `Terminal.app`. FYI, the project I work for is Chromium-like, really huge.

<img width="282" alt="image" src="https://github.com/warpdotdev/Warp/assets/13177974/f21ddadf-a09b-4f04-b65d-021386c78635">

**Comment by LitterSun** [comment]
@g0621 I have downgraded to v0.2023.08.08.08.04, here is the download link.
https://releases.warp.dev/stable/v0.2023.08.08.08.04.stable_00/Warp.dmg

**Comment by szgupta** [comment]
Hi all, sorry for the troubles here. We're actively working on a fix for this.

In the meantime, you can change your prompt to the shell prompt (PS1) and that should mitigate the problem for now. To do so, search for 'Edit Prompt' in the command palette, select the `Shell prompt (PS1)` and `Save`. Please let me know if you still see issues after changing the prompt.

**Comment by jacksongoode** [comment]
Noticed this as well

**Comment by philbogl-db** [comment]
After updating, I see a new issue with laggy update of the current directory in the prompt.

After changing directories in a large git monorepo, it takes several seconds for the prompt to update to the new directory.
