### ISSUE TITLE
"Jump to the bottom of this block" action is not available in the command palette

### ISSUE THREAD

**Issue by hferreiro** [warpdotdev/Warp#3564]
### Describe the solution you'd like?

```Text
Make that command available in the command palette.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Closing as completed. In Warp v0.2023.08.29.08.04.stable_00, for long Blocks, you can press SHIFT-CMD-UP/SHIFT-CMD-DOWN to Scroll to the top/bottom the selected block.

See our docs for more: https://docs.warp.dev/features/blocks/block-basics#select-a-single-block
