### ISSUE TITLE
Swiping finger on the mouse to the right or left changes tabs.

### ISSUE THREAD

**Issue by jmstax** [warpdotdev/Warp#3573]
### Describe the solution you'd like?

```Text
In order to navigate through different tabs, you can swipe your finger on the mouse to the right-hand side or left-hand side. This intuitive function can be helpful when you need to quickly switch between different tabs. It is a convenient feature that can save effort to click manually on tabs, especially when you are working on multiple projects simultaneously. By simply swiping your finger on your mouse to the left or right, you can easily access the tab you need and continue your work without any interruption or delay. This feature is available on another terminal out there.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks @jmstax We already have a request tracking this over at #582. 

Assuming swipe on trackpad and mouse would both apply, if you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
