### ISSUE TITLE
Rich Metadata Status Bar

### ISSUE THREAD

**Issue by naishe** [warpdotdev/Warp#3575]
### Describe the solution you'd like?

Switching from iTerm2 + Zsh + Oh-My-Zsh to Warp + Zsh has been refreshing. One thing I miss on Warp is the present working directory (PWD)'s metadata. I would really like if we have an option to pick and choose what info we want to be extracted and displayed on the shell. Right now, my iTerm2 looks like the image attached under "Additional Context", thanks to Oh-My-Zsh plugins.

It would be great to see container runtime, project version, package manager, programming language and it's version, and active cloud service account like you see the Google account at the end of the image, along with PWD, git branch, and git branch status (untracked, modified, deleted, stashed, staged but not pushed, remote repo has newer changes to be pulled etc).

### Additional context

<img width="1057" alt="Screenshot 2023-08-24 at 12 12 46 PM" src="https://github.com/warpdotdev/Warp/assets/845424/843fe74b-817f-4986-a2c5-4309ec66cb69">

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
@naishe Please also look into our Context Chips feature, or consider a custom prompt like p10k which we support.

Context Chips:
- Docs: https://docs.warp.dev/features/prompt#default-prompt
- Demo:  ![image](https://github.com/warpdotdev/Warp/assets/16809145/96ccd1dc-ee84-418e-8c03-6091c45925d5)

p10k:
- Docs: 
- Install/Demo: https://youtu.be/dIV9Cso4Mi8?si=2qeMWuiarguK--uU

**Comment by naishe** [comment]
Thanks @dannyneira I have been using PS1 prompt and pretty happy with it. Cheers!
