### ISSUE TITLE
Only show once prompt `Type '#' for AI command suggestions`

### ISSUE THREAD

**Issue by zhylmzr** [warpdotdev/Warp#3578]
### Describe the solution you'd like?

After today's update, it prompts every time I start typing a command.

I hope it will only appear once in the release note, and it will not appear in the future, it really disturb the sight.

<img width="321" alt="SCR-20230825-mqdv" src="https://github.com/warpdotdev/Warp/assets/15730824/7682795d-53d1-46ee-819c-8083ca30f2d6">

### How important is this feature to you?

2

**Comment by YurySolovyov** [comment]
Very annoying

**Comment by kiliankoe** [comment]
I agree, it's good to know this exists, previously I was using <kbd>ctrl</kbd><kbd>R</kbd> followed by # to open AI suggestions, but I don't need to see this on every prompt.

**Comment by dannyneira** [comment]
Hey folks, sorry to hear about this issue, I'm not seeing the same on my end, Does warp always show the "Type '#' for AI command suggestions" text? Could you please provide a video of the issue for added context?

**Comment by kiliankoe** [comment]
Interestingly enough it also went away again on my end.

**Comment by dannyneira** [comment]
Oh my mistake, this is something we're looking to launch soon and will have an option to disable in the settings soon!

**Comment by kiliankoe** [comment]
I don't have that setting on v0.2023.08.22.08.03.stable_00, but interestingly enough the input hint also went away on its own?

<img width="511" alt="image" src="https://github.com/warpdotdev/Warp/assets/2625584/46f9430d-7302-4c44-81f5-0b8c7ced4bcb">

**Comment by zhylmzr** [comment]
I can turn off the prompt through the above option.
