### ISSUE TITLE
Some Warp Drive folders don't stay collapsed

### ISSUE THREAD

**Issue by nihaals** [warpdotdev/Warp#3583]
### Describe the bug

Some folders keep uncollapsing after quitting Warp. It's the same folders every time but not all folders.

### To reproduce

1. Quit Warp
2. Open Warp
3. Open Warp Drive
4. Notice some folders are uncollapsed
5. Collapse all folders
6. Close and reopen Warp Drive
7. Notice all folders are still collapsed
8. Close and reopen all Warp windows
9. Notice all folders are still collapsed
10. Quit Warp and reopen it
11. Notice the same original folders are uncollapsed

### Expected behavior

Collapse states are persisted.

### Operating system

MacOS

### Operating system and version

macOS 13.5.0

### Current Warp version

v0.2023.08.22.08.03.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Unsure if it's a regression or not

### Additional context

I can't think of any pattern between the ones that stay collapsed and the ones that don't.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @nihaals We are no longer able to reproduce this in the most recent version of Warp. We're closing this as resolved, but please let us know if the issue persists.

**Comment by nihaals** [comment]
@dannyneira I'm on `v0.2023.11.14.08.02.stable_02` and can still reproduce this.

**Comment by dannyneira** [comment]
@nihaals thanks for letting us know, we've reopened this issue, are working on a fix, and will post updates on this thread when it's released.

**Comment by nihaals** [comment]
It looks like this is now fixed as of v0.2023.12.05.08.02 as also mentioned in the [changelog](https://docs.warp.dev/getting-started/changelog#2023.12.07-v0.2023.12.05.08.02).

**Comment by dannyneira** [comment]
Yes that's correct @nihaals! [Warp Drive folders now keep their opened/closed state through app restarts](https://docs.warp.dev/getting-started/changelog#2023.12.07-v0.2023.12.05.08.02)
