### ISSUE TITLE
"Honor user’s custom prompt(PS1)" option disappeared 

### ISSUE THREAD

**Issue by Vincent-CLY** [warpdotdev/Warp#3598]
### Discord username (optional)

MJIMI_TK8#8924

### Describe the bug

After going to 'Setting' -> 'Features' -> 'Session', there is no option of "Honor user’s custom prompt(PS1)"

### To reproduce

1. Go to 'Setting'
2. Go to 'Features'
3. Scroll Down to 'Session'
4. No option of "Honor user’s custom prompt(PS1)"

### Expected behavior

There should be an option of "Honor user’s custom prompt(PS1)" appears.

### Screenshots

<img width="1019" alt="Screenshot 2023-08-29 at 5 31 09 PM" src="https://github.com/warpdotdev/Warp/assets/122752877/05ef5c02-e165-4dab-9b62-ac79341a6cbf">

### Operating system

MacOS

### Operating system and version

Sonoma 14.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2023.08.22.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I am not sure if the update to the public beta version cause this problem since I am downloading Warp after the update and have never try it before. Actually, I saw that there is also someone mentioned in Discord about this issue, but seems to has no reply and not open an issue in Github. For reference: 
![IMG_3CE8FF5854A8-1](https://github.com/warpdotdev/Warp/assets/122752877/4d9e4ba6-509a-4629-b906-82b3bf9de12d)

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by szgupta** [comment]
Hi @Vincent-CLY, sorry for the confusion here -- the copy in that blog is dated. Here are the instructions on how to toggle your prompt in Warp: https://docs.warp.dev/features/prompt#how-to-access-it

**Comment by leobip** [comment]
Hello ..... I still have the problem.....

I configured the prompt follow the instructions but still the prompt appear in the botton of the screen ... I have to run: exec zsh and the it work ... but the prompt not blinking anymore....

![Screen Shot 2023-10-15 at 00 07 00 AM](https://github.com/warpdotdev/Warp/assets/50139505/a2879b3b-5f2c-4d64-9fb7-8dec5f27c40a)


![Screen Shot 2023-10-15 at 00 08 04 AM](https://github.com/warpdotdev/Warp/assets/50139505/c91a1024-a142-4c31-82f0-526c7ecedae3)


Please help...
