### ISSUE TITLE
Font is bolder than needed

### ISSUE THREAD

**Issue by VKondakoff** [warpdotdev/Warp#360]
### Describe the bug

The same font in Warp is looking bolder, than in other terminals.
Here is a screenshot. iTerm2 (left), Warp (right):

<img width="756" alt="Снимок экрана 2021-11-04 в 19 43 46" src="https://user-images.githubusercontent.com/230824/140383048-b9555861-dabf-4089-a30e-6409e8805948.png">

### Operating System

MacOS

### OS Version

12.0.1

**Comment by VKondakoff** [comment]
BTW, there is something wrong with the colors. Why the colors are so different?

**Comment by VKondakoff** [comment]
Can the font weight be related to Retina screen (I'm using iMac with Retina screen)?

**Comment by VKondakoff** [comment]
Compare the colors and font rendering in Kitty/iTerm2/Warp:
<img width="660" alt="Снимок экрана 2021-11-09 в 18 52 47" src="https://user-images.githubusercontent.com/230824/140958201-2d289bc8-c9e0-4754-85d1-745bbf090e96.png">

**Comment by oskarrough** [comment]
Got the same issue across Warp `v0.2021.11.09.19.46.stable_00` and Terminal.app on 12.0.1. Especially the Warp interface itself looks odd. I hope these screenshots illustrate it.

![screen 2021-11-10 at 16 47 00](https://user-images.githubusercontent.com/184567/141145373-04e88785-d425-4392-806e-ca9a528a08b7.png)

![screen 2021-11-10 at 16 47 28](https://user-images.githubusercontent.com/184567/141145457-6e85184e-f40c-4153-b959-0cf7d0b36e15.png)

**Comment by zmb3** [comment]
I'm seeing similar behavior here.

Warp looks great on my Mac's built in retina display:

<img width="1136" alt="Screen Shot 2022-01-04 at 9 09 16 AM" src="https://user-images.githubusercontent.com/7527103/148088948-c0115c92-825a-4dd2-b39a-4394ae0a4061.png">

But the text is heavier and a bit fuzzy on my external 4K display:
![Screen Shot 2022-01-04 at 9 09 05 AM](https://user-images.githubusercontent.com/7527103/148089026-fe5904ee-8109-48dc-936d-a9897e648bdc.png)

**Comment by emilio-martinez** [comment]
I second this – I'm not clear on why the font renders so much bolder; however, it also occurs to me that there's no control over the font variant that should be used which might aid in this.

**Comment by robrecord** [comment]
Yes, please add control over the font variant.

Many thanks.

**Comment by christiannaths** [comment]
I'm getting a similar issue, but like..... really bold. 😕 

<img width="1680" alt="Screen Shot 2022-06-15 at 8 50 12 AM" src="https://user-images.githubusercontent.com/11584/173857437-eb6cf625-3e74-4e34-9baf-22313fb5da0d.png">

**Comment by elviskahoro** [comment]
This is a WIP in progress. Should be out soon

**Comment by elviskahoro** [comment]
You're able to select thin strokes as an option via the settings page now!
![CleanShot 2022-08-28 at 00 51 23@2x](https://user-images.githubusercontent.com/29553206/187058086-2585451e-53f3-4270-a42a-5bae3f23df1a.png)

**Comment by elviskahoro** [comment]
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">
