### ISSUE TITLE
AM/PM time display instead of xx:xx

### ISSUE THREAD

**Issue by peterkrantz** [warpdotdev/Warp#3600]
### Describe the bug

In the preview of editing the default prompt, I can add a timestamp to it. The example shows for instance "12:25", but the actual displayed timestamp in the prompt is shown in AM/PM time format instead.

### To reproduce

Settings -> Appearance -> Prompt

### Operating system

MacOS

### Operating system and version

MacOS

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by yam-liu** [comment]
+1 for 24-hour format.

**Comment by dannyneira** [comment]
Hey folks, this is being worked on, no official ETA, but we'll post updates on this thread.

Preview below:

![CleanShot 2023-10-03 at 14 12 44](https://github.com/warpdotdev/Warp/assets/16809145/5692c0a7-5905-49e2-8e04-d30e4c13ee75)
