### ISSUE TITLE
Tabs lose custom name after long running processes are killed

### ISSUE THREAD

**Issue by nathanchapman** [warpdotdev/Warp#3603]
### Describe the bug

Tab loses custom name after killing the active process

### To reproduce

- Open more than one tab
- Rename the tab e.g. `compile`
- Run a watch command in the tab e.g. `npx tsc --watch` or `jest --watch`
- Kill the process
- Tab loses the custom name

### Expected behavior

Tab keeps custom name

### Screenshots

<img width="396" alt="image" src="https://github.com/warpdotdev/Warp/assets/4032071/c1b3e65e-5145-4762-af57-4fddf929614e">

### Operating system

MacOS

### Operating system and version

Ventura 13.3.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.22.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by nathanchapman** [comment]
Okay, I was able to reproduce again. Sorry, I left out a crucial detail that this only occurs in `watch` mode

Using the sample you provided in a `example.ts` file:

```
npx tsc example.ts --watch
```

then kill the process

**Comment by el-tumakov** [comment]
I have the same problems with tab names.

**Comment by patik** [comment]
Same here, with Jest `--watch`

**Comment by patik** [comment]
It happens quite reliably while running the TypeScript compiler in watch mode, e.g. `yarn tsc --watch` and then quitting it with control-C

https://github.com/warpdotdev/Warp/assets/262137/5793d3ee-97e1-4578-80f0-4c7c4db5dc95

**Comment by monkariartito** [comment]
I have the same problem with any tab (not only second), when I launch nest.js applications and stop them.

**Comment by eL1fe** [comment]
Same problem with next/nest apps with watch mode.

**Comment by nathanchapman** [comment]
> I have the same problem with any tab (not only second), when I launch nest.js applications and stop them.

Same here, updated the issue to reflect!

**Comment by dannyneira** [comment]
Hey Folks, as of Warp [v0.2024.03.26.08.02](https://docs.warp.dev/getting-started/changelog#id-2024.03.28-v0.2024.03.26.08.02), Custom Window/Tab titles are no longer improperly cleared when a process resets Warp's state.

Please update and let us know of any issues with the bug fix.
