### ISSUE TITLE
App broke after upgrade

### ISSUE THREAD

**Issue by wangyiz4262** [warpdotdev/Warp#3604]
### Describe the bug

After upgrading to the most recent stable version and restarting Warp, I got a blank window and there is no way to proceed. Please refer to the screenshot for details.

### To reproduce

Just start Warp, without doing anything particular.

### Screenshots

![Screenshot 2023-08-29 at 11 48 26 PM](https://github.com/warpdotdev/Warp/assets/3336253/0d7b3795-e17b-47b8-91e3-a1e8e424c248)

### Operating system

MacOS

### Operating system and version

13.5.1

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

08/29/2023

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by alokedesai** [comment]
Hi @wangyiz4262 , sorry for the issues you are experiencing! Does uninstalling and reinstalling Warp fix this issue? Our current theory is that this is an issue with the MacOs Metal API, but we are still investigating

**Comment by wangyiz4262** [comment]
Hi @alokedesai Thanks for getting back to me! I think you might be right. Some of my other apps showing solid white after waking up from sleep, although not pink. So most likely this is a bug from recent MacOS upgrade.

**Comment by heyrandhir** [comment]
faced the exact same issue. Restarting the PC worked for me.
