### ISSUE TITLE
Can't use { on Mac OS keyboard

### ISSUE THREAD

**Issue by adildg** [warpdotdev/Warp#3607]
### Describe the bug

Hello,

Somehow I can't use the openning bracket **{** (alt+5) when I use Wrap, it doesn't work neither on the terminal nor vim, nvim.
On other terminals it works 

### To reproduce

1. Open Wrap
2.a - Type { (alt+5)

### Operating system

MacOS

### Operating system and version

Ventura 13.4

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by alokedesai** [comment]
Hey @adildg, thanks for filing and sorry for the issues you are experiencing. Would you be able to include a video to better document the issue you are seeing? Are you using a non us-en keyboard by chance?

**Comment by alokedesai** [comment]
no problem, thanks for following up here!
