### ISSUE TITLE
settings>about> copyright text is 2022

### ISSUE THREAD

**Issue by EddieOner** [warpdotdev/Warp#3608]
### Describe the bug

v0.2023.08.22.08.03.stable_00
<img width="683" alt="image" src="https://github.com/warpdotdev/Warp/assets/18536676/7cd09dba-f97c-4540-9e12-97e8ed4be2cb">

### To reproduce

launch warp go to settings>about

### Operating system

MacOS

### Operating system and version

Ventura 13.3

### Current Warp version

v0.2023.08.22.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by aryan1306** [comment]
Hi can i pick this issue up if it is not resolved?
