### ISSUE TITLE
Subshell command line hidden behind block

### ISSUE THREAD

**Issue by fpaglia-rbi** [warpdotdev/Warp#3613]
### Describe the bug

Whenever I start a subshell in Warp, the input line is hidden behind the command block that initiated the subshell. Once you scroll down, it reveals the input line.

### To reproduce

1. Open a new subshell that's not "warpified".
2. Run a `clear` command.
3. The subshell disappears.

### Expected behavior

The subshell should always be visible and not hidden behind the previous block.

### Screenshots

<img width="909" alt="Screenshot 2023-08-31 at 14 22 26" src="https://github.com/warpdotdev/Warp/assets/93405069/d38bcdca-1cf2-4865-929c-c00f60a9ebfe">
<img width="621" alt="Screenshot 2023-08-31 at 14 22 35" src="https://github.com/warpdotdev/Warp/assets/93405069/ccfb7d58-6e6c-46bc-b47f-d16aca6996ed">

### Operating system

MacOS

### Operating system and version

Ventura 13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.22.08.03.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
We'll be tracking this issue over at #3214  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
