### ISSUE TITLE
Laggy update of current directory in prompt after changing  directories in a large repo

### ISSUE THREAD

**Issue by philbogl-db** [warpdotdev/Warp#3617]
### Describe the bug

When I change directory in a large monorepo, it takes multiple seconds for the prompt to update to show the current directory.  

This appears to be fallout from the fix to https://github.com/warpdotdev/warp/issues/3563.

### To reproduce

1. Change directories in a large git repo.
2. Note that it takes several seconds for the prompt to update to show the current directory

Screen record shows a repro.

https://github.com/warpdotdev/Warp/assets/119380744/755c13f7-7af7-47b3-9858-30b3ac3883ae

### Expected behavior

Expect directory to update immediately.

### Operating system

MacOS

### Operating system and version

Ventura 13.5

### Current Warp version

v0.2023.08.29.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @philbogl-db Thanks for letting us know. This may have been due to the changes that were introduced to address closed issues #3563. We'll post further updates for this delay on the thread.

As a possible workaround, please consider using a [supported PS1 prompt](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table).

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by philbogl-db** [comment]
Yes, the PS1 prompt resolved the issue for me.

I put the following in my .zshrc to mimic the Warp prompt, cribbed from some examples online.

```
# Find and set branch name var if in git repository.
function git_branch_name()
{
  branch=$(git symbolic-ref HEAD 2> /dev/null | awk 'BEGIN{FS="/"} {print $NF}')
  if [[ $branch == "" ]];
  then
    :
  else
    echo '('$branch')'
  fi
}

# Enable substitution in the prompt.
setopt prompt_subst

# Config for prompt. PS1 synonym.
autoload -U colors && colors

prompt='%{$fg[blue]%}%2/ %{$fg[green]%}$(git_branch_name)%{$fg[black]%}'
```

**Comment by dannyneira** [comment]
Hey @philbogl-db We've resolved this issue in the latest version of Warp. Please update and let us know if it persists. Closing as completed.

**Comment by EvHaus** [comment]
@dannyneira This is still happening for me in Warp v0.2024.03.26.08.02.stable_02

![bug](https://github.com/warpdotdev/Warp/assets/226640/fb3ef478-7c48-4d64-943d-7b1b91246feb)

**Comment by leesawyzard-ui** [comment]
If you're still seeing this issue in the latest version of Warp, please open a new bug report to let us know.
