### ISSUE TITLE
All folders on top on warp drive workflows

### ISSUE THREAD

**Issue by jcovin293** [warpdotdev/Warp#3621]
### Describe the solution you'd like?

```Text
Typically when listing files that are arranged in a folder-type system, the folders are all at the top in alphabetical order and the files are all at the bottom in alphabetical order. While I start to add more folders and workflows to my warp drive, it is more difficult to access items in folders because I expect them to be at the top.
```

### Is your feature request related to a problem? Please describe.

```Text
N/A
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi Folks, This feature will be available in next weeks release. You will be able to sort the Warp Drive objects by type which will push the folders to the top, please see loom demo:

https://www.loom.com/share/f0223dc7c0cd4f51b26715a90f2a880f

Closing as resolved, but please feel free to let us know if any issues.

**Comment by jmsfez** [comment]
@dannyneira, I prefer the previous ordering where folders are not on top of workflows.
Is it possible to let users select the order mode, or more globally to drag & drop any item (folder, workflow...) at the wished position ?
