### ISSUE TITLE
Improve rendering of Vim (full coverage preferrably)

### ISSUE THREAD

**Issue by daweth** [warpdotdev/Warp#3622]
### Describe the solution you'd like?

```Text
I want vim to be flush with the warp window, and have no jagged/rough edges like it is currently

So vim should cover the entire screen other than the tabs bar on top
```

### Is your feature request related to a problem? Please describe.

```Text
Currently, when using vim, there is a noticable border between the vim GUI and the warp underneath. This is a bit unclean and annoying to look at when the colors don't match.


TLDR: Vim doesn't look the same in Warp because of the spacing between the end of the Warp window and the start of the vim window
```

### Additional context

<img width="940" alt="Screen Shot 2023-09-01 at 4 14 06 PM" src="https://github.com/warpdotdev/Warp/assets/46637826/5a90f67c-46a9-4ed1-98cd-43dac49f3d2b">

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by elviskahoro** [comment]
@daweth I think there's an open issue for this already will try to merge it!
