### ISSUE TITLE
Warp hangs on making window very small

### ISSUE THREAD

**Issue by shreyasm-dev** [warpdotdev/Warp#3629]
### Discord username (optional)

diacritics

### Describe the bug

On macOS, when the window it resized to the smallest possible size (just the traffic lights with some padding), it hangs after a bit of time (beachball). Fortunately, the window size seems to somewhat fix itself on a force-quit and relaunch. I have seen other issues asking for a minimum window size, but they don't mention this specific issue.

### To reproduce

1. Open Warp on macOS
2. Resize the window to the smallest possible size
3. Wait for a bit

### Expected behavior

It shouldn't hang, or it should set a minimum size

### Screenshots

<img width="190" alt="Screenshot 2023-09-03 at 12 45 10" src="https://github.com/warpdotdev/Warp/assets/62489066/cc61bc4a-e41d-4abd-ba8b-804c904e488e">

### Operating system

MacOS

### Operating system and version

macOS 13.4.1 (c)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.29.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

(I am on Apple Silicon and zsh says it's x86-64, but `file $(which zsh)` shows that it's a universal binary)

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
thanks for catching this. iirc i think we already have an open issue for this, if we do I'll send over the link and close this in favor of that one; but if we don't we'll leave this open

**Comment by dannyneira** [comment]
I'm still having trouble reproducing with or without the shortcuts visible, but we've made some recent improvements for Sonoma compatibility that should be out this week. As a workaround, you can try disabling the shortcuts, it may help with the issue.

https://github.com/warpdotdev/Warp/assets/16809145/88862747-bf46-4dd7-8278-7e0154de6172

**Comment by dannyneira** [comment]
@shreyasm-dev I was able to reproduce the issue, submitting this to the team for review. We'll post any updates on this thread. Thanks for your patience!

**Comment by dannyneira** [comment]
hey folks, this issue has been fixed in the latest version of Warp.

Closing as completed, but please update and let us know if the issue persists.
