### ISSUE TITLE
Input Editor: Prompt: Unsetting PS1 causes shells to be considered non-interactive

### ISSUE THREAD

**Issue by lak** [warpdotdev/warp#363]
### Describe the bug

Yuck this took a long time to track down.

Many shell profiles -- including the one I've been building up over 25 years -- differentiate between interactive and non-interactive shells, so (for instance) they can load less config during non-interactive shells.

Here's the first hit on duckduckgo for how to do this:

https://www.cyberciti.biz/faq/linux-unix-bash-check-interactive-shell/

It recommends using whether `$PS1` is set. And coincidentally, that's exactly what I've been doing forever. (Like, probably since 1999 or so.)

But Warp unsets PS1.

Thus, all of my shells were marked non-interactive, thus causing all of my aliases and functions not to be loaded.

As a workaround, I am doing this test instead:

```
if [ -n "$PS1" -o "$TERM_PROGRAM" = "WarpTerminal" ]; then
  export INTERACTIVE=1
fi
```

*At the least* you need to provide a supported mechanism for differentiating between interactive shells and not.

In truth, though, you should not unset PS1.

Unless there's some widespread, standard way of determining this without relying on PS1?

### To Reproduce

Use this code:
```
if [ -n "$PS1"  ]; then
  export INTERACTIVE=1
fi
echo $INTERACTIVE
```
You'll see that INTERACTIVE is unset.

### Expected behaviour

INTERACTIVE should be set to 1 if I am at a prompt.

### Operating System

MacOS

### OS Version

Darwin jakuta 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

**Comment by zheng** [comment]
One option is to rely on the special parameter $- instead.

https://www.gnu.org/software/bash/manual/html_node/Is-this-Shell-Interactive_003f.html

Unfortunately, Warp needs to unset PS1 for its functionality. We do want to take more vertical control of the configs to clash less with other things and be more clear about the shell environment, but this is a workaround you can use.

**Comment by lak** [comment]
Ah, thank you, I did not know about this. I will try it.
