### ISSUE TITLE
Launch configuration Global Hotkey

### ISSUE THREAD

**Issue by maclong9** [warpdotdev/Warp#3630]
### Describe the solution you'd like?

```Text
I'd like to use Launch Configurations to start my workflow for each application I work on etc. however I tend to run dev servers etc. in the global hotkey, that way I only have to look at them when I need to access them. However launch configurations don't seem to allow you to alter the Global Hotkey, is this something you are able to add?
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by mac-codes9** [comment]
Not quite, say for example I have 3 launch configurations 1 for each project, then I’d like to be able to launch a tab with 3 panes in the working directory of project 1 and then send the dev server to a tab in the quake terminal, that would be one launch configuration, repeat for the other projects
