### ISSUE TITLE
sudo su in ssh shell

### ISSUE THREAD

**Issue by Jan-Wenner** [warpdotdev/Warp#3631]
### Discord username (optional)

janskywalker

### Describe the bug

Commands in after sudo su in an ssh shell were not separated in different blocks.

### To reproduce

1. ssh into server
2. run "sudo su" for root console
3. run every command

### Expected behavior

Every Command in sudo su-mode should be a new block

### Operating system

MacOS

### Operating system and version

MacOS Ventura 13.5.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.29.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by jrome011** [comment]
I just tested this by adding 'sudo su' to added commands, it warpifies as expected but throws me back into the normal user where I did sudo su from.

**Comment by jrome011** [comment]
Thanks for putting that video up @warpdotdev-dx that worked for me.

**Comment by maxpain** [comment]
> it warpifies as expected but throws me back into the normal user where I did sudo su from.

The same problem is even after adding `sudo su` and `sudo -s` to commands, as shown in the video above.

@warpdotdev-dx

**Comment by piellick** [comment]
@maxpain for me too, did you find any solution ?
