### ISSUE TITLE
Window Jumps Up When Activated

### ISSUE THREAD

**Issue by conradwt** [warpdotdev/Warp#3632]
### Discord username (optional)

conradtaylor

### Describe the bug

When I activate a window by clicking it, the window goes up revealing the blinking cursor.  When I click another window, the original window moves down.

### To reproduce

1. Open Warp
2. Command + D
3. Activate the left window
4. Right window shifts down and the left window shifts up

### Expected behavior

When activating a window, I would expect that the other windows wouldn't shift down but maintain their original size as if they were activated.

### Screenshots

![Screenshot 2023-09-04 at 3 07 49 PM](https://github.com/warpdotdev/Warp/assets/20219/90252abe-553b-4e2d-8771-80deb1c29256)

### Operating system

MacOS

### Operating system and version

13.5.1

### Shell Version

5.9 (arm-apple-darwin22.4.0)

### Current Warp version

v0.2023.08.29.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
thanks for opening @conradwt we should have an open issue for this that I'll find and link here!

**Comment by dannyneira** [comment]
Just got word this is ready for Production/Stable build and should be launching next week's release! 🙏
