### ISSUE TITLE
Can't see full display of top command

### ISSUE THREAD

**Issue by xpader** [warpdotdev/Warp#3634]
### Describe the bug

`Block` covered on top output of the top command.

### To reproduce

Just use top command.

### Screenshots

![WX20230905-103129](https://github.com/warpdotdev/Warp/assets/8629617/a9444dbf-87ca-4633-bac2-fda5d05b084c)

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

zsh 5.8

### Current Warp version

v0.2023.08.29.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
@xpader Thanks for opening this. I'm not able to reproduce on my machine could you send me a video with how this happens. I really like Loom if you want a video recorder recommendatino

**Comment by xpader** [comment]
@elviskahoro 
Close "Show stickly command header" in Features setting solved this problem.
