### ISSUE TITLE
Choose where tabs are displayed

### ISSUE THREAD

**Issue by tanel** [warpdotdev/Warp#3635]
### Describe the solution you'd like?

```Text
I have lots of open tabs, in iTerm it was possible to configure that tabs (tab names) will appear on the left, not on top, would it be possible in Warp too?

I didn't find it in the docs or in the Settings.
```

### Additional context

![Screenshot 2023-09-05 at 13 41 31](https://github.com/warpdotdev/Warp/assets/8346/fefa4d3f-43b9-42bf-8b45-e5deadee76e9)

tabs on the left, in iTerm

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by elviskahoro** [comment]
@tanel thanks for opening. we should have an open issue for this already that I'll try to find and then link here

**Comment by dannyneira** [comment]
Thanks for submitting this @tanel 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2155

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
