### ISSUE TITLE
Edit prompt - able to disable warp prompt or shell prompt

### ISSUE THREAD

**Issue by rl1m4** [warpdotdev/Warp#3638]
### Describe the solution you'd like?

```Text
I want to have only one prompt on Warp (similar behaviour as iTerm).
```

### Is your feature request related to a problem? Please describe.

```Text
I am using Warp for a few months. Before I was using iTerm.
Aftter switching to Warp I enjoy it a lot but now I have 2 prompts and this giving me nightmares trying to fix the same.

I am not able to edit prompt and have only one enabled.
```

### Additional context

Warp prompt (with 2):
<img width="1074" alt="Screenshot 2023-09-06 at 5 38 20 pm" src="https://github.com/warpdotdev/Warp/assets/67620335/938266a5-1f54-4ca0-82e6-2ea8881e362f">

iTerm prompt (with only 1 and very clean):
<img width="1117" alt="Screenshot 2023-09-06 at 5 42 33 pm" src="https://github.com/warpdotdev/Warp/assets/67620335/49371b0d-3022-48e8-9abc-7ce2c163ee4d">

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by zachbai** [comment]
Hey @rl1m4 -- agree this is would be super annoying. A couple follow ups --
* What prompt plugin are you using? (look like it might be starship)?
* Which shell + shell version are you using?

**Comment by rl1m4** [comment]
Thanks for looking into it @zachbai 
Im using spaceship. Even if I disabled the same I continue to have zsh and warp prompts (if I enable bash for new sessions on Warp I don't have this problem but bash doesn't give me zsh options, features)

I have iTerm2 3.4.20 (if I uninstall the same the issue continues), Macbook Termal Version 2.13 (447) and Warp v0.2023.09.06.18.09.stable_00.

**Comment by zachbai** [comment]
Hey @rl1m4, I'm able to reproduce with spaceship installed.  My initial guess is that spaceship's manipulation of the prompt breaks some assumption in our prompt rendering logic.

It _does_ appear to be spaceship-specific (I'm able to use other custom prompt plugins like starship and p10k without this issue), so we'll have to look into this further. I'll file an issue on our end to make Warp compatible with spaceship and follow up here with any updates.

Sorry for the inconvenience! As a workaround, you could disable spaceship to continue using zsh without this issue. Alternatively, you could wrap the spaceship integration in your zshrc with a check `$TERM_PROGRAM = 'WarpTerminal'`, which would disable spaceship within Warp but enable it in other terminal emulators like iTerm2.

```
// in your .zshrc
if [ "$TERM_PROGRAM" = "WarpTerminal ]; then
  source "/opt/homebrew/opt/spaceship/spaceship.zsh"
fi
```

**Comment by dannyneira** [comment]
@rl1m4 This is a known issue with the spaceship prompt we have documented here. https://docs.warp.dev/features/prompt#spaceship

This prompt can cause an issue with typeahead in Warp's input editor. Another workaround is to, run `echo "SPACESHIP_PROMPT_ASYNC=FALSE" >>! ~/.zshrc` if you want to continue using the spaceship prompt in Warp.

**Comment by rl1m4** [comment]
Thanks @zachbai and @dannyneira for giving me 3 different workarounds to fix it.

When I tried to disable spaceshipt it didn't work... 🤔 

I decided to use the `"SPACESHIP_PROMPT_ASYNC=FALSE"` set to false so I can continue using spaceship prompt in Warp... the only thing is that is getting a different style and not the full spaceship one (but this is not an issue for me) :)

Warp now:
<img width="1246" alt="Screenshot 2023-09-12 at 5 05 04 pm" src="https://github.com/warpdotdev/Warp/assets/67620335/11749d11-015a-42c5-b7c3-e7ca510a8940">

iTerm:
<img width="531" alt="Screenshot 2023-09-12 at 5 04 30 pm" src="https://github.com/warpdotdev/Warp/assets/67620335/34cb14a0-0ad0-41cc-abd8-bcb4e070405e">

**Comment by rl1m4** [comment]
Btw:  changing warp settings in the shell prompt can fix the style 😅

**Comment by dannyneira** [comment]
@rl1m4 Thanks for letting us know. Our docs cover how to enable a custom prompt in Warp. There are a couple of ways but easy to right-click and edit the prompt. https://docs.warp.dev/features/prompt#how-to-access-it

Hope this helps with your issue! 🤞
