### ISSUE TITLE
Unicode blocks do not render correctly

### ISSUE THREAD

**Issue by indirect** [warpdotdev/Warp#364]
### Describe the bug

Using a text-art program like `ponysay` does not produce the expected "unicode art". I've included an example screenshot of Warp (on the left) and macOS Terminal (on the right)

### To Reproduce

Steps to reproduce:
1. Run `brew install ponysay`
2. Run `ponysay -b unicode hello`

### Expected behaviour

```shell
I expect to see something that looks like a pony saying "hello".
```

### Screenshots

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/78/140598300-bedc2684-3c91-458d-8276-0328b8e8cef8.png">

### Operating System

MacOS

### OS Version

12.0.1

**Comment by elviskahoro** [comment]
lol, Warp's version is like the gothic rendition. Thanks for sharing, will look into it!

**Comment by pwntester** [comment]
![image](https://user-images.githubusercontent.com/125701/145122154-da733933-fa64-4a4d-866f-ec38011d9ae7.png)

This seems to affect neovim rendering as well (see Telescope menus and indent guides)

**Comment by gagata** [comment]
@indirect are you still experiencing this? we've done some adjustments to our minimal contrast logic (sorry, I haven't seen this ticket before, but I did see the ticket related to `doge` so more updates where there :D )

![Screen Shot 2022-05-05 at 4 49 35 PM](https://user-images.githubusercontent.com/1783606/167044775-09cfe280-f18a-49a4-b3db-82888a5a238c.png)

**Comment by indirect** [comment]
Warp looks about on par with Terminal.app to me, thanks for the update!

<img width="883" alt="image" src="https://user-images.githubusercontent.com/78/167215934-1f32798b-ec74-4569-9e17-01f3556d951e.png">

**Comment by indirect** [comment]
(It might be worth investigating the tiny 1-pixel lines between blocks that seem to only happen in Warp, though!)

**Comment by gagata** [comment]
> (It might be worth investigating the tiny 1-pixel lines between blocks that seem to only happen in Warp, though!)

ah yeah, i think it may be related to the line height / some other grid rendering code that we're solving separately. glad the colors now work! :))

**Comment by elviskahoro** [comment]
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">
