### ISSUE TITLE
The prompt created by Warp always seems to have a newline at the end

### ISSUE THREAD

**Issue by pitosalas** [warpdotdev/Warp#3640]
### Describe the solution you'd like?

```Text
I would like to have a prompt that does not have a newline. So the command input is on the same line as the prompt.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by elviskahoro** [comment]
@pitosalas thanks for opening. we should have an open issue for this; I'll link it and close this one. the explanation here is that the Input Editor box is a native GUI element and the prompt is a SEPARATE but also native GUI element.

This is what enables warp to support an IDE-like text editing experience. It also enables us to build a prompt that's interactive, clickable and customizable from within the app

**Comment by elviskahoro** [comment]
We have someone looking into this right now actually. But they just started so don't have much to share yet

**Comment by dannyneira** [comment]
Thanks for submitting this @pitosalas.

We already actually working on this and have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2304

No official ETA on release, but we'll post any updates there, so stay tuned!

We'll be closing this as a duplicate.
