### ISSUE TITLE
There is something wrong with workflows

### ISSUE THREAD

**Issue by BProg** [warpdotdev/Warp#3641]
### Discord username (optional)

i.os.

### Describe the bug

I created following workflow
<img width="497" alt="Screenshot 2023-09-07 at 11 36 45" src="https://github.com/warpdotdev/Warp/assets/11962191/58d03ec0-315b-461a-ac91-0c360705b6d3">

Sometimes, when I use it, there is a git error and the workflow doesn't work. The rebase step fails.
It happens like once in 20 and it's not easy to catch it.
As you can see in the recording, if I do the rebase without running the workflow, it doesn't fail.

### To reproduce

1. Create same workflow (change the name of the main branch to whatever you use)
  a. You can remove last step from the workflow . The one with `pod install`
1. Switch to new branch and do some work
3. Wait for other to push some commits to main branch
4. Run the workflow
5. Workflow fails with following error

```sh
git checkout main
git pull
git checkout -
git rebase -i main

Switched to branch 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
Switched to branch 'CXIOS-10089-display-CC'
Your branch is up to date with 'origin/CXIOS-10089-display-CC'.
error: Your local changes to the following files would be overwritten by checkout:
	Modules/CrunchyrollChromecast/Sources/Screens/Chromecast/ChromecastInteractor.swift
Please commit your changes or stash them before you switch branches.
Aborting
error: could not detach HEAD
```

### Expected behavior

Based on the workflow - following output should be when I don't have conflicts:
```
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
Switched to branch 'CXIOS-10089-display-CC'
Your branch is up to date with 'origin/CXIOS-10089-display-CC'.
Successfully rebased and updated refs/heads/CXIOS-10089-display-CC.
```

### Screenshots

<img width="497" alt="Screenshot 2023-09-07 at 11 36 45" src="https://github.com/warpdotdev/Warp/assets/11962191/58d03ec0-315b-461a-ac91-0c360705b6d3">

[Screen Recording 2023-09-07 at 11.35.03.mov.zip](https://github.com/warpdotdev/Warp/files/12546726/Screen.Recording.2023-09-07.at.11.35.03.mov.zip)

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.29.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by BProg** [comment]
Hi @zachbai! I'll be happy to help you with that once I can reproduce the issue again. However, I believe option a) is the most likely scenario. Even if I run the workflow multiple times, it still fails

**Comment by zachbai** [comment]
Sounds good! Please do follow up on the thread when you manage to reproduce and we can take a look.

**Comment by dannyneira** [comment]
@BProg any further luck with reproduction? what if you run the last two sequentially? For example:
```
git checkout main
git pull
git checkout - ; git rebase -i main
```

**Comment by BProg** [comment]
I think we can close this as I couldn't reproduce anymore
