### ISSUE TITLE
maybe its a ui bug?

### ISSUE THREAD

**Issue by LearnForDreamK** [warpdotdev/Warp#3642]
### Describe the bug

<img width="845" alt="image" src="https://github.com/warpdotdev/Warp/assets/57825143/a38d2770-670a-4654-a934-0ff0b168b92e">
and i cant click button

### To reproduce

<img width="535" alt="image" src="https://github.com/warpdotdev/Warp/assets/57825143/50b73aea-97cd-4eb7-a33b-a548fcb8ef03">

### Operating system

MacOS

### Operating system and version

macos

### Shell Version

ui

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
@LearnForDreamK thanks for opening this. Can you send us a video it will help us debug what exactly is broken

**Comment by LearnForDreamK** [comment]
@elviskahoro 



> @LearnForDreamK thanks for opening this. Can you send us a video it will help us debug what exactly is broken

https://github.com/warpdotdev/Warp/assets/57825143/ac5a57d7-2570-4769-8b16-749bdfa02e63

**Comment by dannyneira** [comment]
@LearnForDreamK We've fixed this issue in the latest version of Warp and will close as resolved, but please let us know if the issue persists.
