### ISSUE TITLE
Open new tab with empty window is broken

### ISSUE THREAD

**Issue by CaptainVincent** [warpdotdev/Warp#3646]
### Describe the bug

Can't create new tab if current no window exist.

### To reproduce

1. When you close all tabs but still not exit app.
2. Press `cmd t`.

### Expected behavior

Show the new (first) tab.

### Operating system

MacOS

### Operating system and version

13.5.1

### Shell Version

zsh

### Current Warp version

v0.2023.09.06.18.09.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Not sure. But it just recently stopped working

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by szgupta** [comment]
Hi @CaptainVincent, sorry about the regression here. While we actively work on a fix, you should be able to use `CMD-N` in the empty-window state to open a new window.

**Comment by CaptainVincent** [comment]
Fixed in version `v0.2023.09.19.08.04.stable_00`
