### ISSUE TITLE
warpify poetry shell locks up terminal

### ISSUE THREAD

**Issue by adam006** [warpdotdev/Warp#3651]
### Describe the bug

when using the `warpify` option for poetry shell the terminal locks up and must be closed and re opened

### To reproduce

use existing or create new poetry project
execute `poetry shell`
click `warpify subshell`
observe the issue

### Expected behavior

the terminal is warpified for the poetry shell session

### Screenshots

![Screenshot 2023-09-11 at 9 14 59 AM](https://github.com/warpdotdev/Warp/assets/6125814/40f08335-107a-4dcd-8673-0dbd00c43209)

### Operating system

MacOS

### Operating system and version

13.3.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.09.06.18.09.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by adam006** [comment]
looks like a bug has been reported already

**Comment by alanwill** [comment]
For anyone running into this issue, the main issue that this duplicates is https://github.com/warpdotdev/Warp/issues/3105
