### ISSUE TITLE
[Feature Request] Collapsable blocks

### ISSUE THREAD

**Issue by karthik-js** [warpdotdev/Warp#3657]
### Describe the solution you'd like?

```Text
What you guys have built is fantastic, separating each command into its own block. I love it and I use it daily. The more convenient feature for me is to collapse the block so that I can expand it when I want to see the total output. With this, it can help me scroll less.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by ADTC** [comment]
@karthik-js just a side note, suggest you to not use a code block for your text. It makes the text become **horizontally scrollable** and monospaced, thus hard to read.

<img width="822" alt="image" src="https://github.com/warpdotdev/Warp/assets/6047296/f7504425-03d9-48b7-bf3e-9d42ba8f0527">


Just use normal text without any decorations.
