### ISSUE TITLE
Scroll Bar Missing - Settings Window content is hidden in warp terminal 

### ISSUE THREAD

**Issue by osikes** [warpdotdev/Warp#366]
### Describe the bug

```shell
If the warp terminal window's height isn't tall enough, part of the Settings window will be hidden and not scrollable. Only way to then access the remaining Settings window is to increase height of underlying warp terminal window.
```

### To Reproduce

Steps to reproduce:
1. Open up Warp terminal on a laptop with warp terminal height likely less then half the laptop screen's height.
2. Launch the Settings window
3. Notice that some of the content on settings window is cut off by the bottom of the warp terminal.

### Expected behaviour

```shell
I would expect the Settings window to either appear outside of the parent terminal window OR I would expect the Setting's window to be scrollable.
```

### Screenshots

<img width="1097" alt="Screen Shot 2021-11-06 at 9 50 09 AM" src="https://user-images.githubusercontent.com/955081/140613821-95e69644-5b0d-4119-b197-09fa3b85813f.png">

### Operating System

MacOS

### OS Version

12.0.1

**Comment by aycanirican** [comment]
I spot the same problem. It's not an urgent thing since I can resize the window and access all the settings. Definitely low priority for me.

**Comment by elviskahoro** [comment]
This is marked as high priority internally. No ETA on when it'll get done though.

**Comment by vorporeal** [comment]
Closing this out, as the settings pane is now responsive to window size.  There are further improvements we can make, but I believe the core UX issue here is now resolved.

**Comment by osikes** [comment]
Huzzah! Thank you.
