### ISSUE TITLE
Everytime I update warp, the workflows are reset. Really annoying.

### ISSUE THREAD

**Issue by jo32** [warpdotdev/Warp#3667]
### Describe the bug

Everytime I update warp, the workflows are reset. Really annoying.

### To reproduce

update warp

### Operating system

MacOS

### Operating system and version

13.2.1

### Current Warp version

v0.2023.09.12.16.17.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
@jo32 can u send a video

**Comment by kevinyang372** [comment]
Hi @jo32, Warp engineer here. Thanks for filing this issue! We are having trouble repro-ing on our end. Would you be open to share more info on this issue to help us understand the root cause? If so, please email me at kevin@warp.dev
