### ISSUE TITLE
Different text colors on the same background color

### ISSUE THREAD

**Issue by diploidal** [warpdotdev/Warp#3669]
### Describe the bug

I was adding a new folder and a workflow when I've noticed that the same accent color for CTA buttons have different colors. 

I think screenshots are self explanatory. 😃

### To reproduce

1. Go to Warp Drive.
2. Create new folder.
3. Type folder name and check the color of CTA button with `Create` text.
4. Create new workflow and type in any text and check CTA button with `Save workflow` text.

### Expected behavior

I'm not sure how it works but both of those text should've rendered as the same color based on contrast result so the text is readable. In this case it should be dark. 

### Screenshots

<img width="469" alt="SCR-20230915-sfan" src="https://github.com/warpdotdev/Warp/assets/9194893/0c5ca5e8-0f6e-4a92-ada1-2512d8bb584e">
<img width="921" alt="SCR-20230915-sewd" src="https://github.com/warpdotdev/Warp/assets/9194893/526956ba-61ea-4ed3-8a88-2f934ccb77bd">

### Operating system

MacOS

### Operating system and version

MacOS Ventura 13.5.2

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @diploidal We've updated the colors in the latest version of Warp to better contrast with the themes. Closing as resolved, but please update and feel free to let us know if the issue persists.
