### ISSUE TITLE
Prompt Time: support 24 hour format pls

### ISSUE THREAD

**Issue by yam-liu** [warpdotdev/Warp#3673]
### Describe the solution you'd like?

```Text
Please support 24-hour format of Time component when customizing Prompt.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by yam-liu** [comment]
Does starship support blocks in Warp?

**Comment by dannyneira** [comment]
This is being worked on, no eta on release, but we'll update this thread with any changes:

Demo below:
![CleanShot 2023-10-03 at 11 20 07](https://github.com/warpdotdev/Warp/assets/16809145/49133a2b-0355-447a-b728-0e1c1c0476ba)

**Comment by dannyneira** [comment]
Hi Folks, this feature has been added to Warp. Closing as resolved, but please let us know of any issues.
