### ISSUE TITLE
channel 22: open failed: connect failed: open failed

### ISSUE THREAD

**Issue by williamnie** [warpdotdev/Warp#3679]
### Describe the bug

channel 22: open failed: connect failed: open failed
channel 24: open failed: connect failed: open failed
channel 26: open failed: connect failed: open failed
channel 3: open failed: connect failed: open failed
channel 6: open failed: connect failed: open failed
channel 11: open failed: connect failed: open failed
channel 5: open failed: connect failed: open failed
channel 31: open failed: connect failed: open failed
channel 33: open failed: connect failed: open failed
channel 35: open failed: connect failed: open failed
channel 37: open failed: connect failed: open failed
channel 39: open failed: connect failed: open failed
channel 41: open failed: connect failed: open failed

warp version: v0.2023.09.12.16.17.stable_00
When operating from ssh to the server, the above errors are often reported, but it does not affect the use of ssh.

### To reproduce

no

### Operating system

MacOS

### Operating system and version

13.2.1

### Shell Version

5.1.16

### Current Warp version

v0.2023.09.12.16.17.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by qwaldo** [comment]
Hello!

I have the same problem:

```
channel 12: open failed: connect failed: open failed
channel 12: open failed: connect failed: open failed
channel 12: open failed: connect failed: open failed
channel 12: open failed: connect failed: open failed
channel 12: open failed: connect failed: open failed
channel 12: open failed: connect failed: open failed
channel 12: open failed: connect failed: open failed
channel 12: open failed: connect failed: open failed
channel 12: open failed: connect failed: open failed
channel 14: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
channel 21: open failed: connect failed: open failed
```

**Comment by hanggoro-litbang** [comment]
I have the same problem

**Comment by smyja** [comment]
same issue

**Comment by itartyom** [comment]
same error, I have a weak internet connection

**Comment by XenoUniv3rse** [comment]
was there ever a fix for this? I see its closed
