### ISSUE TITLE
vim doesn't render any cursor

### ISSUE THREAD

**Issue by madisp** [warpdotdev/warp#368]
### Describe the bug

```shell
For some reason I don't see any cursor when using `vim`. While it's a nice throwback to only navigate using the `line:col` output in the status bar it's a bit too much these days.

The issue disappears when I disable the use of my `vim` theme - [vividchalk](https://github.com/tpope/vim-vividchalk).

Screenshot from both iterm2 and warp attached.
```

### To Reproduce

1. Install `vim`
2. Configure the [vividchalk](https://github.com/tpope/vim-vividchalk) colortheme for vim
3. edit something with `vim`

### Expected behaviour

```shell
Vim cursor is visible, enabling easy navigation.
```

### Screenshots

warp:

<img width="639" alt="Screen Shot 2021-11-06 at 20 18 50" src="https://user-images.githubusercontent.com/1147723/140619841-1c6b549a-a382-4434-a9ee-a855935cd0b6.png">

iterm:

<img width="602" alt="Screen Shot 2021-11-06 at 20 17 58" src="https://user-images.githubusercontent.com/1147723/140619814-e4639db0-27c5-465d-ae43-9e5b96cba397.png">

### Operating System

MacOS

### OS Version

11.6.1

**Comment by elviskahoro** [comment]
#451
