### ISSUE TITLE
shell lsp and rust lsp

### ISSUE THREAD

**Issue by sablokgaurav** [warpdotdev/Warp#3682]
### Describe the solution you'd like?

```Text
The warp is awesome, and most importantly it focuses on what should be done rather than a theme terminal. I would like to request that if we can integrate the rust lsp and shell lsp with offline support then it will make the warp community bigger as that will provide support for the devops, cluster computing and at the same time rust based. Many terminals have the support for the same such as neovim and others, so if we can integrate this in warp then it will be awesome. 
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by sablokgaurav** [comment]
This will really help the people using the rust at the server side. Some people also want to have that as offline as they like to be concentrated, so a package with in build it like the package add shell language complete, rust language complete, and others if you want that would be awesome.

**Comment by sablokgaurav** [comment]
Really how to use it?. let me know

**Comment by dannyneira** [comment]
Warp supports bash/zsh/fish completions out of the box as well as `neovim` so you can try using that as a workaround.

**Comment by sablokgaurav** [comment]
Thank you and i used that also.
