### ISSUE TITLE
Can I suppress the grey "Type # for ai suggestions" line?

### ISSUE THREAD

**Issue by pitosalas** [warpdotdev/Warp#3688]
### Discord username (optional)

pitosalas#1234

### Describe the solution you'd like?

```Text
Can I suppress the grey "Type # for ai suggestions" line?
```

### Is your feature request related to a problem? Please describe.

```Text
Your UI has so much going on that the overall effect is that I don't like it. I want options to simplify it to look almost identical to iterm2
```

### Additional context

x

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

Ignore

**Comment by dannyneira** [comment]
Hey @pitosalas

Those are [input hints](https://docs.warp.dev/features/editor#input-hints) meant to help with the discovery of features, but can be disabled in the settings menu. Disable "Show Input hint text" in Settings > Features > Editor or search for "input hint text" in the Command Palette `CMD-P` or Right-click on the input editor.

Hope this helps! Closing as completed, but please let me know if any issues with the setting.
