### ISSUE TITLE
Alternative icon

### ISSUE THREAD

**Issue by chrisrowe** [warpdotdev/Warp#3693]
### Describe the solution you'd like?

```Text
I'd love to see alternative icons, or at least a different background color. In dark mode the dock background and icon background wash together.

I've updated the icon from https://macosicons.com/#/warp a few times but it reverts after each update.

![](https://up.chri.sr/Screen-Shot-2023-09-22-09-45-14.27-1695372319.png)
```
![](https://up.chri.sr/Screen-Shot-2023-09-22-09-45-14.27-1695372319.png)

### Is your feature request related to a problem? Please describe.

```Text
Icon
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @chrisrowe Thanks for the feedback. The icon issue can certainly be improved.

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/1865

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by neilcitruslime** [comment]
The new white icon is similar to many other apps can we have a way of using the old (or configurable) icon so I can find Warp quickly when I'm command tabbing thru applications.
