### ISSUE TITLE
Unable to save workflow when argument value has too many lines

### ISSUE THREAD

**Issue by ryenus** [warpdotdev/Warp#3694]
### Describe the bug

Inside the workflow edit dialog, the height of the text input boxes would automatically grow when the text can't fill in one line, so does the workflow edit dialog.

For most of the time this is a nice feature, but when the overall height becomes more than what can be shown in the screen, the bottom part of the workflow edit dialog, more specifically all the 3 buttons would be pushed offscreen (New argument / Autofill / Save workflow), then it's no longer possible to save the workflow.

### To reproduce

1. open the Warp Drive panel
2. + New workflow
3. + New argument
4. in "Default value" field, paste some text with 100+ lines
5. note the buttons at the bottom got pushed down offscreen, causing one not able to save the workflow

### Expected behavior

the buttons at the bottom of the workflow edit dialog should be always visible.

I noted when the workflow script has more lines than what can be accommodated, a scrollbar would be added to limit the height, the same should be considered also for the arguments.

Meanwhile when closing the workflow edit dialog with unsaved changes, it only offers two options, "Keep editing" and "Discard changes", it should also allow the user to save the changes.

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/610161/16063cc8-6416-4092-bc0a-54ae39fc85fa)

### Operating system

MacOS

### Operating system and version

13.6

### Current Warp version

v0.2023.09.19.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @ryenus Thanks for letting us know, I was able to replicate this issue and will let the team know. 

As a possible workaround, I recommend you turn that long command list into a script with parameters as a workaround. That should make it easier to deal with a longer set list of commands.

<details>
<summary><b>Example of a shell script that accepts parameters when running it.</b></summary>
script
```bash
#!/bin/bash

# Access the parameters using $1, $2, $3, etc.
echo "The first parameter is: $1"
echo "The second parameter is: $2"
echo "The third parameter is: $3"
```
command
```bash
./script.sh parameter1 parameter2 parameter3
**```**
</details>

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Hey @ryenus This issue has been resolved in the latest version of Warp. Please update and let us know if the issues persist.

Closing as completed.

**Comment by ryenus** [comment]
@dannyneira confirmed that the layout issue has been fixed, thanks!

> Meanwhile when closing the workflow edit dialog with unsaved changes, it only offers two options, "Keep editing" and "Discard changes", it should also allow the user to save the changes.

BTW, I assume this part was missed on purpose? It would save a few clicks though.

**Comment by dannyneira** [comment]
Yes, since you can "keep editing" then "Save" there is already a solution/workaround for that. So we fixed the bug with the lines.
