### ISSUE TITLE
Dock Place Change After Update

### ISSUE THREAD

**Issue by sineld** [warpdotdev/Warp#3696]
### Discord username (optional)

sineld

### Describe the bug

I update the app just after it warns me for the new update. I've placed Warp in the Dock right to my IDE. When I press update button, previous Dock record for Wap stays the same, it adds a new instance to Dock. Please solve this.

### To reproduce

Add app dock, eg. as 4th app
Click update
Check previous place

### Operating system

MacOS

### Operating system and version

Ventura 13.5.2

### Current Warp version

Always Latest

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by chambliss** [comment]
![Google Chrome-2023-09-22 at 10 32 12AM](https://github.com/warpdotdev/Warp/assets/43484165/6a7568db-b338-4d12-b02c-0af47fa5c38a)

I'm also experiencing this. (Ignore the custom icons and such, this was happening before I started doing any icon customization and so is unrelated)

**Comment by dannyneira** [comment]
Thanks for letting us know @sineld 

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/1535 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue.

We'll be closing this as a duplicate.
