### ISSUE TITLE
Warp prompt doesn't show pyenv virtual environment for `pyenv local` environments

### ISSUE THREAD

**Issue by cadolphs** [warpdotdev/Warp#3697]
### Describe the bug

My warp prompt (just the default one) in zsh (no other fancy zsh stuff present) does _not_ show the current virtual environment for pyenv environments that get activated via the `pyenv local` command.

### To reproduce

1. Create a virtual environment with pyenv: `pyenv virtualenv 3.11 some_environ`
2. In the current directory, tell `pyenv` to use that new virtual environment: `pyenv local some_environ`
3. Navigate out of that directory, `cd ~` and then navigate back in `cd that/dir/you/ran/pyenv/local/in`
4. Confirm via `pyenv which python` that the correct virtualenv has been activated

### Expected behavior

After following the above steps, the Warp prompt should list `some_environ` as the virtual environment. But it doesn't.

When _manually_ activating the environment by calling `source /Users/username/.pyenv/versions/some_environ/bin/activate`, the Warp prompt gets correctly set.

### Operating system

MacOS

### Operating system and version

Ventura 13.5.2

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.09.19.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

I installed it fresh yesterday, so I don't know.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @cadolphs Sorry about this issue with the default prompt, I'm seeing the same on my end as well. As a workaround, I recommend you try a support custom prompt (I'm using starship.rs in my example ) as they will be able to correctly show the 'pyenv` information in the prompt. You need to also make sure the correct init lines are in your `~/.zshrc` file (run `pyenv init` for instructions).

![CleanShot 2023-09-25 at 10 59 10]\(https://github.com/warpdotdev/Warp/assets/16809145/2779bbc4-0c31-4fd1-a67f-2200d0855a13)

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by cadolphs** [comment]
Good point about adding the correct pyenv lines to `.zshrc`. I had done that already but didn't mention it in the original issue report:

```
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

**Comment by mikeharding** [comment]
Same behavior on my end.

**Comment by danielpeng2** [comment]
Hi, seems like this is happening because by default, pyenv doesn't set `$VIRTUAL_ENV` on [auto-activating a virtual environment](https://github.com/pyenv/pyenv-virtualenv/issues/348), which Warp uses to determine the name of the current virtual environment.

Running `echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.zshrc` (step 2 under [Installing as a pyenv plugin](https://github.com/pyenv/pyenv-virtualenv#installing-as-a-pyenv-plugin)) fixes this for me. Can you try that and see if it works?

**Comment by danielpeng2** [comment]
Going to close out this issue. Feel free to reopen if anyone is still encountering this problem!
