### ISSUE TITLE
Tabs in sidebar

### ISSUE THREAD

**Issue by ksr-13** [warpdotdev/Warp#3699]
### Describe the solution you'd like?

```Text
iTerm2 like tabs in sidebar.
```

### Is your feature request related to a problem? Please describe.

```Text
Too many tabs are open, can't tell which tab is for what as all of them are squished together.
```

### Additional context

iTerm2 has a feature where tab title bar with close x button can be shown on the left / right hand side in a long list allowing for a user to see a lot more tab details.

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @ksr-13 Thanks for submitting. We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2155

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
