### ISSUE TITLE
Tab pane covers first line of command output

### ISSUE THREAD

**Issue by kendallm** [warpdotdev/warp#37]
**Describe the bug**
The window offset for the top of the window covers the first line of text. This isn't usually an issue using the Warp as normal, but attaching to a tmux session in a remote terminal this creates a bit of a UX issue. See attached screenshot.

**To Reproduce**
1. Create a tmux session in another terminal window
2. In warp, type `tmux attach -d`
3. See screenshot below 

**Expected behavior**
I would expect the viewport for terminal window not be obstructed by the tab bar. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1841529/126399030-79d55f05-f505-4881-9f27-7b4a814f744d.png)
* See top tmux pane. It is covered by the tab bar.
**Desktop (please complete the following information):**
 - MacOS 11.4

**Additional context**
This seems like it may only be an issue when you are not using the native Warp experience and are using a remote session

**Comment by elviskahoro** [comment]
Something similar was happening to me in vim, but not sure if it is for the same reason as this.

**Comment by elviskahoro** [comment]
Moved to discussion
