### ISSUE TITLE
PG+UP / PG+DOWN for scrolling the block view

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/warp#370]
### Describe the solution you'd like?

```shell
I'd like to be able to scroll the window and block view using pg. up / down.
```

### Is your feature request related to a problem? Please describe.

```shell
N/A
```

### Additional context

N/A

**Comment by thomasheartman** [comment]
I'd like this too 🙋🏾  I was looking for a way to scroll the window / a block with the keyboard but couldn't find anything. 

My particular use case was a command with output that's longer than the screen height. It doesn't seem like I can navigate inside the output block with the keyboard.

**Question**: are there key bindings for doing this as it stands today? 


If not, I'd also like to suggest keybindings that are easily accessible from most laptop keyboards (that might not have pg. up/down. Something like `ctrl+u`/`ctrl+d` (vim) and or `space`/`shift+space` (browsers).
