### ISSUE TITLE
Block output size truncates and does not appear to be configurable

### ISSUE THREAD

**Issue by bcarroll-edb** [warpdotdev/Warp#3702]
### Describe the bug

Block output stream truncates at a certain amount and does not appear to be configurable. While running scripts in a block with large amounts of output, the output stream is truncated from the beginning at a certain size.  

### To reproduce

1. create new block.
2. running a script to create large output stream i.e. > 16 meg approximately.
3. Review block output to see top of output stream is truncated at some point.

### Expected behavior

Make Block output size configurable or at least create a warning message. 

### Operating system

MacOS

### Operating system and version

macOS 13.6 (22G120)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.09.19.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @bcarroll-edb. This has been something that we've done some work on, but it is still in progress as it introduced some memory consumption and performance issues.

We already have a request tracking this over at #610, If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We appreciate your patience as we try and resolve the issue. We'll be closing this as a duplicate.
