### ISSUE TITLE
Autosuggest shortcut no longer working

### ISSUE THREAD

**Issue by apolzon** [warpdotdev/Warp#3704]
### Describe the bug

The latest update (v0.2023.09.19.08.04.stable_00) broke the "Accept autosuggest" command keybinding. I'm unsure what version exactly I upgraded from but I most likely updated previously about a week ago.

I use the "tab key opens autocompletion menu" mode, and had cmd+enter bound for accept autosuggestions (which, if I understand the terminology correctly, is the gray text that appears inline while typing). Both autocomplete and autosuggest were working properly prior to this update.
After updating, when I noticed cmd+enter was not working properly, I checked my keybindings and it had been reset. I updated the keybinding, saved, but the only way I can currently get it to use the autosuggestion is by hitting the right arrow key. I also restarted Warp and double-checked that my keybinding had saved.

### To reproduce

* Change tab key behavior to "Open completions menu"
* Set accepts autosuggestions keybind to cmd+enter
* Start typing a previously used command, when gray text appears, hit cmd+enter but nothing will happen

### Expected behavior

Hitting cmd+enter when autosuggestion is present should accept the command

### Operating system

MacOS

### Operating system and version

osx 13.5.2

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.09.19.08.04.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

9/18/2023 (most likely)

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by Chuck-Koverse** [comment]
Same experience for me.  Autocompletion quit working (v0.2023.09.19.08.04.stable_00)

**Comment by dannyneira** [comment]
Hi @apolzon and @Chuck-Koverse Thanks for letting us know. I've been able to replicate the issue with the settings for TAB behavior resetting on the update to Warp. I'll let the team know and we'll post any updates on this thread.

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by apolzon** [comment]
I can confirm that the latest warp update resolved this issue. Thanks for the quick fix!
