### ISSUE TITLE
Warp is blocking terminal shortcuts

### ISSUE THREAD

**Issue by rogerkerse** [warpdotdev/Warp#3705]
### Describe the bug

I have terminal application that triggers to certain shortcut. In MacOS Terminal the shortcut works, in Warp it doesn't. I also removed any conflicting shortcut from Warp settings and still nothing.

### To reproduce

1. Install https://github.com/TheR1D/shell_gpt
2. Enable shell integration https://github.com/TheR1D/shell_gpt
3. Remove CTRL+L shortcut from Warp settings
4. Try with Terminal and Warp in comparison:
    1. Type `what is sun mass`
    2. Press CTRL+L
    3. It should replace input text with an answer. (**In Warp it doesn't**)

### Expected behavior

Same shortcuts should work as in Terminal if they are set in .zshrc

### Operating system

MacOS

### Operating system and version

MacOS 14.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2023.09.19.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @rogerkerse Thanks for letting us know about the issues with sgpt. I was able to install the integration and noticed it makes use of `bindkey` for the shortcut. Unfortunately, bindkey isn't supported in Warp at this time.

![CleanShot 2023-09-26 at 10 03 06](https://github.com/warpdotdev/Warp/assets/16809145/80974331-aa66-4dcf-8d46-7e75de451c1b)

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/537 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue.

We'll be closing this as a duplicate.
