### ISSUE TITLE
Quick action button 

### ISSUE THREAD

**Issue by B1gG** [warpdotdev/Warp#3707]
### Describe the solution you'd like?

```Text
The idea will be to have some way to create quick actions like ssh connections or running a program or an script with the click of a button. This button can appear in a palette on a side or like an overlay at the top of the prompt section.
```

### Is your feature request related to a problem? Please describe.

```Text
I would love to have a way to execute some commands with click of a button
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request @B1gG!

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by zachlloyd** [comment]
Have you tried our workflows feature for this? https://docs.warp.dev/features/warp-drive/workflows

**Comment by dannyneira** [comment]
@B1gG any luck with the workflow feature mentioned above? They have no quick buttons, but you can easily access workflows from the [Command Palette](https://docs.warp.dev/features/command-palette) or [Command Search](https://docs.warp.dev/features/entry/command-search).
