### ISSUE TITLE
Other: "Seems like your shell is taking a while to start..." every time

### ISSUE THREAD

**Issue by brianduff** [warpdotdev/warp#371]
### Describe the bug

```shell
I always see the "Seems like your shell is taking a while to start..." message at the top of the terminal, and "Starting ksh..." at the bottom. I don't think it's affecting my use of the terminal (I can still type commands while it says "Starting ksh...", but it doesn't seem like this is WAI?
```

### To Reproduce

Start Warp.

### Expected behaviour

```shell
I wouldn't expect this to appear every time I open a tab, and if it is taking longer to start than expected, I'd expect somewhere I can go to see logs or other information about why (More Info takes me to a generic help page).
```

### Screenshots

<img width="823" alt="Screen Shot 2021-11-06 at 5 03 29 PM" src="https://user-images.githubusercontent.com/401512/140627369-bca9109b-3c7f-4ae0-b98a-6f60a8322fdd.png">

### Operating System

MacOS

### OS Version

11.6.1

**Comment by brianduff** [comment]
It looks like something in my company's standard .zlogin is causing this - when I mv .zlogin .zlogin-bak, the problem goes away. However, other terminals don't seem to get stuck this way...

**Comment by elviskahoro** [comment]
You can use something similar to this to control what runs for Warp vs other terminals:

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
    source ~/.config/powerlevel10k/powerlevel10k.zsh-theme
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
    (( ! ${+functions[p10k]} )) || p10k finalize
fi

**Comment by lxy-yz** [comment]
Had the same issue when using fish as default shell. Error gone after changed to zsh in setting. Not sure why.
