### ISSUE TITLE
Scripts with spaces in their pathnames won't run 

### ISSUE THREAD

**Issue by RWCoding58** [warpdotdev/Warp#3710]
### Discord username (optional)

justaping

### Describe the bug

Scripts (e.g. shell scripts or Python scripts) with spacing in their names/pathnames will show a "no such file or directory" zsh error due to Warp not treating the whole pathname as a singular string, instead cutting off where there is a space. I know that Warp doesn't exactly support running scripts (I have to manually select to open in Warp, which isn't a "recommended app"). Still, I thought it would be nice to find a way to circumvent this error since it can run scripts perfectly otherwise. Adding quotation marks around the pathname allows the script to be run properly, so there could be some way to automatically add them when opening a file in Warp.

### To reproduce

1. Create a shell script with a space in its name.
2. Open it in Warp (you have to select Open With -> Other..., select "All Applications", then select Warp).
3. Error pops up

### Expected behavior

The script would run.

### Screenshots

![Screenshot 2023-09-27 at 18 31 20@2x](https://github.com/warpdotdev/Warp/assets/87898490/5de0ddfa-34c5-4d55-a1db-f2657ccf9328)

### Operating system

MacOS

### Operating system and version

14.0 (23A344)

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Current Warp version

v0.2023.09.19.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
@RWCoding58 Thanks for submitting, sorry about this issue. I was able to reproduce this and noticed it's working fine in other terminals. I'll bring this up with the team working on this feature and we'll post any updates on this thread.

**Comment by dannyneira** [comment]
Hi @RWCoding58 Marking this as resolved, please update to the latest Warp and let us know if you still seeing the issue.

**Comment by RWCoding58** [comment]
It started working for me a few days ago, but I forgot to reply here. Thanks!

**Comment by mah3uz** [comment]
Hey, I am using `v0.2024.01.30.16.52.stable_01` but I fetching the same issue.
