### ISSUE TITLE
Git merge with Vim not accepting keystroke input and get stuck

### ISSUE THREAD

**Issue by hagay3** [warpdotdev/Warp#3712]
### Describe the bug

After merging twice, the 2nd merge in git displays an error that the swap file exists and asks me if I want to overwrite the file.
Then I get stuck in Vim and I cant type anything.

### To reproduce

git checkout -b test2
..add some code...
git checkout master
git checkout -b test3
..edit the same code for conflicts...
git merge test2
..CONFLICT...
..RESOLVE..
git checkout master
git checkout -b test4
..edit the same code for conflicts...
git checkout test3
git merge test4

Then you will get the screen with swap file ...

### Expected behavior

Be able to use my keyboard when Vim showing me the conflict screen.

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/13578121/60a08dce-c455-4601-9872-866c619f6c55)

### Operating system

MacOS

### Operating system and version

Ventura 13.5

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.09.19.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @hagay3 Sorry to hear about this blocker, I wasn't able to reproduce it on my end, but I'll let the team working on this know and we'll post updates on this thread.

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by hagay3** [comment]
Hi @dannyneira 
Thanks for your reply 
Can you try create dummy swap file and then merge?
I think what happened is that i couldnt exit from the first merge
So i had to close warp
Then when i tried to merge i stuck with the second merge inside Vim

**Comment by dannyneira** [comment]
Oh I see, the first merge vim was closed while the process was still running, so when you reopened the vim, there is an existing .swp file. This isn't a problem with Warp specifically, just with closing vim while it has a file open. 

This happens only when the file you were trying to edit is not saved completely onto the disk. vi/vim creates a .swp file whenever a file is opened in vi/vim. Every time a file is opened in vi/vim, vi/vim checks for this file, and if found this warning pops up. This can be avoided in two ways:

1. One by deleting the .swp file which is named as "path/of/the/file/you/were/editing/.your_file_name.swp" *please note this may lead to loss of the changes you made before quitting Warp*
2. You can also opt for Recover mode of vi/vim when opening the file and pressing the recovery option.

I hope this helps clear up your concerns. Closing as this isn't an issue with Warp, just with closing vim while file/merge is open.
