### ISSUE TITLE
Key binding to activate previously opened tab

### ISSUE THREAD

**Issue by jmewes** [warpdotdev/Warp#3714]
### Describe the solution you'd like?

There is already a "Activate Previous Tab" key binding which activates the tab with the decremented index number.

Similarly, I would like to have a keybinding to activate the **previously opened tab**.

Here is an example workflow for this feature:

- There are five open tabs
- I am working on something in tab no.2
- I create a new tab (no.6) where I start a server
- When I press Ctrl+TAB, I am immediately back in the previously opened tab (tab no.2)

### Is your feature request related to a problem? Please describe.

Without this feature I have to switch my attention from the actual work to finding and navigating to the previously used tab. This happens multiple times a day and feels like a unnecessary distraction.

### Additional context

**iterm2**

The described behavior can be found in iterm2 under the "Cycle Tabs Forward" key binding.

**IntelliJ**

The described behavior can be found in IntelliJ under the "Switcher" key binding.

**VS Code**

The described behavior can be found in VS Code under the "workbench.action.quickOpenNavigateNextInEditorPicker" key binding.

**Firefox**

The described behavior can be activated in Firefox in the following settings option:

> Ctrl+Tab cycles through tabs in recently used order

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Appreciate your opening this request @jmewes

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified
