### ISSUE TITLE
Settings "font" list does not show all fonts

### ISSUE THREAD

**Issue by dimitrilw** [warpdotdev/Warp#3715]
### Describe the bug

In Warp's Settings > Appearance pane, scrolled down to the Text section, I have checked to see all system fonts:

<img width="272" alt="image" src="https://github.com/warpdotdev/Warp/assets/5898931/b6c57ed7-a20e-431c-a8f1-99f8066ad409">

However, when viewing them, many fonts are missing. For example, here are the fonts starting with "R", per Warp:

<img width="271" alt="image" src="https://github.com/warpdotdev/Warp/assets/5898931/c096aa54-e263-4bec-baf9-b57b47cb18a0">

...only Rockwell.

Meanwhile, my true fonts:

<img width="308" alt="image" src="https://github.com/warpdotdev/Warp/assets/5898931/a12f4104-5dd5-42f3-b314-c09edc4710aa">

The result is that I do not see any of my nerd-fonts listed in Warp's font listing. Some terminal tools that I use rely on having a nerd-font/powerline-font/awesome-font selected so that various symbols are available.

For your reference, that list of fonts that shows *more* than just Rockwell was taken inside the Mac Terminal app. For completeness, here's the top-listed fonts in iTerm's font selector; you can see additional fonts listed that Warp did not offer for me to select.

<img width="219" alt="image" src="https://github.com/warpdotdev/Warp/assets/5898931/5c0e083d-7fc3-4384-aade-37411bdc19c0">

### To reproduce

Settings, Appearance, Text, check "see all", scroll list.

### Expected behavior

I would like to see my nerd fonts.

### Operating system

MacOS

### Operating system and version

Sonoma 14.0, current as of this post

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2023.09.26.08.09.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

not sure; first time I've observed

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dimitrilw** [comment]
I should not have used the "R" fonts; rather I should have ref'd the hack-nerd-font. I rather like Warp's default font (hack) and have installed the hack-nerd-font via Homebrew:

<img width="274" alt="image" src="https://github.com/warpdotdev/Warp/assets/5898931/721fd02c-46d1-4baf-83e5-b2a4b8faefd3">

I would really like to use that font so that nerd symbols are available to terminal tools that use them. Folder icons. Git icons. Etc.

**Comment by elviskahoro** [comment]
@dimitrilw Gonna send over a related issue for font ligatures to subscribe to.

**Comment by dimitrilw** [comment]
Thank you, @elviskahoro . I'll mark this ticket closed when I know which ticket to subscribe to.

**Comment by elviskahoro** [comment]
@dimitrilw https://github.com/warpdotdev/Warp/issues/1377

**Comment by ephes** [comment]
I also ran into this and just needed to restart warp after installing nerdfonts via homebrew. Maybe it's that simple :).

**Comment by aadilayub** [comment]
I'm running into the same issue. I installed "IBM Plex Mono" on macOS, restarted Warp, and can't find the font in the dropdown for choosing the agent mode font.
