### ISSUE TITLE
Switch to previous/next stab shortcuts is not working 

### ISSUE THREAD

**Issue by ap00rv** [warpdotdev/Warp#3717]
### Describe the bug

I configured Ctrl + option + left/right arrow as shortcut to move between previous/next tab but it is not working. 

### To reproduce

1. Ctrl + option + left/right arrow as shortcut to move between previous/next tab
2. Observe that it does not work

### Operating system

MacOS

### Operating system and version

13.6.0

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.09.26.08.09.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @ap00rv `CTRL-OPT-LEFT/RIGHT` is the default for moving back/forward one subword, so make sure you clear those keybinds so they don't conflict with your new tab keybind.

![CleanShot 2023-10-02 at 10 52 06](https://github.com/warpdotdev/Warp/assets/16809145/f0ea47da-9a94-4a27-92a3-d5ade619e498)

Hope this helps, please let us know if the issue persists once you clear the conflict.

**Comment by ap00rv** [comment]
I cleared the subword shortcut and now its working. Thanks and sorry for the trouble.
