### ISSUE TITLE
Please, support cyrillic symbols over SSH

### ISSUE THREAD

**Issue by sandzhaj** [warpdotdev/Warp#3718]
### Discord username (optional)

Sandzhaj

### Operating System

MacOS

### Operating System and Version

Sonoma

### Local Shell Version

5.9

### Remote Shell Version

4.4.20(1)-release

### Warp Version

v0.2023.09.26.08.09.stable_00

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

<img width="1097" alt="image" src="https://github.com/warpdotdev/Warp/assets/13132782/4bddaac5-4c1f-471c-a9a5-28c9564a0009">

### Include shell xtrace output

No output 
<img width="525" alt="image" src="https://github.com/warpdotdev/Warp/assets/13132782/c56621f5-9751-4417-8895-1245bb820ce9">

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
@sandzhaj We're tracking this issue over ligature support at #239 and would appreciate it if you could :+1: and comment there. This helps us gauge the impact of the issue.

We'll be closing this as a duplicate.
