### ISSUE TITLE
use two fingers to swipe through warp tabs

### ISSUE THREAD

**Issue by eambutu** [warpdotdev/Warp#3719]
### Describe the solution you'd like?

```Text
on other terminal apps, for mac, you can use your two fingers to swipe left or right to switch tabs. id like this in warp too.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @

We already have a request tracking this over at #582 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
