### ISSUE TITLE
Numer on history appear in the comand

### ISSUE THREAD

**Issue by AM-I-Human** [warpdotdev/Warp#3722]
### Describe the bug

```
9 cd ~/Projects/iassicur_downloader/ && poetry run python load_on_s3.py upload --environment production --subdomain mach1 --to-date 2023-09-30 --from-date 2023-09-29
```
This is what appeared when i pressed the up arrow, the 9 is not what I ran.

before this I got another
```
8 cd ~/Projects/iassicur_downloader/ && poetry run python load_on_s3.py upload --environment production --subdomain mach1 --to-date 2023-09-30 --from-date 2023-09-29
```

### To reproduce

Up arrow.

### Expected behavior

Only the command runned.

### Screenshots

Not necessary

### Operating system

MacOS

### Operating system and version

14.0.0

### Shell Version

zsh, last version

### Current Warp version

v0.2023.09.26.08.09.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

this morning

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @AM-I-Human, I wonder if there may be something in your .zshrc file Warp doesn't support.
You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv` This forces Zsh to run with zero configs.

A common culprit for issues in the rc file is iterm2_shell_integration for example. You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by dannyneira** [comment]
Hey @AM-I-Human It may be an issue with your rc file. Check it for the common unsupported plugins.
We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>

My guess is that you normally have a [custom prompt, theme, or bash/zsh/fish plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table)

If any are found, you can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```
