### ISSUE TITLE
persistent panes

### ISSUE THREAD

**Issue by snokpok** [warpdotdev/Warp#3724]
### Describe the solution you'd like?

```Text
Something like Tmux where when I reopen Warp, it reopens all the panes that were saved
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting! As a workaround, look into the Launch Configurations feature, it can launch a set of panes/tabs/windows easily. https://docs.warp.dev/features/sessions/launch-configurations

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by zachbai** [comment]
Hey @snokpok, we have support for this (at least as I understand your feature request) via the "Restore windows, tabs, and panes on startup" setting here:

![image](https://github.com/warpdotdev/Warp/assets/10970845/f119d858-c14a-4835-9e39-dbda23965f5e)
