### ISSUE TITLE
"Switch Panes Left" and "Switch Panes Right" shortcuts don't work.

### ISSUE THREAD

**Issue by beginaid** [warpdotdev/Warp#3725]
### Describe the bug

When a window divided into four panes (two each on top and bottom), "Switch Panes Left" and "Switch Panes Right" shortcuts don't work while "Switch Panes Up" and "Switch Panes Down" work well.

### To reproduce

1. Divide window into four panes (two each on top and bottom)
2. Use "Switch Panes Left" and "Switch Panes Right" shortcuts

### Expected behavior

When using "Switch Panes Left", active pane moves to the left.
When using "Switch Panes Right", active pane moves to the right.

### Operating system

MacOS

### Operating system and version

Ventura 13.5.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.09.26.08.09.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @beginaid. I'll let the team know and we'll post any updates on this thread.

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by beginaid** [comment]
Thanks for your information.
I'll close this issue as a duplicate.
