### ISSUE TITLE
Custom fullscreen

### ISSUE THREAD

**Issue by kfatehi** [warpdotdev/Warp#3728]
### Describe the solution you'd like?

I would like an option that avoids using the "native" fullscreen. Effectively like this option in iTerm2: Preferences->General->Window->Uncheck Native full screen windows

![image](https://github.com/warpdotdev/Warp/assets/175305/006d98e5-4f80-4116-8a1c-172c01b6cb1f)

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! 

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.
