### ISSUE TITLE
Theme is broken when using with Oh My Zsh

### ISSUE THREAD

**Issue by teddythinh** [warpdotdev/Warp#3730]
### Discord username (optional)

teddythinh#8001

### Describe the bug

I'm using Oh My Zsh in Warp with the Powerlevel10k theme and it broke.

### To reproduce

1. Start the Warp terminal.
2. See the theme broke.

### Expected behavior

I want to see if the theme is not broken compared to the iTerm terminal in the screenshot below.

### Screenshots

**Warp**

<img width="975" alt="image" src="https://github.com/warpdotdev/Warp/assets/85171754/7a7b9d32-b60b-40b8-9f30-3b9fa554ee87">

**iTerm2**

<img width="954" alt="image" src="https://github.com/warpdotdev/Warp/assets/85171754/a7659937-272f-43ec-baa7-1a9601659ef5">

### Operating system

MacOS

### Operating system and version

Sonoma 14.0 (23A344)

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2023.09.26.08.09.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
hey @teddythinh Thanks for submitting. I'm having trouble reproducing this issue. You may have to try running `p10k configure` and go through the configuration to see if that can help with the issue. Or reinstall p10k from scratch and make sure you're on the latest version. Our docs also have a great video covering the setup of p10k on Warp. https://docs.warp.dev/features/prompt#powerlevel10k

**Comment by thoroc** [comment]
@teddythinh is that resolved? https://github.com/warpdotdev/Warp/issues/2851

**Comment by teddythinh** [comment]
Hi @thoroc, Thanks for your reference. This [comment](https://github.com/warpdotdev/Warp/issues/2851#issuecomment-1605005256) works for me. I'm closing the issue.
