### ISSUE TITLE
Warp Terminal integration with TMUX

### ISSUE THREAD

**Issue by KitAdams** [warpdotdev/Warp#3737]
### Describe the solution you'd like?

```Text
When using tmux + warp, this stops all warp commands.
eg. ctrl + r = search through bash / zsh history, not using warp's command search tool

Please allow for tighter integration when using tmux + warp so that my shortcuts still run the warp shortcuts

For any person who uses tmux + warp, we lose the benefits of the warp terminal.
```

### Is your feature request related to a problem? Please describe.

```Text
When using tmux + warp, this stops all warp commands.
eg. ctrl + r = search through bash / zsh history, not using warp's command search tool
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @KitAdams 

We already have a request tracking this over at #501 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

1. We'll be closing this as a duplicate.
