### ISSUE TITLE
Long press button to move the cursor in VIM mode

### ISSUE THREAD

**Issue by panudetjt** [warpdotdev/Warp#3738]
### Describe the solution you'd like?

```Text
I want to be able to long press buttons to navigate the cursor in VIM mode.
```

### Is your feature request related to a problem? Please describe.

```Text
Currently, if I long press a button in VIM mode, it keeps showing the "alternative" character.
```

### Additional context

<img width="1669" alt="image" src="https://github.com/warpdotdev/Warp/assets/3482285/35e0dff2-3dbc-4b61-91c7-fb2a4fdc0faf">

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by acarl005** [comment]
Hi @panudetjt. I believe this is something that must be configured in MacOS. You have to disable an option called `ApplePressAndHoldEnabled`. 

You can do that in your terminal with something like

```sh
# disable the feature for Warp specifically
defaults write dev.warp.Warp-Stable ApplePressAndHoldEnabled -bool false

# alternatively, disable it for all apps
defaults write -g ApplePressAndHoldEnabled -bool false
```

See [this article](https://vimforvscode.com/enable-key-repeat-vim) for more details.

**Comment by panudetjt** [comment]
Dear @acarl005,

I apologize for misunderstanding the feature of Warp. Your solution resolved the issue.
Thank you for your reply.
