### ISSUE TITLE
CTRL-SHIFT-UP/DOWN to add cursors

### ISSUE THREAD

**Issue by ephemer** [warpdotdev/Warp#374]
### Describe the solution you'd like?

In Sublime Text (and VSCode I think) you can add an additional cursor in the line above/below the current cursor(s) via `Ctrl + Shift + Up` / `Ctrl + Shift + Down`.

To me that is a fundamental part of multi-cursor support, equally important to or even more important than `Cmd + D`. It would be fantastic if you could add this.

### Is your feature request related to a problem? Please describe.

Selecting a word and duplicating that selection is more keystrokes and effort than just adding a cursor directly. I don't always want to add cursors on lines that contain the same word / command.

From what I can see Ctrl+Shift+Down (etc.) are not bound to anything else and implementing this would be a huge fluidity win for transferring my mental model of multi-cursor editing into the terminal.

**Comment by elviskahoro** [comment]
Moving to #579 so all keybinding related issues are in one place:
- #579

**Comment by elviskahoro** [comment]
Added with version: v0.2022.01.31.09.03.stable_00
