### ISSUE TITLE
I'd like the command prompt to display Subversion information like it does for git

### ISSUE THREAD

**Issue by garydgregory** [warpdotdev/Warp#3740]
### Describe the solution you'd like?

```Text
I'd like the command prompt to display Subversion information like it does for git.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! I could see how svn info could be useful in Warps default prompt. As a workaround, I recommend you try using p10k custom prompt and [enable svn support](https://github.com/romkatv/powerlevel10k/issues/531#issuecomment-591932921). Our docs also have a great video covering the setup of p10k on Warp. https://docs.warp.dev/features/prompt#powerlevel10k


To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Hi @garydgregory We recently released the SVN/Subversion prompt chip in Warps prompt. https://docs.warp.dev/getting-started/changelog#id-2023.02.01-v0.2024.01.30.16.52

Closing as resolved :)

**Comment by garydgregory** [comment]
Hi @dannyneira 

Not for me 😞 

<img width="638" alt="image" src="https://github.com/warpdotdev/Warp/assets/1187639/8aaf234c-2e09-4558-a2a3-fdee5de8850d">

Using v0.2024.04.16.08.02.stable_00

Is this something I have to turn on?

TY

**Comment by dannyneira** [comment]
Yes edit your prompt and drag the svn prompt chip into your current prompt.see my screenshot for example.

**Comment by garydgregory** [comment]
@dannyneira 
Ah, yes, that works, TY for the pointer!
