### ISSUE TITLE
Disable "Warp Essentials"

### ISSUE THREAD

**Issue by pika2uuu** [warpdotdev/Warp#3743]
### Describe the solution you'd like?

```Text
I want Warp to disable "Warp Essentials" and "What's new" tab.
It's so annoying.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @pika2uuu 

We already have a request tracking this over at #3742 https://github.com/warpdotdev/Warp/issues/3742

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by 0xFlo** [comment]
Can you just move it somewhere else? It's taking up too much real estate from the terminal.
