### ISSUE TITLE
Make a delete block option

### ISSUE THREAD

**Issue by asidko** [warpdotdev/Warp#3747]
### Describe the solution you'd like?

```Text
I'd be very useful to be able to delete a block.
```

### Is your feature request related to a problem? Please describe.

```Text
i'm always frustrated when accidentally cat a big file or wanded to make a screenshot with the result of few commands but made a mistake in a last one, etc.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @asidko

We already have a request tracking this over at #50

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
