### ISSUE TITLE
Ability to remove paddings for editors like nvim

### ISSUE THREAD

**Issue by Infonautica** [warpdotdev/Warp#3749]
### Discord username (optional)

leodnlv

### Describe the solution you'd like?

```Text
Currently when open interactive application like nvim (and especially colorful configurations like AstroNvim, LunarVim) it doesn't look nice due to the paddings around terminal that don't match the color of the editor.

Full styling configuration maybe a bit too much, but a toggle like "remove terminal paddings" can be sufficient enough
```

### Additional context

Freshly introduced custom themes help, as now i can configure warp theme to match my nvim colorscheme

**Before** custom theme:
<img width="1137" alt="before" src="https://github.com/warpdotdev/Warp/assets/5521648/b19eb979-722b-44d3-8b0a-47b1d243ddb8">

**After** custom theme:
<img width="1137" alt="after" src="https://github.com/warpdotdev/Warp/assets/5521648/17b87bc3-0178-4c1e-9dbc-12dbf3de8a92">

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by elviskahoro** [comment]
We're tracking this in another open issue, will forward the issue number once I find it

**Comment by Infonautica** [comment]
@elviskahoro Is this the one?
https://github.com/warpdotdev/Warp/issues/2373

**Comment by elviskahoro** [comment]
@Infonautica Yep!
