### ISSUE TITLE
DUP: Duplicate of #107 - CMD+m does not minimize on macOS

### ISSUE THREAD

**Issue by marcello3d** [warpdotdev/warp#375]
### Describe the bug

```shell
I can't minimize with the standard keyboard shortcut like in most Mac apps:
```

### To Reproduce

1. open a window
2. hit command m
3. nothing happens

### Expected behaviour

```shell
The window should minimize to the dock
```

### Screenshots

Example menu option from Safari for comparison:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/21952/140662763-25de4b07-a2c4-4292-b53e-cd3452e23859.png">

### Operating System

MacOS

### OS Version

11.6 (20G165)

**Comment by elviskahoro** [comment]
Being tracked here:
- https://github.com/warpdotdev/warp/issues/107
