### ISSUE TITLE
Unable to fill the entire warp terminal with neovim

### ISSUE THREAD

**Issue by Raopend** [warpdotdev/Warp#3752]
### Describe the bug

I use Neovim as code editor. I noticed that neovim couldn't fill the entire terminal, but I tested it fine on terminal.app.

### To reproduce

To reproduce it:
1- open neovim in warp

### Screenshots

![WX20231010-230510@2x](https://github.com/warpdotdev/Warp/assets/76681491/429f1585-9e55-4286-90fc-47ba46825602)

### Operating system

MacOS

### Operating system and version

macos14

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.10.03.08.03.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @Raopend 

We already have a request tracking this over at #2373

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
