### ISSUE TITLE
Have Warp Respect macOS theme settings

### ISSUE THREAD

**Issue by greg-gelfond** [warpdotdev/Warp#3753]
### Describe the solution you'd like?

```Text
Currently, Warp always uses a dark top-bar on the window regardless of whether or not on macOS the UI is set to light mode. Ideally, the *window border* will respect the UI theme of the OS while the individual contents (terminal itself) would be themed separately.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
hey @greg-gelfond Thanks for submitting. As a workaround, you can configure the themes to sync with the OS as with other apps. https://docs.warp.dev/appearance/themes#os-theme-sync. Once you have it enabled you can configure which themes to apply for light/dark modes. 


There is no way to keep the top bar separate from the terminal at this time. To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Hi @greg-gelfond Was the above helpful? 

Closing as this feature exists, but please please let us know of any issues with the OS theme switch.
