### ISSUE TITLE
Unable to set Cmd + Esc key (⌘⎋) as Global hotkey

### ISSUE THREAD

**Issue by stephenmckinney** [warpdotdev/Warp#3757]
### Describe the bug

When trying to set the keybinding for the global hotkey Cmd + Esc key (⌘⎋) is not allowed.

### To reproduce

1. Open Settings > Features > Keys and select "Keybinding"
2. Press `Cmd`+`Esc` key (⌘⎋)
3. Nothing happens.

### Expected behavior

The keybinding is set.

### Operating system

MacOS

### Operating system and version

14.0.0

### Current Warp version

v0.2023.10.03.08.03.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

This is the "classic" Visor hotkey. It works for iTerm2. I'd love to be able to utilize this muscle memory in Warp.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @stephenmckinney We already have a request tracking this over at #1851

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
