### ISSUE TITLE
Add Sticky Window feature like in iTerm2

### ISSUE THREAD

**Issue by orkhanfarmanli** [warpdotdev/Warp#3758]
### Describe the solution you'd like?

```Text
Currently Warp acts as an independent window which can be cumbersome to handle if there are too many windows already in the workspace. iTerm2 has a great solution for this. You can toggle (^ + ~) to show/hide the terminal with a shortcut which sticks to the bottom or the top of the screen with full width and a height you define. It doesn't show up on dock and it doesn't act as an independent window when you are switching between windows in your workspace.
```

### Additional context

Here's a preview of how iTerm2 can be configured:

<img width="1728" alt="image" src="https://github.com/warpdotdev/Warp/assets/14097805/f914fdbc-fd44-4c17-af30-641b54b008d8">

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @orkhanfarmanli Warp has a Dedicated window that you can trigger with a hotkey, Please learn more about this feature here: https://docs.warp.dev/features/windows/hotkey-window#dedicated-window

Closing as this feature already exists.
