### ISSUE TITLE
CTRL-/ does not comment out anymore in my neovim

### ISSUE THREAD

**Issue by corroded** [warpdotdev/Warp#376]
### Describe the solution you'd like?

```shell
I would hope that all the keybindings I have in my vimrc would have been ported over. It looks like there are some keys that have not ported over properly. I think it should be able to port as the neovim window is technically not the terminal window anymore?
```

### Additional context

I am using this plugin:  https://github.com/tomtom/tcomment_vim

Let me know if additional info is needed or there's already an existing issue (I tried to search but couldn't find any)

**Comment by elviskahoro** [comment]
> ctrl shortcuts: "ctrl " usually comments things out in neovim but it doesn't work in warp.

**Comment by elviskahoro** [comment]
Moved to Vim Discussion:
- https://github.com/warpdotdev/Warp/discussions/451

**Comment by elviskahoro** [comment]
@corroded just double checking. This is not happening for you, correct?
