### ISSUE TITLE
Can't double-click part of the prompt to copy

### ISSUE THREAD

**Issue by dep** [warpdotdev/Warp#3762]
### Describe the bug

You can double-click on other text, just not part of the prompt.

I'm always needing to copy the active Git branch name for one reason or another.

### To reproduce

Load Warp, go into a repo, doubleclick on the branch name

### Expected behavior

Branch name gets highlighted to copy

### Screenshots

![CleanShot 2023-10-11 at 11 43 27](https://github.com/warpdotdev/Warp/assets/55112925/2aa14537-76ca-4ce4-95a1-6e8a9f01628b)

### Operating system

MacOS

### Operating system and version

Sonoma

### Shell Version

zsh

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by abhishekp106** [comment]
Hi @dep, thanks for taking the time to file the issue. It's a known issue that some of our UI text is not selectable. Sorry for the inconvenience.

As a temporary workaround, you can right-click on the prompt to bring up a context menu and select "Copy git branch".

<img width="428" alt="Screenshot 2023-10-11 at 11 47 35 AM" src="https://github.com/warpdotdev/Warp/assets/40919306/2ab01a03-10fc-4a02-8ff2-9392f7d84e7c">

**Comment by dep** [comment]
Thank you for the tip and workaround, @abhishekp106!

**Comment by dannyneira** [comment]
Thanks for submitting this @dep We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/36

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
