### ISSUE TITLE
Commands suggestion box does not close when opening settings modal

### ISSUE THREAD

**Issue by karlas** [warpdotdev/Warp#3763]
### Describe the bug

Commands suggestion box does not close when oppening settings modal

### To reproduce

1. Start writing some command
2. Press tab in terminal after writing to display suggestions
3. Without closing it, click "settings" button

### Expected behavior

Suggestions should automatically close when opening settings modal

### Screenshots

<img width="1408" alt="Captura de pantalla 2023-10-11 a las 19 01 17" src="https://github.com/warpdotdev/Warp/assets/1649940/77a7b086-02ca-490b-9727-1600aee98f69">

### Operating system

MacOS

### Operating system and version

14.0.0

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Current Warp version

v0.2023.10.03.08.03.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @karlas.

We're tracking this issue over at #https://github.com/warpdotdev/Warp/issues/2792 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
