### ISSUE TITLE
Display the start time of a currently running command

### ISSUE THREAD

**Issue by lubokkanev** [warpdotdev/Warp#3765]
### Describe the solution you'd like?

```Text
While a long command is running, we can't see the time it started. This info is only available once the command has finished. Please add it since the start of the command.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @lubokkanev Thanks for submitting. If you add the time to the [default prompt](https://docs.warp.dev/features/prompt#default-prompt) (right-click on the prompt an edit), or use a [custom prompt](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table) that supports time, once it starts running you should be able to see the start time while the command is running.

![CleanShot 2023-10-12 at 11 52 35](https://github.com/warpdotdev/Warp/assets/16809145/ee0e905c-d0a7-4c31-a357-c67c67393432)

https://github.com/warpdotdev/Warp/assets/16809145/9cf5bb05-0f03-4f2f-b395-51b639979ec6

Please let me know if this helps with your request, or clarify what you'd like to see differently in Warps prompt.

**Comment by lubokkanev** [comment]
Yes, this seems to do what I want. Thank you.

**Comment by lubokkanev** [comment]
Yes, this seems to do what I want. Thank you.
