### ISSUE TITLE
SSH wrapper not working for sessions started through sshpass

### ISSUE THREAD

**Issue by andrei-onoie** [warpdotdev/Warp#3766]
### Operating System

MacOS

### Operating System and Version

Ventura

### Local Shell Version

zsh 5.9

### Remote Shell Version

n/a

### Warp Version

v0.2023.09.12.16.17.stable_00

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

When starting an ssh session through `sshpass`, it is treated as a regular command and the pretty ssh wrapper is no longer applied. There is also no option to press ^I to lift the current session.

### Include shell xtrace output

n/a

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @andrei-onoie If you add `sshpass` to your Settings > Subshells list, it should trigger the option to warpify the ssh session. https://docs.warp.dev/features/subshells#adding-compatible-commands

https://github.com/warpdotdev/Warp/assets/16809145/634c0bd9-1311-485e-a934-3e6d8ae24907

Please let me know if this helped with your issue.

**Comment by andrei-onoie** [comment]
Thanks @dannyneira, indeed the Warpify option is now available. However, I can't get tab completion for files/directories to work (for normal ssh this works fine). I can only get builtin completions such as common commands and their arguments (with helpful tooltips for what they do). Is it the same on your end too?

**Comment by dannyneira** [comment]
Hi @andrei-onoie Yes the same since there isnt native support for SSH pass with the default Warp SSH Wrapper yet. That being said there is a request for sshpass support we're tracking here #3927

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this bug report in favor of the `sshpass` feature request.
