### ISSUE TITLE
Add "undo" functionality

### ISSUE THREAD

**Issue by lubokkanev** [warpdotdev/Warp#3771]
### Describe the solution you'd like?

```Text
The prompt editing features of Warp are incredible. One thing missing that would improve it even further is an "undo" and "redo" functionality. Limiting it to the life of the current prompt would be enough IMO.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @lubokkanev Warp supports `CMD-Z` to undo and `SHIFT-CMD-Z` to redo any edits to the input editor. https://docs.warp.dev/getting-started/changelog#2022.01.05-v0.2022.01.03.09.07

Please let us know if this helps with your use case, by closing as this feature already exists in the editor.

**Comment by lubokkanev** [comment]
Yes, my bad. I had the key combination remapped.

**Comment by lubokkanev** [comment]
Yes, my bad. I had the key combination remapped.
