### ISSUE TITLE
oh-my-posh not working 

### ISSUE THREAD

**Issue by ghost** [warpdotdev/Warp#3773]
### Describe the solution you'd like?

```Text
I installed the oh-my-posh as it allows me to keep the track of the changes i have to push to git branches and it is not working in the warp. see attached. I checked the same zsh shell on the another one and it is working absolutely fine. Any guess how to enable this so that i can keep track of the changes that i have to push to the git branches. Thank you warp. 


Best regards,
Gaurav
```

### Is your feature request related to a problem? Please describe.

```Text
I installed the oh-my-posh as it allows me to keep the track of the changes i have to push to git branches and it is not working in the warp. see attached. I checked the same zsh shell on the another one and it is working absolutely fine. Any guess how to enable this so that i can keep track of the changes that i have to push to the git branches. Thank you warp. 


Best regards,
Gaurav
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @sablokgaurav, I'm not seeing the same on my end as oh-my-posh is supported, make sure you have the `eval "$(oh-my-posh init zsh)"` in your `~/.zshrc` file and run `brew update && brew upgrade oh-my-posh` to make sure you're on the latest version. You may also have to configure your prompt to show the changes as well as enable the custom prompt in your settings. Right-click on the prompt and edit. https://docs.warp.dev/features/prompt

![CleanShot 2023-10-13 at 13 23 34](https://github.com/warpdotdev/Warp/assets/16809145/851b6e7b-b03d-4da5-a5c6-2dfcf77ff36e)

**Comment by sablokgaurav** [comment]
Hey @dannyneira  thank you for the information and i will give it a go and will let you know.

**Comment by rodrigodabreu** [comment]
thank you @dannyneira really appreciate your recomendation
