### ISSUE TITLE
session shared

### ISSUE THREAD

**Issue by ZH1995** [warpdotdev/Warp#3774]
### Operating System

MacOS

### Operating System and Version

Sonoma 14.0

### Local Shell Version

$ZSH_VERSION 5.9

### Remote Shell Version

-

### Warp Version

v0.2023.10.10.08.06.stable_02

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

In company, I need login a fortress machine firstly. In Iterm2, I can login once, then login moretime in other tab. But Warp can't do it. 

### Include shell xtrace output

-

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Check our SSH GitHub milestone to see if your issue has already been reported. <https://github.com/warpdotdev/Warp/issues/578>

If it hasn't been reported, you can try using adding `/usr/bin/ssh` to you Settings > Subshell menu.
or you can also try disable the SSH wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabling, SSH should work as normal.

**Comment by ZH1995** [comment]
After close [Warp SSH Wrapper] , it has worked!
