### ISSUE TITLE
Warp popup on screen with cursor (Like iTerm2)

### ISSUE THREAD

**Issue by djmango** [warpdotdev/Warp#3775]
### Describe the solution you'd like?

```Text
Ideally, there should be a setting which mimics iTerm2's hot window behavior, where it opens on the screen with the cursor on it. Currently it opens on the screen with an active window, which when working with multiple screens, is often not the one my focus is on.
```

### Is your feature request related to a problem? Please describe.

```Text
This is especially annoying when reading docs on a different screen than my editor is on, and I go to try out a command or something in a quick hot window, just like I do in iTerm2, and it pops up over my text editor. You can interact with most screens by just scrolling without clicking in, leaving warp believing you are still using the screen you were clicked into previously.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! 

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.
