### ISSUE TITLE
Terminal Copilot

### ISSUE THREAD

**Issue by rokn** [warpdotdev/Warp#3781]
### Describe the solution you'd like?

The current AI integrations in Warp can benefit a lot from a CoPilot-like UX. The current AI command suggested command feature is really helpful but it currently seems to be working only when the last is an error. I think this can be extended to suggesting command when possible from the history of the last commands. For example one could use `npm vite create` which would result in output like:

```
...

Done. Now run:

  cd project_name
  yarn
  yarn dev
```

Then Wrap can suggest `cd project_name` and the next commands after executing the first.
On top of that I think AI auto completion can be added for the current command much like the UX currently for completing from history.

I think this will increase the productivity of Wrap users a lot.
I'm free to help explain in more detail if necessary.

Thanks for the great work, Warp team.
```


### Is your feature request related to a problem? Please describe.

_No response_

### Additional context

_No response_

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! Warp AI is certainly something we're looking to improve in the future so stay tuned!

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Soon... https://twitter.com/warpdotdev/status/1792614144354693127

**Comment by rokn** [comment]
My request is now done with the introduction of "Next Command". Thank you guys for the most amazing and advanced terminal!
