### ISSUE TITLE
Full screen commands not visible fully

### ISSUE THREAD

**Issue by rokn** [warpdotdev/Warp#3782]
### Describe the bug

Sometimes when running "fullscreen" commands like `vite` the screen doesn't show the whole output and you have to scroll a bit up.

### To reproduce

```
yarn create vite
cd project
yarn dev
```

### Screenshots

<img width="1503" alt="image" src="https://github.com/warpdotdev/Warp/assets/4174764/8a9cfc07-7a26-4181-bcbf-0cd81560f6b9">

### Operating system

MacOS

### Operating system and version

Ventura 13.3.1

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.10.10.08.06.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know! This has to do with the behavior of the [Sticky Command Header](https://docs.warp.dev/features/blocks/sticky-command-header). As a workaround, please disable the sticky command header.

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/3530 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue.

We'll be closing this as a duplicate.
