### ISSUE TITLE
git push error

### ISSUE THREAD

**Issue by ZH1995** [warpdotdev/Warp#3783]
### Describe the bug

git status
On branch resource_1-0-106_BRANCH
Your branch is ahead of 'origin/resource_1-0-106_BRANCH' by 3 commits.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	app/resource/xxx.toml

nothing added to commit but untracked files present (use "git add" to track)

git push origin HEAD:refs/for/resource_1-0-106_BRANCH
fatal: internal server error
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

### To reproduce

1. git status
2. git push origin HEAD:refs/for/resource_1-0-106_BRANCH

### Expected behavior

push success

### Operating system

MacOS

### Operating system and version

Sonoma 14.0 (23A344)

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)

### Current Warp version

v0.2023.10.10.08.06.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Closing as this doesn't appear to be an issue with Warp, I also recommend you try looking thru the git documentation for a solution. https://git-scm.com/doc. Please feel free to let us know if you can reproduce it.
