### ISSUE TITLE
Highlight running tabs

### ISSUE THREAD

**Issue by pedromonteiro18** [warpdotdev/Warp#3784]
### Describe the solution you'd like?

```Text
Option to enable automatic highlighting of tabs which are running commands
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! 

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by zachbai** [comment]
Closing as a dupe of #2187
