### ISSUE TITLE
Keyboard shortcut: scroll lines within a block

### ISSUE THREAD

**Issue by MissingHandle** [warpdotdev/Warp#3785]
### Describe the solution you'd like?

```Text
When I press some keyboard combination, i can scroll a few lines in the block history.
```

### Is your feature request related to a problem? Please describe.

```Text
Warp has shortcuts for navigating to the top and bottom of a block, but if the output of a block is larger than the size of my window, i don’t necessarily want to scroll to the bottom, I want to just scroll a few lines. And yes, i can do this with the mouse…but of course i’d love to be able to it with the keyboard :)
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

As a possible workaround, you can press `PGUP/PGDN` to scroll through the blocks by page instead of to to top/bottom.

**Comment by szgupta** [comment]
You can also scroll line by line using the `Scroll Terminal Output Down One Line` / `Scroll Terminal Output Up One Line` actions in the command palette. To assign keybindings to these actions, you can do so in the keyboard shortcut editor!
<img width="1136" alt="Screenshot 2023-10-18 at 1 40 25 PM" src="https://github.com/warpdotdev/Warp/assets/39461854/1bbeec7c-91ec-4984-9cb6-a711c757fb0a">

**Comment by dannyneira** [comment]
Yes @MissingHandle As Suraj mentioned above you can set the keybinds for "Scroll up/down one line" or access it from the Command Palette `CMD-P` and search for "scroll one"

![CleanShot 2023-11-09 at 09 51 30](https://github.com/warpdotdev/Warp/assets/16809145/5c2cc9bd-c60a-4d26-8818-fb1211b78489)

Please confirm if this helps fulfill your use case/feature request.
