### ISSUE TITLE
ability to use a block cursor

### ISSUE THREAD

**Issue by alexdauenhauer** [warpdotdev/Warp#3787]
### Describe the solution you'd like?

```Text
in iterm2 they have the ability to use a box cursor. I like using a box cursor instead of vertical bar. Just a nice to have. Sorry if duplicate, I tried to search for this request but couldn't find it.
```

### Additional context

<img width="550" alt="image" src="https://github.com/warpdotdev/Warp/assets/11903445/2ecf3236-93ea-401a-bd14-78efb9b4a8ac">

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by heysweet** [comment]
Hello! Just wanted to let you know that we've implemented not only the Block cursor but Underline as well, available under `Settings > Appearance > Cursor` as `Cursor type`. Enjoy!
