### ISSUE TITLE
Split terminal view in two-page layout

### ISSUE THREAD

**Issue by bphd** [warpdotdev/Warp#3788]
### Describe the solution you'd like?

```Text
I would like to request the implementation of server folders or groups. This feature would allow users to organize their servers into folders or categories, making it much easier to manage and access their servers efficiently. Users should be able to create, name, and customize these server folders and move servers in and out of them as needed.
```

### Is your feature request related to a problem? Please describe.

```Text
I'm always frustrated when I need to manage multiple servers on Discord, and I can't easily organize or group them. The current server list can become cluttered and challenging to navigate, especially if you're part of numerous servers.
```

### Additional context

The addition of server folders would greatly improve the user experience for Discord users who are members of many servers. It would provide a more organized and streamlined way to access servers, enhancing the usability of the application, especially for those who use Discord for both personal and professional purposes.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @bphd I think you meant to open this request on one of the Discord repos. Please see here for the list of Discord repos: https://github.com/discord

Closing as this is request for Discord, not Warp.

**Comment by bphd** [comment]
> Hey @bphd I think you meant to open this request on one of the Discord repos. Please see here for the list of Discord repos: https://github.com/discord
> 
> Closing as this is request for Discord, not Warp.

Please re-open, it's not about Discord, it's about split terminal view in two-page layout. Like it would be great for tiny screen to see the output on two-page layout, like two pages side by side, to we can see more on one screen. Because otherwise the screen have to be in portrait to display all its length
