### ISSUE TITLE
Unable to display float term for neovim

### ISSUE THREAD

**Issue by ivanlee1999** [warpdotdev/Warp#3790]
### Describe the bug

I am using nvchad of neovim. It can use opt+i to open float term and opt+h to open horizontal term.
Opt+h works fine. But it can not display float term using opt+i

### To reproduce

install nvchad, map option to meta+, then enter neovim and hit opt+i

### Operating system

MacOS

### Operating system and version

MACOS 

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @ivanlee1999 I believe this may related to an issue with [option keybinds sometimes not registering](https://github.com/warpdotdev/Warp/issues/1454). We'll post any updates on this thread.

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by jakubdonovan** [comment]
`meta i`, `option v`, `option h` still doesn't work.
