### ISSUE TITLE
Tab dragging to new window

### ISSUE THREAD

**Issue by billwood09** [warpdotdev/Warp#3793]
### Discord username (optional)

billwood09

### Describe the solution you'd like?

```Text
Allow dragging tab outside of window to create new window with that tab
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @billwood09 

We already have a request tracking this over at #466 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
