### ISSUE TITLE
mechanism to support native completion

### ISSUE THREAD

**Issue by ilrudie** [warpdotdev/Warp#3801]
### Describe the solution you'd like?

```Text
A mechanism for accessing the underlying completion of my shell
- Option to set Warp's <tab> behavior to nothing/passthrough
- Option to set a keybinding which passes <tab> down
- Keybinding to toggle <tab> behavior between "native" and "warp"

This would provide an advantage for users of Warp who'd like completion that Warp doesn't yet support as well as offering a sort of "fall back" mode for when native completion would be preferred even though Warp does provide it's own version.
```

### Is your feature request related to a problem? Please describe.

```Text
When using Warp there are times when I'd really prefer to be able to access the completion functionality of my shell. This may be when operating over a slower ssh connection where Warp's completion isn't working very quickly or just times when I'd prefer to be able to have git or kubectl's completion functionality in bash instead of Warp's.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @ilrudie 

We already have a request tracking this over at #434. Completions is something we're working on improving in the near future so please stay tuned to the discussions above.

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there.

We'll be closing this as a duplicate.

**Comment by ilrudie** [comment]
Sounds good, upped 434 and added a note with the ideas from this ticket for implementation options
