### ISSUE TITLE
Please, add pinned tabs

### ISSUE THREAD

**Issue by grigoryevandrey** [warpdotdev/Warp#3802]
### Describe the solution you'd like?

```Text
Hi, i would really appreciate if you add pins and tab groups, same as chrome has. It would be really useful, because i need to have some tabs always open (pin would come at handy here), and sometimes i need to switch between contexts (f.e. i have an urgent bug to fix), and tab groups would be great for these moments
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by mdmuhtasimfuadfahim** [comment]
This feature would be a great plus for Wrap.

**Comment by dannyneira** [comment]
Thanks for this feature request! 

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

Also, we're tracking tab groups in the following request #2314
