### ISSUE TITLE
Autocomplete mechanism isn't user-friendly

### ISSUE THREAD

**Issue by jabr** [warpdotdev/Warp#3804]
### Describe the bug

Not a bug per-se, but the auto-complete mechanism (tab, menus, right arrow, etc) is just too unintuitive. I find myself fighting it at least as often as it is helpful.

And just now, I accidentally overwrote a file because of it, and that was the last straw for me. I'm going to stop using Warp as my terminal now. I'll take another look if you make some updates to that UX.

### To reproduce

Start typing a command, hit tab, accidentally select some auto-completion you didn't intend to because it starting doing stuff you didn't expect.

### Operating system

MacOS

### Operating system and version

13.6.0

### Current Warp version

v0.2023.10.10.08.06.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by zpbonjour** [comment]
I came here to make a similar post, except that I'm not going to stop using it just yet.  Just need to slow down.  

My bad experience is trying to auto-complete a directory path and it pulls from my command history instead of the actual directories in the current working directory.  Since I executed that command last, I've changed directories and the command history is no longer valid.  Annoying.

**Comment by jabr** [comment]
In case it's useful, I remembered specifically what happened for my case: I wanted to move a file (`foo.txt`) to a subdirectory (`bar`) and typed:
```
mv f<tab>b<tab><enter>
```
Expecting to run:
```
mv foo.txt bar/
```
The tabs did autocomplete as expected, but then the menu with existing files in bar/ popped up. My <enter> selected the first of those, and I ended up running:
```
mv foo.txt bar/existing.txt
```

The pop-up menu is an interesting idea with potential, but it simply conflicts with too many years of terminal muscle memory.

**Comment by dcsan** [comment]
agreed it's really annoying tab opens the menu all the time, and not just auto-completes. I have to instead use cmd- --> all the time.
I find that FIG https://fig.io/ in a normal terminal has much smoother behavior, less thought and interactions needed, it just completes what you want.

but if it did NOT do that there would be no way to have that menu appear which I guess is warp's main claim to differentiation.

eg `git s` will show you:

`git stash apply`

i would expect tab to then complete at least the `stash` part but instead it jams this clippy like menu in your face where `stash` is like the fourth command, so i have to page through all that.

![image](https://github.com/warpdotdev/Warp/assets/514002/219084b3-4dea-42a7-b0a0-57bf7bcdc0c7)

I'm finding warp makes using the terminal more tedious and more typing than without.

is there a setting to make tab completion actually er complete?

WARP's long lost cousin:
![image](https://github.com/warpdotdev/Warp/assets/514002/8e933140-1881-4fbc-83c9-90bc387e4c8a)

**Comment by cpuguy83** [comment]
I find autocomplete just way too aggressive, particularly with directories. It keeps trying to complete past where I was intending to go.

**Comment by romfil-trim** [comment]
It looks like you can modify the behavior of pressing 'tab' from accepting the suggestion from Warp to opening the menu, in the context of a path, of the existing directories.

Settings -> Features -> Editor -> Tab key behavior
Set to: Open completions menu

Then you would have -> (arrow right) as the key for accepting autosuggestion.

https://docs.warp.dev/features/command-completions/completions
