### ISSUE TITLE
bad Tap experience

### ISSUE THREAD

**Issue by locustbaby** [warpdotdev/Warp#3806]
### Describe the bug

![image](https://github.com/warpdotdev/Warp/assets/21237232/298af7a9-5419-4954-b473-001ace3d46d3)
![image](https://github.com/warpdotdev/Warp/assets/21237232/600d02c7-fee1-465d-8e0a-08c2f9206c33)

When I Tap, the file in menu is current dir, not `src`

### To reproduce

Just use tap

### Operating system

Linux

### Operating system and version

ubuntu 20

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by locustbaby** [comment]
Append, the Tap in Warp is slower than origin shell/fish/zsh/bash

**Comment by locustbaby** [comment]
It seems warp uses a lot of memory, last time I found it it used 1.5G RAM with only two connection.
![image](https://github.com/warpdotdev/Warp/assets/21237232/4fc53663-7fb2-4203-86a9-cc77a2faa639)

**Comment by dannyneira** [comment]
Thanks for letting us know @locustbaby

We're tracking this issue of high memory usage (this is what is contributing to the slow TAB performance) over at #2611 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
