### ISSUE TITLE
SSH connection bar overlaying top row of window

### ISSUE THREAD

**Issue by ToontjeM** [warpdotdev/Warp#3807]
### Describe the bug

<img width="511" alt="image" src="https://github.com/warpdotdev/Warp/assets/98271783/8440fd96-2097-47a4-8400-e3a87f4efc20">
Prompt not visible.

<img width="836" alt="image" src="https://github.com/warpdotdev/Warp/assets/98271783/d72cde78-d9e5-4eea-bda2-8ffea034ec06">
Top rows of `top` command not visible.

Have to scroll down to see them.

### To reproduce

Open a second pane using CMD-Shift-D
Select 
SSH into a server
Top row of both panes disappear behind SSH connection status bar.

### Expected behavior

Console output below connection status bar.

### Screenshots

See above

### Operating system

MacOS

### Operating system and version

Vetura 3.5.1

### Shell Version

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2023.10.17.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
We'll be tracking this issue over at #3214  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
