### ISSUE TITLE
npx @puppeteer/browsers install fails because "browsers: command not found"

### ISSUE THREAD

**Issue by matiaspan** [warpdotdev/Warp#3808]
### Describe the bug

running the following command in warp returns an error
```
npx @puppeteer/browsers install chromium@latest --path /tmp/localChromium
sh: browsers: command not found
```
when running the same command in `Terminal` succeeds

### To reproduce

execute `npx @puppeteer/browsers install chromium@latest --path /tmp/localChromium` in Warp

### Expected behavior

it should succeed and return the following output
```
Downloading chromium r1214816 - 129.7 MB [====================] 100% 0.0s 
chromium@1214816 /tmp/localChromium/chromium/mac_arm-1214816/chrome-mac/Chromium.app/Contents/MacOS/Chromium
```

### Screenshots

<img width="1410" alt="Screenshot 2023-10-25 at 1 27 25 PM" src="https://github.com/warpdotdev/Warp/assets/277110/6deedea0-5bcc-4173-980f-41887f7ac898">

### Operating system

MacOS

### Operating system and version

13.5.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.10.17.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @matiaspan , Sorry about this issue. I'm not able to reproduce this on my end. If you can, please make sure you update Warp to the version as well as npm `npm install -g npm@10.2.1`, then try running again. 

![CleanShot 2023-10-25 at 12 59 38@2x](https://github.com/warpdotdev/Warp/assets/16809145/ef2d8e83-6116-418e-9832-f125a1514de0)

If this still doesn't work, if you can please check out list of known issues as there may be something in your rc files that's not supported. https://docs.warp.dev/help/known-issues#list-of-incompatible-tools a common culprit is the iterm2_shell_integration for example. if found you can comment the lines out just for Warp with the following:

```
# bash and zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

    # Unsupported plugin/prompt code here

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi
```

**Comment by dannyneira** [comment]
@matiaspan any luck with the above?

**Comment by matiaspan** [comment]
Upgrading to npm 10.2.1 fixed it, thank you!
