### ISSUE TITLE
dead link on web site

### ISSUE THREAD

**Issue by petershank** [warpdotdev/Warp#3811]
### Describe the bug

On https://docs.warp.dev/getting-started/getting-started-with-warp, following the link to https://github.com/warpdotdev/docs/blob/main/getting-started/broken-reference/README.md produces a 404 error

### To reproduce

1. Go to https://github.com/warpdotdev/docs/blob/main/getting-started/broken-reference/README.md
2. Click the "Appearance Settings" link (https://github.com/warpdotdev/docs/blob/main/getting-started/broken-reference/README.md)
3. Notice the 404 error 

### Operating system

MacOS

### Operating system and version

na

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @petershank Thanks for letting us know! I've fixed the broken link on the getting started page https://docs.warp.dev/getting-started/getting-started-with-warp#customizing-warp

Closing as resolved.
