### ISSUE TITLE
Is there a way to choose which editor Warp opens when I Cmd-Click on a line of code?

### ISSUE THREAD

**Issue by BrianKravitz** [warpdotdev/Warp#3813]
### Describe the solution you'd like?

```Text
I ran some Python code that threw an exception, and when I Cmd-Clicked on the error line it tried to open Xcode but I'd prefer that it open the file in IntelliJ. Thanks!
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
hey @BrianKravitz Thanks for letting us know. You should be able to set the default code editor in your Warp `Settings > Features > Choose an editor to open file links`. Please see more in our docs. https://docs.warp.dev/features/files-and-links#files-and-links-1

Closing as resolved, but please do let us know if you're having issues with setting IntelliJ as the default editor.

**Comment by ddoherty03** [comment]
@dannyneira, that entry in Settings only allow one choice: "Default App".  How can we add something else as a choice, or how is the default app determined under Linux?

**Comment by dannyneira** [comment]
@ddoherty03 Warp supports several default editors for opening file links. These include:

1. VSCode
2. Cursor
3. Zed
4. Sublime Text
5. Android Studio
6. DataGrip
7. DataSpell
8. Goland
9. Pycharm 
10. Rider
11. Rubymine
12. Visual Studio Code Insiders
13. Windsurf

You can select your preferred editor in Warp by going to Settings > Features > General > "Choose an editor to open file links".

It's worth noting that Warp currently only supports GUI-based editors and not terminal-based editors like vim, nano, or helix. If you want to use a terminal-based editor, you would need to type `$EDITOR <path/to/file>` to open files with your default terminal editor.

**Comment by dannyneira** [comment]
Warp currently only supports GUI-based editors and not terminal-based editors like vim, nano, or helix. If you want to use a terminal-based editor, you would need to type $EDITOR <path/to/file> to open files with your default terminal editor.

**Comment by ddoherty03** [comment]
Emacs and emacsclient is a GUI-based editor.

I guess what I was hoping for was a setting that allowed one to set a
custom command with place holders for the file name and line, e.g., %f and
$l.

By the way, warp is pretty awesome.

====================================================
Daniel E. Doherty
D.E. Doherty Law Office, LLC
7300 W. 110th Street, Suite 930
Overland Park, KS 66210
913.338.7182 (Phone)
913.338.7164 (FAX)
***@***.***

**Comment by iocron** [comment]
Any updates on this feature? It would be enough if we had a custom input type next to the other options (e.g. Choose an editor to open file links: "Default App", "Warp", "Custom"), so we can use something like: nvim $1

**Comment by oO0oO0oO0o0o00** [comment]
there is no longer `Settings > Features > Choose an editor to open file links. `
