### ISSUE TITLE
The sidebar is too distracting

### ISSUE THREAD

**Issue by abhibeckert** [warpdotdev/Warp#3814]
### Describe the bug

It seems like every few days the sidebar automatically opens in Warp for some reason or another and I need to close it so I can continue working.

Why does Warp do that? It's very distracting and often makes the app unpleasant to use.

### To reproduce

Just use Warp normally. Eventually the sidebar will open and show "Warp Essentials" or some similar message.

### Expected behavior

When I use Warp, I expect the only thing in the window to be the shell. The appropriate place to learn about new features is on a blog or on social media or in an email, don't pop that onto the screen when I'm trying to troubleshoot a DNS problem with a server that has to be fixed right away.

### Screenshots

![Screenshot 2023-10-27 at 13 37 49](https://github.com/warpdotdev/Warp/assets/266088/89b07c36-f73b-4668-9b31-cc0cea0aecab)

### Operating system

MacOS

### Operating system and version

13.4.1

### Current Warp version

v0.2023.10.17.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @abhibeckert

The option to disable the Warp Essentials is something we already have a request tracking this over at #3742

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
