### ISSUE TITLE
Tab to auto complete not working

### ISSUE THREAD

**Issue by iMerica** [warpdotdev/Warp#3817]
### Describe the bug

Tab autocomplete is not working. Entering the tab key does nothing now.

### To reproduce

- Open Warp
- Type `ls ~/Docum` and then <TAB>. 
- Observe that `~/Documents` was not autocompleted.
- Try again with ls or any other command and directory/file pair.

### Expected behavior

I expect for basic POSIX shell behavior to work

### Operating system

MacOS

### Operating system and version

13.5.1

### Current Warp version

v0.2023.10.17.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment]
@iMerica can you try it using `command ls` so `command ls ~/Doc` -> then tab for autocompletion

**Comment by nammminn2** [comment]
same it has not been working for me to like continue a file name
