### ISSUE TITLE
⌘+U can't cleanup current command

### ISSUE THREAD

**Issue by hbakhtiyor** [warpdotdev/Warp#3823]
### Describe the bug

So, if cursor is at the end of the line, can't use ⌘+U to clear the entire line

### To reproduce

Just type anything and use ⌘+U command to cleanup current line texts

### Operating system

MacOS

### Operating system and version

Ventura 13.5.2

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @hbakhtiyor Warp does support "copy and clear" the line with `CTRL-U` not `CMD-U`, you can also "clear" the selected line with `SHIFT-CMD-K`. You can change this in the `Settings > Keyboard shortcuts` menu, please learn more about the shortcuts in our docs. https://docs.warp.dev/features/keyboard-shortcuts#custom-keyboard-shortcuts

https://github.com/warpdotdev/Warp/assets/16809145/64e2c9c8-84ee-4a8e-aa9e-f0885405f7b4

Hope this helps, closing as the clear line shortcuts exist in Warp.

**Comment by hbakhtiyor** [comment]
how about clear current multiple lines?

**Comment by hbakhtiyor** [comment]
@dannyneira ?

**Comment by dannyneira** [comment]
Yes you can clear the entire editor with `CTRL-C` check out the docs for more info.https://docs.warp.dev/features/editor#how-to-use-it

For more advanced editor actions I recommend you also try the Vim keybindings feature. https://docs.warp.dev/features/editor/vim

Hope this helps!
