### ISSUE TITLE
poe ai integration

### ISSUE THREAD

**Issue by hbakhtiyor** [warpdotdev/Warp#3824]
### Describe the solution you'd like?

```Text
integrate poe ai chatbot, instead of your outdated ai
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/3779
