### ISSUE TITLE
Raycast Copy to Clipboard not working on Pin To Top option

### ISSUE THREAD

**Issue by kaanersoy** [warpdotdev/Warp#3826]
### Describe the bug

I am using Raycast. Raycast can not paste the clipboard to Wrap. I think it is a warp bug. It is only can be reproduced in "Pin To Top" mode.

### To reproduce

1- Open warp with pin to top mode.
2- Open Raycast Clipboard history with a shortcut.
3- Select any text to paste it.

It will be pasted to another app that behind the warp.

### Expected behavior

It should be pasted to warp.

### Operating system

MacOS

### Operating system and version

13.3.1

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.10.17.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @kaanersoy Sorry to hear about this issue. I'm unable to reproduce this on my end and it appears you're on the latest version of Warp. Could you please provide a video of the issue, similar to the reproduction attempts I have below:

https://github.com/warpdotdev/Warp/assets/16809145/de7ec561-2d6a-4b0b-b73c-49a24f8df5f7

**Comment by dannyneira** [comment]
@kaanersoy any luck with the video of reproduction of the issue?
