### ISSUE TITLE
Minor doc update: VS Code changed its menus

### ISSUE THREAD

**Issue by adamdmharvey** [warpdotdev/Warp#3828]
### Describe the bug

https://docs.warp.dev/features/integrations-and-plugins#vscode

At this link to configure Warp in VSCode, it says,

> To configure this, use the Apple Menu. Click on Code -> Preferences -> Settings. Type in "terminal" and change Terminal > External: Osx Exec to Warp.app.

In the current version of VSCode, they've renamed this menu to Code -> Settings -> Settings.

### To reproduce

Use VSCode v1.84:

```text
Version: 1.84.0 (Universal)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:30:19.406Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0
```

![image](https://github.com/warpdotdev/Warp/assets/33203301/87bf91e2-cc07-428c-a79e-12fbdabb0f28)

### Expected behavior

The menus the doc describe to use are available, appreciating it's not an app under your control. :)

### Operating system

MacOS

### Operating system and version

Darwin arm64 23.0.0

### Current Warp version

n/a

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @adamdmharvey, appreciate you pointing that out. We've updated [Warp integration docs](https://docs.warp.dev/features/integrations-and-plugins#vscode) to match the newer version of [VS Codes settings editor](https://code.visualstudio.com/docs/getstarted/settings#_settings-editor). Thanks for your help!

Closing as resolved, but feel free to let us know of any issues.
