### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by laibin-wang** [warpdotdev/Warp#3830]
### Describe the bug

![b72a9babeac5214f08db407bc6e3e19](https://github.com/warpdotdev/Warp/assets/58844831/40127476-b79b-4afe-b9f1-e3f5a10f8f9c)
点击登录 注册都没有任何反应

### To reproduce

点击登录 注册都没有任何反应

### Expected behavior

点击登录 注册都没有任何反应

### Operating system

MacOS

### Operating system and version

macos 11.7

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by laibin-wang** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by dannyneira** [comment]
您好，您需要确保您有权访问 `*.googleapis.com` 和 `app.warp.dev` 才能登录。检查您的防火墙或代理并确保它没有阻止这些网站。 请参阅我们的相关文档以获取有关登录的更多帮助。 https://docs.warp.dev/help/troubleshooting-login-issues

**Comment by SuanCaiYv** [comment]
开了clash的话把clash关了，7890端口冲突

**Comment by laibin-wang** [comment]
如何配置呢

**Comment by laibin-wang** [comment]
上面的没有看懂

**Comment by dannyneira** [comment]
If the `*.googleapis.com` is being blocked, there should be a setting for it on your firewall, unless it's being blocked by your Internet Service Provider, in that case, you need to use a VPN with access to an EU or USA server to access Warp.

如果 `*.googleapis.com` 被阻止，您的防火墙上应该有一个设置，除非它被您的互联网服务提供商阻止，在这种情况下，您需要使用可以访问欧盟或 美国服务器访问 Warp。

**Comment by dannyneira** [comment]
Closing as this appears to be an issue with the user access to the APIs and not a bug within Warp.

关闭，因为这似乎是用户访问 API 的问题，而不是 Warp 中的错误。
