### ISSUE TITLE
bash alias replace entered command 

### ISSUE THREAD

**Issue by thoroc** [warpdotdev/Warp#3836]
### Describe the bug

I have npq-hero installed (see https://github.com/lirantal/npq) globally and whenever I try to call `yarn` or `npm` I get the command hidden behind the alias. This has just started to happen with version: v0.2023.10.31.08.03.stable_02 on MacOS. 

### To reproduce

1. have `npq-hero` installed globally with the alias set as per documentation
2. have the alias setup as per documentation:
  a. `alias npm='npq-hero'` for `npm`
  b. `alias yarn="NPQ_PKG_MGR=yarn npq-hero"` for `yarn`
3. start a new session
4. type `npm` or `yarn`
5. hit tab/space and observe them being replaced by the value of the alias (ie `npq-hero` and `NPQ_PKG_MGR=yarn npq-hero`

### Expected behavior

to see the entered command being left as entered, not replaced.

### Operating system

MacOS

### Operating system and version

Sonoma 14.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Current Warp version

v0.2023.10.31.08.03.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
hey @thoroc, thanks for submitting. What you're most likely seeing is the Alias Expansion, it's disabled by default. There are two ways to toggle this on and off:
From Settings: Navigate to `Settings > Features > Editor and toggle “Expand aliases as you type”`.
From the Command Palette: Press `CMD-P` to open the Command Palette. Then, search for the “Enable/disable alias expansion” option and hit `ENTER`. Please see more in the docs. https://docs.warp.dev/features/editor/alias-expansion

Hope this helps with your issue. If there is anything wrong when you disable it, please let us know.

**Comment by thoroc** [comment]
@dannyneira Thank you, I'll check that. I don't recall having that enabled so I am a bit confused how this flag would have been set to true.
