### ISSUE TITLE
Warp AI history search

### ISSUE THREAD

**Issue by Liferenko** [warpdotdev/Warp#3838]
### Discord username (optional)

liferenko

### Describe the solution you'd like?

```Text
It would be nice to have an access to Warp AI history: filter answers, search through etc.
```

### Is your feature request related to a problem? Please describe.

```Text
I'm always frustrated when I want to scroll back in Warp AI to find my previous prompts and answers but got nothing. Or when I accidentally press "Restart" in Warp AI sidebar and all beautiful, lovely and heartwarming words between me and AI are falling into the void...
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @Liferenko, thanks for this feature request!

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

Also, please note a related request for AI Command suggestions history you can track here #3562

**Comment by fatalwithin** [comment]
> ### Discord username (optional)
> liferenko
> 
> ### Describe the solution you'd like?
> ```
> It would be nice to have an access to Warp AI history: filter answers, search through etc.
> ```
> 
> ### Is your feature request related to a problem? Please describe.
> ```
> I'm always frustrated when I want to scroll back in Warp AI to find my previous prompts and answers but got nothing. Or when I accidentally press "Restart" in Warp AI sidebar and all beautiful, lovely and heartwarming words between me and AI are falling into the void...
> ```
> 
> ### Additional context
> _No response_
> 
> ### How important is this feature to you?
> 2
> 
> ### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087
> None

+1

**Comment by mivanovroku** [comment]
I would love this feature as well, especially in the case of "Ask Warp AI" in the terminal prompt. Very frequently I need to modify a previously used prompt and it is a pain to have to type the whole thing again. It would be nice if it was integrated with the command history by pressing `UP arrow` or typing `#` and then pressing `UP arrow`. Btw @dannyneira the workaround you mentioned works in a very narrow use case: it only works within the Warp AI chat window for the current session. It does not help with "Ask Warp AI" in the prompt or allow you to go back past when Warp was most recently launched.

**Comment by mivanov** [comment]
I would love this feature as well, especially in the case of "Ask Warp AI" in the terminal prompt. Very frequently I need to modify a previously used prompt and it is a pain to have to type the whole thing again. It would be nice if it was integrated with the command history by pressing UP arrow or typing # and then pressing UP arrow. Btw @dannyneira the workaround you mentioned works in a very narrow use case: it only works within the Warp AI chat window for the current session. It does not help with "Ask Warp AI" in the prompt or allow you to go back past when Warp was most recently launched.

**Comment by csells** [comment]
Now that I'm using # in Warp to generate commands via AI, I don't want to stop. However, I almost always want to follow up either by updating the previous # prompt (which doesn't seem to be an option) or adding new criterial onto the existing prompt, which does work.

For example, if I do:

```sh
# find apk files recursively
```

I can't do: 

```sh
# show file sizes
```

and get the file sizes for each of the listed apk files. I also can't up arrow and just add "and show files sizes" onto the previous "get apk files recursively" command.

Help!

**Comment by dannyneira** [comment]
Hi folks,
You can now find previous Agent Mode query history in Command Search (CTRL-R) or UP arrow history.

https://github.com/user-attachments/assets/a1932217-36a3-41b5-9894-d001a91046c4

Please note that Warp doesn't keep the history for previous AI Command Suggestions queries.

Closing as resolved, but please let us know if any issues.

**Comment by swajime** [comment]
I'm new to the WARP terminal and am just getting started.  I was dismayed when after several of what I thought were really excellent prompts and results, my system crashed and there is no history available of either.  It would be really really helpful to be able to see the history and also to be able to see historical sessions from other and particularly more advanced users.  AI (uncle Al for short) is not my most trusted friend and I'm trying to improve the relationship.  However, I do have an amnesic disorder ... and when two amnesic entities try to hash through recent issues, it can be exhausting.

**Comment by dannyneira** [comment]
AI conversation history has been added in the recent release. Please see previous conversations with CMD-Y on Mac or CTRL-SHIFT-Y on Windows and Linux.

See more on this in the docs. https://docs.warp.dev/agents/using-agents/agent-conversations#managing-conversations

Let us know if any issues.
