### ISSUE TITLE
Raycast extension's "New Window" command opens a tab in an existing window

### ISSUE THREAD

**Issue by adhusson** [warpdotdev/Warp#3839]
### Describe the bug

Raycast's Warp extension has a `New Window` command:
![image](https://github.com/warpdotdev/Warp/assets/2977/8e9107b4-86b7-4a4b-af18-7dcab6e19a44)

But invoking it creates a new tab in an existing Warp window (instead of creating a new Warp window):

The code of the extension's [new-window.tsx](https://github.com/raycast/extensions/blob/main/extensions/warp/src/new-window.tsx) file is:

```tsx
import { open } from "@raycast/api";
import { newWindow } from "./uri";

export default async function Command() {
  await open(newWindow("~"));
}
```

So I assume this has to do with Warp's API more than with Raycast. IIRC this feature used to work.

### To reproduce

- Open Raycast
- Type 'New Window'
- Select Warp's 'New Window Command'
- Hit Enter

### Expected behavior

A new window should open

### Operating system

MacOS

### Operating system and version

Ventura 13.5.2

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.10.17.08.03.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Don't know

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @adhusson Thanks for submitting this. We are aware of the issue with the "New Window" URI opening a new Tab instead and are working on a fix.

We're tracking this issue over at #3825  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
