### ISSUE TITLE
SSH: bash error message in ssh gets into command editor area

### ISSUE THREAD

**Issue by zilahu** [warpdotdev/Warp#384]
### Describe the bug

```shell
When I ssh into a remote host, and there are some bash error, the error message gets into the command editor area.

ssh examplehost

bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
cursus: error: unexpected __iterm2_prompt_command, try --help


bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
cursus: error: unexpected __iterm2_prompt_command, try --help
```

### To Reproduce

Steps to reproduce:
1. make some error on remote host .bash_profile (eg. missing locale)
2. ssh to remotehost
3. press enter
4. See the bash: warning ... in the command area

### Expected behaviour

```shell
The error displays as result block and command prompt area is empty
```

### Screenshots

![CleanShot 2021-11-09 at 07 44 16](https://user-images.githubusercontent.com/266398/140875409-69af4341-8cbe-4f85-b7ab-4b62101c61bb.png)

### Operating System

MacOS

### OS Version

12.0.1

**Comment by serasset** [comment]
I confirm that this happens each time an error message is broadcasted while no command is executed. This happens for instance if there is a broadcast message from the host.

**Comment by elviskahoro** [comment]
@serasset @zilahu 

Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
