### ISSUE TITLE
Autocomplete for apt doesn't work over SSH

### ISSUE THREAD

**Issue by Javihache** [warpdotdev/Warp#3840]
### Describe the bug

I ssh from MacOS to a lot of different Ubuntu machines. Sometimes I want to install a certain version of a package using apt. I type `sudo apt install firstletters` of the library I want to install and then press tab to be presented with a list of the packages the start by 'firstletters'.

This functionality doesn't work with Warp. I only get the directories or files in a list but not the list of packages. 

Is this the expected behaviour?

### To reproduce

ssh into an Ubuntu Linux machine. Type `sudo apt install someletters` and press Tab. 

### Expected behavior

Normally a list should be displayed with all the packages beginning with 'someletters'.

### Operating system

MacOS

### Operating system and version

Ubuntu 22.04

### Shell Version

bash

### Current Warp version

latest

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @Javihache Thanks for submitting. So from our [supported completions specs](https://docs.warp.dev/features/command-completions/completions#supported-completion-specs), `apt` isn't included, but we're working on improving this in the near future, especially once we have Linux version of Warp available.

We're tracking this issue over at #652  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
