### ISSUE TITLE
Delete Previous Commands

### ISSUE THREAD

**Issue by dinerotres** [warpdotdev/Warp#3841]
### Discord username (optional)

bocash95

### Describe the solution you'd like?

```Text
I would like the ability to delete a command that I entered, incorrectly so when I am copying and pasting, the bad command won't be visible.
```

### Is your feature request related to a problem? Please describe.

```Text
No, it is not a problem. Just a feature that I would like to see implemented.
```

### Additional context

I can not enter in my Discord name with the proper # because they have updated the usernames.  

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @dinerotres Thanks for submitting. We have a couple of existing request which may be similar depending on what you'd like to delete. First is the one for deleting history #516 , then there is another for deleting blocks #50

If you could please give one of those a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates on those threads, so stay tuned! 

We'll be closing this as a duplicate.
