### ISSUE TITLE
Duplicate tab!

### ISSUE THREAD

**Issue by cody-ta** [warpdotdev/Warp#3842]
### Discord username (optional)

codyslexia

### Describe the solution you'd like?

```Text
Duplicate tab, preserve `PATH` where I don't have to type `cd ...`.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @cody-ta We already have a request tracking this over at #1879

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
