### ISSUE TITLE
Sonoma 14.2 - Warp error on startup

### ISSUE THREAD

**Issue by Alphaegen** [warpdotdev/Warp#3843]
### Discord username (optional)

alphaegen

### Describe the bug

Getting a "Warp quit unexpectedly" error on startup in the new MacOS update.

### To reproduce

Install Warp using either Brew or using the default install method (I tried both).

### Expected behavior

It should startup.

### Screenshots

ChatGPT says the following about the content of the error:
<img width="792" alt="image" src="https://github.com/warpdotdev/Warp/assets/45634800/d357439b-9f85-4811-b27a-d4905b207cbb">

### Operating system

MacOS

### Operating system and version

Sonoma 14.2 (23C5030f)

### Current Warp version

Stable 0.1.0 (20231101.192106)

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by Alphaegen** [comment]
I can add the full error log if needed.

**Comment by Alphaegen** [comment]
Full error log:
https://pastebin.com/LP2z7sbN

**Comment by Alphaegen** [comment]
Figured it out! Seems having SIP disabled breaks almost every single app on Sonoma 14.2.

**Comment by dannyneira** [comment]
Thanks for letting us know @Alphaegen. feel free to ping us if the issue returns with SIP enabled.
