### ISSUE TITLE
Open Tab or Window here

### ISSUE THREAD

**Issue by Micnubinub** [warpdotdev/Warp#3844]
### Describe the solution you'd like?

```Text
Open tab or window here works when you right click a folder, but doesn't show up in the context menu when you right click an empty area in a folder in Finder... Could you please add that
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @Micnubinub Thanks for submitting. So there is currently an option to [open from finder](https://github.com/warpdotdev/warp/issues/102) `right-click > services` sub-menu to see the options. 

![CleanShot 2023-11-08 at 09 37 32@2x](https://github.com/warpdotdev/Warp/assets/16809145/f9254c62-77b4-490e-a70e-c5d5a8baee41)

You can also Drag and drop a folder or file onto the Warp dock icon to open a new tab in this directory.

Closing as the ["Open from Finder"](https://docs.warp.dev/features/files-and-links#files-and-links-1) feature exists, but please note there is an issue with "Open new Warp window" (it opens a new tab instead), which we are working on and you can track here https://github.com/warpdotdev/Warp/issues/3825

**Comment by Micnubinub** [comment]
Hey, thanks for the answer... it looks like to me you have right clicked a folder (highlighted in red), my request was for clicking empty space (highlighted in teal)
<img width="1132" alt="image" src="https://github.com/warpdotdev/Warp/assets/4921356/f32608ff-26c0-4b15-9b88-23fb54353f8c">
