### ISSUE TITLE
Option key is meta enabled but not working

### ISSUE THREAD

**Issue by voodoojunk** [warpdotdev/Warp#3845]
### Describe the bug

Same exact issue as #3018
But contrary to what was stated on the issue, this was not resolved 
I don't have this problem on iterm2

### To reproduce

See issue #3018

### Expected behavior

See issue #3018

### Screenshots

See issue #3018

### Operating system

MacOS

### Operating system and version

see Issue #3018

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @voodoojunk Thanks for letting us know. Are you using an international text input source by any chance, or just the ABC?

![CleanShot 2023-11-09 at 10 33 25](https://github.com/warpdotdev/Warp/assets/16809145/6fb9d578-2f03-431c-bdc3-a7327377dba5)

**Comment by voodoojunk** [comment]
Just ABC

**Comment by voodoojunk** [comment]
To be clear,  I DO have other languages enabled,  but this issue happens while I'm on ABC
