### ISSUE TITLE
Do not scroll the window if the view is not at the bottom

### ISSUE THREAD

**Issue by benediktms** [warpdotdev/Warp#3849]
### Describe the solution you'd like?

```Text
I woudl like warp to not move the buffer if new input is received, if I am currently already scrolled up. I think this is the default behaviour in most other terminals.
```

### Is your feature request related to a problem? Please describe.

```Text
If I am scrolling through a large output, for example the live log tail of a running web server and new output is being displayed, warp will automatically scroll the view to accomadate the new information. This makes reading logs basically impossible on a live server since you will have to continiously scroll back up to find where you were.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request! I think we may have a duplicate request, I'll mark here if there is one.

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Hey @benediktms As far as I know, when you're tailing a log for example, if you pause scrolling midway, the new lines will not move the buffer. Please try `tail -f ~/Library/Logs/warp.log`, then click around in the Warp Drive UI, and see if this works. 

https://github.com/warpdotdev/Warp/assets/16809145/b7af2eeb-8c2c-494c-9976-3f43fad475a0

Please let us know if that existing feature meets your use case. If not, please let us know how we could improve the current experience.

**Comment by benediktms** [comment]
Yes this seems to work for me now. It must have been an issue on my end. Sorry for the noise! Closing this.
