### ISSUE TITLE
Autocomplete Suggestiong don't work with Multipass

### ISSUE THREAD

**Issue by DJ90864** [warpdotdev/Warp#3850]
### Describe the solution you'd like?

```Text
It would be great if the smart suggestions or autocomplete features would work even when running Ubuntu instances with Multipass on Mac.
```

### Is your feature request related to a problem? Please describe.

```Text
When I run Ubuntu shell with Multipass on Warp, the autocomplete feature doeesn't work when Ubuntu shell starts. It start behaving like a normal terminal without aby of the smart suggestions that work with Warp
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Also, please make sure you have background blocks enabled ( in the Warp Mac menu > Blocks > "Show background command blocks")

This may help with the issue

**Comment by zachbai** [comment]
Hey @DJ90864, are you using `multipass` with Warp's subshells integration? When working properly, that feature should provide completions/autosuggestions in `multipass` sessions

**Comment by DJ90864** [comment]
@zachbai, thank you for pointing it out. All auto-completions/auto-suggestions work well with multipass now.

**Comment by zachbai** [comment]
Awesome, glad to hear!
