### ISSUE TITLE
Add Host management feature like terminus

### ISSUE THREAD

**Issue by pcccccccccc** [warpdotdev/Warp#3851]
### Describe the solution you'd like?

```Text
I really wish warp can support the host management features like termius. It'll be much more covenient for users if warp can store the passwords and user information of the servers so users can connnect to the server with ssh without using passwords, just simply clicking the button is enough.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @pcccccccccc 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/discussions/442

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
