### ISSUE TITLE
Integrate inshellisense

### ISSUE THREAD

**Issue by hbakhtiyor** [warpdotdev/Warp#3853]
### Describe the solution you'd like?

```Text
Integrate https://github.com/microsoft/inshellisense for auto completion.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hey @hbakhtiyor Thanks for this feature request!

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

Also, we have a related request for supporting shell-based completions you can track here #434.

**Comment by dannyneira** [comment]
Hey @hbakhtiyor The plan is to support missing completions in the near future with a custom completions plugin/extension. This way users can make their own custom completions or add missing ones. We'll post any updated on this thread. https://github.com/warpdotdev/Warp/discussions/652
