### ISSUE TITLE
Other background color for remote servers

### ISSUE THREAD

**Issue by kainbacher** [warpdotdev/Warp#3855]
### Describe the solution you'd like?

```Text
I like to use split panes, great feature. 
But let's say i have 2 panes open, 2 local windows, 2 for remote connections. Sometimes it's a bit hard to see the which window is local and which is remote. Would be great if I can setup differne background colors for local and remote connections. I think then it's clear.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request @kainbacher!

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

Also, we have a related request here for different background/themes per pane/window/tab https://github.com/warpdotdev/Warp/issues/478
