### ISSUE TITLE
Multiple MD Previews on Single Click

### ISSUE THREAD

**Issue by Jonezzyboy** [warpdotdev/Warp#3858]
### Describe the bug

When CMD + Clicking on .md files, it opens two previews of the same file.

### To reproduce

1. Find a markdown file in a directory
2. CMD + Click the .md file
3. Two previews of the file will open

### Expected behavior

Only one preview file should open on a single click.

### Operating system

MacOS

### Operating system and version

14.0.0

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.11.07.08.02.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by longrunningprocess** [comment]
do you happen to know if is there a command line option to get an MD file to open in warp without having to cmd-click or click the "view in warp" link?

**Comment by dannyneira** [comment]
Hi @Jonezzyboy thanks for submitting. I'm not seeing the same issue when you CMD-Click on a .md file only one opens. If you can please submit a video of the issue to help us identify what the bug may be.

@longrunningprocess Opening the files with a markdown viewer like `cat, less, or glow` will trigger a banner to "View in Warp" other than that, there is no command currently to open .MD files in warp other than clicking on them. Please see the docs for more info. https://docs.warp.dev/features/markdown-viewer

**Comment by Jonezzyboy** [comment]
@dannyneira Strangely enough, after a restart of the application it now no longer opens up two previews.

I'm happy to close this issue and will re-open if the bug reoccurs in the future. 😄
