### ISSUE TITLE
Top Find result hidden behind warp command block

### ISSUE THREAD

**Issue by IzakMaraisTAL** [warpdotdev/Warp#3859]
### Discord username (optional)

izakmarais#4489

### Describe the bug

When using find to search for text in long output, the top result will be hidden behind the warp 'command' pane:

![image](https://github.com/warpdotdev/Warp/assets/103260585/adc5bcd9-e395-4f5f-aec7-69c27eb96ea1)

This only happens when jumping between multiple results with the next/down arrow, not with the up arrow:

https://github.com/warpdotdev/Warp/assets/103260585/c87d5f69-9b7e-4ee1-b4d4-f0bce2679412

 

### To reproduce

See the video above

### Expected behavior

The find results should be visible after clicking next.

### Operating system

MacOS

### Operating system and version

Ventura 13.4

### Current Warp version

v0.2023.11.07.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @IzakMaraisTAL thanks for submitting. As a temporary workaround, you can disable [sticky command header](https://docs.warp.dev/features/blocks/sticky-command-header).

We're tracking this issue over at #3214 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
