### ISSUE TITLE
Ability to opt out

### ISSUE THREAD

**Issue by optimizasean** [warpdotdev/Warp#3860]
### Discord username (optional)

optimizasean#0000

### Describe the solution you'd like?

```Text
Ability to selectively opt-out of AI, Warp Drive, ... cloud/network advanced features.

Not everyone may want AI - another sub-request for AI would be to allow people to use their own OpenAI tokens and config. This would allow us to use as many AI requests as desired since we can only pay for 100 from the Teams subscription or to maintain control over their own AI usage (and potentially integrate other LLMs instead such as local ones).
```

### Is your feature request related to a problem? Please describe.

```Text
By opt-out I mean specifically flip a config switch to disable it. I don't use many cloud features and specifically would rather disable AI than have it and not use it.

The Warp drive is nice (personally speaking) but I would also like the freedom to turn it off.

Also the ability to turn off the shared blocks feature since I would want to be sure I don't accidentally share something I don't want to share.

Without the ability to control my data and network access/usage, as much as I like warp and am excited for its future, I can't use this terminal.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by optimizasean** [comment]
Excellent tool, but the ability to control and disable network features is important, especially for those with metered network, limited bandwidth, critical/proprietary business use, and so on.

**Comment by dannyneira** [comment]
Hey @optimizasean Thanks for submitting this. We've received similar requests in the past. That being said, most standard terminal features work when using Warp offline. So a workaround for now would be to login to Warp, then block `app.warp.dev` on your firewall and it should in effect "disable" those online features. https://docs.warp.dev/help/using-warp-offline

We already have a request tracking disabling AI over at #2808, as well as another tracking offline mode #900

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
