### ISSUE TITLE
Open Source future plans (FOSS)

### ISSUE THREAD

**Issue by optimizasean** [warpdotdev/Warp#3861]
### Discord username (optional)

optimizasean#0000

### Describe the solution you'd like?

```Text
Will this tool ever have the code open source?

It would be very nice both to audit for those concerned with security implications and also for those who could contribute, propose and assist in developing new features, aid in bughunting and patching, or identify performance optimizations!
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @optimizasean 

We already have a request tracking this over at #400

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
