### ISSUE TITLE
swipe right/left should lead to terminal tab switch

### ISSUE THREAD

**Issue by gajanand-jm** [warpdotdev/Warp#3864]
### Describe the solution you'd like?

```Text
swipe right/left should lead to terminal tab switch
```

### Is your feature request related to a problem? Please describe.

```Text
have to click on a terminal tab to move there
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @gajanand-jm as a workaround you can move a Tab to the Left or Right with `CTRL-SHIFT-LEFT` or `CTRL-SHIFT-LEFT`. See [Tabs doc for more](https://docs.warp.dev/features/windows/tabs).

We already have a request tracking this over at #https://github.com/warpdotdev/Warp/issues/582

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
