### ISSUE TITLE
Reduce scrolling speed

### ISSUE THREAD

**Issue by thistlillo** [warpdotdev/Warp#3865]
### Describe the solution you'd like?

```Text
Please reduce the scrolling speed in everything contained in the Settings modal dialog window.

Using
Mac OS Sonoma 14.0

Warp v0.2023.11.07.08.02.stable_00
```

### Is your feature request related to a problem? Please describe.

```Text
Scrolling speed in everything inside of the Settings dialog is too fast.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by szgupta** [comment]
Hey, sorry for the poor experience here. This will be fixed in tomorrow's release (11/16/2023)!

**Comment by dannyneira** [comment]
@thistlillo We've normalized the scrolling speed across all scrollbars in the latest version of Warp. Closing as resolved, but please let us know if there are any issues with the fix.

**Comment by thistlillo** [comment]
> Hey, sorry for the poor experience here. This will be fixed in tomorrow's release (11/16/2023)!

Thanks! But the experience was great even with the fast scrolling...
