### ISSUE TITLE
Sub-shell is hidden under the main shell block after clearing the screen

### ISSUE THREAD

**Issue by EslamElHusseiny** [warpdotdev/Warp#3866]
### Describe the bug

I've noticed a few of sub-shells gets hidden behind the main shell block after clearing the screen.

As an example, `ipython` I have to press enter three times to get the sub-shell visible 

### To reproduce

open `ipython` , clear the screen "eg. control + l" , try to type anything. 

### Expected behavior

The sub-shell shouldn't be hidden under the main shell block 

### Screenshots

![Screenshot 2023-11-15 at 2 07 54 pm](https://github.com/warpdotdev/Warp/assets/910187/a8ad6782-0521-4c16-b006-b58afe94c09f)
![Screenshot 2023-11-15 at 2 08 04 pm](https://github.com/warpdotdev/Warp/assets/910187/7608b1d9-ae6a-44f6-a313-828fee7f2f25)
![Screenshot 2023-11-15 at 2 08 11 pm](https://github.com/warpdotdev/Warp/assets/910187/9f063e60-5f6e-463f-944d-f214e5abf652)

### Operating system

MacOS

### Operating system and version

14.1.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2023.11.07.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @EslamElHusseiny 

We're tracking this issue over at #3214 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
