### ISSUE TITLE
launch configs hot key doesn't auto focus

### ISSUE THREAD

**Issue by danny-does-stuff** [warpdotdev/Warp#3867]
### Describe the bug

when I open the launch configs tool using `cmd-ctrl-L`, it doesn't not auto focus on the launch configs search. This used to work great, but now you have to click into the search bar before you start typing in the search

### To reproduce

1. `cmd-ctrl-L`
2. The focus is still in the terminal. You can tell by typing

### Expected behavior

1. `cmd-ctrl-L`
2. The focus is in the launch config search

### Screenshots

![no auto focus](https://github.com/warpdotdev/Warp/assets/11875246/02901835-8ac1-489b-9030-1d8f61625bb8)

### Operating system

MacOS

### Operating system and version

14.0.0

### Current Warp version

v0.2023.11.07.08.02.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Maybe a week ago?

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by danny-does-stuff** [comment]
Oops sorry this is a duplicate of #3833

**Comment by dannyneira** [comment]
We're tracking this issue over at #3833 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
