### ISSUE TITLE
SSHing to the same machine more than once

### ISSUE THREAD

**Issue by benjibee** [warpdotdev/Warp#387]
### Describe the bug

If you log in to the same machine more than once, you will notice this following message:

```shell
ControlSocket /Users/<your-username>/.ssh/bad89d3452f63f92c2a9a56e8d78b02dfebacf1e already exists, disabling multiplexing
```

### To Reproduce

Steps to reproduce:
1. SSH into a remote client
2. Disconnect
3. Connect again to same client
4. See error `ControlSocket /Users/<your-username>/.ssh/bad89d3452f63f92c2a9a56e8d78b02dfebacf1e already exists, disabling multiplexing`
5. Attempt to use use path completion, etc. to no avail

### Expected behaviour

Multiplexing should be enabled

### Operating System

MacOS 12.0.1

### Additional context

This error is listed on the [Known Issues page](https://docs.warp.dev/help/known-issues) of Warp's documentation but it has no corresponding issue or timeline. The document was updated 2-months ago but it says it will be fixed "soon". Most of my work in the terminal is on remote machines and this renders Warp nearly useless for me.

**Comment by elviskahoro** [comment]
@benjibee 
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
