### ISSUE TITLE
Prompt falls below the Fold

### ISSUE THREAD

**Issue by krlmrr** [warpdotdev/Warp#3871]
### Discord username (optional)

karlm89

### Describe the bug

When you set the "line height" to higher than default. The prompt falls below the fold. (also the previous prompt shows up at the top)

### To reproduce

1. Open Warp 
2. Click "Settings > Appearance > Line Height"
3. Set line height to anything higher than 1.2
4. Run "brew update"
5. Notice the prompt falls below the fold.

### Expected behavior

I would expect that when the line height is set it would be respected and the prompt to always be shown.

### Screenshots

https://github.com/warpdotdev/Warp/assets/34105282/fa85bbc3-b84a-46c8-8a84-80b200ac9abc

### Operating system

MacOS

### Operating system and version

14.1.1 (23B81)

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2023.11.07.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for lsubmitting @krlmrr, this is a known issue that I think we're working to improve in an upcoming release (no official eta). We'll post any updates on this thread.

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
hey @krlmrr, thanks for submitting! This has been resolved in the latest version of Warp.

https://github.com/warpdotdev/Warp/assets/16809145/e350268d-43d6-4bd8-b924-4c84f84313ff

Closing as completed, but please update and let us know if the issue persists.

**Comment by krlmrr** [comment]
Just a heads up, the original issue is solved. However the secondary issue hasn't been. The margin is still being added to the top but not the bottom.

in Warp
<img width="1000" alt="image" src="https://github.com/warpdotdev/Warp/assets/34105282/1f99be4d-5c4b-441a-bc59-1cb1218ca4da">

in iTerm2
<img width="1318" alt="image" src="https://github.com/warpdotdev/Warp/assets/34105282/bd826671-7909-4b5b-8c75-79c055a0fe54">

**Comment by dannyneira** [comment]
heard, may you please open a new issue for that and please let us know if the screenshot is vim/neovim or some custom prompt.

**Comment by krlmrr** [comment]
Sure thing.
