### ISSUE TITLE
Tabs grouping

### ISSUE THREAD

**Issue by toondaey** [warpdotdev/Warp#3873]
### Describe the solution you'd like?

```Text
it would be nice to have the ability to group tabs so they can be moved around easily. I find that I use this a lot due to Neovim being my main IDE and I usually have two tabs open (IDE and terminal) for each projects.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @toondaey 

We already have a request tracking this over at #2314 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
