### ISSUE TITLE
Colors in the dark theme are weird

### ISSUE THREAD

**Issue by filipsworks** [warpdotdev/Warp#3877]
### Describe the bug

The colors in the dark theme:
![image](https://github.com/warpdotdev/Warp/assets/47939098/b3b06db8-d2d3-4217-959c-3129394a656d)
Are washed out in comparison to light theme:
![image](https://github.com/warpdotdev/Warp/assets/47939098/83c9787b-820b-4274-90ef-942a1beaa9fb)

### To reproduce

Just open the warp, use neofetch or see p10k prompt.

### Expected behavior

The theme shouldn't affect the colors

### Operating system

MacOS

### Operating system and version

14.1

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by szgupta** [comment]
Hi @filipsworks, changing your theme _will_ change the ANSI escape colors (which is the reflected in the color palette you're seeing). If you wanted to create your own theme with a custom configuration (e.g. colors, background, etc.) , you can do so using [Custom Themes](https://docs.warp.dev/appearance/custom-themes)!

**Comment by dannyneira** [comment]
Closing as this is intentional behavior, but please feel free to let us know if there are any issues with custom themes you've created.
