### ISSUE TITLE
Context menu is not being drawn over the window

### ISSUE THREAD

**Issue by filipsworks** [warpdotdev/Warp#3878]
### Describe the bug

When trying to use the standard 24-25 lines terminal height - it becomes clear that the right click menu is being drawn inside the warp's window instead of over it. There is also no scroll behavior so some options becomes inaccessible.

### To reproduce

Open warp.
Squish window's height to accommodate 24 line of terminal's output.
Right click in a non-prompt block.
![image](https://github.com/warpdotdev/Warp/assets/47939098/5575bd3d-ceed-40aa-8fff-7fba10ea68db)

### Expected behavior

Context menu should be drawn over the window - don't do that inside of the window

### Operating system

MacOS

### Operating system and version

14.1

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @filipsworks We could certainly improve this menu for smaller terminal windows. We'll post any updates on this thread.

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.
