### ISSUE TITLE
Referral Count does not increase

### ISSUE THREAD

**Issue by nagashi** [warpdotdev/Warp#3879]
### Describe the bug

When I invite friends to Warp, the current referrals count does not increase.  It's still listed at 0.

### To reproduce

1. Go to settings.  2.  Click Referrals  3. Enter an email address.  4.  Click send.

### Expected behavior

For every time I click the send button with a valid email, I expect to see the current referrals count increase by one.

### Operating system

MacOS

### Operating system and version

14.0.0

### Shell Version

zsh

### Current Warp version

v0.2023.11.14.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

none

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @nagashi Thanks for submitting. We now only count a user who onboards onto Warp as a real referral. We have to implement this system to prevent recent abuse of the system. Please see more on the referral system in our docs. https://docs.warp.dev/getting-started/refer-a-friend#faqs

Closing as this isn't a bug, but the way the system is designed ( to prevent abuse )

**Comment by nagashi** [comment]
Thanks Danny.CEO’Riley On Nov 17, 2023, at 13:27, Danny Neira ***@***.***> wrote:﻿
Hi @nagashi Thanks for submitting. We now only count a user who onboards onto Warp as a real referral. We have to implement this system to prevent recent abuse of the system. Please see more on the referral system in our docs. https://docs.warp.dev/getting-started/refer-a-friend#faqs
Closing as this isn't a bug, but the way the system is designed ( to prevent abuse )

**Comment by RawSmokeTerribilus** [comment]
sorry for spamming this issue, i installed warp on rhel two days ago and i was so shocked by the amazing performance that i became a fan. as any other fan, i want my stickers lol. so, i am bringing absolutely everyone onboard. That said, my referral count still at 0. I really don´t need an answer and i will review the documentation. i was just willing to inform that even with real people from all around the world using my link it doesn´t count them.
