### ISSUE TITLE
Allow each window to have it's own design/color/font/font size etc.

### ISSUE THREAD

**Issue by mattbaya** [warpdotdev/Warp#3882]
### Discord username (optional)

mattbaya

### Describe the solution you'd like?

```Text
Right now (at least last I checked a few weeks ago) I can change the background design of my windows, or increase/decrease my font size etc but that affects all windows. Prior to using Warp I used iTerm and that app lets me adjust the background color, font size etc for each window... and i can save them too so when I restart it an array of different colored windows appear ec.

What I'd really love is a way to change this from within the terminal, so when I log on to a server I could have my .bashrc script on that server send commands to title the window, adjust the font size and change the background color, so at a glance I'd know that my 'blue windows' are admin servers, green are development etc.
```

### Is your feature request related to a problem? Please describe.

```Text
I tend to have lots of windows open and it gets confusing who is who, especially across 3 monitors.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @mattbaya As a possible workaround, you can set different colors on Tabs. This may help distinguish what you're working on in each Tab. See [Tab docs](https://docs.warp.dev/features/windows/tabs#how-to-use-it).

![CleanShot 2023-11-17 at 12 30 07](https://github.com/warpdotdev/Warp/assets/16809145/7f0e75fd-04c5-401f-b4c4-64da2917b630)

We already have a request tracking custom themes per tab/window/pane over at https://github.com/warpdotdev/Warp/issues/478

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
