### ISSUE TITLE
when I enter `ipython` and press `ctrl-l`, the warp `PS` blocks the prompt at the top

### ISSUE THREAD

**Issue by loftusa** [warpdotdev/Warp#3883]
### Describe the bug

As you can see in the screenshot below, my python cursor prompt is blocked by the thing at the top after entering ipython and pressing ctrl-l.

For the same reason, in the ipython environment, I can scroll down such that the prompt at the top overlaps with my code.

### To reproduce

1. open `ipython`
2. press `ctrl-l`

### Screenshots

<img width="751" alt="Screenshot 2023-11-17 at 7 08 10 AM" src="https://github.com/warpdotdev/Warp/assets/12386450/19e9dfc1-9556-48f8-a60e-2e421d8576b2">

<img width="437" alt="Screenshot 2023-11-17 at 7 10 20 AM" src="https://github.com/warpdotdev/Warp/assets/12386450/05712727-f15c-43d6-b21f-78fbf958369e">

### Operating system

MacOS

### Operating system and version

14.1.0

### Current Warp version

v0.2023.11.14.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @loftusa This is a known issue with the Sticky Command header. As a temporary workaround, you can disable [sticky command header](https://docs.warp.dev/features/blocks/sticky-command-header) in `Settings > Features > General`.

We're tracking this issue over at # and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
