### ISSUE TITLE
incomplete git diff autocompletion

### ISSUE THREAD

**Issue by that70schris** [warpdotdev/Warp#3889]
### Describe the bug

`git diff` just shows hashes and does not include branches or tags as autocomplete options

`git difftool` shows `git` autocompletion options rather than branches, tags, or hashes

### To reproduce

1. type `git diff` or `git difftool`
2. hit `space`
3. notice the autocomplete options available

### Expected behavior

I would expect, branch, tags, and hashes to show (in that order) as options in the autocomplete dropdown

### Screenshots

![PixelSnap 2023-11-20 at 12 02 09](https://github.com/warpdotdev/Warp/assets/1817159/d42815a7-20da-4c68-8221-fd00bf08615c)

![PixelSnap 2023-11-20 at 12 02 23](https://github.com/warpdotdev/Warp/assets/1817159/513550a5-bd1f-43f1-ab7e-6802510141b8)

### Operating system

MacOS

### Operating system and version

14.1.1

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Current Warp version

v0.2023.11.14.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @that70schris Sorry about the blocker. As of Warp version [v0.2022.06.06.09.05](https://docs.warp.dev/getting-started/changelog#2022.06.08-v0.2022.06.06.09.05), modified files are now included (in addition to commit SHAs) for `git diff`. Tags and branches aren't included in the auto-suggestions for `git diff` and `git log`, but you can manually type them in as a workaround and it should show the appropriate changes.

We're tracking this issue over at #3805 and would appreciate it if you could :+1: and subscribe there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
