### ISSUE TITLE
Support to delete selected block

### ISSUE THREAD

**Issue by nguyenduyminhthong** [warpdotdev/Warp#3890]
### Discord username (optional)

nguyenduyminhthong

### Describe the solution you'd like?

```Text
Warp supports the CMD + K shortcut to clear all blocks in the pane; however, it doesn't have the option to delete a selected block.

Currently, I use a filter to temporarily "delete" the unwanted block without losing logs from older blocks.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @nguyenduyminhthong 

We already have a request tracking block deletion over at #50 ( we also have a related one for block folding at #23 )

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
