### ISSUE TITLE
Global hotkey window switching to non-main screen randomly

### ISSUE THREAD

**Issue by vvaidziulis** [warpdotdev/Warp#3891]
### Describe the bug

Scenario: mac built in display + external display
Settings: global hotkey: pin to right: main screen
I use global hotkey to access warp, and when the warp is started it works like a charm for some time, meaning that global hotkey opens warp on the main screen (my main screen is set to be external display). However, after some random time and same setting, warp is switched to non-main screen (mac built in display).

### To reproduce

1. Load warp with two screens (built in + external. make external main screen and warp to open on main screen with global hotkey)
2. Press global hotkey.
3. Warp is opened in main screen (external)
4. ... some random time passed
5. Press global hotkey.
6. Warp is opened on the built in display (which is not main)

### Expected behavior

Warp opening on main screen every time.

### Operating system

MacOS

### Operating system and version

14.0.0

### Shell Version

3.2.57(1)-release

### Current Warp version

v0.2023.11.14.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @vvaidziulis As far as I'm aware, this is a known issue with the hotkey window after sleep(or at random time), not going back to the correct screen when set to "main". As a workaround, you can go to settings, set open to active screen, toggle twice, and change the setting back to main.

We're tracking this issue over at #3275 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug.

We'll be closing this as a duplicate.
