### ISSUE TITLE
If the App is "Keep in Dock" after the update a new icon is created.

### ISSUE THREAD

**Issue by DiegoGLagash** [warpdotdev/Warp#3893]
### Describe the bug

When the App is "Keep in Dock" it works great, but after the app is updated a second icon appears.

### To reproduce

- Start the application.
- Alt-Click on the App icon and select "Keep in Dock"
- Wait for a new version to be anounced on the app
- After the update, two icons will appear in the Dock.

### Expected behavior

Only a single icon in the Dock.

### Operating system

MacOS

### Operating system and version

Ventura 13.5.2

### Shell Version

zsh 

### Current Warp version

v0.2023.11.14.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @DiegoGLagash 

We're tracking this issue over at #2824 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
