### ISSUE TITLE
Support execute the same command in multiple Windows

### ISSUE THREAD

**Issue by daolou** [warpdotdev/Warp#3895]
### Describe the solution you'd like?

```Text
Like iterm2, though hotkey `cmd + shift + i`, could execute the same command in multiple Windows
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by daolou** [comment]
I see it, `cmd+option+i`

![image](https://github.com/warpdotdev/Warp/assets/22312092/65b9b010-2f57-4d88-9294-d4f35307cd12)

**Comment by dannyneira** [comment]
Yes! at Warp, we call this feature Synchronized inputs, please learn more about it here. https://docs.warp.dev/features/entry/synchronized-inputs
