### ISSUE TITLE
parsing error in theme file breaks theme loading, no error message

### ISSUE THREAD

**Issue by jvantuyl** [warpdotdev/Warp#3896]
### Describe the bug

Failure to parse a theme file appears to fail silently.  Specifically, a trailing space on a color entry seems to do it.

UX is pretty ugly as they have no indication what's going on... their theme just never appears.  I haven't verified if this impacts loading other themes.

### To reproduce

Follow steps in bug #3884.

### Expected behavior

An error message (somewhere) that theme loading failed and some diagnostic info needed to fix it.

### Operating system

MacOS

### Operating system and version

MacOS Sonoma 14.1.1

### Current Warp version

v0.2023.11.14.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
thanks for submitting this. That totally makes sense that we could improve the messaging around failed custom themes. Or better yet improve the UI/UX for creating custom themes in general.

We'll close this as a duplicate and track on #3884 and note that we should improve parse error messaging.
