### ISSUE TITLE
Allow to remove output from terminal

### ISSUE THREAD

**Issue by patrykbart** [warpdotdev/Warp#3899]
### Describe the solution you'd like?

```Text
It would be great to have option `Remove` under `Copy Command`, `Copy output`, `Copy both`.
```

### Is your feature request related to a problem? Please describe.

```Text
I want to keep multiple logs in terminal but I had an error, I can't remove it from terminal
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @patrykbart 

We already have a request tracking the ability to delete or remove a block over at #50

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
