### ISSUE TITLE
DUP: Duplicate of #415 - Add a setting for controlling the tab behavior in completions

### ISSUE THREAD

**Issue by zachlloyd** [warpdotdev/warp#39]
Right now hitting tab with the completions menu open, selects the completion and enters it in the input box.

In typical shells, hitting tab will cycle the options instead.

Curious if the community has a strong preference on:
1) The default behavior
2) Whether this should be a setting

**Comment by elviskahoro** [comment]
A vote for 2.

**Comment by elviskahoro** [comment]
Here are all the github issues i've seen relating to tab and or autocompletion:
        https://github.com/warpdotdev/warp/issues/147
        https://github.com/warpdotdev/warp/issues/149
        https://github.com/warpdotdev/warp/issues/150
        https://github.com/warpdotdev/warp/issues/133
        https://github.com/warpdotdev/warp/issues/142
        https://github.com/warpdotdev/warp/issues/85
        https://github.com/warpdotdev/warp/issues/59
        https://github.com/warpdotdev/warp/issues/167
        https://github.com/warpdotdev/warp/issues/24

**Comment by elviskahoro** [comment]
Attached the relating github issues to help with the implementation and show that it isn't a "trivial toggle".

**Comment by elviskahoro** [comment]
The most recently posted issue was 173. Just posting this as a bookmark / timestamp of sorts.

**Comment by elviskahoro** [comment]
Closing in favor:
- #415
