### ISSUE TITLE
Multiline copy outputs as separate lines

### ISSUE THREAD

**Issue by thewoolleyman** [warpdotdev/Warp#390]
### Describe the bug

```shell
Multiline output of long running (REPL) command is copied as multiple separate lines.
```

### To Reproduce

Steps to reproduce:
1. Run a multiline command in a REPL (e.g. irb in Ruby).
2. Try to copy and paste the command again.

### Expected behaviour

```shell
3. Expected: pastes as a single line
4. Actual: Pastes as multiple input lines.
```

### Screenshots

```
irb
irb(main):001:3" '<p data-sourcepos="1:1-1:69" dir="auto"><a class="no-attachment-icon gfm" href="http://localhost/uploads/aa45a38ec2cfe97433281b10bbff042c/test-
file.png" target="_blank" rel="noopener noreferrer" data-canonical-src="/uploads/aa45a38ec2cfe97433281b10bbff042c/test-file.png" data-link="true"><img src="data:
image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="test-file" class="lazy gfm" data-src="http://localhost/uploads/aa45a38ec2cfe97433281b
10bbff042c/test-file.png" data-canonical-src="/uploads/aa45a38ec2cfe97433281b10bbff042c"></a></p>'.gsub(r{(href=")(.*)(/test-file.png)},'\1HREF_PREFIX\2')
irb(main):002:3"       ^C
irb(main):001:0' '<p data-sourcepos="1:1-1:69" dir="auto"><a class="no-attachment-icon gfm" href="http://localhost/uploads/aa45a38ec2cfe97433281b10bbff042c/test-

irb(main):002:0' file.png" target="_blank" rel="noopener noreferrer" data-canonical-src="/uploads/aa45a38ec2cfe97433281b10bbff042c/test-file.png" data-link="true
"><img src="data:
irb(main):003:0' image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="test-file" class="lazy gfm" data-src="http://localhost/uploads/aa45a
38ec2cfe97433281b
irb(main):004:3" 10bbff042c/test-file.png" data-canonical-src="/uploads/aa45a38ec2cfe97433281b10bbff042c"></a></p>'.gsub(r{(href=")(.*)(/test-file.png)},'\1HREF_
PREFIX\2')^C
irb(main):001:0>
```

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
Can you drop the screenshots here?

**Comment by thewoolleyman** [comment]
Here's a more simple example, with a very narrow window:

# Copying a single line:
<img width="386" alt="Screen Shot 2021-11-09 at 1 41 24 PM" src="https://user-images.githubusercontent.com/158/141001425-9c0b199b-627c-4c08-861f-dee53519ca2d.png">

# Pastes as multiple lines:
<img width="387" alt="Screen Shot 2021-11-09 at 1 41 46 PM" src="https://user-images.githubusercontent.com/158/141001446-f5b06f0f-ab09-4b2a-b0d7-7557b6a631cc.png">

**Comment by dannyneira** [comment]
@thewoolleyman I can no longer reproduce this issue on the latest version of Warp.

Closing as fixed, but please feel free to reopen if the issue comes up again.

**Comment by felcheck** [comment]
Not sure if its the same issue, but multiline .md copying is being copied with line breaks instead of a continuous string.

<img width="1156" height="304" alt="Image" src="https://github.com/user-attachments/assets/ce1b75ef-f1c8-42da-9f2c-f874e72aeff3" />

I'm having to generate .mds and copy from them so line breaks are not included in the output.
