### ISSUE TITLE
Moving top buttons to left edge in full screen mode

### ISSUE THREAD

**Issue by SUPERustam** [warpdotdev/Warp#3906]
### Discord username (optional)

superustam

### Describe the solution you'd like?

```Text
Just move to left edge all top bar. Problem showed in image
```

### Additional context

<img width="1470" alt="image" src="https://github.com/warpdotdev/Warp/assets/64551202/d0197837-1a7f-48ac-a529-47e11e6f85e8">

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/3369 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by SUPERustam** [comment]
Thanks!
