### ISSUE TITLE
SSH connection exits after every command

### ISSUE THREAD

**Issue by naor-navina** [warpdotdev/Warp#3908]
### Describe the bug

When I SSH to a server, after every command I run, the connection closes.
It doesn't happen when I disable the ssh wrapping or in the normal terminal.
It also didn't happen in the past when I ran it using Wrap, and I did it pretty recently so it only started now.

### To reproduce

1. ssh into a server
2. run any command ("pip install -U pip" for example)
3. connection closed

### Operating system

MacOS

### Operating system and version

MacOS 14.1.1

### Current Warp version

v0.2023.11.14.08.02.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

November 24/23 approx.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @naor-navina Sorry to hear about this new issue. If you can please provide some details on your local and remote machines. 
Local Shell and version:
Remote Shell and version:
Remote OS and version:

Also besides the updates to Warp, has anything else changed in your rc files (either local or remote)?

**Comment by naor-navina** [comment]
It seems to be solved.
I updated to a newer version that wasn't available when I opened the issue, no idea if that's related or not.
Also just for context, I didn't touch any rc files or any type of configuration file, not before the issue nor after.
Thanks anyway.
