### ISSUE TITLE
Warpify shell does not play nice with other terminals UIs (e.g. IntellIJ)

### ISSUE THREAD

**Issue by norswap** [warpdotdev/Warp#3909]
### Describe the bug

Including the "warpify shell" command at the end of `.zshrc` (`printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "zsh"}}\x9c'`) causes the shell to hang when opened with IntelliJ.

Is there a way to avoid this? e.g. a way to detect the shell is run within Warp?

### To reproduce

See above: include warpify shell command at the end of `.zshrc`, open zsh with IntelliJ.

### Operating system

MacOS

### Operating system and version

Ventura 13.4

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.11.14.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by enochCodes** [comment]
to fix this bug use the ssh .zshrc to compile it to binary then use the command to execute the ssh b/c every IDE have there sandbox so use there sandbox

**Comment by zachbai** [comment]
Hey @norswap -- you can gate that snippet in your .zshrc with `if [[ "$TERM_PROGRAM" -eq "WarpTerminal" ]]`. Note that $TERM_PROGRAM is only set in local shell sessions (it won't be set in remote (e.g. ssh) sessions), but sounds like that's not the problematic use case.

**Comment by dannyneira** [comment]
I'm not 100% sure if it should be `-eq` or `==` since I think the former is for number comparison vs string comparison, but I encourage you to try either. You can try something like the following and let us know if helps with the issue:
```
if [[ $TERM_PROGRAM == "WarpTerminal" ]]; then
  # What you want to ENABLE just for Warp here
  printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "zsh" }}\x9c'
fi
```

**Comment by norswap** [comment]
That works perfectly, thanks a lot!

My use case involved warpifying the shell after `exec zsh`, so I had to make it
`exec env -i HOME=$HOME TERM=$TERM TERM_PROGRAM=$TERM_PROGRAM zsh -li`
(just added the `TERM_PROGRAM=$TERM_PROGRAM`, the rest was there before)

I'm going to close this issue, but I would encourage you to add this info to the "Warpify shell" documentation page.
