### ISSUE TITLE
Some keyboard shortcuts cannot be edited

### ISSUE THREAD

**Issue by matzewolf** [warpdotdev/Warp#3912]
### Describe the bug

Some keyboard shortcuts that can be viewed with Command+/ cannot be edited in the settings. At least the commands for Switching to the Next Tab and Previous Tab are affected.

### To reproduce

Go to settings and search for "Switch to Next Tab" or "Switch to Previous Tab". 

### Expected behavior

These shortcuts should be found and editable.

### Operating system

MacOS

### Operating system and version

14.1.1

### Current Warp version

v0.2023.11.14.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @matzewolf The wording we use is a bit different, please search for "Activate Previous Tab" and "Activate Next Tab" and you should find the keyboard shortcuts you're looking for. 

Please see more in our docs. https://docs.warp.dev/features/keyboard-shortcuts#fundamentals
https://docs.warp.dev/features/windows/tabs#how-to-use-it

Closing as this isn't a bug, but please feel free to let us know if you have any issues with changing the keyboard shortcuts.
