### ISSUE TITLE
Terminal get green and not readable on FreeBSD 14 as root when compiling

### ISSUE THREAD

**Issue by rsyncOSX** [warpdotdev/Warp#3913]
### Describe the bug

Terminal is getting green and not readable when compiling Netdata as root on a Raspeberry Pi4 server with FreeBSD 14 installed. Logging on server by ssh, su to root and start compiling Netdata from source
.

### To reproduce

Connect to a FreeBSD server by ssh, su to root, default shell root, compile Netdata as root. On macOS powerlevel10k and oh-my-zsh are installed.

### Screenshots

<img width="1518" alt="Screenshot 2023-11-27 at 18 22 07" src="https://github.com/warpdotdev/Warp/assets/22427340/90d790be-47fb-430c-8d08-77ef478992cd">

### Operating system

MacOS

### Operating system and version

Sonoma

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi, @rsyncOSX This is a known issue with FreeBSD ssh, but as a workaround you can use `/usr/bin/ssh thomas@backup` and it should give you an option to "Warpify" the FreeBSD connection (assuming it's set to one of the supported shells bash/zsh/fish). 

Please see our docs for more https://docs.warp.dev/features/subshells and let us know if that helped with your issue.
