### ISSUE TITLE
Editing the cursor color when customizing theme

### ISSUE THREAD

**Issue by ivan-robert** [warpdotdev/Warp#3920]
### Describe the solution you'd like?

```Text
When customizing theme, I would like to be able to choose the cursor color.
```

### Is your feature request related to a problem? Please describe.

```Text
I have a custom theme, it has a black background with Saitama (OPM) on the right. However, the automatically chosen color for the cursor is a dark purple. Whenever I have to edit text (vim, nano...) my cursor is almost invisible, which is very frustrating
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @ivan-robert!

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/3210

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Hey Folks, this feature has launched with the latest release of Warp.
You can now add `cursor: '#<hex color value>'` to your custom theme yaml files to customize your cursor! Please see an example in our [docs](https://docs.warp.dev/appearance/custom-themes#create-your-custom-theme-manually).

Closing as resolved, but please update and let us know what you think or any issues.
