### ISSUE TITLE
Saved Configurations

### ISSUE THREAD

**Issue by markgarrigan** [warpdotdev/Warp#3923]
### Describe the solution you'd like?

```Text
When I save a configuration it should remember the size of the panes.
```

### Is your feature request related to a problem? Please describe.

```Text
Each time I launch my saved configuration I need to readjust the pane sizes.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @markgarrigan 

We already have a request tracking this over at #1399 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
