### ISSUE TITLE
Open Saved Configuration

### ISSUE THREAD

**Issue by markgarrigan** [warpdotdev/Warp#3924]
### Describe the solution you'd like?

```Text
I'd like to be able to open a saved configuration when no Warp window is present.
```

### Is your feature request related to a problem? Please describe.

```Text
I'm frustrated when I've closed all Warp windows and I try to use CTRL + COMMAND + L to open the configuration chooser. Instead I have to COMMAND + N then CTRL + COMMAND + L to launch the configuration chooser. Then I open the configuration and it opens in a new Warp window. I think it's ok to need the new blank window but it would be nice if the configuration could use that blank window instead of opening in another new window. But, it would also be nice if it didn't need the new blank window at all.

I also realized I can open the configuration chooser when no windows are open by going up to the File menu. But why would I want to use the mouse?? :)
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @markgarrigan!

You can open saved Launch Configurations via [Raycast](https://www.raycast.com/) Extension as a stopgap measure. Please learn more about installation and implementation [here](https://docs.warp.dev/features/integrations-and-plugins#raycast). 

We already have a request tracking this over at #2247 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

We'll be closing this as a duplicate.
