### ISSUE TITLE
ligatures don't work in apps like nvim

### ISSUE THREAD

**Issue by bidjei** [warpdotdev/Warp#3925]
### Describe the bug

ligatures work on the prompt, but not in opened apps

### To reproduce

Add any font patched with Nerd fonts
Verify they work on the warp terminal prompt say ->
Launch nvim and type the same key combo say ->

### Expected behavior

I would expect ligatures to work

### Operating system

MacOS

### Operating system and version

14.1

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @bidjei 

We already have a request tracking this over at #239

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by bidjei** [comment]
thumbed-up, thanks!

**Comment by Damon-GSY** [comment]
any update? I'm just learning the vim this week and found this question....
I have test it for 5 hours and end up with raise an issue on other place :(
