### ISSUE TITLE
context popup menu on a history item

### ISSUE THREAD

**Issue by behumble** [warpdotdev/Warp#3926]
### Describe the solution you'd like?

```Text
I'm having trouble with removing a specific item from shell history.
I believe there should be a way to remove one, but it'll be great if I could right click on an item and choose 'Remove from history'

```
![image](https://github.com/warpdotdev/Warp/assets/16809145/76454613-5031-4cd7-9c12-533963f7a283)

https://photos.app.goo.gl/r5XtiEPHxigWxhS57

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for submitting this @behumble 

We already have a request tracking this over at #516 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
