### ISSUE TITLE
Command Tip covering K9s kubectl exec -it session into a container

### ISSUE THREAD

**Issue by msc-consults** [warpdotdev/Warp#3932]
_Originally posted by @msc-consults in https://github.com/warpdotdev/Warp/issues/2915#issuecomment-1840375272_

Hi, creating a new issue here as my prior comment was against a Closed issue.
I have been experiencing this issue with the Warp Command Tip function covering content, but when exec'ing into a Kubernetes pod/container using K9s after establishing a psql session with a postgres DB instance
See my repeatable steps below:

1. kubectl exec -it into Pod -> container using K9s
2. establish a psql sessions with a postgres database instances from the container
3. ctrl+d to leave the psql session
4. ctrl+d once more to leave the kubectl exec -it session from the container
5. repeating step 1

When you do this the command sticky header blocks the bash prompt of the container.
You can only see the shell prompt if you hit the return key a few times to move the prompt further down the screen

Warp version: `v0.2023.11.28.08.02.stable_00`
K9s version: `v0.28.2`
K8s client version: `v1.28.4`
K8s server version: `v1.20.13`

![image](https://github.com/warpdotdev/Warp/assets/25661431/7ed868ef-1d29-4d02-85fb-b9a4b545cb9d)

Thanks

**Comment by dannyneira** [comment]
Hi @msc-consults As a temporary workaround, you can disable [sticky command header](https://docs.warp.dev/features/blocks/sticky-command-header). The sticky header is what stays on top and covers the text in `k9s` (among other alt-screen apps ).

FYI, we're tracking a similar issue over at https://github.com/warpdotdev/Warp/issues/3214 and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue.
