### ISSUE TITLE
Bug when Copying URL

### ISSUE THREAD

**Issue by avious00** [warpdotdev/Warp#3939]
### Describe the bug

Hey @michlimlim + crew, ran into a bug when trying to use the Copy URL/open link feature. It seems to drop the colon as well as change some characters, leading to this error when I open the link
<img width="1502" alt="Screenshot 2023-12-06 at 4 56 31 PM" src="https://github.com/warpdotdev/Warp/assets/103125634/58c40e94-dd28-4f9a-a3c3-7fbc2eeb9e6a">

Works fine when the URL gets output in Terminal

[Block link](https://app.warp.dev/block/kxN0WrxpJlK2t0A9woyKtC)

### To reproduce

Ran [this command](https://docs.hyperlane.xyz/docs/deploy-hyperlane#3-run-validators-and-relayers)

Can screenshare or drop by (we're in the same bldg as y'all in soho) to help reproduce since this involves some crypto know how

### Expected behavior

Terminal output

<img width="568" alt="Screenshot 2023-12-06 at 4 51 33 PM" src="https://github.com/warpdotdev/Warp/assets/103125634/16b95959-8bca-48c9-98fa-8ad180cb9614">

### Operating system

MacOS

### Operating system and version

14.1.1 (23B81)

### Shell Version

bash 3.2.57

### Current Warp version

v0.2023.10.31.08.03.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @avious00, I was able to somewhat reproduce this by just copying the "Click the link below...URL" portion of your shared block. The URL is highlighted, but CMD-Clicking on it doesn't open in a browser. That being said, there appears to be a possible workaround where you can RIGHT-Click on the URL and "Copy URL". This should parse out the URL correctly.

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by avious00** [comment]
hey @dannyneira to reproduce did you the block link or desktop app? because copy URL doesn't work either on desktop

**Comment by avious00** [comment]
fyi @dannyneira not sure if these are related issues, but defining a fallback function https://github.com/sindresorhus/terminal-link/issues/18#issuecomment-1068020361 seems to have helped with url output

**Comment by daprahamian** [comment]
@avious00 we landed a fix that should address this recently. Are you still seeing this issue when you attempt to open URLs?

**Comment by avious00** [comment]
> @avious00 we landed a fix that should address this recently. Are you still seeing this issue when you attempt to open URLs?

hey Dan, will check tom!

**Comment by dannyneira** [comment]
Hi @avious00 Please update Warp and let us know if this issue persists.
