### ISSUE TITLE
DUP: Duplicate of #210 - Support git config - git checkout alias auto completes with different values

### ISSUE THREAD

**Issue by rdjpalmer** [warpdotdev/warp#394]
### Describe the bug

When using `git checkout` I correctly see autocompletions for all my active branches.

When using my alias, `git co`, I only see autocompletions for file paths.

### To Reproduce

Steps to reproduce:
1. Run `git config --global alias.co checkout`
2. Navigate to a git repo
3. Type `git checkout` and hit tab
4. Then type `git co` and hit tab

### Expected behaviour

```shell
I would expect Warp to take into account my aliases and give the correct autocompletions.
```

### Screenshots

<img width="322" alt="Screenshot 2021-11-10 at 11 02 13" src="https://user-images.githubusercontent.com/2162181/141101646-eb69e592-b91d-49b6-8622-f43dbecf4df2.png">
<img width="422" alt="Screenshot 2021-11-10 at 11 02 02" src="https://user-images.githubusercontent.com/2162181/141101648-8bcfab1d-c641-4dfe-9dd3-4f14c1d2d818.png">

### Operating System

MacOS

### OS Version

12.0.1

**Comment by mikesnare** [comment]
For my use case I'd take this a step further and allow arbitrary aliases.  I'm too lazy even to type `git co` so I have `co` aliased to `git checkout` in the shell, and it'd be nice if I could tell warp -- even via some manual config -- that `co` _means_ `git checkout` for the purposes of completion.
