### ISSUE TITLE
Automatically fill each new line with one character

### ISSUE THREAD

**Issue by hycreezehao** [warpdotdev/Warp#3946]
### Discord username (optional)

coolbreeze

### Describe the bug

I encountered a particularly strange bug: the warp client automatically adds an R letter before each

### To reproduce

1. open warp client
2. Press Enter and an R letter will appear on the left

### Expected behavior

1. open warp client
2. Press Enter. The left side should be empty.

### Screenshots

<img width="706" alt="image" src="https://github.com/warpdotdev/Warp/assets/115966240/b5c8be0e-a7f3-4d3b-837c-7062d8d225a6">

### Operating system

MacOS

### Operating system and version

14.0 (23A344)

### Shell Version

3.2.57

### Current Warp version

v0.2023.12.05.08.02.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

2023.12.06

### Additional context

I did not enter the R letter manually. As long as I start a new line, R will be automatically filled in at the beginning of the command.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by el-esnawy** [comment]
I decactivated `zsh-autocomplete` plugin and it solved it

**Comment by gavzla** [comment]
+1

**Comment by dannyneira** [comment]
Hey folks, sorry to hear about this issue. Warp does tend to generate this kind of bug when there is an unsupported plugin enabled in your dotfiles (`~/.bashrc`, `~/.zshrc`, or `~/.config/fish/config.fish`). Some common culprits are the. `iterm2_shell_integration` or any `autocompletion` plugins. You can disable parts of your dotfiles just for Warp by using this conditional statement:

```
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

```
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here <
end
```
We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by dannyneira** [comment]
hey folks, a [user on Warp discord](https://discord.com/channels/851854972600451112/1182748857713574029/1182830292122214512) with the same issue mentioned they were able to resolve by putting the plugin code in the [conditional above](https://github.com/warpdotdev/Warp/issues/3946#issuecomment-1847796096):

> So for me, this seems to have been caused by znap and/or some plugins installed via znap in my ~/.zshrc. Putting those in the conditional that you had above resolved the issue. No more magically appearing 'R'.

There may be other zsh plugins that causing issues, but the known ones are noted in our docs [here](https://docs.warp.dev/help/known-issues#list-of-incompatible-tools).

**Comment by hycreezehao** [comment]
> I decactivated `zsh-autocomplete` plugin and it solved it

Thank you very much. After disabling the item2 auto-complete plug-in, it has returned to normal.

**Comment by hycreezehao** [comment]
Thank you all very much for your help. The reason is caused by plug-in incompatibility. It has returned to normal after being disabled.

**Comment by Advait-M** [comment]
@hycreezehao @el-esnawy @gavzla - thank you for raising this! Just wanted to note: we've identified the underlying issue and pushed a fix. Please update to `v0.2023.12.12.08.02.stable_04` and let us know if you're still experiencing any troubles!

**Comment by el-esnawy** [comment]
@Advait-M Nice, works fine now
