### ISSUE TITLE
kubectl autocompletion does not work with log command

### ISSUE THREAD

**Issue by sstendal** [warpdotdev/Warp#3958]
### Describe the bug

The kubectl resources autocompletion does not work correctly with the log command.
It seems to work if you tybe "kubectl logs pod" and then tab, but this is not the correct syntax for the log command.
The correct syntax is "kubectl logs \<resource name\>"

### To reproduce

Type one of 
- "kubectl logs" and then \<tab\>
- "kubectl -n \<namespace\> logs" and then \<tab\>

### Expected behavior

Typing "kubectl logs" and then \<tab\> should give resource autocompletion suggestions

### Operating system

MacOS

### Operating system and version

Sonoma 14.1

### Current Warp version

v0.2023.12.05.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @sstendal I was able to reproduce with the steps you provided. I'll let the team know about this feedback, and we'll post any updates on this thread.

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by zcl0621** [comment]
+1

**Comment by cx2c** [comment]
+1

**Comment by ericvai** [comment]
In the age of kubectl, this has to work, otherwise, warp is like a beautiful toy.

**Comment by yura-kutsiy** [comment]
+1

**Comment by rubengmurray** [comment]
None of the kubectl commands autocomplete for me (including this one obviously).

Warp: v0.2024.03.26.08.02.stable_02
macOS Monterey 12.5.1

I use in conjunction with ohmyzsh.

My aliases do work when I run them e.g.

`kgp namespace` works. That's my shorthand for > 'kubectl get pods -n namespace'

**Comment by Aaron-ML** [comment]
Hardly any of the kubectl commands work for me with zsh and warp. Reverted back to iterm, really enjoyed this terminal but not having autocomplete is a productivity killer day to day. 

@dannyneira Any ETA for this? Would be cool if we could even add our own autocomplete logic in the future, as it must be impossible for your team to continually play catch up.

**Comment by dannyneira** [comment]
@Aaron-ML We plan on improving as well as releasing an open sourcing custom completions specs for Warp in the near future (hopefully sometime in 2024 is the roadmap). This would allow users to create their own custom completions as well as improve existing completions specs for `kubectl`, and others.

As a possible stopgap, you can run `zsh|bash|fish` as a subshell and Warp will fall back to shell-based completions.

**Comment by cx2c** [comment]
> @Aaron-ML We plan on improving as well as releasing an open sourcing custom completions specs for Warp in the near future (hopefully sometime in 2024 is the roadmap). This would allow users to create their own custom completions as well as improve existing completions specs for `kubectl`, and others.我们计划在未来改进并发布 Warp 的自定义完成规范的开源版本（希望在 2024 年某个时间点发布路线图）。这将允许用户创建自己的自定义完成，并改进现有的完成规范以及 `kubectl` ，和其他内容。
> 
> As a possible stopgap, you can run `zsh|bash|fish` as a subshell and Warp will fall back to shell-based completions.作为一种可能的权宜之计，您可以将 `zsh|bash|fish` 作为一个子 shell 运行，Warp 将退而使用基于 shell 的自动完成。

I run zsh as a subshell in warp， kubectl logs ....  ，but “(eval):1: _kubectl: function definition file not found”

**Comment by juancarestre** [comment]
+1
kubectl get svc - works
kubectl -n my-namespace get svc - doesnt work

**Comment by dannyneira** [comment]
Thanks for your patience folks, I'll bring this up with the team and see if we can get this on the queue. We'll post any updates.

**Comment by standujar** [comment]
+1

**Comment by alokedesai** [comment]
Hi all, thanks for your patience here. We have someone actively working on this and should have an update on when this will be fixed soon.

**Comment by shaym007** [comment]
+1

**Comment by kopaygorodsky** [comment]
It would be a good idea just to be able to disable autocompletion for some regexp commands maybe and rely on the binary itself.

**Comment by silversoul93** [comment]
+1

**Comment by gangster** [comment]
+1

**Comment by gangster** [comment]
> Thanks for your patience folks, I'll bring this up with the team and see if we can get this on the queue. We'll post any updates.

I just ran into this issue today while evaluating Warp.   Last update was in June.   Any updates on when a fix might land?

**Comment by tlmanz** [comment]
+1

**Comment by avatarushka** [comment]
+1

**Comment by dannyneira** [comment]
Hi folks, the fix for this issue is in the latest version of Warp! 

We're closing as resolved, but please update and let us know of any issues.

**Comment by maxan98** [comment]
Warp completions only work if I put kube config in ~/.kube/config.
If I `export KUBECONFIG=/path/to/config` warp stops suggesting at all

**Comment by zxh326** [comment]
> Hi folks, the fix for this issue is in the latest version of Warp!
> 
> We're closing as resolved, but please update and let us know of any issues.


only fixed kubectl log?

kubectl delete/get/exec cannot work as well


```sh
kubectl get pods <TAB> # work

kubectl get pods prefix<TAB>  # not work

kubectl -n ns delete pods  <TAB> # work

kubectl -n ns delete pods  prefix<TAB> # not work

kubectl delete pods -n ns  <TAB> # not work

kubectl delete pods -n ns prefix<TAB> # not work
```


Version: v0.2024.10.29.08.02.stable_02

**Comment by seemeroland** [comment]
Hi, I put out the fix for the issue in the description. Thanks for reporting these! Known kubectl completion issues on my radar to fix are:

1. Resource names (like after get/delete) are not completing with a prefix
2. Completions don't respect `KUBECONFIG` env var
3. Top level flags like `-n default` break completions if after the resource name. As a workaround, instead of `kubectl get pod -n default <TAB>`, try `kubectl -n default get pod <TAB>` or `kubectl get -n default pod <TAB>`

Please report any other issues you encounter!

**Comment by hmacias-avaya** [comment]
I'm running v0.2025.01.29.08.02.stable_03 and it still does not seem to work.

Doing `kubectl -n namespace get pod <tab>` pops up all the flags (e.g. --all-namespaces, etc) but does not do anything showing current pod names.

Is there a way to get this working?
Alternatively, as several people already asked, is there any way to *disable* warp's autocompletion and rely on the command's built in autocompletion? at least we can fall back to using the already working completions.
