### ISSUE TITLE
Support blocks feature for trzsz-ssh ( tssh ) in search mode

### ISSUE THREAD

**Issue by lonnywong** [warpdotdev/Warp#3960]
### Describe the solution you'd like?

In the shell function `is_interactive_ssh_session`,
change `[[ ${#ARGS[@]} -ne 1 ]]` to `[[ ${#ARGS[@]} -ne 1 ]] && [[ $(command ssh -V 2>&1) != "trzsz ssh"* ]]`:
```sh
is_interactive_ssh_session () {
	ARGS=()
	# ...
	if [[ ${#ARGS[@]} -ne 1 ]] && [[ $(command ssh -V 2>&1) != "trzsz ssh"* ]]
	then
		return 1
	fi
}
```

In the shell function `warp_ssh_helper`, using `-oRemoteCommand` instead.
change `command ssh -o ControlMaster=yes -o ControlPath=$SSH_SOCKET_DIR/$WARP_SESSION_ID -t "${@:1}" "..."` to:
```sh
warp_ssh_helper () {
command ssh -o ControlMaster=yes -o ControlPath=$SSH_SOCKET_DIR/$WARP_SESSION_ID -t -oRemoteCommand="
export TERM_PROGRAM='WarpTerminal'
# ...
" "${@:1}"
}
```

### Is your feature request related to a problem? Please describe.

[`trzsz-ssh ( tssh )`](https://trzsz.github.io/ssh) supports the Warp blocks feature if ssh login directly. But it's not working in `tssh` search mode.

Steps to reproduce:
```
brew install trzsz-ssh
sudo ln -sv $(which tssh) /usr/local/bin/ssh

# It works if ssh login directly
ssh server

#  It's not working in search mode. tssh will enter search mode without any argument.
ssh

# It works with an argument. e.g., there's a server alias in `~/.ssh/config` contains `s`:
ssh s
```

### Additional context

- `tssh` screenshot  without any argument
![tssh](https://trzsz.github.io/images/tssh.gif)

- BTW, `tssh` supports `trzsz ( trz / tsz )` and `lrzsz ( rz / sz )`: https://github.com/warpdotdev/Warp/issues/988#issuecomment-1807060606

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Hi @lonnywong Thanks for submitting such a details feature request!

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by zlsq** [comment]
+1

**Comment by paststrange** [comment]
+1

**Comment by 00arthur00** [comment]
+1

**Comment by fisherwei** [comment]
+1

**Comment by SunDaydream** [comment]
+1

**Comment by gaoxiang0421** [comment]
+1

**Comment by cruii** [comment]
+1

**Comment by fitzf** [comment]
+1

**Comment by lonnywong** [comment]
I figured out another way to support blocks feature in trzsz-ssh ( tssh ) search mode.

1. Before tssh `v0.1.22` is released, install as follows:

    ```sh
    go install github.com/trzsz/trzsz-ssh/cmd/tssh@main
    sudo rm /usr/local/bin/ssh
    sudo ln -sv ~/go/bin/tssh /usr/local/bin/ssh
    ```

2. Add the following shell function definition in your `.bash_profile` ( bash ) or `.zshrc` ( zsh ):

    ```sh
    tssh() {
        if [ $# -eq 0 ]; then
            ssh FAKE_DEST_IN_WARP
        else
            ssh "$@"
        fi
    }
    ```

3. Restart Warp and run `tssh` (without arguments). You will be able to search servers to log in to, and the Warp blocks feature should be supported.

**Comment by XIEJIAHAN** [comment]
+1

**Comment by shanyutou** [comment]
+1
