### ISSUE TITLE
Keyboard Shortcuts Search with Natural Language

### ISSUE THREAD

**Issue by graysoncash** [warpdotdev/Warp#3963]
### Discord username (optional)

grayson.cash

### Describe the solution you'd like?

```Text
I would like to see an enhancement in the Keyboard Shortcuts search functionality for command combinations by searching with natural language. The search functionality should be capable of understanding and finding commands inputted as natural language combinations. For instance, when a user types "command right," the search should be able to interpret this and display the corresponding shortcut, such as "⌘ →". Arc Browser is a great example of this.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
hey @graysoncash Thanks for submitting. So as far as I'm aware, the keyboard shortcut search in the settings or the sidebar allows you to enter the shortcuts in natural language. Please see my demo below and let me know if that helps meet your use case.

https://github.com/warpdotdev/Warp/assets/16809145/06d2096c-a375-4288-9bb5-557a7c745db2

If not, let us know how we could make this experience better.
