### ISSUE TITLE
Troubleshooting addition - Firebase auth flow uses QUIC

### ISSUE THREAD

**Issue by mr-joshcrane** [warpdotdev/Warp#3967]
### Describe the bug

Not a bug as such, more of a suggested troubleshooting tip. 

Users in corporate environments might struggle to complete the user sign in flow because their corp proxy might be blocking the QUIC call made when Firebase auths. 

One easy work around users can implement is to turn off QUIC in the browser. It will then fall back to TCP and will likely start working.

> To do this, in the Chrome address bar type: chrome://flags . Scroll down until you see Experimental QUIC protocol and choose Disabled.

Not a bug in Warp as such, but might be helpful for others 👍 

### To reproduce

1. Be behind a corp proxy that disallows UDP traffic out
2. Attempt to authenticate with OAuth flow
3. If UDP outgoing is dropped, user will see this screen

![image](https://github.com/warpdotdev/Warp/assets/57082182/a0bb1a6b-ee33-4bf2-84c5-e30c03525bb5)

### Expected behavior

FYI only as potential problem and work around

### Operating system

MacOS

### Operating system and version

Any

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by zachbai** [comment]
@mr-joshcrane Thanks so much for filing this - this isn't something we had considered as a possible troubleshooting step.

Out of curiosity, did you come across this fix when encountering a login issue yourself?

**Comment by mr-joshcrane** [comment]
> @mr-joshcrane Thanks so much for filing this - this isn't something we had considered as a possible troubleshooting step.
> 
> Out of curiosity, did you come across this fix when encountering a login issue yourself?

Yeah troubleshooting for another user at work. Great product btw!

**Comment by dannyneira** [comment]
Thanks for this @mr-joshcrane! I've added these troubleshooting steps (along with steps for disabling QUIC on other browsers) to our docs here: https://docs.warp.dev/help/troubleshooting-login-issues#proxies

Closing this issue as resolved!
