### ISSUE TITLE
SSH: somehow, some shell integration is breaking my bash scripts.

### ISSUE THREAD

**Issue by cam-narzt** [warpdotdev/Warp#397]
### Describe the bug

```shell
Warp is somehow breaking the following code in my bash setup files: https://github.com/CamJN/dot-files/blob/master/.bash.d/completion#L15-L32

It results in this error in Warp.app, but not in Terminal.app: `bash: old_filedir: command not found`
```

### To Reproduce

Pull down my dotfiles and install the deps, then start bash in Warp.

### Expected behaviour

```shell
I expect my shell to execute without interference from my terminal emulator.
```

### Operating System

MacOS

### OS Version

11.6.1

**Comment by elviskahoro** [comment]
@cam-narzt 
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
