### ISSUE TITLE
Unable to move / drag the Warp window when "Settings" is open (only some sections)

### ISSUE THREAD

**Issue by nemroff** [warpdotdev/Warp#3973]
### Describe the bug

When the "Settings" is open to the "Appearance" or "Features" sections, the window cannot be moved / dragged.

### To reproduce

1. In a Warp window, open "Settings"
2. Go to the "Appearance" or "Features" section
3. Click-and-drag the window from the top portion of the window (the tab bar area).  Window does not move.

#### Workarounds
- Close "Settings"
- Switch to a different section in "Settings"
- Deactivate the window (or switch to a different app/window), and then click and drag the Warp window.
    - This only works as you are reactivating the window (subsequent attempts to move the window still won't work without deactivating it first)

### Expected behavior

When clicking and dragging the top portion of the window (the tab bar area) the window should move with the cursor.

### Screenshots

https://github.com/warpdotdev/Warp/assets/4434239/3e9bbca7-ac08-44f4-91aa-d5c86a309bc1

### Operating system

MacOS

### Operating system and version

13.6.1

### Current Warp version

v0.2023.12.12.08.02.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I don't know if this is a regression, this is the first time I noticed this.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @nemroff I was able to reproduce the issue. We'll post any updates on this thread.

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by nichoj10** [comment]
Thanks for reporting this issue!! This should be fixed in the latest release: v0.2024.06.11.08.02.stable_01. Please let us know if it isn't!

**Comment by dannyneira** [comment]
Hi @nemroff, This issue has been resolved in the latest version of Warp. Closing as resolved, but please update and let us know if any issues.
