### ISSUE TITLE
Ability to pop out a pane

### ISSUE THREAD

**Issue by Advait-M** [warpdotdev/Warp#398]
### Describe the solution you'd like?

```shell
Ability to pop out a pane into its own terminal window
```

### Is your feature request related to a problem? Please describe.

```shell
I want to be able to expand a terminal pane quickly and then be able to shrink it later, or introduce more related panes in a new window.
```

**Comment by elviskahoro** [comment]
Linking:
- #466
- #58

**Comment by dannyneira** [comment]
We have an issue tracking this here: #623 

Please :+1: and subscribe to that request as it helps us gauge interest. We'll post any updates there.

Closing as duplicate.
