### ISSUE TITLE
CB: input conflict from Oh My Zsh theme

### ISSUE THREAD

**Issue by byronferguson** [warpdotdev/warp#399]
### Describe the bug

```shell
I'm currently using the "avit" theme within Oh My Zsh, and the added details provided git repositories is inserted into the input field. This pollution interferes with inputting new commands without first clearing the input.
```

### To Reproduce

Steps to reproduce:
1. Install Oh My Zsh
2. Update `.zshrc` set the theme: `ZSH_THEME="avit"`
3. Open Warp
4. Navigate to a git repo folder

### Expected behaviour

```shell
Find a way to honor the formatting of the theme, and correctly position the cursor, or ignore additional formatting provided from themes.
```

### Screenshots

<img width="1422" alt="Screen Shot 2021-11-10 at 8 37 44 PM" src="https://user-images.githubusercontent.com/8176629/141227486-0f220e15-b2b0-4409-b5a6-9d98c2af7f7e.png">
<img width="1422" alt="Screen Shot 2021-11-10 at 8 37 38 PM" src="https://user-images.githubusercontent.com/8176629/141227491-1e247ac9-241a-433f-b33a-ffe5310a417e.png">

### Operating System

MacOS

### OS Version

12.0.1

**Comment by nschejtman** [comment]
+1

**Comment by elviskahoro** [comment]
We're going to building our custom prompt. We'll move this discussion to that thread:
- https://github.com/warpdotdev/warp/discussions/422

**Comment by elviskahoro** [comment]
gg
