### ISSUE TITLE
"insert into input" hangs

### ISSUE THREAD

**Issue by stevesmoot** [warpdotdev/Warp#3993]
### Describe the bug

select test, right click, select Insert into Input
popup menu does not go away, 
mouse shortly changes to spinning color wheel (mac)

### To reproduce

see above

### Expected behavior

i believe its supposed to copy and paste

### Screenshots

<img width="329" alt="Screenshot 2023-12-21 at 2 59 35 PM" src="https://github.com/warpdotdev/Warp/assets/14839896/22030a6d-3d6e-4a87-86e9-e2016421444a">
cant capture the cursor of course.

### Operating system

MacOS

### Operating system and version

Sonoma 14.2.1

### Shell Version

3.2.57(1)-release (arm64-apple-darwin23)

### Current Warp version

v0.2023.12.19.08.02.stable_00

### Regression

Yes, this is a new bug

### Recent working Warp date

v0.2023.11.28.08.02.stable_00

### Additional context

I've no idea if its regression/new other than other issues imply it worked for them.  Just ran into it today (and verified multiple times)

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @stevesmoot Thanks for letting us know. I found this was working in a previous version. I'll let the team know and we'll hunt down the possible regression. We'll post any updates on this thread.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
hey @stevesmoot We've fixed this issue with the "Insert into input" in the latest version of Warp. 

Closing as completed. Please update and let us know of any further issues.
