### ISSUE TITLE
建议支持多语言，中文，英文等

### ISSUE THREAD

**Issue by my3188** [warpdotdev/Warp#3997]
### Describe the solution you'd like?

```Text
建议软件本身支持多国家语言
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by OrageKK** [comment]
I think so, too

**Comment by zxlBen-A** [comment]
表示认同这个想法

**Comment by dannyneira** [comment]
Thanks for submitting this @my3188 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/1194

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/1194
