### ISSUE TITLE
输入命令前缀，后面有提示命令使用tab不会自动填充

### ISSUE THREAD

**Issue by zxlBen-A** [warpdotdev/Warp#3998]
### Describe the bug

输入命令前缀，后面有提示命令使用tab不会自动填充，只能使用方向键能填充

### To reproduce

无

### Expected behavior

我期望tab也可以进行命令行的填充

### Operating system

MacOS

### Operating system and version

Debian 11.3

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @zxlBen-A 
如果输入编辑器中有建议（灰色文本），则默认情况下可以使用向右箭头接受它。 如果有完成菜单，您可以按 ENTER 键选择并运行它。
此外，可以在“Tab 键行为”下的“设置”中配置这些快捷键

请在文档中查看有关这两个功能的更多信息。

https://docs.warp.dev/features/command-completions/autosuggestions
https://docs.warp.dev/features/command-completions/completions

关闭，因为有一种方法可以配置此行为。

If there is a suggestion (grey text) in your input editor, you can accept it with the RIGHT-ARROW by default. If there is a completion menu, you can press ENTER to select and run it.
Also, these shortcuts can be configured in Settings under "Tab key behavior".

Please see more about both features in the docs ☝️ 

Closing as there is a way to configure this behavior.

**Comment by zxlBen-A** [comment]
@dannyneira 谢谢指导
