### ISSUE TITLE
Settings menu does not minimize

### ISSUE THREAD

**Issue by yummyweb** [warpdotdev/warp#40]
**Describe the bug**
The bug is basically about the settings menu not minimizing when clicked on the settings icon.

**To Reproduce**
1. Click on the settings icon i.e. three dots.
2. Click on the icon again.
3. The popup menu does not close.

**Expected behavior**
The popup menu should close when clicked on the icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/33229117/126424483-f52d24a4-4fd8-415a-a424-0a4378ba940f.png)

**Desktop (please complete the following information):**
 - OS Version: MacOS Mojave

**Additional context**

**Comment by zheng** [comment]
This should be fixed in the next release later this week!
