### ISSUE TITLE
ssh jumperserver enter key is not working

### ISSUE THREAD

**Issue by ruhengChen** [warpdotdev/Warp#4010]
### Operating System

MacOS

### Operating System and Version

12.6.5

### Local Shell Version

5.8.1

### Remote Shell Version

4.4.20(1)-release

### Warp Version

v0.2023.12.19.08.02.stable_00

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

![2023-12-29 17 35 48](https://github.com/warpdotdev/Warp/assets/20870282/c6019785-869d-4df4-8164-f7e581139de0)

### Include shell xtrace output

nothing

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

Press enter is not working

**Comment by dannyneira** [comment]
Hey @ruhengChen sorry to hear about this. I think the ssh feature may have [issues when using a jump host](https://github.com/warpdotdev/Warp/issues/2100), especially if the jumphost isn't defaulted to one of the supported shells (bash/zsh/fish). please make sure the remote machine and jumphost are set to default shell that is supported (i.e. `chsh -s /bin/bash`) and then on the remote machine, try adding the following to the ~/.bashrc file.

```
printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "bash"}}\x9c'
```

Please learn more about this in our docs and let me know if that helps with the issue. https://docs.warp.dev/features/subshells

**Comment by ruhengChen** [comment]
> Hey @ruhengChen sorry to hear about this. I think the ssh feature may have [issues when using a jump host](https://github.com/warpdotdev/Warp/issues/2100), especially if the jumphost isn't defaulted to one of the supported shells (bash/zsh/fish). please make sure the remote machine and jumphost are set to default shell that is supported (i.e. `chsh -s /bin/bash`) and then on the remote machine, try adding the following to the ~/.bashrc file.
> 
> ```
> printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "bash"}}\x9c'
> ```
> 
> Please learn more about this in our docs and let me know if that helps with the issue. https://docs.warp.dev/features/subshells

added this, but not work

**Comment by ArickNan** [comment]
> jumphost
Hi @dannyneira , I am not able to change the configuration of the jumphost as it is a standard service provided by the company. Is there a way of fixing it?
