### ISSUE TITLE
Allow VIM Normal Mode After Jumping Back to Previous Command

### ISSUE THREAD

**Issue by wenindoubt** [warpdotdev/Warp#4019]
### Describe the solution you'd like?

```Text
Goal: I'd like to modify my previous command using VIM keybindings

- Press `CTRL+p` or `up arrow` to go to the previous command
- Press `ESC` to jump into VIM normal mode
- Make my edits as needed
- Press enter to execute the command
```

### Is your feature request related to a problem? Please describe.

```Text
What is happening:

- Press `CTRL+p` or `up arrow` to go to the previous command
- Press `ESC` to jump into VIM normal mode
- The command disappears!!

If I am re-typing out the previous command or typing in a new command, I can use VIM keybindings with no problem.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for this feature request @wenindoubt!

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
test
