### ISSUE TITLE
No support for rtl languages

### ISSUE THREAD

**Issue by MatanGbr** [warpdotdev/Warp#4029]
### Describe the bug

A text written in an RTL language (such as Arabic, Hebrew, Parsian and more) would display reverserly on Wrap, for instant:

![Screenshot 2024-01-06 at 12 04 39](https://github.com/warpdotdev/Warp/assets/40032902/189582f4-900c-45a5-9bc1-4e953b4e80a3)

This would also happen when reading names or files with interpeters such as Python or Node.

For instance, the original Mac Terminal is displying these rtl strings right:
![Screenshot 2024-01-06 at 12 09 05](https://github.com/warpdotdev/Warp/assets/40032902/a9f33f97-3bca-4c66-8442-f5b140a31f71)

Maybe that is an encoding problem? I couldn't find any solution yet to this bug.

**THANKS!**

### To reproduce

To reproduce, just try to use a string in hebrew, arabic, etc.:
שלום

### Operating system

MacOS

### Operating system and version

sonoma 14.2.1 (23C71)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @MatanGbr We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/3589

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/3589

**Comment by huraimel** [comment]
Detailed enterprise case + reference implementation posted on #3589: https://github.com/warpdotdev/warp/issues/3589#issuecomment-4385149111

**Comment by BSN4** [comment]
this is being fixed in PR #10809, before and after screenshots on the PR, tracking issue is #10355
