### ISSUE TITLE
Autocomplete autosuggestion trigger / mechanism is unintuitive / not obvious

### ISSUE THREAD

**Issue by ShukantPal** [warpdotdev/Warp#403]
### Describe the bug

```shell
When warp suggests a full command, pressing tab doesn't complete it - and so I don't know how to trigger it.
```

### To Reproduce

Steps to reproduce:
1. Type command that you've used historically
2. Warp should suggest completion but you don't know how to trigger it.

### Expected behaviour

Some indication of how to complete the command.

**Comment by ShukantPal** [comment]
<img width="401" alt="Screen Shot 2021-11-11 at 12 52 39 PM" src="https://user-images.githubusercontent.com/22450567/141345838-36bf4e9f-bb13-408c-8d80-bb951b79d8e0.png">

(please allow uploading images in the issues template)

**Comment by elviskahoro** [comment]
FYI: You can complete it using the right arrow! I personally think there's room for adding more ways to follow through though! Thanks for filing this!

**Comment by gennaios** [comment]
cmd-E is a default in Terminal and I think it should also be with Warp.

**Comment by ahmeij** [comment]
Intuitively I try to use `tab` every time I see the grey suggestion

**Comment by elviskahoro** [comment]
@gennaios What does CMD-E do? Plus which terminal are you referring to?

**Comment by gennaios** [comment]
Not at computer at the moment. Referring to Emacs keybindings. Ctrl-A beginning of line, E end. Maybe the mention of cmd was misrecalling. I use iTerm.

**Comment by elviskahoro** [comment]
Added 2022.02.16
CTRL-F now accepts autosuggestions
CTRL-E and CMD-RIGHT accept autosuggestions when at the end of the buffer
