### ISSUE TITLE
Added remote SSH configuration management

### ISSUE THREAD

**Issue by liuyuan199303** [warpdotdev/Warp#4037]
### Describe the solution you'd like?

```Text
It provides sessions management similar to SecureCRT, simple configuration of ssh password login, key login, the existing working mode configuration is very cumbersome, and the use is not simple enough
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by elviskahoro** [comment]
@liuyuan199303 thanks for opening! We're actually gathering feedback in this GitHub discussion:
https://github.com/warpdotdev/Warp/discussions/442

Could you share some of your thoughts and ideas there instead? Going to close this in favor that
