### ISSUE TITLE
Ansi color mode DIM doesn't seem to show

### ISSUE THREAD

**Issue by jwoertink** [warpdotdev/Warp#405]
### Describe the bug

Probably related to https://github.com/warpdotdev/warp/issues/362

When I try to colorize my output, it doesn't render the dim text like it does in other terminals.

### To Reproduce

Write some code with a string, and colorize the string with dimmed output.

```crystal
# in Crystal lang
require "colorize"

puts "should be dim".colorize.dim
```

### Expected behaviour

```shell
The text should be dimmed
```

### Screenshots

With MacOS Terminal
<img width="793" alt="Screen Shot 2021-11-11 at 7 25 54 PM" src="https://user-images.githubusercontent.com/2391/141403949-c75e56c7-8f9e-4e43-b71e-7a22c89bb0c3.png">

With iTerm2
<img width="691" alt="Screen Shot 2021-11-11 at 7 20 11 PM" src="https://user-images.githubusercontent.com/2391/141403445-3aeba0d8-cedb-4d44-846f-5fb28dfb252d.png">

With Warp
<img width="640" alt="Screen Shot 2021-11-11 at 7 20 29 PM" src="https://user-images.githubusercontent.com/2391/141403455-b1e75893-0bb9-48f7-9068-1c8578e6aaad.png">

### Operating System

MacOS

### OS Version

11.6

**Comment by mds1** [comment]
Hey! Just wanted to bump this and see if it can be resolved soon? I often look at data represented as hex, and the tool I use dims the zero bytes which makes things significantly easier to read 🙂

**Comment by elviskahoro** [comment]
@mds1 I don't think this will be tbh

**Comment by mds1** [comment]
Oh, that's pretty disappointing. Any details as to why there's no plans to support this? Is this harder to implement than it sounds?

**Comment by elviskahoro** [comment]
@mds1 oh let me clarify, I don't think it will be fixed SOON. I think the earliest the team could start looking at it is in 3 weeks time.

**Comment by mds1** [comment]
Ahh got it, that's much more reassuring—thanks a lot! 🙂

**Comment by elviskahoro** [comment]
The dim issue has been fixed. But the color contrast settings are still a WIP. We are tracking that in a different issue however. So gonna close in favor #362

**Comment by elviskahoro** [comment]
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">
