### ISSUE TITLE
when using warp to connect remote ssh server, warp would spawn lots of dbus dameon processes on the server

### ISSUE THREAD

**Issue by ipstone** [warpdotdev/Warp#4056]
### Describe the bug

when using warp to connect remote ssh server, warp would spawn lots of dbus dameon processes on the server, to the point that server is no longer accessible (exhaust all connections). 

Not sure if others have experienced the same/similar thing, this really prevents me to use warp to connect to remote servers.

### To reproduce

Connect to remote openssh  server: version 

```
ssh -V
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
```

### Expected behavior

After ssh connection, everything works fine. However, over extended connection time, lots of dbus-daemon processed are spawned. 

### Operating system

Linux

### Operating system and version

CentOS 7; Kernel: 3.10.0-1160.102.1.el7.x86_64

### Shell Version

bash 4.4.23

### Current Warp version

Kernel: 3.10.0-1160.102.1.el7.x86_64

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @ipstone Thanks for submitting. I'll bring this up with the team and we'll post updates on this thread. If possible can you increase the max connections on the remote server as a workaround?

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by ipstone** [comment]
thanks, I think this might be an issue with my system setup, a real old centOS system, with conda installed dbus daemon - so I am closing this issue now, I think it's not worth pursuing this fix.
Thanks @dannyneira and team
