### ISSUE TITLE
Option to disable automatically scrolling down when a running command completes

### ISSUE THREAD

**Issue by nickelization** [warpdotdev/Warp#4066]
### Describe the solution you'd like?

If I start running a command and I only care about the first lines of output, I frequently hit Cmd-UpArrow to scroll to the beginning of the new block and start reading before the command is done running. When the command finishes, though, Warp immediately scrolls down to the bottom of the terminal session, interrupting what I'm doing. I would love to have an option to disable this auto-scrolling behavior.

If you'd like a more concrete example: I frequently re-run `cargo check` to look for new build errors after making a code change, and I like to address them one at a time, starting with the first error it spits out. I typically scroll up to the top of the output right away, but it takes just long enough to run to completion that I'm often interrupted partway through reading that first error.

(Apologies if this already exists - I looked through the settings and the documentation, and couldn't find anything. I also searched through existing feature requests but couldn't find anything like this that anyone's requested.)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for this feature request! 

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by henricook** [comment]
Absolutely, I often have some debug or similar that's printing at the start of a test and I don't care about the stacktrace etc that gets printed at the end. Vs a typical terminal where it won't auto scroll as output occurs if I've scrolled up a little first this is a big frustration for me as a Day 2 Warp user

**Comment by pilgunboris** [comment]
Yes, the current behavior is absolutely annoying and looks like a bug. I can't use Warp because of this.

**Comment by gedhi** [comment]
possible duplicate #610 

but there's a comment
> Hi Folks, quick update on this request. We have made some early progress https://github.com/warpdotdev/Warp/issues/610#issuecomment-1684348612, but will be dedicating more resources to get this over the finish line later this year, most likely Q3 2024. We appreciate your patience with our small (but growing) team and we'll post more updates as we have them.
[link to comment](https://github.com/warpdotdev/Warp/issues/610#issuecomment-2045947569)

**Comment by szgupta** [comment]
Hey y'all, we've changed the default behaviour to _not_ scroll to the end of the blocklist when a command completes. Please update to `v0.2024.09.03.08.02.stable_03` or later to pick up the change :)
