### ISSUE TITLE
Pink screen when warp is updated to recent version 

### ISSUE THREAD

**Issue by surajyste** [warpdotdev/Warp#4086]
### Describe the bug

I just updated the warp version and the screen turned into pink screen when update completed.

### To reproduce

I am not sure of the version but I updated the version around 2:50 PM PST on Jan 18th, 2023.

### Screenshots

<img width="1512" alt="Screenshot 2024-01-18 at 2 50 29 PM" src="https://github.com/warpdotdev/Warp/assets/144290827/d0761ae4-573a-43bf-b0d2-0ea66f62fcef">

### Operating system

MacOS

### Operating system and version

14.2.0

### Current Warp version

v0.2024.01.16.16.31.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
hey @surajyste sorry to hear about this, it seems to have been an issue with a recent upgrade to MacOS affecting other apps, not just Warp. It seems like a [restart of MacOS](https://github.com/warpdotdev/Warp/issues/3604#issuecomment-1718732241) seems to have fixed it for users with this issue.

Please let me know if that helped with your issue or if you still see the pink screen after restart.

**Comment by surajyste** [comment]
oh, restarting helped! Thanks for pointing that out. Closing the issue!
