### ISSUE TITLE
[Warp Drive] Export workflows option to `YAML` files

### ISSUE THREAD

**Issue by l2D** [warpdotdev/Warp#4092]
### Discord username (optional)

l2d

### Describe the solution you'd like?

It would be really helpful if Warp **_could provide an option to export existing workflows_** to `YAML` files, in addition to its current ability to import defined workflows in YAML format. This feature could allow users to export either each workflow or all workflows in a particular directory/teams option.

Docs: https://docs.warp.dev/features/entry/yaml-workflows#creating-custom-workflows
Format: https://github.com/warpdotdev/Workflows/blob/main/FORMAT.md

### Additional context

![2024-01-21T05-26-21_t5mdZ0Qf](https://github.com/warpdotdev/Warp/assets/20911264/66dbf6f8-117c-40b7-a457-f8d400c65e7b)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for suggesting this @l2D It's already part of the plan to include export/import for all Warp Drive objects to prevent vendor lock-in. https://docs.warp.dev/features/warp-drive/workflows#support-for-yaml-workflows

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Soon 🤞 
Dev build preview:
![CleanShot 2024-03-26 at 11 00 17](https://github.com/warpdotdev/Warp/assets/16809145/1be49110-a80b-478d-af16-8e97305dae11)

**Comment by bnavetta** [comment]
This is in Warp as of `v0.2024.04.02.08.02`!
