### ISSUE TITLE
SSH: Make Warp with work zsh via ssh

### ISSUE THREAD

**Issue by zachlloyd** [warpdotdev/Warp#41]
Right now we only support bash over ssh, but we could also support other shells like zsh.

Posting so people can upvote.

Thank you!

**Comment by fishcharlie** [comment]
I'm unsure if this is the same as the issue I'm having. When I SSH into a server, the `.zshrc` file does not get executed. Therefore commands like `nvm` or `node` don't work correctly.

If it's not the same issue I will create another issue for that.

<img width="1016" alt="Screen Shot 2021-10-11 at 2 40 15 PM" src="https://user-images.githubusercontent.com/860375/136853061-9961fdb7-2b5d-4f90-9076-5032bbb949c1.png">

**Comment by dimfeld** [comment]
@fishcharlie I believe it is the same issue, since Warp's wrapped `ssh` is currently hardcoded to run bash in the ssh session.
