### ISSUE TITLE
Shortcut for reopening last closed tab(s)

### ISSUE THREAD

**Issue by assayire** [warpdotdev/Warp#4100]
### Describe the solution you'd like?

It would be great to have a keyboard shortcut to reopen last closed tabs in the closed order. 

This is similar to how it works in browsers. Ctrl/Cmd-T opens new tabs. Hitting Ctrl/Cmd-Shift-T each time reopens the closed tabs in the descending order of closing.

One reason it would be useful in warp is when a tab is closed by mistake and you would like to reopen quickly.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hey @assayire Warp recently implemented this. You can reopen closed tabs with `SHIFT-CMD-T` for up to one minute; Also, you can configure the timeout period or disable this feature in `Settings > Features > Enable reopening of closed sessions`.

https://docs.warp.dev/features/windows/tabs#how-to-use-it

Hope this helps with your use case! Closing as this feature already exists in Warp! :)

**Comment by Aeromix** [comment]
Please make this work multiple times like Chrome. I just lost a tab and whatever I was working on is like gone. Now I need to sift through every conversation. You should also allow showing recent conversations based on activity with View All. 

Or make it like ChatGPT where they are all stored in a sidebar! Why is Warp so dangerous with closing tabs!?!?!? Not cool!!
