### ISSUE TITLE
可以提供中文化吗?

### ISSUE THREAD

**Issue by kefengzhang** [warpdotdev/Warp#4102]
### Describe the solution you'd like?

如题,我的英文很差,所以希望有中文界面

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by cs-regan** [comment]
me too

**Comment by dannyneira** [comment]
Thanks for submitting this @

We already have a request tracking this over at #1823 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Duplicate of #1823

**Comment by kefengzhang** [comment]
OK,感谢你

**Comment by zxj1997-java** [comment]
me too

**Comment by yezhu70** [comment]
me too
