### ISSUE TITLE
New tab is inserted after the current tab instead of at the end

### ISSUE THREAD

**Issue by lzm0** [warpdotdev/Warp#4106]
### Describe the bug

When you have multiple tabs open and create a new tab, the new tab is inserted after the current tab instead of at the end.
This is the wrong behavior, as it violates the convention followed by _almost_ all tab-based apps, e.g. Chrome, Finder, etc, where new tabs are always created at the end.

### To reproduce

Open two tabs, call them 1 and 2.
1. Highlight tab 1
2. Click `+` to create a new tab
3. The tab is created after tab 1 instead of tab 2.
<img width="783" alt="image" src="https://github.com/warpdotdev/Warp/assets/7163127/064387df-069e-4ed8-9736-6da4f181171a">

### Expected behavior

The new tab should be inserted all the way to the end.

### Operating system

MacOS

### Operating system and version

14.0 (23A344)

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.01.16.16.31.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by tomeresk** [comment]
Also noticed this started recently, +1 for fixing it to previous behavior (or adding some configuration in the settings)

**Comment by Gvex95** [comment]
Hello warp team.
First of all, thanks, since you made an awesome terminal, that is saving so much time when i am debugging.

I would just like to upvote this feature request, since it is really annoying to have tab  opening after current selected tab, instead at the end. Please consider adding some GUI toggle where we can choose behaviour.

Best regards,
Milan

**Comment by lzm0** [comment]
This feature is finally here!
<img width="531" alt="image" src="https://github.com/warpdotdev/Warp/assets/7163127/133337e8-ffe5-47fc-af71-4be11abd592b">
