### ISSUE TITLE
ssh interactive sessions freeze randomly

### ISSUE THREAD

**Issue by moa4020** [warpdotdev/Warp#4107]
### Operating System

MacOS

### Operating System and Version

14.2.1

### Local Shell Version

5.9

### Remote Shell Version

4.4.20(1)-release

### Warp Version

v0.2024.01.16.16.31.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Include shell xtrace output

https://app.warp.dev/block/B0QN5rIZ6erpDPNWxjotsH

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by szgupta** [comment]
Hey @moa4020, do you might elaborating on what you mean by "freeze"? Does the specific ssh session become non-interactive? Or does the Warp application freeze / beachball?

A screen recording would be helpful to diagnose further!

**Comment by moa4020** [comment]
Hi @szgupta It was an personal error. Sorry about that.
