### ISSUE TITLE
Warp loads prompt... twice?

### ISSUE THREAD

**Issue by TheRuky** [warpdotdev/Warp#4108]
### Describe the bug

I'm using zsh with Oh-My-Zsh and Spaceship prompt. If you check out the screenshot (above is Warp, below is iTerm), you'll notice that Warp loads Spaceship PS1 and then loads it's prompt. I would expect that either only Warp's PS1 is shown or (when using PS1 option in Warp) the one from Spaceship. When I switch from Warp to PS1 in Warp's settings - I get double Spaceship PS1.

### To reproduce

I don't know, it just happened when I installed Warp.

### Expected behavior

I guess I should see only Warp's prompt, i.e. the prompt selected in Warp settings.

### Screenshots

<img width="1105" alt="image" src="https://github.com/warpdotdev/Warp/assets/9364388/54eb32ab-f01a-43c7-855e-a947adcfe509">

### Operating system

MacOS

### Operating system and version

Ventura 13.0

### Shell Version

zsh 5.8.1

### Current Warp version

v0.2024.01.16.16.31.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I installed Warp through `brew`.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by TheRuky** [comment]
So, I changed my theme to p10k, and this doesn't happen anymore.

<img width="1072" alt="image" src="https://github.com/warpdotdev/Warp/assets/9364388/809cef33-2db5-40da-a43f-0fd9b2e53ab0">

**Comment by dannyneira** [comment]
Thanks for letting us know @TheRuky This prompt can cause an [issue](https://github.com/warpdotdev/Warp/issues/1973) with typeahead in Warp's input editor.
To workaround the issue, run `echo "SPACESHIP_PROMPT_ASYNC=FALSE" >>! ~/.zshrc`

Closing as this is a known limitation with spaceship prompt. https://docs.warp.dev/appearance/prompt#spaceship

**Comment by mikerosas-mc** [comment]
> Thanks for letting us know @TheRuky This prompt can cause an [issue](https://github.com/warpdotdev/Warp/issues/1973) with typeahead in Warp's input editor. To workaround the issue, run `echo "SPACESHIP_PROMPT_ASYNC=FALSE" >>! ~/.zshrc`
> 
> Closing as this is a known limitation with spaceship prompt. https://docs.warp.dev/appearance/prompt#spaceship

this, I was losing it! 
🙌
