### ISSUE TITLE
Update Warp Markdown Reader on Save

### ISSUE THREAD

**Issue by mac-codes9** [warpdotdev/Warp#4120]
### Describe the solution you'd like?

The built-in markdown reader should watch the file for changes and re-render the page when an edit is made, this would turn warp into a pretty damn good Markdown editor!

See image below.

<img width="1171" alt="Screenshot 2024-02-02 at 09 04 44" src="https://github.com/warpdotdev/Warp/assets/115668288/52962e57-1721-4340-9de2-6b1c6ca4d831">

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for submitting this @mac-codes9 

We already have a request tracking this over at #3971

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Duplicate of #3971
