### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by igorwojda** [warpdotdev/Warp#4133]
### Describe the solution you'd like?

I would like to be able to pass arguments to open new Warp tab rather than changing path in existing tab. 

### Is your feature request related to a problem? Please describe.

To open warp (with the project correct folder path) I have this alias defined in `./zshrc` file:

`alias warp='open -a "Warp" -n --args "$(pwd)"'`

### Additional context

I am often using terminals build in the IntelliJ IDEA.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for this feature request @igorwojda!

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
@igorwojda We've added a URI scheme that you can use to open a new Tab in Warp. https://docs.warp.dev/features/uri-scheme#how-to-use-it

Hopefully, that will meet your use case. Let us know what you think.

**Comment by alokedesai** [comment]
@igorwojda Closing this out since we now have a URI scheme. Please reopen if you're still experiencing issues!
