### ISSUE TITLE
Split Panes Navigation Should Work With Vim Binds if Enabled

### ISSUE THREAD

**Issue by maclong9** [warpdotdev/Warp#4134]
### Describe the bug

Using `􀆔+􀆕+􀰌` to navigate obviously works fine, the issue comes when you have the Vim-like bindings enabled and should be able to navigate panes with a similar set of keys without having to move fingers from the home row.

### To reproduce

Enable Vim-like bindings and then try to navigate panes with `h,j,k,l`

### Operating system

MacOS

### Operating system and version

macOS Sonoma 14.2.1

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @mac-codes9 thanks for submitting. I think there isn't support for those keybinds to navigate just yet, but you can learn the Warp keyboard shortcuts for navigating the panes as a stopgap. https://docs.warp.dev/features/windows/split-panes#how-to-use-it

I'll change this to a feature request for that missing support.

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by patrykk21** [comment]
What we want is to have a seamingless integration with vim just like tmux does.

[Quick video demonstration](https://www.youtube.com/watch?v=qyV_hOtMdwg)

We want to be able to move around using the same keybinds as in vim, and if it's the last pane inside vim, to move the pane in warp.
I think the video explains much better than what I wrote 😅
