### ISSUE TITLE
Add AI execution agent

### ISSUE THREAD

**Issue by MikeyBeez** [warpdotdev/Warp#4135]
### Describe the solution you'd like?

Please take a look at rawdog.  https://github.com/AbanteAI/rawdog  This software can recursively generate and execute code in the terminal.   

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for this feature request @MikeyBeez 

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
@MikeyBeez Soon... https://twitter.com/warpdotdev/status/1792614144354693127

**Comment by dannyneira** [comment]
Closing as this feature is live!
