### ISSUE TITLE
Emojis are not displayed

### ISSUE THREAD

**Issue by cartisan** [warpdotdev/Warp#4136]
### Describe the bug

Emojis are not displayed in the terminal. I can not see them in the prompt, in vim nor can I paste them. Instead whitespace is displayed. Changing fonts does not alleviate the problem.
Figure 1: my starship promp in warp
![image](https://github.com/warpdotdev/Warp/assets/1424400/87b96728-e823-4e45-baa9-c16a6b2af686)
Figure 2: same starship prompt in my other terminal
![image](https://github.com/warpdotdev/Warp/assets/1424400/ffa7e145-f22d-4264-8e5c-8e60fcac4b4f)

### To reproduce

1. Copy emoji: 🚧
2. Paste into Warp
3. Emoji does not appear

### Expected behavior

I expected to see the emojis correctly rendered.

### Operating system

Linux

### Operating system and version

Ubuntu 22.04.3

### Shell Version

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.01.30.16.52.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
Hi @cartisan, thanks for filing. The next release of Warp (coming out on Thursday) will have support for emojis. Thanks for your patience with the beta version of our Linux build!

**Comment by cartisan** [comment]
Works like a charm, thanks guys!

**Comment by alokedesai** [comment]
Great to hear! Thanks for using the Linux beta and your patience as smooth out the kinks :)

**Comment by apuatcfbd** [comment]
I think emojis aren't working again. I'm seeing (attachment) for ✅ ✅

![Image](https://github.com/user-attachments/assets/4e3f1eb0-7d1d-4c19-a28f-d043ab1c7ebe)

**Comment by ksh2177** [comment]
Guys, I really appreciate all the advanced features Warp is bringing — AI assistant, async terminal, GPU acceleration, blocks, Pro mode... it all sounds amazing.

But let’s get real: I just want to see a freaking emoji properly.

My 15-year-old smartphone could render 😎 and 🎉 without breaking a sweat. Meanwhile, Warp — the so-called terminal of the future — still can't handle basic Unicode emoji rendering on Linux in 2025.

Before launching "Pro" upgrades and AI-ready integrations, maybe focus on the fundamentals — like text rendering and proper font fallback (Noto Color Emoji is installed, by the way, but Warp just ignores it).

This issue has been open for 2+ years. It's not a niche feature — it's basic UX.

Please give this some love. Linux users exist. We deserve colors too.

**Comment by Sligcm** [comment]
> Guys, I really appreciate all the advanced features Warp is bringing — AI assistant, async terminal, GPU acceleration, blocks, Pro mode... it all sounds amazing.
> 
> But let’s get real: I just want to see a freaking emoji properly.
> 
> My 15-year-old smartphone could render 😎 and 🎉 without breaking a sweat. Meanwhile, Warp — the so-called terminal of the future — still can't handle basic Unicode emoji rendering on Linux in 2025.
> 
> Before launching "Pro" upgrades and AI-ready integrations, maybe focus on the fundamentals — like text rendering and proper font fallback (Noto Color Emoji is installed, by the way, but Warp just ignores it).
> 
> This issue has been open for 2+ years. It's not a niche feature — it's basic UX.
> 
> Please give this some love. Linux users exist. We deserve colors too.

I agree with you, you've spoken my mind.

**Comment by Sligcm** [comment]
> Guys, I really appreciate all the advanced features Warp is bringing — AI assistant, async terminal, GPU acceleration, blocks, Pro mode... it all sounds amazing.
> 
> But let’s get real: I just want to see a freaking emoji properly.
> 
> My 15-year-old smartphone could render 😎 and 🎉 without breaking a sweat. Meanwhile, Warp — the so-called terminal of the future — still can't handle basic Unicode emoji rendering on Linux in 2025.
> 
> Before launching "Pro" upgrades and AI-ready integrations, maybe focus on the fundamentals — like text rendering and proper font fallback (Noto Color Emoji is installed, by the way, but Warp just ignores it).
> 
> This issue has been open for 2+ years. It's not a niche feature — it's basic UX.
> 
> Please give this some love. Linux users exist. We deserve colors too.

Hey bro, I might have solved this issue. First, tell me—did you connect to a Linux server via Warp, then open a file in an editor like Vim on the server, and found that emojis weren’t displaying?

**Comment by Sligcm** [comment]
> > > Guys, I really appreciate all the advanced features Warp is bringing — AI assistant, async terminal, GPU acceleration, blocks, Pro mode... it all sounds amazing.
> > > But let’s get real: I just want to see a freaking emoji properly.
> > > My 15-year-old smartphone could render 😎 and 🎉 without breaking a sweat. Meanwhile, Warp — the so-called terminal of the future — still can't handle basic Unicode emoji rendering on Linux in 2025.
> > > Before launching "Pro" upgrades and AI-ready integrations, maybe focus on the fundamentals — like text rendering and proper font fallback (Noto Color Emoji is installed, by the way, but Warp just ignores it).
> > > This issue has been open for 2+ years. It's not a niche feature — it's basic UX.
> > > Please give this some love. Linux users exist. We deserve colors too.
> > 
> > 
> > Hey bro, I might have solved this issue. First, tell me—did you connect to a Linux server via Warp, then open a file in an editor like Vim on the server, and found that emojis weren’t displaying?
> 
> it doesn't work on local machine in the first place.

Will your other terminals display it? My local OS is macOS, and emojis show up normally when using Warp.

**Comment by Sligcm** [comment]
> > > Guys, I really appreciate all the advanced features Warp is bringing — AI assistant, async terminal, GPU acceleration, blocks, Pro mode... it all sounds amazing.
> > > But let’s get real: I just want to see a freaking emoji properly.
> > > My 15-year-old smartphone could render 😎 and 🎉 without breaking a sweat. Meanwhile, Warp — the so-called terminal of the future — still can't handle basic Unicode emoji rendering on Linux in 2025.
> > > Before launching "Pro" upgrades and AI-ready integrations, maybe focus on the fundamentals — like text rendering and proper font fallback (Noto Color Emoji is installed, by the way, but Warp just ignores it).
> > > This issue has been open for 2+ years. It's not a niche feature — it's basic UX.
> > > Please give this some love. Linux users exist. We deserve colors too.
> > 
> > 
> > Hey bro, I might have solved this issue. First, tell me—did you connect to a Linux server via Warp, then open a file in an editor like Vim on the server, and found that emojis weren’t displaying?
> 
> it doesn't work on local machine in the first place.

If emojis aren't displaying in other terminals on your local operating system, you'll first need to install an emoji-supported font, then select this emoji-capable font in your terminal settings.

**Comment by ksh2177** [comment]
There is no issue with macOS guys..

It is with Linux. I posted a topic on warp :

Hey everyone 👋

I'm still unable to get **emoji rendering (in color)** working in Warp on **Linux** in 2025, despite having everything set up correctly.

---

## 🧠 Context

- 🖥️ **OS**: Pop!_OS 22.04 LTS (Ubuntu-based)
- 🧱 **Kernel**: 6.12.10-76061203-generic
- 🧠 **CPU**: AMD Ryzen 7 5800X
- 🎮 **GPU**: NVIDIA RTX 3070 Ti
- 🖼️ **WM/DE**: GNOME 42.9 + Mutter (X11)
- 🖍️ **Font in Warp**: `FiraCode Nerd Font`
- 📦 **Emoji font**: `fonts-noto-color-emoji` (installed via APT)
- 🧩 **Warp version**: `warp v0.2025.07.16.08.12.sta4`

---

## ✅ What works

- ✅ GNOME Terminal **renders emojis in full color**, with the same font fallback (`FiraCode Nerd Font` + `Noto Color Emoji`)
- ✅ `fc-cache` rebuilt cleanly
- ✅ `fc-match` returns `FiraCode Nerd Font`
- ✅ `fonts-noto-color-emoji` installed and loaded
- ✅ `~/.config/fontconfig/conf.d/10-emoji.conf` added with fallback config
- ✅ `fc-match -s` returns the expected fallback list (DejaVu etc.)

---

## ❌ What fails

- ❌ In Warp: **emojis do not show at all** (not even monochrome)
- ❌ No sign of fallback being applied inside Warp
- ❌ Same emoji echo command works in all other terminals

---

## 🔎 Possibly relevant

- Emoji font uses CBDT/CBLC tables (bitmap color)
- FontForge can’t merge it (already tried, known limitation)
- Maybe Warp still doesn’t support fallback rendering via `fontconfig` in some environments? (GPU rendering issue? missing Pango-like layer?)

---

## 🖼️ Screenshots

[Attach 2 images]:
1. GNOME Terminal → full color emojis ✅  
2. Warp → nothing rendered ❌

---

## ❓My ask

I’ve read Discord threads and saw this was “resolved” in 2024, but I seem to be among the few where it’s still broken in 2025.

Is there any known incompatibility with:
- NVIDIA GPUs?
- X11 (vs Wayland)?
- Certain Nerd Fonts?
- Or... is there a hidden setting I’m missing?

🙏 Appreciate any help or confirmation from other Linux users. Thanks in advance!

— ksh2177

**Comment by Sligcm** [comment]
> There is no issue with macOS guys..
> 
> It is with Linux. I posted a topic on warp :
> 
> Hey everyone 👋
> 
> I'm still unable to get **emoji rendering (in color)** working in Warp on **Linux** in 2025, despite having everything set up correctly.
> 
> ## 🧠 Context
> * 🖥️ **OS**: Pop!_OS 22.04 LTS (Ubuntu-based)
> * 🧱 **Kernel**: 6.12.10-76061203-generic
> * 🧠 **CPU**: AMD Ryzen 7 5800X
> * 🎮 **GPU**: NVIDIA RTX 3070 Ti
> * 🖼️ **WM/DE**: GNOME 42.9 + Mutter (X11)
> * 🖍️ **Font in Warp**: `FiraCode Nerd Font`
> * 📦 **Emoji font**:  (installed via APT)`fonts-noto-color-emoji`
> * 🧩 **Warp version**: `warp v0.2025.07.16.08.12.sta4`
> 
> ## ✅ What works
> * ✅ GNOME Terminal **renders emojis in full color**, with the same font fallback (`FiraCode Nerd Font` + `Noto Color Emoji`)
> * ✅  rebuilt cleanly`fc-cache`
> * ✅  returns `fc-match``FiraCode Nerd Font`
> * ✅  installed and loaded`fonts-noto-color-emoji`
> * ✅  added with fallback config`~/.config/fontconfig/conf.d/10-emoji.conf`
> * ✅  returns the expected fallback list (DejaVu etc.)`fc-match -s`
> 
> ## ❌ What fails
> * ❌ In Warp: **emojis do not show at all** (not even monochrome)
> * ❌ No sign of fallback being applied inside Warp
> * ❌ Same emoji echo command works in all other terminals
> 
> ## 🔎 Possibly relevant
> * Emoji font uses CBDT/CBLC tables (bitmap color)
> * FontForge can’t merge it (already tried, known limitation)
> * Maybe Warp still doesn’t support fallback rendering via  in some environments? (GPU rendering issue? missing Pango-like layer?)`fontconfig`
> 
> ## 🖼️ Screenshots
> [Attach 2 images]:
> 
> 1. GNOME Terminal → full color emojis ✅
> 2. Warp → nothing rendered ❌
> 
> ## ❓My ask
> I’ve read Discord threads and saw this was “resolved” in 2024, but I seem to be among the few where it’s still broken in 2025.
> 
> Is there any known incompatibility with:
> 
> * NVIDIA GPUs?
> * X11 (vs Wayland)?
> * Certain Nerd Fonts?
> * Or... is there a hidden setting I’m missing?
> 
> 🙏 Appreciate any help or confirmation from other Linux users. Thanks in advance!
> 
> — ksh2177

You can start by testing with the simplest scenario to determine whether the specific issue is caused by warp or something else. If you directly paste an emoji in the Linux warp terminal, will the emoji display properly in the terminal?

**Comment by Sligcm** [comment]
> There is no issue with macOS guys..
> 
> It is with Linux. I posted a topic on warp :
> 
> Hey everyone 👋
> 
> I'm still unable to get **emoji rendering (in color)** working in Warp on **Linux** in 2025, despite having everything set up correctly.
> 
> ## 🧠 Context
> * 🖥️ **OS**: Pop!_OS 22.04 LTS (Ubuntu-based)
> * 🧱 **Kernel**: 6.12.10-76061203-generic
> * 🧠 **CPU**: AMD Ryzen 7 5800X
> * 🎮 **GPU**: NVIDIA RTX 3070 Ti
> * 🖼️ **WM/DE**: GNOME 42.9 + Mutter (X11)
> * 🖍️ **Font in Warp**: `FiraCode Nerd Font`
> * 📦 **Emoji font**: `fonts-noto-color-emoji` (installed via APT)
> * 🧩 **Warp version**: `warp v0.2025.07.16.08.12.sta4`
> 
> ## ✅ What works
> * ✅ GNOME Terminal **renders emojis in full color**, with the same font fallback (`FiraCode Nerd Font` + `Noto Color Emoji`)
> * ✅ `fc-cache` rebuilt cleanly
> * ✅ `fc-match` returns `FiraCode Nerd Font`
> * ✅ `fonts-noto-color-emoji` installed and loaded
> * ✅ `~/.config/fontconfig/conf.d/10-emoji.conf` added with fallback config
> * ✅ `fc-match -s` returns the expected fallback list (DejaVu etc.)
> 
> ## ❌ What fails
> * ❌ In Warp: **emojis do not show at all** (not even monochrome)
> * ❌ No sign of fallback being applied inside Warp
> * ❌ Same emoji echo command works in all other terminals
> 
> ## 🔎 Possibly relevant
> * Emoji font uses CBDT/CBLC tables (bitmap color)
> * FontForge can’t merge it (already tried, known limitation)
> * Maybe Warp still doesn’t support fallback rendering via `fontconfig` in some environments? (GPU rendering issue? missing Pango-like layer?)
> 
> ## 🖼️ Screenshots
> [Attach 2 images]:
> 
> 1. GNOME Terminal → full color emojis ✅
> 2. Warp → nothing rendered ❌
> 
> ## ❓My ask
> I’ve read Discord threads and saw this was “resolved” in 2024, but I seem to be among the few where it’s still broken in 2025.
> 
> Is there any known incompatibility with:
> 
> * NVIDIA GPUs?
> * X11 (vs Wayland)?
> * Certain Nerd Fonts?
> * Or... is there a hidden setting I’m missing?
> 
> 🙏 Appreciate any help or confirmation from other Linux users. Thanks in advance!
> 
> — ksh2177

If the pasted emoji didn't show up in the previous step, try repeating this operation in Pop!_OS's default system terminal to see if the emoji will display?

**Comment by Fab1n** [comment]
This is definitely not resolved, just try one of these emojis:

🇫🇷, 🇧🇪, 🇮🇹, 🇩🇪, 🇦🇹, 🇪🇸, 🇳🇱, 🇫🇮, 🇮🇪, 🇵🇹, 🇺🇸, 🇬🇧, 🇬🇷, 🇸🇰

All are not being displayed with out-of-the-box Warp 2, macOS 15.6

**Comment by Sligcm** [comment]
> 这绝对没有解决，只需尝试以下表情符号之一：
> 
> 🇫🇷, 🇧🇪, 🇮🇹, 🇩🇪, 🇦🇹, 🇪🇸, 🇳🇱, 🇫🇮, 🇮🇪, 🇵🇹, 🇺🇸, 🇬🇧, 🇬🇷, 🇸🇰
> 
> 所有这些都没有使用开箱即用的 Warp 2、macOS 15.6（Hack 默认字体）显示。
> 
> 你能在你的 Mac 上试试这个吗？我认为 macOS 也肯定存在问题。
> 
> 澄清一下，它们是这样显示的： <img alt="图像" width="448" height="28" src="https://private-user-images.githubusercontent.com/754598/482723004-2a8f023b-0ee6-4a6d-899a-35529251ccf7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYzNDc3NTEsIm5iZiI6MTc1NjM0NzQ1MSwicGF0aCI6Ii83NTQ1OTgvNDgyNzIzMDA0LTJhOGYwMjNiLTBlZTYtNGE2ZC04OTlhLTM1NTI5MjUxY2NmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyOFQwMjE3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTA1M2QzMzZiYjU5NTYzZWYyYWY5YTE0ZjVkOThkZTAyOWI0NjkxZTczZDU5N2I2ZTExZWY1YTdjNWZlY2I2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ktp7rEtX-Slnud2jWL3nMPZnYquzAbcv6t6ArK9V4-Y">

Same environment as you. Just change to a font that supports emojis and you'll be fine.

**Comment by stephen-lspd** [comment]
I've finally found a solution for this after trying every font under the sun thinking I was going mad...

Go to: **Warp Settings** → **Appearance** → **Text**
Enable: `Show ligatures in terminal`

Flag emoji's will now render as normal!
