### ISSUE TITLE
SSH disconnect makes commands prefix / suffix with 00~ and 01~

### ISSUE THREAD

**Issue by lewismacnow** [warpdotdev/Warp#4138]
### Describe the bug

When connected to a remote ssh server and the session disconnects "client_loop: send disconnect: Broken pipe"
Further commands on the local machine are prefix / suffix with 00~ and 01~

### To reproduce

Using macos
1. ssh to ubuntu server
2. reset network interface / router etc
3. you are now disconnected from the remote server - see "client_loop: send disconnect: Broken pipe"
4. try to ssh to same server ... or try any other command
5. commands are prefixed with '00~' so always fail.

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/93997957/0ea7268f-bd00-4467-aae6-ed1475a96be1)

### Operating system

MacOS

### Operating system and version

14.3 (23D56)

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)

### Current Warp version

v0.2024.01.16.16.31.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by priyank-trivedi** [comment]
I'm also facing this same issue. I have to close that session and open a new one every time

**Comment by lewismacnow** [comment]
> I'm also facing this same issue. I have to close that session and open a new one every time

Yes me too. I usually just restart in a new tab.
I have not worked out a way to recover from the issue in the same tab/session.

**Comment by OlegYarmolenko** [comment]
I have same issue

**Comment by larsenweigle** [comment]
+1 also experiencing this issue

**Comment by iamthe-Wraith** [comment]
+1 here as well

**Comment by daftu** [comment]
I have same issue.

**Comment by kei-eniblock** [comment]
+1

**Comment by davidbaranek** [comment]
+1

**Comment by eugui** [comment]
+1

**Comment by lewismacnow** [comment]
I moved over to iterm2.
This bug is too frustrating to continue use.

**Comment by larsenweigle** [comment]
Same here. I am also having problems when I simply use `exit` to end a ssh connection. The CLI just stops working as a whole. It's really frustrating because I absolutely love Warp, but not enough to deal with all the bugs that arise when using ssh :(

**Comment by DennisFaucher** [comment]
+1. Looking forward to a fix.

**Comment by lewismacnow** [comment]
> Same here. I am also having problems when I simply use `exit` to end a ssh connection. The CLI just stops working as a whole. It's really frustrating because I absolutely love Warp, but not enough to deal with all the bugs that arise when using ssh :(

There are an unfortunate number of confusing and worrying issues beyond these. 

For example, when using '**glances**' (popular python system monitor) with Warp, I get a '**segmentation fault**'. I am not smart enought to know why **Warp + SSH + python causes memory related problems on the remote host which do not exist with other terminal emulators**. 

But it worries me enough to forego using Warp ever again.

**Comment by bartosik-hep** [comment]
@dannyneira the same issue I've mentioned in #4645 
Hopefully you find the time to investigate it 🙌🏼

**Comment by Sophikitis** [comment]
I have same issue

**Comment by sasquanaut** [comment]
+1, same issue

**Comment by vorporeal** [comment]
Hey all - I've figured out what's going wrong here, and should have a fix out in next week's release. :)

**Comment by DennisFaucher** [comment]
That's great news. Thank you.

**Comment by bartosik-hep** [comment]
@vorporeal  Yes, you're right. 
After switching to `zsh` in my local terminal I don't have the issue any more. Thank you looking into this!

**Comment by DennisFaucher** [comment]
I wonder if upgrading bash using homebrew bash would also solve the problem.

**Comment by vorporeal** [comment]
@DennisFaucher yep, that would also fix the issue

**Comment by thepowerfuldeez** [comment]
+1

**Comment by OlegYarmolenko** [comment]
![image](https://github.com/warpdotdev/Warp/assets/23661807/c7bd144d-ed30-45af-bd13-abe899fc4d8f)
fixed?))

**Comment by vorporeal** [comment]
Yup!  A fix went out in this afternoon's release - let me know if you're still experiencing the issue after you update!

**Comment by thepowerfuldeez** [comment]
Seems like it fixed now! Thank you for such quick turnaround!

**Comment by vorporeal** [comment]
Glad to hear it!  Going to close this as completed, but please let me know if this is unfixed for anyone.
