### ISSUE TITLE
Test issue for linear integration

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#4139]
### Describe the bug

Test

### To reproduce

Test

### Operating system

MacOS

### Operating system and version

test

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Test

**Comment by elviskahoro** [comment]
Test from Linaer

**Comment by dannyneira** [comment]
Test from linear 2

**Comment by dannyneira** [comment]
test
