### ISSUE TITLE
Android / Java / Maven / Gradle crashing on compile

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#414]
### Describe the bug

```shell
Warp keeps crashing for Android / Java / Maven compiles.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

**Comment by zachlloyd** [comment]
Possible to get repro instructions on this one please?

**Comment by dbottillo** [comment]
> Possible to get repro instructions on this one please?

I'm having a similar issue, from time to time when using `gradle` in warp, it just gets into an unusable state. For me it happens when running a gradle command through a script (eg. a git `pre-push` or a bash script), the script starts hanging forever so I need to kill it and now the gradle daemon is "broken":
![Screenshot 2022-01-11 at 13 57 47](https://user-images.githubusercontent.com/485717/148956385-bdbc1794-210e-45ec-a87c-757939d26868.png)

The only way to recover now is to actually kill the gradle process and start from scratch. As an Android developer using gradle all day makes it very hard to use Warp (I've used it today just to reproduce the issue to post this comment!).

Not sure if there is something else that I can check/report, this doesn't happen with `iTerm2`.

**Comment by elviskahoro** [comment]
mvn compile appears to hang in terminal

From @Gregory-Gelfond via #593

### Describe the bug

```shell
While in a git repo that uses maven as the build tool, running `mvn compile` appears to hang. When the same command is invoked from within iTerm 2, the project builds and mvn terminates as expected, but in warp the command appears to hang (with no further output) during the build phase.
```


### To Reproduce

Steps to reproduce:
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error '...'


### Expected behaviour

```shell
Behavior should be identical to that of iTerm 2
```


### Screenshots

_No response_

### Operating System

MacOS

### OS Version

12.1

### Additional context

_No response_

**Comment by elviskahoro** [comment]
From Discord:

 I've been using Warp for few weeks now and I really like it! I do mostly Android development and I have this weird issue that sometimes (1 out of 10) when I run a gradle command (eg. ./gradlew assemble) it then starts hanging and basically it's stuck with "<=============> 100% CONFIGURING [4m 34s] IDLE" and I need to manually stop the command, I then usually go to Iterm2, run a gradle command to realise that "Timeout waiting to lock journal cache (/Users/<username>/.gradle/caches/journal-1). It is currently in use by another Gradle instance." So basically I need to manually kill the gradle process. This is not happening with Iterm2, so at the moment I'm using Iterm2 for gradle commands and warp for everything else but of course it's not ideal and I'm not sure why, I tried to search on github for a similar issue but couldn't find one. What do you think could be the issue?

**Comment by snadon** [comment]
I develop with flutter and running the command `flutter run` will get stuck at `assembleDebug` when testing on an Android device. If I use another terminal like WezTerm or the built-in terminal the command runs normally and doesn't hang.

**Comment by JPWallhorn** [comment]
Is there any update on this? This might be an M1 specific issue?

**Comment by snadon** [comment]
I upgraded Warp to the latest version and now it works.

**Comment by saket** [comment]
I'm running into the same issue as mentioned by @dbottillo. FWIW, switching to a different terminal isn't enough to solve this. Any gradle processes started from warp need to be killed too.

**Comment by rob-pomelo** [comment]
Hitting this very often with Bazel + Java builds on M1 Macbook Pro

**Comment by alokedesai** [comment]
@prashanOS your finding about Gradle processes capped at 800mb is very interesting--can you elaborate more on how you  concluded that?

**Comment by elviskahoro** [comment]
From @liufuyang via #1529
### Discord username (optional)

_No response_

### Describe the bug

Running command `mvn compile` hangs with version `v0.2022.06.13.09.15.stable_01`


### To Reproduce

Just run command `mvn compile` in a Java project folder.


### Expected behaviour

`mvn compile` finishes build or gives an error.

### Screenshots


<img width="934" alt="image" src="https://user-images.githubusercontent.com/161689/174772622-9e279827-7358-49bf-bf0f-6a0e275cdcfe.png">


<img width="631" alt="image" src="https://user-images.githubusercontent.com/161689/174772559-4caa01a3-a6de-476b-882e-38b83fa36f31.png">


### Operating System

MacOS

### OS Version

12.4

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)

### Warp Version

v0.2022.06.13.09.15.stable_01

### Additional context

_No response_

### Warp Internal (ignore): linear-label:24888f54-df93-45d5-9bdd-e38f740cac19

_No response_

**Comment by dsaff** [comment]
What version is the fix in, so that we can verify the fix?  Thanks!

**Comment by elviskahoro** [comment]
this is definitely not fixed! that was an accident. I meant to close the 1529 and bring it over.

**Comment by dsaff** [comment]
Great to hear it!  I'd be happy to give it a try, although it might not be until Monday.

**Comment by alokedesai** [comment]
Hey eveyone, @dsaff was kind enough to confirm that this was fixed on a debug version of Warp. The fix for this should be out on Wednesday. Thanks for your patience here!

**Comment by alokedesai** [comment]
Following up here--we've made a bunch of changes that we believe should have fixed this issue. Please reopen if you're still seeing hangs when using maven!
