### ISSUE TITLE
CB: Vim -  Tab title shows $LINE when using vim

### ISSUE THREAD

**Issue by nipunn1313** [warpdotdev/warp#415]
### Describe the bug

```shell
The tab title shows `$LINE`
I expect it to show `vim abcd`
```

### To Reproduce

Steps to reproduce:
1. Install vim
2. Run `vim abcd`

### Expected behaviour

```shell
Expected tab title change to `vim abcd`
```

### Screenshots

In warp

![image](https://user-images.githubusercontent.com/1300387/141878038-6a7c7fff-6956-450b-a6a3-cb2cbdb9457c.png)

On iterm

![image](https://user-images.githubusercontent.com/1300387/141878053-fbffe56d-9b9e-4656-ad8d-79bae8974bf3.png)

### Operating System

MacOS

### OS Version

11.6

### Additional context

```shell
I think it's a recent regression? I don't remember this happening before. I've found other issues in the tracker with screenshots that look better.
```

**Comment by gagata** [comment]
interesting, what version was this on? is it still happening on the newest (today's) release? frankly, i cannot repro...

**Comment by nipunn1313** [comment]
I'm on the 2021.11.16 release and it's still happening
Looks like this
https://capture.dropbox.com/3OrcYfVGcHlyK19t

Still happens with `vim -u NONE` which rules out any funnybusiness inside vimrc

**Comment by gagata** [comment]
interesting. thanks for the video - it helped me figure out you're most likely using `zsh` (i originally tested with `bash`). but that still doesn't repro for me, even with `vim -u NONE`.  ooc what vim version are you running? wonder if that could be related, though it's kinda a blind guess. 

also - does it only show `$LINE` for new/empty files? does it work correctly for existing ones that are not empty?

**Comment by nipunn1313** [comment]
I can repro the issue in bash as well - as well as both with existing files (`vim existing.txt`) and new files (`vim brand_new.txt`).

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 30 2021 06:51:40)
```

I do use ohmyzsh
I am wondering if there's something about how my tab title is configured that's special - how is the tab title determined by warp?

**Comment by nipunn1313** [comment]
Interesting! I just found that it's not something specific to vim.
I just got it to happen by opening a new terminal (default to zsh) and typing `bash` into it

See this
https://capture.dropbox.com/1pgbKKoSThrnEjlt

I do use ohmyzsh - maybe that's relevant?

**Comment by nipunn1313** [comment]
Here's another example using `cat` as the command
https://capture.dropbox.com/c2kYzEQXdF35JswT

Seems to happen with any command that is waiting for stdin.
Eg if I type
```
grep pat
```
it happens until I ctrl-D

**Comment by gagata** [comment]
wow, that's really interesting! out of curiosity, mind trying to disable ohmyzsh and see if it fixes itself? overall we suggest to do something like this in your configs, since some of those config programs may break/not work correctly with Warp.  

```if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

    # POWERLEVEL10K
    # OH-MY-ZSH-THEMES
    # OH-MY-ZSH-PLUGINS

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi```

**Comment by nipunn1313** [comment]
yep! It's definitely something within ohmyzsh leading to this issue. When I comment out from my zshrc -
```
# source $ZSH/oh-my-zsh.sh
```

Then things start working normally again.

I poked around the ohmyzsh source and I think it's coming from here
https://github.com/ohmyzsh/ohmyzsh/blob/15fd9c84deae400ba52451d75548fb8f6ec26bcf/lib/termsupport.zsh#L102

which sets the tab name here
https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/termsupport.zsh#L22

**Comment by nipunn1313** [comment]
I'm pretty sure it's because a line like
```
print -Pn "\e]2;${ABCD:q}\a"
```

is printing to stdout - but somehow getting buffered into the output of warp - without actually sending that sequence to the terminal to update the title - or somehow it's happening in a weird way.

**Comment by alokedesai** [comment]
Thanks for filing! I just repro'd this morning as well after an ohmyzsh update--what was causing this was a difference between Warp's tab title behavior and ohmyzsh's tab title behavior. Essentially ohmyzsh changed their implementation of the `title` function (linked in https://github.com/warpdotdev/warp/issues/415#issuecomment-974468534) which actually override our own `title` function, hence causing this behavior. I just sent out a fix to escape these two properly so conflicts like this won't happen again--this should fixed in our next release going out on Wednesday.

**Comment by elviskahoro** [comment]
@nipunn1313 please reopen or comment if it still persists
