### ISSUE TITLE
p10k prompt separator colors are broken with warp

### ISSUE THREAD

**Issue by Maorytzio** [warpdotdev/Warp#4164]
### Describe the bug

<img width="973" alt="image" src="https://github.com/warpdotdev/Warp/assets/38633235/2abcf08a-bb6f-4912-a9bd-6e0c768b179a">
I am so frustrated with it and spent so much time trying to figure this out.
how can I fix this? 

### To reproduce

it simply happened to me when I finished following warp setup guide for p10k video

### Operating system

MacOS

### Operating system and version

Sonoma 14.3

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

my warp and p10k version are the latest.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Maorytzio** [comment]
[https://github.com/warpdotdev/Warp/issues/2851#issuecomment-1605005256](url) 
who would've thought 🫠

**Comment by dannyneira** [comment]
Hey @Maorytzio Thanks for submitting. Yes, your best bet is to tweak the contrast settings to help with the broken separators in p10k, or other prompts. 

![CleanShot 2024-03-01 at 11 10 36](https://github.com/warpdotdev/Warp/assets/16809145/9575d05f-43bd-4d17-9d99-1def88998ef0)

Thanks for your interest in Warp and for searching for the solution!
