### ISSUE TITLE
incorrect zsh theme

### ISSUE THREAD

**Issue by Adrien-Marette** [warpdotdev/Warp#4167]
### Describe the bug

powerlevel10k doesn't show correctly

### To reproduce

set warp with zsh and powerlevel10k

### Operating system

MacOS

### Operating system and version

macos sonoma 14.3.1

### Shell Version

zsh 5.9

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by elviskahoro** [comment]
Can you send us a video of what Warp looks like on your end?

**Comment by Adrien-Marette** [comment]
I’ve solved my problem, just forgot to change the font in the settings 😅, but thanks a lot for your quick reply !(I’ve used the font MesloLGS NF to get the appropriate icons)Adrien MARETTEOn 12 Feb 2024, at 8:06 PM, elvis kahoro ***@***.***> wrote:﻿
Can you send us a video of what Warp looks like on your end?

**Comment by dannyneira** [comment]
@Adrien-Marette Awesome! thanks for letting us know. Closing as resolved.
