### ISSUE TITLE
Warp not visible on I3 wm when running apps

### ISSUE THREAD

**Issue by ochan12** [warpdotdev/Warp#4170]
### Describe the bug

Using I3 window manager, when Warp is running a long-standing/non-exiting operation like a node server app, it turns invisible after switching windows back and forth, it doesn't show up once I come back from the previous window
There are no visible issues when Warp is idle. 

### To reproduce

1. Run a node server app, or something simpler `caffeine`
2. Go to another tiling window
3. Come back, and Warp is not there, until mouse is clicked or a key is pressed

### Expected behavior

I'd expect to behave like when Warp is idle, that as soon as I go back to Warp's window it appears without having to press any key/click.

### Screenshots

![Record_select-area_20240213143454](https://github.com/warpdotdev/Warp/assets/20117588/589e6acd-22b5-48c4-9053-82f9808aeb14)

### Operating system

Linux

### Operating system and version

6.4.16-5-MANJARO

### Shell Version

zsh 5.9 (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.02.06.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @ochan12 .I think this may be a known issue with some window managers X11 window managers which do not implement Extended Window Manager Hints. Some examples include: sowm, catwm, Fvwm, dwm, 2bWM, monsterwm, TinyWM, x11fs, XMonad

We'll work to reproduce this issue with i3 and let you know of any updates or questions on this thread.

If anyone else is seeing the same issue please comment with details and subscribe for updates.

**Comment by alokedesai** [comment]
Hi @ochan12 Thanks again for filing this and for your patience while using our Linux beta. This issue should be fixed on the latest version of Warp, would you mind confirming it has been resolve for you?

**Comment by ochan12** [comment]
Hi @alokedesai! Yes, it has been resolved! :smile:
