### ISSUE TITLE
Powerline/Nerd fonts not showing in setup

### ISSUE THREAD

**Issue by bscholer** [warpdotdev/Warp#4176]
### Describe the bug

In the _Shell Prompt (PS1)_ option, the fonts don't display correctly. They look like this in Mac Terminal.
<img width="762" alt="image" src="https://github.com/warpdotdev/Warp/assets/2822945/87a8466f-494f-48ba-b0a8-42ee45160364">

<img width="1624" alt="image" src="https://github.com/warpdotdev/Warp/assets/2822945/0d07e1a2-1d24-4470-bf47-71236e169f69">

### To reproduce

I just installed the app, logged in, and nothing else.

### Operating system

MacOS

### Operating system and version

MacOS 14.2.1

### Current Warp version

v0.2024.02.06.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @bscholer unfortunately, the powerline shell prompt isn't officially supported(but may work partially). Warp does support several other custom prompts (I use [starship.rs](starship.rs) and it works well), Please see the full list in our docs here: https://docs.warp.dev/appearance/prompt#custom-prompt-compatibility-table

Unofficially, I've tested it and I've also noticed it renders on `zsh` with no right-side prompt set and "Enforce minimum contrast" in `Settings > Appearance > Text` set to "Never", I tried with [jet brains mono nerd font](https://www.nerdfonts.com/font-downloads)(you may need to restart Warp for new fonts to take effect). It's for sure not working with `bash` as it renders the prompt more than once when you run a command.

![CleanShot 2024-02-14 at 12 12 10](https://github.com/warpdotdev/Warp/assets/16809145/6fe2d110-ae8e-423b-81b5-25872f7138c9)

Hopefully this helps!

**Comment by bscholer** [comment]
That does, thank you! I changed the fonts and that helped, things seem to be working well. Might do a bit more tweaking though 😋
