### ISSUE TITLE
Linux: Warp xdg-open uses 100% CPU

### ISSUE THREAD

**Issue by yulrizka** [warpdotdev/Warp#4177]
### Describe the bug

whenever warp is opening something with xdg-open, it spawn process that consume 100% of CPU

### To reproduce

1. open side bar
2. click feedback
this should trigger xdg-open to firefox

### Expected behavior

xdg-open complete open the intended application

### Screenshots

![warp-100%-cpu usage](https://github.com/warpdotdev/Warp/assets/117752/5a02aaf7-86f9-47eb-b242-71376f40df41)

### Operating system

Linux

### Operating system and version

39.0.0

### Shell Version

fish 3.7.0

### Current Warp version

v0.2024.02.14.15.46.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @yulrizka sorry to hear about this blocker. It looks like you're on the latest version of fish, but if you can please let us know what version and flavor of linux are you running?

Also if you try and CTRL-CLICK and open links like `echo 'https://www.warp.dev'` does that work? or does it also lock up Warp?

This will help us narrow down the possible root of the issue.

**Comment by dannyneira** [comment]
To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by alokedesai** [comment]
Hey @yulrizka Do you see the same behavior if you try to invoke `xdg-open` with that same github link in another terminal?

**Comment by yulrizka** [comment]
Interestingly if I invoke xdg-open from warp or on my other terminal, it opens firefox.

> Also if you try and CTRL-CLICK and open links like echo 'https://www.warp.dev' does that work? or does it also lock up Warp?

this however, trigger the problem for me.


Linux abi 6.6.13-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 20 18:03:28 UTC 2024 x86_64 GNU/Linux
Fedora release 39 (Thirty Nine)

**Comment by zakhi** [comment]
Happens to me, but only if Firefox is the default app for web links. Tried with chrome, and no problem.
Manually invoking xdg-open - no problem.

New process for firefox is created, but stuck on 100% CPU and does not open a new tab/window.

Ubuntu 23.10 6.5.0-21-generic
GNOME Shell 45.2

Firefox set up from Mozilla apt repository:  https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions

**Comment by alokedesai** [comment]
Hey all, thanks for your patience here. @daprahamian is currently investigating this and we expect to have a fix out for it relatively soon.

**Comment by yulrizka** [comment]
seems like This is solved now with the latest version
