### ISSUE TITLE
SSH: Cannot SSH when config includes a RemoteCommand

### ISSUE THREAD

**Issue by dbowling** [warpdotdev/Warp#419]
### Describe the bug

When using RemoteCommand in my SSH config (using MacOS) I get the following error: Cannot execute command-line and remote command.

```shell
Hosts that do not use the RemoteCommand setting perform SSH correctly.
```

### To Reproduce

Steps to reproduce:
1. Edit .ssh/config and add a host with a RemoteCommand, such as `RemoteCommand tmux new -A -s anynameyoulike`
2. run the SSH command `ssh hostname`

### Expected behaviour

```shell
SSH to connect to the server and run the command.
```

### Operating System

MacOS

### OS Version

12.0.1

### Additional context

```shell
Hosts with `ProxyCommand ssh -W %h:%p proxyhostname.tld` are not impacted.
```

**Comment by elviskahoro** [comment]
@dbowling 
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
