### ISSUE TITLE
Warp update on 19 Feb (Ubuntu Linux) doesn't work?

### ISSUE THREAD

**Issue by paulnakroshis** [warpdotdev/Warp#4196]
### Discord username (optional)

paul_nakroshis

### Describe the bug

I ran the updater and although it appears to work (it installs and restarts Warp), when Warp reopens, it still says update warp at the top of the terminal window. 

### To reproduce

See above.

### Expected behavior

I expect to see NO "Update Warp" at the top of the terminal window .,

### Operating system

Linux

### Operating system and version

Ubuntu 22.04.4 LTS

### Shell Version

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.02.16.17.24.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by df-dev** [comment]
Having the same issue on POP OS. 
- I run the update command, 
- Warp restarts as if to update, 
- No update is applied. 
- Restarting warp manually shows `Update Warp` button again.

**Comment by dannyneira** [comment]
Hey all!  Due to feedback from the community, we've decided to change the name of our `apt/rpm/pacman` packages from `warp` to `warp-terminal`.  Alongside this change, we're updating the name of our config and data directories to warp-terminal to match.

For all users: we recommend moving or copying your config folders to the new location, as the just-released app update will look for files in the new paths.  Specifically:
```
mv ~/.config/warp ~/.config/warp-terminal
mv ~/.local/state/warp ~/.local/state/warp-terminal
mv ~/.local/share/warp ~/.local/share/warp-terminal
```

If you've installed one of the non-AppImage packages, run one of the below commands (as appropriate for your system):
```
sudo apt remove warp && sudo apt update && sudo apt install warp-terminal
sudo dnf remove warp && sudo dnf --refresh install warp-terminal
sudo zypper remove warp && sudo zypper --refresh install warp-terminal
sudo pacman -R warp && sudo pacman -Sy warp-terminal
```

Sorry for the hassle, and thank you all so much for your valuable feedback throughout the private beta process!  We can't wait for the public launch on Thursday, Feb 22nd 2024! We couldn't have done it without you all. ❤️

**Comment by vorporeal** [comment]
Hi, thanks for letting us know! What method did you use to install Warp? What version are you currently running, and what version is Warp trying to update to?

**Comment by vorporeal** [comment]
Also if you wouldn't mind sharing your latest logs (from `~/.local/state/warp-terminal/warp.log`) they might help us figure out what's going wrong.

**Comment by df-dev** [comment]
> Hey @paulnakroshis and @df-dev! Due to feedback from the community, we've decided to change the name of our `apt/rpm/pacman` packages from `warp` to `warp-terminal`. Alongside this change, we're updating the name of our config and data directories to warp-terminal to match.
> 
> For all users: we recommend moving or copying your config folders to the new location, as the just-released app update will look for files in the new paths. Specifically:
> 
> ```
> mv ~/.config/warp ~/.config/warp-terminal
> mv ~/.local/state/warp ~/.local/state/warp-terminal
> mv ~/.local/share/warp ~/.local/share/warp-terminal
> ```
> 
> If you've installed one of the non-AppImage packages, run one of the below commands (as appropriate for your system):
> 
> ```
> sudo apt remove warp && sudo apt update && sudo apt install warp-terminal
> sudo dnf remove warp && sudo dnf --refresh install warp-terminal
> sudo zypper remove warp && sudo zypper --refresh install warp-terminal
> sudo pacman -R warp && sudo pacman -Sy warp-terminal
> ```
> 
> Sorry for the hassle, and thank you all so much for your valuable feedback throughout the private beta process! We can't wait for the public launch on Thursday, Feb 22nd 2024! We couldn't have done it without you all. ❤️

thank you.

**Comment by synnoveolsdatter** [comment]
Experiencing the same issue, assumed it was due to me using a different tiling window manager than gnome (I was using i3) but even when switching to gnome it still crashes.

**Comment by romfil-trim** [comment]
Experiencing the same on Ubuntu 24.10. All directories are set to warp-terminal, there is no `warp` directory at the above mentioned locations. The only "fix" so far was to `apt remove warp-terminal` and then reinstall it from warp download page for Ubuntu.

**Comment by romfil-trim** [comment]
> Experiencing the same on Ubuntu 24.10. All directories are set to warp-terminal, there is no `warp` directory at the above mentioned locations. The only "fix" so far was to `apt remove warp-terminal` and then reinstall it from warp download page for Ubuntu.

I see now that this is mentioned as a known issue [in the warp docs known issues with Linux page](https://docs.warp.dev/help/known-issues#warp-upgrade-fails-after-upgrading-linux).

**Comment by vorporeal** [comment]
Hey @romfil-trim - this issue was from back in February when we first launched Warp on Linux.  Did the instructions on our documentation page fix the issue for you?  If not, please open a new issue and we can discuss further there.
