### ISSUE TITLE
Add a "new window" item to the dock icon menu

### ISSUE THREAD

**Issue by michbarsinai** [warpdotdev/Warp#420]
### Describe the solution you'd like?

```shell
Adding a "new terminal window" item to Warp's Dock icon menu.
```

### Is your feature request related to a problem? Please describe.

```shell
Currently, in order to create a new window one has to switch to Warp and choose "new window"
 from the menu bar. That's inefficient (compared to a Dock menu item), and also might require moving to a different workspace/desktop (e.g. when in trying to open a Warp window in a space where there are no other Warp windows).
```

**Comment by bglw** [comment]
I'm very keen to see this one land — I always right-click the icon expecting the new window option to be there and am surprised every time. 

To expand on this, many apps also surface a list of the open windows in the dock menu which can switch between them. As someone who might have 6 warp instances on different spaces, it would be great to get feature parity on this interaction as well.

**Comment by lzm0** [comment]
I would love this feature. Sometimes I am not on a screen with an existing Warp window and hence cannot do a `Command-N`
Related to https://github.com/warpdotdev/Warp/issues/1096

**Comment by TheNoim** [comment]
Without this warp doesn't feel like a native macos application.

**Comment by elviskahoro** [comment]
This has been triaged but no ETA on release. Will circle back here when it's a WIP.

**Comment by philjones88** [comment]
Was about to raise this as a feature request but tagging on support for this issue. I use a lot of MacOS desktops and with trying to migrate from iTerm2 it's a feature I'm really missing.

**Comment by lzm0** [comment]
I have created an AppleScript to create a new Warp window for convenience.
```AppleScript
tell application "System Events" to tell process "Warp"
	click menu item "New Window" of menu 1 of menu bar item "File" of menu bar 1
end tell
tell application "/Applications/Warp.app" to activate
```
Save it as an Application and create an Automator Quick Action that launches it.
Then, assign a keyboard shortcut to that Quick Action.

**Comment by randallhammond-whs** [comment]
Another vote for this issue

**Comment by alokedesai** [comment]
Closing this out since this is now fixed!

**Comment by dannyneira** [comment]
Hey Folk, related to right-clicking on Warp dock icon, in the latest release, Warp sets the title of the windows active tab/pane!

![CleanShot 2023-02-10 at 11 31 01](https://user-images.githubusercontent.com/16809145/218170151-aac11525-0137-4060-95c2-5f111dd295cd.png)
