### ISSUE TITLE
Allow removal of title bar and/or Icons in the title bar

### ISSUE THREAD

**Issue by mac-codes9** [warpdotdev/Warp#4200]
### Discord username (optional)

*No response*

### Describe the solution you'd like?

The only thing stopping me from moving from Alacritty full time is the fact the title bar can't be edited, I don't need to be able to see the settings and lightbulb indicators all the time. Allow me to hide the title bar entirely or at least edit what's visible.

It can mess with the consistency of how someones setup looks. Other than that great work.

### Is your feature request related to a problem? Please describe.

*No response*

### Additional contexts5

*No response*

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hey @mac-codes9 Thanks for submitting this. We already have a request tracking "Zen mode" or no tab bar this over at #1009 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
