### ISSUE TITLE
[UX improvement PLEASE!] please provide hiding top bar options, and remove the border of the terminal. 

### ISSUE THREAD

**Issue by arglin** [warpdotdev/Warp#4207]
### Describe the solution you'd like?

First of all, thank you all for this nice tool! But there are stop me switching from iterm2 to warp. Here is one of them(level 5):

Please provide hiding top bar options, and remove the border of the terminal. *

1. as a terminal user who doesn't like using mouse, the tabs feature is useless, with the help of tmux there is no need for tabs. So if there is an option to hide the tabs bar, will be great.
2. from the UX point of view, hiding the top bar like iTerm2 does, improve the experience a lot, now Warp looks so much messy, buttons everywhere.
3. form the UX point of view, the border of the warp is ugly. when I open lvim, you can see the background color is not match. Why do I need to see the border of Warp? it is a waste of space.

Bad example: *And please ask the warp UX designer see this!!!**
<img width="1667" alt="image" src="https://github.com/warpdotdev/Warp/assets/48913228/7610e444-86c1-48dc-97c2-e4a349d53bef">
The UI of Warp feels really messy tbh. It looks like an application with loads of unnecessary buttons instead of a shell like clean terminal...   

Good example:
This is iTerm2, I can set it like this so no any distracting elements!
<img width="1667" alt="image" src="https://github.com/warpdotdev/Warp/assets/48913228/918adfaf-7141-438d-a59f-f1d32ac1ced0">

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by iocron** [comment]
I also want do add another point, the title-bars in splitview (as well as the black borders left and right) take too much space and are not used. See screenshot. 
![image](https://github.com/warpdotdev/Warp/assets/3641649/6a4f6805-6c22-4eea-98d8-f90027ce801d)

**Comment by ldelossa** [comment]
Plus one to this. 

As a Sway user who relies on the WM/Compositor to create "tabbed" windows a simple single pane terminal is reused in different Sway windows. 

Warp is super cool but for situations like this its using ALOT of screen real estate. Hope that this can be done sooner or later :).

**Comment by dannyneira** [comment]
Thanks for submitting this @arglin 

We already have a request tracking this request for hiding the top bar at #1009 and a request for the removal of padding here #2373 

If you could please give those a 👍 and subscribe to those requests, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by ldelossa** [comment]
Thanks!
