### ISSUE TITLE
ARM64 Linux Release

### ISSUE THREAD

**Issue by IsaacMarovitz** [warpdotdev/Warp#4213]
### Describe the solution you'd like?

With the release of Warp on Linux, it would be nice to get ARM64 builds for Asahi Linux and similar distros.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by MishaCato** [comment]
Adding to the reasoning: we are using Mac to develop cross-platforms apps and use Linux on a Parallels VM, at times as the MAIN working window...
While not really a show-stopper, we'd love to see Warp running on an ARM-based Linux VM (or native host...)
Thanks.

**Comment by RedstoneWizard08** [comment]
+1 for Raspberry Pi without something like box64

**Comment by Spl0itable** [comment]
Surprised an arm64 option wasn't at launch, but very hopeful it releases soon. Thanks @dannyneira

**Comment by danslinky** [comment]
Would love to see `aarch64` / `arm64`, lots of love, an Asahi user

**Comment by RedstoneWizard08** [comment]
also quick note: this does not work with box64. :( can't wait for this release tho! warp looks amazing!

**Comment by gabrieldonadel** [comment]
I got this working using https://fex-emu.com/

**Comment by joyshmitz** [comment]
Waiting aarm64/arm64

**Comment by hellonico** [comment]
Please aarm64/arm64n

**Comment by ModernTTY** [comment]
Is there any progress on Warp Linux ARM64 support?

**Comment by daprahamian** [comment]
Hi y'all,

Dan from Warp here. We are currently working on ARM64 versions of Warp on Linux, and are looking for users to test it out. If you are interested in trying out our build, please e-mail `feedback@warp.dev` w/ the subject line `ARM64 Test`.

**Comment by Spl0itable** [comment]
> Hi y'all,
> 
> 
> 
> Dan from Warp here. We are currently working on ARM64 versions of Warp on Linux, and are looking for users to test it out. If you are interested in trying out our build, please e-mail `feedback+arm@warp.dev` w/ the subject line `ARM64 Test`.

Email sent. Hope to hear soon. Thanks 🙏

**Comment by alokedesai** [comment]
Hi everyone, we sent an initial email to a few users who emailed feedback+arm@warp.dev to start testing the ARM build. We expect to release ARM support within the next few weeks, thanks for your patience here!

**Comment by daprahamian** [comment]
Hi all,

I am happy to announce that you can now download arm64 versions of Warp at https://warp.dev/download. I am going to close the ticket for now.

**Comment by thegoodduck** [comment]
Btw... i tested it on my pi 400 its amazig software but very slow and buggy at least on my pi

**Comment by alokedesai** [comment]
@thegoodduck That shouldn't be happening, thanks for flagging to us. Would you mind creating a new issue so we can track this? Feel free to tag me in it.

**Comment by aliir74** [comment]
I saw the download page in warp but there wasn't any arm64 version to download :thinking:

**Comment by buchanan** [comment]
> Hi all,
> 
> I am happy to announce that you can now download arm64 versions of Warp at https://warp.dev/download. I am going to close the ticket for now.

@daprahamian This download page was difficult to find. You may want to make these links more visible from the downloads page https://app.warp.dev/get_warp

**Comment by daprahamian** [comment]
> > Hi all,
> > I am happy to announce that you can now download arm64 versions of Warp at https://warp.dev/download. I am going to close the ticket for now.
> 
> @daprahamian This download page was difficult to find. You may want to make these links more visible from the downloads page https://app.warp.dev/get_warp

Hi @buchanan!

Thanks for bringing this up. Can you elaborate a little more into where you found difficulty finding the download page? Were you looking from https://warp.dev, or were you directed to https://app.warp.dev/get_warp and could not find the downloads?
