### ISSUE TITLE
Cannot Copy Paste in New Workflow Dialogue

### ISSUE THREAD

**Issue by da-vinci-noob** [warpdotdev/Warp#4218]
### Describe the bug

Not able to Copy/Paste in the New Warp Workflow in Ward Drive.
When pressing CTRL+C, it deletes the text.
When Pressing CTRL+V, it doesn't do anything.

### To reproduce

1. Open Warp Terminal
2. Open Ward Drive
3. Create New Workflow
4. Try Copy/Paste

### Expected behavior

It Should Copy when Pressing CTRL+C
It Should Paste when Pressing CTRL+V

### Operating system

Linux

### Operating system and version

Ubuntu 22.04.3 LTS

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by da-vinci-noob** [comment]
> @da-vinci-noob Why was this closed? I have the same issue

CTRL+C/V doesn't works.
But CTRL+Shift+C/V works for Copy Paste respectively as kry bindings from Linux Terminal.

**Comment by jsdevtom** [comment]
Just updated to v0.2024.02.20.08.01.stable_02 and experiencing the same behaviour

**Comment by jsdevtom** [comment]
@da-vinci-noob Perfect, thank you for the explanation.

**Comment by jsdevtom** [comment]
Perhaps a notification/ toast somewhere after multiple Ctrl+V's with "Are you trying to paste?  Use the standard terminal keybindings Ctrl+Shift+V instead" with the button "Don't show this message again" could be helpful.

**Comment by da-vinci-noob** [comment]
> Perhaps a notification/ toast somewhere after multiple Ctrl+V's with "Are you trying to paste?  Use the standard terminal keybindings Ctrl+Shift+V instead" with the button "Don't show this message again" could be helpful.
> 
> 

Yeah! Sadly it isn't. It should be as CTRL+C was deleting text. I was confused. Then after multiple tries. I get the working keys.
