### ISSUE TITLE
Arch Linux Warp terminal not fitting on screen

### ISSUE THREAD

**Issue by HenryMigo** [warpdotdev/Warp#4229]
### Describe the bug

When I open the terminal it doesn't fit on the screen within my OS. This is where ever I boot it up on this laptop.

### To reproduce

1. Start warp
2. Loads fully expanded not fitting in.

### Expected behavior

Expected Warp to scale with the format.

Attached image of what kitty terminal does.

### Screenshots

Expected: ![output](https://github.com/warpdotdev/Warp/assets/10053087/dcf50aa2-312b-4016-9208-ccd82d64527c)

Actual: ![output](https://github.com/warpdotdev/Warp/assets/10053087/fd0130f5-e5b0-4e23-8c1e-8783307667c2)

### Operating system

Linux

### Operating system and version

Arch Linux

### Shell Version

GNU Bash, Version 5.2.26(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.02.20.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I usually use Kitty for my terminal.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by vorporeal** [comment]
Hey @HenryMigo, thanks for letting us know!

What window manager are you using here?

**Comment by HenryMigo** [comment]
@vorporeal Hello!

The XDG_CURRENT_DESKTOP is Hyprland, please let me know if this isn't what you are looking for.

**Comment by vorporeal** [comment]
There's currently an issue where Warp windows, by default, are treated as floating instead of being tiled - if you push the window down into the tile stack (not sure what the default keybinding is for that on Hyprland), does that improve things?

**Comment by HenryMigo** [comment]
I don't know how I would go about doing that, I will try figure that out

**Comment by HenryMigo** [comment]
Got it, for me its my windows key + v, that's fixed it

bind = $mainMod, V, togglefloating, # Allow a window to float

**Comment by HenryMigo** [comment]
I do notice it always stays on top as well, so it doesn't split if another application is loaded.

**Comment by vorporeal** [comment]
Yeah, that's because of the floating issue.

Other users have recommended adding this window rule to their Hyprland configuration to force Warp to tile instead of float:

`'tile,class:^dev.warp.Warp.*$'`

**Comment by HenryMigo** [comment]
That seems to have fixed it opening as a float, but it appearing on top still exists. I am not so bothered by that and my original query has been answered :)

I will close this now thanks again!
