### ISSUE TITLE
Blurry text in Wayland

### ISSUE THREAD

**Issue by potatoeggy** [warpdotdev/Warp#4234]
### Describe the bug

Warp is noticeably blurrier than other terminals like GNOME Terminal, Konsole, Alacritty, etc.

On a 1920x1080 display, Sway 1.8.1. Maybe it's because it's running in XWayland as opposed to native Wayland?

### To reproduce

Open Warp

### Expected behavior

It should look the same

### Screenshots

vs Alacritty:

![image](https://github.com/warpdotdev/Warp/assets/25178974/a08bf9af-34e5-4c92-9241-46403cf73a8e)

### Operating system

Linux

### Operating system and version

Arch Linux

### Shell Version

zsh 4.9

### Current Warp version

v0.2024.02.20.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by 0bCdian** [comment]
This is 100% xwayland's fault, so until the warp team supports native Wayland there's no fix.

**Comment by HenryMigo** [comment]
I just noticed this through `hyprctl clients` and saw it was using xwayland, this might be causing a lot of my issues with it while using Wayland and Hyprland

**Comment by ThatOneCalculator** [comment]
Can repro, although I haven't bothered to get past that pesky sign-up screen. It's ridiculous that a new product -- especially one targeted at developers -- would opt to FORCE people to use X and potentially have to emulate the entire X protocol through XWayland JUST IN ORDER TO USE their terminal.

**Comment by strophy** [comment]
I tried Warp on stock Ubuntu 22.04 LTS running Gnome 45.2 on Wayland. I have two monitors:
- Laptop panel 1920 x 1200 with 125% scaling
- External monitor 3840 x 2160 with 150% scaling

Warp is totally blurry on the 4k monitor, the rounded corners and all GUI elements are pixelated and text painful to read. Screenshot attached, note the visual artifacts will only be visible when viewed at 100% scaling. System terminal is perfectly sharp and pixel-perfect, Warp looks like a blurry mess. Please don't use XWayland crap, make it native Wayland and respect the system resolution and scaling settings.
![Screenshot from 2024-02-23 11-11-50](https://github.com/warpdotdev/Warp/assets/32928115/d50f0bc3-35c5-4324-8389-76968edd7b7b)

**Comment by dannyneira** [comment]
Hey folks! Thanks for your patience while trying Warp. Could you download this preview version of Warp and see if it fixes your issues:

[deb](https://releases.warp.dev/stable/v0.2024.02.27.08.01.stable_00/warp-terminal_0.2024.02.27.08.01.stable.00_amd64.deb)
[rpm](https://releases.warp.dev/stable/v0.2024.02.27.08.01.stable_00/warp-terminal-v0.2024.02.27.08.01.stable_00-1.x86_64.rpm)
[pacman](https://releases.warp.dev/stable/warp-terminal-v0.2024.02.27.08.01.stable_00-1-x86_64.pkg.tar.zst)
[appimage](https://releases.warp.dev/stable/v0.2024.02.27.08.01.stable_00/Warp-x86_64.AppImage)

If using Wayland, you can enable Wayland support by setting the `WARP_ENABLE_WAYLAND` envar (e.g`WARP_ENABLE_WAYLAND=1 warp-terminal`).

**Comment by potatoeggy** [comment]
![image](https://github.com/warpdotdev/Warp/assets/25178974/39d452db-8ada-474b-a77f-02e4f1c376d6)
Unfortunately it still looks about the same :/. stable on top left, preview w/WARP_ENABLE_WAYLAND on bottom left, and alacritty on right

**Comment by dannyneira** [comment]
Hey folks! Thanks for your patience while trying Warp. Could you download this preview version of Warp and see if it fixes your issues:

[deb](https://releases.warp.dev/stable/v0.2024.02.27.08.01.stable_00/warp-terminal_0.2024.02.27.08.01.stable.00_amd64.deb)
[rpm](https://releases.warp.dev/stable/v0.2024.02.27.08.01.stable_00/warp-terminal-v0.2024.02.27.08.01.stable_00-1.x86_64.rpm)
[pacman](https://releases.warp.dev/stable/warp-terminal-v0.2024.02.27.08.01.stable_00-1-x86_64.pkg.tar.zst)
[appimage](https://releases.warp.dev/stable/v0.2024.02.27.08.01.stable_00/Warp-x86_64.AppImage)

If using Wayland, you can enable Wayland support by setting the `WARP_ENABLE_WAYLAND` envar (e.g`WARP_ENABLE_WAYLAND=1 warp-terminal`).

**Comment by EndCredits** [comment]
An issue provided by @Ethan0429 in the #4482 for warp-terminal crashed on NixOS seems to be ignored. Since fractional scaling topic will be continued here, move the discussion here too.

> I've looked for some package `libwayland*` or `waylandlib` and cannot find anything in the Nixpkgs repo

Since wayland related libraries are always being dlopen()ed by warp-terminal which is clearly can't work with NixOS. I think we should export wayland libraries to ```LD_LIBRARY_PATH``` just like what we did for electron apps.

On postInstall stage, maybe we can do something like

```nix
    postInstall = ''
      wrapProgram "$out/bin/warp-terminal" \
          --set LD_LIBRARY_PATH ${lib.makeLibraryPath [ pkgs.wayland ] }
    '';
```

To work around this issue

**Comment by hykilpikonna** [comment]
> Hey folks! Thanks for your patience while trying Warp. Could you download the latest version of Warp at [warp.dev/linux-terminal](https://www.warp.dev/linux-terminal) ?
> 
> If using Wayland, you can enable Wayland support by setting the `WARP_ENABLE_WAYLAND` envar (e.g`WARP_ENABLE_WAYLAND=1 warp-terminal`).

Crashes on login:

```
20:39:02 [INFO] Dispatched auth url to window 1
20:39:02 [INFO] dispatching action for "root_view:handle_incoming_auth_url"
20:39:02 [INFO] Dispatched auth url to window 0
20:39:02 [INFO] dispatching action for "root_view:handle_incoming_auth_url"
20:39:02 [WARN] Re-initializing Gles context due to Wayland window
20:39:02 [INFO] Enabled wgpu backends: Backends(VULKAN | GL | METAL | DX12 | DX11 | BROWSER_WEBGPU)
20:39:02 [INFO] Available wgpu adapters (in priority order):
20:39:02 [ERROR] enumerate_adapters: Initialization of an object has failed
20:39:02 [INFO] Other: AMD Radeon Graphics (radeonsi, gfx1103_r1, LLVM 17.0.6, DRM 3.57, 6.8.4-arch1-1)
	Backend: Gl
	Driver: Unknown
	Can present? true
	Supported texture format: Some(Rgba8UnormSrgb)
20:39:02 [INFO] Verifying adapter "AMD Radeon Graphics (radeonsi, gfx1103_r1, LLVM 17.0.6, DRM 3.57, 6.8.4-arch1-1)" is valid...
20:39:02 [INFO] Using Other (AMD Radeon Graphics (radeonsi, gfx1103_r1, LLVM 17.0.6, DRM 3.57, 6.8.4-arch1-1)) for rendering new window.
20:39:02 [INFO] WindowId(0) will close
20:39:02 [INFO] dispatching global action for workspace:save_app
20:39:02 [INFO] window resized
20:39:02 [INFO] dispatching global action for workspace:save_app
thread 'main' panicked at /home/runner/.cargo/git/checkouts/wgpu-163ac9f6133c4ea6/70ade4c/wgpu-hal/src/gles/egl.rs:305:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
```

**Comment by dannyneira** [comment]
Hey Folks, Warp now supports Wayland. You can configure the window system in `Settings > Features > System`. See more in our [changelog](https://docs.warp.dev/getting-started/changelog#id-2024.09.19-v0.2024.09.17.08.02) and [docs](https://docs.warp.dev/features/linux#native-wayland).

Please let us know if this helps with the blurry text you're seeing in Wayland.

**Comment by potatoeggy** [comment]
Hi, thanks for the release! This solved my blurriness problem.
