### ISSUE TITLE
Infomation of location of Launch Configuration files displays macOS location on Linux

### ISSUE THREAD

**Issue by Lily418** [warpdotdev/Warp#4238]
### Describe the bug

When using Warp for Linux and following the steps to save a launch configuration
https://docs.warp.dev/features/sessions/launch-configurations#how-to-use-it

I see `The YAML file is saved to ~/.warp/launch_configurations/`  

Looking at the documentation I see the path is different for Linux
https://docs.warp.dev/features/sessions/launch-configurations#yaml-format

### To reproduce

1. Use Warp for Linux
2. Follow steps to save a launch configuration https://docs.warp.dev/features/sessions/launch-configurations#how-to-use-it
3. Observe the path matches the macOS path, not the linux path https://docs.warp.dev/features/sessions/launch-configurations#yaml-format

### Expected behavior

I expected to see the Linux path for save location of launch configurations `${XDG_DATA_HOME:-$HOME/.local/share}/warp-terminal/launch_configurations/`

### Screenshots

![Screenshot from 2024-02-22 20-02-08](https://github.com/warpdotdev/Warp/assets/1368025/2a40248d-783d-4920-8159-176f617cb34d)

### Operating system

Linux

### Operating system and version

Ubuntu 22.04.3 LTS

### Shell Version

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.02.20.08.01.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Additional context

Super excited to start using Warp for Linux! You are a star :star: 

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks again @Lily418 this should now be resolved in the latest Warp version.

![CleanShot 2024-05-15 at 17 17 02](https://github.com/warpdotdev/Warp/assets/16809145/72bcfacb-2075-4a8e-8474-4d91c4ca747f)

Closing as resolved, but please update and let us know if any issues.
