### ISSUE TITLE
Button to go to the top of the block obscures output of command

### ISSUE THREAD

**Issue by NielsLeenheer** [warpdotdev/Warp#424]
### Describe the bug

```shell
When I execute a command that uses the whole terminal screen a button appears to scroll to the top of the current block. That button is rendered on top of the terminal contents, so it obscures potential important information. 

For example when executing the `top` command it is displayed right on top of the load average.
```

### To Reproduce

Steps to reproduce:
1. Execute a command like `top`
2. A button appears on top of the content

### Expected behaviour

```shell
The button for scrolling to the top is nice to have, but for me it is not important enough for it to obscure the contents. It should definitely be able to turn it off.
```

### Screenshots

In the screenshot below you can see me executing the top command and the ( ^ top ) button is blocking the view of the load average for the server.

<img width="1242" alt="Screenshot 2021-11-17 at 11 52 24" src="https://user-images.githubusercontent.com/233230/142187382-06a52d76-a845-468a-aab8-320bf48c860a.png">

### Operating System

MacOS

**Comment by elviskahoro** [comment]
@NielsLeenheer We're trying to reproduce this but are having difficulty? Can you share steps or a video please?

**Comment by liux2** [comment]
> @NielsLeenheer We're trying to reproduce this but are having difficulty. Can you share steps or a video please?

Hi, I don't think it is a bug. I think it is a feature to improve.

In my case, I am using `byobu` to manage my sessions. Therefore, my command input is always from top to bottom. The jump to the top prompt is blocking my view. As the screenshot shows:

<img width="1430" alt="Screen Shot 2022-04-25 at 6 13 10 PM" src="https://user-images.githubusercontent.com/23517453/165189333-9f0f477d-cb0a-4919-8c30-4f5741d74646.png">
 
Is it possible that the prompt can be transparent? Or any other ways to make it not block the terminal...

**Comment by elviskahoro** [comment]
Gonna merge this into #8

**Comment by 3gmgithub** [comment]
I get the prompt offscreen when logging into a server that is using BYOBU.
I have to scroll up to see the prompt all the time...
