### ISSUE TITLE
Can't bind Cmd + ` as global hotkey 

### ISSUE THREAD

**Issue by K4stor** [warpdotdev/Warp#4246]
### Describe the bug

On my mac I am trying to bind ` + Command as global hotkwy.
` + alt works for example. But somehow ` + cmd wont

### To reproduce

1. Go to settings 
2. Select Features
3. Try to bind ` + cmd als global hotkey

### Expected behavior

` + cmd should be bound as global hotkey

### Operating system

MacOS

### Operating system and version

Sonoma 14.3

### Shell Version

zsh

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
hey @K4stor sorry about this, but on macOS, [system keyboard shortcuts](https://support.apple.com/en-us/HT201236) like CMD-ESC, CMD-BACKTICK, CMD-TAB, CMD-PERIOD, and CMD-TILDE need to be [unbound](https://support.apple.com/guide/mac-help/keyboard-shortcuts-mchlp2262/mac) before you can use them in Warp. See more about the global hotkey in our docs https://docs.warp.dev/features/windows/global-hotkey

Please let me know if that helps with your issue.
