### ISSUE TITLE
Add fullscreen option (F11) on linux

### ISSUE THREAD

**Issue by mrmelon54** [warpdotdev/Warp#4250]
### Describe the solution you'd like?

Sometimes I just want to temporarily use my fullscreen for my terminal (e.g. databases TUI with many columns).

I just want to press F11 to toggle fullscreen mode like in many video games.

### Is your feature request related to a problem? Please describe.

I can't use fullscreen mode

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by jimcornmell** [comment]
+1

**Comment by manuelparra1** [comment]
+1. I thought I was going crazy. I couldn't find any way of making Warp full-screen in the shortcuts.

**Comment by Zepi2509** [comment]
+1. Full screen would be pretty nice. Maybe even the option to display full screen apps like vim without borders

**Comment by dannyneira** [comment]
Thanks for this feature request! 

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by miguelfs** [comment]
Hi guys, is this feature on the roadmap?

**Comment by vorporeal** [comment]
Hi there!  Built this last week and should go out in next week's release!

**Comment by vorporeal** [comment]
Update - this is live in today's release!  You can configure a "Toggle fullscreen" keybinding, which defaults to F11 on Linux and Windows.  (You can also access it through the command palette.)

Let me know if you run into any issues!
