### ISSUE TITLE
Cannot start warp-terminal on SUSE Linux Enterprise 15 SP4

### ISSUE THREAD

**Issue by stefanniemeyer** [warpdotdev/Warp#4260]
### Describe the bug

When starting warp-terminal a lot of warnings are printed and it finally exits with an error
Failed to open window: No wgpu adapter was found

See full log
[warp-error.log](https://github.com/warpdotdev/Warp/files/14382458/warp-error.log)

### To reproduce

1. Install the .rpm w/ sudo zypper install warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64.rpm
2. start the app

DISPLAY is set to ":1"

### Expected behavior

warp should start

### Operating system

Linux

### Operating system and version

SLES 15.4

### Shell Version

zsh 5.6

### Current Warp version

v0.2024.02.20.08.01.stable_01-1

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by vorporeal** [comment]
Hey there @stefanniemeyer, thanks for letting us know!

Can you share your `~/.local/state/warp-terminal/warp.log` file and the output of `glxinfo -B`?

**Comment by Imalmost** [comment]
Hello, I have same problem. My OS is OpenSuseLeep and principal error is 'Failed to open window: NO wgpu adapter was found.

**Comment by ReevesA1** [comment]
This fixed it for me on Debian 12 `sudo apt install libx11-dev`

**Comment by ITSMijaiL** [comment]
> This fixed it for me on Debian 12 `sudo apt install libx11-dev`

Thanks for the solution, fixed it in my OpenSUSE Tumbleweed installation by installing libX11-devel: `sudo zypper install libX11-devel`

**Comment by Imalmost** [comment]
Thanks, now run well !!

**Comment by stefanniemeyer** [comment]
The installation of libX11-devel helped.
I still can't used it because the login behind a proxy is a pain.

**Comment by vorporeal** [comment]
Huh, I don't know why the `-dev`/`-devel` package would be necessary, but good to know that we should add it to our package deps.

We'll fix that for this week's release.  Thanks for letting us know!

**Comment by special-k-anon** [comment]
I just ran into the same problem after the most recent update. I'm on OpenSUSE Tumbleweed too.

**Comment by Jumima67** [comment]
I got the same problem on arch and I’m on Wayland, anybody know what package I need to install?
