### ISSUE TITLE
Can't bind ctrl + ` as global hotkey on linux

### ISSUE THREAD

**Issue by FredHaa** [warpdotdev/Warp#4268]
### Describe the bug

As title describes.

I saw #4246 which reminded me to remove that keybinding from guake-terminal. Afterwards I also deleted guake and rebooted my machine, just to be sure that there was no lingering binding of that key combination.

I still cannot bind ctrl + `

### To reproduce

Open feature settings on linux (arch)

Try to bind the global hotkey as ctrl + `

### Operating system

Linux

### Operating system and version

Archlinux

### Shell Version

zsh

### Current Warp version

v0.2024.02.20.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @FredHaa , please try and run `bindkey | grep '\^`' ` to see if anything is bound to that in the system. I noticed the first time I tried to set CTRL-` it only set `, but when I pressed again it set it, so try a couple times and see if that helps.

Also FYI, `bindkey` isn't supported in Warp, so if anything is set there, it won't work in Warp. We have issue tracking support here #537

**Comment by FredHaa** [comment]
It returns nothing, i.e. nothing is bound to that combination.
I also tried with bindkey | grep "^" and looked through the list, nothing with ` showed up.

**Comment by FredHaa** [comment]
Okay, I had ^` set as a custom shortcut in gnome settings. After removing that it works.
