### ISSUE TITLE
Documentation for integrating warp to vs code on linux may not be accurate for all installations

### ISSUE THREAD

**Issue by DaveParr** [warpdotdev/Warp#4276]
### Describe the bug

[The docs for Warp on Linux with vs-code](https://docs.warp.dev/features/integrations-and-plugins#vscode) state that Settings> Terminal > External: Linux Exec to the value `warp` will allow the user to open a new warp session. 

On my installation via `.deb` download on PopOS that is not correct. The program is actually listed in apt as `warp-terminal`. 

[warp is warp-terminal](https://app.warp.dev/block/dynyrlKm3RJ9s0VF3NMyAC)

### To reproduce

1. Open VS code
2. set Settings> Terminal > External: Linux Exec to `warp`
3. press `Ctrl + Shift + C`
4. No response
5. set Settings> Terminal > External: Linux Exec to `warp-terminal`
6. A new warp session starts

### Expected behavior

When Linux Exec is `warp`, `ctrl + shift + c` opens warp session

### Operating system

Linux

### Operating system and version

Pop!_OS 22.04 LTS

### Shell Version

bash

### Current Warp version

0.2024.02.20.08.01.stable.01 amd64

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by DaveParr** [comment]
Just noticed the little clips also seem to be leftover from the macOSX instructions, so suggest using the `cmd` key and `Warp.app` as the value.

**Comment by vorporeal** [comment]
Good catch!  We'll get this fixed ASAP.

**Comment by abhishekp106** [comment]
Thanks for catching this! It's been updated!

![image](https://github.com/warpdotdev/Warp/assets/40919306/0c4472ac-ff8f-447b-9996-85ef5959bc52)
