### ISSUE TITLE
Korean typing/displaying issues

### ISSUE THREAD

**Issue by byeongjee** [warpdotdev/Warp#428]
### Describe the bug

```shell
As a Korean, I found several bugs of Warp when used along with Korean language. 

1. In Korean input mode, keybindings such as `cmd-P` do not work

The `P` key corresponds to `ㅔ` key in Korean. Physically, the two characters are the same key in keyboards, and I can switch between Korean and English input modes by pressing a toggle.
Thus, I expect `cmd-ㅔ` to be working as the same as `cmd-P`, but unfortunately it does not.

2. Korean characters are not displayed correctly

Some of my files have Korean characters in their names. 
If I use `ls` command to display them, they are displayed incompletely (or incorrectly).

3. Korean typing is not working as expected

[Korean typing system](https://www.90daykorean.com/typing-in-korean/) is quite different from English, where a single keystroke corresponds to a single character.
Two or three keystrokes complete a single Korean character. The problem is that, unlike other text editors, an incomplete character (with single keystroke) is not displayed at all until I press another key and complete the character.
```

### To Reproduce

1 and 3 can be reproduced by installing a Korean IME and typing any Korean characters.

2 can be reproduced by viewing  Korean-named files with `ls` command 

### Expected behaviour

```shell
Refer to the following screenshots.
```

### Screenshots

1. No screenshots

2.

When I see a Korean filename in Warp (bug)
![Dropbox — byeongjee@gangbyeongjis-MacBook-Pro — ~Dropbox — -zsh — 80×24 2021-11-18 at 10 45 52 PM](https://user-images.githubusercontent.com/24953444/142427019-ee711fe4-567e-49ae-bfad-4e50dcd8b6a6.jpg)

When I see the same file in the Mac default terminal (expected behavior)
![Dropbox — byeongjee@gangbyeongjis-MacBook-Pro — ~Dropbox — -zsh — 80×24 2021-11-18 at 10 46 29 PM](https://user-images.githubusercontent.com/24953444/142427090-998994a3-5dd4-49b0-80e3-2789ead750b6.jpg)

3.
When I type Korean in Warp (bug)
![Screen Recording 2021-11-18 at 10 48 41 PM](https://user-images.githubusercontent.com/24953444/142427494-c1f02ea1-f3d5-47db-8653-d31e680cace7.gif)

When  I type Korean in the Mac default terminal (expected behavior)
![Screen Recording 2021-11-18 at 10 51 20 PM](https://user-images.githubusercontent.com/24953444/142427924-d6ace15e-003c-48e2-a5d0-a16db8553db3.gif)

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
This should be fixed. Please comment if it's not working!

**Comment by Zeta611** [comment]
1 is fixed, but 2 and 3 are not. This should be reopened.
