### ISSUE TITLE
Warp Linux works fine but if I suspend and resume the window does not render at all

### ISSUE THREAD

**Issue by lgonzalezsa** [warpdotdev/Warp#4280]
### Describe the bug

Working fine in PopOS! but if I decided to suspend when resume the warp app still open but does not render

### To reproduce

Suspend the OS and resume

### Expected behavior

Warp app to continue be visible and not affected due to suspend

### Operating system

Linux

### Operating system and version

Pop!_OS 22.04 LTS 6.6.10-76060610-generic

### Shell Version

GNU bash, version 5.1.16(1)-release

### Current Warp version

v0.2024.02.20.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
hey @lgonzalezsa sorry about this issue, if you're using Wayland, we recommend you switch to X11 as that has better support. We're actively working on a fix for Wayland support thou so we appreciate your patience.

**Comment by lgonzalezsa** [comment]
Using X11
![image](https://github.com/warpdotdev/Warp/assets/704686/cb83f02a-40b2-46e8-a7aa-c4985ebfa21a)

**Comment by dannyneira** [comment]
heard, thanks for letting us know, we;re tracking this along with other related rendering issues. Please send us your logs found in `~/.local/state/warp-terminal/warp.log`. We recommend quitting Warp, deleting the log file, starting Warp again (for a fresh set of logs), and then attaching that file.

Finally, we'd benefit from the output of `glxinfo -B` (you may need to install mesa-utils to run that).

**Comment by lgonzalezsa** [comment]
A video of the issue.

https://github.com/warpdotdev/Warp/assets/704686/8104c8cf-8d58-4169-ac03-28df508b5d4e

Fresh log file attached.

[warp.log](https://github.com/warpdotdev/Warp/files/14391546/warp.log)

Here the output of `glxinfo -B`

<details><summary>Details</summary>
<p>

```
gonluisr@gonluisr-hp-zbook-15-g3:~$
glxinfo -B
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 530 (SKL GT2) (0x191b)
    Version: 24.0.0
    Accelerated: yes
    Video memory: 31978MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 530 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.0.0-1pop0~1706872735~22.04~0fa430c
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.0-1pop0~1706872735~22.04~0fa430c
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.0.0-1pop0~1706872735~22.04~0fa430c
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

```
</p>
</details>

**Comment by alokedesai** [comment]
Hey @lgonzalezsa, could you check if you're able to reproduce this on the latest version of Warp?

**Comment by lgonzalezsa** [comment]
oh forgot to close the ticket, the latest version is working like a charm! I am super happy with the terminal! awesome!
