### ISSUE TITLE
Support for NixOS

### ISSUE THREAD

**Issue by dannyneira** [warpdotdev/Warp#4286]
This issue is to track and show support for Warp for Linux on NixOS along with nix package manager.

### How important is this feature to you?

Please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified. We'll be posting updates on this thread (if/when this is being worked on).

Please avoid comments with spam-like "+1" or 👍 .

**Comment by arunoruto** [comment]
There is already a PR tracking the progress of enabling warp for Linux in NixOS: NixOS/nixpkgs#290731

**Comment by arunoruto** [comment]
Warp has been included in nixpkgs as of now, and you can see what channels have the PR already included here: https://nixtracker.org/ (the PR number is 290731).

If you want to test it right away, you can always fetch the package from the PR using the following config:
```nix
{ config, pkgs, ... }:
let
  nixpkgs-tars = "https://github.com/NixOS/nixpkgs/archive/";
in
{
  nixpkgs.config = {
    packageOverrides = pkgs: {
      pr290731 = import (fetchTarball
        "${nixpkgs-tars}046ea1a290d21e4c103683a3af2ff801bb6c8424.tar.gz")
          { config = config.nixpkgs.config; };
    };
  };

  environment.systemPackages = with pkgs; [
    pr290731.warp-terminal
  ];
}
```
(I saved it as `/etc/nixos/pr.nix` and import it in the `configuration.nix` file)

**Comment by arunoruto** [comment]
Warp is now available in the [unstable channel](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=warp+terminal)

I guess it will be available in the stable channel starting with NixOS 24.05 in a few months!

**Comment by dannyneira** [comment]
Closing as resolved now that warp-terminal is on nixOS [unstable channel](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=warp+terminal).

**Comment by thapasijan17** [comment]
+1

**Comment by arunoruto** [comment]
> +1

Warp has been available in nixpkgs for quite a while now: https://search.nixos.org/packages?channel=24.11&from=0&size=50&sort=relevance&type=packages&query=warp+terminal

**Comment by rinnegan72** [comment]
While it is available it is never up to date, why is that?
