### ISSUE TITLE
Allow pasting commands with middle button

### ISSUE THREAD

**Issue by Gabriel-p** [warpdotdev/Warp#4295]
### Describe the solution you'd like?

This is a feature from the elementary OS terminal that I use a lot. It just allows you to paste whatever is selected to the terminal through the mouse's middle button.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by Secret-chest** [comment]
Probably a standard X feature that the terminal forcefully disables.

**Comment by ablundgren** [comment]
This one is a must have for me. As a long time Unix and Linux user, not having this is a deal breaker.

**Comment by asacha-ru** [comment]
This one is an absolute deal breaker for me. I am going to remove the Warp from my computer, and wait until it is fixed

**Comment by 0x4r45h** [comment]
An absolute must-have feature. can't set Warp as my default terminal because of this :(

**Comment by igorsantos07** [comment]
Isn't this sort of a dupe of #2853?

**Comment by jcoutinhopt** [comment]
Really enjoying warp, but not having middle-click paste implemented is like a whole process of re-educating my brain. Pls implement it.

**Comment by michaelolson01** [comment]
Agreed, using the middle click on linux is expected in a terminal. Having this not work is a deterrent to using warp.

**Comment by igorsantos07** [comment]
People, please, **stop spamming issues with +1 messages**. If you have no extra opinion to share than "yep, I agree, this is needed", just **react with a :+1: on the original post**; that's what the Warp team uses to track user needs.

**Comment by jeremyronking** [comment]
> Isn't this sort of a dupe of #2853? And #2737, #416..........

If it's coming up that frequently, I would think it's a high demand feature that is missing and should be prioritized accordingly.

**Comment by ZsBT** [comment]
duplicate of #4329 I guess

**Comment by RicHincapie** [comment]
Please :)

**Comment by SMalloyNWNC** [comment]
When this is implemented, I'll switch to Warp.

**Comment by sophware** [comment]
When this is implemented, I'll try again to switch to Warp.

**Comment by dannyneira** [comment]
Thanks for submitting this @Gabriel-p 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/4329

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/4329
