### ISSUE TITLE
When updating, Warp should remember the tabs I had open

### ISSUE THREAD

**Issue by jubby2000** [warpdotdev/Warp#43]
**Is your feature request related to a problem? Please describe.**
Not exactly.

**Describe the solution you'd like**
It would be nice if the path for each open tab (and the positions of each tab) were preserved on an update or when closing Warp altogether.

**Additional context**
What currently happens: All your tabs are closed and if you were working in multiple different paths, you have to open them all up again

**Comment by zeh** [comment]
Judging by similar, lengthly discussions in the Windows Terminal repo ([#766](https://github.com/microsoft/terminal/issues/766), [#961](https://github.com/microsoft/terminal/issues/961), others), this is a harder problem than it looks, and it means different things for different people.

There's several different expected features for full restoration support, from top to bottom:

- Restore windows position
- For each window, restore opened tabs
- For each tab, restore opened folder
- For each tab, restore scroll buffer
- For each tab, restore (individual) command history
- For each tab, restore running processes

For Windows Terminal itself, they're still only at the third bullet point ("restore opened folders"), but not super functional, only on the "Preview" version, and it does require some prompt fiddling to get it working.

So for Warp I can see a gradual approach being needed, where it does thing at a time. IMO each would already improve the user experience dramatically for those who like to live with a... *complex* terminal state.

**Comment by fishcharlie** [comment]
Don't want to add too much noise. But coming from the native macOS Terminal, this is a major lacking feature in Warp. Force quitting the Terminal in macOS restores the contents of the terminal, commands & output. Looks like the default of this is 10k lines.

Hopefully Warp can prioritize this soon.

**Comment by elviskahoro** [comment]
from #243 @ShukantPal 
> I updated Warp and the terminal was reset. It would be nice if 
> 
> 1. The old processes were killed. I had to run `killall mongod` to restart my MongoDB instance.
> 
> OR
> 
> 2. The old processes aren't orphaned and the logs get preserved.
>

**Comment by elviskahoro** [comment]
Was added!
