### ISSUE TITLE
Mouse scroll speed line count

### ISSUE THREAD

**Issue by kolorafa** [warpdotdev/Warp#4308]
### Describe the solution you'd like?

Setting for mouse scroll speed/multiplier.
To be able to adjust the speed to for example 3x

### Is your feature request related to a problem? Please describe.

80% of time my output of commands have at least 4-5 screen length, and I'm a mouse guy in terms of scrolling up down on terminals, browsers and everywhere, so Warp terminal looks nice, but that 3x slower scroll speed compared to any other terminals is a show stopper for me.

Your AI answered me that Warp doesn't have any settings for that and suggested to change global system mouse speed change - that would not not only f..up all other application mouse scroll speed but also make them way to fast if you compare the difference between them that is close to 10x difference.

### Additional context

Context of doing one full motion mouse scroll from up to down without moving the hand, only finger:

Firefox - scrolls +/- 130% of a screen height
Chrome - scrolls +/- 120% of a screen height
Konsole - scrolls +/- 50% of screen - 33lines
Warp - scrolls +/-  15% of the screen - 11 lines ...

Mouse for my whole scroll motion gesture generate around 11 ticks, for Konsole it always multiply by 3 lines, so the % of the page depends on the font size, for chrome it's always the same height.

OS: Linux Arch (Antergos [RIP])
DE: Plasma 5 (X11)

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by durzo** [comment]
+1 on this.

all other terminals (on linux) I use, pressing shift + PgUp actually goes up a whole page as intended while Warp only supports scrolling line by line - this is very frustrating trying to examine output that is multiple pages.

At the very least, i would like to be able to configure how many lines it jumps per mouse wheel scroll

**Comment by DavidRubio24** [comment]
This is necessary feature, the scroll speed is a flow breaker. Or at least it should default to the scroll speed of other terminals.

The work around I'm using is Ctrl+Up / Ctrl+Down to move between blocks and Ctrl+Shift+Up / Ctrl+Shift+Down to go to the beginning or end of the selected block. Not good enough, though.

**Comment by alokedesai** [comment]
![image](https://github.com/warpdotdev/Warp/assets/4110292/1a7393e9-302c-4091-9a0e-2802dd48d321)


Hey everyone, this is now configurable in settings. I'm going to close, but please reopen if you're still experiencing issues!

**Comment by romfil-trim** [comment]
On Ubuntu 24.10, I'm working with a touchpad and have a similar issue, except with touch. Whereas with other apps scroll by moving two fingers up or down to scroll may move the whole screen up or down, Warp limits the scroll a lot more.

On Mac OS, this works fine and scrolls just like every other app, with scroll acceleration and stop.
