### ISSUE TITLE
Newline added to end of PS1 prompt

### ISSUE THREAD

**Issue by MathewBlanc** [warpdotdev/Warp#4309]
### Describe the bug

I have my cursor inset from the side of the terminal window, following an emoji (makes it easier to see where commands are). In Warp, it looks like a newline is being added after my PS1, so the cursor is on a new line.  I've tried compact mode, but no change. 

This is what the prompt looks like in Alacritty (and Terminal, and VSCode terminal), note the cursor after the 🔶:
<img width="296" alt="image" src="https://github.com/warpdotdev/Warp/assets/24759337/374eb30d-e0ba-44e0-b2ce-d070be369c47">

This is what it looks like in Warp, with the cursor on the line below:
<img width="335" alt="Screenshot 2024-02-24 at 8 54 01 pm" src="https://github.com/warpdotdev/Warp/assets/24759337/47756d89-32e0-45d8-9991-5dc4ec6915fa">

This is the prompt config:

`PROMPT=''$'\n''%B%F{white}· · · · · · · ·%b%f'$'\n'$'\n''%B%F{white}💎: %n%b%f'$'\n''%B%F{white}📁: %4~%b%f'$'\n''${()dir_status}'$'\n''%B%F{white}    🔶 %b%f'`

### To reproduce

1. Use this prompt code to replace your current PS1 (tested):

`PS1=''$'\n''%B%F{white}· · · · · · · ·%b%f'$'\n''%B%F{white}    🔶 %b%f'`
2. The cursor should be on the line below where it's meant to be.

### Expected behavior

The cursor should appear right after the end of the prompt, without a newline/carriage return.

### Operating system

MacOS

### Operating system and version

Ventura 13.2.1

### Shell Version

zsh 5.8.1

### Current Warp version

v0.2024.02.13.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Haz3lnut** [comment]
I have found that after entering the terminal, if I `source ~/.bashrc` my prompt is then rendered correctly on 1 line.

**Comment by MathewBlanc** [comment]
I just tried that, and it didn't work for me. I use zsh, so that might be part of it

**Comment by oliversturm** [comment]
I see the same problem using Warp version v0.2024.05.28.08.02.stable_00 and zsh with starship prompt -- a default starship setup is enough to demonstrate this problem.

Prompted by @Haz3lnut 's comment about bash, I noticed this.

- Run `bash` from my zsh -- the prompt `bash-3.2$` appears, and the cursor is shown behind that prompt on the same line - Following the hint "Warpify subshell", I press Ctrl-I
- Warp proudly tells me "Success! This sub shell spawned by bash has been Warpified"
- At the same time, the prompt is now broken. I still see `bash-3.2$`, but now the cursor sits underneath the prompt on a new line.

**Comment by oliversturm** [comment]
I just found that apparently this strange behavior is supposed to be a feature, and a request exists to make the terminal behave like all under terminals under the sun: #2304 

Never crossed my mind, apologies.

**Comment by Advait-M** [comment]
I believe this is fixed with the release of Same Line Prompt 😄 - check out https://github.com/warpdotdev/Warp/issues/2304#issuecomment-2223352668 for details. Closing out this issue!
