### ISSUE TITLE
Warp Terminal Not closed after close  ( show in htop )

### ISSUE THREAD

**Issue by t101804** [warpdotdev/Warp#4341]
### Discord username (optional)

r3plican_

### Describe the bug

![image](https://github.com/warpdotdev/Warp/assets/113588203/b2827875-d4ae-4c48-b2b9-f97a514ae4da)
after i close warp, i see in htop kitty terminal and see if warp not closed

### To reproduce

1. Open Warp in arch
2. close warp
3. open kitty and open htop

### Expected behavior

close the warp

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/113588203/adebc438-7895-45e9-9820-0dee44a20866)

### Operating system

MacOS

### Operating system and version

Arch hyprland 

### Current Warp version

newest

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
@t101804 Apologies if I'm missing it, but could you point me to where in the output of htop you're seeing Warp? I see an entry within firefox, but I can't seem to find an entry for the actual Warp process here. Thanks!

**Comment by alokedesai** [comment]
@t101804 We believe we have fixed this issue with the latest release of Warp, so I'm going to close this out. Please reopen if you are still experiencing this issue!
