### ISSUE TITLE
Linux: Behavior of Session Restoration

### ISSUE THREAD

**Issue by benbrenson** [warpdotdev/Warp#4343]
### Describe the bug

I'm currently not quite sure about the behavior of the session restoration feature. As quoted in the documentation this feature should restore panes, tabs and especially also `windows`.  

But only the sessions of the last closed window are restored. 

It's possible that I'm missing something important here, since I'm very new to warp (warp-terminal cli args, additional required configuration files). 
Maybe the feature would work if I close all current windows at once, rather that one by one, but I didn't find any command/shortcut that does that.
 

### To reproduce

Open multiple windows. Create some tabs and panes and fill each pane which some dummy commands.
Close each window one by one.
Open warp terminal again (either via GUI or via terminal).

### Expected behavior

Close all windows. After starting warp-terminal all previous closed windows should be opened again. All tabs and panes are restored in each window.  

### Operating system

Linux

### Operating system and version

Ubuntu 20.04.6

### Shell Version

bash 5.0.17

### Current Warp version

v0.2024.02.20.08.01.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by benbrenson** [comment]
@abhishekp106 : Was closing the issue intented? I think the behavior on Linux is not like quoted in the documentation?

**Comment by abhishekp106** [comment]
@benbrenson: Sorry about that, this was not meant to be closed yet! I merged in a fix for this internally, but the fix is not in the current release. This should be available in next Thursday's release (3/7).

You're right that there was no way to quit/terminate the app before, but there will be an action called "Quit Warp" in the command palette. Using this, session restoration should work as expected. I also want to note that we don't yet have a fix for quitting the app via a window manager.

**Comment by benbrenson** [comment]
Thank you very much for responding!
I will have a look on the next release.

cheers

**Comment by benbrenson** [comment]
Ok it seems to work now as expected.
This issue can be closed.

cheers
