### ISSUE TITLE
Display images in terminal

### ISSUE THREAD

**Issue by jimcornmell** [warpdotdev/Warp#4346]
### Describe the solution you'd like?

Images are displayed

### Is your feature request related to a problem? Please describe.

So useful to combine filters/searches and display images.

### Additional context

Here are a couple of examples displaying images in another terminal, kitty:
![images](https://github.com/warpdotdev/Warp/assets/7923416/15561c7b-27bf-4837-b966-0363fe5cd9fc)

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for submitting this @

We already have a request tracking this over at #26 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
