### ISSUE TITLE
Does not render window in VNC session

### ISSUE THREAD

**Issue by brian-doherty** [warpdotdev/Warp#4349]
### Describe the bug

When I run warp-terminal in a terminal on my VNC session, no window renders.

### To reproduce

See above.

### Expected behavior

For a window to appear.

### Operating system

Linux

### Operating system and version

Ubuntu 22.04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
@brian-doherty Sorry for the issues and thank you for filing. 

Shot in the dark, but if you install fonts-hack (`sudo apt install  fonts-hack`) is the issue fixed?

**Comment by brian-doherty** [comment]
I already have fonts-hack installed.

**Comment by brian-doherty** [comment]
I am seeing these errors though:

10:23:23 [INFO] Spawning terminal server process...
10:23:23 [INFO] Running terminal server...
10:23:24 [WARN] Failed to load font Some("/usr/share/fonts/X11/Type1/Symbol.pfb"): InvalidFontFormat("Type 1")
10:23:24 [WARN] Failed to load font Some("/usr/share/fonts/X11/Type1/b018012l.pfb"): InvalidFontFormat("Type 1")
10:23:24 [WARN] Failed to load font Some("/usr/share/fonts/X11/Type1/d050000l.pfb"): InvalidFontFormat("Type 1")
10:23:24 [WARN] Failed to load font Some("/usr/share/fonts/X11/Type1/n019003l.pfb"): InvalidFontFormat("Type 1")
10:23:24 [WARN] Failed to load font Some("/usr/share/fonts/type1/texlive-fonts-recommended/pcrr8a.pfb"): InvalidFontFormat("Type 1")

**Comment by brian-doherty** [comment]
![image](https://github.com/warpdotdev/Warp/assets/76168809/2295aa6c-ec05-4ef0-9ed2-1dcff1a4438e)
Eventually I do get a black window as shown here, but that's where it hangs.

**Comment by alokedesai** [comment]
Merging this into the canonical issue here:  https://github.com/warpdotdev/Warp/issues/4435
