### ISSUE TITLE
Window flickers when resizing on Linux

### ISSUE THREAD

**Issue by OlaoluwaM** [warpdotdev/Warp#4353]
### Describe the bug

When resizing the terminal window, it flickers

### To reproduce

1. Open the window on Linux
2. Try to resize it

### Expected behavior

It shouldn't flicker

### Screenshots

[Screencast from 2024-02-26 13-17-53.webm](https://github.com/warpdotdev/Warp/assets/37044906/9756364c-e605-4ded-804a-30df8ff43b07)

### Operating system

Linux

### Operating system and version

Fedora 39 (Gnome 45.4)

### Shell Version

zsh 5.9 (x86_64-redhat-linux-gnu)

### Current Warp version

v0.2024.02.20.08.01.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey folks! Thanks for your patience while trying Warp. Could you download this preview version of Warp and see if it fixes your issues:

[deb](https://releases.warp.dev/stable/v0.2024.02.27.08.01.stable_00/warp-terminal_0.2024.02.27.08.01.stable.00_amd64.deb)
[rpm](https://releases.warp.dev/stable/v0.2024.02.27.08.01.stable_00/warp-terminal-v0.2024.02.27.08.01.stable_00-1.x86_64.rpm)
[pacman](https://releases.warp.dev/stable/warp-terminal-v0.2024.02.27.08.01.stable_00-1-x86_64.pkg.tar.zst)
[appimage](https://releases.warp.dev/stable/v0.2024.02.27.08.01.stable_00/Warp-x86_64.AppImage)

If using Wayland, you can enable Wayland support by setting the `WARP_ENABLE_WAYLAND` envar (e.g`WARP_ENABLE_WAYLAND=1 warp-terminal`).

**Comment by erroreyes** [comment]
First, I don't experience the extreme flickering that has been reported in here and other reports, but I do see that resizing Warp in my machine is a bit jerky.

I tried the preview dep above and I still see the jerky resizing behavior.

OS: Kubuntu 23.10 x86_64
Kernel: 6.7.6-1-liquorix-amd64
Shell: fish 3.6.1
Resolution: 1600x900
DE: Plasma 5.27.8
WM: KWin
Terminal: WarpTerminal
CPU: Intel i5-7300U (4) @ 2.600GHz
GPU: Intel HD Graphics 620
Memory: 15748MiB

**Comment by OlaoluwaM** [comment]
Hi @dannyneira! Unfortunately, no, the preview doesn't fix the issue, regardless of whether I have `WARP_ENABLE_WAYLAND` set to `1`

**Comment by OlaoluwaM** [comment]
Also, it looks like preview builds aren't considered when checking for updates. The preview build you linked is newer than the latest stable build, but I keep getting the "Update Warp" notice

![image](https://github.com/warpdotdev/Warp/assets/37044906/ada2e3e4-90c7-451c-b52e-f6ea3b7d51b0)
