### ISSUE TITLE
all commands treated as one block after sudo -i

### ISSUE THREAD

**Issue by davidcvan** [warpdotdev/Warp#4369]
### Describe the bug

After I switch to root using either `sudo -i` or `sudo su root`, all commands I input are treated as one block

### To reproduce

1. switch to root using `sudo -i` or `sudo su root`

### Expected behavior

To treat every command as its own block.

### Operating system

Linux

### Operating system and version

Ubuntu 23.10

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.02.20.08.01.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by LFd3v** [comment]
Hi, there. I would say this is the expected behavior, please see [subshells](https://docs.warp.dev/features/subshells) in the documentation.

Here I was able to Warpfy `sudo -i` after adding it in Watp settings > Subshells.

**Comment by dannyneira** [comment]
This ^, `sudo -i` is a subshell so should be "Warpifed" before Blocks can work.

**Comment by davidcvan** [comment]
Thanks for the explanation, I will close the issue now.
