### ISSUE TITLE
Fish iterm2 shell integration should be disabled 

### ISSUE THREAD

**Issue by eoliphan** [warpdotdev/Warp#4372]
### Describe the solution you'd like?

Hi, this just requires a documentation update i believe.  When the fish/iterm2 shell integration is enabled, blocks don't appear after you run a command.  Similar to the workaround here: https://docs.warp.dev/~/changes/0rEvgEbBI4plIJzKgVuX/help/known-issues#bash-and-fig, it's just a matter of doing something like the following in your **config.fish**:

```fish
if test $TERM_PROGRAM -eq "iTerm.app"
	test -e {$HOME}/.iterm2_shell_integration.fish ; and source {$HOME}/.iterm2_shell_integration.fish
end
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for the heads up @eoliphan  and for your patience on the fix. We've added this info and workaround in our [known issues debugging section of our docs](https://docs.warp.dev/help/known-issues#debugging). 

Closing as resolved, but please let us know any issues.
