### ISSUE TITLE
Ranger not working

### ISSUE THREAD

**Issue by DaanKorver** [warpdotdev/Warp#4375]
### Discord username (optional)

.daantjuh

### Describe the bug

I am currently using warp for linux. When I try to use ranger, I cant see text, fonts or icons. Everything is just blank.

![image](https://github.com/warpdotdev/Warp/assets/30351629/8d178d8e-1b5e-437d-991d-b4ce7e2d837f)

### To reproduce

1. Open warp
2. ```ranger```

### Expected behavior

I want warp to show me the same as alacritty and other terminal emulators do

![image](https://github.com/warpdotdev/Warp/assets/30351629/ebdc7249-833e-4ba2-84ab-d3989083b2aa)

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/30351629/ebdc7249-833e-4ba2-84ab-d3989083b2aa)

### Operating system

Linux

### Operating system and version

Arch

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.02.20.08.01.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by LFd3v** [comment]
Hi, there. Can you please provide more info to help troubleshooting this issue?

1. Desktop Environment
2. X11 or Wayland
3. Share the output of starting `warp-terminal` from another terminal emulator.

JFYI, Here I can use `ranger` fine (Gnome/Wayland/using iGPU).

**Comment by DaanKorver** [comment]
Hi! ofcourse!

1. I am using Gnome
2. Wayland
3. I've found something interesting in the output

```zsh
[WARN] Unable to get glyph out of glyph cache for glyph Glyph { glyph_key: GlyphKey { glyph_id: 2574, font_id: FontId(23), font_size: OrderedFloat(21.0) }, position: Vector2F(<51, 112>), fade: None, color: #334567 }
```

**Comment by DaanKorver** [comment]
I found the issue! I have a icon plugin for ranger but that didn't seem to work with the "Hack" font so I set a NerdFont as default font and now it seems to work!
