### ISSUE TITLE
CTRL + D shortcut con linux not working

### ISSUE THREAD

**Issue by FidelGB** [warpdotdev/Warp#4378]
### Describe the bug

I have configured `CTRL + D` shortcut for Split Pane Right, but when I run the shortcut, warp close the pane

### To reproduce

1. Go to Settings
2. Go to Keyboard Shortcuts
3. Set Split Pane Right to Ctrl + D
4. Try to split Pane using Ctrl + D

### Expected behavior

I expected that the pane split correctly

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/54261598/0b36daa3-f6b4-4189-9900-89f2f210a94f)

### Operating system

Linux

### Operating system and version

Zorin OS 17

### Shell Version

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2024.02.20.08.01.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

Never

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by erroreyes** [comment]
In addition, that function is mapped to [Shift+Ctrl+D by default](https://docs.warp.dev/features/windows/split-panes), which works fine, and arguably it's a good enough shortcut.

**Comment by dannyneira** [comment]
Closing as this can be bound to other shortcuts that don't conflict with the close session shortcut, You can also close session with CTRL-SHIFT-W as a workaround. Hope this helps!
