### ISSUE TITLE
Linux: Opening new terminal window raises all other warp windows

### ISSUE THREAD

**Issue by Daedaluz** [warpdotdev/Warp#4389]
### Describe the bug

When I open a new terminal window, all other instances of warp puts themselves on top of other windows.

### To reproduce

1) start a warp terminal
2) put something above it, eg a browser
3) start a new warp terminal

### Expected behavior

I expected the other, burried, terminals to stay put.

### Operating system

Linux

### Operating system and version

Pop_OS!

### Current Warp version

v0.2024.02.20.08.01.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

Currently using X11

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
Hey @Daedaluz, thanks for filling. Would you mind sharing a video of the behavior? Also, could you check if you have the "Global Hotkey" feature enabled within settings? Thank you!

**Comment by Daedaluz** [comment]
[warp-2024-02-29_09.30.58.webm](https://github.com/warpdotdev/Warp/assets/310150/5dd23d9c-9c6f-4100-baa1-243ea6d40912)

Global hotkeys feature is disabled.

**Comment by acarl005** [comment]
@Daedaluz Can you also tell us how you opened the new Warp window? Was it Warp's hotkey, or maybe something you configured through your window manager, etc?

**Comment by Daedaluz** [comment]
`gsettings set org.gnome.desktop.default-applications.terminal exec warp-terminal`

and i have bound "terminal" to mod+shift+enter

**Comment by Daedaluz** [comment]
Fyi, same thing happens if i type "warp-terminal" in another terminal to start a new one too.
The issue seems unrelated to how I start the terminal.

**Comment by acarl005** [comment]
Thanks for the info. Looking into it.

**Comment by Daedaluz** [comment]
This appears to have been solved in v0.2024.03.19.08.01.stable_01
