### ISSUE TITLE
Unsharing code block behaviour not guaranteed to unshare

### ISSUE THREAD

**Issue by koalazub** [warpdotdev/warp#439]
### Describe the bug

```shell
This could be something to do with state - but when I unshare a link, it will repopulate right after I invoke the action.
```

### To Reproduce

So:
 - launch Warp
 - view Shared Blocks
 - Unshare code block
 - Code block might/might not repopulate itself in the list

### Expected behaviour

```shell
Remove the shared block from the list
```

### Screenshots

I won't be able to share screenshots as the code is work related

### Operating System

MacOS

### OS Version

Monterey 12.0.1 (21A559)

**Comment by elviskahoro** [comment]
Fixed with:
**Stable release 2021-12-08 (v0.2021.12.06.19.09.stable_00)**
