### ISSUE TITLE
Support hiding the UI in the top bar

### ISSUE THREAD

**Issue by BenoitAverty** [warpdotdev/Warp#4391]
### Describe the solution you'd like?

I would like to be able to hide the top bar completely (tabs and close/minimize buttons)

### Is your feature request related to a problem? Please describe.

Hello,

I'm using a tiling window manager (i3) that has a few features that make some warp features irrelevant to me.

Namely, the tabs and split panes are not useful to me because it's easier and more powerful to just launch another warp window and let i3 organize it however I like

Also, I never need to minimize the terminal because i3 doesn't support it, and I use ctrl+d to close the terminal. So these buttons are also useless to me.

The top bar is just taking some screen real estate.

Thanks in advance

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by LFd3v** [comment]
Hi, there. I looks like a duplicate of one of these issue, you may want to close this one and upvote (add a thumbs up) to one that better fits your needs:

#1009 
#4158
#4207

**Comment by BenoitAverty** [comment]
Duplicate of #1009 and #4207
