### ISSUE TITLE
What is the action associated with Ctrl+Shift+W - Linux 

### ISSUE THREAD

**Issue by Ghasak** [warpdotdev/Warp#4394]
### Describe the solution you'd like?

I want to map Super+W in linux(Ubuntu) to close the session which also will close the tab similar to iTerm or WezTerm 
which action is triggered by pressing `Ctrl+Shift+W` so I can remap it
I have tired (as a guess,as it is not written in the manual) but it doesnt work!!
"workspace:close_current_session": cmd-w  

![image](https://github.com/warpdotdev/Warp/assets/27670946/f69f11e6-984b-4e45-bfaa-dc7b70800221)

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by LFd3v** [comment]
Hi, there. Are you using Warp on Linux running on a Mac, is this correct? If yes, what distro and DE? Is it possible that "Supper + w" is already assigned in the DE? Thank you.

**Comment by Ghasak** [comment]
Thank you for your reply, 
No, I am running warp on Ubuntu Linux and no Mac 
I just want to mimic the key binding of closing pane using super +w

**Comment by LFd3v** [comment]
Ah, I think now I know what you meant initially: you want to change the keybinding to close the session but it is not available in the settings, right? Indeed, this it true. But there is "Close the Current Tab", that will do exactly what you asked initially (you meantioned _tab_, not session).

**Comment by Ghasak** [comment]
Thank you very much, Yes you are right! 
to be clear I meant a single keybinding (super + w) to close pane and tabs 
similar to this one
https://wezfurlong.org/wezterm/config/lua/keyassignment/CloseCurrentPane.html?h=close+p
I set them like this in wezterm
```lua
{ key = "w", mods = "CMD", action = wezterm.action.CloseCurrentTab({ confirm = false }) },
{ key = "w", mods = "CMD", action = wezterm.action.CloseCurrentPane({ confirm = false }) },
```

**Comment by Ghasak** [comment]
The API for closing tab in Warp is 
```
"workspace:close_active_tab": cmd-w
```
So I wish to know what is the API for closing `pane` which is triggered by default when you press `Ctrl + Shift + W`?
That is my question, thank you very much for your support!

**Comment by alokedesai** [comment]
Hey @Ghasak, the shortcut for "Close Current Session" is not able to be configured right now. This is entirely a bug in Warp, we'll aim to have this fixed soon. Sorry for the troubles!

**Comment by Ghasak** [comment]
Thank you very much for your feedback, 
Looking forward for this fix. Please do notify me here, as I will switch back to wezterm for now. 
I appreciate all the great work by you and your team are doing. In the meanwhile , continue with the great work and best luck.

**Comment by alokedesai** [comment]
Hi @Ghasak this should now be fixed. I'm going to go ahead and close, please let me know if you're still experiencing issues.
