### ISSUE TITLE
Emojis not working in WSL2

### ISSUE THREAD

**Issue by drolander** [warpdotdev/Warp#4399]
### Describe the bug

Fresh install of Warp on an existing Debian Bookworm distro running in WSL2. For the most part, Warp features seem to be working fine, but not emojis. They do not display at all in the Warp bash terminal, despite displaying just fine in the WSL2 bash terminal, VS Code bash terminal, and Git for Windows bash terminal. In Warp, all I see is whitespace.

### To reproduce

As a simple test, just paste this echo command:

echo ♻️

Windows WSL2 Bash Terminal:
![image](https://github.com/warpdotdev/Warp/assets/14521/357ca06a-f0fd-492a-9789-8ddc2297ad4b)

VS Code Bash Terminal:
![image](https://github.com/warpdotdev/Warp/assets/14521/cb0fb285-053b-4b55-993b-59b6cfa0ca99)

Warp BASH Terminal:
![image](https://github.com/warpdotdev/Warp/assets/14521/fe5c8229-089e-4b18-a77b-62734f832cd6)

### Expected behavior

I expect to see emojis rendered correctly. This first came to my attention because I was running a mocha test suite in Warp and noticed I was not seeing checkmarks for successful tests. I spent a lot of time looking for ways to resolve this but have not yet found any solutions.

### Screenshots

see "To reproduce" section

### Operating system

Linux

### Operating system and version

Debian 12 (Bookworm)

### Shell Version

GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.02.20.08.01.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

Never, but only installed it a couple days ago

### Additional context

I assume it is X11. I am not using any Wayland command line args when launching warp-terminal, and I initially had a bunch of X11 errors that were resolved by installing needed X11 libraries. glxinfo is not installed in my WSL2 distro.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
@drolander What is the default font you're using in Warp? What's the output of `fc-match --sort "{{NAME OF FONT}}"`?

**Comment by drolander** [comment]
@alokedesai I am back to using the Hack (default) font, but also tried the included Liberation Mono, and I installed the Hack Nerd Font and tried that. None of them work for emojis.

![image](https://github.com/warpdotdev/Warp/assets/14521/bd9703a7-f9fe-4a8f-ace2-0fc3bf5f760b)

fc-match does not list the default Hack, just Hack Nerd. Here is the full sorted list:

fc-match --sort --all
HackNerdFont-Regular.ttf: "Hack Nerd Font" "Regular"
HackNerdFontMono-Regular.ttf: "Hack Nerd Font Mono" "Regular"
HackNerdFontPropo-Regular.ttf: "Hack Nerd Font Propo" "Regular"
LiberationMono-Regular.ttf: "Liberation Mono" "Regular"
LiberationSans-Regular.ttf: "Liberation Sans" "Regular"
LiberationSerif-Regular.ttf: "Liberation Serif" "Regular"
LiberationSansNarrow-Regular.ttf: "Liberation Sans Narrow" "Regular"
HackNerdFont-Bold.ttf: "Hack Nerd Font" "Bold"
HackNerdFontMono-Bold.ttf: "Hack Nerd Font Mono" "Bold"
HackNerdFontPropo-Bold.ttf: "Hack Nerd Font Propo" "Bold"
LiberationMono-Bold.ttf: "Liberation Mono" "Bold"
LiberationSans-Bold.ttf: "Liberation Sans" "Bold"
LiberationSerif-Bold.ttf: "Liberation Serif" "Bold"
LiberationSansNarrow-Bold.ttf: "Liberation Sans Narrow" "Bold"
HackNerdFont-Italic.ttf: "Hack Nerd Font" "Italic"
HackNerdFontMono-Italic.ttf: "Hack Nerd Font Mono" "Italic"
HackNerdFontPropo-Italic.ttf: "Hack Nerd Font Propo" "Italic"
LiberationMono-Italic.ttf: "Liberation Mono" "Italic"
LiberationSans-Italic.ttf: "Liberation Sans" "Italic"
LiberationSerif-Italic.ttf: "Liberation Serif" "Italic"
LiberationSansNarrow-Italic.ttf: "Liberation Sans Narrow" "Italic"
HackNerdFont-BoldItalic.ttf: "Hack Nerd Font" "Bold Italic"
HackNerdFontMono-BoldItalic.ttf: "Hack Nerd Font Mono" "Bold Italic"
HackNerdFontPropo-BoldItalic.ttf: "Hack Nerd Font Propo" "Bold Italic"
LiberationMono-BoldItalic.ttf: "Liberation Mono" "Bold Italic"
LiberationSans-BoldItalic.ttf: "Liberation Sans" "Bold Italic"
LiberationSerif-BoldItalic.ttf: "Liberation Serif" "Bold Italic"
LiberationSansNarrow-BoldItalic.ttf: "Liberation Sans Narrow" "Bold Italic"

And here is the output of `fc-match -v Hack`. Interestingly, I see `color: False(w)` and `symbol: False(s)`. I'm not sure if that is significant.

fc-match -v Hack
Pattern has 38 elts (size 48)
	family: "Hack Nerd Font"(s)
	familylang: "en"(s)
	style: "Regular"(s)
	stylelang: "en"(s)
	fullname: "Hack Nerd Font Regular"(s)
	fullnamelang: "en"(s)
	slant: 0(i)(s)
	weight: 80(f)(s)
	width: 100(f)(s)
	size: 12(f)(s)
	pixelsize: 12.5(f)(s)
	spacing: 100(i)(w)
	foundry: "SRC"(w)
	hintstyle: 1(i)(w)
	hinting: True(s)
	verticallayout: False(s)
	autohint: False(s)
	globaladvance: True(s)
	file: "/home/drolander/.local/share/fonts/HackNerdFont-Regular.ttf"(w)
	index: 0(i)(w)
	outline: True(w)
	scalable: True(w)
	dpi: 75(f)(s)
	scale: 1(f)(s)
	charset:
	0000: 00000000 ffffffff ffffffff 7fffffff 00000000 ffffffff ffffffff ffffffff
	0001: ffffffff ffffffff ffffffff ffffffff 00040000 00018013 00000000 c00000c0
	0002: 0f000000 00000000 00000000 00000000 00000000 00000000 3f0000c0 00000000
	0003: 0000020b 00000008 00000000 00000000 ffffd770 fffffffb 00007fff 00500000
	0004: ffffffff ffffffff ffffffff 000c000c 0fff0000 0c0ffc3c ffff999f 03ffffff
	0005: 3c030000 fffe0000 fe7fffff fffffffe 000006ff 00000000 00000000 00000000
	000e: 00000000 80000000 00000000 00000000 00000000 00000000 00000000 00000000
	0010: 00000000 00000000 00000000 00000000 00000000 00000000 ffff0000 1fffffff
	001e: 00000000 00000000 00000000 00000000 0000003f 30000000 00000000 030c0000
	0020: ffff07ff f6ff80ff 80000bf0 7ff10000 00007c00 03bfffff 00000000 00000000
	0021: 00400000 00000044 fffb0000 00000000 ffff0000 ffffffff 3fffffff fffffbff
	0022: ffafffff 3ff03f89 fffffffe ffffe3ff ffffefff 013c001f fc03e07c 000083ff
	0023: 00010f10 00000003 00000000 00000000 f8000000 00007fff 00000000 78000000
	0025: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0026: 00000000 00010000 00000000 00000420 00000000 00000002 00000000 00000000
	0027: 00000000 00000000 00400000 003fff00 ff100000 7ffeffff 10000064 00e00fc1
	0029: 00000000 00000000 00000000 00000000 01800180 00000000 00000000 0c000800
	002a: 00000001 00008000 00000000 00000c00 00000000 00000000 00000000 00000000
	002b: 07c03fe0 00000000 01000000 00000000 00000000 00000000 00000000 00000000
	002e: 81000000 0000403c 00000000 00000000 00000000 00000000 00000000 00000000
	00e0: 000007ff 00000000 00000000 00000000 00000000 ffff000f 0017f5ff 00000000
	00e2: ffffffff ffffffff ffffffff ffffffff ffffffff 000003ff 00000000 00000000
	00e3: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff 0000000f
	00e5: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 fc000000
	00e6: ffffffff ffffffff ffffffff ffffffff ffffffff 0007ffff 00000000 00000000
	00e7: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff 0000003f 00000000
	00ea: 00000000 00000000 00000000 ffffffff ffff9dff ffffffff fffff2ff ffffffff
	00eb: fffffbff ffffffff ffff7fff ffffffff ffffffff ffffffff ffffffff 00000fff
	00f0: 7fff7fff 7ffffffe 7fff7fff 7fff7fff 7fff7fff 00077fff 7fff7fff 7fff7fff
	00f1: 7fff7fff 7fff7fff 7fff7fff 7fff7fff 7fff7fff 7fff7fff 7fff7fff 7fff7fff
	00f2: 7fff7fff 7ffffffe 7fff7fff 7fff7fff 7fff7fff 7fff7fff 7fff7fff 00000001
	00f3: ffffffff ffffffff ffffffff 0007ffff 00000000 00000000 00000000 00000000
	00f4: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	00f5: ffffffff 000fffff 00000000 00000000 00000000 00000000 00000000 00000000
	00fe: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 80000000
	0f00: fffffffe ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f01: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f02: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f03: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f04: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f05: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f06: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f07: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f08: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f09: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f0a: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f0b: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f0c: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f0d: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f0e: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f0f: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f10: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f11: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f12: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f13: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f14: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f15: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f16: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f17: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f18: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f19: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff
	0f1a: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff 0001ffff
(w)
	lang: aa|af|av|ay|be|bg|bi|br|bs|bua|ca|ce|ch|chm|co|cs|cv|cy|da|de|el|en|eo|es|et|eu|fi|fj|fo|fr|fur|fy|gd|gl|gn|gv|ho|hr|hu|hy|ia|id|ie|ik|io|is|it|ka|kaa|ki|kk|kl|ku-am|kum|kv|ky|la|lb|lez|lt|lv|mg|mh|mk|mo|mt|nb|nds|nl|nn|no|nr|nso|ny|oc|om|os|pl|pt|rm|ro|ru|sah|se|sel|sk|sl|sma|smj|smn|so|sq|sr|ss|st|sv|sw|tk|tl|tn|tr|ts|tt|tyv|uk|uz|vo|vot|wa|wen|wo|xh|yap|zu|an|crh|csb|fil|hsb|ht|jv|kj|ku-tr|kwm|lg|li|mn-mn|ms|na|ng|pap-an|pap-aw|rn|rw|sc|sg|sn|su|za(s)
	fontversion: 196804(i)(s)
	capability: "otlayout:DFLT otlayout:latn"(w)
	fontformat: "TrueType"(w)
	embeddedbitmap: True(s)
	decorative: False(s)
	lcdfilter: 1(i)(w)
	namelang: "en"(s)
	prgname: "fc-match"(s)
	postscriptname: "HackNF-Regular"(w)
	color: False(w)
	symbol: False(s)
	variable: False(s)

**Comment by alokedesai** [comment]
Hmm it's interesting because none of the fonts listed by fontconfig are ones that would support emojis. Do emojis render in any applications within wsl for you?

**Comment by alokedesai** [comment]
If not, I would expect installing `fonts-noto-color-emoji` (a font that includes emoji glyphs) to fix the issue.

**Comment by drolander** [comment]
Thank you, it is working now. At first, I installed the Cascadia Mono font, because that is the font used in Windows Terminal and VS Code and I know it has support for emojis, but that alone did not fix it. Running `sudo apt install fonts-noto-color-emoji` did the trick. Now I see checkmarks for my tests and other emojis and glyphs.
