### ISSUE TITLE
Warp Terminal not working in xrdp remote session

### ISSUE THREAD

**Issue by EFCHolla** [warpdotdev/Warp#4403]
### Describe the bug

Warp terminal works fine locally, but when I remote to the system via xrdp, warp couldn't work properly, it's UI just froze up a rectangular display area no UI content was drown, the stderr output was "libEGL warning: DRI2: failed to authenticate".
Can someone help me solve this issue? It'd be much a shame if I could use this amazing tool remotely. Your help would be much appreciated, thanks!

### To reproduce

1. Install warp locally, it works fine.
2. Connect remotely via xrdp, warp wouldn't start correctly in this scenario.

### Operating system

Linux

### Operating system and version

Ubuntu 22.04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
Merging this into a canonical issue: https://github.com/warpdotdev/Warp/issues/4435

**Comment by dannyneira** [comment]
Duplicate of #4435
