### ISSUE TITLE
No display on kali linux

### ISSUE THREAD

**Issue by S444-gold** [warpdotdev/Warp#4405]
### Describe the bug

After installing the warp application, whenever i run the warp terminal command, it just shows an empty screen with nothing at all

### To reproduce

Install warp on kali, and then run it

### Expected behavior

Expected to see a warp displayed screen

### Operating system

Linux

### Operating system and version

Kali 2023.4

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.02.20.08.01.stable.01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

Just installing it for the first time

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by igorsol** [comment]
I think this issue is not specific to Kali. I have the same issue in Ubuntu 20.04 running as VirtualBox guest.

**Comment by S444-gold** [comment]
> I think this issue is not specific to Kali. I have the same issue in Ubuntu 20.04 running as VirtualBox guest.
> 
> See also #4417 

Yep, also running as a virtual box guest

**Comment by igorsol** [comment]
For me the following command helped to workaround the issue:
```
WGPU_BACKEND=gl warp-terminal
```

**Comment by S444-gold** [comment]
> For me the following command helped to workaround the issue:
> 
> ```
> 
> WGPU_BACKEND=gl warp-terminal
> 
> ```

Not working for me unfortunately

**Comment by PremiereStoss** [comment]
> For me the following command helped to workaround the issue:
> 
> ```
> WGPU_BACKEND=gl warp-terminal
> ```

What does that command do specifically?

thanks!

**Comment by 0xsnowcloud** [comment]
> For me the following command helped to workaround the issue:
> 
> ```
> WGPU_BACKEND=gl warp-terminal
> ```

This also fixed the issue I had running Warp in a Kali VM via VirtualBox. Thanks!

**Comment by igorsol** [comment]
> What does that command do specifically?
> 
One of the warp's developers suggested to try this command in another similar issue's thread.
I can only guess that this command forces 'gl' backend by setting 'WGPU_BACKEND' environment variable. (overriding backend selected by warp's internal logic)

**Comment by alokedesai** [comment]
Hi all, we believe the latest release that came out today has fixed the issues with Kali linux. Could you try updating to the latest version to confirm? Thank you!

**Comment by igorsol** [comment]
> Could you try updating to the latest version to confirm?

Thanks! This update also solved the issue for Ubuntu runnig as VirtualBox guest.

**Comment by 0xsnowcloud** [comment]
Confirmed this is also working on Kali Linux in a virtual box VM.

**Comment by alokedesai** [comment]
Great! Going to go ahead and close this issue.
