### ISSUE TITLE
Wrong warp window position on i3wm with multi-monitor setting

### ISSUE THREAD

**Issue by tuanbass** [warpdotdev/Warp#4406]
### Describe the bug

when spawn a new warp window, it occurs in wrong monitor.

### To reproduce

- using a multi-monitor setup (in my case, using 3 monitor) 
- open a warp window, and move it to monitor 2 
- focus into monitor 1, and open a another warp windows
- The new warp window occurs in monitor 2 

### Expected behavior

new warp window should occur in monitor 1 

### Operating system

Linux

### Operating system and version

Ubuntu 22.04.3 LTS

### Shell Version

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2024.02.20.08.01.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

i3-wm on X11

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by lucieleblanc** [comment]
Hi @tuanbass, thank you for reporting this! I'm trying to reproduce this bug locally (also on Ubuntu/i3/X11) but don't see the same behavior. A few questions:
1. Could I ask how you open each Warp window? Are you using an i3 keybinding, searching with dmenu, or the "new window" keybinding within Warp?
2. Does this bug happen regardless of which monitor you start from? Or does it depend on which monitor is designated as the primary monitor?
3. Any additional info about how you're configuring/managing multiple monitors would also be helpful.

**Comment by tuanbass** [comment]
> Hi @tuanbass, thank you for reporting this! I'm trying to reproduce this bug locally (also on Ubuntu/i3/X11) but don't see the same behavior. A few questions:
> 
> 1. Could I ask how you open each Warp window? Are you using an i3 keybinding, searching with dmenu, or the "new window" keybinding within Warp?
> 2. Does this bug happen regardless of which monitor you start from? Or does it depend on which monitor is designated as the primary monitor?
> 3. Any additional info about how you're configuring/managing multiple monitors would also be helpful.

Hi, 

1. I have the issue either start warp from another terminal (gnome-term) or from a launcher (I'm using ilya from regolith) 
2. I try to swap the position of first warp window, and the terminal that I use to start second `warp-terminal` instance. Whatever I arrange, the second warp always appear next to the first one. 
3. Not sure what you inquiry. Here is my monitor setup. 

![image](https://github.com/warpdotdev/Warp/assets/9334023/16cc9d68-cf9b-481d-bdd9-9c31cdf9b42e)

**Comment by tuanbass** [comment]
Btw, the issue is not occurs in `sway`

**Comment by lucieleblanc** [comment]
Thank you for the info! Just to confirm, does this issue still occur with the latest version of Warp (`v0.2024.03.19.08.01.stable_01`)?

**Comment by tuanbass** [comment]
> Thank you for the info! Just to confirm, does this issue still occur with the latest version of Warp (`v0.2024.03.19.08.01.stable_01`)?

Wow. Seem the issue was fixed in latest version. 
Thanks for your works and supports. 

Tuan.
