### ISSUE TITLE
Local workflows folder crashes restore windows, tabs and panes

### ISSUE THREAD

**Issue by fscaptain** [warpdotdev/Warp#4409]
### Describe the bug

If the local workflows folder under ~/.local/share/warp-terminal/ exists the feature of restoring windows, tabs and panes stopped working. After deleting the folder, everything works as aspected

### To reproduce

1. split into 2 panes
2. close warp
3. make ~/.local/share/warp-terminal/workflows folder
4. start warp -> no panes, any default window 
5. close warp -> delete ~/.local/share/warp-terminal/workflows folder
6. open warp, make 2 panes, close and open it again -> 2 panes were present

### Operating system

Linux

### Operating system and version

Ubuntu 22.04

### Shell Version

GNU bash, Version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.02.20.08.01.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Sorry to hear about this, I'll route to the appropriate team and let them know about this issue. As a possible workaround you can disable the Session Restoration in settings, if you want to use the local workflows.

**Comment by dannyneira** [comment]
In trying to reproduce the issue, I'm not seeing the same on ubuntu 22.04, make sure Warp has right permissions to the `~/.local/state/warp-terminal` folder as that is where the session restoration sqlite db is stored, then try toggling the feature to see if that helps with creating the sqlite db for restoration of panes.

**Comment by fscaptain** [comment]
Works now as it should.
