### ISSUE TITLE
CB: NeoVim in fullscreen is really slow

### ISSUE THREAD

**Issue by iSchoen** [warpdotdev/warp#441]
### Describe the bug

```shell
The terminal gets really slow when running neovim in fullscreen.
```

### To Reproduce

Steps to reproduce:
1. Fullscreen the terminal
2. Open NeoVim
3. Commands take a long time to run and you even get a loading cursor off and on.

### Expected behaviour

```shell
The terminal being just as fast inside of NeoVim in fullscreen just like any other time you're using it.
```

### Operating System

MacOS

### OS Version

11.6

### Additional context

```shell
The terminal runs fine when I'm not in NeoVim and also when I'm running NeoVim but in a smaller window.
```

**Comment by iSchoen** [comment]
Seems like the problem completely goes away when I turn off my colorscheme.  I'll do some further testing when I get a moment.

**Comment by iSchoen** [comment]
One other thing to point out is that the issue and the colorscheme fix apply to neovim and vim.

**Comment by iSchoen** [comment]
Hmm... closed? Alright, well I use vim extensively. If Warp doesn't support something as simple as a vim colorscheme and maintainers simply close the issue then either you're understanding that simply turning off the colorscheme is a literal fix or Warp is looking really bad right now.

Unfortunately it's probably the latter. Best wishes to you guys, but Warp just isn't it.

**Comment by elviskahoro** [comment]
Hey @iSchoen, we're going to move our Vi/Vim/Neovim stuff to this discussion:
- https://github.com/warpdotdev/warp/discussions/451

We're closing the issue but not abandoning the problem. Check out this comment (same scenario as this one), it has the rationale for GitHub discussion:
- https://github.com/warpdotdev/warp/issues/144#issuecomment-974327051
