### ISSUE TITLE
DISCLAIMER: Not really a feature, but a request

### ISSUE THREAD

**Issue by afreidz** [warpdotdev/Warp#4410]
### Perhaps stop pushing so many updates.

I know that Warp is under super-active development, and the current trend in software is to ship, ship, ship.  But the primary users are developers who are notorious for using terminal for long running processes for their own active development. 

Its a bit frustrating that a little yellow pill shows up multiple times a week for me to "Update Warp" and thereby take down my pristinely curated terminal/development-environment.  I'd also prefer not to mess with TMUX or something that Warp connects to.

I appreciate many of the new features, but the core feature I am looking for is a stable terminal environment.  Maybe you could try having 2 channels? One that gets less frequent releases for those looking for "stability" ... and another where you can ship the latest and greatest at the fastest pace possible?

Just a thought!  Nonetheless, amazing work!

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
hey @afreidz Thanks for the comments and request. We don't have immediate plans for a "Stable" channel, but I see how that may be helpful to your workflow. 

As a possible stopgap or workaround to the issue of weekly updates, you can try [Session Restoration](https://docs.warp.dev/features/sessions/session-restoration) that restores the previous session block history windows/tabs/pane configuration, or [Launch Configurations](https://docs.warp.dev/features/sessions/launch-configurations) which allows you to save a layout of windows/tabs/panes cwds and even run commands on launch. Hope this helps for the time being!

**Comment by afreidz** [comment]
@dannyneira thanks! I'll take a look.  The biggest drawback I see initially is that it wont restore the actual running commands but rather the layout and history.  Which is a step better in the interim.  Thanks!
