### ISSUE TITLE
"the stupid content tracker" on `git` hover (lol)

### ISSUE THREAD

**Issue by petermueller** [warpdotdev/Warp#4416]
### Describe the bug

When hovering over the `git` command it says "the stupid content tracker" which I presume is not the intent

### To reproduce

type `git` into the terminal. Hover over it for a sec

### Expected behavior

A description of what `git` is I presume?

### Screenshots

![Screenshot 2024-02-29 at 10 11 34 PM](https://github.com/warpdotdev/Warp/assets/6015288/7f29b352-7cd6-41fa-9091-5d7912662935)

### Operating system

MacOS

### Operating system and version

14.3.1

### Current Warp version

v0.2024.02.27.08.01.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
Fun fact, this is the official (TM) description of `git` per its man page: https://manpages.debian.org/stretch/git-man/git.1.en.html
