### ISSUE TITLE
Linux: Paste & Clear Output action in right-click Menu 

### ISSUE THREAD

**Issue by Yummy-Yums** [warpdotdev/Warp#4418]
Can we add _paste_ action in the menu ( screenshot below ) ? Also, _Clear output_ , _Paste Command_ could be in there as well

![image](https://github.com/warpdotdev/Warp/assets/77977520/0f16506e-6d53-41e3-98f6-40f26000bd1c)

_Originally posted by @Yummy-Yums in https://github.com/warpdotdev/Warp/issues/4329#issuecomment-1971824741_

**Comment by SilentGlasses** [comment]
Latest update seems to have added paste. I have it on mine ...
![Screenshot from 2024-03-07 21-23-06](https://github.com/warpdotdev/Warp/assets/22822565/1ca74d7d-fee8-4c70-b6c3-568ff6b7104b)
