### ISSUE TITLE
Opening a New Warp Terminal Window Sets Other Windows to Urgent State in Sway WM

### ISSUE THREAD

**Issue by rmasad** [warpdotdev/Warp#4422]
### Describe the bug

When using Warp terminal in a Sway window manager environment, opening a new terminal window causes all other existing windows to switch to an "urgent" state. This behavior is unexpected and differs from the normal behavior where windows maintain their current state (focused, unfocused, urgent) unless specifically interacted with. This issue mirrors similar behaviors observed in i3wm.

### To reproduce

1. Open a Sway session and ensure multiple windows are open (e.g., browser, text editor).
2. Open a new Warp terminal window.
3. Observe that all other windows (not the newly opened Warp terminal) switch to an "urgent" state.

### Expected behavior

Opening a new Warp terminal window should not affect the state of other existing windows. Other windows should retain their current state (focused, unfocused) unless specifically interacted with by the user.

### Screenshots

Before opening a new Warp window:
![image](https://github.com/warpdotdev/Warp/assets/49078/014f158c-650d-42f9-8b94-f40f049a62d1)

After:
![image](https://github.com/warpdotdev/Warp/assets/49078/52cc965b-e178-4d47-bf4f-400fadb1b6c1)

### Operating system

Linux

### Operating system and version

Ubuntu 23.10

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment]
Hi @rmasad thanks for reporting. I'll be looking into this issue.

**Comment by acarl005** [comment]
Should be fixed in the latest version of Warp! Please let us know.

**Comment by rmasad** [comment]
Yes, it is fixed. Thanks!
