### ISSUE TITLE
The "Find" input needs to be wider

### ISSUE THREAD

**Issue by ghouston** [warpdotdev/Warp#4424]
### Discord username (optional)

*No response\`*

### Describe the bug

Open the `Find` or `Find within Block` and enter either a long string to search or a search that returns 10000+ results. The Find input box becomes so cluttered you cannot see or edit the search term anymore!

![Screenshot 2024-03-01 at 7 57 28 AM](https://uploads.linear.app/466b8b6d-ad6b-4027-8f8b-4298aeeff692/ffa37005-a9e6-470d-bde6-636083a695fc/5f49e4cb-6c69-458e-bdf7-83c571aa78c6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ2NmI4YjZkLWFkNmItNDAyNy04ZjhiLTQyOThhZWVmZjY5Mi9mZmEzNzAwNS1hOWU2LTQ3MGQtYmRlNi02MzYwODNhNjk1ZmMvNWY0OWU0Y2ItNmM2OS00NThlLWJkZjctODNjNTcxYWE3OGM2IiwiaWF0IjoxNzA5MzMxOTU2LCJleHAiOjMzMjc5ODkxOTU2fQ.jaAMFysfJ6rhist6KoTXzID9UXlmdQnlSvioVoXmFwk)

The Find input should expand or be resizable horizontally to avoid this issue. Currently the `Find` feature becomes unusable for many searches.

### To reproduce

see description.

### Expected behavior

The Find input box to be horizontally wider so that you can see and edit the search term.

### Screenshots

![Screenshot 2024-03-01 at 7 57 28 AM](https://uploads.linear.app/466b8b6d-ad6b-4027-8f8b-4298aeeff692/a8736b1f-b01c-4b98-bd5f-b37a5c261956/5c8c7f05-98bd-4e09-9836-c76ead4f889a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQ2NmI4YjZkLWFkNmItNDAyNy04ZjhiLTQyOThhZWVmZjY5Mi9hODczNmIxZi1iMDFjLTRiOTgtYmQ1Zi1iMzdhNWMyNjE5NTYvNWM4YzdmMDUtOThiZC00ZTA5LTk4MzYtYzc2ZWFkNGY4ODlhIiwiaWF0IjoxNzA5MzMxOTU2LCJleHAiOjMzMjc5ODkxOTU2fQ.J8cOAU4tSkwG0pjasg8iIzHqXDK_f9GMVA42zGXD-m0)

### Operating system

MacOS

### Operating system and version

13\.6.4

### Shell Version

*No response*

### Current Warp version

v0.2024.02.27.08.01.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

*No response*

### Additional context

*No response*

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for this feature request! As a possible stopgap consider using `find` command in the terminal or `grep` for being able to edit the search variables easier and filter your output.

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by AgentOfTech** [comment]
> Thanks for this feature request! As a possible stopgap consider using `find` command in the terminal or `grep` for being able to edit the search variables easier and filter your output.
> 
> To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

The problem with this workaround is that I mainly use it when to search logs while I'm running a syslog script that pulls logs for my container. While developing and testing, I often search the logs for specific event IDs that are different depending on what I'm looking for, given the code changes on a specific branch. 

I think it's odd that the search box size adjusts when the terminal font size changes. If Warp is on my larger external monitor, I can leave the default size and the search box is fine. However, I often keep the terminal open on my smaller laptop monitor with larger font size so it's easier to see, while my IDE is on my larger external monitor. Both sit at the same distance and so the default smaller font size isn't very readable. 

Anyway, sorry to drudge on here. I really like Warp! It's far superior to any other terminal app I've used, except in this one way. This one workflow issue has been annoying enough to keep me going back to iTerm. Even though I don't often use Apple's Terminal.app, it probably does it best with a search that appears at the top of the window and is the entire width of the window. And, it doesn't resize with the font size. 
I'm sure all of this sounds silly, but it's a pain point in a workflow I use dozens of times a day. Hope you guys can find a resolution to this issue, even if it's an alternative search option setting.

**Comment by abhishekp106** [comment]
Re-opening as this isn't completed yet. We're working on a wider find bar!
