### ISSUE TITLE
Dragging scroll bar results in segfault

### ISSUE THREAD

**Issue by mrmelon54** [warpdotdev/Warp#4428]
### Describe the bug

When dragging the scroll bar sometimes warp segfaults

### To reproduce

Run a command with a long output then drag the scroll bar up/down and it will segfault

### Expected behavior

No segfault

### Operating system

Linux

### Operating system and version

Linux Mint 21.3

### Shell Version

bash 5.1.16

### Current Warp version

v0.2024.02.27.08.01.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Additional context

I have no idea if the bug has existed before, I don't usually drag scrollbars with my mouse

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
@mrmelon54 Apologies for the issues here, that shouldn't be happening. Could you share the output of your logs when this happens?

Does the crash seem to depend on anything in particular? Such as the size of the block that was executed, the window size, etc.

**Comment by mrmelon54** [comment]
It doesn't seem to depend on anything in particular. Not sure exactly how it could happen, I don't know rust at all but I thought stuff like this wasn't meant to be possible?

I just copied the output when running from a terminal

[warp-segfault.log](https://github.com/warpdotdev/Warp/files/14466420/warp-segfault.log)

**Comment by brezanac** [comment]
Same issue here.

Dragging a scrollbar by holding the left mouse button results in Warp crashing randomly within the next second or so.

However, just scrolling the mouse wheel over Warp will **not** trigger the crash.

Same applies for the Settings window.

Warp `v0.2024.02.27.08.01.stable_03` running on `Linux Mint 21.3 Cinnamon` (kernel `5.15.0-97-generic`).

**Comment by alokedesai** [comment]
@mrmelon54 @brezanac Thanks for the info, we're actively looking into this. Could you run `glxinfo -B` and send us the output? You may need to install `mesa-utils` to run `glxinfo`. Thank you!

**Comment by brezanac** [comment]
> Additionally, are you able to get a backtrace for the segfault using `gdb`?

Of course, happy to help.

The full output of `glxinfo -B`.

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 6962 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 2070/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 535.161.07
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 535.161.07
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 535.161.07
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

```

The `gdb` backtrace (full gdb output is attached).

```
Thread 1 "warp-terminal" received signal SIGSEGV, Segmentation fault.
0x00005555577c048a in ?? ()
(gdb) backtrace
#0  0x00005555577c048a in ?? ()
#1  0x00005555577b5b95 in ?? ()
#2  0x00005555577a7410 in ?? ()
#3  0x00005555578be6b3 in ?? ()
#4  0x00005555564275c2 in ?? ()
#5  0x0000555556427123 in ?? ()
#6  0x000055555642713d in ?? ()
#7  0x000055555644598f in ?? ()
#8  0x000055555642762c in ?? ()
#9  0x00007ffff7948d90 in __libc_start_call_main (main=main@entry=0x555556427600, argc=argc@entry=1, argv=argv@entry=0x7fffffffdcc8) at ../sysdeps/nptl/libc_start_call_main.h:58
#10 0x00007ffff7948e40 in __libc_start_main_impl (main=0x555556427600, argc=1, argv=0x7fffffffdcc8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdcb8) at ../csu/libc-start.c:392
#11 0x000055555592f8ae in ?? ()
```
[gdb.log](https://github.com/warpdotdev/Warp/files/14485262/gdb.log)

**Comment by alokedesai** [comment]
Thanks for the info! We have an understanding of what the fix is: it's within some unsafe code in a Rust crate we depend on. We should have a fix for this out asap, apologies for the issues and thanks for your patience here.

**Comment by alokedesai** [comment]
@mrmelon54 @brezanac Could you try the latest preview build of Warp to confirm it fixes these crashes:

[deb](https://releases.warp.dev/stable/v0.2024.03.05.08.02.stable_00/warp-terminal_0.2024.03.05.08.02.stable.00_amd64.deb)
[rpm](https://releases.warp.dev/stable/v0.2024.03.05.08.02.stable_00/warp-terminal-v0.2024.03.05.08.02.stable_00-1.x86_64.rpm)
[pacman](https://releases.warp.dev/stable/v0.2024.03.05.08.02.stable_00/warp-terminal-v0.2024.03.05.08.02.stable_00-1-x86_64.pkg.tar.zst)
[appimage](https://releases.warp.dev/stable/v0.2024.03.05.08.02.stable_00/Warp-x86_64.AppImage)

**Comment by mrmelon54** [comment]
This does seem to fix both the scrolling and selecting text issues for me

**Comment by alokedesai** [comment]
Yeah, you'll see that "update warp" notice because this version of Warp hasn't yet been rolled out. We're in the process of rolling it out right now, so you should see that go away in ~30 minutes or so when its fully rolled out.

**Comment by alokedesai** [comment]
Ok this should be fully rolled out. If you run the "Check for updates" action in the command palette, you should no longer see the notice about "Updating Warp"

**Comment by mrmelon54** [comment]
Thanks. I have been messing around for a bit and have not been able to reproduce the segfault.
