### ISSUE TITLE
Allow copying text to the ask AI Section

### ISSUE THREAD

**Issue by ismailghedamsi** [warpdotdev/Warp#4429]
### Discord username (optional)

small44

### Describe the solution you'd like?

I should be able to copy a prompt from a text file or a web page and paste it in the zone where to ask the AI

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for submitting this @ismailghedamsi 

We already have a request tracking this over at #2553

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
