### ISSUE TITLE
DUP: Duplicate of #176 - Vi / Vim / Neovim - Clicking on links not working in Neovim

### ISSUE THREAD

**Issue by corroded** [warpdotdev/warp#443]
### Describe the bug

```shell
In neovim, when you try to do `cmd` + click, nothing happens. It does highlight the URL with an underline but that's it.
```

### To Reproduce

Steps to reproduce:
1. Open a file with a URL in it neovim 
2. Click on URL (or try to)

### Expected behaviour

```shell
Should open a browser window or the appropriate application
```

### Screenshots

![image](https://user-images.githubusercontent.com/46548/142554377-57764c5b-de7d-4189-921c-55942b3a0104.png)

It shows the underline - but can't click

### OS Version

10.15.7

**Comment by gagata** [comment]
Hey! Just a quick check - do you have mouse support enabled in your nvim config? By default (vanilla [n]vim) has it off, and it does work correctly for me. However, if I do `set mouse=a` then the link gets highlighted, but clicking indeed doesn't open the link in the browser. Wanted to clarify if that's the case

**Comment by elviskahoro** [comment]
I'm confident that the underlying issue is this: 
- https://github.com/warpdotdev/warp/issues/176
