### ISSUE TITLE
ability to save window configurations with different directories

### ISSUE THREAD

**Issue by michelle-slang** [warpdotdev/Warp#4430]
### Describe the solution you'd like?

One thing I loved about iTerm was that I could save my window configuration so that when I started or restarted iTerm, each tab would open to a different path/directory of my chosing. For example, I usually have 4 different tabs open - one is running my local build at path `/example-ui`, one is open to my ui directory at path `/example-ui`, one is open to where my api files live at path `/example-apis` and one is open to all my backend code at `/`. 

When I open or restart Warp, I would like each of my 4 tabs to open with those paths in the prompt. Right now, I have to open each path in each separate tab every time I start or restart Warp. 

### Is your feature request related to a problem? Please describe.

It's frustrating and time-consuming to have to re-enter each starting path for each tab every time I start or restart Warp. 

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi again @michelle-slang 👋 Warp has a feature called launch configurations which allows you to save a set of windows/tabs/panes and also run commands on them. Please see our docs and let us know if this meets your use case. https://docs.warp.dev/features/sessions/launch-configurations
