### ISSUE TITLE
Terminal window opens at wrong desktop in linux

### ISSUE THREAD

**Issue by imartemy1524** [warpdotdev/Warp#4432]
### Describe the bug

If one opens warp window at desktop one, then peek to desktop 2, and tries to open the second window right over there — it would open at desktop 1.

### To reproduce

1. Create 2 desktops using KDE (maybe works in GNOME also)
2. Open first window at desktop 1
3. Peek to desktop 2
4. Try opening window at destop 2 — it would open at desktop 1

### Expected behavior

window opens at current selected desktop

### Operating system

Linux

### Operating system and version

Arch linux KDE

### Current Warp version

v0.2024.02.27.08.01.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @imartemy1524 Thanks for letting us know. Sorry if this is a blocker. We're investigating some issues with window managers and desktop environments. We'll post updates on this thread and in our changelogs.  https://docs.warp.dev/getting-started/changelog

**Comment by redflox** [comment]
Hello, the same thing happens to me too, I have Linux Mint with Kde Plasma, it is really annoying, I hope you can solve it, greetings.

**Comment by imartemy1524** [comment]
#4406 — related issue

**Comment by lucieleblanc** [comment]
Thank you for the reports! I'm trying to reproduce this issue using KDE Plasma and GNOME on Ubuntu but am not seeing the same behavior. Maybe this is distro-specific, but just to confirm, are you still seeing this issue with the latest Warp build (`v0.2024.03.19.08.01.stable_01`)?

**Comment by imartemy1524** [comment]
No, it seems to be fixed in `v0.2024.03.19.08.01.stable_01`.

**Comment by lucieleblanc** [comment]
Awesome! Glad to hear it.
