### ISSUE TITLE
Block Filtering should accept negatives

### ISSUE THREAD

**Issue by wesbos** [warpdotdev/Warp#4437]
### Discord username (optional)

wesbos

### Describe the solution you'd like?

I'm working with a script that is puking stuff into the console and there is no way for me to filter it via my codebase.

I would love to be able to filter the block for things I don't want. Chrome dev tools does this, you can type `-deprecated -hydration` and it will filter out items instead of filtering for them.

I was stoked to see the new block filtering - would love to use negatives in there as well! 

Here is what I'm dealing with

<img width="1221" alt="Screenshot 2024-03-01 at 4 34 33 PM" src="https://github.com/warpdotdev/Warp/assets/176013/03a421dd-3794-4987-8175-b652cdd7181b">

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for submitting @wesbos, I see how the inverse filtering could be handy in these situations and a great enhancement to [Block Filtering](https://docs.warp.dev/features/blocks/block-filtering). As a possible stopgap, you can pipe the result of your script into `grep -v`, something like `tsx transcript.ts | grep -v "deprecated.*hydration"` to filter the inverse of deprecated and hydration (`\|` if you want to filter for the inverse of either or).

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by danielpeng2** [comment]
Hey! Totally agree that this would be a useful feature, the team has had internal discussions about this before. We're going to prioritize getting something working for this!

**Comment by wesbos** [comment]
awesome thanks a ton, both of you!

**Comment by danielpeng2** [comment]
This was released in today's update (v0.2024.03.12.08.02.stable_01)! Going to close out this issue, but feel free to reopen if there's any problems/feedback.
