### ISSUE TITLE
Open new windows with custom size

### ISSUE THREAD

**Issue by talison-cardoso** [warpdotdev/Warp#4439]
### Discord username (optional)

talisong-cardoso#5484

### Describe the bug

There is no effect when changing the "rows" and "columns" fields (`settings > appearance > window`), I have already restarted the PC and it still remains at the default size (which is very large)

### To reproduce

1. Settings
2. Appearance
3. Window

### Operating system

Linux

### Operating system and version

Ubuntu 23.10

### Current Warp version

v0.2024.02.27.08.01.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @talison-cardoso sorry to hear about this. Please disable the Session Restoration, and Warp should remember the custom size on startup. https://docs.warp.dev/features/sessions/session-restoration

Please let us know if that helps with the issue.

**Comment by talison-cardoso** [comment]
The problem remains. In the search for a solution I found this discussion [#4011](https://github.com/warpdotdev/Warp/issues/4011) And the same problem as the one presented in this **issues**

[Screencast from 2024-03-02 12-15-02.webm](https://github.com/warpdotdev/Warp/assets/132726516/cc14bb71-80fe-45a1-a8dc-cd0026e55f93)

Also test with the option `Restore windows, tabs, and crashes on startup.` And nothing helped.
I already deleted warp.sqlite and I was also unsuccessful.
