### ISSUE TITLE
DUP: Duplicate of #197 - Confirm before quitting toggle

### ISSUE THREAD

**Issue by corroded** [warpdotdev/warp#444]
### Describe the solution you'd like?

```shell
Have a toggle or option to not quit immediately if you press `cmd` + `q`. A confirmation message would be good.
```

### Is your feature request related to a problem? Please describe.

```shell
I accidentally quit my Warp by pressing `cmd` + `q`. My bad, but I'm pretty sure it's a common thing for us to do since iTerm has a feature to prevent that specifically.
```

### Additional context

![image](https://user-images.githubusercontent.com/46548/142571070-384b7276-b90c-4a90-be2f-33187783ddd4.png)

Bonus if the "even if there are no windows" option is done too.

![image](https://user-images.githubusercontent.com/46548/142571116-a3b959ec-0344-47c4-9969-9325a7e03d5c.png)

**Comment by elviskahoro** [comment]
Linking:
- #197
