### ISSUE TITLE
SEGFAULT when dragging prompt blocks

### ISSUE THREAD

**Issue by kernelb00t** [warpdotdev/Warp#4442]
### Describe the bug

When dragging Warp prompt blocks, the Warp terminal can sometimes SEGFAULT. It seems that this happens when the "Date" block hovers over the red cross of the "user@host" block, when the "Date" block have already been dragged.

### To reproduce

1. Fire up Warp via another Terminal : `warp-terminal`
2. Go into "Settings", then "Appearance", the "Warp prompt"
3. Drag the "Date" block into the prompt builder
4. Then drag it back into the available blocks
5. Re-drag it over the prompt, shake it over the "user@hostname" block
6. Watch the SEGFAULT

### Expected behavior

No crashes, nor bugs.

### Operating system

Linux

### Operating system and version

Arch Rolling latest (March 2, 12:20 Europe/Paris)

### Shell Version

zsh 5.9 (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.02.27.08.01.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

Note for regression : I just installed Warp, so I can't tell.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
Closing this since it was fixed in the latest release of Warp. Please reopen if you're still experiencing issues!
