### ISSUE TITLE
Support the kitty image protocol

### ISSUE THREAD

**Issue by Ast3risk-ops** [warpdotdev/Warp#4446]
### Describe the solution you'd like?

Support the [kitty image protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol/) (or the [iterm2 inline image protocol](https://iterm2.com/documentation-images.html)) to render images in the terminal.

Comparison: 

![Screenshot_20240302_091731](https://github.com/warpdotdev/Warp/assets/83875983/fd830728-c7cb-4d80-b71e-13368a04d5a7) 

(konsole supports it, warp does not)

### Is your feature request related to a problem? Please describe.

No, but it would be a neat feature to add down the line.

### Additional context

This protocol is used for cool neofetches and rendering other media inline in the terminal.

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by Ast3risk-ops** [comment]
It would be a neat feature for a terminal that brands itself as "your terminal reimagined".

**Comment by Ikken9** [comment]
Hi @Ast3risk-ops!

There is already a request for this at #26, if you could give it a :+1: and subscribe to that request so the devs can see the interest, it would be great!

**Comment by Ikken9** [comment]
Duplicate of #26

**Comment by Ast3risk-ops** [comment]
> Duplicate of #26

I did a search and couldn't find this. Thanks for telling me.
