### ISSUE TITLE
Quick copy link to clipboard

### ISSUE THREAD

**Issue by alechenninger** [warpdotdev/Warp#4450]
### Describe the solution you'd like?

It'd be nice if you could quickly copy a link to the clipboard just by clicking on it and clicking a menu item. There is the option to follow the link, but often you need to copy the link as input to another tool.

### Additional context

For example, I need to run a Dart process that starts devtools and waits to attach a debugger. I need the URL as input to the debugger. It's a pain to have to highlight the URL and manually copy and paste, when Warp clearly already see the URL and could theoretically give me a quick way to copy it to the clipboard.

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by alechenninger** [comment]
Ah. I feel like that wasn't there or I would've seen it. Or maybe I just missed it. I wonder if it isn't there when there is a secret detected in the URL, when masking is enabled. I can check later.

**Comment by alechenninger** [comment]
I see, I was looking at the left click menu and didn't realize there was a different menu for right click:
<img width="477" alt="image" src="https://github.com/warpdotdev/Warp/assets/3496559/7a2dfa92-7530-4adc-aa6b-13c283a7ceda">
Thanks!

**Comment by alechenninger** [comment]
(It might be nice if that had another option to copy the link, alongside the others, for what it's worth.)

**Comment by alokedesai** [comment]
Agreed that would be a nice product quality improvement; I filed a task for this in our internal bug tracker.
