### ISSUE TITLE
It would be nice to have mouse wheel button work in warp work like it does in built in terminal of ubuntu

### ISSUE THREAD

**Issue by c0derdx** [warpdotdev/Warp#4452]
### Describe the solution you'd like?

Anything that make it work...

### Is your feature request related to a problem? Please describe.

I get frustrated when I always have to copy a command. I should be able to directly paste it using mouse wheel button (selection buffer)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by SilentGlasses** [comment]
This is a duplicate.....  Think you should close this out and subscribe to the other issue instead as there is already a conversation happening there.

https://github.com/warpdotdev/Warp/issues/4329

**Comment by alokedesai** [comment]
Closing as a duplicate of #4329.
