### ISSUE TITLE
Micro freezes

### ISSUE THREAD

**Issue by ElliIsmail** [warpdotdev/Warp#4456]
### Describe the bug

Every time I have warp opened, my linux ubuntu 22.04.4 LTS gets about 1-2 seconds microfreezes from time to time.
These freezes are completely gone once I close it.

I don't know what kind of additional information do you need ?

### To reproduce

1. Open Warp
2. ???
3. Micro-freezes once in a while

### Expected behavior

A smooth operation

### Operating system

Linux

### Operating system and version

22.04

### Current Warp version

v0.2024.02.27.08.01.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

It didn't use to freeze when I first installed Warp 23 February

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by BlueCannonBall** [comment]
Try running Warp with `WGPU_BACKEND=gl`.

**Comment by kinxyo** [comment]
> Try running Warp with `WGPU_BACKEND=gl`.

Thanks, this did the trick but I hope they release a proper fix soon.

**Comment by ElliIsmail** [comment]
I'm not longer on linux I moved to mac and it's working perfectly. I don't know if I should close this issue ?

**Comment by marcoc2** [comment]
Same problem here on same OS version

**Comment by marcoc2** [comment]
I tried the backend trick, but didn't solve it. It is impossible to use with this issue. Really liked it, but I will have to unistall.
