### ISSUE TITLE
[Warp AI] - The requests used and refresh time should be more prominent so the user understands they are limited

### ISSUE THREAD

**Issue by gp-p2a** [warpdotdev/Warp#4458]
### Describe the solution you'd like?

The following screenshot shows the current request count for Warp AI

![Screenshot 2024-03-04 at 8 38 05 AM](https://github.com/warpdotdev/Warp/assets/69176452/11bd67d3-7722-4244-8af6-faa38e9b28e8)

I only noticed it after I had an error and made 2 requests. I think this information should be more prominent to remind users that they have a limitation. It is also a potential call to action for a transaction. What happens when you run out of your daily amount? For those on the free or team plan, they are stuck. Let them buy an allotment of requests. Tokens for queries. You could have a nice little section at the top.

You have used 4 of 100 requests /day -> Add 500 request tokens for $20, use at any time, never expires

Someone tosses in $20, just cuz, sees that they have a ton of room, and starts playing with confidence that they won't run out. Now Warp AI becomes their daily companion. Running a Neovim editor it's the most efficient coding experience on the planet. 

As Warp drives down the /request cost of AI, those prepaid tokens become less and less expensive to execute. 

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by CaptainVincent** [comment]
warp open source
