### ISSUE TITLE
Core: Drag and drop of files/directories must properly escape whitespace and quotes

### ISSUE THREAD

**Issue by hillegass** [warpdotdev/warp#446]
### Describe the bug

```shell
I was excited to see that you can now drag and drop paths from the Finder on MacOS.  However, for the paths to be useful they need to be properly escaped.  For example, "/Users/aaron/test this.pdf" is a fine path on MacOS.  However, it needs to become  "/Users/aaron/test\ this.pdf" when dragged into the terminal window.  Same with "Users/aaron/fred's dog.png"
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Screenshots

<img width="730" alt="Screen Shot 2021-11-19 at 10 18 06 AM" src="https://user-images.githubusercontent.com/188895/142647158-684d1ae5-3c3f-49b6-966e-5f8eacd1677c.png">

### Operating System

MacOS

### OS Version

MacOS 11.16

**Comment by alokedesai** [comment]
Thanks for filing! We have this fixed internally--it should be released externally early next week

**Comment by elviskahoro** [comment]
v0.2021.11.23.17.55.stable_01 should be fixed! please reopen and comment if not working.
