### ISSUE TITLE
Persist dropdown/visor dimensions

### ISSUE THREAD

**Issue by david-ninety** [warpdotdev/Warp#4463]
### Describe the solution you'd like?

I'd like the visor's appearance settings to persist, not only the "main" app's dimensions.

### Is your feature request related to a problem? Please describe.

I primarily use the dropdown visor rather than the "true app". I also like to set my row size to be about 50 rows or so - not the default 15-20-ish rows. I find that the visor often reverts to the default dimensions, necessitating resizing. This happens about once a day but can occur multiple times due to inputs I haven't yet tried figuring out.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @david-ninety if by visor you mean the dedicated window, that one can be set to a specific relative size of the screen, not col/row size as with the custom size settings. https://docs.warp.dev/features/windows/global-hotkey#dedicated-window

Also, if you set it to Main Screen, it should remember edits to the size that you set as long as you don't fully quit the app, and just toggle it with your global hotkey. when you close the app, it reverts to the relative size set in the settings. 

https://github.com/warpdotdev/Warp/assets/16809145/4054afa2-3c98-437f-aa21-8aba4101451a

Please let us know if that helped with your use case.

**Comment by david-ninety** [comment]
Yes! 

Setting the quake visor's height via `Settings > Features > Keys > Global Hotkey > Height %` accomplished what I was hoping for. Before, I (mistakenly) expected `Settings > Appearance > Window > Rows` to be the controlling value.

Thanks a million.

**Comment by david-ninety** [comment]
Yes! 

Setting the quake visor's height via `Settings > Features > Keys > Global Hotkey > Height %` accomplished what I was hoping for. Before, I (mistakenly) expected `Settings > Appearance > Window > Rows` to be the controlling value.

Thanks a million.
