### ISSUE TITLE
Implementation of Linux Network Proxy Environment Variables and dconf Proxy Configuration Support

### ISSUE THREAD

**Issue by aucub** [warpdotdev/Warp#4470]
### Describe the solution you'd like?

I would like Warp Terminal to automatically recognize and apply the network proxy settings that are configured at the system level. This means that if I set proxy variables in the GNOME settings or configure them through the fish shell, Warp Terminal should detect these settings without requiring additional input or manual configuration from me.
Specifically, the solution should:

    Fetch and use the http_proxy, https_proxy, and no_proxy environment variables that are set through the GNOME network settings, as well as any custom environment variables related to the network proxy.
    Respect the proxy configurations made using the dconf editor or any other system configuration tools on Linux.
    Include these proxy environment settings in the Warp Terminal's environment automatically upon startup or through a refresh mechanism.

I expect that with these enhancements, any commands or applications run within Warp Terminal would seamlessly utilize the system's proxy settings just like they do in other terminals that support this functionality. This would greatly simplify working with network proxies in Warp Terminal and ensure a consistent and more efficient workflow.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for this feature request!

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by alokedesai** [comment]
Hey @aucub, would you mind providing a specific set of repro steps for this? My understanding from looking through the code is that we do support the `HTTP_PROXY` and `HTTPS_PROXY` env vars. I'll make sure to track the other proxy issues you mentioned, but I'd like to make sure at least those two env vars are working for you!

**Comment by aucub** [comment]
Yes, previously I was doing it incorrectly. Warp does indeed support the HTTP_PROXY and HTTPS_PROXY environment variables.
