### ISSUE TITLE
always on top

### ISSUE THREAD

**Issue by duanchengwen** [warpdotdev/Warp#4471]
### Describe the solution you'd like?

i want set warp always on top like this
![2024-03-05_16-04](https://github.com/warpdotdev/Warp/assets/19401583/7913b073-7250-4ad2-8c76-d5678c876eaf)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by Heath123** [comment]
You can use Alt + Space to being up that menu on Gnome

**Comment by duanchengwen** [comment]
> You can use Alt + Space to being up that menu on Gnome

thanks, that's good
