### ISSUE TITLE
Warp crashing after update while dragging split pane

### ISSUE THREAD

**Issue by avnerjose** [warpdotdev/Warp#4474]
### Describe the bug

I use split panes to open 4 different terminal instances in the same window, Warp by default creates all of them side by side, when I try to drag one of the panes to reorganize their other Warp crashes.

### To reproduce

1. Open Warp
2. Type "ctrl + D" to create a split pane
3. Select one of the panes and drag it to the other position
4. Warp Crashes

### Expected behavior

I should be able to move the panes around without any crases

### Screenshots

https://github.com/warpdotdev/Warp/assets/49520658/1a85efd3-b8bf-4435-80dc-1626e953bc08

### Operating system

Linux

### Operating system and version

PopOS 22.04

### Shell Version

fish 3.7.0

### Current Warp version

v0.2024.02.27.08.01.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

I don't recall, it was last week before I updated to the newest version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by abolfazlsajadi** [comment]
Same problem:
v0.2024.02.27.08.01.stable_03

Description:	Ubuntu 22.04.4 LTS

**Comment by alokedesai** [comment]
Hi there, we just released a new version of Warp that fixes this issue. Sorry for these issues here--they were with a Rust crate that we depend on that we've since fixed.

**Comment by alokedesai** [comment]
Closing this out because we believe this issue has been fixed. Please reopen or file a new issue if you're still seeing this crash!

**Comment by avnerjose** [comment]
The issue seems to be solved in the newest version, thanks!
