### ISSUE TITLE
[Linux] Crashes on text selection

### ISSUE THREAD

**Issue by bosskopp** [warpdotdev/Warp#4475]
### Describe the bug

After I have copied some lengthy text into Warp, when i select parts of that text using the mouse, the application crashes.

Demo:

https://github.com/warpdotdev/Warp/assets/1733427/11f4c37b-3af3-4aa8-993c-e1912f39e8e6

### To reproduce

1. Open Warp
2. Copy a paragraph from e.g. https://www.loremipsum.de/
3. Paste the text into Warp
4. Hold down the left button of the mouse to begin to select text
5. Wait until the app crashes (error: 28470 segmentation fault (core dumped)  warp-terminal)

### Expected behavior

Warp not crashing when selecting text

### Operating system

Linux

### Operating system and version

Ubuntu 20.04.6 LTS

### Shell Version

zsh 5.8 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2024.02.27.08.01.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

X11 window manager

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Xalior** [comment]
Came here to report same bug:

I'm on Ubuntu Gnome 22.04 LTS, same warp version, ZSH 5.8.1

Also tried with multiple themes, all behave the same way.

**Comment by rodrigoGA** [comment]
Same problem.
Ubuntu 22.04 and zsh

**Comment by abolfazlsajadi** [comment]
same problem:

v0.2024.02.27.08.01.stable_03

Description:	Ubuntu 22.04.4 LTS

**Comment by alokedesai** [comment]
@bosskopp  @abolfazlsajadi Sorry for the issues, this due to an issue in a Rust crate we depend on. We have a fix that we're in the process of rolling out. We expect to have it out within the next hour or two.

**Comment by alokedesai** [comment]
I'm going to go ahead and close out this issue, please reopen or file an issue if you're still experiencing crashes on the latest version of Warp!

**Comment by iddm** [comment]
I am experiencing this on the latest stable. Warp also crashes randomly when doing nothing.

**Comment by alokedesai** [comment]
@iddm Would you mind filing a new issue with more details including your Warp logs?
