### ISSUE TITLE
Arch Linux with Hyprland: Window Scaling is too big

### ISSUE THREAD

**Issue by askareija** [warpdotdev/Warp#4482]
### Describe the bug

When i open warp terminal, the window scaling is too big. I've already set my hyprland config to set monitor scaling to 1.0 and other applications looks good. just warp terminal looking big.

### To reproduce

1. Open warp terminal

### Expected behavior

Window scaling is normal, or refers to the system scaling.

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/21377617/3d62898e-99e6-4bd4-ac97-a70f97cfedd5)

### Operating system

Linux

### Operating system and version

Endeavour OS Galileo version 2023.11.17

### Shell Version

zsh 5.9 (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.03.05.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I'm using hyprland which is based on wayland, and this is glxinfo -B result:

```
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon Graphics (radeonsi, rembrandt, LLVM 16.0.6, DRM 3.57, 6.7.6-arch1-2) (0x1681)
    Version: 24.0.2
    Accelerated: yes
    Video memory: 512MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 23 MB, largest block: 23 MB
    VBO free aux. memory - total: 14429 MB, largest block: 14429 MB
    Texture free memory - total: 23 MB, largest block: 23 MB
    Texture free aux. memory - total: 14429 MB, largest block: 14429 MB
    Renderbuffer free memory - total: 23 MB, largest block: 23 MB
    Renderbuffer free aux. memory - total: 14429 MB, largest block: 14429 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 512 MB
    Total available memory: 16160 MB
    Currently available dedicated video memory: 23 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon Graphics (radeonsi, rembrandt, LLVM 16.0.6, DRM 3.57, 6.7.6-arch1-2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.0.2-arch1.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.2-arch1.1
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.0.2-arch1.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Sorry about this blocker @askareija. We're working on improvements to compatibility with window managers like hyprland. I suggest you checkout our discord as there are other users who have been able to successfully use hyprland, maybe with a different scaling setting. https://www.warp.dev/community

We'll post any updates on our changelog in the weekly release on Thursdays. https://docs.warp.dev/getting-started/changelog

**Comment by alokedesai** [comment]
Hey @askareija if you start force the user of Wayland (`WARP_ENABLE_WAYLAND=1 warp-terminal`) does this fix the issue?

**Comment by askareija** [comment]
> Hey @askareija if you start force the user of Wayland (`WARP_ENABLE_WAYLAND=1 warp-terminal`) does this fix the issue?

Hi @alokedesai , Yes it's working and fix the issue. I guess it's closed?. Thanks 😀

**Comment by snyderb-de** [comment]
i just made it float... and it snapped into tiling mode.
and now it opens in tiling mode. 

@alokedesai - where would i add the WARP_ENABLE_WAYLAND=1
in my hyprland config file?

**Comment by Ethan0429** [comment]
> Good to hear! We are actively working on native Wayland support, which should fix issues like this. In the meantime, enabling `WARP_ENABLE_WAYLAND=1` should fix this :)

I am running NixOS so it might have something to do with that, but when I attempt to run Warp with `WARP_ENABLE_WAYLAND=1 warp-terminal`, I get the error:

```
/nix/store/5pp5b783nw369pbzmzayqvfbzpm3aplr-warp-terminal-0.2024.02.20.08.01.stable_01/opt/warpdotdev/warp-terminal/warp: /nix/store/84wcm74cp3k2i504ggwkgf4ikdyk0y3m-curl-8.6.0/lib/libcurl.so.4: no version information available (required by /nix/store/5pp5b783nw369pbzmzayqvfbzpm3aplr-warp-terminal-0.2024.02.20.08.01.stable_01/opt/warpdotdev/warp-terminal/warp)
stdout is a tty true, in CI false.  using logfile: false
20:41:07 [INFO] Spawning terminal server process...
thread 'main' panicked at ui/src/windowing/winit/app.rs:118:14:
should be able to create event loop: Os(OsError { line: 81, file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.7/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoWaylandLib)) })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/nix/store/5pp5b783nw369pbzmzayqvfbzpm3aplr-warp-terminal-0.2024.02.20.08.01.stable_01/opt/warpdotdev/warp-terminal/warp: /nix/store/84wcm74cp3k2i504ggwkgf4ikdyk0y3m-curl-8.6.0/lib/libcurl.so.4: no version information available (required by /nix/store/5pp5b783nw369pbzmzayqvfbzpm3aplr-warp-terminal-0.2024.02.20.08.01.stable_01/opt/warpdotdev/warp-terminal/warp)
20:41:07 [INFO] Running terminal server...
20:41:07 [INFO] Received empty message; assuming the connection has been closed.
```

This is on `v0.2024.02.20.08.01.stable_01`. It looks like the main error is `NoWaylandLib`, though I'm not sure what this is trying to say. Any ideas?
