### ISSUE TITLE
Linux (Pop Os) Can't Update Warp

### ISSUE THREAD

**Issue by Yummy-Yums** [warpdotdev/Warp#4488]
### Describe the bug

![image](https://github.com/warpdotdev/Warp/assets/77977520/d2377c7a-bfb2-4654-81c4-f5c19bc0016a)

### To reproduce

can't update Warp
_sudo apt update && sudo apt install warp-terminal && warp_finish_update YjhWTGM_

### Operating system

Linux

### Operating system and version

 Pop!_OS 22.04 LTS x86_64

### Shell Version

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu

### Current Warp version

v0.2024.02.27.08.01.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

previous update

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
@Yummy-Yums Could you share the full output of the update command in text? From the screenshot you linked above, the error doesn't seem to be within Warp but it would be good to confirm with the full output.

**Comment by Yummy-Yums** [comment]
Output below 

Hit:1 http://packages.microsoft.com/repos/code stable InRelease
Hit:2 https://packages.microsoft.com/repos/edge stable InRelease
Ign:3 https://pkg.jenkins.io/debian-stable binary/ InRelease
Get:4 https://pkg.jenkins.io/debian-stable binary/ Release [2,044 B]
Hit:5 https://ppa2.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy InRelease
Ign:6 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 InRelease
Hit:7 https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy InRelease
Get:8 https://pkg.jenkins.io/debian-stable binary/ Release.gpg [833 B]
Hit:9 https://download.docker.com/linux/ubuntu jammy InRelease
Hit:10 https://ppa2.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy InRelease
Get:11 http://deb.volian.org/volian scar InRelease [35.1 kB]
Ign:12 https://releases.warp.dev/linux/deb stable InRelease
Err:8 https://pkg.jenkins.io/debian-stable binary/ Release.gpg
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5BA31D57EF5975CA
Hit:13 https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy InRelease
Get:14 http://apt.pop-os.org/proprietary jammy InRelease [11.5 kB]
Hit:15 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 Release
Hit:18 https://releases.warp.dev/linux/deb stable Release
Hit:21 http://apt.pop-os.org/release jammy InRelease
Ign:22 http://deb.volian.org/volian scar/main Translation-en
Ign:23 http://deb.volian.org/volian scar/main amd64 DEP-11 Metadata
Ign:24 http://deb.volian.org/volian scar/main DEP-11 48x48 Icons
Ign:25 http://deb.volian.org/volian scar/main DEP-11 64x64 Icons
Ign:26 http://deb.volian.org/volian scar/main DEP-11 64x64@2 Icons
Ign:27 http://deb.volian.org/volian scar/main DEP-11 128x128 Icons
Ign:28 http://deb.volian.org/volian scar/main amd64 c-n-f Metadata
Ign:22 http://deb.volian.org/volian scar/main Translation-en
Ign:23 http://deb.volian.org/volian scar/main amd64 DEP-11 Metadata
Ign:24 http://deb.volian.org/volian scar/main DEP-11 48x48 Icons
Ign:25 http://deb.volian.org/volian scar/main DEP-11 64x64 Icons
Ign:26 http://deb.volian.org/volian scar/main DEP-11 64x64@2 Icons
Ign:27 http://deb.volian.org/volian scar/main DEP-11 128x128 Icons
Get:29 http://apt.pop-os.org/ubuntu jammy InRelease [270 kB]
Ign:28 http://deb.volian.org/volian scar/main amd64 c-n-f Metadata
Ign:22 http://deb.volian.org/volian scar/main Translation-en
Ign:23 http://deb.volian.org/volian scar/main amd64 DEP-11 Metadata
Ign:24 http://deb.volian.org/volian scar/main DEP-11 48x48 Icons
Ign:25 http://deb.volian.org/volian scar/main DEP-11 64x64 Icons
Ign:26 http://deb.volian.org/volian scar/main DEP-11 64x64@2 Icons
Hit:16 https://scala.jfrog.io/artifactory/debian all InRelease
Ign:27 http://deb.volian.org/volian scar/main DEP-11 128x128 Icons
Hit:30 http://apt.pop-os.org/ubuntu jammy-security InRelease
Ign:19 https://scala.jfrog.io/artifactory/debian  InRelease
Hit:31 http://apt.pop-os.org/ubuntu jammy-updates InRelease
Ign:33 http://apt.pop-os.org/ubuntu jammy-backports InRelease
Hit:32 https://scala.jfrog.io/artifactory/debian  Release
Ign:35 http://apt.pop-os.org/proprietary jammy/main i386 Packages
Ign:36 http://apt.pop-os.org/proprietary jammy/main Translation-en
Ign:37 http://apt.pop-os.org/proprietary jammy/main amd64 DEP-11 Metadata
Ign:28 http://deb.volian.org/volian scar/main amd64 c-n-f Metadata
Ign:22 http://deb.volian.org/volian scar/main Translation-en
Ign:23 http://deb.volian.org/volian scar/main amd64 DEP-11 Metadata
Err:24 http://deb.volian.org/volian scar/main DEP-11 48x48 Icons
  404  Not Found [IP: 99.118.93.168 80]
Ign:25 http://deb.volian.org/volian scar/main DEP-11 64x64 Icons
Ign:26 http://deb.volian.org/volian scar/main DEP-11 64x64@2 Icons
Ign:38 http://apt.pop-os.org/proprietary jammy/main DEP-11 48x48 Icons
Ign:39 http://apt.pop-os.org/proprietary jammy/main DEP-11 64x64 Icons
Ign:27 http://deb.volian.org/volian scar/main DEP-11 128x128 Icons
Ign:28 http://deb.volian.org/volian scar/main amd64 c-n-f Metadata
Ign:22 http://deb.volian.org/volian scar/main Translation-en
Ign:23 http://deb.volian.org/volian scar/main amd64 DEP-11 Metadata
Ign:40 http://apt.pop-os.org/proprietary jammy/main DEP-11 64x64@2 Icons
Ign:41 http://apt.pop-os.org/proprietary jammy/main DEP-11 128x128 Icons
Ign:42 http://apt.pop-os.org/proprietary jammy/main amd64 c-n-f Metadata
Ign:43 http://apt.pop-os.org/ubuntu jammy/restricted Sources
Ign:44 http://apt.pop-os.org/ubuntu jammy/universe Sources
Hit:45 http://apt.pop-os.org/ubuntu jammy-backports Release
Ign:47 http://apt.pop-os.org/ubuntu jammy/multiverse Sources
Ign:48 http://apt.pop-os.org/ubuntu jammy/main Translation-en
Ign:49 http://apt.pop-os.org/ubuntu jammy/main amd64 c-n-f Metadata
Ign:50 http://apt.pop-os.org/ubuntu jammy/restricted amd64 Packages
Ign:51 http://apt.pop-os.org/ubuntu jammy/restricted i386 Packages
Ign:52 http://apt.pop-os.org/ubuntu jammy/restricted Translation-en
Ign:53 http://apt.pop-os.org/ubuntu jammy/restricted amd64 c-n-f Metadata
Ign:54 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
Ign:55 http://apt.pop-os.org/ubuntu jammy/universe i386 Packages
Ign:56 http://apt.pop-os.org/ubuntu jammy/universe Translation-en
Ign:57 http://apt.pop-os.org/ubuntu jammy/universe amd64 c-n-f Metadata
Ign:58 http://apt.pop-os.org/ubuntu jammy/multiverse amd64 Packages
Ign:59 http://apt.pop-os.org/ubuntu jammy/multiverse i386 Packages
Ign:60 http://apt.pop-os.org/ubuntu jammy/multiverse Translation-en
Ign:61 http://apt.pop-os.org/ubuntu jammy/multiverse amd64 c-n-f Metadata
Ign:35 http://apt.pop-os.org/proprietary jammy/main i386 Packages
Ign:36 http://apt.pop-os.org/proprietary jammy/main Translation-en
Ign:37 http://apt.pop-os.org/proprietary jammy/main amd64 DEP-11 Metadata
Ign:38 http://apt.pop-os.org/proprietary jammy/main DEP-11 48x48 Icons
Ign:39 http://apt.pop-os.org/proprietary jammy/main DEP-11 64x64 Icons
Ign:40 http://apt.pop-os.org/proprietary jammy/main DEP-11 64x64@2 Icons
Ign:41 http://apt.pop-os.org/proprietary jammy/main DEP-11 128x128 Icons
Ign:42 http://apt.pop-os.org/proprietary jammy/main amd64 c-n-f Metadata
Get:43 http://apt.pop-os.org/ubuntu jammy/restricted Sources [57.0 kB]
Err:43 http://apt.pop-os.org/ubuntu jammy/restricted Sources
  File has unexpected size (23660 != 56988). Mirror sync in progress? [IP: 13.224.115.34 80]
  Hashes of expected file:
   - Filesize:56988 [weak]
   - SHA256:44b5e9d8bcf311d53f018618460d8f587faa7b81c13bd1bb70d3142785bf7727
   - SHA1:7d81e2a5e5377cf3704c5a29562443065312ae7c [weak]
   - MD5Sum:e7619d6d7b85648d9b9c92b28e8c1ec6 [weak]
  Release file created at: Wed, 06 Mar 2024 10:57:51 +0000
Get:44 http://apt.pop-os.org/ubuntu jammy/universe Sources [314 kB]
Err:44 http://apt.pop-os.org/ubuntu jammy/universe Sources

Get:47 http://apt.pop-os.org/ubuntu jammy/multiverse Sources [18.9 kB]
Err:47 http://apt.pop-os.org/ubuntu jammy/multiverse Sources

Get:48 http://apt.pop-os.org/ubuntu jammy/main Translation-en [279 kB]
Err:48 http://apt.pop-os.org/ubuntu jammy/main Translation-en

Get:49 http://apt.pop-os.org/ubuntu jammy/main amd64 c-n-f Metadata [16.1 kB]
Err:49 http://apt.pop-os.org/ubuntu jammy/main amd64 c-n-f Metadata

Get:50 http://apt.pop-os.org/ubuntu jammy/restricted amd64 Packages [1,508 kB]
Err:50 http://apt.pop-os.org/ubuntu jammy/restricted amd64 Packages

Get:51 http://apt.pop-os.org/ubuntu jammy/restricted i386 Packages [35.3 kB]
Err:51 http://apt.pop-os.org/ubuntu jammy/restricted i386 Packages

Get:52 http://apt.pop-os.org/ubuntu jammy/restricted Translation-en [249 kB]
Err:52 http://apt.pop-os.org/ubuntu jammy/restricted Translation-en

Get:53 http://apt.pop-os.org/ubuntu jammy/restricted amd64 c-n-f Metadata [520 B]
Err:53 http://apt.pop-os.org/ubuntu jammy/restricted amd64 c-n-f Metadata

Get:54 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages [1,053 kB]
Err:54 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages

Get:55 http://apt.pop-os.org/ubuntu jammy/universe i386 Packages [692 kB]
Err:55 http://apt.pop-os.org/ubuntu jammy/universe i386 Packages

Ign:35 http://apt.pop-os.org/proprietary jammy/main i386 Packages
Ign:36 http://apt.pop-os.org/proprietary jammy/main Translation-en
Ign:37 http://apt.pop-os.org/proprietary jammy/main amd64 DEP-11 Metadata
Ign:38 http://apt.pop-os.org/proprietary jammy/main DEP-11 48x48 Icons
Ign:39 http://apt.pop-os.org/proprietary jammy/main DEP-11 64x64 Icons
Ign:40 http://apt.pop-os.org/proprietary jammy/main DEP-11 64x64@2 Icons
Ign:41 http://apt.pop-os.org/proprietary jammy/main DEP-11 128x128 Icons
Ign:42 http://apt.pop-os.org/proprietary jammy/main amd64 c-n-f Metadata
Ign:35 http://apt.pop-os.org/proprietary jammy/main i386 Packages
Ign:36 http://apt.pop-os.org/proprietary jammy/main Translation-en
Ign:37 http://apt.pop-os.org/proprietary jammy/main amd64 DEP-11 Metadata
Err:38 http://apt.pop-os.org/proprietary jammy/main DEP-11 48x48 Icons
  404  Not Found [IP: 13.224.115.34 80]
Ign:39 http://apt.pop-os.org/proprietary jammy/main DEP-11 64x64 Icons
Ign:40 http://apt.pop-os.org/proprietary jammy/main DEP-11 64x64@2 Icons
Ign:41 http://apt.pop-os.org/proprietary jammy/main DEP-11 128x128 Icons
Ign:42 http://apt.pop-os.org/proprietary jammy/main amd64 c-n-f Metadata
Ign:35 http://apt.pop-os.org/proprietary jammy/main i386 Packages
Ign:36 http://apt.pop-os.org/proprietary jammy/main Translation-en
Ign:37 http://apt.pop-os.org/proprietary jammy/main amd64 DEP-11 Metadata
Fetched 317 kB in 25s (12.9 kB/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://ppa2.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy InRelease' doesn't support architecture 'i386'
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://pkg.jenkins.io/debian-stable binary/ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5BA31D57EF5975CA
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://ppa2.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy InRelease' doesn't support architecture 'i386'
W: Conflicting distribution: http://deb.volian.org/volian scar InRelease (expected scar but got jammy)
W: https://repo.scala-sbt.org/scalasbt/debian/dists/all/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://repo.scala-sbt.org/scalasbt/debian/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Failed to fetch https://pkg.jenkins.io/debian-stable/binary/Release.gpg  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5BA31D57EF5975CA
E: Failed to fetch http://apt.pop-os.org/proprietary/dists/jammy/main/dep11/icons-48x48.tar  404  Not Found [IP: 13.224.115.34 80]
E: Failed to fetch http://deb.volian.org/volian/dists/scar/main/dep11/icons-48x48.tar  404  Not Found [IP: 99.118.93.168 80]
E: Failed to fetch http://apt.pop-os.org/ubuntu/dists/jammy/restricted/source/Sources.xz  File has unexpected size (23660 != 56988). Mirror sync in progress? [IP: 13.224.115.34 80]
   Hashes of expected file:
    - Filesize:56988 [weak]
    - SHA256:44b5e9d8bcf311d53f018618460d8f587faa7b81c13bd1bb70d3142785bf7727
    - SHA1:7d81e2a5e5377cf3704c5a29562443065312ae7c [weak]
    - MD5Sum:e7619d6d7b85648d9b9c92b28e8c1ec6 [weak]
   Release file created at: Wed, 06 Mar 2024 10:57:51 +0000
E: Failed to fetch http://apt.pop-os.org/ubuntu/dists/jammy/universe/source/Sources.xz
E: Failed to fetch http://apt.pop-os.org/ubuntu/dists/jammy/multiverse/source/Sources.xz
E: Failed to fetch http://apt.pop-os.org/ubuntu/dists/jammy/main/i18n/Translation-en.xz
E: Failed to fetch http://apt.pop-os.org/ubuntu/dists/jammy/main/cnf/Commands-amd64.xz
E: Failed to fetch http://apt.pop-os.org/ubuntu/dists/jammy/restricted/binary-amd64/Packages.xz
E: Failed to fetch http://apt.pop-os.org/ubuntu/dists/jammy/restricted/binary-i386/Packages.xz
E: Failed to fetch http://apt.pop-os.org/ubuntu/dists/jammy/restricted/i18n/Translation-en.xz
E: Failed to fetch http://apt.pop-os.org/ubuntu/dists/jammy/restricted/cnf/Commands-amd64.xz
E: Failed to fetch http://apt.pop-os.org/ubuntu/dists/jammy/universe/binary-amd64/Packages.xz
E: Failed to fetch http://apt.pop-os.org/ubuntu/dists/jammy/universe/binary-i386/Packages.xz
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by alokedesai** [comment]
Thank you. This isn't an issue with Warp per-se. We're running `apt update` and you seem to have a few repositories that are misconfigured. 

Out of curiosity, does running `apt-get install --only-upgrade warp-terminal` allow you to update it?

**Comment by Yummy-Yums** [comment]
yeah it worked, thanks

**Comment by Yummy-Yums** [comment]
@alokedesai can we have your suggestion as a fallback cmd if the first one doesn't work i.e _update cmd_ in the upper right corner ? i feel it'd leave a lot of users trying to figure out what's wrong
