### ISSUE TITLE
Random high CPU usage (Linux)

### ISSUE THREAD

**Issue by Pilleo** [warpdotdev/Warp#4491]
### Describe the bug

Warp randomly starts to consume huge CPU resources (about 37% total load on 4 cores, 8 threads laptop). 
I just open it and sooner or later it appears. Nothing is executed at all. 

### To reproduce

Open warp in Kubuntu 23.10, do nothing, wait. After some time you can cook on your laptop 

### Screenshots

![выява](https://github.com/warpdotdev/Warp/assets/10074180/1dfee3ff-94e0-4895-b7b1-caa3e8ae85f6)

### Operating system

Linux

### Operating system and version

Kubuntu 23.10

### Current Warp version

v0.2024.03.05.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

wayland

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @Pilleo sorry to hear about this issue. As a possible workaround, if you have an dedicated GPU you can try making sure the low-power integrated GPU isn't set as default. https://github.com/warpdotdev/Warp/issues/4215#issuecomment-1967500574

Is there anything in particular you're running or it does this on any command like `ls`? ALso if you can please provide logs as this will help us understand the issue better. https://docs.warp.dev/help/sending-us-feedback#gathering-warp-logs


To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by Pilleo** [comment]
Thank you @dannyneira 
I only an internal amd gpu. 
Often I run `sudo nala upgrade -y &&   sudo apt purge $( dpkg --list | grep -P -o "linux-image-\d\S+|linux-headers-\d\S+" | grep -v $(uname -r | grep -P -o ".+\d") ) && sudo nala autoremove && sudo nala install linux-xanmod-x64v3`, but for now I could not see any correlation between CPU load and this command. 
[warp.log](https://github.com/warpdotdev/Warp/files/14529532/warp.log)

**Comment by Pilleo** [comment]
Seems like the issue is gone on Ubuntu 24.04

**Comment by dannyneira** [comment]
Thanks for letting us know. Closing as resolved but feel free to let us know if the issue persists.

**Comment by david1asher** [comment]
the main reason im not using warp is the cpu usage, its through the roof, so its a no go for intel macs
