### ISSUE TITLE
UI Scaling.

### ISSUE THREAD

**Issue by tunafysh** [warpdotdev/Warp#4492]
### Describe the solution you'd like?

I would like a setting where i could scale the UI to my liking.

### Is your feature request related to a problem? Please describe.

The UI personally feels bloated after wasting that space as the UI is too big for my liking. i would like to modify that.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hey @tunafysh Thanks for submitting, We have a few related requests here: 

1. Change the UI size. https://github.com/warpdotdev/Warp/issues/1443
2. Zen mode (disable the UI/tab bar). https://github.com/warpdotdev/Warp/issues/1009
3. Remove padding from alt-screens. https://github.com/warpdotdev/Warp/issues/2373

Hope this helps!

**Comment by tunafysh** [comment]
Actually. It got fixed by switching to Wayland... Hope this helps someone

**Comment by dannyneira** [comment]
cool!  thanks for letting us know, closing this issue.
