### ISSUE TITLE
Switch Accept AutoComplete Suggestion  Keyboard shortcut

### ISSUE THREAD

**Issue by Nasfame** [warpdotdev/Warp#4494]
### Discord username (optional)

laciferin

### Describe the solution you'd like?

I am used to using `tab key` to autocomplete as its faster than the arrow key. I couldn't find the option to set keyboard shortcut for the same on the keyboard shortcuts ui. 

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @Nasfame Thanks for submitting. There is a way to do this in the settings. Please check the terminal tip on this doc. https://docs.warp.dev/features/command-completions/completions#completions-on-aliases

We're also working on a "Classic" completions mode which may help with this issue and make completions work much like in traditional terminals.

**Comment by Nasfame** [comment]
Thanks @dannyneira This was what i was looking for: 
<img width="455" alt="image" src="https://github.com/warpdotdev/Warp/assets/24226219/99046f5a-ea9a-4de1-9555-197284535fb0">
