### ISSUE TITLE
Why isn't Warp allowed in the AUR?

### ISSUE THREAD

**Issue by aidan-gibson** [warpdotdev/Warp#4495]
### Describe the bug

https://lists.archlinux.org/hyperkitty/list/aur-requests@lists.archlinux.org/message/5W6TR3RWIKZGMEKKKTKFRLWGKFFKB46G/

https://lists.archlinux.org/hyperkitty/list/aur-requests@lists.archlinux.org/message/YVDHO5XIIVJYVWDPQ3RYGL3Y7ENSXZIO/

### To reproduce

Search the AUR for warp-terminal. It won't be there.

### Operating system

Linux

### Operating system and version

Arch

### Regression

Yes, this bug started recently or with an X Warp version

### Additional context

You realize it just confuses people right? We are very used to everything being in the AUR. Someone even had to ask how to install a .pkg.tar.zst here https://www.reddit.com/r/archlinux/comments/1az223d/warp_terminal_how_to_download_install/

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @aidan-gibson 

We have an official pacman package! I recommend you install it over the one from the AUR, to make sure you get timely updates and any appropriate modifications to the package definition. This link will download the latest official package: https://app.warp.dev/download?package=pacman

**Comment by dima74** [comment]
it would be great if warp could be installed using
```sh
pacman -S warp-terminal
```
or
```sh
yay -S warp-terminal
```

**Comment by aidan-gibson** [comment]
This issue was made prior to `warp-terminal` being available from `warpdotdev` repo; while the AUR would still be preferable and I think it's kinda weird, as long as I can update with `yay` I'm happy. Closing.

**Comment by CerulanLumina** [comment]
I do kinda feel like only having a package download from website is not the right way to go. It does prevent package upgrades in line with the rest of the system. An alternative that I strongly believe should be considered is to put the package in the AUR on an official basis or at the very least maintain a pacman repository so that updates can be distributed alongside a user's usual system upgrades.

**Comment by matiaslapolla** [comment]
Hey now its open-source... It's more doable
