### ISSUE TITLE
The "Get notified when Warp is cross-platform" form in 'Installing & Onboarding' documentation page never completes (and the link is broken)

### ISSUE THREAD

**Issue by darkred** [warpdotdev/Warp#4503]
### Describe the bug

- The submission of the "Get notified when Warp is cross-platform" form, from the (broken, see below) [link](https://warpdotdev.typeform.com/to/lWeDTQnr/README.md) in the [Installing & Onboarding](https://docs.warp.dev/getting-started/getting-started-with-warp) documentation page never completes (I tried it in both Chrome and Firefox and let it retry for quite some time). I attach a gif below.

- The [link](https://warpdotdev.typeform.com/to/lWeDTQnr/README.md) itself is broken, as points to a broken URL:
    ```
    https://github.com/warpdotdev/gitbook/blob/main/getting-started/[https:/warpdotdev.typeform.com/to/lWeDTQnr/README.md
    ```
    It should point to this instead: 
    `https:/warpdotdev.typeform.com/to/lWeDTQnr/README.md` 
    (I attach a screenshot)

### To reproduce

Visit [https://warpdotdev.typeform.com/to/lWeDTQnr/README.md](https://warpdotdev.typeform.com/to/lWeDTQnr/README.md), enter an email, select platform(s) and click Submit: the submission never completes (see attached gif).

### Screenshots

![gif](https://github.com/warpdotdev/Warp/assets/723651/8a23be3a-9c7b-4945-a148-9b3bacea3f65)

![2024-03-07_235557](https://github.com/warpdotdev/Warp/assets/723651/cbd9fa8d-e820-4a8b-9ebe-ba57c87b56c5)

**Comment by dannyneira** [comment]
Hey @darkred thanks for letting us know. I've fixed this in our docs and on the #204.

I'll work on adding a link for the web version of Warp as well.
Closing as resolved.
