### ISSUE TITLE
zsh: command not found: node

### ISSUE THREAD

**Issue by holy-chen** [warpdotdev/Warp#4505]
### Describe the bug

After updating the version, open a new window, and some commands will prompt that they cannot be found.
<img width="530" alt="image" src="https://github.com/warpdotdev/Warp/assets/142613417/d56f4e32-c16e-4e7f-88d7-d2b62a08c846">

### To reproduce

1. update version: v0.2024.03.05.08.02.stable_01
2. Press `cmd` + `D` to create a new window.
3. Enter the command `node -v`

### Expected behavior

It is expected to work normally like the previous version.

### Screenshots

<img width="533" alt="image" src="https://github.com/warpdotdev/Warp/assets/142613417/5b4c8680-0197-4552-94b3-a5097d7ee948">

### Operating system

MacOS

### Operating system and version

Sonoma 14.2.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.03.05.08.02.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

2024-03-07

### Additional context

When I use `nvm` to re-specify the node version, I run `node -v` to use it normally, but when typing node, it still prompts as an unrecognized command, which is inconsistent with the previous behavior.
<img width="531" alt="image" src="https://github.com/warpdotdev/Warp/assets/142613417/864cfea3-1d6a-4155-a972-fee266289ec3">

However, when I pressed the shortcut key `cmd` + `D` again to create a window, the node command still could not be found.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @holy-chen sorry about this, please run `which node` and find the path to the binary. Then `export` that path in your .zshrc file and it should load on startup. `echo 'export PATH="$PATH:/path/to/node/bin"' >> ~/.zshrc`

Please let us know if that helps!

**Comment by holy-chen** [comment]
@dannyneira  Thank you for the solution, which may be useful for a fixed version. Due to my work, I need to use `nvm` to switch between different versions of nodes, which causes the path of my node bin file to be always the same, and the version number is dynamic.
<img width="509" alt="image" src="https://github.com/warpdotdev/Warp/assets/142613417/c839f6f3-63f2-4652-8fc9-ee728d6948e0">

**Comment by holy-chen** [comment]
I encountered the same problem on different terminals, which may be caused by `nvm`. I created a tracking [issue](https://github.com/nvm-sh/nvm/issues/3315).

**Comment by holy-chen** [comment]
> I encountered the same problem on different terminals, which may be caused by `nvm`. I created a tracking [issue](https://github.com/nvm-sh/nvm/issues/3315).

The problem has been solved. For details, please check the issue tracked here.
