### ISSUE TITLE
Notification on completion of command run

### ISSUE THREAD

**Issue by ad3sai** [warpdotdev/Warp#4511]
### Describe the solution you'd like?

There are commands that can run for a long time in terminal i.e. install all requirements from requirements.txt file. I would like to get a notification (a banner or a chime) when it is done running so I can work on different task as the same time and do not have to keep checking if it is done running. 

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hey @ad3sai Warp does support notification for long running commands and password prompts in the terminal. Please see our docs for more https://docs.warp.dev/features/notifications

Closing as this feature exists, but please let us know if any issues with using it.
