### ISSUE TITLE
Synchronise only panes in current tab

### ISSUE THREAD

**Issue by jpninanjohn** [warpdotdev/Warp#4515]
### Describe the solution you'd like?

Current synchronisation works for all tcurrent panes and future tabs that are being created post the start of synchronisation. Can we have options to only sync for current tab. And another to sync for all tabss including the ones already opened.

CMIIW about the current working process of ssynchronisation. I was not able to find any toher option other than a sync all panes and tabs.

Also is there any indicator that can be showed when synchronisation is turned on.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @jpninanjohn Both options to sync the current tab (not future) and sync all tabs (including future tabs) exist in warp. Also, there is an icon to indicate the tabs that are synced. You can also choose to stop syncing either the current tab or all panes(tabs).

https://github.com/warpdotdev/Warp/assets/16809145/bd4c33ab-0f76-4f1e-b28c-dee174ab75e5

Hope this helps, please see more in our sync input docs. https://docs.warp.dev/features/entry/synchronized-inputs

Closing as the features already exist, but please let us know if any issues with the feature.

**Comment by jpninanjohn** [comment]
What version is this ? I dont see the sync all in current tab. I am on linux and my warp version is v0.2024.03.05.08.02.stable_01

![image](https://github.com/warpdotdev/Warp/assets/11459946/458a8ff9-23af-42c6-92d1-967cde135f90)

**Comment by jpninanjohn** [comment]
Okay i figured out the issue. I had set the shortcut to stop all syncchronisation to the same shortcut that syncs which weirdly caused the option to disappear from the command pallette. I removed the shortcut and can see the options now. Is this intended  ? 

Is there anyway I can set the same shortcut to toggle between synch and stop synch ?
