### ISSUE TITLE
Warp on EndeavourOS with hyrpland has blurry letters

### ISSUE THREAD

**Issue by PWDSerialgamer07** [warpdotdev/Warp#4519]
### Describe the bug

I've just installed the warp terminal on EndeavourOS with hyprland, and the letters all appear extremely buggy.

### To reproduce

1. Install warp
2. Open it
3. Letters are blurry

### Expected behavior

Letters aren't blurry

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/118306463/659c95f0-22c1-40f4-a6a7-4f083582e159)

### Operating system

Linux

### Operating system and version

Endeavour OS rolling

### Shell Version

fish 3.7.0

### Current Warp version

v0.2024.03.05.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
Hi @PWDSerialgamer07, thanks for filing. We believe this is due to Warp's lack of support for native Wayland.

To confirm that, could you run force enable Wayland support by running with `WARP_ENABLE_WAYLAND=1 warp-terminal` to see if it fixes the issue?

**Comment by PWDSerialgamer07** [comment]
That seems to have fixed it, thank you!
