### ISSUE TITLE
Focus taken away from search bar once command is complete

### ISSUE THREAD

**Issue by fishcharlie** [warpdotdev/Warp#452]
### Describe the bug

```shell
The curser focus is switched away from the search bar once a command is complete. This shouldn't occur.
```

### To Reproduce

Steps to reproduce:
1. Run a long running command (ie. a command that takes 20 seconds or so)
2. Focus on the search bar
3. Once command is done, notice that focus is taken away from search bar

### Expected behaviour

```shell
Focus to remain where I selected (the search bar)
```

### Operating System

MacOS

### OS Version

12.1 Beta (21C5039b)

**Comment by elviskahoro** [comment]
Added with v0.2022.02.21.08.55.stable_00
