### ISSUE TITLE
Characters are not displayed correctly on the terminal when inputting Japanese

### ISSUE THREAD

**Issue by hrmtz** [warpdotdev/Warp#4529]
### Describe the bug

When inputting Japanese, the hiragana that is being input temporarily is not displayed before being converted to kanji.

### To reproduce

Input characters with warp in Japanese input mode

### Expected behavior

Unconfirmed characters are not displayed

### Operating system

MacOS

### Operating system and version

Sonoma 14.3.1

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
Hey @hrmtz, thanks for filing and very sorry for the troubles here. Unfortunately, Warp doesn't yet support showing marked text when the input method editor (IME) is open. Merging this into its canonical issue here: https://github.com/warpdotdev/Warp/issues/320
