### ISSUE TITLE
Midnight commander no colors

### ISSUE THREAD

**Issue by xorik** [warpdotdev/Warp#453]
### Describe the bug

```shell
No colors in midnight commander (mc in brew)
```

### To Reproduce

Steps to reproduce:
1. Open `mc`

### Expected behaviour

```shell
Files and folders has colors
```

### Screenshots

Warp VS iterm2
![Screen Shot 2021-11-22 at 22 01 07](https://user-images.githubusercontent.com/347044/142934816-a861b7f3-34ef-4f9b-94df-a624c55f856c.png)

### Operating System

MacOS

### OS Version

12.0

**Comment by xorik** [comment]
@elviskahoro still n colors in v0.2022.07.11.09.11.stable_01

**Comment by elviskahoro** [comment]
Gonna merge this with #362

**Comment by jonnywilliamson** [comment]
Hi,

I'm not seeing any colours in midnight commander at the moment.

Here is what I see when the "Enforce minimum contrast" is set to `NEVER`
<img width="920" alt="CleanShot 2023-01-29 at 13 01 11" src="https://user-images.githubusercontent.com/2513663/215327905-b4841a70-b7bc-4691-b136-c9ed0156f7d1.png">


And when switched to either `Only for named colours` OR `always`:
<img width="928" alt="CleanShot 2023-01-29 at 13 03 00" src="https://user-images.githubusercontent.com/2513663/215327930-a76451f2-f033-4c0c-b5fb-ab4c1f6ac631.png">


Note in both images, the first 2 files have been selected and should be yellow

This is what it looks like in iterm:
<img width="968" alt="CleanShot 2023-01-29 at 13 04 18" src="https://user-images.githubusercontent.com/2513663/215327991-443fba26-281e-4f92-8cbb-c22e935259c3.png">




Currently running:
<img width="419" alt="CleanShot 2023-01-29 at 13 05 32" src="https://user-images.githubusercontent.com/2513663/215328055-9c61302a-9feb-481a-9ca9-180a69b60c8d.png">

**Comment by lprouza** [comment]
I have same problem with Warp v0.2023.05.02.08.03.stable_00
