### ISSUE TITLE
语言支持会考虑除英语以外的其他语言吗？

### ISSUE THREAD

**Issue by larkzhang** [warpdotdev/Warp#4532]
### Describe the solution you'd like?

Does language support consider languages other than English? Such as Chinese, Japanese, Korean, German and other languages

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Duplicate of #1823
