### ISSUE TITLE
is there a way to 'Select All'?

### ISSUE THREAD

**Issue by crispybegs** [warpdotdev/Warp#4540]
### Describe the solution you'd like?

a way of selecting (and then deleting) the entire contents of a file

is there any way of replicating the simple cmd+A on a mac to select the entire contents of a file, then deleting it?

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @crispybegs, you can select all blocks with CMD-A if the focus is on the blocks, if the focus is on the input editor CMD-A selects all the text in the input. https://docs.warp.dev/features/keyboard-shortcuts

If you want to select all in a file (opened with VIM for example), the instructions for that are here https://www.warp.dev/terminus/select-all-in-vim-vi

Closing as this feature already exists. Please let us know if any issues with the CMD-A in blocks or input.

**Comment by crispybegs** [comment]
> Hi @crispybegs, you can select all blocks with CMD-A if the focus is on the blocks, if the focus is on the input editor CMD-A selects all the text in the input. https://docs.warp.dev/features/keyboard-shortcuts
> 
Thanks Danny. not sure if I'm getting something wrong here (i'm not very technical), but when I have a file open and cmd+A, nothing happens

I'm not sure what you mean by 'focus on the blocks' or 'focus is on the input editor'. Does this fall into either of those categories? This how I work...

<img width="1183" alt="Screenshot 2024-03-12 at 17 41 58" src="https://github.com/warpdotdev/Warp/assets/129169122/da3d1567-e8ec-491a-926c-05da635b548a">
