### ISSUE TITLE
Auto Complete the Command Key binding should be changed

### ISSUE THREAD

**Issue by Shoaib19** [warpdotdev/Warp#4547]
### Describe the solution you'd like?

when the user types something warp suggests the autocomplete of the command to do that user has to use the keys `cntrl+f` which is a bad experience for the user it should be the `tab` key as it is used as standard in every other application.

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @Shoaib19 please go to the "terminal tip" on this doc to learn about how to change the keyboard shortcut for Tab completion.  https://docs.warp.dev/features/command-completions/completions#completions-on-aliases

Also, please note that we're working on a "Classic" mode for completions which behaves much like you know in traditional terminals.
