### ISSUE TITLE
Configure command not working on SSH'd Ubiquiti UniFi

### ISSUE THREAD

**Issue by biztems** [warpdotdev/Warp#455]
### Describe the bug

```shell
Hi Warp Team,

The `configure` command usually used to get into configuration mode on a Ubiquiti UniFi / EdgeOS device (access by SSH) isn't working. It should put you into configuration mode, instead it just says command not found. Also it seems like it's not even showing the "welcome" message.

I guess it just chainloads something after SSH'ing, which isn't working on Warp.

Thanks!
```

### To Reproduce

Steps to reproduce:
1. SSH to an UniFi/EdgeOS device
2. Type "configure"
3. It will say "command not found"

### Expected behaviour

```shell
Configure should put you in the configuration mode.
```

### Operating System

MacOS

### OS Version

12.0.1

**Comment by elviskahoro** [comment]
@biztems 
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
