### ISSUE TITLE
Error on updating Warp on Rocky 9

### ISSUE THREAD

**Issue by luanbach** [warpdotdev/Warp#4550]
### Describe the bug

Error when trying to update Warp. using dnf
```
sudo dnf --refresh --repo warpdotdev upgrade warp-terminal && warp_finish_update 2NYNw2T
[sudo] password for luan.bach:
Error: Unknown repo: 'warpdotdev'
```

### To reproduce

Select the "Update Warp" button.

### Expected behavior

Warp should update.

### Operating system

Linux

### Operating system and version

Rocky Linux 9.3 (Blue Onyx)

### Shell Version

Bash version 5.1.8(1)-release

### Current Warp version

v0.2024.02.20.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by luanbach** [comment]
Hi @dannyneira ,

The script snippet worked. Thank you.

**Comment by dannyneira** [comment]
Nice !
Closing but do let us know any issues with updates
