### ISSUE TITLE
Failed to acquire default Secret Service collection: unknown error ( Cant open warp-terminal )

### ISSUE THREAD

**Issue by t101804** [warpdotdev/Warp#4554]
### Discord username (optional)

r3plican_

### Describe the bug

❯ warp-terminal
08:33:12 [INFO] Spawning terminal server process...
08:33:12 [WARN] error setting XSETTINGS; Xft options won't reload automatically
08:33:12 [INFO] Running terminal server...
08:33:12 [WARN] Failed to load a font face 0 from source cause malformed font.
08:33:12 [WARN] Failed to load font: Hack due to error Font family Hack does not contain any valid fonts
08:33:12 [ERROR] Failed to acquire default Secret Service collection: unknown error
thread 'main' panicked at warpui_extras/src/secure_storage/linux.rs:187:33:
range end index 12 out of range for slice of length 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
08:33:12 [INFO] Received empty message; assuming the connection has been closed.

### To reproduce

open warp-terminal

### Expected behavior

working

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/113588203/d3909f90-a971-409f-90d5-8469ddb0110b)

### Operating system

Linux

### Operating system and version

Arch Linux Hyprland

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by t101804** [comment]
> Hi @t101804 Sorry to hear about this, the secret service warning can generally be ignored as far as I know. But based on your logs I recommend you install the hack font.
> 
> We've added a list of workarounds here: https://docs.warp.dev/help/known-issues#linux-workarounds
> 
> Also, make sure to [download the latest version](https://warp.dev/linux-terminal) as we release fixes every week. https://docs.warp.dev/getting-started/changelog
> 
> Please let me know if that helped on this [tracker issue](https://github.com/warpdotdev/Warp/issues/4513).

its fatal error. i cant open warp-terminal

**Comment by t101804** [comment]
> Hi @t101804 Sorry to hear about this, the secret service warning can generally be ignored as far as I know. But based on your logs I recommend you install the hack font.
> 
> We've added a list of workarounds here: https://docs.warp.dev/help/known-issues#linux-workarounds
> 
> Also, make sure to [download the latest version](https://warp.dev/linux-terminal) as we release fixes every week. https://docs.warp.dev/getting-started/changelog
> 
> Please let me know if that helped on this [tracker issue](https://github.com/warpdotdev/Warp/issues/4513).

i use latest version

**Comment by t101804** [comment]
![image](https://github.com/warpdotdev/Warp/assets/113588203/183f8624-acee-49ea-9aa7-d867a038abf5)


here is the backtrace

**Comment by t101804** [comment]
![image](https://github.com/warpdotdev/Warp/assets/113588203/fd60d8ae-ef0c-4092-8f0a-2914aad36102)
already downloaded hack font. here are full backtrace

**Comment by vorporeal** [comment]
Can you use `RUST_BACKTRACE=full` and copy-paste the output here?

**Comment by t101804** [comment]
> Can you copy-paste the output with `RUST_BACKTRACE=full` here?

```
RUST_BACKTRACE=full warp-terminal
08:35:04 [INFO] Spawning terminal server process...
08:35:04 [WARN] error setting XSETTINGS; Xft options won't reload automatically
08:35:04 [INFO] Running terminal server...
08:35:04 [ERROR] Failed to acquire default Secret Service collection: unknown error
thread 'main' panicked at warpui_extras/src/secure_storage/linux.rs:187:33:
range end index 12 out of range for slice of length 0
stack backtrace:
   0:     0x5fcd177255db - <unknown>
   1:     0x5fcd16e33880 - <unknown>
   2:     0x5fcd17720c13 - <unknown>
   3:     0x5fcd17725374 - <unknown>
   4:     0x5fcd17727820 - <unknown>
   5:     0x5fcd1772753f - <unknown>
   6:     0x5fcd17727d3e - <unknown>
   7:     0x5fcd17727c42 - <unknown>
   8:     0x5fcd17725ad6 - <unknown>
   9:     0x5fcd177279b0 - <unknown>
  10:     0x5fcd16afc205 - <unknown>
  11:     0x5fcd16afc852 - <unknown>
  12:     0x5fcd190bb1dd - <unknown>
  13:     0x5fcd18aa52b7 - <unknown>
  14:     0x5fcd18183204 - <unknown>
  15:     0x5fcd18a45d53 - <unknown>
  16:     0x5fcd18a71116 - <unknown>
  17:     0x5fcd19006dcd - <unknown>
  18:     0x5fcd19027a10 - <unknown>
  19:     0x5fcd189f0dea - <unknown>
  20:     0x5fcd181825f2 - <unknown>
  21:     0x5fcd176f9e14 - <unknown>
  22:     0x5fcd176f9983 - <unknown>
  23:     0x5fcd176f999d - <unknown>
  24:     0x5fcd177172a5 - <unknown>
  25:     0x5fcd176f9f0c - <unknown>
  26:     0x7c3913f57cd0 - <unknown>
  27:     0x7c3913f57d8a - __libc_start_main
  28:     0x5fcd16c36a9e - <unknown>
  29:                0x0 - <unknown>
08:35:04 [INFO] Received empty message; assuming the connection has been closed.
```

**Comment by t101804** [comment]
> Can you copy-paste the output with `RUST_BACKTRACE=full` here?

hello , any help to fix this issue???

**Comment by t101804** [comment]
hello?

**Comment by vorporeal** [comment]
Hey, thanks for providing the additional info.

Does the file `~/.local/state/warp-terminal/dev.warp.Warp-User` exist?  If so, try deleting it and see if that fixes the issue.

**Comment by t101804** [comment]
> `dev.warp.Warp-User`

thx its work now
