### ISSUE TITLE
New tab/window does not open with previous session directory

### ISSUE THREAD

**Issue by jpninanjohn** [warpdotdev/Warp#4559]
### Describe the bug

If I am opening a new tab or window, it should retain which directory I am in when opening. It always defaults to home folder now. 

**I have configured working directory to use previous sessions in the features section of the settings for warp.**

### To reproduce

1. Navigate to any directory.
2. Open a new tab.
3. New tab is opened but directory is set to home folder.
4. Same for new window and pane.

### Expected behavior

New tab/window/pane should be set to previos sessions directory on open.

### Screenshots

https://github.com/warpdotdev/Warp/assets/11459946/04146664-0ce5-4001-b503-a684175fd8f2

### Operating system

Linux

### Operating system and version

Fedora release 37 (Thirty Seven) x86_64

### Shell Version

GNU bash, version 5.2.21(1)-release (x86_64-redhat-linux-gnu)

### Current Warp version

v0.2024.03.05.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @jpninanjohn sorry to hear about this. Please I was unable to reproduce this issue so I suspect that you may have something in your `~/.bashrc`, `~/.bash_profile`, or `~/.profile` that is causing the directory to be set to home. Make sure that's not the case and let us know if the issues persists.

**Comment by jpninanjohn** [comment]
This is not the case as this same bashrc runs in my other terminal(Terminator) and opens with the current directory in new tabs/windows/panes.

**Comment by jpninanjohn** [comment]
Identified the culprit. There was a rougue script in my bashrc that was resetting the directory.
