### ISSUE TITLE
can't sign in with github or auth token

### ISSUE THREAD

**Issue by HilSny** [warpdotdev/Warp#4560]
### Describe the bug

I am trying to sign in for the first time after signing up.

I click the "take me to warp" -> warp opens and nothing happens
I copy the auth token -> it says there's an error

I've turned off cloudflare and my coworker can access fine with using just his email log in.

### To reproduce

Try to sign in with a github account

### Expected behavior

I want to be able to sign in.

### Operating system

MacOS

### Operating system and version

14.3.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

latest

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

never

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by HilSny** [comment]
![Screenshot 2024-03-14 at 10 50 04 AM](https://github.com/warpdotdev/Warp/assets/16581033/f7d79102-240c-4c68-8720-320aa9216f55)

**Comment by HilSny** [comment]
It started working so closing the issue

**Comment by TeleDark** [comment]
i have this problem too
