### ISSUE TITLE
Debian package list ignored

### ISSUE THREAD

**Issue by Mariyo** [warpdotdev/Warp#4564]
### Describe the bug

When updating packages on Debian 12, warp deb package list is ignored.

### To reproduce

`sudo apt update`

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/1678254/dab0956b-83cf-47c8-8144-ec2ccaab8101)

### Operating system

Linux

### Operating system and version

Debian 12

### Shell Version

GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.03.12.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by vorporeal** [comment]
I think this is working as intended.

This AskUbuntu post explains the meaning of `Hit`, `Ign`, and `Get`: https://askubuntu.com/a/294532

Basically, what's happening here is that we did something on our end that updated the timestamp of the repository metadata but _didn't_ update the contents.  `apt` notices that the timestamp has changed, so downloads a metadata file, and then finds that the index is the same, so "ignores" the fact that the timestamp is different.

`v0.2024.03.12.08.02.stable_01` is the latest stable version, so updates appear to be working correctly.

We can see about adjusting our release workflows such that the file timestamps aren't updated if the contents are unchanged, but I don't think there's actually anything _wrong_ here.
