### ISSUE TITLE
Selecting text interferes with clipboard

### ISSUE THREAD

**Issue by kinglozzer** [warpdotdev/Warp#4566]
### Describe the bug

When I highlight text with the mouse, it immediately overrides whatever is in the clipboard (both in Warp and if I paste elsewhere). In the video below, I’m not touching the keyboard at all, just using the mouse:

https://github.com/warpdotdev/Warp/assets/1655548/4cde1e32-c591-4c73-9f30-97b1ca4ee2dc

### To reproduce

- Check what’s in your clipboard
- Highlight some text in Warp
- Check what’s in your clipboard again

### Expected behavior

Only adjust clipboard contents when explicitly copying/pasting

### Operating system

MacOS

### Operating system and version

Sonoma 14.2.1 (23C71)

### Current Warp version

v0.2024.03.12.08.02.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

13/03/2024

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by kinglozzer** [comment]
Well that’s embarrassing, copy on select is enabled. Is it possible that an update changed the value of this setting? I’ve been using Warp for months and never noticed this behaviour!

**Comment by nicchristeller** [comment]
It was definitely turned on by the most recent update, I went through the same thing as you.
