### ISSUE TITLE
Macos Popup

### ISSUE THREAD

**Issue by gu5e** [warpdotdev/Warp#4569]
### Describe the bug

when you are in for example neovim and hold down `k` to go up, the macos popup with additional characters popup

### To reproduce

1. lauch for example neovim (nvim)
2. find a file
3. make sure you are in normal mode
4. hold down either `h`, `j`, `k`, `l`

### Expected behavior

the popup should not pop up

### Screenshots

![Screenshot 2024-03-16 at 6 37 19 PM](https://github.com/warpdotdev/Warp/assets/162893147/27f5c4c0-f1ad-4720-8afd-1055390fcd5a)

### Operating system

MacOS

### Operating system and version

Sonoma 14.4

### Shell Version

zsh 5.9 (arm-apple-darwin23.0.0)

### Current Warp version

v0.2024.03.12.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @gu5e thanks for submitting. This may be a setting in macOS causing the behavior, you should be able to run `defaults write -g ApplePressAndHoldEnabled -bool false` to disable that functionality in macOS. Are you using a non-ABC input method by any chance?

**Comment by gu5e** [comment]
yeah, the thing is: i often use that feature (because i use multiple human languages), so i dont wanna disable that across everything
