### ISSUE TITLE
SSH: Some commands does not work "Command not found"

### ISSUE THREAD

**Issue by foadyousefi** [warpdotdev/Warp#459]
### Describe the bug

```shell
While I'm logged into a remote server via `ssh` some commands are not working. This happens especially with some custom commands.
For example, `ll` is an alias for `ls -l` which is way easier to type (I'm a bit lazy).
Or `cv api ....` (this is CLI commands for CiviCRM). 
All of these commands are working with `iterm 2` which shares the same `zsh` shell.
```

### To Reproduce

Steps to reproduce:
1. ssh into some remote servers
2. Try some CLI commands (for ex: `ll`)
3. Try the same commands in `iterm`

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
@foadyousefi 
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
