### ISSUE TITLE
Mouse support, sixel support, and a couple more questions.

### ISSUE THREAD

**Issue by ManuGraiph** [warpdotdev/Warp#4593]
### Describe the bug

Hi, i completely apologize in advance cause i know this is not strictly speaking a 'bug report' but i can't seem to find a section for support questions and after a couple days googling and checking docs i haven't been able to find some good answers for these topics.

I have a couple questions, i just moved to warp a couple days ago but there is some stuff i haven't been able to figure out or it's not working as expected.

1. I'm having some trouble in some cli apps with mouse support (weechat), where the mouse clicks don't seem to work, is there some special mouse option we should activate to get full/normal mouse support or similar in warp?
2. Does warp terminal have any kind of sixel / kitty image / equivalent protocol support to show images?
3. Is there any way to open a warp terminal with a title and an specific process? Many terminals do it as `<term> - T "title" -e "proc"` but i haven't been able to find an equivalent here.
4. I'm having some issues in zsh to get my pl10k prompt working correctly. If i set the prompt to the warp-default, it doesn't load my prompt unless i manually do `exec zsh`. After that, it loads correctly but showing only the first line (i'm using a lean theme). I personally don't mind this format, actually, i like it more than the regular, but it's still not how it should work. Now, if instead of the original prompt i use the PS1, it displays the prompt correctly, but the input text area is below the pl10k lines. I added a ss to show both cases below.
![image](https://github.com/warpdotdev/Warp/assets/93348782/c02ceca2-aa0b-441e-bd30-231e9198e778)
5. And a final question, it's possible to hide the tabs in the top bar somehow? I'm planning to use warp as my default terminal in an i3 env in a tile layout, so i don't really need tabs on each window cause every term window will only have one tab.

I apologize again for tossing questions in the bug report section!.
Thanks in advance!

### Operating system

Linux

### Operating system and version

Arch 6.8.1

### Shell Version

zsh 5.9

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @ManuGraiph thanks for submitting, hopefully i can help with some of these questions below:

> 1. I'm having some trouble in some cli apps with mouse support (weechat), where the mouse clicks don't seem to work, is there some special mouse option we should activate to get full/normal mouse support or similar in warp? 

It may help to enable mouse and scroll reporting both in Warp settings and in the alt-screen cli app you're using. https://docs.warp.dev/features/full-screen-apps#mouse-and-scroll-reporting

> 2. Does warp terminal have any kind of sixel / kitty image / equivalent protocol support to show images?

Not yet, but we are tracking it here https://github.com/warpdotdev/Warp/issues/26

> 3. Is there any way to open a warp terminal with a title and an specific process? Many terminals do it as `<term> - T "title" -e "proc"` but i haven't been able to find an equivalent here.

Yes, the best way would be through a launch configuration which allows you to open windows/tabs/panes and name the tab along with running a command. https://docs.warp.dev/features/sessions/launch-configurations

> 4. I'm having some issues in zsh to get my p10k prompt working correctly. If i set the prompt to the warp-default, it doesn't load my prompt unless i manually do `exec zsh`. After that, it loads correctly but showing only the first line (i'm using a lean theme). I personally don't mind this format, actually, i like it more than the regular, but it's still not how it should work. Now, if instead of the original prompt i use the PS1, it displays the prompt correctly, but the input text area is below the pl10k lines. I added a ss to show both cases below.

We're actively working on the prompt in the same line as the input cursor and tracking it here https://github.com/warpdotdev/Warp/issues/2304

> 5. And a final question, it's possible to hide the tabs in the top bar somehow? I'm planning to use warp as my default terminal in an i3 env in a tile layout, so i don't really need tabs on each window cause every term window will only have one tab.

not an option yet, but there is a request for "zen mode" with no tab bar we are tracking here #1009 

Closing as other issues are tracking these points above, but please let us know if any problems with the mouse and scroll reporting or launch configuration features.

**Comment by ManuGraiph** [comment]
Thanks a REAL LOT for your help Danny, i'm looking forward to make warp my default term. Great project!!!
