### ISSUE TITLE
ARM64 support?

### ISSUE THREAD

**Issue by Firstoften** [warpdotdev/Warp#4594]
### Describe the solution you'd like?

Please add ARM64 CPU support?

### Is your feature request related to a problem? Please describe.

I'm currently using Warp terminal on my MacOS, but sometimes I have to do somethings on Kali Linux VM. I'm using ARM64 based Kali (cuz it's faster for Mac) but Warp for linux doesn't support ARM64 thus can't open it.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by mariusseitan** [comment]
> Hey @Firstoften, thanks for filing. We're actively working on arm support and hope to have it available within the next week or two.

That's great news!
