### ISSUE TITLE
Remove/Delete account

### ISSUE THREAD

**Issue by rtalexk** [warpdotdev/Warp#4595]
### Describe the solution you'd like?

An option to delete my account.

### Additional context

I gave it a try to Warp but I didn't like it, it is too much for what I need from a terminal. Now I just want to delete my account, but there's no option in the Settings > Account section, and I couldn't find a way to do it from the website.

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Closing as resolved since the feature exists, but let us know of any issues with it.

**Comment by threddast** [comment]
would be nice to have the option in your website as well, without having to re-install warp just to delete the account
