### ISSUE TITLE
does not support CJK for visual history

### ISSUE THREAD

**Issue by watura** [warpdotdev/Warp#460]
### Describe the bug

```shell
visual history could not list history which contains CJK characters.

Also block has broken when pwd contains cjk chars
```

### To Reproduce

1. mkdir 日本語Japanese
2. show history ← blank listed
3. cd 日本語Japanese
4. ctrl-l ← blocks broken

### Expected behaviour

```shell
show history including CJK text
```

### Screenshots

![Screen Shot 2021-11-25 at 9 01 04](https://user-images.githubusercontent.com/114887/143327296-a5148313-abc9-40ae-9fea-39bc4249f73d.png)

![Screen Shot 2021-11-25 at 9 07 54](https://user-images.githubusercontent.com/114887/143327756-33f95682-f99a-4f8c-8f5a-fc167394c8ec.png)

### Operating System

MacOS

### OS Version

v0.2021.11.16.20.05.stable_01

**Comment by elviskahoro** [comment]
This was fixed. Apologies for the delay!
