### ISSUE TITLE
Make Prompt block always the active for text entry or pasting

### ISSUE THREAD

**Issue by SilentGlasses** [warpdotdev/Warp#4609]
### Describe the solution you'd like?

Currently, if I mistakenly click on any block other than the one the prompt is on, I cannot do anything really (pasting or typing) unless I manually click back into the prompt block.

The prompt block should always be active and ready for me to input text regardless of how if typing or pasting.

### Is your feature request related to a problem? Please describe.

It's frustrating when you want to type or paste in Warp and you either mistakenly selected a different block, middle clicked on the wrong part of the screen or anything related the the prompt block not being actively/manually selected.

Please let me know if you need more information.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hey @SilentGlasses I think this may have been released today, Update Warp and let us know if you're seeing different behavior. Even if block or text is selected, any paste or typing should automatically focus the input editor and paste/enter the text.

**Comment by SilentGlasses** [comment]
Just got the update, typing and pasting works as expected.

**Comment by lordcris** [comment]
typing and pasting with the keyboard ( ctrl + shift + v ) works.
pasting with the middle click, after clicking on another block doesn't. I have to left click the bottom section first to gain focus.

**Comment by dannyneira** [comment]
@lordcris i believe we're also working on that functionality to make it more in line with traditional terminals, for now you can try using the keyboard shortcut workaround as that should automatically focus the input when pasting.

**Comment by SilentGlasses** [comment]
> typing and pasting with the keyboard ( ctrl + shift + v ) works. pasting with the middle click, after clicking on another block doesn't. I have to left click the bottom section first to gain focus.

Did you install the latest update? Maybe restart Warp?

It works fine for me after the last update.

**Comment by lordcris** [comment]
> @lordcris
> 
> > typing and pasting with the keyboard ( ctrl + shift + v ) works. pasting with the middle click, after clicking on another block doesn't. I have to left click the bottom section first to gain focus.
> 
> Did you install the latest update? Maybe restart Warp?
> 
> It works fine for me after the last update.

I have v0.2024.03.19.08.01.stable_01 installed.
my system is:

```
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.3
Release:	21.3
Codename:	virginia
```

when I select a text from a block, the input loses focus and I can't get it back without left clicking. The middle click does nothing.
Using the keyboard works.

**Comment by dannyneira** [comment]
@lordcris we're tracking middle click paste issues on this thread. https://github.com/warpdotdev/Warp/issues/4329 support was released, but for some users you still need to click on the input before middle-click paste.
