### ISSUE TITLE
Moved to #579: Command to iterate over last arguments of historical commands

### ISSUE THREAD

**Issue by meredian** [warpdotdev/Warp#461]
### Describe the solution you'd like?

I liked experience from iTerm:
Use (on mac) `Option + .` to loop through last argument from historical commands & copy them to command line. On each invocation it goes deeper into history & overwrites previously injected values.

Very handy for running various commands on same file or quickly iterate through historically used files (most often they're passed as last argument)

#### Examples of behaviour:

```
git diff some-file
git diff some-other-file
pwd
git add [Option + .] pwd
        [Option + .] some-other-file
        [Option + .] some-file
```

### Is your feature request related to a problem? Please describe.

Running various commands over same file is an often pattern - saves you from memorising exact name, especially if you touch multiple files concurrently.

**Comment by elviskahoro** [comment]
@alokedesai

**Comment by elviskahoro** [comment]
A schema to reference another block's:
inputted command
output

Sourced from Discord: (General Channel - 09/03/2021)
"It'd also be super cool to be able to reference executed blocks (either the command to be run live again or using existing output) in other blocks/commands and have visual cues while doing so."

Emphasis on visual cues!

**Comment by elviskahoro** [comment]
"When copying both input and output of a command, shouldn’t this copy the working directory and whatever else is displayed on that line too? To give context for the user receiving the copied text" - from discord
