### ISSUE TITLE
Window's size can be reduced to zero!

### ISSUE THREAD

**Issue by aminya** [warpdotdev/Warp#4610]
### Describe the bug

The terminal size can be reduced to zero by mistake making it impossible to use or recover from.		

### To reproduce

Drag the edge of the terminal to make it smaller

### Expected behavior

There should be a minimum size that the terminal accepts before the buttons become invisible

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/16418197/fbfa32d2-099e-430a-a497-4aa938c907a7)

### Operating system

Linux

### Operating system and version

KDE Neon 6

### Shell Version

5.1.16(1)

### Current Warp version

v0.2024.03.12.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for letting us know, We should look into that. If you happen to get stuck in that state, close Warp and run the following from another terminal, it should reset the local Session restoration DB and reset the window size. Run `rm "${XDG_STATE_HOME:-$HOME/.local/state}/warp-terminal/warp.sqlite"`

We'll post updates in this thread.

**Comment by dannyneira** [comment]
@aminya We merged a fix to enforce minimum size to the Warp window which should help with the lost window issue. It should be released in the coming week.

**Comment by aminya** [comment]
Thanks for the update! I can confirm that the issue is fixed in today's release.
