### ISSUE TITLE
Praise

### ISSUE THREAD

**Issue by guyguy2** [warpdotdev/Warp#4616]
### Describe the solution you'd like?

This is an amazing app. Thanks for creating it. It's one of those things, where you ask yourself, how did no one do this before? How did we live with the (almost) same terminal for 50 years. iterm2 is great, but this is next level modern. Looking forward for Windows version.

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks @guyguy2 We appreciate the feedback and are happy to hear you're enjoying Warp!

Regarding Windows support, we're shooting for that later this year, there is no firm ETA set. Your best bet for updates is to sign in at https://www.warp.dev/windows-terminal and/or subscribe to https://github.com/warpdotdev/Warp/issues/204

**Comment by dannyneira** [comment]
I'll pass this on to the team. We'll be closing as resolved, but please let us know if blockers come up.
