### ISSUE TITLE
Save Workflow crash

### ISSUE THREAD

**Issue by xeniode** [warpdotdev/Warp#4619]
### Describe the bug

When I bring up the prompt to use natural language with Ctrl + `
It will find the command properly, but when I click the button to save workflow, it crashes. I have tried multiple times with different prompts, same result. It always crashes, it is not intermittent. 

### To reproduce

Ctrl + `
Use natural language to create a command (i.e. Compress given folder into tarball)
Click the button to save as workflow

### Expected behavior

Save the workflow and run the command

### Screenshots

![Selection_03-22-2024_001](https://github.com/warpdotdev/Warp/assets/282555/797588e0-cbcf-4316-ab02-61002cd8624e)

### Operating system

Linux

### Operating system and version

Ubuntu 22.04

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.03.19.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @xeniode Thanks for letting us know. I was able to reproduce this issue and will let the team supporting Workflows know.

We'll post any updates on this thread.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Hi Folks, a fix has been released for this issue. Please update Warp to the latest and let us know if it persists.
