### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by hughesjs** [warpdotdev/Warp#4628]
### Describe the solution you'd like?

It's 2024, we shouldn't have to use `xwayland` for a new application. It makes text horribly blurry for a start.

Can we get some native Wayland support please.

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
We're working on it, testing internally and should have an update in the coming week(s) to support native wayland. Thanks for your patience! We'll update this thread.

**Comment by hughesjs** [comment]
> We're working on it, testing internally and should have an update in the coming week(s) to support native wayland. Thanks for your patience! We'll update this thread.

Nice one, can't wait

**Comment by danudey** [comment]
> > We're working on it, testing internally and should have an update in the coming week(s) to support native wayland. Thanks for your patience! We'll update this thread.
> 
> Nice one, can't wait. Would be keen on helping to test if there's an opportunity

You can test it by setting the environment variable `WARP_ENABLE_WAYLAND=1` in your environment before launching warp-terminal. For my configuration, I did the following (on Ubuntu 22.04):

```shell
cp /usr/share/applications/dev.warp.Warp.desktop ~/.local/share/applications
```

Then I made this change to the file:

```patch
--- /usr/share/applications/dev.warp.Warp.desktop	2024-04-03 17:47:06.000000000 -0700
+++ .local/share/applications/dev.warp.Warp.desktop	2024-04-09 10:01:50.160393976 -0700
@@ -7,7 +7,7 @@
 Name=Warp
 GenericName=TerminalEmulator
 
-Exec=warp-terminal %U
+Exec=/usr/bin/env WARP_ENABLE_WAYLAND=1 warp-terminal %U
 StartupWMClass=dev.warp.Warp
 
 Keywords=shell;prompt;command;commandline;cmd;
```

It took a few moments for it to be picked up as the default `warp` in my desktop environment (i.e. launching from the Ubuntu app launcher) but afterwards it launched correctly and is now correctly rendering at the native resolution (as I use Wayland display scaling).

**Comment by alokedesai** [comment]
Hi there, the latest version of Warp (`v0.2024.09.17.08.02.stable_01`) now allows you to opt-in to Wayland support.

You can enable this in `Settings > Features > System`. As always, thanks for your patience here and please file bugs if you're experiencing issues.
