### ISSUE TITLE
[macOS] Drag'n'dropped a random `.md` Markdown file onto Warp – now in infinite crash loop

### ISSUE THREAD

**Issue by oliveratgithub** [warpdotdev/Warp#4637]
### Describe the bug

I accidentally drag'n'dropped a Markdown file onto Warp - it tried to open it, but crashed immediately.
Unfortunately it tries to redo / restore this, and crashes over and over again when I start the App.

### To reproduce

* Prepare a Markdown file in macOS Finder (.md extension). Store it in `~/Downloads/`
* Launch Warp
* Drag'n'drop the `.md`-file from Finder onto the Warp App icon
* Warp crashes…
* Manually start Warp again
* Warp crashes again

### Expected behavior

Warp should not crash when a Markdown file is tried to be opened with it (or it should not accept this file type at all, when it cannot handle it?)

### Screenshots

<img width="372" alt="Screenshot 2024-03-25 at 23 25 34" src="https://github.com/warpdotdev/Warp/assets/280207/c1ee6d98-2f3f-41d9-9d2d-34ac72a3015d">

### Operating system

MacOS

### Operating system and version

macOS 14.4.1 (23E224) Sonoma 

### Shell Version

zsh

### Current Warp version

0.1.0

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

25.03.2024

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @oliveratgithub sorry to hear about this issue, sounds like a serious bug. I know Warp can open MD files, but not sure if you can drag them into the icon that way. As a possible workaround to launch Warp, delete the [session restoration sqlite](https://docs.warp.dev/features/sessions/session-restoration#session-restoration-database) file `rm "$HOME/Library/Application Support/dev.warp.Warp-Stable/warp.sqlite"` This should delete any attempts to reopen that MD file that caused the crash.

Please let me know if that helps, we may also need to run other [commands to reset](https://docs.warp.dev/help/uninstalling-warp#uninstalling-warp) Warp.

**Comment by oliveratgithub** [comment]
> Any chance you would be willing to share the specific markdown file that triggered this? 

Sure, will do. I also realized it may be an odd combination: the markdown file only contains a JSON object. But will share the file I used later, so to hopefully help reproducing it.

**Comment by oliveratgithub** [comment]
@vorporeal please find the file causing the Warp app crash attached:
[table.md](https://github.com/warpdotdev/Warp/files/14792360/table.md)

**Comment by bnavetta** [comment]
Hi @oliveratgithub, thanks for sending us the file! We were able to reproduce the crash, and it should be fixed as of the `v0.2024.04.02.08.02.stable_01` release

**Comment by oliveratgithub** [comment]
Cool thanks!

By the way the it worked flawlessly to reset the "restore window" state using the command you provided 👌
