### ISSUE TITLE
"Starting fish..." for ~5 seconds on new panes

### ISSUE THREAD

**Issue by ElijahLynn** [warpdotdev/Warp#4647]
### Describe the bug

When opening a new pane, hangs for ~5 seconds. 

### To reproduce

Use fish shell, open a new pane

### Expected behavior

Fish loads in under a second

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/1504756/07de7c59-2880-42f0-add5-c5b03c590138)

### Operating system

MacOS

### Operating system and version

14.4.1 (23E224)

### Shell Version

fish, version 3.7.1

### Current Warp version

v0.2024.03.19.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @ElijahLynn this is known issue with some [improvements released](https://github.com/warpdotdev/Warp/issues/1298), but due to the variable fish configurations could still be affecting some users. 

My guess is yo may have a [custom prompt, theme, or fish plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table). We have a list of incompatible tools here: https://docs.warp.dev/help/known-issues#list-of-incompatible-tools
If any are in your config, you can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here <
end
```
If that doesn't help, any chance you could provide a copy of your fish config so that we can try and reproduce this issue?

**Comment by ElijahLynn** [comment]
Thanks for the quick response! I do have a custom prompt, which yeah, I don't use anymore because I use the Warp prompt. I also had FZF enabled, which I get that Warp provides similar functionality, so I just disabled that with your snippet. 

Here is my prompt right now https://github.com/ElijahLynn/dotfiles/blob/master/dot_config/private_fish/config.fish

I'll keep hacking on it and post back with results.

**Comment by ElijahLynn** [comment]
I should add that after "Starting fish..." completes, I get a "Bucket   found in project:", which leads me to believe that is related to the hang:
![image](https://github.com/warpdotdev/Warp/assets/1504756/13d6ef96-b4fa-463a-813e-1a84d7aa52d4)

**Comment by ElijahLynn** [comment]
Okay, once I disabled Homebrew integration https://github.com/ElijahLynn/dotfiles/blob/1d24436af1a01030ab1531cba10bafa1e1cf5e97/dot_config/private_fish/config.fish#L2, I got the error:

```
fish: Unknown command: gcloud
~/.config/fish/functions/search_bucket_in_gcp_project.fish (line 6):
gcloud config set project $project_id > /dev/null 2>&1
```

Which points me to the fact that it was trying to execute one of my custom fish functions, which does indeed lookup buckets. So I think this is directly causing the hang. Not sure why it is trying to execute it though. It doesn't seem to take any amount of time loading a new pane in iTerm2 or a new window in regular Mac terminal.

**Comment by ElijahLynn** [comment]
So, somehow Warp (but not Mac terminal) sources this function, and while sourcing it, appears to execute it too. I bit some gibberish in the function and it appears to be trying to execute it. 

```
fish: Unknown command: dielkjlkjjk
~/.config/fish/functions/search_bucket_in_gcp_project.fish (line 5):
dielkjlkjjk
^~~~~~~~~~^
from sourcing file ~/.config/fish/functions/search_bucket_in_gcp_project.fish
	called on line 1 of file /opt/homebrew/Cellar/fish/3.7.1/share/fish/functions/alias.fish
in command substitution
	called on line 18 of file /opt/homebrew/Cellar/fish/3.7.1/share/fish/functions/alias.fish
in function 'alias'
	called on line 1 of file /var/folders/4r/yskjd_rx7xn0126xnbg8r4340000gp/T/.tmpng2NyR
in command substitution
	called on line 1 of file /var/folders/4r/yskjd_rx7xn0126xnbg8r4340000gp/T/.tmpng2NyR
in command substitution
	called on line 218 of file /var/folders/4r/yskjd_rx7xn0126xnbg8r4340000gp/T/.tmpng2NyR
in function 'warp_bootstrapped'
	called on line 358 of file /var/folders/4r/yskjd_rx7xn0126xnbg8r4340000gp/T/.tmpng2NyR
from sourcing file /var/folders/4r/yskjd_rx7xn0126xnbg8r4340000gp/T/.tmpng2NyR
```

**Comment by ElijahLynn** [comment]
K, I see now. It is because that function is actually executable and:
```
#!/usr/bin/env fish
...
```

I had created it as a script to call from within another function. I will have to re-work that. Odd that Mac terminal didn't do the same thing.
