### ISSUE TITLE
the about page in app client has an incorrect description.

### ISSUE THREAD

**Issue by goriginalxxx** [warpdotdev/Warp#4658]
### Describe the bug

![20240329-144900@2x](https://github.com/warpdotdev/Warp/assets/52132072/a28b5fed-8e9b-4b62-8521-7687e288280b)

### To reproduce

the about page in app client has an incorrect description.

### Operating system

MacOS

### Operating system and version

14.4.1

### Current Warp version

v0.2024.03.26.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for letting us know, looking to update this!
