### ISSUE TITLE
No Warp window on MacOS

### ISSUE THREAD

**Issue by mbssecguy58** [warpdotdev/Warp#4677]
### Describe the bug

I have Warp installed on MacOS 12.7.4 and when I launch the app the window does not appear. I can access it via the menu bar but most features are grayed out. I click the logout button but nothing happens. I installed it on a second Mac and got the same results. I installed it on Fedora Linux and it works fine. I am not able to produce bug reports as 95% of features are grayed out! I searched the docs & FAQ's but didn't find anything that could help.

### To reproduce

I can not produce bug reports as I have no functionality 

### Screenshots

![Screen Shot 2024-04-02 at 12 40 33 PM](https://github.com/warpdotdev/Warp/assets/31019283/b37807d8-4c48-49a1-b40b-5021cd7ba74d)
![Screen Shot 2024-04-02 at 12 40 49 PM](https://github.com/warpdotdev/Warp/assets/31019283/87cc08e9-a193-48b7-8f57-cb9777527786)
![Screen Shot 2024-04-02 at 12 41 02 PM](https://github.com/warpdotdev/Warp/assets/31019283/52f9a5d
![Screen Shot 2024-04-02 at 12 41 15 PM](https://github.com/warpdotdev/Warp/assets/31019283/fd69f871-9c14-46ee-ad9c-5f4f6e2a508a)
b-a785-4177-8ff9-cd833de24b0f)
![Screen Shot 2024-04-02 at 12 41 26 PM](https://github.com/warpdotdev/Warp/assets/31019283/590ca4d1-05ad-44a8-8b52-e06704846a7c)
![Screen Shot 2024-04-02 at 12 41 43 PM](https://github.com/warpdotdev/Warp/assets/31019283/19835eb6-762b-4202-a38c-96725e8cdd2e)

### Operating system

MacOS

### Operating system and version

12.7.4

### Shell Version

zsh

### Current Warp version

0.2024.03.26.08.02.stable.02

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

11-13-2023

### Additional context

I'm using X11 on Fedora

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by mbssecguy58** [comment]
![Screen Shot 2024-04-02 at 12 39 48 PM](https://github.com/warpdotdev/Warp/assets/31019283/0e05a633-5a05-46b1-b49e-2b624735f85c)
![Screen Shot 2024-04-02 at 12 40 18 PM](https://github.com/warpdotdev/Warp/assets/31019283/69a6ba77-830d-4e4b-bca1-f2181e8e7a0f)

**Comment by danielpeng2** [comment]
Hey @mbssecguy58, would you mind sending us the Warp logs from your MacOS machine? You can find the logs at `~/Library/Logs/warp.log`. Hopefully there's something in there that will help us debug.

**Comment by mbssecguy58** [comment]
> Hey @mbssecguy58, would you mind sending us the Warp logs from your MacOS machine? You can find the logs at `~/Library/Logs/warp.log`. Hopefully there's something in there that will help us debug.
[Warp Logs.zip](https://github.com/warpdotdev/Warp/files/14908225/Warp.Logs.zip)

Here are the Warp logs from my MacOS 12 iMac

**Comment by danielpeng2** [comment]
Thanks for sending the logs. Seems like there might be an issue with Metal support on your device. Warp currently requires Metal support to run on MacOS, but unfortunately some machines are old enough that Metal isn't supported. What hardware are you running on?

Apple has [docs](https://support.apple.com/en-us/102894) explaining which devices support Metal and how to check if your device has Metal support.

**Comment by zeleniy** [comment]
I have old iMac 2011 patched with [OpenCore Legacy Patcher](https://dortania.github.io/OpenCore-Legacy-Patcher/) and have next record in logs:
```2025-03-08T08:39:15Z [ERROR] error opening window: could not obtain metal device```
