### ISSUE TITLE
Warp Failed to load Font

### ISSUE THREAD

**Issue by cbs-l** [warpdotdev/Warp#4678]
### Describe the bug

Currently trying to launch Warp via a VMware Workstation on Windows 10:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

Seeing something to do with not loading a font. Tried `sudo apt install fonts-hack` and no luck. Also tried setting env variables and low power mode.

[warp.log](https://github.com/warpdotdev/Warp/files/14841923/warp.log)

### To reproduce

Download and installed warp and then run. See terminal icon but no window.

### Operating system

Linux

### Operating system and version

22.04.4

### Shell Version

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

warp-terminal_0.2024.02.20.08.01.stable.02_amd64.deb

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @cbsluke sorry about this blocker. Can you please run `eglinfo` and let us know the result? It appears no adapters may be available for Warp to use on the VM, can you also make sure that 3D acceleration is enabled on the VM? Also, make sure to install the VMware tools on the guest OS as that may help with the right drivers, etc. 
Finally, which of the env variables did you use and did you use them individually or all at once?

**Comment by vorporeal** [comment]
There appear to be compatibility issues between Warp and the SVGA3D graphics driver for VMWare Workstation.  (The font-related log lines are a red herring.)

We've received a couple reports of this; it's something we're looking into.

**Comment by dannyneira** [comment]
Hey folks, We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/4598 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue.

We'll be closing this as a duplicate.
