### ISSUE TITLE
DUP: Duplicate of #101 - You need a Window menu

### ISSUE THREAD

**Issue by hillegass** [warpdotdev/warp#468]
### Describe the solution you'd like?

```shell
Most Mac applications have a window menu that includes tab stuff.  You need one for the window ("Tile Window to left of screen") and tabs ("Move tab to a new window") and panes ("Close pane" and "Move focus to previous pane")
```

### Is your feature request related to a problem? Please describe.

```shell
I couldn't find the keybinding to move from one to pane to the next. It would usually be discoverable from the menu item. But there isn't a menu item for this. When you add the menu item, you will need a whole menu.  But most Mac apps already have that menu, it is called "Window"
```

### Additional context

<img width="516" alt="Screen Shot 2021-11-30 at 9 59 07 AM" src="https://user-images.githubusercontent.com/188895/144071950-a7cdebf0-5b8e-4af6-a6f1-12d3abfc342d.png">

As an example, here is the Window menu from Safari.

**Comment by elviskahoro** [comment]
We'll merge this into:
- https://github.com/warpdotdev/warp/issues/101
