### ISSUE TITLE
Tilde is wrongly expanded for different user

### ISSUE THREAD

**Issue by Evian-Zhang** [warpdotdev/Warp#4682]
### Describe the bug

My local machine has username "foo", and the remote machine has username "bar". After ssh into the remote machine, the tilde will expanded to `/home/foo` instead of `/home/bar`, while the remote machine does not have a user "foo" at all.

### To reproduce

1. Local machine with username "foo"
2. ssh into a remote machine with username "bar"
3. Type `~/some/existed/path` in the prompt (`~/Documents` for example) and use <kbd>Tab</kbd> to expand it
4. The expanded path is `/home/foo/Documents`, which does not exist on the remote machine

### Operating system

MacOS

### Operating system and version

macOS 14.4.1

### Shell Version

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2024.03.26.08.02.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @Evian-Zhang if possible can you please run `uname` and `echo $HOME` on the remote machine to confirm

**Comment by Evian-Zhang** [comment]
@dannyneira Thank you for your response.

`uname` turns out `Linux` in the remote machine, and local machine is a macOS.

`echo $HOME` turns out `/home/bar` in the remote machine.

Something more:

* After I post this issue, Warp has published new versions. I updated to the newest version and the problem remains.
* Only tilde occurred in the command position has this problem. i.e., in an empty prompt, type `~/Documents` and press <kbd>Tab</kbd> will reproduce this problem. If the tilde is in the argument position, i.e. type `cd ~/Documents` and the expansion is correct.

**Comment by dannyneira** [comment]
Hm, if the $HOME is not what it should be on the remote machine, check your remote rc/profile files and see if there is an `export` in there or something overriding the home directory path or something replacing the tilde completion.

**Comment by Evian-Zhang** [comment]
@dannyneira The username in remote machine is bar, and the $HOME is correct I think?

**Comment by Evian-Zhang** [comment]
I have upgraded to the newest release v0.2024.04.09.08.01.stable_01, while the problem remains.

**Comment by dannyneira** [comment]
Sorry to hear about this, if you run whoami on both local and remote do you get the same results?

**Comment by Evian-Zhang** [comment]
`whoami` gives the correct result:

* Remote machine with username bar: `whoami` gives bar
* Local machine with username foo: `whoami` gives foo

**Comment by Evian-Zhang** [comment]
The newest upgrade solved this problem. Thank you for your hardwork:)
