### ISSUE TITLE
Tab autocomplete broken for folders with long names or special characters

### ISSUE THREAD

**Issue by uncapped1599** [warpdotdev/Warp#4689]
### Describe the bug

I want to cd into one of many of my media folders in a directory. When trying tab, it fails to list anything in the directory other than a non-existent "snap" folder. Only way to successfully change directory into a sub folder is to first list all of them and copy the whole folder name verbatim.

### To reproduce

Go to a folder containing multiple folders with special characters such as spaces or curly braces. Try TAB to autocomplete folders after 'cd'.

### Expected behavior

TAB after cd command should list all directories in the folder. Instead lists nothing but a made up snap directory.

### Screenshots

<img width="1077" alt="Screenshot 2024-04-04 at 09 19 05" src="https://github.com/warpdotdev/Warp/assets/126204291/f8fc30c4-fbb7-4d26-9613-3b3ac4c07e07">

### Operating system

Linux

### Operating system and version

Ubuntu 22.04.2

### Shell Version

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.03.26.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @uncapped1599 sorry about this, Its not clear which of the characters may be breaking the completions, I suspect it may be the curly brackets `{}`. The workaround for now would be to run a subshell like `bash` to fallback to shell completions when working in those folders.

**Comment by uncapped1599** [comment]
Can confirm it's fixed. Thanks for all your hard work.
