### ISSUE TITLE
Change  cursor type (mouse pointer) according to the context

### ISSUE THREAD

**Issue by drpayyne** [warpdotdev/Warp#47]
**Describe the bug**
Hovering over URLs should make the cursor a pointer.

**To Reproduce**
1. Hover over a URL

**Expected behavior**
Hovering over URLs should make the cursor a pointer.

**Desktop (please complete the following information):**
 - OS Version: macOS 10.15.7

**Additional context**

Maybe expand the scope of this ticket to change to cursor according to the context.

- clickable -> pointer
- command is running -> loading cursor when hovered over block maybe?
- any other context you can think of :)

**Comment by zachlloyd** [comment]
We'll get this queued up - should be a straightforward fix.  Thanks for reporting.

**Comment by elviskahoro** [comment]
Came out in a recent release!
