### ISSUE TITLE
Can't sign up

### ISSUE THREAD

**Issue by marcgarcia88** [warpdotdev/Warp#4705]
### Describe the bug

I've deleted my account to use a Github account, but now I  can't either sign up with GitHub or my email account...

### To reproduce

Go to sign up.

### Operating system

MacOS

### Operating system and version

Sonoma 

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @marcgarcia88 if you recently deleted the account, you'll need to wait for the deletion job to run before you can signup again with the same email. https://docs.warp.dev/getting-started/privacy#delete-your-data

Please wait 24 hours and let us know if the issue persists.

**Comment by dannyneira** [comment]
Are you still seeing the same issue after waiting to signup again?

**Comment by dannyneira** [comment]
@marcgarcia88 any luck with the above info? Were you able to signup after waiting the 24 hours post-deletion?

**Comment by marcgarcia88** [comment]
> @marcgarcia88 any luck with the above info? Were you able to signup after waiting the 24 hours post-deletion?

Yeap!! Now it's all right! Thanks for your help :)

**Comment by dannyneira** [comment]
Awesome! Closing as resolved, but please let us know any login related issues.
