### ISSUE TITLE
git autocomplete only works on first arg

### ISSUE THREAD

**Issue by nipunn1313** [warpdotdev/Warp#471]
### Describe the bug

```shell
When I use `git branch -D branch1 branch2 branch3` - autocomplete only works on the first arg
```

### To Reproduce

Enter git repo
git branch -D branch1 br[tab]

### Expected behaviour

```shell
Expect to get autocomplete on subsequent args
```

### Operating System

MacOS

**Comment by nipunn1313** [comment]
I think this works fine in other terminals using standard autocomplete stuff - so this feels like a regression of warp compared to other terminals.

Maybe broadly - I expect autocomplete to work at least as well in Warp as other terminals. When warp has extra smart completes, that's great, but when not, falling back to whatever the normal terminal does would be great.

Another example command is git show

`git show a[tab] a[tab]`

**Comment by neelmehta247** [comment]
For me `git branch -d a[tab]` is also broken. Even the first argument won't autocomplete :/

**Comment by elviskahoro** [comment]
This should be fixed now! Apologies for the delay
