### ISSUE TITLE
Env variables not loaded when starting warp terminal

### ISSUE THREAD

**Issue by madisonmay** [warpdotdev/Warp#4722]
### Describe the bug

I've made sure to point to the correct shell (bash).  After running bash manually and creating a subshell, all expected env variables are available.

### To reproduce

1. Open warp terminal
2. Run `env | grep {SOME_ENV_VAR}`
3. Observe no environment variables from ~/.bashrc are present
4. Start a subshell by running `bash`
5. Confirm all expected environment variables are present

Sourcing ~/.bashrc would also populate env vars

### Expected behavior

Environment variables set in ~/.bashrc should be available when starting warp terminal.

### Operating system

Linux

### Operating system and version

Ubuntu 22.04

### Shell Version

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.04.02.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

X11

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @madisonmay sorry about this. Check if your Settings > Features > Startup shell for new sessions is set to the same as the result of `echo $SHELL`. If so, then any `export` statements in your ~/.bashrc file should automatically load on startup of the new shell.

If this isn't the case, please provide a video/screenshots/copy of your `echo $SHELL`, Warp settings for new shells, and you ~/.bashrc file so that we can reproduce the issue on our end.

**Comment by madisonmay** [comment]
@dannyneira thanks for the tips.

```
 m@127  ~  echo $SHELL
/usr/bin/bash
```

![image](https://github.com/warpdotdev/Warp/assets/2645393/cfac6633-ed3f-453e-b42a-1fd4e75bf74c)

w![image](https://github.com/warpdotdev/Warp/assets/2645393/7b80f433-416b-4c4b-8dc5-467f138feb42)

I tried commenting everything in my ~/.bashrc sans a single text export statement, in case this was an interaction between oh-my-bash or something -- but didn't see the export statement returned.

So my bashrc is currently only:

```
export TEST="hello"
```

**Comment by dannyneira** [comment]
Thanks for this, even though we have the same setup I still can't reproduce this issue. Are you opening a new session(window/tab/pane) once you set the default shell to bash? If so, can you try running `chsh -s $(which bash)` to set bash as default system shell, then set the Warp startup shell settings to default. Also, check your `~/.profile` and `~/.bash_profile` for anything that may be affecting Warp (i.e. plugins, on-my-bash, etc.). Finally, you can check if the issue persists on a subshell, run `bash` then run the `env | grep TEST` again in the subshell to see if you can see the result, if not then it may be something in your profile as I mentioned causing this, not in Warp.

**Comment by madisonmay** [comment]
Hi there,

I ran the below in one tab:
```
chsh -s $(which bash)
```
Then edited my settings to use "default" shell, then opened a new tab within warp.  The new tab is still missing my env variables.

The issue does not persist in subshells -- as soon as I source ~/.bashrc or run `bash` my environment variables are loaded as expected.

Could possibly be related to regolith / i3?  A friend of mine running a similar setup is experiencing the same issue.

**Comment by madisonmay** [comment]
~/.bash_profile:
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

export PATH="$HOME/.poetry/bin:$PATH"
. "$HOME/.cargo/env"
```

~/.profile
```
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

export PATH="$HOME/.poetry/bin:$PATH"

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"
. "$HOME/.cargo/env"
```

**Comment by dannyneira** [comment]
It could be if the same is happening across both you and your friend that the desktop manager may be keeping the sessions active and not allowing Warp to update the env variables, but I'm not 100% certain that interaction could happen with a desktop/window manager and Warp.

I didn't notice anything out of the norm in your profiles, but it wouldn't hurt to wrap the python env eval in the conditional in the middle of your `~/.bash_profile` to disable that plugin just for Warp as below:

```sh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
  if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
  fi
fi
```

**Comment by madisonmay** [comment]
Here is the result of running `env` prior to starting a subshell.

```
SHELL=/usr/bin/bash
SESSION_MANAGER=local/127.0.0.1localhostlocalhost.localdomainlocalhost4localhost4.loca:@/tmp/.ICE-unix/3244,unix/127.0.0.1localhostlocalhost.localdomainlocalhost4localhost4.loca:/tmp/.ICE-unix/3244
QT_ACCESSIBILITY=1
COLORTERM=truecolor
PYENV_SHELL=bash
XDG_CONFIG_DIRS=/etc/xdg/xdg-regolith:/etc/xdg
XDG_MENU_PREFIX=gnome-flashback-
TERM_PROGRAM_VERSION=v0.2024.04.02.08.02.stable_01
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GTK_IM_MODULE=ibus
I3SOCK=/run/user/1000/i3/ipc-socket.3560
MANDATORY_PATH=/usr/share/gconf/regolith.mandatory.path
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
WARP_USE_SSH_WRAPPER=1
XMODIFIERS=@im=ibus
DESKTOP_SESSION=regolith
GTK_MODULES=gail:atk-bridge
PWD=/home/m
LOGNAME=m
XDG_SESSION_DESKTOP=regolith
XDG_SESSION_TYPE=x11
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
SYSTEMD_EXEC_PID=3168
XAUTHORITY=/run/user/1000/gdm/Xauthority
WINDOWPATH=2
HOME=/home/m
USERNAME=m
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=Regolith:GNOME-Flashback:GNOME
WARP_HONOR_PS1=0
WARP_COMBINED_PROMPT_COMMAND_GRID=0
SSH_SOCKET_DIR=~/.ssh
VOLTA_HOME=/home/m/.volta
XDG_SESSION_CLASS=user
TERM=xterm-256color
DEFAULTS_PATH=/usr/share/gconf/regolith.default.path
USER=m
DISPLAY=:1
SHLVL=2
QT_IM_MODULE=ibus
DESKTOP_AUTOSTART_ID=108fd91676e9b8fe78171277241085461000000032440016
XDG_RUNTIME_DIR=/run/user/1000
COMPIZ_CONFIG_PROFILE=gnome-flashback
PYENV_ROOT=/home/m/.pyenv
WARP_IS_LOCAL_SHELL_SESSION=1
XDG_DATA_DIRS=/usr/share/regolith:/usr/share/gnome:/home/m/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
PATH=/home/m/.poetry/bin:/home/m/.pyenv/shims:/home/m/.pyenv/bin:/home/m/.cargo/bin:/home/m/.local/bin:/home/m/.poetry/bin:/home/m/.volta/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/m/.dotnet/tools:/home/m/.dotnet/tools
GDMSESSION=regolith
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
GIO_LAUNCHED_DESKTOP_FILE_PID=10217
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/dev.warp.Warp.desktop
OLDPWD=/home/m
TERM_PROGRAM=WarpTerminal
_=/usr/bin/env
```

It seems like my .profile and .bash_profile files may be loaded, just not my ~/.bashrc

**Comment by dannyneira** [comment]
Hm, your `HOME` is set to `/home/m`, if the ~/.bashrc file isn't there that env var may be overriding where Warp should be looking for that file to load it. You could also add a `source <path_to>/.bashrc` in your profiles to have it load explicitly and see if that helps.

**Comment by madisonmay** [comment]
Sourcing the .bashrc from the .bash_profile did the trick.  Thank you for your help!  

Still a bit odd that it didn't work by default -- is there shortcut logic to not load ~/.bashrc if ~/.bash_profile is available, or anything of that sort?

**Comment by madisonmay** [comment]
I'll go ahead and close -- thanks again for the help!  Do let me know if there are any updates that would remove the need for the workaround.

**Comment by HadiAlizade77** [comment]
Guys just copy the content of ~/.bashrc to ~/.bash_profile 
i had this issue with nvm , node and npm ...
good luck
