### ISSUE TITLE
ssh autocompletion does not work with parameters

### ISSUE THREAD

**Issue by pmenuettang** [warpdotdev/Warp#474]
### Describe the bug

```shell
When you write a ssh command, adding, for instance, parameter "-i", and hit tab, nothing happens. 
Even when you try to complete with "~/.ssh" (ssh -i ~/.ssh) and hit tab.
```

### To Reproduce

Steps to reproduce:
1. Go into the 'input editor'
2. Start typing 'ssh -i ~/.ssh/'
3. Hit 'tab'
4. Nothing happens

### Expected behaviour

```shell
Warp should autocomplete with files found in folder ~/.ssh/.
```

### Operating System

MacOS

### OS Version

12.0.1

**Comment by elviskahoro** [comment]
@pmenuettang 
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
