### ISSUE TITLE
No prompt when opening new shell with p10k 

### ISSUE THREAD

**Issue by jpwallace22** [warpdotdev/Warp#4752]
### Describe the bug

I have configured warp to have a prompt I enjoy using p10k. However, if open a subshell (ie: `chezmoi cd` for [chezmoi](https://www.chezmoi.io/reference/commands/cd/)). I lose my prompt, autocomplete, and pretty much everything other than basic terminal behavior. This may be deeper than just losing the prompt, but as I know the prompt worked in the subshell prior to installing p10k (it was a custom prompt as well), this bug report is strictly scoped for that bug. 

### To reproduce

1. [install p10k](https://www.warp.dev/blog/how-to-set-up-powerlevel10k-on-warp)
2. [install chezmoi ](https://www.chezmoi.io/install/)
3. run `chezmoi cd` to open a new shell
4. see that no prompt is visible

### Expected behavior

Mu custom prompt persists for the local subshell as well

## Before running the subshell

<img width="860" alt="Screenshot 2024-04-13 at 1 00 32 PM" src="https://github.com/warpdotdev/Warp/assets/93415734/d4d4a210-e69b-4147-885d-88147a8ed302">

## After running it

<img width="865" alt="Screenshot 2024-04-13 at 1 00 47 PM" src="https://github.com/warpdotdev/Warp/assets/93415734/1824c8ab-7571-49e8-af5b-5c38e6e9d8e5">

### This doesnt have the fonts installed and is not configured, so ignore how ugly it is, but it DOES work 
<img width="866" alt="Screenshot 2024-04-13 at 1 01 52 PM" src="https://github.com/warpdotdev/Warp/assets/93415734/35e85f6a-7961-426d-b142-563c143d8d99">

### Operating system

MacOS

### Operating system and version

Ventura Version 13.5 

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2024.03.26.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @jpwallace22 As a possible fix for this, if chezmoi enables shell based subshell, you can add `chezmoi` to Settings > Subshells menu. Then once you're in a chezmoi session you can Warpify it and enable Warp features. https://docs.warp.dev/features/subshells

https://github.com/warpdotdev/Warp/assets/16809145/faf49e35-e920-430c-9469-adb077e15e5a

Please let us know if this helped with your issue.
