### ISSUE TITLE
Allow key binding to jump around splits

### ISSUE THREAD

**Issue by pencilcheck** [warpdotdev/Warp#4764]
### Describe the solution you'd like?

I setup tmux to jump my cursor focus around the splits with ^h or ^l etc. I found something that seems to be close but it doesn't do so, it jump into the left panel which I have no use of (warp drive). I want to be able to switch focus between splits within a tab.

Ideally I can continue to switch tabs as well, e.g. if ^l and there is a tab on the right of existing tab, it will switch focus to that tab and pick a split to focus on.

### Is your feature request related to a problem? Please describe.

Frustrated to have to use mouse/touchpad to switch split focus

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
hi @pencilcheck thanks for submitting, you can focus on Tabs with `SHIFT-CMD-{` / `SHIFT-CMD-}` on Mac and `CTRL-PGUP` / `CTRL-PGDN` on Linux. 

Then once in a Tab, you can focus the Split Panes in Warp with `OPT-CMD-ARROW` on Mac and `CTRL-ALT-ARROW` on Linux. Please see the demo below and our docs for more.
https://docs.warp.dev/features/windows/tabs
https://docs.warp.dev/features/windows/split-panes

https://github.com/warpdotdev/Warp/assets/16809145/6084bfc6-58f5-4ee5-a71a-c40c0a03494d

These keyboard shortcuts can be configured in the Settings > Keyboard Shortcuts. Hope this helps with your use case!

Closing as there is already a way to switch tabs and split panes with keyboard.

**Comment by pencilcheck** [comment]
@dannyneira I noticed the switching pane stops working if I set the key binding to control + key combination like (⌃k) and the pane is focused in command line mode it doesn't switch, it adds a new line to the command line instead.
