### ISSUE TITLE
Warp in IDE

### ISSUE THREAD

**Issue by emilkor1** [warpdotdev/Warp#4769]
### Describe the solution you'd like?

Adding "warp-terminal" as the terminal in e.g. Intellij opens a new warp window.

Would be nice to have the terminal integrated in the IDE.

If it already is possible, let me know.

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by emilkor1** [comment]
Duplicate issue.

**Comment by dannyneira** [comment]
Duplicate of #472
