### ISSUE TITLE
Multiple execution mode for synchronous execution of the same commands on multiple terminals

### ISSUE THREAD

**Issue by whitekeep** [warpdotdev/Warp#4775]
### Describe the solution you'd like?

I need functionality that will allow me to split the terminal and run commands on both terminals at the same time.

### Is your feature request related to a problem? Please describe.

When I need to set up a Consul cluster or something else, I'm forced to clone a VM or run the same commands multiple times. This is very inconvenient and time consuming

### Additional context

I found the same function in MobaXTerm (https://mobaxterm.mobatek.net/documentation.html#1_3)
![image](https://github.com/warpdotdev/Warp/assets/60810530/42a3c737-e834-4dd5-b1eb-dea3f0587690)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Howdy @whitekeep Warp has a feature called Synchronized Inputs which should meet this use case.
https://docs.warp.dev/features/entry/synchronized-inputs

Closing as this feature exists.
