### ISSUE TITLE
Warp terminal does not apply system font scaling factor, custom cursor

### ISSUE THREAD

**Issue by sc1061** [warpdotdev/Warp#4779]
### Describe the bug

After an upgradation, all text getting smaller and does not apply custom cursor.

### To reproduce

Upgrade warp to v0.2024.04.16.08.02.stable_00

### Screenshots

![Screenshot from 2024-04-19 10-39-35](https://github.com/warpdotdev/Warp/assets/137926862/58db91db-b7a4-4d24-93b7-e91b2b922a0b)
![Screenshot from 2024-04-19 10-41-23](https://github.com/warpdotdev/Warp/assets/137926862/1d0cd04b-5509-4b8c-a150-7bb2dc8b9920)
![Screenshot from 2024-04-19 11-02-01](https://github.com/warpdotdev/Warp/assets/137926862/23707e7a-8f91-44a9-80b9-49f063bdbfa0)
### Operating system

Linux

### Operating system and version

fedora 39

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by tukusejssirs** [comment]
I have a similar problem. After upgrading Warp to `v0.2024.04.16.08.02.stable_00`, my console font and UI font changed size. I fixed the former by changing (again) the font size in the settings, however, I cannot change the UI font (e.g. in tabs, sidebars).

Note that in the previous Warp version, the UI font size was bigger and I have change the default terminal font size (which seemed to be reset on Warp upgrade). 

![warp](https://github.com/warpdotdev/Warp/assets/5111894/817ead95-a7a6-41d6-88d2-d9ad4c14b299)

**Comment by sc1061** [comment]
Fix in v0.2024.04.23.08.01.stable_03
