### ISSUE TITLE
Issue Templates Fix: Add a checkbox at the top to confirm that the reporter searched existing issues.

### ISSUE THREAD

**Issue by ADTC** [warpdotdev/Warp#4781]
### Describe the solution you'd like?

Add a **_required_** checkbox at **top** of all the three issue templates. It must be the first question in the form:

* [ ] I have [searched existing issues](https://github.com/warpdotdev/Warp/issues?q=is%3Aissue) with relevant keywords and **I didn't find any issue which might be a duplicate**.

Note that the link opens a page listing both open and closed issues, so that the user will search in both together.

### Is your feature request related to a problem? Please describe.

You have close to 4700 issues and only 30 pull requests. So many of these issues are closed as duplicates on a weekly basis. Sometimes people need a reminder to search existing issues first. 😆 

### Additional context

I can open a PR if this is acceptable. It should be very easy to do.

_(Yes, I put my money where my mouth is. I searched if this is already suggested. I couldn't find any.)_

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
True, this could help us with dups and could be helpful, we're also trying to balance making issues easier to create for accessibility and other reasons. We do try and remind folks to search on our [new issue page](https://github.com/warpdotdev/Warp/issues/new/choose) along with a link to the issue search, but this could be another helpful reminder and I've seen similar in other popular repos. I'll run this by the team, thanks!

**Comment by dannyneira** [comment]
Done, checkbox added for reminder.  Thanks for the suggestion! We made it required, but the Warp team will still be checking for dupes and triage issues accordingly.
