### ISSUE TITLE
Switch panes left/right is unintuitive

### ISSUE THREAD

**Issue by Laurensdc** [warpdotdev/Warp#4785]
### Describe the bug

When using the hotkeys for "Switch pane left/right", behaviour is not intuitive.

https://github.com/warpdotdev/Warp/assets/17620692/d2b2504b-ac0b-48a5-8905-5e61f08b29c6

### To reproduce

In a 2x2 terminal split:
- Select top left
- Switch right
- ✅  Top right is selected
- Switch left
- ⛔ Bottom left is selected

=> Expected behaviour: Switch back to the **top** left window, where we are "coming from".

---

- Select bottom right
- Switch left
- ✅ Bottom right is selected
- Switch right
- ⛔ Top right is selected

=> Expected bheaviour: Switch back to the **bottom** right window, where we are "coming from".

### Operating system

MacOS

### Operating system and version

14.4.1

### Current Warp version

v0.2024.03.26.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
In the recent release we improved the function of switching panes back and forth. https://docs.warp.dev/getting-started/changelog#id-2024.04.11-v0.2024.04.09.08.01

please update and let us know if you still see the issue.

**Comment by Laurensdc** [comment]
Awesome! Solved quickly and really well, thanks!!
