### ISSUE TITLE
Error when connecting via SSH

### ISSUE THREAD

**Issue by matrael** [warpdotdev/Warp#4789]
### Operating System

MacOS

### Operating System and Version

14.4.1

### Local Shell Version

3.7.1

### Remote Shell Version

3.7.1

### Warp Version

v0.2024.04.16.08.02.stable_00

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

I am attempting to connect to a remote VPS via SSH. I have the fish shell installed on that VPS as well as the system I'm connecting from. If I change the shell on the remote system to ZSH or Bash, I'm able to connect without any error. 

Screenshot:
[Shared Block](https://app.warp.dev/block/dxun8RQhicxvNrkc9FXpo9)

<img width="1215" alt="Screenshot 2024-04-19 at 15 03 00" src="https://github.com/warpdotdev/Warp/assets/252009/42a6cb32-2d1b-4ca0-92e7-d908376790e5">

### Include shell xtrace output

Here is a copy of the entire block:

```
WARP_DEBUG_MODE=1 ssh jason@************
fish: Unsupported use of '='. In fish, please use 'set hook $(printf "{\"hook\": \"SSH\", \"value\": {\"socket_path\": \"~/.ssh/24580\", \"remote_shell\": \"%s\"}}" "${SHELL##*/}" | command od -An -v -tx1 | command tr -d " \n")'.
hook=$(printf "{\"hook\": \"SSH\", \"value\": {\"socket_path\": \"~/.ssh/24580\", \"remote_shell\": \"%s\"}}" "${SHELL##*/}" | command od -An -v -tx1 | command tr -d " \n")
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Connection to ************ closed.
```

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Warp has an SSH Wrapper that enables features (like the prompt, completions, etc.) on remote machines . This requires the default prompt on the remote machine to be either bash or zsh, not fish.

You can change the remote shell to bash or fish and the SSH wrapper should function.

That being said, we have an request tracking that support here  https://github.com/warpdotdev/Warp/issues/871

Please let us know if this helps.

**Comment by matrael** [comment]
Yeah, I switched the shells back to BASH on the remote servers. Thank you for linking that issue. I'll just keep my fingers crossed that Warp fixes this.
