### ISSUE TITLE
Application exit issue/delay

### ISSUE THREAD

**Issue by Hiiirad** [warpdotdev/Warp#4795]
### Discord username (optional)

Hirad#4700

### Describe the bug

Since the latest update, exiting warp-terminal takes few seconds compare to the older version version which exited immediately.

### To reproduce

Steps to reproduce this issue:

1. open the warp-terminal
2. type `exit` and press `Enter`
3. the terminal freezes for 2-3 seconds with the error attached, and then exits.

This issue not happened on the previous versions.

### Expected behavior

I expect the warp-terminal immediately exited after the exit command, not gives me some errors, then exit after a few seconds.

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/26739670/89316d4f-afc4-42b8-bcdd-5c5efac53ef6)

### Operating system

Linux

### Operating system and version

Fedora 39

### Shell Version

bash 5.2.26

### Current Warp version

v0.2024.04.16.08.02.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Since the last update

### Additional context

After I executed the command requested: `RUST_LOG=wgpu_core=info,wgpu_hal=info MESA_DEBUG=1 EGL_LOG_LEVEL=debug warp-terminal` the warp-terminal crashes and exited. Also, no log generated, so that I can attach it here.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by vorporeal** [comment]
Hi @Hiiirad - thanks for letting us know!

You can find the log file at `~/.local/state/warp-terminal/warp.log` if you run it from a desktop icon; if you run from another terminal, please attach whatever gets printed to the terminal.

**Comment by Hiiirad** [comment]
@vorporeal 
The issue fixed in the warp-terminal version `v0.2024.04.16.08.02.stable_03` 
Thanks for your support :)
