### ISSUE TITLE
Vim visual mode selection is not visible in Warp

### ISSUE THREAD

**Issue by jessrosenfield** [warpdotdev/warp#48]
**Describe the bug**
When using visual mode in vim (v or ctrl-v) in other terminals the selected text is highlighted. In Warp, the selection is not visible.

**To Reproduce**
1. `vim`
2. `i` to enter insert mode, then type in a test sentence (eg: `The quick brown fox jumps over the lazy dog`)
3. `[ESC]` to exist insert mode and then `v` to enter visual mode -- `3b` to go back three words

**Expected behavior**
Expected `the lazy dog` to be visually highlighted, but there is no visual evidence of the selection in visual mode. To confirm that the text was actually selected, `d` to delete the selection.

**Screenshots**
![image](https://user-images.githubusercontent.com/1537213/126654318-143b451a-3775-4d6f-854d-0f6e6c685497.png)

**Desktop (please complete the following information):**
 - OS Version: MacOS Catalina 10.15.6

**Comment by gagata** [comment]
thanks for the report @jessrosenfield! seems like it happens in the 'vanilla' vim, and is not related to any user configs and color schemes. we'll get it fixed! :)

**Comment by gagata** [comment]
hey!  this was fixed with few recent releases, since we fixed the 256 colors!
