### ISSUE TITLE
Shell command search history cuts commands short

### ISSUE THREAD

**Issue by miohtama** [warpdotdev/Warp#4804]
### Describe the bug

The command history search box is too small, cutting commands short and making it difficult to find the right command among the many similar-looking commands.

The native shell search (zsh) does not have this issue, as it will wrap long commands to multiple lines.

### To reproduce

1. Write long commands with changes towards the end of them
2 Open history with CTRL+R
3. The end of the commands are not visible

### Expected behavior

I can effectively search back and differetiate long commands.differentiate

### Screenshots

<img width="782" alt="image" src="https://github.com/warpdotdev/Warp/assets/49922/7bb3d1e3-c1ea-47e0-a9c1-a914bbf82d68">

### Operating system

MacOS

### Operating system and version

14.4.1

### Current Warp version

v0.2024.04.02.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

There is 80% of unused screen real estate.

This can be fixed to a some degree by simply making the search box larger.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @miohtama thanks for letting us know. This is a known limitation with the history search you can expand the panel to see more of the command or if you recently ran the command, you can use `UP` arrow history to see the entire command.


https://github.com/warpdotdev/Warp/assets/16809145/fc73a8eb-1b0e-4c56-93e7-082aca0a7aac

**Comment by miohtama** [comment]
Thank you - this was not obvious from the context!

Works here.

**Comment by LaeekAhmed** [comment]
Can we please have it such that it wraps the command over the next line if the screen size is small?
