### ISSUE TITLE
sudo !! 

### ISSUE THREAD

**Issue by photismos** [warpdotdev/Warp#4818]
### Describe the solution you'd like?

I'd like to use 'sudo !!' please and thank you. Presently, when I attempt the command, I'm informed:

`sudo: !!: command not found` 

:( wha happen here? (apologies if this has already been addressed. I did a cursory search but found nothing.)

### Is your feature request related to a problem? Please describe.

meh

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @photismos Which OS are you on? Do you have the latest version of Warp installed? I was able to use `sudo !!` on my Mac in zsh, and it ran the previous command as sudo.

![CleanShot 2024-04-24 at 16 47 07](https://github.com/warpdotdev/Warp/assets/16809145/57565a59-1f4a-4690-9c2b-5896ebd814d3)

Can you please provide a screenshot or video of the issue to better help us understand what failed?

**Comment by photismos** [comment]
Hi @dannyneira . Thanks for responding. Forgive me for taking a minute to get back to you. I'm presently on OCD-updated 64-bit Garuda 2.6.26-1, Kernel: 6.8.7-zen1-1-zen. WM: kwin, Plasma 6.0.4. I spend a lot of time on this old 790-MT 2nd gen i7-2600 (8) @ 3.8 GHz, 32 Gigs RAM. Attaching my screenshot... Thank you. Have a great day.

![Warp_no_sudo_bang_bang_on_Garuda_KDE_Plasma_Screenshot_20240426_122159](https://github.com/warpdotdev/Warp/assets/78651200/2232aab9-7431-4d8a-90a6-4072b39d155a)

**Comment by photismos** [comment]
The other thing that shouldn't go without saying is that—does Warp even need 'sudo !!'? It may be somewhat superfluous. I realized only later, in lieu of two key strokes for bang bang, I can more simply one-key right-arrow complete the previous command after 'sudo'. *shrug* At least for purposes on this machine...

![does_Warp_even_need_sudo_bang_bang_maybe_not_Screenshot_20240426_133903](https://github.com/warpdotdev/Warp/assets/78651200/2a6b18ac-7634-4e9d-942d-7bf2ba9b60cb)

**Comment by dannyneira** [comment]
Thanks for letting us know. Yes the Command Correction is meant to help, but it's still not solving your issue. I wasn't able to reproduce this issue on my arch linux VM, is it possible you have something in your RC files that modifies the normal behavior of `sudo !!`?

![CleanShot 2024-04-26 at 14 32 19](https://github.com/warpdotdev/Warp/assets/16809145/041e4b6f-1d96-4327-af28-7b78e486ca59)

**Comment by photismos** [comment]
> Thanks for letting us know. Yes the Command Correction is meant to help, but it's still not solving your issue. I wasn't able to reproduce this issue on my arch linux VM, is it possible you have something in your RC files that modifies the normal behavior of `sudo !!`?

@dannyneira ...I don't see anything in profile or rc's that would indicate anything amiss. 

`rg "sudo" .bash*
.bash_history
53:sudo fdisk -cu /dev/sdc

.bashrc
40:alias grubup="sudo update-grub"
41:alias fixpacman="sudo rm /var/lib/pacman/db.lck"
45:alias rmpkg="sudo pacman -Rdd"
65:alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
66:alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
67:alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
68:alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
73:alias please='sudo'
76:alias pacdiff='sudo -H DIFFPROG=meld pacdiff'
79:alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'
rg "sudo" .config/fish/
.config/fish/config.fish
102:        sudo pacman -R (pacman -Qdtq)
133:alias fixpacman 'sudo rm /var/lib/pacman/db.lck'
138:alias grubup 'sudo update-grub'
143:alias rmpkg 'sudo pacman -Rdd'
151:alias mirror 'sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist'
152:alias mirrora 'sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist'
153:alias mirrord 'sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist'
154:alias mirrors 'sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist'
159:alias please 'sudo'
162:alias pacdiff 'sudo -H DIFFPROG=meld pacdiff'`

**Comment by dannyneira** [comment]
Hi @photismos this issue has been fixed in the latest version of Warp. Closing this, but please update Warp and let us know if you're still seeing the issue.

![CleanShot 2024-05-29 at 15 28 31](https://github.com/warpdotdev/Warp/assets/16809145/9adee3bc-81f6-4bad-9fe3-beed0ca470a3)
