### ISSUE TITLE
python getpass doesn't work

### ISSUE THREAD

**Issue by HenryL27** [warpdotdev/Warp#4820]
### Describe the bug

python's builtin module getpass (for getting passwords) doesn't seem to read newlines from the terminal, and hence never exits

### To reproduce

run this python file:
```python
import getpass
x = getpass.getpass()
print(x)
```
enter any string, hit return, and observe that nothing happens

### Expected behavior

this program should print the password you just entered

### Operating system

MacOS

### Operating system and version

Darwin Kernel Version 23.4.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.04.16.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @HenryL27 I'm not able to reproduce this using python3 to run the test.

![CleanShot 2024-04-25 at 17 43 09](https://github.com/warpdotdev/Warp/assets/16809145/9d2697df-428f-47d2-bb74-186b770d63a7)

maybe you can workaround the issue by using the input function?
```
# Get user input
user_input = input("Enter your password:")

# Pass the user input to getpass
x = getpass.getpass(user_input)

print(x)
```

**Comment by HenryL27** [comment]
well, I just tried it again after updating warp to v0.2024.04.23.08.01.stable_03 and I don't have any problems. (pyenv) python 3.11.7 fwiw
Idk, I guess I got myself in some weird state somehow.
Feel free to close
