### ISSUE TITLE
Warp always stuck at Starting Shell

### ISSUE THREAD

**Issue by MuradBozik** [warpdotdev/Warp#4824]
### Operating System

MacOS

### Operating System and Version

14.4.1

### Local Shell Version

5.9

### Remote Shell Version

5.8.1

### Warp Version

v0.2024.04.16.08.02.stable_00

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

As soon as ssh command runs, block shifts to upper side. At bottom always showing "Starting shell...." This is regardless of the remote hosts. All remotes behave the same way. Each have different zsh versions and some uses only bash terminal. 

I can still contiune to write commands but not at the bottom, on directly the output blocks. It creates another block as soon as I start typing. If I try to close the shell it gives a warning that there is a running process which is "Starting shell...." I always have to kill the process or click ignore and close button.

### Include shell xtrace output

This command block outputs nothing. Literally empty. 

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by alokedesai** [comment]
Hi @MuradBozik, could you send a video of the behavior you're seeing? Also, could you try enabling showing the initialization block in the mac menu bar ("Blocks" > "Show Initialization Block") and include the output of that block? Thanks!

**Comment by MuradBozik** [comment]
I don't see that option. I copied the output of the block, but it is empty string. 

<img width="893" alt="Screenshot 2024-04-25 at 19 01 24" src="https://github.com/warpdotdev/Warp/assets/45070368/ed2afe5c-aa72-436e-b1c3-877c34847110">

**Comment by dannyneira** [comment]
As a workaround, you can try using adding `command ssh` to your Settings > Subshell menu, then use `command ssh <user@server>` to connect to sessions, this will enable Warp features with the subshell method instead of the ssh wrapper.

Or, you can also try disabling the SSH wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabling, SSH should work as normal.

https://docs.warp.dev/features/ssh
https://docs.warp.dev/features/subshells

**Comment by MuradBozik** [comment]
Thanks for the workarounds. This solves my problem. Appreciated.
