### ISSUE TITLE
VIM Input not working correctly on previous commands

### ISSUE THREAD

**Issue by apolzon** [warpdotdev/Warp#4826]
### Describe the bug

If you are in VIM input mode, and select a previous command (either by using arrow keys or `k` command), the first time you use a vim command (ie `cw`), it does nothing except placing you into insert mode.
Furthermore, oftentimes the suggestion pallette is still open at this point, so if you hit `esc` to go back into command mode, it will just clear the line and place you back on your normal blank command line -- in order to avoid this, you have to first hit space or some other input sequence once in insert mode in order to get out of the history view.

### To reproduce

Have some command history
On a blank command line, enter VIM command mode
Hit `k` to select a previous entry
Navigate on the line (navigation vim commands still work fine)
Type `cw` to change a word

Expected:
The word should now be deleted and you should be in insert mode

Actual:
You are placed into insert mode, but nothing has been altered

### Expected behavior

VIM insert/change/alter commands should work when editing previous history entries

### Operating system

MacOS

### Operating system and version

14.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.04.23.08.01.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

First noticed this ~2 months ago

### Additional context

I'm 99% sure this used to work correctly. I believe it broke 2-3 months ago, possibly around the time "official" vim support was rolled out

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @apolzon Thanks for the feedback. We'll work on reproducing it on our end and post if any updates on this thread.

**Comment by apolzon** [comment]
Just got the latest Warp update and can confirm the issue is resolved
