### ISSUE TITLE
2-3s of lag when opening a new tab

### ISSUE THREAD

**Issue by nukeop** [warpdotdev/Warp#4837]
### Describe the bug

When you press Cmd+T or Ctrl+T, when a new tab is opening, the terminal freezes for a good 2-3 seconds.

### To reproduce

Just open a new tab after the terminal has been left open for a few days.

### Expected behavior

I expect no lag

### Operating system

MacOS

### Operating system and version

14.4.1

### Shell Version

All

### Current Warp version

v0.2024.04.16.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

Also occurs on Linux.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @nukeop This may be due to an incompatible tool in your rc files.

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv` This forces Zsh to run with zero configs.

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

**Comment by nukeop** [comment]
I'm using fish, and looking at the list of incompatible tools, I use none of them. I do use omf (https://github.com/oh-my-fish/oh-my-fish), which on its face looks similar to some of the tools on the list. I expect that list is not exhaustive, so maybe that could be the cause?

**Comment by dannyneira** [comment]
@nukeop thanks for your patience, yes that could be the cause as oh-my-fish isn't a supported prompt. https://docs.warp.dev/appearance/prompt#custom-prompt-compatibility-table

Please wrap in this conditional in your config.fish file to disable it just for Warp.
```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here <
end
```

I'll work on updating those docs to help make this more clear.

**Comment by nukeop** [comment]
Thanks, not ideal, but at least we got to the bottom of the issue.

**Comment by rgaufman** [comment]
Ah, it seems this line was causing it for me:

```
source $ZSH/oh-my-zsh.sh
```

The frustrating thing, in every other terminal I can open a new tab and start typing and it shows what I type, but on Warp, it always excludes the first character. However adding this works around the issue:

```
if test "$TERM_PROGRAM" != "WarpTerminal"; then
  source $ZSH/oh-my-zsh.sh
fi
```
