### ISSUE TITLE
Warp features not enabled while connecting to a Jumpserver

### ISSUE THREAD

**Issue by 666keke** [warpdotdev/Warp#4842]
### Operating System

MacOS

### Operating System and Version

14.2.0

### Local Shell Version

5.9

### Remote Shell Version

5.1.16(1)-release

### Warp Version

v0.2024.04.23.08.01.stable_03

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

<img width="1440" alt="image" src="https://github.com/warpdotdev/Warp/assets/20734123/5e149d23-196d-4ca5-8e52-cf5b8299f742">

### Include shell xtrace output

复用SSH连接（git@10.134.170.171）[连接数量: 2]
Last login: Sun Apr 28 15:36:18 2024 from 10.***.***.231
git@22421010:~ $

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
@666keke were you able to sort out the issue? Warp has an SSH Wrapper that enables features (like the blocks, prompt, completions, etc.) on remote machines requiring the default prompt on the remote machine to be either `bash` or `zsh`.

Related docs:
[https://docs.warp.dev/features/ssh](https://docs.warp.dev/features/ssh#ssh-wrapper-fails)

**Comment by 666keke** [comment]
> @666keke were you able to sort out the issue? Warp has an SSH Wrapper that enables features (like the blocks, prompt, completions, etc.) on remote machines requiring the default prompt on the remote machine to be either `bash` or `zsh`.
> 
> Related docs: [https://docs.warp.dev/features/ssh](https://docs.warp.dev/features/ssh#ssh-wrapper-fails)

Thanks! I've been using the solution from #2100, and it works. Will the solution still be supported in future updates?
