### ISSUE TITLE
Copy on select preference does not persist between launches

### ISSUE THREAD

**Issue by edwardloveall** [warpdotdev/warp#485]
### Describe the bug

```shell
When I disable the `copy on select` feature and then relaunch the app, it's reenabled.
```

### To Reproduce

Steps to reproduce:
1. Go to Warp settings
2. Disable `Copy on select`
3. Quit and reopen Warp
4. Go to Warp settings
5. See that `Copy on select` is enabled

### Expected behaviour

```shell
I would expect it to stay on the setting that I chose.
```

### Screenshots

https://user-images.githubusercontent.com/49549/144619653-b75fcadb-1956-4e0a-a3a7-ad90ab969ce1.mp4

### Operating System

MacOS

### OS Version

11.6.1

**Comment by elviskahoro** [comment]
Fixed with:
**Stable release 2021-12-08 (v0.2021.12.06.19.09.stable_00)**
