### ISSUE TITLE
My Warp AI requests available suddenly shrank from 100 to 40

### ISSUE THREAD

**Issue by fredzannarbor** [warpdotdev/Warp#4854]
### Describe the bug

A couple of days ago I could have sworn my requests available was 100. Now it is 5/40 with 25 days left. What gives?

### To reproduce

Normal operation

### Operating system

MacOS

### Operating system and version

14.2.1

### Current Warp version

v0.2024.04.23.08.01.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @fredzannarbor the free daily 100 requests were while we were in [extended Free Preview](https://www.warp.dev/blog/free-preview-extended). We have recently released the Team plan so we've updated the free requests to 40 per month. Please read our blog and FAQ on this to learn more.

https://www.warp.dev/blog/team-plan
https://docs.warp.dev/help/plans-subscriptions-and-pricing


I understand this was a sudden change, we're continuing to learn as we implement the plans, so we appreciate your understanding.

**Comment by dannyneira** [comment]
There is a related request to remove the limits here: https://github.com/warpdotdev/Warp/issues/4829

Closing as this isn't a bug.

**Comment by Flecart** [comment]
@fredzannarbor its not even 100 to 40, it's from 100 daily to 40 monthly, something like from 100 a day to 1.2 a day.

**Comment by fredzannarbor** [comment]
Yeah.  I can live with it either way.  I have several other copilot things
so upgrading this would not be a priority. Integration with other providers
would be a good idea.

it probably would have been a good idea to emphasize the temporary nature
of the Free Preview quota a bit more strongly, it went completely past me.
---
Fred Zimmerman, Publisher
Nimble Books LLC
The AI Lab for Book-Lovers <http://NimbleBooks.com>
