### ISSUE TITLE
Not respecting my login shell

### ISSUE THREAD

**Issue by nburns** [warpdotdev/warp#486]
### Describe the bug

```shell
My login shell is not respected, I would expect fish to be the shell not zsh
```

### To Reproduce

Steps to reproduce:
1. Change your shell with `chsh` to `fish`
2. Launch Warp.app
3. enter `echo $SHELL`

### Expected behaviour

```shell
`fish` should be running, not `zsh`
```

### Screenshots

![Screen Shot 2021-12-03 at 10 49 52 AM](https://user-images.githubusercontent.com/1725338/144656826-0c36d403-ec58-4735-8f2d-83c174dcea6f.png)
![Screen Shot 2021-12-03 at 10 50 29 AM](https://user-images.githubusercontent.com/1725338/144656858-41091a8f-bb56-435d-9235-992bdbd86f45.png)
![Screen Shot 2021-12-03 at 10 50 44 AM](https://user-images.githubusercontent.com/1725338/144656897-2043b43c-1e86-46df-aa41-c0bdb63d2cef.png)
)

### Operating System

MacOS

### OS Version

11.6

**Comment by davidcelis** [comment]
`fish` isn't supported yet (see #190) so I'm guessing that's why Warp is bumping you to zsh

**Comment by elviskahoro** [comment]
We don't support fish yet! I'll file an internal ticket for us to have an indicator or banner so that the user is informed of this behavior!
