### ISSUE TITLE
Where to get original theme colors?

### ISSUE THREAD

**Issue by max-prtsr** [warpdotdev/Warp#4862]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I want to tweak it a bit, but I don't have it sources

### Is your feature request related to a problem? Please describe.

Provide original themes sources somewhere

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

PS Can't post into discussions, so opened an issue

**Comment by dannyneira** [comment]
Hi @max-prtsr We haven't open sourced our Warp Themes, but many of them can be found on [terminal-themes.com](https://terminal-themes.com). I hope this helps!

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
@max-prtsr were you able to find some of the default themes you're looking for on the site? We also have a themes repository where you can find the .yaml files for many themes including default ones. https://github.com/warpdotdev/themes/

Closing as the default themes are located in the repo, but please let me know of any issues.

**Comment by max-prtsr** [comment]
@dannyneira no, sorry, there are too many files. I don't understand where to look at.
I'm ending with removing wrap prompt since I can't change the color of current dir.

<img width="639" alt="image" src="https://github.com/warpdotdev/Warp/assets/84035280/a51daacf-825a-4e12-a2e7-ae7d18deea0b">
