### ISSUE TITLE
A single instance runs multiple processes of warp-terminal on linux - curious to know why

### ISSUE THREAD

**Issue by roynrishingha** [warpdotdev/Warp#4867]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I'm running warp-terminal on my debian-12 laptop and running `htop` displays multiple processes (with different process ids) are running in parrallel. I'm curious to know why. I expected to have a single process for a single instance of the terminal. 

If this is not a bug, It would be great if somebody can explain me the reason for this. Perhaps share some links that I can check out to learn about this.

### To reproduce

1. Click on the warp-terminal icon to launch it.
2. Run `htop` in a tab and you'll see multiple processes of warp-terminal.

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/99001889/15a9c35a-5bca-470c-94b7-cf2d4d72abe5)

My system:
![image](https://github.com/warpdotdev/Warp/assets/99001889/50bdb446-9c22-4ec5-9e98-dbb2adb7fd31)

### Operating system

Linux

### Operating system and version

Debian 12

### Shell Version

bash 5.2.15

### Current Warp version

v0.2024.04.30.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by weirdan** [comment]
These are not processes, but threads. See https://unix.stackexchange.com/a/10403

**Comment by dannyneira** [comment]
@roynrishingha You can occasionally clear the Blocks on a session with `SHIFT-CTRL-K` on Linux, or close unused sessions with `SHIFT-CTRL-W` on Linux. This will clear up some resources on your machine.

Closing as this isn't a bug, but a [rust feature](https://doc.rust-lang.org/book/ch16-01-threads.html).
