### ISSUE TITLE
nvim meta shortcuts don't work

### ISSUE THREAD

**Issue by jakubdonovan** [warpdotdev/Warp#4871]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

- Default nvchad installation
- Warp feature (use left Alt as Meta) enabled

`M i`  `M h` `M v` don't work at all.

![image](https://github.com/warpdotdev/Warp/assets/16073448/e20fc3fc-78fe-405d-ad83-ec673410a532)

Works in Mac's built-in terminal
![image](https://github.com/warpdotdev/Warp/assets/16073448/abe01f2d-d516-4a72-ba8b-cc0bfe948a70)

Works in iTerm2
![Screenshot 2024-05-04 at 23 11 10](https://github.com/warpdotdev/Warp/assets/16073448/0783311d-c81b-4f86-8f84-1f46182bebca)

Video demonstration: https://www.loom.com/share/6b867526b00a41a398e01972a37af4fe

Other issues reporting the same bug. 
- https://github.com/warpdotdev/Warp/issues/3018 
- https://github.com/warpdotdev/Warp/issues/3790 

Yes, I opened a new issue because one was closed despite the author confirming that the bug still exists while the other has been open since October of last year with no updates.

### To reproduce

`M i`  `M h` M v`

### Operating system

MacOS

### Operating system and version

Sonoma 14.0

### Shell Version

fish, version 3.6.1

### Current Warp version

v0.2024.04.30.08.02.stable_01

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)
Yes, works in Mac's built in terminal, Alacritty, and iTerm2

**Comment by dannyneira** [comment]
Hi @jakubdonovan Thanks for submitting this detailed bug report. I was able to reproduce the issue and will bring this up with the team. We'll post any updates on this thread.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by jakubdonovan** [comment]
> Hi @jakubdonovan Thanks for submitting this detailed bug report. I was able to reproduce the issue , with caveat that `M v` and `M h` were working in Warp, but I will bring this up with the team about floating term. We'll post any updates on this thread.
> 
>  CleanShot.2024-05-08.at.17.52.05.mp4 
> To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

Actually, none of the 3 shortcuts involving the Meta key seem to work for me while `leader h` and `leader v` do.

**Comment by jakubdonovan** [comment]
> Hi @jakubdonovan Thanks for submitting this detailed bug report. I was able to reproduce the issue , with caveat that `M v` and `M h` were working in Warp, but I will bring this up with the team about floating term. We'll post any updates on this thread.
> 
>  CleanShot.2024-05-08.at.17.52.05.mp4 
> To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

Are there any updates?

**Comment by dannyneira** [comment]
Hi Folks, This issue has been resolved in the latest version of Warp. Closing as resolved, but please update Warp and let us know if the issue persists.
