### ISSUE TITLE
getting support is too difficult

### ISSUE THREAD

**Issue by ghost** [warpdotdev/Warp#4874]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

signing up for 3rd party services to submit a support ticket is too time consuming and difficult. I don't use discard or this gither thing and I don't want to learn how. I just want to send a fucking email.

### Is your feature request related to a problem? Please describe.

I have to sign up for a new services to send a fucking email.

### Additional context

I did not "search warp feature requests" for duplicates because I do not know how.

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @ghost, sorry about this, we're try and make other options available like sending email to `feedback@warp.dev`. We also want to make the issues publicly available on github so that others can learn about them and possible workarounds. That was the issue you're facing specifically?

**Comment by dannyneira** [comment]
Closing as the user has a deleted account. Please feel free to reopen if you have a specific issue to troubleshoot.
