### ISSUE TITLE
Stop opening "Warp Essentials" on startup

### ISSUE THREAD

**Issue by mirague** [warpdotdev/Warp#4876]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Don't open the Warp Essentials on startup, or add an option to disable this behaviour.

### Is your feature request related to a problem? Please describe.

I'm always frustrated when the "Warp Essentials" tab is opened on startup or after an update.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for submitting this @mirague 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/3742

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/3742
