### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by qinfeng0214** [warpdotdev/Warp#4877]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Hi,dannyneira,I'd like to update you on the progress of the i18n support work, we have been waiting for a long time, and now there are many issues about requesting i18n support, can you tell us about the progress of this work? We are very anxious, thank you

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @qinfeng0214 Sorry about this delay, there is no immediate update at this time, but ime support is something we are tracking here: https://github.com/warpdotdev/Warp/issues/341 as well as here: https://github.com/warpdotdev/Warp/issues/1194

Please track those requests for any updates.

**Comment by dannyneira** [comment]
Duplicate of https://github.com/warpdotdev/Warp/issues/341

**Comment by leesa-ui-w** [comment]
Thank you for bringing this to our attention. This issue is tracked under #320    Please comment, 👍 upvote and subscribe there for updates. Closing as a duplicate.
