### ISSUE TITLE
Partial completion of Autosuggestions with ctrl+ right arrow

### ISSUE THREAD

**Issue by itsrifat** [warpdotdev/Warp#488]
### Describe the solution you'd like?

zsh autosuggestion allows you to complete the auto suggestion partially with `ctrl + right-arrow` one word at a time. It would be nice to have the feature in warp. Right now you have to accept the whole command with the press of a a right arrow

![zsh-autosuggestion](https://user-images.githubusercontent.com/4328772/144669778-d87ad6aa-5faa-4081-aead-01464b77dc27.gif)

**Comment by elviskahoro** [comment]
Moving to #579 so all keybinding related issues are in one place:
- #579

**Comment by elviskahoro** [comment]
Added with v0.2022.02.21.08.55.stable_00
