### ISSUE TITLE
Issue with Opening Jupyter Notebook: Blank Browser Tab

### ISSUE THREAD

**Issue by assemkadry** [warpdotdev/Warp#4880]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I am writing to report an issue I encountered while using the Wrap Terminal app on macOS. When attempting to open Jupyter Notebook from the Wrap Terminal app, I encountered a problem where the browser opens but only displays a blank tab. This issue persists regardless of the browser used, including Arc Browser and Safari.

### To reproduce

Open the Wrap Terminal app on macOS.
Run the command to start Jupyter Notebook (jupyter notebook).
Notice that the browser opens but only displays a blank tab.

### Expected behavior

After starting Jupyter Notebook from the Wrap Terminal app, I expected the browser to open and display the Jupyter Notebook interface, allowing me to create or open notebooks as usual.

### Screenshots

<img width="1387" alt="Screenshot 2024-05-06 at 7 12 36 PM" src="https://github.com/warpdotdev/Warp/assets/135189593/8d249c52-a374-409b-91b8-90eb5f7560c5">

### Operating system

MacOS

### Operating system and version

14.4.1

### Shell Version

GNU bash, version 3.2.57(1)

### Current Warp version

v0.2024.04.30.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by vorporeal** [comment]
Mind confirming that the same URL is being opened in the web browser when following the link in Warp vs. in other terminals?

**Comment by assemkadry** [comment]
Any link generated from Warp to open a Jupyter notebook does not open in Arc or Safari browsers but works in Google Chrome only. However, any link generated from the built-in terminal to open a Jupyter notebook works in any browser

**Comment by davidmelvin** [comment]
@assemkadry can you post the logs output by running the command `jupyter notebook`?

**Comment by assemkadry** [comment]
(base) Assem-MacBook-Pro:~ assemkadry$
jupyter notebook
[I 2024-05-07 15:24:14.113 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-05-07 15:24:14.120 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-05-07 15:24:14.127 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-05-07 15:24:14.132 ServerApp] notebook | extension was successfully linked.
[I 2024-05-07 15:24:15.272 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-05-07 15:24:15.357 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-05-07 15:24:15.360 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-05-07 15:24:15.362 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-05-07 15:24:15.366 LabApp] JupyterLab extension loaded from /Users/assemkadry/miniconda3/lib/python3.12/site-packages/jupyterlab
[I 2024-05-07 15:24:15.366 LabApp] JupyterLab application directory is /Users/assemkadry/miniconda3/share/jupyter/lab
[I 2024-05-07 15:24:15.369 LabApp] Extension Manager is 'pypi'.
[I 2024-05-07 15:24:15.394 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-05-07 15:24:15.397 ServerApp] notebook | extension was successfully loaded.
[I 2024-05-07 15:24:15.399 ServerApp] Serving notebooks from local directory: /Users/assemkadry
[I 2024-05-07 15:24:15.399 ServerApp] Jupyter Server 2.14.0 is running at:
[I 2024-05-07 15:24:15.399 ServerApp] http://localhost:8888/tree?token=b0f3dbaa55db4e0916cc3eded789c7d48c683e14d585c53b
[I 2024-05-07 15:24:15.399 ServerApp]     http://127.0.0.1:8888/tree?token=b0f3dbaa55db4e0916cc3eded789c7d48c683e14d585c53b
[I 2024-05-07 15:24:15.399 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-05-07 15:24:15.414 ServerApp]

    To access the server, open this file in a browser:
        file:///Users/assemkadry/Library/Jupyter/runtime/jpserver-1223-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/tree?token=b0f3dbaa55db4e0916cc3eded789c7d48c683e14d585c53b
        http://127.0.0.1:8888/tree?token=b0f3dbaa55db4e0916cc3eded789c7d48c683e14d585c53b
[I 2024-05-07 15:24:24.006 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server

**Comment by davidmelvin** [comment]
The blank browser tab is the tab that opens automatically after running `jupyter notebook`, correct?

Does copying and pasting any of the URLs directly into Arc solve the issue? I'm trying to check if there's an issue in the communication between Warp and Arc or with the links themselves.
```
To access the server, open this file in a browser:
    file:///Users/assemkadry/Library/Jupyter/runtime/jpserver-1223-open.html
Or copy and paste one of these URLs:
    http://localhost:8888/tree?token=b0f3dbaa55db4e0916cc3eded789c7d48c683e14d585c53b
    http://127.0.0.1:8888/tree?token=b0f3dbaa55db4e0916cc3eded789c7d48c683e14d585c53b
```
