### ISSUE TITLE
Missing rocky support in rpm postinstall scriptlet

### ISSUE THREAD

**Issue by joeomc** [warpdotdev/Warp#4886]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

The rpm postinstall scriptlet doesn't add the warp dev repo file in /etc/yum.repos.d on rocky linux.   Please add `rocky` to:
```
case $DISTRO_ID in
		"fedora"|"rhel"|"centos"|"amzn"|"mageia"|"openmandriva")
```

### To reproduce

On rocky 9.3:
`sudo dnf install warp-terminal-v0.2024.04.30.08.02.stable_02-1.x86_64.rpm`

### Operating system

Linux

### Operating system and version

Rocky Linux 9.3

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @joeomc thanks for letting us know about this, I'll let the team know. As workaround, you can try the following command to [install the repos manually](https://docs.warp.dev/getting-started/getting-started-with-warp).
```
sudo rpm --import https://releases.warp.dev/linux/keys/warp.asc
sudo sh -c 'echo -e "[warpdotdev]\nname=warpdotdev\nbaseurl=https://releases.warp.dev/linux/rpm/stable\nenabled=1\ngpgcheck=1\ngpgkey=https://releases.warp.dev/linux/keys/warp.asc" > /etc/yum.repos.d/warpdotdev.repo'
sudo dnf install warp-terminal
```

**Comment by alokedesai** [comment]
Hi @joeomc good call out and thanks for flagging. We fixed this in a release 2 weeks ago so I'm going to close this out. Please reopen if you're still seeing issues!
