### ISSUE TITLE
Unable to select text with mouse in mc

### ISSUE THREAD

**Issue by paveldvorak5** [warpdotdev/Warp#4888]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Can't select text using mouse in the midnight commander
I tried to enable the Mouse reporting

Also Alt+I does not work in mc

### To reproduce

You try to select text anywhere when mc is running

### Expected behavior

To be able to select text using shift + mouse button

### Operating system

Linux

### Operating system and version

Debian 12

### Shell Version

zsh 5.9 (x86_64-debian-linux-gnu)

### Current Warp version

v0.2024.04.30.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

Never

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @paveldvorak5 sorry about this issue. Could you please post a video of the issue in Warp? I'm seeing the issue on iTerm2 but not Warp, although Warp does allow you to highlight/copy text. the high light it's not clearly visible when you're copying text.

https://github.com/warpdotdev/Warp/assets/16809145/43b20771-e31d-4706-a148-4dcad4e84a5b

Hope this helps with your issue.

**Comment by paveldvorak5** [comment]
You are right, I can select and copy text with left mouse but it's not visible

**Comment by dannyneira** [comment]
Heard, i'll bring this up with the team and we'll post updates on this thread.

**Comment by alokedesai** [comment]
@paveldvorak5 Can you share a video of what this looks like in iterm? I see the same issue with selections across a few different terminal emulators.

**Comment by paveldvorak5** [comment]
Hi, I don't have a mac

**Comment by alokedesai** [comment]
@paveldvorak5 Ah sorry, could you post a video of another terminal on Linux where you think the behavior is correct?

**Comment by paveldvorak5** [comment]
it works when using shift

https://github.com/warpdotdev/Warp/assets/14863835/b6ca446a-7b7e-4cbe-a662-fa1bb7901926

**Comment by alokedesai** [comment]
@paveldvorak5 What terminal are you using in that video?

**Comment by acarl005** [comment]
Hi @paveldvorak5.

Alt + i should start working correctly in the next release coming out later this week (assuming you've got "alt key is meta" enabled).

I'm working on shift+click selection too. Not sure when that will be out since it still needs approval, but it should be soon.

**Comment by acarl005** [comment]
Shift+click fix has been approved and entered QA. If everything passes, the fix will be in the July 11th release.

**Comment by dannyneira** [comment]
Hi Folks, This issue has been resolved in the latest version of Warp. Closing as resolved, but please update Warp and let us know if the issue persists.
