### ISSUE TITLE
Unable to type in "OC" or "OD" into commands

### ISSUE THREAD

**Issue by DavidTanner** [warpdotdev/Warp#4889]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When trying to navigate to a folder that starts with `OC` the terminal removes the `O`, and this doesn't appear to matter where in the string `OC` shows up.  This also happens with `OD`, but not any other characters. 

oh-my-zsh master (22bbc23)

### To reproduce

Running zshell on MacOS execute the command 
```shell
echo 'OC'
echo 'OD'
```

Output then looks like
```shell
echo 'C'
C
echo 'D'
D
```

### Expected behavior

```text
echo 'OC'
OC
echo 'OD'
OD
```

### Screenshots

![Screenshot 2024-05-07 at 5 10 48 PM](https://github.com/warpdotdev/Warp/assets/368889/286d394d-1206-4048-867f-6e1d45bf481f)
![Screenshot 2024-05-07 at 5 11 00 PM](https://github.com/warpdotdev/Warp/assets/368889/c061bb26-0e31-4ad3-b93d-f84c55fca437)

My screenshots are for `SOC` because that is how I found it, but it doesn't need the `S` to happen.

### Operating system

MacOS

### Operating system and version

MacOS 14.4.1 (23E224)

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.04.30.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I cannot reproduce the issue if I don't run `Warpify subshell`

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @DavidTanner i'm not seeing the issue in a Warpified zsh subshell or native zsh in Warp.

![CleanShot 2024-05-08 at 17 11 57](https://github.com/warpdotdev/Warp/assets/16809145/9b11150e-b87a-4d52-90fb-07ecd0e0dafa)

My guess is that you may have a [custom prompt, theme, or bash/zsh/fish plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table)
You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by DavidTanner** [comment]
@dannyneira Thank you for those links!  I think I found the source of my problems.  I had added some `bindkey` commands to handle beginning/end of line.  After commenting the lines, I no longer have an issue.  Thanks!

```bash

bindkey 'OD' beginning-of-line      # cmd+←
bindkey 'OC' end-of-line            # cmd+→

```
