### ISSUE TITLE
DUP: Duplicate of #403 - Tab to complete doesn't work

### ISSUE THREAD

**Issue by sethfri** [warpdotdev/warp#489]
### Describe the bug

When I start typing something, Warp shows an autosuggestion for what it wants to complete for me. However, when I press Tab, it shows me a menu of things to choose from instead of completing. The autosuggestion is also not at the top of the completion list.

The right arrow key seems to do what I want, but that involves moving my hand off of the keyboard, which is a non-starter for a terminal app. I also don't see any keymap to change this.

### To Reproduce

Steps to reproduce:
1. Type anything
2. Press tab

### Expected behaviour

```shell
Tap should complete the command you're typing
```

### Operating System

MacOS

### OS Version

11.6.1

**Comment by elviskahoro** [comment]
Same as:
- https://github.com/warpdotdev/warp/issues/403
