### ISSUE TITLE
Auto warpify

### ISSUE THREAD

**Issue by alaidine** [warpdotdev/Warp#4891]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

when i change something in my shell config and run the exec zsh command i want warp to automatically warpify instead of just asking me if i want to warpify.

![warpify](https://github.com/warpdotdev/Warp/assets/89530788/27332c19-69b9-467c-ad38-fb2c05fee6ea)

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @alaidine You can add the following line to your zshrc file to automatically warpify the subshell. See more in our docs. https://docs.warp.dev/features/subshells#automatically-warpify-subshells

```
# For zsh subshells, add to ~/.zshrc.
printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "zsh"}}\x9c'
```
Please let us know if this helps with your use case.

**Comment by alaidine** [comment]
Hey @dannyneira I tried it and it worked.
Thank you for your help.

**Comment by alaidine** [comment]
Hey @dannyneira I tried it and it worked.
Thank you for your help.

**Comment by samyouel** [comment]
Hey. I've tried this as described in the docs and it's not working. I'm using `zsh`.
I always still have to warpify the subshell manually via shortcut.

**Comment by alaidine** [comment]
@samyouel can you show me your .zshrc.

**Comment by samyouel** [comment]
hey, it's got quite a few aliases in it (that's probably not the best way to do these things I know but for now it works good for me)

```Shell Script
# # ----------------- OH  MY ZSH --------------------
# Path to your oh-my-zsh installation.
export ZSH="/Users/***/.oh-my-zsh"
# THEMES: https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="zhann"
# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"
# Plugins
plugins=(git)
source $ZSH/oh-my-zsh.sh


# .....
# Quite a few aliases 
# ....

# ----------------- VS CODE ---------------------
export EDITOR="code -w"

# ---------------- Node --------------------------
export PATH="/usr/local/sbin:$PATH"

# ----------------- Ruby -------------------------
export PATH=$PATH:"$HOME/.rbenv/shims/rdbg"

# -------------------- PHP -----------------------
export PATH="/opt/homebrew/opt/php@8.1/bin:$PATH"
export PATH="/opt/homebrew/opt/php@8.1/sbin:$PATH"

# # ---------------- Composer ------------------
export PATH="$HOME/.composer/vendor/bin:$PATH"

# # ----------------- PNPM ---------------------
export VOLTA_FEATURE_PNPM=1

# # # ------------ WARP Subshells --------------
printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "zsh"}}\x9c'

```

Something like this. Don't really get where the issue should be?

**Comment by alaidine** [comment]
@samyouel When i put the warp subshell line it works for my shell i dont know why it doesnt work for you, sorry if I couldn't help you.
