### ISSUE TITLE
clear command bug

### ISSUE THREAD

**Issue by alaidine** [warpdotdev/Warp#4892]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

when i execute the clear command i get this

![warp_bug](https://github.com/warpdotdev/Warp/assets/89530788/be781028-9dbf-41c4-b213-0ee7eaecc532)

### To reproduce

Steps to reproduce: 1. run a shell command that will output something into the terminal like 'ls' 2. run clear

### Operating system

Linux

### Operating system and version

artix linux 6.6.30-1-tls

### Shell Version

zsh 5.9 (x86_64-pc-linux-gnu)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @alaidine It's not clear what's causing this and I can't reproduce it on Arch Linux. Please see the list of possible workarounds here: https://docs.warp.dev/help/known-issues#linux-workarounds

Also, make sure to [download the latest version](https://warp.dev/linux-terminal) as we release fixes every week. https://docs.warp.dev/getting-started/changelog

Please let me know if any of those helped or if you still see the issue.

**Comment by dannyneira** [comment]
@alaidine can you provide a video of the issue and/or more detailed logs?

https://docs.warp.dev/help/sending-us-feedback

**Comment by alaidine** [comment]
@dannyneira It's 3 a.m where i am and i cant do it right now, I will try to do it later in the day.

**Comment by alaidine** [comment]
@dannyneira I just downloaded the new version of warp and dont see the bug anymore.

**Comment by dannyneira** [comment]
amazing! Thanks for letting us know. Please call out of the issue returns.
