### ISSUE TITLE
Documentation: Custom Themes > Clone entire repo

### ISSUE THREAD

**Issue by mudittiwari2000** [warpdotdev/Warp#4896]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

In the documentation, for custom themes, the section where a command is given for cloning entire repo is incorrect. It didn't work for me, and the issue wasn't obvious.

Command I mentioned above:
```
cd ~/.warp/
git clone https://github.com/warpdotdev/themes.git
```

The issue:
Since the above command is a set of two commands, if `~/.warp` directory doesn't already exist, the first command `cd ~/.warp` would fail but since no shorthand operator like `&&` is used in this command in the docs, the next command would run just fine and the github repo for themes will be cloned in a directory called `/themes` at pwd. Instead, maybe add a shorthand or maybe create the `~/.warp` directory first before running both the commands?

Possible Fix #1:
```
cd ~/.warp/ && git clone https://github.com/warpdotdev/themes.git
```

Possible Fix #2:
```
mkdir ~/.warp
cd ~/.warp/
git clone https://github.com/warpdotdev/themes.git
```

### To reproduce

1. Make sure ~/.warp is deleted.
2. Run the following commands in the terminal
```
cd ~/.warp/
git clone https://github.com/warpdotdev/themes.git
```
3. Notice you're still in the same directory.
4. This would fail to install the themes in Warp.

### Operating system

MacOS

### Operating system and version

Sonoma 14.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.04.30.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @mudittiwari2000 thanks for letting us know. checking to confirm, but I think ~/.warp folder may not be automatically created upon installing Warp for Mac. If this is the case, you're correct and we need to update that command to include making the dir. I'll post updates to this thread.

**Comment by dannyneira** [comment]
Updated the custom themes docs to include making the directory before cd and clone repo. 
Thanks for helping to make our docs a bit better!
