### ISSUE TITLE
discontinue warp terminal

### ISSUE THREAD

**Issue by margarineman** [warpdotdev/Warp#4898]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

warp terminal still exists

### To reproduce

download the thing and run it

### Operating system

MacOS

### Operating system and version

p

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

fuck this terminal fuck whatever venture capital firm funded this fuck you fuck your chatgpt addon fuck your fucking programming circlejerk fuck your hypetrain fuck you i hope you all get run over by a bus

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @margarineman sorry you feel this way. Closing as this isn't a bug.
