### ISSUE TITLE
KB: CTRL-L ^-L keyboard shortcut for clear screen

### ISSUE THREAD

**Issue by kendallm** [warpdotdev/warp#49]
**Describe the solution you'd like**
I most terminals I am used to using `ctrl + L` to clear the terminal window. Hyper supports the clear command, but not the keyboard shortcut. I would be cool if `ctrl + L` was supported.

**Additional context**
N/A

**Comment by drpayyne** [comment]
Can we please get this implemented even if it doesn’t get much upvotes? This is a P1 feature, imo. ;)

**Comment by zachlloyd** [comment]
We are going to investigate implementing it this week.  Thanks for the report!

**Comment by brainkim** [comment]
What would this look like? I am reflexively hitting Ctrl-L because in the terminal, this is how I get the cursor to the top of the page. That probably wouldn’t be the behavior for Warp, which always keeps the editor at the bottom of the page, right? Would this just hide the blocks and reset the view to the initial state?

**Comment by kendallm** [comment]
> What would this look like? I am reflexively hitting Ctrl-L because in the terminal, this is how I get the cursor to the top of the page. That probably wouldn’t be the behavior for Warp, which always keeps the editor at the bottom of the page, right? Would this just hide the blocks and reset the view to the initial state?

This would behave the same as typing `clear` into the terminal today. In Warp's case this does not move the cursor but clears the terminal of all visible output lines.

**Comment by CaptainYouz** [comment]
thanks for the `cmd + k` tip @cvega !
and definitely +1 for `cmd + l` feature

**Comment by kendallm** [comment]
Dupe: #421, closing

**Comment by elviskahoro** [comment]
Should be fixed with v0.2021.11.29.18.59.stable_01
please reopen or comment if it still persists
