### ISSUE TITLE
DUP: Duplicate of #210 - zsh completions don't work

### ISSUE THREAD

**Issue by sethfri** [warpdotdev/warp#490]
### Describe the bug

```shell
zsh autocompletes git commands, but Warp breaks these even when they work in iTerm
```

### To Reproduce

Steps to reproduce:
1. Set up zsh Git autocompletion
2. Type `git branch -D` and then the first letter of a branch you have in a repo, then press tab

### Expected behaviour

```shell
Tab should autocomplete the branch name, but it doesn't in Warp
```

### Operating System

MacOS

### OS Version

11.6.1

**Comment by elviskahoro** [comment]
Same as:
- https://github.com/warpdotdev/warp/issues/210
