### ISSUE TITLE
AppImage welcome survey every launch

### ISSUE THREAD

**Issue by chrisdlangton** [warpdotdev/Warp#4905]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I'm getting annoyed to be slowed down for mandatory welcome survey every launch.
If it was fully keyboard controlled it would be less annoying, but it's only partially implemented.
If it wasn't mandatory to answer every quetion and write text responses.
But it is pretty much going to send me back to any other terminal if it slows me down on every launch forever - maybe consider changing this forever situation? it's not a perspective, it's a fact and being slowed down forever is a crazy user experience

### To reproduce

launch the AppImage

### Expected behavior

account linked survey collection - i.e. if you've been sent answers, maybe stop harassing us?

### Screenshots

no point, you know that the welcome survey is

### Operating system

Linux

### Operating system and version

any o/s that supports AppImage

### Shell Version

any shell

### Current Warp version

Warp-x86_64_6d08b2cb17b910c72ddb40da252c2f9b.AppImage

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @chrisdlangton sorry to hear about this. I'll let the team know. Have you used other [install methods](https://docs.warp.dev/getting-started/getting-started-with-warp), and if so, do they have the same issue?

Can you try log out of Warp, and then log back in to see if that triggers the survey?

**Comment by chrisdlangton** [comment]
I'll try the Pacman methods but after reflection of AppImage it may be a permissions issue with where your app code tries to persist Configs or cache, which are usually littered in whatever system or user directory you decided for the regular uncontained installation methods that aren't appropriate for an AppImage

I'll update if the Pacman alternatives work

**Comment by dannyneira** [comment]
Thanks for confirm the repo install didn't help the situation. I recommend you try logout of Watp, then removing Warp user files. You'll lose the session restorations, but this may reset the state for the survey when you log back in it should prompt your for survey once more, but noy every time. `rm -r ${XDG_STATE_HOME:-$HOME/.local/state}/warp-terminal`
https://docs.warp.dev/help/uninstalling-warp#removing-warp-login-settings-files-log-and-database-1

If this doesn't help please provide us the log file is located at `${XDG_STATE_HOME:-$HOME/.local/state}/warp-terminal/warp.log`
https://docs.warp.dev/help/sending-us-feedback

**Comment by chrisdlangton** [comment]
Will try after work.
And what about the gpg error?
