### ISSUE TITLE
while AI tab is open Settings close button dont work sometimes and ui is disturbed 

### ISSUE THREAD

**Issue by AR-92** [warpdotdev/Warp#4906]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

sorry this is my first bug report :
1: open AI tab from the title bar.
2: open settings.

now look at the settings panel close button is dislocated and AI icon is visible on the top of settings panel. 

### To reproduce

sorry this is my first bug report :
1: open AI tab from the title bar.
2: open settings.

now look at the settings panel close button is dislocated and AI icon is visible on the top of settings panel.

### Screenshots

![Screenshot from 2024-05-11 15-33-21](https://github.com/warpdotdev/Warp/assets/25506788/06ef0324-a3bb-443a-b4d7-880b188e4e2d)

### Operating system

Linux

### Operating system and version

arch

### Current Warp version

v0.2024.05.07.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

11/may/2024

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @AR-92 Thanks for letting us know. We're working on a replacement for that panel so this issue should be resolved once the Warp AI "chat" is integrated into the block list. Please stay tuned to our socials and changelog for updates to this.
