### ISSUE TITLE
SSH: Can't use all shell history on a remote machine

### ISSUE THREAD

**Issue by pcarlisle** [warpdotdev/Warp#491]
### Describe the bug

```shell
I can't access all history on a remote machine.
```

### To Reproduce

I have established .bash_history on a remote machine from before I started using warp.
When I ssh in with warp and hit up arrow or ctrl-r to access history, the entries in .bash_history from previous non-warp sessions don't show up.

### Expected behaviour

```shell
I expect warp to use the existing .bash_history or just let the remote shell handle this.
```

**Comment by elviskahoro** [comment]
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
