### ISSUE TITLE
SSH not align

### ISSUE THREAD

**Issue by xinxianwu** [warpdotdev/Warp#4914]
### Dupe Check

- [X] I have [searched Warp SSH issues](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ASSH) and there are no duplicates

### Operating System

MacOS

### Operating System and Version

macOS Sonoma 14.4.1

### Local Shell Version

3.2.57(1)-release

### Remote Shell Version

5.1.16(1)-release

### Warp Version

v0.2024.04.30.08.02.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

<img width="1353" alt="image" src="https://github.com/warpdotdev/Warp/assets/50643550/1e1b6e68-1ca8-45a4-a96c-93a02e9249cd">

### Include shell xtrace output

When using Warp Terminal to SSH into remote Linux machines, the terminal display often misaligns, with commands and window elements not aligning properly. 

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Warp has an SSH Wrapper that enables features (like the prompt, completions, etc.) on remote machines . This requires the default prompt on the remote machine to be either bash or zsh.

As a workaround, you can try using adding `command ssh` to your Settings > Subshell menu, then use `command ssh <user@server>` to connect to sessions, this will enable Warp features with the subshell method instead of the ssh wrapper.

Or, you can also try disabling the SSH wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabling, SSH should work as normal.

https://docs.warp.dev/features/ssh
https://docs.warp.dev/features/subshells

If those don't work, please let us know.

**Comment by danielpeng2** [comment]
Thanks for reporting, seems like there might be an issue with how we parse the backslash in your username. Are you able to test ssh-ing into a remote machine with a username without a backslash? It'd be helpful to know if there's still alignment issues in that case.

**Comment by xinxianwu** [comment]
> Thanks for reporting, seems like there might be an issue with how we parse the backslash in your username. Are you able to test ssh-ing into a remote machine with a username without a backslash? It'd be helpful to know if there's still alignment issues in that case.

Due to the company's policy on managing domains, our username must have backslashes

**Comment by xinxianwu** [comment]
> as a workaround, you can try using adding `command ssh` to your Settings > Subshell menu, then use `command ssh <user@server>` to connect to sessions, this will enable Warp features with the subshell method instead of the ssh wrapper.
> 
> Or, you can also try disabling the SSH wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabling, SSH should work as normal.
> 
> https://docs.warp.dev/features/ssh https://docs.warp.dev/features/subshells
> 
> If those don't work, please let us know.

According to my understanding, using the SSH wrapper should enable intelligent prompts and AI services on remote machines. However, I am experiencing display misalignment issues, where commands and window elements do not align properly. Could this be a side effect of using the SSH wrapper?

**Comment by danielpeng2** [comment]
> Could this be a side effect of using the SSH wrapper?

Yeah, it's likely to do with how the SSH wrapper handles bootstrapping the remote shell so it works with Warp. If you try @dannyneira workaround of using `command ssh` to enable the subshell wrapper instead, does the issue still appear?

**Comment by aminst** [comment]
> as a workaround, you can try using adding `command ssh` to your Settings > Subshell menu, then use `command ssh <user@server>` to connect to sessions, this will enable Warp features with the subshell method instead of the ssh wrapper.
> 
> Or, you can also try disabling the SSH wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabling, SSH should work as normal.
> 
> https://docs.warp.dev/features/ssh https://docs.warp.dev/features/subshells
> 
> If those don't work, please let us know.

I tried adding the command ssh to enable the subshell wrapper, but it didn't work for me. I still have misaligned shell output. I turned off the shell wrapper eventually, and now the output is back to normal.

**Comment by xinxianwu** [comment]
> > Could this be a side effect of using the SSH wrapper?
> 
> Yeah, it's likely to do with how the SSH wrapper handles bootstrapping the remote shell so it works with Warp. If you try @dannyneira workaround of using `command ssh` to enable the subshell wrapper instead, does the issue still appear?

I turned off the SSH wrapper from 'Settings > Features,' and then the SSH was aligned
