### ISSUE TITLE
Ability to delete blocks

### ISSUE THREAD

**Issue by AuburnMedia** [warpdotdev/Warp#4918]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Alongside the "Ask Warp AI", "Bookmark block" and "Filter block output" buttons, but before the options button. Should be a simple trash icon. 👍 

### Is your feature request related to a problem? Please describe.

Often large blocks can take up a lot of scroll space, and CMD-K is not always applicable if there is info needed in above blocks.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

Ignore

**Comment by dannyneira** [comment]
Thanks for submitting this @AuburnMedia 

We already have a request tracking this over at #50 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
Duplicate of #50
