### ISSUE TITLE
SSH: Completion over SSH does't work for dot files

### ISSUE THREAD

**Issue by pcarlisle** [warpdotdev/Warp#492]
### Describe the bug

```shell
Warp won't tab complete filenames beginning with `.` over an ssh connection.
```

### To Reproduce

While connected over SSH
```
> ls -a
.  ..  helloo  .test
> cat .te<tab>
```
Nothing happens

### Operating System

MacOS

**Comment by elviskahoro** [comment]
@pcarlisle 
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
