### ISSUE TITLE
Can't see underscores typed in "Added commands" or "Blocklisted commands" textboxes for Subshells

### ISSUE THREAD

**Issue by emosy** [warpdotdev/Warp#4923]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When typing commands into the "Added commands" or "Blocklisted commands" textboxes, underscores typed do not appear in the textbox, but are only visible once the command is entered.

### To reproduce

1. Go to settings
2. Open subshells
3. Type `test_command` in the "Added commands" or "Blocklisted commands" textboxes
4. Notice that the underscore (`_`) is not visible, so the command looks identical to `test command`

### Expected behavior

I want to see the underscore, so the bottom of the text should not be clipped

### Screenshots

https://github.com/warpdotdev/Warp/assets/27254405/8959e412-53f6-4ebf-9571-ffb1dd909460

### Operating system

MacOS

### Operating system and version

Sonoma 14.5

### Shell Version

N/A

### Current Warp version

v0.2024.05.07.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @emosy I'm struggling to reproduce this issue on my end. Are you using `ABC` input source for your keyboard, or something else?

Also, could you try the new release from today to see if the issue persists?

Here is my example using ABC input source.

https://github.com/warpdotdev/Warp/assets/16809145/f85f8eb7-1d63-4550-9c04-2a9dda2ad6c5

**Comment by dannyneira** [comment]
Awesome! ABC is the US keyboard input source in Mac settings, but glad to hear the new update fixed it!

https://github.com/warpdotdev/Warp/assets/16809145/d50615aa-1314-4be1-b389-def1dcab0b33
