### ISSUE TITLE
Can't use Fish shell on latest Warp update (big regression)

### ISSUE THREAD

**Issue by nikitavoloboev** [warpdotdev/Warp#4925]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

<img width="563" alt="image" src="https://github.com/warpdotdev/Warp/assets/6391776/5a99fd1f-ad32-4f0e-8c92-ebecac83d6b7">

Never completes on latest update.

### To reproduce

Update to `v0.2024.05.14.08.01.stable_02` version.

with this config: https://github.com/nikitavoloboev/config/blob/main/fish/config.fish

### Expected behavior

Hangs as shown in image above.

### Operating system

MacOS

### Operating system and version

14.4.1

### Shell Version

`fish, version 3.7.1`

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by nikitavoloboev** [comment]
<img width="1033" alt="image" src="https://github.com/warpdotdev/Warp/assets/6391776/1b393e2c-4f8a-4362-a9c8-9fdd887159fd">

Terminal works fine

Can I get older version of Warp?

**Comment by elviskahoro** [comment]
For mac users, here's last week's build:
https://storage.googleapis.com/warp-releases/stable/v0.2024.05.07.08.02.stable_02/Warp.dmg

We're looking into the possible regression now!

**Comment by danielpeng2** [comment]
Hey @nikitavoloboev, if you comment out everything in your fish config does the issue still occur? Trying to determine if there's something specific in the config that's causing this.

**Comment by nikitavoloboev** [comment]
@danielpeng2 

yes removing all of config, makes latest version work

**Comment by nikitavoloboev** [comment]
<img width="421" alt="image" src="https://github.com/warpdotdev/Warp/assets/6391776/628eeda3-0644-4673-883e-4ce330c75bd9">

This line in config breaks it for me on latest warp

**Comment by nikitavoloboev** [comment]
https://github.com/nikitavoloboev/config/blob/main/fish/functions.fish

so this file

**Comment by nikitavoloboev** [comment]
ok @danielpeng2 

I found the culprit

```
function .
    if not set -q argv[1]
        open .
    else
        # copy output to clipboard
        set -l output (eval $argv)
        echo $output | pbcopy
    end
end
```

this function will break latest warp

Please fix, I'd like this function to work 🙏 

It works on old version.

**Comment by danielpeng2** [comment]
@nikitavoloboev Thanks for finding the culprit, I can repro on my machine. We're working on fixing this!

**Comment by danielpeng2** [comment]
Hey @nikitavoloboev, we just pushed an update (`v0.2024.05.14.08.01.stable_04`) that should fix this issue! Try it out and let us know if it works.
