### ISSUE TITLE
control+k does not always cut all to the right

### ISSUE THREAD

**Issue by GavinHuttley** [warpdotdev/Warp#4926]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Select a command from history, move cursor within the text and enter ^+k. First event, it jumps to start of the line. If I navigate back to the cut point and do ^+k again, it cuts all to the right correctly.

### To reproduce

1. Up arrow to select a multi-word command from history
2. option left arrow to jump one word
3. enter control+k

### Expected behavior

It should cut all to the right

### Screenshots

![ScreenFlow](https://github.com/warpdotdev/Warp/assets/3102996/db62d922-dd5d-4046-bd15-56990ac597ba)

### Operating system

MacOS

### Operating system and version

Sonoma 14.4.1

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.05.14.08.01.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

About a week ago?

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @GavinHuttley thanks for your patience. Double check that you have the default keybindings for cut all right (CTRL-K) as well as Move to Start of the line/paragraph (CTRL-A). If that doesn't help you can try deleting Warp settings with `defaults delete dev.warp.Warp-Stable` and just note that all your settings with be changed to default.

Please let us know if that helps.

https://github.com/warpdotdev/Warp/assets/16809145/12ebe4d4-7de2-4c04-b2b1-af2040396f15

**Comment by GavinHuttley** [comment]
using `defaults delete dev.warp.Warp-Stable` worked!
Thank you!
