### ISSUE TITLE
Latest build auto-complete is dead

### ISSUE THREAD

**Issue by apudiu** [warpdotdev/Warp#4932]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I'm on a sudo enabled user on Ubuntu 24.04. type `sudo update-` [tab tab...] nothing shows up. Tryid to `update-alternative`.

### To reproduce

N/A

### Expected behavior

It should show autocomplete for (at-least) system commands like `update-alternatives`

### Operating system

Linux

### Operating system and version

24.04

### Shell Version

GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.05.14.08.01.stable_04

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

doesn't remember exactly

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @apudiu Sorry to hear about this. I believe there was a fix for `sudo` prefix completions issues we worked on recently. This fix may be out in an upcoming release.

**Comment by dannyneira** [comment]
Hi Folks, this should be fixed in the latest Warp release. 

Closing as resolved, but please update and let us know if any issues.

**Comment by alokedesai** [comment]
Reopening, the fix for this is merged but will be available in _next_ Thursday's release. Thanks for your patience here!

**Comment by alokedesai** [comment]
Hi @apudiu, the latest version of Warp should have fixed this issue. I'm going to close this out, but please reopen if you're still experiencing issues.
