### ISSUE TITLE
Some Rust unit tests hang when run from Warp.

### ISSUE THREAD

**Issue by hkratz** [warpdotdev/Warp#494]
### Describe the bug

```shell
Some Rust unit tests hang when run from Warp. That does not happen with other terminals.
```

### To Reproduce

Steps to reproduce:
1. Add Warp to the Developer Tools in the Privacy section of the System Preferences.
2. Clone [rust-lang/rust](https://github.com/rust-lang/rust) on a Mac M1.
3. Run `./x.py setup compiler`
4. Run `./x.py test src/test/ui --force-rerun --test-args ui/panics/abort-on-panic.rs`
5. The test hangs and does not complete in any reasonable timeframe. The test framework displays a warning:
```
test [ui] ui/panics/abort-on-panic.rs has been running for over 60 seconds
```

### Expected behaviour

```shell
The test completes within seconds without error just like it does in other terminals.
```

### Operating System

MacOS

### OS Version

12.0.1

### Additional context

```shell
Warp v0.2021.11.29.18.59.stable_01
```

**Comment by hkratz** [comment]
Still hanging with with Warp v0.2022.01.31.09.03.stable_00 running on macOS 12.2.

**Comment by alokedesai** [comment]
Friendly ping on this @hkratz--is this still occurring? If so, could you share a screencast of the error occurring. Thanks so much!

**Comment by elviskahoro** [comment]
This should be fixed now! Please reopen if not.
