### ISSUE TITLE
I am a Chinese, can I add Chinese?

### ISSUE THREAD

**Issue by w776534161w** [warpdotdev/Warp#4943]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I am a Chinese, can I add Chinese? My English is not good

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
As of now, Warp has added character support for Chinese, Korean, and Japanese, but the user interface (UI) currently only supports English. If you're experiencing issues with the terminal rendering Chinese characters, you can try adding the following lines to your rc file:

```bash
export LC_ALL=zh_CN.UTF-8
export LANG=zh_CN.UTF-8
```

However, full support for the Chinese language in the UI is not yet available. There is an open issue on Github tracking the request for Chinese language support. You can follow the progress of this feature request on [Github issue #1823](https://github.com/warpdotdev/Warp/issues/1823).

截至目前，Warp 已添加对中文、韩语和日语的字符支持，但用户界面 (UI) 目前仅支持英语。 如果您在终端呈现中文字符时遇到问题，可以尝试将以下行添加到 rc 文件中：

````bash
导出 LC_ALL=zh_CN.UTF-8
导出 LANG=zh_CN.UTF-8
````

不过，UI 尚未完全支持中文。 Github 上有一个未解决的问题，用于追踪中文支持的请求。 您可以在 [Github issues #1823](https://github.com/warpdotdev/Warp/issues/1823) 上关注此功能请求的进度。

**Comment by dannyneira** [comment]
Duplicate of #1823

**Comment by Ehz-zone** [comment]
我非常想要在warp的ui上看到中文，谢谢🙏

**Comment by jianyestudy** [comment]
+1

**Comment by leo-roborock** [comment]
我非常想在warp的ui上看到中文，谢谢🙏

**Comment by zijiu4** [comment]
🙋

**Comment by davymai** [comment]
+1

**Comment by Eagle-Mao** [comment]
+1

**Comment by hxpy0524** [comment]
+1

**Comment by redto-mato** [comment]
+1

**Comment by learn-G-p** [comment]
+1

**Comment by 716123** [comment]
+1

**Comment by vindisc** [comment]
+1

**Comment by lingmingyu** [comment]
+10086

**Comment by sumayi** [comment]
+1

**Comment by nexttargetyiyi** [comment]
+1

**Comment by hughnwj** [comment]
+1

**Comment by Norvon** [comment]
+1

**Comment by Tiramisupxl** [comment]
+1

**Comment by Serendipity565** [comment]
+1

**Comment by clint456** [comment]
+1

**Comment by imgwho** [comment]
+1

**Comment by aesfas** [comment]
+10010

**Comment by a746791569** [comment]
+1

**Comment by jlliu-sequoia** [comment]
+1

**Comment by w847** [comment]
+1

**Comment by fwd001** [comment]
Much needed.

**Comment by lasterX** [comment]
+1

**Comment by unusuallman** [comment]
非常需要中文的UI界面

**Comment by kokojacket** [comment]
+1

**Comment by sylearn** [comment]
+1

**Comment by zhouchenshu** [comment]
+1 没有中文真的很多地方不能配置

**Comment by Moresl** [comment]
Please support the Chinese language.

**Comment by dannyneira** [comment]
Duplicate of #1823

**Comment by dannyneira** [comment]
Duplicate of #1823

**Comment by kangdy** [comment]
+1

**Comment by GitClound** [comment]
+1

**Comment by mengyuan1997** [comment]
+1

**Comment by Spenlu** [comment]
+1

**Comment by patkemll** [comment]
+1

**Comment by mdddj** [comment]
+1

**Comment by Alonglang** [comment]
+1

**Comment by 1739616529** [comment]
+1

**Comment by Gary-Lv** [comment]
+1

**Comment by JupiterFeng** [comment]
+1

**Comment by Scout--** [comment]
+1

**Comment by chaodoing** [comment]
+1
