### ISSUE TITLE
cannot run a workflow while the current tab runs a command `kubie ctx` 

### ISSUE THREAD

**Issue by iyuhptop** [warpdotdev/Warp#4946]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

run command: `kubie ctx a k8s cluster`
and run a workflow, it shows `a command in this session is still running`

<img width="1088" alt="image" src="https://github.com/warpdotdev/Warp/assets/14036170/0ddbf470-b497-4d47-a153-86b709be9a65">

### To reproduce

1. run `kubie ctx k8s_cluster_ctx_name`
2. run a workflow in the current terminal

### Operating system

MacOS

### Operating system and version

Mac OS sonoma

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @iyuhptop Unfortunately, you can't run workflows on a session which is already running a server/cluster/command. Your best bet is to either run the cluster in the background with an `&` (i.e. `kubie ctx a k8s cluster &`) or open a new session (window/tab/pane) in the same path to run workflows.

Please let me know if that helped or if you're unable to run workflows after the `&`

https://github.com/warpdotdev/Warp/assets/16809145/2dfbd635-dfa0-46fb-a057-e4ee4f418086

**Comment by iyuhptop** [comment]
Hi @dannyneira Thanks for the quick reply. The session crashes when I run this command(`kubie ctx a k8s cluster &`).

Anyway, many other solutions don't require the "kubie" command. 

You know, I was just wondering if there is a more elegant way 😃
