### ISSUE TITLE
Cannot work with`warpgate`

### ISSUE THREAD

**Issue by oslo254804746** [warpdotdev/Warp#4948]
### Dupe Check

- [X] I have [searched Warp SSH issues](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ASSH) and there are no duplicates

### Operating System

MacOS

### Operating System and Version

14.4.1

### Local Shell Version

5.9

### Remote Shell Version

4.2.46(2)-release

### Warp Version

v0.2024.05.21.16.09.stable_02

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

use `Warp`

<img width="1063" alt="image" src="https://github.com/warpdotdev/Warp/assets/57609491/784d6ce6-e979-4d21-8970-b1e5ed68ab19">

Use `iTerm2  + zsh`

<img width="1048" alt="image" src="https://github.com/warpdotdev/Warp/assets/57609491/f8891f96-33c6-4068-81b1-e31bd203ca1c">

### Include shell xtrace output

I have many internal network machines and one public network machine. The public machine and the internal network machines are connected via VPN. The public machine also hosts the [warpgate](https://github.com/warp-tech/warpgate) service. All commands to access the internal machines from the public machine are like ssh 'ticket-aca7077a872e8a6b100d36e3da1bff24c346808ef140580e0937a21da25d2e01@ip' -p 2222. This command works fine on zsh, but it directly throws an error on Warp. 

WARP_DEBUG_MODE=1 ssh 'ticket-aca7077a872e8a6b100d36e3da1bff24c346808ef140580e0937a21da25d2e01@10.xx.xx.3' -p 2222
exec request failed on channel 1

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Warp has an SSH Wrapper that enables features (like the blocks, prompt, completions, etc.) on remote machines requiring the default prompt on the remote machine to be either `bash` or `zsh`.

As a workaround you can add `command ssh` to your `Settings > Subshells > Added commands` menu, then run `command ssh <user@server>` to connect to remote session, this will attempt to enable Warp features as a subshell.

You can also try disabling the SSH Wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabling, SSH should work as normal.

Related docs:
[https://docs.warp.dev/features/ssh](https://docs.warp.dev/features/ssh#ssh-wrapper-fails)
https://docs.warp.dev/features/subshells

Please let us know if that helps.

**Comment by oslo254804746** [comment]
thanks,  after disable ssh wrapper it works
