### ISSUE TITLE
DUP: Duplicate of #407 - `git switch` sub-command doesn't have completion

### ISSUE THREAD

**Issue by ccpost** [warpdotdev/warp#495]
### Describe the bug

Warp doesn't seem to be aware of the `git switch` sub-command; the flags shown are top-level `git` flags.

### To Reproduce

Steps to reproduce:
1. Enter `git switch -`
2. Hit Tab
3. Observe that the completions are incorrect

### Screenshots

![image](https://user-images.githubusercontent.com/55072/144771832-5b901733-c298-4351-9bcd-5e92c42ac1f9.png)

### Operating System

MacOS

### OS Version

10.15.7

### Additional context

Warp version: `v0.2021.11.29.18.59.stable_01`

**Comment by elviskahoro** [comment]
Same as 
- #407
merging
