### ISSUE TITLE
No history in SSH

### ISSUE THREAD

**Issue by zheng** [warpdotdev/Warp#4952]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

History menu is empty in all my SSH sessions

### To reproduce

Happens everytime I SSH into a codespace

This works fine if I open a subshell locally. I don't have any other VM to try SSH-ing into

### Screenshots

https://www.loom.com/share/599c335e26444ff9b50d1bf793099b0f

### Operating system

MacOS

### Operating system and version

Sonoma 14.3

### Current Warp version

v0.2024.05.21.16.09.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Previous release

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
I tried, but failed to reproduce this on a blank codespace, ssh session has history. Do you see the same on a blank codespace? Is there codespace template you can share to reproduce this on?

https://github.com/warpdotdev/Warp/assets/16809145/fb523e36-2555-4c1b-a750-cabd13fc571a

Maybe removing your local history sqlite file will help? `sqlite3 "$HOME/Library/Application Support/dev.warp.Warp-Stable/warp.sqlite"`

**Comment by zheng** [comment]
> I tried, but failed to reproduce this on a blank codespace, ssh session has history. Do you see the same on a blank codespace? Is there a specific codespace template you're using we can try reproduce this on?
> 
> 
> 
> https://github.com/warpdotdev/Warp/assets/16809145/fb523e36-2555-4c1b-a750-cabd13fc571a
> 
> 
> 
> Maybe removing your local history sqlite file will help? `sqlite3 "$HOME/Library/Application Support/dev.warp.Warp-Stable/warp.sqlite"`
> 
> 
> 
> 

Thanks for trying that out!! I made a new code space and history is fine there. I was having a slew of issues because of code space instability

I'll close this issue
