### ISSUE TITLE
SSH: Warp hangs when I try to auto-complete a directory I don't have access to 

### ISSUE THREAD

**Issue by ShukantPal** [warpdotdev/Warp#496]
### Describe the bug

I was working on my university's servers and if I accidentally tried to go outside my home directory in a path - Warp would hang. Sometimes it would go into an infinite loop of messages "channel 25 not allowed" or something like that

### Screenshots

<img width="1028" alt="Screen Shot 2021-12-05 at 8 11 27 PM" src="https://user-images.githubusercontent.com/22450567/144772271-d56b3040-9199-4d77-aef5-d9e177b487dd.png">

### OS Version

12.0.1

**Comment by elviskahoro** [comment]
@ShukantPal 
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.

**Comment by elviskahoro** [comment]
@ShukantPal 
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.

**Comment by zheng** [comment]
Hi @ShukantPal, I replicated the directory permissions on a VM, but I'm not the infinite loop of messages (but I am seeing \* getting suggested).

Does this problem happen for you in the latest version of Warp?

**Comment by zheng** [comment]
Actually, I realized there may be another issue that's happening here!

Is it the case that completions are not working for you? Does the message come up every time you do a tab completion?

This happens if the SSH server has some options (usually in `/etc/ssh/sshd_config`) like `AllowTCPForwarding no`, `PermitOpen` or if there's a `MaxSessions` limit that's being exceeded.
