### ISSUE TITLE
Are already executed commands no longer colored?

### ISSUE THREAD

**Issue by gp0119** [warpdotdev/Warp#4966]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Since the recent update, I noticed that previously executed commands are no longer colored. Is this intentional?

### To reproduce

![CleanShot 2024-05-31 at 15 19 38@2x](https://github.com/warpdotdev/Warp/assets/35173639/11f79632-a57a-49b6-8728-6410c67b8267)

### Operating system

MacOS

### Operating system and version

MacOS 14.5

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @gp0119 I think this may be intentional, but when I went as far back as Jan 2023 build and didn't see the colors on the output for commands. Do you know when or which version you saw with this behavior?

**Comment by gp0119** [comment]
@dannyneira hi, can you tell me where I can download previous versions? I'm quite sure the earlier version had colors. perhaps you could try version 2024.05.16 (v0.2024.05.14.08.01).

**Comment by gp0119** [comment]
@dannyneira I downloaded version v0.2024.05.14.08.01.stable_04 and found that previously executed commands are colored. 
![CleanShot 2024-06-03 at 14 22 04@2x](https://github.com/warpdotdev/Warp/assets/35173639/2b9714f7-713f-4f41-9a8e-efe5f285dda1)

**Comment by gp0119** [comment]
I didn't use any plugins that change colors. Strangely, I upgraded to the latest version again, and the colors have returned.

**Comment by dannyneira** [comment]
hm strange. I'll close for now, but if it happens again please let us know and provide copy of your rc files (with no secrets included).
