### ISSUE TITLE
Control-space needed by emacs

### ISSUE THREAD

**Issue by hillegass** [warpdotdev/warp#499]
### Describe the bug

```shell
I think Warp is intercepting the Control-space keybinding.  However, this is crucial when you use emacs. (It is set-mark, which everyone uses for cutting and pasting.)
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```shell
First, the terminal emulator should not intercept control-space. It is just too important.

However, if you are going to, you need to make it easy for me to find Warp's keybindings and disable them.
```

### Operating System

MacOS

**Comment by Lokdex** [comment]
I think that this should be expanded to the fact Warp intercept several emacs keybindings. For instance I had defined cmd+shift+p to open the "command palet" and it didn't work. Also, I tried with opt+x, the classic "M-x", but on the mini buffer I just saw two ~ over each other (don't know the name of the character or how to replicate it). So perhaps an option for more "vanilla like" terminal keybindings would be useful for us that are more used to old school terminals, or even emacs-like keybindings like Alacritty.

**Comment by elviskahoro** [comment]
Fixed with: v0.2022.01.03.09.07.stable_01

**Comment by Lokdex** [comment]
Yep, thanks!

**Comment by emanuelmanea** [comment]
Emacs is used on Windows as well, do you have plans to do the same also for Windows?
