### ISSUE TITLE
Changing Copy command doesnt work | Ubuntu 22.04

### ISSUE THREAD

**Issue by semenovfilipp** [warpdotdev/Warp#4991]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I want to change Copy command from CTRL+SHIFT+C to CTRL+C at shortcuts.
But when I test new shortcut, it still CTRL+SHIFT+C

P.S.
I tried to do it for all Copy command or where command contains word Copy

Version Warp on Screenshot

### To reproduce

Go to Settings
1. Keyboard shortcuts
2. Change Copy from CTRL+SHIFT+C to CTRL+C

### Expected behavior

It would be great to fix
P.S.
I tried to do it for all Copy command or where command contains word Copy

### Screenshots

![Screenshot from 2024-06-05 17-55-10](https://github.com/warpdotdev/Warp/assets/42844486/2faaf56d-13b8-4558-9403-b6e939a20ce5)
![Screenshot from 2024-06-05 17-51-27](https://github.com/warpdotdev/Warp/assets/42844486/e87989fe-99a0-41bd-813f-d739e4fbfb48)

### Operating system

Linux

### Operating system and version

Ubuntu 22.04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

Wayland 

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @semenovfilipp Sorry about this i think it may default to the shift-ctrl-c so that it doesn't conflict with ctrl-c to stop a running command. That being said, you should be able to change this by editing the `${XDG_CONFIG_HOME:-$HOME/.config}/warp-terminal/keybindings.yaml` file.

include the following:
```
"terminal:paste": ctrl-v
"terminal:copy": ctrl-c
```

let us know if this helped with your issue.

**Comment by semenovfilipp** [comment]
Already in use

```
---
"workspace:move_tab_right": ctrl-shift->
"terminal:paste": ctrl-v
"editor:find": ctrl-f
"workspace:move_tab_left": ctrl-shift-<
"terminal:copy_commands": ctrl-c
"pane_group:close_current_session": ctrl-w
"terminal:find": ctrl-f
"workspace:new_tab": ctrl-t
"workspace:close_window": none
"workspace:close_active_tab": ctrl-w
"terminal:copy": ctrl-c
"terminal:toggle_block_filter_on_selected_or_last_block": none
"editor_view:clear_buffer": ctrl-shift-X
"editor_view:cut_word_left": none
"terminal:ask_ai_assistant_last_block": none
```

Command interrupt I change from value ctrl+c to ctrl+z, by using 
```
stty intr ^z
```

Can anything else be a cause of this problem?

**Comment by semenovfilipp** [comment]
I think better close the issue to await changes in next updates.
