### ISSUE TITLE
Global hotkey doesn't work when the input source is Chinese

### ISSUE THREAD

**Issue by wang9262** [warpdotdev/Warp#4999]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

as described in title

### To reproduce

Set global hotkey for hotkey window，then switch the input source to Chinese; When hotkey triggered, the hotkey window doesn't show/hide as expected. It works fine if I switch input source to English.
<img width="691" alt="image" src="https://github.com/warpdotdev/Warp/assets/5634225/0315c8c9-4228-4726-8884-c02bec05ce14">

### Operating system

MacOS

### Operating system and version

14.3.1

### Current Warp version

v0.2024.05.14.08.01.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment]
Hi @wang9262 thanks for reporting. Looks like this is another example of #341. Would you mind upvoting that one to help us prioritize the original issue? Closing this one here.
