### ISSUE TITLE
Other: Open Source GUI framework crate

### ISSUE THREAD

**Issue by srounce** [warpdotdev/warp#5]
Are there any plans to open source any of the layers of the GUI framework described in [this article](https://blog.warp.dev/how-warp-works/) any time soon?

**Comment by alokedesai** [comment]
Thank you for filing! This is absolutely something we plan on open sourcing once it's more mature, but we don't have a concrete timeline for when that will be just yet. Our main goal is to make it cross platform first, since it only targets MacOS right now.
