### ISSUE TITLE
Warp and Oh My Posh duplicating prompt

### ISSUE THREAD

**Issue by ognjenradojcic** [warpdotdev/Warp#5000]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When I use Warp with Oh My Posh to style my prompt, each time I press enter, prompt is duplicated. 

This only happens when using Oh My Posh, and it's only happening in Warp terminal, normal terminal is working fine.

Note: I saw old threads where it said that update fixed this issue, but I am at the latest warp version.

### To reproduce

1. Install Oh My Posh
2. Add eval "$(oh-my-posh --init --shell bash --config {theme}" to ~/.bashrc
3. Restart terminal

### Expected behavior

I expect to only have single prompt, without it duplicating after each insert

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/85464865/d886d853-1161-4260-a6e6-48535caef593)

![image](https://github.com/warpdotdev/Warp/assets/85464865/92280081-a16e-44e4-a2d2-08fcc1502bd2)

### Operating system

Linux

### Operating system and version

Linux pop-os 6.8.0

### Shell Version

bash version 5.1.16(1)-release

### Current Warp version

v0.2024.06.04.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @ognjenradojcic sorry about this. I was able to reproduce this with a basic oh-my-posh install. I'll let the team know and we'll post updates on this thread.
