### ISSUE TITLE
Multi-cursor: Keyboard inputs across multiple panes

### ISSUE THREAD

**Issue by shaym007** [warpdotdev/Warp#5006]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

The ability to type into one pane and have that input sent to all panes, or to have the executed command on one pane be sent to all panes.

This feature exists on OSX's native terminal as multi-cursor, as well as in Mobaxterm as "Multi-exec". 

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Howdy @shaym007 You're in luck! Warp has just the feature for your use case. We call it Synchronized Inputs and you can enable it for all the panes in a Tab, specific Tabs(panes), or all Tabs. Please see more in our docs. https://docs.warp.dev/features/entry/synchronized-inputs

Closing as this feature already exists, but please let us know if any issues.

**Comment by dannyneira** [comment]
No Problem @shaym007 ! I'll close this one as resolved since we already have the feature you're requesting, but feel free to let me know of any issues with the Synced inputs.
