### ISSUE TITLE
Fish + tide + warp not loading properly prompt after start but working after calling fish again

### ISSUE THREAD

**Issue by MattOrmianek** [warpdotdev/Warp#5007]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

With my config when I create new tab/new window in warp I have problem with loading colors, styles of prompt from fish, but when I use command 'fish' for loading fish again everything works properly. Easy fix is let users add command when launching new tab. Also weird thing, function from fish works when I create new tab (without loading fish again) but shortcuts don't. 

### To reproduce

Add tide to fish and make some changes, also I did some changes in fish_prompt. 

### Expected behavior

I wish that styles to prompt load when whole tab is creating. 

### Screenshots

https://github.com/warpdotdev/Warp/assets/16574489/6e99a711-08c8-4585-ad7e-bf389c8dea2e

### Operating system

MacOS

### Operating system and version

Sonoma 14.5

### Shell Version

fish, version 3.7.0

### Current Warp version

v0.2024.06.04.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @MattOrmianek thanks for submitting this!

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/3358

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by MattOrmianek** [comment]
Sorry for duplicate, fixed this problem with small change, settings > appearance  > prompt and changed it from default to PS1.
