### ISSUE TITLE
The application crashes when cutting or deleting Japanese characters.

### ISSUE THREAD

**Issue by Jin-Taniguchi-0x0** [warpdotdev/Warp#5008]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When cutting or deleting Japanese characters in a notebook, the application crashes. Occasionally, the application does not crash, but the conditions for this are unknown. This issue has been occurring since reinstalling the latest version of Warp.

### To reproduce

1. Open a notebook
2. Delete japanese character
3. Crash

### Expected behavior

The application does not crash when cutting or deleting Japanese characters, unlike with English characters.

### Operating system

MacOS

### Operating system and version

Sonoma 14.5

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)

### Current Warp version

v0.2024.06.04.08.02.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

2024/06/10

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @Jin-Taniguchi-0x0 Thanks for letting us know. We're sorry to hear about this blocker. We're actively working on a fix and it should be in upcoming release.

**Comment by alokedesai** [comment]
Hi @Jin-Taniguchi-0x0 This should be fixed in the latest version of Warp. Please reopen if you're still experiencing issues!
