### ISSUE TITLE
Warpify shell is buggy in latest release

### ISSUE THREAD

**Issue by mharrisb1** [warpdotdev/Warp#5009]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Before upgrading to `v0.2024.06.04.08.02.stable_03`, Warpify shell worked perfectly. After upgrading, initialing the feature with `poetry shell` results in a buggy experience. First, it hung while trying to execute some shell command. Then after quitting and opening back up the app that didn't happen again but I've now lost the beloved block experience.

### To reproduce

See above.

### Operating system

MacOS

### Operating system and version

Sonoma 14.5

### Current Warp version

zsh 5.9 (x86_64-apple-darwin23.0)

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by mharrisb1** [comment]
Restarted again, removed the Warpify entry from zshrc, re-added it, and sources the file. Now I'm getting this error:

```sh
 [ -z $WARP_BOOTSTRAPPED ] && eval 'export WARP_HONOR_PS1=0; export WARP_COMBINED_PROMPT_COMMAND_GRID=0;  setopt hist_ignore_space; unsetopt ZLE; WARP_IS_SUBSHELL=1; WARP_SESSION_ID="$(command -p date +%s)$RANDOM"; _hostname=$(command -pv hostname >/dev/null 2>&1 && command -p hostname 2>/dev/null || command -p uname -n); _user=$(command -pv whoami >/dev/null 2>&1 && command -p whoami 2>/dev/null || echo $USER); _msg=$(printf "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"shell\": \"zsh\", \"user\": \"$_user\", \"hostname\": \"$_hostname\", \"is_subshell\": true}}" | command -p od -v -b | command -p cut -b9- | command -p xargs printf "0%s " | command -p xargs printf "%02x" | command -p tr -d " \n"); if command -p echo a | command -p od -An -v -tx1 >/dev/null 2>&1; then;    _msg=$(printf "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"shell\": \"zsh\", \"user\": \"$_user\", \"hostname\": \"$_hostname\", \"is_subshell\": true}}" | command -p od -An -v -tx1 | command -p tr -d " \n"); fi; printf '"'"'\x1b\x50\x24\x64%s\x9c'"'"' "$_msg"; unset _hostname _user _msg;'
 ```

**Comment by alokedesai** [comment]
Hey @mharrisb1, sorry for the issues you're seeing and thanks for flagging.

1) Do you remember the last version you were using before this happened?
2) Are you able to repro with the build released last thursday? https://releases.warp.dev/stable/v0.2024.06.04.08.02.stable_02/Warp.dmg

**Comment by alokedesai** [comment]
Could you also share a video of what the error looks like in Warp so I can better understand what's happening?

**Comment by mharrisb1** [comment]
Hey @alokedesai thanks for responding.

> Do you remember the last version you were using before this happened?

I don't unfortunately

> Are you able to repro with the build released last thursday?

I am

Here is a recording using that release. The problem is the same as the current release

https://www.loom.com/share/0d0f475cf7c7461bbcf5030607089056?sid=eadb1a95-217a-47f6-bb3b-3c017bc44b3b

**Comment by alokedesai** [comment]
Thanks. Could you try the previous week's release? https://releases.warp.dev/stable/v0.2024.05.28.08.02.stable_00/Warp.dmg

Have you upgraded `poetry` at all? What version of `poetry` are you using?

**Comment by mharrisb1** [comment]
Not able to repro on that release with Poetry v1.8.2

https://www.loom.com/share/a05385afedc44019971ee0ae1cb50e06?sid=cba3628e-4861-4688-951a-fb9fa81eec0d

**Comment by mharrisb1** [comment]
Also just to confirm contents of `~/.zshrc`

```sh
cat ~/.zshrc | grep 'printf'
printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "zsh"}}\x9c'
```

**Comment by alokedesai** [comment]
@mharrisb1 Thanks for the info. We're actively looking at this and should have an update shortly.

**Comment by mharrisb1** [comment]
Thanks for looking into it. I'm set in the meantime with `v0.2024.05.28.08.02.stable_00`

**Comment by alokedesai** [comment]
Found the culprit, working on a fix for this right now. New release should be available within the next hour.

**Comment by alokedesai** [comment]
@mharrisb1 The latest release should have a fix for this. Thanks again for flagging and please reopen if you're still experiencing issues.

**Comment by mharrisb1** [comment]
Confirming that new release works. Thanks for closing so quickly. You guys killed it 🔥
