### ISSUE TITLE
Allow screenshots/images in Notebooks

### ISSUE THREAD

**Issue by GrizzlyByte7** [warpdotdev/Warp#5010]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Can you allow for images/screenshots to be added to notebooks? Either by importing, or copying and pasting? I have been taking notes alongside my terminal which works out great, especially with creating workflows and adding them directly into my notes; but it would be great to be able to take screenshots and quickly add them to my notebook. If this is a feature already, it is not clear how to do it.  

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for submitting this @GrizzlyByte7 

We already have a request tracking this over at #26 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
