### ISSUE TITLE
[Arch] [Linux] [Wayland] Warp too slow since the last 2 updates

### ISSUE THREAD

**Issue by ARKye03** [warpdotdev/Warp#5011]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Since the update "2024.05.30 (v0.2024.05.28.08.02)", the warp has gotten slower, making opening, reacting, and even writing slow. Scrolling down and up through blocks, etc., used to be
 instant, but now it isn't.

This issue is similar to another one [reported](https://github.com/warpdotdev/Warp/issues/4786) on Linux.

### To reproduce

Install Warp Terminal, Arch Linux, Hyprland, Nvidia (this shouldn't be the problem).
Launch it, do anything; it will be slow. My system has remained nearly unchanged since May 23; only Warp has been updated, along with some Nvidia drivers or Mesa. However, these updates
 have significantly improved the Wayland Linux experience, while Warp has worsened.

### Expected behavior

Working as usual

### Operating system

Linux

### Operating system and version

Arch Linux

### Shell Version

zsh 5.9 (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.06.04.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

2024.05.23 (v0.2024.05.21.16.09)

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @ARKye03 Sorry to hear about this. We are working on native Wayland support and it's being tracked here. https://github.com/warpdotdev/Warp/issues/4628

We are also working on high memory consumption which is being tracked here. https://github.com/warpdotdev/Warp/issues/2611

Those two should help significantly with the issues you're mentioning. Thanks for your patience with us while we work to resolve these.

**Comment by ARKye03** [comment]
> Hi @ARKye03 Sorry to hear about this. We are working on native Wayland support and it's being tracked here. #4628
> 
> We are also working on high memory consumption which is being tracked here. #2611
> 
> Those two should help significantly with the issues you're mentioning. Thanks for your patience with us while we work to resolve these.

Thank you for the response, the warp terminal is awesome!!

**Comment by alokedesai** [comment]
Hi @ARKye03, are you still experiencing these issues? If not, would love to close this out :)

**Comment by ARKye03** [comment]
> Hi @ARKye03, are you still experiencing these issues? If not, would love to close this out :)
Yes, I'll close it. The issue arose briefly while using the terminal for prolonged hours, but nowadays it's working as expected. Thank you!
