### ISSUE TITLE
Hitting enter after successful launch config save causes error

### ISSUE THREAD

**Issue by bean5** [warpdotdev/Warp#5022]
### Dupe Check

- [x] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Hitting enter after successful launch config save causes error

### To reproduce

1. Start saving a launch configuration
2. After typing the name, hit enter
3. That works fine. Now hit enter again. You expect it to press the button, but it instead presses a hidden button and attempts to save again!

### Expected behavior

1. Start saving a launch configuration
2. After typing the name, hit enter
3. View message that says it saved
4. Hit enter again to dismiss

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/2052646/619955bf-4b35-49db-9e9c-79883fe24f70)

![image](https://github.com/warpdotdev/Warp/assets/2052646/c2181216-b3e3-415a-87ad-e9c63d36e4e8)

### Operating system

Linux

### Operating system and version

22.04

### Shell Version

zsh 5.8.1

### Current Warp version

v0.2024.06.04.08.02.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @bean5 I was able to reproduce this issue on Mac and Linux. We'll post any updates on this thread.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Hi Folks, this issue has been fixed in the latest version of Warp. 

Closing as resolved, but please update and let us know if it persists.
