### ISSUE TITLE
Multiple separate windows

### ISSUE THREAD

**Issue by dreamlurch** [warpdotdev/Warp#5025]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Love this terminal and thanks so much for making it.  I'd really like to be able to open separate dedicated terminal windows.  is this already possible?  

### Is your feature request related to a problem? Please describe.

No problems

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @dreamlurch you're in luck. Warp supports global hotkey which you can configure to either open a dedicated window or show/hide all windows. You can find it in Settings > Features > Keys > Global Hotkey. Please learn more about it here and let us know if that meets your request/use case. https://docs.warp.dev/features/windows/global-hotkey#dedicated-window

![CleanShot 2024-06-14 at 13 39 13@2x](https://github.com/warpdotdev/Warp/assets/16809145/ef458969-c17c-4a0a-b9da-f15a447ff8ea)

**Comment by dannyneira** [comment]
Closing as resolved since the feature exists, but please let us know if any issues or if you're request is for something different provide details and reopen.
