### ISSUE TITLE
Unable to rebind "Close Pane"

### ISSUE THREAD

**Issue by claydugo** [warpdotdev/Warp#5032]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I would like the "Close Pane" action to be added to the "Configure Keyboard Shortcuts" settings panel.

![cant_rebind_close_pane](https://github.com/warpdotdev/Warp/assets/14915070/40c13823-26cc-4188-9eee-5be7de4cda66)

See above I was able to rebind the different splitting operations but "Close Pane" is not an option in the configuration panel and also defaulted to `⌘` which I personally do not know how to hit on my thinkpad ubuntu setup.

### Is your feature request related to a problem? Please describe.

I was shocked at how closely I was _almost_ able to recreate my `tmux` [workflow](https://github.com/claydugo/dotfiles/blob/main/.tmux.conf#L43) I have been using for 5+ years using the native keybinds on Warp. 

This last option is essential for me to have as I close and open panes constantly. This is the only holdout feature I need to make the switch.

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for letting us know @claydugo. 

The `CMD-W` is the default for closing all sessions, including windows, tabs, or panes.

Are we okay to close this since you found a viable option?

**Comment by claydugo** [comment]
> The CMD-W is the default for closing all sessions, including windows, tabs, or panes.

I guess I was trying to highlight how this default was difficult to find as a linux user. 

I am uncertain which button `⌘`  corresponds to on linux. I've tried ctrl, alt, and the windows key.

Anyway this isnt major to me which my solution above so if you all do not find it worth clearing up then I will close.
