### ISSUE TITLE
Pane Zoom/Maximize Indicator

### ISSUE THREAD

**Issue by claydugo** [warpdotdev/Warp#5041]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

A visual indicator that the tab you are on is visualizing maximized pane.

### Is your feature request related to a problem? Please describe.

Currently when you use the "Toggle Maximize Active Pane" feature to maximize a pane there is no visual indicator that this is the currently mode of the tab. 

Therefore you may forget until you do another pane operation like a split (possibly in the wrong direction due to assuming the current state is a 1 pane tab)

### Additional context

In `tmux` they visualize this by appending `-Z` to the pane name. I think this can be improved on however

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @claydugo Thanks for submitting this. Warp has a couple of ways to indicate you're in a maximized pane, the triangle in the corner indicates the active pane (maximized or not), while the double-arrows icon on the Tab indicates there is a maximized pane there. The Tab indicators can Enabled in the settings. https://docs.warp.dev/appearance/tab-indicators

I've added a demo of these two, Hope this helps!

https://github.com/warpdotdev/Warp/assets/16809145/e5e0116e-34a6-4d12-bb94-3c051e24cf39

Closing as this feature already exists in Warp, but feel free to let me know if any issues.
