### ISSUE TITLE
Warp command search doesn't prioritize workflows anymore

### ISSUE THREAD

**Issue by pascal-is-waging** [warpdotdev/Warp#5046]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Before the last update whenever I opened command search to look up my workflows the search would sort my predefined ones first, but now the search shows all the commands in the history.
This was such a good feature since I could have execute my predefined commands right away, I hope you guys can bring that back

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @pascal-is-waging Thanks for submitting. You can filter for Workflows in the `CTRL-R` [Command search](https://docs.warp.dev/features/entry/command-search#how-to-use-it). 

Activate a Workflow filter, by prepending your search term with the following: `workflows:`, `w:`, or press `W-TAB`.

Please let me know if this helps your use case. Closing as a filter method exists.

**Comment by pascal-is-waging** [comment]
Thank u Danny! That works, I didn't know about the w: and filter methods...
