### ISSUE TITLE
SSH immediately closes with "bash: can't open '/dev/fd/64': No such file or directory"

### ISSUE THREAD

**Issue by alycda** [warpdotdev/Warp#5047]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

```sh
ssh root@192.168.50.28

root@192.168.50.28's password:
bash: can't open '/dev/fd/64': No such file or directory
Connection to 192.168.50.28 closed.
```

trying to ssh in warp fails above. Using terminal works as expected.

the following works: `ssh root@192.168.50.28 'cd /var/log; exec $SHELL -l'` but then there is no prompt so I thought the connection not successful

### To reproduce

ssh to a device on the same network

### Expected behavior

I expected to see the welcome message (unable to share due to sensitive information)

### Screenshots

<img width="672" alt="Screenshot 2024-06-19 at 8 21 24 PM" src="https://github.com/warpdotdev/Warp/assets/1791092/c502e0b4-6a84-481a-9c90-44a6dde61c55">

<img width="486" alt="Screenshot 2024-06-19 at 8 21 44 PM" src="https://github.com/warpdotdev/Warp/assets/1791092/35f54a54-35e3-40a3-a3e2-8b952e38d178">

### Operating system

MacOS

### Operating system and version

Ventura 13.4

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2024.06.11.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I had to restart both my mac and my router after trying to connect via ssh with warp. my mac was connected to my wifi but unable to reach the internet. I don't know if that has anything to do with the problem, but it was unusual if it could be related.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

Ignore

**Comment by dannyneira** [comment]
Hi @alycda Sorry to hear about this issue. 

Warp has an SSH Wrapper that enables features (like the blocks, prompt, completions, etc.) on remote machines requiring the default prompt on the remote machine to be either `bash` or `zsh`.

As a workaround you can add `command ssh` to your `Settings > Subshells > Added commands` menu, then run `command ssh <user@server>` to connect to remote session, this will attempt to enable Warp features as a subshell.

You can also try disabling the SSH Wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabling, SSH should work as normal.

Related docs:
[https://docs.warp.dev/features/ssh](https://docs.warp.dev/features/ssh#ssh-wrapper-fails)
https://docs.warp.dev/features/subshells

If those don't work, please let us know.

**Comment by alycda** [comment]
that worked, thank you!
