### ISSUE TITLE
oh-my-zsh themes give issues

### ISSUE THREAD

**Issue by mandel-macaque** [warpdotdev/warp#505]
### Describe the bug

```shell
I have the following in my .zsrhc https://gist.github.com/mandel-macaque/074f370e5c13f2fd052f4168b49fa3b2 

The configuration does work fine with other terminal emulators without any issue, in wrap you can see in the screenshots that the prompt gets copied twice. On top of that, the second prompt message is on the right side and editable which means I have to remove it to be able to later type my commands.
```

### To Reproduce

Steps to reproduce:

1. Instal oh-my-zsh: https://ohmyz.sh
2. update the .zshrc to https://gist.github.com/mandel-macaque/074f370e5c13f2fd052f4168b49fa3b2 
3. Try to use the terminal.

### Expected behaviour

```shell
Be able to use the configuration like in kitty and iterm2.
```

### Screenshots

iTerm 2 looks:
<img width="1034" alt="Screenshot 2021-12-07 at 11 51 08" src="https://user-images.githubusercontent.com/2190086/145071669-eabec0dd-a9cd-4593-bd73-c9a9be5993e1.png">
Kitty:
<img width="645" alt="Screenshot 2021-12-07 at 11 59 59" src="https://user-images.githubusercontent.com/2190086/145073040-6d778673-40ab-487d-953b-5e903b7c39e1.png">
Warp:
<img width="1028" alt="Screenshot 2021-12-07 at 11 59 14" src="https://user-images.githubusercontent.com/2190086/145072883-0ec408ab-fac2-4843-93d1-61ffb48168cf.png">

### Operating System

MacOS

### OS Version

11.6.1 (20G224)

**Comment by mandel-macaque** [comment]
Looks like the issue comes from the oh-my-zs.sh which can be found [here](https://gist.github.com/mandel-macaque/a625360d47eaf5c1ebb077dc3cddb1c6).

**Comment by elviskahoro** [comment]
@mandel-macaque 
We're not compatible with some Oh-My-Zsh plugins, particularly themes. We have a GitHub discussion for Custom Prompts:
- https://github.com/warpdotdev/warp/discussions/422

For now though, the easiest way is to get up and running is to put theme and plugin related lines behind a flag, that disables them for Warp specifically:

```sh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# POWERLEVEL10K
# OH-MY-ZSH-THEMES
# OH-MY-ZSH-PLUGINS
# FIG
# BIND keys like:
	# bindkey "^j" down-line-or-beginning-search
# [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && 
	# . "/usr/local/etc/profile.d/bash_completion.sh"
	# eval "$(rbenv init -)"


##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi
```

**Comment by mandel-macaque** [comment]
@elviskahoro  I did fin that the following line was the culprit:
```
# gives problems with wrap
#POWERLEVEL9K_PROMPT_ON_NEWLINE=true
```
which makes sense due to the error.

**Comment by elviskahoro** [comment]
Gonna close this since the conversation around this is in the link I shared. Please share thoughts there!

**Comment by elviskahoro** [comment]
@mandel-macaque Thanks for sharing! I'm actually compiling a list of incompatible lines. This helps a lot.
