### ISSUE TITLE
Warp no longer accepts terminal commands and only accepts natural language

### ISSUE THREAD

**Issue by jeffreyzhen** [warpdotdev/Warp#5051]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I am no longer able to enter commands after the Agent AI update. Warp will only respond to natural language. "Loading prompt..." is seen in the background indefinitely.

### To reproduce

Launch Warp.

### Expected behavior

I can type both natural language and terminal commands.

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/13550272/c8797102-3ff4-4f22-a826-3144547b403f)
![image](https://github.com/warpdotdev/Warp/assets/13550272/1dc1f114-7d57-4be1-b8b4-6eaf7e570565)

### Operating system

MacOS

### Operating system and version

14.5 (23F79)

### Current Warp version

v0.2024.06.11.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

June 20, 2024 before Agent AI

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by zachbai** [comment]
Hey @jeffreyzhen, sorry you're hitting some trouble here. What's the behavior here if you try to execute a command? Does it just not execute/do nothing?

It's possible that the issue is actually with the shell session startup (the hanging "Loading prompt..." text usually indicates that shell startup is hanging)

**Comment by zachbai** [comment]
One follow-up to verify the above -- does the issue reproduce with a different default shell selection in settings?

<img width="533" alt="image" src="https://github.com/warpdotdev/Warp/assets/10970845/2390e319-3f4d-488a-ac91-cd0f2814335c">

**Comment by jeffreyzhen** [comment]
Hi @zachbai, when I try to execute a command nothing happens. The command I type stays in the input and nothing happens.

I use Default as the start up shell. I've changed it to zsh and bash and this still happens. I've commented out all of the text in my `.zprofile` and `.zshrc` as well but that also did not work.

**Comment by dannyneira** [comment]
Hey @jeffreyzhen Maybe you can try putting the result of `echo $SHELL` in your startup shell > custom setting.

Also, if you go to the AI settings and disable the input detection, then restart warp do you still see the issue?

**Comment by jeffreyzhen** [comment]
Hi @dannyneira, I don't see the option to add commands to my startup shell in Warp. However, when I put `echo $SHELL` in my `.zshrc` file, and use zsh as my Warp startup shell, it returns `/bin/zsh`.

If I disable the AI input detection and restart Warp, the issue still remains.

**Comment by dannyneira** [comment]
Thanks for trying, sorry if I wasn't clear. So In my example, I run `echo $SHELL` and get `/opt/homebrew/bin/zsh`. I then put that binary into Warp `Settings > Startup shell for new sessions > Custom` to see if that helps.

![CleanShot 2024-06-20 at 17 22 05](https://github.com/warpdotdev/Warp/assets/16809145/409ddf0e-522b-4904-b617-524bc28c58ff)

**Comment by jeffreyzhen** [comment]
Thanks for clarifying @dannyneira. Setting the custom executable for my startup shell to `/bin/zsh` still produces the issue.

**Comment by jeffreyzhen** [comment]
Hi all, I'm not sure what the issue was but restarting my machine fixed the issue. Thank you for your responses and your efforts in debugging.
