### ISSUE TITLE
Double pasting when using middle mouse button

### ISSUE THREAD

**Issue by Gabriel-p** [warpdotdev/Warp#5055]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Since the latest update every time I paste a command using the middle mouse button I get the command pasted twice. 

### To reproduce

1. Select a command with the mouse, e.g.: `git co develop`
2. Paste it in warp with the middle mouse button

### Expected behavior

I expect to see the same command pasted. Instead I get `git co developgit co develop`

### Operating system

Linux

### Operating system and version

elementary OS 7.1 (based on Ubuntu 22.04.3 LTS)

### Shell Version

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2024.06.18.08.02.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @Gabriel-p Thanks for letting us know. I'm having trouble reproducing this issue with the default SHIFT-CTRL-V shortcut. Are you using any `bindkey` in your rc file? This may be an issue as Warp doesn't support those. Also, check your keyboard shortcuts paste and set them to default to see if that helps.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by Gabriel-p** [comment]
The recent update appears to have resolved this issue
