### ISSUE TITLE
Agent Mode: `exit` evaluated as natural language

### ISSUE THREAD

**Issue by lucianthorr** [warpdotdev/Warp#5057]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

when I want to exit, Agent mode evaluates `exit` as natural language and then returns `exit` as the suggested command.

### To reproduce

type `exit` :)

### Expected behavior

exit

### Operating system

MacOS

### Operating system and version

macOS Sonoma

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.06.18.08.02.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @lucianthorr thanks for letting us know. I'm not seeing the same on my Mac, but this may be intermittent or related to something in your rc files. I'll let the team know and we'll investigate this. 

If you can please provide a video or screenshot of the issue. As a workaround, you can try adding `exit` the Settings > AI > Auto-detection deny list and it shouldn't trigger the AI for the time being.


![CleanShot 2024-06-24 at 17 08 35](https://github.com/warpdotdev/Warp/assets/16809145/011eb126-aa14-4eae-bb5c-552b98716b8a)

**Comment by lucianthorr** [comment]
Thanks for double checking.  It was like I couldn't turn off Agent Mode even after toggling it but now it seems fine.  I can't reproduce so either it was user error or maybe some weird state with the first terminal after the initial upgrade.  (probably the former).  Thanks again.
