### ISSUE TITLE
Settings text entry box (such as Font Size) does not show obvious cursor to note you can edit text

### ISSUE THREAD

**Issue by chamons** [warpdotdev/Warp#506]
### Describe the bug

```shell
In the settings text entry box (such as Font Size) does not show obvious cursor to note you can edit text. There is no flickering cursor or text selection.
```

### To Reproduce

Open Settings
Appearance Tab 
Click Font Size text box (13 by default)
Note no flashing cursor or highlighted text
Wait 10 seconds
Say, oh is it invisible, type something, note that it _did_ change

### Expected behaviour

```shell
See screenshots.
```

### Screenshots

Do i have the font size input focused or not?

<img width="358" alt="image" src="https://user-images.githubusercontent.com/6392201/145086696-befff3c7-9f0a-4df9-b80f-03c4ff4cf933.png">

Compare to

<img width="167" alt="image" src="https://user-images.githubusercontent.com/6392201/145086796-ae9150b2-a855-46fa-bbfd-b60d3d80a241.png">

### Operating System

MacOS

**Comment by elviskahoro** [comment]
This is just this particular theme
<img width="702" alt="Screen Shot 2022-01-20 at 3 34 18 AM" src="https://user-images.githubusercontent.com/29553206/150302337-72befbfa-143c-40d7-92f3-d3e79f3c380e.png">
.
