### ISSUE TITLE
Warp for Linux doesn't open a window

### ISSUE THREAD

**Issue by onx2** [warpdotdev/Warp#5060]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Installation seems fine but when I run the program it shows up in the task bar and doesn't open a window. It may be stuck on `winit window`?

### To reproduce

- Download warp for linux (.deb)
- Open with software installer
- Run warp
- Warp is running but there is no window

### Expected behavior

Warp opens a window when I run the program

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/23039725/07e6083b-f831-4379-b549-7dca1b8ede8f)
![image](https://github.com/warpdotdev/Warp/assets/23039725/dd28f9a3-1c75-4afb-a06a-ca2e01519a79)
 
![image](https://github.com/warpdotdev/Warp/assets/23039725/0af1268f-91ed-4edf-aa96-93fca2b1e675)
![image](https://github.com/warpdotdev/Warp/assets/23039725/980818f1-5bbe-46fe-a54a-051aeca131af)

### Operating system

Linux

### Operating system and version

Ubuntu 22.04.4 LTS

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment]
Hi @onx2 thanks for the detailed report. The graphics library we're using has issues with the VMWare drivers, see #4598 
Closing this out so we can consolidate updates on that issue.
