### ISSUE TITLE
Adding start and end times for blocks

### ISSUE THREAD

**Issue by zhiyuan-zhang0206** [warpdotdev/Warp#5064]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Sometimes, I need to know the start / end time of a block. If this info is recorded by Warp it would be great because I wouldn't need to log everything by myself, especially when running .sh scripts.
Maybe hitting some shortcut displays some metainfo about the block?

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @zhiyuan-zhang0206 Thanks for submitting. Currently if you're using the Default prompt in Warp, and you hover over the runtime, it will show start and end times for the block (although smallest unit of time is Minutes)

![CleanShot 2024-06-25 at 09 26 52](https://github.com/warpdotdev/Warp/assets/16809145/b81470c2-17c8-440f-b1eb-e39080e8bb3c)

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
We are also tracking a related request here. https://github.com/warpdotdev/Warp/issues/3975

**Comment by zhiyuan-zhang0206** [comment]
Thanks for the reply. 
I am using default prompt, I hovered over everywhere and the start and end times did not show.
However, as I dragged date and time down in the prompt configuration, like this:
![image](https://github.com/warpdotdev/Warp/assets/87293881/e8e57987-76fc-4e44-a0f4-8f316412bd38)
The start and the run time shows so it's enough for me anyway:
![image](https://github.com/warpdotdev/Warp/assets/87293881/8babe9cc-6b85-4390-bb59-7e3c6fee1f13)
