### ISSUE TITLE
DUP: Duplicate of #101 - Preferences is missing from the menu (but shortcut works)

### ISSUE THREAD

**Issue by chamons** [warpdotdev/warp#507]
### Describe the bug

```shell
I don't see preferences listed in the menu, but the shortcut works. 

See attached screenshots.
```

### To Reproduce

Launch warp.
Click through the menu look for preferences.

### Screenshots

<img width="233" alt="image" src="https://user-images.githubusercontent.com/6392201/145087407-d05a30f2-0fe3-471a-b061-a271b045c341.png">

<img width="208" alt="image" src="https://user-images.githubusercontent.com/6392201/145087576-1491449b-f360-4aaf-a3f8-f69d5f8e7aff.png">

**Comment by elviskahoro** [comment]
Being tracked here:
- https://github.com/warpdotdev/warp/issues/101
