### ISSUE TITLE
[agent mode] Attaching multiple blocks using the keyboard opens the shell history

### ISSUE THREAD

**Issue by youvegotmoxie** [warpdotdev/Warp#5088]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

The agent mode documentation states that after using CMD+up to attach a block to the context you can use the up arrow to add additional blocks. This triggers the shell history dialog instead of doing what's expected

https://docs.warp.dev/features/warp-ai/agent-mode

### To reproduce

Use bottom prompt
Enter agent mode with CMD+I
Use CMD+up arrow to attach a block
Use up arrow to attach an additional block and observe that the shell history opens

### Expected behavior

I expect warp to know it's in agent mode and not invoke the shell history dialog when attempting to attach blocks

### Operating system

MacOS

### Operating system and version

14.5 (23F79)

### Shell Version

zsh 5.9 (arm-apple-darwin22.1.0)

### Current Warp version

v0.2024.06.25.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @youvegotmoxie thanks for letting us know. Could you please provide a video or screenshot of the issue? I wasn't able to reproduce this on Mac. Are you using any custom keyboard shortcuts? check your Settings > Keyboard Shortcuts for anything bound to `CMD-I` on Mac which toggles Agent Mode, or `CMD-UP` which attaches the block in the "pinned to the bottom" input mode.

**Comment by youvegotmoxie** [comment]
https://github.com/warpdotdev/Warp/assets/2840886/9a45390e-b26b-4a8e-ac81-2ae02bca8db7

I checked and don't have any custom keyboard shortcuts that would interfere with `CMD-I` or `CMD-UP`
The key presses in the video are as follows: `CMD-I`, `CMD-UP`, `UP` which is how I'm interpreting the documentation to add an additional block using the keyboard

> To attach blocks to a query, you can use CMD-UP to attach the previous block as context to the query. You can then use your ARROW keys to pick another block.

**Comment by dannyneira** [comment]
@youvegotmoxie thanks for the video. I think the docs may not be accurate in that case. Attaching a block must include holding `CMD` on Mac. Also, if you want to attach multiple blocks you can hold `CMD` and click on the blocks you want to attach. Keep in mind there is a limit to the context you attach, just in case there are multiple large blocks of output.

I'll adjust the instructions in the docs for this.

**Comment by youvegotmoxie** [comment]
Thanks for the clarification
