### ISSUE TITLE
Option for New Session in New Window, Same Session in New Tab

### ISSUE THREAD

**Issue by baerkins** [warpdotdev/Warp#5089]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

It would be great to have an option where opening a new tab kept the same session in the same directory, but opening a new window starts a new session in the home directory. As far as I can tell, there isn't a way to differentiate between the sessions in tabs or new windows. If there is a way to do this...let me know :)

Coming from iTerm, this was a feature I found useful

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @baerkins Yes in Warp you can set a custom working directory for new windows, tabs, or panes. Just go to `Settings > Features > Session > Working directory for new sessions > Advanced. Then setup your preferences. Learn more in our docs. https://docs.warp.dev/features/working-directory

![CleanShot 2024-07-02 at 14 47 16](https://github.com/warpdotdev/Warp/assets/16809145/1782000d-6bbc-47df-a110-85775ccdeb7c)

 I hope this helps! Closing as this feature exist.
