### ISSUE TITLE
in postgresql CLI, navigation with option and command keys are not working

### ISSUE THREAD

**Issue by gokulk16** [warpdotdev/warp#51]
**Describe the bug**
In PostgreSQL CLI, was trying to navigate in a long query I had written but was not able to achieve it. it was misbehaving. 

**To Reproduce**
Steps to reproduce the behaviour:
https://www.loom.com/share/651c57af28e841a0bf16a9259e65e592

**Expected behaviour**
- Was expecting to move to the left one wor on pressing the 'option+left' arrow, but navigation went in the opposite direction.
- Was expecting to move to the beginning of the query when pressing 'Command+left arrow' but something else happens

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 11.3.1]

**Comment by michlimlim** [comment]
Thank you for reporting this! We just released the fix for this today in `v0.2021.08.11.15.36.stable_00`. Arrow keys with modifiers will now work for all CLIs and full-screen apps.
