### ISSUE TITLE
Possible errors of opening the terminal when connecting an external monitor

### ISSUE THREAD

**Issue by Sleon4** [warpdotdev/Warp#5105]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I am currently a Linux user (Debian 12 Bookworm). I have had conflicts when using warp on my PC.

For example... the common use on my PC is to open warp and work with Docker Containers, this seems to work fine without a doubt.

But I have decided to use an external display on my laptop for convenience, but warp for some reason makes my PC slow down somehow. In several cases my system stays completely still forcing me to force a restart of my PC.

I have discovered that turning the screen off and on again causes it to react again, a behavior that I do not understand.

I have found that closing warp and using another terminal is a solution, and in this way I have discovered that warp somehow causes these performance problems.

The external screen I use is an LG Ultragear (144HZ), but these problems do not exist when I am from another system like Windows 11, it only happens on my Debian 12.

Equipment specifications:
- Intel i5 10th 10300H x 8
- Nvidia GForce 1650 TI 4GB
- 32GB RAM
- M.2 512GB

I don't know what else I should add to this question.

### To reproduce

My PC gets completely stuck using Warp

### Screenshots

It is not possible to take screenshots since the PC is completely blocked when this happens

### Operating system

Linux

### Operating system and version

Linux Debian 12 (bookworm) - 64 Bits - Gnome v49.3 - Windowing System (X11)

### Shell Version

zsh (lts)

### Current Warp version

lts

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
Hi @Sleon4, thanks for filing and sorry for the issues you're experiencing with Warp.

A few questions for you:
1) Could you attach your Warp logs so we can debug further? https://docs.warp.dev/help/sending-us-feedback#gathering-warp-logs
2) Does this repro with if you force use of the integrated gpu? `Settings > Features > Performance > Prefer rendering new windows with integrated GPU(low power)`

**Comment by Sleon4** [comment]
Hello @alokedesai , I have done this solution:

"Does this repro with if you force use of the integrated gpu? Settings > Features > Performance > Prefer rendering new windows with integrated GPU(low power)"

It seems that everything works well again, thank you very much for your contribution, success in your developments.
