### ISSUE TITLE
Warp prompt doesn't respect custom line height setting

### ISSUE THREAD

**Issue by Advait-M** [warpdotdev/Warp#5111]
**Note from Warp: Short-term fix: use the default line height of 1.2! Proper fix coming in next release!**

### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Please 👍 this issue if you're facing this to help us track interest/affected users!

Warp prompt does not seem to respect custom line height setting (see below with example of 2.0), which results in issues, especially when using this with the new Same Line Prompt setting.

### To reproduce

1. Set line height to >1.2 (default) e.g. 2.0
2. Enable same line prompt with Warp prompt
3. Observe misalignment

### Expected behavior

Warp prompt and command should be aligned correctly.

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/12927474/3eae1403-8aff-473b-a649-de88ed6029ea)

### Operating system

MacOS

### Operating system and version

Sonoma 14.5

### Shell Version

zsh 5.9

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Advait-M** [comment]
We have a fix for this issue and it'll be in next week's release (Thursday) - however, we'd like to track the # of affected users (please upvote the top-level post here)! If there's a large number affected, we'll consider releasing a hot-fix!

**Comment by dotSpecs** [comment]
Same issue with you.

<img width="166" alt="image" src="https://github.com/user-attachments/assets/a7d37687-9bee-4dae-ad57-7d0082e7d2a3">

<img width="217" alt="image" src="https://github.com/user-attachments/assets/25584e10-6e05-4a12-8f9c-4b0acf21eacf">

**Comment by song54573** [comment]
It's not exactly the same problem as this one, but there is some correlation in that when I change line heights, neovim's cursor and text are supposed to be rendered in the middle of a line, with space above and below, but they're actually at the bottom, both in the editor text and in the file manager display.

**Comment by Advait-M** [comment]
@astnai @dotSpecs closing the loop here - the fix is live in the latest Warp release (`v0.2024.07.16.08.02.stable_03`). Please let us know if there's any continued issues - thanks 😄 !

**Comment by Advait-M** [comment]
> It's not exactly the same problem as this one, but there is some correlation in that when I change line heights, neovim's cursor and text are supposed to be rendered in the middle of a line, with space above and below, but they're actually at the bottom, both in the editor text and in the file manager display.

Hmm interesting, could you please open a new GH issue for this with screenshots to help clarify 👀 - thanks!
