### ISSUE TITLE
Open in Zed doesn't work

### ISSUE THREAD

**Issue by scullionw** [warpdotdev/Warp#5113]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Cmd+Clicking on a file path in the terminal does not open zed. It is correctly highlighted but does nothing

If i copy paste the path and just do `zed crates/predictions/src/pipeline/interp.rs:18:5` it opens perfectly, so zed is working fine.

<img width="591" alt="Screenshot 2024-07-11 at 6 32 51 PM" src="https://github.com/user-attachments/assets/355a57e1-c3b7-4748-ab3d-27dc4a4cc13c">

### To reproduce
0. Configure to open file paths in Zed
1. Cmd+Click on a file path (with row and column numbers)
2. Observe nothing happens

### Expected behavior

I expect Zed to open (like Vscode opens when i configure it to use vscode)

### Operating system

MacOS

### Operating system and version

14.3.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.07.09.08.01.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by davidmelvin** [comment]
Thanks for reporting this! We're actively working on it.

**Comment by j-mcnally** [comment]
same problem

**Comment by scullionw** [comment]
just tried (usually never run into this case), and yes it does work fine.

**Comment by davidmelvin** [comment]
Ok thanks! I've identified a fix. We'll get it out soon!

**Comment by davidmelvin** [comment]
This feature should be released in next-next week's release!

**Comment by davidmelvin** [comment]
No worries!

**Comment by j-mcnally** [comment]
Thank you @davidmelvin and team, this has allowed me to use Zed in my workflow, which i have been enjoying, this was a huge annoyance that is now fixed!

**Comment by davidmelvin** [comment]
Glad to hear it! :D
