### ISSUE TITLE
Warp terminal does not know which version it is on

### ISSUE THREAD

**Issue by Antdol** [warpdotdev/Warp#5116]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When opening Warp, I get a red banner with the message "Your app is out of date and some features may not work as expected. Please update immediately." and an "Update now" button. When I click on update now, the following command appears in the command line:
 
```bash
sudo apt update && sudo apt install warp-terminal && warp_finish_update PLJLXh6
```

After execution, Warp restarts and the banner is still there saying the same thing. When clicking on the update warp button, it tells me:
  - Current version is v0.2024.05.14.08.01.stable_04
  - Install update (v0.2024.07.09.08.01.stable_00)

When running the above command in another terminal, I get the following message:
**warp-terminal is already the newest version (0.2024.05.14.08.01.stable.04).**

### To reproduce

1. Open Warp terminal
2. If the red banner show up, click on update now
3. Press enter to execute command in the terminal
4. The terminal will restart automatically and the red banner will still be there

### Expected behavior

After updating, Warp should stop saying that the app is out of date and be aware of which version it is on.

### Screenshots

![warp_bug_before_update](https://github.com/user-attachments/assets/d6ba6421-b206-4af9-b139-01bf0d9caa95)
![warp_bug_after_update](https://github.com/user-attachments/assets/e860e0f6-0d0b-49e7-881a-dabbcc2111fa)

### Operating system

Linux

### Operating system and version

Ubuntu 24.04

### Shell Version

bash 5.2.21

### Current Warp version

v0.2024.05.14.08.01.stable_04

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

2024-07-11

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by vblanton** [comment]
I'm having the same exact issue here. after going through the update process multiple times i am still shown the same version info.
![Screenshot from 2024-07-12 14-48-27](https://github.com/user-attachments/assets/a119dd44-b11c-4ef0-9c16-3d0464974e88)

**Comment by dannyneira** [comment]
Hi Folks, Sorry to hear about this. We've seen similar issues reported in the part which have since been resolved. You may be able to work around this issue by running `apt-get install --only-upgrade warp-terminal`. I'll notify the team and we'll post updates on this thread.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by Antdol** [comment]
> I'm having the same exact issue here. after going through the update process multiple times i am still shown the same version info. Same system. Ubuntu 24.04 , Warp v0.2024.05.14.08.01.stable_04, Bash 5.2.21 ![Screenshot from 2024-07-12 14-48-27](https://private-user-images.githubusercontent.com/37779807/348266232-a119dd44-b11c-4ef0-9c16-3d0464974e88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjc4MzgsIm5iZiI6MTcyMTAyNzUzOCwicGF0aCI6Ii8zNzc3OTgwNy8zNDgyNjYyMzItYTExOWRkNDQtYjExYy00ZWYwLTljMTYtM2QwNDY0OTc0ZTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA3MTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ODhkZDcxYzY3MWMxYWE0YzgxNGYwN2MwYTQ2ZTY1ODM1MGMyZjI4MGFhNjMwM2U3YjVmZjkwMjgwN2QzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tqkj7pcEKVXCQ403HMtsnIrbj-U0TItAeXttozEbFGk)
> 
> Manually removing warp-terminal (apt remove warp-terminal) and re-downloading the latest deb from the website fixed the issue for me

Indeed, manually removing and reinstalling worked! Thank you

**Comment by AmirPeyravan** [comment]
✅ Confirmed fix (Ubuntu/Debian) for the “Update Warp” loop

Symptom:
Warp shows “Your app is out of date”. You click “Update Warp”, restart, and the banner comes back again.

Why it happens:
Warp was installed as a .deb, but APT isn’t using Warp’s official repo, so upgrades don’t actually pull newer builds.
You can spot this when `apt-cache policy` only shows the local dpkg entry.

✅ Step 1 — Check if APT repo is missing
Run:
  apt-cache policy warp-terminal

If you only see something like:
  100 /var/lib/dpkg/status
(and no `https://releases.warp.dev/...`), your system isn’t getting Warp updates from the official repo.

✅ Step 2 — Add Warp’s official APT repo + key, then upgrade
  sudo apt-get install -y wget gpg
  wget -qO- https://releases.warp.dev/linux/keys/warp.asc | gpg --dearmor | sudo tee /etc/apt/keyrings/warpdotdev.gpg >/dev/null
  echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main" \
    | sudo tee /etc/apt/sources.list.d/warpdotdev.list >/dev/null

  sudo apt update
  sudo apt install --only-upgrade -y warp-terminal

✅ Step 3 — Verify
  apt-cache policy warp-terminal
You should now see `https://releases.warp.dev/...` as the origin and the newer version installed.

Note:
If you `curl` an `InRelease` URL and get 404, that’s OK — this repo uses Release/Release.gpg and apt works fine.

✅ Still looping?
You might be launching another Warp install (AppImage/Flatpak/Snap). Check:
  readlink -f "$(command -v warp-terminal)"
  flatpak list | grep -i warp || true
  snap list | grep -i warp || true
