### ISSUE TITLE
after the latest update, whenever I am typing any command, the python interpreter is opening up

### ISSUE THREAD

**Issue by vsvanshi** [warpdotdev/Warp#5117]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Whenever i type any command into warp terminal, it goes into python interpreter mode with garbage values. Screenshot will help in understanding what I am trying to say

### To reproduce

Cannot say anything, it started with the latest update (v0.2024.07.09.08.01.stable_00)

### Screenshots

<img width="1680" alt="Screenshot 2024-07-12 at 6 03 18 PM" src="https://github.com/user-attachments/assets/bb15b631-0140-4c1b-a704-08bcfdc14633">
I had typed in the "ls" command both times and this is how warp is behaving

### Operating system

MacOS

### Operating system and version

Sonoma 14.5

### Shell Version

GNU bash, version 5.2.12(1)-release (aarch64-apple-darwin22.1.0)

### Current Warp version

v0.2024.07.09.08.01.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

11 July, 2024

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Advait-M** [comment]
hey @vsvanshi could you please provide your `.bashrc` file? Curious if you have anything in there that could be triggering a Python interpreter... It's quite weird that you didn't see this beforehand. 

I haven't seen any other reports of this yet and haven't been able to repro 👀 

Let me know if you're not comfortable sharing your rcfile here and you can also email it to my Warp email!

**Comment by vsvanshi** [comment]
@Advait-M I am using .bash_profile. I am attaching it here.
[br_copy.txt](https://github.com/user-attachments/files/16227998/br_copy.txt)

**Comment by dannyneira** [comment]
Hey folks, sorry to hear about this issue. The issue only appears when you have the python in the path. I was able to reproduce this and I'll let the team know. As a stopgap, you can put the Python path line in a conditional to disable it for Warp. For example:
```
  ### Disable just for Warp
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
  # What you want to disable here
  export PATH="/opt/homebrew/bin/python3.10:$PATH"
fi
```

**Comment by vsvanshi** [comment]
Thanks for checking it out @dannyneira . I can verify that Warp terminal is working fine with python path disabled/conditionally configured. 
Would be great to know if Warp can fix this issue permanently.

**Comment by rizwandelphia** [comment]
Slight deviation but worked for me as well, thank you!

If the above doesn't work for anyone else then here's another option (note your path may be different here)
```
if [[ "$TERM_PROGRAM" == "WarpTerminal" ]]; then
    export PATH=$(echo "$PATH" | awk -v RS=: -v ORS=: '!/\/usr\/local\/bin\/python3/') # Remove python from PATH
    PATH=${PATH%:} # Remove possible trailing colon that might be left
fi
```

**Comment by Advait-M** [comment]
Hey folks! Thanks for flagging this 😄 - **we identified the root cause on our side and a fix is live. Please update to `v0.2024.07.16.08.02.stable_02` where you should no longer need the workaround above.**

Please let us know if you're still facing any issues.

CC @rizwandelphia @vsvanshi
