### ISSUE TITLE
Hot Key window assignment does not always persist 

### ISSUE THREAD

**Issue by samkrishna** [warpdotdev/Warp#5120]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I REALLY want to switch to Warp full-time. However, the inability of the Warp Terminal to keep its Hot Key window assigned to my Screen 4 is a real buzz kill and keeps me using iTerm2 just because iTerm2's Hot key support is bulletproof and has been for over a decade.

What happens intermittently is that I'll configure the Warp Hot Key window to use my Screen 4 BUT sometimes when I come back to my system and unlock my MacBook Pro and invoke the Hot Key window, the window sometimes opens in Screen 2, the laptop monitor, or Screen 3.

Sometimes it does the right thing and works on Screen 4, but I have found that that is not a bulletproof screen assignment that persists no matter how long Warp has been running.

Hardware configuration:

MacBook Pro M1 Max
3 ViewSonic 27" HDMI monitors

![Screenshot 2024-07-12 at 14 04 37](https://github.com/user-attachments/assets/deca3728-681c-472e-9bfb-fe717936bf81)

### To reproduce

The problem is intermittent as I've described.

### Expected behavior

Hot Key window always works on Screen 4.

### Operating system

MacOS

### Operating system and version

14.5.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.07.09.08.01.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I can *reset* the Hot Key to Screen 4 if the bug appears, but why should I have to do that. I **REALLY** want to love this terminal, but it just seems that the Warp developers love doing cool stuff like AI and blocks and internal development with Rust at the expense of a GREAT Hot Key experience. 

I tolerate having to set the Hot Key sequence to Option-Escape because I have never been able to get Command-Escape to work correctly. I'll live with that, but not the sometimes-moving Hot Key window.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @samkrishna Sorry to hear about this issue. You may be able to workaround this by using "Active screen" instead of a specific screen number. Also, make sure you don't have another window manager app like rectangle that may override the default behavior of the hotkey window.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.
