### ISSUE TITLE
Virtual Env not shown when shell prompt is enabled.

### ISSUE THREAD

**Issue by ahmedivy** [warpdotdev/Warp#5122]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

After enabling shell prompt from settings, warp does not show python's virtual env enabled (badge) when virtual env is activated.

### To reproduce

Select Shell Prompt from settings instead of Warp default prompt.
1. Create a virtual env in new directory.
`python -m venv .venv`
2. Activate
`source .venv/bin/activate `

### Screenshots

<img width="735" alt="image" src="https://github.com/user-attachments/assets/c0b2e22d-9367-4aa7-bb19-8df21a5871be">

### Operating system

MacOS

### Operating system and version

14.5.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.07.09.08.01.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alor** [comment]
just update warp and noticed the same thing. I was here to report the same regression. thanks

**Comment by Sailesh-2209** [comment]
+1 Even I am facing the same issue

**Comment by Advait-M** [comment]
Hey folks! Thanks for reporting - we've identified the root cause and we should have a fix in this week's release! I'll re-ping this thread once it's out and ask folks to confirm 😄 !

**Comment by Advait-M** [comment]
Howdy - please update to `v0.2024.07.30.08.02.stable_01`, the fix should be live! Let us know if you're still facing any issues @Sailesh-2209 @ahmedivy ! 😄
