### ISSUE TITLE
After ssh remote login, the block feature, mouse control cursor, control+, wake up AI functions are invalid（ssh 远程登录后 block feature，鼠标控制光标，control+、唤醒 ai 功能失效）

### ISSUE THREAD

**Issue by geekvee** [warpdotdev/Warp#5124]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

After ssh remote login, the block feature, mouse control cursor, control+, wake up AI functions are invalid（ssh 远程登录后 block feature，鼠标控制光标，control+、唤醒 ai 功能失效）
<img width="1463" alt="Xnip2024-07-14_00-16-54" src="https://github.com/user-attachments/assets/12182f3d-1b4e-441d-a7db-67b2d0974bc6">
<img width="1462" alt="Xnip2024-07-14_00-17-30" src="https://github.com/user-attachments/assets/0cfa88fa-d703-4462-915a-bab43e86375e">
Under normal circumstances, for example, if there is no ssh login and it is just a local operation, each command and output will become a block, the mouse can directly control the jump cursor, and the control+, key can call out the ai function, similar to Figure 1. However, after ssh login to the remote secondary weapon, the most intuitive thing is that the block function is gone, similar to Figure 2. I have consulted the information but cannot solve this problem. Does anyone know how to set it so that the above functions can still be used after ssh login to the server?（正常情况下，例如没有 ssh 登录，只是在本地操作，每一个命令以及输出都会变成一个 block，鼠标可以直接控制跳转光标，control+、按键可以呼出 ai 功能，类似于图一，但是 ssh 登录远程副武器后，最直观的就是 block 功能没有了，类似图二，我查阅了资料无法解决这个问题，请问是否有人知道如何设置可以使得 ssh 登录服务器后依旧可以使用上述功能）

### To reproduce

1. ssh connect a server， like ： ssh -o ServerAliveInterval=200 root@ip -p port
2. use some command， like：ls， cd， tree
3. you will find， no block feature

### Operating system

MacOS

### Operating system and version

Sonoma 14.5

### Shell Version

zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by geekvee** [comment]
i have fix it

**Comment by Henry-nlp** [comment]
> i have fix it

how did you fix it ? could you share. I encountered the same problem...
