### ISSUE TITLE
Unable to use warp with custom prompt

### ISSUE THREAD

**Issue by z4nD4R** [warpdotdev/warp#513]
### Describe the bug

```shell
Basically Warp becomes unusable with custom zsh prompt i.e. via oh-my-zsh theming.
```

### To Reproduce

Steps to reproduce:
1. Install `zsh`
2. Install `oh-my-zsh` 
3. Set some theme in `.zshrc`
4. Start Warp with `zsh` shell

### Expected behaviour

```shell
Warp would accept custom zsh prompt
```

### Screenshots
<img width="1026" alt="Snímka obrazovky 2021-12-09 o 8 00 14" src="https://user-images.githubusercontent.com/13903889/145351326-8ee3f71e-50ca-418f-928e-ddf2dec22422.png">

### Operating System

MacOS

### OS Version

12.0.1

**Comment by elviskahoro** [comment]
Hey @z4nD4R. Warp is currently incompatible with some ZSH plugins and some ZSH Themes. We plan on building a custom prompt. See this GitHub discussion:
- https://github.com/warpdotdev/warp/discussions/422

Closing this as we're keeping all prompt related discussions in the discussion thread.
