### ISSUE TITLE
Pink screen on latest version

### ISSUE THREAD

**Issue by duhizjame** [warpdotdev/Warp#5132]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Since updating to latest version, warp wont start and shows a pink screen, like on the provided screenshot.

![Screenshot 2024-07-17 at 00 00 16](https://github.com/user-attachments/assets/18b45172-1cba-4053-af74-f05776c882b9)

### To reproduce

I have updated using the "update wasp" button on the top right. Sadly I cannot check what was the previous or the current version of warp, since the application is unresponsive. I would try reinstalling, but I dont want to lose my workflows.

### Screenshots

![Screenshot 2024-07-17 at 00 00 16](https://github.com/user-attachments/assets/18b45172-1cba-4053-af74-f05776c882b9)

### Operating system

MacOS

### Operating system and version

14.5.0

### Current Warp version

v0.2024.07.09.08.01.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

16.08.2024

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @duhizjame sorry to hear about this. This is a known issue with MacOS after an update, and may affect other app, not just Warp. Restart your machine should resolve the issue.

Hope this helps, please let us know if the issue persists.

**Comment by duhizjame** [comment]
thanks for the fast response :) I will update the ticket after restarting a bit later on the day.

**Comment by duhizjame** [comment]
Closing the issue. Restarting the machine solved it.

**Comment by Caffeine19** [comment]
> Hi [@duhizjame](https://github.com/duhizjame) sorry to hear about this. This is a known issue with MacOS after an update, and may affect other app, not just Warp. Restart your machine should resolve the issue.
> 
> Hope this helps, please let us know if the issue persists.

Hi, I also encounter this issue on other apps, such as WeChat. Is there Any Apple Software Manager or just Tim Cook we can mention to fix it, it's already 2025 and this problem hasn't been fixed at all. It's really driving me crazy.
