### ISSUE TITLE
Updating on Ubuntu 24.04

### ISSUE THREAD

**Issue by krillavilla** [warpdotdev/Warp#5133]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

The update button keeps appearing when starting up Warp Terminal.

![Screenshot_20240716_180342](https://github.com/user-attachments/assets/acbfd770-5f7e-4371-971a-4e2e1bea719c)
![Screenshot_20240716_180821](https://github.com/user-attachments/assets/d63413de-be70-4dc7-ae96-980be91882ae)

I cannot get rid of it. 

### To reproduce

I could not reproduce it.

### Operating system

Linux

### Operating system and version

Ubuntu 24.04

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by hazirliver** [comment]
Hi!
I have the same issue and also I'm on Ubuntu 24.04
Today to regular `Update Warp` button, new red line was added. It's annoying...
![image](https://github.com/user-attachments/assets/fe704ed7-7c95-4fa1-b0a4-606e5a248a61)

**Comment by hernanijr** [comment]
I have the same issue

**Comment by andreimatei** [comment]
Same for me. I update over and over, and yet the old version of the app seems to start (notifying me that it needs an update).

**Comment by andreimatei** [comment]
The instructions in [this comment](https://github.com/warpdotdev/Warp/issues/4955#issuecomment-2143093140) seem to have solved the issue for me.

**Comment by hernanijr** [comment]
> The instructions in [this comment](https://github.com/warpdotdev/Warp/issues/4955#issuecomment-2143093140) seem to have solved the issue for me.

Thanks, it worked here too.

**Comment by dannyneira** [comment]
Hey Folks, by any chance did you recently update Ubuntu to version 24 (from v23.1 or older)? I suspect this issue is related to Ubuntu updates not carrying over the Warp repository since the workaround seems to be manually adding the repository again.

**Comment by dannyneira** [comment]
Hi folks, The workaround is to add the warp repository and you should be able to run the update.
```
sudo apt-get install wget gpg
wget -qO- https://releases.warp.dev/linux/keys/warp.asc | gpg --dearmor > warpdotdev.gpg
sudo install -D -o root -g root -m 644 warpdotdev.gpg /etc/apt/keyrings/warpdotdev.gpg
sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main" > /etc/apt/sources.list.d/warpdotdev.list'
rm warpdotdev.gpg
sudo apt update && sudo apt install warp-terminal
```
We're tracking this particular issue here. https://github.com/warpdotdev/Warp/issues/5201

I'll close this as a duplicate, but please let me know if the issue persists after you add the repo with the command above.
