### ISSUE TITLE
Broken in OSX - Copy / Paste File or Directory to get full path in warp

### ISSUE THREAD

**Issue by jq-87** [warpdotdev/warp#514]
### Describe the bug

```shell
Warp version: v0.2021.12.06.19.09.stable_00

In stock OSX `terminal` app we can copy items from `finer` then pasting into terminal displays full path of copied item. 

Warp currently does not do this.
```

### To Reproduce

Steps to reproduce:
1. Copy File or Directory from `finder` app (command + c)
2. Try pasting the file/directory into warp input (command + v) - you get get directory name

### Expected behaviour

```shell
After step 2 File/Directory path SHOULD display in warp input but currently it does not.
```

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
Thanks for sharing this! I didn't know Iterm had this feature.
