### ISSUE TITLE
Japanese text do not appear while IME conversion.

### ISSUE THREAD

**Issue by leo271** [warpdotdev/Warp#5141]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When using the Japanese IME for text input on the command line, there is a bug where the unconverted text (kana input) does not display as it is being typed. The text only becomes visible after the conversion (to kanji or other characters) is completed and committed. This issue makes it difficult to see and edit text before completing the conversion.

### To reproduce

1. Open the command line interface.
2. Switch to the Japanese IME.
3. Start typing in Japanese (e.g., kana input).
4. Observe that the unconverted text does not appear on the command line.
5. Complete the conversion (e.g., press the spacebar to convert kana to kanji).
6. Notice that only after the conversion is committed, the text appears on the command line.

### Expected behavior

The unconverted text should be visible on the command line as it is being typed, allowing users to see and edit their input before committing the conversion.

### Screenshots

<img width="333" alt="Screenshot 2024-07-19 18 18 22" src="https://github.com/user-attachments/assets/5e94e161-42c1-4941-a7ea-f160b10841e2">

### Operating system

MacOS

### Operating system and version

14.5.0

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.07.16.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

2024/07/19

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by leo271** [comment]
This issue was the same as #4529

**Comment by ryofurue** [comment]
This issue is closed and "completed" . . . But I have (what I think is) the same problem.

Warp v0.2025.03.26.08.10.stable_02
macOS 15.3.2 (24D81)
