### ISSUE TITLE
DUP: Duplicate of #333 - Is warp based on Python2 ?

### ISSUE THREAD

**Issue by haitch** [warpdotdev/warp#515]
### Describe the bug

```shell
I got a warning on Mac says python2 will be deprecated.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Operating System

MacOS

**Comment by elviskahoro** [comment]
Warp isn't based on python 2. This is just a message because of some monterrey stuff. There's something in your rc or path that has a python dependency and macos thinks it's Warp.

**Comment by elviskahoro** [comment]
See:
- #333
