### ISSUE TITLE
Terminal Tab Title

### ISSUE THREAD

**Issue by iamngoni** [warpdotdev/Warp#5156]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

My terminal tab window says modestnerd@Bill-Lenovo, the modestnerd part is correct but the @Bill-Lenovo is not and weird. 

![Screenshot 2024-07-22 at 23 07 35](https://github.com/user-attachments/assets/d033a6a5-d9c4-4cd5-b33b-9e972971c7a3)

### To reproduce

Just open the warp app

### Expected behavior

Information related to my computer

### Screenshots

![Screenshot 2024-07-22 at 23 07 35](https://github.com/user-attachments/assets/d5c215ed-ac6a-427c-a19b-9a2d80c386c9)

### Operating system

MacOS

### Operating system and version

15.0.0

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.07.16.08.02.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Additional context

![Screenshot 2024-07-22 at 23 07 35](https://github.com/user-attachments/assets/0df163f2-c4ba-4e80-aa6a-71ed9bd1c5a4)

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment]
Hi @iamngoni thanks for reporting.

> @Bill-Lenovo is not and weird

Can you elaborate here? The default is to use zsh's config for the title, and that is what zsh believes your computer's hostname is. Are you expecting a different hostname? What do you see when you run `hostname` command? Or perhaps for the hostname to be omitted? What is the title in a different terminal?

**Comment by iamngoni** [comment]
@acarl005 thanks figured out what the issue is. It's only for me (not an issue really 🙏)
