### ISSUE TITLE
Clear command issue 

### ISSUE THREAD

**Issue by ShreehariVaasishta** [warpdotdev/Warp#5160]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

The clear && echo "Hello World" command in Warp Terminal does not produce the expected output.

### To reproduce

1. Open Warp Terminal.
2. Type `clear && echo "Hello World"` and press Enter.

Any other commands output after `clear` are not shown, for eg:
`> clear && kustomize build overlays/staging/`

### Expected behavior

The terminal screen should be cleared, followed by the text "Hello World" being printed on the next line.

### Operating system

Linux

### Operating system and version

Fedora Linux 40 (Workstation Edition) x86_64

### Shell Version

zsh 5.9 (x86_64-redhat-linux-gnu)

### Current Warp version

v0.2024.07.16.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment]
Hi @ShreehariVaasishta thanks for the feedback. Warp overwrites the `clear` command to implement it in a way that better aligns with Warps blocks. Unfortunately, it is asynchronous and so other commands in that same block might get cleared away.

One workaround you could consider is directly calling the original clear command, perhaps by a direct path, something like `/usr/bin/clear`, or maybe something like `command clear` instead. Side-stepping Warp's version of clear may cause some visual issues.

**Comment by ShreehariVaasishta** [comment]
Thanks for the response @acarl005 . Since its not affecting my eveyday work, it should be fine.
Thanks again!

**Comment by SilentGlasses** [comment]
Can it be made so that clear simply closes out the previous block then run any other commands after it as the next block?

**Comment by dannyneira** [comment]
decoupling clear from commands is a request we're tracking here. https://github.com/warpdotdev/Warp/issues/2382

Other than what was suggested above, you could also press `CTRL-L` to clear the screen, this works even with a command in the input editor

https://github.com/user-attachments/assets/096b4a83-0022-401b-9433-a5881202335f

**Comment by ShreehariVaasishta** [comment]
Thanks @dannyneira for the support.
Will close this issue as its a duplicate one.
