### ISSUE TITLE
Warp conflicts with codium Ai coding assistance. 

### ISSUE THREAD

**Issue by marvin-hansen** [warpdotdev/Warp#5161]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

This is bug has been around for at least 2 - 3 months, but I've finally got the time to fill a report.

When you run the Codium Ai assistance in any IDE, it's working fine. If you use a normal mac terminal, it runs fin. If you use iTerm, it runs Fine. The moment you start warp and enter a command, Codium looses connection to its local llvm, grays out, and stops working until you restart the IDE and the Codium plugin gets reloaded. It's a serious bug and I suspect that Codium and Warp access the same port locally. 
 

### To reproduce

1) Install free version of Codium Ai in your favorite code editor
2) Open codium and enter a test prompt, i.e. improve code in method foo
3) Start Warp and enter whatever command, i.e. ls 

Boom, Codium is done. 

### Expected behavior

Warp really shouldn't tank any other application. 

### Screenshots

<img width="511" alt="Screenshot 2024-07-23 at 1 22 32 PM" src="https://github.com/user-attachments/assets/df769e1d-45f5-4391-8366-f99be2204ec9">

### Operating system

MacOS

### Operating system and version

MacOs 14

### Shell Version

3.2.57(1)-release (arm64-apple-darwin23)

### Current Warp version

v0.2024.07.16.08.02.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

The bug is came at least 2 to 3 months ago

### Additional context

I have to use another terminal as workaround as I depend Codium Ai assistant on my work. 
The other thing is, I find it really hard to make fill an issue with Codium when this bug does not occur with any other terminal
so as far as I am concerned, having to chose between Warp and Codiu, Warp is out of the door because there are so many other terminal available that don't bomb my work. 

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment]
Hi @marvin-hansen thanks for reporting the issue. I tried with the VSCode Codium AI extension and that seems to be working fine when used concurrently with Warp AI. I'd like to try with your setup specifically. What editor are you using? And what sequence of steps resulted in that screenshot?

**Comment by marvin-hansen** [comment]
That’s interesting.

I’m using JetBrains RustRover for all my current work. Sorry I didn’t
mention this in the first place. Saw the same issue in another JetBrains
IDE I believe last month.

**Comment by acarl005** [comment]
> Codium looses connection to its local llvm

Can I ask for clarification here? Do you mean a local LLM? I'm not very familiar with Codium AI. On my device, it seems to be communicating with a remote model. Wondering if that's configurable.

I wonder if there may be an issue due to shared use of the GPU between Warp and a local LLM?

**Comment by marvin-hansen** [comment]
I think codium starts a local service and communicates via that service. I
haven’t looked into the details. But what’s happening all the time is
simply that, when you input something into warp, codium loses connection
immediately and stops working. There was an update a few days ago that
added a retry button to codium that may or may not work after codium lost
connection.

I’m on Mac and as far as I understand it, you can only go through metal for
gpu so I wouldn’t necessarily bet too much on conflicting gpu access.

May have to fill a separate issue with codium tomorrow to see if they can
figure this out.

**Comment by marvin-hansen** [comment]
A recent Codium update has fixed the issue.
Closing this for good.
