### ISSUE TITLE
Add a custom keybinding to toggle custom keybindings

### ISSUE THREAD

**Issue by slimreaper35** [warpdotdev/Warp#5164]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Currently, to open the right panel for customized shortcuts, I have to use `Ctrl` + `/.`
It would be nice to be able to customize that as well.
For example, some people (including me) might have reserved this shortcut for Vim bindings, like commenting out a line.

### Is your feature request related to a problem? Please describe.

Also, VS code [uses](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf) `Ctrl` + `/` for a single-line comment.

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by acarl005** [comment]
Hi @slimreaper35. Great profile pic!

This should be customizeable in our "keyboard shortcuts" page in our settings. Search for the "Toggle Keyboard Shortcuts" binding.

<img width="686" alt="Screenshot 2024-07-24 at 10 09 43" src="https://github.com/user-attachments/assets/bee59ed0-b113-4935-bbd0-db87a125acc0">

**Comment by slimreaper35** [comment]
I am blind. Thank you very much. It works perfectly.

**Comment by acarl005** [comment]
We'll consider maybe removing this as a default. `ctrl-/` is a highly contested keybinding with a risk of conflict.
