### ISSUE TITLE
Nano editor showing duplicated text

### ISSUE THREAD

**Issue by chlocoh** [warpdotdev/Warp#5166]
### Dupe Check

- [X] I have [searched Warp SSH issues](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ASSH) and there are no duplicates

### Operating System

MacOS

### Operating System and Version

Sonoma 14.5

### Local Shell Version

5.9

### Remote Shell Version

5.0.17(1)-release

### Warp Version

v0.2024.07.16.08.02.stable_03

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

_** Not sure what the above checkbox is about, so did not do that but checked it off anyway._

**I am running on a macbook and I ssh into a vm running ubuntu 20.04.6 LTS**

I first noticed this when editing a gitlab-rebase-todo file

----

With any text file that already has some lines in it, if I am editing the file in nano, I see an issue where text gets duplicated and the screen becomes malformed. This occurs when I hit backspace on a line that take me to the previous line. Instead of taking me to the previous line, it looks like it duplicated the line I was already on. 

1. starting point:
![starting point](https://github.com/user-attachments/assets/073ffa14-552b-4a1f-a4ea-9efb719824d2)

2. after hitting backspace from the beginning of line 2 to line 1:
![after hitting backspace to the previous line](https://github.com/user-attachments/assets/9f92986d-039f-4bee-985b-7547597460fc)

Scrolling up and down with the mouse wheel does not make a difference. However if I resize the terminal, the text sometimes goes back to normal or sometimes shows many repetitions of the same nano screen.

3. after resizing the terminal window:
![after resizing terminal window](https://github.com/user-attachments/assets/19cb16fd-f06c-4702-a289-24a8e40c1e09)

** Note where the scroll bar is on the right. When I scroll up and down after resizing the window, I just see the repeated editor screen

### Include shell xtrace output

Ran this but it didn't show any different output than what I normally see when I ssh into my vm

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by acarl005** [comment]
Hi @chlocoh thanks for reporting the issue! Do you have any nanorc file? `~/.config/nano/nanorc`
