### ISSUE TITLE
Joining Discord blocked by invalid phone-number message.

### ISSUE THREAD

**Issue by Abstracting** [warpdotdev/Warp#5167]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When using the Verify phone-number in Discord server, i get invalid phone-number message.

### To reproduce

![Screenshot from 2024-07-24 07-53-22](https://github.com/user-attachments/assets/4ff2cda2-7a46-4758-aa75-cba3ef929026)
Clicking verify, selecting Norway and entering full number (8 didget)
Completing "I am human"
Then error:
![Screenshot from 2024-07-24 07-52-48](https://github.com/user-attachments/assets/7c747da7-5db1-4996-a228-0ab429cb69dd)

### Expected behavior

Phone-number is valid so should work

### Operating system

Linux

### Operating system and version

Fedora 40

### Shell Version

bash 

### Current Warp version

Not relevant

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

If this is wrongly posted here i apologize. 

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Archigos** [comment]
Hello... My guess is that you're entering you Country Code as part of you phone number (based on the screenshot)...
So, if you're country code is in fact `+47` you leave that part of your phone number out when you enter it in the box... (unless you're unlucky and your actual phone number starts with the same numbers as your Country code... and if that's the case, it's probably a Discord issue.

**Comment by dannyneira** [comment]
Hi @Abstracting thanks for letting us know, sorry to hear about this issue. If Archigos suggestion above doesn't work I recommend you try a free virtual phone number like [google voice](https://voice.google.com/u/0/about) to verify the discord acount.

**Comment by JonSpeare** [comment]
No, I am not entering the number with the country code, but the first two of the eight digits are "47". I just redacted  the rest for in picture privacy reasons.

Google Voice is not supported in Norway.

**Comment by SilentGlasses** [comment]
Hey @Abstracting Are you using a VOIP or Landline number by chance?  Those are not supported on Discord.

Either way, this is not a Warp issue but a Discord issue.

Per Discrord:
```
VOIP, Burner, or Landline numbers cannot be used. 
```

I think by burner they mean pre-paid phones.

**Comment by Abstracting** [comment]
It's a 100% normal cellphone number that I have had, and used, for 15 years. 8 digits, like everybody else in Norway. Not a burner or landline. Just a plain old phone number on Scandinavia's largest carrier (Telia), with a normal SIM in a normal iPhone, that can send and receive SMS and make call like normal. Not a business subscription. As mundane as can be.

**Comment by Archigos** [comment]
We're not saying that you're wrong or anything like that. When someone creates a discord server they had the option of selecting the verification. They never see this info. They have no control over the verification process. That's all discord. So if you're having an issue with it this is discord's fault and not anything to do with Warp.

**Comment by Abstracting** [comment]
Understood. We can close this issue then.

**Comment by dannyneira** [comment]
@Abstracting Thanks for understanding, please submit a ticket with the discord team here and let them know. https://support.discord.com/hc/en-us/requests/new

Closing this one but feel free to let us know if any issues once you're in the discord.
