### ISSUE TITLE
New tab placement dropdown adds options after changing selection

### ISSUE THREAD

**Issue by matthiasthieroff** [warpdotdev/Warp#5168]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

After each change of the "New tab placement" setting in Settings -> Features the dropdown gains two more options. This is permanent as long as Warp is runnning (re-open the Settings does not reset the dropdown).

### To reproduce

1. Go to Settings -> Features
1. Open the "New tab placement" dropdown
1. There are the expected 2 options: "After current tab" and "After all tabs"
1. Change the current placement
1. Open the dropdown again
1. Now there are 4 options (duplicates of the first 2) 

### Expected behavior

The number of options should stay the same after changing the selected option.

### Screenshots

<img width="705" alt="image" src="https://github.com/user-attachments/assets/153d4aec-698d-4c5f-aec2-6ed58529924e">

### Operating system

MacOS

### Operating system and version

Sonoma 14.5 (23F79)

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.07.16.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @matthiasthieroff Good catch, thanks for letting us know! We've worked on a fix and it should be in next weeks' release.

**Comment by dannyneira** [comment]
Hi @matthiasthieroff this issue has been fixed in the latest version of Warp. 

Closing this as resolved, but please feel free to update and let us know if there are any issues.
