### ISSUE TITLE
Can't launch warp

### ISSUE THREAD

**Issue by eliwind** [warpdotdev/warp#517]
### Describe the bug

Opening warp, I see "Seems like your shell is taking a while to start..." and never get to a prompt where I can do anything.

I have a fairly elaborate terminal setup (oh-my-zsh, tmux, fancy prompt shenanigans), some of which I presume are interfering. But it is very hard to tell what the problem is, or what the path might be to trying out warp.

### To Reproduce

Steps to reproduce:
1. Launch Warp
2. ... wait ...
3. ... keep waiting ...
... never gets interactive.  I just see a "Seems like your shell is taking a while to start" banner.

### Expected behaviour

```shell
Expect to eventually get to a command prompt
```

### Screenshots

<img width="1136" alt="Screen Shot 2021-12-09 at 5 42 17 PM" src="https://user-images.githubusercontent.com/5287231/145487356-88bc422f-8483-4657-babb-7d62e158774d.png">

### Operating System

MacOS

**Comment by elviskahoro** [comment]
@eliwind Can you email me? I'll help you debug!
Will close this for now as we're working on a guide.
