### ISSUE TITLE
Editing long commands is very cumbersome

### ISSUE THREAD

**Issue by C0D3-M4513R** [warpdotdev/Warp#5170]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When editing a long command, where you need to scroll to see the end, the scroll snaps back to the top. Often that's immediately as soon as you start scrolling, but at the very least as soon as any additional character is typed. This makes it extremely cumbersome and hard to edit long commands.

### To reproduce

1. Type in a long command. Ideally copy & paste a really long command in.
2. Try to Scroll to the end
3. Sometimes it is even impossible to do that, and the scroll snaps back here to the top already
4. Try to edit the command
5. The scroll snaps back to the top, as soon as any character is typed or deleted

### Expected behavior

The scroll let's me scroll to the end of the command and doesn't snap back to the top as soon as a character is typed

### Screenshots
![image](https://github.com/user-attachments/assets/a9a8c539-1f59-48db-aea1-4ced18bf1174)

### Operating system

Linux

### Operating system and version

Nixos 24.05

### Shell Version

bash 5.2.26(1)

### Current Warp version

v0.2024.07.09.08.01.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

Unknown

### Additional context

I'm using Kde Plasma 6 on Wayland.

<details><summary>nix-info</summary>
<p>

```
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.40-rt36, NixOS, 24.05 (Uakari), 24.05.20240721.63d37cc`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos-24.05"`
 - nixpkgs: `/nix/store/lzhqf5y9dcgfkg5f7f96jjc814pgrsqy-source`
```
</p>
</details>

You can work around this issue, by copy & pasting the command into a text editor and Search & Replacing e.g. ` --` to ` \\\n--`, to convert the command into a multi-line command, which works fine.
If no solution to very-long one-line commands can be found, this might be good alternative for most use-cases (commands with strings and long strings come to mind as a couple exceptions, where this ofc would not work). 

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment]
Hi @C0D3-M4513R thanks for reporting. I hear you. It's an annoying bug. This has been on our todo list for a while. You can subscribe to #2400 for updates. I'll let the team know we're getting another report about it.

Closing this as a duplicate.
