### ISSUE TITLE
"community search" broken

### ISSUE THREAD

**Issue by peter-kehl** [warpdotdev/Warp#5172]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Both
- https://github.com/warpdotdev/Warp/blob/main/README.md#issues-bugs-and-feature-requests > "[community search](https://widget.orbit.love/widget/55808c32-c958-4da7-83de-3512fea1b278)" and
- https://github.com/warpdotdev/Warp/issues/new/choose > "Warp Community Search"
link to https://widget.orbit.love/widget/55808c32-c958-4da7-83de-3512fea1b278, which fails with
```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: pdx1::r768g-1721858573555-000a06cd95aa

This deployment cannot be found. For more information and troubleshooting, see our documentation.
```
with its last part linking to https://vercel.com/docs/errors/platform-error-codes#deployment_not_found.

While that may not be Warp's fault, it is a problem.

### To reproduce

common browser (current Firefox, Chrome)

### Operating system

Linux

### Operating system and version

current Manjaro

### Shell Version

irrelevant

### Current Warp version

irrelevant

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

no idea

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @peter-kehl thanks for letting us know. This tool was depreciated so I've removed it. I recommend using the Kapa AI widget in the bottom right of https://docs.warp.dev to search for anything in Warps github/docs/blogs/etc.

Closing as resolved, but let me know if any issues with the docs/widget.
