### ISSUE TITLE
Need a lower version for Warp terminal deb file because glibc 2.29 is not supported and i cannot upgrade it for some reasons

### ISSUE THREAD

**Issue by piyushyadav0191** [warpdotdev/Warp#5175]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Warp terminal will not open until i update my glibc 2.28 to 2.29 but there is no way to do that. 

### To reproduce

1. write warp-terminal in terminal
2.got error

### Expected behavior

It should have opened

### Operating system

Linux

### Operating system and version

Deepin 20.9 x86_64

### Shell Version

bash 5.0.3

### Current Warp version

Latest

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment]
Hi @piyushyadav0191 thanks for reporting the issue. Can you post the error message here?
