### ISSUE TITLE
Flickering cursor in neovim

### ISSUE THREAD

**Issue by mkubasz** [warpdotdev/Warp#5176]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When I open a floating window in neovim the cursor behaves like a flickering disco. 

### To reproduce

1. Open neovim
2. Open any kind of floating window

### Expected behavior

Should looks stable

### Screenshots

https://github.com/user-attachments/assets/c8a30dbf-fdab-43ac-a405-3bce8f3cfac9

### Operating system

MacOS

### Operating system and version

14.5

### Shell Version

fish, version 3.7.1

### Current Warp version

v0.2024.07.23.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

25.07

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment]
Hi @mkubasz thanks for reporting the issue. It looks like you've got a combination of plugins which is triggering a lot of re-draws in NeoVim. Can you give more details about your plugins?

**Comment by mkubasz** [comment]
> Hi @mkubasz thanks for reporting the issue. It looks like you've got a combination of plugins which is triggering a lot of re-draws in NeoVim. Can you give more details about your plugins? It looks like you're using the [LazyVim](https://www.lazyvim.org/) distro? Any customizations on top of that?

Yes, exactly. But I compare with kitty which works perfectly.

**Comment by dannyneira** [comment]
@mkubasz any details would help us reproduce the issue and work on a solution

**Comment by mkubasz** [comment]
@dannyneira 
This is ideal situation.
I just installed fresh MacOS system.
Installed brew -> fzf -> ripgrep -> neovim -> lazyvim
Download Warp, login.
And it happened. 
This works few days ago but recently change broke it.

**Comment by mkubasz** [comment]
@dannyneira @acarl005 Sorry for trouble, this was an error from the neovim. I will close comment, Warp works amazing.

**Comment by dannyneira** [comment]
Thanks for letting us know!
