### ISSUE TITLE
Allow me to completely disable all mentions of "AI"

### ISSUE THREAD

**Issue by dlmanning** [warpdotdev/Warp#5188]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I have AI - Input Auto-detection turned off. I have disabled everything I can find that references "AI" in settings.
<img width="516" alt="image" src="https://github.com/user-attachments/assets/d661443b-c7b5-412f-af09-1853d4f8065a">
I still see this when I open a new shell:
<img width="275" alt="image" src="https://github.com/user-attachments/assets/d3496c12-9122-4ed6-9398-a91076b9fa42">

Please give me a way to disable all UI that is in any related to "AI."

### Is your feature request related to a problem? Please describe.

I'm tired of being prompted to enable AI agents and I'm increasingly worried I'm going to do it accidentally. It's a genuine security hazard for me to be within an errant keyboard shortcut of sending things I'm typing into my terminal to external services.

### Additional context

I understand that we're all trying to find ways to work AI into our products, but I do not want an AI agent in my command terminal. Frankly I do not _ever_ want things that I'm typing into my terminal to be sent to remote services. Please let me have a way to disable all this in such a way I'm not going to accidentally turn it back on, or have to waste screen space with buttons to toggle AI agents that I do not want. I will give you money if I can not have to see buttons related to AI agents in my terminal.

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @dlmanning This grey text is called [Input Hints](https://docs.warp.dev/features/editor#input-hints) and can be disabled in the Settings  > Features > Editor > Show input hints. We use the to let users know about new features and options available in Warp.

I hope this helps with your request. Closing as resolved since the feature can be disabled, but please let me know if any issues.

**Comment by dlmanning** [comment]
@dannyneira - That's really not looking for because:
a.) I don't know if there are other "input hint texts" that I might not want to turn off
b.) Turning off the hint doesn't actually eliminate the possibility that I might accidentally hit CMD+I and send command input to a remote service.

What I'm asking for here is a way to disable either all AI related features entirely, or else a way to definitively prevent all command line information from leaving my local computer unless I purposefully enable the setting

**Comment by lukemckechnie** [comment]
I also need to be able to completely disable the AI, as my company does not allow non-approved AI Agents to be used, and unless I can show that the AI is completely disabled, I cannot use Warp.
