### ISSUE TITLE
Should Warp be remembering private tokens?

### ISSUE THREAD

**Issue by Gabriel-p** [warpdotdev/Warp#5192]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I realized that Warp stores the tokens I use and I'm not sure it should? For example I just used the `poetry config pypi-token.pyp` command to set up my Pypi account and I saw that my Pypi token was autocompleted from a previous usage.

Not sure if this is by design, at first glance it looks like a privacy issue.

### Is your feature request related to a problem? Please describe.

Not really, just a question

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @Gabriel-p this is most likely the Autosuggestion feature which suggests commands based on your history. So if you ran that `poetry config` command in the past with the same parameters it will suggest it. You can disable this feature in the Command palette (CMD-P on Mac or CTRL-SHIFT-P on Linux), and search for "autosuggestions". https://docs.warp.dev/features/command-completions/autosuggestions

Also, this may help in the case that you do type in API keys, plaintext passwords, etc. Warp has a secret redaction feature to automatically hide them. https://docs.warp.dev/features/secret-redaction

Closing as these are just features that can be disabled. I hope this helps.
