### ISSUE TITLE
bug: zsh never starts with a new window

### ISSUE THREAD

**Issue by FilipiRafael** [warpdotdev/Warp#5193]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When I open a new window, the status is still always `Starting zsh...`, even when I try to type exit, it doesn't close the window. I have to manually close the window and open it again, it's okay, but happens a lot of times.

### To reproduce

1. Open the Warp
2. Start running something in the first tab
3. Then open a second or third tab

### Screenshots

![Screenshot 2024-07-31 at 10 33 56](https://github.com/user-attachments/assets/77931d8c-d13b-4093-86c7-a4b01bfd5dd4)
![Screenshot 2024-07-31 at 10 34 06](https://github.com/user-attachments/assets/502ecad1-430e-45dd-a56b-aa62b688cf16)

### Operating system

MacOS

### Operating system and version

Sonoma 14.5

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.07.23.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @FilipiRafael this appears to be an issue with Oh My Zsh (OMZ) updates blocking the shell from bootstrapping in Warp. A workaround is to open a new tab, close the first tab, and then run `omz update` in the new tab. Another suggestion is to try running the update from another terminal first, and then Warp should be able to load zsh.

If you want to disable OMZ just for Warp, you can use a conditional statement in your rc file. Here's how you can do it:
```sh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
  # The code you want to disable for Warp goes here
  # For example, if you're sourcing OMZ in your .zshrc or .bashrc, you'd put that line here
fi
```

**Comment by FilipiRafael** [comment]
Hi @dannyneira after running the `omz update` command and it seems to be working now, I did some tests and the error is not occurring anymore, thanks 👍🏻
