### ISSUE TITLE
Warp Doesn't support a past operation from outside the app.

### ISSUE THREAD

**Issue by NegusNati** [warpdotdev/Warp#5197]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I can't seem to past from other apps to warp while using WSL2 with Ubuntu, it doesn't seem to work both using CTR+V or CTR+Shift+V. 

### To reproduce

Copy any text from other "widows" lol, and then open the Warp(Ubuntu) app in windows machine and try to past in nano or anywhere really.

### Expected behavior

You see nothing changing 

### Screenshots

![image](https://github.com/user-attachments/assets/b559009f-a9d7-465c-adc9-5c364ae2ea87)

# no it doesn't read it 

![image](https://github.com/user-attachments/assets/bd9d69a6-241e-4ab9-a29f-5ab403e1d550)

### Operating system

Linux

### Operating system and version

Ubuntu 22.04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @NegusNati We're tracking support for Warp on WSL specifically here https://github.com/warpdotdev/Warp/issues/4240

There are several workarounds listed in the thread, but none that I can think of to fix the shared clipboard issue you're encountering.

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by saiema** [comment]
> Hi @NegusNati For the issue of the shared clipboard I recommend you [install wsl utlities](https://docs.warp.dev/help/known-issues#linux-workarounds) on the Warp on WSL ubuntu. `sudo apt install wslu` then restart Warp. This should help with sharing the clipboard issue.
> 
> We're tracking support for Warp on WSL specifically here #4240
> 
> If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!
> 
> We'll be closing this as a duplicate.

After installing wslu, nothing changes, copying text in windows, is not pasted when using ctrl + shift + v inside warp.

**Comment by dannyneira** [comment]
@saiema sorry about this, it doesnt enabled windows to wsl copy-pasting at this time. We are working on native Warp for Windows support which will include the ability to open tab to WSL instances. Signup here to be notified when it's available. https://windows-when.com

**Comment by saiema** [comment]
> @saiema sorry about this, it doesnt enabled windows to wsl copy-pasting at this time. We are working on native Warp for Windows support which will include the ability to open tab to WSL instances. Signup here to be notified when it's available. https://windows-when.com

What's weird is that in WSL2 (Ubuntu 22.04) I have no problems with copying/pasting to and from (Windows <-> WSL2).

A native WARP for Windows (a la Visual Code) would be awesome!
