### ISSUE TITLE
DUP: Duplicate of #124 - suggestions while typing

### ISSUE THREAD

**Issue by gokulk16** [warpdotdev/warp#52]
**Is your feature request related to a problem? Please describe.**
I was used to with the amazing feature of [starship](https://starship.rs/) where I get the suggested command while I type.
I almost forgot `ctrl+r` searching with this feature. 😄 

**Describe the solution you'd like**
With this amazing UI in warp, we can easily show more than one suggestion of command from the history as we type.

**Comment by charlespierce** [comment]
Hi @gokulk16, thanks for the request! We're actively working on this feature right now, so stay tuned!

**Comment by elviskahoro** [comment]
Closed: v0.2021.11.09.19.46.stable_00
