### ISSUE TITLE
Update Frequency

### ISSUE THREAD

**Issue by Swiftyos** [warpdotdev/Warp#5200]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I don't want to need to always be updating my terminal. Please can you reduce the frequency of updates as it's pretty annoying.

Better to have less frequent but more stable release cycle

### To reproduce

Use warp 

### Expected behavior

Updates come in less frequently

If I'm always seeing that update button, I'll just end up switching to kitty or something

### Operating system

MacOS

### Operating system and version

14.5.0

### Current Warp version

v0.2024.07.23.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @Swiftyos We release bug fixes, improvements, new features, etc. 

That being said, we are tracking this request https://github.com/warpdotdev/Warp/issues/1991 for disabling the auto-updates.

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by Swiftyos** [comment]
> Thanks for submitting this @Swiftyos We release bug fixes, improvements, new features, etc.
> 
> That being said, we are tracking this request #1991 for disabling the auto-updates.
> 
> If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!
> 
> We'll be closing this as a duplicate.

Will do, thank you
