### ISSUE TITLE
Data Privacy Issue When Using the Referral System

### ISSUE THREAD

**Issue by McShauno** [warpdotdev/Warp#5202]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I handed out my referral link to some acquaintances at work and when they used the referral I noticed that I received an email from Warp saying that my referral link was used and then showed me the email address of the person who used it. 

This isn't a huge deal but it does seem like that kind of data should not be shown without the user's consent. 

Thanks so much for a great product. 

### To reproduce

Have someone signup using your referral link. 

### Expected behavior

User's email address probably shouldn't be sent to referrer without consent. 

### Operating system

MacOS

### Operating system and version

macOS Sonoma 14.6

### Shell Version

version 5.2.26(1)-release (aarch64-apple-darwin23.2.0)

### Current Warp version

v0.2024.07.30.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for this feature request! I'll make sure the appropriate team sees this and we'll post updates on this thread.

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Hi @McShauno Thanks for submitting this. We have updated the email for referrals to omit the referral's email address from all subjects/bodies.

Closing as resolved, but please feel free to let us know if the issue persists.
