### ISSUE TITLE
Add the Matrix waterfall effect when terminal is idle…

### ISSUE THREAD

**Issue by marvin-hansen** [warpdotdev/Warp#5203]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Please add the green waterfall falling code effect from the matrix movie as an optional animation to indicate the terminal is idle..

### Is your feature request related to a problem? Please describe.

I’m always frustrated looking at an idle terminal and nothing is moving.

### Additional context

The effect is actually quite easy to implement so there is no actual reason why it isn’t there.

https://youtu.be/SeTSL0JYVVk?si=PjLoWP9g9LqtbQug

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for this feature request @marvin-hansen! As a stopgap, there is a CLI screensaver that does just this called [cmatrix](https://github.com/abishekvashok/cmatrix).

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by synek317** [comment]
Hello, I played a little bit with [cmatrix](https://github.com/abishekvashok/cmatrix) and recently released [tui-screen-savers-rs](https://github.com/oiwn/tui-screen-savers-rs). I've encountered some issues and limitations which I posted on the warp [discord](https://discord.com/channels/851854972600451112/1354020833001213963/1354144721689120838) 

> Ok, I played with it a bit more and now have mixed feelings.
> 
> zsh + TMOUT + TRAPALRM works but with caveats.
> [TMOUT](https://zsh.sourceforge.io/Doc/Release/Parameters.html#Parameters) is time since the last command has been entered and not since the last keystroke, what is quite understandable. It also (obviously, I guess?) doesn't trace any mouse events.
> 
> also, tarts (the rust project I linked in my post) hangs in warp. I used following simple setup:
> 
> TRAPALRM() { tarts matrix }
> TMOUT=2
> 
> The same setup works with other terminals. I experienced similar issues with cmatrix. Also, cmatrix -s prints <ffffffff> instead of the actual effect.
> 
> So... some effect could be achieved with existing tools but warp support would streamline it and made more things possible (e.g. count time since the last keystroke and not last command executed or even allow running on top of the already running programs like htop etc.)
