### ISSUE TITLE
Is there a date for Windows version release?

### ISSUE THREAD

**Issue by adar-cohen-imagenai** [warpdotdev/Warp#5218]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Im waiting Warp to release to windows to switch my mac to windows laptop

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @adar-cohen-imagenai no firm release date yet (soft target is the end of 2024), but we'll post more on this thread. https://github.com/warpdotdev/Warp/issues/204

Closing as duplicate.

**Comment by RKiranKumarReddy010** [comment]
any updates regarding windows release.....

**Comment by NolanNamNguyen** [comment]
This is my dream terminal, you guys have created a masterpiece, I hope the window version is release soon

**Comment by gustavo-engel** [comment]
Hiii waiting for updates on this 🗡️

**Comment by chaloisaza** [comment]
Maybe this masterpiece as christmas gift? 🤞🏽

**Comment by shafayetejaman** [comment]
Any update on the release date?

**Comment by daggmano** [comment]
Assuming there may not be any reply to this channel until the Windows version is released (and perhaps life is better that way). Just had my (Win11) laptop rebuilt and am making the pledge to stay with cmd.exe until Warp is released. Hopefully the increased efficiencies post-Warp will make up for the reduced efficiencies pre-Warp...
