### ISSUE TITLE
Moved to #500 - keybinding block delete

### ISSUE THREAD

**Issue by rkazak** [warpdotdev/Warp#522]
### Describe the solution you'd like?

```shell
When in a block a simple cmd-del or cmd-D could delete the current block.
```

### Is your feature request related to a problem? Please describe.

```shell
Would like the ability to remove blocks I am no longer interested in
```

**Comment by elviskahoro** [comment]
Moving this into:
- https://github.com/warpdotdev/Warp/discussions/500
