### ISSUE TITLE
sudo bash -c bash

### ISSUE THREAD

**Issue by lanwenming** [warpdotdev/Warp#5223]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

In some scenarios when using SSH to remotely access Linux,  I can only continuously obtain root privileges through “sudo bash -c bash”, but this will keep me in that process, causing some functions of warp to be unusable. Is there a way to adapt to  ”bash -c bash“?

### To reproduce

1. ssh remote linux
2. sudo bash -c bash

### Operating system

MacOS

### Operating system and version

macos14

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by davidmelvin** [comment]
Hi @lanwenming! Have you tried adding `sudo bash -c bash` to the Settings > Subshell list of subshell commands? That should Warpify that session so you get the Warp features. Further documentation here: https://docs.warp.dev/features/subshells

Let us know if that solves the issue!

**Comment by lanwenming** [comment]
Yes, this effectively solved my problem. 
Thank you very much! I'm sorry for asking  without fully understanding the warp.
