### ISSUE TITLE
Folder Autocomplete not working 

### ISSUE THREAD

**Issue by rafaelfigma** [warpdotdev/Warp#5224]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Trying to re-open this issue as this keeps happening to me: https://github.com/warpdotdev/Warp/issues/3094

### To reproduce

See original ticket

### Operating system

MacOS

### Operating system and version

Mac OS

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @rafaelfigma thanks for letting us know. I saw your video on the other post. the issue appears to be you have Autosuggestions enabled which will show you the suggested command based on the history, so if you ran `cd folder_a` in the past for example it'll suggest that as a completion. By default you accept it with RIGHT-ARROW, but you can always press TAB to open the completions menu, or you can enable "Open completions as you type" to have the completions menu (with list of folders) show up. https://docs.warp.dev/features/command-completions/completions & https://docs.warp.dev/features/command-completions/autosuggestions

quick example below:

https://github.com/user-attachments/assets/6aa2c2b3-4c98-4a42-8e64-17f1ca63de39

I hope this helps! Change to this default behavior can be found in the Settings > Features.

**Comment by rafaelfigma** [comment]
OK! This was super helpful. Thank you so much!
