### ISSUE TITLE
Cant update

### ISSUE THREAD

**Issue by averriK** [warpdotdev/Warp#5227]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

The "update warp" button in Linux, run the commands
sudo apt update && sudo apt install warp-terminal && warp_finish_update MvZU7Me
but the terminal says that is already the newest version. The button "update warp" still appears

### To reproduce

sudo apt update && sudo apt install warp-terminal && warp_finish_update MvZU7Me

warp-terminal is already the newest version (0.2024.06.25.08.02.stable.01).

### Expected behavior

button update dissappears

### Operating system

Linux

### Operating system and version

Ubuntu 24

### Shell Version

GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu

### Current Warp version

(0.2024.06.25.08.02.stable.01)

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @averriK sorry to hear about this. It's a known issue and we're working on a fix!

The workaround is to add the warp repository and you should be able to run the update.

```
sudo apt-get install wget gpg
wget -qO- https://releases.warp.dev/linux/keys/warp.asc | gpg --dearmor > warpdotdev.gpg
sudo install -D -o root -g root -m 644 warpdotdev.gpg /etc/apt/keyrings/warpdotdev.gpg
sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main" > /etc/apt/sources.list.d/warpdotdev.list'
rm warpdotdev.gpg
sudo apt update && sudo apt install warp-terminal
```

**Comment by dannyneira** [comment]
We're tracking this particular issue here. https://github.com/warpdotdev/Warp/issues/5201

I'll close this as a duplicate, but please let me know if the issue persists after you add the repo with the command above.
