### ISSUE TITLE
Save terminal session output, whole session or block by block

### ISSUE THREAD

**Issue by rkazak** [warpdotdev/warp#523]
### Describe the solution you'd like?

```shell
I sometimes use the Terminal.app feature cmd-s to save my terminal session to a file for later analysis.
```

### Is your feature request related to a problem? Please describe.

```shell
Sometimes when working on an issue I like to save the terminal output which helps in some debugging sessions.
```

**Comment by elviskahoro** [comment]
@rkazak Gonna merge this into
- #234 

I'm copying and pasting your feedback there.

**Comment by elviskahoro** [comment]
@rkazak also check out this issue:
- https://github.com/warpdotdev/warp/issues/385
