### ISSUE TITLE
.zshrc not reload when use command source ~/.zshrc

### ISSUE THREAD

**Issue by aphisiit** [warpdotdev/warp#524]
### Describe the bug

```shell
I try change Java development kit from 1.8 to 11 or 11 to 1.8. And use command source ~/.zshrc to reload .zshrc config. It's not worked. I must re-open the new terminal tab to reload .zshrc profile.
```

### To Reproduce

Steps to reproduce:
1. Type `vim ~/.zshrc`
2. Change `export JAVA_HOME=/usr/libexec/java_home -v 1.8` to change `export JAVA_HOME=/usr/libexec/java_home -v 11`
3. Type `source ~/.zshrc`
4. Type `java --version`, you will see terminal show old versionof JDK (If you change from 1.8 to 11, You will see version 1.8) 

### Operating System

MacOS

### OS Version

12.1 Beta (21C5021h)

**Comment by fishcharlie** [comment]
@aphisiit Are you using SSH? If so duplicate of https://github.com/warpdotdev/warp/discussions/502.

**Comment by aphisiit** [comment]
@fishcharlie No. I just use basic commands such as
- `source ~/.zshrc` for reload profile.
- `javac --version` for check JDK version.

I'm not using ssh command to remote server.

I using zsh instead of bash on my terminal. Because it's become default with MacOS.

**Comment by elviskahoro** [comment]
@aphisiit we're having difficulty reproducing could you also share your rc file here or over email: elvis@warp.dev

**Comment by aphisiit** [comment]
@elviskahoro  It's worked now after install update. Thank you.
