### ISSUE TITLE
Unable to save a workflow from a command that has been generated through AI # -> natural language gen

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#5249]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

https://www.loom.com/share/6e18147a28db4cf4a34cccf3fbd72090

### To reproduce

https://www.loom.com/share/6e18147a28db4cf4a34cccf3fbd72090

### Expected behavior

To be able to save instead of update

### Screenshots

https://www.loom.com/share/6e18147a28db4cf4a34cccf3fbd72090

### Operating system

MacOS

### Operating system and version

NA

### Shell Version

NA

### Regression

Yes, this bug started recently or with an X Warp version

### Additional context

Might be a regression, I don't remember it happening a while back

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @elviskahoro thanks for letting us know. It looks like something's up with that entry point in particular even though we display the workflow in a pane.

I'll let the team know and we'll post any updates on the thread.


To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Hi Folks, this bug has been resolved in recent version of Warp. Please see the loom demo below:

https://www.loom.com/share/711304a25e3d4e309642379d256a415c

Closing as resolved, but please let us know if any issues.
