### ISSUE TITLE
`cmd+D` to open new shell in same window

### ISSUE THREAD

**Issue by sebhs** [warpdotdev/warp#525]
### Describe the solution you'd like?

```shell
Would love to have the same behavior from iTerm2 when clicking `cmd+D`
```

### Is your feature request related to a problem? Please describe.

```shell
Just use it all the time so very used to it
```

**Comment by elviskahoro** [comment]
Hey @sebhs

You can do this with `CMD+e` and `CMD+SHIFT+E`
The intuition here is Warp has the native input editor, as you know! And so we've prioritized keybindings for the editor, so you can have a similar experience when entering commands to like VSCode.

Closing issue! Let me know if anything else comes up.
