### ISSUE TITLE
No documentation for cursor color

### ISSUE THREAD

**Issue by paulyhedral** [warpdotdev/Warp#5257]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

> 2024.08.22 (v0.2024.08.20.08.02)
> New features
> * You can now specify a cursor color in Warp themes

### To reproduce

Documentation does not contain any information on how to set color
UI doesn't not contain any elements to set or change cursor color

### Expected behavior

Ability to set cursor color

### Operating system

MacOS

### Operating system and version

macOS 14.6.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.08.20.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @paulyhedral Thanks for submitting this issue. The cursor color can be set in the theme yaml file. We've included instructions in our docs here. https://docs.warp.dev/appearance/custom-themes#create-your-custom-theme-manually

Closing as the docs exist, but please let us know if any issues with setting up your theme.
