### ISSUE TITLE
support sqlite3 interactive sessions

### ISSUE THREAD

**Issue by alexcohn-ib** [warpdotdev/Warp#5260]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I'd love to use the full power of Warp to work with sqlite databases on remote machines. Today I can 'warpify' **sqlite3**, but this does not separate blocks for each SELECT, does not allow me to graphically edit the SQL statement, does not help me use built-in autocomplete features of **sqlite3**.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Thanks for submitting this @alexcohn-ib 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/4082

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
