### ISSUE TITLE
Too easy to close tab when block is running a long task

### ISSUE THREAD

**Issue by laserjim** [warpdotdev/Warp#5262]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When a block is still running (long running task), the app should warn/confirm before allowing you to to close the tab.  It's way too easy to accidentally press the "close a tab" (either when switching tabs, or because you weren't sufficiently cognizant of what a tab was doing) with a long-running process and end up killing the process.  In the one week I've been using Warp, I've already lost at least an hour due to this bug, closing a tab that was ssh'd into a remote machine and running a long-running task.  Even the basic/default terminal in Mac and Linux will warn you when closing a tab with a process still running.

### To reproduce

1.  SSH into a remote machine
2. Launch a long-running process
3. Click the "close tab" button
4. Observe that the tab did not warn you; it just killed the connection which also killed the process

### Expected behavior

Warn you that a block/process is still running, and confirm that you want to close the tab.

### Operating system

MacOS

### Operating system and version

10.15.7

### Shell Version

bash

### Current Warp version

v0.2024.08.27.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for submitting this @laserjim

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2717

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
