### ISSUE TITLE
Suppress AI Completions when completing a path

### ISSUE THREAD

**Issue by laserjim** [warpdotdev/Warp#5263]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

There is something subtly wrong with the autocomplete when autocompleting file paths.  The AI suggested a path completion which didn't exist (it kept repeating the name of the current directory or something, instead of directories which actually existed).  When completing a path, consider suppressing the AI suggestions in favor of filesystem-provided completions.

### To reproduce

I'm not sure what part of my terminal history sent the AI off the rails, but the AI should never suggest a path completion that isn't a valid file path.

### Operating system

MacOS

### Operating system and version

OS X

### Shell Version

bash

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @laserjim sorry to hear about this, but the Autosuggestions you see in grey text are not part of the AI. You can disable this feature in the Command palette > type in "Autosuggestions". This feature works by suggestion completions based on history or possible completions. https://docs.warp.dev/features/command-completions/autosuggestions

That being said, we have a request for overidding warp completions and autosuggestions in favor of shell completions we're tracking here https://github.com/warpdotdev/Warp/issues/1811

Closing as this is a known limitation, can be disabled and the alternative is being tracked in the above.
