### ISSUE TITLE
Can't update warp

### ISSUE THREAD

**Issue by Trent-Fellbootman** [warpdotdev/Warp#5276]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I can't update warp. The provided command does not work. After running it, warp restarts but version does not change.

### To reproduce

I'm on warp 2024.8.13.08.02.stable_04.
Just click the update warp button and run the command.

### Operating system

Linux

### Operating system and version

Ubuntu 24.04

### Shell Version

zsh 5.9 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2024.08.13.08.02.stable_04

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

v0.2024.08.13.08.02.stable_04 is the last version updated to

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
Hi @Trent-Fellbootman, thanks for filing.  I believe this is partly due to an issue with how Ubuntu disables third party repositories upon updating to a new version.

What's the output of `ls /etc/apt/sources.list.d`?

**Comment by Trent-Fellbootman** [comment]
I don't think that's the problem, cuz warp repos do show up:


```
cuda-ubuntu2204-x86_64.list.distUpgrade &nbsp;github-cli.list.distUpgrade &nbsp; &nbsp; &nbsp;microsoft-prod.list.distUpgrade &nbsp; &nbsp; mozilla.list.distUpgrade &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; unityhub.list.savecuda-ubuntu2204-x86_64.list.save &nbsp; &nbsp; &nbsp; &nbsp; github-cli.list.save &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; microsoft-prod.list.save &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;mozilla.list.save &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;vscode.list.distUpgrade
cuda-ubuntu2404-x86_64.list &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;google-chrome-beta.list.save &nbsp; &nbsp; microsoft-prod.sources &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;nvidia-container-toolkit.list &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;vscode.list.save
deepin-wine.i-m.dev.list.distUpgrade &nbsp; &nbsp; google-chrome.list.save &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;miktex.list.bak &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; nvidia-container-toolkit.list.distUpgrade &nbsp;vscode.sources
deepin-wine.i-m.dev.list.save &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;hashicorp.list.distUpgrade &nbsp; &nbsp; &nbsp; miktex.list.save &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;nvidia-container-toolkit.list.save &nbsp; &nbsp; &nbsp; &nbsp; warpdotdev.list.distUpgrade
deepin-wine.i-m.dev.sources &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;hashicorp.list.save &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;modular-installer.list.distUpgrade &nbsp;third-party.sources &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;warpdotdev.list.save
docker.list &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;microsoft-edge.list.distUpgrade &nbsp;modular-installer.list.save &nbsp; &nbsp; &nbsp; &nbsp; ubuntu.sources
docker.list.distUpgrade &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;microsoft-edge.list.save &nbsp; &nbsp; &nbsp; &nbsp; mongodb-org-7.0.list.distUpgrade &nbsp; &nbsp;unityhub.list
docker.list.save &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; microsoft-edge.sources &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; mongodb-org-7.0.list.save &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; unityhub.list.distUpgrade

```



Trent
***@***.***







                       
Original
                       
                     

From:"Aloke Desai"< ***@***.*** &gt;;

Date:2024/9/5 22:04

To:"warpdotdev/Warp"< ***@***.*** &gt;;

CC:"Trent Fellbootman"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [warpdotdev/Warp] Can't update warp (Issue #5276)




 
Hi @Trent-Fellbootman, thanks for filing.  I believe this is partly due to an issue with how Ubuntu disables third party repositories upon updating to a new version.
 
What's the output of ls /etc/apt/sources.list.d?

**Comment by alokedesai** [comment]
Thanks, this validates the theory. You can fix this by running the following in that directory to re-enable the repository
```
cp  warpdotdev.list.distUpgrade  warpdotdev.list
```

**Comment by dannyneira** [comment]
Hi @Trent-Fellbootman This is a known issue we're tracking here https://github.com/warpdotdev/Warp/issues/5201

The workaround is above or re-adding the repository and updating with the following command.

```sh
sudo apt-get install wget gpg
wget -qO- https://releases.warp.dev/linux/keys/warp.asc | gpg --dearmor > warpdotdev.gpg
sudo install -D -o root -g root -m 644 warpdotdev.gpg /etc/apt/keyrings/warpdotdev.gpg
sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main" > /etc/apt/sources.list.d/warpdotdev.list'
rm warpdotdev.gpg
sudo apt update && sudo apt install warp-terminal
```
We'll continue to track the issue on the github issue above. Closing as a duplicate, but please track the issue for any updates.
