### ISSUE TITLE
Moving Mouse to Bottom of Notebooks Crashes Warp

### ISSUE THREAD

**Issue by joelp172** [warpdotdev/Warp#5283]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When in a notebook that has text the full length of the screen, moving the mouse continuously or attempting to add a new block crashes the app

https://github.com/user-attachments/assets/41f075aa-43c9-45b2-994d-9071d5e87ee0

### To reproduce

Create a note book and add blocks so they reach the full length of your screen, then when moving the mouse to the bottom of the screen or adding a new block the app crashes

### Expected behavior

App not to crash

### Operating system

MacOS

### Operating system and version

14.6.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.09.03.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by vorporeal** [comment]
Hey @joelp172 - when you say "crashes", do you mean that the application stops responding?

If so, do you mind getting Warp into that state, taking a process sample, and attaching it here?

You can do so from Activity Monitor like so:

![image](https://github.com/user-attachments/assets/bb2a7daf-f5cc-4bbc-a7d8-24a7cc1c53b6)

Also, if the app stops responding, is the CPU usage of Warp small or large?

**Comment by joelp172** [comment]
Yes it stops responding, i have to force quit via Finder 

![Screen Shot 2024-09-06 at 16 15 51 PM](https://github.com/user-attachments/assets/72a36d04-c373-4a18-a043-7ae3206a02d0)

CPU goes to 100

[Sample of Warp.txt](https://github.com/user-attachments/files/16909920/Sample.of.Warp.txt)

**Comment by bnavetta** [comment]
This should be fixed as of the v0.2024.10.08.08.02.stable_00 (that's a few releases ago, sorry for not following up sooner!)
