### ISSUE TITLE
Exiting the shell with CTRL-D doesn't work until the shell is loaded

### ISSUE THREAD

**Issue by dannyneira** [warpdotdev/Warp#5291]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When that happened I tried hitting “Ctrl-D” to kill that split, but it doesn’t have the shell loaded for about 3 seconds, so it ignores keys until then.

### To reproduce

1. Add `sleep 3` to your `~/.zshrc` file to delay loading the shell.
2. Open a new Pane (in this case on Linux) with CTRL-SHIFT-E
3. While the new pane is loading the shell, press CTRL-D to exit the shell, notice how the exit fails, even after the shell is done loading.

### Expected behavior

The shell should exit once it is done loading, or immediately upon pressing CTRL-D.

### Screenshots

https://github.com/user-attachments/assets/fbd177fb-8ab4-49ae-92d2-0bbf09cd99ef

### Operating system

Linux

### Operating system and version

Ubuntu 24

### Shell Version

zsh, but also the same in other shells like bash

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

There is a workaround which is to close the session with CTRL-SHIFT-W instead of exiting the shell with CTRL-D

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey folks, this issue can be worked around by pressing `CTRL-SHIFT-W` on Linux or `CMD-W` on macOS which will close the active session (window, tab, or pane) regardless of the shell loading state.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by szgupta** [comment]
For anyone following this: this should be fixed in the next release (likely the week of 10/07/24)!

**Comment by dannyneira** [comment]
Closing as resolved, thanks @szgupta!
