### ISSUE TITLE
Git autocomplete won't show latest commit first

### ISSUE THREAD

**Issue by abarriel** [warpdotdev/Warp#5293]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Hello,

When using the `git commit --fixup=` command and pressing TAB for completion, the commit hashes are displayed in ASCII order rather than showing the most recent commits on the current branch first. 
This behavior differs from other terminals like iTerm2, where the completion shows the most relevant commits for fixup ( HEAD )

It's the same behavior with squash, diff, etc. 

### To reproduce

1. Make a commit
2. Add new changes
3. Type git commit --fixup= and press TAB for completion

### Expected behavior

The completion shows commit hashes ordered alphabetically (ASCII order), which makes it difficult to find and select recent commits for fixup operations.

### Operating system

MacOS

### Operating system and version

14.5

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.09.03.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thank you for the feature request! We don't have time-based commit ordering on our roadmap at the moment, but thank you for putting this on our radar.

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by abarriel** [comment]
Thank you @dannyneira but I though it was a bug since it doesn't make sense to show commit order by commit hash, we rarely need to see our first commits.
It's not actually only time-based commit needs, but we need to see the commits of our current branch first, then the default branch..

**Comment by dannyneira** [comment]
Heard, there is a fix going out for this, most likely will be in next weeks release ordering the commits in chronological order (most recent first)

**Comment by acarl005** [comment]
I just merged the fi. Assuming all goes well, it should be in the Sep 19th release!

**Comment by VinceOPS** [comment]
Hi there! I just wanted to confirm that this had been released? Using the last update as of today and I have the same issue.

Thanks a lot for the amazing work!

**Comment by VinceOPS** [comment]
@abarriel Hi! Did you do any specific config to have the autocompletion work on `--fixup=`? On my side, pressing TAB just does nothing 😅 

Thanks a lot

**Comment by acarl005** [comment]
@VinceOPS Does it work if you omit the `=` and use a space instead? We might have a bug specific to `=`.

**Comment by VinceOPS** [comment]
> @VinceOPS Does it work if you omit the `=` and use a space instead? We might have a bug specific to `=`.

Hi @acarl005 and thanks for your answer. It does work if I omit the `=` (_thanks_).

**Comment by acarl005** [comment]
Ok thanks for confirming. I'll close out this issue and look into the `=` as a separate issue.
