### ISSUE TITLE
Unable to reveal secret

### ISSUE THREAD

**Issue by Integralist** [warpdotdev/Warp#5306]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I see the following output when running a custom `dns` alias (which is just `scutil --dns | grep 'nameserver\[[0-9]*\]'`)

```
dns
  nameserver[0] : *******
  nameserver[1] : ********************
  nameserver[2] : ********************
  nameserver[0] : *******
  nameserver[1] : ********************
  nameserver[2] : ********************
```

The problem is, _sometimes_ the Warp terminal will give me the "Reveal secret" option, sometimes it doesn't and when it doesn't it's very frustrating 😬 

### To reproduce

I don't have a consistent way to reproduce this unfortunately.

At first I wondered if it was because of the alias, so I tried the direct command and still it wouldn't show me a "Reveal secret" option. I then wondered if it was because of the piping to grep, but nope same issue if I remove that it still doesn't show me the "Reveal secret" option.

I then went into the settings to see if I could set a regex to undo the defaults Warp uses and that's when I stumbled across https://github.com/warpdotdev/Warp/issues/3916 which would have been helpful in this case, but I decided to open this issue regardless because it's a separate issue as I should be able to just use the "Reveal secret" option.

### Expected behavior

I would like for every time the terminal hides a secret, that it guarantees it'll give me the option to reveal the secret.

### Screenshots

You'll see there is no "Reveal secret" option...

<img width="944" alt="Screenshot 2024-09-16 at 12 59 10" src="https://github.com/user-attachments/assets/bc6a403a-be31-45ed-afeb-f760135d0e33">

### Operating system

MacOS

### Operating system and version

14.4.1 (23E224)

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Current Warp version

v0.2024.09.10.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @Integralist sorry to hear about this. I was having trouble reproducing it aswell. From your screenshot that looks like the RIGHT-CLICK menu, to reveal the secret you need to LEFT-CLICK on the secret to see the "reveal secret" option. 

https://github.com/user-attachments/assets/a6987047-3d78-42e4-9d95-a8afea398c39

Give that a try and see if it helps. I'll try and reproduce this on my end and let the team know if we can consistently get the issue to come up.

**Comment by Integralist** [comment]
Thanks @dannyneira 

Well TIL that there's a left-click menu 😅🤦🏼‍♂️

So yeah, left-click shows the "Reveal secret" option.

I'll just close this issue and pretend like nothing ever happened 😄
