### ISSUE TITLE
Newly created workflows and notebooks don't show up in sidebar if created inside folders

### ISSUE THREAD

**Issue by apmwebdev** [warpdotdev/Warp#5331]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When creating a new workflow or notebook, if you're creating it inside of a folder and not in the root of your Warp Drive, it won't show up in the sidebar. You need to quit and reopen Warp to see it.

I think this only started in the last day or two, but it definitely started before I updated today, and I updated Warp last Thursday or Friday, whenever the last update was. Updating Warp, and restarting my computer and Warp itself didn't fix the issue.

### To reproduce

1. Create a folder in your personal Warp Drive.
2. Right click on that folder (or left click on the folder's hamburger menu) and select "New Notebook." Enter a title and body for the notebook. Note how it pops up a toast saying that the notebook was saved as soon as you enter any text.
3. Note how the notebook doesn't show up in the sidebar. Changing from editing to viewing mode doesn't help, nor does anything else I was able to think of beyond quitting and restarting Warp entirely. The same behavior happens with workflows as well, although for those there's a manual "Create" button instead. But clicking the Create button doesn't cause the workflow to show up.

### Expected behavior

The notebook should show up in the sidebar as soon as the toast message pops up to say it was added. And workflows should show up as soon as you click the Create button and it says it added it successfully.

### Operating system

MacOS

### Operating system and version

14.6.1

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.09.24.08.02.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

September 24th maybe?

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Mjb141** [comment]
I'm also seeing this. Same set-up - create workflow in existing folder, it's accessible from command palette and `workflows: ...` but invisible in warp drive. Full quit + re-open required on Mac, it's not enough to just close tabs (some or all) - the workflow still doesn't show up until you quit.

**Comment by hcaw** [comment]
I also have the same issue. I've worked out that if you leave the folder expanded, then quit and re-open, the new workflow still doesn't show up. You have to "fold" the folder first, then quit and re-open.

Happy to post log files etc. if helpful.

**Comment by dannyneira** [comment]
Thanks for letting us know @apmwebdev We've found the issue and are working on a fix. We'll post any updates on this thread.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Hi @apmwebdev and folks! This issue has been fixed in the most recent version of Warp. 

Closing as resolved, but please feel free update and to let us know if any issues.
