### ISSUE TITLE
non-userfriendly UI/UX

### ISSUE THREAD

**Issue by 221V** [warpdotdev/Warp#5332]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

there are motto on the warp website:
**Own the command line**

but looks like my command line owns warp, not me --

cause one good day you see non-removable red shit like on the screenshot
https://i.imgur.com/rmhxVlc.png

warp has good enought history/autocomple for me,
and I not need any AI
but please f*.*k anybody other with your red shit, okey?

so delete and forget your shit -- no more any way

dislike this micro$oft-style f*.*king!
have good f*.*king day!

### To reproduce

https://i.imgur.com/rmhxVlc.png

### Expected behavior

no non-removable red shit like on the screenshot
https://i.imgur.com/rmhxVlc.png

just let user to enjoy if he wants to use once installed soft

### Screenshots

https://i.imgur.com/rmhxVlc.png
![Screenshot from 2024-09-27 05-33-43](https://github.com/user-attachments/assets/e40fa414-3b46-4cee-8176-5cafa4e9cdcf)

### Operating system

Linux

### Operating system and version

lubuntu 22.04 LTS

### Shell Version

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.08.06.08.01.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @221V Sorry to hear about this frustration. Since this is more a feature request then a bug, please note that we have a request tracking disabling of the update banner here. https://github.com/warpdotdev/Warp/issues/1991

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
