### ISSUE TITLE
Links are clickable while behind a Warp menu

### ISSUE THREAD

**Issue by OmerFlame** [warpdotdev/Warp#534]
### Describe the bug

```shell
When you have the settings open and there is a clickable link inside Warp right behind the settings window, the link inside the terminal will register a click if you click inside the menu itself where the URL is behind the settings window. I know that this explanation is pretty bad, but I included a screen recording that shows the bug.
```

### To Reproduce

Steps to reproduce:
1. Have a clickable link printed inside the terminal
2. Open settings
3. Click the area in which the link is written behind the menu
4. Profit?

### Expected behaviour

```shell
The whole terminal area should not be able to register any user input (mouse clicks or keyboard input) while any Warp menu is shown, and the links should reject clicks while a Warp menu is open.
```

### Screenshots

https://user-images.githubusercontent.com/17903236/146136416-476eb4cb-f0d5-414d-b8c5-9f520cf92d9b.mov

### Operating System

MacOS

### OS Version

12.0.1

### Additional context

```shell
The solution is to just disable user interaction inside the entire terminal area while any menu is open. It's a fairly easy bug to fix.
```

**Comment by elviskahoro** [comment]
Thanks for reporting. No ETA unfortunately. Will let you know when it gets fixed

**Comment by dannyneira** [comment]
Hey folks and @OmerFlame this issue has been resolved in the latest versions of Warp. Closing as resolved.

**Comment by OmerFlame** [comment]
Always happy to help! Thank you!
