### ISSUE TITLE
Warp crashing when scrolling and Find search item scrolls off screen

### ISSUE THREAD

**Issue by phillystafford** [warpdotdev/Warp#5362]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When you're searching for a value in the console `CMD+F`, if the value isn't on the screen and you're scrolling through the console out put, the value you're looking for will highlight when it comes into view. But when you keep scrolling and the value tries to leave the view, Warp will crash.

In the gif below when the screen stops scrolling I see the spinning beachball icon and have to force close Warp.

### To reproduce

I cloned Warp and

- cd into the warp directory
- git log
- scroll down
- copy a value that is not in the view (a commit hash in this case)
- scroll back up to where the value is out of view
- cmd+f to open Find
- paste in the value
- scroll down to see the value highlighted
- keep scrolling down until the value leaves the screen
- Warp crashes
- force quit to close Warp

### Expected behavior

This used to highlight each occurrence of the search string when it appeared in view and would allow you to continue scrolling to find more occurrneces

### Screenshots

![warp-bug](https://github.com/user-attachments/assets/271882c1-16b4-484b-8c1a-947c30978d4a)

### Operating system

MacOS

### Operating system and version

14.6.1

### Shell Version

zsh, oh-my-zsh

### Current Warp version

v0.2024.09.24.08.02.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

I'm not sure. I haven't searched like this for a while

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by szgupta** [comment]
Hey @phillystafford, sorry for the inconvenience. This should be fixed latest by next week's release.
