### ISSUE TITLE
v0.2024.10.08.08.02.stable_02 update warp FAILS ubuntu 24.10 sudo apt update && sudo apt install warp-terminal && warp_finish_update gZTHjQf 

### ISSUE THREAD

**Issue by intellibitz** [warpdotdev/Warp#5375]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

latest v0.2024.10.08.08.02.stable_02 update warp fails in ubuntu 24.10

### To reproduce

update to ubuntu 24.10
click update warp in warp terminal
not able to update warp from ubuntu oracular repostitory.

### Expected behavior

warp terminal update.

### Operating system

Linux

### Operating system and version

ubuntu 24.10 oracular

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.10.08.08.02.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

11 oct 2024

### Additional context

24.10 ubuntu update

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by mkleger** [comment]
I have the same problem, after what feels like 10 minutes of waiting, the terminal starts up without an error message or anything else

**Comment by psmgeelen** [comment]
Same issue here, might be a Wayland issue? https://github.com/warpdotdev/Warp/issues/5367

**Comment by mkleger** [comment]
I already had Wayland in operation with Ubuntu 24.04 and that without problems, only after the update to 24.10 I have the problem that when I start Warp it takes 10 minutes until the software is started.

**Comment by vorporeal** [comment]
@mkleger @psmgeelen I think you're talking about a different issue than the OP - they reported issues _updating_ Warp, not issues with it taking a while to start.

@intellibitz - Can you share more details about what's going wrong?  Without a screenshot or copy-pasted terminal output, there's little we can do to help you.

**Comment by intellibitz** [comment]
Reinstalled fresh stable_03 in ubuntu 24.10. So this fix bypassed the issue.

**Comment by oktayderman** [comment]
Use following content for the desktop file to open warp in x11

`
[Desktop Entry]
Categories=System;TerminalEmulator;
Comment[en_US]=
Comment=
Exec=env WAYLAND_DISPLAY=, warp-terminal %U
GenericName[en_US]=TerminalEmulator
GenericName=TerminalEmulator
Icon=dev.warp.Warp
Keywords=shell;prompt;command;commandline;cmd;
MimeType=
Name[en_US]=Warp
Name=Warp
Path=
StartupNotify=true
StartupWMClass=dev.warp.Warp
Terminal=false
TerminalOptions=
Type=Application
Version=1.0
X-KDE-SubstituteUID=false
X-KDE-Username=
`

**Comment by vorporeal** [comment]
Hey folks, please keep discussion about Warp being slow to launch on Ubuntu 24.10 in this issue: https://github.com/warpdotdev/Warp/issues/5367.  It'll be easier for everyone if discussion is centralized there.
