### ISSUE TITLE
SSH, ping etc. : No route to host

### ISSUE THREAD

**Issue by yoplait2** [warpdotdev/Warp#5378]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

If I try to ssh into a local machine with warp I get a no route to host error. If I try to do the same with stock terminal from Mac OS it is working flawlessly. 

### To reproduce

Just try to SSH or ping a machine from Warp. 
Tried to fully quit and run warp again same thing is happening

### Screenshots

<img width="650" alt="Screenshot 2024-10-13 at 11 23 58" src="https://github.com/user-attachments/assets/13d6d731-6e14-41a4-99d1-5a64597af4f3">
<img width="1054" alt="Screenshot 2024-10-13 at 11 21 57" src="https://github.com/user-attachments/assets/d9dd5b0c-8c95-458c-8b0d-cbd2f3f9406b">
<img width="1040" alt="Screenshot 2024-10-13 at 11 21 12" src="https://github.com/user-attachments/assets/b704f75a-695c-4c3c-acdd-d64f7c6b2b7e">
<img width="524" alt="Screenshot 2024-10-13 at 11 30 22" src="https://github.com/user-attachments/assets/2661cda5-9715-4b14-9b84-7c9a0d88c54b">

### Operating system

MacOS

### Operating system and version

Sequoia 15.0.1

### Shell Version

zsh 5.9 (arm64-apple-darwin24.0)

### Current Warp version

v0.2024.10.08.08.02.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by kevinherzig** [comment]
I am having this issue too.  Can ping the default gateway, can ping my own IP address, cannot ping or connect to any other device on the network.

**Comment by knut-bergli** [comment]
This issue makes Wrap useless

**Comment by sdebruyn** [comment]
I just lost 3 hours on this issue. Insane. How can a terminal emulator cause something like this? Also _nice_ how the maintainer just closed the issue without any comments.

**Comment by lingdie** [comment]
This issue still exists. I have checked the permissions and they are normal, but the problem still persists. Reboot/reinstall does not help.

![Image](https://github.com/user-attachments/assets/d9b98f42-fc8b-4f48-8474-bac51061dac2)

**Comment by lingdie** [comment]
Solved after I install iTerm2.😢

**Comment by lingdie** [comment]
This problem has appeared again...

**Comment by arik-so** [comment]
Same issue here. Local network permission settings are correct. How is this closed‽

**Comment by TheRealMaN** [comment]
Same issue in Tahoe 26.2

**Comment by rodrigoreyes79** [comment]
I finally moved to Ghostty. Love it and no issue at all.

**Comment by sdebruyn** [comment]
This issue is the best motiviation to abandon Warp and move to something else indeed

**Comment by kgansberger** [comment]
=> cmux ..  love it
