### ISSUE TITLE
Missing keyboard shortcut docs

### ISSUE THREAD

**Issue by danieluhl** [warpdotdev/warp#538]
### Describe the solution you'd like?

```shell
Looks like the current docs are split right, split up, closing, and navigating between panes.

https://docs.warp.dev/features/keyboard_shortcuts

I use `cmd+e` and `cmd+shift+e` on mac to create new panes, I vaguely recall there's also a shortcut to navigate between panes, but can't find docs on it.
```

**Comment by elviskahoro** [comment]
Thanks for opening this up! You can see all of our keybindings by opening the Command Palette with CMD-P.

Our keybindings for switching panes are directional:
OPT-CMD-LEFT to switch to the left pane
OPT-CMD-RIGHT to switch to the right pane

But I'm trying to see if we can get a generic switch to next pane and switch to previous pane! Just updated docs! Thanks again
