### ISSUE TITLE
Github icon on warp.dev links to discord instead of github

### ISSUE THREAD

**Issue by frazze-jobb** [warpdotdev/Warp#5387]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

The Github icon in the footer of the webpage warp.dev links to discord instead of github.

### To reproduce

Go to warp.dev scroll to the bottom, hoover over the github cat, see that it links to discord

### Operating system

Linux

### Operating system and version

Doesnt matter

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @frazze-jobb thanks for letting us know. I'll make sure to notify the team. We'll be sure to fix this!

**Comment by dannyneira** [comment]
Closing as resolved. This has been fixed in the latest version of https://www.warp.dev
