### ISSUE TITLE
Typo in settings/privacy

### ISSUE THREAD

**Issue by akshaybabloo** [warpdotdev/Warp#5389]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Not really a bug, but there is a typo (image below)

![image](https://github.com/user-attachments/assets/509b202c-b57c-472a-9d66-352c10a7434a)

### To reproduce

None

### Operating system

Linux

### Operating system and version

Ubuntu 22.04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @akshaybabloo thanks for letting us know, good catch! I'll make sure we get this fixed.

**Comment by dannyneira** [comment]
Closing as resolved, this has been fixed in the latest version of Warp. @akshaybabloo thanks for letting us know!

![CleanShot 2024-11-01 at 11 19 07](https://github.com/user-attachments/assets/45aa4c78-c1ad-4072-b513-6fed1843f4ff)
