### ISSUE TITLE
Warp swallowing tab completions from fish

### ISSUE THREAD

**Issue by jubishop** [warpdotdev/Warp#5391]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Tab completion using `z` (among others, but this is an easy repro) is being suppressed by the Warp terminal.

### To reproduce

1 ) Use fish
2) Install fisher (https://github.com/jorgebucaran/fisher) 
-- $ curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher

3) Install z for fish (https://github.com/jethrokuan/z)
-- $ fisher install jethrokuan/z

4) Launch a warp terminal using fish, cd into `/Users/jubi/Library/Developer/Xcode/UserData`, then cd back to `~`

5) Now that the `UserData` folder is in your z history, try entering `z Data` and hit tab.  Nothing happens.

6) Launch basic Mac terminal, make sure you're in fish, try entering the same `z Data` and it will autocomplete successfully to `/Users/jubi/Library/Developer/Xcode/UserData`.

### Expected behavior

See repro steps for details. 

### Operating system

MacOS

### Operating system and version

Sequoia 15.0.1

### Shell Version

fish, version 3.7.1

### Current Warp version

v0.2024.10.15.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by jubishop** [comment]
I think what I really want is some way to tell warp to selectively pass through the "tab" button press rather than commandeering it for its own menu.  So I could say, in this example, "don't trap TAB for z commands and pass it through to fish shell instead"

**Comment by dannyneira** [comment]
Hi @jubishop thanks for submitting. Since Warp has built a wrapper around the shell, to support things like Blocks and the IDE-like input, shell completions aren't passed thru TAB. We do have a request to support shell completions here https://github.com/warpdotdev/Warp/issues/1811

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by jubishop** [comment]
Done thanks!
