### ISSUE TITLE
Display black block instead of results on command when input position is set to start at the top(classic)

### ISSUE THREAD

**Issue by kshetritej** [warpdotdev/Warp#5397]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I am running warp on ubuntu 24 and when I run command  until it fills up to center of terminal it would just display black block and I  need to scroll to top to get see the result and when I scroll down again the output will hide and the block of nothing would appear.

I am using bash with starship prompt and using default dark theme. The vim mode is enabled too.

### To reproduce

To reproduce the bug
1. Go to settings > appearance > Input > Set Input Position to Start at the top (Classic mode)
2. Close the modal
3. Execute any frequent command like `ls`
4. The empty block would be added 
![image](https://github.com/user-attachments/assets/9445490a-c23f-4a4a-b9a3-6c8272ce1163)

5. Scrolling back to top would bring the results and scrolling down will again hide the results. 

### Expected behavior

I would except the result to be visible without further actions other than executing the command and see no blank gaps between my commands.

### Screenshots

>> 
![image](https://github.com/user-attachments/assets/52d85a0c-0ebf-4cd2-a873-c1ba30400258)
>>
![image](https://github.com/user-attachments/assets/695898dd-f1d1-4687-9b47-44816f7cce72)

>>![image](https://github.com/user-attachments/assets/9445490a-c23f-4a4a-b9a3-6c8272ce1163)

### Operating system

Linux

### Operating system and version

Ubuntu 24.04.1 LTS

### Shell Version

zsh 5.9 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2024.10.15.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I am using Wrap on Linux with X11.
Running wrap with this command `RUST_LOG=wgpu_core=info,wgpu_hal=info MESA_DEBUG=1 EGL_LOG_LEVEL=debug warp-terminal` solves the issue.

But the logs are empty, i.e no info are printed.

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @kshetritej sorry to hear about this issue and thanks for your patience, A couple of things may be in play here.

- Do you have any alias for `ls`? I've noticed you ran `clear` before ls, and the `clear` command does push up any command output that are also run along with it. (i.e. `ls='clear ; ls'`)
  - Can you run `which ls` to see what the binary is for that command?
- Does this happen with other normal non-aliased commands (i.e. `cat`)

**Comment by kshetritej** [comment]
The issue seems to be with starship prompt. The terminal works fine when running without any customization.
