### ISSUE TITLE
'Save' Button in the prompt selection goes under the window height

### ISSUE THREAD

**Issue by Zaberahmed** [warpdotdev/Warp#5400]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

In the `Appereance` tab in settings, when I am selecting a prompt style the `save` and `cancel` button both gets hidden under the window height (if the row size is less than 40). I need to manually increase the window height by dragging and then click on `save`.

### To reproduce

1. Go to settings
2. Select the `Appearance` tab
3. Click on `Edit prompt`
4. Select any prompt style
5. Try to save it

### Expected behavior

The `save` and `cancel` buttons should be visible disregarding the window height. Now it gets hidden under the window height (less than 40)

### Screenshots

![Screenshot from 2024-10-18 21-59-29](https://github.com/user-attachments/assets/b32a6fca-7b3a-4223-9af3-a494cfa0c929)

### Operating system

Linux

### Operating system and version

24.04

### Shell Version

zsh 5.9 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2024.10.15.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @Zaberahmed sorry about this. It's a known issue that the Settings modal doesn't scale to the window size so as a workaround you have to maximize the window or increase the size manually to see the cancel/save buttons. 

That being said, we have a request tracking Settings as a separate window over here https://github.com/warpdotdev/Warp/issues/5040

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment]
The new settings tab is officially out in `v0.2025.01.22.08.02.stable_02`, give it a try! 🎉🎉 

<img width="700" alt="Image" src="https://github.com/user-attachments/assets/72fafd6e-c79d-4d3a-a955-58e1ef4a9af7" />
