### ISSUE TITLE
Switch tab in access order

### ISSUE THREAD

**Issue by NiJeTi** [warpdotdev/Warp#5402]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Perform tab switch in order similar to windows on OS. Not just from the first to the last. 

### Is your feature request related to a problem? Please describe.

I'm always frustrated when I need to switch through all opened tabs when I actually just want to quickly jump across 2 the most recent tabs.

### Additional context

Requested feature will work just like the window switching in operating systems.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Currently, Warp does not have a built-in feature to quickly switch between the two most recently used tabs. The existing tab navigation options include:
- Using Cmd + number (1-8) to switch to specific tabs or using keyboard shortcuts to navigate to the previous or next tab sequentially, [as documented here](https://docs.warp.dev/features/windows/tabs#how-to-use-it).

That being said, we're tracking an existing feature request to keyboard shortcut cycle thru the last used tabs over at https://github.com/warpdotdev/Warp/issues/2136

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
