### ISSUE TITLE
Autofill and run last command with Up -> Enter does not work after a new command execution.

### ISSUE THREAD

**Issue by irbeez** [warpdotdev/Warp#541]
### Describe the bug

```shell
Currently when I press the Up key, the command history shows, but does not populate the command line with the previous command. The last command will only be populated when there was input, and then that input was changed or removed.
```

### To Reproduce

Steps to reproduce:
1. Go to command line
2. Type in **clear** and execute command.
3. Press the up key and observe there is nothing being populated into the command line.
4. Select any command from history, and hit enter.
5. The command will be populated, but not run.
6. Delete command from command line completely, and press Up key.
7. Observe now initial command will be populated, and all subsequent navigated commands will be populated.
8. And in this case you can press enter once, instead of twice.

### Expected behaviour

```shell
I would expect the Up key to show command history, populate the last command into the command line, and then allow me to execute said command with the press of enter. At the moment, I need to press up, it selects the last command in the history, and then I need to press enter twice to run the command. This is causing an extra keystroke having to be used almost every time I want to run a command.
```

### Operating System

MacOS

### OS Version

12.0.1

**Comment by elviskahoro** [comment]
@irbeez We're having trouble reproducing the bug. If you can, could you send a video?
Thanks again!

**Comment by irbeez** [comment]
@elviskahoro 

Here is the video of the issue I am seeing. Unsure if this expected behavior in  Warp, but it seems as though
this is not the correct behavior.

I have also attached a screen of some system info in case it could possibly be configuration related.

https://user-images.githubusercontent.com/87586387/147009787-3a93d116-05a0-4e0f-b26c-9d00a8a35d69.mov


<img width="344" alt="image" src="https://user-images.githubusercontent.com/87586387/147009609-864d5f0e-e64e-4ca1-bde6-8e79e1e649f1.png">

**Comment by elviskahoro** [comment]
Can you share your rc files here or over email: elvis@warp.dev

**Comment by irbeez** [comment]
Here is an archive of the rc files you might be wanting to check out.

**Comment by elviskahoro** [comment]
I'm not able to see / download them.

**Comment by irbeez** [comment]
https://drive.google.com/file/d/1l-Blf7k348k4D0Ofu2NEv9hE_iJ8EZic/view?usp=sharing

**Comment by elviskahoro** [comment]
Thanks! I'll try reproducing with these!

**Comment by elviskahoro** [comment]
This was fixed!
