### ISSUE TITLE
Run a script by double clicking it.

### ISSUE THREAD

**Issue by Avivhdr** [warpdotdev/Warp#5412]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

On the left side panel, it would be nice to have an option to run a workflow by double clicking it, instead of only copying it to the terminal by one click.
Also, in the case that my current focused terminal is busy, it would be nice to right click a workflow and select "run in a new terminal"

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @Avivhdr, thanks for these feature requests.

We already have a request tracking click to run Workflows over at https://github.com/warpdotdev/Warp/issues/3226

As well as a request to run workflows in another tab here https://github.com/warpdotdev/Warp/issues/4816

If you could please give them a 👍 and subscribe to those requests, it would help us gauge interest.

We'll be closing this as a duplicate.
