### ISSUE TITLE
Bring back the previous app icon

### ISSUE THREAD

**Issue by pRieStaKos** [warpdotdev/Warp#5418]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Make optional to choose between previous and new app icons.

### Is your feature request related to a problem? Please describe.

I don't like the new app icon. 

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
We receive some feedback recently about the new icon and opened a request for icon choice we are tracking here https://github.com/warpdotdev/Warp/issues/5408

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

Additionally, you can find the older icon on this [thread](https://github.com/warpdotdev/Warp/issues/2703), along with a script to apply it every time Warp updates.

I hope this helps! We'll be closing this as a duplicate.
