### ISSUE TITLE
Pop!_Os ssh Issues packages of violation

### ISSUE THREAD

**Issue by raylivesun** [warpdotdev/Warp#5431]
### Dupe Check

- [X] I have [searched Warp SSH issues](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ASSH) and there are no duplicates

### Operating System

MacOS

### Operating System and Version

Pop!_OS system

### Local Shell Version

bash

### Remote Shell Version

ssh

### Warp Version

terminal

### Have you tried commenting out my system & user rc files?

- [X] Yes

### Screenshots

wines

### Include shell xtrace output

step

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @raylivesun sorry to hear about this issue. There isn't much info on this bug report, such as screenshots, logs or any details on reproducing the issue. 

I'm going to close this out but you're welcome to provide details so we can reopen the issue.
