### ISSUE TITLE
Unable to login after deleting my data.

### ISSUE THREAD

**Issue by S-andres0694** [warpdotdev/Warp#5443]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I am trying to log-in through this GitHub Account to Warp but I keep getting an "Oops, unable to login" error. This happened after I deleted all my data and then restarted the app. 

Now I find myself unable to login regardless of what do I use to login with.

### To reproduce

1. Try to login to Warp
2. Use the "Connect with GitHub" button.
3. Receive the error.

### Expected behavior

I should be able to login.

### Operating system

MacOS

### Operating system and version

15.1

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.10.29.08.02.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

4/11/2024

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Advait-M** [comment]
Hey @S-andres0694 - wanted to clarify, when you say "deleted all my data" are you referring to deleting Warp data via https://app.warp.dev/data_management? i.e. this page?

![image](https://github.com/user-attachments/assets/de88e420-adbe-4aa6-92e0-d81081108c2f)

Or are you referring to deleting Warp as an app locally or its associated files and then reinstalling it?

**Comment by S-andres0694** [comment]
I meant the https://app.warp.dev/data_management page accessed through the privacy settings on Warp

**Comment by S-andres0694** [comment]
I see. 

Thank you very much for the prompt answer and all of the details!
