### ISSUE TITLE
Incorrect antialiasing

### ISSUE THREAD

**Issue by yvt** [warpdotdev/Warp#547]
### Describe the bug

```
The antialiasing of rounded corners of rectangles is imperfect, 
and jagged edges are still visible.
```

### To Reproduce

1. Look closely at any rounded corners drawn inside the application window.

### Screenshots

<img width="500" alt="Screen Shot 2021-12-25 at 14 35 01" src="https://user-images.githubusercontent.com/5253988/147378273-58423a37-1235-42b1-b7a6-dd2ce8846830.png">

### Operating System

MacOS

### Additional context

```
I found that a similar rendering can be obtained by using the
code from
<https://github.com/warpdotdev/samples/blob/892d35e32e15c736c8f378b142373b816ca66c31/how-to-draw-rectangles-using-gpu.metal>.
The following Shadertoy sketch uses the above code to render a
rounded rectangle, illustrating this problem:
<https://www.shadertoy.com/view/7lKXzw>

For an ideal antialiasing, each output pixel should approximate
the average color of the infinite-precision rendering of that
pixel. E.g., the above Shadertoy sketch can be improved by
replacing the following line:

    d = smoothstep(-0.75, -0.1, d);

with this:

    d = clamp(d + 0.5, 0.0, 1.0);

n.b. It's mostly pointless to use `smoothstep` here. Its steeper curve
at the midpoint reduces the effective filter width.

n.b. The above approximation is only accurate for horizontal and
vertical edges. For a better accuracy, the gradient direction of the
distance field could be taken into account. But as it turns out, the
difference is subtle: <https://www.shadertoy.com/view/stKXRm>
```

**Comment by elviskahoro** [comment]
@yvt thanks, both for opening and also for sharing some of your insights into how this could be improved

**Comment by elviskahoro** [comment]
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">
