### ISSUE TITLE
Enshittyfication removal when?

### ISSUE THREAD

**Issue by thepragmaticmero** [warpdotdev/Warp#5486]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Sooo... I need to login to use warp?

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by warpmachineuser** [comment]
Hi @thepragmaticmero yes, for now we have the login requirement, but changes are coming soon!

We will post about it on the feature request to remove it here: https://github.com/warpdotdev/Warp/issues/900

Please stay tuned there and subscribe for updates

Closing as a duplicate.

**Comment by dannyneira** [comment]
Hi @thepragmaticmero yes, for now we have the login requirement, but changes are coming soon!

We will post about it on the feature request to remove it here: https://github.com/warpdotdev/Warp/issues/900

Please stay tuned there and subscribe for updates

Closing as a duplicate.

**Comment by dannyneira** [comment]
Duplicate of #900
