### ISSUE TITLE
SSH connection automatically hangs after being idle for a long time (e.g. 30 minutes)

### ISSUE THREAD

**Issue by liuyangjason** [warpdotdev/Warp#5487]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

the ssh wrapper will hang here automatically after being idle for a long time

### To reproduce

ssh into remote rocky linux and keep the tab/session to be idle for more than 30 minutes. when you switch back to this tab and click any button, it will hung there.

### Operating system

MacOS

### Operating system and version

14.3.1

### Shell Version

GNU bash, version 3.2.57

### Current Warp version

v0.2024.11.12.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

Ignore

**Comment by heysweet** [comment]
Thanks for the bug report! We've been working on a new approach to ssh that should be more robust, and we're in the process of rolling it out now. 

If you'd like to see if the new implementation works better for you, here's how you can try it out:

* Update to the latest version (v0.2024.12.10.15.55.stable_02).
* Enable the new ssh feature:
  * On macOS, run defaults write dev.warp.Warp-Stable SshTmuxWrapperOverride true.
  * On Linux, add the "SshTmuxWrapperOverride": true key-value pair to ~/.config/warp-terminal/user_preferences.json.
* Quit and re-open Warp.

Let me know if this fixes it!

**Comment by liuyangjason** [comment]
It should work now. I am using macOS. after run defaults write dev.warp.Warp-Stable SshTmuxWrapperOverride true and follow the recommendation to install tmux and set following configurations.  I make the ssh session to be idle for about one hour.  no ssh session hangup issue again.

```
Host *
    ServerAliveInterval 60
    ServerAliveCountMax 3
    TCPKeepAlive yes
```

**Comment by liuyangjason** [comment]
it works. see my previous comment
