### ISSUE TITLE
Moving to #258 - Output from backgrounded processes is treated as user input.

### ISSUE THREAD

**Issue by hillegass** [warpdotdev/Warp#550]
### Describe the bug

```shell
The output from processes that have been put into the background are treated as user input.

It should be added to the process output (yes, I realize that the output may trickle in over time -- it still needs to be treated as output.)
```

### To Reproduce

Make a file called test.py.  Make it print the string "ls"

print("ls")

In Warp, run the script in the background:

python3 test.py &

Now press Return.

On mine, the command ls is executed and I see the contents of the current working directory.

### Screenshots

<img width="869" alt="Screen Shot 2021-12-27 at 11 26 25 AM" src="https://user-images.githubusercontent.com/188895/147490016-4bda5e46-d2ec-4eee-899e-443a0a0ec6ae.png">

### Operating System

MacOS

### OS Version

12.0.1

**Comment by elviskahoro** [comment]
Gonna merge this with:
- #258
