### ISSUE TITLE
Missing space between two words

### ISSUE THREAD

**Issue by ModernTTY** [warpdotdev/Warp#5503]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

The error message about previously having signed in using the e-mail address has a missing space between "using" and "your"

![Screenshot 2024-11-22 at 18 19 50](https://github.com/user-attachments/assets/07f52f23-8a8f-4ef1-bc80-7cc980688df3)

### To reproduce

1. Create a warp account using an email.
2. Log in using the email
3. Try the login using a Github account associated with that email.
4. See the misspelling

### Expected behavior

Space between "using and "your"

### Screenshots

![Screenshot 2024-11-22 at 18 19 50](https://github.com/user-attachments/assets/2e69ae19-8f36-4c64-925e-71245f92bc54)

### Operating system

MacOS

### Operating system and version

macOS Sequoia

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @ModernTTY thanks for letting us know! We've fixed this and the text should have the proper space now.

Closing as resolved!
