### ISSUE TITLE
Warp Drive – [No Account]

### ISSUE THREAD

**Issue by ByteEVM** [warpdotdev/Warp#5509]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

If you decide to skip the account creation process, you will be able to use Warp Drive **_partially_**, as newly created or imported workflows can be used, but **not edited**, as Warp Drive will require an account if you decide to do so.

Seems like Warp Drive isn't accommodated to the new accountless behavior yet.

<sub> There's also another accountless bug, described [here](https://github.com/warpdotdev/Warp/issues/900#issuecomment-2495526791) _(in case this thread applies)_.</sub>

### To reproduce

1. Create a new workflow or import one at your Warp Drive.
2. Open the workflow and attempt to edit its contents.
3. Sign In requirement is prompted in order to edit the workflow.

### Expected behavior

Being able to edit workflows without an account.

### Screenshots

![bug](https://github.com/user-attachments/assets/fa46674a-b449-4cc3-a1e3-5ad69b5b007a)

### Operating system

Linux

### Operating system and version

Ubuntu 24.04.1 LTS

### Current Warp version

v0.2024.11.19.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by jefflloyd** [comment]
Hey @ByteEVM ! This is definitely not the intended experience, so appreciate you finding this bug + reporting it! I'll dig in today.

**Comment by jefflloyd** [comment]
Just to close the loop here - this should be fixed as of the v0.2024.11.19.08.02.stable_03 release! Let us know if you see any other issues.
