### ISSUE TITLE
`ssh -T git@github.com` Fails

### ISSUE THREAD

**Issue by fishcharlie** [warpdotdev/Warp#551]
### Describe the bug

```shell
Running `ssh -T git@github.com` produces different output in Warp vs Terminal.app.
```

### To Reproduce

Steps to reproduce:
1. Run `ssh -T git@github.com`

### Expected behaviour

```shell
It to work just like Terminal.
```

### Screenshots

<img width="1136" alt="Screen Shot 2021-12-27 at 1 11 20 PM" src="https://user-images.githubusercontent.com/860375/147504148-1ab13202-c1db-4b6a-9a7e-b78185e57a74.png">

<img width="935" alt="Screen Shot 2021-12-27 at 1 11 24 PM" src="https://user-images.githubusercontent.com/860375/147504154-8d6a3c1d-cae2-4f57-8611-837ebd103109.png">

### Operating System

MacOS

### OS Version

12.2 Beta (21D5025f)

**Comment by elviskahoro** [comment]
@fishcharlie 
Subscribe to (this is where we'll share SSH updates):
- #578
This makes it easy for people to get updates as you'll only need to subscribe to 1 SSH issue.

I've moved this issue to our dedicated SSH discussion:
- #502
This helps us keep things organized and makes it easy to see and discuss all our SSH Bugs.
