### ISSUE TITLE
I can't join Discord

### ISSUE THREAD

**Issue by dzienisz** [warpdotdev/Warp#5528]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I can't join Discord

### To reproduce

Click on discord invitation link anywhere.

### Screenshots

<img width="1244" alt="Screenshot 2024-12-02 at 12 36 46" src="https://github.com/user-attachments/assets/20ce99b2-1538-4a0d-a729-6197983dbf8d">

### Operating system

MacOS

### Operating system and version

don't matter

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @dzienisz thanks for the heads up. I'll look into and fix this broken invite link issue.

**Comment by dannyneira** [comment]
The regular link is back up, thanks! https://discord.com/invite/warpdotdev
