### ISSUE TITLE
Close tab on middle button click

### ISSUE THREAD

**Issue by guyzyl** [warpdotdev/Warp#553]
### Describe the solution you'd like?

```shell
It is very common for tab based interfaces (Chrome, iTerm, etc.) to enable closing open tabs by clicking them with a middle button click.
It'd be very helpful to add this feature to Warp, and to streamline its user experience by doing so.
```

**Comment by elviskahoro** [comment]
This has been triaged but no ETA on release. Will circle back here when it's a WIP.

**Comment by davidrenne** [comment]
@elviskahoro was just about to submit an issue on this +1 this....

**Comment by elviskahoro** [comment]
@Advait-M i think you're looking into this?

**Comment by Advait-M** [comment]
Hey, sorry missed this thread - yep! This was launched in the latest stable release (`v0.2022.08.08.09.21.stable_00`). You can now hover over a tab and press your middle click button to close it. 🎉 

@davidrenne @guyzyl please try it out and feel free to let us know if you have any issues 😄 !
