### ISSUE TITLE
'Warpify subshell' not working properly on google cloud virtual machines

### ISSUE THREAD

**Issue by igorol** [warpdotdev/Warp#5532]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When logging to a virtual machine in google cloud and 'warpify subshell' is selected, every command issued in the terminal prompt is immediately followed by a `warp_run_generator_command ....` command, which makes it very difficult to use warp in remote sessions for gcloud machines
Remote shells can be used without the 'warpify' feature, which decreases a lot the value of using warp in these cases

### To reproduce

A google cloud account is needed

Step 1: Start the VM
```gcloud compute instances start --zone <ZONE> <VM_NAME> --project <PROJECT_NAME>```

Step 2: Log into VM
```gcloud compute ssh <VM_NAME> --project=<PROJECT_NAME> --zone=<ZONE>```

Step 3: Type any command (or type anything actually)
> bla bla
warp_run_generator_command 1733214264258981 'cd "/home/<REDACTED>";         find . -maxdepth 1 -type d -print0 |         while IFS= read -r -d '"'"''"'"' 
f;         do printf '"'"'{"file_name": "%s", "file_type": "Directory"}\n'"'"' "${f#./}"; done;         find . -maxdepth 1 -not -type d -print0 |         while IFS= read -r -d '"'"''"'"' f;         do printf '"'"'{"file_name": "%s", "file_type": "File"}\n'"'"' "${f#./}"; done' 

### Expected behavior

It was expected that nothing extra was printed when typying any commands in the prompt

### Operating system

MacOS

### Operating system and version

MacOS 15.1.1 (24B91)

### Shell Version

zsh 5.9 (arm64-apple-darwin24.0)

### Current Warp version

v0.2024.11.19.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment]
Hi @igorol thanks for reporting. Can you specify a couple of things? What is the shell on the VM? Where is the extra stuff appearing? Is it appearing as input (where you're typing) or as output?

**Comment by igorol** [comment]
VM shell is `zsh`, the extra stuff appears as input and is "executed" (probably, I don't understand exactly what the `warp_run_generator_command` cmd does) which sends my inputs to a new line

Sending a screenshot in hope it will be more clear than my explanation
![Screenshot 2024-12-05 at 19 07 04](https://github.com/user-attachments/assets/cb72a687-7cf9-444e-a492-523f0d64bb5d)

**Comment by acarl005** [comment]
We are working on a revamped SSH experience and so I think this should be fixed once that launches. For now I think the best workaround is to avoid warpifying when logged into these gcloud VMs.

**Comment by igorol** [comment]
Thanks @acarl005

**Comment by acarl005** [comment]
Oh one thing to check.. Do you have this option enabled or disabled?
<img width="993" alt="Screenshot 2024-12-10 at 10 46 08" src="https://github.com/user-attachments/assets/0eadac72-6fb7-4990-b433-e035e944129b">

**Comment by igorol** [comment]
It was marked. I un-marked it and the issue *seems* to be gone.
I feel a little silly if the problem was just a bad config on my side, sorry 😬

**Comment by acarl005** [comment]
Ah great. Closing this out. We'll look into making this a bit less confusing.
