### ISSUE TITLE
discord doesnt loads messages

### ISSUE THREAD

**Issue by CloudyKey009** [warpdotdev/Warp#5536]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

same as title

### To reproduce

it says dns proxy error idk

### Expected behavior

to load discord ¯\_(ツ)_/¯

### Screenshots

![image](https://github.com/user-attachments/assets/65ec729d-2c7e-4825-971b-b6f758460528)

and this

Ara 03 23:59:56 debian warp-svc[933]: 2024-12-03T20:59:56.668Z DEBUG actor_connectivity::connectivity: Routes changed:
Ara 03 23:59:56 debian warp-svc[933]: NewNeighbour; Destination: 192.168.1.1;
Ara 03 23:59:57 debian warp-svc[933]: 2024-12-03T20:59:57.311Z DEBUG main_loop: dns_log: via primary NoError 0ms query:("HTTPS", "music.youtube.com.") answers:[("HTTPS", "youtube-ui.l.google.com.", ">
Ara 03 23:59:57 debian warp-svc[933]: 2024-12-03T20:59:57.311Z DEBUG main_loop: dns_log: via primary NoError 0ms query:("AAAA", "music.youtube.com.") answers:[("AAAA", "youtube-ui.l.google.com.", "2a>
Ara 03 23:59:57 debian warp-svc[933]: 2024-12-03T20:59:57.323Z DEBUG main_loop: dns_log: via primary NoError 12ms query:("A", "music.youtube.com.") answers:[("A", "youtube-ui.l.google.com.", "142.250>
Ara 03 23:59:57 debian warp-svc[933]: 2024-12-03T20:59:57.532Z DEBUG main_loop: dns_log: via primary NoError 7ms query:("A", "discord.com.") answers:[("A", "discord.com.", "162.159.138.232"), ("A", ">
Ara 04 00:00:01 debian warp-svc[933]: 2024-12-03T21:00:01.525Z DEBUG dns_proxy::errors: DnsProxy timeout target=discord.com.
Ara 04 00:00:01 debian warp-svc[933]: 2024-12-03T21:00:01.525Z DEBUG main_loop: dns_log: via primary Timeout 4001ms query:("AAAA", "discord.com.") answers:[] authority:[] additional:[]
Ara 04 00:00:01 debian warp-svc[933]: 2024-12-03T21:00:01.549Z DEBUG main_loop: dns_log: via primary NoError 0ms query:("AAAA", "a.nel.cloudflare.com.") answers:[("AAAA", "a.nel.cloudflare.com.", "26>
Ara 04 00:00:01 debian warp-svc[933]: 2024-12-03T21:00:01.549Z DEBUG main_loop: dns_log: via primary NoError 0ms query:("A", "a.nel.cloudflare.com.") answers:[("A", "a.nel.cloudflare.com.", "35.190.8>
Ara 04 00:00:11 debian warp-svc[933]: 2024-12-03T21:00:11.610Z DEBUG main_loop: dns_log: via primary NoError 0ms query:("AAAA", "edge.microsoft.com.") answers:[("AAAA", "dual-a-0036.a-msedge.net.", ">
Ara 04 00:00:11 debian warp-svc[933]: 2024-12-03T21:00:11.610Z DEBUG main_loop: dns_log: via primary NoError 0ms query:("A", "edge.microsoft.com.") answers:[("A", "dual-a-0036.a-msedge.net.", "204.79>
Ara 04 00:00:11 debian warp-svc[933]: 2024-12-03T21:00:11.635Z DEBUG main_loop: dns_log: via primary NoRecords 25ms query:("HTTPS", "edge.microsoft.com.") answers:[] authority:[("SOA", "a-msedge.net.>
Ara 04 00:00:12 debian warp-svc[933]: 2024-12-03T21:00:12.366Z DEBUG main_loop: dns_log: via primary NoError 13ms query:("A", "github.com.") answers:[("A", "github.com.", "140.82.121.3")] authority:[>
Ara 04 00:00:12 debian warp-svc[933]: 2024-12-03T21:00:12.368Z DEBUG main_loop: dns_log: via primary NoRecords 15ms query:("HTTPS", "github.com.") answers:[] authority:[("SOA", "github.com.", "ns-170>
Ara 04 00:00:12 debian warp-svc[933]: 2024-12-03T21:00:12.393Z DEBUG main_loop: dns_log: via primary NoRecords 15ms query:("AAAA", "github.com.") answers:[] authority:[("SOA", "github.com.", "ns-1707>
Ara 04 00:00:12 debian warp-svc[933]: 2024-12-03T21:00:12.799Z DEBUG main_loop: dns_log: via primary NoError 17ms query:("A", "github-production-user-asset-6210df.s3.amazonaws.com.") answers:[("A", ">
Ara 04 00:00:12 debian warp-svc[933]: 2024-12-03T21:00:12.800Z DEBUG main_loop: dns_log: via primary NoRecords 18ms query:("AAAA", "github-production-user-asset-6210df.s3.amazonaws.com.") answers:[] >
Ara 04 00:00:12 debian warp-svc[933]: 2024-12-03T21:00:12.801Z DEBUG main_loop: dns_log: via primary NoRecords 19ms query:("HTTPS", "github-production-user-asset-6210df.s3.amazonaws.com.") answers:[]>
Ara 04 00:00:13 debian warp-svc[933]: 2024-12-03T21:00:13.367Z DEBUG main_loop: dns_log: via primary NoError 12ms query:("A", "nleditor.osi.office.net.") answers:[("A", "prod-eu-resolver.naturallangu>
Ara 04 00:00:13 debian warp-svc[933]: 2024-12-03T21:00:13.367Z DEBUG main_loop: dns_log: via primary NoError 13ms query:("AAAA", "nleditor.osi.office.net.") answers:[("AAAA", "prod-eu-resolver.natura>
Ara 04 00:00:13 debian warp-svc[933]: 2024-12-03T21:00:13.388Z DEBUG main_loop: dns_log: via primary NoRecords 34ms query:("HTTPS", "nleditor.osi.office.net.") answers:[] authority:[("SOA", "akadns.n>
Ara 04 00:00:13 debian warp-svc[933]: 2024-12-03T21:00:13.817Z DEBUG actor_connectivity::connectivity: Routes changed:
Ara 04 00:00:13 debian warp-svc[933]: NewNeighbour; Destination: 192.168.1.1;
Ara 04 00:00:16 debian warp-svc[933]: 2024-12-03T21:00:16.353Z DEBUG dns_proxy::errors: DnsProxy timeout target=github.com.
Ara 04 00:00:16 debian warp-svc[933]: 2024-12-03T21:00:16.353Z DEBUG main_loop: dns_log: via primary Timeout 4000ms query:("AAAA", "github.com.") answers:[] authority:[] additional:[]
Ara 04 00:00:18 debian warp-svc[933]: 2024-12-03T21:00:18.937Z DEBUG actor_connectivity::connectivity: Routes changed:
Ara 04 00:00:18 debian warp-svc[933]: NewNeighbour; Destination: 192.168.1.1;
Ara 04 00:00:18 debian warp-svc[933]: 2024-12-03T21:00:18.940Z DEBUG actor_connectivity::connectivity: Routes changed:
Ara 04 00:00:18 debian warp-svc[933]: NewNeighbour; Destination: 192.168.1.1;
Ara 04 00:00:28 debian warp-svc[933]: 2024-12-03T21:00:28.033Z DEBUG actor_connectivity::connectivity: Routes changed:
Ara 04 00:00:28 debian warp-svc[933]: NewNeighbour; Destination: 192.168.1.1;
Ara 04 00:00:33 debian warp-svc[933]: 2024-12-03T21:00:33.273Z DEBUG actor_connectivity::connectivity: Routes changed:
Ara 04 00:00:33 debian warp-svc[933]: NewNeighbour; Destination: 192.168.1.1;
Ara 04 00:00:34 debian warp-svc[933]: 2024-12-03T21:00:34.300Z DEBUG actor_connectivity::connectivity: Routes changed:
Ara 04 00:00:34 debian warp-svc[933]: NewNeighbour; Destination: 192.168.1.1;

### Operating system

Linux

### Operating system and version

Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux

### Shell Version

GNU bash, sürüm 5.2.15(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

warp-cli 2024.11.309.0

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

2 hours ago

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @CloudyKey009 Warp is a terminal application and version doesn't match anything that Warp has, we didn't create [warp-cli 2024.11.309.0](https://developers.cloudflare.com/cloudflare-one/changelog/warp/#2024-11-18), Cloudflare did, please reach out to them for support.

Closing as this isn't related to Warp terminal.
