### ISSUE TITLE
Warp ssh wrapper Page not found.

### ISSUE THREAD

**Issue by taras-sereda** [warpdotdev/Warp#5537]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Settings -> Features -> Warp SSH Wrapper info
points to non existing page:
https://docs.warp.dev/features/ssh#implementation

### To reproduce

Settings -> Features -> Warp SSH Wrapper info

### Screenshots

<img width="482" alt="image" src="https://github.com/user-attachments/assets/9d5dd3e8-d992-48e3-8399-c7a4d4c768a1">

### Operating system

MacOS

### Operating system and version

15.1.1 

### Current Warp version

v0.2024.11.19.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Thanks for letting us know @taras-sereda. We're working on a fix!

**Comment by heysweet** [comment]
The fix should be live, thank you again for your report!
