### ISSUE TITLE
Latest build can't be scanned by Apple / can't be installed

### ISSUE THREAD

**Issue by patrickdward** [warpdotdev/Warp#555]
### Describe the bug

```shell
"“Warp.app” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information."
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Screenshots

![Screen Shot 2021-12-29 at 2 36 28 PM](https://user-images.githubusercontent.com/9774647/147708465-2c161412-a8ab-4e3b-a633-dfa9685c514f.png)

### Operating System

MacOS

### OS Version

11.6.2

**Comment by elviskahoro** [comment]
@patrickdward can you email me: elvis@warp.dev
I'll send you a link to a recent dmg! That should fix this.

**Comment by Aiden007700** [comment]
I ran into the same issue just now. Is there any workaround? MacOS v 11.6

**Comment by gradinarot** [comment]
Try to reinstall it

**Comment by gradinarot** [comment]
> I ran into the same issue just now. Is there any workaround? MacOS v 11.6

Try to reinstall it

**Comment by amandaporto** [comment]
I'm also running into this issue. I tried downloading from the website and then uninstalling and reinstalling via brew. Both ways I get this warning.

**Comment by alokedesai** [comment]
Hi all, sorry for the troubles, there's a workaround documented here: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac.

Was the application moved to the /Applications directory before you tried to open it?

**Comment by elviskahoro** [comment]
Gonna close for now. Please comment if this still happens with latest builds.
