### ISSUE TITLE
seems like ssh connection on macOS 15.2 RC is broken

### ISSUE THREAD

**Issue by rsyncOSX** [warpdotdev/Warp#5550]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

ssh from Warp is denied. ssh from default terminal works ok. macOS 15.2 RC. latest version of Warp. ssh from Warp on macOS 15.1 works ok.

### To reproduce

install macOS 15.2 rc

### Operating system

MacOS

### Operating system and version

15.2 rc

### Shell Version

zsh 

### Current Warp version

latest

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

before upgrading to macOS 15.2 rc

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment]
Hi @rsyncOSX thanks for reporting. Can you try again after disabling the Warp SSH wrapper in Settings > Features > Session > Warp SSH Wrapper?

We're actually deprecating this feature. We're working on a whole revamped SSH experience.

For now, you can just disable our SSH wrapper and it should function exactly the same as any other terminal.

**Comment by rsyncOSX** [comment]
Hmm, still does not work... Disabled the SSH Wrapper, Warp refuser to Connect by SSH..

<img width="1136" alt="Screenshot 2024-12-09 at 06 20 11" src="https://github.com/user-attachments/assets/0c59ac7b-a16b-4d6d-85c4-7c81ff3b60c8">
<img width="1136" alt="Screenshot 2024-12-09 at 06 20 20" src="https://github.com/user-attachments/assets/d35d42eb-06fe-4148-8bdc-2349b2195e3d">

**Comment by rsyncOSX** [comment]
Also did a restant of Warp after disabled the SSH Wrapper..

**Comment by acarl005** [comment]
Is there an error message you can share when you attempt the connection?

**Comment by acarl005** [comment]
Can you try with verbose logging and post the logs?

```
ssh -vvv thomas@raspberrypi
```

**Comment by rsyncOSX** [comment]
`ssh -vvv thomas@raspberrypi
OpenSSH_9.8p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/thomas/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/thomas/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/thomas/.ssh/known_hosts2'
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug3: channel_clear_timeouts: clearing
debug1: Connecting to raspberrypi port 22.
ssh: connect to host raspberrypi port 22: Undefined error: 0`

**Comment by rsyncOSX** [comment]
And here is the same from the default terminal in macOS 
`ssh -vvv thomas@raspberrypi
OpenSSH_9.8p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/thomas/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/thomas/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/thomas/.ssh/known_hosts2'
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug3: channel_clear_timeouts: clearing
debug1: Connecting to raspberrypi port 22.
debug1: Connection established.
debug1: identity file /Users/thomas/.ssh/id_rsa type 0
debug1: identity file /Users/thomas/.ssh/id_rsa-cert type -1
debug1: identity file /Users/thomas/.ssh/id_ecdsa type -1
debug1: identity file /Users/thomas/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/thomas/.ssh/id_ecdsa_sk type -1
debug1: identity file /Users/thomas/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /Users/thomas/.ssh/id_ed25519 type 3
debug1: identity file /Users/thomas/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/thomas/.ssh/id_ed25519_sk type -1
debug1: identity file /Users/thomas/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /Users/thomas/.ssh/id_xmss type -1
debug1: identity file /Users/thomas/.ssh/id_xmss-cert type -1
debug1: identity file /Users/thomas/.ssh/id_dsa type 1
debug1: identity file /Users/thomas/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_9.2p1 Debian-2+deb12u3
debug1: compat_banner: match: OpenSSH_9.2p1 Debian-2+deb12u3 pat OpenSSH* compat 0x04000000
debug3: fd 5 is O_NONBLOCK
debug1: Authenticating to raspberrypi:22 as 'thomas'
debug3: record_hostkey: found key type ED25519 in file /Users/thomas/.ssh/known_hosts:3
debug3: record_hostkey: found key type RSA in file /Users/thomas/.ssh/known_hosts:4
debug3: record_hostkey: found key type ECDSA in file /Users/thomas/.ssh/known_hosts:5
debug3: load_hostkeys_file: loaded 3 keys from raspberrypi
debug1: load_hostkeys: fopen /Users/thomas/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug3: order_hostkeyalgs: have matching best-preference key type ssh-ed25519-cert-v01@openssh.com, using HostkeyAlgorithms verbatim
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c,kex-strict-c-v00@openssh.com
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,kex-strict-s-v00@openssh.com
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug3: kex_choose_conf: will use strict KEX ordering
debug1: kex: algorithm: sntrup761x25519-sha512@openssh.com
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:6oq05mpLp9xKwWD/UgQr+LNsVP0rEL8aRz30o03mw+4
debug3: record_hostkey: found key type ED25519 in file /Users/thomas/.ssh/known_hosts:3
debug3: record_hostkey: found key type RSA in file /Users/thomas/.ssh/known_hosts:4
debug3: record_hostkey: found key type ECDSA in file /Users/thomas/.ssh/known_hosts:5
debug3: load_hostkeys_file: loaded 3 keys from raspberrypi
debug1: load_hostkeys: fopen /Users/thomas/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host 'raspberrypi' is known and matches the ED25519 host key.
debug1: Found key in /Users/thomas/.ssh/known_hosts:3
debug3: send packet: type 21
debug1: ssh_packet_send2_wrapped: resetting send seqnr 3
debug2: ssh_set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: ssh_packet_read_poll2: resetting read seqnr 3
debug1: SSH2_MSG_NEWKEYS received
debug2: ssh_set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug2: KEX algorithms: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c,kex-strict-c-v00@openssh.com
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug3: kex_input_ext_info: extension server-sig-algs
debug1: kex_ext_info_client_parse: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com,ssh-dss,ssh-rsa,rsa-sha2-256,rsa-sha2-512>
debug3: kex_input_ext_info: extension publickey-hostbound@openssh.com
debug1: kex_ext_info_check_ver: publickey-hostbound@openssh.com=<0>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug3: ssh_get_authentication_socket_path: path '/private/tmp/com.apple.launchd.3KNQEc42jj/Listeners'
debug1: get_agent_identities: bound agent to hostkey
debug1: get_agent_identities: ssh_fetch_identitylist: agent contains no identities
debug1: Skipping ssh-dss key /Users/thomas/.ssh/id_dsa - corresponding algorithm not in PubkeyAcceptedAlgorithms
debug1: Will attempt key: /Users/thomas/.ssh/id_rsa RSA SHA256:qxbdq5r2KPPfj3Bt8vJwOX2yIjESoFCfqvu6sCd495g
debug1: Will attempt key: /Users/thomas/.ssh/id_ecdsa 
debug1: Will attempt key: /Users/thomas/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /Users/thomas/.ssh/id_ed25519 ED25519 SHA256:Olu9N9QzYN250h65RfraBG1YwWEj0WsKXRtJ0nYUf4I
debug1: Will attempt key: /Users/thomas/.ssh/id_ed25519_sk 
debug1: Will attempt key: /Users/thomas/.ssh/id_xmss 
debug2: pubkey_prepare: done
debug1: Offering public key: /Users/thomas/.ssh/id_rsa RSA SHA256:qxbdq5r2KPPfj3Bt8vJwOX2yIjESoFCfqvu6sCd495g
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: /Users/thomas/.ssh/id_rsa RSA SHA256:qxbdq5r2KPPfj3Bt8vJwOX2yIjESoFCfqvu6sCd495g
debug3: sign_and_send_pubkey: using publickey-hostbound-v00@openssh.com with RSA SHA256:qxbdq5r2KPPfj3Bt8vJwOX2yIjESoFCfqvu6sCd495g
debug3: sign_and_send_pubkey: signing using rsa-sha2-512 SHA256:qxbdq5r2KPPfj3Bt8vJwOX2yIjESoFCfqvu6sCd495g
debug3: send packet: type 50
debug3: receive packet: type 52
Authenticated to raspberrypi ([192.168.86.96]:22) using "publickey".
debug1: channel 0: new session [client-session] (inactive timeout: 0)
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: filesystem
debug3: client_repledge: enter
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: client_input_hostkeys: received RSA key SHA256:+N3n1mvSR7yvYj0LEallcIV7s6aMOwAIRBXvlty/PPg
debug3: client_input_hostkeys: received ECDSA key SHA256:0oJcwioTrWnyRHPeaix25koMWgCtomf6WWhl8pHOEqU
debug3: client_input_hostkeys: received ED25519 key SHA256:6oq05mpLp9xKwWD/UgQr+LNsVP0rEL8aRz30o03mw+4
debug1: client_input_hostkeys: searching /Users/thomas/.ssh/known_hosts for raspberrypi / (none)
debug3: hostkeys_foreach: reading file "/Users/thomas/.ssh/known_hosts"
debug3: hostkeys_find: found ssh-ed25519 key at /Users/thomas/.ssh/known_hosts:3
debug3: hostkeys_find: found ssh-rsa key at /Users/thomas/.ssh/known_hosts:4
debug3: hostkeys_find: found ecdsa-sha2-nistp256 key at /Users/thomas/.ssh/known_hosts:5
debug3: hostkeys_find: found ssh-ed25519 key under different name/addr at /Users/thomas/.ssh/known_hosts:8
debug1: client_input_hostkeys: searching /Users/thomas/.ssh/known_hosts2 for raspberrypi / (none)
debug1: client_input_hostkeys: hostkeys file /Users/thomas/.ssh/known_hosts2 does not exist
debug3: client_input_hostkeys: 3 server keys: 0 new, 3 retained, 0 incomplete match. 0 to remove
debug1: client_input_hostkeys: no new or deprecated keys from server
debug3: client_repledge: enter
debug3: receive packet: type 4
debug1: Remote: /home/thomas/.ssh/authorized_keys:3: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug3: receive packet: type 4
debug1: Remote: /home/thomas/.ssh/authorized_keys:3: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 5 setting TCP_NODELAY
debug3: set_sock_tos: set socket 5 IP_TOS 0x48
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug3: send packet: type 98
debug1: Sending environment.
debug3: Ignored env __CFBundleIdentifier
debug3: Ignored env TMPDIR
debug3: Ignored env XPC_FLAGS
debug3: Ignored env TERM
debug3: Ignored env SSH_AUTH_SOCK
debug3: Ignored env XPC_SERVICE_NAME
debug3: Ignored env TERM_PROGRAM
debug3: Ignored env TERM_PROGRAM_VERSION
debug3: Ignored env TERM_SESSION_ID
debug3: Ignored env SHELL
debug3: Ignored env HOME
debug3: Ignored env LOGNAME
debug3: Ignored env USER
debug3: Ignored env PATH
debug3: Ignored env SHLVL
debug3: Ignored env PWD
debug3: Ignored env OLDPWD
debug3: Ignored env P9K_TTY
debug3: Ignored env _P9K_TTY
debug3: Ignored env ZSH
debug3: Ignored env PAGER
debug3: Ignored env LESS
debug3: Ignored env LSCOLORS
debug3: Ignored env LS_COLORS
debug3: Ignored env P9K_SSH
debug3: Ignored env _P9K_SSH_TTY
debug1: channel 0: setting env LC_CTYPE = "UTF-8"
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env _
debug3: Ignored env __CF_USER_TEXT_ENCODING
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug3: client_repledge: enter
debug1: pledge: fork
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0
Linux raspberrypi 6.6.62+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Dec  9 18:27:11 2024 from 192.168.86.120`

**Comment by heysweet** [comment]
Thanks for the bug report! We've been working on a new approach to ssh that should be more robust, and we're in the process of rolling it out now. 

If you'd like to see if the new implementation works better for you, here's how you can try it out:

* Update to the latest version (v0.2024.12.10.15.55.stable_02).
* Enable the new ssh feature:
  * On macOS, run defaults write dev.warp.Warp-Stable SshTmuxWrapperOverride true.
  * On Linux, add the "SshTmuxWrapperOverride": true key-value pair to ~/.config/warp-terminal/user_preferences.json.
* Quit and re-open Warp.

Let me know if this fixes it!

**Comment by rsyncOSX** [comment]
Sorry, did not fix it.. The second last figure is Iterm2 connection to my server by SSH, after trying to Connect by Warp. Warp also tried to solve the issue by ping, see last figure 

<img width="1207" alt="Screenshot 2024-12-12 at 22 06 24" src="https://github.com/user-attachments/assets/d4baef08-32cf-4256-acec-f2825ce1e6c5" />
<img width="1207" alt="Screenshot 2024-12-12 at 22 08 35" src="https://github.com/user-attachments/assets/5a15c367-796c-4c52-bf5d-c02e66a6217c" />
<img width="1207" alt="Screenshot 2024-12-12 at 22 08 53" src="https://github.com/user-attachments/assets/7313fb4e-adfc-4c38-b260-bc878bacd9d7" />
<img width="1207" alt="Screenshot 2024-12-12 at 22 09 24" src="https://github.com/user-attachments/assets/f7af39a1-e87a-41e9-8c36-291cb22408fb" />
<img width="890" alt="Screenshot 2024-12-12 at 22 09 44" src="https://github.com/user-attachments/assets/c0b44ff7-3a10-4e3a-8066-fdbca9d00999" />
<img width="1207" alt="Screenshot 2024-12-12 at 22 13 28" src="https://github.com/user-attachments/assets/afd57506-e70a-4448-8218-dd7a4b1b44bc" />

**Comment by rsyncOSX** [comment]
In macOS 15, Warp has to be added Settings, Privacy & Security, Local Network.. And now SSH works ...

**Comment by rogerkerse** [comment]
I have everything enabled in Settings but it doesn't work, I still get "undefined" error
