### ISSUE TITLE
A blackscreen without text running after installing

### ISSUE THREAD

**Issue by ShianHui** [warpdotdev/Warp#5554]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I am running:
No LSB modules are available.
![Screenshot 2024-12-10 003234](https://github.com/user-attachments/assets/1f7abef5-9df0-4a63-9b68-2c854e6060eb)

Distributor ID: Ubuntu
Description: Ubuntu 22.04.5 LTS
Release: 22.04
Codename: jammy

Installed warp-terminal using:
sudo apt install warp-terminal_0.2024.12.03.08.02.stable.04_amd64.deb

After installation, the warp-terminal is just a black screen:
Screenshot 2024-12-10 003234

user_preferences.json is as follow:
{
"prefs": {
"ChangelogVersions": "{"v0.2024.12.03.08.02.stable_04":true}",
"TelemetryEnabled": "true",
"SameLinePromptBlockState": ""DoNotShow"",
"AIRequestLimitInfo": "{"limit":100,"num_requests_used_since_refresh":0,
"next_refresh_time":"2025-01-08T09:20:03.072237Z","is_unlimited":false}",
"AIAssistantRequestLimitInfo": "{"limit":100,"num_requests_used_since_ref
resh":0,"next_refresh_time":"2025-01-08T09:20:03.072237Z","is_unlimited":
false}",
"AgentModeOnboardingBlockShown": "true",
"ReceivedReferralTheme": ""Inactive"",
"CrashReportingEnabled": "true",
"ExperimentId": "4e1f3728-564e-41bb-af73-0af633e398e6"
}
}

I have the Hack Nerd Font and other nerd fonts installed but still just getting the black screen.

Tried installing and reinstalling warp-terminal to no help. In fact, tried on another debian based Lubuntu OS. The results were the same.

Hope someone can assist. Thanks.

### To reproduce

1. Install Ubuntu or Lubuntu on Vmware Workstation Pro 17
2. Download warp-terminal_0.2024.12.03.08.02.stable.04_amd64.deb
3. Installed warp-terminal using:
sudo apt install warp-terminal_0.2024.12.03.08.02.stable.04_amd64.deb
4. sudo apt update && sudo apt install -f

### Screenshots

![Screenshot 2024-12-10 003234](https://github.com/user-attachments/assets/d1db6a6d-95d6-42ee-bca6-9a9d73e870b4)

### Operating system

Linux

### Operating system and version

Ubuntu 22.04.5 LTS

### Shell Version

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.12.03.08.02.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

[RUST_LOG.log](https://github.com/user-attachments/files/18082358/RUST_LOG.log)

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
hey @ShianHui thanks for submitting this. Unfortunately, Warp for Linux isn't supported to run on VMware virtual machines at this time. This is due to VMware graphics drivers not being supported at this time (we only support VirtualBox VMs as far as I'm aware), but we are tracking this request here. https://github.com/warpdotdev/Warp/issues/4598

We would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by ShianHui** [comment]
Hi @dannyneira 

WGPU_BACKEND=Vulkan warp-terminal is working with VMware Workstation Pro 17. Great stuff! Many thanks! Apologies for the duplicate!
