### ISSUE TITLE
Inconsistent Secret Redaction Behavior

### ISSUE THREAD

**Issue by x9xhack** [warpdotdev/Warp#5574]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When secret redaction is disabled, secrets are visible in the terminal as expected. However, when I copy these secrets, they are replaced with *******************************. In contrast, when secret redaction is enabled, secrets are masked, and I can reveal and copy their actual values correctly.

### To reproduce

1. **With Secret Redaction Disabled:**
   - Disable secret redaction in settings.
   - Run a command that displays secrets in the terminal.
   - Copy a visible secret from the terminal.
   - **Result:** Copied value is replaced with `*******************************`.

### Expected behavior

When secret redaction is disabled, secrets should not be masked in the terminal or altered when copied.

### Operating system

Linux

### Operating system and version

Kali Linux 2024.4

### Shell Version

fish, version 3.7.1

### Current Warp version

v0.2024.12.10.15.55.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by rafbgarcia** [comment]
Please prioritize this. I'm unable to copy DB record ids, this is a productivity killer.

<img width="960" alt="Cursor_and_bin_rails" src="https://github.com/user-attachments/assets/50892046-1f70-499a-8990-ad03f5b42025" />

**Comment by Advait-M** [comment]
Hey @x9xhack @rafbgarcia - thank you for calling out this bug, and sorry for the impact here!

I've confirmed this is a regression and have a fix up for this internally. I'll update this thread when we have a release live with the fix (will be Thursday or earlier).

**Comment by igielskv** [comment]
Workaround:
If you go to Settings > Privacy > Secret redaction ... toggle switch On and back Off it works again as expected.

But absolutely I would consider this behavior as a bug.

**Comment by totoCZ** [comment]
Even after disable/enable it still happens. This is the kind of this that needs immediate downgrade :(

**Comment by totoCZ** [comment]
>But absolutely I would **** this behavior as a *****.

Can you please resend my terminal not showing

**Comment by Advait-M** [comment]
Hey folks - this issue has been resolved and we've pushed a new release. Please update to `v0.2024.12.10.15.55.stable_04` which includes the fix for this.

Let us know if you have any other issues (please open a new issue)!

Sorry for the impact here!

**Comment by rafbgarcia** [comment]
Thanks @Advait-M !

<img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExeTdyMG5kaGRiMnF3ZjRzcGZzMW50NnFvYnBuczBhemVsbGhrdmU5ZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o8doT9BL7dgtolp7O/giphy.gif" />

**Comment by x9xhack** [comment]
Awesome , Thanks @Advait-M
