### ISSUE TITLE
Cursor stuttering in Linux Mint when using fractional scaling

### ISSUE THREAD

**Issue by 66RED99** [warpdotdev/Warp#5578]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Everything works fine with the default scaling provided in mint os (100% and 200%).
But when I use fractional scaling (125%, 150% etc).

The warp terminal is stuttering and lagging so much.

### To reproduce

1. Enable fractional scaling in the display settings.
2. set the scaling to any value other than default

### Expected behavior

Everything working lag free.

### Operating system

Linux

### Operating system and version

Mint Cinnamon

### Current Warp version

v0.2024.12.10.15.55.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment]
Hey @66RED99, thanks for reporting and sorry for the issues you're having. 

Would you mind sending us a video and your Warp logs https://docs.warp.dev/help/sending-us-feedback#gathering-warp-logs so we can debug further?

In addition, if you enable native Wayland support in your settings and restart Warp does it fix the issue?

**Comment by 66RED99** [comment]
Hi ,

**Comment by 66RED99** [comment]
Hi, the issue is not from warp but from Linux mint, it seems fractional scalling is not at all stable in Linux mint, so i will be closing this.
