### ISSUE TITLE
Wrap terminal copied IP can not be displayed, but I have disabled secret redaction

### ISSUE THREAD

**Issue by haoami** [warpdotdev/Warp#5579]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I have disabled secret redaction, and then I want to copy the IP but it doesn't show up after I paste it. I don't see a solution in the documentation.

### To reproduce

Not yet

### Expected behavior

The ip is pasted and displayed correctly

### Screenshots

![image](https://github.com/user-attachments/assets/df6208d1-7b95-4414-ad4b-e9185557b41c)

### Operating system

MacOS

### Operating system and version

macos15

### Shell Version

zsh 5.9 (arm64-apple-darwin24.0)

### Current Warp version

v0.2024.12.10.15.55.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Not yet 

### Additional context

Not yet

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by maxpain** [comment]
the same problem

**Comment by x9xhack** [comment]
[https://github.com/warpdotdev/Warp/issues/5574](5574)

**Comment by Advait-M** [comment]
Hey @haoami @maxpain @x9xhack! Thank you for raising this bug!

I've confirmed this is a regression and I have a fix up for this internally. I'll update this thread when we have a release live with the fix (will be Thursday or earlier).

**Comment by austinginder** [comment]
Same issue. I was able to get it to go away after enabling `Secret Redaction` and then disabling `Secret Redaction`.

**Comment by chenzhiguo** [comment]
mark, me too

**Comment by nuthub-io** [comment]
Mark me too. It is really annoying.

**Comment by vxjohanforssell** [comment]
> Same issue. I was able to get it to go away after enabling `Secret Redaction` and then disabling `Secret Redaction`.

It still comes back.

This is table flip level of annoying

**Comment by nuthub-io** [comment]
> >

Yeah this option doesn't work. We'll have to wait for the fix I guess. Really annoying when you use it as main terminal for work purposes.

**Comment by kira-sakuya** [comment]
I have the same problem, and it's not limited to IP, but anything dealing with Secret Redaction.

**Comment by tim-hanssen** [comment]
Highly frustrated... sme here

**Comment by TsvetomirValchev** [comment]
It also seems to make uuids appear as `****` which is extremely annoying.

**Comment by Advait-M** [comment]
Hey folks - this issue has been resolved and we've pushed a new release. Please update to `v0.2024.12.10.15.55.stable_04` which includes the fix for this.

Let us know if you have any other issues (please open a new issue)!

Sorry for the impact here!

**Comment by vbcnv5eknx** [comment]
Same here. no solution?
