### ISSUE TITLE
Terrible feature

### ISSUE THREAD

**Issue by erasebegin** [warpdotdev/Warp#5585]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I have no idea why this has started happening in Warp. At first it was annoying, but it is now completely, irreversibly messing up my projects. It has destroyed hours worth of work.

I see this link icon appear in the tab at the top, and then somehow when I'm working in another tab, it just starts mimicking my inputs from one tab in another tab. So I'm busy writing code in one tab while my work is being completely destroyed in another tab. 

What is this completely stupid feature? Or is it a bug?

I have been a very happy Warp user for more than a year now, but this alone is enough to make me leave.

<img width="540" alt="image" src="https://github.com/user-attachments/assets/ff9d3935-49b1-44f0-a0ae-b1cf9d24dcdf" />

### To reproduce

Working across multiple tabs using Helix editor

### Expected behavior

No stupid crazy linking behaviour

### Screenshots

<img width="540" alt="image" src="https://github.com/user-attachments/assets/32d57b42-5fb6-4b2f-a6c4-948ce436f8c6" />

### Operating system

MacOS

### Operating system and version

15.1.1

### Current Warp version

v0.2024.12.03.08.02.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @erasebegin That's the Syncronized input feature you're noticing. Which has some default keybindings on Mac:
- Synchronize All Panes in Current Tab `OPT-CMD-I`
- Stop Synchronizing Any Panes `OPT-CMD-I`

You can also enable or disable the input mode from the Command Palette `CMD-P`. Please make sure you do not have other key binds set for the same which could be triggering the feature by accident. Go to `Settings > Keyboard Shortcuts` and search for "OPT CMD I" to see what else is bound to those keys. https://docs.warp.dev/features/entry/synchronized-inputs

That being said, we can work on better communicating that it's enabled and possibly unbinding the default keyboard shortcuts to prevent accidentally triggering it.

**Comment by erasebegin** [comment]
I now understand what is happening. I have a key on a layer bound to
opt+cmd+i to easily open the browser dev tools ... I sometimes press it
accidentally.

I have no idea what the purpose of this linking feature is but it seems
quite niche so yes, maybe an idea to unbind it since it is a dangerous
feature. It allows the user to make changes that they are completely
unaware of. Some accidental keypresses might even lead to git commits and
such depending on key bindings. Initially it led me to break things in my
application without realising it. Although it was easily fixed that time.
Later it led me to destroy hours of code that had not yet been committed.

I'm sure there are many web developers that use Warp and I'm sure there are
plenty of them who play around with keybindings to speed up their workflow
and to increase ergonomics.

Please consider disabling this feature by default.

Thank you for the quick and detailed response. Very much appreciated.

**Comment by dannyneira** [comment]
Thanks for your feedback, it totally makes sense that there are other keybinds that may conflict. I recommend you Delete the keybinds from your `Settings > Keyboard Shortcuts` menu , search for "Sync" and delete them so that they aren't triggered on accident.

I will bring this up with the team and we'll look into some options for better UX with this feature.

**Comment by dannyneira** [comment]
Closing as this isn't a bug. Although the feature may be triggered on accident, which this is something we'll look into.

**Comment by dannyneira** [comment]
@erasebegin It's possible this is a bug. To clarify, when you have the sync enabled in the left Tab, did the right Tab that isn't synced also send commands to the synced tab? (the synced tabs have the little chain icon)
