### ISSUE TITLE
Active AI should be Opt-In

### ISSUE THREAD

**Issue by Gonkers** [warpdotdev/Warp#5586]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I would like to **not** be auto enabled in features that could possibly send my data to parties outside of my organization. I wasn't very happy about having an online account to use Warp, but this feature was too much for me. You have a promising product and I wish you success, but it will be without me.  Good luck!

### Is your feature request related to a problem? Please describe.

I appreciate you being upfront about the Active AI feature, but it should be opt-in, not opt-out.
![Screenshot 2024-12-16 at 5 56 54 PM](https://github.com/user-attachments/assets/64cb0eb9-03dd-4af3-899f-8682612df427)

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hey @Gonkers thanks for your feedback on the new Active AI features and this request.

Warp has recently added a global AI opt-out setting that disables all AI features and removes AI-related UI elements in addition to the option to disable any Active AI features (including any future AI features we may release, like the [Next Command](https://docs.warp.dev/features/warp-ai/active-ai#next-command-coming-soon) which is coming soon). Warp actively listens to our users' feedback and concerns and so this was implemented in response to user feedback on [GitHub issue #2808](https://github.com/warpdotdev/Warp/issues/2808).

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by zachbai** [comment]
@Gonkers Thanks for reaching out. Just to add onto Danny's response above, if you've opted out from either global AI or just at the active AI level, you won't be opted-in to any new AI features in future release and importantly, won't have to deal with any future noise in the UI for them (e.g. no more AI-related modals or announcements within the app).

Totally understand that the repeated notifications about such new features and having to opt-out is a pain. Hopefully in this case, the settings that danny mentioned are 'better late than never'

Closing this as I don't think there's anything actionable on our side (and that the toggle to disable Active AI will in fact opt-you out automatically for all related features in the future).

**Comment by ppassmannpriv** [comment]
I would love for any and all AI functionality to have it be opt-in to have AI features. My employer requires this option for engineers to even be allowed to use warp.

On a personal note I would also love the opt-in instead of opt-out. I mentor people and want them to actually learn a few things and not have it all be off-loaded to an AI. Performance and offline functionality also is important to me as I regularly go into environments where there simply is no internet access. The AI craze is getting tiring.
