### ISSUE TITLE
After today's update, window is chartreuse; no text visible.

### ISSUE THREAD

**Issue by jimratliff** [warpdotdev/Warp#5587]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I was told to update. I did. (I'd tell you what version, but when I do "About Warp," I don't see anything. (Perhaps because (a) it's not a separate window? and (b) I can't see anything in the main Warp window; just solid color.)
<img width="293" alt="Screenshot 2024-12-16 at 4 15 18 PM" src="https://github.com/user-attachments/assets/41161a70-6912-4279-9442-afa49e2a7167" />

### To reproduce

1. Update to latest version.
2. "There is no step two." (paraphrasing Steve Jobs)

### Operating system

MacOS

### Operating system and version

15.2.0

### Current Warp version

v0.2024.12.10.15.55.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @jimratliff, sorry to hear about this, it seems to have been an issue with a recent upgrade to MacOS affecting other apps, not just Warp. It seems like [restarting the Mac](https://github.com/warpdotdev/Warp/issues/3604#issuecomment-1718732241) should fix this issue.

Please let me know if that helped with your issue or if you still see the pink screen after restart.

**Comment by jimratliff** [comment]
Restarting fixed it. Thanks!
