### ISSUE TITLE
npx commands running very slowly

### ISSUE THREAD

**Issue by jakeherp** [warpdotdev/Warp#559]
### Describe the bug

```shell
Running `npx` commands is very slow and for certain scripts keeps hanging indefinitely, for example `npx sb@latest upgrade` (upgrading storybook in a React project) remained stuck at 


 • Checking for latest versions of '@storybook/*' packages
```

Running the same command in iTerm2 executed without delay, ruling out a timeout of npm in that case.
```


### To Reproduce

_No response_

### Expected behaviour

```shell
Should execute npx commands and fetch packages from npm without delay.
```

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment]
Hey jake! I need your help reproing this. Are there any react projects on github that I can download to test the command with?

**Comment by elviskahoro** [comment]
@jakeherp Hey jake! I need your help reproing this. Are there any react projects on github that I can download to test the command with?
