### ISSUE TITLE
Tab completion makes useless suggestions

### ISSUE THREAD

**Issue by dmulder** [warpdotdev/Warp#5599]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When I go to open a file in vim, I normally use tab completion to show me the directory listing. Instead, Warp tries to guess the file I want to open. 90% of the time it is wrong. For example, if I opened the file `src/common/src/idprovider/himmelblau.rs` previously, it suggests this, even if I'm in a different directory and that file doesn't exist from the present directory!

### To reproduce

Open a directory
Open a file in that directory
Change directory
Go to open a different file, tab complete the directory listing, and Warp suggests the previously opened file.

### Expected behavior

Warp suggestions need to include context.

### Screenshots

![Screenshot From 2024-12-19 10-33-59](https://github.com/user-attachments/assets/b154ea10-5dce-4914-b0f8-f62ca2fb2620)

### Operating system

Linux

### Operating system and version

openSUSE Tumbleweed 20241211

### Shell Version

bash 5.2.37

### Current Warp version

v0.2024.12.10.15.55.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by vorporeal** [comment]
Hi @dmulder - are you referring to the auto-suggestion that shows up as a placeholder in the input?

If so, do you have `tab` bound to accepting that suggestion ("Accept Autosuggestion"), as opposed to bound to showing possible completions ("Open Completions Menu")?

**Comment by dmulder** [comment]
AH. Well, that made it work. That's a very bizarre default behavior.

**Comment by vorporeal** [comment]
I agree it would be very bizarre default behavior, which is why it isn't our default behavior. :)

Did you just start using Warp for the first time, or did you use it in the past and recently give it another go?  (We used to have a flow where you could choose whether `tab` opened the completions menu or accepted the auto-suggestion, so I'm curious if perhaps you chose the "wrong" option a while ago.)

**Comment by dmulder** [comment]
Ah, yes. I tried it 6 months ago or so. You guys fixed a few bugs since then, and I decided to try it again today.

**Comment by vorporeal** [comment]
We're working every day to make Warp better and better!  Please continue to let us know if you run into bugs or have other feedback. :)

**Comment by dmulder** [comment]
I have to admit, aside from #5600 now, it's actually proving to be very useful. I really like using workflows to automate bits of my work.
