### ISSUE TITLE
using fn-arrows to pgup/pgdown has strange behaviour

### ISSUE THREAD

**Issue by phrawzty** [warpdotdev/Warp#560]
### Describe the bug

Hello,

When in vim and using the fn+arrow keys to page-up and page-down (as normal), vim will enter insert mode and then add newlines. This doesn't happen in iTerm or terminal.app.

**UPDATE 2022-01-07**: I originally filed this as a vim-related bug, but in fact, this errant behaviour is present _in general_ (e.g. `less` or `bat` or anything where pgup/pgdwn is used).

### To Reproduce

Steps to reproduce:
1. Open a file in `vim --clean`
2. Use fn+arrow keys to page-up and page-down

### Expected behaviour

Vim does not enter insert mode, nor does it insert newlines; it just pages-up and pages-down as normal.

### Screenshots

![Screen Recording 2022-01-04 at 12 14 42 PM](https://user-images.githubusercontent.com/625232/148051267-291f8276-2f67-42ff-a9f0-492310ef9d39.gif)

### Operating System

MacOS

### OS Version

* 11.6.1
* **UPDATE**: also 12.2.1

### Additional context

* Warp is latest afaik: warp `v0.2021.12.27.09.04.stable_01`
* **UPDATE**: also in warp `v0.2022.01.03.09.07.stable_01`
* **UPDATE**: also in warp `v0.2022.01.17.08.48.stable_01`
* **UPDATE**: also in warp `v0.2022.01.24.08.55.stable_01`
* **UPDATE**: also in warp `v0.2022.02.21.08.55.stable_00`
* **UPDATE**: also in warp `v0.2022.03.29.02.23.stable_01`

vim is MacOS default:

```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep  6 2021 01:30:12)
macOS version
Included patches: 1-2029
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
-arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      -mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        -termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
-balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            -gettext           +netbeans_intg     +termresponse
+builtin_terms     -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           -ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     -keymap            +postscript        -vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      -langmap           -profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
-conceal           +linebreak         -python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          -rightleft         +wildignore
+cursorshape       -lua               +ruby/dyn          +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
-emacs_tags        -mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      -mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa
```

**Comment by destroycomputers** [comment]
This really makes it difficult to use applications that rely on PgUp/PgDown to do something useful (like weechat for example).

**Comment by semparichyoung** [comment]
I have this issue too, this is really annoying.

**Comment by rbaezam** [comment]
I just started today using the Warp terminal and it's a fantastic software, but this issue is really causing me to not use it until this is fixed, hard to work on NeoVim this way. Hopefully it's something that get's fixed soon, but not very optimistic seeing it's been open for almost a month now.

**Comment by dimfeld** [comment]
For the record, same happens with PageUp and PageDown on an external keyboard.  

Here's what I see when I run the Linux `showkey` command and press `<PageDown><Spacebar><PageUp>`.

iterm2:
```
^[[6~ ^[[5~
```

Warp:
```
^[[^[[6~ ^[[^[[5
```

It looks like Warp might be sending an extra `ESC[` sequence?

**Comment by phrawzty** [comment]
@elviskahoro Thanks for the fix! 👍  I can go back to using Warp now. 😃
