### ISSUE TITLE
Git completion doesn't work with aliases

### ISSUE THREAD

**Issue by neelmehta247** [warpdotdev/Warp#562]
### Describe the bug

I have various git aliases set up. One of them is `git ch` => `git checkout`. 

Using another terminal, when I run `git ch ma<tab>` it would prompt me branches/tags that match. Warp has this functionality when I type `git checkout ma<tab>` but this doesn't work with the alias.

### To Reproduce

Steps to reproduce:
1. Set a alias
```
git config --global alias.ch checkout
```
2. Try tab completion while using the alias `git checkout <tab>` vs `git ch <tab>`

### Expected behaviour

Expect the behavior to be the same as if the alias was expanded before pressing the tab.

### Screenshots

<img width="197" alt="Screen Shot 2022-01-05 at 11 02 38 AM" src="https://user-images.githubusercontent.com/10547866/148249062-40891ad3-8bdc-4bc0-ad18-7af2f85bb660.png">

### Operating System

MacOS

### OS Version

11.6.1

**Comment by elviskahoro** [comment]
Should be fixed reopen if not!

**Comment by timbarlotta** [comment]
+1

I have similar aliases setup (co = checkout, cob = checkout -b) and neither benefit from branch suggestion. I do love how the completion shows the aliases and what they are aliases for though.

**Comment by YuraLaguta** [comment]
+1 
It's a blocker for me personally to adopt Warp. Otherwise, the product seems fantastic

**Comment by bernardobelchior** [comment]
+1 
Happening to me as well, would be nice to have this. I can live with Warp without it for the meantime, though 😄

**Comment by veloxy** [comment]
I'd also like to see this feature, was wondering why it wasn't auto-completing my branches sometimes. Turned out it was only with aliases

**Comment by mt-dfrey** [comment]
+1
this is preventing me from switching to warp ATM :/

**Comment by elviskahoro** [comment]
this is one of my personal top requests as well. Hopefully it launches in next two quarters!

**Comment by wesleylether** [comment]
+1

**Comment by ThanksSirAlex** [comment]
+1

**Comment by szgupta** [comment]
Hey folks! thanks for your patience on this. @kevinyang372 built this and it was shipped as part of `v0.2022.09.20.08.08.stable_01`! 🎉
