### ISSUE TITLE
AI responses in the user's native language

### ISSUE THREAD

**Issue by Alex063** [warpdotdev/Warp#5622]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

The AI assistant's answers are in the user's native language.
It would be good if, when working with Warp, the AI assistant would ask questions and answer in the user's native language.

For example, I have attached screenshots.
<img width="1287" alt="Снимок экрана 2024-12-26 в 21 51 54" src="https://github.com/user-attachments/assets/6cd1d417-2a17-430b-a091-04579960e9b0" />
<img width="1278" alt="Снимок экрана 2024-12-26 в 21 52 35" src="https://github.com/user-attachments/assets/d2578db4-d9ba-4ab2-863c-3b704d4393f7" />

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment]
Hi @Alex063, Thanks for submitting this. It's not an official feature of Warp to have a set language globally at this time, but a part of working with certain LLMs that they will automatically respond in the language in which you asked the question. We'd have to add such an option to set the default language for prompt suggestions, but as a workaround, you can ask questions explicitly in other languages. Please see the attached examples of the same question asked in multiple languages and the appropriate response:

![CleanShot 2024-12-26 at 16 32 38@2x](https://github.com/user-attachments/assets/5d58e50e-0103-4809-9f44-fb743b8ccc9c)

That being said, we are tracking a request for localization in the following github feature request. https://github.com/warpdotdev/Warp/issues/1194
If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.
