### ISSUE TITLE
Add a new "Quick Terminal" similar to Ghostty 👻

### ISSUE THREAD

**Issue by adamdehaven** [warpdotdev/Warp#5637]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

The new [Ghostty Terminal](https://ghostty.org/) has a "Quick Terminal" that launches a persistent terminal:

> The quick terminal is a terminal that appears on demand from a keybinding, often sliding in from a screen edge such as the top. This is useful for quick access to a terminal without having to open a new window or tab.
> 
> When the quick terminal loses focus, it disappears. The terminal state is preserved between appearances, so you can always press the keybinding to bring it back up.

I've been playing around with Ghostty and it's probably one of my favorite features

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by adamdehaven** [comment]
I did a deeper search and found https://github.com/warpdotdev/Warp/issues/91

**Comment by dannyneira** [comment]
Thanks @adamdehaven, for submitting. You're correct you can set up a Global Hotkey to either show dedicated windows (aka quake mode or quick terminal) or show/hide all windows. Learn more about it here: https://docs.warp.dev/features/windows/global-hotkey
