### ISSUE TITLE
su utility ignores Warp UI

### ISSUE THREAD

**Issue by walkersutton** [warpdotdev/Warp#565]
### Describe the bug

```shell
I wouldn't necessarily characterize this as a bug, but rather unexpected behavior.
```

### To Reproduce

Steps to reproduce:
1. Launch a Warp session
2. use `su` to change users
3. Observe that Warp styling is not active and Warp-specific functions aren't enabled

### Expected behaviour

```shell
I expected the UI to look more or less the same when changing the active user. 

I expected the prompt to look slightly different since changing users should reference a different shell configuration file.
```

### Screenshots

<img width="671" alt="Screen Shot 2022-01-06 at 18 13 38" src="https://user-images.githubusercontent.com/25811783/148465561-3eb729a1-d9b8-4b12-95b5-5e8c0f9bbc22.png">

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment]
Hey @walkersutton 

It's cause we don't support subshells yet! See this issue:
- https://github.com/warpdotdev/Warp/issues/64
