### ISSUE TITLE
Tab API

### ISSUE THREAD

**Issue by ianwalter** [warpdotdev/Warp#566]
### Describe the solution you'd like?

I just used iTerm2's Python API to create a python script in my monorepo that creates a bunch of tabs to run different services (e.g. docker compose, API server, Next.js dev server, iOS simulator, etc). It's great because I can easily start my whole dev environment with one command and have a meaningful tab name set for each tab. I would have preferred to use Node.js instead of Python, but not a big deal. Really liking Warp so far but this is what I am still using iTerm2 for.

### Additional context

Here's an example of a tab I create in the script: 

```python
        # Create a new tab and run the Docker Compose services.
        tab = await window.async_create_tab()
        await tab.async_set_title('Docker')
        command = f'cd {root}/packages/web; yarn docker\n'
        await tab.current_session.async_send_text(command)
```

**Comment by elviskahoro** [comment]
@ianwalter merging this into #345
