### ISSUE TITLE
Docs Dark Mode

### ISSUE THREAD

**Issue by fishcharlie** [warpdotdev/Warp#567]
### Describe the solution you'd like?

```shell
https://docs.warp.dev should support dark mode. https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
```

**Comment by elviskahoro** [comment]
+1 on this

**Comment by dannyneira** [comment]
Thanks for this request. So our GitBook does support Dark Mode, but it's either Light or Dark for everyone, so for readability purposes, I think we're going to stick with Light.

As a workaround, I recommend you try the [Dark Reader extension](https://darkreader.org/). It can turn any site into dark/light mode and even syncs with your OS settings.

**Comment by dannyneira** [comment]
Closing as note planned since there is a workaround ( Dark Reader extension ) and we will be keeping light mode for readability.

**Comment by dannyneira** [comment]
Hi @fishcharlie I've enabled the option for changing from light/dark mode at the bottom. By default the site will use the System's sync mode (Light/Dark).
