### ISSUE TITLE
Share UI is unusable when window is too small

### ISSUE THREAD

**Issue by joe-trellick** [warpdotdev/Warp#570]
### Describe the bug

When I set the Warp window to be 1/4 of my MacBook Pro screen, and I try to share a block with long enough output, the Create Link button is cut off so I can't use it

### To Reproduce

Steps to reproduce:
1. Make a Warp window that's relatively small vertically (1/2 the height of MBP built-in screen)
2. Do something like `ls -la` that produces more than a screenful of output
3. Attempt to share that block
4. Note that it's not possible to share the block because the button to generate the link is offscreen

### Expected behaviour

```shell
Block preview is given less height so that the necessary buttons are visible
```

### Screenshots

<img width="868" alt="Screen Shot 2022-01-07 at 10 53 18 AM" src="https://user-images.githubusercontent.com/159327/148533671-7039ef53-3177-45aa-ae0c-9b69a4ea723a.png">

### Operating System

MacOS

### OS Version

12.0.1

**Comment by elviskahoro** [comment]
Thanks for reporting this @joe-trellick

**Comment by elviskahoro** [comment]
This should be fixed. It should be more responsive now!
