### ISSUE TITLE
DUP: Duplicate of #500 - Customziable keyboard shortcuts

### ISSUE THREAD

**Issue by Sironheart** [warpdotdev/warp#571]
### Describe the solution you'd like?

```shell
Keyboard Shortcuts should be customizable. 

For example, I come from iTerm as my main terminal. To open up a split pane I'm used to pressing Cmd+D. I would love to be able to change the shortcuts to the ones I'm used to
```

**Comment by elviskahoro** [comment]
Hey @Sironheart
This is a work in progress. We're currently tracking this here:
- https://github.com/warpdotdev/warp/discussions/500

We have also added the keybinding label to keybinding related issues. So you can filter that way!
