### ISSUE TITLE
Split Panes can't be switched before typing anything.

### ISSUE THREAD

**Issue by Sironheart** [warpdotdev/Warp#572]
### Describe the bug

```shell
Currenctly it is not possible to open a split pane and directly switch back to the old pane. I do this quite often, if I know I'll need to have a new split pane in the near future.
```

### To Reproduce

Steps to reproduce:
1. Open new split pane (Cmd+E)
2. Try to switch to old pane (Cmd+Opt+Left) 
3. You stay in the new pane
4. start typing anything
5. Try to switch to old pane (Cmd+Opt+Left)
6. You are in the old pane

### Expected behaviour

```shell
The panes should always switch, even when a new one was just created
```

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
@Sironheart I can't reproduce this. Is this still happening to you?
Reopen if it is!
