### ISSUE TITLE
Tabs cannot be rearranged / reordered (reorder \ rearrange)

### ISSUE THREAD

**Issue by simjnd** [warpdotdev/Warp#58]
**Describe the bug**
When opening several tabs in Warp, the order of tabs cannot be changed

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a Warp window
2. Open several tabs
3. Try to rearrange the tabs

**Expected behaviour**
Dragging and dropping tabs should allow you to change their order. Additionally a command / keyboard shortcut should probably allow you to move tabs around too.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS Version: macOS 11.4

**Additional context**
N/A

**Comment by charlespierce** [comment]
Hi @simjnd, thanks for reporting! We have this in our queue already, just bumped it up internally!

**Comment by elviskahoro** [comment]
Linking:
- #466

**Comment by elviskahoro** [comment]
Linking:
- #398

**Comment by elviskahoro** [comment]
A bug related to this that @Vincent Chan found on Discord:
https://discordapp.com/channels/851854972600451112/852249738002956311/946331474561490954

> Hey guys, it seems that I can NOT drag the window in this area. I consider it's a bug.

![image](https://user-images.githubusercontent.com/29553206/156312337-c717b520-1621-4e1a-ac0b-2d1b84bca136.png)

**Comment by jasonobroin** [comment]
any time line for this feature? Thanks!

**Comment by evanmays** [comment]
+1

**Comment by KieranP** [comment]
+1 Need this functionality, along with being able to split tabs off into new windows, and to change tabs to be split panes

**Comment by elviskahoro** [comment]
Still a work in progress folks. But it's being worked on!

**Comment by SaadBazaz** [comment]
Need this. Isn't possible with a mouse drag, in the latest update.

**Comment by dannyneira** [comment]
Yup! still work in progress, but we've added new docs on Tabs usage with useful kb shortcuts. Hope that helps speed up your workflows for now. https://docs.warp.dev/features/tabs

**Comment by TiiFuchs** [comment]
Even more bonus points if you could drag a tab into a existing tab/window to create split views and vice versa.

**Comment by dannyneira** [comment]
Hi All! This feature is in the *very early* work-in-progress stages, but coming along. 

Given that the GUI framework was built in-house, this kind of functionality had to be built from scratch, hence the delay. 

We appreciate your patience! Here is a very early ( not the final product ) sneak preview 🤫 

![CleanShot 2022-11-22 at 10 18 08](https://user-images.githubusercontent.com/16809145/203379873-4a0cd753-76e0-46df-93a4-6fdb9bd7e853.gif)

**Comment by dannyneira** [comment]
@simjnd Thanks for the request. As of today's release, Tabs can now be dragged and reordered with your mouse in Warp!
