### ISSUE TITLE
Warp doesn't follow system proxy

### ISSUE THREAD

**Issue by TENX-S** [warpdotdev/Warp#581]
1. open the app, submit 1RRUST
2. sign up with GitHub
3. take me to warp
4. warp is freezing

macOS 12.1

https://user-images.githubusercontent.com/40336192/148638855-09e23b44-45eb-454a-bf4c-5b2e962b6a6b.mov

<img width="1440" alt="Screen Shot 2022-01-08 at 5 21 09 PM" src="https://user-images.githubusercontent.com/40336192/148638983-b447ad32-8c33-4732-8a2b-ff077bbcbf08.png">

**Comment by TENX-S** [comment]
Problem solved. 
It seems like warp doesn't follow the system proxy(I'm using proxy software because I'm in China), so I manually set the http_proxy env variable and launch it from that session.

**Comment by Nauxscript** [comment]
> Problem solved. It seems like warp doesn't follow the system proxy(I need to use network proxy software because I'm in China), so I manually set the http_proxy env variable and launch it from that session.

请问一下应该怎么设置呢？我也是遇到了这个问题，我的是 mac 环境
