### ISSUE TITLE
Moved to #641: psql: can not move the caret with cmd key

### ISSUE THREAD

**Issue by oguzhantopcu** [warpdotdev/Warp#586]
### Describe the bug

```shell
i can not move my caret with [command] key on "psql", "git add -i" CLI's.

*psql is postgresql's official cli.

it makes psql pretty unusable.
```

### To Reproduce

Steps to reproduce:

1.) run psql.
2.) type "something"
3.) press [command]+[left]

caret won't move to the left side of the word, instead it types [space].

### Expected behaviour

```shell
caret should move to the left side of the word
```

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment]
Moving this to here:
- #641
