### ISSUE TITLE
Glyphs, Nerd Fonts, and Config Files

### ISSUE THREAD

**Issue by mandaputtra** [warpdotdev/Warp#587]
### Describe the solution you'd like?

```shell
- Show symbols/glyph on terminal
- Provide config files
```

### Is your feature request related to a problem? Please describe.

```shell
- Glyph are not found on terminal
- I want a bigger font on my terminal, instead of zooming everytime it would be more practicals if there are config files
- Some terminal gui apps (vim, etc) looks like having a padding
```

### Additional context

Padding when using neovim

![Screen Shot 2022-01-10 at 10 09 26](https://user-images.githubusercontent.com/23342943/148714571-4f2c9260-61e1-4049-8f20-908901343c03.png)

**Comment by elviskahoro** [comment]
Moving to;
- #026

**Comment by elviskahoro** [comment]
We're splitting the image protocol and glyphs so gonna reopen this and use it as the glpyh issue!

**Comment by elviskahoro** [comment]
### Describe the solution you'd like?
```
Support for rendering non-text based mime-types, e.g. svgs, pngs
```

### Is your feature request related to a problem? Please describe.

```
Graphics
```

### Additional context

```
Sourced from Discord: (general channel: 07/28/2021)
"given that the UI framework can render arbitrary object, and like jupyter you have both a) a client server architecture and b) the notion of "cells", do you think you'll ever implement rendering of non-text based mime-types, e.g. svgs, pngs, ... for interactive plots like plotly?"
```
https://discord.com/channels/851854972600451112/870145535993077780/885405266370256907

**Comment by lessless** [comment]
This is much awaited!

**Comment by LucasEThomas** [comment]
Not sure if it's related but this is what Cascadia Cove nerd font looks like for me.
<img width="616" alt="image" src="https://user-images.githubusercontent.com/8398198/214434154-4c6bcaa4-0f62-4bec-aced-47aea97329c6.png">
Notice the erroneous vertical offsets on some of the symbols

**Comment by nikbrunner** [comment]
> Not sure if it's related but this is what Cascadia Cove nerd font on starship looks like for me. Notice the erroneous vertical offsets on some of the powerline symbols <img alt="image" width="616" src="https://user-images.githubusercontent.com/8398198/214434154-4c6bcaa4-0f62-4bec-aced-47aea97329c6.png">

I love this app, but I have the same problem with Glyph Renderings in Neovim. I know its just cosmetics, but its always a little annoying.

![image](https://user-images.githubusercontent.com/46924729/236609979-5ed6d505-9a9c-41dc-9c63-4275349b9e3e.png)

![Screenshot 2023-05-06 at 09 28 39](https://user-images.githubusercontent.com/46924729/236609886-3ae412c7-2c38-49da-a7bd-6589d32c8105.png)
![Screenshot 2023-05-06 at 09 28 48](https://user-images.githubusercontent.com/46924729/236609887-11f825b1-5a03-4ebd-86d4-8cfe42d798b1.png)

In kitty it looks best in my opinion:

![image](https://user-images.githubusercontent.com/46924729/236609959-0f8978d7-5184-4012-b103-629170638133.png)

**Comment by daUnknownCoder** [comment]
any updates?
