### ISSUE TITLE
Sessions: Save panel orientation

### ISSUE THREAD

**Issue by mmahalwy** [warpdotdev/Warp#588]
### Describe the solution you'd like?

I have a certain panel orientation I use for frontend and backend. Ideally, I'd like to save this orientation and be able to default it on start up

See image:
![image](https://user-images.githubusercontent.com/3749095/148846401-6339a9d4-e3fc-4852-b07b-ecbf26cd23c4.png)

**Comment by elviskahoro** [comment]
Thanks for opening this. It's actually a work in progress!

**Comment by elviskahoro** [comment]
@mmahalwy This launched! It's called Launch Configurations: `CTRL-CMD-L`
https://docs.warp.dev/features/session-management/launch-configurations
