### ISSUE TITLE
zsh: Problem with bindkey "^Z"

### ISSUE THREAD

**Issue by hardselius** [warpdotdev/Warp#589]
### Describe the bug

I have the following snippet in my `.zshrc`

```shell
resume() {
  fg
  zle push-input
  BUFFER=""
  zle accept-line
}
zle -N resume
bindkey "^Z" resume
```

It serves as a "toggle" for programs running in the terminal, e.g vim.

### To Reproduce

Steps to reproduce:
1. Add the snippet to .zshrc
2. Open vim
3. Press ^Z to move vim to the background
4. Press ^Z again and nothing happens.

### Expected behaviour

In this case, I expect `^Z` to bring my process back to the foreground, instead I have to manually run `fg`.

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment]
See #537!
