### ISSUE TITLE
Set a color for tabs

### ISSUE THREAD

**Issue by JoeriTheGreat** [warpdotdev/Warp#590]
### Describe the solution you'd like?

```shell
Setting a color for different opened tabs like online = red, local = green,..
```

**Comment by o1lo01ol1o** [comment]
I'd also like something simple that allows me to quickly group tabs.  Maybe you could apply themes at the tab level?

**Comment by elviskahoro** [comment]
Gonna close this and merge it into:
- #478

**Comment by elviskahoro** [comment]
This was launched by the way! Kudos to @gagata
