### ISSUE TITLE
Support text wrapping in the input editor

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#592]
### Describe the solution you'd like?

```shell
Wrap in the input editor
```

**Comment by satvik-s** [comment]
Would like this too

Ran into a scenario with a big `curl` command that was not easy to parse w/o wrap

**Comment by pocketpixels** [comment]
So far this is my biggest annoyance and potential reason to switch back to a different terminal app.
Editing long docker commands (for example) on a single scrolling line feels unnecessarily painful.

**Comment by ivribalko** [comment]
this would also enhance command preview support because currently is shows only starting (first line) characters too so i can't see all the changes i made across multiple attempts at a long command easily

**Comment by elviskahoro** [comment]
This was launched today!
