### ISSUE TITLE
Moved to #579: CTRL-G to exit command history search

### ISSUE THREAD

**Issue by d-lord** [warpdotdev/Warp#594]
### Describe the solution you'd like?

I'd love to copy the Emacs convention and allow Ctrl+G to cancel the Ctrl+R history search. You already support Esc and Ctrl+C, of course.

### Is your feature request related to a problem? Please describe.

Just muscle memory for people used to emacs/fzf/many other implementers of readline keybindings.

### Additional context

[fzf already binds this by default](https://github.com/junegunn/fzf/blob/master/README.md?plain=1#L208).

[A notable readline cheatsheet](https://readline.kablamo.org/emacs.html) mentions it too.

This might end up under #579.

PS - just started trying out Warp today. So far, incredible! Thanks!

**Comment by elviskahoro** [comment]
Moving to #579 so all keybinding related issues are in one place:
- #579
