### ISSUE TITLE
CTRL+L breaks follow-up command

### ISSUE THREAD

**Issue by atilafassina** [warpdotdev/Warp#597]
### Describe the bug

```shell
CTRL+L command breaking follow-up output
```

### To Reproduce

Steps to reproduce:
1. Type command(s)
2. clear output with CTRL+L
3. Enter new command

Output is something like

```
zsh: command not found: ^Lcd
```

### Expected behaviour

```shell
CTRL+L command is cleared/ignored from input before follow-up command
```

### Operating System

MacOS

### OS Version

12.1

### Additional context

```shell
Experience is still great!!!
Congrats on the awesome work
```

**Comment by elviskahoro** [comment]
@atilafassina Can you share a video? I'm not able to reproduce this.

**Comment by atilafassina** [comment]
@elviskahoro since I updated this morning I haven't been able to reproduce the whole day.

---

congrats on the awesome work 🎉  😅

**Comment by elviskahoro** [comment]
@atilafassina that's great! thanks for opening issues it always helps
