### ISSUE TITLE
resourcing zshrc throws a > in the terminal and makes commands fail

### ISSUE THREAD

**Issue by gigatexal** [warpdotdev/Warp#598]
### Describe the bug

```shell
So just running Warp presents a totally usable terminal.

but if I change something in zshrc and source it via source ~/.zshrc

the prompt now has a > and that gets added to commands and causes issues

The fix is to close warp and relaunch
```

### To Reproduce

Steps to reproduce:
1. install zsh
2. install oh-my-zsh
3. select the robbyrussel theme
4. run commands no problem
5. refresh the shell `source ~/.zshrc`
6. see an extraneous > in the shell
7. unable to run commands

### Expected behaviour

```shell
be able to use the shell like normal even after resourcing zsh's config
```

### Screenshots

https://ibb.co/y57rbr9
https://ibb.co/sqbVy2x
https://ibb.co/2qCk7Q4
https://ibb.co/B3F9Dyw

### Operating System

MacOS

### OS Version

11.5.1

**Comment by guilleripa** [comment]
Sounds like I'm getting the same bug, a different use case.

If I activate a python env the prompt now has the environment name. Ex `(.venv)`.

You can still delete the name on each command enter for the time being.

**Comment by anon0mys** [comment]
Same. When using `workon` to activate a python env the prompt has the environment name `(venv)`.

**Comment by elviskahoro** [comment]
@anon0mys @daviddenton We're not compatible with the theme yet.
See this discussion: <https://github.com/warpdotdev/Warp/discussions/422>

For know try this from our docs: <https://docs.warp.dev/help/known-issues>
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

    # POWERLEVEL10K
    # OH-MY-ZSH-THEMES
    # OH-MY-ZSH-PLUGINS
    # FIG
    # BIND keys like:
    # bindkey "^j" down-line-or-beginning-search
    # [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && 
    # . "/usr/local/etc/profile.d/bash_completion.sh"
    # eval "$(rbenv init -)"

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

**Comment by elviskahoro** [comment]
@guilleripa Check out this issue, we're looking into it!
<https://github.com/warpdotdev/Warp/issues/599>

**Comment by gagata** [comment]
hello! we just pushed a release that fixes this issue, please check it out (and feel free to reopen the ticket if it's still happening)

**Comment by gigatexal** [comment]
confirmed it's fixed!!!
