### ISSUE TITLE
(venv) auto populates into text after using python3 -m venv venv 

### ISSUE THREAD

**Issue by jalexanderII** [warpdotdev/Warp#599]
### Describe the bug

```shell
I created a virtual env in a directory. The venv was created perfectly, however, in the terminal now when I go to type (venv) is auto-populated at the beginning of my editor. So without realizing it, if I try something like pip install flask, the terminal actually runs 
"(venv)pip install flask"
```

### To Reproduce

Steps to reproduce:
1. Open new terminal.  
2. mkdir example (press enter)
3. cd example (press enter)
4. python3 -m venv venv (press enter)
5. source venv/bin/activate (press enter)
2. now you will see (venv) auto inserted into your text field 
3. pip install flask (press enter)
4. get parse error near `pip'

To avoid, need to manually press backspace to remove (venv) before typing every time you have a new line

### Expected behaviour

```shell
After activating venv you see "(venv)" prepended to your directory name, but not to your text section
```

### Screenshots

![Screen Shot 2022-01-13 at 11 04 37 AM](https://user-images.githubusercontent.com/93228880/149365420-743001d7-afa1-4f14-a2da-b22dad6932c3.png)

### Operating System

MacOS

### OS Version

12.0.1

### Additional context

```shell
macOS Monterey Intel Chip
```

**Comment by japsu** [comment]
Please note that this is a breaking defect that prevents Python programmers from using Warp and prioritize this accordingly.

**Comment by gagata** [comment]
hello! we just pushed a release that fixes this issue, please check it out (and feel free to reopen the ticket if it's still happening)

**Comment by jalexanderII** [comment]
Seems to be working, thanks for the quick turnaround!
