### ISSUE TITLE
Make keyboard shortcut for split pane consistent with other terminals (Terminal.app, iTerm2, and hyper.sh)

### ISSUE THREAD

**Issue by beorn** [warpdotdev/Warp#600]
Currently Warp uses cmd-e and cmd-shift-e for splitting panes, whereas the convention amongst terminals is to use cmd-d and cmd-shift-d.

It would be great if Warp was consistent with them.

Related to #542 which is asking to NOT use cmd-e for this.

**Comment by beorn** [comment]
Including thread from https://discord.com/channels/851854972600451112/852249738002956311/931455648749740033

Elvis:

> We're adding the ability to set custom keybindings, you'll be able to change it back. But the rationale for changing this is, we have VS Code keybindings for the input editor (fully fledged native text editor). And the input editor's keymaps take precedence in our view hierarchy i.e. `CMD-D` is for multi-cursor which doesn't apply in iTerm's case because the input does not support this kind of functionality.
>
> It's worth changing your muscle memory in the long run for this. Here's a GIF from the docs. https://docs.warp.dev/features/input-text-editor

Bjorn:

> On `cmd-d`: I understand, however I think you can make the case that for a terminal to be consistent with other terminals is probably more important than being consistent with a text editor.  The case for multi-cursor is still somewhat unproven in a terminal (since you're 99% of the case just editing a single line), and there's always history substitution commands such as r old=new.  Finally, split pane in vscode isn't `cmd-e` but `cmd-\` right?
> 
> On `ctrl-n/p/f/b`: I guess these are still supported by even vscode out-of-the-box (and in every text field on macOS) and so would make sense to include as defaults?

**Comment by elviskahoro** [comment]
@beorn let's move this to here:
- https://github.com/warpdotdev/Warp/discussions/500
