### ISSUE TITLE
Command history empty after latest update

### ISSUE THREAD

**Issue by patrickdward** [warpdotdev/Warp#602]
### Describe the bug

```shell
Blank history when hitting the up-arrow key
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```shell
Command history persisted with previous updates
```

### Operating System

MacOS

### OS Version

11.6.2

**Comment by elviskahoro** [comment]
Hey @patrickdward

I think I found a fix for this. Delete: `rm -rf ~/Library/Application Support/warp`
As well as delete: `rm -rf ~/Library/Application Support/dev.warp.Warp-Stable`

**Comment by elviskahoro** [comment]
Closing for now. Let us know if it comes back.
