### ISSUE TITLE
Support any monospace font installed by the user

### ISSUE THREAD

**Issue by fbartho** [warpdotdev/Warp#603]
### Describe the solution you'd like?

If the user has a font installed in the System Font location (eg. on macOS this is the Font Book), this font should be available in the Warp font picker.

### Is your feature request related to a problem? Please describe.

Specifically: I have a Monospace font [Monoid HalfTight](https://github.com/larsenwork/monoid), and it is installed in my User's Font Book.

This font is not selectable in the Font picker in Warp. It would be lovely if available fonts could be selected! If this font somehow doesn't register as monospace, I'd expect there to be a way to force Warp to use this font (even if I had to click through a disclaimer).

### Additional context

![Screenshot of Font Book showing Monoid HalfTight & Variants](https://user-images.githubusercontent.com/209712/149427352-f43a4560-464b-4f8c-ad2a-38fb78ca2617.png)

Related: #239

**Comment by elviskahoro** [comment]
The font is monospace, but like you mentioned it isn't registered as monospace. We do have any open issue to allow any font to be selectable. So closing this in favor of that one:
- https://github.com/warpdotdev/Warp/issues/270
