### ISSUE TITLE
Discord links seems invalid or expired

### ISSUE THREAD

**Issue by wzzrd** [warpdotdev/Warp#604]
### Describe the bug

```shell
Clicking the 'Join our Discord' link brings me to screen that says 'Invite invalid' and then 'This invite may be expired, or you might not have permission to join'.
```

### To Reproduce

Steps to reproduce:
1. Go to menu
2. Click on Join our Discord
3. See error as described above

### Expected behaviour

```shell
Join the appropriate Discord room
```

### Screenshots

![Screenshot 2022-01-14 at 15 18 58](https://user-images.githubusercontent.com/69339/149530550-7a406f32-dc4d-4415-9cdf-8b1501252c36.png)

**Comment by elviskahoro** [comment]
We've fixed this should be coming out this wednesday.
