### ISSUE TITLE
Htop closing after moving the window

### ISSUE THREAD

**Issue by localcc** [warpdotdev/Warp#607]
### Describe the bug

After opening htop and moving warp terminal window htop closes.
If you open htop on your local machine it will just close, but on ssh it also does something like this: 
```shell
htop
^[[<32;132;1M
```

### Steps To Reproduce
1. Open htop
2. Move terminal window
3. Htop closes

### Expected behaviour
Htop should continue running

### Screenshots

![htop_ssh](https://user-images.githubusercontent.com/42898191/149676220-dae0f56e-bc8e-4dfc-a582-a22b878d8336.png)
![htop_local](https://user-images.githubusercontent.com/42898191/149676511-ad000240-5522-4413-baea-c2c49c9dbb9a.png)

### Operating System

MacOS

### OS Version

12.1 (21C52)

**Comment by elviskahoro** [comment]
Thanks for reporting this. I was able to reproduce!

**Comment by elviskahoro** [comment]
This should be fixed!
