### ISSUE TITLE
Ctrl + U/K doesn't cut to clipboard

### ISSUE THREAD

**Issue by mattprecious** [warpdotdev/warp#61]
**Describe the bug**
`Ctrl + U` clears the text, but does not put it in the clipboard, so a subsequent `Ctrl + Y` pastes something different.

**To Reproduce**
Type a bunch of text, press `Ctrl + U`, press `Ctrl + Y`

**Expected behavior**
Cut text is pasted back into terminal.

**Desktop (please complete the following information):**
 - OS Version: [e.g. MacOS 11.5]

**Comment by charlespierce** [comment]
Thanks for reporting @mattprecious, we'll take a look at this!

**Comment by chriskrycho** [comment]
Same thing is happening for <kbd>Ctrl</kbd><kbd>K</kbd>. It appears you're implementing “yank” as “paste from clipboard,” which is close to, but not quite, correct. On macOS, at least, the clipboard is a different buffer than the “kill ring,” which is where commands like <kbd>Ctrl</kbd><kbd>U</kbd>, <kbd>Ctrl</kbd><kbd>K</kbd>, <kbd>Ctrl</kbd><kbd>D</kbd> (kill single character), <kbd>⌥</kbd><kbd>D</kbd> (kill word), etc. all end up.

**Comment by michlimlim** [comment]
We just released the fix for this today in `v0.2021.08.11.15.36.stable_00`
