### ISSUE TITLE
DUP: Duplicate of #026 - Unexpected characters composition

### ISSUE THREAD

**Issue by BastienM** [warpdotdev/Warp#615]
### Describe the bug

```shell
When trying to write `find`, the term ends up drawing a phone icon. But is interpreted correctly.

Tested with `kitty 0.24.1` using the same font `Incosolata Nerd Mono` and I got the correct behavior.
```

### To Reproduce

Steps to reproduce:
1. Open a fresh term
2. Write `f` then `i`

### Expected behaviour

```shell
`f + i` should draw `fi`
```

### Screenshots

![term](https://imgur.com/U2JlYOC.png)

### Operating System

MacOS

### OS Version

12.1

### Additional context

```shell
Build `v0.2022.01.10.17.24.stable_02`
```

**Comment by elviskahoro** [comment]
Does this happen with other fonts?
Do you have anything in your dotfiles that deals with emojis / emoticons? It's likely something in your dotfiles

**Comment by BastienM** [comment]
Does not reproduce with the standard font, so something related to Nerf patched fonts it seems.
I haven't got anything specific to emoji/emoticons support in my dotfiles neither.

**Comment by elviskahoro** [comment]
@BastienM I think this is actually this then:
- https://github.com/warpdotdev/Warp/issues/26

Let's move this to over there!
