### ISSUE TITLE
Gradle plugin (command autocomplete) is not working 

### ISSUE THREAD

**Issue by gabriel-munteanu** [warpdotdev/Warp#616]
### Describe the bug

```shell
I am expecting to see the suggestions offered by the gradle plugin(ohmyzsh) but when I press TAB I get the file suggestions from the terminal.
```

### To Reproduce

Steps to reproduce:
1. Install ohmyzsh
2. Install gradle plugin https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/gradle/gradle.plugin.zsh
3. cd to a project that uses gradle
4. Type ./gradlew or ./gradle
5. Press TAB

### Expected behaviour

```shell
zsh: do you wish to see all 2833 possibilities (2833 lines)?
```

### Screenshots

iTerm2(working example)
<img width="551" alt="Screenshot 2022-01-17 at 16 37 08" src="https://user-images.githubusercontent.com/7124800/149790456-3ab5c729-ccd4-4d31-9b08-ab9388dba567.png">

Warp 
<img width="653" alt="Screenshot 2022-01-17 at 16 43 24" src="https://user-images.githubusercontent.com/7124800/149790348-6c8df64b-3885-469f-b571-17380e8aae00.png">

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment]
@gabriel-munteanu Our completions signature don't pull from the shell their loaded natively. I just checked our completions signatures and we have gradle supported. You should get signatures without OMZ plugins and OMZ.

Best thing to do is to use this flag to isolate things for Warp specifically:
https://docs.warp.dev/help/known-issues
```sh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

    # POWERLEVEL10K
    # OH-MY-ZSH-THEMES
    # OH-MY-ZSH-PLUGINS
    # FIG
    # BIND keys like:
    # bindkey "^j" down-line-or-beginning-search
    # [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && 
    # . "/usr/local/etc/profile.d/bash_completion.sh"
    # eval "$(rbenv init -)"

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi
```

**Comment by elviskahoro** [comment]
@gabriel-munteanu also check out this discussion:
- https://github.com/warpdotdev/Warp/discussions/434

**Comment by gabriel-munteanu** [comment]
I realized that in Warp, OMZ is not loaded(if I load it I will get gradle suggestions but no more native suggestions).
If you say that you support gradle, how can I make it work?(zsh is vanila)

**Comment by elviskahoro** [comment]
@gabriel-munteanu It's bugged. Nothing on your end!
See this issue:
- https://github.com/warpdotdev/Warp/issues/414
