### ISSUE TITLE
Hitting Tab With 1 Item Selected Should Behave Identically to Enter

### ISSUE THREAD

**Issue by fishcharlie** [warpdotdev/Warp#619]
### Describe the solution you'd like?

```shell
See attached screenshot.

In that instance, with only 1 item in the list, hitting `Tab` should be identical to `Enter` and should select that item from the list.
```

### Additional context

<img width="364" alt="Screen Shot 2022-01-17 at 2 44 34 PM" src="https://user-images.githubusercontent.com/860375/149840155-86a82881-9380-4316-9da8-55d406e24280.png">

Possibly Related: #618

**Comment by elviskahoro** [comment]
Hey @fishcharlie moving this to #340
