### ISSUE TITLE
Resize Input Line Field

### ISSUE THREAD

**Issue by fxmb** [warpdotdev/Warp#621]
### Describe the solution you'd like?

```shell
Please make the CL input field resizable. Right now I can only see 3 lines at a time which is very annoying.
```

### Is your feature request related to a problem? Please describe.

```shell
Right now I can only see 1-3 lines of a command in the terminal space. This is very annoying when working with large (curl) requests from the CL.
```

### Additional context

![image](https://user-images.githubusercontent.com/39501592/150139760-6fbb2ef2-cb49-4ceb-b651-7c5a0c16d787.png)

See how there is just one line to write, I cant resize it to be bigger

**Comment by davit-b** [comment]
+1 for this. Really pain in the ass editor large `cURL` commands.

**Comment by elviskahoro** [comment]
2022.02.16 - The input height can now expand to half the pane height

**Comment by davit-b** [comment]
yesssss!!! thank you and enjoy the long weekend
