### ISSUE TITLE
Tab completion for unsupported commands should default to shell

### ISSUE THREAD

**Issue by neelmehta247** [warpdotdev/Warp#622]
### Describe the bug

For commands like `kubectl` that aren't natively supported by Warp, the tab completion should defer to the shell completion. 

When running in a normal terminal emulator running something like `kubectl <tab>` will give a list of supported operations and even stuff like `kubectl describe pod <tab>` will show a list of pods. 

With Warp this doesn't happen and instead, it just shows a list of files in the working directory. This is super annoying and makes it very hard to use. I find myself having to switch between 2 terminals because of this. 

I've also noticed this happen with other commands like `Skaffold`. I think it would be unreasonable to expect native support for every command, but having a way to fall back to Shell completion would be nice.

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Operating System

MacOS

**Comment by elviskahoro** [comment]
@neelmehta247 
Can you move this to here:
- https://github.com/warpdotdev/Warp/discussions/434
This is where we're discussing this! Closing for now
