### ISSUE TITLE
Swap / move / reorder / popout panes / support pane rearrangement

### ISSUE THREAD

**Issue by 0x000bff** [warpdotdev/Warp#623]
### Describe the solution you'd like?

```shell
Akin to tmux, I'd love the ability to shuffle panes around -- move bottom pane to top, rotate clockwise, etc.
```

### Additional context

I'm sure there are a lot of features to be pulled from tmux and other multiplexing tools, but I didn't see any explicit mention of this one so I thought I'd add!

**Comment by mdanlowski** [comment]
I'm surprised Pane re-arrangement isn't getting more attention/requests 😅 
for me lacking this it's sometimes quite a hurdle

Bumping! 👍 

(nice app btw 😃)

**Comment by elviskahoro** [comment]
From @xhyumiracle via #1063
### Discord username (optional)

_No response_

### Describe the solution you'd like?

```text
Currently we can 'select' different panes on the up/down/right/left, which is nice. 
But it would be nicer if we can also 'swap' the position of panels, just like 'swap with split pane on L/R..' feature in iTerm2. 
Specifically, the new function could exchange the position of 2 adjacent panes.

Additionally, customized keyboard shortcut support for the 'swap' functions is also a great feature to have, 
so that people with customized usage habits, like me, can join more smoothly. 
(for me I use cmd+shift+control+j/k/h/l for 'swap' and cmd+control+j/k/h/l for 'select')
```


### Is your feature request related to a problem? Please describe.

_No response_

### Additional context

e.g.:
![image](https://user-images.githubusercontent.com/17793687/163523808-f2c8f3ed-936d-4734-b90a-dac1de1af331.png)

**Comment by deepaktalwardt** [comment]
Yes this would be very helpful indeed! I like to move my panes around in iTerm2 all the time depending on what I need to focus on at the moment.

**Comment by 0x000bff** [comment]
> @0x000bff @mdanlowski are there arrangements that we're still missing?

Hey sorry I haven't been following this so closely, I've kinda just migrated back to iTerm+tmux for the time being.
If other users are happy, don't let me hold you up, go ahead and close when you see fit!

**Comment by vstoppe** [comment]
I am right now looking for this feature in Warp! I worked for over a decade on the terminal mostly using "Terminator" on Linux, which also has this feature and used it on the daily basis. Without the ability to rearrange the panes a terminal is a hassle. I admire the new concepts of Warp, but this feature is a k.o. criteria.
I hope seeing Warp one day on Windows and teaching my colleagues about it. Until then I will check it out on Macos from time to time.

**Comment by dannyneira** [comment]
FYI, We recently released mouse reordering for Tabs, but it would be great to have the same for Panes.

Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by jwthomp** [comment]
keyboard shortcuts to do this is useful, but I wanted to comment that drag and dropping panes with the mouse is more important to me. 

This includes tearing a pane out into it's own tab, or moving a pane from one window to another. iTerm is a great reference implementation of pane management done right (imo of course).

Thank you for a wonderful app, and for taking user feedback so seriously!

**Comment by WoodyWoodsta** [comment]
I'd love this feature = in iTerm2, moving the terminal between a tall screen and a wide screen often means I want to stack panes vertically or horizontally. At the moment once I have a tab arrangement, the only way to update that is to close and recreate panes, which is not possible without restarting everything that was running in those panes. It's... a pain :)

**Comment by EtherealRise** [comment]
once I have create a new pannel in current workspace, say horizontal for example, it seems impossible to actively change the layout to vertical. I'm not sure whether I'm doing something wrong or it's unsupported at this time. @dannyneira

**Comment by anselanza** [comment]
+1 This is the most important reason I keep getting tempted back to using iTerm2. I guess some people prefer tabs, but personally I use split panes almost 100% of the time (never tabs) and having no way to rearrange them after creation is seriously disappointing for an otherwise excellent application.

**Comment by vstoppe** [comment]
@anselanza There is no need to use tabs or panes exclusively. Maybe I explain a tab + pane driven workflow for future readers. Lets say you work with different repos and microservice configurations at the same time, because they are connected. Then I have a tab for every repo or microservice-group to separate my work. In this way I can find my way easily back to the thing I am working on. Lets say I work in different panes in one tab on different text files and terminals. Lets say one vim pane, one for navigating on a vm and two panes for a live log view.
The rearrangement comes handy if you have lets say 2x2 panes. Lets say you want to follow log files of a service. This is usually very helpful to do on the full width of the monitor. In this situation you have to rearrange (or create a new) pane at the bottom of the terminal for the full width.

**Comment by drakythe** [comment]
+1 for this feature. I love the ease of panes Warp compared to tmux (the command sequence just never seems to stick in my head) but its very limiting that if I spawn new panes to watch something or perform a secondary process I can't re-arrange them as my priority shifts, so now I have to plan the panes which defeats at least half their usefulness for me.

**Comment by prakashchokalingam** [comment]
+1 for this request, These would greatly improve user customization and productivity.

**Comment by mjyoung** [comment]
Another +1. Use this feature all the time dragging and dropping panes between windows in iTerm2.

**Comment by aviadhaham** [comment]
+1

**Comment by bsramin** [comment]
Please add 👍🏻 to the first post 
Thanks
![screenshot-20231115-12 56-9PXfg6dt](https://github.com/warpdotdev/Warp/assets/672932/cd17441a-37fb-4f9e-892e-1b1fcafab6ca)

**Comment by bsramin** [comment]
Added to the last release 2023.02.08 (v0.2024.02.06.08.02)

https://docs.warp.dev/getting-started/changelog

```You can now drag and drop panes! Click and drag a pane’s header around a given tab. Drag the pane to the tab bar to move it to another tab, or make it its own tab!```

**Comment by dannyneira** [comment]
Hey Folks! Warp now officially supports rearranging panes + more! in Warp version [v0.2024.02.06.08.02](https://docs.warp.dev/getting-started/changelog#id-2023.02.08-v0.2024.02.06.08.02).

https://github.com/warpdotdev/Warp/assets/16809145/b175dec0-6977-4821-9602-8dcf5e8cc827

Closing as completed, but please feel free to let us know of any issues with the feature.

**Comment by aviadhaham** [comment]
@dannyneira have you implemented new keyboard shortcuts for it as well?
thank you

**Comment by dannyneira** [comment]
@aviadhaham unfortunately, there are no shortcuts to move the panes around at this time, this is just for mouse movement. But you can move the dividers and also activate panes with shortcuts. Please see our docs for the complete list. https://docs.warp.dev/features/keyboard-shortcuts#terminal
