### ISSUE TITLE
Settings modal slightly resizes in the "Shared blocks" tab

### ISSUE THREAD

**Issue by HaydenBL** [warpdotdev/Warp#624]
### Describe the bug

```shell
Incredibly minor, but when you click into the "Shared blocks" tab in the settings, the modal becomes smaller width-wise by like 1 or 2 pixels. The other tabs all keep the modal the same width except for that one.
```

### To Reproduce

Steps to reproduce:
1. Open settings (Cmd + , )
2. Click "Shared blocks"
3. See modal resize

### Expected behaviour

```shell
Modal should stay the same width
```

### Operating System

MacOS

### OS Version

11.6.2

**Comment by jonathanrobichaud4** [comment]
Same issue here. It's very small but irks me just a little bit.

**Comment by brenr** [comment]
Noticed the same lol.

**Comment by elviskahoro** [comment]
This has been triaged but it's not high priority tbh. Will circle back when it's a WIP

**Comment by dannyneira** [comment]
hey folks, this issue has been resolved and the settings modal no longer resizes slightly on the Shared blocks page. Closing as resolved but please feel free to let us know if the issue persists.
