### ISSUE TITLE
Oh-my-zsh support - Warp is not picking up the oh-my-zsh theme

### ISSUE THREAD

**Issue by ricardogaspar2** [warpdotdev/Warp#626]
### Describe the bug

```shell
On a Mac, I'm using Zsh with oh-my-zsh.
I'm using the ZSH theme: `ZSH_THEME="fino-time"` but Warp is not picking that up, just relying on its own theme
```

### To Reproduce

Steps to reproduce:
1. On a Mac, with Zsh, install [oh-my-zsh ](https://ohmyz.sh/)
2. open Mac's default terminal app and check prompt
3. open Warp and check the prompt

### Expected behaviour

```shell
Warp should pick the theme defined by Oh-my-zsh.
```

#### iTerm
<img width="964" alt="Screenshot 2022-01-19 at 23 40 15" src="https://user-images.githubusercontent.com/3660448/150237082-d092fb88-ffdd-4d66-9be1-4e99629417a1.png">

#### Warp
<img width="1008" alt="Screenshot 2022-01-19 at 23 40 11" src="https://user-images.githubusercontent.com/3660448/150237118-f185d7c7-dc6e-4bef-b2b0-3c6f3ab5a0fe.png">

### Operating System

MacOS

### OS Version

11.6.1

### Additional context

```shell
Warp version `v0.2022.01.17.08.48.stable_01`
```

**Comment by elviskahoro** [comment]
@ricardogaspar2 

Can you move this to our custom prompt discussion:
- https://github.com/warpdotdev/Warp/discussions/422
