### ISSUE TITLE
DUP: Duplicate of #091 - Dropdown terminal

### ISSUE THREAD

**Issue by prep2** [warpdotdev/Warp#647]
### Describe the solution you'd like?

A dropdown editor similar to iTerm's Hotkey window or Quake in Gnome. User would be able to use a keyboard shortcut to pull down a terminal from the top of the screen on top of any application. Image attached is iTerm2.

### Additional context

<img width="1728" alt="Screen Shot 2022-01-20 at 7 48 17 AM" src="https://user-images.githubusercontent.com/8042703/150341933-0bac96a7-7526-44cd-ae00-a8e1ed9dbb82.png">

**Comment by elviskahoro** [comment]
@prep2 this is a duplicate see here:
- https://github.com/warpdotdev/Warp/issues/91
