### ISSUE TITLE
Chinese character display issue

### ISSUE THREAD

**Issue by NoirJ0e** [warpdotdev/Warp#648]
### Describe the bug

```shell
when I tried to type some chinese character in warp, sometimes it won't be show correctly, it just becomes transparent, in order to show it I have to type more character to delete one, I guess this might be something related to text caching?
```

### To Reproduce

Steps to reproduce:
1. open a file I want to edit 
2. type in Chinese
3. problem appear

### Expected behaviour

```shell
chinese character don't become transparent
```

### Screenshots

transparent:
![image](https://user-images.githubusercontent.com/60462008/150377734-699f2887-da62-428f-ac5c-5921e2f476b2.png)
normal:
![image](https://user-images.githubusercontent.com/60462008/150378419-cb2db320-a7e6-43b1-936f-9ae817f79738.png)

### Operating System

MacOS

### OS Version

10.15.7

**Comment by Cronos87** [comment]
On top of that, if you have directories written in Chinese and try to navigate inside with `cd`, the current tab will display a JSON and I can't do nothing (see the screenshot).
By the way, the autocomplete is not showing the Chinese characters on the left part (see screenshot too).

<img width="1630" alt="CleanShot 2022-04-07 at 09 20 45@2x" src="https://user-images.githubusercontent.com/1923206/162143408-19ffc104-97e0-482e-adf8-f7f59e3801c9.png">

<img width="1631" alt="CleanShot 2022-04-07 at 09 20 31@2x" src="https://user-images.githubusercontent.com/1923206/162143477-10020ec5-525f-43b9-9ba5-3235434e237f.png">

**Comment by Agenric** [comment]
Updete:
When cd into a folder that contains Chinese characters in the current branch name, the command window will never end.

**Comment by elviskahoro** [comment]
### Discord username (optional)

_No response_

### Describe the bug

```text
Chinese characters are not displayed correctly, for example in `cd directory`
```


### To Reproduce

Steps to reproduce:
1. Open 'warp'
2. Input  'cd '
3. Press  'Tab'
4. See error

### Expected behaviour

```text
Fix it
```


### Screenshots

![image](https://user-images.githubusercontent.com/21958044/162613138-cd94fa9f-7f48-44da-b82b-0b7ac46bba5c.png)


### Operating System

MacOS

### OS Version

12.3

### Additional context

_No response_

**Comment by ooopscc** [comment]
<img width="347" alt="图片" src="https://user-images.githubusercontent.com/1056803/163760775-ff0d271a-2740-4463-a00b-6db0e3e8ae53.png">

**Comment by elviskahoro** [comment]
This should be fixed
