### ISSUE TITLE
Oh-my-bash adds the custom prompt to the user input

### ISSUE THREAD

**Issue by ava-silver** [warpdotdev/Warp#649]
### Describe the bug

```shell
When I hit enter to run a new command, the oh-my-bash prompt is input, meaning I have to delete it every time before entering a command, effectively rendering warp unusable.
```

### To Reproduce

Steps to reproduce:
1. Install [oh-my-bash](https://github.com/ohmybash/oh-my-bash)
2. install warp
3. hit enter

### Expected behaviour

```shell
it to either display the prompt above (like is currently done with the current path) or do not display it, basically anything but interpreting it as user input.
```

### Screenshots

![image](https://user-images.githubusercontent.com/56163633/150390172-40f4349b-fda7-4d67-b16c-93ebd0c3532d.png)

### Operating System

MacOS

### OS Version

11.6.2

**Comment by elviskahoro** [comment]
We're talking about this here:
- https://github.com/warpdotdev/Warp/discussions/422
