### ISSUE TITLE
make suggestions for targets 

### ISSUE THREAD

**Issue by japanese-goblinn** [warpdotdev/warp#65]
**Describe the solution you'd like**
Suggestions just like you did with `git` 

**Additional context**
<img width="387" alt="image" src="https://user-images.githubusercontent.com/33631005/126879499-699aa685-c577-465c-92a2-55fa52c587bc.png">

**Comment by zachlloyd** [comment]
Should be doable, and and makes a lot of sense.  Thanks for the feedback.

**Comment by alokedesai** [comment]
@japanese-goblinn we should now have completions when running `make`. Would you mind double checking that this is working for you? Thanks!

**Comment by alokedesai** [comment]
Closing this out as it should be addressed, feel free to reopen if you are still having issues with completions for `make`!

**Comment by japanese-goblinn** [comment]
Everything is working great! Closing the issue
