### ISSUE TITLE
Easy / Quick way to copy a path (or similar text pattern) + Ability to configure characters selected with mouse DBLCLICK 

### ISSUE THREAD

**Issue by maxjeffos** [warpdotdev/Warp#659]
### Describe the solution you'd like?

It would be nice to be able to easily select an entire phrase of text contained within whitespace. This is especially useful when copying paths.

### Is your feature request related to a problem? Please describe.

When using iTerm2 and Alacritty, if I double click on a word it selects everything inside of the whitespace. Here's an example to hopefully will make it clear:

Say I do `pwd` and get the following:

```shell
/usr/local/bin
```

With the iTerm2/Alacritty, if I double click on any of `usr`, `local`, or `bin`, it selects the entire `/usr/local/bin` and this is usually what I want. With Warp, it selects only the word I double click on, for example, `usr`. I understand this is keeping with the usual function within an editor, however, it would be nice to have a way to select the entire `/usr/local/bin`... i.e. the entire thing inside of whitespace. And I don't just mean to get the current directory - this is just an easy example and I know Warp has a nice easy way to do that. More often this is a thing I do when using git - selecting and copying/pasting paths with git command lines. Does that make sense?

**Comment by phstc** [comment]
For context, iTerm has it as a setting.


![](https://user-images.githubusercontent.com/105652/162323527-4a0b1ff7-bea7-4b4b-856e-b5b3460df697.png)

From: #956

**Comment by elviskahoro** [comment]
### Describe the solution you'd like?

```shell
It would be lovely to be able to customize the world delimiters as the windows terminal propose with wordDelimiters (https://docs.microsoft.com/en-us/windows/terminal/customize-settings/interaction#word-delimiters)

This would allow to make the autoselect on double click behave as we want.

Ideally this would be used by shortcuts as ^ W (control w) as well.
```


### Is your feature request related to a problem? Please describe.

```shell
TodayI basically cannot use autoselect as it never behaves as I'd like (it considers - as a delimiter for example). This is a huge loss in productivity.
```


### Additional context

_No response_

**Comment by elviskahoro** [comment]
From @dmilith via #1134
### Discord username (optional)

dmilith#1284

### Describe the solution you'd like?

```text
I'd like to have control over which chars are included when I do mouse/trackpad double click on a terminal output text.

An example:
I do `exa /dev/` followed by [Enter].
I see "tty.Bluetooth-Incoming-Port" file which I'd like to be able to select as a single word after double-clicking it with my trackpad.

Currently, only one of the graphemes gets selected.
```


### Is your feature request related to a problem? Please describe.

_No response_

### Additional context

_No response_

**Comment by kaedenwile** [comment]
+1 This is my biggest pain point with using warp so far. Would really like to see support for auto-selecting full path

**Comment by george-halpert** [comment]
IMHO even if user configuration is supported a more reasonable default of what is selected should be made (e.g. select all characters in both directions until you hit a whitespace character or start or end of line). 

Also you should be able to easily extend the selection further (e.g. by holding the SHIFT key down and clicking your mouse). Currently if I select text and then SHIFT+Click somewhere it deselects what was selected (happens in both the command input area and the previous blocks).

**Comment by kecinzer** [comment]
+1

**Comment by isaac-mcfadyen** [comment]
Personally I feel that I like the current behavior, but I get that it might not be preferred at all times.

What would really be great is a configuration option that the user has the option to change (i.e. what it currently does or other options).

**Comment by elviskahoro** [comment]
This was launched today! Please let us know your thoughts! We can open up new issues for any trailing requests.
