### ISSUE TITLE
Fish-like Syntax Highlighting - Highlighting existing and not existing commands

### ISSUE THREAD

**Issue by japanese-goblinn** [warpdotdev/Warp#66]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to enter a command to know if it exists 

**Describe the solution you'd like**
Highlight existing command with a green color and not existing with a red color 

**Additional context**
<img width="117" alt="image" src="https://user-images.githubusercontent.com/33631005/126879566-056023ca-93df-4d70-b399-e150e702c56a.png">
<img width="193" alt="image" src="https://user-images.githubusercontent.com/33631005/126879574-1a833298-f43f-4b57-a3ab-54cdc1c5d101.png">

**Comment by zachlloyd** [comment]
Great idea, and very doable.  Thanks for suggesting.

**Comment by elviskahoro** [comment]
https://github.com/warpdotdev/warp/issues/32

The font color should be customizable for both states (command exists vs command does NOT exist).

**Comment by mneira10** [comment]
Hey! I've been loving warp but really need this feature. Is there an estimate on when it will be shipped?

**Comment by piavgh** [comment]
the only thing that prevents me from switching to Warp entirely is this feature :D 
Is there any ETA for this? Thanks.

**Comment by elviskahoro** [comment]
There isn't an ETA. There is a prototype however

**Comment by tiltowait** [comment]
This is the only thing I'm missing and would switch to Warp full-time if it had it!

**Comment by Advait-M** [comment]
Hey folks 👋 ! @japanese-goblinn @mneira10 @piavgh @tiltowait 

Super excited to let everyone know that we just launched **Syntax Highlighting and Error Underlining on Warp yesterday** 🎉 ! By default, Warp will highlight each part of a command in a different color denoting arguments, options/flags, variables, etc. and underline invalid commands with a dashed red line. You can toggle these features on/off via the Command Palette or Settings > Features.

Please download the latest release (`v0.2022.10.11.08.13.stable_01`) to get access to these features! The screenshot below shows the features in action:

![Syntax Highlighting and Error Underlining Demo](https://user-images.githubusercontent.com/12927474/195830313-e3eab7b1-84c7-4118-896d-443215c1e3b5.png)

Check out our [user documentation](https://docs.warp.dev/features/editor/error-syntax-highlighting) for more details!

Let us know if you have any comments/feedback on these features!

<details>
  <summary>CC</summary>

@Ydot19 @denniswenger @joakimhew @markovxmachina @rmaclean-ee @ccpost @Agrailag @m-radzikowski
 
</details>

**Comment by ascendedco** [comment]
> Hey folks 👋 ! @japanese-goblinn @mneira10 @piavgh @tiltowait
> 
> Super excited to let everyone know that we just launched **Syntax Highlighting and Error Underlining on Warp yesterday** 🎉 ! By default, Warp will highlight each part of a command in a different color denoting arguments, options/flags, variables, etc. and underline invalid commands with a dashed red line. You can toggle these features on/off via the Command Palette or Settings > Features.
> 
> Please download the latest release (`v0.2022.10.11.08.13.stable_01`) to get access to these features! The screenshot below shows the features in action:
> 
> ![Syntax Highlighting and Error Underlining Demo](https://user-images.githubusercontent.com/12927474/195830313-e3eab7b1-84c7-4118-896d-443215c1e3b5.png)
> 
> Check out our [user documentation](https://docs.warp.dev/features/editor/error-syntax-highlighting) for more details!
> 
> Let us know if you have any comments/feedback on these features!
> 
> CC

Awesome news! Now just #17 and this becomes an easy replacement for any terminal.

**Comment by Advait-M** [comment]
Going to close this issue - feel free to open new issues for anything that comes up or additional feature requests 😄 !
