### ISSUE TITLE
React Native - Open terminal instead of Warp

### ISSUE THREAD

**Issue by pavillarre** [warpdotdev/Warp#666]
### Describe the bug

```shell
In React Native development, when run the command 'run ios' it opens the bundler in the terminal instead of Warp.
```

### To Reproduce

Steps to reproduce:
1. Open Warp
2. cd to project
3. run the command 'run ios'
4. It open the bundler in another terminal

### Screenshots

https://user-images.githubusercontent.com/94389070/150885013-3b88ea54-a471-443b-a1bf-986bf7ff436e.mp4

### Operating System

MacOS

### OS Version

21.1

**Comment by fishcharlie** [comment]
Isn't this an issue with React Native, not Warp?
