### ISSUE TITLE
Autocomplete can not work when filename contains a space

### ISSUE THREAD

**Issue by semparichyoung** [warpdotdev/Warp#669]
### Describe the bug

```shell
In terminal will use a \ to escape space(" ").

In Warp, it is the same, but if the file is a folder, it will not able to continue to autocomplete after the folder which the name with space.
```

### To Reproduce

Steps to reproduce:
1. Change a folder name with space, like 'Group 210125'
2. Type: cd Grou + TAB
3. The folder name will show, but after that TAB will out of work

### Expected behaviour

```shell
TAB should always works no matter there is space or not.
```

### Operating System

MacOS

### OS Version

11.6.2

**Comment by elviskahoro** [comment]
@semparichyoung can you send a video please?

**Comment by semparichyoung** [comment]
[https://youtu.be/pN9g8oajtcg](url)
I always try tab first, then enter, arrow key.
This will work only if there is a history start with same command.

**Comment by BryanAtVimcal** [comment]
This bug also appears when you attempt to copy the path in a referenced file. The space does not get escaped properly.

**Comment by ark-1** [comment]
I'd like to note that, while not being a show-stopper, this issue annoys me on a daily basis. I have some folders with spaces in their names, and it's real pain to navigate around them.
Also, I recently noticed that this is a regression: when I opened Warp on my previous Mac (an older version of Warp) it worked fine.

**Comment by warpdotdev-dx** [comment]
Aloke is gonna take a look into this when he gets back from vacation.

**Comment by clauber115** [comment]
Would love this to get fixed. Thanks!

**Comment by gutaker** [comment]
Yup, bit annoying, especially when on macOS you have lots of folders/filenames with spaces. Not to mention I moved from `iTerm2+oh-my-zsh`.
Counting on you guys 🤞

**Comment by vysecurity** [comment]
Still having this issue.

**Comment by dannyneira** [comment]
> Still having this issue.
> 
> EDIT: Oh the issue is still open on 669.
> 
> EDIT: This is a massive issue and really hinders usage.
> 
> Wonder if we can prioritize this @dannyneira?

For sure can bring this up with the team.

**Comment by vysecurity** [comment]
Sounds good! It should be a good one to fix as many people also have spaces in their file names.

**Comment by dannyneira** [comment]
Hi Folks, this is being worked on, no solid ETA on the fix, but we'll post updates on this thread as soon as we have them.

**Comment by elviskahoro** [comment]
This is launched!
