### ISSUE TITLE
Show git status indicators in prompt

### ISSUE THREAD

**Issue by zachlloyd** [warpdotdev/Warp#67]
Prompt should be configurable, but the default prompt for git should have an indication of the status of files in the current branch (e.g. are there staged files, merge conflicts, etc).

**Comment by elviskahoro** [comment]
From @philpicton
- #484

Show git/version control status in the prompt as well as the active folder and branch

In order for me to switch over to Warp I'd love there to be a way for me to see at a glance git status. I currently use Iterm and powerlevel10k and the solution there is incredibly useful and has saved me a lot of time fixing my own mistakes... It shows number of tracked and untracked changes, stashes, merge conflicts and so on, very useful.

![image](https://user-images.githubusercontent.com/29553206/148117176-8bd900ba-8385-4681-845b-b4122179c32b.png)

**Comment by elviskahoro** [comment]
>  would like to see more about git like how many commits ahead/behind from the remote branch am i and such things!

**Comment by Oxygen66** [comment]
It would be really useful to have the state of the `git diff` directly in the prompt.
On top of that, the branch name should be shortened because when you have panels and a long branch name, you won't have room to display the `git diff`.

**Comment by elviskahoro** [comment]
Still no ETA on this. But will circle back when there's progress.

**Comment by CoyoteWaltz** [comment]
Is this feature on the ROADMAP? Looking forward to it.

**Comment by philpicton** [comment]
I'd still like to see this too. For now I've used starship to make a custom prompt that suits me, which works great in Warp but the design/ui/ux could be much better if implemented as part of the app. 
![image](https://user-images.githubusercontent.com/89278080/185587861-41871f00-37e8-47f9-b84a-22905083df47.png)

**Comment by beeinger** [comment]
Hey guys, any updates on this? It's quite annoying not having this feature :/
And I do know a lot of developers who heard of you, tried, but stayed with their setups (eg. oh-my-zsh) just because of this feature missing.

**Comment by zachlloyd** [comment]
We are testing this internally and an initial version should launch in the
next week or two.  Thanks for the feedback!

**Comment by elviskahoro** [comment]
Hey everyone!

We are excited to announce that Warp's default prompt now shows the number of uncommitted changed files in your local git branch! Please refer to [the Prompt page in our documentation](https://docs.warp.dev/features/prompt) for more details. If you have any issues, feel free to [reach out to us](https://docs.warp.dev/help/sending-us-feedback) at any point, and thanks again for your continued support!

**Comment by philpicton** [comment]
If anyone is here looking for a more emoji-rich solution to showing the git status in their warp prompt, (and why wouldn't you? 🤓) Check out [starship](https://starship.rs/), and create your dream prompt.. [Here's mine ](https://gist.github.com/philpicton/a232b9662f07e8ce44409f7a03fed8b9) Don't forget to enable the ps1 prompt setting in warp.


![image](https://user-images.githubusercontent.com/89278080/204590768-4134416c-a2a1-4774-9cde-4a124bc2038a.png)
