### ISSUE TITLE
Command cursor moves to end when working with directory with git initialised

### ISSUE THREAD

**Issue by abhimanyubabbar** [warpdotdev/Warp#670]
### Describe the bug

```shell
When I cd in a git based directory, the command cursor moves to the end and commands and then mangled up.
```

### To Reproduce

Steps to reproduce:
1. Go to directory with git initialised.
2. Type any command.
3. Command along with meta information will be sent to terminal.

### Expected behaviour

```shell
Terminal should work in any directory.
```

### Screenshots

![Screenshot 2022-01-25 at 2 57 16 PM](https://user-images.githubusercontent.com/7313380/150950413-99b252c8-3091-4f94-ae74-b2fc82ab039b.png)

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment]
@abhimanyubabbar I love your profile pic.
On another note, it seems like you have a zsh theme or custom prompt set up and Warp unfortunately does not support them yet.

See this discussion:
- https://github.com/warpdotdev/Warp/discussions/422

**Comment by elviskahoro** [comment]
@abhimanyubabbar you should join the discord! 
https://discord.gg/warpdotdev
