### ISSUE TITLE
Block functionality disabled after OMZ Update

### ISSUE THREAD

**Issue by dickiedyce** [warpdotdev/Warp#672]
### Describe the bug

```shell
After running an `omz update` the block functionality is no longer present.
Neither the 3-dot menu in top right, nor the inter-block line appear.
`clear` now puts the cursor at the top of the window.
```

### To Reproduce

1. Open a window, when an OMZ update is due!
2. This seems to confuse Warp, as the response (`N`) already appears in the wrong place.
3. Run an `omz update` instead.

### Expected behaviour

```shell
Blocks with 3-dot menu in top right of each block.
```

### Screenshots

Expected:
![CleanShot 2022-01-25 at 13 47 48](https://user-images.githubusercontent.com/1810481/150988775-fbf51a57-bc55-4f8b-a724-1dfcd01b4bb7.png)

Actual:
![CleanShot 2022-01-25 at 13 47 38](https://user-images.githubusercontent.com/1810481/150988733-23a48dfb-d6b9-4b31-b17e-06da665b9fbe.png)

### Operating System

MacOS

### OS Version

12.1

**Comment by JSextonn** [comment]
This seems to happen when running `omz reload` as well.

**Comment by elviskahoro** [comment]
Is OMZ creating a sub-shell?

**Comment by elviskahoro** [comment]
Just downloaded OMZ and it seems to be creating a subshell in warp.

**Comment by elviskahoro** [comment]
@JSextonn @dickiedyce 
I'm gonna close this until our custom prompt update comes out. After it comes out if this is still broken then we can reopen and figure out next steps. For now I'd just avoid using it:
See this part of our docs: https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files

```sh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

    # POWERLEVEL10K
    # OH-MY-ZSH-THEMES
    # OH-MY-ZSH-PLUGINS
    # FIG
    # BIND keys like:
    # bindkey "^j" down-line-or-beginning-search
    # [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && 
    # . "/usr/local/etc/profile.d/bash_completion.sh"
    # eval "$(rbenv init -)"

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi
```
