### ISSUE TITLE
File tab completion has issues when a directory has a large number of files

### ISSUE THREAD

**Issue by mandel-macaque** [warpdotdev/Warp#673]
### Describe the bug

```shell
When working and trying to do a simple command like `code filename.cs` if the directory contains a lot of files there is a large lag. When you try to use tab the cursor goes back to the end of the directory name and removes all the chars already typed. It is better shown in the attached video.

The file count is 354, which is not that many:

ls src | wc -l    
     354
```

### To Reproduce

Steps to reproduce:
1. Find a directory with a large number of files. In the video I'm suing the src directory in GitHub.com/xamarin/xamarin-macios
2. Try to execute a command using one of the files in the directory and use tab to autocomplete.
3. Tab does not complete and deletes what was already typed.

### Expected behaviour

```shell
Tab completion works.
```

### Screenshots

https://user-images.githubusercontent.com/2190086/151050769-4a8b15d1-944e-4e76-8af2-99c205926952.mov

### Operating System

MacOS

### OS Version

12.1

**Comment by mandel-macaque** [comment]
Video is tiny probably because GitHub is trying to be smart, larger version: https://microsofteur-my.sharepoint.com/:v:/g/personal/mandel_microsoft_com/EWVxJ-2IHBlIr4RXvDbcnqUBQBvJD39xltIQx8Wx3WNhig?e=RmvQqM

**Comment by mandel-macaque** [comment]
The version I'm running is v0.2022.01.17.08.48.stable_01

**Comment by elviskahoro** [comment]
@mandel-macaque so turns out this may not be because of the large number of files. See:
- #695

**Comment by elviskahoro** [comment]
Gonna move this to there actually!
