### ISSUE TITLE
Customizable window and prompt

### ISSUE THREAD

**Issue by Lokdex** [warpdotdev/Warp#676]
### Describe the solution you'd like?

I will make two suggestions at once:
First, I think it would be helpful to have a more customizable window, like the options you get on Alacritty. For example to set a height and width for the window, or even its position on the screen, and some people like to define transparency to the background.

Second, could support for custom prompts be added? The default prompts looks good, but some people coming from other terminals have configured custom prompts, like starship prompt which adds quite a lot of functionalities. I can only get that behavior if I execute zsh again from the terminal.

### Is your feature request related to a problem? Please describe.

Being used to more older terminals I found warp to be really beautiful, fast, and functional, however some customizations that I was used can't be applied yet to Warp. I find the default window size too big for most of my use cases, and the prompt is missing my customizations I added in zsh.

**Comment by elviskahoro** [comment]
See:
- https://github.com/warpdotdev/Warp/issues/19
- https://github.com/warpdotdev/Warp/issues/580
