### ISSUE TITLE
Restore Windows Info link in preferences goes to a missing page.

### ISSUE THREAD

**Issue by bwinton** [warpdotdev/Warp#677]
### Describe the bug

```shell
Clicking the tiny ⓘ beside "Restore windows, tabs, and panes on startup" takes me to https://docs.warp.dev/features/session-management-and-restoration which says "Page not found"…
```

### To Reproduce

Steps to reproduce:
1. Go to app preferences
2. Click on the ⓘ
3. See "Page not found"

### Expected behaviour

```shell
Read a description of the feature?
```

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment]
@bwinton 
This was a weird bug with gitbook. Thanks for flagging. Just fixed it!
