### ISSUE TITLE
Shortcut problem in korean language

### ISSUE THREAD

**Issue by sunyouman** [warpdotdev/Warp#678]
### Describe the bug

```shell
I use Korean Language.
When keyboard setting is Korean, I does not work Shortcut.
```

### To Reproduce

Steps to reproduce:
1. Change keyboard language to Korean
2. `Cmd` + `E`
3. Not working

However, Default Shortcut is OK (like `Cmd` + `W`)

### Expected behaviour

```shell
Shortcut is worked
```

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment]
Moving to:
- https://github.com/warpdotdev/Warp/issues/341
