### ISSUE TITLE
It would be nice if the arrow keys on the command palette wrapped around…

### ISSUE THREAD

**Issue by bwinton** [warpdotdev/Warp#681]
### Describe the solution you'd like?

I was looking for the command to select the previous commands output, so I hit ⌘P, typed "select", and then hit the down arrow a bunch. When it hit the end of the list, I needed to hit the up arrow a lot to get back to the top, and I think it might be nice if I could continue hitting the down arrow, and have it wrap around to the top (and vice versa for the up arrow at the top of the list going to the bottom entry)…

**Comment by elviskahoro** [comment]
Thanks for reporting this

**Comment by elviskahoro** [comment]
This was launched!
