### ISSUE TITLE
Clear doesn't work

### ISSUE THREAD

**Issue by vicyyn** [warpdotdev/Warp#687]
### Describe the bug

```shell
Machine : Mac m1 pro
```

### To Reproduce

type `clear`

### Expected behaviour

```shell
Clears the terminal
```

### Screenshots

![image](https://user-images.githubusercontent.com/55297234/151362340-58ad180b-ee9c-40e6-b706-2ecebc251fde.png)

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment]
Can you send a video?

**Comment by vicyyn** [comment]
Uploading Screen Recording 2022-01-31 at 2.15.13 PM.mov…

**Comment by vicyyn** [comment]
https://user-images.githubusercontent.com/55297234/151800347-e6b51ccf-6591-431d-be8d-6941d61a31bb.mov

**Comment by elviskahoro** [comment]
What does pressing CTRL-L do in your Warp?
Which shell are you using?
Does this happen when you have clean dotfiles?
You can quickly set up clean configs by putting ZDOTDIR=/ in a ~/.zshenv file. This forces zsh to run with zero configs.

**Comment by vicyyn** [comment]
ctrl-l works, it clears the terminal
I am using bash

**Comment by elviskahoro** [comment]
Duplicate of #008
