### ISSUE TITLE
Core: Drag and Drop file/directory etc.

### ISSUE THREAD

**Issue by japanese-goblinn** [warpdotdev/warp#69]
**Is your feature request related to a problem? Please describe.**
I wish I can get an absolute path inserted into the terminal on drag and drop. There's no integration between macOS UI and Warp for now, so that feature might be useful in some cases.

**Comment by simjnd** [comment]
A command in the command palette to open Warp's working directory in Finder could be interesting as well so you can interact both ways: from the Finder to Warp and from Warp to the Finder.

**Comment by zheng** [comment]
We agree! This is a missing native OS feature.

**Comment by mredig** [comment]
I see this is an existing request - throwing in my 2¢ that this is the primary stopper before I can use this for my real terminal.

**Comment by elviskahoro** [comment]
Linking:;

- #356

**Comment by elviskahoro** [comment]
v0.2021.11.16.20.05.stable_01
