### ISSUE TITLE
PTY allocation request failed on channel when trying to SSH into Gitlab

### ISSUE THREAD

**Issue by ahmadalfy** [warpdotdev/Warp#690]
### Describe the bug

When I run

```shell
ssh git@gitlab.com 2fa_recovery_codes
```

I received the following

```shell
PTY allocation request failed on channel 1
```

Tried running on another terminal, worked as expected.

### To Reproduce

Run `ssh git@gitlab.com 2fa_recovery_codes` in terminal when your SSH key is configured on Gitlab

### Expected behaviour

Terminal should prompt if I would like generate new code like the following:

```shell
Are you sure you want to generate new two-factor recovery codes?
Any existing recovery codes you saved will be invalidated. (yes/no)
yes

Your two-factor authentication recovery codes are:

xxxxxxxxx
```

### Screenshots

<img width="356" alt="image" src="https://user-images.githubusercontent.com/87611/151390881-7a321e26-67f8-445e-8ea0-536db413b45b.png">

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment]
We're keeping all our SSH issues into one place, so it's easier for us to investigate it, all at once. Moving to:
- #690
