### ISSUE TITLE
Moved to #101 - Software Update: should appear in System Menu (Warp or Help) on macOS

### ISSUE THREAD

**Issue by fbartho** [warpdotdev/Warp#692]
### Describe the solution you'd like?

**Short Description:** Check-for-updates/Install-updates should appear in the System Menu bar for an application, and should be searchable from the Help menu.

On macOS, it's weird to have an action or operation that isn't available in the standard System Menu bar. Commands in the System Menu can be highlighted if users type fuzzy-match letters to find commands in any of the menus, so this makes the functionality more accessible.

`Update Available` seems to only appear embedded in the Terminal Window Chrome around the 3-dots menu in the top right.

Moving everything in the 3-dots menu under the `Help` menu (except for settings to the `Warp` menu #358 #101) would better match the platform conventions.

### Is your feature request related to a problem? Please describe.

I struggled to find where to check if my app was up-to-date. I checked all the menus in the App's System Menu, and I checked the App's Settings page. Before finally finding the non-standard 3-dots menu.

### Additional context

![Screenshot of the 3-dots menu, open, with no-pending updates](https://user-images.githubusercontent.com/209712/151425552-6575230f-0e29-4920-a33c-72b7f774ec00.png)

**Comment by elviskahoro** [comment]
Just gonna move this to #101 actually so it's all in one place for us.
