### ISSUE TITLE
git diff autocomplete not working

### ISSUE THREAD

**Issue by noells** [warpdotdev/Warp#696]
### Describe the bug

```shell
When running `git diff Docke<tab>`, for example, Warp does not autocomplete the file name.
```

### To Reproduce

Steps to reproduce:
1. Go to a local git repository
2. Modify a file called `filename` (just an example)
3. Try to `git diff filena<tab>`
4. See that it does not autocomplete

### Expected behaviour

```shell
It should autocomplete the filename of modified files
```

### Operating System

MacOS

### OS Version

12.1

### Additional context

```shell
Using warp with zsh as default shell
```

**Comment by shaddoxac** [comment]
Would greatly appreciate an update here - would like to switch fully to warp but small features like this are really keeping me from making the jump.

**Comment by noells** [comment]
Not solved yet. I am actually using Warp on a daily basis but, as you said, this small features make a huge difference!

**Comment by AndyDyer** [comment]
i agree

**Comment by elviskahoro** [comment]
This has since been added. Apologies for the delay!
