### ISSUE TITLE
Hangs when $SHELL prompts for input

### ISSUE THREAD

**Issue by subdigital** [warpdotdev/Warp#698]
### Describe the bug

```shell
I have an SSH agent step in my .zshrc that prompts for a passphrase on first launch. If I run Warp after a reboot, it says "starting zsh..." followed by a warning that my shell is taking a while to load.

Eventually I see a block with this output:


Enter passphrase for /Users/ben/.ssh/id_rsa:
```

But since this is an output block I can't actually type in there.

For now I can type this with a different terminal and re-launch Warp, but would be nice if I didn't have to do this.
```


### To Reproduce

Create an ssh key with a passphrase. Then add this to your .zshrc (or similar) file:

```
if [ ! -S ~/.ssh/ssh_auth_sock ]; then
  eval `ssh-agent`
  ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
ssh-add -l > /dev/null || ssh-add
```

This will prompt for your pass phrase upon first reboot.

### Expected behaviour

_No response_

### Screenshots

_No response_

### Operating System

_No response_

### OS Version

_No response_

### Additional context

_No response_

**Comment by elviskahoro** [comment]
We're keeping all our SSH issues in one place, so it's easier once we start working on this.
Subscribe to this issue:
- https://github.com/warpdotdev/Warp/issues/578

I'm moving this to here:
- https://github.com/warpdotdev/Warp/discussions/502

**Comment by subdigital** [comment]
This isn't an SSH issue, it's a zshrc that prompts for user input issue.

**Comment by elviskahoro** [comment]
@subdigital you're right! I saw ssh and went into autopilot. my bad

**Comment by elviskahoro** [comment]
@subdigital if you moved this to a function and ran it after Warp finished bootstrapping it should work.

**Comment by zheng** [comment]
hi @subdigital you should actually be able to type your password in the output block!

**Comment by zheng** [comment]
> hi @subdigital you should actually be able to type your password in the output block!

Haven't heard anything so I'm going to assume this works. Feel free to re-open if it doesn't!

**Comment by arietis** [comment]
Is there any chance to make the input inside an output block interactive? Right now it's hard to guess that you can actually type something there.

**Comment by csg524** [comment]
I think I'm having this issue? I'm trying to access certain files and they're password locked, and I can't type my password; the cursor changes to a turquoise block instead of the regular flashing line, and no input is registered. Running the same commands in terminal or iTerm2 allows input. It happens even with something simple like `sudo pkgutil --forget org.python.Python.Python310`.

I feel like I'm being stupid though, since I'm not very familiar with terminal usage.
