### ISSUE TITLE
Focus follows mouse

### ISSUE THREAD

**Issue by ianterrell** [warpdotdev/Warp#699]
### Describe the solution you'd like?

iTerm has a "Focus follows mouse" option that allows split panes to be navigated with just the mouse cursor. With a large screen I often split my terminal window into 3-5 panes, and this feature helps me switch between them quickly.

![Screen Shot 2022-01-28 at 12 46 28 PM](https://user-images.githubusercontent.com/54963/151596620-7674bdb2-14c1-4f5e-a739-3290f42ddea7.png)

https://user-images.githubusercontent.com/54963/151596639-6203a874-52cf-4dee-ab07-10c711ed512a.mov

**Comment by yvess** [comment]
This is the feature is miss the most from iTerm. Is there a rough ETA?

**Comment by joaberg** [comment]
+1
I really miss this feature. 
In my Hyprland desktop, window focus follows the cursor. So having to click in the pane always stumbles my workflow a bit.

**Comment by leiyangyou** [comment]
+1

**Comment by gudlyf** [comment]
+1

The context switch from iTerm2 to Warp is jarring, as I had always used mouse focus to switch windows. Now I often forget to click the window before typing.

**Comment by kmcduffee-verisk** [comment]
The lack of this feature is making me consider moving back to iTerm :(

**Comment by peter-kehl** [comment]
Anyone interested please give thumbs up to #2551.

**Comment by zachlloyd** [comment]
I just added this in the latest release.  Please let me know if you experience any issues!

<img width="705" alt="Screenshot 2024-10-17 at 11 31 30 AM" src="https://github.com/user-attachments/assets/292d32b3-4e61-4072-9d21-d7d09fcf2e82">

**Comment by dactylo** [comment]
Hey this is awesome- thanks!

**Comment by chrissmartin** [comment]
Thanks!

**Comment by f91og** [comment]
awesome feature, thanks

**Comment by yulincoder** [comment]
thanks! I love it

**Comment by BonesyWonesy** [comment]
Yessssss. Thank you!
