### ISSUE TITLE
CMD + up allows navigating off-screen

### ISSUE THREAD

**Issue by kesne** [warpdotdev/warp#7]
**Describe the bug**
I was able to issue a few commands, then cmd + up before the first command was issued. It seems to allow for two blocks before the top-most command (I had to issue two cmd + down to get the selected block back on-screen).

**To Reproduce**
1. Open new tab
2. Send a few commands (I issued a couple `clear` commands).
3. cmd + up repeatedly.

**Expected behavior**
It stops at the top-most block.

**Desktop (please complete the following information):**
MacOS 11.2.3

**Comment by zheng** [comment]
This has been fixed on master, should be available in our next release later this week!
