### ISSUE TITLE
Check for update gives no indication that something is happening visual indicator

### ISSUE THREAD

**Issue by rswerve** [warpdotdev/Warp#70]
**Describe the bug**
When clicking "Check for update," there's no indication to the user that the button click has done anything.  When there's no update, nothing at all happens, and when there is an update, it pops up some seconds after the Check button is clicked.

**Expected behavior**
There should be three possible states after the Check for update button is clicked:
Checking
Update available
No update available

**Comment by zheng** [comment]
Totally agree, thanks for reporting!

**Comment by elviskahoro** [comment]
Fix out today! We've moved check for update button to settings dialog.

BTW. The autoupdate check finished too fast for us to have anything in our UI to show. This new place should be better though. We also check for an updates automatically!
