### ISSUE TITLE
DUP: Duplicate of #304 - Focused pane should have a more prominent color scheme or indicator

### ISSUE THREAD

**Issue by ianterrell** [warpdotdev/Warp#700]
### Describe the solution you'd like?

I use a multi-pane workflow daily, usually 3-5 or so panes. When I navigate into or out of my terminal application I want to quickly identify which pane has focus. Warp's primary indicator of pane focus is a small triangle in the upper left corner, which is entirely too subtle. The command input area being expanded is also not quickly visually discernible in several panes.

Contrast with iTerm, which uses colors to distinguish the focus.

https://user-images.githubusercontent.com/54963/151597252-8c56034a-bbcc-40e5-8f11-e9519721be1d.mov

**Comment by elviskahoro** [comment]
@ianterrell moving this to:
- https://github.com/warpdotdev/Warp/issues/304

**Comment by ianterrell** [comment]
@elviskahoro thank you! I missed that issue in my search.
