### ISSUE TITLE
Tabbing into directory crashes Warp

### ISSUE THREAD

**Issue by koalazub** [warpdotdev/Warp#706]
### Describe the bug

```shell
Created `nushell` directory in `.config` and accidentally hit `ls` on `&` symbol that's present in directory. Doing it once was fine, doing it the second time crashed Warp
```

### To Reproduce

Steps to reproduce:
1. Go to something like `.config`
2. Make a directory called `&`
3. `ls` back to `$HOME`
4. `ls` into `&`
5. After first `ls`, attempt second `ls`

### Screenshots

https://user-images.githubusercontent.com/7111524/151727418-47d82ce2-429b-45dd-b97e-4913578135cf.mov

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment]
Thanks for submitting this! It's been triaged!

**Comment by dannyneira** [comment]
Hi @koalazub, We've made some changes and improvements in this area, are you still seeing the same issues on the latest version of Warp?

**Comment by koalazub** [comment]
Hey mate! I'm on Ubuntu for a good while and don't have a machine to test Warp on. Is there any chance that you or a member of the team might be able to give it a crack?

**Comment by dannyneira** [comment]
Hi @koalazub, We have a few cracks, but no luck reproducing. Closing for now, but if/when you are back on Warp and getting the same issues, please reopen and let us know.
