### ISSUE TITLE
Use Oh-My-Zsh themes

### ISSUE THREAD

**Issue by boris-deriv** [warpdotdev/Warp#708]
### Describe the solution you'd like?

```plaintext
It would be nice if we could use themes and customizations from `oh-my-zsh` in Warp.
```

### Is your feature request related to a problem? Please describe.

```plaintext
I am currently using oh-my-zsh and when opening any terminal(Hyper, iTerm2, iTerm), the presentation of the path is consistent to the one provided by the theme I set in `oh-my-zsh` but when I open Warp, it comes with its own presentation of the path.
```

**Expectation**
![Screen Shot 2022-01-31 at 15 25 16](https://user-images.githubusercontent.com/89076828/151801755-8b128ec0-5213-436f-8b88-8824c8715c2f.png)

**Actual**
![Screen Shot 2022-01-31 at 15 25 31](https://user-images.githubusercontent.com/89076828/151801776-077bdc96-c481-453c-a62f-855dcaf45b43.png)

**Comment by elviskahoro** [comment]
See our custom prompts discussion:
- #422
