### ISSUE TITLE
New Tab Directory Changes Change Directory on Original Tab Too

### ISSUE THREAD

**Issue by cschlittPHI** [warpdotdev/Warp#713]
### Describe the bug

```shell
I am in directory A, I open a new tab, cd into directory B, go back to tab A and it says I'm still in directory A but commands I make are reflected in directory B
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

**Comment by elviskahoro** [comment]
Can you please share a video? This sounds really bad!

**Comment by cschlittPHI** [comment]
> Can you please share a video? This sounds really bad!

Will do! Trying again a few times this morning I can't seem to reproduce it again, but the next time it happens I'll definitely share a video of it here. Happy to help squash this bug during the beta period! Stay tuned.

**Comment by elviskahoro** [comment]
Gonna close this for now!
