### ISSUE TITLE
when losing connection to server, the error string copies into where you would type stdin

### ISSUE THREAD

**Issue by jonashojer** [warpdotdev/Warp#714]
### Describe the bug

```shell
After idling for a bit on a server i got the "client_loop: send disconnect: Broken pipe", and whenever it did that it typed the string into where I would type my stdin. This was while I was jumping through another server.

I then tried to directly SSH to a server and idled I got the "Shared connection to <SERVER_NAME> closed." it did the same where it copied the string into where I type my stdin.
```

### To Reproduce

Steps to reproduce:
1. SSH to any server(both through a jump and without)
2. Idle for a while until you get a disconnect message from the server
3. You'll see now that the error message now is copied into your where you type stdin

### Expected behaviour

```shell
I expect it not to copy the string(s) into my stdin.
```

### Screenshots

![image](https://user-images.githubusercontent.com/86884161/151878600-b0695cce-9a9d-4f67-b5de-46e935f4da39.png)
![image](https://user-images.githubusercontent.com/86884161/151878929-48beeb51-3b54-481b-8f68-a1a6f8ae1b9e.png)

### Operating System

MacOS

### OS Version

12.1

### Additional context

```shell
This is not fully researched, I just noticed it randomly.
```

**Comment by elviskahoro** [comment]
@jonashojer moving to:
- #502

Keeping it one place because it helps us debug.
