### ISSUE TITLE
Find is not working with less pager

### ISSUE THREAD

**Issue by mgiachetti** [warpdotdev/Warp#716]
### Describe the bug

```shell
Find feature is not highlighting words when less pager is used by a long output command.
```

### To Reproduce

Steps to reproduce:
1. Execute a command that use less pager eg: `git log/diff` (with big logs) or `man man` (in the attached video)
2. Use find to seach any word shown at the screen

### Expected behaviour

```shell
highlight the word searched
```

### Screenshots

Warp behaviour

https://user-images.githubusercontent.com/1557575/151893746-05f61e1c-26f8-476d-bc5c-964004ae4073.mov

Iterm behaviour

https://user-images.githubusercontent.com/1557575/151893763-f2a36e0a-5983-46ee-9436-20a1bf59e777.mov

### Operating System

MacOS

### OS Version

10.15.7

**Comment by elviskahoro** [comment]
This has been fixed!
