### ISSUE TITLE
Unable to close Settings menu after sending an invite from the settings.

### ISSUE THREAD

**Issue by royalbhati** [warpdotdev/Warp#717]
### Describe the bug

In the Account section when I click on "Send an Invite" button a popup comes up, when you close that pop up there's no way of closing the settings menu. Escape key doesn't work and you are forced to close the application.

### To Reproduce

Steps to reproduce:
1. Go to 'Settings -> Account'
2. Click on 'Send An Invite'
3. Close the popup
4.  Try closing settings now

### Expected behaviour

Should be able to close settings

### Operating System

MacOS

### OS Version

11.2.3

**Comment by alokedesai** [comment]
Hey @royalbhati, just following up here! Are you still able to reproduce this?

**Comment by elviskahoro** [comment]
This should be fixed now!
