### ISSUE TITLE
Moved to #697 - It be nice if one could duplicate tabs or if there are tab presets

### ISSUE THREAD

**Issue by ppwfx** [warpdotdev/Warp#718]
### Describe the solution you'd like?

```shell
It be nice if one could duplicate tabs or if there are tab presets
```

**Comment by elviskahoro** [comment]
@ppwfx what are you imagining presets to look like + what functionality would you want them to support?
+ have you seen this:
- https://github.com/warpdotdev/Warp/discussions/697

**Comment by ppwfx** [comment]
awesome, #697 is exactly what I was looking for 

is there an ETA for it?
