### ISSUE TITLE
`yarn login` breaks block rendering

### ISSUE THREAD

**Issue by colinking** [warpdotdev/warp#72]
**Describe the bug**

When you run `yarn login` (version `1.22.10`), it asks for two prompts, but Warp appears to hide that block. Occasionally it does show the block, but I'm unable to see what I've typed into the prompt (or see the second prompt). Here's a demo:

https://user-images.githubusercontent.com/2907397/127175266-ffee651f-3507-4b5a-8e3f-aad02bf9968e.mp4

`npm login` also appears broken, so this might be specific to prompts?

**To Reproduce**
You should just need to run `yarn login` to recreate.

**Expected behavior**
Here's what happens in iTerm2, which is what I expect:

https://user-images.githubusercontent.com/2907397/127175654-f5e913ec-25bf-4a73-b7e6-7d8bfaea0d85.mp4

**Desktop (please complete the following information):**
 - OS Version:  MacOS 11.4

**Additional context**

**Comment by charlespierce** [comment]
Hi @colinking, thanks for reporting! Is this reproducible regularly for you? I think this may be related to another rendering bug we've run into internally, but haven't been able to reliably reproduce. If it is, then that should help us track it down!

**Comment by zheng** [comment]
This should be fixed in the latest release!
