### ISSUE TITLE
recover lost ssh session

### ISSUE THREAD

**Issue by kdriver** [warpdotdev/Warp#720]
### Describe the bug

```shell
I run long session ssh, but within 24 hours the session breaks.   Then when I log in again, I get a shell script trace and when I move the mouse, only escape characters, and I can not type in the terminal.

v0.2022.01.24.08.55.stable_02
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```shell
normal ssh log in.
```

### Screenshots

![image](https://user-images.githubusercontent.com/179049/151942815-255c0bb1-9a3f-473e-995e-1b953c6edb6f.png)

### Operating System

MacOS

### OS Version

12.2

**Comment by elviskahoro** [comment]
@kdriver moving this to:
- #502
