### ISSUE TITLE
I zoomed out (command -) and I can't zoom in (command +)

### ISSUE THREAD

**Issue by rodrigoescandon** [warpdotdev/Warp#728]
### Describe the bug

```shell
I zoomed out pressing command and the minus key, and I was able to make the font size smaller. I tried to zoom in using command and plus, and it doesn't work. I am able to increase font size from the preferences panel, but not from the keyboard shortcut.

I'm on a Mac with a Spanish ISO keyboard.
```

### To Reproduce

Steps to reproduce:
1. Press command and minus keys; it zooms out.
2. Press command and plus keys (see image); it does not zoom out.

<img width="780" alt="Screen Shot 2022-02-04 at 11 59 47 AM" src="https://user-images.githubusercontent.com/2545393/152579510-20bf7965-19e8-4219-a3e6-22b713c40034.png">

### Expected behaviour

```shell
Text should increase size.
```

### Operating System

MacOS

### OS Version

11.5.2 (Big Sur)

### Additional context

```shell
Spanish ISO keyboard.
```

**Comment by elviskahoro** [comment]
Moving this to #715
