### ISSUE TITLE
Moved to #579: ENTER - Allow configuring whether enter executes command or inserts new line (CMD-ENTER to run)

### ISSUE THREAD

**Issue by colinking** [warpdotdev/Warp#73]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to customize the `Enter` behavior in Warp.

By default, `Enter` executes a command while `Opt-Enter` inserts a newline. There's a similar UX in Slack, which they let you customize:

![image](https://user-images.githubusercontent.com/2907397/127178308-317cacd1-a505-42cd-9f7c-b900949b4466.png)

Would be great if a) this used `CMD` instead of `Opt` (for macOS at least) and b) if there was a way I could flip these bindings to match what I'm used to from Slack.

**Describe the solution you'd like**
(see above)

**Additional context**

**Comment by simjnd** [comment]
A very common pattern on many apps/websites is to use `Shift` + `Enter` to insert a new line, so having the option to choose between `Alt`, `Cmd`, `Shift` and even `Ctrl` as a modifier alongside the `Enter` key could be a good move, offering more flexibility

**Comment by zheng** [comment]
We want to support custom key-binding in general (see #30). This particular setting is really interesting! What would you say is the use case here? We take a lot of inspiration from Slack in general, and I can see this being useful for some segment of users.

By the way, both `Shift` + `Enter` and `Opt` + `Enter` will add a new line in Warp.

**Comment by elviskahoro** [comment]
Moving to #579 so all keybinding related issues are in one place:
- #579
