### ISSUE TITLE
Switch pane up/down regression?

### ISSUE THREAD

**Issue by bylethviva** [warpdotdev/Warp#730]
### Describe the solution you'd like?

```shell
I updated Warp to v0.2022.01.31.09.03.stable_00 today and I've lost the ability to switch panes up or down via the keyboard shortcuts. Has there been a regression or have these shortcuts been deliberately removed? If it's not possible to get these added back, is there someway to navigate between vertical panes using the keyboard? Having to use my mouse whenever I need to change panes, which is very frequent throughout the day, is a very large inconvenience.
```

### Additional context

The [web documentation](https://docs.warp.dev/features/keyboard-shortcuts) still lists these as an option as shown in my included screenshot taken today that's below.

![Screen Shot 2022-02-04 at 3 27 08 PM](https://user-images.githubusercontent.com/69170267/152598890-69db93db-c8c9-4d51-abf0-0a29273f8c6c.png)

If I use `CMD + p` to open the keyboard shortcuts and search for `switch` the desired up/down options aren't there.

![Screen Shot 2022-02-04 at 3 34 32 PM](https://user-images.githubusercontent.com/69170267/152599417-7696cf72-9845-46c3-8fc3-23ee2647faec.png)

**Comment by elviskahoro** [comment]
@bylethviva We launched being able to add multi-cursors using OPT-CMD-DOWN and OPT-CMD-UP and simply forgot about the fact these were binded to switch panes UP/DOWN. So these got overwritten. Sorry about this, will share updates soon.

**Comment by elviskahoro** [comment]
@bylethviva can you email me: elvis@warp.dev?
Will send you a link to the prior release so you can rollback. We're gonna fix it in the next release. Sorry again for the trouble.

**Comment by elviskahoro** [comment]
@bylethviva we've added support for custom keybindings and so you can change them now. Gonna close this issue.
