### ISSUE TITLE
Bindable Keyboard Shortcuts

### ISSUE THREAD

**Issue by pyronaur** [warpdotdev/Warp#732]
### Describe the solution you'd like?

```shell
Allow the user to bind keyboard shortcuts.
```

### Is your feature request related to a problem? Please describe.

I know `Control R` is an ancient standard, but I'd be happy to do away with that and instead bind it to something I'm more used to - `cmd + shift + p` or `cmd + o` are two shortcuts that come to mind.

I think ctrl+r is a good default for most users - but it'd be really cool if we could just choose which keys to rebind to.

**Comment by elviskahoro** [comment]
See this issue:
- https://github.com/warpdotdev/Warp/issues/579

**Comment by pyronaur** [comment]
Oh, I searched for keyboard bindings and couldn't find anything. Thanks @elviskahoro 👍

**Comment by elviskahoro** [comment]
@pyronaur 
Thanks for pointing that out. I'll add bindings to the title so it's easier to find.

**Comment by pyronaur** [comment]
Haha, that reminded me of a joke:

> An SEO copywriter walks into a bar, grill, pub, public house, Irish, bartender, drinks, beer, wine, liquor...
