### ISSUE TITLE
Support for PowerLevel10K zsh theme

### ISSUE THREAD

**Issue by wintermi** [warpdotdev/Warp#734]
### Describe the solution you'd like?

```shell
I would like to see PowerLevel10K zsh theme support.  (https://github.com/romkatv/powerlevel10k)

Specifically supporting the prompt styles, and Power Line font support. As shown in the screenshot provided below.

I know the way the prompt works in Warp is part of its uniqueness, however being able to keep the styles already configured whilst providing this extra capability would take it to the next level. IMO.
```

### Additional context

![Screen Shot 2022-02-07 at 4 57 37 pm](https://user-images.githubusercontent.com/33818/152732725-52414c6d-8076-4642-bda9-e29377709469.png)

**Comment by elviskahoro** [comment]
Hey @wintermi! We recently launched support for some of the custom prompt tools. Not powerlevel10k. We added some details on our docs for what we it supports:
[https://docs.warp.dev/features/prompt](https://docs.warp.dev/features/prompt)

Powerlevel10k probably will not be supported, the team is currently leaning towards creating a native solution. We are having a twitter space on this next wednesday to share how we're thinking about it.

https://twitter.com/i/spaces/1YpKkZeYdNyxj

We'll also create a GitHub discussion so we can solicit feedback.
