### ISSUE TITLE
DUP: Duplicate of #036 - Use mouse to copy text located in prompt

### ISSUE THREAD

**Issue by terrisgit** [warpdotdev/Warp#735]
### Describe the solution you'd like?

Although I can click-drag to select console output (say to copy it to the clipboard), for some reason I can't select text that appears in the prompt. For example, I want to copy the text "NXL-24333" that appears in the prompt (see attachment).

### Additional context

<img width="631" alt="Screen Shot 2022-02-07 at 12 22 54 PM" src="https://user-images.githubusercontent.com/6069365/152865824-8962ac17-3569-44c3-a0c2-7a9f5f567d89.png">

**Comment by elviskahoro** [comment]
@terrisgit Hey! You can right click the prompt! And copy the information in it.

<img width="371" alt="Screen Shot 2022-02-07 at 3 55 22 PM" src="https://user-images.githubusercontent.com/29553206/152870441-c641e2b9-8a70-4b89-ba8e-7850c3fd895b.png">

**Comment by mkartashev** [comment]
The above workaround works only if you want the entire prompt. I usually want to just copy the git branch name I'm working on, for instance, and nothing else.

**Comment by elviskahoro** [comment]
@mkartashev Does the "copy git branch" option not appear for you? Just checking if to see if there's another bug in addition to the text in the prompt not being copyable in general.

**Comment by elviskahoro** [comment]
Moving to:
- #036

**Comment by mkartashev** [comment]
@elviskahoro The "Copy branch" option works for me, thanks!
