### ISSUE TITLE
Add the ability to search though the output of a running command

### ISSUE THREAD

**Issue by JakesObrien** [warpdotdev/Warp#736]
### Describe the solution you'd like?
When the output of a command overtakes the entire viewport I should be able to search through the output

### Is your feature request related to a problem? Please describe.
I often use `git log` to search through git history for information on individual commits and releases. Usually, I would usually achieve this by searching through the output for release or ticket numbers but this is not possible in the warp as you are not able to search the output of the command only the commands that have been input themselves.

**Comment by elviskahoro** [comment]
Hey @JakesObrien I can do this on my warp? Have you tried clicking the find in block once you've opened the search bar with CMD-F
Here's a video:
https://share.getcloudapp.com/d5uNQqXy

**Comment by JakesObrien** [comment]
Hi @elviskahoro, this is interesting. 

After further looking it appears the problem isn't the search is working in the wrong area, the search box itself does not open when I am viewing the output of `Git Log` which is why I am unable to search the contents. Trying to open this search box with the keyboard sortcut and by using the Edit menu does nothing.

https://user-images.githubusercontent.com/32345310/157023436-be2efd89-0938-4ee1-b0d4-f7c0c18e9a08.mov
