### ISSUE TITLE
Re-input as Root is Missing

### ISSUE THREAD

**Issue by OmerFlame** [warpdotdev/Warp#740]
### Describe the bug

```shell
The "Re-input as Root" option when right-clicking a block is missing in the latest version of Warp.
```

### To Reproduce

Steps to reproduce:
1. Type any command into the prompt (valid or invalid) and enter it
2. Right-click on the block.
3. Reconsider life choices after seeing that you accidentally disabled the option in the context menu in a release... 🥲

### Expected behaviour

```shell
The "Re-input as Root" showing up in the right-click menu for blocks.
```

### Screenshots

<img width="1136" alt="Screen Shot 2022-02-10 at 8 18 41" src="https://user-images.githubusercontent.com/17903236/153349372-af3cba9e-48af-4203-ac2a-91c83fb940f5.png">

### Operating System

MacOS

### OS Version

macOS 12.1 (21C52)

### Additional context

```shell
All jokes aside, this project has changed the way I code and work on my projects for the better. I want to thank each and every one of the staff members and everyone who works on this phenomenal project!
```

**Comment by elviskahoro** [comment]
Hey @OmerFlame,

The team decided to remove this functionality because it was not being used much and the context menu has continually been growing and we'd like to keep it digest-able. We apologize for the inconvenience and thanks for the kind words and your feedback!

**Comment by OmerFlame** [comment]
Don't worry, this makes enough sense. While this was useful to me sometimes, I didn't actually use it much. I just thought this was accidental.
