### ISSUE TITLE
Short freeze after switching windows

### ISSUE THREAD

**Issue by artem-karpenko** [warpdotdev/Warp#741]
### Describe the bug

Each time that I switch to a different application after using Warp, if I spend enough time there  (I estimate it as 5 seconds or so) then after switching back to Warp it's kinda unresponsive for a second or so. It still captures input though because whatever I type will appear eventually in terminal.

### To Reproduce

1. Launch warp.
2. Switch to another application (any should do, I reproduced with Chrome, Notes and VSCode).
3. Wait for 5 seconds (does not seem to matter if you do anything in that app or not).
4. Switch back and start typing.
5. Observe: cursor is not blinking and symbols that you type do not appear.

### Expected behaviour

Typing results in symbols to appear in Warp input  field.
Instead, symbols do not appear for about 1 second after a switch.

### Operating System

MacOS

### OS Version

12.1

### Additional context

Warp version v0.2022.01.31.09.03.stable_00

**Comment by seanhogge** [comment]
I also experience this issue:

Mac 12.3.1

Warp 0.2022.04.11.09.09stable_02

**Comment by RyanMcDonald** [comment]
This is still happening to me.

Mac OS 12.4
Warp 0.2022.07.04.09.08.stable_02

**Comment by artem-karpenko** [comment]
It does not seem to be happening to me anymore.

**Comment by vorporeal** [comment]
Going to close this out for now; please re-open if you're still seeing this!
