### ISSUE TITLE
DUP: Duplicate of #149 - auto suggestion is not so "fuzzing"

### ISSUE THREAD

**Issue by AielloChan** [warpdotdev/Warp#748]
### Describe the bug

```shell
I had two records in my history, say "ssh aiellos-macmini.local" and "macmini.aaa.com", and when I type "ssh macmini", I hope these two history will be mached. But now just "macmini.aaa.com" come out in suggest list.
```

### To Reproduce

Steps to reproduce:
1. type "ssh aiellos-macmini.local", and ignore errors
2. type "ssh macmini.aaa.com" and also ignore errors
3. then type "ssh macmini", you will see just "ssh macmini.aaa.com" in suggest list

### Expected behaviour

```shell
when I type "ssh macmini", suggest list will show both "ssh aiellos-macmini.local" and "ssh macmini.aaa.com", thats fuzzing.
```

### Screenshots

record already exist:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/7900765/153746976-7db4a780-ad2e-44e1-98d0-fcfbf2e30ed6.png">

but haven't been matched
<img width="399" alt="image" src="https://user-images.githubusercontent.com/7900765/153747229-b2f24fd3-fb53-4eb8-9b50-f900e441aa66.png">

### Operating System

MacOS

### OS Version

Monterey 12.3 Beta

**Comment by AielloChan** [comment]
I got it! When I keep suggest window open and keep type, its fuzzing. But when I keep suggest window close then type, its not fuzzing!

https://user-images.githubusercontent.com/7900765/153748885-ad6d0b83-0089-4490-b066-c70da3758fcf.mov

**Comment by elviskahoro** [comment]
Duplicate of #149 gonna close!
