### ISSUE TITLE
Theming: Emojis not rendering in Warp

### ISSUE THREAD

**Issue by dantereve** [warpdotdev/warp#75]
**Describe the bug**
I often use emojis to locate things I want to log in to the terminal much faster (and please my eyes as an emoji lover).
But those little fellas don't appear in Warp. 

**To Reproduce**
1. Create a `console.log('😱 <- You want some magic? I'm going to disappear in Warp').`
2. Look at the log in to your terminal and see that ... you can't see the emoji.

**Expected behavior**
Being able to see any emoji in the terminal.

**Screenshots**
<img width="847" alt="CleanShot 2021-07-28 at 08 47 36@2x" src="https://user-images.githubusercontent.com/13101343/127277892-d2030f24-b7f2-4dd6-88f7-5316ce3345de.png">
<img width="418" alt="CleanShot 2021-07-28 at 08 47 52@2x" src="https://user-images.githubusercontent.com/13101343/127277902-eca36c86-632e-40dd-8eec-8e82473398ab.png">
<img width="1165" alt="CleanShot 2021-07-28 at 08 46 09@2x" src="https://user-images.githubusercontent.com/13101343/127277906-a117cd13-5e47-4fdc-ba03-8595efd567ad.png">

**Desktop (please complete the following information):**
 - OS Version:  macOS 11.5
 - Warp version : <img width="300" alt="CleanShot 2021-07-28 at 09 03 48@2x" src="https://user-images.githubusercontent.com/13101343/127278855-52ea81a3-0649-4068-a98b-7a270c277810.png">

**Additional context**
It makes console display quite dull. Here is another example with `yarn`
<img width="291" alt="CleanShot 2021-07-28 at 08 56 55@2x" src="https://user-images.githubusercontent.com/13101343/127278068-88999501-50bf-4777-88f3-a1a4099718fa.png">

**Comment by zheng** [comment]
Agree that we should support this, thanks for reporting!

**Comment by lucasuyezu** [comment]
Just adding another report, this is what I see on Alacritty:

<img width="127" alt="Screen Shot 2021-08-13 at 18 17 17" src="https://user-images.githubusercontent.com/26002/129423333-9f5d2372-31a4-4b2b-9b9b-9d8f11ca0deb.png">

And this is the same output on Warp:

<img width="216" alt="Screen Shot 2021-08-13 at 18 17 43" src="https://user-images.githubusercontent.com/26002/129423362-0ce06152-a881-41d0-8d9a-e4435e6d0504.png">

**Comment by elviskahoro** [comment]
v0.2021.11.23.17.55.stable_01 - Should be fixed. Please comment and reopen if it something went wrong!
