### ISSUE TITLE
minikube service <service-name> not respond back

### ISSUE THREAD

**Issue by l2D** [warpdotdev/Warp#751]
### Describe the bug

```shell
I follow this [repository](https://gitlab.com/nanuchi/k8s-in-1-hour) 

After I run the command `minikube server <service-name>`, Minikube does not respond back in Warp. (I tested on iTerm2, minikube response back)
```

### To Reproduce

Steps to reproduce:
1. Run `minikube` and deploy configuration files on above repository
2. Run command `minikube server webapp-service`
3. See the bug.

### Expected behaviour

```shell
- Warp terminal responds back the result of `minikube service webapp-service`
```

### Screenshots

![_2022-02-16_09-51-19_JLbT63C1](https://user-images.githubusercontent.com/20911264/154187270-5ecb7fa7-af2b-4ddc-8714-439655cdfffd.png)

### Operating System

MacOS

### OS Version

12.2.1 (21D62)

**Comment by elviskahoro** [comment]
Gonna move this to be near our other requests for kubectx! Thanks for sharing repro instructions:
- #652
