### ISSUE TITLE
Git Tower Doesn't Support Warp

### ISSUE THREAD

**Issue by fishcharlie** [warpdotdev/Warp#753]
### Describe the solution you'd like?

```shell
https://www.git-tower.com/mac to support Warp.
```

### Is your feature request related to a problem? Please describe.

```shell
I use Git Tower as a GUI for Git actions. But there is no way to set Warp as my Terminal application within Git Tower.
```

### Additional context

<img width="740" alt="Screen Shot 2022-02-16 at 5 36 09 PM" src="https://user-images.githubusercontent.com/860375/154381467-5d297b2e-ffbe-4aa7-b9d8-06657c828d75.png">

^ the only option is Terminal.

**Comment by elviskahoro** [comment]
Thanks for opening will update you when this is a work in progress!

**Comment by xmannv** [comment]
The feature that I love the most is "Open in Iterm" when I clicked on a directory. Can Warp have that feature or another way to add it?

**Comment by muescha** [comment]
@xmannv i think this need a different implementation - i guess its better to make an own issue for your feature request

**Comment by s-Bzz** [comment]
Ability to make Warp the default terminal can we be able to see that in the near future update of Warp?

**Comment by dannyneira** [comment]
This feature request is something we're investigating with no official ETA, but stay tuned for more updates on this thread.

**Comment by LucasEThomas** [comment]
I do react-native development. React-native will automatically open a new terminal window when it spins up a new metro instance. It always does so in mac's default terminal instead of a new warp tab. This is a minor annoyance.

**Comment by dannyneira** [comment]
From Discord user comment: They would like the option to set Warp as default terminal, like with iterm

![image](https://user-images.githubusercontent.com/16809145/235261980-cf33bb3c-70fe-4096-a7cc-1a0ce95e043c.png)

**Comment by marco-introini** [comment]
Any update on this?

**Comment by prom3theu5** [comment]
Aye, as shown above iTerm2 can do that
The source for how its done in that is here: https://github.com/gnachman/iTerm2/blob/master/sources/iTermLaunchServices.m#L241

**Comment by PnsDev** [comment]
Bump, any update?

**Comment by vanloc1808** [comment]
Hi, any update on this?

**Comment by Crashtor** [comment]
> I do react-native development. React-native will automatically open a new terminal window when it spins up a new metro instance. It always does so in mac's default terminal instead of a new warp tab. This is a minor annoyance.

Did you find any workaround? For me it's a major annoyance 😕

**Comment by JD10NN3** [comment]
Any update on that ?

**Comment by werneric** [comment]
I'd like to express my interest in having Warp as the default terminal throughout the system. E.g. "Open in Terminal" option on a directory, or Warp opening when clicking "Open in external terminal" in a Docker container when set to "System default".

**Comment by MayaqqDev** [comment]
Ive created a quick workaround how to make it default, it is mildly ugly because I am not experienced in objective C and such, but should get the job done.
### How to: 
- create a objective-C file (.m file extention) with this code in it https://gist.github.com/MayaqqDev/ed382d5b5a1d5797460ed8a1aedb36a0
- run `clang -framework Foundation -framework CoreServices -o SetDefaultTerminal <path to your .m file> && ./SetDefaultTerminal` in the command line
- Restart if it still doesn't work.

This has worked for me, because I have virtually 0 experience in this kind of stuff it might be an overcomplicated mess but it does get the job done, I used the code from [iTerm2](https://github.com/gnachman/iTerm2/blob/master/sources/iTermLaunchServices.m#L241) as a base.

If you know how to improve this, tell me, but I think this is generally good enough.

**Comment by Nearbe** [comment]
Hi! Any updates&

**Comment by jayrcodes** [comment]
Any updates?

**Comment by dannyneira** [comment]
Sorry no update at this time, but please keep adding 👍  to the topline issue, the more there are, the higher the chance of this getting prioritized in the next cycle.

**Comment by Shock9616** [comment]
Just commenting to express my interest as well. I would love to be able to use Warp+Neovim as my default code editor but so far that isn't possible

**Comment by oscaromsn** [comment]
and the update?

**Comment by Shasikhan** [comment]
Love to see this feature in warp app. Already loving warp so much.

**Comment by unhingedpanda** [comment]
commenting so it happens

**Comment by Nasfame** [comment]
+1

**Comment by diegocuehdz** [comment]
I am very interested in this

**Comment by semenovfilipp** [comment]
Can I use Warp as terminal from IDE (Intelije IDEA)?
If it does , so how I can do it?

**Comment by Nasfame** [comment]
@semenovfilipp i tried the same. What are u setting for Native terminal COnfiguration: `/Applications/Warp.app/Contents/MacOS/stable`? When i click the terminal icon, its just redirecting me to the warp window

**Comment by divyanshgandhilm** [comment]
Interested in this as well, commenting to express the same.

**Comment by octoxan** [comment]
Damn, I really need this.

**Comment by RLEE0731** [comment]
Would be very helpful to have this

**Comment by ctkcoding** [comment]
Would love to have the option to set warp as default terminal!

**Comment by carlosen14** [comment]
bump

**Comment by stivens13** [comment]
bump

**Comment by fishcharlie** [comment]
Please **stop** commenting things like _bump_. It adds zero value to the conversation and just spams people's emails.

I'm specifically following this issue so that I can receive official updates from the Warp team. Everything else is just noise that adds zero value.

If you want to express interest in this issue please consider adding a 👍 reaction to the original post. There is absolutely no need to comment to express interest.

And PS to the Warp team: Please consider locking this issue. Issues that have no valuable discussion should be locked to prevent further spam.

**Comment by arb000r** [comment]
> Please **stop** commenting things like _bump_. It adds zero value to the conversation and just spams people's emails.
> 
> I'm specifically following this issue so that I can receive official updates from the Warp team. Everything else is just noise that adds zero value.
> 
> If you want to express interest in this issue please consider adding a 👍 reaction to the original post. There is absolutely no need to comment to express interest.
> 
> And PS to the Warp team: Please consider locking this issue. Issues that have no valuable discussion should be locked to prevent further spam.

bump

**Comment by dannyneira** [comment]
Hi Folks, we'll be locking down this issue to prevent spam. Although you will no longer be able to 👍 this issue to show support, we have noticed over 100 👍 's on this request.

To be transparent, this is currently not on the roadmap and as such there is no ETA for the launch of this feature. That said, we will post any updates on this thread if/when it's being worked.
