### ISSUE TITLE
Emoji branch names break the prompt

### ISSUE THREAD

**Issue by yvt** [warpdotdev/Warp#754]
### Describe the bug

```shell
Branch names including certain emojis make the prompt disappear
partially or completely and/or cause the loss of advanced editing
functionality.

The ones that make disappear the prompt completely are even more 
problematic after session restoration: The input line disappears
completely, making it necessary to switch to a "safe" branch name
to  make the terminal tab usable again.
```

### To Reproduce

Steps to reproduce:
1. `git init; git commit --allow-empty --allow-empty-message -m ''`
<img width="163" alt="Screen Shot 2022-02-17 at 20 11 11" src="https://user-images.githubusercontent.com/5253988/154470833-6646d6e0-3186-453e-a3cc-6a4e3fdcf668.png">

2. `git checkout -b 🦆`
3. Observe the unexpected disappearance of the work tree status:
<img width="197" alt="Screen Shot 2022-02-17 at 20 12 15" src="https://user-images.githubusercontent.com/5253988/154470898-cc47722c-cfb0-4207-972f-6848da5ceecd.png">

-----------------

4. `git checkout -b ✨`
5. Observe the vanishing of the fancy prompt and the loss of advanced (GUI-esque) editing functionality:
<img width="169" alt="Screen Shot 2022-02-17 at 20 11 43" src="https://user-images.githubusercontent.com/5253988/154471052-d34a7454-fe70-49b0-8a62-7739d7ece7dd.png">

### Expected behaviour

```shell
Branch names like `🦆` and `✨` should behave exactly the same
as `main`.
```

### Operating System

MacOS

### OS Version

12.2

### Additional context

```shell
Version: v0.2022.02.14.08.44.stable_01
```

**Comment by yvt** [comment]
After some experiments, I suspect that the presence of the byte `0x9c` is problematic:

| ``git checkout -b `printf 'XXXX'` `` | Result |
| ----- | ----- |
| `\x30` | OK |
| `\xc2\x80` | No work tree status |
| `\xc7\x9c` | No prompt | 
| `\xc7\x9d` | No work tree status | 
| `\xe2\x9c\xa8` (`✨`) | No prompt |
| `\xee\x90\x9b` | No work tree status |
| `\xee\x90\x9c` | No prompt |
| `\xee\x90\x9d` | No work tree status |
| `\xf0\xa9\x80\x9c` | No prompt | 
| `\xf0\xa9\x80\x80` | No work tree status |

**Comment by elviskahoro** [comment]
This was fixed. Apologies for the delay!
