### ISSUE TITLE
CMD-F Opening search should select previous text

### ISSUE THREAD

**Issue by Nitive** [warpdotdev/Warp#759]
### Describe the solution you'd like?

When you open search via Cmd+F and start typing text adds to the end of previous search. But you almost always want to delete previous text and write new one. In most applications previous text is selected by default so you could start typing right away. And if you want to modify previous search somehow, you can do it too since it's not deleted, just selected

### Additional context

<details>

<summary>Applications that select previous search by default</summary>

Brave browser
<img width="397" alt="image" src="https://user-images.githubusercontent.com/6770225/154626254-ce6f9136-44cc-4f32-8a3f-57ea9acf1d9d.png">

Sublime Text
<img width="304" alt="image" src="https://user-images.githubusercontent.com/6770225/154626288-70086b23-58dd-45ea-95e2-5a5973909521.png">

VSCode
<img width="385" alt="image" src="https://user-images.githubusercontent.com/6770225/154626543-ff67bf24-ed3d-4ece-9b21-87ac03ca9684.png">

</details>

**Comment by elviskahoro** [comment]
From ZachDaniel via Discord
https://discord.com/channels/851854972600451112/851854972600451115/949862721887809546

https://user-images.githubusercontent.com/29553206/157169821-020dfe68-b4ee-4bf4-8430-931d4da6cd5f.mov

**Comment by daemontus** [comment]
I would maybe also add that pressing `cmd+F` should also re-run the search query on the new content?

That is:
1. Open fresh session.
2. `Cmd+F`, type `hello`, zero results found.
3. Execute `echo hello`. 
4. At this point, the search is showing zero results... I guess this is expected.
5. `Cmd+F` ⇒ now the search should be refreshed and show the new result.

**Comment by elviskahoro** [comment]
This was fixed! Apologies for the delay.
