### ISSUE TITLE
Battery - Warp forces use of the discrete GPU on dual-GPU Macbooks

### ISSUE THREAD

**Issue by trishume** [warpdotdev/Warp#76]
**Describe the bug**
On dual-GPU macbooks Warp forces use of the high-power GPU, which reduces battery life even when Warp isn't being used.

**To Reproduce**
Open Warp, look in Activity Monitor under the Energy tab and see "Yes" under the "Graphics Card" tab (tooltip "Requires high performance GPU") for Warp. Or use iStat Menus to notice it like I did.

**Expected behavior**
Use the Metal APIs to allow the low power adapter instead, the high performance GPU isn't required to use Metal.

**Desktop (please complete the following information):**
 - OS Version: macOS 10.15.6

**Additional context**

It also re-renders the whole window for cursor blinking even when in the background, as visible using Quartz Debug flash on change, also wasting power.

**Comment by zheng** [comment]
Thanks for filing, we will take a look at this!

**Comment by ccpost** [comment]
I've been noticing this too through [iStat Menus](https://bjango.com/mac/istatmenus/). On a 16" MBP with a fair amount of CPU-hungry background junk open (Chrome / Slack / Discord / Superhuman / etc) I idle at about 20W system power. Opening Warp activates the Radeon GPU and takes it up to about 25W idling (25% more).

Anyone who happens to be benchmarking: https://github.com/dkorunic/iSMC also works pretty well for pulling power stats.

**Comment by ccpost** [comment]
@zheng Have y'all had a chance to figure out if this is easy or hard at least?

Having the discrete GPU active shaves off about 20-25% of my on-battery time with Warp just idle in the background. I end up quitting it and losing state to save battery on the go, so it's becoming my most-major blocker for using Warp for everything.

**Comment by kevinyang372** [comment]
@ccpost Apologies for the issue! Discrete GPU is currently necessary for ensuring our rendering performance. We are currently exploring options to make this configurable or switching to only use discrete GPU when user's laptop is plugged in to power

**Comment by rodrigotrombeta** [comment]
Dear @trishume  ,
I have missed this thread and I've opened a similar one:
https://github.com/warpdotdev/Warp/issues/2114

**I could make warp use the integrated GPU by the steps I've provided in my thread.** Please take a look and see if it helps.

Once I've forced MacBook 16 to stop using the external GPU the power consumption of the GPU is now back to very low numbers.

Differently from you I was using the Load Average and the temperature to monitor the increases (of both) after start warp.

**Comment by eberkund** [comment]
Hi, @rodrigotrombeta how did you force Warp to stop using the external GPU? My laptop becomes too hot to comfortably use when I have Warp open, I have switched back to iTerm for now but if there is a work around by applying certain settings maybe I can go back to using it. I don't remember having this issue with earlier versions of Warp.

**Comment by cbpmckinney** [comment]
I've run into this issue with other apps (e.g. PaperCut for managing printing budgets).  In the case of that app, I was able to add a line to the info.plist file: NSSupportsAutomaticGraphicsSwitching to True, and it allowed the app to use the iGPU instead of the dGPU.  I just tried the same with Warp and unfortunately Warp crashes immediately upon execution with that new line added.  It's possible Apple has changed the tag or I screwed something else up (it's late), but worth looking into on the dev side.  

I absolutely love Warp and having it use iGPU instead of dGPU would make it even more awesome.

**Comment by bboysnick5** [comment]
For me it's a must have feature as my mac ages and the battery cannot last for 1 hour given my daily workload with discrete GPU on all the time.

**Comment by gkrawiec** [comment]
For the past 3 weeks I've had a battery and noisy fan issue on my MBP16 2019. I spent hours debugging it. Unfortunately, I had just upgraded macOS and also firefox....and extensions update automatically, so I couldn't concentrate on anything specifically.. Hours and hours wasted trying to figure this out. disabling extensions, reinstalling firefox, etc. Nothing worked. Today I realized it's warp terminal that forces the discreet gpu to stay on. This requirement is weird. Uninstalled warp for the time being. Hopefully you guys can solve the issue of displaying text without taking 30% off my battery. Will follow this bug and try the app again when this issue is fixed.

**Comment by champo** [comment]
Hi warp team, is there any intention of fixing this? This is a really severe issue for those of us with a discrete GPU. My battery life is in the 3 hours range with Warp open. All macbooks without discrete GPUs run Warp just fine, I'm not sure why it's needed on macbooks that do have a discrete GPU.

**Comment by vorporeal** [comment]
Hey!  Yes, this is high up on our list of priorities; we'll tackle it soon (next few weeks).  We appreciate your patience; we've got a small team and a lot to get done. :)

**Comment by Thecentury** [comment]
I've managed to make Warp use an integrated GPU only using the https://codyschrank.github.io/gSwitch/ tool. It's not super convenient, but at least I can continue to use Warp and not turn my laptop into a heater :)

**Comment by antonurankar-moloco** [comment]
I can switch to using integrated GPU on Macbook Pro 2018 using the gSwitch app, but then the performance of just scrolling is abysmal. 
@vorporeal when do you plan to release a build for us to try that improves this?

**Comment by pauloavelar** [comment]
> Hey! Yes, this is high up on our list of priorities; we'll tackle it soon (next few weeks). We appreciate your patience; we've got a small team and a lot to get done. :)

Hey @vorporeal. Any update on this issue? I don't mean to rush the team or anything, but it has become a problem and would not like to switch to another terminal temporarily if the fix is coming soon.

**Comment by avdept** [comment]
Unfortunately I had to stop using app until its resolved. My laptop literally cannot last more than 1.5-2 hours using warp. Opted out to good ol' iterm2

**Comment by gkrawiec** [comment]
> Hey Folks, We apologize for any delays in releasing this fix. There is no immediate update or eta at this time.
> 
> As a workaround, you can try using [gSwitch](https://codyschrank.github.io/gSwitch/) or [the command](https://github.com/warpdotdev/Warp/issues/76#issuecomment-1397309917) suggested above so you can set the integrated GPU as primary and that should help for the time being.

this suggested fix doesn't work if you have an external monitors attached as then the GPU is activated regardless of gSwitch or that command.

It's been 2 years, this likely won't be fixed.

**Comment by stanft** [comment]
> this suggested fix doesn't work if you have an external monitors attached as then the GPU is activated regardless of gSwitch or that command.
> 
> It's been 2 years, this likely won't be fixed.

If you have an external monitor attached the DGPU is activated automatically as Intel-based MacBooks can talk to external displays via DGPU only. This has nothing to do with Warp.

**Comment by zachbai** [comment]
Hey all, thanks for your patience on this. I'm actively working on implementing a toggle in app settings to prefer rendering with the integrated GPU on dual GPU machines. No hard timeline but it should be relatively soon, ideally within the next couple of weeks. Will follow up on the thread with updates

**Comment by stanft** [comment]
I just discovered the new "low power GPU" setting in the current Warp release - great!! Many thanks!

**Comment by dcaravana** [comment]
> I just discovered the new "low power GPU" setting in the current Warp release - great!! Many thanks!

Yep, Warp is not asking for the discrete GPU anymore! Well done and thanks!

<img width="329" alt="image" src="https://github.com/warpdotdev/Warp/assets/102935/0950a63d-078a-4035-8e46-6d708991f574">

**Comment by Thecentury** [comment]
Many thanks for adding the low-power GPU setting.

**Comment by cbpmckinney** [comment]
Awesome!  I'm so glad y'all were able to get this added.  I look forward to warping and having all the power Scotty can muster for other tasks :)

**Comment by dannyneira** [comment]
Hey folks, Warp has recently added support for MacOS using low-power GPU on dual GPU systems in `Settings > Features > Performance > Prefer rendering new windows with integrated GPU(low power)`. Please update to `v0.2023.10.10.08.06.stable_02`, please test and confirm if this has helped with the issue.

**Comment by dannyneira** [comment]
Closing as resolved, but please feel free to let us know of any issues.

**Comment by alexbchr** [comment]
> Hey folks, Warp has recently added support for MacOS using low-power GPU on dual GPU systems in `Settings > Features > Performance > Prefer rendering new windows with integrated GPU(low power)`. Please update to the latest, test and confirm if this has helped with the issue.

I feel like this switch should be turned on by default? It stopped my battery from draining and it basically made my Macbook silent again.

**Comment by mezuky04** [comment]
I also do not see the option, MBP 16" M4. Warp is making the laptop discharge very fast.
