### ISSUE TITLE
Hangs when opened in Rosetta mode on mac m1

### ISSUE THREAD

**Issue by ogoldberg** [warpdotdev/Warp#762]
### Describe the bug

```shell
I have an m1 and I tried to install the heroku cli, but it doesn't support m1 so you have to install it in Rosetta mode, but when I open warp in Rosetta mode it just hangs forever.
```

### To Reproduce

Steps to reproduce:
1. Use Apple Silicon
2. Right click on Warp icon
3. click 'Get info'
4. check 'Open using Rosetta'
5. open the app
6. it will hang

### Expected behaviour

```shell
I expect to be able to use the app in Rosetta mode.
```

### Operating System

MacOS

### OS Version

12.3 beta

**Comment by Hazer** [comment]
Just a suggestion, if instead of fully opening in Rosetta, if it could open TABs running in Rosetta mode, it would be amazing. Not sure if this is possible and it's what @ogoldberg wants tho, but I'd love it.

**Comment by gagata** [comment]
meanwhile, @ogoldberg are you still not able to run Warp in rosetta mode? we've tried reproing also on different os versions and were not able to do so - so wanted to check in

**Comment by ogoldberg** [comment]
Seems to work now. Thanks for checking in!
