### ISSUE TITLE
SSH wrapper does not pass exit codes

### ISSUE THREAD

**Issue by tomjn** [warpdotdev/Warp#763]
### Describe the bug

The `ssh` function warp registers passes the parameters along to either `command ssh` or the warp helper, but it does not return the favour and return the code value. This makes it difficult to determine the success or failure of an `ssh` command in some circumstances.

Instead of this:

```shell
ssh () {
	if [ $1 ]; then
		warp_ssh_helper "$@"
	else
		command ssh
	fi
}
```

It should be something similar to this:

```shell
ssh () {
    if [ $1 ]; then
        return warp_ssh_helper "$@"
    fi
    return command ssh
}
```

Likewise `warp_ssh_helper` does not return the exit code of `ssh`.

While this does not prevent `echo $?` from being used, it is still problematic, for example chained commands:

```sh
ssh slfjvnslkfvn; echo "yes"
```

This will report success in the prompt, despite the `ssh` command failing. The `ssh` error output is also not highlighted in red because of this.

### To Reproduce

Steps to reproduce:
1. Use `ssh` and attempt to directly evaluate the exit code rather than using `$?`

### Expected behaviour

```shell
When `ssh` returns a bad error code, so should Warps wrapper
```

### Screenshots

Notice how Warp only considers the command to have failed if the last command in the statement failed:

<img width="696" alt="Screenshot 2022-02-18 at 19 17 43" src="https://user-images.githubusercontent.com/58855/154747825-bfa53b4e-71b5-4477-b8c2-62b04eddbe1d.png">

Also notice how `ssh` only shows in red if it is the last command. Warp does not know if `ssh` succeeded or not, and it has no way of knowing this because the `ssh` function cannot surface the return code of the ssh command

### Operating System

MacOS

### OS Version

Monterey 12.2

### Additional context

```shell
There is no place to audit and debug all of these wrappers and helpers
```

**Comment by elviskahoro** [comment]
@tomjn Is this still happening to you? Trying to confirm whether we fixed it.

**Comment by tomjn** [comment]
Honestly after issues with ssh I turned off the wrapper then had to stop
using warp and forgot about it. I’d have to update and retest

**Comment by elviskahoro** [comment]
Gonna close since this should be fixed now!
