### ISSUE TITLE
Double Click Drag Text Doesn't Work / selecting text

### ISSUE THREAD

**Issue by fishcharlie** [warpdotdev/Warp#766]
### Describe the bug

```shell
When you double click on text in Warp and try to drag to select other text it doesn't work.
```

### To Reproduce

1. Type `cd Test-1.txt` into Warp
2. Double click on Test and try to drag to the right to select `Test-1.txt`

Notice that it only remains selected on `Test`, not `Test-1.txt`.

### Expected behaviour

```shell
It to have selected `Test-1.txt`.
```

### Screenshots

How about a video instead 😉. This shows the difference between Warp, and Terminal.app.

https://user-images.githubusercontent.com/860375/154816591-b857a221-21da-4b39-8171-b2c036679cd9.mp4

### Operating System

MacOS

### OS Version

12.3 Beta (21E5212f)

**Comment by elviskahoro** [comment]
Thanks for opening @fishcharlie will circle back when it's WIP

**Comment by warrenbhw** [comment]
@elviskahoro thanks to you and the team for this fix!!
One nitpick: when I double-click on whitespace, the selection should start at the whitespace, but instead it starts at the beginning of the word preceding the whitespace.

**Comment by warpdotdev-dx** [comment]
Just opened:
https://github.com/warpdotdev/Warp/issues/1949


Thanks ben
