### ISSUE TITLE
Autocomplete often gives bad suggestions

### ISSUE THREAD

**Issue by iantimmis** [warpdotdev/Warp#770]
### Describe the bug

Wasn't sure whether to consider this a bug report or feature request. 

Autocomplete often gives bad suggestions. For example, typing `cd ` will suggest recent commands starting with `cd ` rather than suggesting folders that are actually located in your current working directory. Similarly, if you type `cd m` it will suggest something like `cd my_directory_that_doesn't_live_in_this_folder` because of recency rather than suggesting folders within the working directory starting with M.

**Comment by elviskahoro** [comment]
See this milestone:
https://github.com/warpdotdev/Warp/milestone/3
