### ISSUE TITLE
<Meta> + . doesn't insert !$ into the current cursor position

### ISSUE THREAD

**Issue by ghuh** [warpdotdev/Warp#772]
### Describe the bug

```shell
In bash or zsh, typically you can type `<Meta> + .` to get the last item on the previous line to show up in the current cursor position.  It does nothing in Warp.
```

### To Reproduce

Steps to reproduce:
1. https://dev.to/irobertson/comment/e99a

### Operating System

MacOS

### OS Version

12.2.1

**Comment by elviskahoro** [comment]
Thanks for reporting. Have gotten multiple reports of this. will circle back once it's a work in progres

**Comment by lubokkanev** [comment]
Where can we +1 it, so it gets a higher priority?

**Comment by elviskahoro** [comment]
Will bump team and get back to you

**Comment by elviskahoro** [comment]
Gonna close this out then!
