### ISSUE TITLE
Can't use up/down when selected multiline command in history, escape clears the input

### ISSUE THREAD

**Issue by syabro** [warpdotdev/Warp#780]
### Describe the bug

```shell
I can't use up/down arrow if I selected multiline command in history
```

### To Reproduce

1. Execute command
    ```
    ping google.com
    ping github.com
    ```
2. Press up button to select previous command. 
    <img width="436" alt="image" src="https://user-images.githubusercontent.com/29029/155916002-b69a265b-19bc-44e3-8151-cd8e3a4f968c.png">
3. Press Esc to remove "history" menu to be able to use up/down arrows
4. See input cleared

### Operating System

MacOS

**Comment by elviskahoro** [comment]
This is essentially a design decision. I personally don't like it either tbh. The argument here is that you can use CTRL-R instead of UP in this case since CTRL-R is for command history search where as up is to rerun a command directly.

**Comment by tvuotila** [comment]
My workaround is to press, for example, space to start editing the command.
