### ISSUE TITLE
environment variable not found

### ISSUE THREAD

**Issue by chakravarthy-mm** [warpdotdev/Warp#784]
### Describe the bug

```shell
Whenever I run a command I see `environment variable not found` printed and I have to delete it and write new command
```

### To Reproduce

Steps to reproduce:

Run any command like `ls` or `cd` or any thing

### Screenshots

<img width="1020" alt="Screenshot 2022-03-02 at 12 02 20 PM" src="https://user-images.githubusercontent.com/84918911/156307962-7f51b66e-986b-4df0-9ec9-a9e74895d79f.png">

### Operating System

MacOS

**Comment by LeHyperion** [comment]
I am also having the same problem described above.

**Comment by anthonycastaneda** [comment]
Just installed, same issue.

**Comment by anthonycastaneda** [comment]
Figured it out, zsh config interferes with warp. Place ZDOTDIR=/ in .zshenv to load zsh without and configs.

**Comment by elviskahoro** [comment]
We're not compatible with Fig!
See docs:
https://docs.warp.dev/help/known-issues
