### ISSUE TITLE
All Terminal Sessions Opening on Initial Launch

### ISSUE THREAD

**Issue by awburgard** [warpdotdev/Warp#786]
### Describe the bug

```shell
After shutting down my machine for the night and re-starting in the morning, all terminal sessions I had opened, and closed, the previous day are opening in multiple terminal windows.
```

### To Reproduce

Steps to reproduce:
1. Open multiple terminal windows
2. Close those terminal windows
3. Shut down machine (or close out Warp -- i havent tried this)
4. Start machine, open Warp, multiple terminals open

### Expected behaviour

```shell
I would either expect an existing session to be re-opened OR a brand new session.
```

### Operating System

MacOS

### OS Version

Montery 12.1

**Comment by elviskahoro** [comment]
Can you send a video?
If you go to settings > features > Disable ("Restore windows, tabs, and panes on startup").
Does disabling the session restoration feature give you the functionality that you want?

**Comment by awburgard** [comment]
> Can you send a video? If you go to settings > features > Disable ("Restore windows, tabs, and panes on startup"). Does disabling the session restoration feature give you the functionality that you want?

@elviskahoro yeah, that was it. I still find it odd that it would open _every_ terminal session. I would expect just my last session to be brought back up  But maybe that's just me,
