### ISSUE TITLE
Doesn't respond keyboard input after latest update

### ISSUE THREAD

**Issue by ibigbug** [warpdotdev/Warp#787]
### Describe the bug

```shell
I installed Warp yesterday and it's been working well with my tmux setup.

After today update it doesn't respond any keyboard input now.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Operating System

MacOS

### OS Version

12.2.1

### Additional context

Edit: it does respond keys like `cmd + ,` to open the preference window. but any other input in the terminal doesn't work

**Comment by elviskahoro** [comment]
@ibigbug can you email me? elvis at warp dot dev
I'll send you a link to the prior version

**Comment by ibigbug** [comment]
thanks @elviskahoro, just emailed.

**Comment by ibigbug** [comment]
thanks @elviskahoro 

I downloaded the old version from the link in your email. however somehow it still doesn't work. not sure what could be the issue then. happy to wait for next release and try.

**Comment by elviskahoro** [comment]
@ibigbug can you send a video?

**Comment by ibigbug** [comment]
sure @elviskahoro 

I'm not sure how to record a video showing "keys not working" but I attached one 

https://user-images.githubusercontent.com/543405/159573189-26cbd3d7-f91d-491c-a7a4-5b24e77e2764.mov
