### ISSUE TITLE
Moving to #101 - Option to open the settings window from the menu bar

### ISSUE THREAD

**Issue by JoelCourtney** [warpdotdev/Warp#788]
### Describe the solution you'd like?

I would like it if under the "Warp" heading in the macOS menu bar (next to the apple symbol), there was a "Settings..." or "Preferences..." option that opened the settings window just like the "Cmd+," shortcut.

### Is your feature request related to a problem? Please describe.

This is a pretty standard design, so I didn't even think there was a settings window for a while. I found it on accident. (The option in the top-right drop-down menu seems obvious in retrospect, but I'm a religious mac user and I always expect the settings option to be somewhere in the menu bar.)

**Comment by elviskahoro** [comment]
Moving to:
- #101
