### ISSUE TITLE
Anti-aliasing issues on external monitor

### ISSUE THREAD

**Issue by madebysid** [warpdotdev/warp#79]
**Describe the bug**
I'm on a Macbook Pro (2019), and I'm noticing anti-aliasing issues when I open up Warp on my external monitor. The monitor in question is has a resolution of 3440x1400. I haven't seen any jagged edges with any of my other apps, so this may be Warp-specific. (I've attached screenshots below). I'm not sure if this matters but I usually use my monitor in clamshell mode: my Macbook is docked so the external monitor is the only screen I work on.
On my Macbook too, I see some jagged edges, but they're not nearly as noticable. (I believe it has a resolution of 2880x1800)

**To Reproduce**
Not relevant

**Expected behavior**

**Screenshots**

Case 1:
External monitor: (Notice the pixelation around the kebab menu on the top right)
![Screenshot 2021-07-29 at 21 05 07](https://user-images.githubusercontent.com/7689783/127576762-9a87cd80-cf06-4ee3-b928-120668200165.png)

MacBook monitor:
<img width="1136" alt="Screenshot 2021-07-30 at 01 07 28" src="https://user-images.githubusercontent.com/7689783/127576908-069d9b4b-4e73-4e87-ba70-2016e1e00225.png">

Case 2:
External Monitor: (Notice the pixelation around the Warp logo and type)
![Screenshot 2021-07-29 at 21 05 28](https://user-images.githubusercontent.com/7689783/127576834-6beea02e-99a4-4927-aa16-42e626097173.png)

MacBook monitor:
<img width="1023" alt="Screenshot 2021-07-30 at 01 07 46" src="https://user-images.githubusercontent.com/7689783/127576932-eb05a793-1762-4027-9d11-2914cf5801dd.png">

**Desktop (please complete the following information):**
 - OS Version: macOS 12.0 beta 3 (21A5284e)

**Additional context**
I'm not entirely sure what else would be relevant, so please ask!

**Comment by zheng** [comment]
Hey @madebysid, thanks for filing! I'm actively working on this icon rendering issue, and the fix should be available in next week's release.

**Comment by michlimlim** [comment]
We just released the fix for this today in `v0.2021.08.11.15.36.stable_00`
