### ISSUE TITLE
Fonts not as crisp/clean in latest version, almost bold

### ISSUE THREAD

**Issue by jacobgraf** [warpdotdev/Warp#790]
### Describe the bug

```shell
On the latest version of Warp (https://cln.sh/Pz1vSG9tqqaM2qXkHV6S, also, should be able to select and copy/paste the version number in the app. Currently, you can't.) and the font (using Hack, but tried others too) is more jagged and bolder than it used to be. It used to be very crisp/clean, but something recently changed and now it's not as pretty as it used to be.
```

### Screenshots

https://cln.sh/5eKqzXyeX2OFQ8SKvAFo

### Operating System

MacOS

### OS Version

12.2.1

**Comment by amustafa** [comment]
Still an issue in v0.2022.03.07.08.51.stable_01.

On the left is kitty terminal and on the right is Warp. Both have the same font (FiraCode Nerd Font Mono)
![image](https://user-images.githubusercontent.com/178707/157744736-1c182b9c-3f1b-4629-b421-d1b40de8ec18.png)

**Comment by elviskahoro** [comment]
See here:
https://github.com/warpdotdev/Warp/milestone/1
