### ISSUE TITLE
DUP: #776 - Other MacOS apps don't seem to recognize the Warp window at all

### ISSUE THREAD

**Issue by djsavvy** [warpdotdev/Warp#794]
### Describe the bug

```shell
Rectangle is a macOS app that allows you to drag windows to sides to snap them to halves of the screen, etc. 

Contexts is basically a cmd+tab replacement. 

Neither of them seem to recognize the Warp window at all. Dragging it doesn't trigger the window-snapping behavior of Rectangle, and it doesn't show up in the Contexts menu. 

I've never seen this with any other app before. 

Unfortunately, Warp is pretty much unusable for me if I can't use Contexts to switch to it.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Operating System

MacOS

### OS Version

12.2.1

### Additional context

```shell
I'm happy to provide debug logs or any other information if I can.
```

**Comment by penance316** [comment]
Just to +1 that, I have the same/similar behaviour on MacOS. 
Using an app called "**easy move+resize**" normally allows me to move and resize the app windows underneath my mouse pointer.
The Warp terminal window seems to not work with this app at all. 
I suppose these issues are all related.
