### ISSUE TITLE
Magnet shortcuts stop working

### ISSUE THREAD

**Issue by norman784** [warpdotdev/Warp#795]
### Describe the bug

```shell
Before I was able to use [magnet](https://magnet.crowdcafe.com) to resize my warp window, now (I'm not sure if was the latest or one before) but it suddenly stop working, and for me is annoying because I use it a lot to move/resize all my windows around.
```

### To Reproduce

Steps to reproduce:
1. Install magnet
2. Select any app (that's not warp) and you would be able to use it
3. Select warp and if you go to the systray, click over magnet you will see that all shortcuts are disabled for warp.

### Operating System

MacOS

### OS Version

12.2

**Comment by elviskahoro** [comment]
DUP of:
- #776
