### ISSUE TITLE
Possibility to disable shortcuts

### ISSUE THREAD

**Issue by wesleylether** [warpdotdev/Warp#796]
## CMD + 0 resets the font to default settings of warp.

Maybe it is handy to have the ability to disable shortcuts within warp.
(Okay, I can set the shortcut to an incredible difficult shortcut to use.)

But I think it may be handy to disable some options in the shortcuts you do not want to use

**Comment by elviskahoro** [comment]
@wesleylether Thanks for submitting. Will let you know once it's a work in progress!

**Comment by elviskahoro** [comment]
Gonna merge this with #868
