### ISSUE TITLE
Visual representation of `clear` is odd - snackbar

### ISSUE THREAD

**Issue by kesne** [warpdotdev/Warp#8]
**Is your feature request related to a problem? Please describe.**
When I clear my terminal, I want it to be visually free from clutter. I completely understand why the current visualization of `clear` is the way that it is, it just feels a little wrong.

**Describe the solution you'd like**
I'm not completely sure, but the snackbar at the top feels odd.

![Screen Shot 2021-07-16 at 1 21 37 PM](https://user-images.githubusercontent.com/498479/126004489-68848d7f-84ab-4954-b405-58440629557f.png)

**Comment by donaldguy** [comment]
@kesne  As, I'm guessing, a fellow habitual-clearer- I'm curious if you have any feelings on my features ideas / opinions in 22 and 23

---

But as to your issue, I'd suggest a good option would be striping the scroll bar — something akin to how iTerm indicates search results in scrollback:

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/43136/126084588-5eb2a3ce-d6db-4914-a3b0-90424fb5a8bb.png">

(possibly hidden until scroll?)

It maintains the practical affordance of the current clear button (a place to click to jump back to scrollback just before the `clear`) while making it a (smaller) target more appropriate to the tendency to do that.

It also can then serve as a milepost in a long session, as `clear`s—if not habitual/compulsive— make sense to run when ~changing tasks, "starting something new"

One could imagine an even richer marker system like this that would let you run a command (possibly aliased with defaults to `clear`) to insert markers of different colors, with tooltips;

once can also imagine indications of this sort used to mark places in scrollback for e.g. `cd`s  out of an scm repo, ssh session starts and ends, starred/favorited commands, as well as - literally like iTerm, search results

**Comment by brunoanken** [comment]
I would love an option to not display this snackbar. I started using Warp today and I've found everything about it great, it's got a delightful UI and UX, the autocomplete is amazing but this snackbar annoys me in insanely high levels.

**Comment by lonnylundsten** [comment]
How about an option to turn off the snackbar? Some people won't want it at all, for any commands.

**Comment by puppycodes** [comment]
agree please please the snackbar is the only reason i don't use this...

**Comment by ryharrin** [comment]
I'd like to echo that this is the only part of Warp that has made me hesitate at all to make it my default terminal. 

I stared at the preferences page for a few minutes trying to find a way to disable it. 

If I want to go to the previous command with my mouse, I'll just scroll up.

**Comment by elviskahoro** [comment]
Gonna bring this back up to the team. Wish me luck!

**Comment by alokedesai** [comment]
Closing this out as this is now fixed. Please reopen if you're still experiencing issues here!

**Comment by elviskahoro** [comment]
Recently came out with an alternative to the snackbar called Sticky Command Header! There's some documentation on it here:
https://docs.warp.dev/features/blocks/sticky-command-header
