### ISSUE TITLE
Bad Powerline rendering with some fonts

### ISSUE THREAD

**Issue by NoaHimesaka1873** [warpdotdev/Warp#802]
### Describe the bug

```shell
Powerline glyphs are messed up with some fonts. Tested with Cascadia Code PL and NeoDGM Code.
```

### To Reproduce

Steps to reproduce:
1. Download [this font.](https://github.com/neodgm/neodgm/releases/tag/v1.530)
2. Use this font on Warp
3. PROFIT!

### Expected behaviour

```shell
Proper font rendering.
```

### Screenshots

<img width="1136" alt="Screenshot 2022-03-10 at 7 33 46 PM" src="https://user-images.githubusercontent.com/39993457/157644147-8d56164d-7d7e-4339-9537-bd3c1692daac.png">

### Operating System

MacOS

### OS Version

12.3

**Comment by byaruhaf** [comment]
+1

**Comment by oiwn** [comment]
Actually it's bad for anything except Hack font.

**Comment by harrisrobin** [comment]
Seems like im not the only one. Fire code NF also doesn't render nicely, I believe it's missing anti-aliasing: 
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/3880008/164993450-3ccfa156-d516-495c-a7d7-f68663d85b1f.png">
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/3880008/164993455-cf1b71e5-efad-4b91-b461-1232ba6c27f7.png">

**Comment by NoaHimesaka1873** [comment]
<img width="1491" alt="Screenshot 2022-04-29 at 5 52 34 PM" src="https://user-images.githubusercontent.com/39993457/165913741-1448d980-5eab-4392-a3e8-6a478f947aa8.png">
With the newest update it's better but it's still misaligned.

**Comment by Buzzraider** [comment]
Looks like there is also problem with ligatures, even tho I have font with ligatures when I use for example brew list there are normal ==> instead of ligature version.

Worth noted is that when I type ==> in promo it turns to ligature version no problem.

![image](https://user-images.githubusercontent.com/69143224/170559870-5d0629bb-8923-4a91-8ab7-ad2a9d425280.png)

**Comment by elviskahoro** [comment]
Thanks for opening! Will circle back on this one.

**Comment by elviskahoro** [comment]
We still don't have support for Font Ligatures, the issue for that is here:
https://github.com/warpdotdev/warp/issues/239

I think everything else has been resolved however and so gonna close this

**Comment by elviskahoro** [comment]
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">
