### ISSUE TITLE
Font selection and rendering

### ISSUE THREAD

**Issue by Patrik-svobodik** [warpdotdev/warp#81]
**Is your feature request related to a problem? Please describe.**
Currently the text rendering inside Warp doesn't seem to be at the native retina resolution (text doesn't look sharp) and I think it might be related to font rendering. I haven't found any way to change the font either and it's a bit disappointing (used to FiraCode)
<img width="1440" alt="Untitled 2" src="https://user-images.githubusercontent.com/25883885/127672490-26179797-f7a2-437c-baa2-203374fb65a6.png">

**Describe the solution you'd like**
A font selector be added and the rendering be improved

**Comment by zheng** [comment]
We're actively improving font rendering #11 and custom fonts will be available in a larger theming effort #9

**Comment by zheng** [comment]
Closing since this is a duplicate. Thanks for reporting!
