### ISSUE TITLE
Clickable links do not ignore trailing dots

### ISSUE THREAD

**Issue by P4sca1** [warpdotdev/Warp#811]
### Describe the bug

```text
Clickable links to HTTP URLs do not ignore trailing dots.
```

### To Reproduce

Paste the following into your terminal:
`echo "Visit https://github.com/warpdotdev/Warp/issues."`
Visit the link by clicking on it.

### Expected behaviour

```text
You should be redirected to https://github.com/warpdotdev/Warp/issues, but you are redirected to https://github.com/warpdotdev/Warp/issues. (notice the dot at the end).
```

### Operating System

MacOS

### OS Version

12.3

### Additional context

```text
Warp version: v0.2022.03.07.08.51.stable_01
```

**Comment by alejoar** [comment]
same with commas and single quotation marks ("," and "'")

**Comment by ramonfabrega** [comment]
same with any delimiter i believe

pretty problematic when console logging urls, as they print as strings and they mess the url 


<img width="250" alt="Screen Shot 2022-05-23 at 7 29 58 PM" src="https://user-images.githubusercontent.com/6278111/169925104-aa446870-5c36-492b-a0d4-723e0d093a1f.png">

`https://foo.com'`the last `'` is included in the url parsing

**Comment by elviskahoro** [comment]
Thanks for opening! This is pretty high priority. Will update yall when it's WIP

**Comment by chrisfromredfin** [comment]
Output from my `[ddev](https://ddev.com/) describe` that has a comma.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/278442/186240705-88fd0312-b813-44ab-b591-9f968b877168.png">

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!
