### ISSUE TITLE
DUP: #776 - Warp not working with alt-tab

### ISSUE THREAD

**Issue by jeffhu1** [warpdotdev/Warp#812]
### Describe the bug

```text
I use a macos app called alt tab that has never had any issues. However, with Warp the window doesn't appear properly. Not sure if this issue should be redirected to their repo but wanted to bring it up.

https://alt-tab-macos.netlify.app/
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

**Comment by elviskahoro** [comment]
DUP:
- #776

**Comment by vorporeal** [comment]
I think this may be different than the window management issues - the alt-tab application does see the Warp window, but is unable to render a preview.

@jeffhu1 Unclear to me why this is happening.  Would you mind opening an issue on their end?  It's probably the result of something we're doing but I don't have enough context on how they're grabbing their snapshot of the application window to debug effectively.

**Comment by vorporeal** [comment]
Update - I've more-or-less figured out what's wrong on our end, and am working on a fix.  No need to reach out to the alt-tab development team.  Should be fixed in next week's release. :)

**Comment by jeffhu1** [comment]
Awesome!! That's great to hear :)
