### ISSUE TITLE
An official way to disable the SSH wrapper helper via the settings

### ISSUE THREAD

**Issue by tomjn** [warpdotdev/Warp#821]
### Describe the solution you'd like?

```text
Your SSH helper is not ready for use, and telling people to run a command every single time they open a new terminal session so that they can have a reliable `ssh` command is a kludge.

Instead, put a checkbox in the settings, you can remove it once blocks in SSH sessions are working reliably again. You already do it for respecting PS1.

It took Apple years of iterations before they finally admitted to themselves butterfly keys don't work, don't do this with Warp. The SSH issues make it unusable, and I can see they're improving slowly, but what's the point when I can have a usable terminal if it was turned off?
```

### Is your feature request related to a problem? Please describe.

```text
See the SSH discussion thread, most if not all the items would be sidestepped by such a toggle
```

### Additional context

Don't make us suffer while you figure out something that might take months, `ssh` is mission critical tech not a fancy feature, you can't treat it as a blackbox that us users should just trust always work, especially not in the current stage of development. If I can't trust `ssh` to work why would I trust anything else in Warp?

I would happily accept no command blocks from SSH sessions if it meant I could use SSH sessions.

**Comment by elviskahoro** [comment]
Fixed with today's release: stable release 2022-03-24 (v0.2022.03.23.22.10.stable_01)
