### ISSUE TITLE
DUP: Duplicate of #776 - Incompatible with Magnet

### ISSUE THREAD

**Issue by adamshaylor** [warpdotdev/Warp#823]
### Describe the bug

```text
I use a window manager for macOS called Magnet. It uses accessibility permissions to resize the currently focused window to a preset (e.g. full screen, left half, right half, etc.) When I open Warp, all of Magnet’s resize options are disabled. It seems likely that other macOS window manager (e.g. Divvy) are incompatible too, but would appreciate some confirmation from others.

If memory serves, Warp used to be compatible with Magnet at some earlier point. The break happened roughly in the last 2–3 months.
```

### To Reproduce

Steps to reproduce:
1. Magnet must, unfortunately, be purchased from the App Store unless there’s some way to get a beta version from the developer.
2. Open Magnet. 
4. Open Warp.
5. Open the Magnet menu.

### Expected behaviour

```text
It should be possible to click on the resize options to resize the Warp window. Instead, the items are all grayed out.
```

### Screenshots

<img width="282" alt="Screen Shot 2022-03-21 at 11 12 30" src="https://user-images.githubusercontent.com/673870/159337466-3c29bd9d-f98b-408a-a31a-a14b8a5dd98a.png">

### Operating System

MacOS

### OS Version

12.3, 12.2.1

**Comment by apfelbox** [comment]
Same issue here. But I think the issue goes deeper, as Warp doesn't seem to use any of the official macOS window management.

That leads to Magnet not working, but also there is no list of active windows when right clicking Warp in the dock:

![Capture 2022-03-22_09-33-11](https://user-images.githubusercontent.com/1032411/159439688-8ea8fe65-758b-49cd-8117-0f87e6e00f66.png)

"Show all windows" also doesn't work for minimized windows. They are just gone.

**Comment by adamshaylor** [comment]
Just found an earlier ticket (#776) that covers basically the same thing. Sorry I didn’t see that sooner.
