### ISSUE TITLE
Accepting an autocomplete prompt from an early cursor position shifts the cursor excessively

### ISSUE THREAD

**Issue by mirichan** [warpdotdev/Warp#830]
### Describe the bug

```text
If you write a command, then take your cursor to the start of the line to change the executable and accept an autocomplete prompt in the process, the cursor gets shifted right twice as far as it should be, ending up in the middle of the following text.
```

### To Reproduce

Steps to reproduce:
1. Type a command: `cat ~/.ssh/id_rsa.pub`
2. Bring the cursor to the start of the line
3. Select `cat`
4. Type `le`
5. Tab-cycle to find `less` and press return to accept the prompt
6. See that the cursor is now located after the tilde

### Expected behaviour

```text
I would expect the cursor to be shifted either to the end of the completed word or one space following.
```

### Operating System

MacOS

### OS Version

12.2.1 (21D62)

**Comment by alokedesai** [comment]
Hey there, thanks for filling! I fixed this in our most recent release that will come out tomorrow morning. Will mark this as closed as soon as it rolls out
