### ISSUE TITLE
m1 mac can't sign in

### ISSUE THREAD

**Issue by xutong-space** [warpdotdev/Warp#832]
### Describe the bug

```text
after input the invite code and log in with Github, WRAP will load for a long time but not log in successfully.
My env is m1 macbook.
```

### Operating System

m1 MacBook macos Monterey 12.3

**Comment by elviskahoro** [comment]
Are you using a proxy?

**Comment by xutong-space** [comment]
Yes, I am in china mainland, I use proxy to speed up access to github.
I guess I found a solution to this issue.
thank you.


2022年3月23日 11:49，elvis kahoro ***@***.******@***.***>> 写道：



Are you using a proxy?

**Comment by cnscottluo** [comment]
> Yes, I am in china mainland, I use proxy to speed up access to github. I guess I found a solution to this issue. thank you.

how to resolve

**Comment by dev4joel** [comment]
I tried to fix it.🧐  https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/

**Comment by elviskahoro** [comment]
Gonna close this! Since it's the same as our proxy issue.
