### ISSUE TITLE
Neovim Screen Size Incorrect on Initial Window 

### ISSUE THREAD

**Issue by ja153903** [warpdotdev/Warp#836]
### Describe the bug

```text
Expect: Neovim window should span entire terminal on app start
Actual: Window size incorrect and must resize client to get neovim to span entire width
```

### To Reproduce

Steps to reproduce:
1. Open up Warp
2. Open up Neovim

### Screenshots

[Video of behavior](https://share.getbento.com/L1uRJODW)

### Operating System

MacOS

**Comment by wyc7758775** [comment]
same

**Comment by Theo-Steiner** [comment]
Opening the theme picker with cmd - s also triggers a resize that renders neovim with the correct width.
![warpe-neovim-render-bug](https://user-images.githubusercontent.com/40017636/166130823-7cdb374e-931f-48ab-a7d5-c8f009fecb7f.gif)

Btw, just to make hunting for the cause of this easier: this is not a regression but has been a problem for a while. Weird that this issue only came up now 😅

**Comment by wyc7758775** [comment]
> 

Below not full mode, drag window can also be solved.

**Comment by elviskahoro** [comment]
Thanks for opening! will circle back when it's a work in progress

**Comment by elviskahoro** [comment]
This has been fixed! If there any new bugs please let us know by opening a new issue!

**Comment by mathjiajia** [comment]
@elviskahoro, is the paddings of four sides on purpose (I changed to a white bg of warp so that you can see it clearly)
<img width="1667" alt="Screenshot 2023-01-14 at 9 38 19 AM" src="https://user-images.githubusercontent.com/35106942/212444809-204b1e3c-3355-46c4-a20d-ac9bc2cc12b5.png">

**Comment by mathjiajia** [comment]
> Yeah, it was an explicit design decision

Is it possible to make it configurable?

**Comment by elviskahoro** [comment]
It's not configurable. There isn't a workaround atm. Personally, I just set my Warp and Vim theme to both match.

**Comment by kamalkech** [comment]
@elviskahoro can u share with us how u customize this ?? thank u
