### ISSUE TITLE
Mutt color schemes aren't respected in Warp

### ISSUE THREAD

**Issue by ttunguz** [warpdotdev/Warp#837]
### Describe the bug

```text
- pick a standard color scheme in mutt
- pick a standard color scheme in warp
- compare mutt colors in Terminal.app and Warp; they will be different in unexpected ways
```

### To Reproduce

- pick a standard color scheme in mutt
- pick a standard color scheme in warp
- compare mutt colors in Terminal.app and Warp; they will be different in unexpected ways

### Expected behaviour

```text
The color scheme in mutt should reflect the .muttrc configuration
```

### Screenshots

<img width="1297" alt="Screen Shot 2022-03-24 at 11 29 58" src="https://user-images.githubusercontent.com/458598/159952249-f8dafac5-494c-487e-bec5-46868af86179.png">
<img width="1303" alt="Screen Shot 2022-03-24 at 11 28 40" src="https://user-images.githubusercontent.com/458598/159952251-41054bcc-3850-4644-aba5-b879530fbded.png">

### Operating System

MacOS

### OS Version

12.2.1

**Comment by elviskahoro** [comment]
Thanks for opening this. I think this is releated to the color contrast enforcement that we introduced

**Comment by elviskahoro** [comment]
Gonna move this to #362

**Comment by elviskahoro** [comment]
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">
