### ISSUE TITLE
Not rendering 256-color escapes from diff-so-fancy

### ISSUE THREAD

**Issue by ccpost** [warpdotdev/warp#84]
**Describe the bug**

**To Reproduce**
1. Install + configure [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) with their suggested `git` config including the "improved colors"
2. Run a `git diff` on something that shows sub-line diff color highlighting
3. Sub-line diff highlighting is missing on Warp but present on iTerm
4. Temporarily disable the pager and capture raw output for comparison: `git -c core.pager= diff | diff-so-fancy > fancy-diff.bin`
5. `cat fancy-diff.bin` on both iTerm and Warp to observe the difference

**Expected behavior**
The sub-line diff color highlighting (with the green / red background colors) to render on Warp.

**Screenshots**
iTerm:
![image](https://user-images.githubusercontent.com/55072/127766424-e48bbfa3-3742-48eb-a5d8-6a8c846134bc.png)
Warp:
![image](https://user-images.githubusercontent.com/55072/127766444-98ff0f53-a7a2-40c1-bf5b-5fe54239d7a4.png)

**Desktop (please complete the following information):**
 - OS Version: macOS 10.15.7

**Additional context**
Here's a file with the raw output including color escapes to repro:
[fancy-diff.bin.zip](https://github.com/warpdotdev/warp/files/6912439/fancy-diff.bin.zip)
(Sorry for the zip, GItHub seems to have limited file formats and I don't want the escapes to get lost if GitHub treated it as text.)

**Comment by ccpost** [comment]
Specifically, it seems like the [8-bit style](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit) sequences `48;5;52` and `48;5;22` to set the custom background colors are the only things not working.

**Comment by ccpost** [comment]
This test script for all 256 colors might be helpful: https://gist.github.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263

iTerm:
![image](https://user-images.githubusercontent.com/55072/127767095-b32adaab-0ae6-4f34-a1fd-41db4ac4281f.png)
Warp:
![image](https://user-images.githubusercontent.com/55072/127767111-69d49416-7c7d-4ec5-a0c9-db19802135e0.png)

**Comment by gagata** [comment]
hi! thanks for the extensive report! we're aware of the 256 colors issue, and I've started looking at this briefly already.

my personal interim solution (to my vim colors :) ) was to disable 256 colors setting (iirc enabling truecolors works just fine). not ideal, but maybe can help you while we get this sorted

**Comment by alokedesai** [comment]
This should be fixed on our latest release (`v0.2021.08.11.15.36.stable_00`) so marking as closed. Thank you for filing!
