### ISSUE TITLE
DUP: #776 - Warp window doesn't respont to Magnet window manager

### ISSUE THREAD

**Issue by webrgp** [warpdotdev/Warp#840]
### Describe the bug

```text
Not sure if it's related to Magnet or any window manager. Magnet used to work with Warp, but a few (Warp) updates ago, Magnet stopped being able to resize and place Warp window.

Here is Magnet App
https://magnet.crowdcafe.com

When Warp is selected, all Magnet options are disabled:
```

### Screenshots

<img width="1512" alt="Screen Shot 2022-03-25 at 9 32 27 AM" src="https://user-images.githubusercontent.com/994788/160121568-9f447ea6-6641-4b4a-aff4-c310b46ec29e.png">

### Operating System

MacOS

### OS Version

12.3

**Comment by elviskahoro** [comment]
Dup of:
- #776
