### ISSUE TITLE
Warp incorrectly loading symlinked bashrc

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#843]
> It seems to be using an old version of my .bashrc? Even after restarting, my bash variables are old values. After I run `. ~/.bashrc`, my variables update, but the prompt is messed up.

> Note: my .bashrc is a symlink.

—

Created via [Raycast](https://www.raycast.com?ref=signatureGithub)

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3xx58)

**Comment by lorensr** [comment]
Can be closed—somehow my bashrc got copied to bash_profile. I've replaced bash_profile with: 

```
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi 
```
