### ISSUE TITLE
ssh to remote machine produces warning

### ISSUE THREAD

**Issue by amirhosseindavoody** [warpdotdev/Warp#844]
### Describe the bug

```text
Every time that I ssh into my remote VM instance I get the following warning message:

rmdir: failed to remove 'warptmp.7QoNaN': Directory not empty
```
```


### To Reproduce

Use ssh command to connect to a remote machine.

### Expected behaviour

_No response_

### Screenshots

![image](https://user-images.githubusercontent.com/8355965/160450070-01330580-55d9-4113-a275-131d6b67678f.png)


### Operating System

MacOS

### OS Version

12.3

### Additional context

_No response_

**Comment by zheng** [comment]
Thanks for reporting. Our method for supporting Warp features over SSH creates a temporary folder that we theoretically clean up as part of the process. There seems to be a bug relating to the cleanup - we're looking into it!

**Comment by kamil-malinski** [comment]
> Thanks for reporting. Our method for supporting Warp features over SSH creates a temporary folder that we theoretically clean up as part of the process. There seems to be a bug relating to the cleanup - we're looking into it!

any news on that issue? it got so annoying to have all the tmp-folders scattered on my servers that I had to stop using warp :-(

**Comment by elviskahoro** [comment]
I'll bump the team and ask

**Comment by kamil-malinski** [comment]
> I'll bump the team and ask

with todays update the bug was fixed, thanks a lot!
