### ISSUE TITLE
PS1 with multiple lines is not shown correctly

### ISSUE THREAD

**Issue by mikrostew** [warpdotdev/Warp#845]
### Describe the bug

```text
For a `PS1` with multiple lines (using newline `\n`), Warp only shows the second line of the prompt.

This has also surfaced in the PS1 discussion: https://github.com/warpdotdev/Warp/discussions/422#discussioncomment-2234174
```

### To Reproduce

Steps to reproduce:
1. Setup a `.bashrc` containing `PS1="username\n$"`
2. In Warp, enable "Honor user's custom prompt (PS1) setting" in Settings > Features
3. Open a new tab, and see that the prompt only shows the `$`, and the username is not visible

### Expected behaviour

```text
Either
a) render multiline prompts on multiple lines, or
b) concatenate multiline prompts to a single line, stripping out the newlines
```

### Screenshots

In Warp:
<img width="178" alt="Screen Shot 2022-03-28 at 2 01 44 PM" src="https://user-images.githubusercontent.com/190129/160459051-59b0211c-88bd-4531-b595-8f8dbe8c30f9.png">

In iTerm2:
<img width="190" alt="Screen Shot 2022-03-28 at 2 01 24 PM" src="https://user-images.githubusercontent.com/190129/160459089-cd596895-5054-4641-b312-269b0bd37b46.png">

### Operating System

MacOS

### OS Version

12.3

### Additional context

```text
I have worked around this by checking `$TERM_PROGRAM`, and setting PS1 appropriately, since Warp already puts some spacing around the prompt (which is why I had newlines in there).
```

**Comment by elviskahoro** [comment]
Moved to:
- #765
