### ISSUE TITLE
Starship right prompt not functioning

### ISSUE THREAD

**Issue by KieranP** [warpdotdev/Warp#846]
### Describe the bug

```text
When I try to use starship right prompt setting, it doesn't display. Instead, Warp is adding a strange invisible character at the start of the second line.
```

### To Reproduce

Install starship and configure with:

```
format = "$directory$git_branch$git_metrics$git_status"
right_format = "$ruby$nodejs"
```

### Expected behaviour

```text
Ruby and Node info would be on the right side of the prompt
```

### Operating System

MacOS

### OS Version

12.3

**Comment by loremaps** [comment]
It worked for me when I enabled the ["Honor user's custom prompt (PS1) setting."](https://docs.warp.dev/features/prompt)

**Comment by elviskahoro** [comment]
Gonna merge this with #936
