### ISSUE TITLE
Fish - History searching

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#849]
From @[jrr](https://github.com/jrr) via #190 Comment: https://github.com/warpdotdev/Warp/issues/190#issuecomment-1078594251

Thanks for adding Fish support! I'm excited to combine my old favorite shell with my new favorite terminal. I noticed two things during the first ~hour with it:

### 1) History searching

Fish does this a little differently from most shells' Ctrl+R.

In Terminal.app, I can type a substring of a previous command, hit the up arrow, and recall the command. (for example, `conf` -> `vim ~/.config/fish/config.fish`)

In Warp:
 - I can type the _beginning_ substring of a command and hit the up arrow (like `v` for `vim ...`)
 - I can type an inner substring and hit Ctrl+R

This isn't super important to me -- I'm sure I'll get used to using Warp's history searching instead of fish's -- but it's definitely a speed bump.

### 2) Tab completion

I noticed this with homebrew. Fish seems to know more about homebrew's CLI than Warp does:
 - when I type `brew i<TAB>`, Fish presents several more options than Warp.
 - when I type `brew install fig<TAB>`, Fish completes based on the available packages in homebrew.

Here's an example:
[![asciicast](https://asciinema.org/a/480399.svg)](https://asciinema.org/a/480399)

Warp's completion knows about fewer brew subcommands, and doesn't offer completions for available packages.

Could Warp one day use Fish's smarts for these?

**Comment by eaganj** [comment]
A related use-case to this bug: `cd proj/per/web<tab>` should expand to `cd Projects/Perso/Web/` in fish, at least on a case-insensitive environment like macOS.  Warp breaks it.

I really dislike my terminal breaking my shell.

**Comment by elviskahoro** [comment]
Moving the tab completion to #652

**Comment by elviskahoro** [comment]
Gonna merge history searching with #149
