### ISSUE TITLE
Option to enable always-on completions dialog (without pressing tab button)

### ISSUE THREAD

**Issue by maximkrouk** [warpdotdev/warp#85]
I use [fig](https://fig.io) and iTerm and it's so convenient to navigate without pressing tab button. Even if you choose a directory using `cd` fig window is not closed and you may just navigate using arrows and the enter button until u reach the destination.

So I'd like to have the same autocomplete experience as I have using fig.

**Comment by elviskahoro** [comment]
@maximkrouk  Gonna merge this into:
- #192
