### ISSUE TITLE
Fish abbreviations don't expand until warp runs the command

### ISSUE THREAD

**Issue by taranlu-houzz** [warpdotdev/Warp#852]
### Describe the bug

```text
With `fish`, you can define abbreviations that expand after pressing `space` or `enter`. This allows you to have the convenience of aliases without forgetting what the underlaying commands actually are. In `fish`, this is expanded as you type, so an abbreviation could be a base or partial command that you then manually add to. Currently, the expansion of the abbreviation only happens after you press `enter` in `warp`, which hampers their use.
```

### To Reproduce

1. Start `fish`
2. `abbr -a -U -- gfa 'git fetch --all'`
3. Type `gfa` in `warp`, then press `space` (the abbreviation does not get expanded)
4. Press `enter` (the command is run, and the abbreviation is expanded)

### Expected behaviour

```text
I would expect abbreviations to be expanded as the user types.
```

### Operating System

MacOS

### OS Version

10.15.7

**Comment by elviskahoro** [comment]
It's still unclear what the team will do for this and also the ETA after flushing out the approach. Apologies that this is currently missing!

**Comment by andresespinosapc** [comment]
This feature is very important, I use it all the time to add parameters after aliases. For example doing something like `gco branch-name` for `git checkout branch-name`

**Comment by d12bb** [comment]
Also, they sometimes don't expand at all, seems to be the case mostly when parameters are added after the abbr like: 
<img width="284" alt="image" src="https://user-images.githubusercontent.com/16717303/163672420-bfe2a1d7-d900-4fb6-8ac1-0b14a4534cc4.png">

**Comment by shrugalic** [comment]
👍 I'm also missing this feature.

Just to reiterate, expansion _does_ work after enter, but **not** after space.

I have this abbreviation `gcb` to create a branch, so it expands to `git checkout -b`:
```sh
abbr --add --global -- gcb 'git checkout -b'
```

It expands without parameter (after typing enter), but this is useless:
```sh
 ~  ❯ git checkout -b
fatal: not a git repository (or any of the parent directories): .git
```

```sh
 ~  ❯ gcb my_new_branch
fish: Unknown command: gcb
```

**Comment by pat-s** [comment]
I just found out that if you reinit the config by running `fish` in a tab, the expansion with a parameter added works afterwards.

**Comment by iain** [comment]
@pat-s that seems to be because you are running plain `fish` inside Warp. This way Warp cannot use it special powers.

**Comment by orbiteleven** [comment]
> I just found out that if you reinit the config by running `fish` in a tab, the expansion with a parameter added works afterwards.

Yeah, while this "works" in that abbreviations/autocompletions work again, it kinda negates a bit purpose for using Warp in the first place.

For my part, it's more important that I can use something similar to https://github.com/jhillyerd/plugin-git on Warp than it is that my "old ways" work 100%, but I can't seem to find an analog in Warp.

**Comment by sullimander** [comment]
Any update on getting this fixed? Fish is basically broken without abbreviations working.

**Comment by rrajath** [comment]
I have the same issue. The abbreviation doesn't expand whether I hit space or enter. It keeps saying "Unknown command"

**Comment by ubmit** [comment]
Has anyone encountered a workaround to be able to use `jhillyerd/plugin-git` or something similar?

**Comment by zoomido** [comment]
Try starting another fish shell inside the first shell by just typing fish and <enter> and see if abbreviations start working and config is loaded.

**Comment by Gorthog** [comment]
One way to work around it and get some of the functionality is to add in fish config
```
alias gb="git branch -vv"
```

You will need to add it manually for each alias. It won't expand in real time but the correct command will be executed, and autocomplete of warp will detect it correctly.

**Comment by erykpiast** [comment]
Not sure if adding one more vote helps, but yes, I want this, too, badly! I just wasted an hour figuring out what I have misconfigured that it doesn't work (after months of patient ignorance) and just found out in this thread that it's Warp that doesn't support it as it is supposed :( Pretty please, add this feature 🙏

**Comment by james2doyle** [comment]
I've gone back to WezTerm for now until this is fixed. I didn't realize how
much I rely on abbreviations...

**Comment by nathanielmom** [comment]
This is a deal-breaker for me, as I use abbreviations regularly. Please address this. 🙏🏾

**Comment by dannyneira** [comment]
Hey Folks! this is being worked on and can be tracked on this feature request here: https://github.com/warpdotdev/Warp/issues/1895

Keeping the FR as it has more 👍 's. Closing as duplicate.

**Comment by ElijahLynn** [comment]
fwiw, abbreviations have been working for me out of the box. I first installed warp about a month ago, I think.

**Comment by shrugalic** [comment]
Yes, that issue has been solved for over 10 months now https://github.com/warpdotdev/Warp/issues/1895
