### ISSUE TITLE
`clear` command takes up a large amount of space in command history

### ISSUE THREAD

**Issue by taranlu-houzz** [warpdotdev/Warp#853]
### Describe the bug

```text
Probably not exactly a bug per se, but the `clear` blocks in the command history are full screens, which makes them take up a lot of unnecessary space. It would be nice if they could squished to a compact size to make scrolling through history blocks more reasonable.

Perhaps it would also be helpful to have a way to filter the blocks that show up in history so that the `clear` blocks do not show up at all?
```

### To Reproduce

1. Run `clear` several times, along with other commands.
2. Scroll through history.

### Operating System

MacOS

### OS Version

10.15.7

**Comment by dev4joel** [comment]
I think It's a feature. 🧐

**Comment by mandel-macaque** [comment]
Can't you achieve the same with the Command + K shootout? Ideally, Warp should pick up the clear command or Ctrl + L and execute the same action as Command + K.

**Comment by taranlu-houzz** [comment]
That command seems to actually clear the blocks. I just want to shift then off the screen to have a clear screen, but be able to scroll back to them if need be. That being said, `warp`'s whole concept of blocks is very different from normal terminal emulators. Thinking about it, I guess this doesn't really make sense when you have the prompt at the bottom of the screen (I am still not really sold on this...).

I guess what I actually want is a command to push all block off the screen without getting rid of them or adding a new block.

**Comment by elviskahoro** [comment]
CTRL-L does this. Kinda similar to clear. In terms of improving the current experience, are you expecting that only the most recent CTRL-L to take up space in the Block list? If you ran 10 CTRL-L's, not all 10 should be the size of the screen but just the most recent one?

**Comment by taranlu-houzz** [comment]
@elviskahoro I think the following would be preferable:
- `clear`/`ctrl+l` in the history is just a single line, not a full screen
- All consecutive, most recent `clear`/`ctrl+l` are merge into a single block (like you mentioned above).
