### ISSUE TITLE
When opening quake style terminal in fullscreen app

### ISSUE THREAD

**Issue by ideea** [warpdotdev/Warp#859]
### Describe the bug

```text
Either main desktop should be focused automatically to see terminal or it should be opened on top of fullscreen app.

Like in iterm.
```

### OS Version

12.3

**Comment by elviskahoro** [comment]
@ideea can you send a video of the desired behavior?

**Comment by ideea** [comment]
something like that.
https://monosnap.com/file/CvJdptdKjfHk0TWYYY2Zcs7V3ESXCm

**Comment by elviskahoro** [comment]
Gonna move this to #975 since some people have already upvoted that issue.
