### ISSUE TITLE
Configure desktop for Hotkey Window when using multiple monitors

### ISSUE THREAD

**Issue by smeier99** [warpdotdev/Warp#862]
### Describe the solution you'd like?

```text
I'd like to be able to configure and change which monitor the Hotkey Window appears on when hitting the shortcut.
```

### Is your feature request related to a problem? Please describe.

```text
I don't wanna have to search for my terminal when restarting it.
```

### Additional context

Currently, upon starting Warp, the Hotkey Window always appears on the monitor where I previously had an app/a window focused. So as far as I could tell, the only way I can control where the Hotkey Window will appear, is to focus some App on the desktop I want it to be and then starting Warp.

**Comment by xikxp1** [comment]
I would also like to suggest that quake mode window could be opened on current macos desktop. I use multiple desktops and quake mode in iterm allows to open overlay terminal without having to switch via mission control. Warp lacks that

**Comment by vorou** [comment]
> I would also like to suggest that quake mode window could be opened on current macos space

I'm also looking for that behavior, I wonder if we should create a separate ticket for that.

There's also one more issue that for me won't be relevant if the above behavior is implemented:

If you are in the full-screen app and you press Warp hotkey, it won't focus on the space where Warp is opened. So I have to first switch to that space manually and then hit the Warp hotkey.

**Comment by kevinyang372** [comment]
Configuring which display to show hotkey window should be supported by Warp already -- Feel free to open a new ticket for supporting Mac spaces so we could track it better!

**Comment by smeier99** [comment]
@kevinyang372 Where exactly would one be able to configure that? I'm on the latest version and can't find it anywhere in the settings.

**Comment by kevinyang372** [comment]
@smeier99 The setting for this is right next to pin position:
![image](https://user-images.githubusercontent.com/30107576/166984176-b2341ac7-e189-4f3a-bf54-6e9eaf577243.png)

**Comment by feedthejim** [comment]
This doesn't seem to respect the current active screen.

**Comment by simerlec** [comment]
as @feedthejim said, the setting either never worked or we have a regression. Can we reopen this issue?

**Comment by wesleylether** [comment]
@kevinyang372 I think this problem is still active on a mac os can you reopen this ticket

**Comment by kevinyang372** [comment]
@simerlec @wesleylether This feature works for me on the latest version of Warp -- please open a new ticket with detailed repro-steps and more details. Thanks!

**Comment by slavashvets** [comment]
The active feature screen is only respected if the second screen is not in full-screen mode. If the application is open in a window, it works, and Warp appears on the second (active) screen. However, if I expand it to full screen, it doesn't work

**Comment by wesleylether** [comment]
@kevinyang372 I am on the latest version of warp. But still the issue continues. I have to actively click on a screen to let warp open on that screen. But if I go with my mouse to another screen without clicking and use the hotkey, the window will not open on that screen. If you know [Raycast](https://www.raycast.com/), this program looks at the mouse position on the screens and not the active screen. That would be me preferred way this should work.

**Comment by d4mr** [comment]
+1, in my experience too this only works when the second screen application is not on full-screen mode.
