### ISSUE TITLE
Typo in workflow picker

### ISSUE THREAD

**Issue by HaydenBL** [warpdotdev/Warp#863]
### Describe the bug

```text
Under the homebrew section in the workflows search, the upgrade workflow says "Upgrade all installed Homebrew caksks"
```

### To Reproduce

Steps to reproduce:
1. Open workflow search
2. Go to "homebrew" section

### Expected behaviour

```text
Should say "Upgrade all installed Homebrew casks"
```

### Screenshots

<img width="263" alt="image" src="https://user-images.githubusercontent.com/5898102/161099837-3afe0095-5517-4a49-b52f-dd7beb89fb9e.png">

**Comment by elviskahoro** [comment]
Thanks for flagging! I just opened a PR for this!
