### ISSUE TITLE
Command + E split panel hotkey no longer working?

### ISSUE THREAD

**Issue by zcaceres** [warpdotdev/Warp#872]
### Describe the bug

```text
I can't split panels by pressing command + e anymore. This seems to have started after one of the last two updates.
```

### To Reproduce

Steps to reproduce:
1. Open a window.
2. Press command + e
3. Nothing happens.

### Expected behaviour

```text
I expect it to split the panel with a vertical line.
```

### Operating System

MacOS

### OS Version

12.3.1

**Comment by dev4joel** [comment]
I think you need this.🧐

![Screen Shot 2022-04-02 at 10 24 08](https://user-images.githubusercontent.com/58339060/161362068-79e0be2b-8e76-49a9-80f3-a9089708b879.png)

**Comment by elviskahoro** [comment]
@zcaceres We changed the default keybinding to CMD-D and SHIFT-CMD-D. Since a large number of people's muscle memory is from iterm2. We also didn't see much usage with multicursor selection which was CMD-D.

**Comment by zcaceres** [comment]
Thanks!
