### ISSUE TITLE
Man page and doc source

### ISSUE THREAD

**Issue by Kallyah** [warpdotdev/Warp#874]
### Describe the solution you'd like?

```text
a Man page and other syntaxes shortcuts to language related docs.
```

### Is your feature request related to a problem? Please describe.

```text
N/A
```

### Additional context

I'm used to consult the man page regularly to find parameters or just read them to better understand the language. I've get used to the terminal easy access, and since warp is so time saving, I would love to have at Warp too.

**Comment by elviskahoro** [comment]
@Kallyah Can you elaborate a bit more! How should this be surfaced in Warp?

We have an internal feature idea called X-Ray where you can hover of words and see descriptions based on docs/man pages/completions. Are you thinking something similar?

**Comment by elviskahoro** [comment]
Gonna close this since X-Ray is coming soon.

+ we launched [https://commands.dev](https://commands.dev)
