### ISSUE TITLE
Right click context menu panel shortcuts are wrong

### ISSUE THREAD

**Issue by norman784** [warpdotdev/Warp#877]
### Describe the bug

```text
When you right click and the context menu appears it says that the shortcut for split pane is CMD+E, while in the command palette says CMD+D
```

### To Reproduce

Right click to open the context menu

### Screenshots

![image](https://user-images.githubusercontent.com/204656/161513507-e413acd7-ec5d-4c0f-a280-a8f7525310c1.png)

![image](https://user-images.githubusercontent.com/204656/161513563-9d9a6e45-86d3-41c4-8f94-625423c644c6.png)

### Operating System

MacOS

### OS Version

12.3

**Comment by dev4joel** [comment]
It's a bug. WARP had changed the default keybinding to CMD-D and SHIFT-CMD-D. 
CMD-E and SHIFT-CMD-E are no longer working.

**Comment by dev4joel** [comment]
You can see it here --> https://github.com/warpdotdev/Warp/issues/872.
