### ISSUE TITLE
Can't type in fullscreen windows created with cmd-n

### ISSUE THREAD

**Issue by lucieleblanc** [warpdotdev/Warp#878]
### Describe the bug

```text
When Warp is in fullscreen, it is not possible to type into the input box of new windows created with cmd-n. 
```

### To Reproduce

Open Warp in full screen. 
Use cmd-n to create a new fullscreen window. 
The newly created window's input box can't be typed into.

### Expected behaviour

```text
It should be possible to type in the newly created window's input box.
```

### Operating System

MacOS

### OS Version

12.2

### Additional context

* Warp version `v0.2022.04.01.01.37.stable_02`. I believe this bug has existed for at least a few weeks, since I had observed it previously.
* The inability to type into the input box persists in the window when it is removed from fullscreen mode.
* Small windows later made fullscreen do not seem to be affected.

**Comment by elviskahoro** [comment]
@lucieleblanc Can you share a video? I'm having trouble reproducing this.

**Comment by lucieleblanc** [comment]
Here's a screen recording showing the following:
1. Warp is open, not full screen.
2. The window is made fullscreen.
3. A new window opened with `cmd-N` doesn't respond to any input except newlines. 

https://user-images.githubusercontent.com/14223323/162782427-8af0bd1b-b73b-43bd-ace4-940613842fad.mov

Additional notes not shown in the recording:
* `ctrl-R` opens command search, but it is not possible to type in the command search box. Using the enter key to select the most recent entry works.
* Using `cmd-V` to paste into the new window works.
* The backspace key works on content selected through command search, as well as content pasted from the clipboard.
