### ISSUE TITLE
SHIFT-CMD-T - Reopen recently closed tab, pane, or window like in chrome

### ISSUE THREAD

**Issue by gagata** [warpdotdev/Warp#88]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
basic solution:
being able to reopen the closed tab at the previous pwd as it was before closing

killer feature:
restoring entire session from the given tab, including the history of executed commands, blocks etc.

**Additional context**

**Comment by Lucas-Kohorst** [comment]
also seems like iterm2 has some form of implementation of the killer feature [https://iterm2.com/documentation-restoration.html](https://iterm2.com/documentation-restoration.html)

**Comment by gagata** [comment]
oh that's cool, thanks for the link! seems like they do this as an opt-in which makes a lot of sense

**Comment by elviskahoro** [comment]
Moving to #579 so all keybinding related issues are in one place:
- #579

**Comment by lukemt** [comment]
It should also be possible to reopen entire windows (like chrome)

**Comment by danvayn** [comment]
1.3k issues 💀 Still waiting for this feature

**Comment by elviskahoro** [comment]
This has been launched!

**Comment by wmendes-ionos** [comment]
Done for tabs not for panes. 👏

**Comment by elviskahoro** [comment]
Just opened this issue:
https://github.com/warpdotdev/Warp/issues/3644
