### ISSUE TITLE
Launching a virtual environment with pipenv gets rid of blocks and autocomplete

### ISSUE THREAD

**Issue by Raees678** [warpdotdev/Warp#881]
### Discord username (optional)

raees678#0247

### Describe the bug
```text
Edit: Upon further investigation this happens when any program launches a subshell. Even just launching zsh from within warp causes this issue.

When launching a virtual environment with pipenv, pipenv launches a subshell `zsh` in the virtual environment. The warp terminal no longer has blocks or any autocomplete features.

I dont have the same issue when launching a python virtual environment with `virtualenv`.
```

### To Reproduce

Steps to reproduce:
1. Install Python 3.9.12, pipenv, version 2022.3.28 from homebrew
2. Launch pipenv in any directory using `pipenv shell`
4. See error: The shell is launched but now its all within the same block, there is no autocomplete.
OR
1. Launch `zsh` from within your terminal.
2. The new shell does not support blocks.

### Expected behaviour

The resulting shell should behave like a warp shell with each prompt in its own block and autocomplete support.

### Screenshots

<img width="1499" alt="Screen Shot 2022-04-05 at 2 26 37 PM" src="https://user-images.githubusercontent.com/10237081/161717897-2743da31-25ce-4400-8a70-87eea33b13e2.png">
<img width="1508" alt="Screen Shot 2022-04-05 at 2 40 00 PM" src="https://user-images.githubusercontent.com/10237081/161720469-09e344ce-5df2-401f-8b45-3667f7d39ace.png">

### Operating System

MacOS

### OS Version

12.3

**Comment by armona** [comment]
Same thing happens when using poetry (`poetry shell`)

**Comment by elviskahoro** [comment]
DUP of 
- #064
