### ISSUE TITLE
autocomplete display incorrect with different font

### ISSUE THREAD

**Issue by srl295** [warpdotdev/Warp#887]
### Discord username (optional)

srl295#9430

### Describe the bug

```text
I thought this was just a general bug, but today I thought to try a different font.

With a custom font (in my case: Source Code Pro), the autocomplete does _not_ show as grayed out on the right, making it look like hitting Enter will accept the entire line.
```

### To Reproduce

1. install Source Code Pro `Version	Version 2.030;PS 1.000;hotconv 16.6.51;makeotf.lib2.5.65220`
2. Set the font to Source Code Pro
3. Attempt to use autocomplete/search

### Expected behaviour

```text
Text to the right of the insertion caret (|) should be grayed out, indicating that it must be accepted
```

## With Source Code Pro: note that the cursor has only typed `qg` so far, all of the right hand side should be grayed out

<img width="754" alt="image" src="https://user-images.githubusercontent.com/855219/161820130-7b8971c4-acea-43fe-92a1-ad8f8ccfb656.png">

## With the font set to Hack

<img width="728" alt="image" src="https://user-images.githubusercontent.com/855219/161820288-81cb0621-a43c-421b-9042-5dc674cbe3d5.png">

### Operating System

MacOS

### OS Version

12.3.1 (21E258)

### Additional context

```text
Warp v0.2022.04.01.01.37.stable_03
```

**Comment by elviskahoro** [comment]
Thanks for reporting this!

**Comment by vorporeal** [comment]
Hey @srl295 - this is an issue specifically with certain copies of the Source Code Pro font.  Some older versions of the font configured the font as having colored glyphs, meaning characters are always rendered as white (as that is the color the font specifies for the glyphs).

See this other GitHub issue for more info (as well as links to places you can download a working version of the font): #1583.
