### ISSUE TITLE
Home/end keys don’t go to top/bottom of buffer

### ISSUE THREAD

**Issue by aaptho** [warpdotdev/Warp#889]
### Describe the bug

```text
Thrilled to see that Warp is not Electron-based!

Given that, I’d expect some native macOS key bindings to work out of the box by default, but my home and end keys aren’t working.
```

### To Reproduce

Steps to reproduce:
1. Open a window/tab with more than a window's worth of content in the buffer
2. Click on the buffer to make sure it’s focused
3. Press the home or end keys

### Expected behaviour

```text
I’d expect it to go to the top or bottom of the buffer, which is the native macOS behavior.
```

### Operating System

MacOS

### OS Version

12.3.1

### Additional context

```text
Note: VS Code’s home/end key behavior mimics Windows’s by default, which is to go to the start or end of a line. That’s cool for Windows, but not what I would like here on macOS!
```

**Comment by elviskahoro** [comment]
This was launched! Thanks for submitting
