### ISSUE TITLE
CTRL+n, CTRL+p, CTRL+j, CTRL+k to navigate lists

### ISSUE THREAD

**Issue by blase** [warpdotdev/Warp#89]
**Is your feature request related to a problem? Please describe.**
In most software when presented with a list it's possible to move up and down using Ctrl-N (down) and Ctrl-(up). I think this is `readline` behavior and is not always consistent across operating systems, but most desktop apps in MacOS (especially the ones targeted at developers) follow that pattern as well.

**Describe the solution you'd like**
When presented with a list of choices I would like to navigate said list using Ctrl-N/Ctrl-P.

**Additional context**
<img width="366" alt="Screenshot 2021-08-03 at 09 55 03" src="https://user-images.githubusercontent.com/453270/127979973-fabcde18-6880-42f0-8dee-44a2763c7722.png">

**Comment by zheng** [comment]
Makes sense, agree we should support this. It was also previously requested, just bumped the priority!

**Comment by ColmanHumphrey** [comment]
Similarly, I typically use Ctrl-p and -n to navigate history of commands instead of the arrow keys, so this would be great!

**Comment by elviskahoro** [comment]
Moving to #579 so all keybinding related issues are in one place:
- #579
