### ISSUE TITLE
[ui] Dropdown deselects

### ISSUE THREAD

**Issue by evanmays** [warpdotdev/Warp#891]
### Discord username (optional)

evanmays#5466

### Describe the bug

```text
The dropdown component (commonly used in top right update button) deselects as user scrolls through. One option should always be selected.
```

### To Reproduce

1. Click on a dropdown menu 
2. Hover over an option
3. Move mouse down to be below option N but above option N+1

### Expected behaviour

```text
It’s expected that one of the two options will be selected at any point in the middle. But if I move my mouse to the middle, neither are selected
```

### Operating System

MacOS

**Comment by alokedesai** [comment]
Hey @evanmays, thanks for filing! Would you mind posting a video of the behavior you're seeing to help us debug further? Thanks!

**Comment by elviskahoro** [comment]
This should be fixed! Apologies for the delay.
