### ISSUE TITLE
Block cursors start with an unncessary space added

### ISSUE THREAD

**Issue by seljabali** [warpdotdev/Warp#893]
### Describe the bug

```text
New blocks' cursor have a space added by default. This allows me to hit backspace and actually remove it.
```

### To Reproduce
```text
Steps to reproduce:
1. Start new block/app
2. Hit backspace
3. Cursor moves back a character
```
### Expected behaviour

```text
Steps to reproduce:
1. Start new block/app
2. Hit backspace
3. Cursor stays still
```

### Operating System
```text
MacOS
```
### OS Version
```text
11.6.2
```
### Additional context

```text
Sometimes backspacing off of default position messes up history and autocompletion.
```

**Comment by RamziJabali** [comment]
Relates to: https://github.com/warpdotdev/Warp/issues/1196

**Comment by razbakov** [comment]
Also sometimes cursor jumps to the end of line

**Comment by elviskahoro** [comment]
Do you have OMZ? There's a plugin that we're not compatible with that results in a space being included into the input editor. Can you try disabling it using these docs:
https://docs.warp.dev/help/known-issues

**Comment by vorporeal** [comment]
We had a bug relating to our handling of right-side prompts (RPROMPT/RPS1) that could lead to a space being inserted at the start of the input after each block.  This bug has been fixed; please re-open this and let me know if you're still seeing issues here!
