### ISSUE TITLE
Open Warp with a directory URL

### ISSUE THREAD

**Issue by ronbarr** [warpdotdev/Warp#896]
### Describe the solution you'd like?

```text
I use a utility called Service Station to open terminal windows pointing to the directory that I have open on my desktop. It works fine with Terminal and iTerm2 but not with Warp. I'd like to be able to use it to open Warp.
```

### Additional context

<img width="1197" alt="Screen Shot 2022-04-05 at 2 44 04 PM" src="https://user-images.githubusercontent.com/6163948/161854885-cbac5bf3-170e-40fd-9d92-93595f6f5879.png">

<img width="258" alt="Screen Shot 2022-04-05 at 2 46 06 PM" src="https://user-images.githubusercontent.com/6163948/161855133-a5df679d-7963-487b-a04a-98b8e1e9be0a.png">

**Comment by lhvy** [comment]
+1 for this. Adding support for opening to a specified directory via a flag/argument will allow for integration with many commonly used tools.

**Comment by geekdada** [comment]
Please add this support!

**Comment by dan-autonomic** [comment]
+1. Very important feature.

**Comment by elviskahoro** [comment]
Thanks for reporting.
We're tracking this here, this'll be where I share updates once we have them:
https://github.com/warpdotdev/Warp/discussions/612
