### ISSUE TITLE
Global hotkey window (Quake Style) should honor currently active screen

### ISSUE THREAD

**Issue by simerlec** [warpdotdev/Warp#904]
### Describe the solution you'd like?

Hey, love warp so far ❤️

one thing I noticed is that the global hotkey window does not honor the currently active window. [Another user already mentioned it here](https://github.com/warpdotdev/Warp/issues/91#issuecomment-1089365549) but since that issue is already closed, I thought it made sense to open a fresh one. Please advise/close if this is not desirable.

thanks and kind regards

**Comment by smeier99** [comment]
I've created [a similar Issue](https://github.com/warpdotdev/Warp/issues/862) a couple of days ago. I would personally prefer making the position configurable (or using the main screen, like iTerm) over honouring the active screen.

**Comment by simerlec** [comment]
@smeier99 thx for the heads up - I'll close this issue in favour of yours.
