### ISSUE TITLE
Can't sign in with Github account 

### ISSUE THREAD

**Issue by Bidon15** [warpdotdev/Warp#906]
### Describe the bug

```text
After initialisation of Warp, the app asks to sign in with gh account. The sign in process is not going anywhere further and blocks at this window(see attachments) on the browser.
```

### To Reproduce

Steps to reproduce:
1. Go to Download page
2. Download Warp for Mac
3. Install Warp of Mac (Intel chipset)
4. Open App
5. Click Login with Github account
6. Start sign in procedure in the browser

### Expected behaviour

```text
1. Successful sign in 
2. Warp terminal opens up after point 1
```

### Screenshots

<img width="412" alt="Screenshot 2022-04-06 at 10 10 23" src="https://user-images.githubusercontent.com/1822365/161928341-e7aac92b-6945-4590-a9c8-71cb8acace54.png">

### Operating System

MacOS

### OS Version

12.2.1

**Comment by Zapfmeister** [comment]
I got exactly the same error

**Comment by Bidon15** [comment]
I've tried on Brave/Safari - the same issue is reeproducible
I witnessed some errors with the link (firebase) after you want to move on with the login process.

**Comment by kaloutsakis** [comment]
Exact same problem with MacOS Monterey 12.3.1 Apple M1 chip, Opera 84.0.4316.42 (arm64) and Safari 15.4 (17613.1.17.1.13)

![image](https://user-images.githubusercontent.com/3593304/161947621-9fd85aca-4c50-4ce7-8fa1-835ce2cf9dcd.png)

**Comment by rtc11** [comment]
I get the same error. I get a HTTP 404 from the graphql endpoint: https://app.warp.dev/graphql
Request:
```
query User {
  user {
    email
    __typename
  }
}
```

Response: 
```
{"error":"Not found: sql: no rows in result set"}
```

**Comment by rtc11** [comment]
I figured it out. When you log in be sure to select "sign up". It is not refering to the github account, but the warp account.

**Comment by Zapfmeister** [comment]
OMG
@rtc11 you are right. So this was simply a misinterpretation of the login / sign up fields.

**Comment by Bidon15** [comment]
> OMG @rtc11 you are right. So this was simply a misinterpretation of the login / sign up fields.

yeah. It is misleading indeed

**Comment by letto4135** [comment]
This was brought up in discord as well, I believe they will be changing it soon to be more clear.

**Comment by sundy-li** [comment]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/3325189/161978450-a3c09362-3a9b-420a-9150-2a4b7d419203.png">

It's hang after I click take me to warp..

**Comment by aaronzs** [comment]
@sundy-li same here, it seems that GFW blocks the login connection. I belive users from China mainland have the same problem. #832 #705

**Comment by vorporeal** [comment]
Hey all - sorry for the confusion in sign up vs. login; we're definitely going to make this clearer!

@sundy-li That link opens Warp via a custom protocol (warp://); the team has already discussed providing an easy manual workaround for when the link doesn't work for folks but we didn't quite get it implemented before the public beta launch.  Aiming to have a fix for you soon!

**Comment by sundy-li** [comment]
Fixed using `ALL_RPOXY` ENV. 

BTW, this APP is really awesome.  But it only works on local env. (I mostly use SSH to the remote server during work).

**Comment by vorporeal** [comment]
@sundy-li Glad to hear you got it sorted!  If you're having issues that prevent you from using Warp with SSH, we'd love to understand what's wrong and try to fix it; we have an issue template specifically for SSH here: https://github.com/warpdotdev/Warp/issues/new?assignees=&labels=&template=03_ssh.yml

**Comment by wxttt** [comment]
> <img alt="image" width="638" src="https://user-images.githubusercontent.com/3325189/161978450-a3c09362-3a9b-420a-9150-2a4b7d419203.png">
> 
> It's hang after I click take me to warp..

I meet the same issue but I cant get through with ALL_PROXY ENV, anything wrong?
macOS 12.1
warp_version=v0.2022.04.01.01.37.stable_03

**Comment by vorporeal** [comment]
Hey @wxttt - are you also using Firefox?

**Comment by wxttt** [comment]
> Hey @wxttt - are you also using Firefox?

No I'm using Chrome

**Comment by wxttt** [comment]
> Fixed using `ALL_RPOXY` ENV.
> 
> EG:
> 
> ```
> export HTTP_PROXY=http://127.0.0.1:1077
> export HTTPS_PROXY=http://127.0.0.1:1077
> 
> /Applications/Warp.app/Contents/MacOS/stable
> ```
> 
> BTW, this APP is really awesome. But it only works on local env. (I mostly use SSH to the remote server during work).

Thank you. I have solved the problem by adding `HTTP_PROXY` and `HTTPS_PROXY` to my rc file.

**Comment by WShiBin** [comment]
> Fixed using `ALL_RPOXY` ENV.
> 
> EG:
> 
> ```
> export HTTP_PROXY=http://127.0.0.1:1077
> export HTTPS_PROXY=http://127.0.0.1:1077
> 
> /Applications/Warp.app/Contents/MacOS/stable
> ```
> 
> BTW, this APP is really awesome. But it only works on local env. (I mostly use SSH to the remote server during work).

thanks a lot, it works

**Comment by BTBMan** [comment]
> Fixed using `ALL_RPOXY` ENV.
> 
> EG:
> 
> ```
> export HTTP_PROXY=http://127.0.0.1:1077
> export HTTPS_PROXY=http://127.0.0.1:1077
> 
> /Applications/Warp.app/Contents/MacOS/stable
> ```
> 
> BTW, this APP is really awesome. But it only works on local env. (I mostly use SSH to the remote server during work).

Thanks, It works for me!

**Comment by hutusi** [comment]
same problem.

**Comment by lone1y-51** [comment]
mac m1 12.0.1  same problem

**Comment by Wifi365** [comment]
MacBook Pro（14，2021）,me too,how to do if i want use it

**Comment by dev4joel** [comment]
The login issue is here:
- 👉 https://github.com/warpdotdev/Warp/milestone/5

How to fix the confusing login flow issue is here:
- 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)

How to fix the proxy issue is here:
- 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by ischenxin** [comment]
> MacBook Pro（14，2021）,me too,how to do if i want use it

not work for me

**Comment by ischenxin** [comment]
> 



> Fixed using `ALL_RPOXY` ENV.
> 
> EG:
> 
> ```
> export HTTP_PROXY=http://127.0.0.1:1077
> export HTTPS_PROXY=http://127.0.0.1:1077
> 
> /Applications/Warp.app/Contents/MacOS/stable
> ```
> 
> BTW, this APP is really awesome. But it only works on local env. (I mostly use SSH to the remote server during work).

not work for me

**Comment by BilyZ98** [comment]
Hi for every user in China mainland who experience the same login issues the login windows pop up and then disappear,  my solution is setting up browser proxy rules with switchyomega.

Currently, I am using the Chrome browser with switchyomega, and my proxy rules looks like this one.
Basically, I am directing all the request from the chrome to my proxy port 127.0.0.1:1087.
I hope this will help you.
![image](https://user-images.githubusercontent.com/26542149/162659348-44593775-8008-421f-8b13-24fe2556c7c9.png)

**Comment by Wifi365** [comment]
> MacBook Pro（14，2021）,me too,how to do if i want use it
I solved the problem，My solution was to type the following command into the terminal。
```
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
/Applications/Warp.app/Contents/MacOS/stable

```

**Comment by mrmattiago** [comment]
Hi, I have this error while trying to login using github account
![image](https://user-images.githubusercontent.com/10748576/164725839-b58a06d7-b770-490d-9fcd-ad7498d3f651.png)
I use proxy in corporate network.

**Comment by mrmattiago** [comment]
> Hi @mrmattiago--thank you for flagging. Would you mind trying again? We believe we've made some issues here that have fixed this

Thanks for the reply :) Unfortunately still have exactly the same error message..

**Comment by elviskahoro** [comment]
@mrmattiago is this still happening to you? Please comment if so, will reopen if it is.
