### ISSUE TITLE
More obvious highlight for the active pane

### ISSUE THREAD

**Issue by Integralist** [warpdotdev/Warp#911]
### Discord username (optional)

integralist

### Describe the solution you'd like?

Instead of the small arrow in the top-left corner of the currently active pane I would prefer for the pane's complete border (e.g. left/top/right/bottom) to be highlighted.

Refer to the attached image for a rough illustration of the solution.

### Is your feature request related to a problem? Please describe.

I often have multiple split tmux panes open and currently it's very difficult to remember which pane I'm in. 

I don't find the arrow design (currently used) to be a good indicator of that (it's too subtle, and this can be made worse by the user's chosen theme) and so I have to look extra hard, rather than being able to know quickly 'at a glance' where I am. 

In tmux I don't have this problem because tmux highlights the border.

### Additional context

<img width="2032" alt="Monosnap 2022-04-06 13-19-48" src="https://user-images.githubusercontent.com/180050/161973387-7b011ba3-4a09-4520-9810-475dee2ce58e.png">

Because this isn't going to be to everyone's preference, maybe allow this to be configured on/off and if it's turned off the user gets the current behaviour, which is a small triangle in the top-left corner of the active pane.

**Comment by yacobyonas** [comment]
I came to report the same issue but just have one other idea for how this could work better. in iterm, all inactive panes have a gray shadow over them (see image). that helps to make clear where i'm working and blur out the rest.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/55720492/162085027-0d95b2df-27ca-42fd-b198-dd3d0f345843.png">
