### ISSUE TITLE
Option to keep hotkey window on screen

### ISSUE THREAD

**Issue by qdozaq** [warpdotdev/Warp#918]
### Describe the solution you'd like?

```text
When using the hotkey window i'd like for there to be an option to persist the terminal on screen even when clicking off of it.

In other words basically the same as the normal window, but can hide and show it via the hot key set without having it hide when I click off of it.
```

**Comment by ZaynJarvis** [comment]
+1
iterm2 provides this feature

**Comment by elviskahoro** [comment]
This should be out now! Try the autohide on keyboard focus
<img width="505" alt="Screen Shot 2022-07-08 at 11 25 18" src="https://user-images.githubusercontent.com/29553206/178022776-864b9b11-a823-431b-bee4-2ab65fd6971b.png">
