### ISSUE TITLE
command description not working for "git cherry-pick -n"

### ISSUE THREAD

**Issue by MiguelSOliveira** [warpdotdev/Warp#926]
### Describe the bug

```text
`git cherry-pick -n` is a flag that allows to cherry-pick only the files from a commit.

For some reason warp does not give me the description for this flag.
```

### To Reproduce

Steps to reproduce:
1. Go to a git project directory
2. Type `git cherry-pick -n` and press Tab
3. The `-n` flag does not show up

### Expected behaviour

```text
The flag's description should show up.
```

### Screenshots

![imagem](https://user-images.githubusercontent.com/8149533/162067579-ee222860-624d-4ba3-9c92-c3358fb2bbfa.png)

### Operating System

MacOS

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
I think this is fixed! Please comment if not
<img width="828" alt="Screen Shot 2022-07-08 at 11 22 01" src="https://user-images.githubusercontent.com/29553206/178022237-0efa5736-543b-4383-9213-63b321226d2a.png">
