### ISSUE TITLE
Redirect unconsumed stdin during one command to the prompt after it completes

### ISSUE THREAD

**Issue by gpeal** [warpdotdev/warp#93]
**Is your feature request related to a problem? Please describe.**
Sometimes, I'll start typing a command before a previous one finishes. In most terminals, the text typed prior to the previous command's completion that isn't redirected to another stdin goes into prompt for the next command.

This might sound like a bizarre and unnecessary feature but I find myself relying on this for things like:
1. Copy a branch name from a PR I want to check out
2. Run git fetch
3. Run "git checkout " + command + V + enter while the fetch is still in progress

With previous terminals, this worked correctly such that the checkout would happen immediately. However, with warp, I wound up with "out BRANCH_NAME" which obviously failed.

**Describe the solution you'd like**
Redirect unconsumed stdin from the previous command to the prompt.

**Comment by zheng** [comment]
This is one of our most popular features requests, not bizarre or unnecessary at all! https://github.com/warpdotdev/warp/issues/82

The reason we don't have this yet is because it gets technically complicated due to having our own input. We're trying to figure out a solution that would work well.

**Comment by michlimlim** [comment]
Thanks for reporting the typeahead issue. We just released the fix for this today in `v0.2021.08.11.15.36.stable_00`
