### ISSUE TITLE
Failed to authenticate user when login with GitHub

### ISSUE THREAD

**Issue by KpwnZ** [warpdotdev/Warp#931]
### Describe the bug

```text
Login failed with [ERROR] Failed to authenticate user error sending request for url (https://securetoken.googleapis.com/v1/token?<token>): operation timed out
```

### To Reproduce

Steps to reproduce:
1. Install Warp
2. Login with GitHub

### Operating System

MacOS

### OS Version

12.3

**Comment by dev4joel** [comment]
Now, you can see it here.  [Login issues](https://github.com/warpdotdev/Warp/milestone/5)

**Comment by KpwnZ** [comment]
> Now, you can see it here.  [Login issues](https://github.com/warpdotdev/Warp/milestone/5)

Didn't notice that, sorry.

**Comment by KpwnZ** [comment]
Duplicated: https://github.com/warpdotdev/Warp/issues/906
