### ISSUE TITLE
ZSH functions do not autocomplete

### ISSUE THREAD

**Issue by miohtama** [warpdotdev/Warp#937]
### Describe the bug

```text
ZSH functions are not autocompleted on a tab key.
```

### To Reproduce

Add the following to your `.zshrc`:

```
# Quick upstream git commit fix with a message
function git-add-commit-push() {
        git add -A && git commit -m "$1" && git push
}

# Another test attempt if $1 has any significance in ZSH function
function add-commit-push-no-param() {
        git add -A && git commit -m "INSERT MESSAGE HERE" && git push
}
```

Start a new ZSH session with Warp.

Then try to autocomplete this with `git-add-comm<TAB>`

### Expected behaviour

```text
The autocompletion of ZSH functions works like any other autocompletion, or like ZSH function auto-completion works in other terminals like iTerm.
```

### Screenshots

Working autocompletion from iTerm. Type in `git-add-com<TAB>`:

<img width="221" alt="image" src="https://user-images.githubusercontent.com/49922/162160752-182eb8da-d6ff-4826-ad34-c47dd44e9395.png">

Non-functional autocompletion from Warp. Type in `git-add-com<TAB>` and nothing happens. For the hint message line, I belive it digs it up from the shell history.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/49922/162161222-d575d62f-55ba-4c4e-a49a-294cfa647083.png">

### Operating System

MacOS

### OS Version

Big sur

**Comment by dmilith** [comment]
As a workaround: If you disable "Autocomplete quotes …" in preferences, tab completion works…

**Comment by dmilith** [comment]
Not only that but also if your project has "bin" dir and runnable scripts there, typing "bin/" and hitting [tab] should also autocomplete per script name. This doesn't work as well in Warp.

**Comment by dmilith** [comment]
Ok, a workaround for my part is to type ./bin/ and hit [tab], then auto-completion works.
