### ISSUE TITLE
Misaligned text baseline in prompt

### ISSUE THREAD

**Issue by gpeal** [warpdotdev/warp#94]
**Is your feature request related to a problem? Please describe.**
I'm on macOS 11.4 on a 16" MacBook Pro with the text size reduced 2 stops (command + -) and the text baseline for my prompt isn't straight
![image](https://user-images.githubusercontent.com/1307745/128078688-8d13744f-4426-48bc-8185-5871107c1951.png)

**Describe the solution you'd like**
The text baseline should be straight

**Comment by zheng** [comment]
We have a fix for this on master, hoping to have it in the next release (by end of week)!

**Comment by michlimlim** [comment]
We just released the fix for this today in `v0.2021.08.11.15.36.stable_00`
