### ISSUE TITLE
Unable to select text from Curses TUI apps (like mc)

### ISSUE THREAD

**Issue by dmilith** [warpdotdev/Warp#943]
### Discord username (optional)

dmilith#1284

### Describe the bug

```text
Basically I'd like to run "mc" and select some text from it's TUI.
```

### To Reproduce

Steps to reproduce:
1. Run curses tui app like "mc", "tig" or "tmux"
2. Try selecting any text to copy it to the clipboard.

### Expected behaviour

```text
In Alacritty you can select text using shift + trackpad selection, or alt + trackpad selection to select the text.
```

### Operating System

MacOS

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
Thanks for opening. Someone made a prototype of this but it's far from launchable

**Comment by vorporeal** [comment]
This appears to be working now; please re-open if it's still an issue!
