### ISSUE TITLE
Page up/ down doesn't work (prints space instead)

### ISSUE THREAD

**Issue by dmilith** [warpdotdev/Warp#944]
### Discord username (optional)

dmilith#1284

### Describe the bug

```text
Just hitting page up/ down should also scroll the Warp output. Scrolling via trackpad works tho.
```

### To Reproduce

Steps to reproduce:
1. Open Warp
2. Type some commands that content will overflow the window
3. Try hitting page up/ down

### Expected behaviour

```text
Scrolling working without mouse/ trackpad?
```

### Operating System

MacOS

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
This shoudl be fixed!

**Comment by gai6948** [comment]
encountered the same issue on `v0.2023.05.09.08.03.stable_01`, is this expected?
