### ISSUE TITLE
psql shell inside warp doesn't allow navigating with Option + Left/Right Arrow

### ISSUE THREAD

**Issue by edhedges** [warpdotdev/Warp#949]
### Describe the bug

```text
On the MBP v12.2.1 native terminal, when I open up `psql`,I can navigate via Option + Left/Right arrow and modify my queries, but this behavior isn't compatible in Warp. Instead, I just get a space in the shell.
```

### To Reproduce

Steps to reproduce:
1. Open `psql`
2. Type out a query like `select * from users`
3. Try to navigate via Option + Left Arrow to replace `*` with specific columns.
4. See that the cursor is moved to the right for some reason 🤷.

### Expected behaviour

```text
I would expect to be moved to the next "word" in the direction of the arrow key I choose while holding Option.
```

### Operating System

MacOS

### OS Version

12.2.1

**Comment by JayWeber04** [comment]
Having the exact same issue. Really frustrating too since postgres is such a core part of my daily routine.

**Comment by elviskahoro** [comment]
Thanks for the feedback!
Gonna move this to our subshell issue:
GitHub issue for [subshell support](https://github.com/warpdotdev/Warp/issues/64)

Will close in favor of that one.

**Comment by warpdotdev-dx** [comment]
Thanks for the feedback!
Can you move this to our subshell issue:
GitHub issue for subshell support


Will close in favor of that one.
