### ISSUE TITLE
Can't sign up with github

### ISSUE THREAD

**Issue by RainMok** [warpdotdev/Warp#958]
### Describe the bug

```text
Can't sign up with github after I verified by github, the ui of Warp is always loading and loading.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Operating System

MacOS

### OS Version

10.15.7

**Comment by ruxpin** [comment]
same here

**Comment by craig-ezyvet** [comment]
Same here downloaded then signed up with GitHub, verifies and opens Warp but doesn't log in.

**Comment by 1294403205** [comment]
same here

**Comment by MaoMiMao** [comment]
same here

**Comment by wujunzhuo** [comment]
same problem, MacBook Air (M1, 2020)

**Comment by tanbamboo** [comment]
same problem

**Comment by yunfan777** [comment]
same problem

**Comment by ZiFy** [comment]
same here.
MacBook Pro (16-inch, 2019)
macOS 12.2.1

**Comment by HP-283** [comment]
same problem

**Comment by dev4joel** [comment]
Now, you can see it here. [Login issues](https://github.com/warpdotdev/Warp/milestone/5)
Alternatively,  you could follow the post to fix it if it's a proxy issue.[WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by clark-cui** [comment]
same here , mbp16 m1pro.

**Comment by YOCdot** [comment]
Same here, sign up then load for eternity and in the end back to the initial interface.

**Comment by zxitedu** [comment]
same here Hope the official can give a method or give a reply or solve a thank you

**Comment by feynmanloo** [comment]
same here Hope the official can give a method or give a reply or solve a thank you

**Comment by hxp0618** [comment]
same here Hope the official can give a method or give a reply or solve a thank you

**Comment by huimingz** [comment]
same problem

**Comment by IT-ACG** [comment]
same here Hope the official can give a method or give a reply or solve a thank you

**Comment by rokiyer** [comment]
same problem

**Comment by hxp0618** [comment]
> WARP-does-not-work-after-submitting-an-invite-code

Maybe try this, it worked for me at least

https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/

**Comment by 727000692** [comment]
same problem(Macbook Pro,intel chip,macOs 10.15.6)

**Comment by zengchunhao** [comment]
same problem, i have config proxy

**Comment by MatrixAge** [comment]
+1

**Comment by molvqingtai** [comment]
same problem

**Comment by ajluo** [comment]
same here, macbookpro 14' m1

**Comment by mahesh-shiva** [comment]
Same problem. Macbook Pro (2021) M1 with macOS 12.0.

**Comment by Gavinchen92** [comment]
same problem, macbook air m1

**Comment by xxrlzzz** [comment]
Check #705 #972 for chinese users, proxy must be set due to the GFW 😭

**Comment by RainMok** [comment]
> Check #705 #972 for chinese users, proxy must be set due to the GFW 😭

Thx， I had try that, but it still did not work. 😭

**Comment by RainMok** [comment]
> Now, you can see it here. [Login issues](https://github.com/warpdotdev/Warp/milestone/5) Alternatively, you could follow the post to fix it if it's a proxy issue.[WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

yes, I have an ad blocker, I had uninstall it, the response still returned 401. Let it go, I won't focus on it, maybe next version, I will be back 😄

**Comment by dev4joel** [comment]
The login issue is here:
- 👉 https://github.com/warpdotdev/Warp/milestone/5

How to fix the confusing login flow issue is here:
- 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)

How to fix the proxy issue is here:
- 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by bkingalex** [comment]
Please refer to this article   [https://learnku.com/articles/66996?order_by=vote_count&](https://learnku.com/articles/66996?order_by=vote_count&)

**Comment by elviskahoro** [comment]
I think all the login issues have been fixed by now, so gonna close this out. Apologies for all the trouble
