### ISSUE TITLE
can't sign up warp with github

### ISSUE THREAD

**Issue by RealForce1024** [warpdotdev/Warp#960]
### Describe the bug

```text
no response when I use github sign up the warp.
I just want use it as soon, now the warp is broken.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```text
can sign up with github success. now the warp is broken.
```

### Screenshots

just no response. 

### OS Version

macos 12.3

### Additional context

```text
pls solve the problem as soon. thx.
```

**Comment by chendifan** [comment]
macos 11.6.5 the same

**Comment by IT-ACG** [comment]
I try the solution,it works. #705. https://github.com/warpdotdev/Warp/issues/705
Alternatively, go to /Applications/Warp.app/Contents/MacOS and launch warp via

ALL_PROXY="your_proxy" ./stable
Not sure which proxy is actually used, so I used ALL_PROXY. If you already have the proxies set in your rc file, ./stable works out of box.

@dev4joel's solution is nice, but for people behind proxies, installing another program can often be painful (need manager's approval and admin privilege, etc).

**Comment by IT-ACG** [comment]
> macos 11.6.5 the same

https://github.com/warpdotdev/Warp/issues/705

hi I try the solution,it works. https://github.com/warpdotdev/Warp/issues/705. https://github.com/warpdotdev/Warp/issues/705
Alternatively, go to /Applications/Warp.app/Contents/MacOS and launch warp via

ALL_PROXY="your_proxy" ./stable
Not sure which proxy is actually used, so I used ALL_PROXY. If you already have the proxies set in your rc file, ./stable works out of box.

@dev4joel's solution is nice, but for people behind proxies, installing another program can often be painful (need manager's approval and admin privilege, etc).

**Comment by zxitedu** [comment]
> > macos 11.6.5 the same
> 
> #705
> 
> hi I try the solution,it works. #705. #705 Alternatively, go to /Applications/Warp.app/Contents/MacOS and launch warp via
> 
> ALL_PROXY="your_proxy" ./stable Not sure which proxy is actually used, so I used ALL_PROXY. If you already have the proxies set in your rc file, ./stable works out of box.
> 
> @dev4joel's solution is nice, but for people behind proxies, installing another program can often be painful (need manager's approval and admin privilege, etc).

@IT-ACG Can there be a specific operation procedure? GitHub login failed, do not know how to solve the problem

**Comment by dev4joel** [comment]
Now, you can see it here. [Login issues](https://github.com/warpdotdev/Warp/milestone/5)
Alternatively, you could follow the [post](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/) to fix it if it's a proxy issue.[WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by dmilith** [comment]
Click on "Sign on" not "Sign in"… It worked for me when I only clicked the "blue buttons" :)

**Comment by chendifan** [comment]
> > macos 11.6.5 the same
> 
> #705
> 
> hi I try the solution,it works. #705. #705 Alternatively, go to /Applications/Warp.app/Contents/MacOS and launch warp via
> 
> ALL_PROXY="your_proxy" ./stable Not sure which proxy is actually used, so I used ALL_PROXY. If you already have the proxies set in your rc file, ./stable works out of box.
> 
> @dev4joel's solution is nice, but for people behind proxies, installing another program can often be painful (need manager's approval and admin privilege, etc).

Thank you very much! But now I got another issue: [#970](https://github.com/warpdotdev/Warp/issues/970), will try later.

**Comment by dev4joel** [comment]
The login issue is here:
- 👉 https://github.com/warpdotdev/Warp/milestone/5

How to fix the confusing login flow issue is here:
- 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)

How to fix the proxy issue is here:
- 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by bkingalex** [comment]
Please refer to this article   [https://learnku.com/articles/66996?order_by=vote_count&](https://learnku.com/articles/66996?order_by=vote_count&)

**Comment by elviskahoro** [comment]
We've fixed most of the login issues, if any more come up please feel free to open new GitHub issues.
