### ISSUE TITLE
Spotlight key binding does not work when using the hotkey window in full-screen mode

### ISSUE THREAD

**Issue by totaloncue** [warpdotdev/Warp#962]
### Describe the bug

```text
When using the Hotkey Window in full-screen mode (i.e. width and height both set to 100%) the Spotlight global key binding (Command+Space) does not work.
```

### To Reproduce

Steps to reproduce:
1. Go to 'Settings/Features'
2. Set HotKey Window to Width 100% and Height 100% 
3. Open a HotKey Window
4. Try keyboard shortcut for Spotlight  (on my computer it is Command+Space). This does not work.

### Expected behaviour

```text
Global hotkey for Spotlight should work in full-screen mode also.
```

### Operating System

MacOS

### OS Version

11.6.5

**Comment by elviskahoro** [comment]
This should be fixed now.
