### ISSUE TITLE
Settings screen cannot be properly accessed with Hotkey Window

### ISSUE THREAD

**Issue by totaloncue** [warpdotdev/Warp#964]
### Describe the bug

```text
When Hotkey Window is used, the Settings screen is limited to the width/height of the Hotkey Window and many settings are inaccessible
```

### To Reproduce

Steps to reproduce:
1. Go to 'Settings/Features'
2. Set Hotkey Window to 'Pin To Top', width 100%, height 30%
3. Open a Hotkey Window
4. Open the Settings by using 'Cmd+,' or any other mechanism
5. The Settings screen opens within the Hotkey Window and cannot be scrolled beyond the height of the Hotkey Window
6. Scroll down to '...'
7. See error '...'

### Expected behaviour

```text
It would be preferable for the Settings Window to open separately as it does in iTerm
```

### Screenshots

![Screenshot 2022-04-08 at 12 47 35](https://user-images.githubusercontent.com/711204/162384598-a675d581-2979-4a25-93fa-60af55ec11f9.png)

### Operating System

MacOS

### OS Version

11.6.5

**Comment by elviskahoro** [comment]
Thanks for reporting. Gonna merge:
#366
