### ISSUE TITLE
Suggesting commands like github copilot

### ISSUE THREAD

**Issue by clong365** [warpdotdev/Warp#968]
### Describe the solution you'd like?

```text
When the number of users of Warp grows to a certain level, user data can be collected, and then there can be intelligent prompts similar to copilot.
```

**Comment by elviskahoro** [comment]
We have a feature that's similar to this but it uses OpenAI:
https://docs.warp.dev/features/ai-command-search

We wouldn't do this ourselves, we also couldn't since we don't collect Input or Command data:
https://docs.warp.dev/getting-started/privacy
