### ISSUE TITLE
Mac apps should maximize when double-clicking the top frame of the window

### ISSUE THREAD

**Issue by SamBallantyne** [warpdotdev/Warp#97]
**Describe the bug**
Mac apps should maximize (note: not enter fullscreen mode) when double-clicking the top frame of the window.

**To Reproduce**
1. Double-click the top frame of the window.

**Expected behavior**
The window resizes to fill the available space on the Desktop

**Screenshots**

**Desktop (please complete the following information):**
 - OS Version: 11.4

**Additional context**

**Comment by elviskahoro** [comment]
Added with: v0.2022.01.31.09.03.stable_00
