### ISSUE TITLE
app does not response after login with Github

### ISSUE THREAD

**Issue by zhanglun** [warpdotdev/Warp#972]
### Describe the bug

```text
I am trying to login with github. I did login successfully on the webpage, but the app does't response and stays at the login place.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Screenshots

<img width="394" alt="image" src="https://user-images.githubusercontent.com/3086358/162452846-6351d74a-a0a8-41fa-a0ea-06d84f37be26.png">
<img width="248" alt="image" src="https://user-images.githubusercontent.com/3086358/162453324-f7e90d53-4778-4924-801d-5fe5847f6e17.png">

### Operating System

MacOS

### OS Version

12.3.1

**Comment by BH-M87** [comment]
I met the same problem just as same as you. 
Why a terminal can only be allowed to use after login with GitHub?

**Comment by BH-M87** [comment]
![CleanShot 2022-04-08 at 22 56 54](https://user-images.githubusercontent.com/16903266/162470921-1846a636-f524-41e4-8486-b5fae92dde97.gif)

**Comment by zhtubo** [comment]
I have the same problem, I just downloaded it and after logging in via github, I can't get a response from warp. mac os is 12.1

**Comment by BH-M87** [comment]
> I have the same problem, I just downloaded it and after logging in via github, I can't get a response from warp. mac os is 12.1

Don't you think it's weird that a terminal need to login with GitHub as  precondition before you use it...

**Comment by mymistoe** [comment]
I'm having the exact same problem. When I log in with github, the program does not respond.

### OS version: 
mac OS Monterey 12.3.1

### Device model: 
MacBook Air (M1, 2020)

**Comment by corbinu** [comment]
> > I have the same problem, I just downloaded it and after logging in via github, I can't get a response from warp. mac os is 12.1
> 
> Don't you think it's weird that a terminal need to login with GitHub as precondition before you use it...

It is super weird and broken for me also

**Comment by dev4joel** [comment]
Did you use the proxy? If so and login is still not working then it's likely one of these issues: https://github.com/warpdotdev/Warp/milestone/5.

Alternatively, you could follow the [post](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/) to fix it if it's a proxy issue.[WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/).

**Comment by lzhaoyang** [comment]
why a terminal tool need login in before use?  It's really suck design.

**Comment by zhanglun** [comment]
> Did you use the proxy? If so and login is still not working then it's likely one of these issues: https://github.com/warpdotdev/Warp/milestone/5.
> 
> Alternatively, you could follow the [post](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/) to fix it if it's a proxy issue.[WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/).

Thanks，ClashX's Enhanced mode saves me. But the application does not have any prompts when it is unresponsive or has errors, which is very unfriendly. Also, why do I have to log back in after every launch?

**Comment by dev4joel** [comment]
> 

Can you send a video of what's happening? I think this is a bug.

**Comment by dev4joel** [comment]
The login issue is here:
👉 https://github.com/warpdotdev/Warp/milestone/5
How to fix the confusing login flow issue is here:
👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)
How to fix the proxy issue is here:
👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by dev4joel** [comment]
The login issue is here:
- 👉 https://github.com/warpdotdev/Warp/milestone/5

How to fix the confusing login flow issue is here:
- 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)

How to fix the proxy issue is here:
- 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by elviskahoro** [comment]
For future reference also check out here:
https://docs.warp.dev/help/troubleshooting-login-issues

**Comment by Three-fire** [comment]
fucking design,why only register through GitHub authorization? **Fucking product manager!**
