### ISSUE TITLE
Non-Latin character issues in PS1

### ISSUE THREAD

**Issue by gershik** [warpdotdev/Warp#973]
### Describe the bug

```text
The default PS1 prompt has issues displaying non-Latin characters. Blank space is visible instead of these non-latin names. See screenshots below.
```

### To Reproduce

Steps to reproduce:
1. cd into a folder with a Cyrillic/Hebrew/etc. name
2. Look at the PS1 prompt

### Expected behaviour

```text
These characters are properly displayed
```

### Screenshots

Default PS1, Cyrillic (тест)
<img width="178" alt="image" src="https://user-images.githubusercontent.com/31369902/162479930-eddcb93d-4d5c-45c3-bc93-63d462f6c0df.png">

Custom PS1, Cyrillic (тест)
<img width="176" alt="image" src="https://user-images.githubusercontent.com/31369902/162478759-45c6e8eb-8e2a-48dd-9e29-9ab80100223b.png">

Default PS1, Hebrew (מבחן)
<img width="175" alt="image" src="https://user-images.githubusercontent.com/31369902/162479990-c2b8819e-02a0-474d-bcce-1996194f2a4c.png">

Custom PS1, Hebrew (מבחן)
<img width="169" alt="image" src="https://user-images.githubusercontent.com/31369902/162479044-12456c05-499f-4345-9a35-d96a44cf5a23.png">

Default PS1, Emoji (🤔)
<img width="198" alt="image" src="https://user-images.githubusercontent.com/31369902/162479716-e399bb12-ecee-42b0-8db6-80b0d54af4ad.png">

Custom PS1, Emoji (🤔)
<img width="184" alt="image" src="https://user-images.githubusercontent.com/31369902/162479807-04ed0ef5-b3ea-42a5-93dc-0d03f6c76874.png">

### Operating System

MacOS

### OS Version

12.3.1

**Comment by elviskahoro** [comment]
Check out https://github.com/warpdotdev/Warp/issues/209
