### ISSUE TITLE
Global Hotkey Window / Quake Mode window should float / appear above fullscreen apps (on active screen above other windows)

### ISSUE THREAD

**Issue by kevinyang372** [warpdotdev/Warp#975]
### Describe the bug

```text
In Iterm you could configure hotkey window to be floating above fullscreen apps, but Warp does not currently support it.
```

**Comment by elviskahoro** [comment]
From @ideea via 859

> something like that.
> https://monosnap.com/file/CvJdptdKjfHk0TWYYY2Zcs7V3ESXCm
>

**Comment by adamos-kyriakou-wolt** [comment]
Here's a GIF of the behaviour I originally described in the feedback survey compared between Warp and iTerm

![CleanShot 2022-04-16 at 23 03 25](https://user-images.githubusercontent.com/83470174/163691305-c64dbd7d-b917-4608-a187-6ea0c164d9ba.gif)

**Comment by ozsay** [comment]
a reference of how it's implemented in electron
https://github.com/electron/electron/blob/main/shell/browser/native_window_mac.mm#L1342-L1363

**Comment by kevinyang372** [comment]
> a reference of how it's implemented in electron https://github.com/electron/electron/blob/main/shell/browser/native_window_mac.mm#L1342-L1363

@ozsay Unfortunately this does not work with Warp:
```
TransformProcessType(&psn, kProcessTransformToUIElementApplication);
```
will transform the application process into a background app -- causing it to not show up in dock icon and app switcher

**Comment by smeier99** [comment]
Any updates on this? This is currently the only thing blocking me from using warp :/

**Comment by adamos-kyriakou-wolt** [comment]
It remains a major annoyance for me as I use Warp alongside Raycast a lot so I'd love for that to somehow be sorted. Was hoping that the introduction of this toggle in the Warp settings would do the trick but alas it doesn't autohide behind Raycast

![CleanShot 2022-06-07 at 12 14 57](https://user-images.githubusercontent.com/83470174/172356016-4f1cd030-35b1-4b7f-8eed-bd58cbf1e69a.png)

**Comment by ozsay** [comment]
@kevinyang372 sorry for the very late response!

https://github.com/ozsay/winit/pull/1

I made a few tests for it using `winit` and it seems to work with dock and app switcher (without transforming the process).
not sure what is Warp's window handler, but I assume it's cocoa underneath..

**Comment by adamos-kyriakou-wolt** [comment]
Happy to report that for a few weeks now Warp has not been floating over Raycast and I'm super happy with it 😍 !

![CleanShot 2022-08-01 at 07 27 09](https://user-images.githubusercontent.com/83470174/182078216-d6b2b4b4-dc57-4792-bfc0-ebc0dcb2fb26.png)

**Comment by elviskahoro** [comment]
Yep that was Kevin's doing!

**Comment by digitalkaoz** [comment]
@elviskahoro but its not solved et all. Warp still doesnt open above fullscreen apps?!

**Comment by elviskahoro** [comment]
I'm able to use the Quake window over full-screen apps. What version are you on and are you using the Quake window?

**Comment by kevinyang372** [comment]
@digitalkaoz The "Active Screen" could be the culprit of this. Under some scenarios, Mac won't consider the screen you have active full-screen app on as the active screen. Could you try with pinning it to a certain screen and try again?

**Comment by elviskahoro** [comment]
Gonna close this! @digitalkaoz please let us know the outcome of your investigation.

**Comment by digitalkaoz** [comment]
@elviskahoro its neither completed nor working. tried all combinations of toggles to make it work.

**Comment by warpdotdev-dx** [comment]
What kind of keyboard do you use?


Do you have an international keyboard or use an international keyboard format on your Mac?


We have a separate bug where some keys and keyboard combinations aren't registered.

**Comment by fullheart** [comment]
I have the same problem. Here my system informations:

* Mac **OSX 12.6**
* warp **version v0.2022.11.14.14.55.stable_01**
* Apple Keyboard **Swiss Layout (Language: de-CH)**
* Hotkey Setting:
![image](https://user-images.githubusercontent.com/25485618/202665401-1debd49d-50c8-4955-a3d7-8cd7a2863e5d.png)

**Comment by helgeblod** [comment]
I'm having the same problem as mentioned above. When I switch to "Main Screen" instead of "Active Screen" the hotkey window appears on top of fullscreen apps on my main screen.

**Comment by exsesx** [comment]
It'd also be extremely useful to exclude the Warp window from the tab switcher.

**Comment by HernanEscola** [comment]
I'm experiencing the same proble. If it's related to how MacOS Natively detects which screen is active, can I suggest impelementing something like using the screen where the mouse is on? There will be some minor cases in which all interactios were done with keywboard and the `active windows` doesn't match with the mouse position, but I think at least worth adding the option.

**Comment by ayan-multipl** [comment]
Any updates on this issue. On external monitor, it opens the warp in a different screen and not above the fullscreen.

**Comment by GorvGoyl** [comment]
Floating window is essential to my workflow but it didn't work on mac 15.4.1. Switching back to iTerm2.

**Comment by VictorValar** [comment]
> Floating window is essential to my workflow but it didn't work on mac 15.4.1. Switching back to iTerm2.

this is also a deal breaker for me

**Comment by rckm** [comment]
Same problem, please promote PR from @asboppana
