### ISSUE TITLE
No terminal, missing, sign in to GitHub?

### ISSUE THREAD

**Issue by AddictArts** [warpdotdev/Warp#978]
### Describe the bug

```text
I don't see a terminal, just a login? That is as far as I got.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

**Comment by ripley** [comment]
It a bit confusing, why a terminal application asks people login to github?

I took a step back and went ahead to login, after I finished it the login window was gone but I'm still facing the sign in window.

Tried this on two device with different browser, end up removed the application at last.

**Comment by wongFanx** [comment]
I have the same problem. macbook air M1

**Comment by dev4joel** [comment]
The login issue is here:
- 👉 https://github.com/warpdotdev/Warp/milestone/5

How to fix the confusing login flow issue is here:
- 👉 [Can Not Sign Up Or Sign In Warp With Github(Public Beta)](https://embiid.blog/post/Can-not-sign-up-or-sign-in-Warp-with-Github/)

How to fix the proxy issue is here:
- 👉 [WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

**Comment by elviskahoro** [comment]
Apologies for the login issues! They should all be fixed by now for the most part.

Updated the docs to explain how the team is thinking about telemetry and login.
https://docs.warp.dev/getting-started/privacy

Also check out issue #900
