### ISSUE TITLE
Blocks: Jittery button for blocks!

### ISSUE THREAD

**Issue by chriskrycho** [warpdotdev/warp#98]
**Describe the bug**
When interacting with an output block, the block actions button is jittery whenever the top of the block is too close to the edge of the viewport, including in the default scroll position from the block navigation button.

**To Reproduce**

1. Trigger a command which generates a block taller than the current terminal window will display.n
2. Click on the block jump button _or_ scroll to the same position the block jump button would take you to.
3. Attempt to click the block options button.
4. It jitters like crazy, only allowing you to actually interact with it in very specific spaces.

Notably, this *only* happens if the top border of the block is (a) out of view or (b) within ~20px of the top of the “viewport”. Beyond that, interaction with the button works normally.

**Expected behavior**
The button should be able to be interacted with normally regardless of the block position.

**Screenshots**

Since a screenshot wouldn't show this *at all*, have a video!

https://user-images.githubusercontent.com/2403023/128524778-82465ee0-acc7-4607-9370-3dcfedf8234e.mov

**Desktop (please complete the following information):**

 - OS Version: macOS Version 11.5.1
 - iMac (Retina 5K, 27-inch, 2019)

**Additional context**
N/A

**Comment by elviskahoro** [comment]
@chriskrycho I think this was fixed! Can you reopen if it isn't?

**Comment by chriskrycho** [comment]
Yep, confirmed. Thanks!
