### ISSUE TITLE
Now, you can see it here. [Login issues](https://github.com/warpdotdev/Warp/milestone/5)

### ISSUE THREAD

**Issue by RainMok** [warpdotdev/Warp#983]
Now, you can see it here. [Login issues](https://github.com/warpdotdev/Warp/milestone/5)
Alternatively,  you could follow the post to fix it if it's a proxy issue.[WARP-does-not-work-after-submitting-an-invite-code](https://embiid.blog/post/WARP-does-not-work-after-submitting-an-invite-code/)

_Originally posted by @dev4joel in https://github.com/warpdotdev/Warp/issues/958#issuecomment-1092365207_

thx your tip , I had try ,but it still did not work :( . My err code is 401

**Comment by dev4joel** [comment]
Could you comment on the post or the original issue rather than create a new issue? Please close the issue. Thx.

**Comment by dev4joel** [comment]
Alternatively, you cloud to join the [discord](https://discord.gg/warpdotdev).https://discord.gg/warpdotdev

**Comment by dev4joel** [comment]
Oh dear, Do you have an ad blocker active? It could potentially block the sign-in pop-up.
