### ISSUE TITLE
Exiting from Glances does not return to command prompt

### ISSUE THREAD

**Issue by totaloncue** [warpdotdev/Warp#984]
### Describe the bug

```text
When exiting from Glances system monitoring tool, Warp seems to get stuck and does not return to the command line
```

### To Reproduce

Steps to reproduce:
1. Start 'glances' from the command line
2. Exit glances
3. Warp does not return to the command line

### Operating System

MacOS

### OS Version

11.6.5

**Comment by elviskahoro** [comment]
Thanks for reporting. Will try to repro this and get back to you

**Comment by elviskahoro** [comment]
Should be fixed now!
