### ISSUE TITLE
Warp could not handle Turkish characters in Directory and Filenames

### ISSUE THREAD

**Issue by selim** [warpdotdev/Warp#985]
### Discord username (optional)

selim#8661

### Describe the bug

```text
if there Turkish characters (İŞşğĞçÇöÖüÜ) in dir&file names cd, ls and intellisense do not work properly.
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Expected behaviour

```text
Create some dir and file names:

mkdir folderTürkçe
mkdir İupperi

and try to 
cd
```

### Screenshots

<img width="192" alt="image" src="https://user-images.githubusercontent.com/241385/162573121-69d24611-b441-4b6b-b81e-2761a56aa6bf.png">

### Operating System

MacOS

### OS Version

11.6.5

### Additional context

```text
This problem affects pipelining and other file handling commands. May be same problem exists with other Codecs.
```

**Comment by selim** [comment]
OSX Terminal SS:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/241385/162573320-3799bb39-a734-47a7-891d-1f97adfba9d3.png">

**Comment by elviskahoro** [comment]
This should be fixed now!
