### ISSUE TITLE
Poor vertical alignment in title bar

### ISSUE THREAD

**Issue by chriskrycho** [warpdotdev/Warp#99]
**Describe the bug**
The "stoplight" buttons and the tab titles are not vertically aligned.

**To Reproduce**
1. Open the app.
2. Look at the title bar.

😅 

**Expected behavior**
The text should be vertically aligned.

**Screenshots**

<img width="1136" alt="Warp" src="https://user-images.githubusercontent.com/2403023/128525832-e7c28edd-d9bb-496f-9e90-6e393c6de526.png">

**Desktop (please complete the following information):**
 - OS Version: macOS Version 11.5.1
 - iMac (Retina 5K, 27-inch, 2019)

**Additional context**

For comparison, here are two other Mac terminals which get this as expected

<details><summary>Terminal</summary>
<img width="822" alt="terminal" src="https://user-images.githubusercontent.com/2403023/128525773-23a6ced6-5313-4f4a-8adc-d221a20fa9eb.png">
</details>

<details><summary>iTerm 2</summary>
<img width="932" alt="iTerm 2" src="https://user-images.githubusercontent.com/2403023/128525806-d671f6d1-4529-43ae-83c8-edfe30c6b41e.png">
</details>

**Comment by elviskahoro** [comment]
hey @chriskrycho this has been triaged but no eta on when someone will be able to get to it

**Comment by bradmsmith** [comment]
This has been fixed and can be closed. 

<img width="781" alt="image" src="https://github.com/warpdotdev/Warp/assets/4544726/909c0cdd-cd24-42b3-9b0f-d612b33c8b42">
