### ISSUE TITLE
Tab completion does not work over SSH

### ISSUE THREAD

**Issue by hryang** [warpdotdev/Warp#996]
### Describe the bug

```text
When ssh to a remote machine, the tab completion for a command does not work in the sub-diretory.
```

### To Reproduce

Steps to reproduce:
1. ssh to a remote machine
2. cd to a sub-directory.
3. Do tab completion for the "cd" command again.
4. No candidate directory display.

### Expected behaviour

```text
The tab completion works anywhere.
```

### Screenshots

SSH to the remote machine. 

The tab completion works only in the first level directory. As shown in the below pictures, tab completion works in the home directory.
![图片](https://user-images.githubusercontent.com/626967/162618744-699c6372-b85a-4eee-9461-4ac51532a824.png)

Then cd into the sub-directory, say "projects". Now the tab completion does not work.
![图片](https://user-images.githubusercontent.com/626967/162618701-2562359b-df36-48a3-bd79-5b2edb82a98e.png)

### Operating System

MacOS

### OS Version

12.3.1

**Comment by KoStard** [comment]
Having the same issue. I am working over SSH connection quite often and not having such basic functionality will limit the productivity significantly. For now will switch back to regular terminals, but hope this gets fixed. Thanks for opening this issue!

**Comment by dyxushuai** [comment]
Same with this problem. Very important to me.

**Comment by chris075966** [comment]
Same with this issue. Please let me know if u guys to fix this. Thanks.

**Comment by tblxdezhu** [comment]
+1, Many commands and services can not use tab complements, which is very important to me and almost impossible to improve work efficiency

**Comment by elviskahoro** [comment]
Thanks for opening will update when it's a work in progress

**Comment by alokedesai** [comment]
Hey folks, this should be fixed. Please reopen if you're still experiencing issues here!
